### ISSUE TITLE
No Nuget packages since October 28th.

### ISSUE THREAD

**Issue by serkantkaraca** [Azure/azure-sdk-for-net#10037]
Both Microsoft.Azure.EventHubs and Microsoft.Azure.EventHubs.Processor package builds blocked since October 28th. I don't see new packages on azuresdkartifacts any more. We need to start testing latest changes and release 4.2 in 2 weeks. Can someone please help?

**Comment by jsquire** [comment]
//cc: @weshaggard, @mitchdenny, @danieljurek, @mikeharder

**Comment by weshaggard** [comment]
@serkantkaraca are you wanting the older Microsoft.Azure.EventHubs.* packages? Since we refactored the pipelines there hasn't been any asks for builds of those so we currently don't build them in any of our pipelines. 

@jsquire if these track 1 packages are needed they will need to be added to the artifact list in the eventhub ci.yml file at https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/eventhub/ci.yml#L41.

**Comment by serkantkaraca** [comment]
Yes, we need older Microsoft.Azure.EventHubs.* packages. This is an actively developed SDK. I don't know why you guys decided to stop the pipeline.

**Comment by weshaggard** [comment]
A lot of our track 1 libraries are being replaced with track 2 libraries and unless needed, which this is the first request that I'm aware of, we didn't enable the track 1 builds because most of them are in servicing mode and don't need active daily builds. 

@chidozieononiwu can you please work with @jsquire to get these packages added to the eventhubs pipeline?

**Comment by jsquire** [comment]
It looks as if @chidozieononiwu made the change already and it was merged yesterday evening.   Happy to assist as needed, but beyond verifying the feed, I don't believe there is further action to take at this point.

**Comment by serkantkaraca** [comment]
Thanks all, new packages should appear on Nuget repository soon. Closing the issue for now.

**Comment by weshaggard** [comment]
Looks like the nightly build is failing due to test issues, https://dev.azure.com/azure-sdk/internal/_build/results?buildId=265684&view=logs&j=807bcc1d-e4a4-52ea-b30c-0355b7adcdfe&t=587c71f4-238c-5355-397e-d8cbfa262366. Until those test issues are addressed the dev packages will build and be published.

**Comment by jsquire** [comment]
Apologies; that looks to be related to a merge that went in yesterday.  We've got someone investigating and we'll get those at least marked to be skipped today.
