### ISSUE TITLE
[BUG] Blueprint Management Client Does Not Populate Versions

### ISSUE THREAD

**Issue by Lutando** [Azure/azure-sdk-for-net#10194]
I am trying to retreive a blueprint and its published versions so that I can see what versions have been published in code.

**Describe the bug**
using the `BlueprintManagementClient` to retreive blueprints does not correctly populate the `BlueprintModel.Version` property

**Expected behavior**
That the BlueprintModel.Versions property is populated

**Actual behavior (include Exception or Stack Trace)**
The field is null

**To Reproduce**
`var blueprint = await blueprintClient.Blueprints.GetWithHttpMessagesAsync(blueprintScope, blueprintName);`

inspection of the Versions field is null, same behaviour is observed when `var blueprint = await blueprintClient.Blueprints.GetInSubscriptionAsync(subscriptionId, blueprintName);` is used

**Environment:**
 - Package `Microsoft.Azure.Management.Blueprint` v0.20.0-preview
 - NetCoreApp 3.1, DotNet SDK 3.1.102
 - Rider 2019.3.3

Keep up the good work 👍  enjoying using this SDK over REST.

**Comment by Lutando** [comment]
So I know what the problem is. Azure Management API requires `$expand=versions` querystring parameter to return the versions of the blueprint to the caller. 
I got around this by making a `DelegatingHandler` that appends the mentioned query string parameter to the HttpRequest.RequestUri. Bobs your uncle.

I still feel like from an SDK perspective this should be fixed because I dont think that the Versions member ever can get populated with the latest Azure Management API version.

**Comment by isra-fel** [comment]
Hi Alex or Filiz, could you add more context about why `versions` is not in the response by default and your thoughts on making it there. Thanks!

**Comment by filizt** [comment]
@Lutando Thanks for reporting this. We don't populate blueprint versions by default in the GET response. The workaround we have, which you are using, is to use the `DelegatingHandler` to add `$expand-versions` query string to the request. Currently, we don't have any plans of making this behavior the default. If using the `DelegatingHandler` is particularly not convenient or not working for you, let us know why and we can consider that. Otherwise, I'll close this issue. Feel free to reopen if there is a need.
