### ISSUE TITLE
[FEATURE REQ] Symbols for Microsoft.Azure.ServiceBus.dll

### ISSUE THREAD

**Issue by StevenDevooght** [Azure/azure-sdk-for-net#10262]
**Microsoft.Azure.ServiceBus**
Provide PDB symbols for Microsoft.Azure.ServiceBus.dll (version 4.1.1)
 
**Is your feature request related to a problem? Please describe.**
I'am trying to investigate an issue related to Azure ServiceBus queues. However the symbol files cannot be loaded. I have the following symbol locations configured:

- Microsoft Symbol Servers
- NuGet.org Symbol Server

**Comment by jsquire** [comment]
//cc: @weshaggard, @danieljurek

**Comment by kurtzeborn** [comment]
We generally publish symbols for all of the packages we release to the Microsoft Symbol Server. 
@chidozieononiwu, would you please look into where the symbols went for this package.

**Comment by chidozieononiwu** [comment]
There was a brief period of time when our release pipeline failed to publish symbols. Unfortunately the build responsible for the release of version 4.1.1 has been cleaned up so symbols for this release cannot be published. I will work with the Service bus team to release a hotfix with symbols published.

**Comment by SeanFeldman** [comment]
Cough, cough, SourceLink. https://github.com/Azure/azure-sdk-for-net/issues/6239

**Comment by SeanFeldman** [comment]
BTW, this client [used to have](https://github.com/Azure/azure-sdk-for-net/blame/64a0ee64a70f30dc80da80334d0ad132261d81db/src/SDKs/ServiceBus/data-plane/src/Microsoft.Azure.ServiceBus/Microsoft.Azure.ServiceBus.csproj#L43) SourceLink enabled :(

**Comment by SeanFeldman** [comment]
If PDB would be shipped with the package (
`<AllowedOutputExtensionsInPackageBuildOutputFolder>$(AllowedOutputExtensionsInPackageBuildOutputFolder);.pdb</AllowedOutputExtensionsInPackageBuildOutputFolder>`) and SourceLink enabled, that would allow developers easily step into the code.

**Comment by chidozieononiwu** [comment]
We are not including symbols in the package because of size. Hence the need to publish to symbols server.

**Comment by bording** [comment]
> My understanding is that we are not including symbols in the package because of size. Hence the need to publish to symbols server.

Portable PDBs are quite small. I don't see why you need to bother with a symbol server at all.

**Comment by chidozieononiwu** [comment]
> > My understanding is that we are not including symbols in the package because of size. Hence the need to publish to symbols server.
> 
> Portable PDBs are quite small. I don't see why you need to bother with a symbol server at all.

Ok @weshaggard could you clarify why the symbols server needed?

**Comment by chidozieononiwu** [comment]
Please make use of [Microsoft.Azure.ServiceBus.4.1.2](https://www.nuget.org/packages/Microsoft.Azure.ServiceBus/) which has symbols published.

**Comment by weshaggard** [comment]
There is a long discussion about using embedded pdb's and some of the drawbacks at https://github.com/dotnet/sdk/issues/2679. We are essentially using the same pdb policy that the .NET team is using which for the most part has served us well (minus a few publishing issues which were just oversights). 

As for source link we have enabled it for all the data-plane libraries by default so that should be working as long as the pdb is present. If someone finds that not to be the case then we have a bug to fix.

**Comment by SeanFeldman** [comment]
> We are essentially using the same pdb policy that the .NET team is using which for the most part has served us well (minus a few publishing issues which were just oversights).

I don't know what those policies are but can share my side of the story where I would agree with the arguments brought in https://github.com/dotnet/sdk/issues/2679 by supporters of embedding PDBs in the package - it simplifies troubleshooting and additional 20-30% of size increase justify it. Just as today no one claims that all data should be normalized just because storage was expensive, I hope to see this decision reviewed. Thank you, @weshaggard.

**Comment by StevenDevooght** [comment]
@chidozieononiwu I can confirm version 4.1.2 has symbols published. This issue can be closed.
