### ISSUE TITLE
[BUG] Azure.Storage.Blobs 12.3.0 does not correctly handle percent signs in blob names

### ISSUE THREAD

**Issue by dandriscoll** [Azure/azure-sdk-for-net#10272]
**Describe the bug**
I'm using Azure.Storage.Blobs 12.3.0 to enumerate and download blobs. If the blob name contains a percent sign, BlobClient does not properly encode it. I can work around this issue by manually replacing all `%` in blob names with `%25` before passing them into the client.

**Expected behavior**
BlobClient should encode percent signs in blob names so the service handles them properly.

**Environment:**
 - Name and version of the Library package used: Azure.Storage.Blobs 12.3.0
 - Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects): Win10 netcore 3.1.101
 - IDE and version : 16.4.5

**Comment by amishra-dev** [comment]
@amnguye can you please look. I think the sdk does not urlencode blob names. Lets make sure the behavior is consistent across java and python and possibility of providing a helper function.

**Comment by dandriscoll** [comment]
To add: snippets that describe this code (in doc repos, in StackOverflow, on random webpages) generally instruct developers to call `container.GetBlobClient(blob.Name)`. So please factor that into your thinking when considering whether BlobClient should handle this or a helper method.

**Comment by amnguye** [comment]
Hi,

Could you should provide a code snippet? I just tried to reproduce your issue by calling `container.GetBlobClient(blob.Name)' where the blobname had percent signs in it and we properly encoded the blob name. I ran it with a Fiddler trace and it sent the correct encoded url.

If you can could you also run it with a trace and show us the raw requests?

**Comment by seanmcc-msft** [comment]
Please reopen if you continue to experience this issue.

**Comment by ImrePyhvel** [comment]
This can be reproduced.

Enumeration provides actual blob names, but `GetBlobClient(blobName)` gets confused when blob name happens to look like it already is urlencoded. It has no way of knowing whether it actually is or not, Unfortunately it tries to guess, leading to unpredictable behavior.

See repro code: 

	//create test file:
	container.GetAppendBlobClient("%2525.txt").Create(); // creates "%25.txt"

	// list + get client:
	var blob = container.GetBlobs(prefix: "%25.txt").Single();
	var exists = container.GetBlobClient(blob.Name).Exists().Value;
	if (!exists) { Console.WriteLine($"'{blob.Name}' - where is it?"); }
	// prints: '%25.txt' - where is it?


Note that `%.txt` works fine.

So, it seems unless you have the rare case where you fully control the blob name and can limit the name only to safe characters then one must urlEncode blob.Name before passing it to `GetBlobClient(blobName)`,  EVERY SINGLE TIME.

To make things even worse, not every urlencoder suits. Should one use `WebUtiltity.UrlEncode()` then %-sign blobs are fine, but all blobs with spaces will fail (due to encoding turning them into `+` signs, which once again do not work. `Uri.EscapeDataString()` seems to work better. So one must also remember which url encoder to use.. 

To make things worse - if you miss urlEncoding somewhere, then it usually works for many names (like during development and testing). And fails in production with unexpected "Blob not found" errors for actually existing blobs.

Not sure if this is a bug or WAD, but it's sure is painful to work with.
