### ISSUE TITLE
[Azure Cognitive Search]  Consider additional constructor options for Field

### ISSUE THREAD

**Issue by mzilberman** [Azure/azure-sdk-for-net#10302]
**Azure Cognitive Search**
This feature is specifically related to the Models in the Azure Search.  It seems logical to support the following construct:

var f = new Field ("PhoneNumbers", DataType.Collection(DataType.Complex));  

@brjohnstmsft let me know what you think

**Comment by brjohnstmsft** [comment]
@mzilberman The issue with that constructor is that it allows you to create a complex field without sub-fields. [This constructor](https://github.com/Azure/azure-sdk-for-net/blob/fea83738df4ccb85eeffc1fd143fc67a96510bc0/sdk/search/Microsoft.Azure.Search.Service/src/Customizations/Indexes/Models/Field.Customization.cs#L72) requires providing sub-fields at the time of defining the parent field, which makes it more robust. Is there a scenario where this constructor isn't sufficient for your needs?

**Comment by brjohnstmsft** [comment]
We had an offline discussion and explored the context behind this feedback, and some of the discoverability issues around the `Field` class in general. Here are my notes from the part of this conversation related to `Field`:

> Found static `New` methods, but concepts weren't self-explanatory (e.g. `NewSearchableCollection`).
> Did find `DataType.Collection`
> `FieldBuilder` was not an option for this scenario because it's for a content management system that doesn't know the index schema a priori.
> How `DataType` was represented was confusing (sort of like an enum, but not).
> Consistency around how `Fields` are created would be helpful. Current mix of constructors and `New` methods is not self-explanatory and is hard to navigate.

@mzilberman I'm closing this issue only because it's more of a broad conversation rather than a specific ask. We'll definitely take your feedback into account when re-designing `Field` for the next-generation SDKs.
