### ISSUE TITLE
[Validation] Handle case where DocumentResult.Fields.Value.Page == null

### ISSUE THREAD

**Issue by annelo-msft** [Azure/azure-sdk-for-net#10369]
Right now we're setting pageNumber to 0 if this is the case.

We need to understand:
- Is this expected or possible?
- Is 0 the right thing to set, or should it be something else?

See: https://github.com/Azure/azure-sdk-for-net/blob/5111925a4021ef5ee498bcf5fddf4a16c4e2da62/sdk/formrecognizer/Azure.AI.FormRecognizer/src/ExtractedForm.cs#L72

**Comment by annelo-msft** [comment]
@ctstone, would you be able to let us know whether this is possible (per question 1 above)

**Comment by ctstone** [comment]
I think field page is not a required property on `FieldValue` only because `FieldValue` may be used a "wrapper" field when the `type` is "array" or "object". In those cases, page would not be set, but the page would be set on the fields inside the wrapper (wherever there is a "text" property). Since "array" and "object" fields would already get mapped to native types, I don't you would need to account for missing page.

**Comment by kinelski** [comment]
Since we have already gone GA, we can't change this behavior. We haven't gotten negative feedback about this behavior in 3 years so we have no strong reason to discuss it further. Closing this.
