### ISSUE TITLE
Design approach to merging Confidence across supervised and unsupervised fields

### ISSUE THREAD

**Issue by annelo-msft** [Azure/azure-sdk-for-net#10378]
Confidence is a required field for unsupervised KeyValuePair, but is an optional field for supervised FieldValue.

Confidence also comes back for the full unsupervised KeyValue pair, but for supervised it comes back on the FieldValue itself (not the label).

What is the best approach to merging Confidence in ExtractedForm's fields?

See:
- https://github.com/Azure/azure-sdk-for-net/blob/ce046949f17fc4ceeab5c87beb4750047b983565/sdk/formrecognizer/Azure.AI.FormRecognizer/src/ExtractedField.cs#L43

**Comment by annelo-msft** [comment]
@kristapratico Please add anything I missed here.  Thanks!

**Comment by ctstone** [comment]
1. I suspect the reason that confidence is not required on FieldValue is b/c FieldValue may hold collections of other fields (array, object)
2. I believe the confidence refers to the pairing itself (this key goes with that value), but I will try to get some more precise language for you

**Comment by annelo-msft** [comment]
See: https://teams.microsoft.com/l/message/19:88f2d9dea2344075b5d4bc34d82a3d1c@thread.skype/1583537987876?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=3e17dcb0-4257-4a30-b843-77f47f1d4121&parentMessageId=1583537987876&teamName=Azure%20SDK&channelName=Service%20-%20Form%20Recognizer&createdTime=1583537987876

**Comment by annelo-msft** [comment]
@ctstone @bojunehsu

**Comment by bojunehsu** [comment]
Chris's suspicion is correct.  We do not currently return a confidence value for the "items" FieldValue because it is not well defined for arrays.  Since this corresponding confidence value is not directly exposed right now, we may be able to make this required in the SDK.

Note, we are currently releasing business card (v2.1-preview.1), which introduces a "fullName" FieldValue of type ObjectValue, which contains "firstName" and "lastName" as subfields.  We plan to output confidence for this "fullName" field.  It is currently unclear if we will always output a confidence value for ObjectValue fields right now.

In general, elements (word bounding boxes) will cooccur with confidence value.

**Comment by annelo-msft** [comment]
Moving to May as we won't unify models for preview 1

**Comment by annelo-msft** [comment]
We will unify models for preview 1, moving back to April.

**Comment by annelo-msft** [comment]
@bojunehsu recommendation is to set confidence to 1.0 wherever it is null, per Teams thread: https://teams.microsoft.com/l/message/19:88f2d9dea2344075b5d4bc34d82a3d1c@thread.skype/1586389362256?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=3e17dcb0-4257-4a30-b843-77f47f1d4121&parentMessageId=1586389362256&teamName=Azure%20SDK&channelName=Service%20-%20Form%20Recognizer&createdTime=1586389362256

**Comment by annelo-msft** [comment]
Related item: https://github.com/Azure/azure-sdk-for-net/issues/10490
Investigating whether we can use the same approach in both places.

**Comment by annelo-msft** [comment]
Closed for preview 1 - we'll set confidence to 1.0 wherever it comes back null from the service.
