### ISSUE TITLE
Event Hub Partition - Properties of .NET Framework required in .NET Standard/Core

### ISSUE THREAD

**Issue by srivathsanvlb** [Azure/azure-sdk-for-net#10421]
**Library or service name.**
Azure.Messaging.EventHubs 
 
**Is your feature request related to a problem? Please describe.**
As described in the issue https://github.com/Azure/azure-sdk-for-net/issues/10014, we need the following properties in .NET Standard/Core

  | .NET Framework |   | .NET Standard
-- | -- | -- | --
  |   |   |  
Class Name | Property Name |   |  
PartitionDescription | SizeInBytes |   |  
PartitionDescription | IncomingBytesPerSecond |   |  
PartitionDescription | OutgoingBytesPerSecond |   |  
EventHubDescription | Status

Since we are working for migration to .NET Core from Framework, availability of the above properties would remove a major blocker for us. Thanks in advance.

**Comment by jsquire** [comment]
Hi @srivathsanvlb; thank you for your feedback.  For this to make its way into the library, there are two key things that we'll need to lock down.  The first is to determine whether or not the service is exposing this information for us to consume, which I'll follow up on. 

The second would be building a proposal for changes to the public AP, and passing through a review process.  In order for me to be able to do that, I'll need an understanding of the scenarios that you're looking to address using the requested information.  Any details and context that you can provide would be very helpful.

**Comment by srivathsanvlb** [comment]
@jsquire 

Thanks for your support

Long story short, we are exposing in-depth details of the specified event hub to an external party. They probably use it for displaying it to the end user as status of the event hub, kind of monitoring stuff.

For that we do the below in .NET Framework

` NamespaceManager namespaceManager = NamespaceManager.CreateFromConnectionString(eventHubPartitionRequest.ConnectionString);
            return await namespaceManager.GetEventHubPartitionAsync(eventHubPartitionRequest.EventHubName, eventHubPartitionRequest.PartitionName);`

` var sbConnStringBuilder = new ServiceBusConnectionStringBuilder(connectionString)
            {
                TransportType = Microsoft.ServiceBus.Messaging.TransportType.Amqp
            };
            NamespaceManager namespaceManager = NamespaceManager.CreateFromConnectionString(sbConnStringBuilder.ToString());
            var eventhub = await namespaceManager.GetEventHubAsync(eventHubPath);
            return eventhub.PartitionIds;`

Now we have to migrate to Core/Standard, but some of properties are missing. I am working on identifying the API methods of WindowsAzure.ServiceBus nuget package, Microsoft.ServiceBus namespace, that would fail in .NET core. 

Hope the above information would suffice. Let me know if it doesn't

**Comment by jsquire** [comment]
Hi @srivathsanvlb.  Thank you for the additional context.  

I've spoken with @serkantkaraca, and it appears that the the information requested is only available via the [management REST API](https://docs.microsoft.com/en-us/rest/api/eventhub/get-partition-runtime-metadata).  Serkant, please correct me if I misunderstood that conversation.

I've commented on #10014 to ask that the team owning the management library consider adding these, which may be the best short-term solution to unblocking you.   While I certainly understand that potentially having to use two SDKs would be inconvenient, it is probably the most expedient path forward.

Unfortunately, the management plane isn't something that we're able to consume within the client; in order to include the additional fields in the `Azure.Messaging.EventHubs` library, the Event Hubs service will need to expose those fields as part of the data plane interface.    To begin that conversation, I'm going to route this to the service team's attention as a request and ask that @jfggdl, @ShubhaVijayasarathy, and @serkantkaraca offer their thoughts.

**Comment by serkantkaraca** [comment]
@srivathsanvlb  you should implement an HTTP wrapper to provide such functionality. We currently don't have any plans to expose those metrics on our data-plane endpoints.

**Comment by srivathsanvlb** [comment]
@serkantkaraca  @jsquire 

I will use the REST API as of now. Thanks for the quick turn around. You may have this thread open or close it. I will leave it to your discretion.

**Comment by jsquire** [comment]
I'll go ahead and close this one out and we'll continue to use #10014 to advocate for having this added to the management library.
