### ISSUE TITLE
[Storage] Retries exceed MaxRetries if server sends partial response

### ISSUE THREAD

**Issue by mikeharder** [Azure/azure-sdk-for-net#10449]
When using `Azure.Core@1.1.0` and `Azure.Storage.Blobs@12.4.0-dev.20200306.1`, `BlobClient.DownloadToAsync()` appears to retry indefinitely if the server sends a partial body, even though `MaxRetries = 1`.

## Repro Steps
1. Start a server which can inject HTTP faults, like https://github.com/mikeharder/HttpFaultInjector.

2. Create a BlobClient with the following options:

```C#
var httpClient = new HttpClient(httpClientHandler)
{
    Timeout = TimeSpan.FromSeconds(5)
};

var blobClientOptions = new BlobClientOptions()
{
    Transport = new ChangeUriTransport(new HttpClientTransport(httpClient), "localhost", 7778),
    Retry = {
        MaxRetries = 1,
        NetworkTimeout = TimeSpan.FromSeconds(10)
    },
};

var blobClient = new BlobClient(connectionString, "testcontainer", "testblob", blobClientOptions);
var response = await blobClient.DownloadToAsync(new MemoryStream());

private class ChangeUriTransport : HttpPipelineTransport
{
    private readonly HttpPipelineTransport _transport;
    private readonly string _host;
    private readonly int? _port;

    public ChangeUriTransport(HttpPipelineTransport transport, string host, int? port)
    {
        _transport = transport;
        _host = host;
        _port = port;
    }

    public override Request CreateRequest()
    {
        return _transport.CreateRequest();
    }

    public override void Process(HttpMessage message)
    {
        ChangeUri(message);
        _transport.Process(message);
    }

    public override ValueTask ProcessAsync(HttpMessage message)
    {
        ChangeUri(message);
        return _transport.ProcessAsync(message);
    }

    private void ChangeUri(HttpMessage message)
    {
        // Ensure Host header is only set once, since the same HttpMessage will be reused on retries
        if (!message.Request.Headers.Contains("Host"))
        {
            message.Request.Headers.Add("Host", message.Request.Uri.Host);
        }

        message.Request.Uri.Host = _host;
        if (_port.HasValue)
        {
            message.Request.Uri.Port = _port.Value;
        }
    }
}
```

3. Run the client app, and instruct the server to send a partial response (say 50% of the body).

4. The client will read the partial response, block for 10 seconds (`NetworkTimeout`), then retry but only requesting the remaining 50% of bytes (with a `Content-Range` header).

5. Again instruct the server to send a partial response (50% of the remaining body == 25% of the original body).

6. The client will again read the partial response, block for 10 seconds (`NetworkTimeout`), then retry but only requesting the remaining 25% of original bytes.

7. This can be repeated indefinitely, despite `MaxRetries=1`.  I'm not sure if this is a bug or by design.

**Comment by mikeharder** [comment]
Might also repro if service sends headers but no body (compared to 50% of body).

**Comment by pakrym** [comment]
I'm not sure how to best approach this without making customer code less reliable.

It's true that we're applying MaxRetries only to the attempt to re-establish connection when it fails but if connection resumed succesfully we "reset" the retry counter.

But looking at our current default of 3 retries it's insufficient to be able to successfully download a reasonably large file.

I'm tempted to backlog this until we get reports from customers that we are trying too hard.

@tg-msft what are your thoughts here?

**Comment by tg-msft** [comment]
I agree with @pakrym for our current design.  Otherwise we'll have to add more configurable knobs allowing users to explicitly control this scenario if and when we hear customer feedback.  I would also welcome input from @JeffreyRichter as he probably knows of any serious flaws with this approach in practice.

**Comment by JeffreyRichter** [comment]
I'm not familiar with your exact implementation but why would you reset the retry counter if something is successful? My mental model (and what I've implemented in the past) was that each operation (XxxClient method) starts out with the customer's configured max retry count and then this decrements with each try and nothing resets this. This works great for everything. 

Now, blob download has an additional issue in that after you've left the pipeline, you return the network stream back to customer code and it continues to read the blob. Since you've left the pipeline, the retry count no longer applies. What I did in this case, was a created a ReliableStream class and had an instance of this wrap the NetworkStream. The ReliableStream ctor took a max retry count (which was unrelated to the retry count used by the pipeline policy) and no retry delay options - just a count. Now, while reading from the ReliableStream, if it detected a network failure, it could retry calling DownloadBlob which would then use the pipeline policy's retry. The end result is that that you had one set of retries to initiate downloading a blob and another (very simple) retry that only kicked in once you started reading from the stream.

**Comment by pakrym** [comment]
We have very similar implementation but our `ReliableStream` currently doesn't limit retry count.

**Comment by tg-msft** [comment]
So my understanding of this issue is that we'll do the following:

1. Start downloading with the customer's `MaxRetries` via the pipeline
2. Wrap in a `RetriableStream`
3. If downloading the stream fails after we've left the pipeline
    a. Try to start downloading from where we left off with the customer's `MaxRetries` via the pipeline
    b. If that succeeds, go back to step 2
    c. If that fails, loop back to step 3, up to 3 times
4. Return the downloaded blob

We don't adjust `MaxRetries` in Step 3a to account for the number of attempts in Steps 1 or previous iterations of Step 3a.  We also don't keep a running number of attempts in Step 3c so every stream failure kicks off a whole new cycle.  This could take a very long time under adverse circumstances _(absolute worst case being `3 * MaxRetries * BlobSize` requests if Mike sets up a test server that fails after sending back a single byte)_.

Mike's point in raising the issue is number of actual retries that could happen in a flaky blob download doesn't correspond to how the customer envisions `MaxRetries` working.  Pavel and I are okay with this until we hear from customers at which point we could add a few more RetryPolicy knobs to allow configuring what happens in Step 3.

**Comment by pakrym** [comment]
Customers never reported problems with this behavior.
