### ISSUE TITLE
[FEATURE REQ] Single-staged uplads for non-seekable content streams

### ISSUE THREAD

**Issue by rmja** [Azure/azure-sdk-for-net#10532]
**Library or service name.**
Azure.Storage.Blobs
 
**Is your feature request related to a problem? Please describe.**
The current overloads of `UploadAsync` on `BlobClient` does not allow to specify a specific length of the content stream resulting in multi-staged uploads for non-seekable streams: 

https://github.com/Azure/azure-sdk-for-net/blob/1326260cf35a15f6152f5977f18e8aa3bf8c0ce1/sdk/storage/Azure.Storage.Blobs/src/PartitionedUploader.cs#L106-L120

It would be nice if the `CanSeek` check was removed here:

https://github.com/Azure/azure-sdk-for-net/blob/1326260cf35a15f6152f5977f18e8aa3bf8c0ce1/sdk/storage/Azure.Storage.Common/src/Shared/PartitionedUploadExtensions.cs#L29-L33

so that the length could be used even for non-seekable streams resulting in single staged uploads.
Alternatively, add `contentLength` as an optional parameter to `UploadAsync`.

**Comment by amnguye** [comment]
@seanmcc-msft Did we resolve this already?

**Comment by seanmcc-msft** [comment]
Hi @rmja,

Unfortunately, [non-seekable streams do not support the Length property](https://docs.microsoft.com/en-us/dotnet/api/system.io.filestream.canseek?view=netcore-3.1#remarks), so we were to remove this check, we would throw a `NotSupportedException` if the stream is not seekable, so we can't remove this check.

Individual upload calls to the storage service have a length limit:

- [4,000MiB for Block Blobs](https://docs.microsoft.com/en-us/rest/api/storageservices/put-block#request-headers),
- [4MiB for Page Blobs](https://docs.microsoft.com/en-us/rest/api/storageservices/put-page)
- [4MiB for Append Blobs](https://docs.microsoft.com/en-us/rest/api/storageservices/append-block)

Because we can't detect the length of a non-seekable stream, it is not safe for us to attempt a single-shot upload.

Please re-open if you have further questions.

-Sean
