### ISSUE TITLE
Return a collection of forms from ExtractForm and variants

### ISSUE THREAD

**Issue by annelo-msft** [Azure/azure-sdk-for-net#10541]
Consider whether this should be pageable

**Comment by annelo-msft** [comment]
@ctstone , @kristapratico , @samvaity, @jeremymeng , @mayurid, @bojunehsu

**Comment by bojunehsu** [comment]
Not quite sure how we can make this pageable if the API returns the full set of results at the same time.

**Comment by annelo-msft** [comment]
@bojunehsu Would you ever support processing so many forms/pages in a single input document at once that you would want to send back the results in difference pages?

**Comment by bojunehsu** [comment]
We recently bumped up the PDF page limit to 2000.  I agree that it will be really nice to support streaming processing for such situations in the future.  This would require significant changes to the REST API that APIM cannot easily support today.

That said, at the SDK interface level, it would be great if ExtractForm returns IEnumerable<> or equivalent instead of IList<> even if the underlying implementation today does not support paging.  This is assuming it is just as easy for developers to use a paged result as a list result.  (IEnumerable in .NET is good.  Not sure what is the Python/Java/JS equivalent.)
