### ISSUE TITLE
[FEATURE REQ] Way to log the client information for messages being read

### ISSUE THREAD

**Issue by Sandeep321** [Azure/azure-sdk-for-net#10705]
**Library or service name.**
Microsoft.Azure.ServiceBus
 
**Is your feature request related to a problem? Please describe.**
We are using the Azure service bus for message processing. We host one or more App Service instances(subscribers) that would be connected to the same Topic and subscription. 
After a message is published from the publisher, the message becomes available in subscription and then it gets consumed by one of the App Service instances. 
Without actually digging into logs for each App Service instance, it's not possible to know which instance has actually processed the message. Is there a way to get that information from the Service Bus side, if yes, please provide some details. If not, can this be considered as a feature request? I am sure it would add a lot of value to consumers.

**Comment by axisc** [comment]
@Sandeep321 Thanks for opening this issue.

We don't log data operations on the service side because data operations are too many. I would definitely recommend that these are logged by the client applications.

When you use MessageHandler (or SessionHandler) on the QueueClient and SubscriptionClient, we utilize [ServiceBusDiagnosticSource](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/servicebus/Microsoft.Azure.ServiceBus/src/ServiceBusDiagnosticsSource.cs) to log this information which you can place into an AppInsights instance.

If you use MessageReceiver, then you will have to log these manually.

hope this helps.

**Comment by Sandeep321** [comment]
@axisc I have a service bus instance running and there are a couple of subscribers connected to it(Subscribers are our services and we can very well add the logs to get the info we want to capture.)
Here is where my problem lies.
I (or someone else) writes a piece of code that doesn't have any logging etc and starts subscribing and consuming the events from the service bus. We as a team would never get to know who actually is subscribing and processing the messages.
So, here it becomes very important for the Service bus to know and expose the information on which message we received by whom.
Is there a way to achieve the same?

**Comment by Sandeep321** [comment]
Hi @axisc Can you please provide your inputs on the above question?

**Comment by axisc** [comment]
@Sandeep321 at the moment, no. we may add audits eventually, but those still wouldn't capture data at the level you need. That must be through client side tracing.
