### ISSUE TITLE
[Design] Design FormRecognizer Checkboxes Feature

### ISSUE THREAD

**Issue by annelo-msft** [Azure/azure-sdk-for-net#10767]
Design the CheckBox feature for Form Recognizer.

**Comment by annelo-msft** [comment]
Comment on the APIView:

We are planning to introduce FormField of type CheckBox (v2.1). The intent was that we use the element references to specify the path to the checkbox (ex. "/pageResults/0/checkBoxes/0"). Not sure how we would fit this into the current SDK design.

@bojuneshu, can you share more details about how this wouldn't fit into the design? I'm not sure I understand.

**Comment by bojunehsu** [comment]
When we introduce checkbox into supervised form, it will be returned as a field with type=checkbox. 
Currently, we resolve the element references to the words that make up the field value using FormTextElement.  But since checkboxes do not inherit from FormTextElement, we would need to tweak the design to allow the field to reference the words/lines/checkboxes/tables/future content that make up the field value.

**Comment by annelo-msft** [comment]
@bojunehsu, would adding FormContent to FormCheckbox address this concern?
