### ISSUE TITLE
[QUERY] Best way to create a new, empty blob?

### ISSUE THREAD

**Issue by sebader** [Azure/azure-sdk-for-net#10784]
**Query/Question**
With the latest Azure.Storage.Blob SDK (v12), what is the best way to create a new, empty block blob? Currently I'm using this but not sure if this is the best way, using an empty MemoryStream?!

````
var _blobContainerClient = new BlobContainerClient(new Uri(containerUrl), new DefaultAzureCredential());
var stateBlobClient = _blobContainerClient.GetBlobClient("myblob");

await stateBlobClient.UploadAsync(new MemoryStream());
````

**Environment:**
 - Name and version of the Library package used: Azure.Storage.Blobs 12.4.0 
 - Hosting platform or OS and .NET runtime version: .NETCore 3.1

**Comment by seanmcc-msft** [comment]
Which type of blob would you like to create?  Block, Append, or Page?

**Comment by sebader** [comment]
Block blobs

**Comment by seanmcc-msft** [comment]
Currently, I believe the only way to create an empty Block Blob is your current method, with the empty Stream.  We should consider adding BlockBlobClient.Create() and .CreateAsync().  @tg-msft , what do you think?

**Comment by tg-msft** [comment]
I don't think we want a `BlockBlobClient.Create` method.  That would end up causing a lot of new users to think they had to call `Create` and then `Upload`.  But of course that would be overwriting an existing blob which isn't the default for `Upload` and then they'd have to struggle through that.

While this isn't an advanced scenario, it's far less common than the mainline "upload my bits" that we want to keep as smooth as possible for new users.  I think a better approach here would be documenting how to create an empty blob in the `content` property's XML doc comment.

I think we could also pass `Stream.Null` instead of allocating a `new MemoryStream` to make this slightly easier as it has no .ctor parameters for people to worry about, but we should test that to be safe.

**Comment by JimSuplizio** [comment]
Hi @sebader, we deeply appreciate your input into this project. Regrettably, this issue has remained inactive for over 2 years, leading us to the decision to close it. We've implemented this policy to maintain the relevance of our issue queue and facilitate easier navigation for new contributors. If you still believe this topic requires attention, please feel free to create a new issue, referencing this one. Thank you for your understanding and ongoing support.
