### ISSUE TITLE
Search package reference docs do not show on azure.github.io

### ISSUE THREAD

**Issue by kaerm** [Azure/azure-sdk-for-net#10790]
Missing link for the new preview of the libraries: https://azure.github.io/azure-sdk-for-net/search.html

https://www.nuget.org/packages/Azure.Search/11.0.0-preview.1

**Comment by kaerm** [comment]
Same as for Python: https://github.com/Azure/azure-sdk-for-python/issues/10449

**Comment by chidozieononiwu** [comment]
The issue here is that the Packages Directory Name in the repo `Azure.Search.Documents` which happens to also be the project name is different form the names used to publish the Nuget Package `Azure.Search` which happens to be the names used to publish the docs to blob storage. These names will have to match because github.io depends on consistent namint to be able to pickup ad display the docs.

I ran a local `dotnet pack` and the generated packages are named correctly `Azure.Search.Documents` we will have to figure out why it is generated as `Azure.Search` in the [pipeline](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=288745&view=artifacts&type=publishedArtifacts).

**Comment by scbedd** [comment]
I'm betting it's because they released with the previous name, then re-named in place. This is exactly what bit Python.

**Comment by chidozieononiwu** [comment]
[Azure.Search.Documents](https://azuresdkdocs.blob.core.windows.net/$web/dotnet/Azure.Search.Documents/1.0.0-preview.2/api/index.html)  1.0.0-preview.2 is now published with the correct name.
