### ISSUE TITLE
How to use ServiceBusManagementClient to get authenticated NamespaceManager

### ISSUE THREAD

**Issue by davihar** [Azure/azure-sdk-for-net#1080]
NamespaceManager takes NamespaceManagerSettings as a parameter which has a TokenProvider to enable authentication.  I don't have the Service Bus connection string but I have the Azure management certificate.  How can I use ServiceBusManagementClient to obtain the connection string or token information so I can create a NamespaceManager capable of creating Service Bus Event Hubs, etc?

Thanks

**Comment by OneOfSome** [comment]
ServiceBusManagementClient client = new ServiceBusManagementClient(credentials);
Code to do it:
var response = await client.Namespaces.CreateAsync(namespaceName, region, cancellationToken);
// you can create one here using CreateAuthorizationRule – below is the default one
var sasRule = await client.Namespaces. GetAuthorizationRuleAsync(namespaceName, “RootManageSharedAccessKey”, cancellationToken);

var connStr = new ServiceBusConnectionStringBuilder();
connStr.Endpoints.Add(ServiceBusEnvironment.CreateServiceUri("sb", namespaceName, string.Empty));
connStr.SharedAccessKey = sasRule.AuthorizationRule.PrimaryKey;
connStr.SharedAccessKeyName = sasRule.AuthorizationRule.KeyName;
var manager = NamespaceManager.CreateFromConnectionString(connStr.ToString());

Short explanation:
ServiceBusManagementClient uses Azure wide Credentials (CloudCredentials) to gain Management access on the Namespace. Its a rest framework built on top of all Azure services to make management story easy.
ServiceBus.NamespaceManager existed since inception of ServiceBus and had support for Managing Entities inside a Namespace (the above one - SBMgmtClient can do ServiceBus NS's too) using servicebus specific authorization. 
Using SBMgmtClient you will be able to query everything - including the SB authorization rules - using which you can achieve this.
