### ISSUE TITLE
Prevent generation of src/SDKs/_metadata/ Directory

### ISSUE THREAD

**Issue by chidozieononiwu** [Azure/azure-sdk-for-net#10924]
Track down the actual reason why _metadata is still being generated in the old repo structure, stop this from happening then clean up `src/SDKs/_metadata/` directory.

**Comment by kurtzeborn** [comment]
Labeling this for the Mgmt team to follow up on since this is coming from management tool generation.

**Comment by Petermarcu** [comment]
What's the eta for a fix here?

**Comment by isra-fel** [comment]
My theory is that this file is generated in the wrong path because an old version of build tools was used, so every time I see that I tell the author to [update their build tools](https://github.com/Azure/adx-documentation-pr/blob/master/engineering/adx_netsdk_process.md#updating-build-tools). Apparently I'm not accurate enough though.

To prevent this, my plan is to add a check in the mgmt ci pipeline. If `src/SDKs/_metadata/` exists, it fails. Planning to do in this week.

**Comment by isra-fel** [comment]
Also opened #11111 (wow) to move the file to the right place
