### ISSUE TITLE
Azure.Messaging.ServiceBus versioning is off

### ISSUE THREAD

**Issue by SeanFeldman** [Azure/azure-sdk-for-net#10959]
For Track 2 of the Service Bus SDK the following decisions where made:

- The implementation has nothing in common with Track 1 code base and is a complete rewrite. Ok.
- A new package name was embraced to be consistent with the rest of the SDKs. Ok.
- The version is continued from the Track 1. Not ok.

Trak 1 current major version is version 4. Track 2 was planned to start from version 5.
When I brought up the concern about the potential issue should Track 1 require a major release, it was brushed off. Now the first major version of Track 2 is [version 7](https://github.com/Azure/azure-sdk-for-net/pull/10909/files#diff-5d015c6526e2e1072de99d9908402e51R3). Seven?

What is the though rationale behind this? Why not 10? Or why simply not to start with version 1 given this is a brand new package. Starting with a version other than version 1 is confusing and misleading.

**Comment by AlexGhiondea** [comment]
Hi @SeanFeldman 

Thanks for your question. The reason we went with version 7 is because that is the next highest version across **all** releases of Service Bus:
- [WindowsAzure.ServiceBus](https://www.nuget.org/packages/WindowsAzure.ServiceBus) which is the 'Track 0' library is version `6.0`.
- [Microsoft.Azure.ServiceBus](https://www.nuget.org/packages/Microsoft.Azure.ServiceBus/) which is the 'Track 1' library is version `4.0`

We wanted to make sure that when people search for Service Bus on Nuget.org they will see a version that is higher than both of those. That is how we landed on version `7.0`.

To give you some additional context on this: when we first started our Track 2 work the libraries started with a version `1.0` in our early previews. During our UX studies we noticed that because the Track 2 library had a lower version than the Track 1 library, people tended to overlook the Track 2 library. When we switched the version of the Track 2 library to be the highest+1 version available, we saw that people were successfully finding and using our Track 2 library. 

We have been using this pattern (of using the highest version available + 1) for all of the services we have released as a Track 2 library for and we are continuing the same pattern with the Service Bus library.

**Comment by SeanFeldman** [comment]
Thank you, @AlexGhiondea.
Don't know what those UX studies looked like, but this is what it looks like when searching for "service bus":

![image](https://user-images.githubusercontent.com/1309622/78082747-01633900-7371-11ea-80ea-d4a7b2ddee09.png)

The version doesn't play any role ATM. It's the number of downloads. And I would expect the Track 0 version to lead for quite a while. Track 1 is out for a few years and still is rated lower based on the downloads. Unless NuGet is tweaked in a way that returns results based on the version.

Regarding 
> We have been using this pattern (of using the highest version available + 1) for all of the services we have released as a Track 2 library for and we are continuing the same pattern with the Service Bus library.

When I've provided the feedback about using version 5, it also was turned down. Yet an internal decision since then was to bump it to version 7. It's never too late to change a strategy.

**Comment by AlexGhiondea** [comment]
@SeanFeldman thanks for the feedback, Indeed the download number is a factor. We want to ensure that what is under our control (ie. the version) helps put customers in the 'pit of success' as much as possible.

We were initially going to go with version `5.0` until we looked at the version for the 'Track 0' library. Because that version was `6.0` we decided to go with `7.0` in order to have the highest version available.

**Comment by SeanFeldman** [comment]
The focus should not be on a lab-like exercise to measure UX on NuGet. There are much better and proven ways to generate the awareness. One of the multiple possible paths is the  documentation and generating awareness. Works better than NuGet search. You've got the luxury of learning from lessons of the track 0/1 transition, though it looks like you're going to repeat it.

You're a bunch of smart folks and I can only suggest. Your decision wherever to listen or ignore.

**Comment by jongio** [comment]
@loarabia - Applies to the NuGet work you are doing.

**Comment by CumpsD** [comment]
I personally only use a library if it has reached at least version 10 to prove its stability. 

:trollface:

**Comment by Petermarcu** [comment]
Thanks for all the feedback. At this point, we plan to continue with the pattern we've used for all other services and leverage the new NuGet feature that supports promotion in the search results across package renames of the same lineage. I'm going to close this issue now.
