### ISSUE TITLE
Add Receive Timeout

### ISSUE THREAD

**Issue by JoshLove-msft** [Azure/azure-sdk-for-net#10965]
We should add an optional timeout to our receive methods, instead of relying on the TryTimeout from RetryPolicy. This will give a greater degree of configurability to users and is something that they will expect for long polling use cases.

**Comment by pakrym** [comment]
Why isn't cancellation token enough?

**Comment by JoshLove-msft** [comment]
> Why isn't cancellation token enough? Usually we rely on passing a cancellation token if customer needs to specify additional parameter.

The underlying AMQP library doesn't have cancellation token support, so our use of cancellation tokens in EH and SB only really applies to the outer layer. The [AMQP library](https://github.com/Azure/azure-amqp/blob/4dcaf85d6073902c62b6866112447020321095da/src/ReceivingAmqpLink.cs#L140) expects a TimeSpan.

We are proposing adding a Maximum wait time which is similar to what EH has here https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/eventhub/Azure.Messaging.EventHubs/src/Consumer/ReadEventOptions.cs#L72

**Comment by pakrym** [comment]
Did we raise this issue with the AMQP library team? Is there a plan of when if ever it's going to be supported?

**Comment by ShivangiReja** [comment]
cc: @nemakam

**Comment by jsquire** [comment]
> Did we raise this issue with the AMQP library team? Is there a plan of when if ever it's going to be supported?

Yes; they don't feel that it aligns with the AMQP spec, which discusses things in terms of timeouts, since the connection/link are persistent resources.  There is no plan to extend it with cancellation token support on the roadmap.

**Comment by jsquire** [comment]
There's a bit of a difference with respect to the Event Hubs `MaximumWaitTime` and `TryTimeout`.    The latter is always used at the protocol level for operations like creating the AMQP connection, links, and similar.   The wait time, which this sounds similar to, is used as an override at the operation level - when sending/receiving messages over an existing link.

I'm guessing that's what you've got in mind, but wanted to mention it, just in case.    _([example](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/eventhub/Azure.Messaging.EventHubs/src/Amqp/AmqpConsumer.cs#L190))_

**Comment by pakrym** [comment]
Streams are persistent resources but they do support cancellation tokens.

So basically all cancellation tokens customers pass in are not respected as soon as we get into the transport layer.

**Comment by JoshLove-msft** [comment]
> There's a bit of a difference with respect to the Event Hubs `MaximumWaitTime` and `TryTimeout`. The latter is always used at the protocol level for operations like creating the AMQP connection, links, and similar. The wait time, which this sounds similar to, is used as an override at the operation level - when sending/receiving messages over an existing link.
> 
> I'm guessing that's what you've got in mind, but wanted to mention it, just in case. _([example](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/eventhub/Azure.Messaging.EventHubs/src/Amqp/AmqpConsumer.cs#L190))_

Yes, this is what we have in mind.

**Comment by jsquire** [comment]
> Streams are persistent resources but they do support cancellation tokens.
> 
> So basically all cancellation tokens customers pass in are not respected as soon as we get into the transport layer.

Yup;  this is the same discussion that we had back in the September/October timeframe and discussed with the members of the messaging team that own the AMQP library.   I can't claim to be familiar enough with the full scope of the AMQP spec to make an authoritative judgement on whether adding cancellation would or would not break compliance with the protocol.

**Comment by nemakam** [comment]
@pakrym ,
Here's my opinion around this - 
`Receive()` in AMQP would be a long-poll operation that would never return if there's no message. So having a way to cancel the operation is necessary every time the method is called. We cannot allow them to call the method without either passing a timeout or a cancellationToken. 
We can definitely ask users to pass in a new cancellation token for every operation, but when you look at this as a mainstream solution, the hello world sample would get complicated if you want users to create a token for every operation just because it doesn't support timeout value. 
What would the default value look like here? 
Can we make sure customers are actually cancelling the tokens after the "timeout", if not they would end up debugging their code which keeps getting stuck. 
A much simpler option would be for the ServiceBus library to provide a `timeout` parameter with a default value (say 60 seconds). so that the customers need to fiddle with the cancellation token every single time.

Regarding AMQP library, I do not have a strong opinion, but I do see there are pros and cons of both. There is some value in not having "cancellation" support in AMQP since that is a stateful persisted protocol. Defining what would happen when the "Cancellation" occurs would be a difficult thing as the state could be very inconsistent. AFAIK, the amqp-library has uses the approach that if you close the amqp-link, all running operations would immediately return. And thats the only way they allow cancellation as you are not worried about a complicated state. 
Things would have been super simpler in a request-response protocol like HTTP/REST. But unfortunately in AMQP, the HTTP constructs do not hold valid in lot of scenarios.

**Comment by pakrym** [comment]
Thank you for your perspective @nemakam !

> Receive() in AMQP would be a long-poll operation that would never return if there's no message. 

Stream.ReadAsync has exactly the same semantics. It would block forever if no data arrives or cancellation token is not cancelled. This pattern is pretty widely used in the framework and we haven't seen a too much confusion from customers about it.

> the hello world sample would get complicated

Do we advertise the library as being consumable directly? I thought it's mostly supporting other client libraries that layer on top of it.

> Regarding AMQP library, I do not have a strong opinion, but I do see there are pros and cons of both. There is some value in not having "cancellation" support in AMQP since that is a stateful persisted protocol. Defining what would happen when the "Cancellation" occurs would be a difficult thing as the state could be very inconsistent. AFAIK, the amqp-library has uses the approach that if you close the amqp-link, all running operations would immediately return. And thats the only way they allow cancellation as you are not worried about a complicated state.

I understand that cancellations in a protocol like AMQP are not easy to define. What happens right now when an operation timeouts?

> Things would have been super simpler in a request-response protocol like HTTP/REST. But unfortunately in AMQP, the HTTP constructs do not hold valid in lot of scenarios.

I would argue that HTTP2 is not that far from AMQP in terms of multiplexing/streams and connection state management, even HTTP1.1 has Keep-Alive mode that persists connections between requests so there should be some prior art on the topic.

On of the main goals of Track 2 libraries is consistency between themselves and consistency with base class library. From this perspective our AMQP based libraries are outliers in having to take timeouts in addition to cancellation tokens and having cancellation tokens that don't work in some cases.

The other reason is that timeout can always be implemented via cancellation token but not the other way around, we can't use existing timeout functionality to add cancellation token support in any meaningful way.

**Comment by JoshLove-msft** [comment]
Fixed in https://github.com/Azure/azure-sdk-for-net/pull/10981
