### ISSUE TITLE
[FEATURE REQ] Upgrade DotNetCoreRuntimeVersion to latest (3.1.2)

### ISSUE THREAD

**Issue by chidozieononiwu** [Azure/azure-sdk-for-net#11014]
Upgrade DotNetCoreRuntimeVersion in `eng\pipelines\templates\variables\globals.yml` to the [latest available on our build agents](C:\Git\azure-sdk-for-net\eng\pipelines\templates\variables\globals.yml) i.e. 3.1.2.

@AlexGhiondea Should we move past Net core netcore 2.1 or stay there and add a netcore 3.x test leg as well?

**Comment by heaths** [comment]
Might be a good idea, but I have concerns about timing and resources. This will incur additional Azure resources, so right now under current use guidance, it might not be a good idea.

Even still, we do have some live tests that take quite a while and we can only parallelize so much because of limits. If we increase the number of platforms/frameworks to test, we will either need to increase those limits, or increase any timeouts on pipelines we have and expect longer pipelines.

**Comment by weshaggard** [comment]
@AlexGhiondea can you or someone on your team advise on what version of .NET Core we want to test?

**Comment by kurtzeborn** [comment]
We just added runtime support for .NET 5.  We don't need to track this one any more.
