### ISSUE TITLE
[QUERY] What purpose does connection string serve when using SAS

### ISSUE THREAD

**Issue by mtaylorfsmb** [Azure/azure-sdk-for-net#11026]
Which version of the SDK was used?
v12.0 on .NET Core 2.1

Question?
We use a SAS to connect from one of our apps. We previously used the legacy Azure Storage library and we had code similar to the following.

```csharp
_account = new CloudStorageAccount(new StorageCredentials(storagAccountName, storageAccounKey), true);

var blobClient = _account.CreateCloudBlobClient();
```

Now we have to do something like this.

```csharp
_credentials = new StorageSharedKeyCredentials(storageAccountName, storageAccountKey);

var blobClient = new BlobServiceClient(connectionString, _credentials);
```

Why is the connection string now required when using SAS credentials? Looking at the connection string that is generated it contains some default options (e.g. HTTPS) and embeds the account name/key already. So it seems that the constructor could infer the connection string from the credentials like it used to do. It seems redundant to need to specify a connection string (with embedded credentials) in addition to creating a separate credentials object.

I see 2 possible options here right now.

- Store both the connection string and storage account name/key and set all this up even though it is somewhat redundant.
- Forget the SAS credentials altogether and just use the connection string. But I'm not sure what impact that has, if any.

**Comment by amishra-dev** [comment]
@mtaylorfsmb thanks for reporting this. we are in the process of refactoring the SAS implementation, @jaschrep-msft to respond and ack that this behavior will get fixed once the refactor is in.

**Comment by jaschrep-msft** [comment]
@amishra-dev, I don't agree just yet this has to do with our SAS refactors, as those refactors are to do with generation, not usage of an existing SAS.

@mtaylorfsmb, can you help me to better understand your code snippits? I think there is confusion of terminology here, as what you are saying doesn't match your code snippits as far as I can tell.

Regarding your legacy snippit, you state you use a SAS, but I only see you authenticating with your account key, also called your storage shared key (not the same thing as a shared access signature, which is what you state is being used).

Regarding your v12 snippet, I see you creating the exact same shared key credential object to start out (with its different name in the new library), so I still don't see any SAS usage. You then say you are using a connection string with that constructor, but the only constructors on BlobServiceClient that take a connection string are as follows:
```csharp
public BlobServiceClient(string connectionString);
public BlobServiceClient(string connectionString, BlobClientOptions options);
```
You display the explicit use of a `StorageSharedKeyCredentials` instance in the constructor, the only constructor of which is as follows:
```csharp
public BlobServiceClient(Uri serviceUri, StorageSharedKeyCredential credential, BlobClientOptions options = default)
```
This would mean you are using the url to the storage account as a `Uri` instance, not a connection string. The constructor intended for SAS usage is the following, where the uri to the account has the SAS query string appended to it:
```csharp
public BlobServiceClient(Uri serviceUri, BlobClientOptions options = default);
```

Could you please clarify exactly what you are doing and what you want to be doing? For clarification of terminology, since at first glance this appears to be part of the issue:
- A **shared key** is the key to your storage account. Our object model pairs it with the account name.
- a **shared access signature (SAS) is a query string on the end of a url that is signed to authenticate the user without any additional mechanisms (e.g. `?se=2020-04-07T18%3A42%3A18Z&sp=rw&sv=2018-03-28&sr=b&sig=<REDACTED SIGNATURE>`).
- a **connection string** is a string of key value pairs that contains the necessary information to construct a client authenticated using a shared key (e.g. `DefaultEndpointsProtocol=https;AccountName=<ACCOUNT NAME>;AccountKey=<ACCOUNT KEY>;EndpointSuffix=core.windows.net`).

Apologies if I am misunderstanding and explaining things you already understand. I am just having trouble understanding the scenario and want to be as accurate as possible.

**Comment by seanmcc-msft** [comment]
You can also just new up a BlobClient with ```BlobClient blob = new BlobClient(new Uri([sas url string]));```

**Comment by jaschrep-msft** [comment]
That particular code path in our legacy SDK assumed defaults about your URL's construction. While the docs you point out the URL to your account will "likely to be similar to `"https://{account_name}.blob.core.windows.net`," this is not true 100% of the time, depending on configurations of the account. It could have a different suffix, or it may not even have the account name in it at all (something necessary to know for shared key authentication to work).

While in many cases, including yours, the account name and key is enough to determine the endpoint, it is increasingly not the case for many others, and so the new library does not currently assume these defaults.

You are correct to point out that the connection string won't correctly be parsed by the Uri constructor. The easiest option for you is to call `public BlobServiceClient(string connectionString)` and supply the connection string from the azure portal, which does contain your shared key. You do not need to make a StorageSharedKeyCredential object when using a connection string, as the connection string already handles your credentials. If you do not wish to use a connection string, you will have to construct your Uri (likely as the docs you pointed to describe it), and supply the StorageSharedKeyCredential with your account name and key.

**Comment by CoolDadTx** [comment]
@jaschrep-msft thanks. We're not attached to the separate credential thing so we'll look at just using the connection string directly.
