### ISSUE TITLE
[FEATURE REQ] Provide access to IServiceProvider in AddAzureClients method.

### ISSUE THREAD

**Issue by TechWatching** [Azure/azure-sdk-for-net#11057]
**Library or service name.**
Microsoft.Extensions.Azure
 
**Is your feature request related to a problem? Please describe.**
There is no way in the `AddAzureClients` method to retrieve a class already registered (with the `GetService` or `GetRequiredService` methods of `IServiceProvider`). That is preventing us to retrieve a registered IOptions configuration.
In an ASP.NET Core application, we are often grouping settings in IOptions configuration classes that are registered in depencency injection. But we can't use them here and have to manually retrieve the expected settings from the Configuration object.
Moreover with Azure Functions DI, there is currently no direct access to IConfiguration in FunctionStartup class, so it's not possible to use AddAzureClients.

**What feature would you like to get added? What problem is it solving?**
`ServiceProvider` shoud be available as a property of `AzureClientFactoryBuilder` or there should be an override to `Add.AzureClients` that accept a `Action<AzureClientFactoryBuilder, IServiceProvider>`.

**Comment by pakrym** [comment]
I'm afraid that we can't provide the exact overload you've mentioned because that would mean that IServiceProvider is required to know which services would be registered that creates a circular dependency.

**Comment by TechWatching** [comment]
Hum I understand. Do you have any other idea that would solve this issue ? The other methods providing such an overload like `AddTransient` don't have this circular dependency problem ?

**Comment by pakrym** [comment]
I was thinking about something like 

```
services.AddAzureClients(builder =>

builder.AddClient<SomeClient>((options, provider) => new SomeClient(...., options));

);
```

It would work for client of any type and allow you to use service provider as part of client construction.

**Comment by AlexGhiondea** [comment]
Given that we have an acceptable workaround I'll go ahead and close this. Please reactivate if this didn't address your issue.

**Comment by TechWatching** [comment]
Hum there is no workaround @AlexGhiondea . @pakrym sample was a suggestion of overload to implement that would solve the issue.

**Comment by AlexGhiondea** [comment]
Heh -- that's right! I'll reopen this.

**Comment by felinepc** [comment]
Just encountered this issue while trying to use DI with Azure Functions. 

Because Azure clients such as storage queues are often used at the "messaging" layer that connects the frontend and backend services, it should be a very common scenario for both the frontend and backend to depend on the same configurations.

In this case, we want to follow the best practice and use the Options pattern to register the necessary settings (storage account Uris, names etc), but this does require the various `.AddClient' methods to support an `IServiceProvider` parameter, much like how configurations are done in EF Core etc.

I hope this feature request can be considered and added in the near future.

**Comment by TechWatching** [comment]
@pakrym  Awesome, in which versin of the SDK can I find this ?

**Comment by pakrym** [comment]
https://www.nuget.org/packages/Microsoft.Extensions.Azure/1.1.0-beta.3
