### ISSUE TITLE
Azure.Security.KeyVault.Secrets library support for net462 not available

### ISSUE THREAD

**Issue by bhawna2303** [Azure/azure-sdk-for-net#11067]
My project is on target Framework .NETFramework 4.6.2

I added the above library in packages.config
<package id="Azure.Security.KeyVault.Secrets" version="4.0.1" targetFramework="net462"/>

But when I see the library folder that is downloaded, I see only NetStandard2.0 folder and not net45
![image](https://user-images.githubusercontent.com/12200729/78562581-425ac200-7837-11ea-8eaa-1666a9849ee7.png)

**Environment:**
 .NETFramework 4.6.2

**Comment by AlexGhiondea** [comment]
.NET Standard 2.0 is supported (with some caveats) on versions of .NET starting [with .NET 4.6.1](https://docs.microsoft.com/en-us/dotnet/standard/net-standard#net-implementation-support).

This means that you should be able to add a reference to that package from your .NET Framework project and it will work.

Please let us know if you run into situations where something does not work.

Regardless of this, I would encourage you to consider moving to .NET Framework 4.7.2 or later.

**Comment by heaths** [comment]
Don't author a targetFramework attribute in your `<package>` reference. This should just work. Do you get an error when you try to build? We use these libraries to target 4.6.1 even for tests and they build fine.

**Comment by heaths** [comment]
Also, to update the issue with information from the internal conversation, you will only find folders in the extracted directories that the library targets. Azure.* packages only target netstandard2.0 which covers 4.6.1* and newer. What your project targets doesn't affect these directories, and you can only specify the `targetFramework` attribute in your packages.config for targets the package actually targets, but is meant for when you need to override behavior if targeting doesn't work right. Normally, you shouldn't specify this.

\* There are a few caveats since 4.6.1 isn't 100% compatible with netstandard2.0. There are a few algorithms you can't use with Azure.Security.KeyVault.Keys, for example, including any EC and a couple RSA algorithms, like RS256K.
