### ISSUE TITLE
Add test coverage for event source logging

### ISSUE THREAD

**Issue by JoshLove-msft** [Azure/azure-sdk-for-net#11220]
Track 1 has some good tests for this.

**Comment by jsquire** [comment]
If I recall, the track one tests use a diagnostics listener to hook the event source and validate.   That requires running tests serialized, because concurrent operations using the event source can taint the results and cascade failures.  I'd recommend taking a look at the approach that Event Hubs uses in the  `EventProcessorClient` and new `EventProcessor{TPartition}` which uses the approach of mocking out the event source and validating in isolation using mocks.   

This approach also gives you more flexibility for injecting into known points of background behavior (like setting a completion source when the `XXXComplete` log is written, so that you know deterministically at what point a non-public operation completes).   This comes in very handy for testing things like message pumps which are difficult to test due to non-determinism around timing.
