### ISSUE TITLE
Add back SendAsync(IEnumerable<ServiceBusMessage> messages) overload

### ISSUE THREAD

**Issue by JoshLove-msft** [Azure/azure-sdk-for-net#11250]
As per the discussions around smart send, we will support three send options:
SendAsync(ServiceBusMessage message)
SendAsync(IEnumerable<ServiceBusMessage> messages)
SendBatchAsync(ServiceBusMessageBatch batch)

**Comment by SeanFeldman** [comment]
As per the **internal** discussions? Could you please share the details?

In general, the idea of being able to send a collection of messages w/o going through the safe batching is good.

**Comment by JoshLove-msft** [comment]
Sure, there were discussions on the Event Hubs side for implementing a form of "intelligent batching" where the SDK would batch up the events automatically. A lot options were proposed but each one had significant drawbacks. The final result, which isn't totally reflected in the document I am linking (I believe there is another one coming soon that will have more of a summary), is that we will add back the Send overload that takes a collection of events/messages to make it easier for users who don't care about batching. If needed, we can also add the CreateBatches overload to make it easier to create a set of batches.

https://gist.github.com/srnagar/8616fede4d53677201e0ba50512a70f9

**Comment by SeanFeldman** [comment]
Safe batching is great when sending a large number of messages and need to be able to ensure the batch doesn't fail the size limit.

Quick batch sending is about having N number of messages that is not necessarily large, but needs to be sent out with as low setup overhead is possible. And that's where passing an `IEnumerable<ServiceBusMessage>` is handy.

That's why I'm 👍 for bringing back that overload in addition to safe batching.
