### ISSUE TITLE
[BUG] CertificateClient.StartDeleteCertificateAsync throws ArgumentNullException

### ISSUE THREAD

**Issue by shevchenkobn** [Azure/azure-sdk-for-net#11258]
**Describe the bug**
`Azure.Security.KeyVault.Certificates.CertificateClient.StartDeleteCertificateAsync` throws `ArgumentNullException` whenever certificate without soft delete is **successfully** deleted.

**Expected behavior**
No exceptions thrown.

**Actual behavior (include Exception or Stack Trace)**

Stacktrace:
```
System.ArgumentNullException: Value cannot be null.
Parameter name: uriString
   at System.Uri..ctor(String uriString)
   at Azure.Security.KeyVault.Certificates.DeleteCertificateOperation..ctor(KeyVaultPipeline pipeline, Response`1 response)
   at Azure.Security.KeyVault.Certificates.CertificateClient.StartDeleteCertificateAsync(String certificateName, CancellationToken cancellationToken)
   
```

**To Reproduce**

1. Create Azure Key Vault without soft delete enabled.
2. Create App Registration for your app and add it as Access Policy to Azure Key Vault.
3. Create C# project (I used Visual Studio 2017, .NET Core 2.2).
3.1. Ensure C# version is minimum 7.1.
3.2 Install NuGet packages:
3.2.1 Azure.Security.KeyVault.Certificates 4.0.1
3.2.2 Azure.Identity 1.1.1
4. Run snippet, similar to https://gist.github.com/shevchenkobn/32a5cfcf56d12aa06edbfa50c6dfab76

**Environment:**
 - Azure.Security.KeyVault.Certificates 4.0.1; Azure.Identity 1.1.1
 - Windows 10.0.17763 .NET Core 2.2.106
 - Visual Studio 15.9.17

**Comment by heaths** [comment]
Thank you for the report. Are you able to work around this for now? We are working toward a new preview and can include a fix there (to be released later this spring).

I also highly recommend enabling soft delete - now the default. If someone deletes a Key Vault, your secrets, keys, and certificates are gone forward unless you have other backups. Soft delete allows you to recover it.

Still, this is something we'll fix (also in Keys and Secrets, which likely have the same problem). Just wanted to recommend that.

**Comment by shevchenkobn** [comment]
Thank you for your reply.

*Workaround*
I have a workaround for now. It is included in the code gist I shared:
try-catch with a particular stack trace, very dirty hack.

*Soft delete feature*
I tried it initially, but couldn't purge the certificate even though app
registration had purge privilege. It seems only recourse group owner can
purge them, however I didn't drill into this. It is unclear whether my app
needs soft delete anyway.

**Comment by heaths** [comment]
Thanks for confirming. We'll include this in the next preview going out since a simple workaround is available.

Interesting about the purge. All our tests use that with a service principal that has all permissions, so it should work. If ever you enable it again, we'd be happy to help figure out why you couldn't. While your app may not need to delete and purge (FWIW, purge happens after a period of time automatically) itself, soft delete also enables the entire Key Vault to be recovered. For example, there was an incident some time back where a vault was deleted that did not have soft delete enabled and we had to re-create a bunch of secrets for tests. We enabled soft delete on all our Key Vaults after that.
