### ISSUE TITLE
[Design Discussion] Exposing x-ms-client-request-id in our APIs

### ISSUE THREAD

**Issue by tg-msft** [Azure/azure-sdk-for-net#11273]
We should get together and discuss a unified approach to exposing `x-ms-client-request-id`.  We've had a variety of approaches thus far:
- [Storage doesn't really expose it](https://github.com/Azure/azure-sdk-for-net/issues/10018) (and you need [hacky pipeline plugins to get around it](https://github.com/Azure/azure-sdk-for-net/issues/10056))
- Search is exposing it in our options bags (blocked on #11198 though)

**Comment by pakrym** [comment]
This is what I've experimented with https://github.com/Azure/autorest.csharp/blob/feature/v3/test/AutoRest.TestServer.Tests/lro.cs#L25

``` C#
using var _ = ClientRequestIdScope.Start("9C4D50EE-2D56-4CD3-8152-34347DC9F2B0");
var value = new Product();
var operation = await client.StartPostAsyncRetrySucceededAsync(value);
return await operation.WaitForCompletionAsync().ConfigureAwait(false);
```

while an instance returned from ClientRequestIdScope is not disposed all operations would have the specified client request id. This somewhat copies the Activity pattern but makes it way simpler. Because the method return an `IDisposable` the API change can be really tiny - adding a method on one of the existing classes like `HttpPipeline`.

**Comment by tg-msft** [comment]
The team met to discuss and think we should adopt some variant of @pakrym's prototype.

**Comment by tg-msft** [comment]
Can we move this into Azure.Core.Experimental to start playing with?

**Comment by pakrym** [comment]
Will do.
