### ISSUE TITLE
Breaking changes should be detected in Data plane API's

### ISSUE THREAD

**Issue by Petermarcu** [Azure/azure-sdk-for-net#11316]
This is a follow up from this item for the management plane.
https://github.com/Azure/azure-sdk-for-net/issues/2230

**Comment by kurtzeborn** [comment]
We already have APICompat checks running in the .NET repo today ([added in January](https://github.com/Azure/azure-sdk-for-net/pull/9568)).  We also have https://github.com/Azure/azure-sdk/issues/180 opened already tracking doing this in a more consistent way across all languages (instead of each langauge doing their own thing).
