### ISSUE TITLE
Migrating from Event Hubs library v4 to v5 ignores old checkpoints

### ISSUE THREAD

**Issue by gregmus** [Azure/azure-sdk-for-net#11367]
**Describe the bug**
New Azure.Messaging.EventHubs nuget package is using a different way of storing checkpoints in a storage account. In Microsoft.Azure.EventHubs (v4) checkpoints (offset/sequence number) were stored as blob files in JSON format. In Azure.Messaging.EventHubs (v5) checkpoints are stored as blob files metadata, and blobs are stored in a different location.

**Expected behavior**
Assuming I use the same event hub consumer group and storage account/container name, I would expect that new Event Hubs library would pick up from where the old library left, so to use old checkpoint offset/sequence number as a starting point and store them in a new way.

**Actual behavior**
After deploying the code based on new library, EventProcessorClient will start processing messages from the beginning of stream in EventHub, repeating all the messages.
It's not even mentioned in v4 -> v5 migration guide here:
https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/eventhub/Azure.Messaging.EventHubs/MigrationGuide.md

**Comment by jsquire** [comment]
Hi @gregmus.  We're sorry that you're experiencing difficulties and appreciate you reaching out to let us know.  It was an unfortunate, though intentional, decision to not support legacy checkpoint data in the new client.  In order for us to meet the goals set for unifying checkpoint data across languages for the new set of Event Hubs libraries and to make improvements to the algorithm used for managing partition ownership, breaking changes were necessary.

You're absolutely correct in that we should highlight this in the migration guide, offer guidance around how to migrate checkpoint data, and, ideally, offer a utility to assist with that migration.  To address those gaps, I've opened the following:

-  Create a utility to demonstrate migration of legacy checkpoints for use with the EventProcessorClient ([#11373](https://github.com/Azure/azure-sdk-for-net/issues/11373))
-  Update the migration guide to document that processor checkpoints from legacy versions are not applied ([#11374](https://github.com/Azure/azure-sdk-for-net/issues/11374))

**Comment by jsquire** [comment]
The best work-around in the short term would be to handle the `EventProcessorClient.PartitionInitializingAsync` event and set the `PartitionInitializingEventArgs.DefaultStartingPosition` value in the arguments received to the position that was recorded in the legacy checkpoint.  This would be necessary only for the first run, until a new checkpoint was recorded using the `EventProcessorClient` but would require reading and parsing the legacy checkpoint blob to determine the position.

**Comment by gregmus** [comment]
Hi @jsquire.
 
It's fine... of course I verified that first in development environment so it's not a big deal.
Thanks for the hint with PartitionInitializingAsync event, that simplifies a bit.
