### ISSUE TITLE
[Pending service change] Undo our own deserialization method in DataTableCell

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-for-net#11487]
When the service start sending a value for `confidence` we should undo the changes related to `DataTableCell` from this PR https://github.com/Azure/azure-sdk-for-net/pull/11481

**Comment by annelo-msft** [comment]
Let's check on whether the service team has made this fix, and if not, remove the blocking-release label and move to P5.

**Comment by maririos** [comment]
Check today and there is still no Confidence value returned. @annelo-msft  Do you know if the service confirmed that they were going to add this for GA? or should I ping them again

**Comment by maririos** [comment]
This doesn't affect our release so will remove the blocking-release tag and moving to backlog

**Comment by pallavit** [comment]
@annelo-msft , @kinelski can this be closed?

**Comment by kinelski** [comment]
This issue has not been fixed by the service yet but decided to close it for the following reasons:
- At this point it's clear a fix won't happen as only old versions of the service are affected, which makes this very low priority.
- We've been encouraging customers to move to newer service versions. As time passes, less customers will be affected by it.
- We've never received any negative feedback from customers regarding this issue.
- There's already a workaround in the SDK in place, so there's nothing more we can do on our side.
