### ISSUE TITLE
Improve documentation for ReceiveBatchAsync

### ISSUE THREAD

**Issue by JoshLove-msft** [Azure/azure-sdk-for-net#11550]
Need to emphasize that the maxMessages specified will not be guaranteed to be returned, even if there are that many messages available in the queue.

**Comment by SeanFeldman** [comment]
When the name discussion was taking place, one of the reasons I was questioning the use of "batch" is due to the fact that it has a connotation of a known size. Track1 had `ReceiveAsync(n)` that would return a collection of **up-to N items**. Aside from emphasizing that it's the best effort to bring up-to-the requested number of item, what else could improve the API documentation?

**Comment by ShivangiReja** [comment]
Closed with https://github.com/Azure/azure-sdk-for-net/pull/11719
