### ISSUE TITLE
AuthN fails trying to call ComputeManagementClient.VirtualMachines.ListAllAsync

### ISSUE THREAD

**Issue by pjirsa** [Azure/azure-sdk-for-net#1157]
Trying to call this method using a compute client that was created using token credentials from a service principal in my AAD and getting the following error. Where is client id coming from? That is not the clientID of my service principle.

An exception of type 'Hyak.Common.CloudException' occurred in mscorlib.dll but was not handled in user code

Additional information: AuthorizationFailed: The client '63df65da-6df8-43f2-b687-c4762e099d86' with object id '63df65da-6df8-43f2-b687-c4762e099d86' does not have authorization to perform action 'Microsoft.Compute/virtualMachines/read' over scope '/subscriptions/6c47cf9a-aa56-4de6-ac1f-4e89c9f50151/resourceGroups/New_Resource_Group/providers/Microsoft.Compute'.

**Comment by matt-gibbs** [comment]
Hello @pjirsa . Did you put your service principal in a role with sufficient permissions? From the message, it looks like you are getting authenticated. There are a few guids in place (AD application and service principal). The guid displayed may be for the application object instead of the service principal. If the SP has permissions already and you are seeing this, you can PM me and we can get some additional details to investigate: mattgi at microsoft dot com. Here's a PS script for creating and configuring a SP with 'owner' permissions. https://github.com/matt-gibbs/azbits/blob/master/src/New-AzureServicePrincipalOwner.ps1

**Comment by pjirsa** [comment]
Hi @matt-gibbs I discovered that I was trying to authenticate with a management certificate key instead of using client credentials and token auth.
Thanks.
