### ISSUE TITLE
Mangement plane PR triggers data-plane CI

### ISSUE THREAD

**Issue by isra-fel** [Azure/azure-sdk-for-net#11640]
## What I see

Mgmt-plane-only PR triggers data-plane CI, for example #11625 , so if there's error in data-plane, the pr is blocked (check-enforcer demands all CI to pass).

## Question

I think in general the failure of data-plane CI should not block mgmt-plane PRs, but I want to here your voice.

## Proposed solution

1. The reviewer tells check enforcer it's OK to ignore the failed data-plane checks
1. Update data-plane CI to exclude mgmt-plane projects

cc @weshaggard @mitchdenny @erich-wang @chidozieononiwu

**Comment by weshaggard** [comment]
cc @allenjzhang 

This is being triggered because we don't limit the path filtering to just the data-plane library at https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/containerregistry/ci.yml#L22. 

We have a couple options here:
1) We could update our script https://github.com/Azure/azure-sdk-for-net/blob/master/eng/scripts/Update-Mgmt-Yml.ps1 which correctly sets up the mgmt path filters to also update the path filters in the ci.yml files as well.
2) We could simply let them continue to trigger and if they are failing for other reasons ignore the failures and proceed with check-in.
3) We could work to ensure both mgmt and data-plane stay clean and always passing.

I was chatting with @allenjzhang about the track 2 mgmt libraries and for those I would like to go with option 3. However for the existing track 1 mgmt libraries perhaps we can go with option 1. It shouldn't be too hard to alter that script to adjust all these.

**Comment by jsquire** [comment]
This issue is fairly stale by now and the T1 packages are deprecated with T2 reaching GA.   I'm going to close this out and we can address any specific cases on an as-needed basis.
