### ISSUE TITLE
Use proper brand names in Search README

### ISSUE THREAD

**Issue by heaths** [Azure/azure-sdk-for-net#11749]
We need to decide on whether to use proper branding names in the Search README.

> We could probably resolve this for preview 4, but, @HeidiSteen, since "Search" is a product name shouldn't this be "Search" or even "Azure Search" (or maybe "Azure Cognitive Search") per branding guidelines (I had to do quite a bit of these changes back in the day for .NET and Visual Studio, including on my formerly popular blog - they were pretty serious).
> 
> _Originally posted by @heaths in https://github.com/Azure/azure-sdk-for-net/pull/11748_

**Comment by HeidiSteen** [comment]
The original service name was "Azure Search", but it was rebranded last October to "Azure Cognitive Search" (full).  Because the rebranding is new, I always use the full name, but I sometimes see PMs and other contributors using the short form: "Cognitive Search".  I personally think that looks too close to Cognitive Services so I don't use it.   

Lower-casing stuff:  "service" is always lower case. If you want to make a generic reference to a search service (for example, when referring to the customer's search service), lower case the "s" in "search" also.

Do:  Azure Cognitive Search, Cognitive Search, search service
Don't:  Azure Search, Search service, Search Service

**Comment by heaths** [comment]
I've verified in the places Ted changed that we do refer to a customer's search service, so closing.
