### ISSUE TITLE
[CodeGen] [FormRecognizer] Per-Sprint Code Generation

### ISSUE THREAD

**Issue by kinelski** [Azure/azure-sdk-for-net#11834]
- [ ] Trigger code generation for this sprint.

This should be done once every sprint, preferably one week before code completion date to incorporate latest updates, and to have enough time to implement necessary changes.

Once done, don't close this issue and move it to the next sprint.

**Comment by maririos** [comment]
You mean against the latest swagger?

**Comment by annelo-msft** [comment]
There are two purposes here:
1. Make sure we're up to date with the latest swagger from the service (or the latest whose feature set we support in the client library)
2. Make sure we're using code generated by the latest version of the C# generator


We should already understand features we get from the latest swagger - if not, development of those features should be handled as separate issues.

We'll need to make sure we allocate time to understand any changes that happened in the generator since the last time we generated from it.

Any changes to public APIs that we get from the generator should be reviewed with architects.

**Comment by maririos** [comment]
>Make sure we're using code generated by the latest version of the C# generator

Any time the version of code generator increases, the team makes sure to update each library with the changes. If it involves a lot of changes, they create an issue in our repo. We could link the issues they create in this issue, or just marked them as blocked-release so we know we have to address them before releasing

**Comment by annelo-msft** [comment]
@pakrym, can we rely on the code-gen team to keep the the generated code up to date for all .NET libraries?
