### ISSUE TITLE
[FEATURE REQ] - Azure Key Vault Configuration Provider doesn't support complex configuration types

### ISSUE THREAD

**Issue by MikeBecatti** [Azure/azure-sdk-for-net#11943]
**Library or service name.**
What library or service is this request related to? [e.g. Azure.Storage.Blobs] 
Microsoft.Extensions.Configuration.AzureKeyVault/Azure.Extensions.Configuration.Secrets
 
**Is your feature request related to a problem? Please describe.**
This issue was originally filed here (https://github.com/dotnet/extensions/issues/1522) but we were asked to move it to this repo instead.

We recently migrated our secret configuration from appsettings.json to Azure Key Vault. When using appsettings.json we always used complex strongly typed configuration classes such as ExternalAPIConfig where in appsettings.json this looked like the following:

"ExternalAPIConfig : { "APIUrl" : "https://myapiurl", "APIKey" : "myapikey" }

Then in startup.cs we would make GetSection and Bind calls like this:

ExternalAPIConfig apiConfig = new ExternalAPIConfig(); Configuration.GetSection("ExternalAPIConfig").Bind(apiConfig);

or register a service configuration like this:

services.Configure<ExternalAPI>(Configuration.GetSection("ExteranlAPIConfig"));

or grab a connection string like this:

var connectionString = Configuration.GetConnectionString("ConnectionStringName");

This always worked perfectly and was very clean. After switching over to using Azure Key Vault we are finding that local dev secrets stored in secrets.json work identically to the way that they do when being consumed from appsettings.json, so what is above works perfectly (I assume b/c both use the underlying json configuration file provider).

However when we consume the same secret value from Key Vault (we are pasting the body of the setting from appsettings.json into the value for the secret in key vault so our secret values are json) using the Azure Key Vault Configuration Provider it appears that the kv provider treats the values of secrets as strings and does not recognize them as json objects so the only way to get at the value is with the .Value property of the ConfigurationSection as a string.

So when deployed to staging or prod where the values are actually pulled from key vault we can no longer use GetSection or GetConnectionString as shown above and instead we have to do something like this:

services.Configure<ExteranlAPIConfig>(options => { var config = JsonConvert.DeserializeObject<ExternalAPIConfig>(Configuration.GetSection("ExteranlAPIConfig").Value); options.APIUrl= config.APIUrl; options.APIKey= config.APIKey; });

or

Dictionary<string, string> connectionStrings = JsonConvert.DeserializeObject<Dictionary<string, string>>(Configuration.GetSection("ConnectionStrings").Value);

So now I have to introduce environment specific code all over startup.cs just b/c my configuration source is different. It seems like I should be able to use these functions the same way whether I am using the json provider or the key vault provider. This feels very unnatural and results in different code depending on which provider we are using which seems to kind of defeat the purpose of the provider abstraction. Hoping we are missing something obvious here or just doing something plain wrong and would be happy to learn that is the case. What I have outlined above works but is that really the best approach?

**Comment by JoshLove-msft** [comment]
@MikeBecatti, thank you for bringing this issue to our attention. There is indeed a way to get this working without having to make the changes you mentioned to your Startup.cs file. KeyVault uses a separate [configuration provider](https://docs.microsoft.com/en-us/aspnet/core/security/key-vault-configuration?view=aspnetcore-3.1) than what is used when working directly with appsettings.json. Because of this, there is a different format for specifying hierarchical values. Here is an [example ](https://docs.microsoft.com/en-us/aspnet/core/security/key-vault-configuration?view=aspnetcore-3.1#bind-an-array-to-a-class )that shows how to migrate from json to KV format:
```
"Serilog": {
  "WriteTo": [
    {
      "Name": "AzureTableStorage",
      "Args": {
        "storageTableName": "logs",
        "connectionString": "DefaultEnd...ountKey=Eby8...GMGw=="
      }
    },
    {
      "Name": "AzureDocumentDB",
      "Args": {
        "endpointUrl": "https://contoso.documents.azure.com:443",
        "authorizationKey": "Eby8...GMGw=="
      }
    }
  ]
}
```

Key | Value
-- | --
Serilog--WriteTo--0--Name | AzureTableStorage
Serilog--WriteTo--0--Args--storageTableName | logs
Serilog--WriteTo--0--Args--connectionString | DefaultEnd...ountKey=Eby8...GMGw==
Serilog--WriteTo--1--Name | AzureDocumentDB
Serilog--WriteTo--1--Args--endpointUrl | https://contoso.documents.azure.com:443
Serilog--WriteTo--1--Args--authorizationKey | Eby8...GMGw==

In terms of actually storing the secrets in key vault, you can use the [Azure CLI](https://docs.microsoft.com/en-us/cli/azure/keyvault/secret?view=azure-cli-latest#az-keyvault-secret-set) or manually create the secrets from the portal. 

So to boil it down, instead of having one secret that is in json format, you would create separate secrets using the double dash notation to represent the hierarchy. At that point, your Startup code should work the same when consuming from KeyVault or using appsettings.json.

**Comment by MikeBecatti** [comment]
Thank you for your response.  The possibility of using "double dash" notation is mentioned in the original issue that I referenced.  However, since we can specify 'json' as the content type for a Key Vault secret I'd like to ask that an enhancement be made to support pulling hierarchical values out of a single key vault secret.

**Comment by JoshLove-msft** [comment]
One issue to contend with is that this would be a breaking change for customers whose code is currently written to get back the json as a string. We could consider introducing a new content type such as `application/json;configuration`, which should make the possibility of breaking anyone extremely remote. Adding this to our backlog. 

Thanks again for the suggestion @MikeBecatti!

**Comment by dnrbeiro** [comment]
> @MikeBecatti, thank you for bringing this issue to our attention. There is indeed a way to get this working without having to make the changes you mentioned to your Startup.cs file. KeyVault uses a separate [configuration provider](https://docs.microsoft.com/en-us/aspnet/core/security/key-vault-configuration?view=aspnetcore-3.1) than what is used when working directly with appsettings.json. Because of this, there is a different format for specifying hierarchical values. Here is an [example ](https://docs.microsoft.com/en-us/aspnet/core/security/key-vault-configuration?view=aspnetcore-3.1#bind-an-array-to-a-class)that shows how to migrate from json to KV format:
> 
> ```
> "Serilog": {
>   "WriteTo": [
>     {
>       "Name": "AzureTableStorage",
>       "Args": {
>         "storageTableName": "logs",
>         "connectionString": "DefaultEnd...ountKey=Eby8...GMGw=="
>       }
>     },
>     {
>       "Name": "AzureDocumentDB",
>       "Args": {
>         "endpointUrl": "https://contoso.documents.azure.com:443",
>         "authorizationKey": "Eby8...GMGw=="
>       }
>     }
>   ]
> }
> ```
> 
> Key	Value
> Serilog--WriteTo--0--Name	AzureTableStorage
> Serilog--WriteTo--0--Args--storageTableName	logs
> Serilog--WriteTo--0--Args--connectionString	DefaultEnd...ountKey=Eby8...GMGw==
> Serilog--WriteTo--1--Name	AzureDocumentDB
> Serilog--WriteTo--1--Args--endpointUrl	https://contoso.documents.azure.com:443
> Serilog--WriteTo--1--Args--authorizationKey	Eby8...GMGw==
> In terms of actually storing the secrets in key vault, you can use the [Azure CLI](https://docs.microsoft.com/en-us/cli/azure/keyvault/secret?view=azure-cli-latest#az-keyvault-secret-set) or manually create the secrets from the portal.
> 
> So to boil it down, instead of having one secret that is in json format, you would create separate secrets using the double dash notation to represent the hierarchy. At that point, your Startup code should work the same when consuming from KeyVault or using appsettings.json.

This is great stuff, but is there any way instead of storing secrets with the index of the array, to have a more powerful way that allows us to store it by telling the value of a property, so the position of the item itself inside the array is not relevant?

Based on the example above, a couple of suggestions:
SeriLog--WriteTo-Name:AzureTableStorage--Args--connectionString, instead of Serilog--WriteTo--0--Args--connectionString
SeriLog--WriteTo-AzureDocumentDB--Args--authorizationKey instead of Serilog--WriteTo--1--Args--authorizationKey

The syntax is just a suggestion, but something that allowed a more robust way. In my experience, using an index of an array soon or later some side effect will happen and you won't know what is causing it at least in a reasonable amount of time...

**Comment by pakrym** [comment]
You can now implement this using a custom secret manager. See https://github.com/Azure/azure-sdk-for-net/pull/19788/files#diff-758e6ae3230293156dca90f33005ebb13d24a67f15076676b8661d87844e1e92R665-R682 for an example
