### ISSUE TITLE
Add shared file logger implementation to the test framework

### ISSUE THREAD

**Issue by pakrym** [Azure/azure-sdk-for-net#11981]
We need a common logger implementation that would always log requests/responses into files that would be added as an artifact.

There should be one file per test invocation with the path something like:

`Azure.Core/HttpClientTransportTests/SomeTestNameAsync.txt`

This would allow us to get rid of multiple test logger implementations and always have some logs when a test unexpectedly fails without requiring someone to instrument the code.

cc @heaths @JoshLove-msft

**Comment by heaths** [comment]
Why log to a file and explicitly attach a file when logging to stdout gets attached like a file automatically? That's built-in behavior of the test runner and what I've been seeing in bit only this repo but many others.

**Comment by pakrym** [comment]
Test runner has problems with storing logs when the test crashes as @jsquire had found out. 

It's also a lot of logs that would create a ton of noise in pipeline build logs.

**Comment by JoshLove-msft** [comment]
In Storage, the output is logged using NUnit TestContext.Out, but only for failed tests:
https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/storage/Azure.Storage.Common/tests/Shared/TestEventListener.cs#L48

The downside here is that tests that time out based on NUnit Timeout attribute will not be included.

**Comment by heaths** [comment]
Why would you read the pipeline logs when the Test tab is so much easier to use (read, filter, analyze historical tends, etc)? We could use the TestContext instead as Josh suggests. Either way, I want to see not only successful logs (to find issues with potentially shared resources, where one or more tests fail because of the first one that succeeded) but the kids attached to the actual tests - not having to correlate separate like files of only attached to the test run.

There are ways in either case to make sure logs are attached even if a test throws using nunit (xunit does too).

**Comment by pakrym** [comment]
We can try but from my experience it makes things too noisy.

**Comment by JoshLove-msft** [comment]
> We can try but from my experience it makes things too noisy.
> 
> > We could use the TestContext instead as Josh suggests.
> 
> It doesn't help with crashed or hanging tests and that's the ones you want logging the most.

It not working with crashed or hanging tests is probably related to how it is implemented in Storage. We only output the logs in the tests [TearDown] method. I assume TestContext would work if you just logged the requests as they occurred.

**Comment by pakrym** [comment]
> It not working with crashed or hanging tests is probably related to how it is implemented in Storage. We only output the logs in the tests [TearDown] method, and only if the test failed. I assume TestContext would work if you just logged the requests as they occurred.


Not really, some test failures cause the entire process to crash (Debug.Assert would do it) so test framework doesn't even get time to forward the TestContext to the right place.

**Comment by JoshLove-msft** [comment]
So it is true that Debug.Assert(false) would cause the Test to not be marked as Passed or Failed, but the output is still there:

```
        [Test]
        public void DebugAssert()
        {
            TestContext.Progress.WriteLine("event output");
            Debug.Assert(false);
        }
```
```
event output
The active test run was aborted. Reason: Test host process crashed : Assertion Failed
   at Azure.Messaging.ServiceBus.Tests.Processor.SessionProcessorTests.DebugAssert() in C:\Users\jolov\source\repos\Azure\azure-sdk-for-net\sdk\servicebus\Azure.Messaging.ServiceBus\tests\Processor\SessionProcessorTests.cs:line 35
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at NUnit.Framework.Internal.Reflect.InvokeMethod(MethodInfo method, Object fixture, Object[] args) in D:\a\1\s\src\NUnitFramework\framework\Internal\Reflect.cs:line 266
   at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context) in D:\a\1\s\src\NUnitFramework\framework\Internal\Commands\TestMethodCommand.cs:line 64
   at NUnit.Framework.Internal.Commands.TimeoutCommand.<>c__DisplayClass2_0.<Execute>b__0() in D:\a\1\s\src\NUnitFramework\framework\Internal\Commands\TimeoutCommand.cs:line 102
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```

**Comment by pakrym** [comment]
Good point but `TestContext.Progress` is not associated with a test, the `TestContext.Out` should be used to get output associated with a test instance.

And `TestContext.Out` is susceptible to not logging crashed test output.

```
Out
Gets a TextWriter used for sending output to the current test result.

Error
Gets a TextWriter used for sending error output intended for immediate display.

Progress
Gets a TextWriter used for sending normal (non-error) output intended for immediate display.
```

**Comment by JoshLove-msft** [comment]
Yep, you're right. When switching to use TestContext.Out, the output from the test is not included. But then again, if the test has a Debug.Assert in it that fails, the test won't show as failing anyway so there would be no way to include any output associated with the test instance. We could always do both, so that we get the test output included with the test instance for normal failures, but have the Progress (and include the test name in the output) as a fallback for cases where the test hangs or crashes.

**Comment by pakrym** [comment]
But always writing to Progress would make the output incredibly noisy.

**Comment by heaths** [comment]
If we write to a file, can we still *try* to attach the file to individual tests, and maybe package them all up at the end as an artifact? That way, we get the best of both worlds: test output would be attached to their respective tests, but if they crash (I haven't had this happen in a while, but I know it can sometimes) we have all the files - even if incomplete - attached to the test run.

**Comment by pakrym** [comment]
We'll need to experiment to see how to make it the easies to consume from devops.

**Comment by jsquire** [comment]
To add some context around the scenario that Pavel mentioned:

As I understand it, the way that NUnit collects log information set via `TestContext` or `sdtout`, it builds it into a cache that it only flushes once all tests in a fixture complete.  The stated reason for this is to ensure that there is locality of information for tests when running in parallel, so that the output is more relevant and easier to parse.  This runs into issues if you have a test that hangs, since the pipeline terminates the process and all cached test logging output is lost.  Because there may be tests from multiple fixtures running in parallel, it can be very difficult to understand what tests have run and which tests were completed.  The caching is applied to Setup/Teardown as well.   To Josh's point `Progress` is not cached until the fixture completes, but does interleave tests (not an issue if you're only trying to log completion) and still performs some kind of interval flushing;  it was a bit more helpful but still gave me inconsistent output depending on timing. While there is a `Timeout` attribute intended to kill tests that take longer than some interval to complete, it modifies the `TestContext` and does some things with the thread pool that can weaken guarantees and cause issues - such as tests marked `[NonParallelizable]` running at the same time as tests tagged with `[Timeout]`.   Or, at least that has been my experience.  

Thankfully, the `dotnet test` command will log completed tests to the console as they run if the verbosity flag is set to normal or higher.  This is now the default for CI and nightly runs, but I think this suggestion by Pavel is great; Having a common logging solution in place when you need to instrument and troubleshoot would be incredibly helpful, in my opinion.

**Comment by JoshLove-msft** [comment]
I can look into this one this week.

**Comment by pakrym** [comment]
We can start with an implementation that only logs to TestContext.Out for now and expand on it later.

**Comment by JoshLove-msft** [comment]
This is essentially what Storage is doing - log to TestContext.Out for failed tests.

**Comment by heaths** [comment]
Yes, and Search too, but please log it for successful tests as well. Often, that's necessary for race conditions (well, not really in our tests since we rarely run parallel because of live testing/recording) or shared resource issues. That's exactly the problem I faced with Key Vault (I turned on logging for all tests), and now for Search.

Frankly, though, I don't see the problem with writing to stdout (or `Progress`) and the impact in test logging. Trying to find the failed test in the logs and why is more difficult than just reviewing the **Test** tab in Azure Pipelines. I would rather have complete information and verbose logs, that missing information I on which I can't take action (which has been the problem).

**Comment by pakrym** [comment]
What we have (nunit logging) seems to be enough to diagnose failures.
