### ISSUE TITLE
[FEATURE REQ] Storage Migration Guide

### ISSUE THREAD

**Issue by jongio** [Azure/azure-sdk-for-net#12106]
Sean Feldman requested a storage migration guide for .NET

https://twitter.com/sfeldman/status/1260424765984120833

Here's the Java equiv: https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/storage/azure-storage-blob/migrationGuides/V10_V12.md

**Comment by SeanFeldman** [comment]
Thank you @jongio for raising the issue.

With the new major there are quite a few changes and it would be good to have a migration guide to demonstrate the differences. This is also handy to quickly discover and map the concepts from the old SDK to the new SDK. Especially when certain types are either replaced with new ones or don't have an equivalent.

**Comment by amishra-dev** [comment]
@rishabpoh fyi

**Comment by SeanFeldman** [comment]
@jsquire, given the work on the migration guide is taking place, is it truly a backlog item?

**Comment by jsquire** [comment]
Only insofar as anything that is classified as a `Feature Request` is required to have a milestone and epic assigned in order to pass issue validation.  The team responsible for the issue should assign to the correct milestone and epic as part of beginning work.

**Comment by Tapanila** [comment]
Any timeline for this?

Currently it’s hard to do more advanced scenarios with new sdk since you can’t figure out how to change the blog examples to work with new versions. Later on this will not be a problem when there is enough samples with new SDK but currently this would be amazing.

Also I have seen some issues about dropping certain features from new SDK and if I can’t find a document that lists all of them I’m not very confident on switching to new SDK.

just a statement that everything which was supported previously is also supported on a new version would go for a long way or a list of known issues.

**Comment by SeanFeldman** [comment]
@rishabpoh FYI https://github.com/Azure/azure-sdk-for-net/issues/12106#issuecomment-651267807

**Comment by rishabpoh** [comment]
Hey everyone, happy to say we have a PR out for the Azure Storage .NET Blob migration guide (https://github.com/Azure/azure-sdk-for-net/pull/13159). You will notice that some sections say TODO, this is pending work that the engineering team will be helping me with. We wanted to get this out as soon as possible in order to cover some of the basic aspects and scenarios of the migration. We will iteratively improve this document over time and welcome feedback.

**Comment by jongio** [comment]
I don't think this issue should be closed given the PR referenced.  It would be prudent to close this issue when the Migration guide is complete, not when partially done.  I appreciate the start, but work still needs to be done to consider this closed.  Thanks

**Comment by vit-svoboda** [comment]
Well, the migration guide seems to have been merged and finished meanwhile, see [the markdown file](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/storage/Azure.Storage.Blobs/AzureStorageNetMigrationV12.md).

**Comment by amnguye** [comment]
See PR https://github.com/Azure/azure-sdk-for-net/pull/15749 for the merged Migration Guide. We even had an update https://github.com/Azure/azure-sdk-for-net/pull/16295. Please open a new issue if there are any new requests to add to the migration guide or if there's any problems with the migration guide. Thanks.
