### ISSUE TITLE
EventProcessorClient seems to end up lagging behind

### ISSUE THREAD

**Issue by mrblonde91** [Azure/azure-sdk-for-net#12180]
**Query/Question**
So up until now I was using the older of the events processor, I upgrade to the latest which doesn't have the option of setting batch sizes. So I copied the batching logic from the examples. The issue that occurs is that my batch always seems to fall behind in terms of processing events. 

So I've got around 6000 messages per second, previously I was using a batch size of around 800 and that seemed to comfortably work with the old library. Is there a specific approach you'd recommend with EventProcessorClient for batching large numbers of events?

**Environment:**
 - Azure.Messaging.EventHubs.Processor 5.1.0

 - Dotnet Core 3.1

**Comment by jsquire** [comment]
Hi @mrblonde91.   We're sorry to hear that you're having difficulties and appreciate you reaching out to let us know.   I'm happy to try and help as I'm able; I'll offer a couple of initial thoughts, but we'll probably need to dig a bit more into the specifics of your scenario  to figure out the best way forward.

Generally speaking, the best approach to scaling the `EventProcessorClient` is to add more instances to distribute the load.  That said, once you've got a 1:1 ratio between processors and partitions or are running into quota issues, that option is no longer going to offer benefits.  

The `EventProcessorClient` was designed to provide a familiar API to that of the `EventHubConsumerClient` and offer an intuitive "step-up" experience for developers exploring Event Hubs as they move into production scenarios.  The reason that the batch size doesn't appear for the `EventProcessorClient` is because it is streaming events one-by-one from the local cache and the batch size is used only to grab a handful from that cache to be emitted, which allows the cache to be refilled from the service.  For a large portion of our library users, that covers their needs well. 

In this case, it is certainly possible that you may be processing events quickly enough that the cache is starved.  It's also possible that being able to adjust the `PrefetchCount` and size of the batch used for local buffering would help achieve your goals; that is something that we're considering and definitely open to  feedback on.

There's a point, however, where an application requires native batching and greater control to handle higher throughput or specialized needs - that's where the `EventProcessor<TPartition>` is intended to help.  The `EventProcessor<TPartition>` fills a similar role as the `EventProcessorClient`, with cooperative load balancing and resiliency as its core features but offers native batch processing, extension points for using different storage providers, and a lighter, less opinionated API.   The caveat is that this comes in the form of an abstract base, which needs to be extended for use.  More on the design and philosophy behind this can be found [[here]](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/eventhub/Azure.Messaging.EventHubs/design/event-processor%7BT%7D-proposal.md).

If I may ask, there are a few things that it would be helpful to know:

- How many partitions are in the Event Hub being processed?
- How many `EventProcessorClient` instances are sharing the processing?
- What's the average size of the body of an event flowing through your system?
- In your `ProcessEvent` handler, are you taking any action other than buffering to build a batch?
- Are you seeing the `ProcessEvent` handler tick at regular intervals, or are you seeing it fire normally and then stop for a period of time, and then fire again?
