### ISSUE TITLE
Verify docs.microsoft.com docs for Azure.Core are generated successfully

### ISSUE THREAD

**Issue by pakrym** [Azure/azure-sdk-for-net#12221]
Recently we've added ability to inject snippets into XML doc comments we need to verify that the format is right, pipeline is able to handle it and result looks good.

**Comment by scbedd** [comment]
[Documentation](https://review.docs.microsoft.com/en-us/help/onboard/dotnet-requirements?branch=master#dlls-and-xml) seems to claim that it's supported. 

Working through DLL/commentXML Sourced pipeline [here.](https://apidrop.visualstudio.com/Content%20CI/_build/results?buildId=140473&view=logs&j=fd490c07-0b22-5182-fac9-6d67fe1e939b&t=ce91d5d6-0c55-50f5-8ab9-6695c03ab102)

**Comment by scbedd** [comment]
Reached out to Tianqi last night about the [generated bits](https://github.com/dotnet/dotnet-api-docs/tree/scbedd/core-test/xml) I'm seeing. 

Another user is seeing the methodology [successfully work](https://review.docs.microsoft.com/en-us/dotnet/api/azure.digitaltwins.core.digitaltwinsclient.queryasync?view=digitaltwin-preview&branch=smoke-test), but there is an additional issue that crops up from it. That issue is filed [here](https://ceapex.visualstudio.com/Engineering/_queries/edit/227459/?triage=true) and will be triaged with Robert Outlaw tomorrow AM.

**Comment by scbedd** [comment]
Had a chat with Robert this morning. comment XMLs are **absolutely supported. Currently attempting to get access to docs that list out the recipe for what SHOULD be happening.

**Comment by scbedd** [comment]
[Generates Successfully](https://review.docs.microsoft.com/en-us/dotnet/api/azure.asyncpageable-1?branch=scbedd%2Fcore-test)

Barring the [issue](https://ceapex.visualstudio.com/Engineering/_workitems/edit/227459). Robert doesn't think the value within the <code> declaration should actually affect this.

**Comment by scbedd** [comment]
Closing this item. We have an example + an issue filed for follow-up.

**Comment by pakrym** [comment]
Is excessive indentation covered by that issue? 

![image](https://user-images.githubusercontent.com/1697911/83424741-b05bd980-a3e1-11ea-8b76-72df5af9a51d.png)

**Comment by scbedd** [comment]
I don't think so. 

1. I filed a new issue [here](https://ceapex.visualstudio.com/Engineering/_workitems/edit/230024) will discuss with Robert tomorrow AM
2. The original item I link above hasn't been triaged, though I did discuss it with Robert/get it it verbally acked as a bug. I will follow up on that.

Just be aware that the indentation issue is probably going to end up triaged super low on their backlog.
