### ISSUE TITLE
[QUERY] Can you show a sample connecting to blob storage with RBAC and certificate?

### ISSUE THREAD

**Issue by gjmoyer** [Azure/azure-sdk-for-net#12257]
**Query/Question**
With Microsoft.Azure.EventHubs namespace, there is an EventHubClient.CreateWithTokenProvider method for instantiating the client with TokenProvider.  I am using this successfully in production to connect from on premises to Azure Event Hub with role based security.  Now I wish to do the same with storage, and to my surprise there is no BlobClient.CreateWithTokenProvider so that I can have the same code to also work with storage.  When I look at your examples it shows the new BlobServiceClient with the TokenCredential using application secret.  What am I missing?  Why does BlobClient work diffferently than the EventHubClient?

private static void GetEventHubClient()
{
  X509Certificate2 certificate = CertificateHelper.GetCertificate();

  tp = TokenProvider.CreateAzureActiveDirectoryTokenProvider(
    async (audience, authority, state) =>
  {
  IConfidentialClientApplication app = ConfidentialClientApplicationBuilder.Create(CertificateHelper.ClientId)
    .WithAuthority(authority)
    .WithCertificate(certificate)
    .Build();

  var authResult = await app.AcquireTokenForClient(new string[] { $"{audience}/.default" }).ExecuteAsync();
  return authResult.AccessToken;
  },
  $"https://login.microsoftonline.com/{ActiveDirectoryTenantId}");

  ehClient = EventHubClient.CreateWithTokenProvider(new Uri($"sb://{EventHubNamespace}/"), EventHubName, tp);
}

**Environment:**
Include="Microsoft.Azure.EventHubs" Version="4.2.0"
Include="Azure.Storage.Blobs" Version="12.4.2"
Include="Azure.Identity" Version="1.1.1"
Include="Microsoft.Azure.Services.AppAuthentication" Version="1.5.0"
Include="Microsoft.Identity.Client" Version="4.14.0"

Windows 10 1909, netcoreapp3.1.202
Visual Studio 16.5.5

**Comment by jsquire** [comment]
Hi @gjmoyer.  We're sorry that you're experiencing difficulties and appreciate you brining it to our attention.  If I understand correctly, you're using the legacy Event Hubs package (`Microsoft.Azure.EventHubs`) and the current Storage package (`Azure.Storage.Blobs`).   Because those packages are from different generations of the SDK, they use a different means of authentication.

The current version of the SDKs are built around a common story for authentication, using the [`Azure.Identity`](https://www.nuget.org/packages/Azure.Identity) library.  The current version of the Event Hubs library is in the package [`Azure.Messaging.EventHubs`](https://www.nuget.org/packages/Azure.Messaging.EventHubs) and would offer a consistent API for authorization when compared to the Storage library that you're using.  

A general example of certificate-based authentication with `Azure.Identity` can be found in this [[example]](https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/identity/Azure.Identity#authenticating-a-service-principal-with-a-certificate), though that does not explicitly demonstrate Storage.  I've looped in the folks responsible for the Storage client, who would be better able to offer guidance for your specific scenario.

**Comment by gjmoyer** [comment]
Hi @jsquire and thank you for the prompt response.  I didn't realize that was I using the legacy Event Hubs package, and comparing to the new generation storage SDK.  Thank you for the link, that is what I was looking for.  Appreciate your time!  I look forward to all Azure services supporting role based authentication (especially function triggers).
