### ISSUE TITLE
[QUERY] Storage: DeleteIfExistsAsync behavior

### ISSUE THREAD

**Issue by EasySlepian** [Azure/azure-sdk-for-net#12503]
**Describe the bug**
BlobContainerClient.DeleteIfExistsAsync returns true- result whether the target container existed or not.

**Expected behavior**
Returns true- value when the target container existed and has been deleted
Returns false- value when the target container does not exist and thus is not deleted

**Actual behavior (include Exception or Stack Trace)**
Returns true- value always

**To Reproduce**
Invoke BlobContainerClient.DeleteIfExistsAsync method against existing and not existing containers.

**Comment by seanmcc-msft** [comment]
Hi @EasySlepian, the reason you are seeing this behavior is because it takes some time (~30 seconds-1 minute) for a container to be deleted.  The Rest API returns the same response for calling Delete on a Container that exists and one that is being deleted, so we match this behavior in the SDK.

If you wait a bit before calling `DeleteIfNotExists()` again, it should return false.
