### ISSUE TITLE
[FEATURE REQ] Run Cosmos .NET v4 Library Tests against Cosmos Emulator

### ISSUE THREAD

**Issue by jongio** [Azure/azure-sdk-for-net#12514]
When we bring Cosmos to the mono-repo and our CI, let's make sure the tests are run against the cosmos emulator, which is currently in place for Java, JS, and Python.

azsdke2e

**Comment by MehaKaushik** [comment]
Hey @jongio we are the CosmosDB Resource Provider team, I am not very clear on your ask here. 
Can you please elaborate.

**Comment by jongio** [comment]
@danieljurek - Has this running for all other langs in our CI.  I believe Daniel is going to take this task when we move Cosmos .NET to the mono-repo.

**Comment by danieljurek** [comment]
I think this work item relates to work on the Cosmos client SDKs (as opposed to management SDKs). We have the ability to run the test suite against a locally deployed instance of the Cosmos DB emulator with other languages.

**Comment by MehaKaushik** [comment]
@danieljurek this repo doesnt contain the client SDK, I believe this issue should not be in this repo.

**Comment by jongio** [comment]
The idea with this issue is to ensure that when the cosmos sdk data plane sdk moves to this repo that we have an issue to make sure it is wired up to cosmos emulator in tests

**Comment by WestDiscGolf** [comment]
Hi, Just curious as to see if there is any update on when the Cosmos SDK package will be brought in to the repo and the Azure.Cosmos package be the "latest" to use? I've tried to find more information but the preview v4 package on nuget was last updated in Jan 2020 and the project link takes me to the v3 package repo. I've looked in the links provided here - https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md#nuget-package-dev-feed - but only the management package is listed. Sorry if I've missed something somewhere. Thanks!

**Comment by danielmarbach** [comment]
FYI this is my research so far

- It looks like the development on the [v4 branch](https://github.com/Azure/azure-cosmos-dotnet-v3/tree/v4) has stalled since November 2021
- [There was no update after the preview 3 on Nuget](https://www.nuget.org/packages/Azure.Cosmos/4.0.0-preview3)
- [Quickstart: Azure Cosmos DB SQL API client library for .NET](https://learn.microsoft.com/en-us/azure/cosmos-db/sql/quickstart-dotnet) no longer mentions the preview. The [initial commit](https://github.com/MicrosoftDocs/azure-docs/commit/8b1e63e0c56122649ecee347c2e4a53eb8b5dfea#diff-516dd001236cc4ce404f6505113d79537c39744e5b12f04f59b375eae563b395R100) is entirely built around the ` Microsoft.Azure.Cosmos` package and has [deleted the previous v4 preview page](https://github.com/MicrosoftDocs/azure-docs/commit/8b1e63e0c56122649ecee347c2e4a53eb8b5dfea#diff-601cc37bcae33d061897cd7c4ca2aa7adb307a673b39f254f724611f15a1a3b6) (see [original issue](https://github.com/MicrosoftDocs/azure-docs/issues/73357) that mentioned the sample should be marked as preview)
- The [v4 issue in the Azure SDK repo](https://github.com/Azure/azure-sdk-for-net/issues/12514#issuecomment-867415017) has remained unanswered
- [Difference Between Azure.Cosmos 4.0.0 preview and Microsoft.Azure.Cosmos v3 SDK](https://github.com/Azure/azure-cosmos-dotnet-v3/issues/2316) has been closed and not updated since

Based on the public traces I could find, my observations would lead towards thinking the efforts have been abandoned.

**Comment by jsquire** [comment]
As there are no current plans for moving Cosmos to this repository, I'm going to close this out.
