### ISSUE TITLE
[QUERY] Unable to connect to EventHub using Managed Identity

### ISSUE THREAD

**Issue by ctrlaltdan** [Azure/azure-sdk-for-net#12657]
The `Microsoft.Azure.EventHubs` (old) package accepts the connection string `Endpoint=sb://mynamespace.servicebus.windows.net/;Authentication=Managed Identity` whereas the `Azure.Messaging.EventHubs` (recommended) package seems to not support this feature.

`Azure.Messaging.EventHubs` returns the error:

> The connection string used for an Event Hub client must specify the Event Hubs namespace host, and a Shared Access Signature (both the name and value) to be valid. The path to an Event Hub must be included in the connection string or specified separately. (Parameter 'connectionString')

We can see the error being raised when parsing the connection string here:

https://github.com/Azure/azure-sdk-for-net/blob/379d3fc75376cea465e6cb8bc83c29ea32136d8b/sdk/eventhub/Azure.Messaging.EventHubs/src/EventHubConnection.cs#L504-L507

Is it the case that Microsoft recommends using the older package to use Managed Identity security?

**Comment by drdamour** [comment]
@jsquire this is an issue because of things like azure functions event hub extensions which only let you define the connection string , as they generate the client for you

**Comment by jsquire** [comment]
Hi @drdamour.  Thank you for your feedback.  Azure Function bindings are a separate product that are responsible for their own approach for supporting RBAC integration within the host context.

Currently, the Event Hubs bindings make use of the legacy client which has chosen to take a dependency on the legacy authentication libraries and extend the connection string grammar.   The workstream to update these bindings to the current generation of Event Hubs library can be found [here](https://github.com/Azure/azure-sdk-for-net/issues/15173), and would be the recommended issue to discuss the planned approach for supporting identity-based authorization.

**Comment by AAATechGuy** [comment]
It was way better if connection string supported ManagedIdentity. This removes the hazzle of writing another set of if/else to initialize the client.

**Comment by Swing0601** [comment]
I got the same error message, and looked into the source code, finally figured it out. Hope it will be helpful.

here is the source code, there is condition whether get the connection with Identity or Shared Access
https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/eventhub/Microsoft.Azure.WebJobs.Extensions.EventHubs/src/Config/EventHubClientFactory.cs
![image](https://user-images.githubusercontent.com/20235713/149273362-9a73ad5f-a733-4921-875b-33db2995257c.png)


Identity-based connections require "<CONNECTION_NAME_PREFIX>__fullyQualifiedNamespace" property. 
https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-event-hubs-trigger?tabs=csharp#identity-based-connections


My issue is caused by CONNECTION_NAME_PREFIX is not correct, the format is AzureWebJobs + connectionName, here is an example, CONNECTION_NAME_PREFIX is "AzureWebJobsmyEventHubConnectionString", then "<CONNECTION_NAME_PREFIX>__fullyQualifiedNamespace" value is "AzureWebJobsmyEventHubConnectionString___fullyQualifiedNamespace"

function.json:
![image](https://user-images.githubusercontent.com/20235713/149271683-15fff968-f407-41b4-8159-ade541b6b6f7.png)

BTW, my develop language is Python, 

CONNECTION_NAME_PREFIX source code:
https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/extensions/Microsoft.Azure.WebJobs.Extensions.Clients/src/Shared/WebJobsConfigurationExtensions.cs
 
![image](https://user-images.githubusercontent.com/20235713/149272768-556987ca-7602-4c7e-ad46-9477268c3f97.png)

Good Luck!!!
