### ISSUE TITLE
Azure Blob Storage: BlobClient name causing issues when generating SAS token

### ISSUE THREAD

**Issue by Smurfa** [Azure/azure-sdk-for-net#12738]
Trying to generate SAS tokens for blobs that are stored in Azure Blob Storage, using the Azure.Storage.Blobs.BlobClient and Azure.Storage.Sas.BlobSasBuilder. Provided the BlobClient's Name property to BlobSasBuilder's BlobName property. This only works as long as there is no character that will be URL-encoded in the blob name, e.g. a blankspace.

I would expect the BlobClient.Name to return the blob name without any encoding. 

Using BlobClient.Name for the SAS-token will generate a URI that is invalid if used.
```xml
<Error>
  <Code>AuthenticationFailed</Code>
  <Message>
    Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature. RequestId:7b5be14d-d01e-0052-3bbc-401398000000 Time:2020-06-12T13:24:49.0110739Z
  </Message>
  <AuthenticationErrorDetail>
    Signature did not match. String to sign used was r 2020-06-12T13:23:26Z 2020-06-12T14:23:26Z /blob/xxx/files/a0958aeb-3de7-430f-a94b-88314be31f26/test (2).txt https 2019-07-07 b
  </AuthenticationErrorDetail>
</Error>
```

**To Reproduce:**
I realize that the BlobClient isn't necessary in below example. It would be more valid if the method were to say, upload a blob and return the SAS URI.

```c#
// Called with:
// id = "a0958aeb-3de7-430f-a94b-88314be31f26"
// fileName = "test (2).txt"
public string GetBlobUri(Guid id, string fileName)
{
  var blobName = $"files/{id}/{fileName}";
  var blobClient = _containerClient.GetBlobClient(blobName);

  var sas = new BlobSasBuilder
  {
    BlobContainerName = _containerClient.Name,
    BlobName = blobClient.Name, // will be "files/a0958aeb-3de7-430f-a94b-88314be31f26/test%20(2).txt" instead of "files/a0958aeb-3de7-430f-a94b-88314be31f26/test (2).txt"
    Resource = "b",
    StartsOn = DateTimeOffset.UtcNow,
    ExpiresOn = DateTimeOffset.UtcNow.AddHours(1),
    Protocol = SasProtocol.Https,
  };
  sas.SetPermissions(BlobSasPermissions.Read);

  var sasUri = new UriBuilder(blobClient.Uri)
  {
    Query = sas.ToSasQueryParameters(_sharedKeyCredential).ToString()
  };

  return sasUri.ToString();
}
```
**Package:**
 - Azure.Storage.Blobs 12.4.1

**Comment by amnguye** [comment]
Hi,

We are actually aware of this issue where the `BlobClient.Name` returns back an encoded name, instead of the original name that it was given.

However I believe it is a breaking change if we unencode the Name, so we were thinking to create another property called `OriginalName` that is not unencode, to not break current customers and still provide original unencoded name form the client.

I will label this as a bug for now and will look to put out a change soon.

**Comment by kasobol-msft** [comment]
@blueww found out that Name was not encoded in 12.4.0 so we might have regression introduced after that.

**Comment by amnguye** [comment]
Related to #12837

So scratch what I said before.

Looks like since the behavior on encoding the name isn't consistent between using GetBlobClient and making a new BlobClient. So since it's clearly a regression and bug, it's not a breaking change and we can change it back to not an encoded Name.

We will look to get this fixed soon.

**Comment by Smurfa** [comment]
Awesome, thank you for the update.
