### ISSUE TITLE
Improve formatting for code examples

### ISSUE THREAD

**Issue by estensen** [Azure/azure-sdk-for-net#12745]
Looking at code in GitHub it's sometimes hard to read the code and the comments, because the lines are longer than GitHub displays. Is it possible to enforce, or at least encourage, shorter lines?

This is from  [Azure.Messaging.EventHubs/samples/Sample09_ReadOnlyNewEvents.cs](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/eventhub/Azure.Messaging.EventHubs/samples/Sample09_ReadOnlyNewEvents.cs)

<img width="780" alt="Screenshot 2020-06-13 at 10 36 20" src="https://user-images.githubusercontent.com/9142800/84564430-dc704680-ad61-11ea-8480-67e7a0e3e294.png">

**Comment by jsquire** [comment]
Hi @estensen.   Thank you for sharing your feedback. 

During the initial wave of new SDKs, our approach to samples was focused on presenting things in a way that developers could clone and then explore by running/debugging locally in an IDE.  We learned during this time that isn't the approach that is ideal for some who use the samples as a point of quick reference in a read/only manner.

We've since begun reorganizing samples into a form where each is represented by a markdown write-up with focused snippets that will render much better for those reading in a browser.  Samples will continue to be backed by a full implementation for those to probe more deeply, but that won't be the initial presentation.  

Event Hubs has not yet transitioned to the new approach, but it is something that we'll be working on in the near future.
