### ISSUE TITLE
Rename whitelist to allowlist in Microsoft.Azure.ServiceBus

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-for-net#12759]
- https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/servicebus/Microsoft.Azure.ServiceBus/tests/API/APIApprovals.cs

**Comment by jsquire** [comment]
@maririos:  Please be aware that this may not be possible in this instance, as the API in question belongs to a third party dependency.   I'll defer to @nemakam and team for the final call, as I'm not familiar with its usage here.

**Comment by nemakam** [comment]
@maririos, thanks for the suggestion. Its a good idea, but unfortunately that API is not owned by Microsoft. We might have to remove the entire dependency if this needs to be done, which might lead to other issues (because of which this dependency was introduced in the first place). 
Given the scenario, let me know if you have any alternate ideas

**Comment by maririos** [comment]
Thanks @nemakam . Looking at MS documentation:
>When industry naming conventions or consistency make replacement of the term impractical => Leave term unchanged

I will differ to the service team to make the call.

**Comment by SeanFeldman** [comment]
The package with this API is `ApprovalTests`. An issue can be raised with the maintainers of the project to update the language. GitHub issue tracker for the project: https://github.com/approvals/ApprovalTests.Net

**Comment by nemakam** [comment]
Closing this as there is no action on this SDK.
