### ISSUE TITLE
[BUG] Cognitive Services docs state that "Cognitive Services User" role is required, but it is not.

### ISSUE THREAD

**Issue by jongio** [Azure/azure-sdk-for-net#12814]
Here: https://azuresdkdocs.blob.core.windows.net/$web/dotnet/Azure.AI.FormRecognizer/1.0.0-preview.3/api/index.html#create-formrecognizerclient-with-azure-active-directory-credential

We have: 

> You will also need to register a new AAD application and grant access to Form Recognizer by assigning the "Cognitive Services User" role to your service principal.

But I have found that this role is not required. 

The API run successfully without any additional roles assigned.

azsdke2e

**Comment by kinelski** [comment]
The Cognitive Services User role is now required. Strangely enough, it was not required before, but this recently changed (related: https://github.com/Azure/azure-sdk-for-net/issues/13126). We're investigating if this was a service-side fix, but we're closing this issue since this is the desired behavior and no updates to the documentation are required.

This is the error message we get when trying to authenticate without the required role:
```
Azure.RequestFailedException
  HResult=0x80131500
  Message=Service request failed.
Status: 401 (PermissionDenied)

Content:
{"error":{"code":"PermissionDenied","message": "Principal does not have access to API/Operation."}}
```

**Comment by jongio** [comment]
Okay, Thanks for checking @kinelski
