### ISSUE TITLE
Plugin design considerations for Azure.Messaging.ServiceBus

### ISSUE THREAD

**Issue by JoshLove-msft** [Azure/azure-sdk-for-net#12943]
- [ ] Plugin vs policy - https://gist.github.com/JoshLove-msft/a9a5150ac55625af5c66b74958362597
- [ ] how to register a plugin (clientOptions vs client method)
- [ ] Task vs ValueTask as return type for overrideable methods.

/cc @SeanFeldman @danielmarbach

**Comment by SeanFeldman** [comment]
Looking at the policy option, I'm really concerned about one plugin awareness of the other plugins and the ability to manipulate other plugins execution w/o understanding the impact it might have. This feels like a separation of concerns issues.

A policy would decide wherever a message should or should not be sent out or received. A plugin would never do that. In a typical **messaging** scenario, and I deliberately focusing on that, when a message is requested, is retrieved from the broker, and is dropped because of a policy would raise an eyebrow. What would be the use case for such a scenario? Is there a practical use case for such a policy? Do you have customers you know of that have asked for such a feature?

**Comment by danielmarbach** [comment]
I'm with @SeanFeldman on this one. Furthermore the plugin/policy (I think we should call it Gummy Bear until we agree on the name) now suddenly has the possibility to add generate more messages because it has full exposure to the message list. Can't that go hairy pretty quickly especially considering things like send via as well as atomic sends?

For me the picture I got from the discussion was we had most agreement around

- Use a conventional approach to shape Gummy Bears across the library
- Gummy Bears give access to the higher level constructs exposed by the library so for SB it would be Message, for event hub the event data or a batch of event data...

Where things went into interesting territory was when we started letting the desire to align trump the design discussions what Gummy Bears are supposed to do. Because we started putting things together into the same bucket suddenly Gummy Bears need to be renamed to Mammoth just because Mammoth where already there (even though it was kind of said on the sidelines the name Mammoth kind of sticked around from the inception of Mammoth). Now suddenly the nice and sweet little Gummy Bears become these giant hairy beasts :) (I'm sorry dear mammoth!)

To me it seems a strong driver to uniform/align things seems to be biasing our viewpoints. Is it really necessary that everything has to be looked at wholistically? If the group could align an a few basic principles for the conventions couldn't EventHub and Azure Service Bus start experimenting with the conventions and then from that higher level learning and refinements can take place, potentially leading to more SDK components taking on the refined conventions or even EventHub or ASB needing to make slight "breaking changes" over time to realign? As long as abstract classes are in place for the Gummy Bears those things can be reasonably evolved with proper obsoletes and a few engineering trickeries.

**Comment by JoshLove-msft** [comment]
> I'm with @SeanFeldman on this one. Furthermore the plugin/policy (I think we should call it Gummy Bear until we agree on the name) now suddenly has the possibility to add generate more messages because it has full exposure to the message list. Can't that go hairy pretty quickly especially considering things like send via as well as atomic sends?
> 
> For me the picture I got from the discussion was we had most agreement around
> 
> * Use a conventional approach to shape Gummy Bears across the library
> * Gummy Bears give access to the higher level constructs exposed by the library so for SB it would be Message, for event hub the event data or a batch of event data...
> 
> Where things went into interesting territory was when we started letting the desire to align trump the design discussions what Gummy Bears are supposed to do. Because we started putting things together into the same bucket suddenly Gummy Bears need to be renamed to Mammoth just because Mammoth where already there (even though it was kind of said on the sidelines the name Mammoth kind of sticked around from the inception of Mammoth). Now suddenly the nice and sweet little Gummy Bears become these giant hairy beasts :) (I'm sorry dear mammoth!)
> 
> To me it seems a strong driver to uniform/align things seems to be biasing our viewpoints. Is it really necessary that everything has to be looked at wholistically? If the group could align an a few basic principles for the conventions couldn't EventHub and Azure Service Bus start experimenting with the conventions and then from that higher level learning and refinements can take place, potentially leading to more SDK components taking on the refined conventions or even EventHub or ASB needing to make slight "breaking changes" over time to realign? As long as abstract classes are in place for the Gummy Bears those things can be reasonably evolved with proper obsoletes and a few engineering trickeries.

Those are all great and humorous points 😄 The purpose of the gist is merely to explore what the shape/behavior would look like if we went all in on aligning with with the existing Policy concept. The points that you and Sean raise are valid concerns that will help guide the discussion as to whether the Policy approach is viable here. If it is not viable, we will try to establish a set of principles that can be used should Event Hubs, Storage Queues, or any other library run into a similar need.

**Comment by JoshLove-msft** [comment]
As an update, we are exploring the possibility of using a stack based implementation of the plugin model. Instead of it being the plugins responsibility for executing the next plugin (as is the case with HTTP policies), we would invoke the `ProcessNextAsync` method after each plugin runs, thereby maintaining a call stack of plugins. If in the future we want to explore chainable plugins, we could expose the `ProcessNextAsync` method. The net result of this line of thinking is that the API shape would be unchanged from what has currently been merged in, but our implementation would be such that we can easily evolve in the future to chainable if needed.

**Comment by SeanFeldman** [comment]
Plugins shouldn't be responsible executing for other plugins. 👍

**Comment by JoshLove-msft** [comment]
We have been discussing internally how best to support this workflow. One idea that we want to explore is what it would take to extend our types so that a customer can create their own PluginReceiver/PluginSender/PluginProcessor. It appears that we would have to add a few protected ctors to make this possible:
```cs
protected ServiceBusReceiver(ServiceBusClient client, string entityPath);
protected ServiceBusSender(ServiceBusClient client, string queueOrTopicName);
protected ServiceBusProcessor(ServiceBusClient client, string entityPath);
protected ServiceBusSessionProcessor(ServiceBusClient client, string entityPath);
```

A custom library could then define extension methods on the ServiceBusClient (Plugin is assumed to be a model type that mirrors the Track 1 type but uses the new Track 2 SBMessage/SBReceivedMessage).
```cs
    public static class ServiceBusClientExtensions
    {
        public static PluginReceiver CreatePluginReceiver(
            this ServiceBusClient client,
            string entityPath,
            IEnumerable<Plugin> plugins)
        {
            return new PluginReceiver(entityPath, client, plugins);
        }

        public static PluginSender CreatePluginSender(
            this ServiceBusClient client,
            string queueOrTopicName,
             IEnumerable<Plugin> plugins)
        {
            return new PluginSender(queueOrTopicName, client, plugins);
        }
    }
```

If we want to configure all the plugins at the client level, we could derive from the client instead of using extension methods.

The PluginSender would look like:

```cs
    public class PluginSender : ServiceBusSender
    {
        private IEnumerable<Plugin> _plugins;

        internal PluginSender(string queueOrTopicName, ServiceBusClient client,IEnumerable<Plugin> plugins) : base(queueOrTopicName, client)
        {
            _plugins = plugins;
        }

        public override async Task SendMessageAsync(ServiceBusMessage message, CancellationToken cancellationToken = default)
        {
            foreach(var plugin in _plugins)
            {
                await plugin.BeforeSendAsync(message);
            }
            await base.SendMessageAsync(message, cancellationToken).ConfigureAwait(false);
        }
    }
```

The PluginReceiver would like:
Receiver:
```cs
    public class PluginReceiver : ServiceBusReceiver
    {
        private IEnumerable<Plugin> _plugins;

        internal PluginReceiver(string entityPath, ServiceBusClient client, IEnumerable<Plugin> plugins) : base(entityPath, client)
        {
            _plugins = plugins;
        }

        public override async Task<ServiceBusReceivedMessage> ReceiveMessageAsync(TimeSpan? maxWaitTime = null, CancellationToken cancellationToken = default)
        {
            ServiceBusReceivedMessage message = await base.ReceiveMessageAsync(maxWaitTime, cancellationToken).ConfigureAwait(false);
            foreach (var plugin in _plugins)
            {
                await plugin.AfterMessageReceivedAsync(message);
            }
            return message;
        }
    }
```

One thing to keep in mind with this approach is that only overriden methods would be guaranteed to apply the plugins so it would be important to override all methods that should apply the plugins. On the other hand, this gives the custom library complete control as to what methods are plugin-enabled. In the Track 1 library, receiving deferred messages would not apply plugins, but receiving regular messages would. This decision would now be in the hands of the Plugin library author rather than the Service Bus SDK.

**Comment by JoshLove-msft** [comment]
Just pinging on this - @SeanFeldman do you think this is a viable approach for implementing the plugin functionality?

**Comment by danielmarbach** [comment]
Wouldn't this approach suffer from the shortcoming that the plugin ecosystem becomes less composable and therefore plugin A might no longer be usable/mixable with plugin B? 

Of course it might be possible with community effort to introduce a base lib that plugin authors decide to rely upon if composability is desirable

**Comment by danielmarbach** [comment]
> Plugins shouldn't be responsible for executing other plugins. 👍

In addition it doesn't cover this concern

**Comment by JoshLove-msft** [comment]
> Of course it might be possible with community effort to introduce a base lib that plugin authors decide to rely upon if composability is desirable

Exactly, with this model the community would define the contract for what a plugin looks like and use a base lib to compose plugins on top of it.

**Comment by JoshLove-msft** [comment]
> > Plugins shouldn't be responsible for executing other plugins. 👍
> 
> In addition it doesn't cover this concern

Not sure I follow. The plugin receiver/sender implemented by a custom library would define how the plugins are executed. In the code snippet shown the plugins are executed independently of one another.

**Comment by JoshLove-msft** [comment]
@danielmarbach @SeanFeldman just wanted to ping on this. Do you think this approach of allowing extensible senders/receivers/processors would address the plugin scenarios? It would work best if a custom library would also define the contract for what a plugin looks like to allow composition as @danielmarbach mentioned.

**Comment by danielmarbach** [comment]
I do think it is a good strategy but I'll leave that to Sean to confirm since he is way more involved in the plugin space

**Comment by SeanFeldman** [comment]
> This decision would now be in the hands of the Plugin library author rather than the Service Bus SDK.

As a plugin author, I don't want to think I want that. The focus of a plugin author is on the logic of the plugin (what's done to the message payload/headers), not how the message is received. The suggested extension methods approach raises the question of usability as now a customer that wants to use a plugin would need to create a plugin-enabled receiver/sender for each entity involved in the solution rather than registering the plugins with the already existing senders/receivers as it was done in Track 1.

**Comment by JoshLove-msft** [comment]
> As a plugin author, I don't want to think I want that. The focus of a plugin author is on the logic of the plugin (what's done to the message payload/headers), not how the message is received. 

To clarify, this would be the decision of the author of the library that would add PluginSender/PluginReceiver/etc. Other plugin authors would depend on this first library and they would be able to focus on the logic of their plugin.

**Comment by esbenbach** [comment]
I am not a plugin writer, so I have little idea about how this is perceived in the area of Service Bus, but allowing the community to define how plugins compose seems like a disaster waiting to happen.

Worst case scenario, every plugin author decides to build der own composition, meaning no plugins can be combined with each other, leading to everyone having to invent everything each time.

My two cents on this would be: If you want it to be possible to allow the community to define how plugins are composed/executed, by all means provide the option, but PLEASE include a "default composer" that we can use and rely upon.

**Comment by czb182** [comment]
This seems like a major miss.  Most enterprise projects I have worked one use plugins for some piece of functionality.  Claim check, message size check, passing ambient context values to properties, remove user properties filter, etc

**Comment by danielmarbach** [comment]
If I recall correctly you can simply decorate the client object since the necessary constructors are accessible and many methods are overrideable

**Comment by JoshLove-msft** [comment]
Yeah there are some samples for how plugin senders/receivers can be created - https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/servicebus/Azure.Messaging.ServiceBus/samples/Sample09_Extensibility.md by extending the various types.

**Comment by SeanFeldman** [comment]
@JoshLove-msft, I've looked at the sample and there's one area that seems to be lacking. Specifically, working with the incoming message body. The sample is showing how to update properties that are available directly on the `AmqpMessage` but doesn't show how to process the body.
```c#
var rawMessage = message.GetRawAmqpMessage();
rawMessage.Properties.Subject = "Last subject";
```

And the body is `AmqpMessageBody` which is not as trivial as properties when it comes to mutation. It feels like there could be some improvement to allow plugin creators access and modify the message body more easily. Thoughts?

**Comment by JoshLove-msft** [comment]
Hi @SeanFeldman,
There are setters on the Body property so this can be mutated in plugins. Are you asking for this to be shown in the samples?

**Comment by SeanFeldman** [comment]
The `Body` has a setter and a getter but requires an `AmqpMessageBody`. As a point of abstraction, the SDK should facilitate it, and it does by providing `AmqpMessageBody.FromXXXX()` where the options are data, value and sequence. Which one to use?
Also, when authoring an incoming pipeline plugin, it's most likely operating on the incoming payload. To retrieve that, `TryGetXXX()` with the three mentioned options are exposed. Which one to use? Showing that in the sample would be good to understand how to mutate the payload that is usually a simple primitive such as a string or a byte array.

**Comment by danielmarbach** [comment]
Some of these problems seem to comw from the level of abstraction the plug in uses. Because it operates more on the Amqp level the one providing a plug in is forced to understand intricacies of that protocol data representation. For HTTP based plug in one could argue that is more common knowledge but for Amqp that cannot be assumed a given. Having more guidance makes sense to me

**Comment by JoshLove-msft** [comment]
Ok I think we can take this as feedback to add samples demonstrating how one would mutate the message body in a plugin.

**Comment by SeanFeldman** [comment]
@JoshLove-msft any updates? Thank you.

**Comment by JoshLove-msft** [comment]
I've created a separate issue, https://github.com/Azure/azure-sdk-for-net/issues/28037, describing the samples ask and have added it to the June milestone.

**Comment by JoshLove-msft** [comment]
Closing this out as we are tracking the samples asks separately and the discussion has concluded.
