### ISSUE TITLE
[QUERY] Managed identity token for App Service throws AuthenticationFailedException occasionally

### ISSUE THREAD

**Issue by shpathak-msft** [Azure/azure-sdk-for-net#13054]
**Query/Question**

We have a webapp which uses managed identity token service to get a token to talk to one of our AKS hosted backend service. We are occasionally seeing AuthencationFailedException, with inner message - "Invalid response, the authentication response was not in the expected format." This is causing our customer workflows to fail. 

Exception Type: Azure.Identity.AuthenticationFailedException

Stacktrace:
```
   at Azure.Identity.ExtendedAccessToken.GetTokenOrThrow()
   at Azure.Identity.ManagedIdentityCredential.GetTokenAsync(TokenRequestContext requestContext, CancellationToken cancellationToken)
   at Microsoft.Azure.DevSpaces.Common.Auth.ServicePrincipal.ManagedIdentityTokenService.GetAccessTokenAsync(String resource) in C:\A\vs2019mb-00003I-1\_work\39\s\src\common.auth\ServicePrincipal\ManagedIdentityTokenService.cs:line 74
```
I also tried to fetch token on the kudu console using following command but I get a "Unable to connect to the remote server" error.

Invoke-WebRequest -Uri 'http://169.254.169.254/metadata/identity/oauth2/token?api-version=2018-02-01&resource=https%3A%2F%2Fconfiguratorsvc.eus.azds.microsoft.io%2F' -Headers @{Metadata="true"}

Could you please help figure out why am I not able to fetch a token from the kudu console and where can we get more information/logs to figure out why the token is in a invalid format?

****Code snippet to get token****

var token = await this._managedIdentityCredential.GetTokenAsync(new TokenRequestContext(new[] { resource }));

**Environment:**

<PackageReference Include="Azure.Identity" Version="1.1.1" />

 - Azure AppService
> dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.1.301
 Commit:    7feb845744
Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x86

**Comment by shpathak-msft** [comment]
We are seeing this happening frequently. Can someone please help troubleshoot?

**Comment by schaabs** [comment]
@shpathak-msft thanks for filing this issue. There was an issue in the `ManagedIdentityCredential` when authenticating against  App Service MSI endpoint when the application was using a culture other the en-us. This issue has been fixed in our latest preview 1.2.0-preview.5. Would it be possible to upgrade to this version to see if you still hit the error your describing above?

Also, with regard to your issue using kudu to directly hit the endpoint. I think the issue might be with the endpoint your using. "'http://169.254.169.254/metadata/identity/oauth2/token" is the endpoint that IMDS uses for managed identity but I believe App Service actually provides it's own endpoints since it's hosting multiple processes. The managed identity endpoint for your app should be defined in the MSI_ENDPOINT environment variable. Also to ensure you're using the same API version as Azure.Identity is currently using you'll need to user the API version "2017-09-01" and you'll also need to add the header "secret" which should have the value which is defined the in the MSI_SECRET environment variable.

**Comment by shpathak-msft** [comment]
@schaabs Thanks for the response. I checked the issue with authenticating when the application was using culture other than en-us. We are seeing this issue in some US as well as non-US regions, so I am unsure if it is the same issue. So I would first like to check the token and figure out what is invalid. I used your instructions and tried hitting kudu to hit the MSI endpoint. This time, I was able to hit the MSI end point but I see this error now:

**Request:
Invoke-WebRequest -Uri 'http://127.0.0.1:41337/MSI/token/?api-version=2017-09-01&resource=https://management.azure.com/' -Method GET -Headers @{Metadata="true";Secret="****"} -UseBasicParsing

**Response:
{"StatusCode":400,"Message":"No MSI found for specified ClientId/ResourceId.","CorrelationId":"8f3d414f-81b4-4288-ac11-7328ae1b3460"}

**Comment by schaabs** [comment]
@shpathak-msft Does the App Service in question have a system assigned identity or only a user assigned identity? If it is a system assigned identity you can omit the client id query parameter. However to get a user assigned identity this has to be passed, but this version of the App Service managed identity endpoint actually expects the parameter as clientid rather than client_id. Can you try altering your command as so:

Invoke-WebRequest -Uri 'http://127.0.0.1:41337/MSI/token/?api-version=2017-09-01&resource=https://management.azure.com/&clientid=f58ad482-817e-4b5a-ac64-d68445bfff71' -Method GET -Headers @{Metadata="true";Secret="****"} -UseBasicParsing

**Comment by shpathak-msft** [comment]
I got it working after using "clientid" instead of "client_id". I see this on the token "expires_on":"7/10/2020 6:04:48 PM +00:00". Is this the invalid format? Also, only some requests fail with this AuthenticationFailedException and not all. If it were the culture issue, shouldn't it affect all requests?

**Comment by schaabs** [comment]
Do you have both successful and unsuccessful authentication in the same process? If this is the case you're right that it's most likely not a problem with the culture. In that case it would probably be best to use logging to try and capture the responses which are responsible for the AuthenticationFailedExceptions.
