### ISSUE TITLE
[FEATURE REQ] ServiceBusActiveMessagesAvailableWithNoListenersEventData Event Grid Data Model is missing SessionId

### ISSUE THREAD

**Issue by mikemarmar** [Azure/azure-sdk-for-net#13080]
**Library or service name.**
Azure Service Bus and Microsoft.Azure.EventGrid.Models
 
**Is your feature request related to a problem? Please describe.**
Service Bus can be configured to publish an event to Event Grid when a message arrives on a subscription but no receivers are connected and waiting to receive messages. This event contains data of type ServiceBusActiveMessagesAvailableWithNoListenersEventData, which contains the Topic and Subscription that received the message.

This event data model does not contain the SessionId of the message. Thus, if sessions are enabled on the Topic, there is no way to specifically request messages from the correct session (such as with SessionClient.AcceptMessageSessionAsync). In this case, the only way to handle the event is to register a session handler and process messages in all sessions. This can be very inefficient if there are many concurrent sessions and most do not currently need to be processed.

I assume that in addition to updating the data model, this change will require input from the Azure Service Bus service team to update the event payload.

**Comment by jsquire** [comment]
//fyi: @ellismg, @JoshLove-msft, @kerri-lee

**Comment by axisc** [comment]
@mikemarmar  Thanks for raising this issue. the Event Grid notification here is to behave as a shoulder tap indicating that messages are available.
Unfortunately, it's not straightforward to add the session id to the EG event. This is due to the fact that the entire queue (or subscription) would have to be scanned.

Could you elaborate the end to end scenario you are looking to enable ? Perhaps we can provide an alternate solution for the same.

**Comment by axisc** [comment]
@mikemarmar closing this issue for now. Please feel free to open a new issue if this is still an open question.
