### ISSUE TITLE
Explore credential support across languages

### ISSUE THREAD

**Issue by JoshLove-msft** [Azure/azure-sdk-for-net#13102]
Come up with the plan for credential types that will be used in the Event Grid library. We know that our base type will be `AzureKeyCredential`, but since there are two forms of auth - one with a SAS key and another with a SAS token, we may want to have derived types for each form of auth.
We should probably align across languages here. It is also worth considering whether there should be something like `AzureSharedSignatureCredential`.

**Comment by ellismg** [comment]
Thanks for opening this, I talked a bit about this with Scott S last week, and here's my current thoughts on the space (if they are helpful), but I trust you and Kerri to come up with something great.

I think that we should be able to re-use `AzureKeyCredential` as is for the shared key support.  I believe this aligns with other services (like TA) which have a shared key. 

I think we do need another credential type for the SharedAccessSignature support.  I don't think we want to have that be a subclass of `AzureKeyCredential` however, because we don't want to encourage passing a signature credential to a method that expects a key.

I had imagined we would just do an `EventGridSharedAccessSignatureCredential` type in our own package, and then have overloaded constructors that took either `AzureKeyCredential` or `EventGridSharedAccessSignatureCredential`, but maybe creating some shared `AzureSignatureCredential` type in core makes sense for .NET, to be shared with other services.  I'm not sure that I know any other services that use SAS keys in this way, but it might be an interesting thing for the .NET team to explore, to do what makes most sense in .NET.

One other thing to keep in mind, internally in Azure, services can publish to event grid authenticating using a client certificate (this is TLS client certificate, not some AAD thing where you use a client cert to act as a principal).  The existing Track 1 SDK doesn't really provide good support for doing this, so in practice most internal services end up forging the Client SDK in favor of just using `HttpClient` directly to hit the REST endpoints.  I do not believe that we should add client certificate support to the public surface area, but I would like if there was a way we could design our types such that they could be reused by internal azure services.

I think if we add a protected constructor to our `EventGridClient` type that looks like:

```csharp
protected EventGridClient(Uri endpointUri, HttpPipelinePolicy authentication, EventGridClientOptions options)
```

It would allow us to build some something like this:

```csharp
public class AzureInternalServiceEventGridClient : EventGridClient {
    public AzureInternalServiceEventGridClient(Uri endopointUri, X509Certificate2 clientCertificate, EventGridClientOptions options)
}
```

And that types `.ctor` would be able to construct the relevant `HttpPieplinePolicy` that would use the a client certificate.

That would provide a nice way for us to support this internal scenario in .NET.


FWIW - with respect to cross language alignment, here's where I currently stand with TS:

- `KeyCredential` (an existing interface type in `@azure/core-auth`)
- `AzureKeyCredential` (an implementation of the above, also in `@azure/core-auth`)
- `SignatureCredential` (a new interface, exported from `@azure/eventgrid`)
- `EventGridSharedAsscessSignatureCredential` (a new implementation of the above, exported from `@azure/eventgrid`)

Unlike .NET, we have interfaces and concrete types.  The design guidelines have us take the interfaces types in our constructor, so the constructor looks like this:

```typescript
export class EventGridClient {
  constructor(endpointUrl: string, credential: KeyCredential | SignatureCredential, options?: EventGridClientOptions);
  ...
}
```

**Comment by JoshLove-msft** [comment]
>I had imagined we would just do an EventGridSharedAccessSignatureCredential type in our own package, and then have overloaded constructors that took either AzureKeyCredential or EventGridSharedAccessSignatureCredential, but maybe creating some shared AzureSignatureCredential type in core makes sense for .NET, to be shared with other services. I'm not sure that I know any other services that use SAS keys in this way, but it might be an interesting thing for the .NET team to explore, to do what makes most sense in .NET.

Storage uses SAS signature, but they are included in the Uri itself that gets passed to the [constructor](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/storage/Azure.Storage.Blobs/src/BlobClient.cs#L98).
I'm not sure if other services would need something like this. /cc @tg-msft as he has looked into SAS quite a bit.

For the certificate stuff, do we think that the built-in transport swapping is not enough for internal partners:
```c#
            var handler = new WebRequestHandler();
            handler.ClientCertificates.Add(publisherCertificate);
            var options = new EventGridClientOptions()
            {
                Transport = new HttpClientTransport(new HttpClient(handler))
            };
```
This would let internal partners use the SDK without us needing to expand the surface area. If we want to make things more seamless for partners at the slight cost of expanding surface area, then I think what you show makes sense.

Thanks Matt!

**Comment by ellismg** [comment]
> For the certificate stuff, do we think that the built-in transport swapping is not enough for internal partners:

So, if we take that route, what does the construction of the client type look like?  I assume the code would continue like the following:

```csharp
var handler = new WebRequestHandler();
handler.ClientCertificates.Add(publisherCertificate);
var options = new EventGridClientOptions()
{
    Transport = new HttpClientTransport(new HttpClient(handler))
};

var client = new EventGridClient(new Uri("https://my-topic.uswest2-1.eventgrid.azure.net/api/events"), /* ??? */, options);
```

What do I pass in to the existing credentials parameter?  `null`?  I assume we would want to fail if `null` is passed in as a credential in general, so maybe I can't pass in `null`.  Do I pass in something like `new AzureKeyCredential("this key should never be used")`?  In that case, how does the client library know that it should not construct a pipeline policy to add the `aeg-sas-key` header?

My main goal is that we don't make the external scenario worse in some dimension to support the internal one.  If we can support the internal scenario without adding additional `.ctors`, that's great, but I don't know if that's going to make us do weird things like "allow a null credential because sometimes you'll pass in a custom transport that can do client auth".

**Comment by JoshLove-msft** [comment]
> > For the certificate stuff, do we think that the built-in transport swapping is not enough for internal partners:
> 
> So, if we take that route, what does the construction of the client type look like? I assume the code would continue like the following:
> 
> ```cs
> var handler = new WebRequestHandler();
> handler.ClientCertificates.Add(publisherCertificate);
> var options = new EventGridClientOptions()
> {
>     Transport = new HttpClientTransport(new HttpClient(handler))
> };
> 
> var client = new EventGridClient(new Uri("https://my-topic.uswest2-1.eventgrid.azure.net/api/events"), /* ??? */, options);
> ```
> 
> What do I pass in to the existing credentials parameter? `null`? I assume we would want to fail if `null` is passed in as a credential in general, so maybe I can't pass in `null`. Do I pass in something like `new AzureKeyCredential("this key should never be used")`? In that case, how does the client library know that it should not construct a pipeline policy to add the `aeg-sas-key` header?
> 
> My main goal is that we don't make the external scenario worse in some dimension to support the internal one. If we can support the internal scenario without adding additional `.ctors`, that's great, but I don't know if that's going to make us do weird things like "allow a null credential because sometimes you'll pass in a custom transport that can do client auth".

I would think we could just have a null key passed to the AKC, and that we wouldn't actually have client side validation here. But I will need to see what other libraries are doing in terms of client-side validation of keys.

**Comment by JoshLove-msft** [comment]
Ah I guess you are right Matt - https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/core/Azure.Core/src/AzureKeyCredential.cs#L33
