### ISSUE TITLE
[FEATURE REQ] Copy a file from URL to a blob

### ISSUE THREAD

**Issue by Socolin** [Azure/azure-sdk-for-net#13212]
**Library or service name.**
Azure.Storage.Blobs
 
**Is your feature request related to a problem? Please describe.**
What feature would you like to get added?

Copy a file from URL to a blob

This:
https://docs.microsoft.com/en-us/azure/storage/common/storage-use-data-movement-library#copy-a-file-from-url-to-a-blob

What problem is it solving?
It avoid using bandwith for nothing, (download then upload) instead it's just a copy from a server to another directly.

**Comment by amnguye** [comment]
Hi,

Thanks for the feedback! Looks like this should be an ask on the Microsoft.Azure.Storage.DataMovement library to support the v12 library.

I've linked an existing open issue for that. https://github.com/Azure/azure-storage-net-data-movement/issues/221

Since this is a duplicate issue not on the correct repo, I will be closing this issue.
