### ISSUE TITLE
[QUERY] How to Send Binary Data as parameter to FormRecognizerClient.StartRecognizeCustomFormsFromUri method?

### ISSUE THREAD

**Issue by Vuharish** [Azure/azure-sdk-for-net#13407]
I have trained the model successfully using 5 forms placed in storage blob container. I have used the below method.
CustomFormModel model =
                    await trainingClient.StartTrainingAsync(new Uri(trainingDataUrl), useLabels: false).WaitForCompletionAsync();

After training, I want to send my test form document as binary data  as parameter to StartRecognizeCustomFormsFromUri.

At present I am using formClient.StartRecognizeCustomFormsFromUri(modelId, new Uri(pdfFormFile)).WaitForCompletionAsync(); method? 

I am sending the file uploaded in the blob storage like below.
string pdfFormFile= "<SAS-URL-of-a-form-in-blob-storage>";

Can you help me how to send binary data as parameter to above method?

Environment:

    visual stuido 2019
    .net core 3.1
   Azure.AI.FormRecognizer --version 1.0.0-preview.1.

Thanks in advance.

**Comment by kinelski** [comment]
Hello, @Vuharish. Thanks for reaching out.

I noticed you are using an old version of the Azure.AI.FormRecognizer package. This version is missing newest features and has known bugs that have already been fixed in our latest release, `1.0.0-preview.4`, so I suggest updating it. You can find more information about installing the newest version [here](https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/formrecognizer/Azure.AI.FormRecognizer#install-the-package).

Regarding your question, the package does support sending binary data as a `FileStream`. You just need to use the `StartRecognizeCustomForms` method (without the `FromUri` suffix). You can take a look at our sample [here](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/formrecognizer/Azure.AI.FormRecognizer/samples/Sample2_RecognizeCustomForms.md#recognize-custom-forms-from-a-file-stream) to see how to create a `FileStream` and pass it to the correct method.

Let me know if this answers your question!

**Comment by Vuharish** [comment]
Thanks Kinelski.

I have updated my solution with the newest version. I have used var forms = await formClient.StartRecognizeCustomFormsAsync(modelId, byteData).WaitForCompletionAsync();  to send binary data as parameter and it is completely working fine.

Thanks for your reply.

**Comment by Vuharish** [comment]
Working fine now after updating he version and using the overloaded method.
