### ISSUE TITLE
Microsoft.Rest.Azure present in Search Client section of Docs.MS ToC

### ISSUE THREAD

**Issue by scbedd** [Azure/azure-sdk-for-net#13458]
[Location](https://review.docs.microsoft.com/en-us/dotnet/api/overview/azure/search.documents-readme?view=azure-dotnet&branch=smoke-test)

Screenshot:

![image](https://user-images.githubusercontent.com/45376673/87484461-13e54380-c5eb-11ea-9a18-b88124196049.png)

Find a better location and move this.

**Comment by kurtzeborn** [comment]
This is an issue that library owners should be able to address by following the documentation we've created for these types of issues [here](https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/283/Docs.MS-Primer?anchor=how-do-i-actually-update-the-toc%3F).  Please reach out to @danieljurek or @scbedd if you need assistance.

**Comment by ramya-rao-a** [comment]
Thanks @kurtzeborn

@Mohit-Chakraborty, I believe the file to update is https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/docs-ref-toc/top_level_toc.yml. When you create a PR to fix this, please add @scbedd and @danieljurek as reviewers.

Please see if we can get this fixed in the current milestone. If not, please move it to the March milestone
