### ISSUE TITLE
[Identity] xxxCredential.GetToken() should return token containing Account/TenantId

### ISSUE THREAD

**Issue by erich-wang** [Azure/azure-sdk-for-net#13504]
**Library or service name.**
What library or service is this request related to?
**Azure.Identity**
 
**Is your feature request related to a problem? Please describe.**
What feature would you like to get added? What problem is it solving?
Currently xxxCredential.GetToken() returns AccessToken that contains only token string and expiration time, which hides some useful properties of AuthenticationResult returned from underlying MSAL library, e.g. TenantId, Account, Azure PowerShell needs to use property `TenantId` and `Account` for acquiring token silently and/or saving context.

**Proposed change**
Define a child class MsalAccessToken derived from AccessToken and add the following properties, then return MsalAccessToken for all xxxCredential.GetToken()
```csharp
public IAccount Account { get; }
public string TenantId { get; }
```

**Comment by schaabs** [comment]
@erich-wang as we have discussed online we won't be adding these properties to the `AccessToken` structure. Because this structure is returned from the `TokenCredential.GetToken` abstract method there would be no way to ensure this data would be returned as older implementations would not return this information. The `Authenticate` method has been added to credential types in Azure.Identity which authenticate users. This method returns the `AuthenticationRecord` type which contains the requested fields. I'm closing this issue, but if you find that the `Authenticate` APIs don't meet your needs, and feel that augmenting `GetToken` is still necessary feel free to reopen it.
