### ISSUE TITLE
[QUERY] Event Grid Clients question, where do headers send using PublishEventsWithHttpMessagesAsync end up?

### ISSUE THREAD

**Issue by Expecho** [Azure/azure-sdk-for-net#13575]
**Query/Question**
In the `PublishEventsWithHttpMessagesAsync` of the `EventGridEvent` class there is the option to send custom headers along with the http request using the `customHeaders` argument ([docs](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.eventgrid.eventgridclient.publisheventswithhttpmessagesasync?view=azure-dotnet)). I was wondering where they end up.

I would expect to be able to query those headers on the consuming side so I create an Http Triggered Azure Function but the headers are not present in the http request.

**Environment:**
 - Name and version of the Library package used: Microsoft.Azure.EventGrid 3.2.0
 - Hosting platform or OS and .NET runtime version: Azure Function App v3 / .Net Core 3.1
 - Visual Studio 2019

**Comment by ahamad-MS** [comment]
Investigating.. will update thread once finalized.

**Comment by ahamad-MS** [comment]
Event Grid does not deliver these custom headers to destinations. We use some of them for validation purposes currently. For example, the content size header (which is optional too).

Hence, it is by design that these headers are not consumed at the receiving side. 

Is there any specific scenario you have in mind where you need to use these custom headers? Why no include this info in the data payload?

Also note that we are in the process of adding support of cloud event 1.0 to the client SDK where there will be more flexibility in adding attributes outside of the data payload itself in case this helps.

**Comment by Expecho** [comment]
> Is there any specific scenario you have in mind where you need to use these custom headers? Why no include this info in the data payload?

I want to send correlation data with the request so Application Insights can pick it up on the receiving side and set the correct operation id and parent id based on the values in the request. Having this data in the payload means it is too late in the pipeline to be able to correlate the incoming request with the request sending the event.

**Comment by ahamad-MS** [comment]
Thanks @Expecho for the additional info. This helps a lot.

The good news is that we are adding distributed tracing and OpenTelemetry support for CloudEvent 1.0 in our Data plane SDKs which we are currently working on (No final ETA yet). We will follow the approach documented here for CloudEvent 1.0: https://github.com/cloudevents/spec/blob/master/extensions/distributed-tracing.md

We are still in discussion on how to support that in the SDK for event grid event schema. This will require modifying the current event grid schema to include new properties for tracing. Again, no commitment on this work or ETA yet.

Will you be able to use CloudEvent initially? Does this answer your question/request?
