### ISSUE TITLE
BaseUri is not initialized in some constructors of SubscriptionClient (ARM)

### ISSUE THREAD

**Issue by bvirkler** [Azure/azure-sdk-for-net#1362]
Some of the ARM [SubscriptionClient](https://github.com/Azure/azure-sdk-for-net/blob/9154888d1ddbfe84cac0d86492f4bd6b99ed06ff/src/ResourceManagement/Resource/ResourceManagement/Generated/SubscriptionClient.cs) constructors leave the baseUri null while others set it to a default value of "https://management.azure.com/".  

Shouldn't all constructors that don't accept baseUri as a parameter set it to a default value?  Since the BaseUri property is read-only there's no other way to specify a value.

**Comment by markcowl** [comment]
@bvirkler The underlyingissue is that the constructors which do not take required parameters (credentials) should be protected.  This is fixed in the newly generated clients using autorest https://github.com/Azure/autorest, you should see new clients using the new generator in the coming months that will solve the issue.
