### ISSUE TITLE
Use Azure.Identity to connect a client via a service principal to Azure Queue

### ISSUE THREAD

**Issue by StefH** [Azure/azure-sdk-for-net#13747]
The link below describes how to access Azure Blob / Queue using ClientSecretCredential from the service principal.
https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/identity/Azure.Identity#authenticating-a-service-principal-with-a-client-secret

However I want to use a different scenario:
1. Service Principal has Storage Queue Data Contributor role
`az ad sp create-for-rbac -n "MyApp" --role 'Storage Queue Data Contributor' .  .  .`

2. This Service Principal is also defined as an API app-registration:
![image](https://user-images.githubusercontent.com/249938/88580982-c5a15d00-d04c-11ea-89b2-cf5e456d8bfe.png)

3. Another app registration QueueClient has access to this API.
However when using ClientSecretCredential for this client and calling the code to send a message, I get an error:
```
Unhandled exception. Azure.RequestFailedException: This request is not authorized to perform this operation using this permission.
RequestId:48070a49-3003-009c-6e48-64e817000000
Time:2020-07-27T19:05:54.7051685Z
Status: 403 (This request is not authorized to perform this operation using this permission.)
ErrorCode: AuthorizationPermissionMismatch
```

**Comment by jsquire** [comment]
Tagging and routing to the team best able to assist.

**Comment by amnguye** [comment]
Hi,

I tried to reproduce your issue with sending a message with a QueueClient authenticated with a `ClientSecretCredential` with a Service Principal that has Storage Queue Data Contributor role applied to it, but I wasn't able to get the 403 `AuthorizationPermissionMismatch` error.

The way to authenticate with a Service Principal with Storage Queue Data Contributor role should not be different with a Service Principal that has access to the entire storage account. Have you tried with a service principal that has more authorization than just Storage Queue Data Contributor?

Maybe there's something you have to do with your configurations in order to give your AAD service principal access to your queue data/storage account.
https://docs.microsoft.com/en-us/azure/storage/common/storage-auth-aad

**Comment by StefH** [comment]
@amnguye 
Thank you for replying. Let me explain it...

## Scenario 1:
- A Service Principal with Storage Queue Data Contributor role can indeed send messages --> this is correct.

---
However I've a different scenario:

## Scenario 2:
- I want to configure the "Service Principal with Storage Queue Data Contributor role" and **Expose this as an API app registration**
- Then I create a new **client app registration** which has rights to call this API
- However when this **client app registration** tries to send a message, I get that error.

**Comment by amnguye** [comment]
Sorry for the late reply. Also Sorry if I'm not too familiar with exposing APIs through the app registration but I have two theories.

1. This "Expose an API" is for exposing Web APIs. Which will make it think you already created a web API that has the functionality to message Queues (which means that its trying to point to an existing created API). I don't think it's pointing to the right place, and if I am able to find out if there's actually one for Azure.Storage.Queues then I will let you know.
2. You need to add the Azure Storage to your API permissions

I think if 1. is correct then, you need to create your own Web API that has the queue function you wanted, and have the scope point to that.

**Comment by StefH** [comment]
Correct ; I did some investigation and it seems my scenario is not supported.
