### ISSUE TITLE
I cannot get DeviceCode credentials cached

### ISSUE THREAD

**Issue by thoemmi** [Azure/azure-sdk-for-net#13751]
I'm implementing an internal tool for our administrative tasks on our Azure resources. Because it's a console app I want to use `DeviceCodeCredential` for authentication. However, even though I do set `EnablePersistentCache` to `true`, the tool asks for authentication on every start-up. I can see that the file _%LOCALAPPDATA$\.IdentityService\msal.cache_ is created nevertheless. Do I miss something s that caching doesn't work? Here's my minimal repro:

```cs
class Program
{
    static async Task Main()
    {
        var tokenRequestContext = new TokenRequestContext(new[] { "user.read" });

        var dcc = new DeviceCodeCredential(DeviceCodeCallback, new DeviceCodeCredentialOptions
        {
            EnablePersistentCache = true,
            AllowUnencryptedCache = true,
            TenantId = "<<<redacted>>>",
            ClientId = "<<<redacted>>>",
        });
        var authRecord = await dcc.AuthenticateAsync();
        var accessToken = await dcc.GetTokenAsync(tokenRequestContext);

        Console.WriteLine($"Your token: {accessToken.Token}");
    }

    private static Task DeviceCodeCallback(DeviceCodeInfo deviceCodeInfo, CancellationToken _)
    {
        Console.WriteLine(deviceCodeInfo.Message);
        return Task.CompletedTask;
    }
}
```

I have tested it with the current source of _Azure.Identity_ (https://github.com/Azure/azure-sdk-for-net/commit/c83d960202d6d3cf7e88693fad997f1b53b46baa).

Here's the output of `dotnet --info`:
```
.NET SDK (reflecting any global.json):
 Version:   5.0.100-preview.6.20318.15
 Commit:    4356580024

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.100-preview.6.20318.15\

Host (useful for support):
  Version: 5.0.0-preview.6.20305.6
  Commit:  4ba9ecaabd
```

**Comment by jsquire** [comment]
Tagging and routing to the team member best able to assist.

**Comment by schaabs** [comment]
@thoemmi Thanks for filing this issue. Sorry your experiencing this trouble. In this case the caching is happening, which is why you see the `msal.cache` file being created. However there are a couple of small tweaks needed to avoid prompting the user.

First, the persistent cache can contain tokens from many authentications of different accounts so the `DeviceCodeCredential` needs more information to silently authenticate. The `AuthenticationRecord` returned from `AuthenticateAsync` is a key into the persisted cache which identifies the proper entry for silent authentication. You need to persist it using `SerializeAsync` method and read it on subsequent executions using `DeserializeAsync`.

Secondly, the `Authenticate` method will always prompt the user, so it should only be called on the initial execution.

Here's an example expanding on what you have above:

~~~ c#
class Program
{
    static async Task Main()
    {
        var tokenRequestContext = new TokenRequestContext(new[] { "user.read" });

        AuthenticationRecord authRecord = null;

        // if the AuthenticationRecord has been persisted from a previous execution deserialize it
        // and pass it to the DeviceCodeCredentialOptions
        if (File.Exists("authrecord.json"))
        {   
            using FileStream readStream = new FileStream("./profile.json", FileMode.Create, FileAccess.Read);

            authRecord = await AuthenticationRecord.DeserializeAsync(readStream);
        }

        var dcc = new DeviceCodeCredential(DeviceCodeCallback, new DeviceCodeCredentialOptions
        {
            EnablePersistentCache = true,
            AllowUnencryptedCache = true,
            AuthenticationRecord = authRecord;
            TenantId = "<<<redacted>>>",
            ClientId = "<<<redacted>>>",
        });

        // if no AuthenticationRecord was found we need to call AuthenticateAsync to authenticate a user
        // and serialize the AuthenticationRecord which was returned. 
        if (authRecord == null)
        {
            var authRecord = await dcc.AuthenticateAsync();
 
            using FileStream writeStream = new FileStream("./profile.json", FileMode.Create, FileAccess.Write);

            await record.SerializeAsync(writeStream);

            await writeStream.FlushAsync();
        }

        var accessToken = await dcc.GetTokenAsync(tokenRequestContext);

        Console.WriteLine($"Your token: {accessToken.Token}");
    }

    private static Task DeviceCodeCallback(DeviceCodeInfo deviceCodeInfo, CancellationToken _)
    {
        Console.WriteLine(deviceCodeInfo.Message);
        return Task.CompletedTask;
    }
}
~~~

One last thing to note is the `DeviceCodeCredential` might still prompt the user in some cases, such as if the cached refresh tokens have expired, or elevated consent is needed to obtain a token for the specified scope. In these cases the `DeviceCodeCredential` will automatically prompt the user to reauthenticate, and the cache will be updated with the expanded refresh tokens. 

If you wish to have total control of when the user is prompted, you can set `DisableAutomaticAuthentication` to true on `DeviceCodeCredentialOptions`. This will result in an `AuthenticationRequiredException` being thrown from `GetTokenAsync` in the case that the user needs to be prompted. Your application would then be responsible for calling `AuthenticateAsync` to update the cache when appropriate.

If you have any other questions or trouble with this, please let us know. Also, as you may know, the features you're using (`DeviceCodeCredentialOptions`, `AuthenticateAsync` and `AuthenticationRecord`) are still in preview, and they are being added to enable scenarios such as yours. So if you have any feedback or suggestions we'd love to hear them!

**Comment by thoemmi** [comment]
@schaabs Thanks for your answer. I've implemented the authentication like in your example, and it works.

> If you have any other questions or trouble with this, please let us know. Also, as you may know, the features you're using (DeviceCodeCredentialOptions, AuthenticateAsync and AuthenticationRecord) are still in preview, and they are being added to enable scenarios such as yours. So if you have any feedback or suggestions we'd love to hear them!

I'm aware that I'm living on the edge and that the API may still be subject of change. :wink:

Before using _Azure.Identity_ I have used _Microsoft.Identity.Client.Extensions.Msal_ directly. My understanding of `StorageCreationPropertiesBuilder` was that it just works, with file-based cache on Windows, keyring on Linux and keychain on macOS.
When using `DeviceCodeCredential`, is storing of the `AuthenticationRecord` like in your example above required on Windows only, or on every platform?

**Comment by schaabs** [comment]
> Before using Azure.Identity I have used Microsoft.Identity.Client.Extensions.Msal directly. My understanding of StorageCreationPropertiesBuilder was that it just works, with file-based cache on Windows, keyring on Linux and keychain on macOS.

Setting `EnablePersistentCache` to true will cause the cache to be stored automatically, in the same manner as using `MsalCacheHelper` from *Microsoft.Identity.Client.Extensions.Msal* directly. In fact *Azure.Identity* is using this library for cache persistence.

> When using DeviceCodeCredential, is storing of the AuthenticationRecord like in your example above required on Windows only, or on every platform?

The `AuthenticationRecord` essentially identifies the correct account in the cache. Just as when using MSAL directly you would need this account information when silently authenticating. It's up to the application how to store this information. No tokens are included in the `AuthenticationRecord` so it doesn't need to be protected. In my above example the file would be stored and read regardless of the platform.

**Comment by thoemmi** [comment]
Many thanks for the clarification 👍 

I'm afraid I have to wait for 1.3.0-preview to continue with `DeviceCodeCredential` or stick with 1.2.0-preview.6 😉
