### ISSUE TITLE
Need code review approval

### ISSUE THREAD

**Issue by srisrutim** [Azure/azure-sdk-for-net#13861]
**Query/Question**
I have a pull request that I need to merge soon for a feature - https://github.com/Azure/azure-sdk-for-net/pull/13759. According to the PR policies, I won't be able to merge it unless a reviewer with admin or write permissions approves it.

How can I find someone with admin/write permissions to get my PR approved? The SLA is 48 hours and its been 3 days since I submitted the PR.

**Comment by jsquire** [comment]
Hi @srisrutim.  Thank you for your contribution and apologies that it hasn't been picked up.  I was curious as to why and when I looked, I noticed that it does not reference any of the Azure SDK libraries and was submitted to our cross-service sample area; because of that, the system was not able to apply tags that would have alerted the folks who should review.

This looks to be a gap in our GitHub automation around that repository folder.  I'll open discussions and get that fixed up.    In the meantime, I've tagged your PR and looped some folks in to help review.

I'm going to close this out, as I believe discussion will move to the PR.   Please feel free to reopen if you believe there is further discussion needed here.
