### ISSUE TITLE
BlobContainer ListBlobsSegmentedAsync with searchPattern

### ISSUE THREAD

**Issue by fabiomaulo** [Azure/azure-sdk-for-net#1387]
Useful to have
An overload of ListBlobsSegmentedAsync with a 'searchPattern'.
Similar to Directory.GetFiles()
Thanks.

**Comment by fabiomaulo** [comment]
A client side implementation using a Func as a match (the user can use anything including regex)
https://gist.github.com/fabiomaulo/29fec2240c0b6c4b842e

**Comment by mirobers** [comment]
Hi, for questions about the storage .NET client, please use the azure-storage-net repo.

We provide result lists that can be filtered in any number of ways using LINQ. By the way, I see that your implementation calls ListBlobSegmentedAsync and waits synchronously; consider using the ListBlobs() API instead which provides the lazy enumeration already. (Unless you're using the netstandard library, in which case the synchronous APIs are not available yet but coming soon.) Also, note that a flat blob listing will return instances of CloudBlob, so you can cast directly to CloudBlob, access the blob name property, and filter using LINQ.

Closing this issue because it's old and in the wrong repo, but please feel free to open new issues in the azure-storage-net repo.
