### ISSUE TITLE
[FEATURE REQ] Get topicHostname from BaseUri in EventGridClient

### ISSUE THREAD

**Issue by mattosaurus** [Azure/azure-sdk-for-net#13997]
**Library or service name.**
Microsoft.Azure.EventGrid
 
**Is your feature request related to a problem? Please describe.**
When publishing events using EventGridClient the PublishEventsAsync method requires topicHostname to be provided, however it's possible to determine this from the internal BaseUri attribute which is set at initialization so providing this argument is unecessary.

Would it be possible to add an overload of the PublishEventsAsync and PublishEventsWithHttpMessagesAsync methods that doesn't require the topicHostname argument but instead sets this from the BaseUri?

e.g. `topicHostname = new Uri(BaseUri).Host;`

I think this is the relevant code where the change would be required.

https://github.com/Azure/azure-sdk-for-net/blob/9d671143f4d54be7c02aeddc8e0ad99037236793/sdk/eventgrid/Microsoft.Azure.EventGrid/src/Generated/EventGridClient.cs

Thanks

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.

**Comment by jsquire** [comment]
//fyi - @ellismg, @JoshLove-msft

**Comment by mattosaurus** [comment]
Thanks.

This would essentially involve adding the following overload to EventGridClient and updating IEventGridClient and EventGridClientExtensions accordingly.

```
public async Task<AzureOperationResponse> PublishEventsWithHttpMessagesAsync(IList<EventGridEvent> events, Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken))
{
	string topicHostname = new Uri(BaseUri).Host;
	return await PublishEventsWithHttpMessagesAsync(topicHostname, events, customHeaders, cancellationToken);
}
```

**Comment by ellismg** [comment]
Hi @mattosaurus!

You're correct that this is an unfortunate pattern we have in the existing SDK, however, I'm not certain that your proposed change will behave the way we want.  While you are correct that `BaseUri` is initialized when the client is created, it's initialized to a fixed value, which is the string: [`"https://{topicHostname}"`](https://github.com/Azure/azure-sdk-for-net/blob/9702b7e1c4901c6d4147c68892a2ef584ea6c56f/sdk/eventgrid/Microsoft.Azure.EventGrid/src/Generated/EventGridClient.cs#L201).  Note that this is a literal string, and not an instance of a interpolated string which is putting in the value of some `topicHostname` parameter.

This is used as the [basis of forming the actual URL](https://github.com/Azure/azure-sdk-for-net/blob/9702b7e1c4901c6d4147c68892a2ef584ea6c56f/sdk/eventgrid/Microsoft.Azure.EventGrid/src/Generated/EventGridClient.cs#L297-L309) for the service, by replacing `{topicHostname}` with what was passed into the `PublishEvents....` method.  I believe in your proposed code we would end up trying to construct a Uri from the string `https://{topicHostname}` and that will fail, because it is an invalid URI.  Even if it were to succeed, the `Host` property would return some fixed value like `{topicHostname}` and not the name of your actual event grid topic.  Because of this, I don't think we can make a simplification here.

However, we are in the process of creating a new Event Grid SDK which follows our new [Azure SDK Design Guidelines for .NET](https://azure.github.io/azure-sdk/dotnet_introduction.html) and as part of that work, we now take the endpoint url of the topic as a parameter when you **construct** the client vs when you publish the event.

You can see the shape of the new API [here](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/eventgrid/Azure.Messaging.EventGrid/api/Azure.Messaging.EventGrid.netstandard2.0.cs) and in fact all of the work we're doing is being done in [GitHub right now](https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/eventgrid/Azure.Messaging.EventGrid) (please forgive the templated README.md, it will be updated to something real shortly).  In addition to cleanups like this we're adding support for publishing events in the Cloud Events 1.0 schema, which the existing SDK does not support.

If you have any additional feedback on the SDK, the team would love to hear it.  As I mentioned above, we're in the process now of doing this work with the hopes of releasing a preview release in September to get additional feedback, but if you have additional feedback now we can work to incorporate this in the design.

I'm going to close this issue because I don't think there's a low cost way for us to take the improvement.  We would need to add additional constructors to `EventGridClient` or some other way to set the topic host name so we could use it when you go to send and event.  We'd rather spend our development effort on the newer SDK which we believe fixes this wart and is in general more approachable while at the same time adding new features like Cloud Event support.  But it's possible I've misunderstood your suggestion, in which case feel free to respond or reopen it.

By the way, if you have additional feedback on EventGrid (either sending or processing events) you'd like to share with us feel free to let me know.
