### ISSUE TITLE
[BUG] Requests executed via Azure Search .Net SDK can be abnormally long

### ISSUE THREAD

**Issue by TonyMalandain** [Azure/azure-sdk-for-net#13995]
**Describe the bug**
When executing Azure Search API calls via the SDK, I get a significant overhead compared to running the same calls from postman. Anywhere from 300ms to 16s.
If I use Fiddler to monitor the network traffic, I see that the majority of the delay is spent when the client submit the request to the server.
Here is a captured request in fiddler. Note the big delay between ClientBeginRequest and ClientDoneRequest

ACTUAL PERFORMANCE
ClientConnected:	22:46:55.087
ClientBeginRequest:	22:46:55.172
GotRequestHeaders:	22:46:55.172
ClientDoneRequest:	22:47:05.388
Determine Gateway:	0ms
DNS Lookup: 		0ms
TCP/IP Connect:	0ms
HTTPS Handshake:	0ms
ServerConnected:	22:46:55.112
FiddlerBeginRequest:	22:47:05.388
ServerGotRequest:	22:47:05.388
ServerBeginResponse:	22:47:07.930
GotResponseHeaders:	22:47:07.930
ServerDoneResponse:	22:47:07.930
ClientBeginResponse:	22:47:07.930
ClientDoneResponse:	22:47:07.931

Overall Elapsed:	0:00:12.759

**Expected behavior**
I would expect the time required to submit the request to be in the 0-30 milliseconds range, not hundreds of ms or even seconds.

**Actual behavior (include Exception or Stack Trace)**
Delays from hundreds of milliseconds up to tens of seconds.

**To Reproduce**
1. simply attach fiddler to your .net program
2. run any query via the Azure Search SDK and capture the time taken by the API to run the request
3. compare it with what we reported by fiddler.
4. If you run multiple queries back-to-back, the issue tends to be less significant (i.e. average of 300ms delay). but if you want a few minutes and retry, then you're likely to see large delay again.

**Environment:**
 - Code running as a IIS web app (w3wp process)
 - Reproduced with version 3.0.4 to version 11 of the Azure Search SDK
 - Reproduce with both .Net framework 4.7 and 4.8
 - Windows Server 2019

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by heaths** [comment]
Most of the unexpected delay is all client-side, so we'll need to perftrace what's going on. There is overhead for `HttpClient`, which we use internally, but I wouldn't expect that to take 10 seconds, nor have I seen that. Could this be a binding / assembly load issue, especially since the code in question is running against Framework?

/cc @pakrym

**Comment by TonyMalandain** [comment]
@heaths : if you give me the instructions on the perftrace, I'm happy to run it. I thought about binding / assembly, but then it would happen most likely once the first time the app is loaded. Here, it seems to happen randomly, even after the app has been loaded.

**Comment by heaths** [comment]
Thanks! It would help since I've not seen times like this, and it may be limited to IIS or something else about the hosting environment.

1. Download [perfview](https://github.com/microsoft/perfview).
2. Open it and click **Collect** -> **Collect**.
3. Make sure ".NET" is checked (default).
4. Click **Start Collection**.
5. Run your scenario. Maybe do it a couple times as you suggested above in the repro steps so we can compare (some initial overhead is expected, but nothing like that).
6. Click **Stop Collection**. It'll take some time to generate, but you'll end up with an *.etlx file. I'll need that file.

The process is also described in a video (old, but still relevant) here: https://channel9.msdn.com/Series/PerfView-Tutorial/PerfView-Tutorial-11-Data-Collection-for-Server-Scenarios

If you could post that on OneDrive or some other share and email me the link directly, I can extract just the information for IIS. **Note**: this file will contain .NET trace information for all processes, so sandbox the server if possible. The data will be deleted once I can extract just the perf trace data for the call stacks in question.

**Comment by TonyMalandain** [comment]
My apologies. I got busy and didn't get a chance to follow-up.
As an FYI in case it happens to others.
We were able to confirm that the library works fine in a console test app and web app.
The issue seems to be deeper in the .Net framework as it impacts any HTTPClient calls, not just the Azure Search client library
