### ISSUE TITLE
[QUERY] Potential bug in Azure.Messaging.EventHubs Sample04

### ISSUE THREAD

**Issue by NIXC** [Azure/azure-sdk-for-net#14095]
**Query/Question**
Hello, I was reading over the [PublishMultipleEventBatches](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/eventhub/Azure.Messaging.EventHubs/samples/Sample04_PublishMultipleEventBatches.cs) sample for Azure Messaging EventHubs, and noticed what I believe to be a bug. On line 84 when an event is dequeue'd if it fails to add to the batch (eg when the batch is full) it is not put back into the queue or otherwise handled. I suspect the event is thus lost.

I couldn't get the samples library to compile from a zip of the repo, so I couldn't validate my findings (My actual project is using framework, so debugging issues with core is out of my ball park). But I feel fairly confident I am correct...

Thanks!

**Environment:**
 - Name and version of the Library package used: Azure.Messaging.EventHubs 5.1.0
 - Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects): Windows 10 .NET Framework 4.6.2, core version 3.1.6?
 - IDE and version : Visual Studio 16.7.0

**Comment by jsquire** [comment]
Hi @NIXC.   Thank you for reaching out with your feedback.   This is a nice find on your part; it definitely looks like we've got an oversight for the error case, as you're describing.   We should switch over to doing a `TryPeek` and only dequeue on successful `TryAdd` call.

**Comment by heesunlee9** [comment]
Let me try fixing this potential bug

**Comment by jsquire** [comment]
That would be very much appreciated, @heesunlee9.  Please let us know if you run into any difficulties getting your environment setup to build and run tests; we're happy to help get you onboarded.

The Event Hubs [contributing guide](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/eventhub/Azure.Messaging.EventHubs/CONTRIBUTING.md) should be helpful, as well.

**Comment by heesunlee9** [comment]
Hello, 

As @jsquire said, my suggestion is below. 

On line 84:                       
while (TryPeek(eventsToPublish, out EventData currentEvent) && (eventBatch.TryAdd(currentEvent)))      
{    
TryDequeue(eventsToPublish, out EventData currentEvent);      
}      

I did not do below on line 86:
if (TryDequeue(eventsToPublish, out EventData currentEvent))
{
...
}
It is because even if some events remain in 'eventsToPublish' due to the false result of TryDequeue(), those events will be processed in 
line 80 : while (eventsToPublish.Count > 0). 
As long as an event remains in 'eventsToPublish', a while loop in line 80 is executed and the remaining event is processed one day.

**Comment by heesunlee9** [comment]
I did not open a pull request. It is because I have a question on testing. 
I reviewed materials in 'CONTRIBUTING.md'. 
I discovered that there is no test code of Sample04 and other SampleXX. 
Do I have to write a new test code? Or Can I open a pull request without test code?

**Comment by jsquire** [comment]
Fixed by #16479
