### ISSUE TITLE
[FEATURE REQ] Allow Tagging Azure Batch Resources

### ISSUE THREAD

**Issue by BenKoth** [Azure/azure-sdk-for-net#14103]
**Library or service name.**
Microsoft.Azure.Batch
 
**Is your feature request related to a problem? Please describe.**
The azure batch creation methods should allow you to tag the azure resources you are creating. So allow adding tags to Pools/Jobs/etc. Right now I've been told that the this could possibly be done with the Microsoft.Azure.Management.ResourceManager, but that SDK is still in preview and I haven't been able to decipher the documentation on how to accomplish tagging azure batch resources.

My organization would like to use tagging of resources to help when analyzing costs.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by allenjzhang** [comment]
Look in at the [swagger](https://github.com/Azure/azure-rest-api-specs/blob/409fc85092469bfc21153bed5b33deaeaeef3b42/specification/batch/resource-manager/Microsoft.Batch/stable/2020-05-01/BatchManagement.json#L2860) that Pool and other entities are based on ProxyResource which does NOT have tags.

Route to Batch team to support that in the rest api definition.

**Comment by bgklein** [comment]
The only Azure Batch model which is a fully backed ARM resources is the account which is why it is the only one which natively supports tagging. Pools may be possible if ARM is adding support for tagging Proxy resources, but due to the unbounded nature of Jobs/Tasks they are not capable of being ARM managed directly blocking tag support.
