### ISSUE TITLE
[FEATURE REQ] Add support for filters when receiving messages

### ISSUE THREAD

**Issue by mrwatts** [Azure/azure-sdk-for-net#14202]
The AMPQ protocol supports filtering of messages of interest when receiving messages. I would like to be able to use filters too when using the Microsoft.Azure.ServiceBus API.

This request originates from another request here: [Issue 13799](https://github.com/Azure/azure-sdk-for-net/issues/13799).

I have no idea if this is just something that needs to be implemented in the client or that support for this has to be added to the Service Bus first. But I believe it would be a very useful feature to have.

Filters on Topic subscriptions do not accomplish the same thing. They are too static, part of the infrastructure. We need to be able to set filters at runtime.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.

**Comment by jsquire** [comment]
//cc: @ramya-rao-a, @JoshLove-msft, @MiYanni

**Comment by SeanFeldman** [comment]
To be able to request messages with a filter, wouldn't that need to be a broker side feature first?

**Comment by ramya-rao-a** [comment]
Pasting what I believe is the relevant section from AMQP spec here:

<img width="643" alt="Screen Shot 2020-08-13 at 11 03 06 AM" src="https://user-images.githubusercontent.com/16890566/90170248-98df8c00-dd54-11ea-9418-dc2ee8e542ec.png">

**Comment by SeanFeldman** [comment]
@ramya-rao-a just to make sure, spec 1.0 (no link is provided)

**Comment by ramya-rao-a** [comment]
Thanks @SeanFeldman, updated my comment above with the link to the spec that I have been using as a reference

**Comment by axisc** [comment]
Wrote this on #13799 , but adding it here for completeness

Filtering when receiving messages (if implemented) is going to give bad performance because you have to scan the whole queue to identify the first message that satisfies the condition. Topic-Subscription with filters is a much better idea here.

This is allowed in Java Message Service (JMS) API, but admittedly it is less preferred than simply using Topics and Subscriptions.

@mrwatts, you can utilize the management library to create a subscription with specific filters on a topic at runtime - will that help?

**Comment by mrwatts** [comment]
@axisc my assumption was creating a subscription at runtime would be quite an expensive operation. I would be creating the subscription for one message only, and removing it once I have received that message (or after a timeout). Is my assumption wrong?

**Comment by axisc** [comment]
@mrwatts yes that pattern is not going to scale.

Based on your use-case, I believe you need a persisted data store and the queue doesn't fit well because you have to adhere to first in first out as opposed to querying the queue.

I'd recommend rethinking either the way the receivers process the information, or replacing the queue with an alternate data store.

**Comment by mrwatts** [comment]
That's fine. I was already using a storage table for this purpose, but was hoping to be able to refactor it to a 100% service bus solution. Polling a storage table feels very 2004. It's like polling a SQL table while there is SqlDependency.

I do feel there is something missing in this respect. Not necessarily saying that service bus should solve it. The only other viable option besides polling a storage table I can think of is signalr, but that comes at a price tag that's not sensible in respect to the amount of traffic we are handling.
