### ISSUE TITLE
Unable to validate credentials using EventProcessorClient 5.1.0

### ISSUE THREAD

**Issue by shivan19** [Azure/azure-sdk-for-net#14244]
**Describe the bug**
I'm sending incorrect (tested with both malformed and credentials for a different event hub to retain the validity) credentials as part of the connection string and using EventProcessorClient to start and stop processing. Apparently, it doesn't throw an exception stating 401 or ```UnauthorizedAccessException```. How should I test the event hub connection and report bad credentials, in case?

**Expected behavior**
EventProcessorClient throws ```UnauthorizedAccessException```

**Actual behavior (include Exception or Stack Trace)**
None of the event handlers get called and the program timeouts as expected(because of a configured cancellation token)

**To Reproduce**
```
public override async Task StartAsync(CancellationToken token)
{

    // $"Endpoint={this.serviceBusUri};SharedAccessKeyName={this.sasKeyNameValue};SharedAccessKey={this.sasKeyValue};EntityPath={this.eventHubName}"
    EventProcessorClient processor = new EventProcessorClient(storageClient, consumerGroup, ehConnectionString, eventHubName, clientOptions);

    // registering handlers
    processor.ProcessEventAsync += this.ProcessEventHandler;
    processor.ProcessErrorAsync += this.ProcessErrorHandler;

    try
    {
        // starting processors for each partition
        await processor.StartProcessingAsync();

        // Awaiting a cancellation on the token
        while (processor.IsRunning && !token.IsCancellationRequested)
        {
            await Task.Delay(TimeSpan.FromSeconds(1));
        }
        await processor.StopProcessingAsync();
    }
    finally
    {
        Console.WriteLine($"Disposing event handlers");
        processor.ProcessEventAsync -= this.ProcessEventHandler;
        processor.ProcessErrorAsync -= this.ProcessErrorHandler;
        Console.WriteLine($"Done stopping the processor at {DateTime.UtcNow}");
    }
}

private async Task ProcessEventHandler(ProcessEventArgs eventArgs)
{
    if (eventArgs.CancellationToken.IsCancellationRequested)
    {
        return;
    }

    try
    {
        if (eventArgs.Data != null)
        {
            // Blocking call to add elements to queue
            // process
            await eventArgs.UpdateCheckpointAsync(eventArgs.CancellationToken);
        }
    }
    catch (Exception ex)
    {
        CTracer.LogError($"An error was observed while processing events.  Message: {ex}");
    }
}

private Task ProcessErrorHandler(ProcessErrorEventArgs eventArgs)
{
    if (eventArgs.CancellationToken.IsCancellationRequested)
    {
        return Task.CompletedTask;
    }

    Console.WriteLine($"The error handler was invoked during the operation: {eventArgs.Operation ?? "Unknown"}, for Exception: {eventArgs.Exception.Message}");
    return Task.CompletedTask;
}
```

**Environment:**
 - Azure.Messaging.EventHubs.Processor, Version=5.1.0.0
 - .NET Framework 4.6.2
 - Visual Studio 15.9.26

**Comment by jsquire** [comment]
Hi @shivan19.   Thank you for moving this discussion to a new issue.  As mentioned in #10576, the service has responsibility for validating your credentials and making a decision on authorization.  The client will respond with an `UnauthorizedAccessException` if the service rejects a connection/link as unauthorized.   If your credentials are malformed,  it is possible that you'll to see a more generic exception because the server cannot parse the values and instead returns a non-specific server error.

In order to assist, can you please help me understand what exceptions you're seeing surface to your error handler?   I'm interested in the type, stack trace, and `Reason`  in the case of any `EventHubsExceptions`.

**Comment by jsquire** [comment]
I've tested with a well-formed connection string using tokens not valid for the specified namespace.  I'm seeing the error handler invoked as expected.  The Event Hubs service rejects the first operation run (querying properties of the Event Hub), considering the signature generated from the shared key information as invalid.

This presents as an `EventHubsException` with the reason `ServiceCommunicationProblem` (which indicates that the client wasn't able to discern a more specific reason) and a message indicating  `InvalidSignature: The token has an invalid signature. `

I would have expected that this present as an authorization failure, but presumably because the shared key information specified doesn't exist for the given Event Hub, the service couldn't determine if it was well-formed or not.

@serkantkaraca, could I ask you to offer your insight regarding the service behavior in this scenario?

**Comment by shivan19** [comment]
Thanks for following up. Interestingly I don't see my error handler get invoked once I call StartProcessingAsync. Are you referring to the same code that I've put up? I probably might be missing something but for me it doesn't call  ```ProcessErrorHandler``` in case token's invalid. Assuming you're not referring to EventHubClient but EventProcessorClient?

**Comment by jsquire** [comment]
I'm running a slightly simplified version where I start the processor with a cancellation token set to expire in 60 seconds and wait indefinitely until it is cancelled, bypassing your while loop.  I'm also no checking cancellation in the error handler and my event handler is just logging.  Otherwise, the structure is equivalent.

**Comment by shivan19** [comment]
Would you mind posting your sample code, just so that I can compare it directly with my example?
Just to piggy back on the the existing question:
1. Is there a Rest API to test event hub connection directly? The ask is to avoid importing NuGet packages.
2. Are SaS signatures supported by the current event hub client SDK?

**Comment by jsquire** [comment]
1) I did not keep the code that I used, but I lightly modified the test [`EventsCanBeReadByOneProcessorClient`](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/eventhub/Azure.Messaging.EventHubs.Processor/tests/Processor/EventProcessorClientLiveTests.cs#L42) from our live test suite when validating,  changing the error handler to a local function and inspecting via breakpoint.

2) They are not, currently.  This is on our roadmap, but I don't have a timeline.  The initial work for a design across languages is being  covered by (#[11910](https://github.com/Azure/azure-sdk-for-net/issues/11910)) if you're interested in tracking it.

3) The `EventProcessorClient` requires durable storage in order to coordinate ownership of partitions to balance work.  It is not possible to use the processor client without Blob storage.   You could consider creating your own subclass of our [`EventProcessor<T>`](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/eventhub/Azure.Messaging.EventHubs/src/Primitives/EventProcessor%7BTPartition%7D.cs) primitive, which gives you full control over storage.
