### ISSUE TITLE
[BUG] Cannot Use AppAuthentication with Local database

### ISSUE THREAD

**Issue by nraghava123** [Azure/azure-sdk-for-net#14285]
when I am using AppId = "RunAs=Developer; DeveloperTool=VisualStudio" to connect to my local SQL DB I am getting error Login failed for User''.

I should be able to run SQL queries loally using app

Can not login to SQL server.Login failed for User''.

I am using below code to get token.

                 AppidToToken = AzureServiceTokenProvider(AppId);
                AppidToToken.GetAccessTokenAsync(AzureManagementUri);

**Comment by nraghava123** [comment]
Version we are using <package id="Microsoft.Azure.Services.AppAuthentication" version="1.0.3" targetFramework="net472" />

**Comment by nraghava123** [comment]
Microsoft.Azure.Services.AppAuthentication" version="1.0.3

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by jsquire** [comment]
@AlexGhiondea:  Would you be so kind as to assist in routing?

**Comment by nonik0** [comment]
@nraghava123 Could you verify if the access token you are getting is for the identity you expect? Check your VS account settings under Tools > Options > AzureServiceAuthentication. You can also check the identity for the token by decoding the token (can use jwt.io) or by checking the AzureServiceTokenProvider.PrincipalUsed property.

Also, how specifically did you grant your identity access to SQL? Is access granted directly to your user principal, or is access granted to a group that your user principal is a member of?

**Comment by nraghava123** [comment]
Token has right user name,. Verified Tools->Options, this also right user name, Token has right PrinicipalUserID property.
In SQL I have give permission to my user principal. 

When I connect to SQL thru SSMS by using AAD - Universal with MFA I am getting same error, Login failed for User '<empty>' Error 18456. I need to do some config setting in SQL server?

**Comment by jsquire** [comment]
Hi @nraghava123.  We've spoken with the SQL Server team and they let us know that the behavior that you're seeing is the expected behavior for your this scenario. 

The underlying reason is that Azure Active Directory authorization is not supported for on-premises SQL Server instances, including Local DB.  That is also why you're unable to connect through SSMS.  This is not a limitation of the client tools, rather of the server itself.  Unfortunately, there is no configuration that you'd be able to set to enable this.
