### ISSUE TITLE
Azure KeyVault Active Directory AcquireTokenAsync timeout when called asynchronously

### ISSUE THREAD

**Issue by akonyer** [Azure/azure-sdk-for-net#1432]
AcquireTokenAsync does not work after the first active directory authentication token expires. 

I'm trying to authenticate against Azure KeyVault using some code from the 'Hello Key Vault' sample application. I am able to authenticate and get a new token properly after the first 1 hour token expires using AcquireToken, but not AcquireTokenAsync.

```
var result = context.AcquireToken(resource, clientCredential); //works
var result = await context.AcquireTokenAsync(resource, clientCredential); //hangs
```

I opened up a question on Stack Overflow outlining my problem in more detail: https://stackoverflow.com/questions/32594642/azure-keyvault-active-directory-acquiretokenasync-timeout-when-called-asynchrono

However I think this may actually be a bug. The reason is that even calling .Result on the AcquireTokenAsync return object hangs, but using AcquireToken does not:

```
         var result = context.AcquireTokenAsync(resource, clientCredential);
         return result.Result.AccessToken; //hangs

         var result = context.AcquireToken(resource, clientCredential);
         return result.AccessToken; //works
```

**Comment by devigned** [comment]
I bet someone forgot a ConfigureAwait(false) and it never gets back to the right thread.

**Comment by devigned** [comment]
@akonyer please provide your authentication context code as well (minus all sensitive strings).

**Comment by akonyer** [comment]
public class AzureEncryptionProvider : IEncryptionProvider
       {
      public AzureEncryptionProvider()
      {
         _keyVaultClient = new KeyVaultClient(GetAccessToken);
         _keyBundle = _keyVaultClient.GetKeyAsync(_keyVaultUrl, _keyVaultEncryptionKeyName).GetAwaiter().GetResult();
      }

      private static readonly string _keyVaultAuthClientId = ConfigurationManager.AppSettings["KeyVaultAuthClientId"];

      private static readonly string _keyVaultAuthClientSecret =
         ConfigurationManager.AppSettings["KeyVaultAuthClientSecret"];

      private static readonly string _keyVaultEncryptionKeyName =
         ConfigurationManager.AppSettings["KeyVaultEncryptionKeyName"];

      private static readonly string _keyVaultUrl = ConfigurationManager.AppSettings["KeyVaultUrl"];


      private readonly KeyBundle _keyBundle;
      private readonly KeyVaultClient _keyVaultClient;

      public string DecryptString(string textToDecrypt, string algorithm = null)
      {
         algorithm = GetEncryptionAlgorithm(algorithm);
         var data = Convert.FromBase64String(textToDecrypt);
         var decrypted = _keyVaultClient.DecryptDataAsync(_keyBundle, algorithm, data).GetAwaiter().GetResult();
         return Encoding.UTF8.GetString(decrypted.Result);
      }


      public string EncryptString(string textToEncrypt, string algorithm = null)
      {
         algorithm = GetEncryptionAlgorithm(algorithm);
         var data = GetPlainText(textToEncrypt);
         var encrypted = _keyVaultClient.EncryptDataAsync(_keyBundle, algorithm, data).GetAwaiter().GetResult();
         return Convert.ToBase64String(encrypted.Result);
      }

      private async Task<string> GetAccessToken(string authority, string resource, string scope)
      {
         var clientCredential = new ClientCredential(_keyVaultAuthClientId, _keyVaultAuthClientSecret);
         var context = new AuthenticationContext(authority, null);
         var result = await context.AcquireTokenAsync(resource, clientCredential);
         return result.AccessToken;
      }

      private string GetEncryptionAlgorithm(string algorithm = "")
      {
         if (string.IsNullOrEmpty(algorithm))
         {
            algorithm = JsonWebKeyEncryptionAlgorithm.RSAOAEP;
         }
         return algorithm;
      }

      private byte[] GetPlainText(string text)
      {
         return Encoding.UTF8.GetBytes(text);
      }

       }

**Comment by akonyer** [comment]
I'm not sure if you have read through the StackOverflow question, but I'll add some more information here as well.

I have discovered that this does not seem to happen from within a console application, but is reproducible in a MVC web application. If I call the "EncryptString" method from within a controller context, the first call here works. The second time I hit the same web endpoint, the program hangs on await context.AcquireTokenAsync.

In this sample, I am passing null as the second constructor to AuthenticationContext. This is to force no caching and request a new token each time. Otherwise, I had to wait an hour for the token to expire before I could reproduce the problem.

In production, I got this to work by using AcquireToken instead. So AcquireTokenAsync seems to be causing the issue. TokenCache.DefaultShared is passed into the AuthenticationContext in production to allow for caching.

A user on stack overflow believes I am causing a deadlock by not using "async" all the way down. He believes that calling ".GetAwaiter().GetResult();" in the constructor is part of the problem - but since I can not make the constructor asynchronous, this is a bit of a pain.

**Comment by smoothdeveloper** [comment]
I'm facing same issue, I don't think this should be closed.

@devigned you said:

> I bet someone forgot a ConfigureAwait(false) and it never gets back to the right thread.

Did you mean something in the SDK or in client code we are supposed to write?

Any chance to also have a *sync* version of the calls which at least saves one from trying to understand why the call would lock for eternity / help troubleshooting AD stuff (which doesn't provide very helpful messages).

For the AD part itself, when I manage to get `task.Result` I'm getting `Microsoft.IdentityModel.Clients.ActiveDirectory.AdalServiceException: AADSTS65001: The user or administrator has not consented to use the application with ID 'MYCLIENTID'. Send an interactive authorization request for this user and resource.`

This message could, let say, give the complete URI to go to and login so that "consent" is given, even after doing it succesfully (although it took me some time to peruse several pages in the portal + some google search to find correct URIs just to get the info I needed).

When those error messages are designed, people shouldn't assume that the recipient is going to have in-depth knowledge of Azure, Active Directory on azure, all the authentication API or REST end points, etc. so message should drive to next step for resolution in a more straight-forward manner.

I've also commented there:

https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/issues/248#issuecomment-230645154

**Comment by akonyer** [comment]
The problem for me was that I was not using "async all the way down".

There were places I was using async/await, and then other places I was forcing it to be synchronous by calling .Result, which was causing a deadlock. I'm not 100% sure why the deadlock was happening, but using async all the day down did solve the issue.

It is good practice in general when you are working with async code.

Hopefully this helps you with your issue.

**Comment by smoothdeveloper** [comment]
@akonyer thanks for feedback.

Then as I say the issue is that we don't have any alternative to the async method, and a Task exposed as a public API shouldn't deadlock client code, this seems totally backward.

There is probably lots to say about how `async`/`await`/`task` is done in C#, in F# running `async` workflow has never led me to such outcome of deadlocking calling thread.

I've tried to run the code in a background thread as well and it was doing the same kind of deadlocking, only after cancelling and running several ones it would somehow complete (now with the AD error message that I'm sure many people faced).

Ideas for the Azure team to help people using their APIs/SDKs:
* provide synchronous calls which are guaranteed to not deadlock aside of async calls (so they can be tested for correctness of setup from a simple script file)
* methods returning tasks shouldn't lead to deadlock, even if user doesn't do the "best practice", make `.Result` throw an exception or complete but no such thing as deadlock
* get rid of "only AD is great" in all the APIs/SDKs, having something akin to .publishsettings seems like a reasonable alternative for those who don't want to deal with AD
* provide more helpful error messages in API responses
* provide only a single code sample per language, and very focused to the sequence of few calls, the profusion of samples and their questionable lack of focus is not helping end-users

**Comment by akonyer** [comment]
I agree that it should not deadlock, and that there should be alternatives to having to use async/await.

Since the GetAccessToken method absolutely has to be async, I have simply labelled it as such in the method signature, but used no await within the method.

`      private static async Task<string> GetAccessToken(string authority, string resource, string scope)
      {
         ILogger logger = new Log4NetLogger();
         ClientCredential clientCredential = new ClientCredential(_keyVaultAuthClientId, _keyVaultAuthClientSecret);
         AuthenticationContext context = new AuthenticationContext(authority, TokenCache.DefaultShared);
         AuthenticationResult result = context.AcquireToken(resource, clientCredential);
         return result.AccessToken;
      }`

This is what my GetAccessToken method looks like, and it is working without deadlocking. It is too bad though that you can not initialize the KeyVaultClient withouth an async callback.

**Comment by smoothdeveloper** [comment]
@akonyer somehow I don't have `AcquireToken` available this is the version of the assembly I'm using:

> Microsoft.IdentityModel.Clients.ActiveDirectory (3.10.305231913)

Am I using wrong version?

My code, I'm not using vault but the end result is the same as you had initially (deadlocking on .Result):

```fsharp
 let authenticate (settings: CloudSettings) =
    let authenticationContext =
      settings.ActiveDirectoryAuthenticationUrl
      |> AuthenticationContext

    let userCredential =
      UserPasswordCredential(settings.ActiveDirectoryLogin, settings.ActiveDirectoryPassword)

    authenticationContext.AcquireTokenAsync(settings.ServiceManagementUrl, settings.ActiveDirectoryClientId, userCredential)
```

**Comment by akonyer** [comment]
Hmm, actually you are using a newer version than I am. I am using 2.25.305061457

I just updated to 3.10 to check, and sure enough, they have removed the non-async method.

I guess I am going to have to look into updating my code myself then. Seems likely that if I update I will run into the same problem as you.

**Comment by peterno** [comment]
I have had the same deadlock problem with version 3.13.7 and a web api using Entity Framework/SQL Always Encrypted.

I added ConfigureAwait(false) to the AcquireTokenAsync call and then it worked without any problems.

One way to test is to set the TokenCache to null in the AuthenticationContext constructor. Without ConfigureAwait(false) it deadlocks immediately but with ConfigureAwait(false) it works every time.
