### ISSUE TITLE
[QUERY] KeyOperations not settable when creating a key

### ISSUE THREAD

**Issue by isra-fel** [Azure/azure-sdk-for-net#14365]
**Query/Question**
When using track 2 key vault SDK, I found that `KeyOperations` was not settable ([source code](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/keyvault/Azure.Security.KeyVault.Keys/src/CreateKeyOptions.cs#L24)) when creating a key. This is different behavior from track 1 ([source code](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/keyvault/Microsoft.Azure.KeyVault/src/Generated/KeyVaultClient.cs#L286)).

My questions:
1. Is this by design?
1. Will it be supported in the future?
1. Is there any work-around except for `UpdateKeyProperties`?

Thank you

**Environment:**
 - Name and version of the Library package used: `Azure.Security.KeyVault.Keys, Version=4.1.0.0`
 - Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects): [e.g. Azure AppService or Windows 10 .NET Framework 4.8]
```
.NET Core SDK (reflecting any global.json):
 Version:   3.1.401
 Commit:    5b6f5e5005

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19041
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.401\

Host (useful for support):
  Version: 3.1.7
  Commit:  fcfdef8d6b

.NET Core SDKs installed:
  2.1.701 [C:\Program Files\dotnet\sdk]
  2.1.801 [C:\Program Files\dotnet\sdk]
  2.2.207 [C:\Program Files\dotnet\sdk]
  3.1.401 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.21 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.21 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.21 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```
 - IDE and version : [e.g. Visual Studio 16.3] `vscode 1.48.0`

**Comment by heaths** [comment]
Per [.NET Guidelines](https://docs.microsoft.com/dotnet/standard/design-guidelines/guidelines-for-collections#collection-properties-and-return-values), collection properties are not settable. Instead, you can use the collection initializer pattern:

```csharp
var options = new CreateRsaKeyOptions("my-rsa-key")
{
  KeyOperations =
  {
    KeyOperation.WrapKey,
    KeyOperation.UnwrapKey,
  },
  // other options
}

KeyVaultKey key = await keyClient.CreateRsaKeyAsync(options);
```

The `KeyVaultKey.KeyOperations` is a read-only collection (i.e. the above pattern won't work) because you can only set them when creating like above, or when updating via `KeyClient.UpdateKeyProperties(Async)`. The `KeyVaultKey` itself is merely a response model and is never sent back to the service as a means to help ensure it's a valid key and can only responsibly be used for operations for which it was granted (e.g. don't accidentally using it for encryption if only wrap/unwrap was granted).

I hope this answers your questions, but feel free to follow up if not.

**Comment by isra-fel** [comment]
I got it. Thanks for the great explaination! It works perfectly.
