### ISSUE TITLE
[QUERY] Is there a way to use service bus on iOs with Unity?

### ISSUE THREAD

**Issue by SimonStHilaire** [Azure/azure-sdk-for-net#14380]
**Query/Question**
Hi,
  I am trying to control an Hololens 2 experience using iPads/iPhones as remotes. The app is As developed in Unity. As expected it works fine on the Hololens as a receiver. On the sender side, I tested with Windows desktop and Android device and they both work well. The exception I get when I call SendAsync on my TopicClient on an iPhone is that the library have been "Linked away". Any idea on what is causing this and if whan I want can be achieved?

Thank you,

Simon

**Environment:**
 - NuGet package Microsoft.Azure.SeviceBus version 4.1.3 
 - Unity 2019.4.5f1 (on Windows 10)
 - macOS 10.15.6
 - XCode 11.6

**Comment by axisc** [comment]
I believe it just needs you have to have the .NET framework runtime installed.

**Comment by SimonStHilaire** [comment]
Oh, sorry for the lack of precision of my last question, I meant on iOs (iPhone). This is where I am trying to run my code calling teh Azure Service Bus.

Thank you

**Comment by axisc** [comment]
do you have a specific need to use the .NET SDK? why not use the JS one - I'm not very familiar with iOS development so I'll let @jsquire  help route the query.

Even so, I'd recommend having your mobile device not talk to Service Bus directly because it needs a stateful AMQP connection to Azure Service Bus. You're probably better off having a REST endpoint your mobile app can talk to and that REST endpoint manages communication with Azure Service Bus.

hope that helps.

**Comment by SimonStHilaire** [comment]
Maybe my design is wrong; I want to remote control an Hololens experience on one or multiple devices from a phone or tablet.  I need a realtime communication to send command to the devices. I want to be able to talk to each one wherever they are but maybe I can bring myself to use WiFi for this and think about a more decentralize solution later.

I am already planning to use the REST api to keep track of the progression on each device but I don't like every device polling for commands.

Maybe there is a better way to do this, I am pretty new to all cloud services and even more with Microsoft solutions.

**Comment by SimonStHilaire** [comment]
But I really don't want to waste your time. I was able to make it work on an Android device so we can buy more of these and use the iPads for something else.

**Comment by jsquire** [comment]
Apologies for the delay; Unity is not my area of expertise and I had to wait on an inquiry from some folks in the gaming space.  This particular error is rumored to be related to tree-shaking when the Mono build process prepares the iOS target.  Essentially, static analysis does not appear to be finding use of the types and is "shaking away" the types when linking in order to minimize the executable size.   

Unfortunately, consensus appears to be that this isn't something that can be resolved by a general setting or code change; it requires walking the specific source and trying to reconcile with the build.   Unity makes this a bit harder, as they're usually a few versions behind and have some of their own additions to the build pipeline.

Generally speaking, the Service Bus library targets `netstandard2.0` which should allow it to be used with Unity, per the [Unity docs](https://docs.unity3d.com/Manual/dotnetProfileSupport.html).   One thing that is probably worth double-checking is what transport you're using.  We've seen some mobile platforms get cranky about TCP access;  I think it is a long shot for why something may be linked away, but it might be worth trying with [`TransportType.AmqpWebSockets`](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/servicebus/Microsoft.Azure.ServiceBus/src/TransportType.cs) for a quick test.
