### ISSUE TITLE
[FEATURE REQ] Improvements to Code Coverage Collection.

### ISSUE THREAD

**Issue by chidozieononiwu** [Azure/azure-sdk-for-net#14427]
https://github.com/Azure/azure-sdk-for-net/pull/14185 added code coverage reporting for internal pipeline runs, However more work needs to be done on code coverage collection and reporting.

- [ ] The Code Coverage is not showing up for the `net - core` pipeline.
- [ ] Filter out share libraries such that only the library for the specified service is built.
- [ ] Add ability to generate the coverage HTML locally.
- [x] Re-enable coverage after #15231 disabled it due to https://github.com/coverlet-coverage/coverlet/blob/master/Documentation/KnownIssues.md#1-vstest-stops-process-execution-earlydotnet-test.

**Comment by kurtzeborn** [comment]
Switching label from "EngSys" to "Client" since these labels are used to indicate who is working on the issue and not the area the issue is in.  In this case, we need the libraries team to implement the appropriate/preferred filtering to get the code coverage reports they want.  Dozie has already hooked up the tooling.

**Comment by bquantump** [comment]
@ShivangiReja What is the current status of this? We would like to coordinate this with MGMT plane.

**Comment by heaths** [comment]
To note, fixing #15231 means using VSTest integration which is pretty limited. For example, no report item is created because the build targets can't know what the file will be called like with MSBuild integration. This causes downstream issues, like ever-increasing file counts on dev boxes and difficulty generating a useful report because we can only collect all files, which of course will increase report generation time.

**Comment by heaths** [comment]
It seems the problem with displaying results for core is the sheer size - cobertura.xml is 128MB.
