### ISSUE TITLE
Replace Accept header transform with a swagger fix

### ISSUE THREAD

**Issue by pakrym** [Azure/azure-sdk-for-net#14477]
We should remove https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/search/Azure.Search.Documents/src/autorest.md#set-odatametadata-accept-header-in-operations in favor of setting a global/per-operation produces value in `searchservice.json`.

After the https://github.com/Azure/azure-sdk-for-net/pull/14407 is merged.

cc @heaths

**Comment by pakrym** [comment]
https://github.com/Azure/azure-rest-api-specs/blob/38388fadb2a31238262c96520a96f413ff7c7311/specification/cognitiveservices/data-plane/LUIS/Authoring/preview/v3.0/LUIS-Authoring.json#L68

https://github.com/Azure/azure-rest-api-specs/blob/97318e230c61f00bb5ebf977507aa19838cb531d/specification/intune/resource-manager/Microsoft.Intune/preview/2015-01-14-privatepreview/intune.json#L16

**Comment by heaths** [comment]
Thanks, though, wouldn't it be `consumes`? It's part of the request header telling the server how much extra OData "stuff" to send.

**Comment by pakrym** [comment]
This value describes what format the server produces and the Accept header specifies what the client would prefer service to produce.

**Comment by AlexGhiondea** [comment]
I think we should consider doing this. /cc @Mohit-Chakraborty @tg-msft

**Comment by ShivangiReja** [comment]
I've a PR out for this work item https://github.com/Azure/azure-rest-api-specs/pull/22032/files and it works fine when I try to generate code using it but the PR is failing with the format error.

@archerzz @pshao25 @chunyu3 - Could you please suggest me the correct format for adding `odata.metadata` in global produces for accept header?

**Comment by ShivangiReja** [comment]
Discussed this issue with the team and adding the conclusion below:

Since external users also use the swagger, we will not update the swagger for these changes. 

I found accept header transform only for [.NET](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/search/Azure.Search.Documents/src/autorest.md#set-odatametadata-accept-header-in-operations) and [Java](https://github.com/Azure/azure-sdk-for-java/tree/main/sdk/search/azure-search-documents/swagger#set-odatametadata-accept-header-in-operations).  If we add the accept header transform for all the languages, we can consider adding common autorest transform. If we add this transform only for .NET and java, then we can keep the changes as is.

@xiangyan99 and @jairmyree could you please confirm whether we add accept header transform for Python and TS or not?

**Comment by dgetu** [comment]
@ShivangiReja Please see https://github.com/Azure/azure-sdk-for-js/blob/7acf428575e62b544c147e0d302a7c2cb9c493be/sdk/search/search-documents/src/odataMetadataPolicy.ts for the callback where this is handled.

**Comment by ShivangiReja** [comment]
Thanks @dgetu!

[Python](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/search/azure-search-documents/azure/search/documents/_search_client.py#L57) and [JS](https://github.com/Azure/azure-sdk-for-js/blob/7acf428575e62b544c147e0d302a7c2cb9c493be/sdk/search/search-documents/src/odataMetadataPolicy.ts) hardcode the accept header, so closing this issue as only .NET and Java use transform.
