### ISSUE TITLE
Add OpenAPI/Swagger Import to API Management operations

### ISSUE THREAD

**Issue by bradygaster** [Azure/azure-sdk-for-net#14483]
The API Management `IApiOperations` interface (and down-level implementation classes) would be great if they offered support for creating new APIs from either a URL referencing a Swagger/OpenAPI document, or from a `System.IO.Stream`. This would **really** open up integration opportunities. 

Thanks!

**Comment by KranthiPakala-MSFT** [comment]
@miaojiang Following up to see if there is any update on the above issue ? - Thank you

**Comment by navba-MSFT** [comment]
@bradygaster Apologies for the late reply. Thanks for reaching out to us. We are looking in this and we will provide an update once we have more details on this.

@adrianhall Could you please look into this ask and provide an update on this ?

**Comment by adrianhall** [comment]
Hey Brady,  We can currently take a file or URL.  We are internally investigating if we can take a stream; if we can, it will be in the next major release of our SDK.  Since that will take longer than 6 months, I'm going to close this issue and track it in our internal backlog.

Thanks for the idea!

#close
