### ISSUE TITLE
Include additional AMQP elements in Message

### ISSUE THREAD

**Issue by JoshLove-msft** [Azure/azure-sdk-for-net#14489]
https://apiview.dev/Assemblies/Review/b5d7e3304000449c859c2016f718db52

- AbsoluteExpiryTime
- ContentEncoding
- CreationTime
- DeliveryAnnotations
- Footer
- GroupId (same as SessionId)
- GroupSequence
- Header
  - Durable
  - Priority 
  - Ttl (this should also be top level property)
  - FirstAcquirer
  - DeliveryCount (this should also be top level property on received message)
- MessageAnnotations
- ReplyToGroupId (same as ReplyToSessionId)
- Rename Label to Subject
- UserId

**Comment by ramya-rao-a** [comment]
_**Motivation for this change:**_ 

A desire to allow reading and writing of the different parts of an AMQP message as described by the AMQP spec. See "Message Format" in section 3.2 of the [AMQP spec](https://www.amqp.org/sites/amqp.org/files/amqp.pdf)

_**Guiding factors:**_
- Existing users used to accessing either AMQP properties like `messageId` or AMQP message annotations like `partitionKey` or AMQP message header like `deliveryCount` should continue to have these as top level entities
- All inner details of AMQP message should be accessible to the advanced user. But, since these do not matter to the rest of the user base, we would like to hide the "complete" AMQP message (header, footer, message annotations, deliver annotations, properties) in a nested field. This model can be replicated in Event Hubs in the future
- We do not want to introduce any new AMQP message detail as a top level entity at this moment in time to avoid increasing the surface area and confusing the normal users. If the service team determines that any new AMQP message entity from header/footer/message annotations/delivery annotations deserve to get a spot on the top level, it should be do-able incrementally in a non breaking fashion

_**Revised proposal:**_
- Keep all the top level entities that exist today (like body, messageId, sessionId, partitionKey etc)
- Rename label to subject (to match what AMQP nomenclature)
- Rename userProperties to applicationProperties (to match what AMQP nomenclature)
- Add a field for "AMQP message details" (this sooo needs a better name)
    - header
    - footer
    - message annotations
    - delivery annotations
    - properties
