### ISSUE TITLE
[QUERY] What are the recommendations for the lifetime of a SecretsClient instance in a Desktop App or a long running Service ?

### ISSUE THREAD

**Issue by IoBebe** [Azure/azure-sdk-for-net#14485]
**Query/Question**
What are the recommendations for the lifetime of a SecretsClient instance in a Desktop App or a long running Service ?
Is there a difference in this recommendation for the KeyVaultClient in verison 3.* ?

**Environment:**
I'm working on a client library that consumes our API and consumes secrets from a Azure Key Vault. This client library will be used from Desktop Applications and Windows Services. 

**Our Context**
We are currently using version 3.0.5.
We are in the process of adding manual control over the HttpClient instance used by the KeyVaultClient.
We evaluating switching to version 4.* now or later. Depending on the migration effort + introducing the manual HttpClient instance control.
Our intention is to manage the HttpClient instance used by the KeyVaultClient/SecretsClient ourselves using the HttpClientFactory provided in Microsoft.Extensions.DependencyInjection.
I am aware of the HttpPipeline improvements in verison 4.*

**Comment by heaths** [comment]
Yes, moving to v4 is highly recommended. As for the instances of either client, sharing an `HttpClient` among 1 or more clients is probably a better consideration than the clients themselves if lifetime is a concern. They are somewhat thin wrappers (in v4, the pipeline is much more extensible, but still ultimately relies on the `HttpClient`) over `HttpClient` and stateless. But, yes, tying an instance of the client to its own `HttpClient` is probably going to be simpler and lead to less errors over time for a long-running application since yo're not having to worry about lifetime management.

Hopefully that helps. Any other questions related to this issue/quesiton?
