### ISSUE TITLE
[BUG] - occasional timeout trying to send message to service bus queue

### ISSUE THREAD

**Issue by dazinator** [Azure/azure-sdk-for-net#14669]
**Describe the bug**
Our asp.net core 3.1.0 application is running on Azure Web App for Windows Containers as a docker image.
Every so often we are seeing calls to add a message to a service bus queue, fail with a timeout:

![image](https://user-images.githubusercontent.com/3176632/91540355-995e5200-e912-11ea-9f4b-0eda473c3e16.png)

Stack trace in text format:

> Microsoft.Azure.ServiceBus.ServiceBusCommunicationException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. ErrorCode: TimedOut
 ---> System.Net.Sockets.SocketException (10060): A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
   at Microsoft.Azure.ServiceBus.ServiceBusConnection.CreateConnectionAsync(TimeSpan timeout)
   at Microsoft.Azure.Amqp.FaultTolerantAmqpObject`1.OnCreateAsync(TimeSpan timeout)
   at Microsoft.Azure.Amqp.Singleton`1.GetOrCreateAsync(TimeSpan timeout)
   at Microsoft.Azure.Amqp.Singleton`1.GetOrCreateAsync(TimeSpan timeout)
   at Microsoft.Azure.ServiceBus.Amqp.AmqpLinkCreator.CreateAndOpenAmqpLinkAsync()
   at Microsoft.Azure.ServiceBus.Core.MessageSender.CreateLinkAsync(TimeSpan timeout)
   at Microsoft.Azure.Amqp.FaultTolerantAmqpObject`1.OnCreateAsync(TimeSpan timeout)
   at Microsoft.Azure.Amqp.Singleton`1.GetOrCreateAsync(TimeSpan timeout)
   at Microsoft.Azure.Amqp.Singleton`1.GetOrCreateAsync(TimeSpan timeout)
   at Microsoft.Azure.ServiceBus.Core.MessageSender.OnSendAsync(IList`1 messageList)
   --- End of inner exception stack trace ---
   at Microsoft.Azure.ServiceBus.Core.MessageSender.OnSendAsync(IList`1 messageList)
   at Microsoft.Azure.ServiceBus.RetryPolicy.RunOperation(Func`1 operation, TimeSpan operationTimeout)
   at Microsoft.Azure.ServiceBus.RetryPolicy.RunOperation(Func`1 operation, TimeSpan operationTimeout)
   at Microsoft.Azure.ServiceBus.Core.MessageSender.SendAsync(IList`1 messageList)

**Expected behavior**
Wouldn't expect a timeout to be occuring with everything running on azure infrastructure.

**Actual behavior (include Exception or Stack Trace)**
As per above.

**To Reproduce**
As per the above stack trace, we aren't doing anything unusual, just sending a message to a queue.
The application is deployed to Azure App Service for Windows containers and is built from the base image: `FROM mcr.microsoft.com/dotnet/core/aspnet:3.1 AS base`

Our azure service bus in the "standard" pricing tier, in the "West Europe" region.
Our azure app service plan is in the "PC2: 1" tier, in the West Europe region, with one app service which is the windows container.

**Environment:**
 - Name and version of the Library package used: `Microsoft.Azure.ServiceBus 4.1.3`
 - Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects): Azure App Service for Windows Containers (West Europe region, PC2: 1 pricing tier.
 - IDE and version : Microsoft Visual Studio Professional 2019 Version 16.7.2

**Comment by jsquire** [comment]
Hi @dazinator.   Thank you for your feedback and we regret that you're experiencing difficulties.  Unfortunately, timeouts and transient failures are inherent in any network environment, whether running entirely within the Azure infrastructure or elsewhere.   Applications should expect to encounter occasional transient network issues and guard against them.

To assist with these scenarios, each of the Service Bus clients follows a retry policy to maximize its ability to recover from transient issues.  Because application scenarios have different tolerances for the length of operations and classifying failures, the default retry policy attempts a balanced approach.  If retries are exhausted, transient exceptions will be surfaced to the application so that it can make decisions appropriate to its context.

If your application favors more aggressive retries, the Service Bus library allows configuration of the [retry policy](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.servicebus.retrypolicy?view=azure-dotnet) that can be specified when constructing the various Service Bus clients.   For example, the [QueueClient](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.servicebus.queueclient.-ctor?view=azure-dotnet#Microsoft_Azure_ServiceBus_QueueClient__ctor_Microsoft_Azure_ServiceBus_ServiceBusConnection_System_String_Microsoft_Azure_ServiceBus_ReceiveMode_Microsoft_Azure_ServiceBus_RetryPolicy_) accepts a retry policy as the last argument in all of its constructor overloads.

**Comment by dazinator** [comment]
Ok thanks. I guess I was just concerned that the in-built tolerance didn't catch the transient fault within azure infrastructure. We will look at taking control over the retry policy, but also moving to the premium tier as I understand the standard tier service bus is shared infrastructure and subject to much more variability in performance. Thanks for the pointers.
