### ISSUE TITLE
Consider implementing byte[] property types as BinaryData

### ISSUE THREAD

**Issue by christothes** [Azure/azure-sdk-for-net#14673]
# Summary
Consider replacing `byte[]` property types with `BinaryData`

# References
[PR discussion](https://github.com/Azure/azure-sdk-for-net/pull/13561/files/3735b0ffac817733662327c99df8efc1ced93a34#r458369441)
[BinaryData type](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/core/System.Memory.Data/src/BinaryData.cs)

**Comment by joelverhagen** [comment]
I have a situation where I am splitting a buffer up across several binary columns. For deserialization (reading), `byte[]` is acceptable in my mind but for serialization (writing) I would really like to pass in several `ReadOnlyMemory<byte>` chunks referencing a single larger buffer instead of copying out the chunks to entirely new `byte[]` just for writing.

This could save big allocations in some cases.
