### ISSUE TITLE
[BUG] CryptographyClient not usable with ASP.NET Core/Azure Functions dependency injection.

### ISSUE THREAD

**Issue by mitchdenny** [Azure/azure-sdk-for-net#14695]
**Describe the bug**
Consider the following code in ```Startup.cs```:

```csharp
builder.Services.AddAzureClients(builder =>
{
  builder.AddCryptographyClient(keyVaultUriFromSomewhere);
}
```

I then later inject CryptographyClient into a another piece of code. Problem is -- which key does ```CryptographyClient``` point to? In order to construct a ```CryptographyClient``` we need a key ID from KeyVault to feed into the constructor. It isn't easy to learn from the API surface how to do this inside the DI container configuration.

**Expected behavior**
Not sure what the expected behavior should be here. ```CryptographyClient``` is interesting in that it maps not just to a keyvault instance, but also to a particular entity within that instance. But then why does it have the configuration extension to support configuration at DI container setup time?

**Comment by pakrym** [comment]
What would you want to use the client for? The use-case I had in mind is using a key to encrypt/decrypt some data. Typically you pick this key beforehand and keep using the same one.

Somewhat similar to https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/extensions/Azure.Extensions.AspNetCore.DataProtection.Keys/README.md#examples

**Comment by mitchdenny** [comment]
In my particular use case I'm generating a auth token for GitHub which requires me to sign a JWT with a certificate that they provide. In my case I can pre-create the ```CryptographyClient``` instance in ```Startup.cs```. So I can solve the issue, my main point was that the ```AddCryptographyClient``` extension method doesn't appear to be useful?

**Comment by heaths** [comment]
That is the use case, yes: it has to point to a key ID: <https://docs.microsoft.com/dotnet/api/azure.security.keyvault.keys.cryptography.cryptographyclient.-ctor?view=azure-dotnet#Azure_Security_KeyVault_Keys_Cryptography_CryptographyClient__ctor_System_Uri_Azure_Core_TokenCredential_>

That said, the parameter name / description of `AddCryptographyClient` isn't correct.

**Comment by heaths** [comment]
@mitchdenny yes, if you don't know the key ID (URI) up front, adding the crypto client in `Startup` is probably not useful. The crypto client is designed to work with a single key. Sounds like what you really want is a `KeyResolver`. I'm not sure how useful it is since it will fetch a key on demand each time and create a new `CryptographyClient` each time. The only thing it would cache is the `HttpPipeline` - that's the only state besides the requested/default service version the class holes.

**Comment by lfshr** [comment]
@heaths `KeyBuilder` is exactly what's needed in this scenario, but unfortunately it doesn't live inside the `AddAzureClients` ecosystem so has no visibility to the internal `AzureClientsGlobalOptions` object which contains the credential that all other clients pick up. If people were to go down this route they would have to write their own custom code for handling the credential (or just inject the token directly), which is fine but introduces multiple methods for a client to get it's credentials (I have a soft spot for consistency)

The current implementation is fine for when you're happy to relinquish control of what key version is being used. In our case, we're figuring out the version based on a few conditions, and then using the `CryptographyClient.Sign` method on the active key version. Which would be fine if not for the fact we're caching the versions for validation purposes. So if a new key were to be added, it would break everything (at least for the length of the cache).

I suggest this issue is re-opened on that basis. There should be a way to get `KeyResolver` (or equivalent) into the `AddAzureClients` ecosystem that has access to the `AzureClientsGlobalOptions` that contains the credential used for each client.

**Comment by heaths** [comment]
The version is an optional part of the key ID you can supply already: https://{vault-name}.vault.azure.net/keys/{key-id}/{optional-key-version}.

**Comment by lfshr** [comment]
@heaths aye, I've got it working without the KeyVersion, but what if somebody wants to apply filters before signing it? We figure out the "Active Key" based on the `KeyProperties.Enabled`, `KeyProperties.NotBefore`, and `KeyProperties.ExpiresOn` properties, and we grab a list of the public information of all the active keys. We then cache that information. When it comes to doing the signing, because I'm not passing in the version, the key that's doing the signing isn't guaranteed to be in my verification keys. We're unfortunately constrained from using the `Verify` method.

**Comment by heaths** [comment]
The service provides no way to filter on those. You'd need to list all keys (and/or versions) and check those properties. That's beyond the scope of just specifying a key ID and, optionally, a version. A custom configuration that finds an appropriate key for key operations may be more to your liking, but seems very application-specific and very different from why this issue was opened.
