### ISSUE TITLE
[FEATURE REQ] Align with azcopy retry settings (20 attempts)

### ISSUE THREAD

**Issue by ohadschn** [Azure/azure-sdk-for-net#14753]
**Library or service name.**
All of `Azure.Storage`
 
**Is your feature request related to a problem? Please describe.**
I have ran into timeouts that look like this, trying to upload ~400MB files using slow connections:
```
System.AggregateException: Retry failed after 6 tries. (Error while copying content to a stream.) (Error while copying content to a stream.) (Error while copying content to a stream.) (Error while copying content to a stream.) (Error while copying content to a stream.) (Error while copying content to a stream.)
 ---> Azure.RequestFailedException: Error while copying content to a stream.
 ---> System.Net.Http.HttpRequestException: Error while copying content to a stream.
 ---> System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host..
 ---> System.Net.Sockets.SocketException (10054): An existing connection was forcibly closed by the remote host.
```
I suspect `azcopy` has more optimized retry parameters, especially for upload. Looking at their code, the main difference seems to be the retry count of **20** (for uploads):  https://github.com/Azure/azure-storage-azcopy/blob/2c30af330b681d3a1f31db32e11245eafce9c5c3/ste/xfer.go#L36

Compare this to the Azure SDK retry count of 5 (which translates to a total of 6 attempts): https://github.com/Azure/azure-sdk-for-net/blob/00d31be869a010d4b5801726d11bf83f39031248/sdk/storage/Azure.Storage.Common/src/Shared/Constants.cs#L15

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.

**Comment by amnguye** [comment]
Hi,

I don't think it's right to change the `MaxReliabilityRetries` for all requests, because we could have other requests coming in that will consistently error out due to other reasons aside from slow connections (e.g. internal error, weird auth errors, throttling etc). So if we had a retry of say 20 and the user decides to do a call like `list` but runs into the service having internal errors, then they would wait a very long time to get an error back to say that the service isn't ready or available for this request, when they can receive it much quicker.

One solution we could think over is maybe having a different retry amount/policy for upload / download vs. other types of calls.

Another idea is allowing the user to manually set retry policies, but I'm not sure we're able to do that today. @seanmcc-msft is there a way to set the retry policy today or is that currently being worked on somewhere in Core?

**Comment by ohadschn** [comment]
> Another idea is allowing the user to manually set retry policies, but I'm not sure we're able to do that today. @seanmcc-msft is there a way to set the retry policy today or is that currently being worked on somewhere in Core?

Yes, you can control the retry settings like this:
```cs
var serviceClient = new DataLakeServiceClient(serviceUri, credential, new DataLakeClientOptions
{
    Transport = new HttpClientTransport(new HttpClient { Timeout = Timeout.InfiniteTimeSpan }),
    Retry = 
    { 
        Mode = RetryMode.Exponential,
        NetworkTimeout = Timeout.InfiniteTimeSpan,
        MaxRetries = 19,
        //...
    }
});
```
> One solution we could think over is maybe having a different retry amount/policy for upload / download vs. other types of calls.

This is what `azcopy` does. The partitioned uploader already sets some upload specific storage transfer defaults when not set specifically by the user (like max block size), perhaps the same could be done for retry: https://github.com/Azure/azure-sdk-for-net/blob/49081317e57fa4b44ac64dce9598e08a6460c9a3/sdk/storage/Azure.Storage.Common/src/Shared/PartitionedUploader.cs#L115

> I don't think it's right to change the `MaxReliabilityRetries` for all requests, because we could have other requests coming in that will consistently error out due to other reasons aside from slow connections (e.g. internal error, weird auth errors, throttling etc). So if we had a retry of say 20 and the user decides to do a call like `list` but runs into the service having internal errors, then they would wait a very long time to get an error back to say that the service isn't ready or available for this request, when they can receive it much quicker.

The question is, are those failures transient or not? If they are not transient (e.g. auth errors), they should not be retried at all. If they are transient, I guess it's a question of how long it should take to give up. I concede that the answer might depend on the scenario (specifically, upload vs download or even list). But remember that the "user" could (most of the time?) be an automated program where it might be better to retry 20 times than to fail and force manual human intervention (which in the case of transient errors, would be a retry anyway).

**Comment by amnguye** [comment]
If it's an automated program, then maybe the retries should be set to 20 then right? However in the case that a storage account is getting throttled, 503, (i.e. automated program overloading the storage account) then there needs to be a back-off mechanism to kick of to allow the storage account .

Another question to ask is how much of this should be heavily relied on the SDK. The SDK cannot predict the manner of the environment (e.g. VM size, concurrency, size of the blob) as well as external factors such as if the storage account/container/blob is being accessed by other users, region of the storage account, region of the request sent, and if there's any internal errors on the storage side. I think it's best to leave some of these things up to the user to determine rather than have the SDK set the default judgement, only to be incorrect just because of internal and external factors.

That being I'm not sure how open we are to changing the default value, if we don't have any other reasoning aside from this is what `azcopy` does. We need to ensure that the value being set works on all platforms, blob sizes, environments etc. Sorry if this doesn't help your issue.

**Comment by ohadschn** [comment]
> If it's an automated program, then maybe the retries should be set to 20 then right? However in the case that a storage account is getting throttled, 503, (i.e. automated program overloading the storage account) then there needs to be a back-off mechanism to kick of to allow the storage account .
Seeing as this is an SDK, the reasonable assumption would be that it's used for automated programs. The default is already exponentials backoff...
 
> Another question to ask is how much of this should be heavily relied on the SDK. The SDK cannot predict the manner of the environment (e.g. VM size, concurrency, size of the blob) as well as external factors such as if the storage account/container/blob is being accessed by other users, region of the storage account, region of the request sent, and if there's any internal errors on the storage side. I think it's best to leave some of these things up to the user to determine rather than have the SDK set the default judgement, only to be incorrect just because of internal and external factors.
I agree but at the end of the day you do have to have some default, which is what I'm suggesting to discuss here. At the very least, you could have different defaults for upload (which is typically >10X slower than download).

> That being I'm not sure how open we are to changing the default value, if we don't have any other reasoning aside from this is what `azcopy` does. We need to ensure that the value being set works on all platforms, blob sizes, environments etc. 
That's fair, but perhaps you could discuss it with the `azcopy` folks? The have similar considerations, and I think a lot of experience - `azcopy` has been around for many years...
