### ISSUE TITLE
Increment version for template releases PRs being constantly filed

### ISSUE THREAD

**Issue by pakrym** [Azure/azure-sdk-for-net#14760]
No-one is releasing template but we have ~60 PRs in both open and closed states in the repo.

**Comment by kurtzeborn** [comment]
Maybe what needs to happen here is to add @Azure/azure-sdk-eng to the CODEOWNERS for all of the templates.

**Comment by weshaggard** [comment]
We can also look into options about updating existing version bump PR's instead of opening new ones. @chidozieononiwu we can probably do this by making the version bump branch name only account for the service directory instead of including the pipeline id.

We will of course need to test that strategy and ensure that we don't end up with merge conflicts because they will be updating the same links in the files and if they push a new commit that might fail.
