### ISSUE TITLE
[Text Analytics] Lack text analytics configuration information about US Gov cloud in pipeline.

### ISSUE THREAD

**Issue by Luyunmt** [Azure/azure-sdk-for-net#14790]
In PR [#14633](https://github.com/Azure/azure-sdk-for-net/pull/14633),  tests changed to use a exist text analytics service stored in pipeline .

![image](https://user-images.githubusercontent.com/53427149/91960748-db392f00-ed3c-11ea-889f-6b08c2fabf4f.png)

Such text analytics was prepared in azure cloud. Need to prepare such text analytics in US Gov cloud and China Cloud, and let pipeline configured properly.

BTW, a text analytics service also deployed by file "test-resources.json", but this service would not be used in test.
@jongio @danieljurek

**Comment by maririos** [comment]
Oh no. looks like I broke something? @danieljurek could you explain to me what this other things are that I broke?
We are working on preparing TA for 3.1-preview.2 which is currently only available in a PPE endpoint but next week will be deployed to other regions.

**Comment by danieljurek** [comment]
Chatted w/ @maririos -- These tests will fail because the code in the SDK relies on features in a PPE endpoint hosted by the Text Analytics team. They would need to roll this out to production before we can support these features. 

At this time the failure is "expected" because these features don't exist in the sovereign clouds. 

A larger question here is that we should consider how to handle these situations where the SDK code is ahead of what versions are in production.

**Comment by maririos** [comment]
This behavior has been reverted. @Luyunmt  could you verify again?

**Comment by Luyunmt** [comment]
@maririos Great to know. We will verify while the test branch was Rebase.
