### ISSUE TITLE
[FEATURE REQ] Add more details to RequestFailedException

### ISSUE THREAD

**Issue by ohadschn** [Azure/azure-sdk-for-net#14792]
**Library or service name.**
All of `Azure.Storage`
 
**Is your feature request related to a problem? Please describe.**
Storage operations (in my case ADLS uploads) can fail with exceptions such as the following:
```
System.AggregateException: Retry failed after 6 tries. (Error while copying content to a stream.) (Error while copying content to a stream.) (Error while copying content to a stream.) (Error while copying content to a stream.) (Error while copying content to a stream.) (Error while copying content to a stream.)
 ---> Azure.RequestFailedException: Error while copying content to a stream.
 ---> System.Net.Http.HttpRequestException: Error while copying content to a stream.
 ---> System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host..
 ---> System.Net.Sockets.SocketException (10054): An existing connection was forcibly closed by the remote host.
```

Now, suppose I was trying to upload a 1GB file using chunks of 50MB. 
1. Which of the 20 chunks received this error?
1. Were other chunks successful?
1. What was the average upload speed of each chunk?
1. How long did it take each failing attempt to hit an exception, and how much of the chunk was uploaded before it was hit (including failed attempts for other chunks that were eventually retried and succeeded)?

All of these would be very helpful in fine tuning the retry parameters for each specific case (e.g. decrease upload block size, increase retry attempts, increase HTTP timeout, etc). Right now the lack of the information above forces me into a long guesswork process of trial and error...

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.

**Comment by amnguye** [comment]
Hi,

Have you tried using the progressHandler when you call to upload?
```
public virtual async Task<Response<PathInfo>> UploadAsync(
            string path,
            PathHttpHeaders httpHeaders = default,
            DataLakeRequestConditions conditions = default,
            **IProgress<long> progressHandler** = default,
            StorageTransferOptions transferOptions = default,
            CancellationToken cancellationToken = default)
```

I know that doesn't answer any of your questions, but that's currently what we have in terms of monitoring the progress of the upload. 

We also have logging available on the SDK that way you can track the HTTP requests called and duration I/O as well.
https://docs.microsoft.com/en-us/dotnet/azure/logging

If we have more information on what to recommend for retry parameters (e.g. based on VM size, concurrent threads, blob size) we will let you know. That's always a hard one to recommend to customers due to the fact of different environments, latency, thread count etc.

**Comment by ohadschn** [comment]
Thank you, I will look into these diagnostics logs, it's a good idea (already using IProgress).
