### ISSUE TITLE
[QUERY] Multiple v5 EventProcessors on Event Hub

### ISSUE THREAD

**Issue by dkattan** [Azure/azure-sdk-for-net#14848]
**Query/Question**
What is the expected behavior in the v5 SDK when a second EventProcessor is connected to the EventHub?

Would it disrupt the existing EventProcessor causing it to stop receiving events?

In v4 there was an EpochReceiver where the behavior could be defined.

In v5 it appears similar functionality could be obtained using the [ClaimOwnership](https://docs.microsoft.com/en-us/dotnet/api/azure.messaging.eventhubs.eventprocessorclient.claimownershipasync?view=azure-dotnet#Azure_Messaging_EventHubs_EventProcessorClient_ClaimOwnershipAsync_System_Collections_Generic_IEnumerable_Azure_Messaging_EventHubs_Primitives_EventProcessorPartitionOwnership__System_Threading_CancellationToken_) Method.

The desired outcome is that when production data is cloned for testing, both production and local environments receive events. Currently it appears that when a local environment connects to the Event Hub, production stops receiving events.

@jsquire 
**Environment:**
 - Azure SDK v5 
 - dotnet core 3.1 LTS

**Comment by jsquire** [comment]
Hi @dkattan.  The `EventProcessor<T>` and `EventProcessorClient` types in the v5 client align with the `EventProcessorHost` type in v4.   The v4 `EpochReceiver` that you mention would align with the `EventHubConsumerClient` or `PartitionReceiver` types in v5.

Event processor instances that belong to the same consumer group will coordinate to share partitions evenly between them.  When processors join or leave the consumer group, they will begin claiming partitions and once the work is distributed, the guarantee is that one partition will have a single processor responsible for it.   While the mechanism for load balancing differs slightly between them, the behavior and ultimate guarantee is shared by both the v4 and v5 event processor types.

With respect to your scenario, if I understand correctly, you're looking for multiple readers to be active against a partition where those readers have different purposes (production, test cloning).  Regardless of which type and SDK version you're using, you'll need to have them associated with different consumer groups.  Personally, I'd advise having each consumer group represent the role/intention of the reader for consistent organization.

Where types are concerned, if you'd prefer not to manage partitions directly and take advantage of built-in checkpointing, then `EventProcessorClient` would be a good choice.   You will want to ensure that the processors for each purpose use a different consumer group and Blob Storage container so that they operate independently.

You could also choose to use a set of `EventProcessorClient` instances for your production processing for the reasons mentioned above and use a simpler approach for cloning test data, depending on your needs.   If you're looking to keep a consistent and stateful mirroring of data, using the same appraoch for cloning test data as production is likely your best bet.   If you're looking to do a more simple "copy everything from the first event to the last and then stop" where the ordering/fairness of partitions and performance aren't a concern, then using the [`EventHubConsumerClient::ReadEventsAsync`](https://docs.microsoft.com/dotnet/api/azure.messaging.eventhubs.consumer.eventhubconsumerclient.readeventsasync?view=azure-dotnet) would do that with low friction.  

There are other options for more specific scenarios, but I'll avoid introducing them unless the above thoughts don't meet your needs.

_(Just to be clear, I would advise against using ReadEventsAsync for production processing scenarios.  It is not intended/optimized for that and has non-trivial trade-offs to prioritize ease of use.)_

**Comment by dkattan** [comment]
After the 5th read, I think I get it. 

Internally we were working under the assumption that if we simply changed the blob connection string to point somewhere else we’d be OK. However after your explanation it sounds like the real problem is that we are instanciating EventProcessorClient with constant consumerGroup string “$Default”

When the local dev environments connect, they are being made the reader for one or more partitions, causing production to no longer receive those events. The problem is then made worse if the blob storage connection string and blobName are the same as production as both are updating the checkpoints in the same blob.

I think the best course of action is to use an environmental variable that changes with each unique environment to create the consumer group and checkpoint blob name.

**Comment by jsquire** [comment]
Apologies if that was difficult to parse.   Please let me know if there was a way to phrase that would have been more clear and helpful.

Your proposed approach seems reasonable to me.  So long as you have different consumer groups for production and each local reader and a unique Blob Storage container for each, you'll be able to read concurrently.  Setting those via environment variable is a good option.
