### ISSUE TITLE
[QUERY] EventHubProducerClient thread safety

### ISSUE THREAD

**Issue by jackbond** [Azure/azure-sdk-for-net#14998]
The documentation at:

https://docs.microsoft.com/en-us/dotnet/api/azure.messaging.eventhubs.producer.eventhubproducerclient?view=azure-dotnet

makes no mention of thread safety. We recently upgraded from the old event hub library, and today, for the first time ever, we saw events come through with corrupted data. Is SendAsync thread safe? Currently we use a single producer which is being called by multiple threads, and have millions of events go through without a problem, but I'd like to confirm.

Our environment is

Azure.Messaging.EventHubs Version="5.1.0"
Running on .NetCore 3.1
OS info:
Publisher: MicrosoftWindowsServer  
Offer: WindowsServer  
SKU: 2016-Datacenter  
Version: latest

**Comment by jsquire** [comment]
Hi @jackbond.  Thank you for your question and we regret that you're experiencing difficulties.  With respect to thread-safety, the v5 client offers the same guarantees of the v4 client, though the answer can be considered nuanced depending on how you're thinking of thread-safety.

In the classic sense of the term, the client is thread-safe in that it has no shared mutable state that is unprotected and calling from multiple threads will not result in data races, state corruption, nor do `SendAsync` calls interact with one another within the client.  Each time a set of events is published using a `SendAsync` call,  the events will succeed or fail as a single batch and the ordering of events in that batch will be maintained.

However, since each call to `SendAsync` is an individual unit of work, concurrent calls are not coordinated by the client.  If multiple calls are made to `SendAsync` concurrently, there are no guarantees that those calls will complete in the order that they were made on the client due to contention around network resources, network latency, intermittent failures and retries, and similar.  That also means that batches of events published concurrently may be received by the Event Hubs service in a different order than the `SendAsync` calls were made.

I'd like to better understand the statement `we saw events come through with corrupted data`, if you're willing to share details.  Can you tell me what you're seeing and why the events were considered corrupt?

**Comment by jackbond** [comment]
@jsquire With regards to thread safety, your response addresses my only concern, which could be summarized as...

Does each thread need its own client?

And your answer appears to be no. In regards to ordering, we don't happen to care, but I appreciate the thoroughness of your answer.

As to "we saw events come through with corrupted data", we compress our data prior to enqueuing it, and have dequeued and decompressed hundreds of millions of events without a problem. A couple days ago, after dequeuing an event, we failed on the decompress step (never happened before), so we're left wondering if data was corrupted in transit, if there was a compression error and we enqueued bad data, or something completely unknown happened.

Since this is the first glitch we've seen after millions of events, and who knows when it might happen again, we're adding some code to handle the decompression exception. I'm also now including a hash of the enqueued data in the event properties. to help diagnose any potential future issue. So now it's just a waiting game. :)

The documentation I included in my initial post makes no mention of thread safety. I'm honestly surprised it isn't a checkbox requirement for every Microsoft documentation article as this point. You guys might want to add some comments in regards to the EventHubProducerClient. We actually have a Polly Cache <string, EventHubProducerClient> where the key is the connection string. Thanks again for the timely response.

**Comment by jsquire** [comment]
> Does each thread need its own client?

No.    _(just to make that definitive, since it seemed that I left some doubt)_

> I'm also now including a hash of the enqueued data in the event properties. to help diagnose any potential future issue. 

That's exactly what I would have suggested.  For what its worth, we use that approach in our stress scenarios, where we include verification for different types of body formats.  I've seen a few rare cases where we weren't able to process the event in the way we expected, but thus far it's always been traced back to an error in how we formed the event.

The event body is treated as an opaque stream of bytes, that we just copy from one place to another when we serialize for network transmission.  It's not impossible that there's an obscure corner case that we haven't encountered.  Should you end up seeing this behavior in the future, I'd definitely be interested in the details and helping to troubleshoot.

> The documentation I included in my initial post makes no mention of thread safety. I'm honestly surprised it isn't a checkbox requirement for every Microsoft documentation article as this point. You guys might want to add some comments in regards to the EventHubProducerClient.

Thank you for the feedback.  I'll see what I can do to get that added into the official documentation.
