### ISSUE TITLE
Add a Refresh Token Method for SDK Methods that invoke Azure Data Factory Pipeline

### ISSUE THREAD

**Issue by baskarmib** [Azure/azure-sdk-for-net#15020]
**Library or service name.**
Azure DataFactory Pipelines can be created and invoked using the .Net SDK as mentioned in the below documentation. 
https://docs.microsoft.com/en-us/azure/data-factory/quickstart-create-data-factory-dot-net
 
**Is your feature request related to a problem? Please describe.**
What feature would you like to get added? What problem is it solving?

Azure DataFactory Pipeline SDK methods support execution of the pipeline by creating a datafactory client. If we use singleton pattern and create the client only once, future requests to invoke the pipeline fails with an access token expired message. 

During these scenario currently we have to create a new client to get a new access token. It would be great to add a Refresh Token method to the client, so that we can reuse the same client and get new token when current token is expired.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by markcowl** [comment]
@baskarmib Unfortunately, that document is pointing you in the direction of using a token credentials with an access token rather than using a self-renewing token.  There are two ways you can do this:

(1) Use the existing Microsoft.Rest.Client.ClientRuntime.Azure.Authentication library to create  a self-renewing credential from your login: https://docs.microsoft.com/en-us/dotnet/api/microsoft.rest.azure.authentication.usertokenprovider.createcredentialsfromcache?view=azure-dotnet#Microsoft_Rest_Azure_Authentication_UserTokenProvider_CreateCredentialsFromCache_System_String_System_String_System_String_.  There are also some methods here fir creating a self-rnewing token from your login credentials.

(2) Implement a self-renewing token by creating an ITokenProvider using your AuthenticationContext from the ADAL call.  Here is the constructor that takes a TokenProvider: https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/mgmtcommon/ClientRuntime/ClientRuntime/TokenCredentials.cs#L87, and here is an implementation of a token provider using your authentication context: https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/mgmtcommon/Auth/Az.Auth/Az.Authentication/UserTokenProvider.cs#L276  This code defers the decision on whether to refresh the token to the ADAL library, which will automatically refresh the token when it is near expiry)

Unfortunately, ADAL doesn't provide public APIs that would allow libraries to renew access tokens using a refresh token, so the best that we can do is to create credentials based on your AuthenticationContext (which both of these methods do).

**Comment by markcowl** [comment]
Closing as resolved.

**Comment by baskarmib** [comment]
The current methods expect a username to be provided as part of the input. Is there a way to implement the same using applicationId, tenantId and authenticationKey?
