### ISSUE TITLE
[BUG] Microsoft.Azure.Search does not respect the nulls-first ordering when sorting in ascending mode

### ISSUE THREAD

**Issue by jsancho** [Azure/azure-sdk-for-net#15093]
**Describe the bug**

The [official documentation](https://docs.microsoft.com/en-us/rest/api/searchservice/search-documents) for Azure Search Cognitive Services quotes the following

> If there are null values in the sort field, nulls appear first in asc order and last in desc order. 

And that's precisely how it works when querying an index directly from the Azure Portal when using `$orderby` 
However, when using the `SearchIndexClient` from the Azure SDK, the records with null values are retrieved last when sorting in ascending mode.

Sorting in descending order works as expected with the null values coming last.

**Expected behavior**
When sorting by a field that includes nulls, the records with nulls should appear first.

**Actual behavior (include Exception or Stack Trace)**
What is the actual behavior?
When using ascending order for a field that includes nulls, those null records are retrieved last.

**To Reproduce**
Steps to reproduce the behavior (include a code snippet, screenshot, or any additional information that might help us reproduce the issue)

I have forked the quickstart (Hotels) example to reproduce the issue more easily.
https://github.com/jsancho/azure-search-dotnet-samples/commit/85271d48c688fffc2b9f87f259aae4880bd91fc0

The `Hotel` class now has an additional `Dummy` property.
From the 4 hotels: 2 have actual values, the other 2 have nulls.

1. Download the forked quickstart
2. Add `searchServiceName` and `SearchServiceAdminApiKey` to appsettings.json
3. Run the project

**Environment:**
 - Name and version of the Library package used:  Microsoft.Azure.Search 10.1.0
 - Hosting platform or OS and .NET runtime version: Windows 10, .Net Core 3.1
 - IDE and version : Visual Studio 2019

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.

**Comment by jsquire** [comment]
//cc: @tg-msft

**Comment by brjohnstmsft** [comment]
@jsancho You're seeing this sorting behaviour because version 10 of Microsoft.Azure.Search is targeting version 2019-05-06 of the REST API, which has a known bug around sorting of nulls. This has been fixed in API version 2020-06-30. To use that API version from .NET, please upgrade to the new .NET SDK, [Azure.Search.Documents](https://www.nuget.org/packages/azure.search.documents). There is a migration guide [here](https://docs.microsoft.com/azure/search/search-dotnet-sdk-migration-version-11).

Please let us know if you have further questions about this.

**Comment by jsancho** [comment]
Well, that definitely explains it then!

I did give the v11 library a shot but I got stuck when I didn’t find a way
to port the attributes on the models.
E.g IsSortable, IsFilterable, etc

Is that still available or planning to be at some point?
We have plenty of models and it would be significant work to port them to
fluent definitions.

**Comment by brjohnstmsft** [comment]
@jsancho `FieldBuilder` support has just shipped in the latest version (@tg-msft or @heaths please correct me if I'm wrong). I'm seeing the new attributes in the [SDK reference docs](https://docs.microsoft.com/dotnet/api/azure.search.documents.indexes.searchablefieldattribute?view=azure-dotnet). They've been consolidated into fewer attributes since v10, but conceptually they work the same.

**Comment by tg-msft** [comment]
Yes and https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/search/Azure.Search.Documents/samples/Sample04_FieldBuilderIgnore.md is the best sample we've got at the moment.  If you try to migrate and run into trouble, just ask here.

**Comment by jsancho** [comment]
I've had a pretty good go at porting most of our indexing and querying of documents. Thanks so much for all the input!

I can confirm that the null-ordering is indeed solved with this version of the library and API. Besides, I quite like the new API surface, it makes for more concise and understandable code.

@tg-msft I got stuck with the spec for `SearchOptions`, though, as some properties are designed as read-only, so AFAIK it's not possible to specify params for them.

I specifically need access to
- OrderBy
- SearchFields
- Select

but I'd say that all of them should be writeable, e.g. `HighlightFields`, `Facets`, etc

There's a usage example in azuresdkdocs that cannot be compiled with the syntax as it is specified. I was trying to do something quite close to it.
https://azuresdkdocs.blob.core.windows.net/$web/dotnet/Azure.Search/11.0.0-preview.1/api/index.html#searchoptions

```
int stars = 4;
SearchOptions options = new SearchOptions
{
    // Filter to only ratings greater than or equal our preference
    Filter = SearchFilter.Create($"rating ge {stars}"),
    Size = 5, // Take only 5 results
    OrderBy = new[] { "rating desc" } // Sort by rating from high to low
};
```

Could you please advice?

**Comment by brjohnstmsft** [comment]
@jsancho The properties can't be set, but the collections themselves can be modified, so you'll have to call `Add`. We're discussing options for making this better in a future release.

**Comment by heaths** [comment]
Per [guidelines](https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/guidelines-for-collections#collection-properties-and-return-values), collection properties in the Azure SDK for .NET are not settable. This can lead to downstream issues like `NullReferenceException`s.

Instead, you can use the collection initializer pattern like so:

```csharp
SearchOptions options = new SearchOptions
{
  // ...
  OrderBy = { "rating desc" },
};
```

Or, after initialization, use `Add` on the collection properties.

**Comment by brjohnstmsft** [comment]
Thanks @heaths. This is only the second time I've ever seen the collection initializer syntax. I'll be sure to suggest that from now on.

**Comment by heaths** [comment]
For general information on collection initializers, see <https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/object-and-collection-initializers#collection-initializers>. Basically, anything that implements `IEnumerable<T>` and has an `Add` method (that takes a `T` or otherwise) can use the collection initializer pattern.

The main reason is to make sure collections are never null or inadvertently have previous contents erased by assigning a new collection or `null`. But, as @brjohnstmsft said, we have heard this feedback several times and are considering options for future releases.

**Comment by jsancho** [comment]
Brilliant, thanks everyone for the tips on the collection initializer, as well as the links on the best practice guidelines.

closing the bug, as we've already gone way beyond the call of duty :)
