### ISSUE TITLE
[FEATURE REQUEST] Expose equivalent of track 1 MD5 FIPS compliance toggle

### ISSUE THREAD

**Issue by pharring** [Azure/azure-sdk-for-net#15422]
**Query/Question**

I'm upgrading my app service from the WindowsAzure.Storage SDK to the Azure.Storage.Blobs SDK.
In my app startup, I have this code:
```csharp
    // Use FISMA MD5 setting for verifying blob blocks. This avoids the default .NET MD5
    // crypto algorithm which is unavailable when the OS is set to FIPS compliant mode.
    CloudStorageAccount.UseV1MD5 = false;
```

That property is described here: https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.storage.cloudstorageaccount.usev1md5?view=azure-dotnet

**Is there an equivalent setting in the new SDK?**

**Environment:**
 - Name and version of the Library package used: Azure.Storage.Blobs 12.6.0]
 - Hosting platform or OS and .NET runtime version: Windows, .NET 4.6.2
 - IDE and version : Visual Studio 16.8 preview.

**Comment by Predictor** [comment]
@jsquire is there any progress on this request?

**Comment by jsquire** [comment]
Hi @Predictor.   Unfortunately, I was just first triage for this issue;  I don't have insight into its current status nor what process the storage team is using for their triage and tracking.   We would need a member of @xgithubtriage for insight.

**Comment by jaschrep-msft** [comment]
@pharring apologies for losing this feature request. We had intended to address this after refactoring the public transactional hashing API with https://github.com/Azure/azure-sdk-for-net/pull/23056, but that PR was met with delays. I will be investigating this as a feature request.

**Comment by jaschrep-msft** [comment]
With completion of #27253 I have looked into this feature request. I'm afraid I don't understand what the original feature in the legacy storage library was fulfilling. My understanding of FIPS is that it regulates which algorithms are acceptable for use and that MD5 is simply not FIPS compliant. While I understand that in this use case it is just being used as a checksum for transfers, it still seems that the legacy SDK was just attempting to skirt a compliance feature of the operating system.

Meanwhile, the Storage service has supported a transactional CRC-64 with custom polynomial for some time now, and the mentioned issue's completion has provided support for that checksum algorithm in the modern .NET v12 storage library. This algorithm also provides better performance than MD5. We encourage developers to migrate to CRC-64 usage rather than sticking with MD5.

If I'm not understanding the use case for this feature request, feel free to reopen discussion.
