### ISSUE TITLE
[EventHubs] Enable SchemaRegistry samples in live smoke tests

### ISSUE THREAD

**Issue by MiYanni** [Azure/azure-sdk-for-net#15464]
Relates to: https://github.com/Azure/azure-sdk-for-net/pull/15433

At the time of writing, the SchemaRegistry service is not in the public cloud. Thus, making Azure templates to create resources for it is not feasible. Once SchemaRegistry resources are able to be created normally, a template needs to be made for the SchemaRegistry sample in EventHubs. Then, enable this scenario in the smoke test runner.

**Comment by jsquire** [comment]
Because Schema Registry is a separate service, a sample demonstrating integration between it and Event Hubs should be stand-alone and live in the root [samples](https://github.com/Azure/azure-sdk-for-net/tree/master/samples) area with the other cross-service examples.   Since those samples are integrated with the common [SmokeTests](https://github.com/Azure/azure-sdk-for-net/tree/master/common/SmokeTests), closing this issue as it is no longer needed.
