### ISSUE TITLE
Add support for JWE to Azure.Security.KeyVault 4.1+ or guidance on safely rolling keys

### ISSUE THREAD

**Issue by knightpfhor** [Azure/azure-sdk-for-net#15596]
**Library or service name.**
Azure.Security.KeyVault
 
**Is your feature request related to a problem? Please describe.**
Key Vault has features that make creating new versions of certificates and secrets easy.  However, it order to be able to safely expire a keys or certificate, you need to be able to keep track of which keys you have used to encrypt and sign data you already have.  From my research it would seem that JWE offers this ability.  It seems that all of the base components already exist in the Key Vault client libraries so it would be possible to create your own implementation, but this is an area where it would be easy to make a mistake, so having a dependable implementation would be beneficial.

If using JWE in this way is a terrible idea, then some documented guidance on how to deal with rolling keys would be a good alternative.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by heaths** [comment]
We do have some samples for secret rotation at https://docs.microsoft.com/en-us/samples/browse/?products=azure-key-vault&languages=csharp, but Key Vault does not keep information about what certificate you used to encrypt, sign, or wrap plaintext. That would be required by the application, whether that's storing which key ID was used, or to read that from the payload.

How the data is formatted and stored is also up to the application. Different applications have different requirements, so we really don't want to push a certain format or take dependencies that other applications won't need. For example, you can use [System.IdentityModel.Tokens.Jwt](https://nuget.org/packages/System.IdentityModel.Tokens.Jwt) to format a JWE fairly easily. See <https://www.scottbrady91.com/C-Sharp/JSON-Web-Encryption-JWE-in-dotnet-Core> for a good post on how to use it.

We are considering getting an `X509Certificate2` since `KeyVaultCertificate.Cer` only contains the public key, and we are tracking that in #12083. Would that be sufficient in this case?

**Comment by knightpfhor** [comment]
None of those options help me much in my situation, so I've rolled my own solution.

Knowing when a key is rotated (in the associated sample) is useful to ensure that you have the most up to date set of keys, but it doesn't help much with knowing which of the available keys you need to use to decrypt data that has been presented to you.
