### ISSUE TITLE
Multiple HTTPS error and long wait time when combine MSI and local development for KeyVault access [BUG]

### ISSUE THREAD

**Issue by bernardjeef** [Azure/azure-sdk-for-net#15626]
**Describe the bug**
Localhost connection to Keyvault on startup will fallback multiple HTTPS requests before working and will cause long waiting time on startup. There is 1 minute delay before it start working. 

**Expected behavior**
I would expect that the Azure Keyvault SDK does not try to get keyvault secrets without bearer.

**Actual behavior (include Exception or Stack Trace)**
What is the actual behavior?
![image](https://user-images.githubusercontent.com/17995992/94867021-66761500-040e-11eb-869a-b5bfc5e79548.png)

**To Reproduce**

1. Create the infra from here [https://github.com/hugogirard/devOpsMonolith](https://github.com/hugogirard/devOpsMonolith)
2. Add your personal account on keyvault accessPolicy and give access to GET/LIST secrets
3. Open the project in Visual Studio and make sure you are logged in Azure Service Authentification.

Here is the startup : 
![image](https://user-images.githubusercontent.com/17995992/94867944-2dd73b00-0410-11eb-8fad-d8a251f8d93f.png)

**Environment:**
![image](https://user-images.githubusercontent.com/17995992/94867988-434c6500-0410-11eb-9a53-6d60618133c5.png)
 - IISExpress .Net Core 3.1
 - Visual Studio Enterprise 2019 16.7.2

**Comment by jsquire** [comment]
//cc: @schaabs

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team members best able to assist.

**Comment by heaths** [comment]
Key Vault issues a challenge and responds with a 401, to which the challenge is authenticated and sent back. Given that Microsoft.Azure.KeyVault is deprecated and that we made some concurrency improvements to this challenge behavior in our newer packages, we recommend you upgrade to [Azure.Security.KeyVault.Secrets](https://www.nuget.org/packages/Azure.Security.KeyVault.Secrets). For ASP.NET configuration, you can use newer versions of [Microsoft.Configuration.ConfigurationBuilders.Azure](https://www.nuget.org/packages/Microsoft.Configuration.ConfigurationBuilders.Azure/) that use this packge.

This is still going to get an HTTP 401 response, however, but fewer if you have concurrent requests since we minimally block the threads until we can issue a challenge response.

**Comment by heaths** [comment]
We will consider a challenge-free auth flow as well: #15651
