### ISSUE TITLE
[FEATURE REQ] Use default credentials in test framework

### ISSUE THREAD

**Issue by bquantump** [Azure/azure-sdk-for-net#15663]
**Library or service name.**

Common TestFramework 
 
**Is your feature request related to a problem? Please describe.**

As of now, one must set a bunch of environment variables to run a test live or in record mode. 

We should change this to use Azure Default credentials. This would also be in line with how python sdk and Azure CLI do things. 
https://docs.microsoft.com/en-us/dotnet/api/overview/azure/identity-readme

**Comment by pakrym** [comment]
You don't have to set them manually, use the `New-TestEnvironment` script with `-OutFile` parameter and you would both get your test resources deployed and auth configured.

**Comment by bquantump** [comment]
> You don't have to set them manually, use the `New-TestEnvironment` script with `-OutFile` parameter and you would both get your test resources deployed and auth configured.

Why not use azure default credentials? This seems to be the easiest way to do this and is cross platform friendly. Also, some of develop in Ubuntu and this scripts are not friendly to that environment.

**Comment by pakrym** [comment]
>Why not use azure default credentials?

Doesn't always work on CI

**Comment by bquantump** [comment]
> > Why not use azure default credentials?
> 
> Doesn't always work on CI

That seems like a CI issue then, since CLI works just fine with it. I mean, I'd be will to fix the CI to do this.

**Comment by pakrym** [comment]
Let's explore what we can do here. cc @heaths

**Comment by heaths** [comment]
Even if we authenticated using `DefaultAzureCredential`, most - if not all - tests require other environment variables. Given this, is there much advantage to bifurcating authentication and other variables? Seems like any issues would require more troubleshooting. Also, not everyone may have the CLI or Az modules installed. (E.g. I only install azure-cli in WSL2 because Python is too slow on Windows.) What we have now works consistently across platforms and environments without additional dependencies.

Just as a point of clarification, at the time I wrote the TestResources scripts, `DefaultAzureCredential` didn't read from the CLI, VS, or anything other than the original stuff (e.g. env vars).

**Comment by bquantump** [comment]
> Even if we authenticated using `DefaultAzureCredential`, most - if not all - tests require other environment variables. Given this, is there much advantage to bifurcating authentication and other variables? Seems like any issues would require more troubleshooting. Also, not everyone may have the CLI or Az modules installed. (E.g. I only install azure-cli in WSL2 because Python is too slow on Windows.) What we have now works consistently across platforms and environments without additional dependencies.
> 
> Just as a point of clarification, at the time I wrote the TestResources scripts, `DefaultAzureCredential` didn't read from the CLI, VS, or anything other than the original stuff (e.g. env vars).

Hey Heath,

Thanks for the reply.

What are these other environment variables? The only one we found that was need, once default creds was implemented, was the subscription ID, which we worked around (We only tested our mgmt client track 2 SDKs). Also, I don't foresee mgmt plane new track 2 test needing extra environment variables at all. We have only prototyped against our mgmt plane sdks, and everything works there, haven't expand beyond that, though. The main advantage is to lower the risk of client secrets being leaked so developers don't need to have this set in environment variables etc. Especially since service teams will be writing the test in the future and it should be simple as possible to authentic, the point of default credentials. (a lot of service teams are logged in with VS or VsCode as well).

Also, why would we need to worry about someone not having the CLI installed? This is not required for azure default credentials (Also curious (don't need to answer) how much slower the CLI is on windows for you; I've used it on windows and it was not that slow for me. The only difference one should see is that GCC is more optimized for Linux and not windows, which why there is a difference, network stack is also more optimized on Linux, but this is a small speed up.)

Also, what exactly does this scripts ( TestResources script) do?

**Comment by heaths** [comment]
For `DefaultAzureCredential` to check if the azure CLI has authenticated, you need the azure CLI to authenticate. To my knowledge, that's the only thing that creates the cached credentials. `DefaultAzureCredential` doesn't create them - merely checks for them, if configured to (by default).

Other services have many other variables. For Key Vault - the first consumer of these scripts - there's also `AZURE_KEYVAULT_URL`, `KEYVAULT_SKU`, `CLIENT_OBJECTID`, `BLOB_STORAGE_ACCOUNT_NAME`, `BLOB_PRIMARY_STORAGE_ACCOUNT_KEY`, and `BLOB_CONTAINER_NAME`. Search has `SEARCH_SERVICE_NAME`, `SEARCH_ADMIN_API_KEY`, `SEARCH_QUERY_API_KEY`, `SEARCH_STORAGE_NAME`, `SEARCH_STORAGE_KEY`, and `SEARCH_COGNITIVE_KEY`. For any service, see _test-resources.json_ in its _sdk/<service>_ folder. The scripts not only provision the resources, but work with the ARM templates and other internal script code to generate information - in the form of environment variables - that tests require. Authentication is only one small part of that workflow.

As pointed out, you don't need to set these variables yourself. In fact, we recommend you don't. Because other variables may be needed, you should use the _eng/common/TestResources/New-TestResources.ps1_ script. You can run `help eng/common/TestResources/New-TestResources.ps1` for more information, or check the markdown file with the same name in the same directory, just with the _.md_ file extension. This script is the fastest, easiest, and most complete way of provisioning test resources.

For the Azure/azure-sdk-for-net on Windows, you should also pass `-OutFile` so you don't have to restart Visual Studio or whatever IDE you use. The test resources will pick up those new variables automatically.

**Comment by nisha-bhatia** [comment]
Hi, thank you for your updates. I, along with Steve, had already started prototyping the new test credentials. Please do let me know if we should continue working on the test credentials from our side or should we stop since the impact to the CI could be significant?

**Comment by heaths** [comment]
I think we also should be using a unified test framework within the repos. This makes it easier to support, and roll out changes that impact all SDKs.

Have you looked at eng/common/TestResources - the markdown files, at least? It's easy to use. You just run a command to provisoin, and another to deprovision resources when done. The nightly test runs use this same system, so ad-hoc dev testing and nightly tests run against resources configured exactly the same way.

See https://github.com/Azure/azure-sdk-for-net/tree/master/eng/common/TestResources for an overview and how to get started.

**Comment by bquantump** [comment]
> I think the first thing to figure out is whether you are going to use test-resources arm templates for your tests. Because if you do having the DefaultAzureCredential doesn't buy you much as you need to run New-TestResources anyway.

@pakrym 

How does this resolve the problem of not having to have secrets around and lowering the barrier for entry for RPs team?
I guess I am not seeing why this would be such a issues adding. It makes it much easier for people to use who don't want to setup a service principle, get secrete, etc. 

Most RP test writers on service team I assume will pretty junior, and this makes it super easy for them to use, which is part of the reason for Azure default credentials. Also, if env vars are set, great, it won't effect anything since azure default creds will look for those first.

Now, the users has to be aware of some other things, like Sub ID, or what not.

**Comment by pakrym** [comment]
If you need test resources deployed before running tests it doesn't matter whether we support DefaultAzureCredential or not you would have to run `New-TestResources`. And as soon as you run that the current credential implementation just works.

**Comment by bquantump** [comment]
> If you need test resources deployed before running tests it doesn't matter whether we support DefaultAzureCredential or not you would have to run `New-TestResources`. And as soon as you run that the current credential implementation just works.

So in the test I run let's say, I change some parameters of a resource, say an update, and check that update happened as expected, what credentials would the test use to verify the application can make this change on this resource?

**Comment by pakrym** [comment]
What resource group does your test use? Do you create and remove one every time? Would you like to have the resource you are operating on to be created once or do you recreate it every time as well?

**Comment by bquantump** [comment]
This not for a particular test, it is more abstract than one particular test. 

For background, we don't plan on writing the MGMT test in the future, this will be on the service teams to do. We want it to be as simple as possible for them to write test. Service teams generally know and use azure default credentials. So, question is why add this overhead of creating a new service principle ETC if the user already is logged in with VS or VsCode etc? 

Does " Resource group, service principal are the things that `New-TestResources` would create for you and set in the way tests can read" mean that the environment vars are set for the test framework to read? 

Another question, somewhat tangential here, let's say a test writer wants to randomly generate a name for some resource in the test, how does the test framework get knowledge of that randomly generated name? The test writer needed that randomly generated resource name in the code for test purposes.

(Also note test writers don't universally develop on windows)

**Comment by pakrym** [comment]
>This not for a particular test, it is more abstract than one particular test.
> So, question is why add this overhead of creating a new service principle ETC if the user already is logged in with VS or VsCode etc?

Because most of the time tests need more inputs than just the credential, they need location, subscription, resource group, etc.

We have an established pattern of setting up all these things in a common way by running "New-TestResources" and TestFramework features that support it including making sure things are setup correctly on CI.

>Does " Resource group, service principal are the things that New-TestResources would create for you and set in the way tests can read" mean that the environment vars are set for the test framework to read?

Yes, env vars or a test environment file that doesn't require restarting your dev environment.

>(Also note test writers don't universally develop on windows)

We don't currently support 100% of the features on non-windows but mostly because we didn't hear any asks for that.

>Another question, somewhat tangential here, let's say a test writer wants to randomly generate a name for some resource in the test, how does the test framework get knowledge of that randomly generated name? The test writer needed that randomly generated resource name in the code for test purposes.

I would need more details about your exact scenario to respond. Typically when resources are created as part of arm templates we expose their names as template outputs.

https://github.com/Azure/azure-sdk-for-net/blob/2e1eeadc802aafca02962fbcbc819afb6b35f4ff/sdk/extensions/test-resources.json#L144

and consume via a test environment class https://github.com/Azure/azure-sdk-for-net/blob/ee4200957ef7b53e4502a87ce562339ea021e7fa/sdk/extensions/Azure.Extensions.AspNetCore.DataProtection.Blobs/tests/DataProtectionTestEnvironment.cs

**Comment by bquantump** [comment]
> Because most of the time tests need more inputs than just the credential, they need location, subscription, resource group, etc.

I don't see this being something that prevents default credentials though. Is the argument that if a user has to possibly supply one environment var, we should make them provide all environment vars or run a script to make a new service principle and client secret etc? I think the premise we should work off of his they need to provide want they need for a test, and sometimes they can just use default credentials with a subscription provide either via environment var or default sub in CLI etc. (Especially for MGMT sdk test)

Do you have some broader concern here about this breaking data plane things? 


> We don't currently support 100% of the features on non-windows but mostly because we didn't hear any asks for that.

How are test typically written right now for the data plane SDKs? Are they written by RP owners or someone else?

>I would need more details about your exact scenario to respond. Typically when resources are created as part of arm templates we expose their names as template outputs.

So let's take CosmosDB, as you may know a DB account needs to be azure globally unique since it is put in the DNS, hence must be unique. So let's say I want to generate N number of database accounts in an ARM template, and want those names to be random (Note this should only run when I want the CosmosDB test to run as well since db accounts take awhile to provision). I now in the test want to get the names of those N database accounts.  So is that read from a file? Read from and environment vars?

**Comment by heaths** [comment]
You can set those in an environment variable. The `-OutFile` parameter writes a file, yes, but the `TestEnvironment` class @pakrym referenced earlier makes reading from either transparent. The point is that we want a single unified way of testing to make it easy to support and for developers to onboard onto different services. If each service or language repo has its own way of reporting, it will get difficult to use and support pretty fast. This is why most language repos use this, and it was based on what python was doing.

If there are deficiencies in the current system, please describe them and we can discuss improvements.

**Comment by bquantump** [comment]
> You can set those in an environment variable. The `-OutFile` parameter writes a file, yes, but the `TestEnvironment` class @pakrym referenced earlier makes reading from either transparent. The point is that we want a single unified way of testing to make it easy to support and for developers to onboard onto different services. If each service or language repo has its own way of reporting, it will get difficult to use and support pretty fast. This is why most language repos use this, and it was based on what python was doing.
> 
> If there are deficiencies in the current system, please describe them and we can discuss improvements.

@heaths this was reply to the cosmos question, I assume.

So agreed with the point, " the point is that we want a single unified way of testing to make it easy to support and for developers to onboard onto different services" This the current discussion we are having on our team as well given the feedback we got from a talk with @pakrym last week. 

So some question and comments on the cosmos part only.

Would the scenario creating N number of DB accounts only run for the CosmosDB test? 

It wasn't exactly clear, so if you don't write an output file, are the N comos db accounts written to an environment variable somewhere? 

Test can be optimized by bypassing ARM template setup since all resources must be setup before a test can start. 

Do arm template setups get recorded? I am pretty sure they do not, right?

Note, I think we are somewhat getting away from default credentials.
If the user wants to use them, they can still use ARM template to setup resource using those credentials. This is orthogonal to other environment variables. 

Credentials and other environment setup are two different things.

**Comment by heaths** [comment]
Whatever your ARM template would set up, the `Remove-TestResources.ps1` script undoes because it deletes the whole resource group. As long as you're within a single resource group, there should be no problem.

The point about credentials though is that you can still authenticate as you, using `Connect-AzAccount` (the scripts, being PowerShell, which is cross-platform, use the Az PowerShell module since it's PowerShell-native). But the rest of the script then sets up everything for you. Is there still a concern about credentials then?

If you set up multiple resources, one way or another you still need to get a list of what they are. Packing those into an environment variable - or even using a file if you want - would be necessary either way, correct?

**Comment by JoshLove-msft** [comment]
Just wanted to check in on this - @bquantump have you been able to onboard to the New-TestResources script?

**Comment by pakrym** [comment]
Closing the thread as inactive.
