### ISSUE TITLE
[BUG] Azure.Storage.Blobs BlobUriBuilder doesn't generate correct blob uri's when hosting the emulator on a non-expected HTTP port

### ISSUE THREAD

**Issue by wcabus** [Azure/azure-sdk-for-net#15693]
**Describe the bug**
When calling SDK methods which use BlobUriBuilder to generate the full blob URI, for example `BlobContainerClient.GetBlobClient` using a storage emulator running on a port different than the ones currently supported (10000, 10001, ...), the container name is not being found in the original path.
This bug has been created from #15403 and relates to PR #13124

**Expected behavior**
The blob client points to `http://azurite-azure-storage-emulator.azurite:9100/devstoreaccount1/containername/blobname`

**Actual behavior (include Exception or Stack Trace)**
The blob client points to `http://azurite-azure-storage-emulator.azurite:9100/devstoreaccount1/blobname`

**To Reproduce**

1. Deploy Azurite using Docker on a port like 9100, `docker run -p 9100:10000 mcr.microsoft.com/azure-storage/azurite azurite-blob --blobHost 0.0.0.0`
2. Attempt to create a blob container or access blobs in an existing container, from a .NET Core app or API hosted in another Docker container (we are hosting these in a local Kubernetes cluster)

**Environment:**
- Azure.Storage.Blobs 12.6.0 (this was working in 12.4.4, not tested with 12.5.1)
- .NET Core 3.1

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.

**Comment by amnguye** [comment]
Thanks for submitting this issue. As you mentioned in the other issue which I agree with, it looks like it has something to do with the port number specified. We will look into why this is happening and will update the issue accordingly.

**Comment by mbauerdev** [comment]
Same issue here. I tried different versions, here's the outcome when calling `BlobContainerClient.GetBlobClient(blobName)` 

Version 12.7.0, 12.6.0, 12.5.1 return:
`http://azurite-azure-storage-emulator.azurite:9100/devstoreaccount1/blobname`

Versions 12.4.*, 12.3.0 return:
`http://azurite-azure-storage-emulator.azurite:9100/devstoreaccount1/containername/blobname`

**Comment by devax** [comment]
Same here. Is there a workaround for this? I tried to instantiate like this:
```
BlobContainerClient.GetBlobClient($"{containerName}/{blobName}")
```
But Version 12.8.0 returns: ```http://azurite-azure-storage-emulator.azurite:9100/devstoreaccount1/containername%2Fblobname```

**Comment by amnguye** [comment]
Sorry for the late reply on this. Currently we don't have a mitigation for this bug. I've been attempting to look into the context on why we only accept certain port numbers (since the PR referenced the v11 library for the fix they implemented), however I cannot find it. Also our other storage libraries (java, python) do not have limitations on the port number.

We will try to get in a fix soon where we remove the limitation of the port numbers and aligned with the other storage SDK behaviors.

Thanks for your patience.

**Comment by amnguye** [comment]
Unfortunately the problem with this bug is that there's many ways that a storage account url can be formed/look alongside using port numbers. We are working on a way so that our other language libraries so we can come up with the best solution.
In short, if we fix this bug as it stands right now, it will cause another bug unfortunately.

**Comment by paule96** [comment]
It would be nice to maybe produce an error if the sdks can't find the accountname. And in the error message you can maybe reference to this bug. This would be maybe an """"""Workaround"""""""""

**Comment by navba-MSFT** [comment]
@wcabus Apologies for the delay in fixing this issue. @amnguye Could you please let us know if you have any update on the fix for this issue ?

**Comment by blueww** [comment]
We have a customer repro the similar issue with create blob client, following is the code:

```
const string blobPort = "51264";
const string connectionString =
    "DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=[key];BlobEndpoint=http://localhost:" +
    blobPort + "/devstoreaccount1";

var blobServiceClient = new BlobServiceClient(connectionString);
var blobContainerName = Guid.NewGuid().ToString("D");

BlobContainerClient blobContainerClient = await blobServiceClient.CreateBlobContainerAsync(blobContainerName);

var blobClient = blobContainerClient.GetBlobClient("data");
```
In the last line, `blobContainerClient.GetBlobClient("data")` will lost the container info of the blob.
However, when user port 10000, the container info won't be lost.

Since we allows user to configure the emulator port, hope we can fix this on SDK side.

**Comment by p3t3rix** [comment]
Any news regarding a fix for this ? Would also appreciate if this would be either documented in the azurite documentation since the scenario that the ports for services are not fixed is quite common, especially for an automated integration test scenario

**Comment by ripvannwinkler** [comment]
I just ran into this nasty little bug when my integration test failed in Azure pipelines despite succeeding locally. It's rather disheartening to see such a critical bug left untouched for so long...

**Comment by philipborg** [comment]
Uggly workaround: Use IP instead of hostname... The bug in BlobUriBuilder isn't triggered if it considers the host to be an IP.

**Comment by TomaszChrosniak** [comment]
Hi,

I've ran into the same issue when running azurite in k8s for a repeatable, automated testing environment.
I imagine it all works for connecting to Azure proper, so it's probably not a priority?

---

From what I can see the URI parsing ends up interpreting URIs incorrectly, e.g. for the following:
`http://azurite:30369/local-0/containername`
`BlobUriBuilder` parses it as follows:
scheme: `http`
host: `azurite`
port: `30369`
account name: (empty)
container name: `local-0`

I see that in the constructor, `BlobUriBuilder` is calling out to the `IsHostIPEndPointStyle` extension method
https://github.com/Azure/azure-sdk-for-net/blob/b890d3cd0df5efcc6c7ba4b283867b412c91f2cb/sdk/storage/Azure.Storage.Blobs/src/BlobUriBuilder.cs#L211
implemented as:
https://github.com/Azure/azure-sdk-for-net/blob/b890d3cd0df5efcc6c7ba4b283867b412c91f2cb/sdk/storage/Azure.Storage.Common/src/Shared/UriExtensions.cs#L114-L118
which for checks whether the URI has an IP address
_or_
has specific ports, defined as constants:
https://github.com/Azure/azure-sdk-for-net/blob/b890d3cd0df5efcc6c7ba4b283867b412c91f2cb/sdk/storage/Azure.Storage.Common/src/Shared/Constants.cs#L653

---

If neither are true, it then continues to:
https://github.com/Azure/azure-sdk-for-net/blob/b890d3cd0df5efcc6c7ba4b283867b412c91f2cb/sdk/storage/Azure.Storage.Blobs/src/BlobUriBuilder.cs#L230
which tries to infer the account name from the URI.
This looks for specific subdomains within the host:
https://github.com/Azure/azure-sdk-for-net/blob/b890d3cd0df5efcc6c7ba4b283867b412c91f2cb/sdk/storage/Azure.Storage.Common/src/Shared/UriExtensions.cs#L87-L96
`BlobUriBuilder` provides the following as `serviceSubDomain`:
https://github.com/Azure/azure-sdk-for-net/blob/b890d3cd0df5efcc6c7ba4b283867b412c91f2cb/sdk/storage/Azure.Storage.Common/src/Shared/Constants.cs#L213

I don't know what the requirements for URI parsing were, but this seems like a very specific solution.
I also don't have the complete requirements for it atm, so I can't contribute.

I would like to offer some advice to others running into this issue, instead of what @philipborg suggested:
use the URI form with the `blob` subdomain

In my case the URI would become:
`http://local-0.blob.azurite:30369/containername`

Which works for now.

I hope any of this helps.
