### ISSUE TITLE
appsettings.json Samples for AddAzureClient Extensions

### ISSUE THREAD

**Issue by MooVC** [Azure/azure-sdk-for-net#15722]
**Query/Question**

There are a series of very useful extensions within the SDK to support configuration, some of which take an IConfiguration parameter instead of parameters that explicitly relate to their contextual settings e.g. [AddBlobServiceClient](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.azure.blobclientbuilderextensions.addblobserviceclient?view=azure-dotnet#Microsoft_Extensions_Azure_BlobClientBuilderExtensions_AddBlobServiceClient__2___0___1_).

I have been unable to find any documentation as to the composition of the JSON needed by these extensions. Are there any resources available to support their consumption?  

**Environment:**
- Name and version of the Library package used:
Azure.Messaging.EventHubs 5.2.0
Azure.Security.KeyVault.Secrets 4.1.0
Azure.Storage.Blobs 12.6.0
Microsoft.Extensions.Azure 1.0.0

**Comment by kimjamia** [comment]
I, too, would like to understand how to know the structure of the json configuration. E.g. on [this page](https://learn.microsoft.com/en-us/dotnet/azure/sdk/dependency-injection#store-configuration-separately-from-code) it says that Key Vault has `VaultUri` and Storage has `ServiceUri`. Where can I see what other options there are? What about the options for Service Bus?

**Comment by pallavit** [comment]
@jsquire is there any documentation for the extensions?

**Comment by jsquire** [comment]
There is a [README](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/extensions/Microsoft.Extensions.Azure/README.md) and set of general [samples](https://github.com/Azure/azure-sdk-for-net/tree/main/sdk/extensions/Microsoft.Extensions.Azure/samples).   There is definitely room for improvement here, as the The [MS Docs](https://learn.microsoft.com/dotnet/api/microsoft.extensions.azure?view=azure-dotnet) content uses just the doc comments for each library extension and is overly generic.

The [MS Docs](https://learn.microsoft.com/dotnet/api/microsoft.extensions.azure?view=azure-dotnet) content also looks to be misconfigured and appears under AppConfig, so it's just the doc comments and doesn't have the overview version of the README that it should.   That also makes it difficult to find via search.   

//cc: @danieljurek, @JimSuplizio

**Comment by jsquire** [comment]
I overlooked the official Azure SDK DI docs, which are the most comprehensive and probably where we should be pointing folks:  https://learn.microsoft.com/dotnet/azure/sdk/dependency-injection

We should include a `<seealso>` for these in the extension doc comments.

**Comment by danieljurek** [comment]
The `Microsoft.Extensions.Azure` package is categorized as a `compat` package and doesn't get a full entry in the ToC today. 

(incidentally, the README page is [published](https://learn.microsoft.com/en-us/dotnet/api/overview/azure/microsoft.extensions.azure-readme?view=azure-dotnet) but `compat` packages aren't included in the ToC so it's basically not findable)

Also, the `Microsoft.Extensions.Azure` namespace is present in a number of other packages. We should probably deduplicate this across all of the packages because learn.microsoft.com only shows the first instance in the ToC which means that this is slotted under `Azure.Data.AppConfiguration` instead of packages later in the alphabet (like `Azure.Messaging.EventGrid`).

A couple things we can do here: 

1. Handle this case one-off -- If this is the only `compat` package we care about this might be a good approach.. Are there other packages that need this kind of treatment? 
2. Design a better way to handle these cases if there are multiple packages here

@jsquire, @pallavit -- What do y'all think? Are there other compat packages that we want to handle in this way?

**Comment by jsquire** [comment]
This is really the only data plane package of its type.  The package itself serves as the basis for the extensions that are specific to each service and defined in other packages.    The ArmClient for the management plane works kind of like this, I think.

**Comment by pallavit** [comment]
@danieljurek given @jsquire insights I believe we should special handle only this particular case, designing a better way to handle this scenario given there is only 1 such case may be overkill. Let me know how you would want to handle this?

**Comment by JimSuplizio** [comment]
Hi @MooVC, we deeply appreciate your input into this project. Regrettably, this issue has remained inactive for over 2 years, leading us to the decision to close it. We've implemented this policy to maintain the relevance of our issue queue and facilitate easier navigation for new contributors. If you still believe this topic requires attention, please feel free to create a new issue, referencing this one. Thank you for your understanding and ongoing support.
