### ISSUE TITLE
[QUERY] Azure Storage Blob Change Feed exception

### ISSUE THREAD

**Issue by mkwired** [Azure/azure-sdk-for-net#15831]
The following code throws an `InvalidOperationException` with the message `Segment doesn't have any more events`.  Am I doing some thing wrong?

```lang-cs
public static void ChangeFeedStreamAsync(string connectionString, string continuationToken)
{
    BlobServiceClient blobServiceClient = new BlobServiceClient(connectionString);
    BlobChangeFeedClient changeFeedClient = blobServiceClient.GetChangeFeedClient();

    foreach (var page in changeFeedClient.GetChanges(continuationToken).AsPages())
    {
        Console.WriteLine(page);
    }
}
```

# Environment:
## Azure.Storage.Blobs.ChangeFeed 12.0.0-preview.5
- .NET Core SDK (reflecting any global.json):
- Version:   3.1.402
- Commit:    9b5de826fd
## Runtime Environment:
- OS Name:     Windows
- OS Version:  10.0.17763
- OS Platform: Windows
- RID:         win10-x64
- Base Path:   C:\Program Files\dotnet\sdk\3.1.402\
## IDE and version
- Microsoft Visual Studio Professional 2019
- Version 16.7.5

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.

**Comment by seanmcc-msft** [comment]
Hi,

Mostly likely the change feed for your account doesn't have any events.  Creating and deleting blobs will populate the change feed.

-Sean

**Comment by seanmcc-msft** [comment]
Please re-open if you have further questions.

**Comment by mkwired** [comment]
My test case had unprocessed events, and it was throwing an exception.  Even if all the events had been processed, I do not think throwing an exception is the right way to handle no more events.

**Comment by seanmcc-msft** [comment]
Re-opening.

@tg-msft, @kasobol-msft, what do you think?  I think @mkwired makes a decent point here.

**Comment by seanmcc-msft** [comment]
@mkwired, can you provide some more information about how this situation occurred?  Is it just that you were processing a change feed populated with events, and then hit the end?

**Comment by m2xumb** [comment]
Hey, I am receiving the same error while requesting data from the change feed. It runs on a schedule, i.e. every minute if not already running. It works for some time and then stop working and keeps failing until i reset the cursor. There are more changes in the blob after that (i.e. files get added all the time).

See exception, code and cursor below.

```
System.InvalidOperationException
  HResult=0x80131509
  Message=Segment doesn't have any more events
  Source=Azure.Storage.Blobs.ChangeFeed
  StackTrace:
   at Azure.Storage.Blobs.ChangeFeed.Segment.<GetPage>d__13.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at Azure.Storage.Blobs.ChangeFeed.ChangeFeed.<GetPage>d__14.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at Azure.Storage.Blobs.ChangeFeed.BlobChangeFeedAsyncPageable.<AsPages>d__6.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.Tasks.Sources.ManualResetValueTaskSourceCore`1.GetResult(Int16 token)
   at Azure.Storage.Blobs.ChangeFeed.BlobChangeFeedAsyncPageable.<AsPages>d__6.System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult(Int16 token)
   at System.Runtime.CompilerServices.ValueTaskAwaiter`1.GetResult()
   ...
```

The code I'm using to get the feed:
```
string cursor = await LoadCursorAsync(cursorBlob);
BlobServiceClient client = new BlobServiceClient("...");
BlobChangeFeedClient changeFeedClient = client.GetChangeFeedClient();

IAsyncEnumerator<Page<BlobChangeFeedEvent>> enumerator = changeFeedClient
    .GetChangesAsync(cursor).AsPages(pageSizeHint: 100).GetAsyncEnumerator(cancellationToken);

while (true)
{
    //exception is thrown here!
    var result = await enumerator.MoveNextAsync();

    if (result)
    {
        foreach (BlobChangeFeedEvent changeFeedEvent in enumerator.Current.Values)
        {
            ...
        }

        await SaveCursorAsync(cursorBlob, enumerator.Current.ContinuationToken);
    }
    else
    {
        break;
    }

    if (cancellationToken.IsCancellationRequested)
        break;

}
```

The cursor in question:
```
{"CursorVersion":1,"UrlHost":"<name>.blob.core.windows.net","EndTime":null,"CurrentSegmentCursor":{"ShardCursors":[{"CurrentChunkPath":"log/00/2020/10/20/1000/00000.avro","BlockOffset":24210559,"EventIndex":0}],"CurrentShardPath":"log/00/2020/10/20/1000/","SegmentPath":"idx/segments/2020/10/20/1000/meta.json"}}
```

***Library: Azure.Storage.Blobs.ChangeFeed 12.0.0-preview.5***
***Environment:***
.NET Core SDK (reflecting any global.json):
 Version:   3.1.302
 Commit:    41faccf259

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64

***IDE: Microsoft Visual Studio Professional 2019***
Version 16.6.3

**Comment by amnguye** [comment]
@mkwired Following up. Could you provide some more information (e.g. environment, event(s) state) on how the situation occurred? That way we can get a repro

@m2xumb So it works if you reset the cursor when the hour changes (e.g. you would reset the cursor once the time went from 10.59 to 11.00?) There might be a problem with the cursor but we have to take some time to reproduce the issue.

**Comment by m2xumb** [comment]
@amnguye Yes, as a workaround, whenever the error occurs, i use the current time to reinitialize the ChangeFeedClient:

`enumerator = changeFeedClient
                            .GetChangesAsync(DateTimeOffset.UtcNow).AsPages(pageSizeHint: 100).GetAsyncEnumerator(cancellationToken);`

afterwards i save the resulting cursor and use it until the next time the hour changes.

**Comment by mivalkonen** [comment]
I get the same InvalidOperationException very frequently, when using continuationToken cursor on GetChangesAsync. GetChangesAsync operation without parameters seems to work just fine, so I think that there is a problem on cursor construction/handling.

I have been querying for changes in 1 minute intervals. Most of the queries work, but every now and then the exception occurs. Seems that there has to be changes in order to reproduce the problem, meaning that when no changes have been made and the enumerator is "empty", the exception doesn't pop up. An easy way to reproduce the problem seems to be that I make changes to blob storage and query those changes (with the 1 minutes interval ongoing) and after that wait for a long while (like an hour) without making any changes and then make changes again => on next GetChangesAsync the enumeration fails. 

Could be that @m2xumb is right about the cursor failing on every hour change, but I have been getting this same exception intra-hour also. Problem with the mentioned cursor reset workaround is that it misses the last batch of changes when the cursor is reset. Unfortunately this makes me think that this library is very unreliable.

Here is an example of "faulty" continuationToken and call stack of the "Segment doesn't have any more events" exception that occurs:
cursor:
"{\"CursorVersion\":1,\"UrlHost\":\"xxx.blob.core.windows.net\",\"EndTime\":null,\"CurrentSegmentCursor\":{\"ShardCursors\":[{\"CurrentChunkPath\":\"log/00/2021/03/29/0600/00000.avro\",\"BlockOffset\":7762,\"EventIndex\":0}],\"CurrentShardPath\":\"log/00/2021/03/29/0600/\",\"SegmentPath\":\"idx/segments/2021/03/29/0600/meta.json\"}}"
exception:
"at Azure.Storage.Blobs.ChangeFeed.Segment.<GetPage>d__13.MoveNext()\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at Azure.Storage.Blobs.ChangeFeed.ChangeFeed.<GetPage>d__14.MoveNext()\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at Azure.Storage.Blobs.ChangeFeed.BlobChangeFeedAsyncPageable.<AsPages>d__6.MoveNext()\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Threading.Tasks.Sources.ManualResetValueTaskSourceCore`1.GetResult(Int16 token)"
