### ISSUE TITLE
CloudConfigurationManager doesn't respect file attribute on appSettings

### ISSUE THREAD

**Issue by PilotBob** [Azure/azure-sdk-for-net#1594]
A common method of hiding secrets from source control is to use the file= attribute of the appSettings element in web.config/app.config. 

However, it seems the cloud configuration manager doesn't support this element or it is ignored.

Can this support be added, or if it's there, what am I doing wrong? I have the following file= in my app.config appsettings:

file="%APPDATA%\myappname\AppSettingsSecrets.config

and the file is in that location. I also tried it with the absolutepath, didn't work either.

**Comment by hovsepm** [comment]
@PilotBob Currently we only fix existing bugs and do not add new features to CloudConfigurationManager. However since this is a publicly available source code please feel free to create a PR with the functionality that will address your scenario and be useful for other customers. We will review it, help you get it merged and publish new package to Nuget.org.

**Comment by PilotBob** [comment]
So, does that mean this class is deprecated?
