### ISSUE TITLE
[FEATURE REQ] PS 7 is not cross platform friendly

### ISSUE THREAD

**Issue by bquantump** [Azure/azure-sdk-for-net#15985]
**Library or service name.**
Scripts here (https://github.com/Azure/azure-sdk-for-net/tree/master/eng/common/TestResources) require PS 7. PS is not supported on Ubuntu 20.04 (https://docs.microsoft.com/en-us/powershell/scripting/install/installing-powershell-core-on-linux?view=powershell-7)

**Is your feature request related to a problem? Please describe.**
Some MGMT partners use Ubuntu 20.04 (Contractors)

**Comment by heaths** [comment]
See https://github.com/PowerShell/PowerShell/issues/12626. Support is coming, but you can use the tarball today it seems. The snap may also work since it's just a container. There's really no good alternative to cross-platform scripts either, and the Azure PowerShell modules have fewer dependencies to install.

**Comment by bquantump** [comment]
Works on WSL, but seems to have issues installing straight onto 20.,04 OS. Can look into that more. What are PS 7 specific features that won't work with PS 6 btw?

**Comment by heaths** [comment]
Converting a SecureString to plain text. That was added in PS7. You should be able to use the PS7 tarball, though.

**Comment by kurtzeborn** [comment]
We believe this is not an issue anymore.  We're also currently in the process of moving our pipelines to ubuntu 20 by default, so if this is still a problem, we'll find out really quickly. :-)
