### ISSUE TITLE
Significant changes to ComputeManagementClient constructor.

### ISSUE THREAD

**Issue by billmcknight1953** [Azure/azure-sdk-for-net#1620]
There seems to be significant changes to the constructor for **ComputeManagementClient** in constructor in the package **Microsoft.Azure.Management.Compute** between versions 9, 10, and even further changes in version 11.  Is there some documentation for the new constructor?  Also, can someone clarify the difference between **Microsoft.Azure.Management.Compute** and **Microsoft.WindowsAzure.Management.Compute**?

**Comment by hovsepm** [comment]
@billmcknight1953, libraries with WindowsAzure in the namespace are RDFE based management libraries, whereas Azure are ARM based libraries. 
Version 11 of Compute library is a preview and is DNX based (cross platform) and is generated from [swagger](www.swagger.io) service [specification file](https://github.com/hovsepm/azure-rest-api-specs/blob/master/arm-compute/2015-06-15/swagger/compute.json) while versions up to 9 are generated from internal service metadata. Due to difference in the specification format Compute client has a lot of differences in the generated method.
