### ISSUE TITLE
Azure.AI.MetricsAdvisor Readme issues

### ISSUE THREAD

**Issue by Tianyun-G** [Azure/azure-sdk-for-net#16257]
1.
Section [link](https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/metricsadvisor/Azure.AI.MetricsAdvisor#data-feed)

![image](https://user-images.githubusercontent.com/65581162/97137584-167e3a00-1791-11eb-951b-677327e4d631.png)
Suggestion:
Update to: It's the entry point of `data, and therefore,` 

@jongio for notification.

**Comment by kinelski** [comment]
Thank you for pointing this out.

> Suggestion:
> Add hyperlink: https://westus2.dev.cognitive.microsoft.com/docs/services/MetricsAdvisor/operations/createDataFeed

This is not a link to the SDK API, though. It's for the REST API. We couldn't add a link for the documentation in the first beta because there was no documentation to begin with.

Let's go with: https://azure.github.io/azure-sdk-for-net/metricsadvisor.html
Let me know if there are any concerns.

**Comment by Tianyun-G** [comment]
@kinelski Okay, thank you. I have updated this issue.
