### ISSUE TITLE
[Microsoft.Azure.ServiceBus] Test Failures: ReceiveLotOfMessagesWithoutSettling

### ISSUE THREAD

**Issue by jsquire** [Azure/azure-sdk-for-net#16265]
# Summary

The test `ReceiveLotOfMessagesWithoutSettling` has been consistently failing nightly test runs on the Linux platform, with the number of received messages not matching the number sent.  

# Scope of Work

- Adjust the test such that the results are consistent across platforms.

- Mark the test as enabled rather than skipped.

# Success Criteria

- `ReceiveLotOfMessagesWithoutSettling` has been updated to provide consistent results across platforms.

- `ReceiveLotOfMessagesWithoutSettling` has been enabled and is executed as part of the nightly runs.

- The existing test suite continues to produce deterministic results and pass reliably.

# References

- [Example run with failures](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=588010&view=ms.vss-test-web.build-test-results-tab&runId=14397802&resultId=100537&paneView=debug)
- [Example run with failures](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=590275&view=ms.vss-test-web.build-test-results-tab&runId=14429006&resultId=100597&paneView=debug)

**Comment by jsquire** [comment]
//cc: @yvgopal, @DorothySun216

**Comment by axisc** [comment]
Closing this because we're tracking this in an internal tracking item.

**Comment by DorothySun216** [comment]
@jsquire What environment is the test failing at? Is it standard or premium? I can't see details from the log. I also cannot repro it locally. The tests are consistently passing. Can you upgrade to Nuget dependency 5.1.1, https://www.nuget.org/packages/Microsoft.Azure.ServiceBus/ to see if the tests are passing? There is a Singleton concurrent opening & closing bug that got fixed in the AMQP library we depend on, which might affect the receiver close problem in the test. Can you try updating the nuget and see?

**Comment by jsquire** [comment]
These were failing the nightly runs via Azure Pipelines.  Each nightly run pulls the most recent source and runs the tests against it.   You can verify or kick-off runs by using the internal pipeline "net - servicebus - tests.data".    Looking over recent history,  `Microsoft.Azure.ServiceBus` has been continuing to experience test failures this month.

I've sent you a direct link to the pipeline via DM.
