### ISSUE TITLE
IKeyEncryptionKey vs IKey in the legacy SDK

### ISSUE THREAD

**Issue by huaw** [Azure/azure-sdk-for-net#16357]
How to implement SymmetricKey using the new interface IKeyEncryptionKey ?

**Comment by jsquire** [comment]
Hi @huaw.  Thank you for reaching out.  Unfortunately, there's not enough information for me to determine what client library you're using so that I can find the right folks to assist you.   Can you please help me understand more around what library you're using, which version, and what scenario you're having difficulty with?

**Comment by jsquire** [comment]
I'm going to close this out, as we do not have enough information to take action.   Please feel free to reopen with additional context if you'd like us to assist.
