### ISSUE TITLE
[QUERY] ConfigurationClient: How to check if requests number is throttled?

### ISSUE THREAD

**Issue by sslepova** [Azure/azure-sdk-for-net#16502]
**Query/Question**
I'm using ConfigurationClient to retrieve key values from Azure AppConfiguration store. But GetConfigurationSetting method just hangs when requests limit is reached. So, when I use GetConfigurationSetting/GetConfigurationSettings methods, how can I check if store responses with 429 error?

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by maririos** [comment]
Hi @sslepova . Are you getting an exception with error code 429? Is there something in the message of the `RequestFailedException` that will indicate the `Retry-after` policy for the service?
[Here](https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/appconfiguration/Azure.Data.AppConfiguration#troubleshooting) is some documentation on how you can get more information when an error occurs.

**Comment by sslepova** [comment]
No, the problem is I don't get any exceptions, that's the whole point. ConfigurationClient just hangs and hangs when tries to get a value from AppConfiguration if the limit is exausted. In my case, it's free SKU Azure AppConfiguration store with limit of 1000 request per day and I debug the app locally in Visual Studio 2019.

**Comment by maririos** [comment]
I see. thanks for the clarification. 
What version of the SDK are you using?

**Comment by maririos** [comment]
Also, is there any code you could share that will show how are you calling the service?

**Comment by sslepova** [comment]
Azure.Data.AppConfiguration 1.0.2
I created a separate console app to reproduce this behaviour. This is basically my code:
`DefaultAzureCredential credentials = new DefaultAzureCredential();`
`ConfigurationClient ConfigClient = new ConfigurationClient(new Uri("https://***.azconfig.io"), credentials);`
`ConfigClient = new ConfigurationClient(Endpoint, credentials);`
`ConfigurationSetting ConfigItem = ConfigClient.GetConfigurationSetting("App:Sentinel", "Dev2");`
It all works fine while requests limit isn't reached. After that, the app hangs on the last line without any exceptions be thrown.
Though I get an exception when I try to request a non-existent AppConfiguration store.

**Comment by maririos** [comment]
Thanks @sslepova .
When you say the app hangs, for how long have you waiting until considering it hanging? I am asking this because it looks like after hitting the quota, the service return `429` with a waiting time of 5min, so you will see the SDK doing nothing while waiting for those 5min.

To keep helping you with the issue, is there any change you could include/get the `ClientRequestId`? that way we could share it with the service team and look at the logs on their side.
See information [here](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/core/Azure.Core/samples/Diagnostics.md#setting-x-ms-client-request-id-value-sent-with-requests) on how to customize the ClientRequestID and/or [here](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/core/Azure.Core/samples/Diagnostics.md#logging-redacted-headers-and-query-parameters) to see how to enable it in your logs

**Comment by sslepova** [comment]
Hi! I tried to wait for quite a long time but probably I didn't wait long enough to see the error. To be honest I can't imagine use case when it would be appropriate to wait for 5 minutes. In case of free-tier AppConfig limit is reset once a day. So this 5-minutes waiting makes no sense. I believe at least there should be an option to choose how to handle this type of situation: wait and for how long or throw an error immedately.
As for me, I solved my problem using REST API instead of SDK.

**Comment by maririos** [comment]
I am sorry to hear that @sslepova although glad you are unblocked.

So looking more into it, because of the delay the service requires, the SDK is going to respect that and wait for the 5min, then retry again, and .. wait for another 5min. This will happen 3 times as the default value of our retries. So the app will do nothing for 15minutes. You could enable [logging](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/core/Azure.Core/samples/Diagnostics.md) to verify this is the case.

>To be honest I can't imagine use case when it would be appropriate to wait for 5 minutes. In case of free-tier AppConfig limit is reset once a day. So this 5-minutes waiting makes no sense.

I have pass the information to the service team so they can evaluate.

>  I believe at least there should be an option to choose how to handle this type of situation: wait and for how long or throw an error immedately.

I will like to understand more your recommendation so we can improve. Are you suggesting being able to set in the SDK the maximum amount of time to wait after a `429` and when that it is hit, don't retry the request, but throw?

**Comment by sslepova** [comment]
In my particular case I would prefer to get the exception right away rather than wait, especially when the limit would be reset only hours later. And of course, it should be different for a production environment where we don't want an application to break. 
So, to be flexible I would suggest providing some more options for how ConfigurationClient should handle 429 issue:
- throw an exception immediately when service responded with 429
- wait for a specified time before try again
- how many times (maybe including unlimited number) it should try until finally giving up
On the other hand, we always could handle any type of response in the application code in the manner we prefer. So in my opinion, at least the first option is a must)).

**Comment by AlexGhiondea** [comment]
@maririos is there a way to configure the client such that it throws on 429? Maybe a custom policy?

**Comment by maririos** [comment]
Yeah. Custom Policy will def help here
