### ISSUE TITLE
Azure.Storage.Blobs upload stream restarting without throwing exception

### ISSUE THREAD

**Issue by ctrlaltdan** [Azure/azure-sdk-for-net#16548]
Hi, I've had an issue with uploading large files to blob storage which is blocking me.

When uploading a large file from a stream, the stream appears to restart without throwing any exceptions. This is a large file and the restarts cause the file to never fully upload.

Sample code streaming from an FTP directory, to azure.

(using Azure.Storage.Blobs `12.6.0`, dotnet core 3.1, running locally on Windows 10)

```
await using (var stream = sftp.OpenRead(message.FilePath))
{
    var progressHandler = new Progress<long>();
    progressHandler.ProgressChanged += (_, uploadedBytes) =>
    {
        Log.Information("Streaming file {Name}. {BytesUploaded} of {TotalBytes} bytes transferred ({Percentage}) after {Duration}ms.", message.FileName, uploadedBytes, fileSizeInBytes, ((double)uploadedBytes / fileSizeInBytes).ToString("P"), timer.ElapsedMilliseconds);
    };

    await blob.UploadAsync(stream, progressHandler: progressHandler);
}
```

The same issue occurs when first streaming the whole file into memory.

```
var stream = new MemoryStream();
sftp.DownloadFile(message.FilePath, stream, delegate (ulong bytesTransferred)
{
    Log.Information("Downloading file {Name}. {BytesDownloaded} of {TotalBytes} bytes transferred ({Percentage}) after {Duration}ms.", message.FileName, bytesTransferred, fileSizeInBytes, ((double)bytesTransferred / fileSizeInBytes).ToString("P"), timer.ElapsedMilliseconds);
});

stream.Seek(0, SeekOrigin.Begin);

var progressHandler = new Progress<long>();
progressHandler.ProgressChanged += (_, uploadedBytes) =>
{
    Log.Information("Uploading file {Name}. {BytesUploaded} of {TotalBytes} bytes transferred ({Percentage}) after {Duration}ms.", message.FileName, uploadedBytes, fileSizeInBytes, ((double)uploadedBytes / fileSizeInBytes).ToString("P"), timer.ElapsedMilliseconds);
};

await blob.UploadAsync(stream, progressHandler: progressHandler);
```

When looking at the logging output I see:

```
[18:45:42 INF] Streaming file large_file.zip. 50069504 of 238035600 bytes transferred (21.03%) after 99611ms.
[18:45:42 INF] Streaming file large_file.zip. 50200576 of 238035600 bytes transferred (21.09%) after 99883ms.
[18:45:43 INF] Streaming file large_file.zip. 50331648 of 238035600 bytes transferred (21.14%) after 100287ms.
[18:45:44 INF] Streaming file large_file.zip. 0 of 238035600 bytes transferred (0.00%) after 101325ms.
[18:45:44 INF] Streaming file large_file.zip. 131072 of 238035600 bytes transferred (0.06%) after 101789ms.
[18:45:45 INF] Streaming file large_file.zip. 262144 of 238035600 bytes transferred (0.11%) after 102212ms.
[18:45:45 INF] Streaming file large_file.zip. 393216 of 238035600 bytes transferred (0.17%) after 102625ms.
```

Is there anything I can try to gain further insight into what error is occurring, causing the restart? I'd have assumed error handling and "PutBlock" retrys would be handled by the framework given these methods seem to be removed from the latest package.

Many thanks,

---

For completeness question also asked on StackOverflow https://stackoverflow.com/questions/64668945/streaming-large-files-to-azure-blob-storage-stream-restarting

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.

**Comment by ctrlaltdan** [comment]
Approaching this from a new angle and this time attempting to write the file using the `BlockBlobClient` as detailed in the following tests: https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/storage/Azure.Storage.Blobs/tests/BlockBlobClientTests.cs

Interestingly have the same issue during upload (block 11 of 25) although this time I'm able to catch a 400 `InvalidBlobOrBlock` error from the server:

```
The specified blob or block content is invalid.
RequestId:6b1744eb-f01e-0044-7190-b25542000000
Time:2020-11-04T09:58:15.2075900Z
Status: 400 (The specified blob or block content is invalid.)
ErrorCode: InvalidBlobOrBlock

Headers:
Server: Windows-Azure-Blob/1.0,Microsoft-HTTPAPI/2.0
x-ms-request-id: 6b1744eb-f01e-0044-7190-b25542000000
x-ms-client-request-id: 40697463-8818-4421-a4ba-b2a3745326fb
x-ms-version: 2019-12-12
x-ms-error-code: InvalidBlobOrBlock
Date: Wed, 04 Nov 2020 09:58:14 GMT
Content-Length: 234
Content-Type: application/xml
```

Latest code for completeness:

```
var client = new BlockBlobClient(_storageOptions.ConnectionString, _storageOptions.Container, message.FileName);

const int blockSize = 10000000;
var blockIndex = 0;
var totalBlocks = (int) Math.Ceiling(fileSizeInBytes / (double) blockSize);
var committedBlocks = new List<string>(totalBlocks);

var progressHandler = new Progress<long>();
progressHandler.ProgressChanged += (_, uploadedBytes) =>
{
    Log.Information("Uploading file {Name} block {Index} of {TotalBlocks}. {BytesUploaded} of {TotalBytes} bytes transferred ({Percentage}) after {Duration}ms.", 
        message.FileName,
        committedBlocks.Count + 1, 
        totalBlocks,
        uploadedBytes, 
        blockSize, 
        ((double)uploadedBytes / blockSize).ToString("P"), 
        timer.ElapsedMilliseconds);
};

try
{
    await using var stream = sftp.OpenRead(message.FilePath);
    var buffer = new byte[blockSize];
    while (stream.Read(buffer, 0, blockSize) > 0)
    {
        var blockId = Convert.ToBase64String(System.Text.Encoding.UTF8.GetBytes($"{message.FileName}_{blockIndex}"));
        await client.StageBlockAsync(blockId, new MemoryStream(buffer), progressHandler: progressHandler);
        committedBlocks.Add(blockId);
        blockIndex++;
    }

    await client.CommitBlockListAsync(committedBlocks);
}
catch (Exception ex)
{
    Log.Error(ex, "Unable to upload file.");
    throw;
}
```

Is there something I'm doing fundamentally wrong here?

Any help would be much appreciated.

**Comment by ctrlaltdan** [comment]
It would appear ensuring the ID length of my `blockId` is always the same length has fixed the above `400 Bad Request` error as cited in the following blog: https://gauravmantri.com/2013/05/18/windows-azure-blob-storage-dealing-with-the-specified-blob-or-block-content-is-invalid-error/

Could this also be an underlying issue with the `blob.UploadAsync(stream);` method?

**Comment by amnguye** [comment]
Hi,

Thanks for bringing this find of this issue to our attention.

There's two issues that I want to address. First is the restart of the upload, I will have to look into reproducing this issue and seeing why we are restarting the upload (like if there was a network interruption, a random 500 error in the middle of the upload, or something weird happening when reading from the stream).

The second issue I find very interesting that the block id has to always be the same length when uploading or else an invalid error will occur. I will write a specific test for this, and let you know what I find.

**Comment by petro2050** [comment]
@ctrlaltdan  @amnguye I ran into this issue as well. I'm trying to upload a 200MB file from Xamarin Forms using an Android device, and the same `UploadAsync` method keeps restarting the upload. I posted a question on SO (https://stackoverflow.com/questions/65499942/azure-storage-blobclient-keeps-resetting-itself-while-uploading-large-files) before seeing this thread. I was able to see an exception after waiting for minutes.

I'm getting an object disposed exception.

```
Cannot access a disposed object.
Object name: 'MobileAuthenticatedStream'.

  at Mono.Net.Security.MobileAuthenticatedStream.StartOperation (Mono.Net.Security.MobileAuthenticatedStream+OperationType type, Mono.Net.Security.AsyncProtocolRequest asyncRequest, System.Threading.CancellationToken cancellationToken) [0x00245] in /Users/builder/jenkins/workspace/archive-mono/2020-02/android/release/mcs/class/System/Mono.Net.Security/MobileAuthenticatedStream.cs:410 
  at System.Net.Http.HttpConnection.WriteAsync (System.ReadOnlyMemory`1[T] source) [0x00118] in /Users/builder/jenkins/workspace/archive-mono/2020-02/android/release/external/corefx/src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnection.cs:1008 
  at System.IO.Stream.CopyToAsyncInternal (System.IO.Stream destination, System.Int32 bufferSize, System.Threading.CancellationToken cancellationToken) [0x000e7] in /Users/builder/jenkins/workspace/archive-mono/2020-02/android/release/external/corert/src/System.Private.CoreLib/shared/System/IO/Stream.cs:152 
  at Azure.Core.RequestContent+StreamContent.WriteToAsync (System.IO.Stream stream, System.Threading.CancellationToken cancellation) [0x00094] in <7b1dc95b0b4841539beb48023c1128d3>:0 
  at Azure.Core.Pipeline.HttpClientTransport+PipelineRequest+PipelineContentAdapter.SerializeToStreamAsync (System.IO.Stream stream, System.Net.TransportContext context) [0x0007c] in <7b1dc95b0b4841539beb48023c1128d3>:0 
  at System.Net.Http.HttpContent.CopyToAsyncCore (System.Threading.Tasks.ValueTask copyTask) [0x00022] in /Users/builder/jenkins/workspace/archive-mono/2020-02/android/release/external/corefx/src/System.Net.Http/src/System/Net/Http/HttpContent.cs:361 
```

This is a blocking issue for me. Providing `StorageTransferOptions ` does not work. Using a `BlockBlobClient` does not work either. I'm also unable to use https://www.nuget.org/packages/Microsoft.Azure.Storage.DataMovement because it doesn't work with Xamarin Forms.

**Comment by amishra-dev** [comment]
Hi @petro2050,
You have set the block size too high (~10MB). I would drop it to 265K. What is happening most likely is that the network (by the virtue of it being a mobile device) is flaky. And because a block is a unit of transfer for us, we retry the whole thing again. Try it and let me know. If you git InvalidBlockOrBlob again, send me the request id rightaway and i can ask my friends in the service to investigate what is happening.

**Comment by seanmcc-msft** [comment]
Please re-open if you have further questions.

**Comment by sumitkm** [comment]
This is an extremely infuriating issue, led on by poor documentation and sample code in this repository. No one in the SDK team seems to be able to fathom, a prime use-case for `BlockBlob` this is a chunked file upload from a browser. The most common way to do that is to use an integer for block Id. If you use their sample `ToBase64` helper you are doomed. 

Someone write a test to upload a 20 Mb file in 1Mb chunks :-p. Mine uses lot of my custom code so can't share here directly!

So, for anyone who's spent days going round in circles as to why your chunked upload fails with a `400, The specified blob or block content is invalid`, there are few possible reasons:

1. You are uploading a file using a name say `myfile.abc`, to a particular container say `mycontainer`. If this file upload fails for any reason, you cannot use that file name again (until the uncomitted blockblob is discarded, that takes 7 days I believe). So best case is don't use files names sent from client. Use a `Guid.NewGuid().ToString()` to generate a new file name for every upload attempt (not every chunk ;-) ). E.g.
```csharp
string fileName = "RunOnDemand\\SampleMedia\\20MB_Test.mp4";
string containerName = "00-integration-testing";
string storagePath = $"chunked-upload-test/{Guid.NewGuid().ToString()}.{Path.GetExtension(fileName)}";
```

2.  When creating `MemoryStream` for the `StageBlock` call, use starting index and chunk size explicitly as shown below. If you don't you may end up with 400 errors when you try to call `CommitBlockListAsync`.  (That took a good day to sort)
```csharp
public async Task UploadCurrentChunk(string containerName, string storagePath, byte[] chunk, int blockId)
{
    using (var chunkStream = new MemoryStream(chunk, 0, chunk.Length))
    {
        var container = this.EnsureContainer(containerName); // my helper function
        var blockBlob = container.GetBlockBlobClient(storagePath);
        var fileName = Path.GetFileNameWithoutExtension(storagePath);
        var currentBlockId = ToBase64(blockId);
        try
        {
            var response = await blockBlob.StageBlockAsync(
                currentBlockId,
                chunkStream);
            return null;
        }
        catch (RequestFailedException e)
        {
          // TODO: Log/status/stuff
        }
    }
    return;
}
```
3. As mentioned by @ctrlaltdan if you use integer indexes for block Ids _do not_ use the `ToBase64` function as shown in the samples in this repository. That's another day of going round in circles for you. You can use a helper like the following
```csharp
public string ToBase64(int blockIndex)
{
    return Convert.ToBase64String(System.Text.Encoding.UTF8.GetBytes($"{blockIndex:D8}"));
    //var bytes = Encoding.UTF8.GetBytes(id);
    //return Convert.ToBase64String(bytes);
}
```

Back in the days I used to blog these things, little did I know I was documenting for myself 🤦🏾‍♂️ . Now my 8 year old samples don't work anymore because all the underlying API has been changed and new stuff don't work as documented \o/
