### ISSUE TITLE
remove Storage Test Namespace from parent namespace

### ISSUE THREAD

**Issue by amnguye** [Azure/azure-sdk-for-net#16692]
In issue https://github.com/Azure/azure-sdk-for-net/issues/15853 we saw that our tests were failing to catch when we accidentally set a constructor to internal, preventing users from being able to create instances of public class objects.

Our test namespace are included in the parent namespace, which allows the test namespace to call properties, constructors and objects that are internal.

This could be a bug and not a bug. Because we could need these access these internal objects for our tests but we don't want to expose them publicly. At the same time we do want to be able to write tests/code that users would be writing as well.

Open to any ideas or help on how to do this for our existing tests. Or if we should write separate tests in a namespace outside of the existing tests that have access to call our internally set objects.

**Comment by JoshLove-msft** [comment]
> In issue #15853 we saw that our tests were failing to catch when we accidentally set a constructor to internal, preventing users from being able to create instances of public class objects.

Was the constructor actually changed from public to internal or was it always internal? ApiCompat should catch an API break like this.

> Our test namespace are included in the parent namespace, which allows the test namespace to call properties, constructors and objects that are internal.

The reason that that internal methods can be called is because InternalsVisibleTo is enabled for the project - https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/storage/Azure.Storage.Files.Shares/src/AssemblyInfo.cs#L7
