### ISSUE TITLE
Make autorest --csharp default to track2

### ISSUE THREAD

**Issue by AlexGhiondea** [Azure/azure-sdk-for-net#16751]

**Comment by ShivangiReja** [comment]
Added a step in the pipeline to publish @autorest/csharp-v3 on npm as autorest expects an npm package. Here is the [PR](https://github.com/Azure/autorest.csharp/pull/957) and here is the [npm package](https://www.npmjs.com/package/@autorest/csharp).

**Comment by ShivangiReja** [comment]
Now I'm able to generate code using `autorest --use:@autorest/csharp@v3.0.0-beta.20201217.3 --input-file:Inputfile --public-clients:true` command but when I set to `--clear-output-folder:true`, it removes all the customizations because all the customizations are inside the generated folder. I'm working on the fix.

**Comment by ShivangiReja** [comment]
Now I'm able to generate code using `autorest --use:@autorest/csharp@v3.0.0-beta.20201217.3 --input-file:Inputfile --public-clients:true` command but when I set to `--clear-output-folder:true`, it removes all the customizations because currently we put all the customizations inside the generated folder. I'm working on the fix.

**Comment by ShivangiReja** [comment]
Moved customization code and csproj outside of generated folder - https://github.com/Azure/autorest.csharp/pull/981

**Comment by ShivangiReja** [comment]
Releasing shared sources with NPM package: https://github.com/Azure/autorest.csharp/pull/1001

**Comment by ShivangiReja** [comment]
Add autorest package reference in generated csproj for outside of autorest.csharp repo: https://github.com/Azure/autorest.csharp/pull/1008

**Comment by ShivangiReja** [comment]
Update csharp plugin to default to track-2 generator: https://github.com/Azure/autorest/pull/3850
