### ISSUE TITLE
Create migration guide for Tables

### ISSUE THREAD

**Issue by christothes** [Azure/azure-sdk-for-net#16771]

**Comment by joelverhagen** [comment]
I ran in to another different between `WindowsAzure.Storage` and `Azure.Data.Tables`. When you are specifying a projection (`$select` column names) the old SDK always forces PartitionKey, RowKey, and Timestamp to be present. In Azure.Data.Tables, only the provided set is used.

For example suppose the SKD user asks for `select: new[] { "FieldB" }` in `TableClient.QueryEntities`, the following query parameter is actually sent:

- New SDK: `$select=FieldB` 
  - Server returns `FieldB` and `odata.etag` (seems like Azure Table Storage is hardcoded to do this on the server side?)
- Old SDK: `$select=FieldB,PartitionKey,RowKey,Timestamp`
  - Superset of new SDK. `PartitionKey`, `RowKey`, and `Timestamp` are returned as specified in the HTTP request
 
I like the Azure.Data.Tables behavior better since it's more true to the user's request.

This is easy to fix in the user code. Ask for the columns you actually need 😄.

**Comment by christothes** [comment]
#21909
