### ISSUE TITLE
BlockBlobClient streaming API generates incorrect content hash [BUG]

### ISSUE THREAD

**Issue by chrisblock** [Azure/azure-sdk-for-net#16779]
As this is a bug I encountered during my day job, and it seems to me to be a bug with the actual Azure Storage Service, I originally opened this as a ticket using the Azure Support portal. The Azure Support Engineer that contacted me has passed the issue up the chain, but also requested I put in this issue here as well.

**Summary:**
When using the streaming API of the BlockBlobClient (e.g. `OpenWrite`) to upload files, the resulting file has the hash (MD5) of the empty string (`d41d8cd98f00b204e9800998ecf8427e`).

I have verified that when uploading a file manually (via the Azure Portal) it gets the correct hash, as well as if I update the file using the Azure Portal. Additionally, using the `Upload` and `UploadAsync` methods also results in the correct hash.

**Expected behavior**
I would expect that after the write is finished (i.e. the stream is closed), the blob in Azure Storage would have the hash of the content of the file. I would also expect that in the event of a transport error, or some other error condition, the hash displayed in the Azure Portal (and available via the API) would reflect the actual contents of the file as it exists in the Azure Blob Storage Service.

**Actual behavior (include Exception or Stack Trace)**
After finishing and closing the stream, the blob has the hash of the empty string (`d41d8cd98f00b204e9800998ecf8427e`).

**To Reproduce**
```
var client = new BlobServiceClient(<uri>, new DefaultAzureCredential(), new BlobClientOptions());

var container = client.GetBlobContainerClient(<container>);

container.CreateIfNotExists();

var blob = container.GetBlockBlobClient(<filename>);

using (var input = File.OpenRead(<path-to-local-file>))
{
    using (var output = blob.OpenWrite(true))
    {
        input.CopyTo(output);

        output.Flush();
    }
}
```

**Environment:**
 - Name and version of the Library package used: `Azure.Storage.Blobs` `v12.6.0` 
 - Hosting platform or OS and .NET runtime version: `Windows 10`, `.NET Framework 4.7.2`
 - IDE and version : `Visual Studio Professional 2019`, `v16.7.6`

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.

**Comment by amishra-dev** [comment]
@seanmcc-msft can you please look at this

**Comment by seanmcc-msft** [comment]
I can repo this issue, when I upload a small blob (14 bytes) using the Azure portal and `BlobClient.Upload()`, the service generated Content MD5 is present.  This is not the case with `BlockBlobClient.OpenWrite()`

Because this is a small blob, uploading via the Azure Portal and `BlobClient.Upload()` makes a single [Put Blob](https://docs.microsoft.com/en-us/rest/api/storageservices/put-blob) request.

Open Write always makes [Put Block](https://docs.microsoft.com/en-us/rest/api/storageservices/put-block) calls, followed by a [Put Block List](https://docs.microsoft.com/en-us/rest/api/storageservices/put-block-list) call when `Stream.Flush()` is called.  Blobs created in this manner won't have a service-generated Content MD5.

This is just how the service handles Content MD5.  A workaround would be to calculate and set the Content MD5 yourself:
```
BlockBlobOpenWriteOptions options = new BlockBlobOpenWriteOptions
{
    BlobHttpHeaders = new HttpHeaders
    {
        ContentHash = calculatedContentMD5
    }
};
Stream writeStream = await.OpenWriteAsync(overwrite: true, options: options);
```

Please reopen if you have further questions.

**Comment by gius** [comment]
@seanmcc-msft Is it possible to set the content hash after the stream is closed? I use a `StreamWriter` to write into the Blob stream and thus the content's MD5 is unknown at the time of calling `OpenWriteAsync`. 
I know that a temporary `MemoryStream` could be used, but it is not a memory-wise solution for larger data.
