### ISSUE TITLE
Invalid blob metadata gives confusing error

### ISSUE THREAD

**Issue by njannink** [Azure/azure-sdk-for-net#16873]
**Describe the bug**
When uploading a new blob with invalid metadata. In our case a trailing space you get the following error:

> Azure.RequestFailedException: Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.

This is very confusing because there is nothing wrong with the authorization header.

**Expected behavior**
A more relevant exception, eg `InvalidArgumentException` with a message saying the metadata isn't valid.

**To Reproduce**
Upload a blob with invalid metadata (trailing spaces or special chars) and then the following error is thrown:

```
Azure.RequestFailedException: Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
RequestId:27687209-401e-00d4-1d3c-b8894c000000
Time:2020-11-11T15:07:22.2871106Z
Status: 403 (Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.)
ErrorCode: AuthenticationFailed

Headers:
Server: Microsoft-HTTPAPI/2.0
x-ms-request-id: 27687209-401e-00d4-1d3c-b8894c000000
x-ms-error-code: AuthenticationFailed
Date: Wed, 11 Nov 2020 15:07:22 GMT
Content-Length: 1151
Content-Type: application/xml

   at Azure.Storage.Blobs.BlobRestClient.BlockBlob.UploadAsync_CreateResponse(ClientDiagnostics clientDiagnostics, Response response)
   at Azure.Storage.Blobs.BlobRestClient.BlockBlob.UploadAsync(ClientDiagnostics clientDiagnostics, HttpPipeline pipeline, Uri resourceUri, Stream body, Int64 contentLength, String version, Nullable`1 timeout, Byte[] transactionalContentHash, String blobContentType, String blobContentEncoding, String blobContentLanguage, Byte[] blobContentHash, String blobCacheControl, IDictionary`2 metadata, String leaseId, String blobContentDisposition, String encryptionKey, String encryptionKeySha256, Nullable`1 encryptionAlgorithm, String encryptionScope, Nullable`1 tier, Nullable`1 ifModifiedSince, Nullable`1 ifUnmodifiedSince, Nullable`1 ifMatch, Nullable`1 ifNoneMatch, String ifTags, String requestId, String blobTagsString, Boolean async, String operationName, CancellationToken cancellationToken)
   at Azure.Storage.Blobs.Specialized.BlockBlobClient.UploadInternal(Stream content, BlobHttpHeaders blobHttpHeaders, IDictionary`2 metadata, IDictionary`2 tags, BlobRequestConditions conditions, Nullable`1 accessTier, IProgres...
```

**Environment:**
 - Library package used: Azure.Storage.Blobs 12.6.0
 - Hosting platform: Azure development storage
 - IDE and version : Visual Studio 16.8

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.

**Comment by amnguye** [comment]
I was able to reproduce your issue. Looks like special characters and trailing spaces could corrupt the http headers in some way due to the fact that metadata is a http header value. Which is why we get an unhelpful error such as AuthenticationError.

Let me check if there are restrictions on the metadata, since special characters and spaces could mess with the format of all the other headers.

**Comment by amnguye** [comment]
We should be throwing an invalid metadata error, instead of allowing the user to send invalid metadata here.

**Comment by zane-woodard-drc** [comment]
Any change we can get a definition for "special characters"?
I'm seeing the same issue when a blob has a metadata entry that's just a comma (",").

AFAIK a comma is not strictly a special character per the http spec and would only be a special character if the parser implementation on the other end is treating it as such.

**Comment by njannink** [comment]
Maybe the azure sdk can provide a base64 encoding and decoding of the metadata api extensions to prevent issues with invalid chars?

**Comment by seanmcc-msft** [comment]
> Any change we can get a definition for "special characters"?

The metadata keys must ahead to C# identifier naming rules - https://docs.microsoft.com/en-us/rest/api/storageservices/naming-and-referencing-containers--blobs--and-metadata#metadata-names.

I believe the metadata values must be valid HTTP header characters.

> I'm seeing the same issue when a blob has a metadata entry that's just a comma (",").

I don't think "," is a valid header value in the HTTP spec - https://tools.ietf.org/html/rfc7230#section-7.

>    In contrast, the following values would be invalid, since at least
   one non-empty element is required by the example-list production:

     ""
     ","
     ",   ,"


I'm not sure if we should provide extension method to base64 encode/decode metadata values, since we would actually be changing the data that is stored in the service, and the data can be accessed outside of the SDK.  @tg-msft.

**Comment by njannink** [comment]
I know that is why I say extension methods so people can optionally use those methods.

    blob.SetMetaData64(IDictionary<string,string> metadata);
    var metadata = blob.GetMetadata64();

**Comment by njannink** [comment]
Because I read that that is also the suggestion for setting metadata with invalid chars

**Comment by brian-knoll-micronetonline** [comment]
Just ran into this myself. Azure support lead me to believe it was because I was storing some email data. but after a lot of digging, I found out it was a trailing space on the metadata. the error is not helpful and if there was a check for leading and trailing spaces in the library so we could get a more useful error that would of saved me a lot of time.

**Comment by JimSuplizio** [comment]
Hi @njannink, we deeply appreciate your input into this project. Regrettably, this issue has remained inactive for over 2 years, leading us to the decision to close it. We've implemented this policy to maintain the relevance of our issue queue and facilitate easier navigation for new contributors. If you still believe this topic requires attention, please feel free to create a new issue, referencing this one. Thank you for your understanding and ongoing support.
