### ISSUE TITLE
[FEATURE REQ] BlobSasBuilder should take BlobContainerName and BlobName as ctor parameters

### ISSUE THREAD

**Issue by msavaria** [Azure/azure-sdk-for-net#16914]
**Library or service name.**
Azure.Storage.Sas.BlobSasBuilder 
 
**Is your feature request related to a problem? Please describe.**
I was running this code initially and kept getting null reference exceptions when calling GenerateSasUri:

```csharp
var blob = new BlobClient(new Uri(absoluteUrl), storageSharedKeyCredential);
var permission = writePermission ? BlobSasPermissions.Write : BlobSasPermissions.Create;

var sasBuilder = new BlobSasBuilder(permission, expiresOn: DateTimeOffset.UtcNow.AddHours(1))
{
   StartsOn = DateTimeOffset.UtcNow.AddMinutes(-5)
};

var sas =  blob.GenerateSasUri(sasBuilder);
return sas.Query;
```

Turns out, you have to explicitly set the `BlobContainerName` and `BlobName` properties of the `BlobSasBuilder` like so or else you get a `NullReferenceException`.

```csharp
var sasBuilder = new BlobSasBuilder(permission, expiresOn: DateTimeOffset.UtcNow.AddHours(1))
{
   StartsOn = DateTimeOffset.UtcNow.AddMinutes(-5),
   BlobContainerName = blob.BlobContainerName,
   BlobName = blob.Name
};
```

However, it's not clear when looking at the available `BlobSasBuilder` constructors that those properties are mandatory. Hence, they should be included as constructors parameters, or even better, inferred from the `BlobClient`.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.

**Comment by amnguye** [comment]
Hi,

`BlobSasBuilder` is used across all Blob Clients to create a SAS, so having them take in the `BlobContainerName` and `BlobName` would probably not be the right solution since then people would need to provide them to make a service level SAS which would not be the correct solution. Also if they wanted to make a container SAS, providng a `BlobName` would be inappropriate for this situation to create a `BlobSasBuilder` object.

I think the problem that needs to be addressed here is that the `GenerateSas` method should check if the `BlobContainerName` and `BlobName` is empty in the builder. If it's empty we should default to the client's respective `ContainerName` and `BlobName`, since thats probably the SAS information you want to generate off of anyways.

This also needs to be address for `Files`, `DataLake` and `Queues`.

I will put the label feature request on this and we will look to address this issue soon. Thanks for bringing this to our attention.
