### ISSUE TITLE
[FEATURE REQ][CAE]Pre-populate user name for InteractiveBrowserCredential

### ISSUE THREAD

**Issue by erich-wang** [Azure/azure-sdk-for-net#16983]
**Library or service name.**
What library or service is this request related to? 
Azure.Identity
 
**Is your feature request related to a problem? Please describe.**
What feature would you like to get added? What problem is it solving?

One S500 customer is asking pre-populate user name from Azure PowerShell side, this needs Azure.Identity to support it first. 
It is also required for supporting CAE re-authenticate

**Comment by christothes** [comment]
Hi @erich-wang Could you provide a bit more context for why pre-populating the user name is needed? Is this just to save a step of having to re-type it, or is there some other issue that this is meant to address?

**Comment by NickEales** [comment]
@christothes - Yes - this is so that the customer doesn't have to retype their username. 

The (S500) customer had been using this command:
> Connect-AzAccount -Tenant XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX -Credential $(Get-Credential -Message "Connect-AzAccount" -user $myUser)

The customer has had to enable Conditional Access policies for these users on their domain. The above command uses a User name plus password authentication (ROPC) method that doesn’t support any type of conditional access policy.
