### ISSUE TITLE
[FEATURE REQ] Expose enableRbacAuthorization property in Vault

### ISSUE THREAD

**Issue by GalPillar** [Azure/azure-sdk-for-net#17011]
**Library or service name.**
The new unified sdk for key vault (Azure.ResourceManager.KeyVault)
 
**Is your feature request related to a problem? Please describe.**
When using the new unified sdk for key vault (Azure.ResourceManager.KeyVault), if you fetch a key vault, the property enableRbacAuthorization in VaultProperties isn't parsed and exposed via the sdk, even though it is returned in the json response from the api. The property is required to know if the access policies are enabled or the rbac is enabled.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by markcowl** [comment]
@GalPillar Thanks for pointing this issue out.  It looks like this preview SDK is not up to date with the latest api definition for KeyVault, which includes this property.  We will update the sdk the next time we release preview libraries.

@m-nash This looks like a change in the api-version since we updated the SDK.  We should re-release this with the latest updates when we next release preview sdks.

**Comment by GalPillar** [comment]
Hey, thanks for the quick reply!! 
Can I ask when the next preview sdks are scheduled to release?
I don't need an exact date, and I'm not going to hold you to it, we're just curious as to when they're gonna come out

**Comment by ArthurMa1978** [comment]
The new [KeyVault lib](https://www.nuget.org/packages/Azure.ResourceManager.KeyVault/) support this property now.
