### ISSUE TITLE
[QUERY] CachingKeyResolver missing in new version of the Key Vault SDK

### ISSUE THREAD

**Issue by georgelivingston** [Azure/azure-sdk-for-net#17111]
**Query/Question**
How can we help?
CachingKeyResolver missing in V12 SDK. Can you point me in the direction? Would I need to implement our own caching key resolver or am I missing something?

https://docs.microsoft.com/en-us/azure/storage/common/storage-client-side-encryption?tabs=dotnet#interface-and-dependencies

![image](https://user-images.githubusercontent.com/16534040/99798794-9e205400-2b57-11eb-8df2-954194f06c9d.png)

**Environment:**
 - Name and version of the Library package used: Azure.Security.KeyVault.Keys 4.1.0 and Azure.Storage.Blobs 12.6.0, 
 - Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects):  Azure AppService or Windows 10 .NET Core 3.1
 - IDE and version : Visual Studio 2019

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.

**Comment by seanmcc-msft** [comment]
@jaschrep-msft, could you take a look?

**Comment by jaschrep-msft** [comment]
@georgelivingston, apologies that this fell under the radar.

This appears to be a bug in our documentation. The section you reference should be contained in the v11 tab in the box you find above. CachingKeyResolver is a part of the legacy KeyVault SDK that was used with the legacy storage library.

The v12 library is intended to work with the v4 KeyVault library, which handles everything already with its `CryptographyClient` class.
```csharp
CryptographyClient cryptographyClient = new CryptographyClient(myKeyVaultKeyUry, myCredential);
ClientSideEncryptionOptions clientSideOptions = new ClientSideEncryptionOptions(ClientSideEncryptionVersion.V1_0)
{
    KeyEncryptionKey = cryptographyClient,
    KeyWrapAlgorithm = myKeyWrapAlgorithmName
};
```

We will work to update this in the docs.

**Comment by walunjsachin** [comment]
@jaschrep-msft 
Does myKeyVaultKeyUry uri is actual key id (specific to version) or just key uri (reference to key)?  By using Key Uri (without version) we found that uploaded blob metadata only includes key reference (but key rotation may break it in future).
Also this does not mention about download scenario which based on documentation uses the key resolver (https://docs.microsoft.com/en-us/dotnet/api/azure.storage.clientsideencryptionoptions.keyresolver?view=azure-dotnet)

**Comment by jaschrep-msft** [comment]
@walunjsachin it is the keyid, as described by the [constructor documentation](https://docs.microsoft.com/en-us/dotnet/api/azure.security.keyvault.keys.cryptography.cryptographyclient.-ctor?view=azure-dotnet#Azure_Security_KeyVault_Keys_Cryptography_CryptographyClient__ctor_System_Uri_Azure_Core_TokenCredential_).

The same library also contains the [`KeyResolver`](https://docs.microsoft.com/en-us/dotnet/api/azure.security.keyvault.keys.cryptography.keyresolver?view=azure-dotnet) class which returns `CryptographyClient` instances on resolution.

`KeyResolver` does NOT cache resolved key instances. The bit of documentation you found is meant to be Storage v11-specific, as the KeyVault v3.x library provided an extra class to cache resolved keys. KeyVault 4.x, what is used by Storage 12.x, does not currently provide a caching class. A docs update is underway to clarify these differences.

**Comment by walunjsachin** [comment]
@jaschrep-msft , Thanks for your response.
Please correct me if am missing something here...  below code sample just  loops and download encrypted document. Every loop execution makes to 2 calls to Key Vault (captured with Fiddler).

1) Get - GET /keys/blobEncryption/70d8363d5ab04f7c82e90aa74e5f908c?api-version=7.1 HTTP/1.1
2) POST - /keys/blobEncryption/70d8363d5ab04f7c82e90aa74e5f908c/unwrapKey?api-version=7.1 HTTP/1.1

```
            for (int i = 0; i < 10; i++)
            {
                BlobClient blob = new BlobServiceClient(connectionString, options).GetBlobContainerClient("mycontainer").GetBlobClient($"myblob");
                using MemoryStream outputStream = new MemoryStream();
                blob.DownloadTo(outputStream);
                using StreamReader reader = new StreamReader(outputStream);
                string outputText = reader.ReadToEnd();
                Console.WriteLine($"Output: {outputText}");
            }
```
Based on v11 understanding, CachingKeyResolver ensured Get key call only once for particular keyid for all subsequent request it just reused key reference from cache.  The reason for me to look for CachingKeyResolver was not only due to documentation reference but also to avoid that Get call which could potential cause key vault throttling based on load.

Please suggest if there is option that I am missing to avoid this additional get calls, instead of me writing own implementation of IKeyEncryptionKeyResolver to cache key.  _Do ignore newing of blob client it may very well be just transient\scoped objects injected during a http request..._

**Comment by jaschrep-msft** [comment]
Latest KeyVault 4.x (currently 4.1) does not contain an equivalent of CachingKeyResolver.

It looks as if KeyVault publishes a [separate package](https://docs.microsoft.com/en-us/samples/azure/azure-sdk-for-net/azure-key-vault-proxy/) that can help with the caching, instead of implementing from scratch. You can mention `@heaths` if the link is not enough to get started.

**Comment by walunjsachin** [comment]
@jaschrep-msft 
This may not help, since KeyResolver do no expose any constructor to inject key client or attribute itself for us to set such policies.  Do understand that KeyClient does have caching options but KeyResolver does not use key client instead directly uses KeyVaultPipeline and Storage SDK needs KeyResolver while downloading.

@heaths

**Comment by heaths** [comment]
`KeyResolve` takes an optional `CryptographyClientOptions` to which you can add the sample proxy policy. In the newer Azure SDKs (Azure.*), all our REST clients take an `*ClientOptions` class with the same base capabilities like custom user policies.

We will consider adding a `CachingKeyResolver` to the Key Vault SDK (title updated to reflect), but the proxy should help in the meantime or, if possible, switch to encryption-at-rest that both Azure Storage and Azure SQL Server support and the services are recommending.

**Comment by heaths** [comment]
@jaschrep-msft are you tracking the doc fixes in another bug, perhaps in a MicrosoftDocs repo? The docs' source is not located here, so we can use this bug to track the feature ask.

**Comment by jaschrep-msft** [comment]
@heaths PR is nearly out in the appropriate repo. Working with Storage docs team to determine proper messaging.

**Comment by heaths** [comment]
We're going through our backlog and I'm wondering if, given the [sample](https://docs.microsoft.com/en-us/azure/storage/common/storage-client-side-encryption?tabs=dotnet#blob-service-encryption), the caching of a single key is sufficient. Our `Azure.Security.KeyVault.Keys.Cryptography.KeyResolver` in Azure.Security.KeyVault.Keys returns a `CryptographyClient`, which already caches the public key for subsequent operations where only the public key is needed, e.g. encryption, verification, and key wrapping.

Given how client-side encryption is handled in that sample, it seems only a single key is needed already.

/cc @schaabs in case there's a scenario I'm not considering.
