### ISSUE TITLE
Not able to access properties of the container created using URI with SAS_Token

### ISSUE THREAD

**Issue by VarunSaiTeja** [Azure/azure-sdk-for-net#17142]
**Query/Question**
Not able to access properties of the container created using URI with SAS_Token

**Environment:**
 - Name and version of the Library package used: Azure.Storage.Blobs 12.7.0
 - Hosting platform or OS and .NET runtime version : donet 5.0
 - IDE and version : Visual Studio 16.8

I created a container using below code
```

 var container = new BlobContainerClient(containerUri, key);

 var sasUri = container.GenerateSasUri(BlobContainerSasPermissions.All, DateTimeOffset.UtcNow.AddHours(1));

 var props = new BlobContainerClient(sasUri).GetProperties();
 
```

Getting Following Error: 
This request is not authorized to perform this operation.
RequestId:a61af534-001e-0011-1ba6-c0ebd2000000
Time:2020-11-22T08:07:56.0540943Z
Status: 403 (This request is not authorized to perform this operation.)
ErrorCode: AuthorizationFailure

I want to share sasUri of x container(All permissions on the selected container) with all blobs in that container(All permissions).
And the blobContainerClient created using sasUri need to access the properties like metadata of container.
Can someone please help me to resolve situation?

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.

**Comment by amnguye** [comment]
Hi I was able to reproduce your issue.

I'm not sure where its going wrong, it looks like it's an issue in `ToSasQueryParameters` which `GenerateSas` takes a dependency on. I will mark this as a bug for now and follow up on this issue with any of the findings we have to this issue.

**Comment by seanmcc-msft** [comment]
Hi @VarunSaiTeja, I can also reproduce this issue.  It turns out that Container SAS doesn't actually have permissions to view the properties of a container - [Create a service SAS](https://docs.microsoft.com/en-us/rest/api/storageservices/create-service-sas#specifying-the-signed-resource-blob-service-only)


Resource | Parameter value | Supported versions | Description
-- | -- | -- | --
Container | c | All |  **Grants access to the content and metadata of any blob in the container, and to the list of blobs in the container.**

Note that access to the Container's properties is not mentioned.

To get a Container's properties via SAS, we need to use [Account SAS](https://docs.microsoft.com/en-us/rest/api/storageservices/create-account-sas).  Here is an example:

```
            BlobServiceClient blobServiceClient = new BlobServiceClient("connectionString");
            Uri serviceSasUri = blobServiceClient.GenerateAccountSasUri(
                AccountSasPermissions.All,
                DateTimeOffset.UtcNow.AddDays(1),
                AccountSasResourceTypes.Container);
            BlobContainerClient sasContainerClient = new BlobServiceClient(serviceSasUri).GetBlobContainerClient("containerName");

            // Act
            await sasContainerClient.GetPropertiesAsync();
```

-Sean
