### ISSUE TITLE
[Form Recognizer]Form recognizer cilent fail to authenticate with token credential in USGOV

### ISSUE THREAD

**Issue by Luyunmt** [Azure/azure-sdk-for-net#17192]
In https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/formrecognizer/Azure.AI.FormRecognizer/src/FormRecognizerClient.cs#L95 as follow,
The scope is hard code leading to only work well in the public cloud.
![image](https://user-images.githubusercontent.com/53427149/100182542-da690100-2f17-11eb-8e68-f018a3a5f977.png)
The value of the scope in different clouds is follow:
Azure public cloud: https://cognitiveservices.azure.com/.default
USGOV cloud: https://cognitiveservices.azure.us/.default
China cloud: https://cognitiveservices.azure.cn/.default

**Comment by maririos** [comment]
@benbp have you seen this in the work you are doing testing against other clouds? I haven't seen this requirement before.

If this is indeed needed, @schaabs  do you know of any guidance regarding how we should manage this in our SDKs is? I don't see anything like this in our .NET docs or in any other library...

**Comment by benbp** [comment]
@maririos yes the team has been gradually uncovering the hardcoded values that need to be pulled out for multiple cloud support.

Form Recognizer is already partway there. We override the endpointSuffix and endpointValue on a per-cloud basis via the [parameters we pass to the provisioning scripts](https://github.com/Azure/azure-sdk-for-net/blob/cdd3a31f2f96cd0c72e79c64b836c1ad06430262/sdk/formrecognizer/test-resources.json#L51). I believe if you consume the DefaultCognitiveScope value the same way you consume the [FORM_RECOGNIZER_ENDPOINT](https://github.com/Azure/azure-sdk-for-net/blob/cdd3a31f2f96cd0c72e79c64b836c1ad06430262/sdk/formrecognizer/test-resources.json#L73-L76) environment variable, we should be able to add the necessary overrides in the sovereign cloud configs we use for live tests.

**Comment by benbp** [comment]
Regarding guidance, there isn't much of a standard yet here, so there isn't much in the way of documentation. I'll be working on this.

**Comment by maririos** [comment]
do you know it this is something we expect to expose for our customers? 
Because although the solution you are proposing will work for our pipelines, it won't be clear for our users so this will involve a bigger conversation with our architects (from all I know).

**Comment by schaabs** [comment]
Client libraries handle this differently depending on how the service handles scopes. A general goal for our track 2 SDK has been to make the service clients determine the scope needed to authenticate calls to the service so customers don't need to.  If it's possible to determine the scope based off the service endpoint, I would suggest doing this. 

However this might not be possible in the case that the service supports vanity URLs or something similar.  For services which have different default scopes for different clouds and you cannot determine the cloud based off the service endpoint there are generally two options. The preferred approach here would be for the service to provide the scope in an authentication challenge. This is what the Key Vault library does and other services have started following suit such as Storage. However, this most likely would require work on the service side. In this case this isn't possible the last resort would be to add an option which users can set to specify the scope (or scope base for services which use different scopes per method rather than .default). We haven't needed to cross this bridge yet fortunately, but if we must in this case we'll need to have a deeper discussion on what this should look like. 

Lastly, I would advise against using an environment variable to control this as it would limit users ability to write code which interacts with multiple clouds. Even if we did decide to make this configurable via environment variable it would need to be configurable via code as well. So if it's required to allow users to configure scope directly I think we should start with it being configurable via code.

**Comment by benbp** [comment]
Environment variables have been the way we bridge cloud configuration from the test pipeline infrastructure through the arm templates to the test context, so I was coming at it from that angle. I agree @schaabs that if the SDK can figure these things out on its own without the need for configuration (or keeping the configuration in the internal testing scope only), that's ideal.

**Comment by schaabs** [comment]
@maririos do you know if the cloud can be determined by the client internally based off the endpoint provided?

**Comment by maririos** [comment]
>@maririos do you know if the cloud can be determined by the client internally based off the endpoint provided?

After asking the service, yes, we can. Although it is unsure what will happen if the user decides to create a private link/domain (do you know more about this? I have been trying to play around with it but still blocked on making a service call with a private link)

**Comment by jongio** [comment]
Can we get an update on this issue please?

**Comment by maririos** [comment]
This is the same as in TA issue #18520
The same comment about priority applies here, so let me know if there is an urgency to get it fixed.

**Comment by jongio** [comment]
@v-xuto - Can you please do a PR for this?  @maririos can be advisor.  Thanks

**Comment by v-xuto** [comment]
@jongio - Working on this.

**Comment by jongio** [comment]
We are holding on fixing this until the ACR design is complete. https://github.com/azure/azure-sdk-for-net/issues/21603#issuecomment-865408535

**Comment by zedy-wj** [comment]
Hi, @benbp, @jongio, @maririos! We noticed that the `TokenCredential` has been updated, so we started to retry `form recognizer` tests in sovereign clouds. All tests look fine in public cloud, but when we switched to usgov cloud, some tests related to AAD Authentication failed. Because the `DefaultCognitiveScope` was hardcoded in the [code](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/formrecognizer/Azure.AI.FormRecognizer/src/Constants.cs#L12) and report error message : 
```
  Error Message:
   Azure.RequestFailedException : Service request failed.
Status: 401 (Unauthorized)

Content:
{ "statusCode": 401, "message": "Unauthorized. Access token is missing, invalid, audience is incorrect (https://cognitiveservices.azure.us), or have expired." }

Headers:
apim-request-id: 432a5115-feff-4164-8918-884143c10177
Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
X-Content-Type-Options: nosniff
Date: Mon, 27 Sep 2021 05:53:57 GMT
Content-Length: 160
```


**Example test** : [CopyModel(True) ](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/formrecognizer/Azure.AI.FormRecognizer/tests/FormTrainingClient/FormTrainingClientLiveTests.cs#L396-L418)
So we tried to set `AuthorityHost ` and `DefaultCognitiveScope `with the value in usgov, it reported new error message : `"API/SKU combination not supported for AAD Authentication."`:
![image](https://user-images.githubusercontent.com/81678720/135036318-8f8bb5f2-7726-4d4d-b41c-9e94b25b87dc.png)

![image](https://user-images.githubusercontent.com/81678720/135036436-43b00044-6143-4783-a90c-e038019cac96.png)


Whether it is enabled in usgov or am I missing anything?

**Comment by maririos** [comment]
> We are holding on fixing this until the ACR design is complete. #21603 (comment)

The work was completed but hasn't been applied to FR or TA. Until that doesn't happen, the AAD test will keep failing

**Comment by nisha-bhatia** [comment]
This bug fix will go out in the next release.
