### ISSUE TITLE
Storage Test Failures do not cause the pipeline to fail

### ISSUE THREAD

**Issue by mikeharder** [Azure/azure-sdk-for-net#17299]
It appears that tests in pipeline `net - storage - tests` can fail but they are not reported as "failures" and the pipeline is considered passing.  Here's an example build:

https://dev.azure.com/azure-sdk/internal/_build/results?buildId=637940&view=ms.vss-test-web.build-test-results-tab

Even though the UI shows two tests which failed, it also shows "0 Failed" and the pipeline is green.

Does the pipeline have a bug where failed tests or an non-zero exit code from some process is being ignored?

I'm not sure if this is specific to Storage or impacts all .NET pipelines.

**Comment by kasobol-msft** [comment]
We used "Re-run failed jobs" to retry. This is expected.

**Comment by weshaggard** [comment]
Yes this reporting issue is because of the retries. The pipeline in the end all jobs passed but earlier attempts had failed tests which is why they show up in the test results as failed tests. I don't know if there is a good way to filter to only the last passing test results but in either case it is probably good they show there so we know the flakey tests.
