### ISSUE TITLE
CloudConfigurationManager.GetSetting signature changed in version 3.2.0 and broke our code

### ISSUE THREAD

**Issue by Karamell** [Azure/azure-sdk-for-net#1738]
We passed on `GetSetting` as a Func, and in version 3.2.0 the signature changed. It would have been better if an overload was used so that old versions don't break.

Not just
```csharp
public static string GetSetting(string name, bool outputResultsToTrace = true)
``` 
but also keep the old function, thus not changing the signature
```csharp
public static string GetSetting(string name, bool outputResultsToTrace)
{
     //code
}
public static string GetSetting(string name)
{
    return GetSetting(string name, true);
}


```

**Comment by ca-ta** [comment]
:+1: Same here. We keep being tripped by `CloudConfigurationManager`. Funny, seeing  how it only has one public method.

This component has superfluously broken backwards compatibility before (e.g. by changing the namespace name). Yes, one can/should break compatibility *if necessary*. However, I feel it is bad practice to do so if easily avoidable.

**Comment by akrause32** [comment]
:+1: Same here, albeit with a different scenario.

We have an internal NuGet package which references CloudConfigurationManager.GetSetting(string) using Microsoft.WindowsAzure.Configuration 3.1.0. Projects which utilize this package could previously use assembly binding redirects to update the Configuration NuGet independently. This change has broken that ability. Projects which update to version 3.2.0 will get a MissingMethodException since the method's signature has changed.

**Comment by AndyCJ** [comment]
We've also been tripped up by this.

If you aren't already aware of what causes binary incompatibilities SO has a good guide here: http://stackoverflow.com/questions/1456785/a-definitive-guide-to-api-breaking-changes-in-net

> Adding a parameter with a default value.
Kind of Break: Binary-level break

>Even if the calling source code doesn't need to change, it still needs to be recompiled (just like when adding a regular parameter).

**Comment by hovsepm** [comment]
@Karamell thank you for your contribution!

The package with the fix is released to nuget. Please reference Microsoft.WindowsAzure.ConfigurationManager version 3.2.1.
