### ISSUE TITLE
[Storage] Livetests - Actively wait for RBAC assignments.

### ISSUE THREAD

**Issue by kasobol-msft** [Azure/azure-sdk-for-net#17384]
It may take up to 5 minutes for RBAC (AAD) role assignments to replicate. This makes live tests flaky.
The short term solution is to add "sleep" after test resources provisioning.
This issue is to find better solution - i.e. actively query whether replication took place.
Possibilities:
- discover and query API that returns assignments
- keep executing small suite of tests that would fail until replication is complete (i.e. smoke tests discussed in https://github.com/Azure/azure-sdk/issues/2025 )

**Comment by kasobol-msft** [comment]
One other option is to make assignments at resource group level before account creation.

**Comment by JoshLove-msft** [comment]
Is this 5 minute lag specific to storage, or is it the same for all services?

**Comment by kasobol-msft** [comment]
https://docs.microsoft.com/en-us/azure/storage/common/storage-auth-aad-rbac-portal
![image](https://user-images.githubusercontent.com/61715331/102410143-f9056980-3fa4-11eb-9e92-f8df77a891ee.png)

I'm not aware of how other services do that.

**Comment by mvelosop** [comment]
Hi, excuse me for jumping in, just found this issue looking a solution to a "mistery" that might be related to this although, perhaps, it's a bit extranger.

This is related to a devops pipeline that fails because the service principal of the service connection can't set a policy on a keyvault so a webapp with SMI can read the KV secrets, even though the related AD app has the Owner role on the Azure subscription where the KV is created.

The pipeline is triggered after an installation script that finishes by pushing code to a DevOps repo.

The permission problem occurs about half an hour after the KV has been created and the role granted.

And the "solution" is to request the user to log in again, before the installation script completes.

Does this qualify as a "case study" someone on your team might tackle?

TIA 😊

**Comment by mvelosop** [comment]
Hi @kasobol-msft, thanks for the reply.

Well, I didn't explained myself good enough.

What I meant to convey with the part you quoted. is that the role is needed about half an hour after it's been granted, wich is much more than the five minutes metioned here.

I considered the token expiration might've been an issue, so I log out and then log in back again to ensure a fresh session.

Thanks anyway 😊

**Comment by JimSuplizio** [comment]
Hi @kasobol-msft, we deeply appreciate your input into this project. Regrettably, this issue has remained inactive for over 2 years, leading us to the decision to close it. We've implemented this policy to maintain the relevance of our issue queue and facilitate easier navigation for new contributors. If you still believe this topic requires attention, please feel free to create a new issue, referencing this one. Thank you for your understanding and ongoing support.
