### ISSUE TITLE
Azurite fails to start in tests runs

### ISSUE THREAD

**Issue by pakrym** [Azure/azure-sdk-for-net#17410]
Still happening https://dev.azure.com/azure-sdk/public/_build/results?buildId=646247&view=logs&j=9cfc3b0b-53b1-524f-85ed-0ef4880bef82&t=277ae693-9b68-5ef5-d666-bb5a558e8cc2

```
   OneTimeSetUp: System.InvalidOperationException : 
Could not run Azurite based test due to: azurite process could not start with following output:

and error:
.
Make sure that:
- NodeJS is installed and available in $PATH (i.e. 'node' command can be run in terminal)
- Azurite V3 is installed via NPM (see https://github.com/Azure/Azurite for instructions)
- AZURE_AZURITE_LOCATION envorinment is set and pointing to location of directory that has 'azurite' command (i.e. run 'where azurite' in Windows CMD)



```

cc @kasobol-msft

**Comment by kasobol-msft** [comment]
The absence of output made me find this https://github.com/dotnet/runtime/issues/18789 and plenty of similar posts on stackoverflow and other places. Then I found this https://github.com/dotnet/runtime/issues/28025 .
Maybe we're using .netcore version that still has these problems.

As a workaround - instead of using these events I could spin out a Thread that reads from process.StandardInput directly. @pakrym  what do you think?

**Comment by pakrym** [comment]
We are waiting 15 seconds before firing the exception. Should be plenty for stdout to flush.

**Comment by kasobol-msft** [comment]
I hope this will yield more answers https://github.com/Azure/azure-sdk-for-net/pull/17419
