### ISSUE TITLE
[BUG] Custom Timeout doesn't work anymore in Azure.Messaging.EventHubs (5.2.0)

### ISSUE THREAD

**Issue by andregodin** [Azure/azure-sdk-for-net#17500]
In the previous version of Azure.Messaging.EventHubs the CancellationToken Timeout is working correctly but with the latest version of Azure.Messaging.EventHub, the same timeout doesn't work anymore and it just consider a default Timeout of 60 seconds.

I wrote a test to prove it using the example provided in: https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/eventhub/Azure.Messaging.EventHubs/samples/Sample05_ReadingEvents.md#read-events-from-a-partition

```csharp
using System;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Azure.Messaging.EventHubs.Consumer;
using Xunit;

namespace XUnitTestEventHub
{
    public class EventHubTests
    {
        private const string EventHubConnString = "Endpoint=...PRIVATE...";
        private const string EventHubConsumerGroup = EventHubConsumerClient.DefaultConsumerGroupName;

        [Fact]
        public async Task TimeoutIssue_AzureMessagingEventHubs_Demo()
        {
            await using var consumer = new EventHubConsumerClient(EventHubConsumerGroup, EventHubConnString);

            using CancellationTokenSource cancellationSource = new CancellationTokenSource();
            cancellationSource.CancelAfter(TimeSpan.FromSeconds(5)); // This timeout doesn't work in Azure.Messaging.EventHubs (5.2.0) !

            await Assert.ThrowsAsync<TaskCanceledException>(async () =>
            {
                var firstPartition = (await consumer.GetPartitionIdsAsync(cancellationSource.Token)).First();

                await foreach (var partitionEvent in consumer.ReadEventsFromPartitionAsync(firstPartition, EventPosition.Earliest, cancellationSource.Token))
                {
                    //Irrelevant considering we are testing timeout when no event receive
                }
            });
        }
    }
}
```
We can see in the images attached that for the same code, the version 5.1.0 timeout at 5 seconds, 
![Azure Messaging EventHubs(5 1 0)](https://user-images.githubusercontent.com/43258445/102097643-2ced5d00-3df4-11eb-93e2-ac10e94617d8.png)

but the versions 5.2.0 timeout at 1 minute
![Azure Messaging EventHubs(5 2 0)](https://user-images.githubusercontent.com/43258445/102097677-37a7f200-3df4-11eb-8674-beac2fdbca16.png)

Tested locally:
![image](https://user-images.githubusercontent.com/43258445/102097888-7a69ca00-3df4-11eb-8aab-c1ca491c1305.png)

**Comment by jsquire** [comment]
This behavior has not changed; it is an unfortunate limitation of our network transport dependency and has been consistent since the initial beta of `Azure.Messaging.EventHubs`. 

The underlying transport library for AMQP used by the Event Hubs client does not respect cancellation tokens.   The client does its best to honor them, however, once there is an active service request, it is unable to do so.   The `TryTimeout` of the configured retry policy is used for the timeout value associated with service requests and, as you observed, has a default value of 60 seconds.   This can be configured as part of the options for the client, as discussed in [this sample](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/eventhub/Azure.Messaging.EventHubs/samples/Sample02_EventHubsClients.md#configuring-the-client-retry-thresholds).

**Comment by andregodin** [comment]
Thanks @jsquire ,

I did not know about this limitation, so from my point of view the behavior was different from the previous version.

I'll try the sample you provided

If the new releases of AMQP (https://github.com/Azure/azure-amqp/releases) are not fixing the issue, would it be possible to mention the limitation in the sample I used  (https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/eventhub/Azure.Messaging.EventHubs/samples/Sample05_ReadingEvents.md#read-events-from-a-partition) ?

You can close this ticket ;)

**Comment by andregodin** [comment]
I tried to used the `RetryOptions.TryTimeout` in my previous test and the timeout is working but not with the one I specified in the RetryOptions!?

It timeout at 10 seconds instead of 5!  

`using System;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Azure.Messaging.EventHubs.Consumer;
using Xunit;

namespace XUnitTestEventHub
{
    public class EventHubTests
    {
        private const string EventHubConnString = "Endpoint=...PRIVATE...";
        private const string EventHubConsumerGroup = EventHubConsumerClient.DefaultConsumerGroupName;

        [Fact]
        public async Task TimeoutIssue_AzureMessagingEventHubs_Demo()
        {
            var consumerOptions = new EventHubConsumerClientOptions();
            consumerOptions.RetryOptions.TryTimeout = TimeSpan.FromSeconds(5);

            await using var consumer = new EventHubConsumerClient(EventHubConsumerGroup, EventHubConnString, consumerOptions);

            using CancellationTokenSource cancellationSource = new CancellationTokenSource();
            cancellationSource.CancelAfter(TimeSpan.FromSeconds(10)); // This timeout doesn't work in Azure.Messaging.EventHubs (5.2.0) !

            await Assert.ThrowsAsync<TaskCanceledException>(async () =>
            {
                var firstPartition = (await consumer.GetPartitionIdsAsync(cancellationSource.Token)).First();

                await foreach (var partitionEvent in consumer.ReadEventsFromPartitionAsync(firstPartition, EventPosition.Earliest, cancellationSource.Token))
                {
                    //Irrelevant considering we are testing timeout when no event receive
                }
            });
        }
    }
}`

**Comment by andregodin** [comment]
It's really weird!

The timeout of the CancellationToken is only considered when we are using a EventHubConsumerClientOptions who specified a RetryOptions.TryTimeout no matter the value specified in it.

**Comment by jsquire** [comment]
What you're seeing is the expected behavior.  As you may have gleaned from its name, the `TryTimeout` governs one call to the service.   In the event that the operation exceeds the `TryTimeout` a failure occurs that is considered retriable.  The client will continue to apply the retry policy until attempts are exhausted or the operation succeeds/fails fatally.

When the operation times out, control returns to the client from the transport library.   At that point, the client will take the cancellation token into account and respect it - skipping retries if the token is signaled.   In your latest snippet, you're using the default value of 3 retry attempts.  The first and second service may timeout after 5 seconds _(or may not timeout because it has completed)_.    After the second retry, your cancellation token would be signaled - so you'd see the call abort with cancellation at roughly the 10 second mark.

**Comment by andregodin** [comment]
Well if you're right, how do you explain this:

`[Fact]
        public async Task TimeoutIssue_AzureMessagingEventHubs_Demo()
        {
            var consumerOptions = new EventHubConsumerClientOptions();
            consumerOptions.RetryOptions.TryTimeout = TimeSpan.FromSeconds(1);
            consumerOptions.RetryOptions.MaximumRetries = 1;

            await using var consumer = new EventHubConsumerClient(EventHubConsumerGroup, EventHubConnString, consumerOptions);

            using CancellationTokenSource cancellationSource = new CancellationTokenSource();
            cancellationSource.CancelAfter(TimeSpan.FromSeconds(10)); 

            await Assert.ThrowsAsync<TaskCanceledException>(async () =>
            {
                var firstPartition = (await consumer.GetPartitionIdsAsync(cancellationSource.Token)).First();

                await foreach (var partitionEvent in consumer.ReadEventsFromPartitionAsync(firstPartition, EventPosition.Earliest, cancellationSource.Token))
                {
                    //Irrelevant considering we are testing timeout when no event receive
                }
            });
        }`
![image](https://user-images.githubusercontent.com/43258445/102142267-1c5ad800-3e30-11eb-924c-a7d1055571f6.png)

**Comment by andregodin** [comment]
Sorry for the code being malformed
Is seems that the "insert code" doesn't work correctly or I'm just too stupid to know how to use it

**Comment by jsquire** [comment]
The first time that you perform a service operation, an AMQP connection is opened to the service, a corresponding AMQP session is created, and in the case of a management operation, two AMQP links are opened.  When you're using `ReadEventsFromPartition` an AMQP link has to be opened to each partition of the Event Hub, a bounded channel is created, and events flow into the channel as part of a background process.  Once cancellation or timeout is acknowledged, each of these needs to be cleaned up, awaited, and closed down.

This will take a non-deterministic amount of time, depending on a variety of factors in the application, on the host machine, and at the service-side.  You're not going to see precise timing - especially when using a higher level construct built for exploration rather than throughput and efficient resource use.

May I ask what your goal is for this particular test or what behavior in your application you're looking to better understand?

**Comment by andregodin** [comment]
It's just a part of an Utility class I made to help me monitoring EventHubs in IntegrationTests.

I still find it weird that using official example from up-to-date microsoft's github was working in version 5.1.0 but not in the 5.2.0.

To conclude what you're saying is that the example of "CancellationToken Timeout" was not supposed to work in 5.1.0 and if we want to make it work properly we need to specified a value to "RetryOptions.TryTimeout".  

Is that right?

**Comment by jsquire** [comment]
To be sure that I'm not misremembering, I took a walk through history and can confirm that we've made no changes to how we process cancellation between 5.1.0, 5.2.0, and latest.  Neither the client code paths nor the tests that validate were changed functionally.  The closest set of changes that may impact timing were restructuring how events are read from a single partition with consumer client and adjustments to the default sizing for background publishing.  

I don't see anything that indicates the potential for a behavioral change or regression, though to say that definitively, I'd need to block some time to dig in and do a side-by-side investigation.  If this is something that you feel is important to you and impactful to your application, I'm happy to do so, though I won't be available to do so until after the holidays.

**Comment by jsquire** [comment]
> To conclude what you're saying is that the example of "CancellationToken Timeout" was not supposed to work in 5.1.0 and if we want to make it work properly we need to specified a value to "RetryOptions.TryTimeout".

> Is that right?

That's not quite what I'm trying to convey.   The take-away that I'm going for is "Cancellation is performed as best-effort attempt by the Event Hubs clients and is influenced by a number of factors.  Timing is non-deterministic and will vary depending on what the state of the client is when cancellation is requested." 

Some of the impactful factors for cancellation are:

- The client is unable to signal cancellation to the transport; if a service operation is active, it must either succeed, fail, or timeout to complete.  The client will attempt to honor cancellation, if possible, when the operation returns control.

- Most forms of timeout that occur during service calls are considered transient and the client will apply the retry policy accordingly.  Between retry attempts, the client will attempt to honor cancellation.

- The client will ensure that state is not corrupted and will not honor cancellation if it would result in an inconsistent state.

- The client will ensure that resource cleanup is performed.  When honoring cancellation, there may be a delay due to awaiting background tasks, disposing resources, and updating client state.

- The configuration of the client plays a role in cancellation timing; for example, the `CacheEventCount` and `PrefetchCount` of the `EventHubConsumerClient` play heavily into the frequency and length of service operations.

- The traffic flowing through an Event Hub has an impact on cancellation for clients when publishing and reading events;  this includes the average event size as well as the frequency.  Both play into the frequency and length of service operations.

**Comment by andregodin** [comment]
Thanks again @jsquire for the investigation and the detailed answer.

All I can say is that I was able to cancel the operation in 5.1.0 without noticable delay, but in 5.2.0 I now have to specify the RetryOption.TryTimeout.  I just tought it was a bug that you need to be aware of.

I did some research from my side too and I would probably just revisit the monitoring of eventHub by using the EventProcessorHost.  It should be simpler to use.

Feel free to investigate deeper or not

Best wishes and happy new year ;)

**Comment by jsquire** [comment]
Thank you for bringing this to our attention, the discussion, and for the detailed context around your scenarios.  I'm going to stash this to do some poking around, just to confirm that there's nothing amiss.

Happy new year to you as well!

**Comment by jsquire** [comment]
This turns out to be entirely on me; my memory of the structural change did not take into account some of the behavioral differences.  You are seeing a different responsiveness on timeouts, and it is an expected one due to shifting the priority of the trade-offs that we made in the implementation.  The key is this statement:

> The closest set of changes that may impact timing were restructuring how events are read from a single partition with consumer client and adjustments to the default sizing for background publishing.

The TLDR version is that, yes, there is a behavioral difference between 5.1.0 and 5.2.0.  The current behavior is expected due to performance enhancements.  My last comment from December 15 is accurate with respect to how things operate.

**Detailed context:**

In v5.1.0, we had a long pipeline for reading events where a background task would push events to a channel that the asynchronous enumerator would read from.  This allowed the loop to be more responsive to cancellation from a caller's perspective because the teardown of the background thread was responsible for dealing with the service communication timeout as well as other infrastructure.  

We did this primarily to keep a unified approach to `ReadEvents` and `ReadEventsFromPartition` so that we could share code between them; the benefit of hiding the underlying timeout-based nature of the transport was a benefit that we hadn't really considered.  There were some significant downsides to this approach in terms of complexity and performance.  The performance aspects were something that we received quite a bit of feedback on.  There was a fairly large performance drift between the `EventHubConsumerClient` and `PartitionReceiver` in the new library and when compared to the `PartitionReceiver` in the legacy library.  

In 5.2.0, we decided that there weren't enough benefits to justify the approach.  We wanted to allow developers to use the asynchronous enumerable pattern without taking a performance penalty, so we removed the background publishing pipeline in favor of a very thin wrapper over the transport - synonymous with the abstraction of the `PartitionReciever`, just exposed as a different paradigm.  The unfortunate side-effect of this is the loss of an abstraction over the transport, surfacing the timeout-based nature more directly.
