### ISSUE TITLE
Service level overview for Event Hubs not updated even though the backing page in GitHub has been updated

### ISSUE THREAD

**Issue by ramya-rao-a** [Azure/azure-sdk-for-net#17574]
Our understanding was that the [Service level readme for Event Hubs reference docs](https://docs.microsoft.com/en-us/dotnet/api/overview/azure/eventhubs?view=azure-dotnet) was backed by the content in https://github.com/Azure/azure-docs-sdk-dotnet. @jsquire had updated this in https://github.com/Azure/azure-docs-sdk-dotnet/pull/1685 last month, but the content is not yet updated/refreshed.

Found during https://github.com/azure/azure-sdk-for-net/issues/16736

**Comment by scbedd** [comment]
This was immediately suspicious as the updates are definitely happening.




12/8: https://github.com/Azure/azure-docs-sdk-dotnet/pull/1711
12/15: https://github.com/Azure/azure-docs-sdk-dotnet/pull/1718

The real reason this is occurring is because the service overview isn't attached.  When you see this: 
![image](https://user-images.githubusercontent.com/45376673/102551301-1bb28380-4074-11eb-9a9c-8e2fb5ecab35.png)

it is pretty much always a case of _mapping_ a file into the ToC.

[This PR](https://github.com/Azure/azure-docs-sdk-dotnet/pull/1724) fixes the issue.
