### ISSUE TITLE
[BUG] Receiving duplicate messages during consumer rebalancing to new partitions

### ISSUE THREAD

**Issue by Marusyk** [Azure/azure-sdk-for-net#17651]
**Describe the bug**
I'm using EventHub build-in endpoint in IoT Hub to read device messages by backend service. (1 consumer group and 4 partitions).

When there is 1 consumer application, then everything works fine.

After scale up instances to 2, change partition ownership is starting. During this process, the consumer apps start receiving duplicate messages. After partition ownership changed, everything works fine. The problem is with duplication. The process of changing partition ownership takes some time and I got more than 150 duplicate messages during that time. Could you please advise how to avoid duplication?

Before I worked with Kafka and there the rebalancing process works very fast and I didn't have any problems with duplication on scaling.

Why EventHub still sending messages to consumer applications within one consumer group? Could you please suggest?

**Expected behavior**
The EventHub should not send the same message to all consumer applications within one consumer group

**Actual behavior (include Exception or Stack Trace)**
Receiving duplicate messages during consumer rebalancing to new partitions.
See logs

> >-- Instance 1
> [20-12-18 22:40:37.37Z INF] Application started.
> [20-12-18 22:40:38.38Z INF] Assigned partition: 1 
> [20-12-18 22:40:47.47Z INF] Assigned partition: 3 
> [20-12-18 22:40:57.57Z INF] Assigned partition: 2 
> [20-12-18 22:41:07.07Z INF] Assigned partition: 0 
> [20-12-18 22:44:51.51Z INF] Event State received from DevEmulator.dev. Offset: 107375707664. Payload: {"EquipmentNumber":"3333333","CabinPosition":1}. Partition: 1. 
> [20-12-18 22:44:54.54Z INF] Event State received from DevEmulator.dev. Offset: 107375708176. Payload: {"EquipmentNumber":"2222222","CabinPosition":1}. Partition: 1. 
> [20-12-18 22:44:55.55Z INF] Unassigned partition: 2 
> [20-12-18 22:44:59.59Z INF] Event State received from DevEmulator.dev. Offset: 107375716984. Payload: {"EquipmentNumber":"7777777","CabinPosition":1}. Partition: 1. 
> [20-12-18 22:45:00.00Z INF] Unassigned partition: 1 
> 
> -- Instance 2
> [20-12-18 22:44:38.38Z INF] Application started.
> [20-12-18 22:44:39.39Z INF] Assigned partition: 2 
> [20-12-18 22:44:48.48Z INF] Assigned partition: 1 
> [20-12-18 22:44:51.51Z INF] Event State received from DevEmulator.dev. Offset: 107375707664. Payload: {"EquipmentNumber":"3333333","CabinPosition":1}. Partition: 1. 
> [20-12-18 22:44:51.51Z INF] Event State received from DevEmulator.dev. Offset: 107375708176. Payload: {"EquipmentNumber":"2222222","CabinPosition":1}. Partition: 1. 
> [20-12-18 22:44:59.59Z INF] Event State received from DevEmulator.dev. Offset: 107375716984. Payload: {"EquipmentNumber":"7777777","CabinPosition":1}. Partition: 1. 
> [20-12-18 22:45:01.01Z INF] Event State received from DevEmulator.dev. Offset: 107375727824. Payload: {"EquipmentNumber":"2222222","CabinPosition":2}. Partition: 1. 

As you can see, Instance 1 started and has owned all partitions (1,2,3,4) .
Then, start the Instance 2 and start listening to Partition 1. At this time my Instance 1  and Instance 2 are listening to the same Partition 1. After `Unassigned partition: 1 ` occurs in Instance 1, the problem with duplicates is gone.

**To Reproduce**

1. Create a simple EventHub consumer

```
_eventProcessor = new EventProcessorClient(
	storageClient,
	EventHubConsumerClient.DefaultConsumerGroupName,
	options.EventHubConnectionString,
	options.EventHubName);

_eventProcessor.ProcessEventAsync += ProcessMessage;
_eventProcessor.ProcessErrorAsync += ExceptionReceivedHandler;
_eventProcessor.PartitionInitializingAsync += AssignPartition;
_eventProcessor.PartitionClosingAsync += UnassignPartition;
```

where `ProcessMessage` is:

```
private async Task ProcessMessage(ProcessEventArgs eventArgs)
{
	EventData eventData = eventArgs.Data;
	string equipmentNumber = eventData.SystemProperties["iothub-connection-device-id"].ToString();
	string message = Encoding.UTF8.GetString(eventData.Body.ToArray());


	_logger.LogInformation(
		"Event State received from {EquipmentNumber}. Offset: {Offset}. Payload: {Payload}. Partition: {Partition}.",
		equipmentNumber, eventData.Offset, message, eventArgs.Partition.PartitionId);

	...

	await eventArgs.UpdateCheckpointAsync(eventArgs.CancellationToken);
}
```

2. Start sending messages
3. Run the second instance

**Environment:**
 - Name and version of the Library package used: Azure.Messaging.EventHubs 5.1.0, Azure.Messaging.EventHubs.Processor 5.1.0, 
 - Hosting platform or OS - docker, linux 
 - .NET runtime version 3.1
 - IDE and version : Visual Studio 16.8.3

**Comment by jsquire** [comment]
Hi @Marusyk.  Thank you for your feedback and we regret that you're experiencing difficulties.   In this case, what you're seeing is the expected behavior when processor instances are scaling.  

When a processor is starting up, it will attempt to balance the work for processing with other processors active for the same consumer group.  In the case where a processor isn’t able to reach its fair share of the work by claiming unowned partitions, it will attempt to steal ownership of partitions from other processors.  During this time, the new owner will begin reading from the last recorded checkpoint.  At the same time, the old owner may be dispatching the events that it last read to the handler for processing; it will not understand that ownership has changed until it attempts to read the next set of events from the Event Hubs service.
 
As a result, you will see some duplicate events being processed when processors are started or stopped which will subside when the processors have reached a stable state with respect to load balancing.  The duration of that window will differ depending on the configuration of your processor and your checkpointing strategy.   

> Could you please advise how to avoid duplication?

An important call-out is that Event Hubs has an at-least-once delivery guarantee; duplication is possible when consuming events regardless of the client used. 
 It is highly recommended that you ensure that your processing is resilient to event duplication in whatever way is appropriate for your application scenarios.  

The most common technique is for publishers to inject a property that contains a unique identifier for the event, and consumers track the ids that have been processed for a rolling window of time, discarding duplicates.  Another common approach is to deploy a static set of `EventProcessorClients` that can handle the maximum expected load; those will still see duplication during the initial startup but won't see additional periods, as there is no scaling.  

Some applications with extreme sensitivity to duplication will choose to bypass using the `EventProcessorClient` and instead use the `PartitionReceiver`,  managing checkpointing, load balancing, resilience, and fail-over at the application-level.  This approach shifts much of the responsibility handled by the processor to the host application, but allows the application to have full control.

It is also possible to implement a more robust method of load balancing that uses a central point of coordination or a peer-to-peer mesh approach by extending the `EventProcessor<TPartition>`,  though that would involve trade-offs around additional hosting cost, increased complexity, and lower throughput.   

Just to mention again, any of these approaches would still be subject to the potential for duplication due to the service guarantee.

**Comment by Marusyk** [comment]
Thank you very much for such a detailed answer. Really appreciate it. Thanks
