### ISSUE TITLE
[BUG] Storage: Confusing error message returned when user delegation key interval is invalid

### ISSUE THREAD

**Issue by tamram** [Azure/azure-sdk-for-net#17690]
**Describe the bug**
I am seeing this message intermittently with what should be a valid user delegation key period (exactly 7 days), but perhaps isn't due to clock skew. And I am also seeing it with a clearly invalid key key period (e.g., 9 days). 

The error message could be confusing to customers as it doesn't indicate what the problem is. A few customers have been confused by this:

https://github.com/Azure/azure-sdk-for-net/issues/12595
https://www.nuomiphp.com/eplan/en/419091.html

**Expected behavior**

An error message that indicates that the user delegation key period is invalid.

**Actual behavior (include Exception or Stack Trace)**

{"The value for one of the XML nodes is not in the correct format.\nRequestId:6f914103-b01e-0132-539c-d826ec000000\nTime:2020-12-22T19:54:03.5264336Z\r\nStatus: 400 (The value for one of the XML nodes is not in the correct format.)\r\nErrorCode: InvalidXmlNodeValue\r\n\r\nAdditional Information:\r\nXmlNodeName: 2020-12-29T19:54:04Z\r\nXmlNodeValue: 2020-12-29T19:54:04Z\r\n\r\nHeaders:\r\nx-ms-request-id: 6f914103-b01e-0132-539c-d826ec000000\r\nx-ms-client-request-id: 18c14232-1b8c-4a6e-b334-b51dd6ddfc93\r\nx-ms-version: 2020-02-10\r\nx-ms-error-code: InvalidXmlNodeValue\r\nContent-Length: 348\r\nContent-Type: application/xml\r\nDate: Tue, 22 Dec 2020 19:54:02 GMT\r\nServer: Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0\r\n"}

**To Reproduce**
Steps to reproduce the behavior (include a code snippet, screenshot, or any additional information that might help us reproduce the issue)

1. Create a user delegation key with an invalid period, e.g.:

            UserDelegationKey userDelegationKey =
                await blobServiceClient.GetUserDelegationKeyAsync(DateTimeOffset.UtcNow,
                                                                  DateTimeOffset.UtcNow.AddDays(9));

2. Run and view error.

**Environment:**
 - Name and version of the Library package used: [e.g. Azure.Storage.Blobs 12.7.0] 
 - Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects): [e.g. Azure AppService or Windows 10 .NET Framework 4.8]
 - IDE and version : Visual Studio 16.8.3

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.  Please be aware that due to the holidays, responses may be delayed.

**Comment by amnguye** [comment]
Unfortunately this is the exact error message we receive from the service and not from the SDK. I can see why that would be the correct error message for 9 days since you can only specify the key to be valid for a period of up to seven days. I think it would be more clear if the message was along the lines of "The set expirey time is not a valid value" since it would go over the amount. If they specify exactly 7 days it could get affected by the time skew so then it should also have a similar message.

I will log a backlog item for the 9 days message being confusing.

If possible if you received the error when you tried 7 days, could you send me the error log including the x-ms-request-id so I can properly see what's happening with the exact time we are sending and see why we're getting that error back? Thanks

**Comment by amnguye** [comment]
Received request-id offline. Looks like after some investigation that there's a time skew, and it might be causing it by a second. Which is why the error is being thrown because it thinks we are handing it a value over the 7 day limit. We can either try to round down `DateTimeOffset` by a second, but it might mess with the already successful 7 day conversion. So we will have to see if there's a way to have `DateTimeOffset` to round down instead of up when converting `DateTimeOffset` to the 7 day value from the current time and date.

**Comment by tamram** [comment]
@amnguye - I'm not sure how to remove the no-recent-activity label. Adding activity so this doesn't get closed if you're still investigating.

**Comment by amnguye** [comment]
Yeah I'm not sure why the bot did that, considering this isn't even a PR. but looks like commenting on the issue removes the tag :)

**Comment by Vishwanath-Reddy-M** [comment]
@tamram ,

Yes, we also ran into same issue and error message is clearly confusing. Ideally it should show "An error message that indicates that the user delegation key period is invalid."

rather than it's giving big message with xml....  and later narrowdown problem is caused by adding more than 7 days.

Below documentation which tells max duration is 7 days:

https://learn.microsoft.com/en-us/azure/storage/blobs/storage-blob-user-delegation-sas-create-cli#use-microsoft-entra-credentials-to-secure-a-sas

Regards,
Vishwa

**Comment by JimSuplizio** [comment]
Hi @tamram, we deeply appreciate your input into this project. Regrettably, this issue has remained inactive for over 2 years, leading us to the decision to close it. We've implemented this policy to maintain the relevance of our issue queue and facilitate easier navigation for new contributors. If you still believe this topic requires attention, please feel free to create a new issue, referencing this one. Thank you for your understanding and ongoing support.
