### ISSUE TITLE
ASP.NET Core SSO with Azure AD. Got SecurityTokenSignatureKeyNotFoundException: Signature validation failed. Unable to match key Signature validation failed. On POST /signin-oidc request.

### ISSUE THREAD

**Issue by tatarincev** [Azure/azure-sdk-for-net#17695]
**Describe the bug**
We have the ASP.NET Core 3.1 web application that has SSO configured with Azure AD.
The problem is that for some AD (for some AD all work well) we receive this error on 
`POST https://localhost:5001/signin-oidc` request.
```
Microsoft.IdentityModel.Tokens.SecurityTokenSignatureKeyNotFoundException: IDX10501: Signature validation failed. Unable to match key
```
here is our config in startup.cs
https://github.com/VirtoCommerce/vc-platform/blob/master/src/VirtoCommerce.Platform.Web/Startup.cs#L240
```C#
 authBuilder.AddOpenIdConnect("AzureAD", "Azure Active Directory",
                        openIdConnectOptions =>
                        {
                            openIdConnectOptions.ClientId = "my AD application id";
                            openIdConnectOptions.Authority = $"https://login.microsoftonline.com/my AD tenant id";
                            openIdConnectOptions.UseTokenLifetime = true;
                            openIdConnectOptions.RequireHttpsMetadata = false;
                            openIdConnectOptions.SignInScheme = IdentityConstants.ExternalScheme;
                            openIdConnectOptions.SecurityTokenValidator = new  JwtSecurityTokenHandler();
                        });
```
Here is the Azure AD configuration that doesn't work for us
```JSON
{
	"id": "<<hidden for security reasons>>",
	"acceptMappedClaims": null,
	"accessTokenAcceptedVersion": null,
	"addIns": [],
	"allowPublicClient": false,
	"appId": "<<hidden for security reasons>>",
	"appRoles": [
		{
			"allowedMemberTypes": [
				"User"
			],
			"description": "User",
			"displayName": "User",
			"id": "<<hidden for security reasons>>",
			"isEnabled": true,
			"lang": null,
			"origin": "Application",
			"value": null
		},
		{
			"allowedMemberTypes": [
				"User"
			],
			"description": "msiam_access",
			"displayName": "msiam_access",
			"id": "hidden for security reasons",
			"isEnabled": true,
			"lang": null,
			"origin": "Application",
			"value": null
		}
	],
	"oauth2AllowUrlPathMatching": false,
	"createdDateTime": "2020-09-06T10:36:38Z",
	"disabledByMicrosoftStatus": null,
	"groupMembershipClaims": null,
	"identifierUris": [],
	"informationalUrls": {
		"termsOfService": null,
		"support": null,
		"privacy": null,
		"marketing": null
	},
	"keyCredentials": [],
	"knownClientApplications": [],
	"logoUrl": null,
	"logoutUrl": null,
	"name": "<<hidden for security reasons>>",
	"oauth2AllowIdTokenImplicitFlow": true,
	"oauth2AllowImplicitFlow": false,
	"oauth2Permissions": [
		{
			"adminConsentDescription": "<<hidden for security reasons>>",
			"adminConsentDisplayName": "<<hidden for security reasons>>,
			"id": "<<hidden for security reasons>>",
			"isEnabled": true,
			"lang": null,
			"origin": "Application",
			"type": "User",
			"userConsentDescription": <<hidden for security reasons>>",
			"userConsentDisplayName": "<<hidden for security reasons>>",
			"value": "user_impersonation"
		}
	],
	"oauth2RequirePostResponse": false,
	"optionalClaims": null,
	"orgRestrictions": [],
	"parentalControlSettings": {
		"countriesBlockedForMinors": [],
		"legalAgeGroupRule": "Allow"
	},
	"passwordCredentials": [],
	"preAuthorizedApplications": [],
	"publisherDomain": "<<hidden for security reasons>>",
	"replyUrlsWithType": [
	<<hidden for security reasons>>
	],
	"requiredResourceAccess": [],
	"samlMetadataUrl": null,
	"signInUrl": "<<hidden for security reasons>>",
	"signInAudience": "AzureADMyOrg",
	"tags": [],
	"tokenEncryptionKeyId": null
}
```
**Expected behavior**
The SSO works well as for other AD instances.

**Actual behavior (include Exception or Stack Trace)**
The problem is that for some AD (for some AD all work well) we receive this error on POST https://localhost:5001/signin-oidc request.
```
Microsoft.IdentityModel.Tokens.SecurityTokenSignatureKeyNotFoundException: IDX10501: Signature validation failed. Unable to match key
```

**Environment:**
 - ASP.NET Core 3.1
 - Azure AD

**Comment by jsquire** [comment]
Hi @tatarincev.  Thank you for your feedback and we regret that you're experiencing difficulties.   I'm not able to determine which Azure SDK library that you're looking for assistance with from the context in this issue nor from looking through the references in your project file.   From what I can see, your application is using a combination of the ASP.NET Core built-in authentication libraries and the `OpenIddict` open source library for authentication.   

Unfortunately, the Azure SDK team is not able to assist with libraries that are not part of the Azure SDK.   If I'm mistaken and overlooking something, can you help me understand which Azure library you're working with so that I can involve the correct folks to assist?

As I was looking in your project, I did notice one thing that may (or may not) be something to look at.   In your [Startup](https://github.com/VirtoCommerce/vc-platform/blob/master/src/VirtoCommerce.Platform.Web/Startup.cs#L244), you're building the authority using the pattern `{options.AzureAdInstance}{options.TenantId}` which according to your [settings](https://github.com/VirtoCommerce/vc-platform/blob/master/src/VirtoCommerce.Platform.Web/appsettings.json#L148) would translate to `https://login.microsoftonline.com/{TENANT}`.    If I'm not mistaken, this should be `https://login.microsoftonline.com/{TENANT}/v2.0` assuming that you're using the public cloud.   The wrong authority would seem  seem to correlate with a signature validity failure.

_([refrence](https://docs.microsoft.com/en-us/azure/active-directory/develop/quickstart-v2-aspnet-webapp#owin-startup-class))_ 
_(also [here](https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-protocols-oidc#fetch-the-openid-connect-metadata-document))_

Please be aware that due to the holidays, responses may be delayed.

**Comment by tatarincev** [comment]
Hi, @jsquire  thanks for the quick response.  It turned out that Azured AD calls the `POST /signin-oidc` with a token that has `kid` that does not exist in the keys  taken from the discovery URL for this tenant
`GET https://login.microsoftonline.com/{tenant id}/discovery/v2.0/keys` that the key reason. I suppose that we have the wrong configuration with the Azure AD.

**Comment by jsquire** [comment]
I'm glad that you've figured it out.   I'm going to close this issue, as it seems confirmed that it isn't related to an Azure client library from the SDK.

**Comment by tatarincev** [comment]
Finally, I solved this error by adding `MetadataAddress` to the configuration
```C#
 authBuilder.AddOpenIdConnect("AzureAD", "Azure Active Directory",
                        openIdConnectOptions =>
                        {
                            openIdConnectOptions.ClientId = "my AD application id";
                            openIdConnectOptions.Authority = $"https://login.microsoftonline.com/my AD tenant id";
                            openIdConnectOptions.UseTokenLifetime = true;
                            openIdConnectOptions.RequireHttpsMetadata = false;
                            openIdConnectOptions.SignInScheme = IdentityConstants.ExternalScheme;
                            openIdConnectOptions.SecurityTokenValidator = new  JwtSecurityTokenHandler();
                          --->  openIdConnectOptions.MetadataAddress =  $"https://login.microsoftonline.com/{{TenantId}}/v2.0/.well-known/openid-configuration?appid={{ApplicationId}}"});
```
