### ISSUE TITLE
Consider using Storage SAS URI generation for training samples

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-for-net#17746]
The Storage team has made SAS URI generation much easier.  Instead of using a *SasBuilder, the happy path scenario in the latest GA release of Blobs looks like:
```
var blob = new BlobClient(ConnectionString, ContainerName, BlobName);
await blob.UploadAsync(LocalFilePath);
Uri sas = blob.GenerateSasUri(BlobSasPermissions.Read, DateTimeOffset.UtcNow.AddDays(1));
```
We can look into this for the training samples instead of asking the customer to upload their files and create the SAS token

**Comment by kinelski** [comment]
Discussed offline.

In order to create a storage account on the fly, we'd still need to use ARM libraries, which falls outside the scope of what we wanted to use. We'd also need to ask users to provide credentials for creating or updating their storage accounts, which in the end is not that much better than asking for a SAS token.

Making the requirements for running the sample the same as the requirements for the actual service call (endpoint, credential, and SAS token) seems more intuitive. In other words, it could be misleading to ask for a Storage Account connection string in our samples when the Form Recognizer client itself does not require this piece of information in any of its service calls.
