### ISSUE TITLE
[WebJobs/EventHubs] Allow configuring ProducerClientOptions 

### ISSUE THREAD

**Issue by pakrym** [Azure/azure-sdk-for-net#17742]
We have `EventProcessorOptions` exposed on the `EventHubOptions` but no way to modify the `ProducerClientOptions` used for event publishing. 

`ConnectionOptions` is particularly interesting for setting up proxies/transport.

The unfortunate part of having both exposed is having to change some settings twice.

**Comment by JoshLove-msft** [comment]
Is this exposed in the currently released extensions?

**Comment by pakrym** [comment]
In a way, the current exception allows you to pass a preconfigured client for both producer and processor host. We can't do it in T2 because the processor host requires inheritance.

**Comment by JoshLove-msft** [comment]
So here are the settings that can be configured
- EnableIdempotentPartitions
- PartitionOptions
- ConnectionOptions (also in ProcessorOptions)
- RetryOptions (also in ProcessorOptions)

EnableIdempotentPartitions requires that users set a partition key on outgoing events. To support this we would need a new output parameter.
PartitionOptions is used for advanced scenarios and is dependent on EnableIdempotentPartitions being set to true.

Given this, do we think it is worth exposing in Functions?

**Comment by pakrym** [comment]
And these are things configurable on the processor:

 - ConnectionOptions (also in ProducerOptions)
 - RetryOptions (also in ProducerOptions)
 - DefaultStartingPosition (we expose it via a different setting)
 - Identifier
 - LoadBalancingStrategy
 - LoadBalancingUpdateInterval
 - MaximumWaitTime
 - PartitionOwnershipExpirationInterval
 - PrefetchCount
 - PrefetchSizeInBytes
 - TrackLastEnqueuedEventProperties

**Comment by pakrym** [comment]
@jsquire what's your opinion on this?

**Comment by jsquire** [comment]
> EnableIdempotentPartitions requires that users set a partition key on outgoing events. To support this we would need a new output parameter.

This requires a partition identifier.   Idempotent publishing can only happen directly to a partition.   You can't send to the gateway - so no automatic partition routing or partition keys.

**Comment by jsquire** [comment]
> Given this, do we think it is worth exposing in Functions?

I don't think so.   The feature is limited in its scope - idempotency is only valid in the context of one operation.  When you call `SendAsync` it becomes idempotent across retries.  In the case where that call fails, including if it timed out across all retry attempts, the next send is treated as a new operation.

Given the rigid nature of the responsibilities placed on the caller and the minimal benefit.... I don't think that it offers enough for the Functions context to offset the additional complexity that it brings.

**Comment by jsquire** [comment]
From the processor perspective, my thoughts are:

We probably want:

- _**Identifier**_
This can be helpful for debugging/logging use.  Not essential, but worth including.

- _**PrefetchCount**_, _**PrefetchSizeInBytes**_  
These are two important knobs for tuning.  They can help improve throughput for cases where the eventing patterns are different.  For example, very frequent small events and less frequent large events benefit from very different values.   

  One caution is that this potentially increases resource use on the machine, as the prefetch cache is memory-based.  Not sure how that plays with the functions environment.

- _**TrackLastEnqueuedEventProperties**_  
This offers a slight efficiency when not set, as less information is set by the broker to be transferred.

I'm not sure:

- _**LoadBalancingStrategy**_  
With Functions scaling automatically and, potentially, frequently.... leaving this as `Balanced` will be a big help in reducing event duplication.   You'll see duplication when scaling up or down regardless, but `Greedy` would exacerbate this.   The trade-off is that the initial instantiation will be slower to claim all partitions and scaling will take a bit longer to balance the load.   The more partitions for an Event Hub, the more appealing `Greedy` becomes if you can tolerate the duplication while scaling.

- _**LoadBalancingUpdateInterval**_  
As you'd expect, this will tune load balancing to run more/less frequently, which has an impact on how quickly you'll see the effects of scaling.  The longer the interval, the less you'll see "bouncing" partition ownership, but the longer it will take to detect scaling.   Because of the implicit scaling behavior of Functions, we probably want to tune the value to something that makes sense for the Functions runtime and, maybe, considers the number of partitions.

- _**PartitionOwnershipExpirationInterval**_  
This is the means that processors can detect if one crashed or things were scaled.  The longer the expiration, the more stable ownership is in the face of latency and Storage timeouts.   That gets traded off against potentially taking longer to detect that a processor crashed or that things have been scaled down.   Because of the implicit scaling behavior of Functions, we probably want to tune the value to something that makes sense for the Functions runtime and, maybe, considers the number of partitions.

*We probably don't want:*

- _**MaximumWaitTime**_  
Do we really want the Function firing when there are no events for a partition?   Seems that if we wanted this behavior, using a scheduled Function and manually polling events from the body would be a better pattern.

**Comment by jsquire** [comment]
Across the clients, I think that the `ConnectionOptions` and `RetryOptions` are really the most important point.   The customer feedback that I've seen has been primarily focused around tuning timeout values and configuring the transport to use WebSockets or a proxy.

**Comment by pakrym** [comment]
Thank you, Jesse, for the context. After all the discussion, I'm leaning towards what Josh proposed and copying the applicable settings to the EventHubOptions class.

**Comment by JoshLove-msft** [comment]
@jsquire what about DefaultStartingPosition?

**Comment by jsquire** [comment]
> what about DefaultStartingPosition?

You're exposing this as your "initial offset provider" setting.    I think that it would be redundant to introduce a second way of setting that.

**Comment by jsquire** [comment]
> Also for the options you are unsure of. Did the T1 client expose these options?

Not in the same way;  the architecture was very different around the concept of "leasing" for load balancing.   They allowed you to plug in a class instance to control some of the lease data, but most of the logic was not configurable.   (see [ILeaseManager](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/eventhub/Microsoft.Azure.EventHubs.Processor/src/ILeaseManager.cs))
