### ISSUE TITLE
Azure Storage Emulator not working with restoring snapshots when using DevelopmentStorageProxyUri

### ISSUE THREAD

**Issue by olmg-mike** [Azure/azure-sdk-for-net#1778]
I am not sure this is the best place for this issue.

I ran into an issue recently where I was trying to copy a snapshot back to its original blob.  In other words restoring the original blob from a snapshot.  I was using the following connection string:
UseDevelopmentStorage=true;DevelopmentStorageProxyUri=http://local.d.com;
where local.d.com is in my host file pointing to 127.0.0.1.  I did this so I could monitor the requests going through fiddler.  If I try to copy a snapshot blob back to its original it will fail.  If I remove the DevelopmentStorageProxyUri it will work.

I am using the following method:
CloudBlockBlob.StartCopyFromBlob(new Uri(snapshotBlob.SnapshotQualifiedUri.AbsoluteUri)) ;

Emulator version is 4.2
WindowsAzure.Storage nuget package version is 4.3.0

**Comment by EmmaZhu** [comment]
@olmg-mike 
Could share the exact error code? The request should work with proxies.

**Comment by EmmaZhu** [comment]
@olmg-mike 
Could you share the exact error info? The request should work with proxies.

**Comment by mirobers** [comment]
Hi, for questions about the storage emulator and the storage .NET client, please use the azure-storage-net repo.

For your question, the storage emulator isn't able to resolve your hostname when contacting the source of the copy. You can write a simple helper to convert local.d.com to 127.0.0.1 in the source URL; you will still see the requests your code is making through fiddler and the emulator will be able to communicate (with itself) when processing the copy request.

Closing this issue because it's old and in the wrong repo, but please feel free to open new issues in the azure-storage-net repo.
