### ISSUE TITLE
[BUG] Blob Storage: blobBaseClient.DownloadToAsync is always returning partial content

### ISSUE THREAD

**Issue by pranavq212** [Azure/azure-sdk-for-net#17945]
**Describe the bug**
blobBaseClient.DownloadToAsync is always returning partial content & HTTP 206 and destination stream is empty even when blob has data

**Expected behavior**
blobBaseClient.DownloadToAsync should return data in destination stream with HTTP 200
More details & code here
https://stackoverflow.com/questions/65700497/getting-fullcontent-from-blobbaseclient-downloadtoasync

**Actual behavior (include Exception or Stack Trace)**
What is the actual behavior?

**To Reproduce**
Steps to reproduce the behavior (include a code snippet, screenshot, or any additional information that might help us reproduce the issue)

```
string messageJson = string.Empty;
            try
            {
                var blobBaseClient = new BlobBaseClient(_connectionString, _containerName, blobName);
                Stream stream = new MemoryStream();
                CancellationToken cancelToken = new CancellationToken();
                StorageTransferOptions storageTransferOptions = new StorageTransferOptions
                {
                    //bytes * 1000000 = MB
                    InitialTransferSize = blobInitialChunkSize.Value * 1000000,
                    MaximumConcurrency = blobChunkUploadMaxThreadCount.Value,
                    MaximumTransferSize = long.MaxValue
                };

                BlobRequestConditions blobRequestConditions = new BlobRequestConditions();
                Response response = await blobBaseClient.DownloadToAsync(stream, blobRequestConditions, storageTransferOptions, cancelToken);
                if(response.Status == Convert.ToInt32(HttpStatusCode.OK)
                {
                    using (StreamReader streamReader = new StreamReader(stream))
                    {
                        messageJson = streamReader.ReadToEnd();
                    }
                }
                else
                {
                    _logger.LogInformation("response.Headers.ContentType : " + response.Headers.ContentType + DateTime.Now.ToString());
                _logger.LogInformation("response.Headers.ContentLength : " + response.Headers.ContentLength + DateTime.Now.ToString());
                _logger.LogInformation("response.Headers.ETag : " + response.Headers.ETag + DateTime.Now.ToString());
                _logger.LogInformation("response.Headers.RequestId : " + response.Headers.RequestId + DateTime.Now.ToString());
                _logger.LogInformation("response.Status : " + response.Status + DateTime.Now.ToString());
                _logger.LogInformation("response.ReasonPhrase : " + response.ReasonPhrase + DateTime.Now.ToString());
                _logger.LogInformation("stream : " + stream + DateTime.Now.ToString());
        }
        catch (Exception ex)
        {
            _logger.LogInformation(ex.Message + " " + DateTime.Now.ToString());
            _logger.LogInformation(ex.StackTrace + " " + DateTime.Now.ToString());
            _logger.LogInformation(ex.Source + " " + DateTime.Now.ToString());
            _logger.LogInformation(ex.InnerException + " " + DateTime.Now.ToString());
            throw;
        }
        return messageJson;
```

this is always going to else(not exception). Tried retries, thread sleep & without StorageTransferOptions too
Tried for all blob sizes from 1 kb, 3MB, 300 MB, 500 MB
Also tried combinations of  MaximumConcurrency from 2 to 100 but always same.

Sample Values from else log:
```
response.Headers.ContentType : application / octet - stream
response.Headers.ContentLength : 189778220
response.Headers.ETag : 0x8D860678531E07B
response.Status : 206
response.ReasonPhrase : Partial Content
stream: System.IO.MemoryStream
messageJson: 
```

**Environment:**
Tried on 
-  Azure.Storage.Blobs 12.6.0  
-  Azure.Storage.Blobs 12.7.0
-  Azure.Storage.Blobs 12.8.0
 
 - Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects): tried to run this code inside Azure function on :
  i) Consumption Plan,
 ii) Premium Function P1v1 & P2V2
iii) App Service Plan S2

 - IDE and version : Visual Studio Professional 2019 16.7.2

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.

**Comment by amnguye** [comment]
The reason why you get a Partial Content Code 206 is due to the way we are attempting to download the blob. The first request we send to the service to download the blob, we send it with the largest range we can. When we get the result back, it will provide us back the content length, and if we were not able to download the entire blob in one shot, then we continue to download the blob in smaller segments (this is all in attempts for the best download speed possible).

For short, the 206 code is expected because we send the request with the range. With that if the blob fits in the first request sent then the entire blob is downloaded in one request (so it's actually not part of the blob, it's the entire blob unless it's a very large blob).

The big issue here is that the stream you have is getting returned empty even though your blob does have content. I wasn't able to reproduce the issue you're running into. Taking a look at your snippet, it looks like you only read the stream if you get the status code 200 (OK). The else body printout shows that it is getting a content length header, but it's not showing the content of the stream because you're attempting to print out the stream. Could you change the logic to also accept the 206 and see if you get the blob downloaded to the stream there? Or add to the else body, to read the stream with the streamreader?

**Comment by pranavq212** [comment]
@amnguye As you suggested, I added condition for HTTP 200 or  HTTP 206 too, it is working now.
