### ISSUE TITLE
[BUG] [App Configuration] 401 when retry on request

### ISSUE THREAD

**Issue by x9xu** [Azure/azure-sdk-for-net#18093]
**Describe the bug**
Our Runner hit 401 when retrying the request (for any retry scenario)

For our Runner test, runner will replace the uri host with the ip address and add a host header with configuration store endpoint before it sends the request to backend service, eg.

request final look will be:

request uri: {https://20.49.127.64/kv/TestKey-DataOperationsByHMAC?api-version=1.0}
request host header: {Host:minint-appe4b4-funcprodwus-2021-01-20--22-18-23-69.azconfig.io}

But if the first request fails, the second request for retry will be wrong, because sdk gets the host for signing from request uri (https://github.com/Azure/azure-sdk-for-net/blob/2d029bc79fdbbe601f4b8ff32b322d58d52a9a02/sdk/appconfiguration/Azure.Data.AppConfiguration/src/AuthenticationPolicy.cs#L83) which will be the resolved ip address and is not expected by backend service. This could cause the second request fail with 401 response.

**Expected behavior**
sdk should check host header instead of always getting the host from request uri

https://github.com/Azure/azure-sdk-for-net/blob/2d029bc79fdbbe601f4b8ff32b322d58d52a9a02/sdk/appconfiguration/Azure.Data.AppConfiguration/src/AuthenticationPolicy.cs#L83

**To Reproduce**
Steps to reproduce the behavior (include a code snippet, screenshot, or any additional information that might help us reproduce the issue)

1. add http pipeline policy with retry policy of perretry for replacing the request uri host with resolved ip, and add a host header with configuration store endpoint.
2. make a fake response with status code 500 to enforce sdk retry on the request
3. for retry request, the request uri host is resolved ip and it includes a host header, and the response should be 401

**Environment:**
 - Name and version of the Library package used: Azure.Data.AppConfiguration v1.0.2
 - IDE and version : vs 2019

**Comment by jsquire** [comment]
@ShivangiReja:  Would you please take a look and determine if this is still an issue?

**Comment by ShivangiReja** [comment]
Getting the host from the request uri haven't changed [here](https://github.com/Azure/azure-sdk-for-net/blob/2d029bc79fdbbe601f4b8ff32b322d58d52a9a02/sdk/appconfiguration/Azure.Data.AppConfiguration/src/AuthenticationPolicy.cs#L83) since this issue got created. So it seems like this issue still exists.

@x9xu do you mind providing a sample to reproduce this issue? Thanks!

**Comment by ShivangiReja** [comment]
Getting the host from the request uri hasn't changed [here](https://github.com/Azure/azure-sdk-for-net/blob/2d029bc79fdbbe601f4b8ff32b322d58d52a9a02/sdk/appconfiguration/Azure.Data.AppConfiguration/src/AuthenticationPolicy.cs#L83) since this issue got created. So it seems like this issue still exists.

@x9xu do you mind providing a sample to reproduce this issue? Thanks!
