### ISSUE TITLE
[FEATURE REQ] Allow us to set restrictions on blob size when SAS tokens are created

### ISSUE THREAD

**Issue by petro2050** [Azure/azure-sdk-for-net#18158]
Please allow us to set restrictions on blob size at the time a SAS is generated. As of now, anyone who has a token can upload files of any size and we have to do server-side validation on our own to decide if the files are too big. This requires unnecessary chatter that could be eliminated. While I understand that ingress is free, we still end up paying for storage as long as the blob is present. Also, server-side validation requires EventGrid communication as well as a running VM which are not free either.

Please note that checking file size on the client side is not enough.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.

**Comment by amnguye** [comment]
This seems like a huge feature ask that is non-trivial on the storage service that is not possible solely on the Storage SDK or client side. So I would have to close this issue due to the complexity and that the Storage SDK would be unable to support such a feature.

The only limits we have is limiting which users can have certain permissions or even have permissions to the blob/container/account in question. https://docs.microsoft.com/en-us/rest/api/storageservices/create-user-delegation-sas#specify-a-signed-object-id-for-a-security-principal-preview
