### ISSUE TITLE
[QUESTION] [Servicebus|Azure.Messaging.ServiceBus] Sender cannot be created with empty or null entityName?

### ISSUE THREAD

**Issue by jorjbotezat** [Azure/azure-sdk-for-net#18221]
If the entity name is specified in the connection string and you pass null or empty to ValidateEntityName, that method will throw the ArgumentException. In the method is written that you should specify the entityName in only one place.

**Comment by jsquire** [comment]
Hi @jorjbotezat.   Thank you for your feedback and we regret that you're experiencing difficulties.  The behavior that you're describing is by design;  when creating a sender, you must specify the entity name, regardless of whether it exists in the connection string or not.   _(see remarks in the [docs](https://docs.microsoft.com/dotnet/api/azure.messaging.servicebus.servicebusclient.-ctor?view=azure-dotnet#Azure_Messaging_ServiceBus_ServiceBusClient__ctor_System_String_))_.

As I'm unfamiliar with the rational, I'll defer to @JoshLove-msft for additional insight.

**Comment by JoshLove-msft** [comment]
Thanks for the feedback @jorjbotezat. As @jsquire mentioned, this is indeed by design. The rationale behind this is that we wanted to optimize the API surface and behavior for the common scenario where the connection string was scoped to the namespace rather than a specific entity. We have exposed the [ServiceBusConnectionStringProperties](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/servicebus/Azure.Messaging.ServiceBus/src/Primitives/ServiceBusConnectionStringProperties.cs) type that can be used to extract the EntityPath from the connection string:
```cs
ServiceBusConnectionStringProperties parsed = ServiceBusConnectionStringProperties.Parse(connectionString);
ServiceBusSender sender = client.CreateSender(parsed.EntityPath);
```

**Comment by jorjbotezat** [comment]
Thanks for answering, but looking at the code, I think you should change the comment. This is the reason why I opened this issue.

`// The entity name may only be specified in one of the possible forms, either as part of the
 // connection string or as a stand-alone parameter, but not both.  If specified in both to the same
 // value, then do not consider this a failure.`
