### ISSUE TITLE
Search SDK: Why does Microsoft Azure Search Library 1.1.0 not work with Client Runtime for Microsoft Azure 3.0.2

### ISSUE THREAD

**Issue by alindgren** [Azure/azure-sdk-for-net#1822]
Client Runtime for Microsoft Azure 3.0.2  was released 2016-02-03, before Microsoft Azure Search Library 1.1.0 which was released on 2016-02-09 but the dependencies for Microsoft.Rest.ClientRuntime.Azure are >= 2.5.2 && < 3.0.0.

**Comment by brjohnstmsft** [comment]
The short answer is, because the ClientRuntime library has some breaking changes in 3.x. In the next few months we'll be releasing a new preview version of the Azure Search .NET SDK that will target the 3.x ClientRuntime.

The long answer is in this issue: https://github.com/Azure/autorest/issues/662

Are you having trouble with a conflict? Which other library are you using with Microsoft.Azure.Search that has a dependency on ClientRuntime 3.x?

**Comment by alindgren** [comment]
That's not quite the conflict I'm having. I was just trying to trace the dependencies to resolve a problem in which my Umbraco CMS 7.3.8 site was getting upgraded to to 7.4.1 (which I'm not ready for) when I installed Microsoft.Azure.Search 1.1.0. I think this is because Umbraco 7.3.8 does not support newer version of Newtonsoft.Json (Umbraco 7.4.1 however does).

Somehow (I think by installing oldest version of ClientRuntime allowed for Microsoft.Azure.Search but I'm not certain because I tried so many times), I managed to get this installed but now I'm running into this error when I try to build:

`1>c:\Projects\xxx\Source\packages\Microsoft.Azure.Search.1.1.0\lib\net45\Microsoft.Azure.Search.dll : error CS1705: Assembly 'Microsoft.Azure.Search, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' uses 'Newtonsoft.Json, Version=7.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' which has a higher version than referenced assembly 'Newtonsoft.Json, Version=6.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'`

I'm a little surprised by that message because I have installed [Microsoft.Rest.ClientRuntime 1.8.2](https://www.nuget.org/packages/Microsoft.Rest.ClientRuntime/1.8.2) which should have a dependency on Newtonsoft.Json (>= 6.0.8) for .NET 4.5.

This is what my package list looks like for the relevant packages:

```
  <package id="Microsoft.Azure.Search" version="1.1.0" targetFramework="net451" />
  <package id="Microsoft.Rest.ClientRuntime" version="1.8.2" targetFramework="net451" />
  <package id="Microsoft.Rest.ClientRuntime.Azure" version="2.5.4" targetFramework="net451" />
  <package id="Newtonsoft.Json" version="6.0.8" targetFramework="net451" />
```

**Comment by brjohnstmsft** [comment]
Hmm, it looks like maybe we are missing an explicit dependency on NewtonSoft.Json in the Microsoft.Azure.Search NuGet package. It depends on version 7. Fixing that will probably not fix your conflict by itself, but JSON.NET 6 and 7 should be compatible enough that an assembly binding redirect should fix it. I'm guessing NuGet might not have created the right binding redirect for you because of this missing dependency.

I'll fix the nuspec in the next week or two. In the meantime, check your binding redirects.

**Comment by brjohnstmsft** [comment]
After looking at other Azure client libraries and discussing with the owners of ClientRuntime, it looks like the Search library follows existing practice. A binding redirect should solve the issue. If it doesn't, please leave a comment and I'll re-open this issue.

**Comment by alindgren** [comment]
I couldn't get the binding redirect to work, but I ended up upgrading Umbraco to a version that works with a new enough version of NewtonSoft.Json. 

Thanks!
