### ISSUE TITLE
update Microsoft.Azure.ServiceBus dependency on Microsoft.IdentityModel.Tokens to version 6.5

### ISSUE THREAD

**Issue by qub1n** [Azure/azure-sdk-for-net#18279]
**Describe the bug**
Microsoft.Azure.ServiceBus depends on Microsoft.IdentityModel.Tokens 5.5

This is a reallly problem for us, because other dependencies we have already depends on Microsoft.IdentityModel.Tokens 6.5

**Expected behavior**
update dependency to Microsoft.IdentityModel.Tokens 6.5

**Environment:**
 - .Net Core

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.

**Comment by axisc** [comment]
We will review this request internally and provide an ETA.

**Comment by DorothySun216** [comment]
We are working on this dependency update on the server side first. After we thoroughly tested it on the server side, we will roll out the fix for client side. We might not tailor to your specific version need since we need to think from the perspective of the SDK development. Is  Microsoft.IdentityModel.Tokens 6.5 the specific version you need or as long as it is greater than this version? As far as my knowledge,  Microsoft.IdentityModel.Tokens is back-compat >= 6.x.x, so even if we upgrade to the latest stable version, you should be able to consume it.

**Comment by qub1n** [comment]
Latest stable is great as well. Thanks

**Comment by vDiBo** [comment]
Hi @shankarsama,
Imho updating Microsoft.Azure.ServiceBus dependencies gets more urgent, since it has a dependency on System.Text.RegularExpressions.4.3.0 which has this known vulnerability:
https://msrc.microsoft.com/update-guide/en-US/vulnerability/CVE-2019-0820

Microsoft.Azure.ServiceBus/5.1.3 » Microsoft.Azure.Services.AppAuthentication/1.0.3 » Microsoft.IdentityModel.Clients.ActiveDirectory/3.14.2 » NETStandard.Library/1.6.1
» System.Text.RegularExpressions/4.3.0

**Comment by SaurabhSharma-MSFT** [comment]
@qub1n Following up again to know if your issue is resolved.

**Comment by yvgopal** [comment]
Current SDK version 5.2.0 depends on Microsoft.IdentityModel.Tokens (>= 6.14.1). Closing it.
