### ISSUE TITLE
[FEATURE REQ] Add import feature in the Azure.Data.AppConfiguration .NET SDK

### ISSUE THREAD

**Issue by ahocquet** [Azure/azure-sdk-for-net#18295]
**Library or service name.**
Azure.Data.AppConfiguration
 
**Is your feature request related to a problem? Please describe.**
I would like to get the feature `import` implemented in the .NET SDK. At the moment, I need to fall back to the `az appconfig kv import`  cli in order to batch import settings. I would like to do it with the .NET SDK.

I know I can create or update configuration setting with the .NET SDK, but it has to be a call per setting. I would like to batch import all my settings as with the az cli client.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by pakrym** [comment]
Hey, thank you for the feature request. To clarify a bit. Are you interested in the ability to add multiple settings in a single call or to import settings in bulk from some particular data source?

**Comment by ahocquet** [comment]
Hi, thanks for coming back to me so fast!

I'm interested in the ability to add/set multiple settings in a single call, from a data structure such as  `List<ConfigurationSetting>`

My current app is a console app that reads and parse a json file and then updates all the settings, therefore making multiple calls.

**Comment by pakrym** [comment]
@ahocquet I'm afraid there is no service endpoint that takes a list of settings. The az cli does a manual enumeration when uploading values via import: https://github.com/Azure/azure-cli/blob/9e674a14d0445afb91cd317aff0134fdc36615c5/src/azure-cli/azure/cli/command_modules/appconfig/_kv_helpers.py#L348

We try to avoid adding aggregate methods like this to .NET Azure SDK clients because often there is no good way to handle failures/retries in a consistent and user-friendly manner.

**Comment by ahocquet** [comment]
I thought that the az cli used a non documented endpoint for bulk import, but couldn't find the source code to verify that. 

It makes sense to not expose this feature if there's no such endpoint in the REST API to handle bulk import. You can close the issue. 

Thanks!
