### ISSUE TITLE
Does it pop the message from queue

### ISSUE THREAD

**Issue by thejman1989** [Azure/azure-sdk-for-net#18387]
[Enter feedback here]

Maybe good to add if this method deletes the message from the queue or not. 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b3346aae-d499-7525-b9f1-7e6d0d4bf1d6
* Version Independent ID: bbc68357-83e0-beb0-01df-3fca3b886203
* Content: [CloudQueue.GetMessageAsync Method (Microsoft.Azure.Storage.Queue) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.storage.queue.cloudqueue.getmessageasync?view=azure-dotnet-legacy)
* Content Source: [xml/Microsoft.Azure.Storage.Queue/CloudQueue.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.Storage.Queue/CloudQueue.xml)
* Service: **storage**
* GitHub Login: @CamSoper
* Microsoft Alias: **casoper**

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.

**Comment by amnguye** [comment]
Hi. This method does not pop off the message. I don't think adding this detail is necessary, it clearly states that the method gets a single message from the queue. We cannot including every single detail of what every single API does not do. We can clear up any misunderstandings if there's something in the API name or documentation that would state otherwise or be confusing.
