### ISSUE TITLE
[MetricsAdvisor] Add tests for extra Get call in the Create methods

### ISSUE THREAD

**Issue by kinelski** [Azure/azure-sdk-for-net#18589]
We need to test the behavior when the first call (create) succeeds and the last call (get) fails. We can probably do it by mocking our client.

Methods to test:
- CreateDataFeed
- CreateDetectionConfiguration
- CreateAlertConfiguration
- CreateHook
- AddFeedback

Note: maybe only applicable to `CreateDataFeed` depending on the outcome of https://github.com/Azure/azure-sdk-for-net/issues/18480.

**Comment by ibocon** [comment]
Hi, @kinelski. I am interested in this issue.

I see this issue is started from [your comment](https://github.com/Azure/azure-sdk-for-net/pull/18491#discussion_r572587818) in PR #18491. And #18480 does not avoid using extra `Get` method. So Methods to test are

* CreateDataFeed
* CreateDetectionConfiguration
* CreateAlertConfiguration
* CreateHook
* AddFeedback

---
I am planning to create a mock of `MetricsAdvisorAdministrationClient` like below as you suggest in description,

```cs
public class MockMetricsAdvisorAdministrationClient : MetricsAdvisorAdministrationClient
{
        public virtual async Task<Response<AnomalyAlertConfiguration>> GetAlertConfiguration(string alertConfigurationId, CancellationToken cancellationToken = default)
        {
            // Throw exception when CreateAlertConfiguration call GetAlertConfiguration inside to test.
            throw;
        }
        
        // Other Get method mocks...
}
```
Where should I put this class in project **Azure.AI.MetricsAdvisor.Tests**?

---

LiveTests create `MetricsAdvisorAdministrationClient` instance form `MetricsAdvisorLiveTestBase.GetMetricsAdvisorAdministrationClient` method like below,

https://github.com/Azure/azure-sdk-for-net/blob/4283d09a0364c306251a68a2281cfe6548b6a71e/sdk/metricsadvisor/Azure.AI.MetricsAdvisor/tests/MetricsAdvisorAdministrationClient/AnomalyAlertConfigurationLiveTests.cs#L734

So, should I create new `MetricsAdvisorLiveTestBase`, which use `MockMetricsAdvisorAdministrationClient` to create a live tests?

```cs
public class MockMetricsAdvisorLiveTestBase : MetricsAdvisorLiveTestBase
{
            public override MetricsAdvisorAdministrationClient GetMetricsAdvisorAdministrationClient(bool useTokenCredential = false)
        {
            return new MockMetricsAdvisorAdministrationClient();
        }
}
```

Or, just create a method like in `AnomalyAlertConfigurationTests`?

https://github.com/Azure/azure-sdk-for-net/blob/4283d09a0364c306251a68a2281cfe6548b6a71e/sdk/metricsadvisor/Azure.AI.MetricsAdvisor/tests/MetricsAdvisorAdministrationClient/AnomalyAlertConfigurationTests.cs#L165-L171

```cs
private MetricsAdvisorAdministrationClient GetMetricsAdvisorAdministrationClient()
{
    return new MockMetricsAdvisorAdministrationClient();
}
```
