### ISSUE TITLE
AzureApplicationSettings has "internal" access modifier instead of "private" or "public"

### ISSUE THREAD

**Issue by BrianMcBrayer** [Azure/azure-sdk-for-net#1866]
I was wondering if someone on the team could explain the reasoning behind the `internal` access modifier on `AzureApplicationSettings`. Is this better than making it public or even private, since `CloudConfigurationManager` is the only class that uses it?

**Comment by markcowl** [comment]
@BrianMcBrayer It's not public for encapsulation purposes.  I'm guessing that it was made internal rather than private to lower the complexity of CloudConfigurationManager.  Making it an internal class opens up the possibility of targeting unit tests at the class directly, but this has not been done to date..
