### ISSUE TITLE
[QUERY] Use SAS Token with EventHubProducerClient

### ISSUE THREAD

**Issue by toutougabi** [Azure/azure-sdk-for-net#18726]
**Query/Question**
I am trying to use a SAS Token with the EvenHubProducerClient but i cannot find any documentation on how to do it. The only documentation i could find only says coming soon : https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/eventhub/Azure.Messaging.EventHubs/samples/Sample06_IdentityAndSharedAccessCredentials.md

**Environment:**
Azure.Messaging.EventHubs latests version
.net core 3.1
 - IDE and version : Visual Studio 16.8.2

**Comment by jsquire** [comment]
Hi @toutougabi.  Thank you for reaching out and we regret that you're experiencing difficulties.   At present, the only way to use a SAS credential with any of the Event Hubs clients is through the connection string.   That would be in the format of:

`Endpoint=sb://<< ENDPOINT ADDRESS>>;SharedAccessSignature=<< SAS TOKEN>>` and may also optionally contain the `EntityPath=<< EVENT HUB NAME>>`.

We're working on some additional features in this area to allow a SAS token to be provided as a credential type so that it can be refreshed without having to recreate your client, but I don't have a date that I can share for that functionality at this point in time.
