### ISSUE TITLE
DataLakeFileClient.Upload does not upload data

### ISSUE THREAD

**Issue by Kyle8329** [Azure/azure-sdk-for-net#18951]
**Describe the bug**
Data is not uploaded when Upload is called with a non seekable, non length supporting stream.  Data is not uploaded when UploadAsync is called under the same conditions with a maximum concurrency of 1.

**Expected behavior**
Data is uploaded

**Actual behavior (include Exception or Stack Trace)**
Data is not uploaded.

**To Reproduce**
See attached repro.
[Repro.zip](https://github.com/Azure/azure-sdk-for-net/files/6031261/Repro.zip)

It looks like the issue is in PartitionedUploader.UploadInSequenceInternal.  Inside the foreach loops StagePartitionAndDisposeInternal is called.  This will dispose the PooledMemoryStream so that when partitions.Add((block.AbsolutePosition, block.Length)); is run the position and block length are both 0.  That leads to an incorrect length + offset when flushing.

**Environment:**
Tested with Azure.Storage.Files.DataLake Version="12.6.0"

**Comment by Mohit-Chakraborty** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.

**Comment by amnguye** [comment]
@seanmcc-msft What do you think about this bug? In order to upload we need to be able to get the `Stream.Length` and `Stream.Position` in order to determine what can be uploaded from the stream.

`contentLength: (content?.Length - content?.Position) ?? 0`

**Comment by seanmcc-msft** [comment]
@Kyle8329, Upload does not support non-length streams.  This API is calling [Put Block](https://docs.microsoft.com/en-us/rest/api/storageservices/put-block) and [Put Block List](https://docs.microsoft.com/en-us/rest/api/storageservices/put-block-list), and we have to know the stream length to correctly partition the blob into blocks.

**Comment by Kyle8329** [comment]
@seanmcc-msft  Did you read my comment in the Reproduce section?  It shouldn't matter if the consumer of the library passes in a non seakable non length supporting stream.  The issue is that appears to trigger a code path with a bug in the sdk.  UploadInSequenceInternal is going to call GetPartitionsAsync in the foreach loop.  The user stream is going to be abstracted behind a SlicedStream (implemented by a PooledMemoryStream in my testing).

**Comment by Kyle8329** [comment]
Repro above may not have been very clear.  Here's an updated repro showing the behavior I'm seeing more clearly.  [Repro2.zip](https://github.com/Azure/azure-sdk-for-net/files/6051948/Repro2.zip)

**Comment by Kyle8329** [comment]
Bumping this thread

**Comment by amnguye** [comment]
Just to be clear are you saying that Upload should support non-seekable and non-length streams? Or are you saying there's a scenario where the SlicedStream gets disposed too early which causes this condition to happen?

If it's the first question, I would just reiterate what was said earlier that it would be difficult to create these blocks without the length and position of the stream. If it's the second then is there a different repro you have? because looks like the repro code you have has the stream always non-seekable and non length.

**Comment by Kyle8329** [comment]
The second:  In the SDK it looks like UploadInSequenceInternal is disposing the SlicedStream (PooledMemoryStream) too soon.  The only significance of the non non-seekable, non-length streams is that they just happen to take this code path when passed to Upload.  A stream that supports seeking and length goes through a different method.

If you haven't run repro (and I should have put this at the beginning for clarity):  Run with line 25 uncommented (Upload) and line 28 (UploadAsync) commented out.  The test stream is 9 bytes.  You should see the uploaded file is 0 bytes.

Reverse that and run the repro with UploadAsync instead of Upload.  You should see that the uploaded file is 9 bytes as expected.

The difference appears to be that Upload in this case (non seekable, non length) uses UploadInSequenceInternal (where the stream gets disposed too early) while UploadAsync takes a different code path that correctly uploads the stream.

**Comment by amnguye** [comment]
Not sure how to move forward with this issue because if the stream later becomes unseekable and/or non length down the line, the upload method cannot perform like that.

>A stream that supports seeking and length goes through a different method.
I'm not sure what this means. I don't think the upload method can make assumptions on what other APis to retrieve the length and seekability.

When I went to repro, it does show me the results you were mentioning, however we can't justify supporting non-length and non-seekable streams still.
