### ISSUE TITLE
RequestActivityPolicy does not update Traceparent on retries

### ISSUE THREAD

**Issue by JoshLove-msft** [Azure/azure-sdk-for-net#18992]
The Traceparent request header doesn't change - https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/core/Azure.Core/src/Pipeline/Internal/RequestActivityPolicy.cs#L117 on retries.

Keep in mind that we shouldn't update to _always_ update this header, but rather only update the header if it was added by the policy, i.e. we still need logic to avoid overwriting a Traceparent that was already set before getting to this policy.

**Comment by JoshLove-msft** [comment]
@lmolkova I expect that it would be rare for activity context to change between retries, but do you think we should fix this?

**Comment by lmolkova** [comment]
Great catch @JoshLove-msft!

The propagated context must be the same as client span. I.e. each try is a new span and each time we should change the context regardless if it was present or not. 

This way people can request support using the traceparent they set. I know we use x-ms-request-id for it on most services, but  Azure is slowly converging to W3C.

There is no legit scenario for user or SDK to set traceparent and we should ignore it. If they want a different tracing story, they can pass their own policy. Still, since we call Azure services, there is no reason to implement custom tracing to them.

I did a quick look to see if any SDK does something interesting with traceparent:
- EH/SB/EG/CloudEvents propagate it in the payload
- DigitalTwin has it in the models

So I assume it's pretty safe to always update it no matter what. 

Also, we added a new attribute to otel spec ([`http.resend_count`](https://github.com/open-telemetry/opentelemetry-specification/blob/682260d258f5c46d9a51c48b71ac59b4d36e40cf/specification/trace/semantic_conventions/http.md#http-request-retries-and-redirects))  to stamp the number of retries/redirects. It'd be nice to add it at some point.  It shouldn't be set on the first try, second try span gets  `http.resend_count=1`,  etc. We'll need to support int attributes for this.

**Comment by JoshLove-msft** [comment]
> Also, we added a new attribute to otel spec ([`http.resend_count`](https://github.com/open-telemetry/opentelemetry-specification/blob/682260d258f5c46d9a51c48b71ac59b4d36e40cf/specification/trace/semantic_conventions/http.md#http-request-retries-and-redirects)) to stamp the number of retries/redirects. It'd be nice to add it at some point. It shouldn't be set on the first try, second try span gets `http.resend_count=1`, etc. We'll need to support int attributes for this.

Oh interesting.. this lines up with our work to add the RetryNumber in the HttpMessage.
