### ISSUE TITLE
[BUG]  Data Protection Extensions:  Potential application hang

### ISSUE THREAD

**Issue by michaelpaulus** [Azure/azure-sdk-for-net#19482]
### Describe the bug
Our site is hanging, sometimes unrecoverable during a refresh of the data protection provider.  I was able to get a memory dump while it was occurring one time.   I have been trying to load test locally and duplicate the issue without any luck.  It seems that most of the times this happens our response time goes way up

![response_time](https://user-images.githubusercontent.com/11060495/110376933-cc03a880-8021-11eb-839c-74cd685e91f2.PNG)

our 500 count

![server_errors](https://user-images.githubusercontent.com/11060495/110376985-d756d400-8021-11eb-93ce-5bf73828129b.PNG)

and thread count

![thread_count](https://user-images.githubusercontent.com/11060495/110377016-e2116900-8021-11eb-936e-d3d347ddd07f.PNG)

Here is a picture of the stack trace from the memory dump:

![refresh_thread](https://user-images.githubusercontent.com/11060495/110377071-f2c1df00-8021-11eb-8849-bf001f887123.PNG)

and one of the threads waiting for that one:

![wait_thread](https://user-images.githubusercontent.com/11060495/110377089-fa818380-8021-11eb-908f-c2a1eea1c862.PNG)

### To Reproduce
Sorry, but I've not been able to repo this in a testing environment

### Further technical details
.NET SDK (reflecting any global.json):
 Version:   5.0.103
 Commit:    72dec52dbd

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x86
 Base Path:   D:\Program Files (x86)\dotnet\sdk\5.0.103\

Host (useful for support):
  Version: 5.0.3
  Commit:  c636bbdc8a

.NET SDKs installed:
  1.1.14 [D:\Program Files (x86)\dotnet\sdk]
  2.1.518 [D:\Program Files (x86)\dotnet\sdk]
  2.1.521 [D:\Program Files (x86)\dotnet\sdk]
  2.2.109 [D:\Program Files (x86)\dotnet\sdk]
  3.1.111 [D:\Program Files (x86)\dotnet\sdk]
  3.1.112 [D:\Program Files (x86)\dotnet\sdk]
  5.0.103 [D:\Program Files (x86)\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.25 [D:\Program Files (x86)\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.14 [D:\Program Files (x86)\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.25 [D:\Program Files (x86)\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.14 [D:\Program Files (x86)\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.3 [D:\Program Files (x86)\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.8 [D:\Program Files (x86)\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.12 [D:\Program Files (x86)\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.3 [D:\Program Files (x86)\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 1.0.16 [D:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.13 [D:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.9 [D:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.25 [D:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.14 [D:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.3 [D:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.12 [D:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.3 [D:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]

**Comment by jsquire** [comment]
Hi @michaelpaulus.  Thank you for reaching out and we regret that you're experiencing difficulties.  Can you help me understand Azure SDK you're inquiring about so that I can make sure to involve the right folks to assist?   

From the current context, I can see only that you're using ASP.NET Core.   If you're seeking help with ASP.NET Core itself and not one of the Azure SDKs,  you're best path forward would be to open an issue in the [dotnet/aspnetcore](https://github.com/dotnet/aspnetcore/issues) repository.

**Comment by jsquire** [comment]
Ah,  on closer inspection of the stack trace and after seeing your issue in the ASP.NET Core repository, I understand the context.    Tagging and routing to the team member best able to assist.

**Comment by michaelpaulus** [comment]
My apologies, it was originally written for the aspnetcore team (https://github.com/dotnet/aspnetcore/issues/30752) but they had me post it over here, although I think it is probably more related to the internals of data protection vs your implementation specifically:

Azure.Extensions.AspNetCore.DataProtection.Blobs

**Comment by pakrym** [comment]
Is there a way you can share the dump with me? pakrym @microsoft.com

Otherwise, I'm suspicious that this is a thread pool starvation considering the thread count spike.

The DataProtection abstraction is synchronous with a lock on the main code path. When the refresh happens under load incoming requests start being blocked on that lock and async completions for blob client calls are not able to get executed (because thread pool threads are being taken over by blocked requests threads).

**Comment by michaelpaulus** [comment]
I emailed it to you, thanks!

**Comment by pakrym** [comment]
I'm sorry it took me so long to get to this. The deadlock is caused by the flood of requests that are all getting blocked behind data-protection infrastructure (>1200 queued work items with ~40 thread pool threads). 
![image](https://user-images.githubusercontent.com/1697911/135688177-bf84960e-2f06-4227-b135-4eb9fadfa19c.png)


It's a known issue in aspnetcore https://github.com/dotnet/aspnetcore/issues/30752
