### ISSUE TITLE
[QUERY] Service Bus:  The lock supplied is invalid when attempting to dead letter a message

### ISSUE THREAD

**Issue by rorococo** [Azure/azure-sdk-for-net#19519]
**Query/Question**
I raised this question on Stack Overflow but have had no response. I am trying to send a message to the deadletter queue on a polly retry failure but I get "Lock supplied is invalid" error. I have tried sending the message to deadletter before the retry as a test as well but I get the same error.

Not sure what is going wrong.
SO Question: https://stackoverflow.com/questions/66606948/azure-service-bus-the-lock-supplied-is-invalid-error-on-deadlettering

**Environment:**
 - Azure.Messaging.ServiceBus 7.1.0
 - Hosting platform or OS and .NET runtime version: Windows 10.0.19042, .NET 5.0.103
 - IDE and version : Visual Studio 16.8.2

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.

**Comment by JoshLove-msft** [comment]
Hi @rorococo, can you tell us what the exception was that landed the message in the error handler? In order to dead letter a message you will need the message to still be locked. Otherwise, the message will be abandoned, which means the delivery count will be incremented and it will be available to be received again.

**Comment by JoshLove-msft** [comment]
I looked at your code snippet from the SO post and I think I see the issue. You are attempting to dead letter the message with a separate receiver, not with the args from the processor. This won't work because the receiver will not have a lock for the message that you are getting through the processor. You would need to deadletter it with the processor.

**Comment by rorococo** [comment]
I tried with args and it doesn't work either. How can I deadletter with the processor? I don't see any options for it in the API

**Comment by JoshLove-msft** [comment]
Yes, I meant that you would need to use args with the processor. Can you tell us what the initial exception was that triggered the error handler?
