### ISSUE TITLE
[FEATURE REQ] Enable code coverage filtering for AutoGenerated Code

### ISSUE THREAD

**Issue by paolamvhz** [Azure/azure-sdk-for-net#19567]
**Library or service name.**
Code Coverage
 
**Is your feature request related to a problem? Please describe.**
We are using autorest for some of the code in the sdk services as the code gets generated in this services we would like to have the code coverage filtered in the code coverage tab, we are not able to use the tags [ExcludeFromCodeCoverage] because this has to be added every time we re-generate the code

**Comment by paolamvhz** [comment]
This could be related to the past issue. https://github.com/Azure/azure-sdk-for-net/issues/17066

**Comment by heaths** [comment]
By default we do want code coverage over generated code, but if you want to exclude it you can declare a partial class and add the `[ExcludeFromCodeCoverage]` attribute. All classes generated by autorest.csharp are `partial`, and you can declare your own `partial` class with overrides. In fact, that's the supported way to "tweak" generated types.

Consider the following directory structure:
```
sdk
  <service>
    <package>
      src
        Generated
          <service>RestClient.cs
            Models
              Model.cs <- public partial class Model { ... }
        <service>Client.cs
        Models
          Model.cs <- [ExcludeFromCodeCoverage] public partial class Model {}
```
Currently there's no other way to provide overrides since there's no supported way to merge or provider additional .runsettings files. I did open an [issue](https://github.com/Azure/azure-sdk-for-net/issues/17066#issuecomment-739075082-permalink:~:text=Switch%20from%20.runsettings%20file%20to%20generate%20a%20command%20line) with some ideas, but for now there's not been enough need since workarounds like this exist. In this particular case, on how many classes would this attribute need to apply?

**Comment by heaths** [comment]
The corollary is: why not add coverage for them? If they are public, they should be tested. If they are not public, they shouldn't be included in coverage reports (if they are, that's a separate bug). Note that we are not gating PRs or even releases on coverage results, so nothing is blocking you from adding coverage later. It's currently on the honor system, targeting 70% or better coverage.

**Comment by paolamvhz** [comment]
we do have a structure like the requested but even with that some classes in the Generated folder which is not public are appearing in the code coverage

example 
Class: | Azure.Communication.Identity.Models.CommunicationError
-- | --
FILE : 
C:\NetFork\azure-sdk-for-net\sdk\communication\Azure.Communication.Identity\src\Generated\Models\CommunicationError.cs
C:\NetFork\azure-sdk-for-net\sdk\communication\Azure.Communication.Identity\src\Generated\Models\CommunicationError.Serialization.cs

**Comment by heaths** [comment]
As noted, we don't want to exclude generated code by default; however, to better help prioritize doing something like what I [commented here](https://github.com/Azure/azure-sdk-for-net/issues/17066#issuecomment-739075082), how many classes do you need to hide from coverage? Is the supported workaround of using a partial class with the `[ExcludeFromCodeCoverage]` attribute not feasible? Changing how we execute code coverage to be able to filter out some directories ad-hoc has some cost.

**Comment by jsquire** [comment]
@heaths:  Is there work to be done for this?  Your last comment seems to imply that directory-level filtering is not a feature that we believe should be implemented.   I'd like to close this out if it is not needed for tracking.

**Comment by heaths** [comment]
As the leads, I defer to you and @pallavit. :smile: I personally feel we shouldn't exclude generated code, *especially* as we shift left and most/all of the code is generated.

**Comment by jsquire** [comment]
> I personally feel we shouldn't exclude generated code, _especially_ as we shift left and most/all of the code is generated.

I'm with Heath on this one.  @pallavit:  Any objections?

**Comment by pallavit** [comment]
> I'm with Heath on this one. @pallavit: Any objections?

None at all. We should have code coverage for public surface area, generated or otherwise. 

In one of the comments the issue creator mentioned they are seeing code coverage getting flagged for non public types which if is still present should be fixed.

**Comment by heaths** [comment]
> In one of the comments the issue creator mentioned they are seeing code coverage getting flagged for non public types which if is still present should be fixed.

This I disagree with. It's hard to test every permutation through public types and it's common to test non-public types and members to better test those permutations. As such, getting coverage over non-public types seems vital.

**Comment by jsquire** [comment]
I would assume that types are generated for a specific purpose in support of the service client API.   In theory, testing the public API should exercise those types unless there are service methods intentionally made non-public.   Since that would seem to be an exception case and there's a means to opt-out explicitly - I don't think there's anything to be done here.    

Am I overlooking anything?

**Comment by heaths** [comment]
For internal generated types, perhaps, but internal types in general, no. We often mark types as internal so we can specifically test them, since test assemblies can see internals of their associated production assembly via `InternalsVisibleTo`. This is a common way to make code paths easily testable without exposing them directly to customers.

**Comment by pallavit** [comment]
No concerns on that front. I was not sure if there are any non-public types that are needed say by code generator itself or other internal purposes which may skew are numbers. From the conversation there seems to be none, so I agree on it as well.

**Comment by heaths** [comment]
Thanks. We'll leave as-is then.
