### ISSUE TITLE
[QUERY] ServiceBus AmqpMessageConverter creates unnecessary MemoryStream allocations

### ISSUE THREAD

**Issue by danielmarbach** [Azure/azure-sdk-for-net#19666]
**Query/Question**

`ReadStreamToArraySegment` does currently the following

```csharp
            using var memStream = new MemoryStream(StreamBufferSizeInBytes);
            stream.CopyTo(memStream, StreamBufferSizeInBytes);

            return new ArraySegment<byte>(memStream.ToArray());
```

which causes quite a bit of memory allocations. Would it be worthwile the complexity to change the code to something like (very raw thoughts for the discussion)

```csharp
        private static (ArraySegment<byte>, BufferRent) ReadStreamToArraySegment(Stream stream)
        {
            if (stream == null)
            {
                return new (new ArraySegment<byte>(), null);
            }

            var buffer = ArrayPool<byte>.Shared.Rent(StreamBufferSizeInBytes);
            stream.Write(buffer, 0, StreamBufferSizeInBytes);
            return new (new ArraySegment<byte>(buffer), new BufferRent(buffer));
        }

        public sealed class BufferRent : IDisposable
        {
            private readonly byte[] _buffer;

            public BufferRent(byte[] buffer)
            {
                _buffer = buffer;
            }
            public void Dispose()
            {
                ArrayPool<byte>.Shared.Return(_buffer);
            }
        }
```

and then let the upper layers that call `BatchSBMessagesAsAmqpMessage` deal with returning the buffers rented?

**Environment:**
 - Name and version of the Library package used: [e.g. Azure.Storage.Blobs 12.2.0] 
 - Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects): [e.g. Azure AppService or Windows 10 .NET Framework 4.8]
 - IDE and version : [e.g. Visual Studio 16.3]

**Comment by danielmarbach** [comment]
@JoshLove-msft @jsquire

**Comment by jsquire** [comment]
Hi @danielmarbach.   It's an interesting idea, and we're definitely open to ways to make the send flow more efficient.  Once upon a time, I was thinking about trying shared buffers during publish operations but ended up feeling savings didn't warrant the complexity.  Here's what my thoughts were, feel free to call out any oversights and offer additional perspective.

- In the majority case, we'd end up doing one AMQP conversion to send.  The savings would only come into play when we had retries, and could be helpful for reducing memory pressure with large payload sizes.  With the 1MB limit for messages, I don't know that the payload savings is significant when considered against the typical memory available on a modern system.

-If we were to shift up to the batch and store the serialized AMQP message rather than the message model, we could avoid paying the cost multiple times, but due to some behavior in the AMQP library, we have to do a full conversion for each send attempt at the moment.  This is something that we'd like to revisit, but haven't had been able to figure out in the limited time that we've had to look into it.   Even if we figure out the issue, the AMQP library doesn't allow the same AMQP message to be sent twice, so we would have to clone for retries, so we'd still be stuck with a bunch of allocations - though the payload may could likely be copied without reforming the array segment.  _(#9569 is tracking this for Event Hubs)_.

- Service Bus has an additional consideration there as well.  It does not clone the Message when it is added to at batch.  Callers can continue to manipulate the message until it is sent.  Currently, if they add data, it could result in a send failure.   Adding a cached message translation (be it a shared buffer or AMQP) would potentially be a breaking change as changes made by callers would no longer be recognized - unless we did some non-trivial work to detect any Message changes and flag as dirty to force a new serialization at send.

- We want to ensure that the Message model is simple and does not require disposing; we can't use a shared buffer there.  That prevents us from something like "we could serialize the message bytes and hold them in the Message itself."

- Event Hubs has some additional challenges around state that can't be captured until the moment a publish operation is kicked off when the (still beta) idempotent publishing feature is enabled.   We can ignore this for now; I think it's orthogonal to the core of this discussion.

Please feel free to poke holes and offer alternate perspectives; I feel like this is a valuable discussion for both Service Bus and Event Hubs and would be very interested in figuring out some revisions in approach.

**Comment by danielmarbach** [comment]
How about this nice improvement?

https://github.com/Azure/azure-sdk-for-net/pull/19683

**Comment by danielmarbach** [comment]
I was pondering over this a bit more and concluded the following. At the moment we treat all cases of receiving and peeking the same. So that means it is necessary to copy the AmqMessage content and then dispose the AmqpMessage. I wondered if it would make sense to clearly differentiate the following cases

- Peeking messages
- Manually receiving
- Receiving as part of a processor

When you are peeking you are probably not even really interested in completing or abandoning messages. Therefore copying the body makes sense.

When messages are manually received the control is given into the hands of the users. Theoretically, one could argue a settlement outcome should also be possible on a message and therefore any shared buffer could be released either at complete or at abandon. Yet this might be dangerous because if not done right memory might leak which I think from an SDK standpoint should be avoided. Ergo the payload should be copied.

Which leaves us with the last case which is the processor. When the processor is set to autocomplete it fully owns the scope of the message. When it is set to not auto complete the scope has to be controlled by the users (again potentially dangerous territory). So I guess we could say for processors with autocomplete disposing the amqp message could be moved into the explicit scope owned by the processor and therefore memory copying would no longer be necessary. For cases where auto complete is not set one could argue given the nature of the code being executed as part of an event handler a user would need to go through significant abuse to make sure the service bus message survives that scope and I'm inclined to say even then it would be ok to hold the amqp message until complete or abandon is called. Therefore, I think there would be opportunity to optimize the receive path as part of processors.

**Comment by danielmarbach** [comment]
I quickly spiked another idea. Basically a flag on the receiver and potentially processor options that allows to opt-in for managed bodies. When an opt-in is done the client assumes you are Completing, Abandoning, Deadlettering... the received message. Right now it is quick and dirty implemented without paying much attention to whether it fully works. I'm piggy backing the original AMQP message for simplicity reasons but of course a similar design could be done by still disposing the original message but before doing that copying the original data into a managed buffer that then is returned on complete, abandon...

The PR is really just a discussion starter

https://github.com/Azure/azure-sdk-for-net/pull/19885

What do you think?

**Comment by felipepessoto** [comment]
I was about to open an issue about the same behavior in EventHub SDK. Even sending a static message, I see my application consuming a lot of memory (100MB/s):

![image](https://user-images.githubusercontent.com/1336227/132173327-7edb9e0b-59b4-43fb-b2b1-aefdcc455e6e.png)

ReadStreamToArraySegment also called my attention, but in one of my traces I see a lot of memory is consumed in Amqp library:

![image](https://user-images.githubusercontent.com/1336227/132174385-f02b8b62-7d9d-42f2-9fbb-ea6d69935488.png)

**Comment by danielmarbach** [comment]
@felipepessoto I did a bunch of little PRs to improve things I could in my spare freetime

https://github.com/Azure/azure-amqp/pulls?q=is%3Apr+is%3Aclosed+author%3Adanielmarbach

most notable, probably these

https://github.com/Azure/azure-amqp/pull/182
https://github.com/Azure/azure-amqp/pull/185

I stopped though due to lack of time in my hands nowadays as well as no real commitment where the journey is going with the AMQP lib.

**Comment by felipepessoto** [comment]
Are these changes incorporated in latest releases?

**Comment by ramya-rao-a** [comment]
@danielmarbach, @felipepessoto Thanks for your patience here
@JoshLove-msft Do we have any updates here?

**Comment by JoshLove-msft** [comment]
The approach we decided on was to focus on improvements within the AMQP lib itself rather than introducing a new programming model in the Service Bus library. Thank you for your contributions @danielmarbach! We should make sure that these changes made their way into the hotfix branch - https://github.com/Azure/azure-amqp/tree/hotfix
