### ISSUE TITLE
Management Libraries: Supported services?

### ISSUE THREAD

**Issue by aL3891** [Azure/azure-sdk-for-net#19663]
I'm trying to understand what azure services are supported by the various versions of the azure sdk, especially the Azure.ResourceManager.* family of management apis. 
Is there an easy way to discover this within the api (f.e extension methods) or in the docs? i've searched around but not been able to find a comprehensive list, "to make an x, use this"

I understand productivity is the goal of this new api, but if people can't create the resources they need, the rest is kind of moot :)

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by JonathanCrd** [comment]
Thanks for contacting us. 
Re-routing this to @nickzhums.

**Comment by nickzhums** [comment]
@aL3891 thanks for your feedback. We have been doing further improvement and re-design of the current "Azure.ResourceManager" packages to provide better user experience, and target to public preview the new SDK around June. Because of this, we have not released that many "Azure.ResourceManager" SDKs yets because they are subject to change.

You can find the list of current released packages here:
https://azure.github.io/azure-sdk/releases/latest/mgmt/dotnet.html

Also, if you are interested in trying out our new SDK, please let us know and we'd be happy to arrange that. Thanks!

**Comment by aL3891** [comment]
Hello, Ok i understand, sure trying them out could be interesting, we're currently exploring bicep to modernize our deployment (using arm and powershell today) however some steps will still probably require some code so it would be nice to have a complete c# sdk.

Currently there are some issues that i hope can be sorted out such as some classes like SubResource being duplicated in diffrent namespaces making it cumbersome to create compute and networking resources in the same file for example.

I've seen the list you linked but it is a little bit too course grained though, for example i'd like to create a vmss, is that in compute? probably, but what about service fabric or aks? Also we need app insights and log analytics, are those in the "insights" one? i could not find them in there but maybe they arent added yet.

**Comment by allenjzhang** [comment]
With the new Azure.ResourceManager.XXX, we only have about 10 services out. These libraries are beta only as we are in the process of redesign the APIs in new Azure.ResourceManager.XX SDKs. We hope we can start previewing these in 2, 3 months time. Once the new APIs are stabilized, we will be going broad in service coverages of the new SDK.
