### ISSUE TITLE
[QUERY] Using EventProcessorClient to read batches of events

### ISSUE THREAD

**Issue by hellooperatorpatchmethrough** [Azure/azure-sdk-for-net#19677]
**Query/Question**
I was not able to find any examples, direct documentation on how to use the `EventProcessorClient` with event batching in mind. I am particularly interested in examples/docs on using the client in event batch processing and checkpoint management. The events available on public api AFAIK support processing just one by one.

Thanks

It would really help to have documentation/examples available on such use case as well.

**Comment by jsquire** [comment]
The `EventProcessorClient` does not natively support batches by design.  An example of implementing a batched approach using it can be found in our [Processing Events sample](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/eventhub/Azure.Messaging.EventHubs.Processor/samples/Sample04_ProcessingEvents.md#batch-processing).

For a bit more context, `EventProcessorClient` was designed to provide a familiar API to that of the `EventHubConsumerClient` and offer an intuitive "step-up" experience for developers exploring Event Hubs as they advance to production scenarios.  For a large portion of our library users, that covers their needs well.   There's definitely a point, however, where an application requires more control to handle higher throughput or specialized needs - that's where the `EventProcessor<TPartition>` is intended to help.
 
The `EventProcessor<TPartition>` fills a similar role as the `EventProcessorClient`, with cooperative load balancing and resiliency as its core features but also offers native batch processing, extension points for influencing load balancing, customizing of storage providers, and a lighter, less opinionated API.  The caveat is that this comes in the form of an abstract base, which needs to be extended and the core “handler” activities implemented via override.  More on the design and philosophy behind this can be found [here](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/eventhub/Azure.Messaging.EventHubs/design/proposal-event-processor%7BT%7D.md) and an article that demonstrates creating your own customized processor using `EventProcessor<TPartition>` can be found [here](https://devblogs.microsoft.com/azure-sdk/custom-event-processor/).

**Comment by steavy29** [comment]
Hello @jsquire 

I am trying to migrate my EventHub implementation from v4(Microsoft.Azure.EventHubs) to the new v5.

I came here with the same question in mind about batch processing. In one of my cases I'm processing data by storing it in a database. So batch processing, which is native in v4 SDK(by implementing IEventProcessor interface), worked good for me. 

As I see, most straightforward way of using v5 SDK is by utilizing `EventProcessorClient` class. But as you mentioned above, it does not support batch processing by design. The way forward here, as I understand, is to use a bit lower-level class `EventProcessor<TPartition>`. I checked it out and it does provide override methods for batch processing. But the issue I see there is that now I am not provided with any checkpointing implementation and should add it by myself somehow. `EventProcessorClient` class has checkpointing logic implemented inside which perfectly suites my needs. 

My plan is to keep using default approach with blob checkpoints, so I don't need to customize anything there. 
So is there a relatively easy way to have best from both worlds - batch processing availability and a ready-to-use checkpointing functionality without need to re-implement what is in `EventProcessorClient` class.

Thanks

**Comment by jsquire** [comment]
Hi @steavy29.  Thank you for your feedback.  You're correct in your assessment of the trade-offs in choosing between the processor types.  There currently is no ready-made option for storage in the `EventProcessor<TPartition>`; custom processors would need to provide their own implementation.   The [article](https://devblogs.microsoft.com/azure-sdk/custom-event-processor/) that I shared above walks through creation of a Blob Storage-based processor implementation that offers a batch-based approach and is intended to be extended with processing logic.   We'll be offering that as an end-to-end sample as well, though I don't have a timeline to share on when that may be available.

**Comment by steavy29** [comment]
Thank you for the reply, that makes sense.
For now, we will probably keep using v4 SDK. Are there any thoughts/plans for improving batch processing interfaces of the SDK? Something that would offer feature parity with v4 SDK.

**Comment by jsquire** [comment]
We don't have any current plans to release a stand-alone storage integration for the processor.   Beyond that, there is feature parity with the legacy SDK, though with a different usage pattern and a different set of types.  Was there something outside of a storage provider that you're seeing as a parity gap?
