### ISSUE TITLE
[QUERY] Service Bus Processor: Should the error handler be invoked when there is no topic?

### ISSUE THREAD

**Issue by rorococo** [Azure/azure-sdk-for-net#19749]
**Query/Question**
Not sure if this is a bug or not. I wanted to check my error handling code for Transient errors so during debugging I will delete my Topic from the Azure Portal. 
Using the mandatory ProcessErrorAsync event I receive the ProcessErrorEventArgs. At this stage the ErrorHandler continues to be hit indefinitely until I call _processor.StopProcessing();

Is this expected? 

**Environment:**
Azure.Messaging.ServiceBus 7.1.0
Hosting platform or OS and .NET runtime version: Windows 10.0.19042, .NET 5.0.103
IDE and version : Visual Studio 16.8.2

**Comment by jsquire** [comment]
Hi @rorococo.  Yes, this is expected.  One of the core features of the processor is a high degree of resilience in the face of exceptions.  Once successfully started, it will continue to retry failures and surface them to the error handler until you explicitly request stopping it or the host process is torn down.

The processor has no way of knowing that your topic has been deleted and that you do not intend to recreate it.  From the processor's perspective, he same error could occur with a transient service error, when you created a topic but the resource is not yet available, or an intentional delete/recreate.

**Comment by rorococo** [comment]
If I have ServiceBusRetryOptions with MaxRetries, will this number of retries be completed before the error is thrown to the handler?

**Comment by jsquire** [comment]
Correct;  the retry policy governs a single operation.  That operation is retried until it is either successful or the number of retries is exhausted, at which point the error is surfaced.   The exception that occurred is available as part of the [ProcessErrorEventArgs](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/servicebus/Azure.Messaging.ServiceBus/src/Processor/ProcessErrorEventArgs.cs) that the error handler is invoked with.
