### ISSUE TITLE
[FEATURE REQ] Easier troubleshooting of 403 (Forbidden) when using DefaultAzureCredential

### ISSUE THREAD

**Issue by ayeltsov** [Azure/azure-sdk-for-net#19948]
**Library or service name.**
Azure.Identity
Azure.Security.KeyVault.Secrets
 
**Is your feature request related to a problem? Please describe.**

I have recently rolled out new application with Azure.Identity. Some users are experiencing 403 errors which are difficult to troubleshoot:

```
Status: 403 (Forbidden)

Content:
{"error":{"code":"Forbidden","message":"Caller is not authorized to perform action on resource.\r\nIf role assignments, deny assignments or role definitions were changed recently, please observe propagation time.\r\nCaller: appid=872cd9fa-d31f-45e0-9eab-6e460a02d1f1;oid=d45307dc-69ea-4daf-a1ac-a9ab54f3650e;iss=https://sts.windows.net/33e01921-4d64-4f8c-a055-5bdaffd5e33d/\r\nAction: 'Microsoft.KeyVault/vaults/secrets/getSecret/action'\r\nResource: '/subscriptions/**/resourcegroups/**/providers/microsoft.keyvault/vaults/**/secrets/**'\r\nAssignment: (not found)\r\nVault: **;location=eastus\r\n","innererror":{"code":"ForbiddenByRbac"}}}
```

Q1: what was the underlying provider of security token? We spent a lot more time than we should have to identify that particular user was running tool on Azure and token was provided by Managed Identity. The fix was easy once we understood cause, but getting there was not.
[edit] Just had another case where developer had VisualStudio Code credential being picked up. Maybe there's a better way to troubleshoot this, but we ended up inspecting DefaultCredential object's private fields in the debugger and thus were able to find which credential it picked up.

Q2: when authentication fails like above, we need means to inspect the token (for example, run it by https://jwt.ms/). Currently there is no way to get specific token that was used for failed operation

Q3: need clear troubleshooting instructions on removing the cached tokens. We currently have situation where shipped version of the app is picking cached token for the wrong tenant. We know the fix, but it requires code change and shipping that code is not easy. To mitigate the issue, we need to know how to clear cached token, but Azure.Identity does not make it easy. There are [instructions ](https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-net-clear-token-cache) to clear underlying MSAL cache, but it's a different layer - I should not need to go to lower level library; and also I could not make that work, maybe because I need to supply the right ClientId, or maybe because Azure.Identity is using it's own caching

**Comment by schaabs** [comment]
@ayeltsov Thanks for reaching out with your questions and feedback. I know diagnosing authentication issues in general can be difficult, and we want to continue to improve this experience in the Azure.Identity library, as well as across the Azure SDK. Your feedback is very appreciated, and it will help us better understand the practical pain points, and ways we can improve the diagnostic experience. I'll try to address your specific questions here with what is possible in the library today, and I welcome any suggestions you have on how this could be improved upon.

> Q1: what was the underlying provider of security token? We spent a lot more time than we should have to identify that particular user was running tool on Azure and token was provided by Managed Identity. The fix was easy once we understood cause, but getting there was not.
[edit] Just had another case where developer had VisualStudio Code credential being picked up. Maybe there's a better way to troubleshoot this, but we ended up inspecting DefaultCredential object's private fields in the debugger and thus were able to find which credential it picked up.

This is a common request from users and an area which definitely needs improvement, even if just documenting currently available troubleshooting. One way which you could currently get this information, other than in the debugger, is via our logs other than in the debugger. Every credential in the Azure.Identity library logs event source events on the success or failure of  `GetToken` or `GetTokenAsync`, specifically the events `GetTokenSucceeded`, and `GetTokenFailed`.  Since logging all SDK events can be rather noisy, here's a small exampl of how you could filter logged events, to specifically see which credentials have been tried, and which credential ultimately succeeded.

```c#
static void Main(string[] args)
{
    AzureEventSourceListener listener = new AzureEventSourceListener(IdentityCredentialEventSourceHandler, EventLevel.Informational);

    SecretClient client = new SecretClient(new Uri("https://myvault.vault.azure.net/"), new DefaultAzureCredential());

    KeyVaultSecret secret = client.GetSecret("mysecret");
}

public static void IdentityCredentialEventSourceHandler(EventWrittenEventArgs eventArgs, string text)
{
    if (eventArgs.EventName == "GetTokenFailed" || eventArgs.EventName == "GetTokenSucceeded")
    {
        Console.WriteLine($"{eventArgs.Payload[0]} {eventArgs.EventName}");
    }
}
```
Here's some sample output from the above example where the `AzureCliCredential` was ultimately used by the `DefaultAzureCredeential`
```
EnvironmentCredential.GetToken GetTokenFailed
ManagedIdentityCredential.GetToken GetTokenFailed
SharedTokenCacheCredential.GetToken GetTokenFailed
VisualStudioCredential.GetToken GetTokenFailed
VisualStudioCodeCredential.GetToken GetTokenFailed
AzureCliCredential.GetToken GetTokenSucceeded
DefaultAzureCredential.GetToken GetTokenSucceeded
```
Keep in mind that each instance of `DefaultAzureCredential` will only walk the chain of credentials once, so on subsequent requests you would only see the last two lines. Also if you want more information as to why particular credentials failed you can just log the `text` parameter, I only wrote the event name and the first event argument, which is contains the specific credential, to increase the readability for demonstration purposes.

We have considered adding an API onto the `DefaultAzureCredential` and `ChainedTokenCredential` in the past, but we opted to start with the logging instead. Would the above approach suit your needs? Or would you prefer to see a property so you could programmatically access the credential which was chosen?

> Q2: when authentication fails like above, we need means to inspect the token (for example, run it by https://jwt.ms/). Currently there is no way to get specific token that was used for failed operation

Yes unfortunately getting the actual token used in a particular request is fairly difficult. In order to protect customers from accidently leaking tokens into logs we redact this information from all logs and exceptions by default. You _could_ get this information by specifically enabling the Authorization to be logged via the specific clients as below.

```c#
SecretClientOptions options = new SecretClientOptions
{
    Diagnostics = { LoggedHeaderNames = { "Authorization" } }
};

SecretClient client = new SecretClient(new Uri("https://dotnettestvault.vault.azure.net/"), new DefaultAzureCredential(), options);
```

However, to keep your application secure I would __STRONGLY ADVISE YOU NOT DO THIS__, or if you do enable this only do this in temporarily in a debug environment, and ensure you protect the logs as __LEAKING THE LOGS IN THIS CASE WOULD COMPROMISE THE AUTHENTICATED ACCOUNT__.

I'm wondering instead if, in the case, the error returned from key vault actually had the information you needed? It contains the application id, account oid, and tenant (in the form of issuer) corresponding to the token the call was authenticated with.

```
Caller: appid=872cd9fa-d31f-45e0-9eab-6e460a02d1f1;oid=d45307dc-69ea-4daf-a1ac-a9ab54f3650e;iss=https://sts.windows.net/33e01921-4d64-4f8c-a055-5bdaffd5e33d
```

Is this information not sufficient? If not what other information would you want from the access token to aid with debugging the failure?


> Q3: need clear troubleshooting instructions on removing the cached tokens. We currently have situation where shipped version of the app is picking cached token for the wrong tenant. We know the fix, but it requires code change and shipping that code is not easy. To mitigate the issue, we need to know how to clear cached token, but Azure.Identity does not make it easy.

By default each credential in Azure.Identity has its own token cache, so "clearing the cache" is as simple as creating a new credential instance. However, we have introduces a new feature in 1.4.0-beta.4 which allows you to configure credentials to persist their token cache using a new options class `TokenCachePersistenceOptions`. Examples on how to use this feature can be be found [here](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/identity/Azure.Identity/samples/TokenCache.md), though keep in mind the feature is still in beta so the API might change slightly before our GA of 1.4.0. 

Currently, with this feature we don't have a way to clear the persisted cache, but it's an interesting request. Could you give me more information on when your application might want to clear the cache? Also would your application only need to remove every account out of the cache, or just tokens for specific accounts?

I hope these answers here help somewhat. Please let me know your thoughts and if you have any other questions related to diagnosing authentication failures.
