### ISSUE TITLE
[File Shares] Uploading file to Premium File Storage account fails with InvalidRange

### ISSUE THREAD

**Issue by tomasr** [Azure/azure-sdk-for-net#20007]
**Describe the bug**
I can't seem to figure this one out. I have some code that is currently being used to upload files to an Azure File Share, kinda like this:

```C#
    public async Task Upload(String file, byte[] contents) {
        var share = GetShareClient(pod);

        var root = share.GetRootDirectoryClient();
        var fileref = root.GetFileClient(file);
        using ( var stream = new MemoryStream(contents) ) {
          await fileref.UploadAsync(stream);
        }
    }
```
It works perfectly when used with a regular Azure storage account.

However, I can't seem to make it work with an Azure File Storage Premium account. Downloading files works great, but every Upload() call I make just fails with:

```
Azure.RequestFailedException: The range specified is invalid for the current size of the resource.
RequestId:6da55241-501a-008e-1e77-268f50000000
Time:2021-03-31T21:49:55.3495265Z
Status: 416 (The range specified is invalid for the current size of the resource.)
ErrorCode: InvalidRange
```

**Expected behavior**
I would expect the code above to work, since it works with regular accounts. In this case, I'm using the code to replace a file that already exists on the file share, if that makes a difference.

**Actual behavior (include Exception or Stack Trace)**
See above

**Environment:**
 - Azure.Storage.File.Shares v 12.6.1 running on .NET core 3.1 on linux.
 -

**Comment by seanmcc-msft** [comment]
Hi @tomasr,

Could you post the working request/response and failing request/response from Fiddler?

Also, what is the size of the file you specified when the file was created in Azure Storage, and the size of the stream you are trying to upload?

Thanks,

-Sean

**Comment by tomasr** [comment]
Hi @seanmcc-msft

Unfortunately, I don't have an easy way to grab those since it's in a fairly restricted environment.

Both the existing file and the new one are small, under 400 bytes, but probably slightly different sizes.

After looking at it for a while, I think the fundamental issue is that the library is always doing a ranged request, so unless the files are exactly the same size, things are just not going to work properly. I suspect that might have been going on in the non-premium storage account it was working on initially, but I am not entirely sure.

I will say the biggest issue here is not even the library behavior. It's that there's simply no documentation on how it's supposed to work. For example, while trying to get this to work I said "well, I'll just delete the existing file and upload a new one".... well, no that doesn't work either because the ranged upload request will fail if the file doesn't already exist. That was very surprising, since it's not really documented.

I kinda worked around it for now by first forcing a call to Create() first with the exact size of the file that is going to get uploaded, but even that is kinda weird, because Create() is documented as taking the "maximum size", not the *actual* size of the resulting file you want. Again, confusing.

I fully understand the library tries to be a relatively thin wrapper on top of the Storage API but.... It's definitely been more confusing and harder to use than the older ones, in my experience.

**Comment by seanmcc-msft** [comment]
Hi @tomasr,

> I kinda worked around it for now by first forcing a call to Create() first with the exact size of the file that is going to get uploaded, but even that is kinda weird, because Create() is documented as taking the "maximum size", not the actual size of the resulting file you want. Again, confusing.

I agree, the maximum size parameter can be confusing.  I believe the workflow you are describing should also work if you are setting max size to a size that is larger than the content you are about to uploading.

We do have public REST docs that provide more information about these operations:

- [Create File](https://docs.microsoft.com/en-us/rest/api/storageservices/create-file)
- [Put Range](https://docs.microsoft.com/en-us/rest/api/storageservices/create-file)

I think the key points are:
- You need to create the file with a max size >= the size of your content before you call Put Range
- Put Range requests are limited to 4 MB each, and the range must fall within the range of your file, which is offset 0 - max size.  The size of the range you specify must equal the length of the stream you are trying to upload.
- If you don't want to worry about the 4 MB limit and ranges, you can call [ShareFileClient.Upload()](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/storage/Azure.Storage.Files.Shares/src/ShareFileClient.cs#L4209), and we will handle the chunking for you.

-Sean

**Comment by tomasr** [comment]
> I agree, the maximum size parameter can be confusing. I believe the workflow you are describing should also work if you are setting max size to a size that is larger than the content you are about to uploading

Well.... that was actually what I tried first, by setting maxSize=Int32.MaxSize. Imagine my surprise when querying the file properties later reported the file size as being 2GB. So... no, sounds like it better be exactly the size you want to upload.

> We do have public REST docs that provide more information about these operations:

For the REST API, yes. Not the actual library. I really don't want to have to go around looking at the library source code first to figure out which REST APIs it's calling, so that I can look up the REST API docs.  ¯\_(ツ)_/¯

> If you don't want to worry about the 4 MB limit and ranges, you can call ShareFileClient.Upload(), and we will handle the chunking for you.

I've always been using Upload(). It was just very confusing to be getting errors related to ranges, when I wasn't doing a range request directly, nor was I uploading content over 4MB.

**Comment by amnguye** [comment]
I was actually looking at the documentation for maximum size. "Specifies the maximum size for the file." I think says what it exactly needs to say however I can see this can be misleading. The reason why it's documented as is, is to to allow the customer to be able to allocate enough space in their file to upload. The file will not expand if you upload at the end of the file size. We are documenting it the same as the Rest API is documenting this.
https://docs.microsoft.com/en-us/rest/api/storageservices/create-file

> For the REST API, yes. Not the actual library. I really don't want to have to go around looking at the library source code first to figure out which REST APIs it's calling, so that I can look up the REST API docs. ¯\(ツ)/¯
I'm not sure how far in the library source code you even have to go to look for this information. In our doc strings we clearly state the corresponding REST API for these methods.
https://docs.microsoft.com/en-us/dotnet/api/azure.storage.files.shares.sharefileclient.createasync?view=azure-dotnet
![image](https://user-images.githubusercontent.com/48961492/124993196-e4e49080-dff8-11eb-8772-ee11f88b6391.png)
https://docs.microsoft.com/en-us/dotnet/api/azure.storage.files.shares.sharefileclient.uploadasync?view=azure-dotnet
![image](https://user-images.githubusercontent.com/48961492/124993365-207f5a80-dff9-11eb-8e1f-f4324de7af2c.png)
These pages are generated from our doc strings in our source, and which you don't have to dig very deep at all.
![image](https://user-images.githubusercontent.com/48961492/124993522-51f82600-dff9-11eb-8d3a-d7e71ff59631.png)

If you're looking to expand the size of the file you would have to use our `SetHttpHeaders` API in order to set the size to be larger.

Please reply if you have any further questions.
