### ISSUE TITLE
Service Bus webjobs extension should cancel retry loop if lock is lost

### ISSUE THREAD

**Issue by paulbatum** [Azure/azure-sdk-for-net#20177]
Port the fix for this issue to 5.x servicebus webjobs extension:
https://github.com/Azure/azure-functions-servicebus-extension/issues/145

**Comment by JoshLove-msft** [comment]
Discussed this and https://github.com/azure/azure-sdk-for-net/issues/20174 during our sync today. The functions retry feature is still in beta. We should make sure that the function retry logic does not happen when the message lock is lost before the functions retry feature is stable (this may require coordination between the extension and webjobs SDK code), but this is not required for the extensions stable release.

**Comment by JoshLove-msft** [comment]
I dug into this a bit and here is what I found:
The use of [IRetryStrategy](https://github.com/Azure/azure-webjobs-sdk/blob/dev/src/Microsoft.Azure.WebJobs.Host/IRetryStrategy.cs) does not seem to permit preventing an exception from being retried. The interface has two members - MaxRetryCount and GetNextDelay. By overriding GetNextDelay you can customize how long to wait before the next retry, but you can't prevent the retry from occurring. One way to achieve this would be to change the method from returning a `TimeSpan` to returning a `TimeSpan?` and using the semantic that a null return means the operation should not be retried. We do this in both Service Bus and Event Hubs T2 libraries. 

The tricky part is that we still want to respect the retry strategy that is used in the class or function attribute. So the SB/EH retry strategies should augment the attribute specified rather than replace them. In fact, the retry SB/EH retry strategies would only apply if a retry attribute is specified by the user. 

## Option 1
As a straw man proposal, one way that we could do this would be to define an abstract class called something like ComposedRetryStrategy which implements IRetryStrategy. This abstract class would define a constructor that takes a RetryAttribute:
```cs
public abstract class ComposedRetryStrategy : IRetryStrategy
    {
        // this is needed for dependency injection
        public ComposedRetryStrategy();
        public ComposedRetryStrategy(RetryAttribute attribute);
        public abstract TimeSpan? GetNextDelay(RetryContext context);
        public int MaxRetryCount => _attribute.MaxRetryCount;
    }
```
We would then have specific strategies for SB/EH, e.g.:
```cs
public abstract class ServiceBusRetryStrategy : ComposedRetryStrategy 
{
      public override TimeSpan? GetNextDelay();
}
```

We would then add ComposedRetryStrategy them into a new parameter of the [FunctionIndexProvider constructor](https://github.com/Azure/azure-webjobs-sdk/blob/dev/src/Microsoft.Azure.WebJobs.Host/Indexers/FunctionIndexProvider.cs#L36) from the Service Bus/Event Hubs extensions. This would get injected using the default parameterless constructor. We would then need to use reflection to create an instance of the relevant composed strategy using reflection passing in the looked up attribute in [FunctionIndexer](https://github.com/Azure/azure-webjobs-sdk/blob/dev/src/Microsoft.Azure.WebJobs.Host/Indexers/FunctionIndexer.cs#L380). 

The things I don't like about this approach is that we need to use reflection to construct the composed strategy, and that we still need to use DI to inject the ComposedStrategy using the parameterless constructor.

## Option 2
Define a IRetryClassifer interface:
```cs
    public interface IRetryClassifier
    {
        public bool ShouldRetry(RetryContext context);
    }
```

Implement instances of these for SB/EH and Inject into [FunctionIndexProvider constructor](https://github.com/Azure/azure-webjobs-sdk/blob/dev/src/Microsoft.Azure.WebJobs.Host/Indexers/FunctionIndexProvider.cs#L36). Pass this information through to FunctionInstance.
 Update [TryExecuteAsync](https://github.com/Azure/azure-webjobs-sdk/blob/dev/src/Microsoft.Azure.WebJobs.Host/Executors/FunctionExecutorExtensions.cs#L69) in FunctionExecutorExtensions to call ShouldRetry (if IRetryClassifier instance is not null) before calling GetNextDelay.

This approach seems a lot cleaner at the cost of introducing a separate IRetryClassifier type and needing to pipe it through to FunctionInstance.

**Comment by JoshLove-msft** [comment]
Based on my investigation, we would need support added into WebJobs SDK to allow retries to be skipped based on an exception. I've proposed a couple ideas, but I suppose this should probably be further explored by WebJobs folks.

**Comment by alrod** [comment]
Retry loop only applies to function code which executes inside WebJobs SDK. Once the function code was successfully executed (without unhandled exceptions) retry loop is finished and control moves to an extension. Completing(SB)/checkpointing(EH) occurs outside retry loop in the extensions. There will be duplicate executions neither or not we have retry policy in case of message lock lost/partition lease lost.

I see only problem when the SB trigger defined AutoComplete=false and the MessageLockLostException will be thrown on each retry causing duplicate executions - I think we can point it out in documentation.

**Comment by alrod** [comment]
@JoshLove-msft, thanks for the feedback. 
I like "Option 2" but the question is how to choose right implementation in `FunctionIndexProvider` constructor

**Comment by JoshLove-msft** [comment]
> @JoshLove-msft, thanks for the feedback.
> I like "Option 2" but the question is how to choose right implementation in `FunctionIndexProvider` constructor

Well wouldn't this be up to the extensions to inject the right implementation? By default, it would be null.

**Comment by alrod** [comment]
@JoshLove-msft, correct approach here is cancelling execution using cancellerationToken we pass to each execution: see the PR above.
For EventHub it's easy as there is the event of closing an partition:
https://github.com/Azure/azure-functions-eventhubs-extension/blob/dev/src/Microsoft.Azure.WebJobs.Extensions.EventHubs/Listeners/EventHubListener.cs#L134

for ServiceBus it's more complicated as 
1. we only will know if the lock is expired on completing the message. 
2. anyway after lock is lost the message will be reappeared in the SB entity immediately -> multiple execution

We have the same issues for long running ServiceBus execution right now which is the same as ServiceBus executions with retries. Is there a way to monitor when lock is expired from ServiceBus SDK?

I am thinking to restrict using retries for ServiceBus as there is the build-in retry logic already or warn the customers that execution with retries can lead to lease lost if a retries policy is defined for SB trigger.

cc: @mathewc

**Comment by JoshLove-msft** [comment]
I think we could actually try/catch/rethrow the LockLostExceptions in ServiceBusMessageActions. If there is a lock lost exception, then we can cancel an internal token source property that we add to ServiceBusMessageActions. The token we pass to TryExecute would need to be a linked token containing this other token.

**Comment by JoshLove-msft** [comment]
> anyway after lock is lost the message will be reappeared in the SB entity immediately -> multiple execution

I'm not sure I follow what the issue is here. The message would be redelivered and executed in a separate function invocation where presumably we would have the lock. The invocation using the message with the expired lock should still not be retried.

**Comment by alrod** [comment]
> > anyway after lock is lost the message will be reappeared in the SB entity immediately -> multiple execution
> 
> I'm not sure I follow what the issue is here. The message would be redelivered and executed in a separate function invocation where presumably we would have the lock. The invocation using the message with the expired lockToken should still not be retried.

retry logic incapsulated into https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/servicebus/Microsoft.Azure.WebJobs.Extensions.ServiceBus/src/Listeners/ServiceBusListener.cs#L252 call. so we do not call `CompleteProcessingMessageAsync` while the function is failing.

**Comment by JoshLove-msft** [comment]
> I think the improvements Josh suggested make sense from the SB SDK point of view - it would be useful for general users of SB SDK to have a way to know immediately when they've lost a message lock, so they can optimize their code and stop long running operations. We'd then be able to leverage that in our extensions via a linked cancellation token. I assume you're only talking about adding this for Track2? We'd still need to figure out what to do for Track1 SB extension.

Making this change in the SB SDK would require API changes and it isn't as obvious that this will be beneficial for users there, as the callback won't be retried automatically like it would with functions retries enabled. The code changes I was suggesting would be made in the SB extensions and would not require API changes. If we needed to, we could always move this to the SDK in the future (with a new API) if users request it.

**Comment by JoshLove-msft** [comment]
> This issue is also relevant to QueueTrigger - I don't see a tracking item for that extension (only EventHubs/ServiceBus). In this case the extension manages its own message visibility and uses a background timer to keep the message invisible to other instances while the function is processing it (code here). It's possible for that background update timer to loose ownership of the message as well, and currently that isn't communicated via any cancellation or anything. This is analogous to the SB issue.

/cc @kasobol-msft for Queue extension

**Comment by JoshLove-msft** [comment]
Retries are not currently enabled for Service Bus extension.
