### ISSUE TITLE
[BUG] InvalidOperationException is thrown for BlobBatchClient.DeleteBlobsAsync

### ISSUE THREAD

**Issue by martinjoshua** [Azure/azure-sdk-for-net#20196]
**Describe the bug**
When bulk deleting a large amount of files using the DeleteBlobsAsync function of the batch client, the function throws an InvalidOperationException.

**Expected behavior**
The function should complete with the blobs having been marked for deletion.

**Actual behavior (include Exception or Stack Trace)**
```
Azure.RequestFailedException: Invalid response
Status: 202 (Accepted)

Headers:
Transfer-Encoding: chunked
Server: Windows-Azure-Blob/1.0,Microsoft-HTTPAPI/2.0
x-ms-request-id: af90d6fc-c01e-001c-71e5-2b9d87000000
x-ms-version: 2020-04-08
x-ms-client-request-id: 25e6bd61-4374-4935-926d-5ef449506af0
Date: Wed, 07 Apr 2021 19:35:38 GMT
Content-Type: multipart/mixed; boundary=batchresponse_0226c30a-0183-4f1c-92a2-b2d65491c4c8

 ---> System.InvalidOperationException: Expected 24083 responses for the batch request, not 1.
   at Azure.Storage.Blobs.Specialized.BlobBatchClient.UpdateOperationResponses(IList`1 messages, Response rawResponse, Stream responseContent, String responseContentType, Boolean throwOnAnyFailure, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at Azure.Storage.Blobs.Specialized.BlobBatchClient.UpdateOperationResponses(IList`1 messages, Response rawResponse, Stream responseContent, String responseContentType, Boolean throwOnAnyFailure, Boolean async, CancellationToken cancellationToken)
   at Azure.Storage.Blobs.Specialized.BlobBatchClient.SubmitBatchInternal(BlobBatch batch, Boolean throwOnAnyFailure, Boolean async, CancellationToken cancellationToken)
   at Azure.Storage.Blobs.Specialized.BlobBatchClient.DeleteBlobsInteral(IEnumerable`1 blobUris, DeleteSnapshotsOption snapshotsOption, Boolean async, CancellationToken cancellationToken)
   at Azure.Storage.Blobs.Specialized.BlobBatchClient.DeleteBlobsAsync(IEnumerable`1 blobUris, DeleteSnapshotsOption snapshotsOption, CancellationToken cancellationToken)
```

**To Reproduce**
Steps to reproduce the behavior (include a code snippet, screenshot, or any additional information that might help us reproduce the issue)
 ```
var container = cloudBlobClient.GetBlobContainerClient("mycontainer");

var batchClient = cloudBlobClient.GetBlobBatchClient();

var blobs = container.GetBlobs(prefix: $"test-")
    .OfType<BlobItem>()
    .Select(a => container.GetBlobClient(a.Name).Uri)
    .ToList();

if (blobs.Any())
    await batchClient.DeleteBlobsAsync(blobs, DeleteSnapshotsOption.IncludeSnapshots);
```

**Environment:**
 - Name and version of the Library package used: Azure.Storage.Blobs.Batch 12.5.1
 - Hosting platform or OS and .NET runtime version: Windows 10, net5
 - IDE and version: Visual Studio 16.8.3

**Comment by amnguye** [comment]
I attempted to reproduce your bug, looks like from your exception you attempted to delete `24083` blobs or something around that number, but looks like there's a limitation on how many blobs can be deleted in each batch because when I went to create 2000 blobs, and delete them I got a 400 error `ExceedsMaxBatchRequestCount` which is the error you should have gotten. However you didn't get, you got a different error.

I think what's frustrating about this bug is that there's another bug here where we don't print out what the response you received from the service. We should be printing out the responses some how even if it doesn't match the amount of responses we expect. Or at least if we only see one response we should print it out.
https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/storage/Azure.Storage.Blobs.Batch/src/BlobBatchClient.cs#L620

For now could you attempt this in smaller batches (current max is 256 according to [documentation](https://docs.microsoft.com/en-us/rest/api/storageservices/blob-batch))?

**Comment by martinjoshua** [comment]
Thanks for looking into it.  I also re-ran the same code but on a smaller list of blobs (but still well over 256) and received the same error that you did. That new error message is very clear, and if I had seen that the first time, would have made the necessary adjustments without raising an issue. 

Thank you for pointing to the documentation. I had checked to see if there is a limit but could not find it (didn't look hard enough!) With that said, we can close this as everything is mostly working (but a more clear exception should probably be returned for the insanely large batch requests.)

**Comment by amnguye** [comment]
I might want to keep this open (maybe rename the issue) because the error handling could be better (aka printing out the full exception message, along with saying the expectation of number of responses).

**Comment by amnguye** [comment]
Changed to feature request.

**Comment by seanmcc-msft** [comment]
Blob Batch operations are limited to 256 sub requests - https://learn.microsoft.com/en-us/rest/api/storageservices/blob-batch?tabs=microsoft-entra-id#remarks
