### ISSUE TITLE
Hyak.Common.CloudException is not Serializable

### ISSUE THREAD

**Issue by ikolos-softheme** [Azure/azure-sdk-for-net#2020]
Despite of common practice of exception implementing this exception is not marked with SerializableAttribute and does not implement ISerializable. How should I pass it to a front-end part of my application through WCF or store in a database?

**Comment by hovsepm** [comment]
@ikolos-softheme thank you (and all people from Softheme ;)) for bringing this up. 2 things here:
1. We will not add any new features/functionality to the Hyak libraries since it is in the support mode. We a transitioning to AutoRest generators.
2. Use Newtonsoft.Json nuget package to serialize this type into a json file.
