### ISSUE TITLE
[FEATURE REQ] Storage Files: Faster Upload

### ISSUE THREAD

**Issue by Asfandtnt** [Azure/azure-sdk-for-net#20220]
using Azure.Storage.Files.Shares;

When ever I have to upload large file using Azure file share SDK I can use following function and its works perfectly
  ShareFileClient  file.upload()
it seems it single threaded and relatively very slow for large file e.g more than 400 mb.
can we have any thing like Microsoft.Azure.Storage.DataMovement libray it upload 400mb files in few seconds.

**Comment by amnguye** [comment]
Hi,

This is an overarching ask regarding the SDK since the aim should be to make requests as fast as possible. We've actually already recognized places where we can help improve the speed of uploads and downloads in File Shares (as well looking to allow customers to alter knobs to help increase their speed depending on environment).

https://github.com/Azure/azure-sdk-for-net/issues/15882
https://github.com/Azure/azure-sdk-for-net/issues/14506
https://github.com/Azure/azure-sdk-for-net/issues/19384
https://github.com/Azure/azure-sdk-for-net/issues/13545

Can you track these issues as well? and if you find a bit more specific improvements we can make please open a new issue and we will look to attempt to make those improvements as well. 

We're glad to hear the data movement library still is able to maintain the speed that you are looking for. Are there features in the v12 library you are looking to advantage of that aren't provided in the data movement library? Or is the intent just to use one library instead of two different libraries? (We would like to hear this feedback in order to not regress in any feature asks)
