### ISSUE TITLE
Form Recognizer SDK: Non-english Invoice date causing unhandled exception

### ISSUE THREAD

**Issue by kristapratico** [Azure/azure-sdk-for-net#20223]
Moving this issue to github from [here](https://msazure.visualstudio.com/Cognitive%20Services/_workitems/edit/9672937)

-------------------------------

Hi Team,

We are using the Form Recognizer SDK version 3.1.0-beta.3 and encountered an exception with the following details:

Event time 4/1/2021, 4:47:48 PM (Local time)
Message Field value is null.
Exception type System.InvalidOperationException
Failed method Azure.AI.FormRecognizer.Models.FieldValue.AsDate
CorrelationId dc21fc3c-177d-49df-9663-443565810ba6
```
This issue occurred at the following code block:
if (invoice.Fields.TryGetValue("InvoiceDate", out FormField invoiceDateField))
{
if (invoiceDateField.Value.ValueType == FieldValueType.Date)
{
entities.InvoiceDate = invoiceDateField.Value.AsDate();

}
}
```
The value of the invoice date text was correctly picked as “21 de jul. de 2020” for this specific invoice however believe this failed as it could not be parsed to Date causing the Value.AsDate() to break. Would help to have such exceptions handled by the Form Recognizer SDK and perhaps return a Null value if the date parsing fails?

**Comment by kristapratico** [comment]
@nautiyalshivya

**Comment by maririos** [comment]
FYI we have a very similar issue https://github.com/Azure/azure-sdk-for-net/issues/19858 but haven't been able to confirm.

Need to see what the service output is in order to understand more the issue. It could be also related to the guidance we should give customers ->https://github.com/Azure/azure-sdk-for-net/issues/17712

>perhaps return a Null value if the date parsing fails

For .NET guideline is to throw an exception instead of return null as throwing makes it more obvious to the user and prevents silent errors.

**Comment by maririos** [comment]
Recommendation to users in this case, has been added in PR https://github.com/Azure/azure-sdk-for-net/pull/20722
