### ISSUE TITLE
DataLake.Store: High Number of Requests And Padding

### ISSUE THREAD

**Issue by mmcc1** [Azure/azure-sdk-for-net#2043]
I used the following code to read back a 14KB file (bytes of UTF16 string) placed on the DataLake Store:

`try
            {
                MemoryStream ms = new MemoryStream();
                await (await azureDLConnection.dataLakeStoreFileSystemManagementClient.FileSystem.OpenAsync(azureDLConnection.dataLakeAccountName, remotePath)).CopyToAsync(ms);
                byte[] bytes = ms.GetBuffer();
                ms.Close();
                ms.Dispose();
                return bytes;
            }
            catch (Exception ex)
            {
                throw ex;
            }`

The code itself appears to work fine, but I have two odd issues.  The first is that the Azure portal states there has been over 100 requests which seems very high for a 14KB file.  The second is that when the contents of the file is returned, it is padded with trailing '\u0000'.

This is the output I get:
"testing\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"

I checked the file in the DataLake Store and it only has the words "testing" in it, with some unicode symbols in between each letter.

Is this expected behaviour?

**Comment by begoldsm** [comment]
@mmcc1 this is not expected behavior. I am investigating this now and think this might be an issue with the "grab all the bytes" option for this method when you don't specify length/offset. To work around this in your code, you can specify the length and offset (of 0 in this case) of the data you want back.

**Comment by begoldsm** [comment]
@mmcc1 I think I figured out why you are getting the padding, although I am unable to reproduce the 100 requests for a simple file. I tried create the same file you created with the contents of "testing" and then used the exact same code that you have. The problem lies in how you are using the memory buffer and getting content out of the memory buffer.

The buffer capacity is increased to 256 when you use CopyTo (I am not exactly sure why, though, since it correctly only copies 7 bytes). When you then call GetBuffer(), it returns the entire memory stream as a byte array, including the unused 249 positions in the stream (which are all the equivalent of null). See the screenshot below to see how big the memory stream actually is versus the capacity it has set:
![image](https://cloud.githubusercontent.com/assets/8781927/16435104/7c8aa7ca-3d48-11e6-8293-752ac88f278a.png)

To ensure that you don't load in more data than you want, I recommend instead of GetBuffer() using ToArray(), which will take the actual contents of the buffer up to the current length and return them in a byte array.

As for the 100 requests, can you give us a snippet of the types of requests you are seeing happen over and over when you make the single call? It should just be a single request for a file of that size (excluding initial authentication challenges).

**Comment by mmcc1** [comment]
I'll give that a shot and see how I get on.  I don't feel that my code is making 100 requests, but rather it is something to do with how Azure handles it.  I'll dig a little deeper on this and let you know.

**Comment by begoldsm** [comment]
@mmcc1 were you able to dig deeper in this and discover if that resolved the issue?

**Comment by mmcc1** [comment]
Unfortunately not, this is part of a migration strategy that has been placed on hold for now.  But it looks about right.  I will come back to this in due course and it is still an issue, we can address it then.

**Comment by begoldsm** [comment]
@mmcc1 sounds good. Until then I am going to consider this issue closed since we have been unable to reproduce it on our side during this time. If you end up being able to reproduce it when you come back, please re-open the issue. Thanks!
