### ISSUE TITLE
ApiVersion in management client not initialized to the current version in Generated Code for StorageCache

### ISSUE THREAD

**Issue by brpanask** [Azure/azure-sdk-for-net#20444]
**Describe the bug**
The ApiVersion property is not getting initialized in the Generated ManagementClient Initialize function like it is in other management clients.

I recently had this update merged for updates to StorageCache.  Our test team had an bug for the previous version as well that noted that the ApiVersion had to be explicitly set.  This was due to the generated code not having an ApiVersion = "2021-03-01"; line in the initialize function in the management client class.

https://github.com/Azure/azure-sdk-for-net/pull/19447

Adding @markcowl, since we discussed it in the .net sdk office hours on 4/14/21.

**Comment by markcowl** [comment]
Per the offline discussion, this is due to the standard c-sharp generator configuration for management clients not being picked up when generating this RP.  This has a number of effects, including the default exception type, license headers in the source code, and differences in LRO execution. To fix all these issues, you would need to update the swagger configuration to turn azure-arm on, and this would result in a number of breaking changes in your library.


Since this appears to be a longstanding problem, and we have track 2 SDKs coming next semester, my advice is to not make this breaking change at this point, but wait for the track 2 SDKs, which will be entirely new packages.

**Comment by markcowl** [comment]
@brpanask let me know if you would like to pursue the management library changes.  I think this would require a substantial testing effort, and definitely involves a substantial set of breaking changes, and all of this will be fixed in track 2 management sdk in a few months, which is why I am advising against it.

**Comment by brpanask** [comment]
I think we can close this then.
I will publish the nuget package as is.

Do I still need to update the readmes for .net for the track 2 update?

**Comment by brpanask** [comment]
Closing since the issue is in our rest api readme.
