### ISSUE TITLE
[BUG] QueueProcessorOptions.Options.BatchSize Not Respected In QueueTrigger. 5.0.0-beta.3

### ISSUE THREAD

**Issue by steventmayer** [Azure/azure-sdk-for-net#20455]
**Describe the bug**
I have created a custom IQueueProcessorFactory in which the .Options.BatchSize doesn't seem to be respected and it's grabbed all of the messages it is able to.

**Expected behavior**
It grabs up to Options.BatchSize for the respective queue.

**Actual behavior (include Exception or Stack Trace)**
It is grabbing all of the messages it is able to.

**To Reproduce**
Steps to reproduce the behavior (include a code snippet, screenshot, or any additional information that might help us reproduce the issue)

1. Create a custom IQueueProcessorFactory, and set the queueProcessorOptions.Options.BatchSize to a number less than 16 (4, in my case). 
2. Don't set the queue name so it'll affect all queues. Just turn a new CustomQueueProcessor that inherits from QueueProcessor (it's internal).
3. Put more messages than batch size in your queue
4. Run Your Azure Webjob with a QueueTrigger which has a function that is just wait 30 seconds.
5. You'll see more than X (batch size) messages grabbed.

**Environment:**
 - Microsoft.Azure.WebJobs.Extensions.Storage v.5.0.0-beta.3
 - Microsoft.Azure.WebJobs v3.0.27
 - Net Core 5
 - Visual Studio 2019 16.9.4

**Comment by kasobol-msft** [comment]
@steventmayer I could not repro this. Could you please share some code snippets of a function (or sample project zipped) where you're observing such behavior?

That's what I got:

![image](https://user-images.githubusercontent.com/61715331/115083823-d9337300-9ebc-11eb-9516-2c9fea6c795a.png)

**Comment by steventmayer** [comment]
@kasobol-msft I'll put together a project. In the meantime, you're correct you'll see that the 4 is grabbed, but if you watch network traffic (fiddler), you'll see it'll grab 4 more immediately after without waiting for the first 4 to complete.

![image](https://user-images.githubusercontent.com/22377780/115084604-03d1fb80-9ebe-11eb-9784-18571128d292.png)

This is shown using local emulator but same issue when using Azure Storage directly.

**Comment by kasobol-msft** [comment]
There's separate knob to tweak that behavior - [QueuesOptions.NewBatchThreshold](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.webjobs.host.queuesoptions.newbatchthreshold?view=azure-dotnet-preview#Microsoft_Azure_WebJobs_Host_QueuesOptions_NewBatchThreshold) . This is the [default](https://github.com/Azure/azure-sdk-for-net/blob/850df4dc21246f6d216e8ed472313b741a8362b7/sdk/storage/Microsoft.Azure.WebJobs.Extensions.Storage.Common/src/Shared/Queues/QueuesOptions.cs#L82). So setting batch size to 4 might be low enough to trigger immediate fetch of next batch.

**Comment by steventmayer** [comment]
Thanks for that information. From my perspective, I am expecting the BatchSize to be limiter on how many messages are handled at once (in this case, handle 4 until they are done, then get new batch, even if it's pregrabbed using one of the other settings).

Repo: https://github.com/steventmayer/AzureStorageBatchIgnore

Here is my running of the repo with 8 messages:
![image](https://user-images.githubusercontent.com/22377780/115086723-ab046200-9ec1-11eb-9477-8862e555884d.png)

**Comment by kasobol-msft** [comment]
Thank you. Please disregard second part of my previous comment (I keep confusing it every time I revisit this topic). There has been also confusion about this topic in the past ([here](https://github.com/Azure/azure-webjobs-sdk/issues/628)). 

Both `BatchSize` and `NewBatchThreshold` drive how many messages can be processed concurrently. This covers two aspects of the problem:
- we want to keep the process occupied if messages are keep coming, so that it doesn't stop from time to time and just waits for more to be pulled from queue service, so we'd like to request more before current work stops. (this is useful if worker can burn down messages fast)
- we'd like to have control how much extra messages are pulled so we don't just poll them and wait too much before processing them (if burning a single message takes long this might be useful).

So:
- `BatchSize` corresponds directly to `numofmessages` in [the REST API call](https://docs.microsoft.com/en-us/rest/api/storageservices/get-messages) when Function host requests more messages to burn down.
- `NewBatchThreshold` tells function host to request more if number of messages in flight (not yet processed) false below that.
- Maximum number of messages processed by function host is `BatchSize` + `NewBatchThreshold`
- If system is under load then number of messages in flight would more-less oscillate between `NewBatchThreshold` and `BatchSize` + `NewBatchThreshold` (may fall below `NewBatchThreshold` a bit of course).

I hope this help clarify how this works and we'd take action to improve documentation for these two settings.

On the side note. 
I just noticed that we feed `IQueueProcessorFactory` the `QueuesOptions` that were read from app config/defaults. So updating properties on them may affect other queue processors (if desire was different settings per processor). The workaround would be to make a copy (or fresh instance) of `QueueProcessorOptions` instead of mutating it. We'll take a look at fixing it.
