### ISSUE TITLE
[QUERY] missing <owners> in nuspec file (e.g. Azure.Core.nuspec, Microsoft.Azure.Amqp.nuspec)

### ISSUE THREAD

**Issue by ruiminwang** [Azure/azure-sdk-for-net#20464]
**Query/Question**
Why remove <owners> from nuspec files such as `Azure.Core.nuspec` and  `Microsoft.Azure.Amqp.nuspec`?

There's `<owners>Microsoft</owners>` in Azure.Core.1.6.0 https://www.fuget.org/packages/Azure.Core/1.6.0
But it was removed since Azure.Core.1.6.0 and not exist in later versions

The same case for Microsoft.Azure.Amqp since version 2.4.6.

Because we used <owners> property to do the LCA check. when we upgrade the versions of the packages, the LCA check failed and block the build and release. We could change the logic of LCA check, but I'm still wondering why can't we just keep compatibility with the previous versions.

**Comment by jsquire** [comment]
@weshaggard:  Do you mind offering your thoughts?

**Comment by jsquire** [comment]
Hi @ruiminwang.   Thank you for your feedback.  The `Microsoft.Azure.Amqp` library is an external dependency some of the Azure SDK libraries in package form; it is maintained by the Azure Messaging team in a dedicated [repository](https://github.com/Azure/azure-amqp).   You may wish to open in issue there as well.

**Comment by weshaggard** [comment]
@ruiminwang thanks for bringing this issue to our attention, I didn't realize this had changed. When we updated to the latest .NET 5.0 tools the nuget team has decided to remove the owner tag from the nuspec. You can read more about it at https://github.com/NuGet/Home/issues/5134. I don't think there is anything we can do ourselves to add it back. I'd suggest you start using the author tag instead of the owner tag.

**Comment by ruiminwang** [comment]
Thanks for the reply~
