### ISSUE TITLE
[BUG] In Microsoft.Azure.EventHubs.EventDataBatch TryAdd method adds first event data even if it has a size greater then the limit

### ISSUE THREAD

**Issue by orlov11111** [Azure/azure-sdk-for-net#20615]
**Describe the bug**
In Microsoft.Azure.EventHubs.EventDataBatch TryAdd method adds first event data even if it has a size greater then the limit.

**Expected behaviour**
TryAdd returns false if the size of the passed event is greater then the limit.

**Actual behaviour (include Exception or Stack Trace)**
TryAdd returns true if the size of the passed event is greater then the limit.

**To Reproduce**

1. Create a EventDataBatch and set the limit (e.g. 1,048,576)
2. Create a EventData with the size greater then the limit (e.g. 1,048,577)
3. Use TryAdd method to check if this EventData can be added to the batch

**Environment:**
 - Assembly Microsoft.Azure.EventHubs, Version=4.3.1.0,

**Investigation**
Looking into the code of Microsoft.Azure.EventHubs.EventDataBatch, there is a check  **this.eventDataList.Count > 0** that seems causes this issue
```
        public bool TryAdd(EventData eventData)
        {
            Guard.ArgumentNotNull(nameof(eventData), eventData);

            this.ThrowIfDisposed();
            long size = GetEventSizeForBatch(eventData);
            if (this.eventDataList.Count > 0 && this.currentSize + size > this.maxSize)
            {
                return false;
            }

            this.eventDataList.Add(eventData);
            this.currentSize += size;

            return true;
        }
```

**Comment by jsquire** [comment]
Hi @orlov11111.  Thank you for reaching out and we regret that you're experiencing difficulties.  Unfortunately, this was confirmed as expected behavior for the legacy Event Hubs library in #18571.   From that issue:

>  Count check is by design. EventDataBatch allows adding first message to the batch regardless of message size. When check removed, 1MB max message support will be broken and first batch won't be able to send messages larger than 256KB.

We would recommend that you consider migrating to [`Azure.Messaging.EventHubs`](https://www.nuget.org/packages/Azure.Messaging.EventHubs/) library.  The `EventDataBatch` in `Azure.Messaging.EventHubs` will enforce the correct size limit for the batch.   

`Azure.Messaging.EventHubs` is the current generation Azure SDK package for Event Hubs, meant to supersede the legacy `Microsoft.Azure.Messaging` package.  For more information and a side-by-side usage comparison, you may wish to refer to the [migration guide](https://aka.ms/azsdk/net/migrate/eh) for more information.

**Comment by jsquire** [comment]
I'm going to close this out;  please feel free to reopen if you believe that further discussion would be helpful.
