### ISSUE TITLE
How to get RBAC roles of a Subscription using SDK

### ISSUE THREAD

**Issue by sunilprabha** [Azure/azure-sdk-for-net#20716]
i am able to get the role defnitions  like owner role name,roleID  and i am tying to find a method or class to list all users in the rbac roles of the subscription . Any pointer is appreciated. 

Regards
SP
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ad130f0b-f0af-66b2-b017-bf3d34af3f14
* Version Independent ID: 88f389bb-7a47-0f99-35e0-46f4b69cdf5a
* Content: [RoleAssignmentsImpl.GetById(String) Method (Microsoft.Azure.Management.Graph.RBAC.Fluent) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.management.graph.rbac.fluent.roleassignmentsimpl.getbyid?view=azure-dotnet#Microsoft_Azure_Management_Graph_RBAC_Fluent_RoleAssignmentsImpl_GetById_System_String_)
* Content Source: [xml/Microsoft.Azure.Management.Graph.RBAC.Fluent/RoleAssignmentsImpl.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.Management.Graph.RBAC.Fluent/RoleAssignmentsImpl.xml)
* Service: **role-based-access-control**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by markcowl** [comment]
@sunilprabha To do this, you need to combine together 2 service SDKs.  The Resource Manager 'Authorization' api has all of the details around role assignments in a subscription - role definition ids, user ids (as guids), etc.  (list api here: https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/authorization/Microsoft.Azure.Management.Authorization/src/Generated/RoleAssignmentsOperationsExtensions.cs#L421 in the Microsoft.Azure.Management.Authorization nuget package) .  Once you have this data, you will need to look up the role definition based on the id in the assignments, using this API: https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/authorization/Microsoft.Azure.Management.Authorization/src/Generated/RoleDefinitionsOperationsExtensions.cs#L163

And you will need to use the graph library (either MSGraph or AD Graph) if you want to look up the user ids to get good, human readable principal names (.e. user@contoso.com instead of xxxx-yyyyyyy-zzzz-zzzzz): https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/graphrbac/Microsoft.Azure.Graph.RBAC/src/Generated/UsersOperationsExtensions.cs#L104 (from the Microsoft.Azure.Graph.RBAC library in nuget]

You can see a sample of how this works together in this PowerShell cmdlet: https://github.com/Azure/azure-powershell/blob/d37075984b0152b44c838c3b633aeedbbb30c5fd/src/Resources/Resources/Models.Authorization/AuthorizationClient.cs#L210

**Comment by markcowl** [comment]
Closing as answered, please let us know if you have any additional questions
