### ISSUE TITLE
SetMetadataAsync deletes encryptiondata Key Wrapping Metadata Item

### ISSUE THREAD

**Issue by simps7b2** [Azure/azure-sdk-for-net#20737]
When migrating to the new v12 Azure.Storage libraries I noticed that if you call SetMetadataAsync on a blob uploaded with encryption options it will wipe out the system generated meta data item "encryptiondata". This renders the blob useless for all eternity as the key is now lost. I think this is a bug, because the docs say that SetMetadata is used to set "custom" properties, of which encryptiondata is not one.

In my use case I was creating the blob, uploading to it, and then setting the meta data all at once and was using all the async operations. I have not tested other variations, such as updating the meta data at a later date with a separate BlobClient object.

This issue can be worked around by manually copying all metadata retrieved from BlobClient.GetProperties().Value.Metadata into whatever dictionary is used to set the meta.

**Comment by amnguye** [comment]
Please see the Set Blob Metadata document for details on how this API operates.
https://docs.microsoft.com/en-us/rest/api/storageservices/set-blob-metadata

It is by design that "each call to this operation replaces all existing metadata attached to the blob".
![image](https://user-images.githubusercontent.com/48961492/116744764-98088c00-a9af-11eb-89cf-4becca68fa23.png)

**Comment by simps7b2** [comment]
I am converting up from v9 of the storage libraries (not the REST endpoint), and they did not behave this way. The encryption data was stored in the meta-data, but it is not wiped out by a call to set the meta data. If you're going to retain this behavior you could at least post about it here: [https://docs.microsoft.com/en-us/azure/storage/blobs/storage-encrypt-decrypt-blobs-key-vault?tabs=dotnet](Tutorial - Encrypt and Decrypt Blob), when y'all get around to actually creating code samples for the v12 libraries. Even if this is the designed behavior, it's pretty dumb to override system generated meta-data when setting user-defined meta-data. The least you could do is create a non-destructive set meta data call.

**Comment by amnguye** [comment]
Just for clarificiation all versions of the storage library call the REST endpoint. I don't know the exact behavior of v9, however I don't believe the API would have a huge breaking change as to go from updating the metadata of a blob to removing the metadata of a blob. Unless the v9 SDK made two requests, one to get the metadata of the existing blob and then a second one to update the metadata of the blob (which is also hard to believe).

@camsoper @tamram This customer is asking about updating code samples in this specific document could you comment on it?

The SDK simply implements what the service supports.

**Comment by simps7b2** [comment]
After looking at the v9 code closely, what was done was to call ICloudBlob.Metadata.Add repeatedly and then ICloudBlob.SetMetadataAsync so that it was non-destructive. The v12 SDK lacks any way to set the metadata non-destructively, and the blob encryption documentation is also silent on the issue that calling SetMetadata will brick an encrypted blob.

**Comment by jaschrep-msft** [comment]
@simps7b2 v12 explicitly avoids storing state like that as it takes very few false moves to get out of sync with the service and start corrupting metadata, and it's impossible to prevent in a multi-user scenario without automatically leasing every operation (expensive). Instead of luring developers into safety/complacency, it forces you to think about this before it's too late, while allowing you to adopt the solution best suited to your application.

This of course requires very good documentation, and we're happy to improve it where possible. I see you explicitly call out our clientside encryption documentation, but we do call that out very early in a bright warning box on [our main page for clientside encryption](https://docs.microsoft.com/en-us/azure/storage/common/storage-client-side-encryption?tabs=dotnet#blobs), which is generally the first result people find. The tutorial page you point to also recommends you visit said page multiple times. So I'm not exactly sure what you're looking for in that regard.

We have logged work to go over our method docstrings and v12 migration guide to ensure clarity.
