### ISSUE TITLE
[QUERY] Event Hubs. Partition Keys, Event Batching and Load Balancing

### ISSUE THREAD

**Issue by hellooperatorpatchmethrough** [Azure/azure-sdk-for-net#20815]
By sending out event batches with `partitionId` assigned, I suspect, it can get into the situations where the load is not distributed evenly across all of the partitions. What if the batches were sent out with `partitionKey` set instead of the `partitionId` and let's say there are 12 different `partitionKey` values possible and 6 partitions available. Would this lead to a more evenly balanced load i.e. 2 keys per 1 partition?
I was not able to find any documentation on what happens when there are more keys than partitions, if there is any load balancing under the hood.

Thanks!

**Comment by jsquire** [comment]
//cc: @serkantkaraca, @JamesBirdsall, @sjkwak

**Comment by jsquire** [comment]
Hi @hellooperatorpatchmethrough.  The Event Hubs service controls the behavior of partition assignment when a partition key is used.   I've looped in the service team for their insight.

**Comment by JamesBirdsall** [comment]
If an application sends directly to partitions, then it has taken over responsibility for balancing -- the service cannot apply any balancing behavior because that would defeat the application's explicit request to put certain messages in certain partitions.

With partition keys, the key string is hashed to produce a partition id. The exact balancing depends how the strings used interact with the particular hash function.

All of this only matters if particular groups of messages must be processed by the same consumer instance. Each consumer instance is by nature attached to a particular partition, so putting related messages in the same partition (either by explicit send or by putting the same partition key on all of them) ensures that they all go to the same consumer instance. If you don't need that, then you don't need a partition sender or partition keys -- you can let the service round-robin the messages for best balancing.

**Comment by hellooperatorpatchmethrough** [comment]
@JamesBirdsall 
Thanks, that does answer the question.
I am going to implement clustering using partitions and the cluster key directly will map to the partition key.
