### ISSUE TITLE
Better documentation for WebKeyTypes

### ISSUE THREAD

**Issue by ppittle** [Azure/azure-sdk-for-net#2086]
Issue is based on Stack Overflow Post: [What are the valid list of WebKeyTypes for Azure Key Vault API](http://stackoverflow.com/q/37805535/1224069)

Documentation for [KeyVaultClient.CreateKeyAsync](https://msdn.microsoft.com/en-us/library/azure/dn891724.aspx) `keyType` Property should be improved to indicate values are stored in `JsonWebKeyType`.  (This is the only place I could find 'valid' values but please update if there are more).

Would it be possible to change `WebKeyType` to an enum:

    public enum WebKeyType
    {
        EllipticCurve = "EC";
        Rsa = "RSA";
        RsaHsm = "RSA-HSM";
        Octet = "oct";    
    }

And then update `CreateKeyAsync`:

     public Task<KeyBundle> CreateKeyAsync (
    	    string vaultAddress,
	    WebKeyType keyType,
     	    KeyAttributes keyAttributes)

**Comment by pomortaz** [comment]
@ppittle we added more [documentations](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/src/KeyVault/Microsoft.Azure.KeyVault/Generated/KeyVaultClientExtensions.cs#L39-L41). However, we kept the keyType's type as string instead of enum to allow setting new key types when they are introduced without code change and avoid unnecessary breaking changes.
