### ISSUE TITLE
[QUERY/Feature Request] Determining payload size on EventDataBatch before adding to batch.

### ISSUE THREAD

**Issue by hellooperatorpatchmethrough** [Azure/azure-sdk-for-net#21101]
I am wondering if there is an API to determine the payload size on the [EventDataBatch](https://docs.microsoft.com/en-us/dotnet/api/azure.messaging.eventhubs.producer.eventdatabatch?view=azure-dotnet).
We have noticed so far that there is some 16byte overhead per each message added meaning that the `byte[].Length` property cannot be used to determine the payload size on batch.

Are there any other peculiarities that should be taken into account besides the 16 byte overhead? If that is that, this is something that we could consider hardcoding at the moment. 

 The reason why I'd like to know the size in bytes on the batch beforehand is that I am consuming messages from a message queue and a single queue message contains multiple events. In order to prevent any data loss all events must fit onto the batch and reach the hub safe and sound before popping the message of the queue. For that I need to know the size of an event on batch before adding it to the batch as there is no api to remove events of the batch.

p.s. not sure what is the API design process, but as far as the code is concerned I could raise a PR with a couple of hints from you guys on where to look at.

**Comment by jsquire** [comment]
Hi @hellooperatorpatchmethrough.  Thank you for reaching out and we regret that you're experiencing difficulties.  There is not currently a way to premeasure an event before adding to the batch.   There's a few parts to your inquiry, and I'm going to split into multiple responses to try and keep from throwing too large a wall of text at once.

> Are there any other peculiarities that should be taken into account besides the 16 byte overhead? If that is that, this is something that we could consider hardcoding at the moment.

I would advise against assuming that your application can accurately measure the size of an event.  The overhead that you're seeing is not a constant guarantee and may change depending on the content of your event, the properties of your Event Hubs namespace and Event Hub instance, and implementation details of the protocol.

- To accurately determine the size of an event, it must be measured in the format used by the active protocol as well as account for overhead of the batch envelope that will contain it.  Even were there a trustworthy `sizeof` equivalent in .NET to measure the model, it wouldn't be an accurate representation.  Best case, you'd end up wasting space because you'd have to reserve overhead padding defensively.  Worst, you'd end up with a miscalculation that causes publishing to fail.  

- The size limit for communication is not a property of the Event Hub, it is a property of the communications channel for the active protocol at the entity level.  This means that the service could choose to specify a different value for individual partitions of an Event Hub or for the gateway used for automatic routing and servicing of partition keys.   Pragmatically, this isn't how the service operates today, but the client cannot make that assumption and neither should an application. 

- Communication channels are ephemeral to a certain extent, where the client will potentially be opening, closing, and recreating links to the service to provide a stable and resilient experience for callers that doesn't waste resources.  As the service controls the size, any point where a new link is opened, the maximum size allowed for it may differ.   Here again, this isn't likely, but it is possible and so the client cannot make assumptions. 

- The reason that `EventDataBatch` exists is to provide a deterministic and accurate means to measure the size of a message sent to the service in the context of a single operation, minimizing the chance of failure.  Because the batch is created in the context of a link to the service, the size limit is the most accurate available.  It is still possible for that value to change and a batch be rejected, but it is as close to per-request validation as possible.

**Comment by jsquire** [comment]
> The reason why I'd like to know the size in bytes on the batch beforehand is that I am consuming messages from a message queue and a single queue message contains multiple events. In order to prevent any data loss all events must fit onto the batch and reach the hub safe and sound before popping the message of the queue. For that I need to know the size of an event on batch before adding it to the batch as there is no api to remove events of the batch.

I'd like to understand a bit more about the scenario, if you're willing.   

- Are you using a Peek/Lock approach to reading the queue?

- Assuming yes, if you peek a message and attempt to add it to the batch but it does not fit, is there a reason why you wouldn't be able to just abort the read?  You don't mention a specific queue, but most will allow you to abandon the lock without removing the message.  

- What happens if you form an event batch and publishing is unsuccessful today?  I'm assuming that you complete the queue read upon successful publishing of a batch.  On failure, I'm assuming that you're doing something today that allows you to retry in a safe manner.   I'm curious why you wouldn't apply this same technique to a message that you attempt to add to a full batch.

**Comment by jsquire** [comment]
> p.s. not sure what is the API design process, but as far as the code is concerned I could raise a PR with a couple of hints from you guys on where to look at.

There's an involved process for changes to the public API that requires championing the proposed change across the different languages for an SDK as well as getting approval from a central architecture board.  While we very much appreciate contributions, we'd probably want to wait until we know this is something that we'd be able to move forward on.

The first step for doing so ties in with my previous response.  The more that I understand the scenario, the better I can make a case for consideration of a new API if there's no better approach that exists today.

**Comment by hellooperatorpatchmethrough** [comment]
@jsquire 

Thank you for a such detailed response. 

We are ongoing a modernization process in the organization and first and foremost we are upgrading our content delivery channels. To do so we are reading the intermediate data product produced by services that communicate via the good old MSMQ. MSMQ is being read by what we can call an event producer. MSMQ messages contain multiple events in a collection and these messages share the same metadata set. We expand the collection into multiple messages so we could cluster them to different partitions so the events that correspond to a same entity would be stored on a single partition. This allows us to scale out horizontally within a single process as the event consumer application mostly waits for IO to complete - data batch insertion on the data vault.

The MSMQ is being read in a single threaded context, there is no other process that has access to that queue. Messages are being peeked; message contents are received without popping the message of the queue. This is done up to the event batch size limit. Once the limit is reached, the event data batch is sent to the hub and after it was successfully sent out, a number of messages is dequeued at once. You can say it is done in "all or nothing" manner. This is all done using the MSMQ cursors. 

Well to be honest, this is not something that we have implemented yet but this is in our plans once we resolve how to determine the message size beforehand placing it on the event data batch. 

> Assuming yes, if you peek a message and attempt to add it to the batch but it does not fit, is there a reason why you wouldn't be able to just abort the read? You don't mention a specific queue, but most will allow you to abandon the lock without removing the message.

This is worth to consider. At worst, you'd be delivering a bunch of messages twice. Hell, as the event hub is a "guaranteed delivery at least once" ingestion service, the mechanisms that deal with duplicates are already there. 

...

From your response it is clear that it would be naive to attempt to capture the event size determination algorithm as there are too many things at play. We do not have such great need to publish events as optimally as possible because the bottleneck in our pipeline is storing data on the data vault. This means that slashing the batch size defensively by let's say 10% could result in a better performance than producing more duplicates which would lead to more wasted IO.

**Comment by jsquire** [comment]
Apologies for the lack of feedback.  We've been discussing potential approaches internally to see if there was some form of premeasurement that we could expose that felt like it wouldn't crowd the public API surface or cause confusion around the recommended publishing patterns for those without your scenario.  Unfortunately, the decision at this point is that your scenario is unique enough that it there isn't justification for expanding the public API.

Since it seems that you had some thoughts on ways to work around this within the application and we've reached a conclusion on potential client changes,  I'm going to tag this as being addressed.  Please feel free to "`/unresolve`" if you'd like to continue discussion.
