### ISSUE TITLE
Not able to create a mock/object of Azure.Containers.ContainerRegistry.TagProperties

### ISSUE THREAD

**Issue by amit-avit** [Azure/azure-sdk-for-net#21105]
Hi,

I'm not able to create a mock/dummy object of `Azure.Containers.ContainerRegistry.TagProperties`.
I actually want to return a mocked object for a call to `ContainerRepositoryClient.GetTagsAsync`.
Below is the code snippet should give idea what I'm trying to do:
```C#
var tagProperty22 = Substitute.For<TagProperties>();
tagProperty22.Repository.Returns<string>("dummyRepo");
tagProperty22.Name.Returns<string>("22");
tagProperty22.Digest.Returns<string>("dummySha");

var tagPropertyLatest = Substitute.For<TagProperties>();
tagPropertyLatest.Repository.Returns<string>("dummyRepo");
tagPropertyLatest.Name.Returns<string>("latest");
tagPropertyLatest.Digest.Returns<string>("dummySha");

var asyncPageableResponse = AsyncPageable<TagProperties>.FromPages(new Page<TagProperties>[] { Page<TagProperties>.FromValues(new TagProperties[] { tagProperty22, tagPropertyLatest }, null, Substitute.For<Response>()) });
_containerRepositoryClient.GetTagsAsync(Arg.Any<GetTagsOptions>()).Returns<AsyncPageable<TagProperties>>(asyncPageableResponse);
```

Please help by providing the info as to how this could be done or in case there is other way to test it out. I've also tried creating an object for TagProperties using JsonSerializer.Deserialize but that also did not work out.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 044e9d4f-5f75-5dcb-b844-a28ee5857183
* Version Independent ID: 72cca95c-27d2-2614-c534-9e1549506644
* Content: [ArtifactTagProperties Class (Azure.Containers.ContainerRegistry) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/azure.containers.containerregistry.artifacttagproperties?view=azure-dotnet-preview)
* Content Source: [xml/Azure.Containers.ContainerRegistry/ArtifactTagProperties.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Azure.Containers.ContainerRegistry/ArtifactTagProperties.xml)
* Service: **azure**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by annelo-msft** [comment]
Hi @amit-avit!  Our [Azure SDK .NET Guidelines on mocking](https://azure.github.io/azure-sdk/dotnet_introduction.html#dotnet-mocking) describe how we support mocking in Azure SDK libraries -- feel free to follow up if you have questions after reviewing this.  

That being said, the ACR Beta 2 library does not currently provide [the factory for constructing model types](https://azure.github.io/azure-sdk/dotnet_introduction.html#dotnet-mocking-factory-builder) that the guidelines describe because it is still an early beta.  I've created [this issue](https://github.com/Azure/azure-sdk-for-net/issues/21144) to track adding this type.

**Comment by annelo-msft** [comment]
Tracking addition of requested feature with https://github.com/Azure/azure-sdk-for-net/issues/21144
