### ISSUE TITLE
[FEATURE REQ] Allow to specify DateTime format for SAS tokens

### ISSUE THREAD

**Issue by austeja-bentley** [Azure/azure-sdk-for-net#21182]
**Library or service name.**
Azure.Storage.Blobs

**Is your feature request related to a problem? Please describe.**
Currently BlobSasBuilder.ToSasQueryParameters method converts SAS token validity range dates using a hardcoded datetime format that includes time specified in hours, minutes and seconds. For our specific use case we need tokens that are more unique - one unique token per resource per second is not granular enough.

The documentation specifies up to 7 decimal digits for fractional seconds are supported: https://docs.microsoft.com/en-us/rest/api/storageservices/formatting-datetime-values
I have tried to form the token manually with a more granular date string and everything seems to work fine. We would of course prefer to use the client library to generate SAS tokens as it handles more edge cases and is updated.

Could the support for custom DateTime formats be added? Or would it at least be something that would be accepted as a contribution in a pull request for this package?

That being said, are there maybe plans to allow the user to specify some custom property that would get hashed into SAS signature and then verified upon resource access along with the rest of the properties? That would fit our use case better but sounds like more of an edge case and would also require more effort to implement.

**Comment by amnguye** [comment]
Hi,

What are you attempting to solve with creating a SAS with fractional seconds, where you would need a SAS to start or expire at the fraction of a second? If you're looking for having a SAS to be later verified, have you looked into using AAD?

**Comment by austeja-bentley** [comment]
Maybe I was not clear enough, but we now use more granular time not because we need the token to start being valid or expire at a very specific time, but we need them to be unique. Seven decimal second places in timestamps pretty much guarantees (with edge cases of course) that whenever we generate a token (even if we do that in a loop consecutively for the same resource) it will be unique.

Using granular time is the only way we found to make the tokens unique. That's why I mentioned another possibility of allowing users to add custom information in SAS hash, for our use case we could possibly add a unique identifier and then the tokens would be guaranteed to be unique, but this sounds like a lot of effort. Allowing to specify the DateTime format used for SAS hash generation would be a lower effort change.

**Comment by kasobol-msft** [comment]
@austeja-bentley  Could you elaborate more about why do you need them to be unique?

**Comment by austeja-bentley** [comment]
We are attempting to collect telemetry and we need to correlate blob storage logs with user identifier and other metadata. We use SAS hash as the common property that we get from both Azure storage logs and from our application side. This is why uniqueness is important - we do not want to have multiple users using identical tokens with the same SAS hash as then we cannot determine which storage log belongs to who.

**Comment by amnguye** [comment]
Have you looked into User Delegation SAS?
https://docs.microsoft.com/en-us/rest/api/storageservices/create-user-delegation-sas
https://docs.microsoft.com/en-us/azure/storage/blobs/storage-blob-user-delegation-sas-create-dotnet

It can secure and sign the SAS with the Azure AD credentials of the user. You can assign the AAD credentials access to the storage account, and then use those credentials to get the User Delegation Key, then use the key to sign the SAS.

This would be a more secure option because not only would you know which user was uploading which logs, but also it's the more recommended and less easily compromised.

**Comment by austeja-bentley** [comment]
The correlation id parameter looks great, unfortunately with the current authentication infrastructure that we use we are not really able to leverage Azure AD capabilities. I will double check with other teams if we could somehow apply this solution but it is not likely

**Comment by amnguye** [comment]
The user delegation key is analogous to the account key used to sign a service SAS or an account SAS, except that it relies on your Azure AD credentials. So instead of signing the SAS with your account key, we sign it with the user delegation key. So in short, yes the token operates the same way, it grands access to the container and/or blobs.
