### ISSUE TITLE
[Inquiry] .NET Framework 4.8 compatibility

### ISSUE THREAD

**Issue by argelj289** [Azure/azure-sdk-for-net#21216]
I just want to inquire about this new replacement library for Microsoft.Azure.Keyvault library if this is .NET 4.8 and above compatible?

because I only see in the nuget description that its depency on .NET is for .NETStandard version 2.0

![image](https://user-images.githubusercontent.com/40298377/118907498-31ddac00-b952-11eb-9085-0fd5a2365260.png)

**Comment by johanbenschop** [comment]
.NET Standard is a bit like an interface for the .NET Framework. .NETStandard 2.0 is compatible with .NET Framework 4.6.1 and above (and .NET Core 2.0 and above). See https://docs.microsoft.com/en-us/dotnet/standard/net-standard for more information.

**Comment by jsquire** [comment]
Hi @argelj289.  Thank you for reaching out.  As @johanbenschop was kind enough to mention, .NET Standard 2.0 supports a range of .NET implementations including the .NET Framework 4.8.    The link shared above is official documentation for target platforms should you be interested in more context.

The Azure SDKs are tested nightly against multiple target frameworks, including the .NET Framework v4.6.1,  .NET Core 2.1, and .NET 5.   Running on the .NET Framework 4.8 should work just fine.   Since we've got a definitive answer to your question, I'm going to close this out;  please feel free to reopen if you'd like to discuss further.
