### ISSUE TITLE
Consider not throwing for completed but unsuccessful long-running operations

### ISSUE THREAD

**Issue by pakrym** [Azure/azure-sdk-for-net#21312]
https://github.com/Azure/autorest.csharp/issues/464

From @heaths :

>FWIW, Krzysztof asked that we not throw during UpdateStatus for supported status codes (e.g. 200, 202, 404) and similar calls - only when getting a value (similar to Nullable). I believe Pavel was part of this discussion as well. As a result - with oversight from Krzysztof, the Key Vault pseudo-LROs are what Krzysztof wanted: https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/keyvault/Azure.Security.KeyVault.Keys/src/DeleteKeyOperation.cs

**Comment by pakrym** [comment]
@kinelski pointed out that this would be against our current guidelines.

cc @christothes who worked on https://github.com/Azure/azure-sdk/pull/2003

**Comment by heaths** [comment]
When I implemented the LROs for Key Vault (real and pseudo-LROs) back in 2019, @KrzysztofCwalina recommended we throw from `Value` much like `Nullable<T>.Value`. If recommendations have changed, please ignore my comment.

**Comment by pakrym** [comment]
No, I think you were right. The `Value` should throw but I don't think the `UpdateStatus` should.

**Comment by annelo-msft** [comment]
@tg-msft: it would be good to scope this to DPG libraries; consider pointing customers to RequestContext to control error experience.

**Comment by pallavit** [comment]
Do we see us doing this for exsiting HLCs? For DPG and newer light-up APIs we already have a means to achieve this behavior albeit as an advanced scenario. 

Do we see us changing this to mainstream scenario however?
/cc: @annelo-msft

**Comment by annelo-msft** [comment]
@pallavit: @JoshLove-msft is driving this investigation and can make a recommendation based on his findings once available.

**Comment by pallavit** [comment]
@JoshLove-msft could you please share your current thinking here?

**Comment by JoshLove-msft** [comment]
The scope of my investigation was to determine whether or not the current shared source implementation actually aligns with the current guidelines and whether the guidelines may need updating to reflect the behavior.

The guidelines say that [UpdateStatus should throw if the operation completed with a failed result](https://azure.github.io/azure-sdk/dotnet_implementation.html#dotnet-lro-return). They also state that accessing the Operation `Value` property should rethrow the same exception for failed operations:

```If the Value property is evaluated after the operation failed (HasValue is false and HasCompleted is true) throw the same exception as the one thrown when the operation failed.```

The shared source implementation [throws on failed results in UpdateStatus](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/core/Azure.Core/src/Shared/OperationInternalOfT.cs#L262-L265). It also throws the same exception when accessing [`Value`](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/core/Azure.Core/src/Shared/OperationInternalOfT.cs#L154).

So our official guidance in the implementation guidelines matches up with the Azure.Core shared source implementation.

The problem is that many LRO's created before the Azure.Core shared source implementation, such as [Key Vault's ](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/keyvault/Azure.Security.KeyVault.Keys/src/DeleteKeyOperation.cs), did the implementation themselves and do not follow the guidelines of throwing on a failed result from `UpdateStatus`. Changing this behavior from not throwing to throwing is a breaking change. I would recommend that these be left as is. 

I do think there is room for improvement by adding a static analyzer. A simple analyzer could verify [these conditions](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/core/Azure.Core/src/Shared/OperationInternal.cs#L17-L19) for any `Operation` subtype. For existing LROs that don't follow the pattern the analyzer can be disabled on a case by case basis.

**Comment by pallavit** [comment]
Thank you for sharing the details @JoshLove-msft 

> I do think there is room for improvement by adding a static analyzer. A simple analyzer could verify [these conditions](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/core/Azure.Core/src/Shared/OperationInternal.cs#L17-L19) for any Operation subtype. For existing LROs that don't follow the pattern the analyzer can be disabled on a case by case basis. We could either repurpose this issue to track the static analyzer work, or open a separate issue for that and close this issue. @pallavit, any preference there?

As for this, I think we should open a bug in azure-sdk-tools for static analyzer. I agree with you that older SDKs would likely not be updated due to breaking changes concerns however this may be valuable for net new SDKs branded as well as other 3rd party scenarios in future. Even though LROs is a azure specific concept it may be worth evaluating it for the new toolchain as well so having a static analyzer bug for this will be useful. I would suggest tagging that issue with System.ClientModel as well so we think this scenario from that perspective as well. Let me know what you think?

**Comment by JoshLove-msft** [comment]
Works for me - filed https://github.com/Azure/azure-sdk-for-net/issues/21312#issuecomment-1864920346.

**Comment by annelo-msft** [comment]
[like]  Anne Loomis Thompson reacted to your message:
________________________________
