### ISSUE TITLE
[Event Grid] MS Docs Navigation Pointing to the Wrong Version

### ISSUE THREAD

**Issue by kzu** [Azure/azure-sdk-for-net#21444]
The article shows installing a beta version of the package, but it's already stable.

Would be nice to allow direct PRs like other MS docs allow (i.e. dotnet/msbuild/etc.)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e236e89-a929-1c68-0dee-246b2a5b4a5f
* Version Independent ID: 99f80e40-5907-c1b4-4da2-24830f53d3ba
* Content: [Azure Event Grid client library for .NET - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/overview/azure/messaging.eventgrid-readme-pre)
* Content Source: [api/overview/azure/messaging.eventgrid-readme-pre.md](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/api/overview/azure/messaging.eventgrid-readme-pre.md)
* Service: **eventgrid**
* Product: **azure**
* Technology: **azure**
* GitHub Login: @maggiepint
* Microsoft Alias: **magpint**

**Comment by jsquire** [comment]
Hi @kzu.  Thank you for your feedback.   Tagging and routing to the team member best able to assist.

**Comment by jsquire** [comment]
@danieljurek:  The main navigation seems to still be pointing at the prerelease README.  Clicking here:

![image](https://user-images.githubusercontent.com/913445/120075498-87f7d100-c06f-11eb-9d69-90d720adbc1b.png)

Navigates to the [pre-release version](api/overview/azure/messaging.eventgrid-readme-pre.md)  (note the `-pre.md` ending of the URL) rather than the [release version](https://docs.microsoft.com/dotnet/api/overview/azure/messaging.eventgrid-readme) that I'd expect post-GA.   Do you have any insight as to why this may be?

**Comment by jongio** [comment]
I saw this today as well.

**Comment by kurtzeborn** [comment]
*If* this is still happening, this is an update that needs to be made to the service level readme for the SDK.  It also could be the package level overview page which also originates from .md files in our repos.

There's a whole bunch of things that could have addressed this.

**Comment by jsquire** [comment]
Closing this out; it looks like the current landing page is now correctly pointing to the GA content: 
https://learn.microsoft.com/dotnet/api/overview/azure/messaging.eventgrid-readme?view=azure-dotnet
