### ISSUE TITLE
Open Question: How do we handle AdditionalProperties in a forward compat safe way in C#

### ISSUE THREAD

**Issue by chamons** [Azure/azure-sdk-for-net#21483]
As part of https://github.com/Azure/autorest.csharp/issues/1232 it was decided to:

- Remove the `IDictionary` interface from generated models that have AdditionalProperties
- Make the AdditionalProperties public
- Punt other work to a future work item.

This is that 3rd item.

There are open questions on how to handle AdditionalProperties safely:

- What do you do when an AdditionalProperty is promoted to a known one?
- What is the source of truth for models that have these? A stored dictionary or the deserialized model?
- How do you handle V1 customers that got the AdditionalProperty dictionary and added fields when that is promoted to a model.

cc @pakrym @KrzysztofCwalina @johanste @AlexGhiondea  @tg-msft

**Comment by jsquire** [comment]
@m-nash:  Is this issue still relevant or can we close it?

**Comment by m-nash** [comment]
@ArcturusZhang can you verify that we don't inherit from IReadOnlyDictionary?  If we do can you give me some data on how many cases of this we have in the wild today?

**Comment by ArcturusZhang** [comment]
@m-nash as far as I know this is incorrect. The way described in the description is not the way we handle AdditionalProperties right now.
This is how we do for AdditionalProperties:
```csharp
public partial class ModelWithAdditionalProperties
{
public IDictionary<string, BinaryData> AddtionalProperties {get;}
// it changes to IReadOnlyDictionary when the model does not have the input usage
public IReadOnlyDictionary<string, BinaryData> AddtionalProperties {get;}
}
```
Instead I have concerns that we get breaking changes because there is a shift from IReadOnlyDictionary to IDictionary when the model gets a input usage when it previously does not.
But in general, we never let a model to implement the IReadOnlyDictionary interface or IDictionary interface.
In code model of modeler v4, it represents additional properties by setting the base model of this model is a dictionary, but we never implemented it in that way.

**Comment by pallavit** [comment]
@m-nash given your last comment here, I am going ahead and closing this issue. Please feel free to reopen if you feel otherwise.
