### ISSUE TITLE
[QUERY] To read and write blobs, what IAM role should a user have ?

### ISSUE THREAD

**Issue by TechWatching** [Azure/azure-sdk-for-net#21592]
**Query/Question**
When using the new Azure.Storage.Blobs SDK with DefaultAzureCredentials, I encountered some 403 errors for my Azure Ad account connected to Visual Studio. My account was Contributor on the ressource when errors occur, but as soon as I gave him the Storage Blob Data Contributor it worked.
So my understanding is that Storage Blob Data Contributor is necessary to read and write blobs in an azure storage with the SDK, am I right ? 

It surprised me a bit that Contributor role is not enought because with only my Contributor role I was able to read and write blobs through the Azure Storage Explorer desktop application as well as the Azure Portal. I am guessing that what the azure storage explorer does is to get access to the blobs by using the azure storage keys that can be retrieved on the behalf of my user., am I correct ?

**Environment:**
 - Name and version of the Library package used: Azure.Storage.Blobs 12.8.4
 - Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects):  Windows 10 .NET 5.0
 - IDE and version : Visual Studio 16.10.0

**Comment by amnguye** [comment]
How portal and storage explorer operate is that by default, it will grab the key information (if it has permissions) in order to access the storage account information and keys. It does this by calling the management plane API

The storage SDK does not call into the management plane API, only the data plane API, and will not grab your storage account information. So yes you would either have to grant your user at least Storage Blob Data Contributor rights or you would have to provide the keys yourself. If you don't want to grant your user those rights and want to leave it as a Contributor then I recommend calling into the [management storage SDK](https://www.nuget.org/packages/Microsoft.Azure.Management.Storage/) to grab the necessary key information.

**Comment by TechWatching** [comment]
Okay thank you for the explanation. It's clear now. I don't know if this is explicitely explained in documentation but if not I think it should be to avoid potential confusion. 

Indeed, when building an application (hosted on App Service or other Azure component) that queries an Azure Storage using Managed Identities, we often test the application locally using the account connected to Visual Studio / Vs Code / Azure CLI (azure default credentials) and it seems weird to have a forbidden exception while having no problem accessing the data through azure storage explorer with the same account.

Apart from that, I think this issue can be closed as my question has been answered, thanks.
