### ISSUE TITLE
Add custom converter for EventGridEvent

### ISSUE THREAD

**Issue by JoshLove-msft** [Azure/azure-sdk-for-net#21639]
CloudEvent has a custom System.Text.Json converter but users would need to rely on documentation to know this, and it doesn't support other serializers.

EventGridEvent doesn't have a custom converter so there is not an easy way to serialize to JSON (since the Data property is BinaryData which does not get serialized by JSON serializers).

Proposal:
Add Serialize/SerializeAsync methods to CloudEvent/EventGridEvent that have an optional ObjectSerializer parameter.
Add custom STJ converter to EventGridEvent.

**Comment by pakrym** [comment]
>EventGridEvent doesn't have a custom converter

Should we add it?

**Comment by JoshLove-msft** [comment]
> > EventGridEvent doesn't have a custom converter
> 
> Should we add it?

Yeah, we may as well for consistency sake.

**Comment by pakrym** [comment]
If we have the converter do we still need the serialize method?

**Comment by JoshLove-msft** [comment]
Technically, we don't _need_ any of this. The idea here is to make the serialization more discoverable (explicit method), and more flexible (ObjectSerializer support).

**Comment by pakrym** [comment]
We can already use `ObjectSerializer.Serialize(event)` for the `ObjectSerializer` support.

>Technically, we don't need any of this. The idea here is to make the serialization more discoverable (explicit method)

I slightly worry we would have a different set of serialize/deserialize methods on various classes across libraries. Might be a good time to think on some common names/patterns.

**Comment by JoshLove-msft** [comment]
> We can already use `ObjectSerializer.Serialize(event)` for the `ObjectSerializer` support.

Ah good point, I still think if we were to include a Serialize method, it should probably include the ObjectSerializer as a parameter for convenience. But this helps make narrow the scope to discoverability. 

> I slightly worry we would have a different set of serialize/deserialize methods on various classes across libraries. Might be a good time to think on some common names/patterns.

Yeah, that is fair, but I think Serialize is a pretty good name for this. 😆 
Also it is possible that we just need a better way to document what converters exist for a given type.

**Comment by tg-msft** [comment]
> I think Serialize is a pretty good name for this.

It's not a bad name, but don't we have other cases where we call things `ToJson` as well?

**Comment by JoshLove-msft** [comment]
Looks like we do - https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/formrecognizer/Azure.AI.FormRecognizer/src/CopyAuthorization.cs#L56

**Comment by JoshLove-msft** [comment]
I think ToJson is probably better. We can leave off ObjectSerializer parameter as an advanced use case that requires doing ObjectSerializer.Serialize.

**Comment by pakrym** [comment]
We also have WriteTo(Utf8JsonWriter) that's why I want to stop adding more until we take stock

**Comment by JoshLove-msft** [comment]
WriteTo seems like a low level API, whereas ToJson is high level. They don't seem to conflict - but taking stock of all the existing patterns sounds good.

**Comment by pakrym** [comment]
>They don't seem to conflict

True. But should CloudEvent maybe have WriteTo as well?

**Comment by JoshLove-msft** [comment]
> > They don't seem to conflict
> 
> True. But should CloudEvent maybe have WriteTo as well?

We could always add it in the future, but I am more concerned about the basic scenario of getting the JSON for an event and adding it to the HttpRequestContent.

**Comment by pakrym** [comment]
>We could always add it in the future, but I am more concerned about the basic scenario of getting the JSON for an event and adding it to the HttpRequestContent.

Then we start by adding the converter.
That way 

`content = RequestContent.Create(event); `

would just work

**Comment by jstensved** [comment]
This issue causes major issues with Azure Functions (dotnet-isolated). You can't use it as input which all public documentation on Azure Function say except for a sample in GitHub. I posted about this at stack overflow with a workaround for accepting EventGridEvent as input.

Official documentation (https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-event-grid-trigger?tabs=csharp%2Cbash) show how to use `EventGridEvent` as input but that will give you the following error:

`Cannot convert input parameter 'e' to type 'Azure.Messaging.EventGrid.EventGridEvent' from type 'System.String'.`


The template in Visual Studio even gives this kind of duck typing when creating an Azure Function from GUI which seems to indicate that this is some preferred way? The rest of the Microsoft SDKs generally "just work" with the provided types without having to crate a copy of a defined type with the same properties.

At least there could be an interface like `IEventGridEvent` to enforce the EventGrid schema if I choose to use that instead of CloudEvent or custom?
 
```

    public static class BugReport
    {
        [Function("BugReport")]
        public static void Run([EventGridTrigger] MyEvent input, FunctionContext context)
        {
            var logger = context.GetLogger("BugReport");
            logger.LogInformation(input.Data.ToString());
        }
    }

    public class MyEvent
    {
        public string Id { get; set; }

        public string Topic { get; set; }

        public string Subject { get; set; }

        public string EventType { get; set; }

        public DateTime EventTime { get; set; }

        public object Data { get; set; }
    }

```

I found this thread while troubleshooting why returning an EventGridEvent from an Azure Function with [EventGridOutput] always gives an empty Data property which seems to be due to serialization issues when the event is sent which makes it hard (impossible) to use without the duck typing above?

**Comment by JoshLove-msft** [comment]
@jstensved out of curiosity have you run into the same issue when using CloudEvent schema?
