### ISSUE TITLE
[QUERY] [Storage] How to get SecondaryUri of a blob in v12 API?

### ISSUE THREAD

**Issue by RetYn** [Azure/azure-sdk-for-net#21640]
Query/Question
With the v11 API we could use CloudBlob.StorageUri.SecondaryUri to retrieve a blob's secondaryUri. The new BlobClient only has the Uri property, but not StorageUri. 
How can  the SecondaryUri be retrieved from BlobClient ?

Environment:

Azure.Storage.Blobs 12.8.4
NET Core SDK 3.1.300, Windows 10 x64
Visual Studio 16.6.1

**Comment by RetYn** [comment]
same question as https://github.com/Azure/azure-sdk-for-net/issues/12413

**Comment by amnguye** [comment]
Are you asking on how to set the secondary tenant? This would be located in `BlobClientOptions.GeoRedundantSecondaryUri` or change out `BlobClientOptions` for the according service you are looking to use.

If you're looking for the SDK to assist the construction of the secondary tenant url or to grab any endpoint information, I recommend using the storage management SDK instead of the regular storage client information. As grabbing the endpoint information is on the management plane SDK. We no longer add the substring "-secondary" to the url due to the possibility of having a custom endpoint.

**Comment by RetYn** [comment]
Does any documents or key words to search about how to do that in storage management SDK?
