### ISSUE TITLE
[QUERY] Service Bus Transaction Difficulties

### ISSUE THREAD

**Issue by rorococo** [Azure/azure-sdk-for-net#21704]
**Query/Question**
Can transaction scopes be used with Azure Service bus?
Stack Overflow question: https://stackoverflow.com/questions/67892423/azure-service-bus-with-transaction-scope  _**(SEE BELOW)**_

**Environment:**
Azure.Messaging.ServiceBus 7.1.0
Hosting platform or OS and .NET runtime version: Windows 10.0.19042, .NET 5.0.103
IDE and version : Visual Studio 16.8.2

**Comment by jsquire** [comment]
Reflecting the Stack Overflow question content:

---
**Namespace**: **Azure.Messaging.ServiceBus**

I am using a transaction scope around my ```ServiceBusSender.SendMessageAsync``` operation and getting "Local transactions are not supported with other resource managers/DTC."

Can transaction scopes be used with Azure Service Bus?

**Current scope**:
```
using (var transaction = new TransactionScope(
   TransactionScopeOption.Required,
   new TransactionOptions
   {
      IsolationLevel = IsolationLevel.Serializable
   },
   TransactionScopeAsyncFlowOption.Enabled))
{
   try
   {
     // do a database operation
     // do azure bus sendmessageasync
   }
    catch
   {
      transaction.Dispose();
      throw;
   }
}
```

**Comment by jsquire** [comment]
Hi @rorococo.  Thank you for reaching out and we regret that you're experiencing difficulties.   Service Bus supports transactions involving a single Service Bus entity, such as reading/publishing to the same queue currently and is expected to receive support for cross-entity transactions at some point in the near-term future.  To my knowledge, Service Bus does not support participating in DTC (or other distributed) transactions, which is what your scope is bound to due to the database operation being included.   I believe that's why the exception is the exception is being triggered.  

@JoshLove-msft is the expert in this area, and I'll defer to him for additional thoughts or corrections, as the authoritative voice.

**Comment by JoshLove-msft** [comment]
Yes, that is correct - the transaction support is limited to operations involving Service Bus - https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-transactions#operations-within-a-transaction-scope
