### ISSUE TITLE
[QUERY] - For greenfield projects, which should Package should I use?

### ISSUE THREAD

**Issue by 1RedOne** [Azure/azure-sdk-for-net#21780]
**Query/Question**
I see a lot of overlap of capability between 

* Azure .NET SDK
* Azure Fluent .NET SDK 

For greenfield projects is there any guidance on which one I should use?  Migrating a legacy code base over and I'm seeing in some places we used `"Microsoft.Azure.Management.Fluent` but in others we used `Microsoft.Azure.Management.ResourceManager` to do largely the same thing.

Which one _should_ we be using? 

**Environment:**
 - "Microsoft.Azure.Management.Fluent" Version="1.33.0
 - "Microsoft.Azure.Management.ResourceManager" Version="3.11.1-preview"
 - dotnet core + Azure Queue Functions
 - IDE and version : [e.g. Visual Studio 16.10]

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by allenjzhang** [comment]
Thanks for your inquiry. I know the situation is a little bit confusing right now. In effect we are having three track of .NET SDKs.

- Microsoft.Azure.Management.XXX  (Track 1, API been out for many years. Autorest generated, have the most RP coverage and refresh.)
- Microsoft.Azure.Management.XXX.Fluent  (Fluent, hand-written with friendly IDE IntelliSense support, have only key RP support. **Will be in maintenance mode pending Track 2 SDKs release**)
- Azure.ResourceManager.XXX  (Track 2, New API surfaces supports Azure.Core. Still in the work but previewing soon.)

So depending on your needs, I would say you can start with track 1 given it has the most RP coverages if you are starting now. Otherwise, you can wait for Track 2 in the coming month.
