### ISSUE TITLE
[FEATURE REQ] - Service bus processing handler and error handler under the same logical thread

### ISSUE THREAD

**Issue by shlomiassaf** [Azure/azure-sdk-for-net#21838]
**Service Bus**
 
**Is your feature request related to a problem? Please describe.**
When registering to the processor via `ProcessMessageAsync` and `ProcessErrorAsync` it appears that the library wrap the invocation of `ProcessMessageAsync` in a logical thread context which does not follow to fire `ProcessErrorAsync` when error occur. Instead the library internally catch and will move on to fire `ProcessErrorAsync` in a different async flow which is not the child of the async flow in `ProcessMessageAsync`

Since there are a lot of approaches in the eco-system to use `AsyncLocal` for things like logging, tracing, etc... It might be
confusing to some why those does no longer work.

The error handler signature does not include the original args from the receiver handler, which for me imply that this design is intended since there are not helpers there to settle the message. However, it is not clear at first sight and might make it harder for developers to integrate.

If it's possible to invoke the error within the logical context of the message handler it will be great.  
However, I suspect it won't be the case, so I suggest more clear documentation on this subject, explaining the relationships between both handler and making it more clear for users to use.

If I've misses such documentation, my apologies in advance.
Thanks

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by JoshLove-msft** [comment]
Hi @shlomiassaf,
If I'm understanding this correctly, you are wondering why the exception handler is not being triggered as a descendant of the message handler invocation. The reason for this is that the exception handler is not triggered _only_ as a result of errors from the message handler. The exception handler can also be triggered due to errors that occur while the processor receives messages, completes messages, and other parts of the processor lifecycle (see https://docs.microsoft.com/en-us/dotnet/api/azure.messaging.servicebus.servicebuserrorsource?view=azure-dotnet). As such, it wouldn't be possible to have the kind of structure that you are looking for, or to include the settlement args (as there may not even be a message to settle). 

If you want to handle errors that might occur in your message handler, the best way to do that would be to catch exceptions within the message handler and handle them as you see fit. Please let us know if you have further questions about this.

**Comment by shlomiassaf** [comment]
Hi @jsandoval-msft 

Thank you for the time and the detailed information.

I assumed this will be the case, I only suggested to add this to the docs so users will know that both handlers originate from different async flows.

Anyway, thank you for clarifying :)
