### ISSUE TITLE
[FEATURE REQ] Allow setting metadata on Storage queue output, such as Visibility Timeout

### ISSUE THREAD

**Issue by anthonychu** [Azure/azure-sdk-for-net#21887]
**Library or service name.**
Microsoft.Azure.WebJobs.Extensions.Storage.Queue
 
**Is your feature request related to a problem? Please describe.**

For out of process languages, including the .NET isolated worker, it's not possible to set metadata on output messages such as visibility timeout. Provide a way to optionally set [these properties](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.storage.queue.cloudqueuemessage?view=azure-dotnet-legacy) on output messages.

https://github.com/Azure/azure-functions-dotnet-worker/issues/493

**Comment by kasobol-msft** [comment]
@anthonychu This is by design. Queue messages received from queue service aren't fully mutable to reflect the fact that you can't really modify these values without calling [UpdateMessageAsync](https://docs.microsoft.com/en-us/dotnet/api/azure.storage.queues.queueclient.updatemessageasync?view=azure-dotnet) first. The result of that operation can we used in [QueueMessage.Update](https://docs.microsoft.com/en-us/dotnet/api/azure.storage.queues.models.queuemessage.update?view=azure-dotnet#Azure_Storage_Queues_Models_QueueMessage_Update_Azure_Storage_Queues_Models_UpdateReceipt_) call to reflect changes made.

If changing code of your application to accommodate that pattern is challenging then you may consider workaround like [this](https://github.com/Azure/azure-sdk-for-net/blob/c11b1289e120d8fd1bdad41808065f416f0ef824/sdk/storage/Microsoft.Azure.WebJobs.Extensions.Storage.Queues/tests/HostCallTests.cs#L494), i.e. use `QueuesModelFactory.QueueMessage` to create new instance with modified properties.

**Comment by anthonychu** [comment]
This is specifically regarding out of process languages (Node.js, Python, .NET out of process etc), where `QueueMessage` cannot be used.

Perhaps a better way to solve this is for us on the Functions side to come up with a design proposal for addressing these types of issues. Will get back to you.
