### ISSUE TITLE
ServiceBusClient.AcceptNextSessionAsync throws exception for topic subscriptions

### ISSUE THREAD

**Issue by Identifier** [Azure/azure-sdk-for-net#21907]
https://github.com/Azure/azure-sdk-for-net/blob/725428489b3c3d3b1407358c719d977b082eae30/sdk/servicebus/Azure.Messaging.ServiceBus/src/Client/ServiceBusClient.cs#L393

When having a ServiceBusClient for a subscription **topic**, the EntityPath is a combination like "TopicName/Subscriptions/SubscriptionName".
When someone calls ServiceBusClient.AcceptNextSessionAsync("topicName", "subscriptionName"), the first thing that method does is call ValidateEntityName(topicName).  But ValidateEntityName tries to validate that the passed-in-parameter == EntityPath.  In this case, ValidateEntityName() always throws an exception since "topicName" != "topicName/subscriptions/subscriptionName".

The fix: Either don't call ValidateEntityName(), or call it with $"{topicName}/Subscriptions/{subscriptionName}".

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by JoshLove-msft** [comment]
ValidateEntityName validates that if an entity path was included in the connectionString, it matches the entity that you are attempting to create a receiver for. The connection string that you get in the portal for a topic would not include a subscription name in the entity path, hence why the validation is done only on the topic name.

Does your connection string include the subscription name as part of the entity path? If so, where did this come from?

**Comment by Identifier** [comment]
Yeah, our connection strings contain an EntityPath in the form of topic/subscriptions/subscription.  I thought this was the appropriate syntax for EntityPath for subscriptions?  Otherwise where should the connection string contain the subscription name?

(By the way, I forgot the `/subscriptions/` middle piece in my original report above, but I updated the report now).

**Comment by JoshLove-msft** [comment]
Subscriptions are not included as part of the connection string syntax. It should either be a topic or a queue - you can't specify a shared access policy at the subscription level. See https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-sas#configuration-for-shared-access-signature-authentication

**Comment by Identifier** [comment]
It's true that the azure portal doesn't let you specify a shared access policy at the subscription level, but the scope of the access policy can be broader than the specific entity path in the connection string.

**Comment by JoshLove-msft** [comment]
The doc linked above mentions that this is not supported at the service level (not just a portal limitation). If you need to restrict access by subscription you can use rules to do this.

**Comment by JoshLove-msft** [comment]
> It's true that the azure portal doesn't let you specify a shared access policy at the subscription level, but the scope of the access policy can be broader than the specific entity path in the connection string.

If the scope of the access policy is meant to be broader than the specific entity path, what is the reason for including the entity path at all?

**Comment by Identifier** [comment]
So that the code using the connection string has all of the information necessary to make the connection.

**Comment by JoshLove-msft** [comment]
With the new library, you need to create the receivers/senders using the CreateSender/Receiver methods. This is where you would specify the entity path. The entity path being in the connection string is only relevant if you are using an entity-level shared access policy. Since that is not the case here (because it includes a subscription), it should be fine to remove it from the connection string.

**Comment by Identifier** [comment]
Ok, we still use connection strings to fully contain all information needed to connect to the subscription, but I can use this workaround if you don't want to fix the issue:

new ServiceBusClient(**Regex.Replace(connectionString, "(EntityPath=[^;/]+)/[^;]+$", "$1")**)

**Comment by JoshLove-msft** [comment]
Can you help me understand how the connectionString is being populated? The library supports the format of the connectionString that comes from the portal. If this is an issue, we should fix it, but I'm not convinced that there is an actual issue here.

The point of this validation is to fail early if someone has a shared access policy scoped to a specific entity, but they try to create a sender/receiver for a different entity.

**Comment by JoshLove-msft** [comment]
> Ok, we still use connection strings to fully contain all information needed to connect to the subscription, but I can use this workaround if you don't want to fix the issue:
> 
> new ServiceBusClient(**Regex.Replace(connectionString, "(EntityPath=[^;/]+)/[^;]+$", "$1")**)

Is the access key from your connection string specific to the topic? If not, you can just remove the entire entityPath key value pair.

**Comment by Identifier** [comment]
The connection strings are generated dynamically by another part of the system when it creates a subscription.  It so happens that so far of the access policies I've been using have been scoped to the topic, but there's nothing wrong with using a root access policy.  This should be a perfectly valid connection string:

`Endpoint=sb://MyNamespace.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=ABCDEFGHIJKLMNOPQRSTUVWXYZ=;EntityPath=TopicName/Subscriptions/SubscriptionName`

**Comment by JoshLove-msft** [comment]
Using a connection string that includes an entity path means that you can only perform operations with that specific entity with your client (otherwise you would get a 401 error). This is why we added the validation - to make it more clear why things are failing. It is correct that you can use the root access key along with an entityPath, but you are still telling the client that all operations will be performed with that specific entity. 

How are you actually creating the receiver? Wouldn't you need to parse the topicName and subscription name anyways? If you attempted to pass the EntityPath string as-is into the CreateReceiver overload that takes a single parameter, I don't think it would work as the entityPath for a subscription is just topicName/SubscriptionName (not topicName/Subscriptions/SubscriptionName).

**Comment by Identifier** [comment]
Regarding your first comment, yes, we only perform operations on the EntityPath specified in the connection string.
And for your second comment, this is how we create receivers:

```
var connectionStringParser = new DbConnectionStringBuilder { ConnectionString = connectionString };

if (connectionStringParser.TryGetValue("EntityPath", out var name))
{
    entityPath = (string)name;
}

...

var client = new ServiceBusClient(Regex.Replace(connectionString, "(EntityPath=[^;/]+)/[^;]+$", "$1"));
var split = entityPath.Split("/");
var receiver = await client.CreateReceiver(split[0], split[^1], options)
```

As you can see, there's quite a lot parsing/string manipulation going on in order to work with the ServiceBusClient/Receiver APIs.  It would be great if we could use these APIs with the full connection strings as-is.

**Comment by JoshLove-msft** [comment]
You can use [ServiceBusConnectionStringProperties.Parse](https://docs.microsoft.com/en-us/dotnet/api/azure.messaging.servicebus.servicebusconnectionstringproperties.parse?view=azure-dotnet#Azure_Messaging_ServiceBus_ServiceBusConnectionStringProperties_Parse_System_String_) for a standard connection string to extract the EntityPath.

If the entity path doesn't contain just a queue or topic name (which is what a standard connection string would contain), you would still need to split up the entity path into the topic and subscription pieces. I'm not sure if the library could support this out of the box because the connection string you are using appears to be custom (it contains `Subscriptions/SubscriptionName`). Basically, the library doesn't know about this "Subscriptions" format. I would be interested to learn where this format came from. Were you using this with a different Service Bus library?

**Comment by Identifier** [comment]
Thanks for pointing out ServiceBusConnectionStringProperties.Parse.  It makes the code slightly nicer looking than DbConnectionStringBuilder.  But it still ultimately just returns the exact content after the EntityPath=... attribute, so if EntityPath=foo/bar/baz we're still going to get ServiceBusConnectionStringProperties.EntityPath == "foo/bar/baz".

Regarding the connection string looking custom, funny enough the EntityPaths **_used to be_** simply EntityPath=topicname/subscriptionname.  It wasn't until recently that we started using EntityPath=topicname/**subscriptions**/subscriptionname since that's ultimately what the REST API uses.  It's also mentioned [here](https://stackoverflow.com/questions/63170308/what-is-the-entitypath-in-azure-servicebusconnectionstringbuilder).

**Comment by JoshLove-msft** [comment]
Ah ok, the REST API that is used for administration operations uses that in the request URI for subscription operations, but this isn't a generally supported format for connection strings.
