### ISSUE TITLE
[Azure-Identity] VisualStudioCredential has "slow" subsequent GetTokenAsync calls

### ISSUE THREAD

**Issue by vicinting** [Azure/azure-sdk-for-net#21958]
**Description**

I'm comparing between VisualStudioCredential and InteractiveBrowserCredential token credentials for local development and from my understanding, the first get token call should be the slowest as subsequent calls should used the cached token.

**Expected behavior**

Subsequent GetTokenAsync calls should be faster as a cached token is used

**Actual behavior**

While using VisualStudioCredential, subsequent calls are equivalent/comparable to the first call, around 800ms for me. See screenshots below for comparison between both credentials mentioned above.

InteractiveBrowserCredential 

![InteractiveBrowserCredential2](https://user-images.githubusercontent.com/4598010/122520405-e6084a80-d056-11eb-98d4-85aa82823b2c.jpg)

VisualStudioCredential 

![VisualStudioCredential2](https://user-images.githubusercontent.com/4598010/122520420-ea346800-d056-11eb-846c-0c64ae266ab1.jpg)

**Environment**

- Azure.Identity (1.4.0.0)
- Windows 10 Pro (Build 19043)
- Visual Studio Professional (16.10.2)

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team members best able to assist.

**Comment by christothes** [comment]
> I'm comparing between VisualStudioCredential and InteractiveBrowserCredential token credentials for local development and from my understanding, the first get token call should be the slowest as subsequent calls should used the cached token.

Hi @vicinting - `VisualStudioCredential` relies on the `Microsoft.Asal.TokenService.exe` utility shipped with Visual Studio to fetch tokens which, in turn, relies on MSAL. MSAL should be caching tokens, as long as the token request was successful.

It's possible the delay you are seeing is from something other than token caching. In my local testing using Fiddler, I noticed that it sends some traffic related to telemetry. This credential is meant for development use, so performance is not one of its goals.

**Comment by vicinting** [comment]
Thank you @christothes. I'll look into monitoring the network traffic as well but just provided this as feedback in case it was an issue.

The delay is not really a big issue but it could lead to misleading metrics to someone trying to work on performance. I'll just note it as a comment in our project, closing this issue for now.

**Comment by peter-bertok** [comment]
> This credential is meant for development use, so performance is not one of its goals.

Performance should always be a goal, even at development time.

I'm seeing a full second added to every dependency call, which would otherwise take single-digit milliseconds to complete.

This is slowing down dev-test cycles unacceptably. It makes it impossible to determine the performance of code while in Visual Studio. This generally makes Azure.Identity an absolute no-go for our purposes.

**Comment by peter-bertok** [comment]
> Azure.Identity does not need to use VisualStudioCredential even if the code is being tested inside Visual Studio.

This is the specific scenario that we need to "just work", so alternatives aren't helpful.

In the meantime I did more research and discovered that Azure.Identity has essentially no caching at all. Downstream consumers may opt to do caching, but this is inconsistent and unreliable.

If I can make a recommendation: avoid the use of the words "you" or "your" when thinking about or communicating with the users of these SDKs. This is an *enormous* ecosystem of related libraries, and "I" don't get to control how they interact with each other. Even Microsoft is not in full control of this -- there are SDKs written by third parties that use Azure.Identity internally, and I may not have any choice in how those SDKs are used.

The performance issues with Azure.Identity appear to be fundamental and cannot be consistently resolved by individual end-users. The only thing that can be done is for Microsoft to ensure that all scenarios are fast, and that downstream users fall into the pit of success instead of the pit of failure. Right now, there are people complaining about 429 errors in all sorts of related libraries because Microsoft hasn't done this consistently or correctly enough. They're falling in to the pit of failure, because that's the default path.

**Comment by christothes** [comment]
> In the meantime I did more research and discovered that Azure.Identity has essentially no caching at all. Downstream consumers may opt to do caching, but this is inconsistent and unreliable.

Although the documentation indicates that caching is the callers responsibility, this is not entirely true. Some credentials do cache because of the underlying implementation provided by MSAL. We also allow for some configuration of token cache for scenarios where sharing cache across credential instances is needed. See [this sample](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/identity/Azure.Identity/samples/TokenCache.md) for more information.

> The performance issues with Azure.Identity appear to be fundamental and cannot be consistently resolved by individual end-users. The only thing that can be done is for Microsoft to ensure that all scenarios are fast, and that downstream users fall into the pit of success instead of the pit of failure. Right now, there are people complaining about 429 errors in all sorts of related libraries because Microsoft hasn't done this consistently or correctly enough. They're falling in to the pit of failure, because that's the default path.

I apologize if you have encountered any performance issues with Azure.Identity. If there is a specific scenario we can assist with, please feel free to create an issue with the details and we will do our best to assist.

**Comment by Jawvig** [comment]
Thanks for the sample link, @christothes. Unfortunately it looks like you can't pass `TokenCachePersistenceOptions` to `DefaultAzureCredentials` and have this propagate it down the chain.

My use case is that I'm running local xunit integration tests that test code use Entity Framework to perform some operations on an Azure SQL database. The tests make about 5 database calls each on < 10 rows of data, pretty simple. However, each test takes about 20s to run inside Visual Studio. In the DbContext I'm using the token based authentication as laid out in Mikaël's blog here: https://devblogs.microsoft.com/azure-sdk/azure-identity-with-sql-graph-ef/ 

Note that whilst it stores the `ChainedTokenCredential` statically, it does not cache the tokens retrieved.

The difference in my case is I'm using `DefaultAzureCredential` in the interceptor rather than `new ChainedTokenCredential(new ManagedIdentityCredential(), new EnvironmentCredential())`. We run the code under test in a variety of contexts - Visual Studio Test Explorer, `dotnet test` in Azure pipelines and then the code itself in both console apps and Azure functions with managed identities. `DefaultCredential` has been really handy to support all of these.

When I profiled the tests I could see that most of the time was spent by the `VisualStudioCredential` running processes:
<img width="919" alt="image" src="https://user-images.githubusercontent.com/488393/157993491-dd48e452-1312-404f-8b20-8a753f0d1338.png">

I have a few different accounts logged into Visual Studio for different tenants. I noticed that `DefaultAzureCredentialOptions` supports `SharedTokenCacheTenantId`. From the code docs:

_"Specifies the tenant id of the preferred authentication account, to be retrieved from the shared token cache for single sign on authentication with development tools, in the case multiple accounts are found in the shared token.
If multiple accounts are found in the shared token cache and no value is specified, or the specified value matches no accounts in the cache the SharedTokenCacheCredential will not be used for authentication."_

However, specifying the required tenant id in this field did not alter the performance as far as I could see.

I'm nervous about caching the tokens as there's no information about their expiry and caching beyond their expiry would lead to an annoying class of bugs. But is that the way to go?

I appreciate any help here.
