### ISSUE TITLE
[BUG] ReceiveMessageAsync hangs if Queue is empty

### ISSUE THREAD

**Issue by reyou** [Azure/azure-sdk-for-net#21985]
**Describe the bug**    
`ReceiveMessageAsync()` method hangs infinitely if **Queue is empty**. 

**Expected behavior**
It should return null as in description.

**Actual behavior (include Exception or Stack Trace)**
hangs infinitely.

**To Reproduce**
	Snippet

    ServiceBusReceiverOptions options = new ServiceBusReceiverOptions()
               {
                   ReceiveMode = ServiceBusReceiveMode.PeekLock,
               };
               _serviceBusReceiver = _serviceBusClient.CreateReceiver(queueOrTopicName, options);
    ServiceBusReceiver receiver = _serviceBusReceiver;
    ServiceBusReceivedMessage serviceBusReceivedMessage = await receiver.ReceiveMessageAsync();

**Environment:**
Windows 10, VS 2019 latest as of today.

     <PackageReference  Include="Azure.Messaging.ServiceBus"  Version="7.1.2" />

**Comment by jsquire** [comment]
Hi @reyou.   Thank you for reaching out and we regret that you're experiencing difficulties.  I've routed this to the team member best able to assist.   To help us better understand your scenario, would you be so kind as to include a snippet to show us how you're configuring/creating your `ServiceBusClient`?    

Because your snippet above is not specifying a `maxWaitTime` when making the receive call, the `ServiceBusClientOptions.RetryOptions.TryTimeout` from the client will be used as the wait time for the call.   By default, that is 60 seconds.   After that period has elapsed, you should see the call return, either with a message or `null`.    

In my attempt to reproduce, I'm seeing the expected behavior.   Any additional context or details that you can provide to help us repro what you're seeing would be greatly appreciated.   In case it is helpful, this is the minimal snippet that I tested against, using an empty queue:

```csharp
var conn = "<< CONNECTION STRING >>";
var queue = "<< QUEUE NAME >>";

var clientOptions = new ServiceBusClientOptions();
clientOptions.RetryOptions.TryTimeout = TimeSpan.FromSeconds(6);

await using var client = new ServiceBusClient(conn, clientOptions);
await using var receiver = client.CreateReceiver(queue, new ServiceBusReceiverOptions { ReceiveMode = ServiceBusReceiveMode.PeekLock });

var watch = Stopwatch.StartNew();
var message = await receiver.ReceiveMessageAsync();
watch.Stop();

(message == null).Dump();
watch.Elapsed.TotalSeconds.Dump();
```

With the results being within the expected interval, allowing for the initial connection to also be established:

```text
True
7.3755274
```

**Comment by reyou** [comment]
OK that's right. I had integration tests was failing due to not passing explicit timeout.
But there is already `MessageProcessor` for long running tasks, I was more thinking to use this for utility/testing purposes.

So, let's assume there are 100 items in the queue and I am passing `1 seconds` as parameter, does it guarantee to fetch the message even if network is slow and take 2 seconds to fetch the message? Or will it timeout even if there are messages in the queue?

**Comment by jsquire** [comment]
> So, let's assume there are 100 items in the queue and I am passing 1 seconds as parameter, does it guarantee to fetch the message even if network is slow and take 2 seconds to fetch the message? Or will it timeout even if there are messages in the queue?

I'm going to assume that by "parameter", we're referring to the `maxWaitTime` and the subsequence uses of "timeout` are also referring to that, rather than the `TryTimeout`.  Finally, I'm going to assume that you're not setting the `PrefetchCount`.  With those assumptions, the answer to your question is no.   If you ask that the call wait a maximum of 1 second, it will do so.   If the network is slow and it takes 2 seconds to fetch the message, then you would timeout before receiving it.

Setting a small prefetch count would help to mitigate this, if you're using a short `maxWaitTime` and you expect to be polling the `ReceiveMessageAsync` call in a loop.  However, that does come with a trade-off with the lock duration being less deterministic for your application because it starts when the message is locally queued.  _([more details](https://docs.microsoft.com/azure/service-bus-messaging/service-bus-prefetch))_

To be transparent, I'm not exactly sure of the top of my head what the behavior is without prefetch enabled if the call times out;  @JoshLove-msft  - do you know if the message is locked by the service in a timeout scenario or is available to be read by the next request?

**Comment by reyou** [comment]
OK thank you. In case of timeout, would you maybe throw timeout exception, that let's consumer know client could not even communicate with service bus in a given time, or return `null` meaning that reached the MessageBus but 0 result returned during the time observation (timeout) 

If you return null on both instances it is a little bit confusing and race against the network slowness in that case.

**Comment by JoshLove-msft** [comment]
> To be transparent, I'm not exactly sure of the top of my head what the behavior is without prefetch enabled if the call times out; @JoshLove-msft - do you know if the message is locked by the service in a timeout scenario or is available to be read by the next request?

The message may be locked by the service, but it will have been sent on the existing link, so as long as the next request is using the same receiver, the message should be retrieved. If the next request doesn't happen for a while, the message lock may already be lost by the time the receiver gets it. To better support scenarios like this, we would need to support draining unused link credits, which is on our roadmap for the next semester.

**Comment by jsquire** [comment]
> OK thank you. In case of timeout, would you maybe throw timeout exception, that let's consumer know client could not even communicate with service bus in a given time, or return null meaning that reached the MessageBus but 0 result returned during the time observation (timeout)

I understand your perspective and the ambiguity that exists but, unfortunately, there are a couple of challenges with the proposed approach:

- The client knows only that the timeout it set for the read operation has expired; it has no insight into whether that was because the service was waiting because no message was available or the network was slow and the service didn't have time to respond.

- The state of the service is continually changing; it would be quite possible for a timeout to occur because there was no message available to be read and then have a message published even before the client was even able to fully communicate the timeout.  In that scenario, the client would throw the timeout exception and the application may act on bad information, causing the newly published message to be delayed or missed.

- The library has reached GA and we want to ensure that we do not introduce breaking changes;  this shift in behavior has the potential to break existing consumers who are expecting the empty set and aren't explicitly handling a timeout exception.

If your application would like to understand the number of messages that are available, you may want to consider calling  [`ServiceBusAdministrationClient.GetQueueRuntimeProperties`](https://docs.microsoft.com/dotnet/api/azure.messaging.servicebus.administration.servicebusadministrationclient.getqueueruntimepropertiesasync) when your receive call returns an empty set; that would offer visibility into the current state of the queue and allow your application to make decisions around the action that it would like to take.

I'm going to mark this as addressed, but please feel free to `/unresolve` if you have further questions or would like to continue the discussion.

**Comment by reyou** [comment]
Thanks for your clarification @jsquire, this helps a lot :)
