### ISSUE TITLE
Note out of date

### ISSUE THREAD

**Issue by AlexandraKemperMS** [Azure/azure-sdk-for-net#22011]
Hi, could you please remove the note at the top of this page? The Microsoft.FeatureManagement Namespace is stable and released, a warning about it being in in prerelease is not necessary anymore. Developers are getting confused whether they can use this namespace. 
Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1fe8dba5-8f5e-1e3b-22b0-e9b9ce96e157
* Version Independent ID: 6838cdd3-c038-d2cf-14c8-90f5555e96a4
* Content: [Microsoft.FeatureManagement Namespace - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/microsoft.featuremanagement?view=azure-dotnet-preview)
* Content Source: [xml/ns-Microsoft.FeatureManagement.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/ns-Microsoft.FeatureManagement.xml)
* Service: **azure-app-configuration**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by jsquire** [comment]
Because `Microsoft.FeatureManagement` is not sourced from the Azure SDK repository, I've transferred this issue to the `Azure/AppConfiguration` repository identified on [NuGet](https://www.nuget.org/packages/Microsoft.FeatureManagement/) as the project home as #[527](https://github.com/Azure/AppConfiguration/issues/527).
