### ISSUE TITLE
DataLakeStoreUploader.Tests is causing intermittent CI build failures

### ISSUE THREAD

**Issue by brjohnstmsft** [Azure/azure-sdk-for-net#2208]
See this build log: http://azuresdkci.cloudapp.net/job/sdk-for-net/3003/console

Here is the failure:

```
18:23:16   Discovering: DataLakeStoreUploader.Tests
18:23:17   Discovered:  DataLakeStoreUploader.Tests
18:23:17   Starting:    DataLakeStoreUploader.Tests
18:31:56      Microsoft.Azure.Management.DataLake.StoreUploader.Tests.DataLakeUploaderTests.DataLakeUploader_FreshFolderUploadDownload [FAIL]
18:31:56         Assert.Equal() Failure
18:31:56         Expected: 3
18:31:56         Actual:   2
18:31:56         Stack Trace:
18:31:56            src\ResourceManagement\DataLake.StoreUploader\DataLakeStoreUploader.Tests\UnitTests\DataLakeUploaderTests.cs(645,0): at Microsoft.Azure.Management.DataLake.StoreUploader.Tests.DataLakeUploaderTests.VerifyFolderProgressStatus(UploadFolderProgress progress, Int64 totalFileLength, Int32 totalFiles)
18:31:56            src\ResourceManagement\DataLake.StoreUploader\DataLakeStoreUploader.Tests\UnitTests\DataLakeUploaderTests.cs(229,0): at Microsoft.Azure.Management.DataLake.StoreUploader.Tests.DataLakeUploaderTests.DataLakeUploader_FreshFolderUploadDownload()
18:31:56   Finished:    DataLakeStoreUploader.Tests
```

Also, these tests take a long time to run. Perhaps they are not using mocks? We should keep our tests fast and reliable for the CI build.

CC @hovsepm

**Comment by begoldsm** [comment]
These are pure unit tests that do data manipulation on the local machine. The download tests are tricky since they don't fake the actual download, meaning they put temporary filesin the temp folder where they are run. If that folder gets cleaned up or doesn't allow the files to be created, then we will see these types of errors. Also, unfortunately, they require ~50mb of data to be created, which makes the data comparison portion of the test take some time. On my local machine all of these tests run in < 3 minutes, but I agree that is a non-trivial amount of time.

**Comment by begoldsm** [comment]
I am investigating the test flakiness now, though.

**Comment by hovsepm** [comment]
@begoldsm please take a look to in-mermory data store instead of real file system. That should stabilize tests and speed up execution time.

**Comment by begoldsm** [comment]
This is resolved with my latest PR: https://github.com/Azure/azure-sdk-for-net/pull/2758
