### ISSUE TITLE
Missing info about the "nameid" field

### ISSUE THREAD

**Issue by Yozez** [Azure/azure-sdk-for-net#22451]
I try to understand all the fields in the jwt token,
and I can't found documentation about the "NameId" field, 
and it seems like this field is a combination between account id and tenant id.

it will be great if someone could approve that for me, and besides that will add more info about that field to the documentation.

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fad76c95-16a4-e946-c015-f79fe72c84c7
* Version Independent ID: 0eedd505-3e2f-efa0-6b8c-ac57c08d5206
* Content: [JwtRegisteredClaimNames.NameId Field (System.IdentityModel.Tokens.Jwt) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/system.identitymodel.tokens.jwt.jwtregisteredclaimnames.nameid?view=azure-dotnet)
* Content Source: [xml/System.IdentityModel.Tokens.Jwt/JwtRegisteredClaimNames.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/System.IdentityModel.Tokens.Jwt/JwtRegisteredClaimNames.xml)
* Service: **active-directory**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by jsquire** [comment]
This issue is in reference to the `System.IdentityModel.Tokens.Jwt` package, which is not sourced from this repository.   I've transferred to the Azure Active Directory repository where the package is maintained as issue [#1664](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues/1664).
