### ISSUE TITLE
AmqpAnnotatedMessageExtensions - CopyDictionary forces allocation of Keys-collection

### ISSUE THREAD

**Issue by snakefoot** [Azure/azure-sdk-for-net#22622]
https://github.com/Azure/azure-sdk-for-net/blob/7be25e8cca0c649c6e9fac29677ad5a7c6893982/sdk/eventhub/Azure.Messaging.EventHubs/src/Amqp/AmqpAnnotatedMessageExtensions.cs#L402-L405

Instead it should just be this:

```c#
foreach (var item in source)
{
   destination[item.Key] = item.Value;
}
```

**Comment by jsquire** [comment]
Hi @snakefoot.   Nice catch; we overlooked that.   

In this case, there's unlikely to be an impact since we're checking to see if the section exists before copying.  The only scenario where we'd allocate is if a caller had previously accessed the AMQP message section, causing lazy allocation of the dictionary, but didn't perform any operation that would have caused the `Keys` collection to allocate.

I've got a PR out to change the approach; better to guard against any future changes now.

**Comment by jsquire** [comment]
Fixed by:  #22632

**Comment by jsquire** [comment]
I'm going to mark this as addressed and we'll close out once the PR merges.   Please feel free to use the "`/unresolve`" command if you'd like to continue discussing.

**Comment by snakefoot** [comment]
Guess one could also check if the source-dictionary is not empty, before doing foreach and allocating enumerator

On 13 Jul 2021 23:11, "msftbot[bot]" ***@***.***> wrote:

Hi @snakefoot<https://github.com/snakefoot>. Thank you for opening this issue and giving us the opportunity to assist. We believe that this has been addressed. If you feel that further discussion is needed, please add a comment with the text “/unresolve” to remove the “issue-addressed” label and continue the conversation.

**Comment by snakefoot** [comment]
Thank you for the quick attention and fast result.
