### ISSUE TITLE
[BUG] Azure.ResourceManager.Resources ResourcesOperations Slow Response.

### ISSUE THREAD

**Issue by zep-uipath** [Azure/azure-sdk-for-net#22664]
**Describe the bug**
Hello MS team, we met a problem that when we create/delete an Azure resource (for example virtual machine image/disk) in Azure Portal, it takes about 20 minutes for the change to eventually update in the result of calling the Azure ResourceManager SDK.

Specifically when calling the `ResourcesOperations::ListAsync` function with the `filter` string passed in to get resources of type `"Microsoft.Compute/images"` and type `"Microsoft.Compute/snapshots"` in a subscription. 

(Function doc is here: https://docs.microsoft.com/en-us/dotnet/api/azure.resourcemanager.resources.resourcesoperations.listasync?view=azure-dotnet-preview)

**Expected behavior**
Calling `ListAsync` should return the updated list of resources in the subscription without waiting for a long time.

**Actual behavior (include Exception or Stack Trace)**
When calling `ListAsync`, it takes about 20 minutes to return the updated list of resources. Before that the returned list of resources is outdated and did not reflect the changes been made.

**Environment:**
`<PackageReference Include="Azure.ResourceManager.Resources" Version="1.0.0-preview.2" />`

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by allenjzhang** [comment]
@grizzlytheodore , can you pass to the right team member to see if this is an ARM issue or Compute issue, please? Thank you.

**Comment by zep-uipath** [comment]
Hi! Just checking in: is there any update about this issue?

**Comment by snaheth** [comment]
Hey @zep-uipath - Thanks for checking in and bumping this issue.

The delay to see your resources with an updated status could be due to multiple causes, such as:

1. Long resource deletion latency from the Resource Provider (e.g. Compute)
2. Backend updates within ARM
3. Other reliability or perf issues with the Resource Provider that affect what ARM can return to you

The causes mentioned above are likely the cause of the list operation returning updated resource data later than expected.

@zep-uipath -- If you email me at Snaheth.Thumathy@microsoft.com with the specific Correlation IDs for your operations and the affected resources, I can take a look and get back to you with a response. If for some reason, you don't hear back from me within a day, you'd receive a much timelier response by creating a support case within the Azure Portal.

**Comment by jingtaoren** [comment]
@snaheth thx for response. I am taking this from @zep-uipath . 

The issue only happens when we use .Net Azure ResourceManager SDK. But not able to repro thru Portal. So I doubt it is a ARM side issue. (When list thru Portal or cli, we can see the resource immediately)

```
➜  jingtao.ren az resource list -g Jingtao-Personal-RG --resource-type "Microsoft.Compute/snapshots" -o table
Name     ResourceGroup        Location    Type                         Status
-------  -------------------  ----------  ---------------------------  --------
winsnap  Jingtao-Personal-RG  westus2     Microsoft.Compute/snapshots
```

Here is how we use this query in SDK
`var resources = await azureClient.Resources.ListAsync(filter: $"resourceType eq 'Microsoft.Compute/images' or resourceType eq 'Microsoft.Compute/galleries/images/versions'" +  $" or resourceType eq 'Microsoft.Compute/snapshots'").ToListAsync(cancellationToken);
`
