### ISSUE TITLE
CreateMessageBatchAsync function will be hung when max thread limited

### ISSUE THREAD

**Issue by dabinguoguoboy** [Azure/azure-sdk-for-net#22761]
Package version: Azure.Messaging.ServiceBus 7.2.1
When I limit the concurrent thread count, the function CreateMessageBatchAsync will be hung always.
sample code:
```csharp
//limit the thread count
int concurrent = 9;
ThreadPool.SetMaxThreads(concurrent, 100);
int sessionCount = 100
for (int i = 0; i < sessionCount; i++)
{
    Send(i);
}

void Send(int i)
{
    ThreadPool.QueueUserWorkItem(new WaitCallback(obj=>
        {
             ....
             var   client = new ServiceBusClient("connection string");
             var   sender = client.CreateSender("queue name");
             //create message batch object, it will be hung
             var messageBatch = sender.CreateMessageBatchAsync().Wait();
             if (!messageBatch.TryAddMessage("message sample json"))
             ....
        }
}
```
When I modify variable as concurrent > sessionCount, the function CreateMessageBatchAsync runs normal, like:
```csharp
//limit the thread count
int concurrent = 100;
ThreadPool.SetMaxThreads(concurrent, 100);
int sessionCount = 10
for (int i = 0; i < sessionCount; i++)
{
    Send(i);
}

void Send(int i)
{
    ThreadPool.QueueUserWorkItem(new WaitCallback(obj=>
        {
             ....
             var   client = new ServiceBusClient("connection string");
             var   sender = client.CreateSender("queue name");
             //create message batch object, it will runs normally
             var messageBatch = sender.CreateMessageBatchAsync().Wait();
             if (!messageBatch.TryAddMessage("message sample json"))
             ....
        }
}
```

**Comment by JoshLove-msft** [comment]
It doesn't appear as though the code snippet would be runnable since the CreateMessageBatchAsync method returns a `ValueTask<T>`, but I think I understand the intent. I can repro the issue by modifying the code to:
```cs
var messageBatch = sender.CreateMessageBatchAsync().Result;
```
It looks like what is happening is that we are running into a deadlock due to the use of sync-over-async. This scenario is described in [this blog post](https://devblogs.microsoft.com/pfxteam/should-i-expose-synchronous-wrappers-for-asynchronous-methods/). In particular, this paragraph:
> But now let’s say that instead of queuing one task to call Foo, you queue 25 tasks to call Foo. Each of the 25 threads in the ThreadPool will pick up a task, and invoke Foo. Each of those calls will start some asynchronous I/O and will block until the work completes. The async I/O for all of the 25 Foo calls will complete and result in the final processing work items getting queued to the pool. But the pool threads are now all blocked waiting for the calls to Foo to complete, which won’t happen until the queued work items get processed, which won’t happen until threads become available, which won’t happen until the calls to Foo complete. Deadlock!

To avoid this situation, it would be better to await the async method, i.e. 
```cs
  ThreadPool.QueueUserWorkItem(new WaitCallback(async obj =>
  {
      var sender = client.CreateSender(scope.QueueName);
      //create message batch object, it will be hung
      var messageBatch = await sender.CreateMessageBatchAsync();
      if (!messageBatch.TryAddMessage(new ServiceBusMessage()))
      {
      }
  }));
```
I know this isn't a real world example, but as an FYI, you would probably want to avoid creating a client in each iteration of the loop, as Service Bus has a limit on the number of connections that can be active at one time, as mentioned [here](https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-quotas#messaging-quotas). Similarly, you would probably want to avoid using different senders for each iteration as each sender is mapped to an additional AMQP link under the hood. The cost for establishing each of these links is non-trivial.

**Comment by dabinguoguoboy** [comment]
@JoshLove-msft Thank you for your reply. Yes this code is only for example, not product env. The sender object will not be reused. Now I understand it, your solution works.
