### ISSUE TITLE
BlockBlobClient.OpenWrite Stream gives Timeout exception on writes. sdk 12.9.1 

### ISSUE THREAD

**Issue by MohitNagpaldce** [Azure/azure-sdk-for-net#22855]
Blob write code new

```
        /// <summary>
        /// Blob write operations.
        /// </summary>
public static BlockBlobOpenWriteOptions BlobStreamOptions =
            new BlockBlobOpenWriteOptions()
            {
                BufferSize = 8 * 1024 * 1024,
            };



var blobclientOptions = new BlobClientOptions();
            blobclientOptions.Diagnostics.IsLoggingEnabled = false;
            blobclientOptions.Diagnostics.IsTelemetryEnabled = false;
            blobclientOptions.Diagnostics.IsDistributedTracingEnabled = false;
            blobclientOptions.Retry.MaxRetries = 3;
            blobclientOptions.Retry.Mode = RetryMode.Exponential;
            blobclientOptions.Retry.NetworkTimeout = TimeSpan.FromSeconds(1200);
            var cloudBlobClient = new BlockBlobClient(new Uri(blobPathUri), blobclientOptions);
            cloudBlobClient.DeleteIfExists();

blobclientOptions.AddPolicy(new TimeoutPolicy(2000000), HttpPipelinePosition.PerCall);


var cloudBlobClient = new BlockBlobClient(new Uri(blobPathUri), blobclientOptions);
cloudBlobClient.DeleteIfExists();
this.blobStream = cloudBlobClient.OpenWrite(true, BlobStreamOptions);

this.blobStream.Write(data) 
this.blobStream.Write(data) 
this.blobStream.Write(data) 
this.blobStream.Write(data) 
this.blobStream.Write(data) 
this.blobStream.Write(data) 
this.blobStream.Write(data) 

…….. 100K + calls 

this.blobStream.Flush();
this.blobStream.dispose()
```

<<Many calls to write : 100K+ calls>>
After some time, calls are getting timeout. 
How to do make sure calls does not timeout. 

```
 /// <summary>
    /// Timeout policy.
    /// </summary>
    public class TimeoutPolicy : HttpPipelineSynchronousPolicy
    {
        /// <summary>
        /// time out period.
        /// </summary>
        private int timeout;

        /// <summary>
        /// Initializes a new instance of the <see cref="TimeoutPolicy"/> class.
        /// </summary>
        /// <param name="timeout"></param>
        public TimeoutPolicy(int timeout)
        {
            this.timeout = timeout;
        }

        /// <inheritdoc/>
        public override void OnSendingRequest(HttpMessage message)
        {
            message.Request.Uri.AppendQuery("timeout", this.timeout.ToString());
        }
    }
 ```

**Comment by amnguye** [comment]
I think the real question is why the timeouts are occurring rather than attempting to do an infinite timeout. I believe there should always be a timeout to set for requests. If it waits for an unreasonable amount of time, I think it's best to either close the connection and resolve the issue, then retry.

https://docs.microsoft.com/en-us/rest/api/storageservices/setting-timeouts-for-blob-service-operations

From the above article, the maximum timeout interval for blob service operations is 30 seconds with some exceptions. And will automatically reduce any timeout to 30 seconds (this is not on the SDK). Since you're writing blocks to the blob, the exception is changed to 10 minutes per megabyte to complete, so if it goes over it will automatically timeout. This is for efficiency and not to throttle the storage account.

**Comment by MohitNagpaldce** [comment]
thanks for clarification. 
is blobclientOptions.Retry policy  will also apply to when calling this.blobStream.Write(data) .  I belive this.blobStream.Write(data) internally is doing putblock so  blobclientOptions passed to blobclient will apply in calls to this.blobStream.Write(data) . 
var cloudBlobClient = new BlockBlobClient(new Uri(blobPathUri), blobclientOptions);

Please confirm this part. Thanks for help.

**Comment by amnguye** [comment]
Yes it will also apply to the this.blobStream.Write(data) if the `BlobClientOptions` passed to the `BlobClient` was the one who created the `blobStream`.
