### ISSUE TITLE
Reference URL is 404

### ISSUE THREAD

**Issue by Bafff** [Azure/azure-sdk-for-net#22870]
Hi!

Can you update the reference URL: https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.storage.common

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 910dab69-65c9-d3b9-4bde-a04320ab8f7d
* Version Independent ID: d85d233b-9b65-e24a-390f-1dc1e5844b40
* Content: [Azure Storage client libraries for .NET - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/overview/azure/storage?view=azure-dotnet)
* Content Source: [api/overview/azure/storage.md](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/api/overview/azure/storage.md)
* Service: **storage**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by amishra-dev** [comment]
@Bafff which API's doc are you looking for? This SDK was deprecated and some of the documents might have been moved around.

**Comment by Bafff** [comment]
@amishra-dev I was looking for this 
![image](https://user-images.githubusercontent.com/26187677/127218493-f66f045d-cb18-42b9-8f48-8ea9b22a155a.png)

Maybe if those links are gone forever can you point me for the latest appropriate docs?

**Comment by amnguye** [comment]
Looks like we should remove the Microsoft.Azure.Storage.Common Reference link since no reference page has never existed.

Is there a reason or something specific you're looking in the Common package? The Common package isn't meant to used as a standalone.
For v12 we have the page for the Azure.Storage Namespace if that's what you're looking for.
https://docs.microsoft.com/en-us/dotnet/api/azure.storage?view=azure-dotnet

**Comment by Bafff** [comment]
Ok, thanks!

If you'll remove this link I would be happy :)
