### ISSUE TITLE
[BUG] BlobClient.UploadAsync do not write stream if this one has not been read once.

### ISSUE THREAD

**Issue by NtgTNabet** [Azure/azure-sdk-for-net#22994]
**Describe the bug**
Using BlobClient.UploadAsyncwith a stream wich has not been read once ( lenght = 0, position = 0, canSeek = true ) result in creation of empty blob. ( NOTE The stream does contain data but is not aware of the lenght until first read )

**Expected behavior**
Using BlobClient.UploadAsync with a stream wich has not been read once ( lenght = 0, position = 0, canSeek = true ) properly read the stream until end and create the blob with the stream content.

**Actual behavior (include Exception or Stack Trace)**
N/A

**To Reproduce**
Create Asp.net core APP. 
Upload The Request.Body ( which has not been read yet ) of POST Method using BlobUploadAsync.

**Environment:**
Azure.Storage.Blobs 12.9.1
.Net 5.0.301

For person who look for a fix best way is to OpenWriteAsync a BlockBlobClient and use Stream.CopyToAsync().

**Comment by amnguye** [comment]
Not sure if this is a fix we should do because if we attempt to read a stream that actually is empty (length = 0) then we would run into a null exception for attempting to read at a position we can't make the request.

What's the scenario where `UploadAsync` has to take in a no-length stream? (this is seems like the Stream itself has a problem) Maybe we can find another solution for this. For now it looks like OpenWrite seems like the best solution for this scenario.
