### ISSUE TITLE
[FEATURE REQ] KeyVaultKeyIdentifier.TryParse

### ISSUE THREAD

**Issue by jimmyca15** [Azure/azure-sdk-for-net#23146]
**Library or service name.**
Azure.Security.KeyVault.Keys
 
**Is your feature request related to a problem? Please describe.**
If I develop an application that takes user input that should be a key vault key URI I have to write the following code to validate it is a Key Vault URI.

```
try
{
    identifier = new KeyVaultKeyIdentifier(id);
}
catch (ArgumentException)
{
    // Invalid id
}
```

Ideally I would like to write

```
if (KeyVaultKeyIdentifier.TryParse(id, out KeyVaultKeyIdentifier identifier))
{
    // use it
}
else
{
    // Return error
}
```

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by heaths** [comment]
@KrzysztofCwalina customers here are asking for my original design. Do you see any problem adding this? The `KeyVault*Identifier` structs across languages were only ever meant for parsing anyway - merely exposing what we were all already doing internally anyway.

**Comment by avanigupta** [comment]
Hi @heaths, any update on whether this API will be added to the next stable release?

**Comment by KrzysztofCwalina** [comment]
I am not totally opposed to digging deeper here and possibly solving a problem, but:

It's not really parsing. The URI is already parsed when it's passed to the ctor. The issue seems to be that some users (e.g. @jimmyca15) do not like exceptions for invalid arguments. I totally understand issues with C# exception handling, and I talked to the C# team many times about it), but don't think TryParse was intended for that. In .NET, we throw exceptions for invalid arguments.

.NET guidelines specifically state that Try methods should not be added because we don't like exceptions. Try methods are performance optimizations, and so if you add them you need to show that performance is a problem (not in microbenchmarks).

If we started to add Try methods to all places where we don't like exceptions, we would end up with every BCL API duplicated (try and non-try variants).

@MadsTorgersen, @jaredpar, if would be nice to have try expressions in the language, just like we planned in M# :-)

**Comment by heaths** [comment]
The URI is not parsed. It is a URI, yes, but not necessarily a valid Key Vault URI. That's why I had `KeyVaultSecretIdentifier.TryParse` originally. As @tg-msft pointed out from the .NET Framework Guidelines,

> DO NOT use exceptions for the normal flow of control, if possible. Prefer Tester–Doer or the Try pattern to throwing exceptions in common cases.

The point of this struct was to parse a URI as a valid Key Vault (or Managed HSM) URI. I agree that we need a `TryParse`.

**Comment by heaths** [comment]
We will add a `TryCreate` in the next preview (and stable) release. We feel this will better coincide with the existing ability to create (via the constructor) a `KeyVaultKeyIdentifier` and be less confusing since the URI is already parsed into a `System.Uri`.
