### ISSUE TITLE
remoterendering - cspell found spelling errors in public API surface

### ISSUE THREAD

**Issue by danieljurek** [Azure/azure-sdk-for-net#23187]
Investigation for this PR: https://github.com/Azure/azure-sdk-for-net/pull/23150 found spelling errors. When the linked PR merges this service will be opted out of public API surface spell checking to keep other PRs unblocked. This issue describes how to opt back in. 

If the above linked PR has not merged this service is still opted out and not blocked by the detection of spelling errors in the public API surface. 

## What to do

1. Correct spelling errors or check in fixes for the false positives 
1. Opt back into Public API surafe spell checking

## Correct errors

To correct false positives or learn about spell checking see: https://aka.ms/azsdk/engsys/spellcheck

#### Spell Check Output

```
1/1 .\sdk\remoterendering\Azure.MixedReality.RemoteRendering\api\Azure.MixedReality.RemoteRendering.netstandard2.0.cs 991.35ms X
D:\code\azure-sdk-for-net\sdk\remoterendering\Azure.MixedReality.RemoteRendering\api\Azure.MixedReality.RemoteRendering.netstandard2.0.cs:85:110 - Unknown word (Aync)
CSpell: Files checked: 1, Issues found: 1 in 1 files
```

To check the public API surface locally, in the root of the repo run:

```
eng/scripts/Export-API.ps1 -ServiceDirectory remoterendering -SpellCheckPublicApiSurface
```

You may also need to set `-SDKType` if the appropriate value of `SDKType` is not `all` for the service.

## Opt back in

NEW INSTRUCTIONS: In the [`.vscode/cspell.json`](https://github.com/Azure/azure-sdk-for-net/blob/main/.vscode/cspell.json) file remove the line for your service (of the form `"sdk/<service>/*/api/*.cs"`) from the `ignorePaths` section and check in the change. 

OLD INSTRUCTIONS: ~~In the `ci.yml` file for this service, remove the line: `SpellCheckPublicApiSurface: false`~~

**Comment by FlorianBorn71** [comment]
Hi @danieljurek, hi @jsquire  
My team and I took over ownership for the Azure Remote Rendering SDKs, so I'm looking into this one now.
Unfortunately the typo mentioned here is in a function name ('GetConversionsAync'), so fixing this would imply a breaking change.
Do you have any suggestion how to move forward? Maybe adding the correct spelling as well, marking the wrong one as deprecated and remove it at some point in the future?

**Comment by danieljurek** [comment]
I think @AlexGhiondea can help you interface with the right architecture folks for strategies to sort this out. Thanks!

**Comment by jsquire** [comment]
You'll want to speak with @KrzysztofCwalina and @tg-msft, who are the architects for .NET.     Since we do not normally want to include breaking changes, the typical approach that we would use to resolve this would be:

- Move the implementation into a new method with the correct name.
- Update the existing method to delegate to the new method.
- Add `[EditorBrowsable(EditorBrowsableState.Never)]` to the existing method to hide it from Intellisense and docs.   

This has the effect of allowing code using the existing method to continue to work while guiding callers to the new method.   While a motivated individual could call the existing method, since it does not appear in code completion or in documentation, they would either need to know that it exists or be reading it from the source.

That said, I'd recommend discussing with the architects to confirm before taking any action.

**Comment by KrzysztofCwalina** [comment]
It would be worth digging into why our static analysis rule that requires all async methods to end in "Async" did not detect this issue. But yes, we should add a new method, hide the old one, and then obsolete it after a couple of releases.
