### ISSUE TITLE
Add Retry Policy Support to AddAzureKeyVault

### ISSUE THREAD

**Issue by ColKrumpler** [Azure/azure-sdk-for-net#23288]
AddAzureKeyVault does not currently accommodate an exponential backoff retry policy as described in the Azure Key Vault throttling guidance here:

https://docs.microsoft.com/en-us/azure/key-vault/general/overview-throttling

Could the AddAzureKeyVault method be altered to accept a SecretClientOptions parameter or a similar mechanism to handle 429 errors more gracefully?

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by pakrym** [comment]
The AddAzureKeyVault uses the SecretClient that should implement the feature in question.

`AddAzureKeyVault` already has an overload that takes the `SecretClient`:

```
builder.AddAzureKeyVault(new SecretClient(..., new SecretClientOptions());
```

cc @heaths

**Comment by heaths** [comment]
Additionally, if you're getting throttled on application start up, please see a sample we just made available last week that shows how to use App Configuration to store non-secrets with a link to Key Vault for secrets. Key Vault does have low rate limits due to backend hardware, and the configuration providers - especially when using lots of configuration key/value pairs - can cause a lot of pressure against a key vault.

https://docs.microsoft.com/samples/azure/azure-sdk-for-net/app-secrets-configuration/

The service team also recommends using a Key Vault per application, not only to mitigate this class of issues (fewer secrets means fewer calls back to the service to retrieve values) but also to mitigate and isolate the impact of potential credential leaks.

I'm going to mark this issue as addressed, but please feel free to use the `/unresolve` command should you wish to discuss further.

**Comment by ColKrumpler** [comment]
Thank you @pakrym.  After updating to 1.2.1 I was able to apply a retry policy.

@heaths I was able to apply the retry policy to the SecretClient within the App Configuration as well.

**Comment by heaths** [comment]
Glad that worked for you! Can this issue be resolved then?

**Comment by ColKrumpler** [comment]
Yes, please resolve this issue.  Thanks.
