### ISSUE TITLE
[QUERY]KeyVault Certificate/Secret Client- Response for expired certificate

### ISSUE THREAD

**Issue by vijayanand-m** [Azure/azure-sdk-for-net#23321]
**Query/Question**
What will be the response from Certificate /Secret client when a request is issued for expired certificate? 
Consider the certificate in keyvault is expired already and request is made for the certificate.

**Environment:**
 - Azure.security.keyvault.certificate 4.2.0
 -  Azure AppService  .NET Framework 4.8]
 - Visual Studio 2019

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by heaths** [comment]
When creating a certificate, the expiration date is automatically set for the `ExpiresOn` property of the SDKs for both the certificate, public key, and secret (private key). When fetching any of these resources from Key Vault, there is no error response. If you try to use the certificate or key - say, by creating an `X509Certificate2` - it will likely fail because it's expired. The same is true if you try to use the expired public key in calls with the `CryptographyClient` - Key Vault will return an error response.

I'm going to mark this issue as addressed, but please feel free to use the `/unresolve` command should you wish to discuss further.
