### ISSUE TITLE
Set <DocumentationFile> tag in data plane .csproj files

### ISSUE THREAD

**Issue by danieljurek** [Azure/azure-sdk-for-net#23529]
We need a way to set <DocumentationFile> consistently across track 1 csproj files if possible. This may require cleaning up manually specified instances of <DocumentationFile> in .csproj or other files.

Build pipelines should also warn in instances where xml documentation does not make it into the package. 

For example, this csproj is missing a `<DocumentationFile>` entry and does not produce reference documentation: https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/containerregistry/Microsoft.Azure.ContainerRegistry/src/Microsoft.Azure.ContainerRegistry.csproj 

(as describedin this bug: https://github.com/Azure/azure-sdk-for-net/issues/11798)

Some data plane packages already specify this manually in the .csproj file. See this search: https://github.com/Azure/azure-sdk-for-net/search?p=1&q=%3CDocumentationFile%3E&type=

**Comment by kurtzeborn** [comment]
One point of context... this is only for track 1 .csproj files.  We set it globally for track 2 packages and it should not be set in individual .csproj files.

**Comment by ramya-rao-a** [comment]
@kurtzeborn Not having the documentation show up in docs.microsoft.com should not be acceptable for any package regardless of Track 1 or Track 2. Can we have a list of the packages affected this way and log an issue for each? If there are docs errors on any of these packages, can they be surfaced in these issues so that the package owners can fix them?

cc @AlexGhiondea for any additional thoughts

**Comment by AlexGhiondea** [comment]
I thought an issue was logged to enable this in the common props file -- if there are issues in the libraries that are triggered by enabling this in the common file we will fix those.
