### ISSUE TITLE
Convert Batch lib to .NET Core

### ISSUE THREAD

**Issue by jraadt** [Azure/azure-sdk-for-net#2360]
Are there plans to convert Batch lib (nuget: Azure.Batch) to .NET Core?  Many libs have a dependency now for .NETStandard, but Batch is only .NETFramework 4.5.

**Comment by cormacpayne** [comment]
@matthchr Hey Matt, would you mind looking at this issue?

**Comment by darylmsft** [comment]
We do plan to convert the .net assembly to .NET Core.  We do not yet have a date certain for this conversion, however.  We are actively tracking our blocking issues and when they are resolved we will proceed with the conversion.

**Comment by chadwackerman** [comment]
@darylmsft I was forced to rewrite the functions I needed in two hours -- most of which was spent dealing with the incorrect 'how to generate a signature' documentation on MSDN and the absurdly redundant date header. Why this simple library hasn't been ported to .NET Core baffles me. It's not something you can ask the community to do because the code is mostly generated and frankly, total garbage.

**Comment by matthchr** [comment]
This has been ported to netcore now:
https://www.nuget.org/packages/Azure.Batch/

Closing this issue.
-Matt
