### ISSUE TITLE
[QUERY] Azure Search Index Soft Delete Detection

### ISSUE THREAD

**Issue by ssghoda** [Azure/azure-sdk-for-net#23611]
I wanted to know a bit more about the Soft Delete Detection policy and how it works if you could help.

Currently, we have a lot of fields in our Cosmos document structure. We have introduced a new field “IsLogicalDelete” for soft delete purposes. I would like to know how it finds documents in Azure Search Index to mark for soft delete, whether it is just based on this soft delete field, or it also looks for the document key, or it needs all existing fields unchanged. Our upstream process is set up in such a way that it will delete all other fields from the Cosmos document except the id fields. Do you think that is okay or do we need to retain all those fields as well?

Any pointers towards an article or video which explains all this in detail will also be great

**Comment by dereklegenzoff** [comment]
Hi @ssghoda - You should be fine to delete all other fields in the document as long as the `softDeleteColumn` and the `id` field are preserved. You'd also need the `highWaterMarkColumn` to be preserved since we use that to find which documents have been updated but that shouldn't be an issue if you're using `_ts` for that

Essentially, what the indexer does is look for all documents in the database that are newer than then latest `_ts` value we processed. We'll then pull those newer documents and index them, but when the `softDeleteColumn` is set to the `softDeleteMarkerValue`, that tells the indexer to delete the document rather than updating it.

This document will have more details on indexers for Cosmos DB: https://docs.microsoft.com/en-us/azure/search/search-howto-index-cosmosdb

**Comment by ssghoda** [comment]
Thank you @dereklegenzoff for the information. Our upstream process is set up in a way that we were preserving the ID column,  SoftDeleteColumn with marker value, HighWaterMarkColumn which is _ts in our case, and deleting all other custom metadata fields but it was not working so I was concerned whether the Indexer process needs all the document fields.

**Comment by dereklegenzoff** [comment]
Sorry to hear it's not working for you. Please create a support request so we can look into the issue for you: https://docs.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

**Comment by ssghoda** [comment]
Sorry, @dereklegenzoff I figured out the issue. We have a GeoLocation field in the document and while creating the data source, we are checking if the Location field is Valid using ST_ISVALID of Azure Cosmos Db. Upon retaining the Location field, it is working fine now.

**Comment by dereklegenzoff** [comment]
Awesome, glad you got it working!
