### ISSUE TITLE
Method Not Found Exception When Using File Staging

### ISSUE THREAD

**Issue by jmthornton** [Azure/azure-sdk-for-net#2362]
Using Azure.Batch 5.1.1 and WindowsAzure.Storage 7.2.0

The following exception occurs when staging a file:
e.g.
FileToStage ff = new FileToStage("test.txt", stagingStorageAccount);
...
task.FilesToStage = new List<IFileStagingProvider>() { ff };
client.JobOperations.AddTask("job", task);

Method not found: 'System.Threading.Tasks.Task Microsoft.WindowsAzure.Storage.Blob.ICloudBlob.UploadFromFileAsync(System.String, System.IO.FileMode)'.

It appears that the UploadFromFileAsync method signature has changed in the latest version of WindowsAzure.Storage.

**Comment by markcowl** [comment]
@matthchr Can you take a look? Please feel free to assign this elsewhere on the Batch team.

**Comment by matthchr** [comment]
@jmthornton Sorry it took so long to get to this issue. Yes -- the `UploadFromFileAsync` method has changed between 6.* and 7.* versions of the Azure Storage library.

I see a few options:

1. Move back to use Azure Storage 6.* (to match the Batch dll).
2. Stop using the FilesToStage feature and manage the storage files yourself (using the Azure Storage 7.* dll). You can see how we do this in some of our samples, check out [this file](https://github.com/Azure/azure-batch-samples/blob/master/CSharp/Common/SampleHelpers.cs) for example

Sadly an assembly remapping won't work due to the breaking change.

**Comment by matthchr** [comment]
@jmthornton We recently split the FileStaging part out into a separate nuget package: [Azure.Batch.FileStaging](https://www.nuget.org/packages/Azure.Batch.FileStaging/6.0.0) -- you should now be able to use the latest version of storage (8.0.1) with the assembly.

If you want to use an older version (7.* for example) you can try an app.config remapping.
