### ISSUE TITLE
Form Recognizer: Forms with multiple tables on a page have no name property

### ISSUE THREAD

**Issue by vkurpad** [Azure/azure-sdk-for-net#23679]
**Describe the bug**
The REST API returns a list of tables with the key for each table being the table name. The value is the table details. The SDK only contains a list of tables with no name property.

**Expected behavior**
Add an additional table name property for each 

**Actual behavior (include Exception or Stack Trace)**
What is the actual behavior?

**To Reproduce**
Steps to reproduce the behavior (include a code snippet, screenshot, or any additional information that might help us reproduce the issue)

1. Create a custom form model with multiple tables on a single page
2. Analyze the results and the REST API returns a key with the labeled table name but the SDK returns a list of tables with no name property

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by maririos** [comment]
Hi @vkurpad 

It looks like you are calling the `CustomForms` method, right?
I am assuming you are looking at the tables under `RecognizedForm.Pages[i].Tables` where you don't have the table name.

Please note that `RecognizedForm.Pages` contains information about the recognized form elements present in the input document. Here, no labels assigned by the customer are recognized.

In order to access the fields that have labels set by the user when training the model, you need to access the `RecognizedForm.Fields` property and look for the `name` that was assigned to the table, same as you would do with any other field.

For example, if the table name is `Expenses` you could do:
```
foreach (FormField field in form.Fields.Values)
{
    if (field.Name == "Expenses")
    {
        ...
    }
}
```

Here is an example on how to iterate over the table when it is in the Fields section: https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/formrecognizer/Azure.AI.FormRecognizer/tests/samples/Sample15_DifferentiateOutputLabeledTables.cs#L117

Mode information on `RecognizedForm`: https://docs.microsoft.com/en-us/dotnet/api/azure.ai.formrecognizer.models.recognizedform?view=azure-dotnet
