### ISSUE TITLE
[BUG] Incompatibility between Microsoft.Spark and Azure.Messaging.EventHubs

### ISSUE THREAD

**Issue by agaucher** [Azure/azure-sdk-for-net#23710]
**Describe the bug**
Please provide the description of issue you're seeing.

> An error occurs when we try to publish an application containing both the two following dependencies: 
> - Microsoft.Spark
> - Azure.Messaging.EventHubs
>
> It is possible to compile the project, but **an error occurs during the publication phase** (Publish).

**Expected behavior**
What is the expected behavior?

> The "Publish" operation should work.

**Actual behavior (include Exception or Stack Trace)**
What is the actual behavior?

> The 'Publish' operation fails with the following error message:
> 
> """
> Publish has encountered an error.
> Publish has encountered an error. We were unable to determine the cause of the error. Check the output log for more details.
>
> A diagnostic log has been written to the following location:
> "C:\Users\...\AppData\Local\Temp\tmp6A08.tmp"
> """

**To Reproduce**
Steps to reproduce the behavior (include a code snippet, screenshot, or any additional information that might help us reproduce the issue)

1. Create a new .NET 5 project (Console)
2. In the 'Solution Explorer' tab, right click on 'Packages' and 'Manage Nuget packages'
3. Add the two dependencies: "Microsoft.Spark" and "Azure.Messaging.EventHubs"
4. Try to publish the application --> it will fail whatever the parameters that you use

**Environment:**
 - Name and version of the Library package used: [e.g. Azure.Storage.Blobs 12.2.0] 

> - Azure.Messaging.EventHubs 5.4.0
> - Microsoft.Spark 2.0.0

 - Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects): [e.g. Azure AppService or Windows 10 .NET Framework 4.8]

> - Windows 10
> - .NET 5

 - IDE and version : [e.g. Visual Studio 16.3]

> - Visual studio 2019

**Comment by jsquire** [comment]
Hi @agaucher.  Thank you for reaching out and we regret that you're experiencing difficulties.   In order to assist, we'll need to ask for some additional information:

- Is this just a stand-alone console application, or is it intended for a specific hosting platform?
- Where are you trying to publish to?
- What is the specific error being shown in the logs?

**Comment by agaucher** [comment]
Hi @jsquire,

* Is this just a stand-alone console application, or is it intended for a specific hosting platform?

It's just a stand-alone console application.
I just created a .NET 5 console application in C# then I added the two dependencies in the projet.
It's all !
The Publish operation fails whatever the target platform (linux-x64 or win-x64)

* Where are you trying to publish to?

In a folder.

* What is the specific error being shown in the logs?

There is the same message in the log file: "Publish has encountered an error. We were unable to determine the cause of the error. Check the output log for more details."

* Can you help me understand why you believe the error is related to these particular packages?

Because the project is empty, except these two dependencies, and it works when i remove one of them :)

Regards,

**Comment by jsquire** [comment]
Thanks for the additional context.   I'll attempt to repro today.    In the meantime, can you share the contents of the log file that your error message mentioned?

**Comment by jsquire** [comment]
Unfortunately, I don't seem to be able to reproduce this in Visual Studio 2019 v16.11.2.    Our best bet to help get you unblocked will be to understand the details in the log from your IDE.

Based on your context, I did the following:

- Create a new .NET 5 Console application
- Added a reference to `Azure.Messaing.EventHubs` v5.6.0  (latest GA)
- Added a reference to `Microsoft.Spark` v2.0 (latest GA)
- Build in debug (no errors)
- Build in release (no errors)

I'm able to repeatedly publish to a folder with no errors.   The settings that I used are detailed below.   Please let me know if I misunderstood your scenario or overlooked something that would help to reproduce.

![image](https://user-images.githubusercontent.com/913445/131858946-2064a777-ea81-4016-98a9-bd4ab6a489a6.png)

![image](https://user-images.githubusercontent.com/913445/131859005-0274575e-2c9c-4a53-9c49-5c525d1b47a2.png)

![image](https://user-images.githubusercontent.com/913445/131859089-4ff86f24-f928-4cc6-a9f6-56e6f7d78f96.png)

**Comment by jsquire** [comment]
Hi @agaucher.   I was able to reproduce this.    The root cause appears to be the difference in target platforms between the two references, which is causing a package downgrade for the `win-x64` and `linux-x64` publishing targets.   I've included details below, if you're interested.   

The mitigation is to explicitly reference these packages in the application, which takes precedence over the references and ensures a consistent version.  For your scenario, the following is needed:

```xml
  <ItemGroup>
    <!-- Desired Packages -->
    <PackageReference Include="Azure.Messaging.EventHubs" Version="5.6.0" />
    <PackageReference Include="Microsoft.Spark" Version="2.0.0" />

    <!-- Application References for Conflicts -->
    <PackageReference Include="System.Collections" Version="4.3.0" />
    <PackageReference Include="System.Diagnostics.Tracing" Version="4.3.0" />
    <PackageReference Include="System.Diagnostics.Debug" Version="4.3.0" />
    <PackageReference Include="System.Globalization" Version="4.3.0" />
    <PackageReference Include="System.Runtime.InteropServices" Version="4.3.0" />
    <PackageReference Include="System.IO.FileSystem.Primitives" Version="4.3.0" />
    <PackageReference Include="System.Resources.ResourceManager" Version="4.3.0" />
    <PackageReference Include="System.Runtime.Extensions" Version="4.3.0" />
    <PackageReference Include="System.Threading" Version="4.3.0" />
    <PackageReference Include="Microsoft.Win32.Primitives" Version="4.3.0" />
  </ItemGroup>
```

Those additional references allowed me to publish on both the `win` and `linux` targets:

![image](https://user-images.githubusercontent.com/913445/131867929-4bac25f8-f4f8-46b6-9498-b70d726065c1.png)

![image](https://user-images.githubusercontent.com/913445/131868018-a650e54a-050e-4768-bce4-beb42ab47edb.png)

### Next steps

Maintaining compatibility with older .NET frameworks as well as supporting the newer platforms is a core goal of the Azure SDKs.   I'll raise this issue within the Azure SDK team to consider whether we should also explicitly target `netstandard2.1` to mitigate this scenario.   

### Details

Because `Microsoft.Spark` has a `netstandard2.1` target, that is preferred by an application using `net5.0`.    The Azure SDKs support a `netstandard2.0` target to maintain compatibility with older frameworks as well as supporting .NET 5.  It seems that the `win` and `linux` targets use a different set of system packages for `netstandard2.1` then they do for `netstandard2.0`.

I was able to diagnose this using the Build output from Visual Studio, which noted the version downgrades:

```text
2>Determining projects to restore...
2>Detected package downgrade: System.Runtime.InteropServices from 4.3.0 to 4.1.0. Reference the package directly from the project to select a different version.
2> TestPublish -> Azure.Messaging.EventHubs 5.6.0 -> Microsoft.Azure.Amqp 2.5.1 -> System.Net.WebSockets.Client 4.0.2 -> Microsoft.Win32.Primitives 4.0.1 -> runtime.unix.Microsoft.Win32.Primitives 4.3.0 -> System.Runtime.InteropServices (>= 4.3.0)
2> TestPublish -> Azure.Messaging.EventHubs 5.6.0 -> Microsoft.Azure.Amqp 2.5.1 -> System.Net.WebSockets.Client 4.0.2 -> System.Runtime.InteropServices (>= 4.1.0)
2>Detected package downgrade: Microsoft.Win32.Primitives from 4.3.0 to 4.0.1. Reference the package directly from the project to select a different version.
2> TestPublish -> Azure.Messaging.EventHubs 5.6.0 -> Microsoft.Azure.Amqp 2.5.1 -> System.Net.WebSockets.Client 4.0.2 -> System.Net.Primitives 4.0.11 -> runtime.unix.System.Net.Primitives 4.3.0 -> Microsoft.Win32.Primitives (>= 4.3.0)
2> TestPublish -> Azure.Messaging.EventHubs 5.6.0 -> Microsoft.Azure.Amqp 2.5.1 -> System.Net.WebSockets.Client 4.0.2 -> Microsoft.Win32.Primitives (>= 4.0.1)

... << SNIP >> ...
```

To mitigate, each of those downgrades were hoisted to an application reference to explicitly force the higher version.

**Comment by jsquire** [comment]
I'm going to mark this as addressed.   Please feel free to use the "`/unresolve`" command if you'd like to continue the discussion.

**Comment by agaucher** [comment]
Thank your for your investigation !

It's not a blocking point for me: i will finally use the Confluent.Kafka library to publish and consume the EventHub notifications.

But it would be better to fix that for other potential users.

Best regards,

Alexis Gaucher
