### ISSUE TITLE
[QUERY] Improve Azure.Identity docs for in-memory token caching behavior

### ISSUE THREAD

**Issue by loic-sharma** [Azure/azure-sdk-for-net#23726]
The links to the API reference docs on the Azure.Identity README are broken here: https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/identity/Azure.Identity/README.md#authenticating-azure-hosted-applications

I would like to use `DefaultAzureCredential` and `ClientSecretCredential` in my client app to manually create AAD access tokens to authenticate to my own service. Both [`DefaultAzureCredential.GetTokenAsync`'s documentation](https://github.com/Azure/azure-sdk-for-net/blob/8383d4959a3e8089b160278ca1b5e851c5c1d7ff/sdk/identity/Azure.Identity/src/DefaultAzureCredential.cs#L105) and [`ClientSecretCredential.GetTokenAsync`'s documentation](https://github.com/Azure/azure-sdk-for-net/blob/3c0bce5293846a18ec1fbe09c3e1d1a121a0d164/sdk/identity/Azure.Identity/src/ClientSecretCredential.cs#L105) mention that the caller must handle token caching and token refreshing:

> You may call this method directly, but you must also handle token caching and token refreshing.

What does that entail?

The [SDK guidelines for authentication](https://azure.github.io/azure-sdk/dotnet_introduction.html) recommend calling `TokenCredential.GetToken()` before each service request, however it does not mention needing to cache tokens from credentials. Also, [this sample](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/identity/Azure.Identity/samples/TokenCache.md#persisting-credentials-by-configuring-tokencachepersistenceoptions) indicates tokens are cached in memory by default. Additionally, the logs outputted when calling `GetTokenAsync` repeatedly indicates that tokens are indeed cached. If so, how long are these tokens cached for? Do I need to do any additional caching on top of `DefaultAzureCredential.GetTokenAsync()`'s and `ClientSecretCredential.GetTokenAsync()`'s default in-memory caching?

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team members best able to assist.

**Comment by christothes** [comment]
Hi @loic-sharma - 

> The links to the API reference docs on the Azure.Identity README are broken here: https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/identity/Azure.Identity/README.md#authenticating-azure-hosted-applications

I tried the 4 credential links in that section and they all seem to work. Which ones were you finding to be broken?

> > You may call this method directly, but you must also handle token caching and token refreshing.
> 
> What does that entail?

We don't provide specific guidance on token caching because it depends on your specific scenario. But, in general, whatever implementation you use to cache would check the cached token for expiration and use the cached token in your service request if it is not expired. If it is, a call to GetToken is required to get a new token and refresh the cache. You would not call GetToken unless your caching strategy determined that a new token is required. Depending on your specific scenario, understanding whether a cached token is valid for the request can be complex. For example, does the request require the same scope(s), claims, or some valid subset of the ones requested for the cached token.

> The [SDK guidelines for authentication](https://azure.github.io/azure-sdk/dotnet_introduction.html) recommend calling `TokenCredential.GetToken()` before each service request, however it does not mention needing to cache tokens from credentials. Also, [this sample](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/identity/Azure.Identity/samples/TokenCache.md#persisting-credentials-by-configuring-tokencachepersistenceoptions) indicates tokens are cached in memory by default. Additionally, the logs outputted when calling `GetTokenAsync` repeatedly indicates that tokens are indeed cached. If so, how long are these tokens cached for? Do I need to do any additional caching on top of `DefaultAzureCredential.GetTokenAsync()`'s and `ClientSecretCredential.GetTokenAsync()`'s default in-memory caching?

It's a bit nuanced, but that sample mentioned that "**Many** credential implementations in the Azure.Identity library have an underlying token cache". 

Only `TokenCredential` implementations that use MSAL in their GetToken implementations cache tokens. In practice, this tends to mean that any of the development time credentials like VisualStudio, VisualStudioCode, Azure CLI, and Azure PowerShell do not cache by default. 

So as to whether or not you need to do any additional caching depends on which credential is ultimately selected by the `DefaultAzureCredential` which is why the general guidance is to not rely on automatic caching.

**Comment by loic-sharma** [comment]
Thank you for the detailed answer, much appreciated!

> > The links to the API reference docs on the Azure.Identity README are broken here: https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/identity/Azure.Identity/README.md#authenticating-azure-hosted-applications
> 
> I tried the 4 credential links in that section and they all seem to work. Which ones were you finding to be broken?

Weird, the links are working for me as well now. Yesterday these all 404ed for me:

* https://docs.microsoft.com/en-us/dotnet/api/azure.identity.defaultazurecredential?view=azure-dotnet
* https://docs.microsoft.com/en-us/dotnet/api/azure.identity.chainedtokencredential?view=azure-dotnet
* https://docs.microsoft.com/en-us/dotnet/api/azure.identity.managedidentitycredential?view=azure-dotnet
* https://docs.microsoft.com/en-us/dotnet/api/azure.identity.environmentcredential?view=azure-dotnet

> It's a bit nuanced, but that sample mentioned that "**Many** credential implementations in the Azure.Identity library have an underlying token cache".
> 
> Only `TokenCredential` implementations that use MSAL in their GetToken implementations cache tokens. In practice, this tends to mean that any of the development time credentials like VisualStudio, VisualStudioCode, Azure CLI, and Azure PowerShell do not cache by default.

For the implementations that do cache tokens, do you think it would make sense to update their XML docs to reflect this? The current docs on these implementation appear to contradict the actual implementation: `You may call this method directly, but you must also handle token caching and token refreshing`
