### ISSUE TITLE
Installation check should do retries

### ISSUE THREAD

**Issue by pakrym** [Azure/azure-sdk-for-net#23739]
When multiple packages are released from the same pipeline and one depends on another Azure.Core.Experimental -> Azure.Core I tend to kick off both releases at the same time. This causes the `Installation Check` to fail for `Azure.Core.Experimental` because `Azure.Core` is just being published.

I think we should loop and try to restore for some time (30m?) before failing the step.

**Comment by benbp** [comment]
@ckairen FYI this is related to the ordering you introduced for java. I think I like the eventual approach @pakrym is proposing here better, since it will make releases easier to kick off in the background.

I think we should see if we can find a way to determine whether there is a package we expect to be published before retrying, so we don't stall the release for no reason and make people wait. This might not be possible as I don't think agents have any way to communicate values with each other while running, and additionally I don't know of a way to have a deployment job auto-retry (e.g. schedule to a new agent which would pick up a new variable context).

**Comment by benbp** [comment]
@pakrym I'm marking this `needs-triage` just so it comes across for @kurtzeborn, @weshaggard and I in our weekly triage.

**Comment by jsquire** [comment]
Adjusting tags so that the reports don't yell at me.

**Comment by weshaggard** [comment]
@benbp is a retry loop similar to what @ckairen did in python enough here, so retry in the install check and not the full job.
