### ISSUE TITLE
[BUG] Improve XML doc comments for KeyVault methods

### ISSUE THREAD

**Issue by AlexGhiondea** [Azure/azure-sdk-for-net#23820]
There is an expected difference between these two methods:

* Azure.Security.KeyVault.Certificates.CertificateClient.GetPropertiesOfCertificateVersions()
* Azure.Security.KeyVault.Secrets.SecretClient.GetPropertiesOfSecretVersions()

One returns only enabled certificates while the other only returns both enabled and disabled secrets.

We should consider improving the XML doc comments around this.

**Comment by heaths** [comment]
I was able to repro this in Postman and both return enabled and disabled resources and they should, by default. As a REST client, we generally don't want to hide such details from the users. Disabled resources can still be useful - like an old, expired certificate or key (certificate private keys are stored as secrets) to decrypt something that was encrypted before it was expired/disabled.

We could add filtering logic, but we haven't done this to date in the SDK outside of passing fields to an OData `$filter` query param, to my knowledge. It's easy enough for the user to filter out disabled or managed secrets.

We can and should, however, do a better job of explaining this in samples if not the README. E.g. I could see adding something to the certificates README about how it uses keys and secrets for some aspects of storage as "managed" keys and secrets that they might want to otherwise filter out if using a Key Vault for numerous resources.
