### ISSUE TITLE
[QUERY]KeyVault secrets caching- using keyvaultproxy

### ISSUE THREAD

**Issue by vijayaz** [Azure/azure-sdk-for-net#23861]
**Query/Question**
I am trying cache the response from keyvault sdk. I understand keyvaultproxy in the samples provide an option to cache the response in  HttpPipelinePolicy.  Can I use keyvaultproxy reference for my production grade application. since the keyvault proxy reference says it is just an sample. 

**Environment:**
 - Azure.Security.KeyVault.Secrets;[4.2.0] / AzureSamples.Security.KeyVault.Proxy
 - Azure AppService .NET Framework 4.8
 - Visual Studio 2019

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by heaths** [comment]
@vijayaz that's really up to you and your team. It is only a sample, as you pointed out, but it straight forward enough for a simple, effective in-memory cache. It's main purpose was to demonstrate how you could cache results, though that could be to Redis, disk, or any storage medium. We've not done any stress testing on it, though.

I'm going to mark this issue as addressed because it's really a matter of opinion, but please feel free to use the `/unresolve` command should you wish to discuss further.

**Comment by vijayaz** [comment]
> @vijayaz that's really up to you and your team. It is only a sample, as you pointed out, but it straight forward enough for a simple, effective in-memory cache. It's main purpose was to demonstrate how you could cache results, though that could be to Redis, disk, or any storage medium. We've not done any stress testing on it, though.
> 
> I'm going to mark this issue as addressed because it's really a matter of opinion, but please feel free to use the `/unresolve` command should you wish to discuss further.

Thank you for answering @heaths . It helps making some decision.
