### ISSUE TITLE
Sign JWT token using Azure Key Vault

### ISSUE THREAD

**Issue by dracan** [Azure/azure-sdk-for-net#23919]
Hi. Apologies if it's bad form to link straight to my StackOverflow question - I thought I'd save on the duplication. I'm happy to copy across the content if that's preferred.

Basically, I'm having trouble signing a JWT via Azure Key Vault. It works fine if I don't use Azure Key Vault. I put code example and full description in the Stackovlow question...

https://stackoverflow.com/questions/69117288/sign-jwt-token-using-azure-key-vault

**Environment:**
 - Name and version of the Library package used: Azure.Security.KeyVault.Keys 4.2.0
 - Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects): LINQPad 6 (which I believe is .NET 5 runtime)
 - IDE and version : LINQPad 6

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by dracan** [comment]
Great thanks. I'm sure it must be something stupid that I'm doing. But can't think what. Any help is greatly appreciated :)

**Comment by heaths** [comment]
I [replied](https://stackoverflow.com/a/69126059/462376). You were pretty close, though use either UTF8 or ASCII (better since it's already base64url-encoded and you avoid any BOM concerns) to encode the header and payload.

I wrestled with this myself quite a bit and had @schaabs look it over who worked on Key Vault. Ultimately, the problem I had was with https://jwt.io itself. Since you blurred the public key, I can't tell if you did the same thing, but the common "BEGIN PUBLIC KEY" PEM label didn't work. It has to be "BEGIN RSA PUBLIC KEY". "BEGIN CERTIFICATE" worked fine.

I posted both sample solutions I tried.

I'm going to mark this issue as addressed, but please feel free to use the `/unresolve` command should you wish to discuss further.

**Comment by dracan** [comment]
@heaths - that's amazing, it worked! :) It was literally just the changing from `Encoding.Unicode.` to `Encoding.ASCII.` that fixed it for me. Amazing how a single word can cause so many problems! The public keys that I pasted into jwt.io were all `-----BEGIN CERTIFICATE-----`, but I think that was fine. The tokens also weren't working against the endpoint I was trying to authenticate against either - so it wasn't just jwt.io. Using `Encoding.ASCII`, it all works perfectly! Thank you so much for your help with this :)

**Comment by heaths** [comment]
Great!

FWIW, one thing I've learned over the years is that Windows-based APIs are often Unicode, i.e. wide chars, but industry standards more often tend to be UTF-8 based - JWTs and the family included. `Encoding.UTF8` is *technically* correct in this case, but there's the potential for more processing involved when, because the value is base64url-encoded, you know all the characters are ASCII already.
