### ISSUE TITLE
Azure Event Hub - How to consume events parallelly using the official SDK?

### ISSUE THREAD

**Issue by Leonardo-Ferreira** [Azure/azure-sdk-for-net#23939]
**Describe the bug**
I've setup the following test:

- Created a azure event hub with 10 partitions
- Created a single storage account
- Created a single consumer group
- Filled the hub with 10k messages
- Created 2 containers (on AKS) that would basically consume those events (using the same consumer group) and log them azure application insights.

**Expected behavior**
Running 
```
traces
| where message == "Event received"
| summarize count() by bin(timestamp,1s), cloud_RoleInstance
| render timechart 
```
I was expecting to see something like:
![Screen Shot 2021-09-09 at 17 17 06](https://user-images.githubusercontent.com/5585339/132874744-b551005a-f8d0-4405-94a4-83f3e7049ed8.png)

**Actual behavior**
What is the actual behavior?
![Screen Shot 2021-09-10 at 10 52 05](https://user-images.githubusercontent.com/5585339/132874774-79ffb39f-e88c-4662-a5a1-4045809d758b.png)

(red line is pod 1, blue line is pod 2)
this is a 3x 10k run, to eliminate the "pod was not warmed up" variable

**To Reproduce**
```csharp
protected override async Task ExecuteAsync(CancellationToken stoppingToken)
{
    _processor = new EventProcessorClient(_storageClient, _consumerGroup, _hubConnection, _eventHubName);
    _processor.ProcessEventAsync += ProcessEventHandler;
    _processor.ProcessErrorAsync += ProcessErrorHandler;

    // Start the processing
    await _processor.StartProcessingAsync(stoppingToken);
}

internal async Task ProcessEventHandler(ProcessEventArgs eventArgs)
{
    _logger.LogTelemetry("Event received");

    await eventArgs.UpdateCheckpointAsync(eventArgs.CancellationToken);
}
```

**Environment:**
 - "Azure.Messaging.EventHubs" Version="5.6.1"
 - "Azure.Messaging.EventHubs.Processor" Version="5.6.1"
 - Pod image: mcr.microsoft.com/dotnet/runtime:5.0
 - AKS, Kube version 1.19.7

**Comment by jsquire** [comment]
Hi @Leonardo-Ferreira.  We regret that you're experiencing difficulties, and appreciate you being willing to shift from Stack Overflow over to an issue so that we can better dig in to assist.  To start, I'm going to bring over my questions/observations from the SO question:

### Open Questions

- `ExecuteAsync` will exit immediately once the processor starts; if something else is not blocking to keep the host process alive, it may be terminating.    Can you confirm that the process isn't terminating after `ExecuteAsync` returns?

- `_logger` will be called concurrently by different threads.  Can you confirm that it is thread-safe and that there's nothing shared between the containers for it?

- `ProcessEventHandler` is not accounting for exceptions; if it throws, the task responsible for processing the partition will fault.  Depending on your host environment, it may be restarted or the host process may crash.  Can we wrap that in a try/catch and log for any further testing that we do?

- Often when we see these types of issues with a container-based host, it comes down to the network configuration.  Are you willing to test by running two instances of your host application locally and taking AKS out of the mix?

- Can you share the code that illustrates how you're publishing the events?

### Next Steps

It would be helpful to run the test again with some adjustments:

#### Ensure more events are available

Given the configuration that you're describing, we'll probably want to measure over at least a 10 minute span to see the progression of things, which means that we'll also likely want to seed the partitions with 250,000 events or more, so that each partition has at least 25k.   

#### Configure the handler to run when no events are available in a partition

For this, we'll need to set the `MaximumWaitTime` [option](https://docs.microsoft.com/dotnet/api/azure.messaging.eventhubs.eventprocessorclientoptions.maximumwaittime) so that we'll continue to see the event handler get pinged if there are no events for a given partition.  This [sample](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/eventhub/Azure.Messaging.EventHubs.Processor/samples/Sample04_ProcessingEvents.md#heartbeat-while-processing-events) illustrates.

#### Capture SDK logs

It would also be helpful to capture the logs that the SDK is emitting, so that we can understand what it is seeing.  The logs are emitted as ETW events; the easiest way to hook them is to use the `AzureEventSourceListener`.    There's a [sample](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/eventhub/Azure.Messaging.EventHubs/samples/Sample10_AzureEventSourceListener.md#apply-filtering-logic-to-logs) that demonstrates using the listener with the Event Hubs SDK, which may come in handy.

We'll need to set the `LogLevel` to `Verbose`, which emits a large volume of logs, so  filtering down to the following set would help us focus on the important ones: 

**Event Source Name:  “Azure-Messsaging-EventHubs”**
-	6 (Event Receive Start)
-	7 (Event Receive End)
-	8 (Event Receive Error)
-	36 (Event Processor Task Error)
-	37 (EventProcessorPartitionProcessingStart)
-	38 (EventProcessorPartitionProcessingStartError)
-	39 (EventProcessorPartitionProcessingStartComplete)
-	40 (EventProcessorPartitionProcessingStop)
-	41 (EventProcessorPartitionProcessingStopError)
-	42 (EventProcessorPartitionProcessingStopComplete)
-	43 (EventProcessorParitionProcessingError)
-	44 (EventProcessorLoadBalancingError)
-	45 (EventProcessorClaimOwnershipError)

**Event Source Name:  “Azure-Messaging-EventHubs-Processor-PartitionLoadBalancer”**
-	2 (CurrentOwnershipCount)
-	4 (ClaimOwnershipStart)
-	5 (ClaimOwnershipError)
-	8 (RenewOwnershipStart)
-	9 (RenewOwnershipError)
-	10 (RenewOwnershipComplete)

**Event Source Name:  “Azure-Messaging-EventHubs-Processor-BlobEventStore”**
-	26 (ClaimOwnershipError)
-	27 (OwnershipNotClaimable)
-	34 (UpdateCheckpointError)
-	35 (InvalidCheckpointFound)
-	37 (GetCheckpointComplete)
-	38 (GetCheckpointError)

**Comment by Leonardo-Ferreira** [comment]
Hi @jsquire, tks for the assistance... lets go with the answers I have right away:
 - I can confirm that the process is not terminating and that the pod is alive (application insights continues to capture mim/cpu uninterruptedly)
 - yes `_logger` is thread safe, but in this case, it doesn't matter that much because the whole point of the application is to consume this event hub and log it...
 - All the relevant code is actually wrapped on a try/catch. The caught exceptions are logged to app insights.  Application insights or any other monitoring tool (pod console logs for example) are not reporting any exceptions of any kind. The pods are not reporting restarting events also. At the time of this writing, the pods have been running for 21 hours without any kind of restart.
 - yes I can try running 2 instances locally. I will get back with the results asap
 - the code for publishing the events is:
```
Task.Run(async () =>
{
    var producerClient = new EventHubProducerClient(_connectionString, _eventHubName);
    var rdn = new Random();
    var eventBatch = await producerClient.CreateBatchAsync();
            
    for (int i = 0; i < 10000; i++)
    {
        eventBatch.TryAdd(new EventData(Encoding.UTF8.GetBytes(JsonConvert.SerializeObject(new
        {
            Origin = "System A",
            Ip = "192.168.124.124",
            Port = rdn.Next(1, 64999),
            Login = "teste@teste.com",
            Before = JsonConvert.SerializeObject(new { A = "A", B = "B" }),
            After = JsonConvert.SerializeObject(new { A = "C", B = "D" }),
            Timestamp = DateTime.Now,
            Action = "Login"
        }))));
        if (i % 250 == 0)
        {
            await producerClient.SendAsync(eventBatch);
            eventBatch = await producerClient.CreateBatchAsync();
        }
    }
    await producerClient.SendAsync(eventBatch);
    Console.WriteLine("Done");
}).Wait();
```

**Comment by Leonardo-Ferreira** [comment]
good news! as recommended I ran a batch of 500k events and after a initial hick-up (yes pods were warm and running for over 23h) I got this:
![Screen Shot 2021-09-10 at 16 03 41](https://user-images.githubusercontent.com/5585339/132904502-d4b860ba-acce-4a51-a3c1-2d0cc84ee58e.png)
We can see a good amount of intertwining and low-medium fluctuation on the flow of events but everything seems to be OK...

I think that the only question left now is "Why dont we see this behavior with 10k batches?"... and I mean, 10k events sitting around w8ing to be processed is not a "ignorable number"

**Comment by jsquire** [comment]
good news! 

Glad to hear.  😄 

> I think that the only question left now is "Why dont we see this behavior with 10k batches?"... and I mean, 10k events sitting around w8ing to be processed is not a "ignorable number"2

With 10k events, you were only publishing 1,000 to each partition, which would be consumed in ~4 batches.   Since the `MaximumWaitTime` wasn't set in your options, the processor would stop pinging your handler, even though it was still attempting to read/dispatch events.

I suspect that the timing that you were seeing was coincidental due to natural latency in establishing connections and similar at startup;  one processor was just getting its ownership more quickly and ran out of events to process before both were stable.   By using a greater number of events, we avoided starvation and the processors each had work to do for long enough that they both hit ownership stability.

I had thought this may be what we were seeing, based on the second and third runs in your initial graph show a very slight overlap.   Each of the three graphs also showed different timing which seemed to indicate there was some variance in overhead from run-to-run.   If we had things blocking each other, I'd have expected that  gap to be fairly consistent.

I'm going to mark this addressed, but please feel free to use the "`/unresolve`" command if you'd like to continue the discussion.
