### ISSUE TITLE
[BUG] Event Hub - EventProcessorClient - partitions are changing very often

### ISSUE THREAD

**Issue by petrformanek** [Azure/azure-sdk-for-net#23956]
**Describe the bug**
We use `EventProcessorClient` to consume events from the event hub.
The event processing runs on 8 instances and event hub has 32 partitions.
I can see in logs that partitions are changing the processing instances very often. One partition change the processing instance 17 times per hour.
There is no reason to change the instance as the amount of processing instances is stable all the time.
I observed the behavior in version 5.4.1. I updated to 5.6.1 as there were some bug fixes related to balancing but the issue is not fixed.

**Expected behavior**
Partitions should stay on the same processing instance after initial load balancing.

**Actual behavior (include Exception or Stack Trace)**
See description.

**To Reproduce**
See description. 
Sample of consumer:
```csharp
var clientOptions = new EventProcessorClientOptions()
{
    MaximumWaitTime = TimeSpan.FromMilliseconds(150),
    LoadBalancingStrategy = LoadBalancingStrategy.Greedy
};

var eventProcessorClient = new EventProcessorClient(blobContainerClient,
                consumerGroupName, eventHubConnectionString, eventHubOptions.HubName, clientOptions);

```
We use the Greedy strategy to reduce delays in processing during service restarts.

**Environment:**
 - Azure.Messaging.EventHubs.Processor 5.6.1
 - .NET 5/Linux container running in Kubernetes
 - We use premium BLOB storage for the checkpoint store.

**Comment by jsquire** [comment]
Hi @petrformanek.   Thank you for your feedback and we regret that you're experiencing difficulties.  Once initially stabilized, there are only two scenarios that would cause partition ownership to change: 

1) The number of processors configured for that Event Hub, Consumer Group, and Storage container have changed  (scale up/down)
1) A processor has failed to update any of its ownership records for owned partitions within the ownership interval and the other processors see it as dead.

To dig in, it would help to understand:

- What is the approach that you're using to observe partition ownership changes?

- Can you share the host machine details?  In particular, we're interested in the number of cores and any network-related budgets that may be applied.

- Are you seeing K8s recycle nodes to move them around or recover from crashes?  Each time a node stops and is restarted, the processors are likely to see that as a scaling activity, where processor leaves and a new processor joins the group. 

- What is your error handler seeing during these periods?  

It would also be helpful to capture the logs that the SDK is emitting, so that we can understand what it is seeing.  The logs are emitted as ETW events; the easiest way to hook them is to use the `AzureEventSourceListener`.    There's a [sample](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/eventhub/Azure.Messaging.EventHubs/samples/Sample10_AzureEventSourceListener.md#apply-filtering-logic-to-logs) that demonstrates using the listener with the Event Hubs SDK, which may come in handy.

We'll need to set the `LogLevel` to `Verbose`, which emits a large volume of logs, so  filtering down to the following set would help us focus on the important ones: 

**Event Source Name:  “Azure-Messsaging-EventHubs”**
-	6 (Event Receive Start)
-	7 (Event Receive End)
-	8 (Event Receive Error)
-	36 (Event Processor Task Error)
-	37 (EventProcessorPartitionProcessingStart)
-	38 (EventProcessorPartitionProcessingStartError)
-	39 (EventProcessorPartitionProcessingStartComplete)
-	40 (EventProcessorPartitionProcessingStop)
-	41 (EventProcessorPartitionProcessingStopError)
-	42 (EventProcessorPartitionProcessingStopComplete)
-	43 (EventProcessorParitionProcessingError)
-	44 (EventProcessorLoadBalancingError)
-	45 (EventProcessorClaimOwnershipError)

**Event Source Name:  “Azure-Messaging-EventHubs-Processor-PartitionLoadBalancer”**
-	2 (CurrentOwnershipCount)
-	4 (ClaimOwnershipStart)
-	5 (ClaimOwnershipError)
-	8 (RenewOwnershipStart)
-	9 (RenewOwnershipError)
-	10 (RenewOwnershipComplete)

**Event Source Name:  “Azure-Messaging-EventHubs-Processor-BlobEventStore”**
-	26 (ClaimOwnershipError)
-	27 (OwnershipNotClaimable)
-	34 (UpdateCheckpointError)
-	35 (InvalidCheckpointFound)
-	37 (GetCheckpointComplete)
-	38 (GetCheckpointError)

**Comment by petrformanek** [comment]
Hi @jsquire,
I will come with more detail later.
For now I can give these observations:
- there are no restarts of K8s instances
- there are no exceptions
- CPU request for K8s is set to 200m cores and CPU limit is set to 1100m cores (it causes that .NET considers it as 2 cores CPU)
- on production environment we have 8 fixed instances connected to event hub with 32 partitions - partitions are initializing and closing very frequently like 10 time per hour
- on testing environment we have 2 instances connected to event hub with 32 partitions - partitions distribution is stable as expected
- the only difference between production and testing environment is a number of instances

**Comment by petrformanek** [comment]
Hi @jsquire,
it seems that issue is with the lease blob storage which has a very high latency and very slow ListBlob operation. A month ago someone turned on "soft delete" on all storages in our subscription to "improve" security.
I turned it off. 
Lets wait a couple of days until the latency improves whether the issue disappear.

Thanks

**Comment by jsquire** [comment]
Hi @petrformanek.    Thanks for the additional context.   High latency in storage would certainly cause the behavior that you're seeing.  Turning off soft delete is a good start; if that turns out to not be adequate, you may wish to consider adjusting your `LoadBalancingInterval` and `PartitionOwnershipExpirationInterval` values in the options that you pass your `EventProcessorClient` to compensate for the storage latency.  There's some discussion of these values [here](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/eventhub/Azure.Messaging.EventHubs.Processor/samples/Sample02_EventProcessorConfiguration.md#load-balancing-intervals).

> Lets wait a couple of days until the latency improves whether the issue disappear.

Sounds good.   I'm going to mark this as addressed in the meantime, which will leave it open for 7 days.  If at any point you wish to continue the discussion, just use the "`/unresolve`" command.
