### ISSUE TITLE
[FEATURE/PERFORMANCE] Better Token Caching for ManagedIdentityCredential

### ISSUE THREAD

**Issue by karshinlin** [Azure/azure-sdk-for-net#24046]
**Library or service name.**
Azure.Core, Azure.Identity, Azure.Storage, Azure.EventHubs, Azure.ServiceBus

**Is your feature request related to a problem? Please describe.**
When using Managed Identity, a network call is made to obtain an AAD token used to access an Azure service (i.e. Storage, Service Bus, etc.). Caching of the tokens at the library level is critical to performance and stability of the Managed Identity framework. Looking at the different Azure service clients, caching is inconsistent and can lead to unnecessarily high traffic on Managed Identity dependencies (i.e. Token Service on App Service, IMDS on Azure VMs). Recently, we have seen high traffic on Token Services in the order of thousands of requests per minute - caching in the SDK could drastically reduce the number of calls (already seen with some customers after a design review of their code). This adds resiliency to Managed Identity, especially in the event of an AAD or internal Azure infrastructure outage. 

In Azure storage libraries today, caching is done per client (i.e. per BlobContainerClient, BlobClient, QueueClient). This is done through the BearerTokenAuthenticationPolicy in Azure.Core.
When using DefaultAzureCredential directly (for ManagedIdentityCredential), caching is not done at the credential level here. Customers who use these credentials directly often shoot themselves in the foot since caching should be abstracted from them.
~~In Azure Event Hub library, I don't think token caching is done - EventHubTokenCredential is just passthrough object to the DefaultAzureCredential which leverages ManagedIdentityCredential (no caching).~~

Possible options:
1. Caching is performed at the TokenCredential level
    - A DefaultAzureCredential would maintain a ManagedIdentityCredential that has it's own token cache 

2. Static variables 
    - Can the token cache in BearerTokenAuthenticationPolicy be made static? 
    - This is helpful for scenarios like Azure Functions and WebJobs that can have thousands of requests per minute with different clients instantiated in customer code, leading to thousands of requests to underlying token services downstream without a static cache.
    - A static cache here would mean consumers of the SDK don't have to think about caching (it just comes out of the box like a static http client).

The goal of this is to reduce the dependency on retrieving tokens through networking calls. In the context of Azure Functions or WebJobs, we have seen abnormally high number of requests that lead to load issues. This can cause customer application downtime.

**Comment by jsquire** [comment]
@karshinlin:  Would you please be so kind as to leave the issues untagged other than `needs-triage` when filing them so that the Azure SDK team can triage?

**Comment by karshinlin** [comment]
> @karshinlin: Would you please be so kind as to leave the issues untagged other than `needs-triage` when filing them so that the Azure SDK team can triage?

Certainly! Noted for future reference too.

**Comment by jsquire** [comment]
With respect to Event Hubs and Service Bus, as an AMQP services, authorization is not performed per-request like it is for HTTP-based services.   Instead, authorization is sent in the background over a dedicated AMQP link as the credential is nearing expiration.  

Both perform caching of Identity-based credentials as part of their CBS token providers to ensure that a single token is requested and then used across active links as authorization is needed.

**Comment by xinyi-joffre** [comment]
+1 for this! We also migrated recently to use ManagedIdentityCredential for our EventHubClient connections, but ran into a growing number of SocketExceptions and NetworkTimeouts because this was causing so many token service requests to the local network for our App Service in App Service Environment. Today, App Service cannot handle many, many requests to MSI GetToken, so it would be a huge help if Azure.Identity could guarantee some amount of caching.

We also saw this with the Blob SDK w/ MSI which was also calling out at least once a minute to get a token, and sometimes failing, which led to less reliability than we can usually count on with the connection string methods.

**Comment by xinyi-joffre** [comment]
@christothes , do you know if an AMQP based client will share a connection for multiple EventHubReceiverClients? Or if each one is initiating the call (and causing a token call)?

We rolled back our MSI change and our network stabilized after that. It's probably a combination of our use case w/ orleans and the lack of token caching, but App Service team said they saw upwards of 30 requests per second against their token service at one point.

**Comment by christothes** [comment]
I'll let @jsquire comment on the specifics, since this is his area of expertise but I suspect if your use case it to create many clients, you'd get a token request for each instance.

**Comment by jsquire** [comment]
@xinyi-joffre:  With respect to connection sharing, the answer for Event Hubs and Service Bus is:  "it depends on how you create them."   Generally speaking, any type with the `Client` suffix is intended to represent an independent connection to the service.   However, in Event Hubs it is possible to create a client by passing an existing `EventHubConnection`, which enables sharing.   

For the Orleans use case, depending on which version is in use, you may be using `Azure.Messaging.EventHubs` or the legacy `Microsoft.Azure.EventHubs` package.  The details differ a bit, but the result is the same: 

  - In the v3.5 branch and `main`, Orleans is using `Azure.Messaging.EventHubs` and creating the `PartitionReceiver` as a stand-alone instance - which means that it will spawn and own a dedicated connection.  _([src](https://github.com/dotnet/orleans/blob/main/src/Azure/Orleans.Streaming.EventHubs/Providers/Streams/EventHub/IEventHubReceiver.cs#L50))_.   
  
  - In the v3.4.3 branch, Orleans is using `Microsoft.Azure.EventHubs` and is creating a new `EventHubClient` to spawn each `PartitionReciever`, which also ensures each will use a dedicated connection.  _([src](https://github.com/dotnet/orleans/blob/3.4.3/src/Azure/Orleans.Streaming.EventHubs/Providers/Streams/EventHub/EventHubAdapterReceiver.cs#L274))_.

> orleans and the lack of token caching, 

I'm not sure that I understand the inference, and I question its accuracy.  Assuming that the version of Orleans that you're using references the `Azure.Messaging.EventHubs` package, the Event Hubs clients do not send a token with each service request.  The token is sent only when a connection/link is created and then ~10 minutes before the token is set to expire.   The version of the Event Hubs SDK that Orleans is currently referencing is about 8 months old  _([src](https://github.com/dotnet/orleans/blob/main/Directory.Build.props#L71))_ and does lack token caching -  but, that would only be impactful if `PartitionReciever` instances are being created often or there are connectivity issues that require them to reconnect often.

> but App Service team said they saw upwards of 30 requests per second against their token service at one point.

Again, assuming the current generation of Event Hubs, this wouldn't happen under normal operation; the expiration of tokens is calculated using some random jitter to ensure that there is no thundering herd of requests due to mass expiration.   This would only be possible if:  

- You have 30 or more partitions for your Event Hub

- Orleans created 30+ `PartitionReceivers` and invoked a service operation on each of them within the same exact second  OR  the connection for each existing `PartitionReceiver` disconnected and an operation was invoked on 30+ instances within the exact same second, causing them to all attempt reconnection at once.

**Comment by xinyi-joffre** [comment]
@jsquire we are using the latest v3.5 of Orleans, which uses Azure.Messaging.EventHubs. This is the only one supports ManagedIdentityCredential, since it was added in the latest release.

It unfortunately was not a random occurrence, we saw failures throughout a 5 day window after deployment. We were finally able to isolate the root cause and rolled back to using connection strings. We didn't change the EventHub or Orleans version, just the how EventHub was authenticating.

Once we rolled back, the engineer from App Service RDP'd to our instance to ensure that token requests had gotten better (though Blob SDK was still calling out to App Service's token service around once every 1-2 minutes for blob leases), which is an okay load, but it is still more than it needs to call out to token service.

Here's a count of MSI.GetToken DependencyTelemetry failures across 5 day window:
2021-09-09 	82
2021-09-10 	536
2021-09-11 	1382
2021-09-12 	1392
2021-09-13	828 (partial day, this is when we rolled back)

This also happened across multiple global regions, so it was not an isolated to a single instance. You are correct that there was also something amiss in the host environment--App Service could not handle the load, so the token service was breaking and getting stuck (confirmed to be a bug, but even after that's fixed, they still are relying on SDKs having caching to reduce the load).

For the EventHub configuration piece:
- Our EventHub did have 32 partitions.
- I'm not sure why there were so many MSI.GetToken calls from the EventHub library w/ Orleans, but once we went back to Connection String, even the MSI.GetToken success telemetry was gone from our service telemetry, so it was definitely coming from EventHub MSI connections. I'll see if I can dig into the internals of Orleans later today and see why it was calling out so often. As a consumer of the Azure.Identity and Orleans libraries, we don't directly instantiate any EventHub clients, but at the moment, given the major reliability issues we had migrating, it's not feasible to use Azure.Identity MSI together with Orleans v3.5 and the older EventHubs version.

@ReubenBond, based on discussion above, would we be able to upgrade to the latest EventHub library w/ TokenCaching? Do you want me to create an issue in Orleans repo instead to update packages?:

> Assuming that the version of Orleans that you're using references the Azure.Messaging.EventHubs package, the version of the Event Hubs SDK that Orleans is currently referencing is about 8 months old (src) and does lack token caching - but, that would only be impactful if PartitionReciever instances are being created often or there are connectivity issues that require them to reconnect often.

**Comment by karshinlin** [comment]
@jsquire Checking back if there is any traction here. App Service team is working on improvements for availability and reliability, but the issue of overloading downstream services while using Managed Identity will continue to be a problem without effective caching at the SDK level. Without a static/shared cache at the library level, customers run into issues requesting too many tokens, causing trouble for their app when deployed to Azure with production load, and often not noticed in dev/qa environments.

**Comment by jsquire** [comment]
@karshinlin:  My role for this issue was only first triage.   For any updates, we'll need to ask the engineers assigned.   @christothes / @schaabs:  Are there any updates to share?

**Comment by christothes** [comment]
Token Caching support for Managed Identity is being tracked here https://github.com/Azure/azure-sdk-for-net/issues/27778

**Comment by scottaddie** [comment]
The development work on token caching for `ManagedIdentityCredential` kicks off next month. We're targeting the Azure.Identity v1.7.0 release, which will GA in early October. For those interested in testing this caching feature, a beta release will be available before October.

**Comment by christothes** [comment]
This is now available in the [1.7.0-beta.1 release](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/identity/Azure.Identity/CHANGELOG.md#170-beta1-2022-08-09)
