### ISSUE TITLE
EventProcessorClient Not receiving events when connected to the $Default ConsumerGroup 

### ISSUE THREAD

**Issue by qamessenger** [Azure/azure-sdk-for-net#24081]
**Describe the bug**
I am using the Basic Processing Code example here: https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/eventhub/Azure.Messaging.EventHubs.Processor/samples/Sample04_ProcessingEvents.md#basic-event-processing 
I can receive eventhub Events when I use a non-default consumer group, but when using the $Default consumer group no events are received. I can use ServiceBus Explorer and connect to the $Default Consumer Group and receive data

**Expected behavior**
When Connecting to the $Default consumer Group using EventProcessorClient or EventHubConsumerClient we should receive events from the eventhub

**Actual behavior (include Exception or Stack Trace)**
The processEventHandler is not triggered to process data no data is received

**To Reproduce**
1. Use this code:
2. https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/eventhub/Azure.Messaging.EventHubs.Processor/samples/Sample04_ProcessingEvents.md#basic-event-processing

**Environment:**
 - MSVS version:
Microsoft Visual Studio Professional 2019
**_Version 16.11.1
VisualStudio.16.Release/16.11.1+31613.86
Microsoft .NET Framework
Version 4.8.04084
Installed Version: Professional
ADL Tools Service Provider   1.0
This package contains services used by Data Lake tools
ASA Service Provider   1.0
ASP.NET and Web Tools 2019   16.11.75.64347
ASP.NET and Web Tools 2019
ASP.NET Web Frameworks and Tools 2019   16.11.75.64347
For additional information, visit https://www.asp.net/
Azure App Service Tools v3.0.0   16.11.75.64347
Azure App Service Tools v3.0.0
Azure Data Lake Node   1.0
This package contains the Data Lake integration nodes for Server Explorer.
Azure Data Lake Tools for Visual Studio   2.6.1000.0
Microsoft Azure Data Lake Tools for Visual Studio
Azure Functions and Web Jobs Tools   16.11.75.64347
Azure Functions and Web Jobs Tools
Azure Stream Analytics Tools for Visual Studio   2.6.1000.0
Microsoft Azure Stream Analytics Tools for Visual Studio
C# Tools   3.11.0-4.21403.6+ae1fff344d46976624e68ae17164e0607ab68b10
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.
Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.
Fabric.DiagnosticEvents   1.0
Fabric Diagnostic Events
IntelliCode Extension   1.0
IntelliCode Visual Studio Extension Detailed Info
Microsoft Azure HDInsight Azure Node   2.6.1000.0
HDInsight Node under Azure Node
Microsoft Azure Hive Query Language Service   2.6.1000.0
Language service for Hive query
Microsoft Azure Service Fabric Tools for Visual Studio   16.10
Microsoft Azure Service Fabric Tools for Visual Studio
Microsoft Azure Stream Analytics Language Service   2.6.1000.0
Language service for Azure Stream Analytics
Microsoft Azure Stream Analytics Node   1.0
Azure Stream Analytics Node under Azure Node
Microsoft Azure Tools for Visual Studio   2.9
Support for Azure Cloud Services projects
Microsoft Continuous Delivery Tools for Visual Studio   0.4
Simplifying the configuration of Azure DevOps pipelines from within the Visual Studio IDE.
Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines
Microsoft Library Manager   2.1.113+g422d40002e.RR
Install client-side libraries easily to any web project
Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers
Microsoft Visual Studio Tools for Containers   1.2
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.
Node.js Tools   1.5.30526.3 Commit Hash:c09c81113bcbc86d57943fcdd67e82434263d61d
Adds support for developing and debugging Node.js apps in Visual Studio
NuGet Package Manager   5.11.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/
ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info
Razor (ASP.NET Core)   16.1.0.2122504+13c05c96ea6bdbe550bd88b0bf6cdddf8cde1725
Provides languages services for ASP.NET Core Razor.
SQL Server Data Tools   16.0.62107.28140
Microsoft SQL Server Data Tools
ToolWindowHostedEditor   1.0
Hosting json editor into a tool window
TypeScript Tools   16.0.30526.2002
TypeScript Tools for Microsoft Visual Studio
Visual Basic Tools   3.11.0-4.21403.6+ae1fff344d46976624e68ae17164e0607ab68b10
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.
Visual F# Tools   16.11.0-beta.21322.6+488cc578cafcd261d90d748d8aaa7b8b091232dc
Microsoft Visual F# Tools
Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio
Visual Studio Container Tools Extensions   1.0
View, manage, and diagnose containers within Visual Studio.
Visual Studio Tools for Containers   1.0
Visual Studio Tools for Containers
Visual Studio Tools for Kubernetes   1.0
Visual Studio Tools for Kubernetes_**

Nugets:
Using the nugets: https://www.nuget.org/packages/Azure.Messaging.EventHubs/5.6.1 and https://www.nuget.org/packages/Azure.Messaging.EventHubs.Processor/5.6.1 
Windows: 
OS Name	Microsoft Windows 10 Pro
Version	10.0.19041 Build 19041

**Comment by jsquire** [comment]
Hi @qamessenger.  Thank you for reaching out and we regret that you're experiencing difficulties.

If you're able to read from other consumer groups but not `$Default`, the most likely cause is that there are other readers active and you've reached the limit on concurrent readers.  

To diagnose, would it be possible to share your code?  It would also be helpful to understand:

- Why you don't believe that you're reading events?  Is it because you're not seeing your handler called?
- What is your error handler seeing during this time?  
- Are there any checkpoints that exist in storage?
- If you register a handler for `PartitionInitializingAsync`, are you seeing that get called with the partitions that you're expecting to read from?

**Comment by qamessenger** [comment]
Hi Jesse,

Im using the test code from here
https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/eventhub/Azure.Messaging.EventHubs.Processor/samples/Sample04_ProcessingEvents.md#basic-event-processing
with the InitializeEventHandler.

I set a break point in the handlers processEventHandler,
processErrorHandler and initializeEventHandler. I added debug.Writeline so
I can see the events processed.
when I run my code we call await
processor.StartProcessingAsync(cancellationSource.Token); when this occurs
the initializeEventHandler is triggered, the processEventHandler
and processErrorHandler are never triggered.

If I run the same test using a non default consumer group the
processEventHandler is triggered and I receive all of the events I sent.

There are no checkpoints
There are no other Listeners connected to the consumer group.


I would be more than happy to have a call with you. I need to get this
resolved as we will be dynamically creating EventHubs and will be using the
$Default consumerGroup

Thanks,

Greg

**Comment by jsquire** [comment]
Hi @qamessenger.   The Event Hubs clients are tested nightly and the bulk of these tests make use of the `$Default` consumer group;  what 

I understand that you've based your code on our sample, but the sample itself is not a stand-alone application.   It would be helpful to see your actual test application code to better understand the end-to-end context.   Can you also share how many partitions the Event Hub has, how many events were published, and whether they were published using a partition key?

What I'd recommend to troubleshoot further:

  - Ensure that your application is blocking after `StartProcessingAsync` is called; that call will return once processing has started and will not prevent the application from terminating.
  
  - If you're using the 30 second timeout in the sample, disable that and allow the host to continue running until cancellation.  It is possible that cancellation is occurring before the processor is able to fully initialize in your application.

  - Ensure that the container that you're using to test against is empty;  old ownership records will take time to expire.  Your processor may not be claiming all of the partitions when it first starts because the ownership records indicate there's another processor instance running to share with.  You can help avoid this by configuring your processor with a stable [Identifier](https://docs.microsoft.com/dotnet/api/azure.messaging.eventhubs.eventprocessorclientoptions.identifier) so that a random one isn't assigned from run-to-run.

  - Configure your processor to use the `Greedy` [load balancing strategy](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/eventhub/Azure.Messaging.EventHubs.Processor/samples/Sample02_EventProcessorConfiguration.md#load-balancing-strategy) to speed up the initialization process.

  - Configure your processor with a [MaximumWaitTime](https://docs.microsoft.com/dotnet/api/azure.messaging.eventhubs.eventprocessorclientoptions.maximumwaittime) of 250 milliseconds or so; this will ensure that your handler is being pinged for each owned partition whether events are available or not.

It would also be helpful to capture the logs that the SDK is emitting, so that we can understand what it is seeing.  The logs are emitted as ETW events; the easiest way to hook them is to use the `AzureEventSourceListener`.    There's a [sample](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/eventhub/Azure.Messaging.EventHubs/samples/Sample10_AzureEventSourceListener.md#apply-filtering-logic-to-logs) that demonstrates using the listener with the Event Hubs SDK, which may come in handy.

We'll need to set the `LogLevel` to `Verbose`, which emits a large volume of logs, so  filtering down to the following set would help us focus on the important ones: 

**Event Source Name:  “Azure-Messsaging-EventHubs”**
-	6 (Event Receive Start)
-	7 (Event Receive End)
-	8 (Event Receive Error)
-	36 (Event Processor Task Error)
-	37 (EventProcessorPartitionProcessingStart)
-	38 (EventProcessorPartitionProcessingStartError)
-	39 (EventProcessorPartitionProcessingStartComplete)
-	40 (EventProcessorPartitionProcessingStop)
-	41 (EventProcessorPartitionProcessingStopError)
-	42 (EventProcessorPartitionProcessingStopComplete)
-	43 (EventProcessorParitionProcessingError)
-	44 (EventProcessorLoadBalancingError)
-	45 (EventProcessorClaimOwnershipError)

**Comment by qamessenger** [comment]
Hi Jesse,

Thank you for the help. Using these settings worked. I can now retrieve
events from the Default consumerGroup
 var processorOptions = new EventProcessorClientOptions
            {
                LoadBalancingStrategy = LoadBalancingStrategy.Greedy,
                MaximumWaitTime = TimeSpan.FromSeconds(1),
                Identifier = "SomeName"
            };
Any good examples of creating custom EventProcessorClient so I can put the
handlers in a separate class.
Greg

**Comment by jsquire** [comment]
Glad to hear that things got worked out.   With respect to samples, I'm not sure exactly what you're describing or looking for, but our samples can be found in the following spots:

- [Event Hubs package](https://github.com/Azure/azure-sdk-for-net/tree/main/sdk/eventhub/Azure.Messaging.EventHubs/samples)
- [Event Processor Client package](https://github.com/Azure/azure-sdk-for-net/tree/main/sdk/eventhub/Azure.Messaging.EventHubs.Processor/samples)
