### ISSUE TITLE
[QUERY] Is there guidance on checkpointing on PartitionClosingAsync when using the EventProcessorClient?

### ISSUE THREAD

**Issue by stambunan** [Azure/azure-sdk-for-net#24135]
**Query/Question**
Our scenario is that we checkpoint given an interval (X number of seconds) and we want to safely checkpoint an event when the partition is closing, due to a shutdown or perhaps when ownership of the partition changes.

What is the recommended approach to creating a checkpoint when a partition is closing? Should we be creating a concurrent dictionary to checkpoint the last event for the particular partition before it is closed, similar to 
the example in https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/eventhub/Azure.Messaging.EventHubs.Processor/samples/Sample04_ProcessingEvents.md#checkpointing-while-processing? Instead of a `ConcurrentDictionary<string, int>`, a `ConcurrentDictionary<string, ProcessEventArgs>` would be used to checkpoint the last event processed but not checkpointed? 

Would the `OnPartitionProcessingStoppedAsync` handler for the current processor instance be executed before a new processor instance calls its `OnInitializingPartitionAsync` handler?

**Environment:**
 - Name and version of the Library package used: Azure.Messaging.EventHubs.Processor v5.6.1
 - Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects): .NET 5
 - IDE and version : VS 16.11.2

**Comment by jsquire** [comment]
Hi @stambunan.   Thank you for reaching out and we regret that you're experiencing difficulties.   

With respect to the scenario where the processor is shutting down and you'd like to record a final checkpoint, the general approach that you're describing is what we would recommend.  You'd need to preserve the last set of `ProcessEventArgs`  that hasn't been checkpointed so that you can access them to create the final checkpoint in your `PartitionProcessingStopped` handler.    The proposed concurrent dictionary is a reasonable way to do so.

For partitions changing ownership, there is no reliable way to write a final checkpoint before ownership changes.   In order to prioritize throughput and reduce complexity in the hosting environment, processors do not communicate peer-to-peer nor is there a central orchestrator that directs an ordered hand-off.  Instead, ownership coordination is performed in a loose manner using Storage as the intermediary.   

When processors are added/removed from the group or a processor is no longer able to communicate with Storage, ownership of partitions will change.  During that time, the new owner will begin processing once Storage accepts their request to update the ownership record.  The old owner may still be processing the last batch of events read and won't become aware that their ownership was lost until the next time they attempt to read from the partition or the next load balancing cycle occurs.

It would be possible to manually force a checkpoint before you scale processors by tracking the `ProcessEventArgs` in the manner that you proposed earlier and having the host application respond to some sort of notification that scaling is about to occur.   In the extreme, that could be used to stop all processing to ensure final checkpoint stability before scaling and then restarting after scaling. 

For a more robust approach, you could write an orchestrator that assigns a specific set of partitions to a processor, notifies it when it is losing ownership, and waits for the final checkpoint, and then hands the partition to another instance.  That, of course, comes with additional complexity, performance costs to overall throughput, and the need to build resilience into the orchestrator or accept a single point of failure. 

I'm going to mark this as addressed, but please feel free to use the "`/unresolve`" command if you'd like to continue the discussion.
