### ISSUE TITLE
[Query] Doubt in IReliableDictionary<TKey,TValue>.TryAddAsync

### ISSUE THREAD

**Issue by saurabh18213** [Azure/azure-sdk-for-net#24136]
[Enter feedback here]

In which situations can this function return false? Will it return false if key was already present in the dictionary? Will it update the value of the key if the key was already present in the dictionary?
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 055cb749-038b-07ee-8427-20c300bcfe27
* Version Independent ID: 00de0c0a-461e-1a6a-3935-7d2e40d2c342
* Content: [IReliableDictionary&lt;TKey,TValue&gt;.TryAddAsync Method (Microsoft.ServiceFabric.Data.Collections) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/microsoft.servicefabric.data.collections.ireliabledictionary-2.tryaddasync?view=azure-dotnet)
* Content Source: [xml/Microsoft.ServiceFabric.Data.Collections/IReliableDictionary`2.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.ServiceFabric.Data.Collections/IReliableDictionary`2.xml)
* Service: **service-fabric**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by navba-MSFT** [comment]
@saurabh18213 Apologies for the late reply. Dictionary Keys can’t be modified, by design. To answer your question, 'No' this function would not update the TValue of a supplied key. As this function is for adding a new key,value pair to a dictionary. 

You would use a different function, [AddOrUpdateAsync: IReliableDictionary<TKey,TValue>.AddOrUpdateAsync Method (Microsoft.ServiceFabric.Data.Collections) - Azure for .NET Developers | Microsoft Docs](https://docs.microsoft.com/en-us/dotnet/api/microsoft.servicefabric.data.collections.ireliabledictionary-2.addorupdateasync?view=azure-dotnet) to add a new key,value pair OR update the TValue of an existing one.

More Info:[ IReliableDictionary<TKey,TValue>.TryAddAsync Method (Microsoft.ServiceFabric.Data.Collections) - Azure for .NET Developers | Microsoft Docs](https://docs.microsoft.com/en-us/dotnet/api/microsoft.servicefabric.data.collections.ireliabledictionary-2.tryaddasync?view=azure-dotnet).

This issue is open for quite sometime. Please let me know if you have any further questions on this.
