### ISSUE TITLE
Add ability to insert comments in generated code by reading from a text file

### ISSUE THREAD

**Issue by Mohit-Chakraborty** [Azure/azure-sdk-for-net#24254]
During code generation, we should be able to replace the comments specified in the REST spec using comments specified in some text file.
The comments in the REST spec are typically short and service-oriented. If the SDK has no need to add partial classes to augment/replace the functionality of the generated type, then it is too cumbersome to add one only to add comments to the type/member. It also adds confusion by adding files needlessly to the SDK projects.

It would be good if SDK developers could specify comments for types/members in a text file that can be used by autogen to put comments.

**Comment by pallavit** [comment]
@m-nash, @jsquire do you think this is possible today? If not, do you think there is value in implementing something like this? Have we had service partners need\ask for this behavior?

**Comment by jsquire** [comment]
@pallavit:  This would work around the issues where the service definitions do not have adequate documentation or use HTML which gets double-encoded, but I don't like the idea, personally.  This would just kick the problem down the stack and allow a local override rather than ensuring that the API definition is fixed in a way that would ensure quality documentation for all languages doing generation.

If anything, I'd say the local doc overrides would be a candidate for client TSP rather than some stand-alone file.   I'll defer to @m-nash, but my vote is to close this out.
