### ISSUE TITLE
[BUG] Some of messages are not consumed from the event hub

### ISSUE THREAD

**Issue by VarditShimborsky** [Azure/azure-sdk-for-net#24338]
**Describe the bug**
We see strange behavior when retrieving messages from the event hub.

From a certain point in time, some of the messages did not consume and newer messages were consumed.

after the app restart, all the messages are consumed.

You can see the differences in the following picture
![image](https://user-images.githubusercontent.com/85234348/135441451-438e90c9-309c-400d-8cbf-7a7a8f1fcb10.png)

**Expected behavior**
All messages created will be consumed immediately

**Actual behavior**
some of the messages did not consume and newer messages were consumed.

**To Reproduce**
It does not happen consistently and has happened several times between 23-26/9.

**Environment:**
- Azure.Messaging.EventHubs 5.2.0
- Windows 10 .NET Core 5.0.6

**Comment by jsquire** [comment]
Hi @VarditShimborsky.  Thank you for reaching out and we regret that you're experiencing difficulties.   In order to assist, we'll need some additional information about your scenario.  To start:

- What type are you using from the Event Hubs client library to consume events?
- Can you tell us a bit about the host application?  For example, knowing the application type, how it is hosted, and how it is run would be helpful.

**Comment by VarditShimborsky** [comment]
Hi, 
 

- I am using Azure.Messaging.EventHubs.EventProcessorClient to consume events
consumer options: EventProcessorClientOptions 
                LoadBalancingStrategy = LoadBalancingStrategy.Balanced,
                CacheEventCount = 128,
                PrefetchCount = 256,
                MaximumWaitTime = new TimeSpan(0, 0, 60)
- the application is a windows service on windows VM,   the event hub used consumer group default with 2 VMs

the bug reproduces again today, you can see the metrics in the following image below, from last hour.
![image](https://user-images.githubusercontent.com/85234348/135489693-d04113a4-76c2-4224-a5eb-e33c3adfc698.png)

thanks, 
Vardit

**Comment by VarditShimborsky** [comment]
> Thank you for the additional context. Now that we know more about the scenario, there's some additional information that will be helpful to understand the behavior that we're seeing:
> 
> * How many partitions does the Event Hub have? **8**
> * Since you mentioned 2 VMs, does this mean that there are two instances of the processor running against the Event Hub + Consumer Group? **Yes**.
> * What is the error handler for each processor seeing during this period? **has not any errors**
> * Is the handler for processing events ensuring that all exceptions are handled and the handler does not throw? **all exceptions are handled, see the error handling bellow**
> * How long have the processors been running at the time this behavior is observed? **the processors are up at all times.**
> * If you're handling partition initialization and partition close,  what are those handlers seeing during this period? **we don't have any code block to handle partition close.**
> 
> I also note that you're using a version that is about a year old. In that time there have been a number of enhancements and fixes to the library; we would strongly recommend updating to the latest GA version.
**it is a mistake, we are using version 5.4.1**
> 
> Additionally, can you share what your outcome was with the similar [issue](https://github.com/Azure/azure-sdk-for-js/issues/16444) that you had previously reported with the JavaScript SDK? **it is another project and the problem was memory consumption in the pod.**

Session Ids   for example: 
46EF2CE0-EE6A-4E95-9519-DD2CF5EFEA0B
48C0E5B2-6F3E-4060-A967-075904C15251
8784CB6A-D835-4F04-8B8E-5F9BC4E74A0B
972540CE-91AF-4CEE-9E9A-F08B0C224446
8BB0E3FB-88F4-46E0-87D4-2734B280A5C6
129683EF-AEC3-452C-97FF-E17ED7FACC5A
![image](https://user-images.githubusercontent.com/85234348/135518303-34405406-1025-439e-9a2a-0a05c394795f.png)

**Comment by jsquire** [comment]
To start digging in, we'll want to capture the logs that the SDK is emitting, so that we can understand what the processor is seeing.  The logs are emitted as ETW events; the easiest way to hook them is to use the `AzureEventSourceListener`.    There's a [sample](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/eventhub/Azure.Messaging.EventHubs/samples/Sample10_AzureEventSourceListener.md#apply-filtering-logic-to-logs) that demonstrates using the listener with the Event Hubs SDK, which may come in handy.

We'll need to set the `LogLevel` to `Verbose`, which emits a large volume of logs, so  filtering down to the following set would help us focus on the important ones: 

**Event Source Name:  “Azure-Messsaging-EventHubs”**
-	6 (Event Receive Start)
-	7 (Event Receive End)
-	8 (Event Receive Error)
-	36 (Event Processor Task Error)
-	37 (EventProcessorPartitionProcessingStart)
-	38 (EventProcessorPartitionProcessingStartError)
-	39 (EventProcessorPartitionProcessingStartComplete)
-	40 (EventProcessorPartitionProcessingStop)
-	41 (EventProcessorPartitionProcessingStopError)
-	42 (EventProcessorPartitionProcessingStopComplete)
-	43 (EventProcessorParitionProcessingError)
-	44 (EventProcessorLoadBalancingError)
-	45 (EventProcessorClaimOwnershipError)

**Event Source Name:  “Azure-Messaging-EventHubs-Processor-EventProcessorClient”**
-	20 (Event Processing Start)
-	21 (Event Processing End)
-	22 (Event Processing Error)
-	23 (Update Checkpoint Start)
-	24 (Update Checkpoint End)
-	25 (Update Checkpoint Error)

**Comment by jsquire** [comment]
> Is the handler for processing events ensuring that all exceptions are handled and the handler does not throw? all exceptions are handled, see the error handling bellow

Exceptions that occur in your handler code are not routed to the error handler.

It is extremely important that you always guard against exceptions in your handler code; it is strongly recommended to wrap your entire handler in a try/catch block and ensure that you do not re-throw exceptions. The processor does not have enough understanding of your handler code to determine the correct action to take in the face of an exception nor to understand whether it is safe to assume that processing has not been corrupted. Any exceptions thrown from your handler will not be caught by the processor and will NOT be redirected to the error handler. This will typically cause processing for the partition to abort, and be restarted, but may also crash your application process.

More information can be found in the [Event Processor Handlers](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/eventhub/Azure.Messaging.EventHubs.Processor/samples/Sample03_EventProcessorHandlers.md#event-processor-handlers) documentation.

> it is a mistake, we are using version 5.4.1

That version is nearly 6 months old; we'd still recommend updating to the latest GA.

**Comment by amjad-Alhusseini** [comment]
@VarditShimborsky have you tried to reduce the MaximumWaitTime or BatchSize Property mentioned here (https://docs.microsoft.com/en-us/dotnet/api/azure.messaging.eventhubs.primitives.eventprocessoroptions.maximumwaittime?view=azure-dotnet#Azure_Messaging_EventHubs_Primitives_EventProcessorOptions_MaximumWaitTime), it could be that your messages are not reaching into full Batch size limit, that's why you see messages are not received immediately.

"If there are enough events available in the Event Hub partition to fill a batch of the requested size, the processor will populate the batch and dispatch it to this method immediately. If there were not a sufficient number of events available in the partition to populate a full batch, the event processor will continue reading from the partition to reach the requested batch size until the MaximumWaitTime has elapsed, at which point it will return a batch containing whatever events were available by the end of that period.

If a MaximumWaitTime was not requested, indicated by setting the option to null, the event processor will continue reading from the Event Hub partition until a full batch of the requested size could be populated and will not dispatch any partial batches to this method."

Ref: https://docs.microsoft.com/en-us/dotnet/api/azure.messaging.eventhubs.eventprocessorclient.onprocessingeventbatchasync?view=azure-dotnet

**Comment by jsquire** [comment]
Thank you, @amjad-Alhusseini, for your thoughts.   I'm afraid that it looks like we've got some incorrect documentation that we'll need to fix:

> If there were not a sufficient number of events available in the partition to populate a full batch, the event processor will continue reading from the partition to reach the requested batch size until the MaximumWaitTime has elapsed, at which point it will return a batch containing whatever events were available by the end of that period.

That isn't a correct statement;  due to behavior in the underlying transport library, when we make an attempt to read, the call will return as soon as any message is available up to the maximum batch size requested.  In other words,  if the read call is waiting because no events are available, the moment that at least one message is available in the prefetch queue, it will be returned without an attempt to build up a batch of the requested size.

I'll take a follow-up to get the processor documentation corrected.
