### ISSUE TITLE
[FEATURE REQ] Allow us to use a connection string for Azure Search

### ISSUE THREAD

**Issue by petro2050** [Azure/azure-sdk-for-net#24427]
I'm using the `Azure.Search.Documents` package and it looks like we need to provide the endpoint and the api key separately. If possible, can we connect to the backend using a single connection string similar to how services like Cosmos DB, SQL Database, Redis, etc. allow access?

**Comment by petro2050** [comment]
Thank you. This will also require UI change on the Azure portal so customers can see the full connection string and copy it easily after a new service is created.

**Comment by AlexGhiondea** [comment]
@dereklegenzoff to comment on this as as this is a service-side ask.

**Comment by dereklegenzoff** [comment]
Thanks for this feedback @petro2050. 

There's not a way to use something like a connection string with Azure Cognitive Search today. We have recently added support for using [Azure AD to authenticate requests](https://docs.microsoft.com/azure/search/search-howto-aad) though so that you don't have to use a key. I wonder if that would be helpful to you?

**Comment by Mohit-Chakraborty** [comment]
Closing this issue. Please let us know if you need further assistance or want to continue the discussion.
