### ISSUE TITLE
Enable StartTrainingSucceedsWithValidPrefix

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-for-net#24448]
@maririos commented on [Mon Aug 30 2021](https://github.com/Azure/azure-sdk-for-net-pr/issues/1442)

Currently service fails when trying to set a prefix

**Comment by kinelski** [comment]
In order to make the prefix work, we need to append a slash `/` to the end of the string to indicate that it is a subfolder:
```cs
new BuildModelOptions() { Prefix = "subfolder/" }
```

The service team confirmed this is intended, but they want to improve the usability of this feature if possible. We need to sync with them about the progress in this task.

Also, even if we fix the test, it will only search the subfolder for training files, ignoring the files placed in the root of the container, so our test will fail anyway. If this behavior is kept, we need to include training files in the `subfolder` folder as well.
