### ISSUE TITLE
Look into CopyAuthorization properties visibility and FromJson and ToJson methods

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-for-net#24474]
@maririos commented on [Mon Sep 20 2021](https://github.com/Azure/azure-sdk-for-net-pr/issues/1500)

Do we want them? to mimic what we did in FTC?

**Comment by kinelski** [comment]
`FromJson` and `ToJson` are not necessary anymore. They were used to convert the `CopyAuthorization` model to a format that can be consumed by the service. Since the service now has consistency on the way it handles the `CopyAuthorization` model, no conversion is needed anymore.

We still need to understand if we can expose the `TargetResourceId` property. It will depend on whether it contains Personal Identifiable Information or not. The following pieces of information are part of the resource ID:
- Subscription ID.
- Resource group name.
- Resource name.

Since exposing `TargetResourceID` is an additive change and a minor feature that isn't much used, I'm removing the `blocking-release` tag from this issue.

**Comment by kinelski** [comment]
Fixed by https://github.com/Azure/azure-sdk-for-net/pull/30133.
