### ISSUE TITLE
Rename for all Operation types

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-for-net#24500]
Currently, there are methods and types that include the word `Operation` that are not related to an LRO. `Operation` is a reserved word in the .NET SDKs, so we need to come up with an alternative term

**Comment by kinelski** [comment]
We decided to keep the `Operation` word since the types actually represent running LROs in the service. We just have to be careful with the `ModelOperation` class, since that ending the name of the type with `Operation` could lead customers to believe that it is a subclass of `Operation<T>`. For this and other reasons, it will be renamed to `DocumentModelOperationDetails`.
