### ISSUE TITLE
RetryPolicy does not honor max delay set by clients if server delay is greater

### ISSUE THREAD

**Issue by avanigupta** [Azure/azure-sdk-for-net#24519]
If the retry-after delay returned from server is greater than the `_maxDelay` set in `RetryPolicy`,  SDK will honor the server delay only ([code here](https://github.com/Azure/azure-sdk-for-net/blob/44feecc15e5f321a0d01a3a06f8c4194db4a615c/sdk/core/Azure.Core/src/Pipeline/Internal/RetryPolicy.cs#L195)). 

We are running into an issue where the server is returning a 5 minute retry-after header with 429 response, but the client does not want to wait that long to find out that they are being throttled. Is there an option for clients to set an overriding timeout for all requests regardless of the server's response?

**Comment by pakrym** [comment]
No, there is no such an option, but you can use the CancellationToken with timeout for your call.

``` C#
using var cancellationSource = new CancellationTokenSource();
cancellationSource.CancelAfter(...);

client.CallASync(..., cancellationSource.Token);
```

**Comment by avanigupta** [comment]
Hi @pakrym, is there any update on the intended usage of `MaxDelay`?

**Comment by pakrym** [comment]
Yes, I checked and the .NET behavior is consistent across languages. We might need to change docs to clarify that `MaxDelay` only applies to delay we calculate but we'll respect whatever service returns.

**Comment by skystedt** [comment]
When using Azure Web PubSub on the Free Tier and after running out of the included messages per day included.
The service will return status code 429 with Retry-After header that is a value between 20-60 minutes (I tested it several times and this is the range I got but the range might not be exactly this).

The default behavior when using Azure SDK for .NET is 3 retries for 429 errors.

Meaning in this scenario there is a wait between 60 to 180 minutes...
Which is just asking for problems :(

Now I understand you can change this by providing a CancellationToken, which is great, but having the _**default behavior**_ be such a long wait isn't good.

I don't know if this problem is isolated just to Azure Web PubSub or if other services has similar problem.

**Comment by christothes** [comment]
> Meaning in this scenario there is a wait between 60 to 180 minutes... Which is just asking for problems :(
> 
> Now I understand you can change this by providing a CancellationToken, which is great, but having the _**default behavior**_ be such a long wait isn't good.
> 
> I don't know if this problem is isolated just to Azure Web PubSub or if other services has similar problem.

I think the right thing to do is just to properly document the `MaxDelay` behavior for a few reasons
- Changing the behavior for `MaxDelay` could have unexpected results for existing code
- The default behavior remains the same in any case since to get different behavior requires either supplying the custom retry options or a cancellation token
- I think the cancellation token is the preferable way to override the absolute max operation duration since MaxDelay is per retry.
