### ISSUE TITLE
[QUERY] Migrating public URI downloads from V11 to V12

### ISSUE THREAD

**Issue by Joren-Thijs** [Azure/azure-sdk-for-net#25124]
### Problem
In our application we have different microservices that reach out to our blob storage container to download files like pdf's.
When we were using the [now depricated V11 sdk](https://github.com/Azure/azure-storage-net) we decided to store the full public uri of the document in the database. With the sdk we then created a `CloudStorageAccount` with necessary Azure credentials. From that we created a `BlobClient` and downloaded the file with the "public" uri. (See V11 code sample below)

Now with V12 of the sdk it seems the blobclient download method only supports downloading from relative paths.
In V12 we have to create a `BlobContainerClient` with the necessary Azure credentials and the blob container name.
Then we create a `BlobClient` with the relative path to the file in the container. And from there we can download the file.

Does version 12 not support downloading from public uri's?: yes it does but only for non authenticated resources.

What happens when you try to feed a public uri to the `BlobClient` derived from the authenticated `BlobContainerClient`?: It throws a 404 exception because it expects a relative path.

Can you get it to work with relative paths?: Yes but it requires manual parsing of uri's stored in the database which is not robust/testable code and can break easily.

### Questions
Can you explain why this change was made?
Can you add support for downloading authenticated resources with a public uri back in the sdk?
If not can you provide guidance on how to proceed and best practices for storing uri's to resources in azure storage accounts?

### Code samples
V11 approach:
```cs
public class BlobClient : IBlobClient
    {
        private readonly BlobClientOptions _options;
        public BlobClient(IOptions<BlobClientOptions> options)
        {
            if (string.IsNullOrWhiteSpace(options?.Value?.ConnectionString))
            {
                throw new ArgumentException("BlobClient needs a valid connectionstring", nameof(options));
            }
            _options = options?.Value ?? throw new ArgumentNullException(nameof(options));
        }
        public async Task<byte[]?> DownloadAsByteArray(Uri uri)
        {
            if (CloudStorageAccount.TryParse(_options.ConnectionString, out var storageAccount))
            {
                var blobClient = storageAccount.CreateCloudBlobClient();
                var cloudBlob = await blobClient.GetBlobReferenceFromServerAsync(uri); // uri is a public uri
                if (await cloudBlob.ExistsAsync())
                {
                    var content = new byte[cloudBlob.Properties.Length];
                    await cloudBlob.DownloadToByteArrayAsync(content, 0);
                    return content;
                }
            }
            return null;
        }
    }
```

V12 approach:
```cs
public async Task DownloadDocumentTo(Stream destination, Uri uri, CancellationToken ct = default)
{
    var containerName = BlobStorageOptions.ContainerName;
    var container = new BlobContainerClient(connectionString: _options.ConnectionString, blobContainerName: containerName);
    var blobClient = container.GetBlobClient(uri); // uri is a public uri, this throws 404 exception because it expects relative path.
    await blobClient.DownloadToAsync(destination, ct);
}
```

**Environment:**
 - Name and version of the Library package used: Azure.Storage.Blobs 12.10.0
 - Hosting platform or OS and .NET runtime version: [Azure Storage account]
 - IDE and version : [Visual studio code 1.61.2]

**Comment by Joren-Thijs-KasparSolutions** [comment]
Any updates on this?

**Comment by amnguye** [comment]
Looks like your expectation of `GetBlobClient` is incorrect.
https://docs.microsoft.com/en-us/dotnet/api/azure.storage.blobs.blobcontainerclient.getblobclient?view=azure-dotnet#Azure_Storage_Blobs_BlobContainerClient_GetBlobClient_System_String_
This API takes in the `blobName` not the full Uri to the blob.

The scenario to support in the event that in the Connection string that the "BlobEndpoint=" or "EndpointSuffix=" is specified and you prove the full Blob Uri, what if there's a mismatch where the full Blob Uri does not have the beginning BlobEndpoint matching, or the "EndpointSuffix" matching in the full Blob Uri.

This scenario seems rather specific and puts a burden on the SDK to decide which suffix is correct the blob Uri passed or the Uri passed in the connection string. That's not a decision up to the SDK to decide what's correct. 

That's why we provided the following options to create a `BlobClient`
BlobClient(Uri, StorageSharedKeyCredential, BlobClientOptions)
https://docs.microsoft.com/en-us/dotnet/api/azure.storage.blobs.blobclient.-ctor?view=azure-dotnet#Azure_Storage_Blobs_BlobClient__ctor_System_Uri_Azure_Storage_StorageSharedKeyCredential_Azure_Storage_Blobs_BlobClientOptions_
With this option you should be able to parse the storage account name and key from the connection string. I don't see how that could easily break since the connection string format is not something storage changes.

Or you can have the blob name separately, but you noted that for your scenario that it would easily break you, so the option above should be the one should go down.

**Comment by seanmcc-msft** [comment]
Please reopen if you have further questions.
