### ISSUE TITLE
 Service Bus: provide batch API to complete/abandon message

### ISSUE THREAD

**Issue by cfauchere** [Azure/azure-sdk-for-net#25142]
**Library or service name.**
Azure.Messaging.ServiceBus
 
**Is your feature request related to a problem? Please describe.**
With latest version of SDK I can retrieve messages in batch but I cannot complete or abandon those messages in batch, I have to go message by message. It would be nice to have a batch API to avoid multiple calls to Azure endpoint.

**Comment by jsquire** [comment]
Hi @cfauchere.  Thank you for your feedback.  Unfortunately, this request has been discussed previously and is not something that we will be adding to the Service Bus client library.  There is no support for multiple complete or abandon operations offered by the Service Bus service; any batched API would be client-side only and would be similar to:

```csharp
  var tasks = new List<Task>();

  for (ServiceBusReceivedMessage message in messages)
  {
      tasks.Add(receiver.CompleteMessageAsync(message));
  }

  await Task.WhenAll(tasks);
```   

We have concerns that this would introduce complexity and confusion around error scenarios due to the potential for partial success.  It also may hide a performance bottleneck, which is also a concern.  Since this pattern is fairly straight-forward to implement, we felt it was better applied in the application than hidden within the SDK.    

More context and the full discussion can be found in [#7291](https://github.com/Azure/azure-sdk-for-net/issues/7921).

**Comment by jorgelevy** [comment]
There use to be a feature for this purpose on Microsoft.Azure.ServiceBus assembly
-> public Task CompleteAsync(IEnumerable<string> lockTokens)

**Comment by JoshLove-msft** [comment]
> There use to be a feature for this purpose on Microsoft.Azure.ServiceBus assembly -> public Task CompleteAsync(IEnumerable lockTokens)

As @jsquire mentioned, the service has no support for batch completion, and this was simply added as a client-side convenience. The equivalent would be to write this code when using the new SDK:
```c#
  var tasks = new List<Task>();

  for (ServiceBusReceivedMessage message in messages)
  {
      tasks.Add(receiver.CompleteMessageAsync(message));
  }

  await Task.WhenAll(tasks);
```
