### ISSUE TITLE
Diagnose/investigate timeouts on TA live tests

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-for-net#25152]
Only happens on Live tests. I haven't been able to repro this locally.
Started happening after adding the custom features tests.

**Comment by maririos** [comment]
After multiple runs, it looks like custom features with multiple actions could be the cause. I will communicate with the service and meanwhile, we can disable those tests

PR: https://github.com/Azure/azure-sdk-for-net/pull/25042

**Comment by jsquire** [comment]
Not currently seeing timeouts, outside of very occasional outliers.   Closing this out and will continue to monitor.

**Comment by kinelski** [comment]
@jsquire  From Mariana's comment, it seems we just stopped seeing timeouts because the tests causing it have been disabled.

> After multiple runs, it looks like custom features with multiple actions could be the cause. I will communicate with the service and meanwhile, we can disable those tests

From my understanding, this issue was still left open to track the work of checking with the service team and re-enabling those tests (we have three disabled tests that point to this issue). I'm opening it again so we don't forget about it.

**Comment by pallavit** [comment]
@joseharriaga please check if this is still an issue.
