### ISSUE TITLE
Microsoft.Azure.WebJobs.Extension.Storage.Queues v5.0.0: How to do a dynamic binding in Azure Functions to put a QueueMessage in a storage queue

### ISSUE THREAD

**Issue by marcduiker** [Azure/azure-sdk-for-net#25164]
**Query/Question**
I have [this HTTP triggered function](https://github.com/marcduiker/azure-functions-university/blob/main/src/dotnetcore31/AzureFunctions.Queue/Output/NewPlayerWithDynamicQueueOutput.cs) that uses a dynamic output binding to put a message on a queue. This works fine with Microsoft.Azure.WebJobs.Extension.Storage v4.x but since v5 the types have changed (no more `CloudQueue`) and I can't find any documentation which type should be used instead.

**v4.x**
```csharp
var cloudQueue = await binder.BindAsync<CloudQueue>(queueAttribute);
await cloudQueue.AddMessageAsync(cloudQueueMessage);
```

What would be the way to setup dynamic binding with Microsoft.Azure.WebJobs.Extension.Storage.Queues v5?

**Environment:**
 - Microsoft.Azure.WebJobs.Extension.Storage.Queues v5
 - Windows & .NET Core 3.1.408
 - VSCode

**Comment by SaurabhSharma-MSFT** [comment]
@marcduiker We are looking into it and get back to you.

**Comment by superjulius** [comment]
@marcduiker While I have not been able to try it out, I think that it is because the underlying Azure Storage SDK was upgraded to 12.x

CloudQueue was used in [Version 11](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.storage.queue?view=azure-dotnet-legacy)

It should now be QueueClient in [Version 12](https://docs.microsoft.com/en-us/dotnet/api/azure.storage.queues?view=azure-dotnet)

**Comment by amishra-dev** [comment]
@marcduiker do you still need help?
