### ISSUE TITLE
[BUG] EventHubsModelFactory.EventBatch BatchSize always returns initial value

### ISSUE THREAD

**Issue by MartinKosicky** [Azure/azure-sdk-for-net#25185]
The EventHubsModelFactory EventBatch method returns an EventBatch such that the SizeInBytes is always in the initial value. Thus making it impossible to unit testing of the TryAdd functionality.

**Comment by jsquire** [comment]
Hi @MartinKosicky.  Thank you for your feedback and we regret that you're experiencing difficulties.   The behavior that you're seeing is by design.   The model factory creates a batch that does not perform the AMQP serialization needed for measuring the size of an event and instead stashes anything that you pass to `TryAdd` in the list that you provide in order to allow your code to inspect and manipulate batch events.

The last parameter in the [EventDataBatch](https://docs.microsoft.com/dotnet/api/azure.messaging.eventhubs.eventhubsmodelfactory.eventdatabatch?view=azure-dotnet) method is a predicate function that controls the response from `TryAdd`, allowing your code to make the decision of whether an event is accepted  or rejected by the batch.  For example:

```csharp
var options = new CreateBatchOptions { PartitionKey = "abc123" };
var batchedEvents = new List<EventData>();

bool tryAddPredicate(EventData eventToAdd)
{
    return batchedEvents.Count <= 10;
}

using var batch = EventHubsModelFactory.EventDataBatch(1_048_576, batchedEvents, options, tryAddPredicate);

// ... << SNIP >>
```

By controlling how the predicate responds when your application attempts to add an event to the batch, you've got the freedom to ensure deterministic behavior when testing using predictable conditions.   If you're working with a scenario where the design blocks your ability to test, we'd be very interested in understanding the details so that we can consider how to improve the experience.

I'm going to mark this as addressed, but please feel free to "`/unresolve`" if you'd like to continue the discussion.

**Comment by MartinKosicky** [comment]
Hello. I now understand that there is no ampq serialization availabile which make sence. Im just wondering if the EventDataBatch contract isnt violated, since bytesize is always 0. If there was at least some counter (for example just increment some number based on the payload (.tostring().count()).  Me as user should not care or depend on the concrete serialization technique, i should just care that there is some limit that is reachable by using public api in the original code

/unresolve

**Comment by jsquire** [comment]
The size of the batch is not always zero,  your application can specify it as a parameter of the method.   It is, however, true that the size is static and will not change as events are added.   The mock batch allows limiting, controlled by the predicate supplied.

Can you share more about the specific scenario that you're concerned with and help us understand where the size rather than the result of `TryAdd` is impactful to your application code being tested?
