### ISSUE TITLE
[BUG] Azure.ResourceManager 1.0.0-beta.3: DeploymentProperties has incorrect documentation

### ISSUE THREAD

**Issue by jackhorton** [Azure/azure-sdk-for-net#25182]
**Describe the bug**
The documentation of Azure.ResourceManager.Resources.Models.DeploymentProperties is incorrect. It states that the Template and Properties values should be either `string`s or `JObject`s, but neither is true (technically it _can_ be a string, but that gets sent down the wire to the ARM backend as a JSON-encoded string, which is incorrect). It must actually be a `Dictionary<string, object>` (where the `object` values are also `Dictionary<string, object>` or `JsonElement`) or `JsonElement`.

**Expected behavior**
```cs
props.Template = File.ReadAllText("mytemplate.json");
props.Parameters = File.ReadAllText("myparams.json"); // or JsonSerializer.Serialize(myCustomParamsObject)
```

**Actual behavior (include Exception or Stack Trace)**
Upon issuing a `CreateOrUpdateAsync` when using string parameters, you will get an error similar to:
```
Unhandled exception. Azure.RequestFailedException: The request content was invalid and could not be deserialized: 'Error converting value "{
  "$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#",
...
}" to type 'Azure.Deployments.Core.Definitions.Schema.Template'. Path 'properties.template', line 1, position 4644.'
```

Similarly, when passing an arbitrary System.Text.Json-serializable object, you will get a `System.NotSupportedException`.

**To Reproduce**
Steps to reproduce the behavior (include a code snippet, screenshot, or any additional information that might help us reproduce the issue)

1. See above

**Environment:**
 - Name and version of the Library package used: Azure.ResourceManager.Resources 1.0.0-beta.3
 - Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects): Windows 11 22489, .NET 6.0.11-rc SDK
 - IDE and version : Visual Studio 2022 preview 7

**Comment by jackhorton** [comment]
There were previous similar issues reported about the old Microsoft.Azure.Management.Resources SDK, but most were closed or irrelevant to the new packages. As far as I can tell, this code and documentation is generated with Autorest, so the backing swagger/cadl definitions may need to change to fix this.

But, since this was also a rough experience in previous versions of the SDK -- is there any way we can get a hand-written layer on top of this code that is more strongly typed? For instance, I am envisioning the SDK could provide the following class for parameters:

```cs
public class DeploymentParameterValue : IUtf8JsonSerializable
{
    public string Name { get; set; }
    public object Value { get; set; }
}
public class DeploymentParameterKeyVaultReference : IUtf8JsonSerializable
{
    public string Name { get; set; }
    public ResourceIdenfitier KeyVaultId { get; set; }
    public string SecretName { get; set; }
}
public class DeploymentParameters : IUtf8JsonSerializable
{
    public IList<DeploymentParameterValue> Values { get; }
    public IList<DeploymentParameterKeyVaultReference> KeyVaultReferences { get; }
}
```

This way, for people generating custom parameters (like our team), we wouldn't need to implement our own serialization logic to mimic the parameter file syntax (which is cumbersome for normal `"myparam": { "value": "myvalue" }` but even more cumbersome for key vault references)

**Comment by yukun-dong** [comment]
I have reproduced the error using string on template or parameters to create a deployment. Since the descriptions come directly from swagger doc, I created a issue on swagger repo to track this problem: https://github.com/Azure/azure-rest-api-specs/issues/16759.

For JObject, could you @jackhorton please elaborate what specific object you used that caused this error, because "System.Text.Json-serializable object" seems general. Appreciate it if you can provider some code examples.

**Comment by jackhorton** [comment]
By "System.Text.Json-serializable object", I just meant any normal POCO: For example:

```cs
// For instance, if we are crafting our own parameters file in C#, we may like to pass an object in
// that would serialize down to a parameters file (where you get "paramName": { "value": "paramValue" })
JsonSerializer.Serialize(new { Foo = new { value = 1 } }); // works
deploymentProperties.Parameters = new { Foo = new { value = 1 } }; // assigns just fine, but causes CreateOrUpdateAsync to throw NotSupportedException
```

**Comment by yukun-dong** [comment]
The Serialization logic existed in SDK is not the same as JsonSerializer. The current solution for this is to pass a `JsonElement` rather than a `Object` to Parameters:

```csharp
string str= JsonSerializer.Serialize(new { Foo = new { value = 1 } });
JsonElement jsonElement = JsonDocument.Parse(str).RootElement;
tmpDeploymentProperties.Parameters = jsonElement;
```
If you are using .NET 6.0, then `SerializeToElement` function can help.
```csharp
tmpDeploymentProperties.Parameters = JsonSerializer.SerializeToElement(new { Foo = new { value = 1 } });
```

We will add some more samples of creating Deployment in the Resource RP, and we will consider modifying Serialization logic in SDK so that can pass a Object to Parameters or Template in the future.

**Comment by jackhorton** [comment]
More examples would definitely be helpful. Instead of allowing more kinds of objects directly in the current structure, is there any chance this could get more strongly typed so consumers know what they can use without needing to look at the examples? In addition to the suggestion for a native `DeploymentParameters` type in my first comment, I could also imagine the following would allow for more natural intellisense discoverability:

```cs
public abstract class DeploymentTemplate
{
    public static DeploymentTemplate FromJson(System.Text.Json.JsonElement json) {}
    public static DeploymentTemplate FromJson(System.Text.Json.JsonNode json) {}
    public static DeploymentTemplate FromJson(string jsonText) {}
    public static DeploymentTemplate FromFile(FileInfo template) {}
    public static DeploymentTemplate FromSerializable(IUtf8JsonSerializable obj) {}
}
```
```diff
public class DeploymentProperties
{
-    public object Template { get; set; }
+    public DeploymentTemplate Template { get; set; }
}
```

**Comment by yukun-dong** [comment]
Talked with the team. Below are our conclusions.

1. The description comes from [swagger doc](https://github.com/Azure/azure-rest-api-specs/blob/972507baffd480eff639840a27ce83dd1bc432ae/specification/resources/resource-manager/Microsoft.Resources/stable/2021-04-01/resources.json#L4564) and it is shared by all SDKs. The reason of defining the `Template` and `Parameters` to be type "Object" is making sure they can take a string or JObject as input. 

2. When using string on `Template`, it's SDK's job to convert it to a JObject first. However in c#,  the string just be serialized as a string, therefore causing error. So it is indeed an issue in c# SDK rather than in swagger doc. We will find a way to fix this.

3. The "JObject" in the description means certain types of JObject rather than general Object. In Java SDK it uses Object from "Jackson" and it also doesn't support general Object types. Therefore we will not modify c# SDK to accept any POCO Object, but we will add some sample code so that customers know what Object can be used here.

4. After discussion, we think using the proposed **strong type** solution might not be the best way. If there are 10 more cases like `Template` then there would be 10 more redundant classes like `DeploymentTemplate` generated, which all serve the same general purpose.
