### ISSUE TITLE
[FEATURE REQ] Cognitive-Translator client SDK is missing a method to enumerate languages

### ISSUE THREAD

**Issue by chriswendt1** [Azure/azure-sdk-for-net#25281]
**Library or service name.**
Cognitive - Translator 

**Is your feature request related to a problem? Please describe.**
Document Translation SDK is missing a method to enumerate the available languages
You should not expect the client developer to manually maintain a list of valid languages.

**Example**
Here is my implementation of that functionality:
https://github.com/MicrosoftTranslator/DocumentTranslationService/blob/master/Language.cs

**Comment by maririos** [comment]
Hi @chriswendt1 

Thanks for your implementation! As of today, the decision of not including the language codes in the .NET /SDK is by design.
We have included a link to the official documentation. You can find it here: https://docs.microsoft.com/azure/cognitive-services/translator/language-support#translate

@FadyEssam, @alexhcheng do you know if there are any plans of adding a method to the REST API that will include this information, as we have it for supported documents and glossary formats?

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team members best able to assist.

**Comment by chriswendt1** [comment]
I maintain that the SDKs usefulness is severely limited if it doesn't enumerate its capabilities. You have recognized this with other capabilities, just not this one, the languages.
