### ISSUE TITLE
[FEATURE REQ] [Forms Recognizer] Make RecognizedForm and child class serializable

### ISSUE THREAD

**Issue by yowl** [Azure/azure-sdk-for-net#25303]
**Library or service name.**
Azure.AI.FormRecognizer.Models
 
**Is your feature request related to a problem? Please describe.**
I would like to be able to deserialize `RecognizedForm` .  You can serialize it, and to JSON that looks ok, but you can't deserialize due to missing parameterless constructors.  We process forms as a 2 stage process

1. Process the forms and extract key fields used for matching against entities.
2. Later, when an entity is "matched", process the whole form

Currently both steps involve a call to `StartRecognizeCustomFormsAsync` but if the result could be stored from step 1 (e.g. in a database), then we can make step 2 more efficient.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by kinelski** [comment]
Thank you for your feedback, @yowl.

Currently we do not offer JSON (de)serialization since we can't guarantee serialized data compatibility across SDK versions. This would be a major feature that needs careful consideration. We've had similar feedback in the past, so we're aware this is a frequently requested feature: [[QUERY] FormRecognizer - Serialization for RecognizedFormCollection](https://github.com/Azure/azure-sdk-for-net/issues/21982)

Unfortunately, for now the only way of deserializing JSON data into our models is by writing the deserialization code yourself. You can use our [FormRecognizerModelFactory](https://docs.microsoft.com/en-us/dotnet/api/azure.ai.formrecognizer.models.formrecognizermodelfactory?view=azure-dotnet) to instantiate our models.

Let me know if you have further questions.

**Comment by yowl** [comment]
Thanks, doesn't have to be JSON, XML would do fine, but I think the same restrictions exist and I understand the suggestion of ` FormRecognizerModelFactory` would work for me. I'll close this as I don't see it adds anything over the linked issue.
