### ISSUE TITLE
EventGrid subscription filtering on arrays

### ISSUE THREAD

**Issue by garoplin** [Azure/azure-sdk-for-net#25324]
**Query/Question**
Hi Team,
I have question regarding Event Grid Subscription filtering via Azure Portal/Rest api. This may not be the right place for asking that, but I could not find a proper repository for that. My question is, whether it will be possible to filter array fields in the event. Do you have any timeline for that or maybe is it on your roadmap? The documentation clearly states that it is not possible **today** but maybe it will be available in the future (https://docs.microsoft.com/en-us/azure/event-grid/edge/advanced-filtering#filtering-on-array-values)
<img width="787" alt="Screenshot 2021-11-15 at 17 01 30" src="https://user-images.githubusercontent.com/79226004/141814443-773498d2-1d80-458a-8b83-caf80b2daad5.png">
. I'm attaching a screenshot from the docs. Thanks in advance.

Best regards

**Comment by jsquire** [comment]
Hi @garoplin.  Thank you for reaching out and we regret that you're experiencing difficulties.  Unfortunately, this repository is focused on the Azure SDK for .NET - we're unable to assist with other Azure issues.  Since what you're describing appears to be related to the portal and not one of its SDKs, your best path forward would be to [open an Azure support request](https://docs.microsoft.com/azure/azure-portal/supportability/how-to-create-azure-support-request).

I'm going to close this out;  if I've misunderstood what you're describing, please let us know in a comment and we'd be happy to assist as we're able.
