### ISSUE TITLE
[QUERY] Azure SDK guidelines for error handling

### ISSUE THREAD

**Issue by violetVo** [Azure/azure-sdk-for-net#25384]
**Query/Question**
Hi,
I am working on an API that will serve long-running operations in our service and I want to follow azure sdk
[error handling guidelines](https://azure.github.io/azure-sdk/general_implementation.html#error-handling).
I have a question regarding this guideline:
![image](https://user-images.githubusercontent.com/17854021/142240620-5d0c912e-680c-4283-b597-8c9b0de0d9a5.png)

Our service returns an [errorResponse](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md#handling-errors) object in the body. For example:
`{"error":{"code":"CustomServiceCode","message":"My error","target":null,"details":[{"code":"AlreadyReported","message":"Custom Inner Code Message","target":null,"details":null,"innererror":null}],"innererror":{"code":"Inner Error Code","innererror":null}}}`

Currently, the exception produced in the service-specific doesn't contain a mapping between the error object described above, and the exception's properties/fields.
Instead, the exception contains:
1.	Status - HTTP status code of the request
2.	ErrorCode - being populated from the error.code property from the error information
3.	Message – a formatted message **string** that contains all the data (including a toString of the error information) but as a regular string. This string doesn’t represent JSON. For example:
"My error title Status: 409 (Conflict) ErrorCode: CustomServiceCode Content:
{"error":{"code":"CustomServiceCode","message":"My error","target":null,"details":[{"code":"AlreadyReported","message":"Custom Inner Code Message","target":null,"details":null,"innererror":null}],"innererror":{"code":"Inner Error Code","innererror":null}}} Headers: 
Content-Type: application/json; charset=utf-8 Content-Length: 256"

Is that considered as compliant with Azure-SDK error handling?
And if it isn't, how does the exception produced in the service-specific should look like to follow the guidelines?

Thanks,
Violet.

**Environment:**
 - Windows 11 .NET Framework 4.8
 -  Visual Studio 17.0.0

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team members best able to assist.

**Comment by tg-msft** [comment]
Hi Violet.  How is your exception being created?  Is this a [`RequestFailedException`](https://docs.microsoft.com/en-us/dotnet/api/azure.requestfailedexception?view=azure-dotnet) from the [latest code generator](https://github.com/azure/autorest.csharp#c-code-generator-for-autorest-v3)?  If so, yes, that's compliant.

There's a good reason that only status, top-level error code, and message are exposed publicly.  While your error examples conform to the official Azure error schema at https://aka.ms/azapi/guidelines#Handling-errors, the last guideline of that section says:

> ✔️ YOU MAY treat the other fields as you wish as they are not considered part of your service's API contract and customers should not take a dependency on them or their value. They exist to help customers self-diagnose issues.

The folks at https://aka.ms/AzBreakingChangesPolicy interpret this to mean only the HTTP status code and top-level error code are part of your API's contract that cannot change between versions.  _(I think that needs to be made clearer in the REST API Guidelines though and I'll address that soon.)_  This is very important because customers should be able to upgrade to a newer version of your service without having all their application's error handling break.  So if you return a `400` when someone tries creating a duplicate resource in v1, you cannot change that to a `409` in v2 even though it's more informative.  All of the other error properties like `target`, `details`, `innerrrror`, etc., are **not guaranteed** to be the same across versions which gives you room to evolve the developer experience of your service.

Given all that, we've designed `RequestFailedException` and `ResponseError` to only expose the parts of the error payload that are safe for customers to rely on.  Everything else is only surfaced via the `Message` to aid diagnosability/debugging.  This was most recently discussed again in the `ResponseError` portion of https://github.com/Azure/azure-sdk/issues/3221 around the 25 minute mark of the recording linked in the comments.

If you're building a new service and want to review the errors of either your REST API or client libraries, consider setting up a [REST API Review](https://aka.ms/azapi) or [SDK Arch Board Review](https://aka.ms/azsdk/join) to go through everything in detail with us.

**Comment by violetVo** [comment]
Thanks a lot for the detailed answer! This clarifies things.
Regarding your question - yes, this is a `RequestFailedException` from the latest autorest code generator.
