### ISSUE TITLE
Microsoft.Azure.Batch.Conventions.Files 0.9.5-preview is incompatible with WindowsAzure.Storage 7.2.1

### ISSUE THREAD

**Issue by peter172sp** [Azure/azure-sdk-for-net#2539]
It would be nice if the latest azure batch package was compatible with the latest azure storage package. When trying to use this combination, calling TaskOutputStorage.SaveAsync, I get this error

```
	{System.MissingMethodException: Method not found: 'System.Threading.Tasks.Task Microsoft.WindowsAzure.Storage.Blob.CloudBlockBlob.UploadFromFileAsync(System.String, System.IO.FileMode, System.Threading.CancellationToken)'.
   at Microsoft.Azure.Batch.Conventions.Files.StoragePath.<SaveAsync>d__3.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.Azure.Batch.Conventions.Files.StoragePath.SaveAsync(IOutputKind kind, String sourcePath, String destinationRelativePath, CancellationToken cancellationToken)
   at Microsoft.Azure.Batch.Conventions.Files.StoragePath.<SaveAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.Azure.Batch.Conventions.Files.TaskOutputStorage.<SaveAsyncImpl>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.Azure.Batch.Conventions.Files.TaskOutputStorage.<SaveAsync>d__6.MoveNext()}
```

**Comment by peter172sp** [comment]
see PR #2540

**Comment by matthchr** [comment]
Duplicating my comment on your PR here for the record:
Unfortunately, we have a bit of a dependency problem:

Powershell depends on our C# library. Our C# library depends on Azure Storage 6.2. All of the other Azure Powershell modules depend on storage 6.2 as well (and since Azure ships Powershell as a single unit all of them must match). This means we cannot update our C# library from 6.2...
But if FileConventions (which is an extension on top of our C# client) gets upgraded to 7.2 then it will conflict.

The solution to this problem is to probably to break our C# libraries dependency on storage 6.2 out into a separate assembly which then can be optionally included (PSH actually doesn't use that functionality) which will let us rev the versions independently of powershell (and then we can move to Storage 7.2 for both FileConventions and Task file staging). Note that this still doesn't resolve all the problems -- if you wanted to use Storage 5.1 or something it may not work because 5.1 isn't compatible with 6.2 or 7.2... so there will always be issues for somebody due to the way the Storage dependency is versioned and the fact that it has had some breaking changes made.

**Comment by matthchr** [comment]
Hi @peter172sp, sorry for the delay. We're in the process of updating our client to more gracefully handle this situation ([in PR here](https://github.com/Azure/azure-sdk-for-net/pull/2822)).

What we are doing is this: 
1. We split out the stuff in Azure.Batch that used storage to a separate assembly which will be called Azure.Batch.FileStaging. (Note this isn't published on NuGet yet but it will be shortly).
2. We removed the storage dependency from Azure.Batch entirely, which freed us from the restriction that we must target 6.2 due to powershell.
3. We updated the storage dependency in both Azure.Batch.FileStaging and Azure.BatchFileConventions to be 8.0.1

Hopefully this should resolve your issue (and similar issues that other customers had run into).

Thank you for your patience,
-Matt

**Comment by matthchr** [comment]
@peter172sp This is all published now: 
[Azure.Batch which doesn't rely on storage at all](https://www.nuget.org/packages/Azure.Batch/)
[Microsoft.Azure.Batch.Conventions.Files which targets the latest storage library (8.0.1)](https://www.nuget.org/packages/Microsoft.Azure.Batch.Conventions.Files)
[Azure.Batch.FileStaging which contains the logic which used to be in Azure.Batch and requires storage (targets storage 8.0.1)](https://www.nuget.org/packages/Azure.Batch.FileStaging/)

I am closing this issue as I think it should resolve your problem.
