### ISSUE TITLE
CryptographyClient - Using the WebJsonKey decrypting not working locally.

### ISSUE THREAD

**Issue by ShekarKalyankar** [Azure/azure-sdk-for-net#25403]
**Describe the bug**
Current architecture is:
Azure Function -> 1 Activity Function -> Batches iteration (synch) -> Individual batch iteration (async) -> Decrypting and Encrypting for each record using CryptographyClient

We need to process 40 million requests, our process will decrypt and encrypt for every iteration, and is not able to handle even a 1000 requests. 
I noticed that can handle only 999 at the top. 
So the statistics shown in this page https://docs.microsoft.com/en-us/azure/key-vault/general/service-limits doesn’t seem accurate, that is one thing. 

Now, trying to improve the performance, to do all parts of the process asynchronous and running in parallel, the other issue is, I’m trying to setup the CryptographyClient using the WebJsonKey which seems to work for Encrypting without doing the roundtrip to Key Vault, it does the encryption locally, but is not working the same for decrypting using the WebJsonKey, is throwing an error: Key does not exist.

How do we overcome this 2 problems?

**Expected behavior**
CryptographyClient using the WebJsonKey should also work for decrypting locally.

**Actual behavior (include Exception or Stack Trace)**
CryptographyClient using the WebJsonKey which seems to work for Encrypting without doing the roundtrip to Key Vault, it does the encryption locally, but is not working the same for decrypting using the WebJsonKey, is throwing an error: Key does not exist.

**To Reproduce**
Steps to reproduce the behavior (include a code snippet, screenshot, or any additional information that might help us reproduce the issue)

**Environment:**
 - Name and version of the Library package used: [e.g. Azure Function, Azure KeyVault] 
 - Hosting platform or OS and .NET runtime version - .net core 3.1 application hosted on Azure Function

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by heaths** [comment]
The number of requests depend on the operation type and whether you're using an HSM-backed key or a purely software key, as shown here for Key Vault: https://docs.microsoft.com/en-us/azure/key-vault/general/service-limits#key-transactions-maximum-transactions-allowed-in-10-seconds-per-vault-per-region1. How did you create your `CryptographyClient` in this way as well that you're seeing lower limits? And are you counting both encrypt and decrypt as a transaction, because each of those is a separate transaction to Key Vault.

Public and private key implementations using a JSON Web Key (JWK) [should work](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/keyvault/Azure.Security.KeyVault.Keys/tests/LocalCryptographyClientTests.cs) in `CryptographyClient`, but depend on what information is available. For example, how did you get the JWK? If you got it from Key Vault it will only have the public key. The private key is not currently released. If you have a copy of the JWK from somewhere else, how did you deserialize into a `JsonWebKey`? The only supported way is to use the [`JsonWebKeyConverter`](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/keyvault/Azure.Security.KeyVault.Keys/src/JsonWebKeyConverter.cs), for which we also [have samples](https://github.com/heaths/azure-sdk-for-net/blob/main/sdk/keyvault/Azure.Security.KeyVault.Keys/samples/Sample7_SerializeJsonWebKey.md).

But if performance is critical, you might instead consider key wrap / unwrap. This is common for streaming block ciphers, like encrypting media. You would wrap a symmetric key (e.g. AES) you create and can safely store the wrapped result. Pass that to Key Vault to unwrap it using your secured asymmetric key (RSA) and you have your symmetric key you can use within your service for faster encryption and decryption. This also means a single transaction to Key Vault to unwrap, and you don't need to store your private key outside of Key Vault, which isn't recommended (pretty much defeats the main purpose of using Key Vault).

/cc @schaabs as I'll be on vacation for a while.

**Comment by ShekarKalyankar** [comment]
•	We don’t have any issues to get the key
•	We don’t have any issues to serialize or deserialize the key
•	We don’t have any issues to wrap and unwrap
•	When you say “If you got it from Key Vault it will only have the public key. The private key is not currently released”, I think that is why not going to work to decrypt locally, that means without doing an internal call to Key Vault to do the process remotely, we want it to do it locally as it is working for encrypting. We may think now that the message “Key does not exist” refers to the private key.
•	So, any possibility that the product can change to allow it? That’s the whole point of our request, because the roundtrip to Key Vault is what hurts the performance. But I also understand, that’s what it makes us dependent on Key Vault.

**Comment by heaths** [comment]
Currently, no, it's not possible to release the private key. That's why I recommended using key wrap and unwrap, which was designed for this purpose. It's not a limitation of the SDK, but of Key Vault as designed: the private key, unless you generate it locally and import it, is not designed to be exportable.

You can use a symmetric key to improve performance, given that RSA, for example, can only encrypt a block size based on the key size and algorithm. It's not designed for larger blocks or streaming applications.

See https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/keyvault/Azure.Security.KeyVault.Keys/samples/Sample6_WrapUnwrap.md for an example of wrapping and unwrapping keys. By storing an wrapped symmetric key, say, as part of your data, you can control access to the key - granting the application only the ability to unwrap the symmetric key - and perform all operations locally and faster than using RSA.
