### ISSUE TITLE
ServiceBusMessageActions - Add support for batch completing messages

### ISSUE THREAD

**Issue by oystehei** [Azure/azure-sdk-for-net#25461]
**Library or service name.**
Microsoft.Azure.WebJobs.Extensions.ServiceBus, Version=5.1.0.0
 
**Is your feature request related to a problem? Please describe.**
I'm currently trying to migrate some code from the old `MessageReceiver` class to use the new `ServiceBusMessageActions` class instead. Using the `MessageReceiver` it is possible to complete a list of messages by sending a list of lock tokens to the `CompleteAsync()` method. This is useful when processing messages in batches, to avoid multiple roundtrips to the Service Bus.

From what I can see this is currently not possible using the `ServiceBusMessageActions` class, as the `CompleteMessageAsync()` method only accepts a single message. It would be nice to see support for completing a list of messages as well.

**Comment by jsquire** [comment]
Hi @oystehei.  Thank you for your feedback.  Unfortunately, this request has been discussed previously and is not something that we will be adding to the Service Bus client library.  There is no support for multiple complete or abandon operations offered by the Service Bus service; the previous `MessageReceiver` implementation of the batched API was client-side only and implemented  similar to:

```csharp
  var tasks = new List<Task>();

  for (ServiceBusReceivedMessage message in messages)
  {
      tasks.Add(receiver.CompleteMessageAsync(message));
  }

  await Task.WhenAll(tasks);
```   

We have concerns that this implementation introduces complexity and confusion around error scenarios due to the potential for partial success.  It also causes confusion around the performance characteristics, potentially hiding a  performance bottleneck, as it was often assumed to be a single batch call.  Since this pattern is fairly straight-forward to implement, we felt it was better applied in the application than hidden within the SDK.    

More context and the full discussion can be found in [#7291](https://github.com/Azure/azure-sdk-for-net/issues/7921).

**Comment by oystehei** [comment]
Thanks for the detailed explanation @jsquire, appreciate it 👍
