### ISSUE TITLE
QueueTrigger binding support updating the queue message

### ISSUE THREAD

**Issue by camerondm9** [Azure/azure-sdk-for-net#25470]
**Library or service name.**
Microsoft.Azure.WebJobs.Extensions.Storage.Queues
Microsoft.Azure.WebJobs.Extensions.Storage.Common (relevant code is actually here)
 
**Is your feature request related to a problem? Please describe.**
I would like there to be a way to update the QueueMessage that triggered my function. I see that the [QueueListener](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/storage/Microsoft.Azure.WebJobs.Extensions.Storage.Common/src/Shared/Queues/QueueListener.cs#L378) already has code in place to do this to extend the hidden time of the queue message, and I don't want to interfere with that, but I would like to update the contents of the message to record which parts of the work have been completed. This would ensure that even if my function fails, when the queue message is retried, the next function instance can resume without doing all the work again.

Currently I'm updating the message myself, but doing that invalidates the pop receipt that the [QueueProcessor](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/storage/Microsoft.Azure.WebJobs.Extensions.Storage.Common/src/Shared/Queues/QueueProcessor.cs#L88) will use when the function completes successfully, or to extend the message hidden time, so that means I have to also delete the message myself. Since extending the message hidden time is also broken, I'm just cancelling my function after 4 minutes to prevent that code from running.

It would be nice if I could update the message contents without breaking most of the QueueTrigger internals.

**Comment by PramodValavala-MSFT** [comment]
@camerondm9 Thanks for the feedback! I have routed this to the appropriate team for review.

While updating the message is indeed one way to go about this, you could also consider one of the following approaches as well

1. Use a separate store to keep track of progress. This way the state of your workflow is stored separately to the queue message that triggers the workflow. You could also use this to query the progress from other systems.
2. Implement the [Choreography Pattern](https://docs.microsoft.com/en-us/azure/architecture/patterns/choreography). This would just be a set of functions (one for each step in your workflow) listening on their own queues.
3. Leverage [Durable Functions](https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-overview?tabs=csharp). This uses queues internally to ensure workflows are run to completion and works around the timeout per function since each step would be a separate function call.
