### ISSUE TITLE
How to copy a blob from NFSv3-enabled storage account

### ISSUE THREAD

**Issue by AntonZiminSaritasa** [Azure/azure-sdk-for-net#25481]
**Query/Question**
I try to copy a blob from a storage account that has NFSv3 enabled.

```
            var source = "https://source.blob.core.windows.net/container1/file1.bin?sv=2020-10-02&st=2021-11-23T08%3A53%3A18Z&se=2021-12-01T08%3A53%3A00Z&sr=b&sp=r&sig=8Bt3I1guQe0VXjMjeOGOhPHv5tS2%2BH8gpx00bWhCnnE%3D";
            var target = "https://target.blob.core.windows.net/container2/file2.bin?sv=2020-08-04&st=2021-11-23T08%3A54%3A13Z&se=2021-12-01T08%3A54%3A00Z&sr=c&sp=racwl&sig=WZULxHkbM6yo4s%2FIw%2FKH7UNpaf4AQVxnhxIUGq0nv88%3D";

            var blobClient = new Azure.Storage.Blobs.BlobClient(new Uri(target));
            var result = await blobClient.StartCopyFromUriAsync(new Uri(source));
```

The operation fails. Diagnostic logs show the following error:

```
StatusCode
409

OperationName
GetBlockList

StatusCode
409

StatusText
BlobOperationNotSupportedForBlobCreatedByNfsV3
```

I can download the blob without an issue:
```
            var blobClient = new Azure.Storage.Blobs.BlobClient(new Uri(source));
            await blobClient.DownloadToAsync(@"C:\Temp\MyFile");
```

Also, `azcopy copy` works fine.

```
.\azcopy_windows_amd64_10.12.2\azcopy.exe" copy 'source' 'target'
```

How can I copy the blob without downloading and re-uploading?

**Environment:**
 - Azure.Storage.Blobs 12.10.0
```PM> dotnet --info
.NET SDK (reflecting any global.json):
 Version:   5.0.403
 Commit:    bf9d168ac2

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19043
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.403\

Host (useful for support):
  Version: 5.0.12
  Commit:  7211aa01b3
```

-----

It happens only for blobs created by NFS. I can copy blobs created using the storage SDK without an issue.

**Comment by amnguye** [comment]
Hi, could you double check that the `StartCopyFromUriAsync` actually causes the following error you posted.

According to the error you posted, it looks like you attempted to do a `GetBlockList` and received a 409 error. But your claim is that the `StartCopyFromUri` command caused this error. I looked in our internals, and we do not call `GetBlockList` under the hood either (and there's no reason for us to either).

**Comment by AntonZiminSaritasa** [comment]
@amnguye 
You're right, I found another error:

```
CallerIpAddress
52.239.151.128

OperationName
GetBlobProperties

AuthenticationType
SAS

StatusCode
403

StatusText
AuthorizationFailure
```

Apparently, I need to include the range `52.239.150.0/23` to the firewall somehow.

**Comment by amnguye** [comment]
This other error is a `GetProperties` Error, please provide an error related to your original issue. (StartCopyFromUriAsync).

**Comment by AntonZiminSaritasa** [comment]
Here are all requests from the diagnostic logs:

| Uri       | File Uploaded By | TimeGenerated [UTC]        | OperationName     | AuthenticationType | StatusCode | StatusText                                     | CallerIpAddress      | UserAgentHeader                                                                           |
|-----------|------------------|----------------------------|-------------------|--------------------|------------|------------------------------------------------|----------------------|-------------------------------------------------------------------------------------------|
| file1.txt | Storage Explorer | 11/23/2021, 8:08:45.705 PM | GetBlobProperties | SAS                | 403        | AuthorizationFailure                           | 52.239.151.128:62272 | azsdk-net-Storage.Blobs/12.10.0 (.NET 6.0.0-rtm.21522.10; Microsoft   Windows 10.0.22000) |
| file1.txt | Storage Explorer | 11/23/2021, 8:08:45.847 PM | GetBlobProperties | SAS                | 200        | Success                                        | 99.128.xxx.xxx:62273 | azsdk-net-Storage.Blobs/12.10.0 (.NET 6.0.0-rtm.21522.10; Microsoft   Windows 10.0.22000) |
| file1.txt | Storage Explorer | 11/23/2021, 8:08:45.996 PM | GetBlockList      | SAS                | 200        | Success                                        | 99.128.xxx.xxx:37504 | services_xstore_transport_HTTP2/1.0                                                       |
| file1.txt | Storage Explorer | 11/23/2021, 8:08:46.031 PM | GetBlob           | SAS                | 206        | Success                                        | 99.128.xxx.xxx:37504 | services_xstore_transport_HTTP2/1.0                                                       |
|           |                  |                            |                   |                    |            |                                                |                      |                                                                                           |
| file2.txt | NFSv3            | 11/23/2021, 8:10:23.353 PM | GetBlobProperties | SAS                | 403        | AuthorizationFailure                           | 52.239.151.128:9344  | azsdk-net-Storage.Blobs/12.10.0 (.NET 6.0.0-rtm.21522.10; Microsoft   Windows 10.0.22000) |
| file2.txt | NFSv3            | 11/23/2021, 8:10:23.494 PM | GetBlobProperties | SAS                | 200        | Success                                        | 99.128.xxx.xxx:9345  | azsdk-net-Storage.Blobs/12.10.0 (.NET 6.0.0-rtm.21522.10; Microsoft   Windows 10.0.22000) |
| file2.txt | NFSv3            | 11/23/2021, 8:10:23.623 PM | GetBlockList      | SAS                | 409        | BlobOperationNotSupportedForBlobCreatedByNfsV3 | 99.128.xxx.xxx:37505 | services_xstore_transport_HTTP2/1.0                                                       |

I have 2 files:
file1.txt - uploaded using Storage Explorer, copy works fine for it.
file2.txt - created using NFSv3, copy does not work.

**Comment by amnguye** [comment]
According to your logs, it says the `BlobOperationNotSupportedForBlobCreatedByNfsV3` was caused by the an application by the user agent `services_xstore_transport_HTTP2/1.0` not `azsdk-net-Storage.Blobs/12.10.0 (.NET 6.0.0-rtm.21522.10; Microsoft Windows 10.0.22000)` (which is our SDK user agent).

Also I already confirmed that the `StartCopyFromUri` API calls into the [Copy Blob From Url](https://docs.microsoft.com/en-us/rest/api/storageservices/copy-blob-from-url) which is not the same as the `GetBlockList` operation.

Please confirm whether or not the application you are writing send the user agent string as `services_xstore_transport_HTTP2/1.0` and that you are altering the user agent string to be this header value.

**Comment by AntonZiminSaritasa** [comment]
@amnguye 
I executed the API request manually without the .NET SDK and I can confirm that every `import` request produces 3 lines in the diagnostics log.

```
PUT https://target.blob.core.windows.net/container2/file2_sftp.txt?sv=2020-08-04&st=2021-11-23T08%3A54%3A13Z&se=2021-12-01T08%3A54%3A00Z&sr=c&sp=racwl&sig=WZULxHkbM6yo4s%2FIw%2FKH7UNpaf4AQVxnhxIUGq0nv88%3D HTTP/1.1
Host: target.blob.core.windows.net
x-ms-copy-source: https://source.blob.core.windows.net/container1/file2.txt?sv=2020-10-02&st=2021-11-23T19%3A54%3A54Z&se=2021-12-01T19%3A54%3A00Z&sr=b&sp=r&sig=wv0KVfbESRqdQpdnbqMFwYTbMQUD1gd%2FuoEC8Cs4Z0g%3D
x-ms-version: 2020-10-02
Accept: application/xml
x-ms-client-request-id: d464c562-6754-40ca-aa30-4a4b97100d73
x-ms-return-client-request-id: true
User-Agent: Fiddler
Content-Length: 0
```

```
| TimeGenerated   [UTC]      | OperationName     | AuthenticationType | StatusCode | StatusText                                     | CallerIpAddress     | UserAgentHeader                     |
|----------------------------|-------------------|--------------------|------------|------------------------------------------------|---------------------|-------------------------------------|
| 11/23/2021, 8:55:08.833 PM | GetBlobProperties | SAS                | 403        | AuthorizationFailure                           | 52.239.151.128:2048 | Fiddler                             |
| 11/23/2021, 8:55:08.969 PM | GetBlobProperties | SAS                | 200        | Success                                        | 99.128.xxx.xxx:2049 | Fiddler                             |
| 11/23/2021, 8:55:09.301 PM | GetBlockList      | SAS                | 409        | BlobOperationNotSupportedForBlobCreatedByNfsV3 | 99.128.xxx.xxx:9984 | services_xstore_transport_HTTP2/1.0 |
```

Maybe Azure creates multiple log items per log request or it passes my IP address for additional internal requests.

`services_xstore_transport_HTTP2/1.0` is not my user agent. I assume it belongs to the internal Azure copy worker.

**Comment by amnguye** [comment]
Could you get me the details of that one request that you sent then (e.g. the full request made, and the full response made). Please also redact any credentials or signatures.

**Comment by AntonZiminSaritasa** [comment]
@amnguye 
Please see above, I added the response to my previous comment.

**Comment by amnguye** [comment]
Okay I see what's happening now. Obviously `Copy Blob`, e.g. `StartCopyFromUri` is not supported by NFSv3 currently.

The reason azcopy (and storage explorer since it also uses azcopy) works is because they're using `Put Blob From Url`. In order to do copies with NFSv3. the API needs to change to using [Put Blob From Url](https://docs.microsoft.com/en-us/rest/api/storageservices/put-blob-from-url)

The SDK API to call this method is [BlockBlobClient.SyncUploadFromUri](https://docs.microsoft.com/en-us/dotnet/api/azure.storage.blobs.specialized.blockblobclient.syncuploadfromuriasync?view=azure-dotnet). Please use this one instead.

**Comment by AntonZiminSaritasa** [comment]
@amnguye
Unfortunately, it does not work. `SyncUploadFromUriAsync` uses the same API with additional `x-ms-requires-sync` header.

Request:
```
PUT https://target.blob.core.windows.net/targetcontainer/file2_sftp.txt?sv=2020-08-04&st=2021-11-23T08%3A54%3A13Z&se=2021-12-01T08%3A54%3A00Z&sr=c&sp=racwl&sig=xxxx HTTP/1.1
Host: iwim2dev.blob.core.windows.net
x-ms-requires-sync: true
x-ms-copy-source: https://source.blob.core.windows.net/sourcecontainer/file3.txt?sv=2020-10-02&st=2021-11-23T22%3A41%3A37Z&se=2021-12-01T22%3A41%3A00Z&sr=b&sp=r&sig=xxxx
x-ms-version: 2020-10-02
Accept: application/xml
x-ms-client-request-id: 10b16214-892d-47c7-9e7c-f6b1e776e84e
x-ms-return-client-request-id: true
User-Agent: azsdk-net-Storage.Blobs/12.10.0 (.NET 6.0.0-rtm.21522.10; Microsoft Windows 10.0.22000)
Content-Length: 0
```

Response:
```
HTTP/1.1 409 Copy source blob has been modified.
Content-Length: 226
Content-Type: application/xml
Server: Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0
x-ms-request-id: 35cc9539-301e-0009-0bbd-e0ff0d000000
x-ms-client-request-id: 10b16214-892d-47c7-9e7c-f6b1e776e84e
x-ms-version: 2020-10-02
x-ms-error-code: CannotVerifyCopySource
Date: Tue, 23 Nov 2021 22:57:18 GMT

<?xml version="1.0" encoding="utf-8"?><Error><Code>CannotVerifyCopySource</Code><Message>Copy source blob has been modified.
RequestId:35cc9539-301e-0009-0bbd-e0ff0d000000
Time:2021-11-23T22:57:19.2748708Z</Message></Error>
```

The log contains the same error `BlobOperationNotSupportedForBlobCreatedByNfsV3`.

**Comment by AntonZiminSaritasa** [comment]
Here's a workaround that works:
```
            var sourceClient = new Azure.Storage.Blobs.BlobClient(sourceUri);
            var destClient = new Azure.Storage.Blobs.BlobClient(destUri);

            using (var sourceStream = await sourceClient.OpenReadAsync())
            {
                await destClient.UploadAsync(sourceStream);
            }
```

**Comment by amnguye** [comment]
Thanks for providing a request and response that uses the SDK.

Though that request looks like it's sending a [BlobBaseClient.SyncCopyFromUri](https://docs.microsoft.com/en-us/dotnet/api/azure.storage.blobs.specialized.blobbaseclient.synccopyfromuri?view=azure-dotnet) request rather than a [BlockBlobClient.SyncUploadFromUri](https://docs.microsoft.com/en-us/dotnet/api/azure.storage.blobs.specialized.blockblobclient.syncuploadfromuriasync?view=azure-dotnet) request. I can depict this because `x-ms-requires-sync` is a required header on the [Copy Blob From Url](https://docs.microsoft.com/en-us/rest/api/storageservices/copy-blob-from-url) (e.g. SyncCopyFromUri) rest call and not on the [Put Blob From URL](https://docs.microsoft.com/en-us/rest/api/storageservices/put-blob-from-url) (e.g. SyncUploadFromUri) Rest call. While the Put Blob From URL rest call requires the `x-ms-blob-type: BlockBlob` header and value, and your request did not have this value.

I just ran both these APIs and they both send the headers expected (e.g. BlockBlobClient.SyncUploadFromUri has the `x-ms-blob-type: BlockBlob` header and value, but not the `x-ms-requires-sync` header, and the BlobBaseClient.SyncCopyFromUri has `x-ms-requires-sync` header but not the x-ms-blob-type: BlockBlob` header and value)

---

The workaround would work if you have the capacity to download the blob and re-upload the blob, and that has already been confirmed that in your original post when you said you were able to download the blob.

Does not solve the question of  "How can I copy the blob without downloading and re-uploading?"

**Comment by AntonZiminSaritasa** [comment]
Perhaps `SyncUploadFromUri` can't work across different storage accounts and falls back to `SyncCopyFromUri`.

> Does not solve the question of "How can I copy the blob without downloading and re-uploading?"

As far as understand, I need to use the workaround for now. Maybe later copying of NFSv3 blobs will be added to the API.

**Comment by amnguye** [comment]
> Perhaps SyncUploadFromUri can't work across different storage accounts and falls back to SyncCopyFromUri.

This is incorrect. Please send me a code snippet with your updated code using the BlockBlobClient.SyncUploadFromUri

`SyncUploadFromUri` works across different storage account, and does not state otherwise in the documenation, and I also have tested this across my storage accounts.

**Comment by AntonZiminSaritasa** [comment]
@amnguye 
Thank you! It works.

```
            var sourceUri = new Uri("https://source.blob.core.windows.net/sourcecontainer/tenant7/file3.txt?sv=2020-10-02&st=2021-11-23T22%3A41%3A37Z&se=2021-12-01T22%3A41%3A00Z&sr=b&sp=r&sig=xxxx");
            var destUri = new Uri("https://target.blob.core.windows.net/targetcontainer/file1644.txt?sv=2020-08-04&st=2021-11-23T08%3A54%3A13Z&se=2021-12-01T08%3A54%3A00Z&sr=c&sp=racwl&sig=xxxx");

            var blockBlobClient = new Azure.Storage.Blobs.Specialized.BlockBlobClient(destUri);
            var restult = await blockBlobClient.SyncUploadFromUriAsync(sourceUri);
```
