### ISSUE TITLE
[QUERY]Blob StorageでCreateIfNotExistsを使用するとHTTPStatus409が発生する

### ISSUE THREAD

**Issue by fj6731bn** [Azure/azure-sdk-for-net#25540]
**Question**
ファイル有無が分からない Blob Storage に対して、storage client library Ver7.1.2で
「CreateIfNotExists();」を行うと正常に完了するが、storage client library Ver9.3.3では
Application Insightsの失敗にHTTPStatus409が記録される。
実行するコードは同じなのですが、仕様が変わったのでしょうか。回避策があれば教えてください。

**Environment:**
storage client library Ver9.3.3
AppService
StorageV2 (general purpose v2)
.NetFramework 4.7.2
IDE and version : Visual Studio 16.8.5

**Sample Code.**
            // Blobクライアントの取得
            _client = _clients.GetOrAdd(connectionString, (cs) =>
            {
                var account = StorageManager.CreateStorageAccount(cs);
                var client = account.CreateCloudBlobClient();
                client.DefaultRequestOptions.RetryPolicy = retryPolicy;
                return client;
            });
            // コンテナの取得
            _container = _client.GetContainerReference(containerName);
            // パブリックアクセスを設定
            if (publicAccess.HasValue == true)
            {
                var p = _container.GetPermissions();
                p.PublicAccess = publicAccess.Value;
                _container.SetPermissions(p);
            }
            _container.CreateIfNotExists();

**Comment by jsquire** [comment]
Hi @fj6731bn.  Thank you for your feedback and we regret that you're experiencing difficulties.  Unfortunately, this repository is English-based and we're not able to understand your scenario well enough to help.   Would you be able to translate into English so that we can assist?   If you're unable to translate, your best path forward would be to [open an Azure support request](https://docs.microsoft.com/azure/azure-portal/supportability/how-to-create-azure-support-request), where they'll have folks with the language skills needed to help.

**Comment by amnguye** [comment]
Hi,

I apologize in advance if I got the Japanese Translation wrong.

Looks like you're using version 9.3.3 of the Blobs package. That package is currently deprecated, I suggest you update to version 12.

However for a short explanation, that's the expectation if you did a CreateIfNotExists on a Blob that already exists. The SDK recevies the 409 BlobAlreadyExists error that you see in Application Insights, and omits it from your view since that's the functionality of CreateIfNotExists. This is expected behavior of the API.

**Comment by fj6731bn** [comment]
thank you.

This case complies with the specifications.
I understand that it cannot be suppressed.
