### ISSUE TITLE
[QUERY] Storage bindings extension v5 upgrade

### ISSUE THREAD

**Issue by dxynnez** [Azure/azure-sdk-for-net#25570]
### Library name and version

Microsoft.Azure.WebJobs.Extensions.Storage 5.0

### Query/Question

Hi team,

We are currently migrating to the Microsoft.Azure.WebJobs.Extensions.Storage 5.0 to take advantage of the new identity-based connection. However, we do notice that in the old storage queue SDK the message are base64 encoded by default while in the new SDK the default is no encoding - we do want to switch to the new default behavior (no encoding), but that would mean that any existing message in the queue wouldn't be processed correctly by our function app.

Is there a way to allow queue trigger functions to handle messages w/ & w/o encoding at the same time so that we can leave enough buffer time before completely switching to no encoding?

**Comment by PramodValavala-MSFT** [comment]
@dxynnez While the new storage SDK defaults to no encoding, the extension exposes the encoding via [`host,json`](https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-storage-queue#hostjson-settings) and defaults to Base64.

**Comment by dxynnez** [comment]
Thanks @PramodValavala-MSFT . I understand that it's possible to change the encoding. My question was what would be the best way to migrate to the new SDK default (no encoding) for an existing function app? Would it be possible for storage binding to 'auto-detect' the encoding and decode the message accordingly (so that the old base64 encoded messages can be flushed out)? Otherwise, we will have to stick with Base64 encoded basically forever...

**Comment by dxynnez** [comment]
Hello @PramodValavala-MSFT , any comment?

**Comment by PramodValavala-MSFT** [comment]
@dxynnez Sorry for not getting back sooner! The extension currently retries until the configured max dequeue count and then sends messages to the poison queue. So one approach would be to process these messages separately by checking if they have failed due to being base64 which can be checked by binding to a string and [check if its base64](https://stackoverflow.com/a/54143400/10417839).

If your actual function is also binding to a string (or QueueMessage so that we can get the raw payload) or if it can be changed to do so, then you could perform the same check in code and process the incoming string based on whether it is Base64 or not. This code will be just an extra check after all the base64 messages are processed and none are being sent no more. Your code could be something like this (leveraging code from [this SO answer](https://stackoverflow.com/a/54143400/10417839))

```cs
using System;
using System.Text;
using System.Text.Json;
using Microsoft.Azure.WebJobs;
using Microsoft.Extensions.Logging;

namespace Some.Function
{
  public class SampleObject
  {
    public string Data { get; set; }
  }

  public static class TestBase64Encoding
  {
    [FunctionName("TestBase64Encoding")]
    public static void Run([QueueTrigger("do-nothing", Connection = "CONN_STORAGE")] string raw, ILogger log)
    {
      var o = JsonSerializer.Deserialize<SampleObject>(TryBase64Decode(raw) ?? raw);

      log.LogInformation($"C# Queue trigger function processed: {o.Data}");
    }

    public static string TryBase64Decode(string base64)
    {
      Span<byte> buffer = new Span<byte>(new byte[base64.Length]);
      if (Convert.TryFromBase64String(base64, buffer, out int bytesParsed))
      {
        return Encoding.ASCII.GetString(buffer).TrimEnd('\0');
      }

      return null;
    }
  }
}
```

I believe the first option is more preferred for such changes, but both should achieve the same goal.

**Comment by dxynnez** [comment]
Thanks @PramodValavala-MSFT . If I understand you correctly, you were suggesting to set the messageEncoding to none and decode if it's base64 encoded; otherwise use it as plain string (assuming we can process them the same way whether it's base64 encode or not).

**Comment by PramodValavala-MSFT** [comment]
@dxynnez for the first part, yes that is correct.

For Durable Functions, I believe they have separate settings and since the underlying library still uses the older storage SDK, it will continue to use the base64 encoding I suppose. @cgillum Could you confirm?

**Comment by cgillum** [comment]
Correct, the Durable Functions settings are independent of the Storage extension settings. Durable Functions doesn't expose any setting to control the encoding - the encoding we use is an implementation detail of our storage provider that shouldn't impact your application.

**Comment by PramodValavala-MSFT** [comment]
@dxynnez Just following up here... Hope this clears things up

**Comment by dxynnez** [comment]
> @dxynnez Just following up here... Hope this clears things up

Sorry for the delayed response! Yes it does! Thanks for the help!
