### ISSUE TITLE
[BUG] CopyStatus is not correct when the blob is not a copied blob

### ISSUE THREAD

**Issue by jeffhli** [Azure/azure-sdk-for-net#25634]
### Library name and version

Azure.Storage.Blobs 12.11.0

### Describe the bug

Now I have a blob that is uploaded to a container in a storage account. But when I get the blob properties and check the CopyStatus, the value is Pending which is odd that the blob is not a copied blob and is not being copied.

### Expected behavior

For a blob that is not being copied, The CopyStatus should be null.

### Actual behavior

Pending

### Reproduction Steps

1. Upload a blob.
2. Get the blob properties
3. Check the CopyStatus

**Comment by SaurabhSharma-MSFT** [comment]
@jeffhli We are looking into this and get back to you.

**Comment by MughundhanRaveendran-MSFT** [comment]
@jeffhli , Could you please share the code that you are using to retrieve the copy status?

I am using the below method to retrieve the properties of the uploaded blob but that doesn't give me the copy status

https://docs.microsoft.com/en-us/azure/storage/blobs/storage-blob-properties-metadata?tabs=dotnet#set-and-retrieve-properties

**Comment by jeffhli** [comment]
```
BlobServiceClient serviceClient = new BlobServiceClient(connectionString);
var container = serviceClient.GetBlobContainerClient(containername);
var blob = container.GetBlobClient(blobId);
await blob.UploadAsync(filepath);
BlobProperties destProperties = await blob.GetPropertiesAsync();

Console.WriteLine($"Copy Id: {destProperties.CopyId}");
Console.WriteLine($"Copy status: {destProperties.CopyStatus}");
Console.WriteLine($"Copy progress: {destProperties.CopyProgress}");
Console.WriteLine($"Completion time: {destProperties.CopyCompletedOn}");
Console.WriteLine($"Total bytes: {destProperties.ContentLength}");
```
Then the result is Copy status: Pending

**Comment by MughundhanRaveendran-MSFT** [comment]
@jeffhli , Thanks for your response. I am able to reproduce the issue at my end. We will triage and let you know the progress.

**Comment by jaschrep-msft** [comment]
This appears to be a similar issue to #19263. While the poster of that issue was assuming the object would update, they ended up hitting this situation after making recommended changes.

I have reproduced this issue with the provided sample, and it stems from `BlobProperties.CopyStatus` being of type `CopyStatus` and not `CopyStatus?`, combined with the enum getting no `None = 0` value from the code generation process. `Pending` is the 0-value and so will show up even when the `x-ms-copy-status` header isn't present in the HTTP response.

This also means there's no clean way to fix this issue without introducing a breaking API change. While a boolean flag could be introduced alongside the property, that is a less-than-desirable API design. Will discuss this with the team.
