### ISSUE TITLE
Is value of SecretProperties.ExpiresOn based on UTC time?

### ISSUE THREAD

**Issue by Yomodo** [Azure/azure-sdk-for-net#25837]
[SecretProperties.ExpiresOn](https://docs.microsoft.com/en-us/dotnet/api/azure.security.keyvault.secrets.secretproperties.expireson?view=azure-dotnet#Azure_Security_KeyVault_Secrets_SecretProperties_ExpiresOn), from the documentation it is not clear if the value is based on UTC time,
as is the case with [AuthenticationResult.ExpiresOn](https://docs.microsoft.com/en-us/dotnet/api/microsoft.identity.client.authenticationresult.expireson?view=azure-dotnet) property.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 50e33539-c1bd-dc07-006e-44c71967c2c7
* Version Independent ID: d8539487-dcce-d598-2dbc-0b9faf02871d
* Content: [SecretProperties Class (Azure.Security.KeyVault.Secrets) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/azure.security.keyvault.secrets.secretproperties?view=azure-dotnet)
* Content Source: [xml/Azure.Security.KeyVault.Secrets/SecretProperties.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Azure.Security.KeyVault.Secrets/SecretProperties.xml)
* Service: **azure**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by heaths** [comment]
The service properties are, yes, but the property type - a `DateTimeOffset` - always has an associated time zone offset so whether you convert to local time or UTC time (the latter would be a no-op) it won't matter: you get the right date as originally based on the service time zone offset (UTC). This is why we use `DateTimeOffset` instead of `DateTime`, which may or may not have a timezone offset and can lead to ambiguities like this. See https://docs.microsoft.com/dotnet/api/system.datetimeoffset for details.

**Comment by Yomodo** [comment]
@heaths Thank you for the clear explanation.
