### ISSUE TITLE
Missing valid range and Exceptions thrown

### ISSUE THREAD

**Issue by itaibh** [Azure/azure-sdk-for-net#26035]
I tried using this with `int.MaxValue` and was thrown a `BadRequestException` but with no explanation. Thus I think the valid range should be documented.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2ecff54e-5ec6-cda7-4dc3-2567d316f350
* Version Independent ID: 6801ff50-1a4f-5fe1-5b5a-4f9f14b40fd6
* Content: [TableQuery&lt;TElement&gt;.TakeCount Property (Microsoft.Azure.Cosmos.Table) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.cosmos.table.tablequery-1.takecount?f1url=%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(Microsoft.Azure.Cosmos.Table.TableQuery%601.TakeCount);k(DevLang-csharp)%26rd%3Dtrue&view=azure-dotnet)
* Content Source: [xml/Microsoft.Azure.Cosmos.Table/TableQuery`1.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.Cosmos.Table/TableQuery`1.xml)
* Service: **cosmos-db**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by PramodValavala-MSFT** [comment]
@itaibh the limit itself is enforced by the service, which is [1000 entries per response](https://docs.microsoft.com/en-us/rest/api/storageservices/query-entities#response-headers). Since the behavior is to return a continuation token after 1000 entries, using `int.MaxValue` will have no effect here even if accepted since the limit would be per page. You can read more about this in the [Query Timeout and Pagination doc](https://docs.microsoft.com/en-us/rest/api/storageservices/query-timeout-and-pagination).

To iterate over all the values, you would just want to use [`ExecuteSegmentedAsync`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.cosmos.table.tablequery-1.executesegmentedasync?view=azure-dotnet) method instead which returns an iterable object that fetches records as you loop over it.

**Comment by itaibh** [comment]
I understand, but it's not accepted and in no where I could find out why. So I think it's best to add these missing pieces of information to the docs.
