### ISSUE TITLE
Search SDK: Not possible to set HttpClient.Timeout on new Azure.Search SDK (3.0.1)

### ISSUE THREAD

**Issue by viktor-morin** [Azure/azure-sdk-for-net#2604]
We updated to latest version now, since we want to run to the lastest Azure.Search API version.
However, following error occured:

```
var indexClient = _searchConnection.Indexes.GetClient(indexName);
indexClient.HttpClient.Timeout = TimeSpan.FromSeconds(3);
```

The second line is no longer possible. I could however change the timeout for _searchConnection (SearchServiceClient) but that timeout dosnt follow when creating a client. Will you fix this or how is your suggestion? To have 1min and 30s timeout is not acceptable for us (default).

**Comment by brjohnstmsft** [comment]
@viktor-morin I'll investigate and get back to you.

Related issue: https://github.com/Azure/autorest/issues/1445

**Comment by brjohnstmsft** [comment]
@viktor-morin There are actually two issues here:

1. `Indexes.GetClient` doesn't propagate the `SearchServiceClient` timeout. We can fix this and release a new version maybe some time next week.
1. `Indexes.GetClient` now returns `ISearchIndexClient` instead of `SearchIndexClient`, *and* `ISearchIndexClient` does not expose the `HttpClient` property. The good news is that you can work around this with a downcast:

```csharp
var indexClient = (SearchIndexClient)_searchConnection.Indexes.GetClient(indexName);
indexClient.HttpClient.Timeout = TimeSpan.FromSeconds(3);
```

However, arguably this shouldn't be necessary. I'll file an issue for the AutoRest code generator to promote the `HttpClient` property from the implementation to the interface. In the meantime, we can patch our interface manually to include this property so you don't need the type cast.

**Comment by brjohnstmsft** [comment]
@viktor-morin Thinking about this some more, I don't think we can add to the `ISearchIndexClient` interface without bumping the major version of the SDK. We just did that, so we'll wait until the next time we have a bunch of breaking changes before making that change. However, we can make `Indexes.GetClient` propagate the timeout value. I'll update this issue when that change is ready.

**Comment by brjohnstmsft** [comment]
@hovsepm Thanks!
