### ISSUE TITLE
[FEATURE REQ] Service Bus: Core classes public instead of internal

### ISSUE THREAD

**Issue by npehrsson** [Azure/azure-sdk-for-net#26107]
### Library name

Azure.Messaging.ServiceBus

### Please describe the feature.

Currently trying to "MOCK" ServiceBus for local-only development with a Filesystem implementation, been going through the source code and the best level of intervening would be on **TransportReceiver** and **TransportSender** level.

However, **ServiceBusConnection**, **TransportClient**, **TransportSender**, and **TransportReceiver** are internal classes which makes it unnecessarily difficult.

It would also be good to be able to inject a custom implementation of **ServiceBusConnection** into the **ServiceBusClient**

**Comment by jsquire** [comment]
Hi @npehrsson.  Support for mocking and unit testing is one of the core goals of the new Azure SDKs, and the details of the approach that we use are discussed in the [Azure SDK Design Guidelines](https://azure.github.io/azure-sdk/dotnet_introduction.html#dotnet-mocking).  

All of the public members of the client types are `virtual` or settable, the class is not sealed, and a parameterless constructor is available to ensure that it is usable with a mocking framework such as Moq or FakeItEasy.   You should be able to mock any client using the same approach that you prefer for other types, whether with a mocking framework or inheriting from the class and creating your own mock type, using the model factory to simulate behavior.  For model types that are returned by service operations, a factory class exists to enable creating them for testing.  In the case of Service Bus, the [ServiceBusModelFactory](https://docs.microsoft.com/dotnet/api/azure.messaging.servicebus.servicebusmodelfactory?view=azure-dotnet) would be the place to look.

If I understand correctly, it sounds like what you're looking to do is a replace the AMQP transport with a local filesystem implementation - essentially replacing functionality wholesale to enable a full end-to-end local development experience rather than mocking specific behavior for a test scenario.  Unfortunately, that would be a beyond the scope of our intention for mocking support.   That said, it should be possible to do this by deriving a custom client and overriding all public methods to behave as you'd like them to.  

Can you help us understand a bit more about your scenario and what appeals to you about attempting to replace the internals rather than extending and overriding client behavior?   Please forgive delays, as most of us are out for the holidays this week.  I expect that we'll not likely get a chance to continue the discussion until some point next week.

**Comment by npehrsson** [comment]
Due to that ServiceBus cannot be hosted locally through installing the service or be hosted in any container we feel the need to do our own implementation of being able to run our solution locally.

We have taken the approach to not be tied to the cloud during the development because we want the developer experience to be.

- git pull <repo>
- install some prerequisite software through a script
- open with vs.net
- select the projects you want to start
- hit F5

This would also give us_

- Cheaper development cost (not the driver for doing this)
- Faster/easier to reset the environment
- Easier to get an overview of what data/messages are in the files

We do today have an implementation on top of the IReceiverClient and ISenderClient in the _old_ package.

We were first aiming to extend the ServiceBusClient ServiceBusReceiver, ServiceBusSender implementations, but when we saw that we could inject the custom code at the _root_ instead of the _leaf_ level.

The pros for doing it at the _root_ level would be:
-  Lesser methods and classes to override.
-  Closer to the real implementation.

Implementation thoughts at the Transport-level with the filesystem with
- FileWatcher for push
- File locking for message locks
- Directories for topics and message logs
- Deferred, TTL messages management would be handled by the client doing some cleanups.

In most cases, we do not need the performance when we're developing and when we do we would like to build it so that when giving the ServiceBusFactory the service-bus connection string instead of the directory path it would switch to the real implementation.

**Comment by jsquire** [comment]
Hi @npehrsson.   Thank you for your patience and the additional context.  

The obvious challenge of exposing our implementation details is that they become part of the public API surface - which requires that we ensure no breaking changes to them and that they would need to follow the Azure SDK guidelines and be subject to API governance.  This would be a fairly large effort that would need to be coordinated across the different languages of the Service Bus client library, most of which don't have a transport abstraction currently.  It would very likely mean non-trivial changes to the API surface of the transport abstraction (as part of governance review) and would lead to us pushing our current implementation down a level of abstraction to retain the flexibility to change our implementation without impacting the public surface.  

If I'm being honest, given that the scenario can be implemented by extending the public API of the clients themselves, I don't believe that we can make a case to justify the additional costs for engineering and governance investment needed.  I'm going to mark this as addressed, as I don't believe that we can take this further.  Please feel free to unresolve if you'd like to continue the discussion.
