### ISSUE TITLE
Queue SDK 12.8.0 Returns Multiple Error Patterns for Enqueue to Deleted Storage Account - AggregateException Inner RequestFailedException is Missing ErrorCode

### ISSUE THREAD

**Issue by dolenox** [Azure/azure-sdk-for-net#26174]
Hi Azure Devs,

I am writing an auto failover class that enables our queue wrapper to fall back to a backup storage account via circuit breaker, to handle cases where someone may accidentally delete a storage account in prod.

I've noticed two separate exception patterns in this case:

1) RequestFailedException with error code "ResourceNotFound" and message "The specified resource does not exist."
2) AggregateException, with InnerException being RequestFailedException, and a **blank error code**, and message "Name or service not known"

The bug is that I would expect the InnerException in the AggregateException to have the "ResourceNotFound" error code.

**Comment by SaurabhSharma-MSFT** [comment]
@dolenox Are you getting these two different exceptions using `SendMessageAsync` ?

**Comment by dolenox** [comment]
Yes. I am guessing here, but I think it has to do with the retry policy. If its invoked, it fails for all retries, and that returns the AggregateException. If that's true, there might also be a bug where the SDK is retrying something it shouldn't.

Otherwise, I'm not sure what is causing me to sometimes get the AggregateException and sometimes not.

**Comment by SaurabhSharma-MSFT** [comment]
@dolenox Are you comfortable sharing your code so that we can take a look?

**Comment by dolenox** [comment]
Assuming you're internal, let's see if you can access our repo:

QueueClients - Repos (visualstudio.com)<https://microsoft.visualstudio.com/Universal%20Store/_git/CXE.CPU.ConsumerPurchase.Core?path=/ConsumerPurchaseCore/src/ConsumerPurchaseInfrastructure/QueueClients>

There's quite a bit of DAL cod built up around the QueueClient, but the SendMessageAsync call is made here<https://microsoft.visualstudio.com/Universal%20Store/_git/CXE.CPU.ConsumerPurchase.Core?path=/ConsumerPurchaseCore/src/ConsumerPurchaseInfrastructure/QueueClients/PartitionedCloudQueue.cs&version=GBmaster&line=75&lineEnd=76&lineStartColumn=1&lineEndColumn=1&lineStyle=plain&_a=contents>

**Comment by SaurabhSharma-MSFT** [comment]
@dolenox Thanks. Yes, I can access your repo and the code, and I assume nothing else is causing this aggregate exception.  I will be redirecting this to service team for further investigation. Thanks

**Comment by jaschrep-msft** [comment]
@dolenox Do you have a sample that can produce this failure case? Does it produce only one or the other? If not, can you produce HTTP logs of the failed request/response pairs, identifying which pairs result in which exception surfacing? (Please be careful to redact sensitive information in web traces)

`SendMessageAsync()` does very little aside from translating requests down to a code-generated REST layer, so I assume the Storage service must be sending back different responses in these different exception cases. Knowing what's being sent back in the different cases would be a major help in identifying the issue.

**Comment by dolenox** [comment]
Ack, please give me some time and I will regenerate the http logs for this scenario

**Comment by dolenox** [comment]
I have a consistent repro with this console app:

static void Main(string[] args)
{
    string connectionString = "TODO";
    var serviceClient = new QueueServiceClient(
        connectionString,
        new QueueClientOptions());
    var queue = (serviceClient.CreateQueue("somequeue")).Value;
    queue.CreateIfNotExists();
    for (int i = 0; i < 100; i++)
    {
        try
        {
            // Put breakpoint here, first hit, delete storage account, then remove breakpoint & continue
            queue.SendMessage("somemessage");
        }
        catch (RequestFailedException re)
        {
            var errorCode = re.ErrorCode;
            Console.WriteLine($"{i}: Caught RequestFailedException. code: {re.ErrorCode}");
        }
        catch (AggregateException ae)
        {
            Console.WriteLine($"{i}: Caught AggregateException.");
            if (ae.InnerException is RequestFailedException innerRe)
            {
                Console.WriteLine(
                    $"  AggregateException has inner RequestFailedException. code: {innerRe.ErrorCode}");
            }
        }
        catch
        {
            Console.WriteLine("Some other unexpected error");
        }
        Thread.Sleep(2000);
    }
}

Here is the console output:

***@***.***

At some point, the retry logic kicks in - you can tell the request takes longer, and then the AggregateException

**Comment by jaschrep-msft** [comment]
@dolenox Thanks for the repro code! I'll investigate this.

**Comment by jaschrep-msft** [comment]
@dolenox Thank you for your patience.

While I'm not actually seeing the aggregate exception itself, I am seeing the rest of the behavior you describe. When the Storage account gets deleted from under the program, it shifts from successful message sending to failure state 1 for a few dozen requests to failure state 2.

In failure state 1, the client is receiving 404 responses with code "ResourceNotFound", because the account has been deleted. But the account endpoint still exists; that's how we're still able to receive 404 responses.

In failure state 2, Azure has finally removed the DNS records of the deleted account. Now we receive 502 responses as we attempt to establish an HTTPS tunnel, as the endpoint can't be found. At this point, you are no longer receiving error messages from Azure Storage. You are receiving DNS failure messages and will receive whatever HTTP status code and message the DNS lookup decides to return.

So while you are getting two different error states, you are in fact encountering two entirely different errors (one of which is out of the storage service's control), even though they both amount to the queue not existing. "ResourceNotFound" is explicitly an error code sent by the Storage service, and retroactively fitting a DNS lookup failure response with that error code would be misleading.

That you encounter an AggregateException and I don't is interesting, but as this exception is thrown from the .NET web stack on my end (feel free to check the stack trace on your end), the fault is likely in the implementation details there, perhaps in a version/platform difference.
