### ISSUE TITLE
Link to Confidential Ledger package leads nowhere - package appears to be under Azure.Security.ConfidentialLedger

### ISSUE THREAD

**Issue by antiphon0** [Azure/azure-sdk-for-net#26229]
[Enter feedback here]
Not 100%, but it looks like the package is now Azure.Security.ConfidentialLedger, not Azure.Storage.ConfidentialLedger. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 30fbbcd5-c2d9-cd79-e384-57147cd8de0b
* Version Independent ID: 7dad563d-2595-e09a-667f-60b30a0e1f8f
* Content: [Azure Confidential Ledger client library for .NET - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/overview/azure/storage.confidentialledger-readme-pre)
* Content Source: [api/overview/azure/storage.confidentialledger-readme-pre.md](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/api/overview/azure/storage.confidentialledger-readme-pre.md)
* Service: ****
* Product: **azure**
* Technology: **azure**
* GitHub Login: @ramya-rao-a
* Microsoft Alias: **ramyar**

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by danieljurek** [comment]
Looks like we need a redirect from the old `storage.confidentialledger` to the new `security.confidentialledger` page

**Comment by antiphon0** [comment]
Just wanted to throw in - it looks like the code referenced in the portal when using the Confidential Ledger (AAD Users tab) is also referencing the Azure.Storage.ConfidentialLedger (and the code appears to be outdated, which might confuse a lot of people). I'm not sure if this is tied to a git page somewhere.

**Comment by danieljurek** [comment]
Update here: This should be fixed and live before the end of the week. 

I'm testing a redirect which will fix this problem by redirecting browsers that land on the [storage.confidentialledger](https://docs.microsoft.com/en-us/dotnet/api/overview/azure/storage.confidentialledger-readme-pre) page to [security.confidentialledger](https://docs.microsoft.com/en-us/dotnet/api/overview/azure/security.confidentialledger-readme-pre). Because it's a redirect the link in the portal will also ensure that browsers land at the proper URL.  

@christothes -- Can you help us update the link the portal? On the AAD-Based Users page for completeness? 

![image](https://user-images.githubusercontent.com/2158838/150847225-c4d7d264-ecc7-4696-8dac-acd2293911bd.png)

**Comment by pallavit** [comment]
This has been fixed, closing the issue.
