### ISSUE TITLE
[QUERY] Storage: Exception while copying blob

### ISSUE THREAD

**Issue by Shivam60** [Azure/azure-sdk-for-net#26256]
### Library name and version

Azure.Storage.Blobs 12.10.0

### Query/Question

I have the requirement to copy the file from an URI to my azure storage account. The file can be in another azure storage account or can be anywhere, i just have the link to it and no other information. 

I am trying to use `StartCopyFromUriAsync` function from `BlobClient` object to upload a file to my azure storage account.
I have noticed that randomly my copy operation will fail.

Mostly whenever i get an error it is below(8 out of 10 times) 

`Error: Azure.RequestFailedException: Forbidden RequestId: Time:2022-01-12T19:00:05.1483054Z Status: 403 (Forbidden) ErrorCode: CannotVerifyCopySource`

`Error: System.InvalidOperationException: The operation has not completed yet.`

Some times I get this error also(2 out of 10 times)
`Error: Azure.RequestFailedException: Forbidden ErrorCode: CannotVerifyCopySource`

Here is my code 

```csharp
CopyFromUriOperation operation = await this.blobServiceClient.GetBlobContainerClient("Container").GetBlobClient("fileName").StartCopyFromUriAsync("urlOfTheNewBlob");

await operation.WaitForCompletionAsync();

if (operation.HasCompleted)
{
    //do stuff
}
```

The weird thing is that if I try, sometime it succeeds. Sometimes I have to retry 2-3 times.

### Environment

I am using azure function v3. Azure sdk version is azurefunctions: 3.3.1.0

**Comment by SatishBoddu-MSFT** [comment]
Thank you @Shivam60 ,We are checking on this error if this is intermittent or not, we will keep you posted.

**Comment by SatishBoddu-MSFT** [comment]
As per the offline conversation the below error looks like related to access issue.

_**Error: Azure.RequestFailedException: Forbidden RequestId: Time:2022-01-12T19:00:05.1483054Z Status: 403 (Forbidden) ErrorCode: CannotVerifyCopySource**_



I was able to reproduce the issue due to public access not being enabled on the source container.

[2022-01-12T19:42:26.131Z] Executed 'Function1' (Failed, Id=ac3f4d1e-bb29-430d-b4cc-33bb016d1bbb, Duration=2109ms)
[2022-01-12T19:42:26.134Z] System.Private.CoreLib: Exception while executing: Azure.Storage.Blobs: Public access is not permitted on this storage account.
RequestId:5b0b8a03-c01e-002b-46ec-075b69000000
Time:2022-01-12T19:42:24.9424324Z
[2022-01-12T19:42:26.137Z] **Status: 409 (Public access is not permitted on this storage account.)**
[2022-01-12T19:42:26.138Z] **ErrorCode: CannotVerifyCopySource**
[2022-01-12T19:42:26.139Z]


Once the public access was given, I was able to run the command! May be we should try with Storage account which has public access enabled, please do let us know if the issue still exists when trying with another storage account? would be able to help further!

**Comment by Shivam60** [comment]
Thanks @SatishBoddu-MSFT 
This is indeed an issue at my end. Thanks for helping me
