### ISSUE TITLE
[BUG] Missing property `categoryGroup` in `Insights.Models.LogSettings`

### ISSUE THREAD

**Issue by asleire** [Azure/azure-sdk-for-net#26254]
### Library name and version

Azure.ResourceManager.Insights 1.0.0-preview.1

### Describe the bug

Inspecting the API request for creating a DiagnosticSetting in the Azure Portal I see the following request body: 
![image](https://user-images.githubusercontent.com/631907/148932341-c4282232-9182-4b3e-ba7c-aaa89dd1dcc4.png)

It is currently not possible to reproduce this request using the POCO models from `Azure.ResourceManager.Insights` because the [LogSettings](https://github.com/Azure/azure-sdk-for-net/blob/4162f6fa2445b2127468b9cfd080f01c9da88eba/sdk/insights/Azure.ResourceManager.Insights/src/Generated/Models/LogSettings.cs) class does not contain the `categoryGroup` property

### Expected behavior

The [LogSettings ](https://github.com/Azure/azure-sdk-for-net/blob/4162f6fa2445b2127468b9cfd080f01c9da88eba/sdk/insights/Azure.ResourceManager.Insights/src/Generated/Models/LogSettings.cs)class should have a property for `CategoryGroup`

### Actual behavior

The [LogSettings ](https://github.com/Azure/azure-sdk-for-net/blob/4162f6fa2445b2127468b9cfd080f01c9da88eba/sdk/insights/Azure.ResourceManager.Insights/src/Generated/Models/LogSettings.cs)class does not have a property for `CategoryGroup`

### Reproduction Steps

See above

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by ArthurMa1978** [comment]
Thanks @asleire for reporting this issue, this lib will be deprecated soon, but we will check it in new release

**Comment by asleire** [comment]
Will a new library replace this one? As I understand from the readme file, libraries starting with `Azure.ResourceManager` are already the "new" management libraries

**Comment by ArcturusZhang** [comment]
Hi @asleire the new version is WIP here if you are interested: https://github.com/Azure/azure-sdk-for-net/pull/26023

And in the new generated library, I also did not see the categoryGroup in DiagnosticSettings model.

I believe the root cause of this is that it is not defined in the swagger we are using to generate this package: https://github.com/Azure/azure-rest-api-specs/blob/e7f37ea54a638425ce5202bd6d6bc2ce1c633a89/specification/monitor/resource-manager/Microsoft.Insights/preview/2017-05-01-preview/diagnosticsSettings_API.json#L270
I found the `categoryGroup` in a newer api-version of the swagger, here: https://github.com/Azure/azure-rest-api-specs/blob/e7f37ea54a638425ce5202bd6d6bc2ce1c633a89/specification/monitor/resource-manager/Microsoft.Insights/preview/2021-05-01-preview/diagnosticsSettings_API.json#L264

We will contact the corresponding service team to let them update the reference of the collection of consumable swaggers for SDK so that we could update our package. Sorry for the inconvenience!

**Comment by ArcturusZhang** [comment]
Hi we already released the new monitor SDK that includes the missing property: https://www.nuget.org/packages/Azure.ResourceManager.Monitor
Please notice that the namespace `Azure.ResourceManager.Insights` has been deprecated and no longer supported
