### ISSUE TITLE
Cannot merge null values

### ISSUE THREAD

**Issue by johnsoaa** [Azure/azure-sdk-for-net#2633]
As stated in the Azure Search REST API documentation [here](https://docs.microsoft.com/en-us/rest/api/searchservice/addupdate-or-delete-documents), "If you want to remove an individual field from a document, use merge instead and simply set the field explicitly to null." So I did that:

    // subset of my index's fields
    private class SyncFields
    {   
        public string Id { get; set; }
        public DateTimeOffset? ApprovedOn { get; set; }
    }

    // ...

    var sync = new SyncFields
    {
        Id = "94303",
        ApprovedOn = null
    };

    var searchClient = new SearchServiceClient("xxxx", new SearchCredentials("xxxx"));
    searchClient.SerializationSettings.NullValueHandling = NullValueHandling.Include;

    using (var client = searchClient.Indexes.GetClient("xxxx"))
    {
        client.SerializationSettings.NullValueHandling = NullValueHandling.Include;
        var batch = IndexBatch.Merge<SyncFields>(new[] { sync });
        client.Documents.Index<SyncFields>(batch);
    }

Unfortunately as I discovered, my setting NullValueHandling to Include is being ignored. In [JsonUtility](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/src/Search/Microsoft.Azure.Search/Customizations/Serialization/Private/JsonUtility.cs) the `CreateSerializerSettings(JsonSerializerSettings, bool)` sets NullValueHanding.Ignore on line 51 with no options I can see to avoid this.

For now I am using a custom converter to convert default(DateTimeOffset) and string.Empty into null. Is there an option in the SDK I am missing? [StackOverflow question I asked](http://stackoverflow.com/questions/41112376)

**Comment by brjohnstmsft** [comment]
@johnsoaa This is a known limitation of the typed overloads of the `Index` family of methods. The issue is described in detail here: https://github.com/Azure/azure-sdk-for-net/issues/1804

Some workarounds:

1. Use the untyped version of `Index` instead for merge scenarios.
1. Use `Upload` instead of merge.
1. Put `[JsonProperty(NullValueHandling = NullValueHandling.Include)]` on the properties of your model class that you need to explicitly set to null in a merge operation (*not recommended* if you have many fields in your index).
