### ISSUE TITLE
The page doesn't indicate what is returned if the container name passed to GetBlobContainerClient doesn't exist.

### ISSUE THREAD

**Issue by ChrisGroupScape** [Azure/azure-sdk-for-net#26458]
The page doesn't indicate what is returned if the container name passed to GetBlobContainerClient doesn't exist.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 61828c00-0a3f-d3a5-9fbb-8a02d866dcf4
* Version Independent ID: dbedd4e1-1596-050b-56d0-694f785ae6d6
* Content: [BlobServiceClient.GetBlobContainerClient(String) Method (Azure.Storage.Blobs) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/azure.storage.blobs.blobserviceclient.getblobcontainerclient?view=azure-dotnet)
* Content Source: [xml/Azure.Storage.Blobs/BlobServiceClient.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Azure.Storage.Blobs/BlobServiceClient.xml)
* Service: **azure**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by PramodValavala-MSFT** [comment]
@ChrisGroupScape This method just creates a new `BlobContainerClient` object and no connection is made until you perform an operation. In the case where the container doesn't exist and you perform some operation (apart from [`CreateAsync`](https://docs.microsoft.com/en-us/dotnet/api/azure.storage.blobs.blobcontainerclient.createasync?view=azure-dotnet#azure-storage-blobs-blobcontainerclient-createasync(azure-storage-blobs-models-publicaccesstype-system-collections-generic-idictionary((system-string-system-string))-azure-storage-blobs-models-blobcontainerencryptionscopeoptions-system-threading-cancellationtoken)) or the likes), you will be met with an error

```
Azure.RequestFailedException : The specified container does not exist.
```

**Comment by amnguye** [comment]
In order to check if a container exists, please use [ExistsAsync](https://docs.microsoft.com/en-us/dotnet/api/azure.storage.blobs.blobcontainerclient.existsasync?view=azure-dotnet), [DeleteIfExistsAsync](https://docs.microsoft.com/en-us/dotnet/api/azure.storage.blobs.blobcontainerclient.deleteifexistsasync?view=azure-dotnet) or [CreateIfNotExists](https://docs.microsoft.com/en-us/dotnet/api/azure.storage.blobs.blobcontainerclient.createifnotexistsasync?view=azure-dotnet).
