### ISSUE TITLE
[BUG] Message Output ReceiveBatchAsync start.  LogLevel Trace - ServiceBusTrigger

### ISSUE THREAD

**Issue by FabianLueke** [Azure/azure-sdk-for-net#26468]
### Library name and version

Microsoft.Azure.WebJobs.Extensions.ServiceBus >=5.0.0

### Describe the bug

I use ServiceBusTrigger with queues and topics and i updated the package from 4.3.0 to greater than or equal 5.0.0.
After the update my console is full (over 20 messages) of (queueName/Subscriptname)-(Guid): ReceiveBatchAsync start. MessageCount = 1. 
I use the setting     "AzureFunctionsJobHost__Logging__LogLevel__Default": "Trace".
When i change the logLevel to Warning, i don't see the messages anymore, but i i guess this is not the solution.

The problem are not only the logs, it also lock some threads

### Expected behavior

Recieve the message only one time

### Actual behavior

many executions of ReceiveBatchAsync 

### Reproduction Steps

-use servicebus trigger 
-use version <5.0.0 and the setting "AzureFunctionsJobHost__Logging__LogLevel__Default": "Trace",
-you don't see so much messages
- upgrade to >=5.0.0., you see so  much messages

### Environment

.netCore 3.1 and dotNet  6 i tested

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by JoshLove-msft** [comment]
These logs are coming in from the underlying SDK logging. You can filter the logs that originate from Azure.Messaging.ServiceBus as demonstrated in https://docs.microsoft.com/en-us/dotnet/azure/sdk/logging#map-to-aspnet-core-logging.

Related issue - https://github.com/Azure/azure-sdk-for-net/issues/25945

**Comment by JoshLove-msft** [comment]
In terms of receiving only 1 message at a time, this can be tuned in your host.json setting - https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-service-bus#additional-settings-for-version-5x by setting the `maxConcurrentCalls` property.

**Comment by shudson302** [comment]
@JoshLove-msft   I believe the original question here:
Expected behavior
Recieve the message only one time

Was not asking to only receive the messages one at a time, but that a single message would only be received 1 time.  Instead of the current behavior which is receiving the messages and logging them many times for each single message.

Is there a fix for this behavior?  We are being charged high costs for our Log Analytics with the Trace logs being very high and they are full of logs from our service bus triggered functions.  See attachment.  These logs are coming in constantly even when there are no messages in the service bus queue.

Can this be reopened or addressed?

<img width="1553" alt="temp" src="https://user-images.githubusercontent.com/9217242/176221888-d70c7218-f388-4e45-b92b-c7de1a2f0783.png">
.

**Comment by JoshLove-msft** [comment]
As mentioned in this [comment](https://github.com/Azure/azure-sdk-for-net/issues/26468#issuecomment-1016819361), the logs can be filtered in the host.json.
