### ISSUE TITLE
No information on valid values for domainValidationMethod proeprty

### ISSUE THREAD

**Issue by minimonsters** [Azure/azure-sdk-for-net#26505]
Trying to find information on creating ARM templates for service managed certificates, there is no indication about what valid values for this string value are.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d46863db-c48c-b7e1-acae-b2bdf98ae880
* Version Independent ID: 72b4791b-0735-3c98-bc95-ab5927df4d86
* Content: [Certificate.DomainValidationMethod Property (Microsoft.Azure.Management.WebSites.Models) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.management.websites.models.certificate.domainvalidationmethod?view=azure-dotnet)
* Content Source: [xml/Microsoft.Azure.Management.WebSites.Models/Certificate.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.Management.WebSites.Models/Certificate.xml)
* Service: **app-service**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by AdamRiddick** [comment]
Is this information available anywhere else?

**Comment by ArthurMa1978** [comment]
Thank you for reaching out to us about the Azure SDK for .NET. Unfortunately, this issue is related to the service side and not the SDK side, so we are not able to help you with it. Therefore, we are closing this issue for now. If you need more assistance, please [open an Azure support request](https://docs.microsoft.com/azure/azure-portal/supportability/how-to-create-azure-support-request). We apologize for any inconvenience this may cause you.

We value your feedback and we want to make sure that your problem is solved. If you think that we have misunderstood your issue or closed it incorrectly, please feel free to comment on this thread and reopen the issue. We will be happy to assist you further. Thank you for your understanding and cooperation.
