### ISSUE TITLE
Enable implementors of TypeBinder<TExchange> to serialize properties from explicitly implemented interfaces

### ISSUE THREAD

**Issue by christothes** [Azure/azure-sdk-for-net#26514]
### Library name

Azure.Core

### Please describe the feature.

Currently `TypeBinder<TExchange>` doesn't support serialization of properties that are explicitly implemented from an interface.

Ideas for this change include:
- addition of method `protected virtual bool ShouldSerialize(MemberInfo info)`
  - Allows for implementors to have find grained control over how the TExchange type's properties are considered for serialization.

Areas of interest in the code include:
https://github.com/Azure/azure-sdk-for-net/blob/dcac296df717dbb75fcc50648c2132d47cd413f2/sdk/core/Azure.Core/src/Shared/TypeBinder.cs#L74
https://github.com/Azure/azure-sdk-for-net/blob/dcac296df717dbb75fcc50648c2132d47cd413f2/sdk/core/Azure.Core/src/Shared/TypeBinder.cs#L170-L171

related to #26363

**Comment by jsquire** [comment]
It's worth noting that the current lack of support for explicit interface implementation creates a poor developer experience when using F# with `Azure.Data.Tables`.   Because F# lacks implicit interface implementation, it is necessary to create a shadow for each property of `ITableEntity` when creating  table entitties in F#.   For example:

```fsharp
type Customer() =

    interface ITableEntity with
        member val PartitionKey = "" with get, set
        member val RowKey = "" with get, set
        member val Timestamp = Nullable () with get, set
        member val ETag = ETag () with get, set

    member val PartitionKey = "" with get, set
    member val RowKey = "" with get, set
    member val Timestamp = Nullable() with get, set
    member val ETag = ETag() with get, set

let customer = Customer()
customer.PartitionKey <- "SomePartitionKey"
customer.RowKey <- "SomeRowKey"

table.AddEntity customer |> ignore
```

More context can be found in [F# Azure Table Storage sample is broken (#28828)](https://github.com/dotnet/docs/issues/28828).

**Comment by isaacabraham** [comment]
Indeed, the error you get from this is difficult to diagnose and will confuse basically every F# developer who tries this.

**Comment by marklio** [comment]
This is another _hugely_ problematic issue for me coming from a previous Table Storage SDK where ITableEntity properties are (of course) included in serialization, and ALL of my entities implement them this way (mostly because they inherit from a base class of some kind that implements them explicitly so they aren't in the way. :( Before tackling the general case of implicit members, the SDK **needs** to ensure that the ITableEntity properties are appropriately accounted for. I'd be happy to take a stab at implementing this narrower case of this broad feature.

**Comment by marklio** [comment]
Any way of tracking how this feature is being prioritized? It is still pretty problematic for me.

**Comment by marklio** [comment]
> would that address this issue for you around explicit implementation?

@christothes I think the thing missing from that workflow would be objects participating as a "tracked" object for the purposes of optimistic retrieve->edit->update via ETag and conditional update. That is what's important about being an "entity" and is separate from how we used TableEntityAdapter to blast query results back into "plain old .NET types" without the overhead of entities. In my mind, those are different scenarios that were well-suited to the "official entity" path and the "adapter" specifically.

In the old model, implementing ITableEntity meant "I want to fully participate in the table model", and using TableEntityAdapter  was "I only want to represent data" (or some other scenario disconnected from participating in the table model). That gave us lightning fast queries (along with selecting only the columns we were interested in and not pulling OData stuff in the payload) for "data", and full-fidelity optimistic concurrency when doing updates.

So, while it would provide a path forward, it's not ideal, and it certainly won't help the F# folks trying to make the basic samples work :)

**Comment by christothes** [comment]
I thought a bit about the implementation for this - Would you have any concerns if we required implicitly implemented interface members to be decorated with the `DataMember` attribute (which we already use for property renames)?

Some of the advantages of this approach I see over having to specify an interface are:
- This decouples the mechanism from whether or not the property is implemented as an explicit interface member and allows model owners control over which non-public members should be serialized
- serialization of interface members is not all or nothing
- simplifies the implementation of DataBinder as compared approaches that need to match interface type members with model type members

**Comment by marklio** [comment]
I think there are 2 different things here:
* Having a mechanism for getting data from any arbitrary explicitly-implemented interface - I don't think this is important at all, not even for the F# cases. I don' think the old SDK supported this either.
* Honoring the ITableEntity interface, which is an interface designed to interact with table storage concepts and required to participate in the APIs, but not honored if implemented explicitly because the current implementation doesn't actually use the interface to get the data because of a layering choice (using an agnostic serializer).

For non-ITableEntity members, if you want to require this that's fine, but I don't think there's a strong use case here. For ITableEntity, this doesn't make sense to me. In .NET, interfaces are meaningful and represent contracts. In this case, the required contract isn't being honored. The type system requires that interface to be implemented to participate in the APIs, but when you implement that interface to the satisfaction of the type system, it still doesn't work. I think the Table Storage APIs should honor the ITableEntity interface full-stop.

Just as an aside, another approach would be to run the object through the serializer, then cast the object to ITableEntity and then run _that_ through the serializer and overwrite anything that's already been serialized.
