### ISSUE TITLE
[QUERY]Will UploadAsync operation failed when other instance are acquiring Lease

### ISSUE THREAD

**Issue by RetYn** [Azure/azure-sdk-for-net#26593]
### Library name and version

Azure.Storage.Blobs

### Query/Question

Consider that situation:
If Instance A is doing UploadAysnc without lease named RequestA, while at the same time Instance B is using BlobLeaseClient - AcquireAsync  to get lease named RequestB.
Will any of these two request failed when blob is serving RequestA while RequestB arrived at the same time?

**Comment by SatishBoddu-MSFT** [comment]
Hello @RetYn 

[**Optimistic concurrency:**](https://docs.microsoft.com/en-us/azure/storage/blobs/concurrency-manage?tabs=dotnet#optimistic-concurrency)

We pass only the E-Tag and no lock is aquired in this case, so the request which has the latest eTag will win!!!
Azure Storage returns HTTP status code 412 (Precondition Failed). This error indicates to the client that another process has updated the blob since the client first retrieve.


[**Pessimistic concurrency for blobs.**](https://docs.microsoft.com/en-us/azure/storage/blobs/concurrency-manage?tabs=dotnet#pessimistic-concurrency-for-blobs)

A client has to acquire the lock exclusively so that when a lease exists, Azure Storage enforces exclusive access to write operations for the leaseholder. only one client at a time has a valid lease ID.
If the lease is active and the lease ID is not provided on a write request, then the write operation fails with error code 412 (Precondition Failed).


**Brief:**
Blob Leases allow you to claim ownership to a Blob. Once you have the lease you can then update the Blob or delete the Blob without worrying about another process changing it underneath you. **When a Blob is leased, other processes can still read it, but any attempt to update it will fail.** You can update Blobs without taking a lease first, but you do run the chance of another process also attempting to modify it at the same time.

Please read this article as well, written by Robin Shahan :[Article link](https://www.red-gate.com/simple-talk/cloud/platform-as-a-service/azure-blob-storage-part-8-blob-leases/)

There is beautiful documentation on this full topic: [Managing Concurrency in Blob storage](https://docs.microsoft.com/en-us/azure/storage/blobs/concurrency-manage?tabs=dotnet) with Examples to demonstrate these scenarios!!!

Please do visit the above link and let us know if you need further help in this matter! happy to help!

**Comment by SatishBoddu-MSFT** [comment]
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.

Please also do visit [Microsoft Q&A](https://docs.microsoft.com/en-us/answers/index.html) the home for technical questions and answers at Microsoft.
