### ISSUE TITLE
[FEATURE REQ] Azure.Identity support for SN+I validations using CA based certificates in Azure AD

### ISSUE THREAD

**Issue by saurabh-mridul** [Azure/azure-sdk-for-net#26655]
### Library name
Azure.Identity 

We are trying to leverage SN+I validations for CA based certificates for ClientCertificateCredential based authentication. 
SN+I Validations doesn’t require pinning certificate thumbprint to SPNs which enables easy certificates rollover whenever certificates gets renewed. 
MSAL libraries (>= v3.19.4) have support for SN+I validations using sendX5c parameter while fetching the token.  
![image](https://user-images.githubusercontent.com/16285348/151490645-5c9b88d4-d538-4cac-be8f-96c340bb1252.png)

However, there is no support available to use SN+I validations in Azure.Identity SDK for ClientCertificateCredential. 
Let me know if there are any alternatives available to use SN+I validations for CA based certificates in azure identity SDK to prevent thumbprint pinning on SPNs.
@azure-identity

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by christothes** [comment]
Hi @saurabh-mridul - Have you tried the latest beta of Azure.Identity? We added this support there.

https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/identity/Azure.Identity/CHANGELOG.md#features-added

**Comment by schaabs** [comment]
Just to add some clarification, SN+I authentication support was added to the `ClientCertificateCredential` in late 2020 in version [1.3.0](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/identity/Azure.Identity/CHANGELOG.md#130-beta1-2020-09-11). To enable sending the x5c header you need to set the `SendCertificateChain` property in `ClientCertificateCredentialOptions` to true.

The change which @christothes referenced brings similar support when authenticating with a certificate using the  `EnvironmentCredential`. It is due to release in 1.6.0-beta.1 in the next couple of weeks.

**Comment by saurabh-mridul** [comment]
thank you @christothes @schaabs for your suggestions. I am using Azure.Identity package with v 1.5.0 and found `SendCertificateChain  `property in `ClientCertificateCredentialOptions  `for enabling SN+I validations.
