### ISSUE TITLE
[QUERY] Seeing Service Bus Lock Exceptions for Session Enabled Service Bus Subscriptions

### ISSUE THREAD

**Issue by fazal60** [Azure/azure-sdk-for-net#26755]
### Library name and version

Microsoft.Azure.ServiceBus

### Query/Question

Hi team,
In our prod instances, we are seeing the following exception coming from Service bus.

**"The session lock has expired on the MessageSession. Accept a new MessageSession"**

Ours is a session enabled service bus subscription, and I was referring to this post https://github.com/Azure/azure-sdk-for-net/issues/19662, where one of the suggestions was to use sessionHandlerOptions (pls check last reply on that post).

While registering the session handler we make sure to use sessionHandlerOptions for a session enabled service bus subscription.
![image](https://user-images.githubusercontent.com/7508202/152216606-833f1803-99b6-4c63-ba80-ec47efeed818.png)

Also verified that autocomplete is set to false.

Could you point to what could be causing this error?

**Comment by MughundhanRaveendran-MSFT** [comment]
@fazal60 , Thanks for reporting. I am looking into this issue, I will get back to you once I have an update

**Comment by MughundhanRaveendran-MSFT** [comment]
@fazal60 , Thanks for the follow up. I will provide an update tomorrow

**Comment by MughundhanRaveendran-MSFT** [comment]
@fazal60 , As mentioned in this [issue](https://github.com/Azure/azure-sdk-for-net/issues/19662) This happens when the session lock is expired and needs to be reacquired. 

You are using the sessionhandleroptions class to renew the lock. Are you getting the lock expired exception even after renewing the session lock? What is the timeout value that you have set.

By default, the messagewait timeout is 1 minute and the autorenew duration is 5 minutes while using the [Sessionhandleroptions ](https://github.com/Azure/azure-service-bus-dotnet/blob/dev/src/Microsoft.Azure.ServiceBus/SessionHandlerOptions.cs)class

**Comment by fazal60** [comment]
@MughundhanRaveendran-MSFT I checked in our code and it appears the MessageWaitTimeout value is 30 seconds and the Autorenew duration is 5 minutes. Does this make a difference?

**Comment by fazal60** [comment]
@MughundhanRaveendran-MSFT what are the implications if the timeout is less than 1 min. Is this problem caused due to this?

**Comment by MughundhanRaveendran-MSFT** [comment]
@fazal60 , Apologies for the delay in response. 1 minute is the default timeout and I am not sure if the issue is caused due to setting the value to 30 seconds. You can try to set the MessageWaitTimeout value to 1 minute to see if the frequency of the issue is decreased. Also I would like to know the answer for the below query
Are you getting the lock expired exception even after renewing the session lock?

**Comment by fazal60** [comment]
"Are you getting the lock expired exception even after renewing the session lock?"

Yes @MughundhanRaveendran-MSFT from the logs thats what seems to happen

**Comment by krishna0209** [comment]
@shankarsama @DorothySun216 Any updates on this?

**Comment by pulkitgupta08** [comment]
![image](https://user-images.githubusercontent.com/86068342/213979532-5a5b0ac1-e7e4-4181-8e67-43fee0a1be26.png)

**Comment by bakes82** [comment]
I get the same issue when using an azure function app v5 where the function app itself is supposed to auto renew the message locks, it seems like whatever the message lock is on the topic/subscription is the max, it doesnt seem to auto renew when its a session based queue.
