### ISSUE TITLE
JavaScript BlobTrigger loads the entire blob into memory. Any plans to support streams like in C#?

### ISSUE THREAD

**Issue by cmendible** [Azure/azure-sdk-for-net#26826]
### Library name and version

Microsoft.Azure.WebJobs.Extensions.Storage.Blobs

### Query/Question

According to [Azure Blob storage trigger for Azure Functions | Microsoft Docs](https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-storage-blob-trigger?tabs=csharp#concurrency-and-memory-usage): JavaScript and Java functions load the entire blob into memory.

This is an issue with big files. Are there plans to support something like C# streams? Or is the alternative to use Event Grid Triggers and download the blob with custom code?

Thanks!

**Comment by PramodValavala-MSFT** [comment]
@cmendible The Functions Runtime [doesn't support streaming data](https://github.com/Azure/azure-functions-host/issues/1361). The Event Grid trigger approach is the best approach today and is in fact the [recommended approach](https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-storage-blob-trigger?tabs=csharp#event-grid-trigger) compared to the blob trigger which has overhead due to polling and keeping track of processed blobs.

Once the runtime supports this, all language works should get support as well. Closing this issue in favor of the one linked.
