### ISSUE TITLE
Links on github samples page are broken

### ISSUE THREAD

**Issue by jrathor** [Azure/azure-sdk-for-net#26896]
These links point to  Azure.AI.FormRecognizer_3.1.1 branch.  All the links on the github page https://github.com/Azure/azure-sdk-for-net/blob/Azure.AI.FormRecognizer_3.1.1/sdk/formrecognizer/Azure.AI.FormRecognizer/samples/README.md(on this branch) are broken.
All links work on master branch though. 
![image](https://user-images.githubusercontent.com/61607553/153269096-1b93b709-f840-421c-b393-cc95098bf5f6.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fec567b8-17d0-c890-d4f8-2242290efc03
* Version Independent ID: 1db10b10-4614-4bfe-a39c-32758a090a40
* Content: [Azure Cognitive Services Form Recognizer client library for .NET - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/overview/azure/ai.formrecognizer-readme?view=azure-dotnet-preview&source=docs#contributing)
* Content Source: [api/overview/azure/ai.formrecognizer-readme.md](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/api/overview/azure/ai.formrecognizer-readme.md)
* Service: **formrecognizer**
* Product: **azure**
* Technology: **azure**
* GitHub Login: @ramya-rao-a
* Microsoft Alias: **ramyar**

**Comment by jsquire** [comment]
@danieljurek:  This looks like it may be an issue with the docs pipeline.   If you start with the [MS Docs overview page](https://docs.microsoft.com/dotnet/api/overview/azure/ai.formrecognizer-readme?view=azure-dotnet), then click the [Samples link](https://github.com/Azure/azure-sdk-for-net/blob/Azure.AI.FormRecognizer_3.1.1/sdk/formrecognizer/Azure.AI.FormRecognizer/samples/README.md), you end up on the `Azure.AI.FormRecognizer_3.1.1` tag for content as expected.  

However, when clicking on any of the samples, the link references the `master` branch (which no longer exists) rather than the release tag.  For example, "Recognize form content" points to "https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/formrecognizer/Azure.AI.FormRecognizer/samples/Sample1_RecognizeFormContent.md"

Do you have any insight as to how we can correct that?

**Comment by jsquire** [comment]
Hi @jrathor.  Thank you for reaching out and we appreciate you bringing this to our attention.   We'll investigate and see how we can get this corrected.

**Comment by danieljurek** [comment]
* The code that's in the `main` branch today points to the `main` branch instead of the defunct old `master` branch.. Future releases should work as expected provided the branch name doesn't change. 
* The code at the `Azure.AI.FormRecognizer_3.1.1` tag points to the old `master` branch as you observed 

This may have something to do with GitHub... The [GitHub branch renaming guidance](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-branches-in-your-repository/renaming-a-branch) says: 

> When you rename a branch on GitHub.com, any URLs that contain the old branch name are automatically redirected to the equivalent URL for the renamed branch. 

My expectation is that it should redirect from `master` to `main` ... I'll see if I can find someone who can help us go deeper here.

**Comment by pallavit** [comment]
@danieljurek did you get a chance to look at this?

**Comment by danieljurek** [comment]
I think we can close this issue. More recent releases have links which point to the `main` branch and those links are working.
