### ISSUE TITLE
Update page with latest stable version, like 5.2?

### ISSUE THREAD

**Issue by LeszekKalibrate** [Azure/azure-sdk-for-net#26918]
This page mentions 5.0 beta-1 and 5.0 beta-6, but not latest stable like 5.2?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dab2626a-9579-fe2b-f11b-0ffec8666fcf
* Version Independent ID: 9f48d2bc-eda0-57e8-1ecd-a2489f1cb862
* Content: [Azure WebJobs Service Bus client library for .NET - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/overview/azure/microsoft.azure.webjobs.extensions.servicebus-readme-pre)
* Content Source: [api/overview/azure/microsoft.azure.webjobs.extensions.servicebus-readme-pre.md](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/api/overview/azure/microsoft.azure.webjobs.extensions.servicebus-readme-pre.md)
* Service: **webjobs**
* Product: **azure**
* Technology: **azure**
* GitHub Login: @ramya-rao-a
* Microsoft Alias: **ramyar**

**Comment by jsquire** [comment]
Hi @LeszekKalibrate.  Thank you for reaching out and we regret that you're experiencing difficulties.  The page that you're referencing is the pre-release version of the documentation:
https://docs.microsoft.com/dotnet/api/overview/azure/microsoft.azure.webjobs.extensions.servicebus-readme-pre  _(note the `-pre` at the end)_

The documentation for the stable version is available here:  https://docs.microsoft.com/dotnet/api/overview/azure/microsoft.azure.webjobs.extensions.servicebus-readme  and references v5.2.0.   There is an error in the example for `addPackage` that was fixed in #26757 and will update during the next docs sync.

Because you don't seem to have been expecting the prerelease version, I'm wondering if there's a link somewhere pointed to the wrong version.  Can you help me understand how you navigated to the prerelease page?

**Comment by LeszekKalibrate** [comment]
Hi,

I am afraid that was Google.
Open Google, type: "Azure WebJobs Service Bus 5" - click on first result that points to https://docs.microsoft.com/dotnet/api/overview/azure/microsoft.azure.webjobs.extensions.servicebus-readme-pre
(at least on my pc)
