### ISSUE TITLE
[QUERY] How to replace IMessageSession.CloseAsync() in new Azure.Messaging.ServiceBus?

### ISSUE THREAD

**Issue by LeszekKalibrate** [Azure/azure-sdk-for-net#26921]
### Library name and version

Azure.Messaging.ServiceBus 7.5.1

### Query/Question

Hi,
I have started updating code that uses Microsoft.Azure.WebJobs.Extensions.ServiceBus" Version="4.3.0" to new 5.2.0 that uses new Azure.Messaging.ServiceBus 7.5.1.
So using session there is a check in my code and then a call to IMessageSession.CloseAsync() is executed, but the new library is missing CloseAsync() (this is inherited in IMessageSession from IClientEntity) in new ServiceBusSessionMessageActions class.

Assuming this is the correct new way: 
        public async Task Run([ServiceBusTrigger("%QueueName%", Connection = "QueueConnectionString", IsSessionsEnabled = true)] ServiceBusReceivedMessage message, ServiceBusSessionMessageActions messageSession, ILogger logger)

How to call: await messageSession.CloseAsync() now?

### Environment

Net core 3.1
<PackageReference Include="Microsoft.Azure.WebJobs.Extensions.ServiceBus" Version="5.2.0" />
<PackageReference Include="Azure.Messaging.ServiceBus" Version="7.5.1" />

**Comment by JoshLove-msft** [comment]
Hi @LeszekKalibrate,
Thanks for filing this issue. I've submitted a PR to expose the ReleaseSession method in ServiceBusSessionMessageActions. This would be the equivalent of CloseAsync, with the difference being that this doesn't actually close the session immediately (note it is not async), but rather marks it for closing so that autocompletion will still happen. If you want to prevent the message from being completed you would need to abandon it, or not use autocompletion in your function.
