### ISSUE TITLE
[QUERY] Why is `using Azure.Messaging.ServiceBus;` not working inside a namespace?

### ISSUE THREAD

**Issue by Shivam60** [Azure/azure-sdk-for-net#27161]
### Library name and version

Azure.Messaging.ServiceBus 7.6.0

### Query/Question

I have a .net core project where I am trying to use using Azure.Messaging.ServiceBus;.

I have realized that if i import this outside the namespace then it dotnet is able to recognize the library however if i import it inside it then dotnet is not able to recognize it.

working
<img width="431" alt="image" src="https://user-images.githubusercontent.com/13963817/155332996-64fefff3-6974-4108-af27-f1fb3918f728.png">

Not working
<img width="502" alt="image" src="https://user-images.githubusercontent.com/13963817/155333061-3900ed98-7a72-4782-80a0-c8055f7df6bf.png">

### Environment

observed in net5.0 and .netcore3.1

**Comment by jsquire** [comment]
Hi @Shivam60.  Thank you for reaching out and we regret that you're experiencing difficulties.  The issue that you're encountering is due to how namespaces are resolved; because you're using a top-level namespace that begins with `Microsoft` and have dependencies with namespaces using the `Microsoft.Azure.*` pattern, when the `using` clause is contained in your namespace, it is interpreted as `Microsoft.Azure.Messaging.ServiceBus`, which does not exist.

You can resolve this by changing the form to: `using global::Azure.Messaging.ServiceBus` or changing the top-level namespace to not begin with `Microsoft`.

**Comment by Shivam60** [comment]
Thanks @jsquire for quickly explaining the issue and providing a solution to it.
