### ISSUE TITLE
[FEATURE REQ] FormRecognizer - Ability to deserialize AnalyzeResult

### ISSUE THREAD

**Issue by wahyuen** [Azure/azure-sdk-for-net#27202]
### Library name and version

Azure.AI.FormRecognizer 4.0.0-beta,3

### Describe the bug

Currently whilst performing the new `Read` operation, the resultant response can be serialized but cannot be deserialized due to contructors being marked as `internal`.

This should be removed such that customers are able to utilize the object as they wish. Currently, a common pattern that is used is that resultant objects are persisted to Storage for later use, and also for passing the object around in Durable Functions (which internally serializes/deserializes to its internal store). Both scenarios currently fail and we are left, at best, to create proxy objects and manually copy data across models to facilitate our use cases.

It is noted this pattern does NOT seem prevalent in other Azure SDKs, both in the 'older' style and the newer Azure.* style.

Looking at the Azure SDK Design guidelines also does not point to setting constructors as `internal` but instead suggest that if a class is not meant to be modified, then the public properties should be made `get` only. [Model Types](https://azure.github.io/azure-sdk/general_design.html)

![image](https://user-images.githubusercontent.com/4549796/155644156-4149ea46-94a0-40ed-a206-7f6c6420d2b0.png)

### Expected behavior

Object should be able to be deserialized in line with other SDK models.

### Actual behavior

Exception is thrown due to `internal` constructors

### Reproduction Steps

```
        public static async Task Main(string[] args)
        {
            var documentAnalysisClient = new DocumentAnalysisClient(<removed>);

            var operation = await documentAnalysisClient.StartAnalyzeDocumentFromUriAsync("prebuilt-read",
                new Uri("https://images.google.com.au/images/branding/googlelogo/1x/googlelogo_color_272x92dp.png"));

            await operation.WaitForCompletionAsync();

            var result = operation.Value;

            var serializedString = JsonSerializer.Serialize(result);

            var deserializedObject = JsonSerializer.Deserialize<AnalyzeResult>(serializedString);

            Console.WriteLine("Finished!");
        }
```

![image](https://user-images.githubusercontent.com/4549796/155643492-b90a433a-f23a-4e89-8daa-32e949ff8d10.png)

### Environment

❯ dotnet --info
.NET SDK (reflecting any global.json):
 Version:   6.0.102
 Commit:    02d5242ed7

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19044
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.102\

Host (useful for support):
  Version: 6.0.2
  Commit:  839cdfb0ec

**Comment by jsquire** [comment]
Hi @wahyuen.  Thank you for your feedback.

Currently we intentionally do not support serialization for our model types since we can't guarantee compatibility across SDK versions.  Unfortunately, for now, the only supported way to instantiate models for data returned by the service is using the [FormRecognizerModelFactory](https://docs.microsoft.com/dotnet/api/azure.ai.formrecognizer.models.formrecognizermodelfactory?view=azure-dotnet); deserialization would need to be customized to make use of the factory.

Serialization support would be a major feature that needs careful design and approval by our API governance board. We've had similar feedback in the past, so we're aware this is a feature that there is interested in.   I've tagged this as a feature request and moved this to the backlog for consideration.

_(related: #21982, #25303)_

**Comment by KrzysztofCwalina** [comment]
> Currently we intentionally do not support serialization for our model types since we can't guarantee compatibility across SDK versions.

Let me clarify. We do support strong compatibility across SDK versions for public Azure SDK APIs on par with the high compatibility of .NET/CLR APIs. Serialization compatibility is a separate problem though, and a much harder problem, if I may add. Because of that, we probably don't want to say that we guarantee serialization compatibility of arbitrary models, but I think it's totally reasonable to make a subset of models serialization compatible, if there are requests from users. We should probably do it through a custom converter, not by exposing the ctor.

**Comment by wahyuen** [comment]
@jsquire I may have missed something here, but I don't quite understand the thought process behind not guaranteeing 'compatibility' across SDK versions for serialization.

In the case where a model would change (as it can/should over the lifetime of a service), whether or not you support serialization or not still results in a customer/consumer having to update their code.

Whether its the SDKs model changing property `a` to `a_and_b`, whether that sits at the SDK model level, or, effectively downstream in consumers code is kind of irrelevant. Breaking changes are breaking changes and require some sort of code modification. Whether or not a service will support the same serialized object between versions is kind of irrelevant in my opinion. (would love to hear your thoughts on this!)

Whilst I certainly don't know the inner machinations of what happens on the API governance board, all I can offer is that as a consumer who is **_wanting_** to use the SDK, these types of issues are just further barriers to entry and adds to developer frustrations. It's not that we can't work around the issue, its more to the point that a developer should not have to!

**Comment by mitsufu** [comment]
Hi, do you have a clean way to do this now ? thanks

**Comment by jeremy-visionaid** [comment]
I'd also like to be able to deserialize AnalyzeOperationResult and/or FormPageCollection from JSON. The reflection is a bit trickier for that since FormPageCollection is the highest level public type, but perhaps still better to be able to leverage  Azure.AI.FormRecognizer rather than writing a custom set of types for the model in the interrim of this issue hopefully getting addressed.

I'm curious what Microsoft's expectation is here for users that need to store the results and/or process them at a later time? Deserialization from JSON seems a reasonable expectation and the library's utility is greatly reduced for not being able to do that. For another instance, testing for regressions might require an awful lot of data to be mocked (if you want to avoid hitting the service again, which is slow and costs money). Replaying actual JSON is a much simpler proposition than using the model factory.

**Comment by minimalisticMe** [comment]
I can confirm the workaround of @kennyfowler is working nicely.

However I'd prefer a "real" solution like `JsonSerializer.Deserialize<AnalyzeResult>(jsonString);` like suggested by @jeremy-visionaid for testing and regressions, where cached files can speed up the process by a lot.

**Comment by jeremy-visionaid** [comment]
@minimalisticMe After trying out the various options and combinations of Azure API offerings, I did end up going the route of writing custom types to support serialization, and accepted the possible need for multiple heirarchies for future models/APIs. Making REST API calls in C# is fairly trivial anyway, so it turned out to be less effort than trying to adapt azure-sdk-for-net for my use case. Essentially, I only found it useful for an initial proof of concept and as a reference for my own initial data model.

**Comment by jgrusewski** [comment]
Using Azure.AI.FormRecognizer 4.1.0 the workaround does not seem to work.

`var content = response.Content.ToString();`
After the analysis has finished the Content variable is empty.

When trying:

`var content = JsonConvert.SerializeObject(result);`

In combination with the following code:

`var jsonElement = JsonDocument.Parse(content).RootElement;
var methodInfo = typeof(AnalyzeResult).GetMethod("DeserializeAnalyzeResult", BindingFlags.NonPublic | BindingFlags.Static);
var analyzeResult = (AnalyzeResult)methodInfo.Invoke(null, new object[] { jsonElement });			
`

The deserialization is only partially done, any thoughts on how to use this workaround with 4.1.0?

**Comment by pallavit** [comment]
@m-nash this seems to be another usecase for model serialization. Do you have an overall issue that I should link all the dependent issues to?

**Comment by supplemarty** [comment]
I believe the below workaround should provide a solution, using Azure.AI.DocumentIntelligence 1.0.0-beta.1.

`            Byte[] bytes = File.ReadAllBytes(filePath);
            AnalyzeDocumentContent content = new AnalyzeDocumentContent() { Base64Source = BinaryData.FromBytes(bytes) };
            var operation = await client.AnalyzeDocumentAsync(WaitUntil.Completed, "prebuilt-layout", content);

            using (var sr = new StreamReader(operation.GetRawResponse().ContentStream))
            {
                string j = sr.ReadToEnd();
                File.WriteAllText(targetJsonFilePath, j);
            }

            string json = File.ReadAllText(targetJsonFilePath);
            var jd = JsonDocument.Parse(json);
            var jsonElement = jd.RootElement.GetProperty("analyzeResult");
            var methodInfo = typeof(AnalyzeResult).GetMethod("DeserializeAnalyzeResult", BindingFlags.NonPublic | BindingFlags.Static);
            var analyzeResult = (AnalyzeResult)methodInfo.Invoke(null, new object[] { jsonElement });

`

**Comment by jandedude** [comment]
> I believe the below workaround should provide a solution, using Azure.AI.DocumentIntelligence 1.0.0-beta.1.
> 
> `
> 
> ```
>        Byte[] bytes = File.ReadAllBytes(filePath);
>        AnalyzeDocumentContent content = new AnalyzeDocumentContent() { Base64Source = BinaryData.FromBytes(bytes) };
>        var operation = await client.AnalyzeDocumentAsync(WaitUntil.Completed, "prebuilt-layout", content);
> 
>        using (var sr = new StreamReader(operation.GetRawResponse().ContentStream))
>         {
>             string j = sr.ReadToEnd();
>             File.WriteAllText(targetJsonFilePath, j);
>         }
> 
>         string json = File.ReadAllText(targetJsonFilePath);
>         var jd = JsonDocument.Parse(json);
>         var jsonElement = jd.RootElement.GetProperty("analyzeResult");
>         var methodInfo = typeof(AnalyzeResult).GetMethod("DeserializeAnalyzeResult", BindingFlags.NonPublic | BindingFlags.Static);
>         var analyzeResult = (AnalyzeResult)methodInfo.Invoke(null, new object[] { jsonElement });
> ```
> 
> `

Please Note that version 1.0.0-beta.**2** introduced an error for the above script, apparently the amount of parameters have changed. A very simple fix is updating the last line to:

var analyzeResult = (AnalyzeResult)methodInfo.Invoke(null, new object[] { jsonElement, **null** });

**Comment by pallavit** [comment]
@kinelski as FYI and to ensure that the workaround proposed will work.

@m-nash , @kinelski I am assuming model serialization support will work for document intelligence SDK since it is the new DPG SDK if not, @kinelski we should enable the flag for it as cognitive customers will definitely find it useful.

**Comment by stefannovak** [comment]
I wanted to aggregate the confidence values for my documents in the response. It should have been as simple as `Deserialize<AnalyzeResult>(json)`, but instead I've had to do a bunch of JObject parsing. Either that or make up my own models to mimic AnalyzeResult.
