### ISSUE TITLE
Azure Resource Manager Cdn Readme issues

### ISSUE THREAD

**Issue by Tianyun-G** [Azure/azure-sdk-for-net#27211]
1.
Section [link](https://github.com/Azure/azure-sdk-for-net/tree/main/sdk/cdn/Azure.ResourceManager.Cdn#getting-started):
![image](https://user-images.githubusercontent.com/65581162/155692114-83c698c0-98fe-4860-aa00-a78c9a45a639.png)
Suggestion: 
Update package version to [1.0.0-beta.3](https://www.nuget.org/packages/Azure.ResourceManager.Cdn/1.0.0-beta.3)

2.
Section [link](https://github.com/Azure/azure-sdk-for-net/tree/main/sdk/cdn/Azure.ResourceManager.Cdn#contributing):
![image](https://user-images.githubusercontent.com/65581162/155692133-a4d02162-b926-43ff-8957-f97511f132fc.png)
Suggestion: 

1. Add Link:  https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/resourcemanager/Azure.ResourceManager/docs/CONTRIBUTING.md
2. Add Link: https://opensource.microsoft.com/codeofconduct/
3. Add Link: https://opensource.microsoft.com/codeofconduct/faq/

@scottaddie ,@AlexGhiondea and @cdnfdsuppgithub for notification.

**Comment by Yao725** [comment]
- We released the 1.0.0-beta.3 from this [feature branch](https://github.com/Azure/azure-sdk-for-net/tree/feature/mgmt-cdn-2021-06), so 1.0.0-beta.2 is still used here because the code in main branch belongs to beta.2. In next release from the main branch, this version number here will be updated to 1.0.0-beta.4.
- We missed this part and will add the link to the places that you mentioned.

Thanks a lot for your feedback.

**Comment by Yao725** [comment]
This issue has been fixed.
