### ISSUE TITLE
[QUERY] How to detect or sync the real-time Event Hub partition length from receiver SDK code

### ISSUE THREAD

**Issue by gjjtip0926** [Azure/azure-sdk-for-net#27295]
### Library name and version

Azure.Messaging.EventHubs 5.6.2

### Query/Question

In some certain circumstances while receiving events data from Event Hub partition, I will get following error which indicates 
 the mismatching of offset between supplied value (in the checkpointing file) and system value(current real length of EH partition)

**The supplied offset '10000' is invalid. The last offset in the system is '5000'**

As we known, Checkpointing is the responsibility of the consumer side and the checkpointing files will be generated and stored into associated Blob Storage Account generally by SDK code. Based on this [method](https://github.com/Azure/azure-sdk-for-net/blob/3bfb0f8509a0fdf30cdae639b9861f047118d96c/sdk/eventhub/Azure.Messaging.EventHubs/src/Primitives/EventProcessor.cs#L689), I understand that we can pass the starting position(offset) parameter or read the offset from checkpointing file ([code link](https://github.com/Azure/azure-sdk-for-net/blob/3bfb0f8509a0fdf30cdae639b9861f047118d96c/sdk/eventhub/Azure.Messaging.EventHubs/src/Primitives/EventProcessor.cs#L1684))make sure that event data won't be duplicate per consumer group.

But if the event data in the partition is removed due to retention policy and the length of partition changes. For example, if the latest offset was updated as 10000 in the checkpointing file, but the current real length of this specific partition became 5000, so that consumer can't receive the data from 10000 index anymore.

How consumer side detect and sync this behavior and update the offset value in the checkpointing file accordingly?  

If I have any misunderstanding regarding above information, please kindly correct me. Thanks a lot.

**Comment by jsquire** [comment]
Hi @gjjtip0926.  Thank you for reaching out.  The offset is not an index into the event stream, it's the physical location of it.  It is a stable value that should not change as events age out of the retention period.   If the event that the offset corresponds to ages out, that offset is no longer valid, causing the event processor to begin with the next available event in the stream.  

If you're not using an event processor and are manually positioning a consumer, when you create your [EventPosition](https://docs.microsoft.com/dotnet/api/azure.messaging.eventhubs.consumer.eventposition.fromoffset?view=azure-dotnet#azure-messaging-eventhubs-consumer-eventposition-fromoffset(system-int64-system-boolean)), you have the option of passing `isInclusive`.  Setting this to `false` will opt you into the "read the next event in the stream after this offset" behavior.   If you'd prefer, you can also call [GetPartitionPropertiesAsync](https://docs.microsoft.com/dotnet/api/azure.messaging.eventhubs.consumer.eventhubconsumerclient.getpartitionpropertiesasync?view=azure-dotnet#azure-messaging-eventhubs-consumer-eventhubconsumerclient-getpartitionpropertiesasync(system-string-system-threading-cancellationtoken)) from the consumer, producer, or receiver which will return information about the last enqueued offset.

I'd like to understand a bit more about your scenario, if you're willing.    

- Is that error one that you're seeing while using an event processor?   
- Are you manually managing checkpoints for one of the other consumers?  If so, can you share how you're initializing the consumer?
- How old was the checkpoint data?
- What is the retention period for the Event Hub configured to be?
- Was the Event Hub deleted and recreated after the checkpoint was recorded?

**Comment by gjjtip0926** [comment]
Hello Jess Squire,

Thank you so much for your prompt reply.

You have the option of passing isInclusive. Setting this to false will opt you into the "read the next event in the stream after this offset" behavior.
Does that mean the EP SDK will set the isInclusive as false? If the retention causes the event been removed and offset invalid, it will read next event automatically even the specified offset is bigger than last event offset in partition.

The offset is not an index into the event stream, it's the physical location of it.
Let’s say if we have offset 1-10 in one partition. If the first event was removed due to retention policy, remaining 2-9 events, where will the new incoming event be inserted? The offset 1 or offset 11?
If it’s inserted into offset 1 and the offset 10 is logged in the current checkpointing file, will the new event be consumed by client side? If it’s inserted into offset 11, what about the offset 1? Will it be used still again?

Look forward to your update😊.

Best Regards,
Jay

**Comment by jsquire** [comment]
> Does that mean the EP SDK will set the isInclusive as false?

This depends on the client type that we're talking about.   In the case of an event processor, yes.

> If the retention causes the event been removed and offset invalid, it will read next event automatically.

Yes, that is the expected behavior when setting `isInclusive` to `false` or when using an event processor.

> Even the specified offset is bigger than last event offset in partition.

Offsets do not change by a predictable pattern and only the Event Hubs service can correctly interpret them.  Generally, if an offset is larger, then it was enqueued later than an event with a smaller offset - but that is not always the case because offsets will wrap around when they reach more than the maximum offset value.

> Let’s say if we have offset 1-10 in one partition. If the first event was removed due to retention policy, remaining 2-9 events, where will the new incoming event be inserted? The offset 1 or offset 11?

Your scenario is flawed unless we define each event as a single byte.  Offsets are not contiguous; they are not an index into the stream.  At a high-level, they represent "the number of bytes that this location is offset from the first location in the partition."   That said, it's not quite as straightforward as that; the service maps and tracks the partition across a series of segments rather than one large space.

The point is that the event may have an arbitrary offset; there's no guaranteed pattern.  Generally, based on the current implementation, the new single-byte event would have an offset of 11 or greater.

> what about the offset 1? Will it be used still again?

An offset will not be reused until it grows beyond the capacity of a 64-bit integer and wraps around.   

If we assume every event that is published to the partition is exactly the maximum of 1MB, you will have to publish 8,796,093,022,207 events to experience a wrap-around.   Let's assume that you're using a dedicated Event Hubs cluster with no ingress limit and can publish 1,000 of those 1MB events per second, it will take you nearly 101,807 days to reach the overflow point where the offset would wrap.
