### ISSUE TITLE
Detect and run project ref dependencies for both root and leaf pipelines

### ISSUE THREAD

**Issue by benbp** [Azure/azure-sdk-for-net#27304]
Currently, when a leaf project has any sort of "hidden" dependency on a root project, the build/test pipeline dependencies are manually maintained, not exhaustive, and sometimes duplicated. For example, if a root project pipeline definition includes a path trigger for any leaf projects, then pull request CI jobs will trigger both the root and leaf project pipelines, running duplicate tests. This has cost in terms of extra PR cycle time and build storms.

We can simplify and improve the coverage for this scenario by:

1. Removing path triggers outside of the immediate root service directory
2. Updating the matrix job generation logic to detect any root and/or leaf projects that need to be run
    - e.g. root pipeline detects all leaves and runs the platform matrix for each of those. Leaf pipeline detects all root dependencies and runs the platform matrix for each of those.

This way, PR gates will only run for the immediate service directory pipeline in question, but will have extra jobs generated for any dependencies. It will be easier to write logic for testing these dependencies, and make PR cycle time + pipeline status history easier to reason about. It will slightly reduce build agent time by consolidating build/test job duplicates into a single pipeline run.

CC @christothes @jsquire @ckairen

**Comment by benbp** [comment]
Brainstorming: we could dynamically generate a new parent matrix.json like so, which would multiply the inner matrix by the outer project set:

```
{
  "matrix": {
    "$IMPORT": "eng/pipelines/templates/staging/platform-matrix.json",
    "TestProject": ["sdk/core/Azure.Core", "sdk/identity/Azure.Identity"]
  }
}
```

Then we could have some sort of `generateMatrixConfigPathScript` parameter that can be passed to the matrix generator pipeline, whereas right now the json config is just a hardcoded path

**Comment by m-nash** [comment]
This might go without saying, but can we make sure that this wouldn't result in duplicate runs of the same dependency?

If 2 projects A and B both depend on C, C should only run once.

It would also be nice to make sure that these don't run as one big uber step so that if a failure occurs in C we only need to rerun C and NOT A or B.  This becomes particularly important when there are dozens of dependencies,

**Comment by benbp** [comment]
@m-nash my idea is that for the scope of pull request CI checks, there are no duplicate runs. Scheduled nightly builds will have duplicate tests for the same dependency, one in the dependent pipeline and one in the dependencies pipeline. If we want to avoid that case as well, then I think we'll need some higher level validation.

Re: the uber step, I plan to make a separate issue as this is going to be a more involved solution. Right now our pipelines operate at the service directory level granularity, and only check the diff from the head of main to the head of the PR branch. I think that would need a more sophisticated check that can determine the files changed in the diff from the latest PR commit to the previous PR commit, and some sort external of build/test cache state that we can use to determine dotnet test targets within the same service directory (e.g. we test `sdk/core` but only need to re-test `Azure.Core.Experimental` on a new PR commit). Ideally there's a simpler solution but I haven't thought of it yet.

**Comment by m-nash** [comment]
@benbp yes we are the same page for deduping in PRs but not necessarily in nightly or weekly runs.

I think the deduping might be inextricably linked to the "uber step".  If I have a PR that touches service A and service B and service A depends on service B if I understand you correctly this will result in the build / test for B happening twice.  Once in the new "uber step" inside of the pipeline for A and once because the pipeline for B will also kick off.

In management case this will be quite a few duplications since most of the time the PRs are generator based which touch many projects in the same PR.
