### ISSUE TITLE
[Flaky Timeout Test] CertificateOperationTests.UpdateStatusEventuallyCompleted

### ISSUE THREAD

**Issue by christothes** [Azure/azure-sdk-for-net#27393]
### Library name

Azure.Security.KeyVault.Certificates

### Please describe the feature.

https://dev.azure.com/azure-sdk/public/_build/results?buildId=1415076&view=ms.vss-test-web.build-test-results-tab&runId=29434626&resultId=111242&paneView=historyD

This test always hovers right at the timeout limit.
![image](https://user-images.githubusercontent.com/1279263/157137095-884b0c58-19bd-4f59-9cda-5d06c95b5c7c.png)

**Comment by heaths** [comment]
Actually, it didn't *always*:

<img width="227" alt="image" src="https://user-images.githubusercontent.com/1532486/157142136-432b2f32-cd8a-4dde-9ead-a3edb5be370f.png">

This is caused by the new operation helper changes introduced around then, and the poller that gets created has a minimum 1s delay with no direct way to override. The default poller uses the retry header, but even if I pass the standard `Retry-After` (measured in seconds), the minimum enforced by the fallback polling strategy is 1s. I could use the Microsoft-specific retry headers which gives me millisecond resolution, but Key Vault only uses the `Retry-After` so I feel like I'm working around a problem introduced in the infrastructure in a non-realistic way.

@JoshLove-msft @m-nash any suggestions? I could plumb a polling strategy through the shared code, but that seems like overkill just for tests. Specifically, I'm talking about this code path:

```csharp
// CertificationOperation.cs
        public override ValueTask<Response<KeyVaultCertificateWithPolicy>> WaitForCompletionAsync(TimeSpan pollingInterval, CancellationToken cancellationToken) =>
            this.DefaultWaitForCompletionAsync(pollingInterval, cancellationToken);

// OperationHelpers.cs
        public static async ValueTask<Response<TResult>> DefaultWaitForCompletionAsync<TResult>(this Operation<TResult> operation, TimeSpan pollingInterval, CancellationToken cancellationToken)
            where TResult : notnull
        {
            OperationPoller poller = new OperationPoller();
            return await poller.WaitForCompletionAsync(operation, pollingInterval, cancellationToken).ConfigureAwait(false);
        }

// OperationPoller.cs
        public OperationPoller(DelayStrategy? fallbackStrategy = null)
        {
            _delayStrategy = new RetryAfterDelayStrategy(fallbackStrategy);
        }

// RetryAfterDelayStrategy.cs
        public RetryAfterDelayStrategy(DelayStrategy? fallbackStrategy = null)
        {
            _fallbackStrategy = fallbackStrategy ?? new ConstantDelayStrategy();
        }

// ConstantDelayStrategy.cs
        public override TimeSpan GetNextDelay(Response response, TimeSpan? suggestedInterval)
            => suggestedInterval.HasValue ? Max(DefaultPollingInterval, suggestedInterval.Value) : DefaultPollingInterval;
```

As you can see, without modifying at least the first couple files in this call stack, there's no way we can override the strategies at play here.
