### ISSUE TITLE
[QUERY] Completing a message before the handler is done

### ISSUE THREAD

**Issue by johnknoop** [Azure/azure-sdk-for-net#27491]
### Library name and version

Microsoft.Azure.ServiceBus 5.1.2

### Query/Question

Hi

I've been searching the web for an answer to this question, but I haven't come across any. My question is this:

I have a type of message that takes a long time to handle (~30-50 min). Instead of using the AutoRenewLock feature, I'm just completing the message early, before the handler function is done. I understand that if the handling fails, then the message will of course be lost, but that is ok in this case.

I've also found that the ASB client will not start receiving another message (my MaxConcurrentMessages is set to 1) until the handler function is done, regardless of whether or not I complete the message early. And this is great, it's just how I want it to behave.

Now, my question is: could there be any unexpected consequences from this unconventional way to receiving messages? I mean, the norm is to complete the message as the last action in the handler, to make sure it gets back in the queue if the handler fails. But since I don't need this fail-safety in this case, do you think it's a sound approach? Or could there be downsides that I haven't discovered yet?

Cheers

**Comment by jsquire** [comment]
//cc: @JoshLove-msft

**Comment by PramodValavala-MSFT** [comment]
@johnknoop That is perfectly fine. It is like receiving messages with [`ReceiveMode`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.servicebus.queueclient.receivemode?view=azure-dotnet) set to [`ReceiveAndDelete`](https://docs.microsoft.com/en-us/azure/service-bus-messaging/message-transfers-locks-settlement#receiveanddelete), only that you are manually completing the message after a while instead of immediately on receiving it.

**Comment by johnknoop** [comment]
Thanks
