### ISSUE TITLE
[QUERY] Azure Search Spelling Mistakes

### ISSUE THREAD

**Issue by ssghoda** [Azure/azure-sdk-for-net#27574]
### Library name and version

Azure Search 

### Query/Question

We are trying to solve the issue of spelling mistakes in names/nouns while doing a search in an Azure Index. We have tried the fuzzy search but it gives a lot of unnecessary results. We also tried a custom phonetic analyzer which solves some scenarios but not all. Recently we came across Spell Checker API which is in public preview mode. 

We were wondering if we can train Azure Cognitive Search on our data set for the spelling (using the spell check listed [here](https://docs.microsoft.com/en-us/azure/search/speller-how-to-add)). So that next time someone enters the same wrong spelling, Azure Search knows what to do. We are aware of SynonymMaps but that is a list that we need to maintain ourselves. We were wondering if there was something that Azure Search itself can do.

How does Azure Cognitive Search Spell Check work on proper nouns?  (ex: Jeferson didn’t correct to Jefferson, whereas Smth was corrected to Smith)

Why does Bing API [spell](https://docs.microsoft.com/en-us/azure/cognitive-services/bing-spell-check/overview) check fix the proper nouns and not Azure Cognitive Search Spell Check?  (ex: Jeferson was corrected to Jefferson)

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by Mohit-Chakraborty** [comment]
Adding @dereklegenzoff for suggestions.

**Comment by dereklegenzoff** [comment]
Hi @ssghoda - there's not currently a way to train Azure Cognitive Search's spell check functionality. If you want to train a model for spell check, you'd have to leverage some open-source technologies and then integrate that with your search experience.

The spell check powering Azure Cognitive Search is different than what's powering the Bing Spell Check API so you should expect different results from the two services. The best way to determine how the APIs work on different words and phrases is to test them out (which it sounds like you've already been doing).

**Comment by ssghoda** [comment]
Thank you @dereklegenzoff for your response. I have some follow-up questions:

Is there a way to integrate Bing Spell Check API and Azure Cognitive Search? If not today, can we seek support from Microsoft on this or maybe open a support ticket?
If not, can you recommend some open-source technologies which we can easily integrate with Azure Cognitive Search?
Any other ideas to solve this spelling mistakes issue, apart from fuzzy search and custom phonetic analyzer?

**Comment by dereklegenzoff** [comment]
One approach I see customers take to solve problems like this is to use a mix of query syntax to produce the desired results. For example, fuzzy search is more likely to produce unexpected matches for shorter strings because the default edit distance is 2.

`Jefferson~` is equivalent to `Jefferson~2` and will find all terms within 2 characters. However, for Smith, two edit distances will produce a ton of candidates so you would probably want to only use an edit distance of one: `Smith~1`. You could add some logic in your code to decrease the edit distance to 1 if the word is 5 characters or less (or something along those lines).

You also have the option to boost exact matches higher than fuzzy matches. For example, you could do `Jefferson~ OR Jefferson^2` which will return both fuzzy and exact matches but boost the exact matches higher. These two approaches in combination with spell check are probably the best way to further refine spell check without pulling in an external service.

**Comment by dereklegenzoff** [comment]
In general, the pattern for using the Bing Spell Check API and Azure Cognitive Search together would be to:
1. Take a user's query and send it to the Bing Spell Check API
2. Use the output of the Spell Check API to edit or append to the query and then send the query to Azure Cognitive Search.

Regarding open-source options, I found this repo that looks promising and allows for customization: https://github.com/neuspell/neuspell. In general, I expect you could find a lot of good models on Hugging Face.

**Comment by ssghoda** [comment]
This is awesome @dereklegenzoff . The last two comments provide much more information that we can try and see how it helps.

Along with, `Jefferson~ OR Jefferson^2` should we also add `/.*Jefferson.*/` ? For example, `Jefferson~ OR Jefferson^2 OR /.*Jefferson.*/`

How would you change that line if you are searching for multiple words such as "Jefferson Medical Center"? Would it be `Jefferson~ Medical~ Center~ OR "Jefferson Medical Center"^2`?

**Comment by dereklegenzoff** [comment]
I'd recommend against also adding in `/.*Jefferson.*/` unless you expect users to be needing partial term searches. Any type of partial term search (fuzzy search, regex search, prefix search) is more computationally expensive than other keyword searches because it requires a full index scan so adding in additional clauses will slow down queries and limit throughput. If you want to also match just parts of terms, I'd recommend exploring the custom analyzer presented in this [document](https://docs.microsoft.com/en-us/azure/search/search-query-partial-matching).

Regarding the second part of your question, this depends a bit on your requirements. When you put `"Jefferson Medical Center"` in quotes you're requiring that exact phrase to be matched. If you want the exact phrase to be matched, then that syntax is great. If you'd also want results that just said `Jefferson Medical` then you might want other syntax such as `(Jefferson~ Medical~ Center~) OR (Jefferson^2 Medical^2 Center^2)`. You could also decide if you want all terms to be matched and add in additional `And`s and `OR`s. You could also go one step further and do  `(Jefferson~ Medical~ Center~) OR (Jefferson^2 Medical^2 Center^2) OR "Jefferson Medical Center"^4` to further boost exact phrase matches.

I'd probably recommend testing out different syntax and seeing what produces the best results for your scenario.

**Comment by ssghoda** [comment]
Thanks a lot @dereklegenzoff This gives a lot of clarity and gives nice information to test different things.
