### ISSUE TITLE
Missing aspects the policy will honor

### ISSUE THREAD

**Issue by zitzerd** [Azure/azure-sdk-for-net#27615]
Under remarks there is a line saying 

The retry policy will honor the following aspect: 
*
*
*

The bullet list with the aspects it will honor is blank

Thanks
diego

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 75652f4c-d360-24f6-c3a9-bab9030c6d3e
* Version Independent ID: e9b0ab11-34f7-c2f2-aea0-2a3f33a6743b
* Content: [RetryExponential Class (Microsoft.ServiceBus) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/microsoft.servicebus.retryexponential?view=azure-dotnet)
* Content Source: [xml/Microsoft.ServiceBus/RetryExponential.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.ServiceBus/RetryExponential.xml)
* Service: **service-bus-messaging**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by navba-MSFT** [comment]
@zitzerd Apologies for the late reply. Since that is an older version of the SDK, we are checking on the feasibility of the docs fix. I would recommend to use [Azure.Messaging.ServiceBus](https://docs.microsoft.com/en-us/dotnet/api/azure.messaging.servicebus?view=azure-dotnet) SDK.

In the meantime, I am sending you the missing retry details this github thread. Hope this helps.

The retry policy will honor the following aspect:
- The policy always honor the [Microsoft.ServiceBus.Messaging.ClientEntity.OperationTimeout](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.servicebus.cliententity.operationtimeout?view=azure-dotnet#microsoft-azure-servicebus-cliententity-operationtimeout) property so that retry will terminate if the next retry interval will exceed the operation time.

- The policy only retry when [Microsoft.ServiceBus.Messaging.MessagingException.IsTransient](https://docs.microsoft.com/en-us/dotnet/api/microsoft.servicebus.messaging.messagingexception.istransient?view=azure-dotnet) is true.

- The policy should delay further by an additional 10 seconds if exception is a [Microsoft.ServiceBus.Messaging.ServerBusyException](https://docs.microsoft.com/en-us/dotnet/api/microsoft.servicebus.messaging.serverbusyexception?view=azure-dotnet).

Please let me know if you have any follow-up questions.

**Comment by zitzerd** [comment]
Hi! Thank you!

Diego

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by navba-MSFT** [comment]
@zitzerd Thanks for your reply. Please let me know if you need any further assistance on this or we can proceed with the archival.

**Comment by navba-MSFT** [comment]
@zitzerd I have got a confirmation from the Product Owners that since “WindowsAzure.ServiceBus” is our old SDK, they have no plans to enhance it any further (critical bug fixes only). So the docs are unlikely to be updated. To answer your question related to the retry policy aspects I have shared it in my above comments. Our recommendation is to use [Azure.Messaging.ServiceBus](https://docs.microsoft.com/en-us/dotnet/api/azure.messaging.servicebus?view=azure-dotnet) SDK. The same has been suggested [here](https://www.nuget.org/packages/WindowsAzure.ServiceBus/#readme-tab) too. 

With that, I am proceeding with the closure of this issue. If you need any further assistance in future, please feel free to reopen this github thread.
