### ISSUE TITLE
[BUG] ServiceBusRetryOptions seems to be not working

### ISSUE THREAD

**Issue by pjonusas** [Azure/azure-sdk-for-net#27630]
### Library name and version

Azure.Messaging.ServiceBus 7.6.0

### Describe the bug

We recently experienced ServiceBus issues where after receiving a bunch of `ServiceTimeout` exceptions noticed in application insights no retries. 

We have `ServiceBusRetryOptions` setup as follows for our client:
```
var serviceBusClientOptions = new ServiceBusClientOptions()
            {
                RetryOptions = new ServiceBusRetryOptions()
                {
                    MaxRetries = 5,
                    Mode = ServiceBusRetryMode.Exponential,
                    MaxDelay = TimeSpan.FromSeconds(30),
                    TryTimeout = TimeSpan.FromSeconds(30)
                }
            };
```

And in application insights it is shown to only have taken 30s.
![timeout](https://user-images.githubusercontent.com/7058871/158962433-b7b4f1cb-a0bb-43cc-9aec-2e1ccfc4502f.PNG)

### Expected behavior

Expect request duration to be longer as it should include all 5 retries.

### Actual behavior

Request seems to return `ServiceTimeout` exception after first attempt.

### Reproduction Steps

Difficult to reproduce on demand.

### Environment

Azure AppService
.Net Version: 6.0.1

**Comment by jsquire** [comment]
Hi @pjonusas.  Thank you for reaching out and we regret that you're experiencing difficulties.   Can you help us understand more about your end-to-end scenario?  Snippets that demonstrate your publishing flow would be helpful.   One area of interest that we'd like to understand is whether you're using transactions.

**Comment by jsquire** [comment]
Thank you for the additional context, @pjonusas.  Unfortunately, the behavior that you're seeing is expected in this scenario.   Due to the way that transactions work with Service Bus, retries cannot be performed when there is an active ambient transaction.   Looking over the docs, it seems that we did a poor job of calling this out.   I've opened [#27637](https://github.com/Azure/azure-sdk-for-net/issues/27637) and [#90071](https://github.com/MicrosoftDocs/azure-docs/issues/90071) to track getting this context added.

I'm going to mark this as addressed, but please feel free to unresolve if you'd like to continue the discussion.
