### ISSUE TITLE
[BUG] GetFilesAndDirectories does not enumerate files and directories in lexical order

### ISSUE THREAD

**Issue by mattgotteiner** [Azure/azure-sdk-for-net#27692]
### Library name and version

Azure.Storage.Files.Shares 12.9.0

### Describe the bug

GetFilesAndDirectories returns a list of directories followed by a list of files in a single page. The public API docs state that directories and files are returned intermingled in lexical order

### Expected behavior

Behave the same as the public API and v11 SDK when returning files and directories in lexical order
https://docs.microsoft.com/en-us/rest/api/storageservices/list-directories-and-files#remarks
> Files and directories are listed intermingled in lexically sorted order in the response body.

### Actual behavior

Returns a list of directories followed by a list of files

### Reproduction Steps

Upload directories "a", "b", and files "a.txt", "b.txt" to some file share. Run the following code:

```
using Microsoft.Azure.Storage.File;
using Azure.Storage.Files.Shares;

var shareUri = new Uri("SAS URI TO YOUR FILE SHARE");
var v11Client = new CloudFileShare(shareUri);
var v12Client = new ShareClient(shareUri);

string[] v11Paths = v11Client.GetRootDirectoryReference().ListFilesAndDirectories().Select(item => Path.GetFileName(item.Uri.LocalPath)).ToArray();
string[] v12Paths = v12Client.GetRootDirectoryClient().GetFilesAndDirectories().Select(item => item.Name).ToArray();

Console.WriteLine($"v11 paths in order: {string.Join(", ", v11Paths)}");
Console.WriteLine($"v12 paths in order: {string.Join(", ", v12Paths)}");
```

Output:
```
v11 paths in order: a, a.txt, b, b.txt
v12 paths in order: a, b, a.txt, b.txt
```

### Environment

.NET 6

**Comment by SaurabhSharma-MSFT** [comment]
@mattmsft We are looking into it and get back to you for any questions.

**Comment by amnguye** [comment]
Sorry for the late reply, this fell through the cracks.

I'm not able to reproduce the issue you're running into. I ran our tests and I ran your code snippet and I'm seeing the ordering as
```
a
a.txt
b
b.txt
```

Could you also try the latest version and see if that resolves your issues?

**Comment by amnguye** [comment]
Scratch that, I was able to reproduce the issue you're seeing. Looks like the issue is in the generated code and the fact after that when we go to combine the lists again it goes directories then files, and with pagination the order gets mixed up.

https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/storage/Azure.Storage.Files.Shares/src/Models/Internal/GetFilesAndDirectoriesAsyncCollection.cs#L51
(same is in the Sync collection as well).

We will update once we know what fix to make to have the generated code not do this, or if we can maintain the order after the generated code gets the response back from the service.
