### ISSUE TITLE
[BUG][Azure.Identity] Failed to parse scope for Azure Analysis Service

### ISSUE THREAD

**Issue by zhiweiv** [Azure/azure-sdk-for-net#27749]
The scope of Azure Analysis Service is **https://*.asazure.windows.net** per https://docs.microsoft.com/en-us/azure/analysis-services/analysis-services-async-refresh#authentication, while getting token for this I get following error

```
AzureCliCredential authentication failed: The specified scope is not in expected format. 
Only alphanumeric characters, '.', '-', ':', and '/' are allowed (Parameter 'scope')
```
Here is the code
```
var resource = "https://*.asazure.windows.net";
var cred = new DefaultAzureCredential();
cred.GetToken(new TokenRequestContext(new string[] { $"{resource}/.default" }));
```

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team members best able to assist.

**Comment by schaabs** [comment]
@zhiweiv Sorry you've run into this problem. Have you tried using the actual host of the server you're trying to connect to? According to the docs you link to it seems the host is region specific, so if you haven't already, could you try using the specific host rather than the wildcard. For example if your instance is in the west us region try `https://westus.asazure.windows.net/.default` rather than `https://*.asazure.windows.net`

**Comment by zhiweiv** [comment]
Thanks for the suggestion, in my test the * can be replaced with any chars, for example https://test.asazureaa.windows.net or https://abcd.asazureaa.windows.net, the tokens generated with these are all work, it is weird. 

Token with https://*.asazure.windows.net is also work definitely, you can see the official code example https://github.com/microsoft/Analysis-Services/blob/master/RestApiSample/RestApiSample/Program.cs#L69.

To avoid confusion, do you plan to add * to the allow list in scope validation?

**Comment by zhiweiv** [comment]
I will do more test soon.

**Comment by zhiweiv** [comment]
The * can be replaced with any chars, the token still work, it is ok now.
