### ISSUE TITLE
Remove spaces from path /doc/Data\%20Plane\%20Code\%20Generation

### ISSUE THREAD

**Issue by annelo-msft** [Azure/azure-sdk-for-net#27799]
Spaces in filepaths are difficult to work with on non-Windows systems.
See https://github.com/Azure/azure-sdk-for-net/pull/27769#discussion_r836427814

**Comment by lirenhe** [comment]
The original issue was fixed in https://github.com/Azure/azure-sdk-for-net/pull/27870

Looks there is a merging issue that cause 2 folders now.
![image](https://user-images.githubusercontent.com/9100546/162654226-623f6f6a-5f88-4d2e-aa78-26c836eab7ca.png)

@chunyu3, could you help to update the folder structure again?  Thanks

**Comment by chunyu3** [comment]
Resoved. https://github.com/Azure/azure-sdk-for-net/pull/28136
