### ISSUE TITLE
[BUG] Blob State Filter Not Working as Expected

### ISSUE THREAD

**Issue by RadekMyska27** [Azure/azure-sdk-for-net#27813]
### Library name and version

Azure.Storage.Blobs 12.11.0

### Describe the bug

I tried use blobstate to list uncommitted blobs by GetBlobsByHierarchyAsync(). Method with BlobStates.Uncommitted return blobs which was succesful uploaded. Moreover GetBlobsByHierarchyAsync() with BlobStates.Uncommitted return same result as with BlobStates.None.

### Expected behavior

Blob which was successful uploaded are not listed by method GetBlobsByHierarchyAsync() with BlobStates.Uncommitted

### Actual behavior

Blob which was successful uploaded are listed by method GetBlobsByHierarchyAsync() with BlobStates.Uncommitted

### Reproduction Steps

- upload some blob
- call GetBlobsByHierarchyAsync() with BlobStates.Uncommitted

### Environment

.NET SDK (s ohledem na libovolný soubor global.json):
 Version:   6.0.201
 Commit:    ef40e6aa06

JetBrains Rider 2121.2.3

**Comment by RadekMyska27** [comment]
Hi @SaurabhSharma-MSFT ,

I want to ask if you have any progress with my issue? 
Eventually if need some information please let me know. 
Many thanks.

With best regards
Radek

**Comment by SatishBoddu-MSFT** [comment]
Hello @RadekMyska27 Thanks for reaching this issue on this forum, I have verified the method GetBlobsByHierarchyAsync(). Method with BlobStates.Uncommitted, for me the result set contains both committed and uncommitted, same as stated in your initial query!

We are working internally with the team on this query!
Meanwhile, please make use of the Etag property to identify the uncommitted blobs as a workaround, so that you don't have any blockers as of now, until we get back to you!

![image](https://user-images.githubusercontent.com/62923178/162783981-344819f9-6ede-43d7-b198-726c8a45d00c.png)

**Comment by RadekMyska27** [comment]
Hi @[SatishBoddu-MSFT](https://github.com/SatishBoddu-MSFT), 
for my app will be very helpful have opportunity **listed only committed blobs**. Can method GetBlobsByHierarchyAsync() and GetBlobsAsync() support this by for example new BlobState flag **Committed**? 
Thank you.

**Comment by SatishBoddu-MSFT** [comment]
Hello @RadekMyska27 I agree with your suggestion!

**Comment by RadekMyska27** [comment]
Hi @SatishBoddu-MSFT , 
thanks this is really good news for me, I appreciate that.
