### ISSUE TITLE
[QUERY] Porting to .net 6 - behind a proxy - connection string induced amqpwebsockets transport type - seems not working anymore 

### ISSUE THREAD

**Issue by VaclavK** [Azure/azure-sdk-for-net#27812]
### Library name and version

Microsoft.Azure.WebJobs.Extensions.ServiceBus/Azure.Messaging.ServiceBus

### Query/Question

Porting our Azure function to .net core 6/fn v 4

so this involved switching Microsoft.Azure.WebJobs.Extensions.ServiceBus over to 5.3.0 so internally it switches from deprecated SB SDK to Azure.Messaging.ServiceBus

we are running behind a corp proxy here
we used to be able to append transport mode to connection string to switch over to amqpwebsockets (443)

as in 
"ServiceBusQueueConnection": "Endpoint=sb://....;TransportType=AmqpWebSockets",

this no longer works and I have to switch the transport mode via config (which is fine) or code I guess
e.g. 
"AzureFunctionsJobHost:extensions:ServiceBus:TransportType": "AmqpWebSockets",

Just wondering if this is recognized "breaking change" or essentially a bug?

### Environment

.net60
local env on VS 17.1.2
azure function tooling 4.0.1

**Comment by jsquire** [comment]
Hi @VaclavK.   Thank you for reaching out and we regret that you're experiencing difficulties.  

The change that you're seeing was an intentional design decision.  The client libraries in the current generation of the Azure SDK, `Azure.Messaging.ServiceBus` included, support connection strings only in the format that the Azure portal returns them.  Many of the legacy packages built custom dialects around connection strings, supporting additional tokens with specific requirements for content and format.  These were inconsistent between different packages, often non-obvious and not well documented, and were a frequent cause of confusion.

For Azure Functions configuration of the Service Bus trigger and bindings, in addition to the setting that you mentioned, the transport can be specified in `host.json` when using v5.0+ of the `Microsoft.Azure.WebJobs.Extensions.ServiceBus` package.

```json
{
  "extensions": {
    "serviceBus": {
      "transportType" : "amqpWebSockets"          
  }
}
```

**Comment by VaclavK** [comment]
@jsquire thanks for reply and the full context here

the decision taken makes perfect sense of course and adding a value for the future - as mentioned, I have already addressed this in my app -  thanks for the pointer re _host.js_

closing from my side
