### ISSUE TITLE
[BUG] Get Properties Services failed 

### ISSUE THREAD

**Issue by dioum2touba** [Azure/azure-sdk-for-net#27819]
### Library name and version

Azure.ResourceManager.ArmClient.GetGenericResource (1.0.0-beta.7)

### Describe the bug

We have two app plan services in our azure subscription

`var properties = await armClient.GetGenericResource(new ResourceIdentifier(app.ResourceIdentifier)).GetAsync();`

When we try to run this code in a loop (over a list containing data from our two services), the first run fails and the second runs successfully.

### Expected behavior

Normally this piece of code should return the properties of the azure services (App Plan) that are in our subscription

### Actual behavior

We have two app plan services in our azure subscription that we wanted to retrieve their properties with Azure ResourceManager SDK with version 1.0.0-beta.7.

`var properties = await armClient.GetGenericResource(new ResourceIdentifier(app.ResourceIdentifier)).GetAsync();`

When we try to run this code in a loop (over a list containing data from our two services), the first run fails and the second runs successfully.

To solve this problem, we used the GET API https://management.azure.com/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Web/serverfarms/{name}?api-version= 2021-02-01 which works fine.

### Reproduction Steps

`var properties = await armClient.GetGenericResource(new ResourceIdentifier(app.ResourceIdentifier)).GetAsync();`

### Environment

Information about our environment:

.Net SDK: 6.x.x

C language#

Framework: .Net

Operating System: Windows 10

Project Type: Azure Functions

Company: Expertime

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by ArthurMa1978** [comment]
@ArcturusZhang  please help to check if our new release has upgraded to right version

**Comment by ArcturusZhang** [comment]
Hi @dioum2touba thanks for this issue.
I can reproduce your issue on my side using the resource id of `serverfarms`.

Our "GenericResource" API has the ability to automatically fetch the latest api-version of the corresponding resource type and use it immediately in the request.
It first calls [an API](https://github.com/Azure/azure-sdk-for-net/blob/fa1a1f030666cf1156f3fced8c7c98bff5e3eef1/sdk/resourcemanager/Azure.ResourceManager/src/Resources/Custom/ResourceProviderCollection.cs#L64) that list all the available resource types and their corresponding api-version on the RP (in your case, it is `Microsoft.Web`), and then get the corresponding resource type out from the dictionary ([code here](https://github.com/Azure/azure-sdk-for-net/blob/fa1a1f030666cf1156f3fced8c7c98bff5e3eef1/sdk/resourcemanager/Azure.ResourceManager/src/Resources/Custom/ResourceProviderCollection.cs#L67))
The root cause of this is that the dictionary get above is case sensitive. The resource id you are using might be like this:
```
/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Web/serverfarms/{name}
```
this is what will return from app service - and its resource type is `Microsoft.Web/serverfarms`. But in the response of list REST APIs of Microsoft.Web, the resource type is `serverFarms`:
```
{
      "resourceType": "serverFarms",
      "locations": [ /*...*/],
      "apiVersions": [
          "2022-03-01",
          /* .... */
      ]
}
```
And at this point, my local reproduction gives me the exception: 
```
Unhandled exception. System.InvalidOperationException: Invalid resource type Microsoft.Web/serverfarms
   at Azure.ResourceManager.Resources.ResourceProviderCollection.GetApiVersionAsync(ResourceType resourceType, CancellationToken cancellationToken)
   at Azure.ResourceManager.Resources.GenericResource.GetApiVersionAsync(CancellationToken cancellationToken)
   at Azure.ResourceManager.Resources.GenericResource.GetAsync(CancellationToken cancellationToken)
```

I have an assumption that your second call could succeed because in your second resource id, it might have a upper case `F`, or it is another resource type that occasionally does not have similar issues.

Considering that the request urls are case insensitive, we will make some follow up to make the matching mechanism I described above also case insensitive, and this issue could be resolved.

As a workaround you currently could use, you could try first uniform the casing in your resource ids, to make sure they all have `serverFarms` instead of `serverfarms`.
