### ISSUE TITLE
Azure.AI.FormRecognizer API gives different results when used in winform and .net core webapi 3.1.

### ISSUE THREAD

**Issue by akmichael** [Azure/azure-sdk-for-net#27933]
### Library name and version

Azure.AI.FormRecognizer 4.0.0-beta.3

### Describe the bug

I am scanning below file using Invoice pre-built api. When I call azure form api in .net core webapi, I get additional data in invoice no (order No concatenated) for same invoice file. but it is correct when api is called from Winform. Same code is used in both.

**Invoice**
![image](https://user-images.githubusercontent.com/8349884/161237871-a30e7210-b3a0-4d2a-bfc6-9735ca6e7faf.png)

**web api result**
![image](https://user-images.githubusercontent.com/8349884/161238773-90417158-541a-44aa-8c29-2acf00782651.png)

**winform api result**
![image](https://user-images.githubusercontent.com/8349884/161238553-9b4c19a1-8580-46a7-a126-fc9e876875fb.png)

**formrecognizer output**
![image](https://user-images.githubusercontent.com/8349884/161242194-85e7f2b2-15a3-4626-851d-8e8f89059e73.png)

### Expected behavior

screenthost attached

### Actual behavior

screenthost attached

### Reproduction Steps

screenthost attached

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by akmichael** [comment]
note: Azure.AI.FormRecoginzer version in .net core web api is **4.0.0-beta.2**

**Comment by kinelski** [comment]
> note: Azure.AI.FormRecoginzer version in .net core web api is **4.0.0-beta.2**

Hello @akmichael. To make sure I understand, the .NET Core Web API uses SDK version `4.0.0-beta.2` and the WinForms API uses `4.0.0-beta.3`. Is that correct?

**Comment by akmichael** [comment]
Hi @kinelski,

yes, correct. web api uses 4.0 beta.2. I dont find beta.3 for webcore.

**Comment by kinelski** [comment]
> yes, correct. web api uses 4.0 beta.2. I dont find beta.3 for webcore.

This explains the difference you're seeing. SDK version 4.0.0-beta.2 targets version `2021-09-30-preview` of the service, while SDK version 4.0.0-beta.3 targets `2022-01-30-preview`.

It's unexpected that you're not finding beta.3 for the web API. Have you tried updating your csproj file directly to include beta.3?

**Comment by akmichael** [comment]
@kinelski, I tried installing beta-3.  but I get error, discussed in this thread.

https://github.com/Azure/azure-functions-host/issues/7248

**Comment by kinelski** [comment]
@akmichael, I see. Unfortunately, this is not an error caused by the SDK nor the Form Recognizer service, so you may need to wait on https://github.com/Azure/azure-functions-host/issues/7248 getting addressed. The difference you're seeing is caused by using two different versions of the service, and the newest version is already producing the expected output as you pointed out.

While you can't update, you could rollback the SDK version used by the WinForms app to `4.0.0-beta.2`. This ensures that both apps will behave in the same way, but you'll still have to handle with the invoice parsing bug. You also won't be able to use the features introduced in `4.0.0-beta.3` in your WinForms app ([changelog here](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/formrecognizer/Azure.AI.FormRecognizer/CHANGELOG.md#400-beta3-2022-02-10) for more details).

Please let me know if you have further questions.

**Comment by akmichael** [comment]
thanks @kinelski. I will use beta-2 in both for now.
