### ISSUE TITLE
Updating from 4.2.1 to 5.1.0 introduces issue with MessageReceiver

### ISSUE THREAD

**Issue by jenp-jb** [Azure/azure-sdk-for-net#27968]
Upgrading the extension nuget package from 4.2.1 to 5.1.0 resulted in IMessageReceiver and MessageReceiver in my function / class becoming unknown.  I use this in order to be able to Complete and Deadletter messages according to our logic as some failures will never succeed so there's no point retrying.

I tried to fix this by installing the deprecated Microsoft.Azure.ServiceBus nuget package 5.2.0.  This allows for the code to be compiled but running the function  gives me the error:
Microsoft.Azure.WebJobs.Host: Error indexing method 'XXX'. Microsoft.Azure.WebJobs.Host: Can't bind parameter 'messageReceiver' to type 'Microsoft.Azure.ServiceBus.Core.MessageReceiver'.

![image](https://user-images.githubusercontent.com/77314668/142129935-f00a73b7-640f-48fc-9a5e-8ca05b164b42.png)

The reason I use IMessageReceiver is for moq unit test purposes so I can assert that a message was completed/deadlettered as expected.

![image](https://user-images.githubusercontent.com/77314668/142130014-56491db2-92ec-45d2-9c3a-9bb7aa398374.png)

Whilst there is documentation on how to instantiate a MessageReceiver - I can't seem to find any reference to accessing it within the ServiceBusTriggered Function.

It doesn't seem like MessageReceiver is part of the newer Azure.Messaging.ServiceBus package as I explored using that as well.

**Comment by jsquire** [comment]
Hi @jenp-jb.   Thank you for reaching out and we regret that you're experiencing difficulties.  Starting in v5.0, the Service Bus extensions package shifted to using the `Azure.Messaging.ServiceBus` client library, which necessitated a change in some types and patterns used.   

For message settlement, you'll want to bind to `ServiceBusMessageActions` rather than a receiver.  An example and additional context is available in the [Message settelment](https://docs.microsoft.com/dotnet/api/overview/azure/microsoft.azure.webjobs.extensions.servicebus-readme-pre#message-settlement) of the package overview.
