### ISSUE TITLE
Search SDK: SearchParameters.ToString() reverse?

### ISSUE THREAD

**Issue by viktor-morin** [Azure/azure-sdk-for-net#2797]
Hi,

Thanks for all support.
I was wondering if its possible to reverse SeachParameters.ToString() and use that query again?

**I have been trying following:**
``
var query = SeachParameters.ToString();
``

``
var results = await indexClient.Documents.SearchAsync(query);
``
``
var results = await indexClient.Documents.SearchAsync(query, new SearchParameters { QueryType = QueryType.Full });
``
``
var results = await indexClient.Documents.SearchAsync("*", new SearchParameters { Filter = query });
``

First one result similar but not exactly the same result, for example is all fields included which isnt wanted.
Is there anyway to do this? Otherwise I would have to save SearchParameters as a JSON string and deserialize the entire object.

Looks however that i get corrent result when i use the query in Search explorer (Azure Portal)

**Comment by brjohnstmsft** [comment]
@viktor-morin `SearchParameters.ToString` isn't meant to be used directly. It is implemented so that a `SearchParameters` instance can be converted to a URL query string, but that is only used when the `SearchAsync` method is configured to use HTTP GET instead of POST (it uses POST by default, which we recommend).

The first parameter to `SearchAsync` is the same as the `search` parameter you would use in the REST API or Search Explorer. For example, if you execute this query in search explorer:

`search=description:jacket&$filter=price lt 100&queryType=full`

You can achieve the same thing in .NET with this code:

```csharp
var results = await indexClient.Documents.SearchAsync("description:jacket", new SearchParameters { QueryType = QueryType.Full, Filter = "price lt 100" });
```

Please let me know if that clarifies things.

**Comment by viktor-morin** [comment]
Okay, understand!
So in my case I guess the best way is to save it as a JSON string and deserialize it back to a `SearchParameters` object since we set alot of properties. There isn't a "smart" way to convert `SearchParameters.ToString()` back to `SearchParameters` by try figure out which part of the string should be used as the query string and rest as parameters for `SearchParameters` object

**Comment by brjohnstmsft** [comment]
There's something about your scenario that I'm not understanding. Are you just looking for a way to safely persist `SearchParameters` instances? If so, why?

**Comment by viktor-morin** [comment]
@brjohnstmsft I worked wound it so it isnt longer an issue. However to explain the situation. We build up a `SearchParameters` object depending on user interactions and our own selections and then using that to get our results from Azure Search. Since many of these search are the same, we would like to save the complete query as a key, the results as value and store it in our cache. Thats how we are using it today.

However, we with my question we tried to (and have) implemeted so when one of the results is affected in the search we throw away that cachekey since its invalid. But instead of letting the user perform the new search I tried to use the key, in this case the compete query, make a new search and update the prepopulate the value. This case would the user never actaully wait for the search, always just go to the cache.

We solved it in another way, but I still think it would be a good feature that you could save your query as a string and use it again 👍 Have a great weekend!

**Comment by brjohnstmsft** [comment]
@viktor-morin Thanks for the details. It's always interesting to learn how people are building solutions with the SDK. :)

You didn't mention whether the cache in your scenario is in-memory or out-of-process. If in-memory, you could always cache the `SearchParameters` object alongside the results so you could use it again later. If it's a remote cache, I'd recommend defining your own persistence format for `SearchParameters`. It's much safer from a backwards compatibility perspective because you explicitly control the versioning. If you rely on the results of serializing SDK model classes, you may be caught by surprise if those classes change in a future version of the SDK.

Anyway, glad you got it working! Closing this issue.
