### ISSUE TITLE
ServiceBusTrigger continously logs warnings about "The operation did not complete within the allocated time 00:01:00 for object receiverNNN"

### ISSUE THREAD

**Issue by marnilss** [Azure/azure-sdk-for-net#27976]
We have a Function App running in Azure, with a ServiceBusTrigger configured.
And while it is running, twice every minute, it will log a warning for:
```
RunOperation encountered an exception and will retry. Exception: Azure.Messaging.ServiceBus.ServiceBusException: The operation did not complete within the allocated time 00:01:00 for object receiver596. (ServiceTimeout)
 ---> System.TimeoutException: The operation did not complete within the allocated time 00:01:00 for object receiver596.
   at Microsoft.Azure.Amqp.AsyncResult.End[TAsyncResult](IAsyncResult result)
   at Microsoft.Azure.Amqp.AmqpObject.OpenAsyncResult.End(IAsyncResult result)
   at Microsoft.Azure.Amqp.AmqpObject.EndOpen(IAsyncResult result)
   at Microsoft.Azure.Amqp.AmqpObject.<>c.<OpenAsync>b__51_1(IAsyncResult r)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location ---
   at Azure.Messaging.ServiceBus.Amqp.AmqpConnectionScope.OpenAmqpObjectAsync(AmqpObject target, TimeSpan timeout, CancellationToken cancellationToken, String entityPath)
   at Azure.Messaging.ServiceBus.Amqp.AmqpConnectionScope.OpenReceiverLinkAsync(String identifier, String entityPath, TimeSpan timeout, UInt32 prefetchCount, ServiceBusReceiveMode receiveMode, String sessionId, Boolean isSessionReceiver, CancellationToken cancellationToken)
   at Azure.Messaging.ServiceBus.Amqp.AmqpReceiver.OpenReceiverLinkAsync(TimeSpan timeout, UInt32 prefetchCount, ServiceBusReceiveMode receiveMode, String identifier, CancellationToken cancellationToken)
   at Microsoft.Azure.Amqp.FaultTolerantAmqpObject`1.OnCreateAsync(TimeSpan timeout)
   at Microsoft.Azure.Amqp.Singleton`1.GetOrCreateAsync(TimeSpan timeout)
   at Microsoft.Azure.Amqp.Singleton`1.GetOrCreateAsync(TimeSpan timeout)
   at Azure.Messaging.ServiceBus.Amqp.AmqpReceiver.<>c.<<OpenLinkAsync>b__72_0>d.MoveNext()
--- End of stack trace from previous location ---
   at Azure.Messaging.ServiceBus.ServiceBusRetryPolicy.RunOperation[T1,TResult](Func`4 operation, T1 t1, TransportConnectionScope scope, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
```
Category: Azure.Messaging.ServiceBus
LogLevel: Warning
EventName: RunOperationExceptionEncountered

I spent about 1 working-day troubleshooting this, until I realized it is actually fully functional, and I guess the behavior is part of the intented implementation. BUT logging this with loglevel warning should not be done then.

Nuget packages:
Microsoft.Azure.WebJobs.Extensions.ServiceBus, 5.2.0
Microsoft.NET.Sdk.Functions, 4.0.1

**Comment by jsquire** [comment]
//cc: @JoshLove-msft

**Comment by Archomeda** [comment]
I'm seeing the same errors here as well, also using a session based queue.

**Comment by JoshLove-msft** [comment]
These should be logged as Informational or Verbose when using the processor, which corresponds to single dispatch functions. Ideally, the same would be true for multiple dispatch functions, but it is trickier in that case because the function extension uses the ServiceBusSessionReceiver which correctly logs these exceptions as errors.

**Comment by fandrusi** [comment]
What are you talking about? can you explain at an 'easier level'...  why is it a information/verbose in one situation and a legit error in another?

I think the problem is, including a massive exception call stack being included when it's just "information", most developers are going to see that and assume it's a problem and burn time trying to figure it out.

**Comment by JoshLove-msft** [comment]
> What are you talking about? can you explain at an 'easier level'... why is it a information/verbose in one situation and a legit error in another?
> 
> I think the problem is, including a massive exception call stack being included when it's just "information", most developers are going to see that and assume it's a problem and burn time trying to figure it out.

When using Functions, I think it should always be information/verbose. The problem is that this behavior can only be changed inside the SDK as that is where the logging happens. If someone is using the Service Bus SDK directly, and they are trying to accept sessions using ServiceBusClient.AcceptNextSessionAsync, the SDK throws an exception if there are no sessions available. Because of this behavior, it seems appropriate that this would be logged as an error when using the SDK. If using the ServiceBusProcessor in the SDK, then it is fair to change this from an error to information/verbose, because these errors do not ever get raised to the user.

**Comment by JoshLove-msft** [comment]
I just realized that this issue is about the Warning that is logged for retries rather than about the Error logged for exceptions. I think it is reasonable to say that retries should always be logged as informational rather than warning.

**Comment by JoshLove-msft** [comment]
Submitted https://github.com/Azure/azure-sdk-for-net/pull/28270

**Comment by marnilss** [comment]
@JoshLove-msft, Now I'm getting into details here, but I put it out there and you can ignore it if you don't agree:

I usually like to have my log settings to write all informational, and more serious, to my logs. But I have seen that with the Functions SDK/Framework/Host a lot of "noise" is then written to the log. Things that I myself would have classified as "Trace" or "Debug" level log messages.
In this case: something happens, it is by design and fully intentional, AND happens every minute - should that be considered of "Informational" log level? I don't think so - I think it is just an implementation detail and should be either Trace or Debug log level.

Since there are 2 of these messages for every BlobTrigger function, every minute, and we have ~10 of these - that is 864 000 of these log messages per month!

Your own definition:
> Logs that track the general flow of the application. These logs should have long-term value.

from https://docs.microsoft.com/en-us/azure/azure-functions/configure-monitoring?msclkid=46fd565fc06c11ecaf69608b1789989d&tabs=v2#configure-log-levels  
Has it really any "long-term value" that the app behaves exactly as intended?

**Comment by danielabbatt** [comment]
@JoshLove-msft  I totally agree that these messages should be at the Debug level. I don't want to have to filter out this namespace specifically at the Informational level as there may be other messages that I do want to log. As no action can be performed by the developer to change whether or not these messages would appear, I see them as diagnostic and part of normal correct operation rather than something which should be logged with such frequency.

**Comment by fandrusi** [comment]
Daniel, I couldn't have said it any better.  The decision to leave this in at information level is disappointing.  It becomes more information you never want to see.  I'd love to see this go to Verbose/Trace with an option not to see the Exception call stack.  It's incredibly annoying.

**Comment by JoshLove-msft** [comment]
> @JoshLove-msft I totally agree that these messages should be at the Debug level. I don't want to have to filter out this namespace specifically at the Informational level as there may be other messages that I do want to log. As no action can be performed by the developer to change whether or not these messages would appear, I see them as diagnostic and part of normal correct operation rather than something which should be logged with such frequency.

I would agree that for this specific retriable error, logging as verbose would be sufficient. In general, I think retries for exceptions that are not expected during the normal application flow should be Informational. I will take a look and see what we can do to improve this.

**Comment by johankson** [comment]
We are also seeing these a lot. It doesn't seem to impact performance or functionality but it's very annoying. 

There seems to have been code merged to main (https://github.com/Azure/azure-sdk-for-net/pull/28302) at the 25th of April. Is this code released into a nuget package or is it still awaiting release?

<img width="511" alt="image" src="https://user-images.githubusercontent.com/1113636/192248246-90559403-98ca-4d0b-9138-cd89a24265eb.png">

**Comment by JoshLove-msft** [comment]
@johankson the fix was to reduce the severity of this log message. Are you seeing this logged as Verbose?
