### ISSUE TITLE
Are there additional diagnostics for dead-lettering that we can log?

### ISSUE THREAD

**Issue by brettsam** [Azure/azure-sdk-for-net#27971]
We occasionally get customer-reported incidents that indicate that a message has been dead-lettered, yet we show no indication that the message was handled by Functions. We should work with the SB SDK team to see if there are additional diagnostic events we can listen for and log so we can better track these scenarios down.

**Comment by jsquire** [comment]
This issue is centered around a version of the extensions package using the legacy Service Bus client library.   Since this time, the package has been updated to make use of the current generation Service Bus library.   To date, there have not been reports of this behavior with the new package, closing this out.
