### ISSUE TITLE
[BUG] AzurePowerShellCredential cannot find Powershell

### ISSUE THREAD

**Issue by yunxzhan** [Azure/azure-sdk-for-net#28030]
### Library name and version

Azure.Identity 1.6.0

### Describe the bug

Using AzurePowerShellCredential to get token while getting error saying I have not installed the Powershell.

CredentialUnavailableException
PowerShell is not installed.

Having powershell 5.1 installed and azure powershell installed in machine.

```
PS C:\Users\YUNXZHAN> $host.Version

Major  Minor  Build  Revision
-----  -----  -----  --------
5      1      22000  593
```

### Expected behavior

N/A

### Actual behavior

N/A

### Reproduction Steps

```
AzurePowerShellCredential environmentCredential = new AzurePowerShellCredential();
accessToken = await environmentCredential.GetTokenAsync(new TokenRequestContext(new string[] { authority + "/.default" }), cancellationToken).ConfigureAwait(false);
```

### Environment

target .netstandard 2.0

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by emmanuelbenitez** [comment]
I have the same issue.  I debug the code and i found more details about the bug.

The method `GetTokenImplAsync` (code [here](https://github.com/Azure/azure-sdk-for-net/blob/efade6aecf56490d57b2da59f47e38a3332862b7/sdk/identity/Azure.Identity/src/Credentials/AzurePowerShellCredential.cs#L94)) of the class `Azure.Identity.AzurePowerShellCredential ` try to execute the script based on the PowerShell Core. If the executable `pwsh` does not exist or is not found, the script is executed based on the PowerShell Framework.

The bug is coming from the expected exception when PowerShell Core is not installed.

Expected exception:
```csharp
try
{
    // Unrelevant code
}
catch (Win32Exception ex) when (ex.NativeErrorCode == ERROR_FILE_NOT_FOUND && RuntimeInformation.IsOSPlatform(OSPlatform.Windows))
{
    UseLegacyPowerShell = true;
    try
    {
        AccessToken token = await RequestAzurePowerShellAccessTokenAsync(async, requestContext, cancellationToken).ConfigureAwait(false);

        if (_logAccountDetails)
        {
            AzureIdentityEventSource.Singleton.AuthenticatedAccountDetails(null, _tenantId, null, null);
        }

        return scope.Succeeded(token);
    }
    catch (Exception e)
    {
        throw scope.FailWrapAndThrow(e);
    }
}
```

Actual Exception:
```
'pwsh' is not recognized as an internal or external command, operable program or batch file.

   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() in f:\dd\ndp\clr\src\BCL\system\runtime\exceptionservices\exceptionservicescommon.cs:line 133
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) in f:\dd\ndp\clr\src\BCL\system\runtime\compilerservices\TaskAwaiter.cs:line 156
   at Azure.Identity.ProcessRunner.Run() in /_/sdk/identity/Azure.Identity/src/ProcessRunner.cs:line 65
   at Azure.Identity.AzurePowerShellCredential.<RequestAzurePowerShellAccessTokenAsync>d__26.MoveNext() in /_/sdk/identity/Azure.Identity/src/AzurePowerShellCredential.cs:line 140
```

As workaround, the installation of  PowerShell core fix the issue.
