### ISSUE TITLE
[BUG] the AddAzureStorage extension of IWebJobsBuilder doesn't exist in Microsoft.Azure.WebJobs.Extensions.Storage 5.0.0

### ISSUE THREAD

**Issue by KayMKM** [Azure/azure-sdk-for-net#28075]
### Library name and version

Microsoft.Azure.WebJobs.Extensions.Storage 5.0.0

### Describe the bug

We are using Microsoft.Azure.WebJobs.Extensions.Storage v4.0.4 and using this function in `StorageWebJobsBuilderExtensions` class:
`public static IWebJobsBuilder AddAzureStorage(this IWebJobsBuilder builder, Action<QueuesOptions> configureQueues = null, Action<BlobsOptions> configureBlobs = null);`
But after we upgraded the package to 5.0.0. The function seems to be removed. How can I use the function `AddAzureStorage()` with the latest pacakge?

### Expected behavior

I can use the AddAzureStorage()

### Actual behavior

can't find AddAzureStorage() in new package

### Reproduction Steps

```
var builder = new HostBuilder();
builder.ConfigureWebJobs(b =>
{
    b.AddAzureStorage();
});
```

### Environment

Windows 11 .NET Framework 4.8
Visual Studio 2019 16.11.11

**Comment by SaurabhSharma-MSFT** [comment]
@KayMKM We are looking into it and get back to you for any additional information.

**Comment by PramodValavala-MSFT** [comment]
@KayMKM There is no `AddAzureStorage` method since the package is just [a combination of the extension for blobs and queues](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/storage/Microsoft.Azure.WebJobs.Extensions.Storage/src/Microsoft.Azure.WebJobs.Extensions.Storage.csproj#L13). So instead you have [`AddAzureStorageBlobs`](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/storage/Microsoft.Azure.WebJobs.Extensions.Storage.Blobs/src/StorageBlobsWebJobsBuilderExtensions.cs#L30) and [`AddAzureStorageQueues`](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/storage/Microsoft.Azure.WebJobs.Extensions.Storage.Queues/src/StorageQueuesWebJobsBuilderExtensions.cs#L29) methods that you can use.

**Comment by KayMKM** [comment]
@PramodValavala-MSFT Thanks for your reply. I want confirm two questions:
1. Previously we were using `b.AddAzureStorage();` and now we should use `b.AddAzureStorageBlobs().AddAzureStorageQueues();` instead right?
2. If we have set one of parameter of it, like `b.AddAzureStorage(queueOptions)`. We should use `b.AddAzureStorageQueues()` or `b.AddAzureStorageQueues().b.AddAzureStorageBlobs()`?

**Comment by PramodValavala-MSFT** [comment]
@KayMKM They are both independent of each other, so you would call both or either one depending on your scenario. The answers to your queries would be

1. If you are using both blobs and queues, then yes. Otherwise, just use the one you need.
2. If you are using just one, then just the one would be added.

**Comment by PramodValavala-MSFT** [comment]
@KayMKM Hope that helps! Since there is no bug here, closing this issue.
