### ISSUE TITLE
Cannot get full list of Virtual Machines

### ISSUE THREAD

**Issue by mxcolin** [Azure/azure-sdk-for-net#2811]
When I try to get a list of Virtual Machines it just returns the first VM and then nothing after that.

```
AzureCredentials credentials = AzureCredentials.FromServicePrincipal(this.Credentials.ClientID, this.Credentials.ClientSecret, this.Credentials.TenantID, AzureEnvironment.AzureGlobalCloud);

IAzure azure = azure.Configure().Authenticate(credentials).WithSubscription(this.Credentials.SubscriptionID);

foreach (IVirtualMachine vm in azure.VirtualMachines.List())
{
	// This loop runs once although I have 3 Virtual Machines
}
```

Additionally `azure.ResourceGroups.List()` never returns.

**Comment by hovsepm** [comment]
@mxcolin please make sure you have all the 3 VMs under the same Service Principal Subscription that you use in the List method. A good way to double-check it is to run Azure PS or Xplat CLI cmdlets and make check the output. e.g.
```
#Azure PowerShell
Login-AzureRmAccount
Select-AzureRmSubscription -SubscriptionId <Your Subscription ID>
Get-AzureRmVM
```

**Comment by mxcolin** [comment]
I have 1 single subscription. The method I am using "FromServicePrincipal" asks for 3 ID's which I get from the subscription and the Application I have registered. I have 3 VM's of which 1 is in WestUS and 2 are in WestUS2. It only lists the one in WestUS and NOT the ones in WestUS2.

Your suggested PowerShell script fails with

Get-AzureRmVM : Run Login-AzureRmAccount to login.
At line:3 char:1
+ Get-AzureRmVM -Status
+ ~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Get-AzureRmVM], PSInvalidOperationException
    + FullyQualifiedErrorId : InvalidOperation,Microsoft.Azure.Commands.Compute.GetAzureVMCommand

**Comment by mxcolin** [comment]
I have no clue how to associate a Virtual Machine with a service principal. I created an Enterprise Application in the Active Directory section so I could use the 3 ID's for this method, but there is no mention of service principals there or in any properties for a Virtual Machine.

**Comment by martinsawicki** [comment]
has it been verified that all 3 VMs are in the same subscription?  (note this is a different question from "how many subscriptions you have", it is about "how many subscriptions do you have access to". If your login credentials have access to multiple subscriptions and the VMs are spread across them, then only the VMs in the subscription the Azure client is authenticated for would be returned.

Also, another possibility is: how were these VMs created? If the two that are not listed are "Classic" then that'd be by design, as classic VMs are not accessible to ResourceManager-based API that the SDK supports exclusively.

**Comment by hovsepm** [comment]
This issue was moved to Azure/azure-libraries-for-net#62
