### ISSUE TITLE
Poor error reporting by ResourceManagementClient

### ISSUE THREAD

**Issue by troshko111** [Azure/azure-sdk-for-net#2819]
```
 IPage<GenericResource> page = await resourceManagementClient
     .Resources
     .ListAsync(new ODataQuery<GenericResourceFilter>(filter => filter.Tagname == "name" && filter.Tagvalue.Contains("vm-49154")));
```

Gives

> Microsoft.Rest.Azure.CloudException: Invalid $filter 'tagname eq 'name' and tagvalue/any(c: c eq 'vm-49154')' specified in the query string.

*What exactly* was invalid in that filter? Saying "invalid filter" and dumping entire filter in this case is like throwing an Exception saying "error"

**Comment by markcowl** [comment]
@ravbhatnagar please take a look

**Comment by adewaleo** [comment]
@ravbhatnagar  @markcowl has this been addressed? We have a similar [issue](https://github.com/Azure/azure-cli/issues/7674) in the CLI. 
It seems like specifying tags and other parameters in a filter fails. But specifying a filter alone works. If this is a bug, will it be fixed? If this is not a bug, can it be documented somewhere (and in the error response) that this is the expected behavior?
 
I can easily add a work around in the CLI to do two-step filtering. However, I would like to know the progress on this first, before making any changes.
