### ISSUE TITLE
Event hub get partition id from key

### ISSUE THREAD

**Issue by srivathsanvlb** [Azure/azure-sdk-for-net#28206]
### Library name and version

Azure.Messaging.EventHubs 5.6.2

### Query/Question

I have two questions

1. While sending events to an event hub I am doing the below

```csharp
           var producer = new EventHubProducerClient(connectionString, eventHubName);

            try
            {
                var batchOptions = new CreateBatchOptions
                {
                    PartitionKey = "PartitionKeyName"
                };

                using EventDataBatch eventBatch = await producer.CreateBatchAsync(batchOptions);

                for (var index = 0; index < 5; ++index)
                {
                    var eventData = new EventData($"Event #{ index }");

                    if (!eventBatch.TryAdd(eventData))
                    {
                        throw new Exception($"The event at { index } could not be added.");
                    }
                }

                await producer.SendAsync(eventBatch);
            }
```

While receiving, I need to receive from the same partition that I used for sending

```csharp
                await foreach (PartitionEvent partitionEvent in consumer.ReadEventsFromPartitionAsync(
                    partitionId,
                    startingPosition,
                    cancellationSource.Token));
```

The second parameter needs the partitionid. Is there a way I can get partition id from the partition key (which I used for sending)?

2. I need to create a consumer group dynamically. I found an answer in the link below. 

https://github.com/Azure/azure-event-hubs/blob/master/samples/Management/DotNet/EventHubsManagementSample/EventHubsManagementSample.cs

But it needs client id, client secret, tenant id and subscription id. Can't I create a consumer group using the Azure.Messaging.EventHubs or some other library using the connection string of the event hub?

### Environment

.NET 6 console app running in a Windows 10 machine.

**Comment by jsquire** [comment]
Hi @srivathsanvlb.   Thank you for reaching out and we regret that you're experiencing difficulties.   To answer your questions:

**1)** There is no supported way to translate a partition key into a partition identifier.   Partition keys are intended to help you group events together when you don't have a need to control the partition that they're assigned to.   If your application needs awareness of the partition, you'll want your application to assign it and publish to that partition directly.  Note that this does come with some trade-offs around availability.   The [Mapping of events to partitions](https://docs.microsoft.com/azure/event-hubs/event-hubs-features#mapping-of-events-to-partitions) section of the Event Hubs docs has more context.

For consuming events, if you do not have a specific application need to read from a single and specific partition, we'd recommend considering the `EventProcessorClient`.  This would allow you to read from all partitions of your Event Hub in a highly resilient manner, manage data about what events have been read to avoid unintentional reprocessing share the load for doing so with other nodes.   More information can be found in the [overview](https://docs.microsoft.com/dotnet/api/overview/azure/messaging.eventhubs.processor-readme?view=azure-dotnet) documentation.

**2)** Creating of consumer groups is an ARM operation that belongs to the Azure management plane, which intentionally requires a different set of permissions to promote good security practices.  More context can be found in the [Azure control plane and data plane](https://docs.microsoft.com/azure/azure-resource-manager/management/control-plane-and-data-plane) documentation.

Because the operation exists in the management plane, the Event Hubs client library cannot interact with it.   To do so, we'd recommend using one of the management libraries, either [Azure.ResourceManager.EventHubs](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/eventhub/Azure.ResourceManager.EventHubs/README.md) _(currently in beta)_ or [Microsoft.Azure.Management.EventHub](https://www.nuget.org/packages/Microsoft.Azure.Management.EventHub/), which your sample references.

It is possible to use the legacy Event Hubs REST API directly to perform management operations, including creation of consumer groups, with a SAS token, but there is no library support offered for it.   More information can be found in the [Entity Management REST API](https://docs.microsoft.com/rest/api/eventhub/event-hubs-management-rest) documentation.

**Comment by srivathsanvlb** [comment]
Thank you @jsquire for the quick turn around.
