### ISSUE TITLE
[QUERY] Move samples from track 1 SDK to track 2 SDK

### ISSUE THREAD

**Issue by EldertGrootenboer** [Azure/azure-sdk-for-net#28215]
### Library name and version

Azure.Messaging.ServiceBus

### Query/Question

There are a lot of samples for the [track 1 SDK](https://github.com/Azure/azure-service-bus/tree/master/samples/DotNet/Microsoft.Azure.ServiceBus) which are not available for the [track 2 SDK](https://docs.microsoft.com/en-us/samples/azure/azure-sdk-for-net/azuremessagingservicebus-samples/).
We should convert these, as it will help customers getting onboarded easier on the new SDK.
Below an overview of all the samples, if they have an equivelant in the track 2 samples, and if not, my opinion on priority.

| Track 1                                                                                                                                                                                | Track 2                                                                                                                                                                          | Priority |
| -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | -------- |
| [TopicFilters](https://github.com/Azure/azure-service-bus/tree/master/samples/DotNet/Microsoft.Azure.ServiceBus/TopicFilters "TopicFilters")                                           |                                                                                                                                                                                  | 0        |
| [TransactionsAndSendVia](https://github.com/Azure/azure-service-bus/tree/master/samples/DotNet/Microsoft.Azure.ServiceBus/TransactionsAndSendVia "TransactionsAndSendVia")             |                                                                                                                                                                                  | 0        |
| [ReceiveLoop](https://github.com/Azure/azure-service-bus/tree/master/samples/DotNet/Microsoft.Azure.ServiceBus/ReceiveLoop "ReceiveLoop")                                              |                                                                                                                                                                                  | 1        |
| [RoleBasedAccessControl](https://github.com/Azure/azure-service-bus/tree/master/samples/DotNet/Microsoft.Azure.ServiceBus/RoleBasedAccessControl "RoleBasedAccessControl")             |                                                                                                                                                                                  | 1        |
| [SendersReceiversWithTopics](https://github.com/Azure/azure-service-bus/tree/master/samples/DotNet/Microsoft.Azure.ServiceBus/SendersReceiversWithTopics "SendersReceiversWithTopics") |                                                                                                                                                                                  | 1        |
| [TopicsGettingStarted](https://github.com/Azure/azure-service-bus/tree/master/samples/DotNet/Microsoft.Azure.ServiceBus/TopicsGettingStarted "TopicsGettingStarted")                   |                                                                                                                                                                                  | 1        |
| [AutoForward](https://github.com/Azure/azure-service-bus/tree/master/samples/DotNet/Microsoft.Azure.ServiceBus/AutoForward "AutoForward")                                              |                                                                                                                                                                                  | 2        |
| [DuplicateDetection](https://github.com/Azure/azure-service-bus/tree/master/samples/DotNet/Microsoft.Azure.ServiceBus/DuplicateDetection "DuplicateDetection")                         |                                                                                                                                                                                  | 2        |
| [GeoReplication](https://github.com/Azure/azure-service-bus/tree/master/samples/DotNet/Microsoft.Azure.ServiceBus/GeoReplication "GeoReplication")                                     |                                                                                                                                                                                  | 2        |
| [PartitionedQueues](https://github.com/Azure/azure-service-bus/tree/master/samples/DotNet/Microsoft.Azure.ServiceBus/PartitionedQueues "PartitionedQueues")                            |                                                                                                                                                                                  | 2        |
| [Prefetch](https://github.com/Azure/azure-service-bus/tree/master/samples/DotNet/Microsoft.Azure.ServiceBus/Prefetch "Prefetch")                                                       |                                                                                                                                                                                  | 2        |
| [QueuesRequestResponse](https://github.com/Azure/azure-service-bus/tree/master/samples/DotNet/Microsoft.Azure.ServiceBus/QueuesRequestResponse "QueuesRequestResponse")                |                                                                                                                                                                                  | 2        |
| [TimeToLive](https://github.com/Azure/azure-service-bus/tree/master/samples/DotNet/Microsoft.Azure.ServiceBus/TimeToLive "TimeToLive")                                                 |                                                                                                                                                                                  | 2        |
| [DurableSender](https://github.com/Azure/azure-service-bus/tree/master/samples/DotNet/Microsoft.Azure.ServiceBus/DurableSender "DurableSender")                                        |                                                                                                                                                                                  | 3        |
| [PrioritySubscriptions](https://github.com/Azure/azure-service-bus/tree/master/samples/DotNet/Microsoft.Azure.ServiceBus/PrioritySubscriptions "PrioritySubscriptions")                |                                                                                                                                                                                  | 3        |
| [SessionState](https://github.com/Azure/azure-service-bus/tree/master/samples/DotNet/Microsoft.Azure.ServiceBus/SessionState "SessionState")                                           |                                                                                                                                                                                  | 3        |
| [DeadletterQueue](https://github.com/Azure/azure-service-bus/tree/master/samples/DotNet/Microsoft.Azure.ServiceBus/DeadletterQueue "DeadletterQueue")                                  | [Settling Messages](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/servicebus/Azure.Messaging.ServiceBus/samples/Sample02_MessageSettlement.md)                        |          |
| [Deferral](https://github.com/Azure/azure-service-bus/tree/master/samples/DotNet/Microsoft.Azure.ServiceBus/Deferral "Deferral")                                                       | [Settling Messages](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/servicebus/Azure.Messaging.ServiceBus/samples/Sample02_MessageSettlement.md)                        |          |
| [ManagingEntities](https://github.com/Azure/azure-service-bus/tree/master/samples/DotNet/Microsoft.Azure.ServiceBus/ManagingEntities "ManagingEntities")                               | [CRUD Operations](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/servicebus/Azure.Messaging.ServiceBus/samples/Sample07_CrudOperations.md)                             |          |
| [MessageBrowse](https://github.com/Azure/azure-service-bus/tree/master/samples/DotNet/Microsoft.Azure.ServiceBus/MessageBrowse "MessageBrowse")                                        | [Sending and Receiving Messages](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/servicebus/Azure.Messaging.ServiceBus/samples/Sample01_HelloWorld.md)                  |          |
| [QueuesGettingStarted](https://github.com/Azure/azure-service-bus/tree/master/samples/DotNet/Microsoft.Azure.ServiceBus/QueuesGettingStarted "QueuesGettingStarted")                   | [Sending and Receiving Messages](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/servicebus/Azure.Messaging.ServiceBus/samples/Sample01_HelloWorld.md)                  |          |
| [ScheduledMessages](https://github.com/Azure/azure-service-bus/tree/master/samples/DotNet/Microsoft.Azure.ServiceBus/ScheduledMessages "ScheduledMessages")                            | [Sending and Receiving Messages](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/servicebus/Azure.Messaging.ServiceBus/samples/Sample01_HelloWorld.md)                  |          |
| [SendersReceiversWithQueues](https://github.com/Azure/azure-service-bus/tree/master/samples/DotNet/Microsoft.Azure.ServiceBus/SendersReceiversWithQueues "SendersReceiversWithQueues") | [Sending and Receiving Messages](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/servicebus/Azure.Messaging.ServiceBus/samples/Sample01_HelloWorld.md)                  |          |
| [Sessions](https://github.com/Azure/azure-service-bus/tree/master/samples/DotNet/Microsoft.Azure.ServiceBus/Sessions "Sessions")                                                       | [Sending and Receiving Session Messages](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/servicebus/Azure.Messaging.ServiceBus/samples/Sample03_SendReceiveSessions.md) |          |

**Comment by JoshLove-msft** [comment]
TopicFilters was migrated already - https://github.com/Azure/azure-sdk-for-net/tree/main/sdk/servicebus/Azure.Messaging.ServiceBus/samples/TopicFilters

As was DeadLetterQueue - https://github.com/Azure/azure-sdk-for-net/tree/main/sdk/servicebus/Azure.Messaging.ServiceBus/samples/DeadLetterQueue

**Comment by JoshLove-msft** [comment]
@EldertGrootenboer, we've gone through the samples listed and think they fall roughly into three buckets: 
- A feature of the service that is exposed via the data-plane operations. The user has to do something with the data-plane types to use the feature.
- A feature of the service that can be configured with the admin client, but once configured, it will just work and the samples merely demonstrate that the feature is working.
- A general messaging pattern that is demonstrated with the library

We think that all of the samples that fall into the first bucket belong in the samples and possibly README of the library in this repo. For the second bucket, it makes sense to have more extensive samples involving all of the configuration options via the admin client, but the actual samples that prove that the feature works would probably be better suited in the Azure-Samples repo along with other Azure samples. For the third bucket, we think these can go in the Azure-Samples repo as well. Please let us know if you have any thoughts or concerns with the plan!

Here is the breakdown:

| Track 1                                                                                                                                                                                | Track 2                                                                                                                                                                          | Priority |
| -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | -------- |
| [TopicFilters](https://github.com/Azure/azure-service-bus/tree/master/samples/DotNet/Microsoft.Azure.ServiceBus/TopicFilters "TopicFilters")                                           |[TopicFilters](https://github.com/Azure/azure-sdk-for-net/tree/main/sdk/servicebus/Azure.Messaging.ServiceBus/samples/TopicFilters)                                                                                                                                                                                 | 0        |
| [TransactionsAndSendVia](https://github.com/Azure/azure-service-bus/tree/master/samples/DotNet/Microsoft.Azure.ServiceBus/TransactionsAndSendVia "TransactionsAndSendVia")             | [Transactions](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/servicebus/Azure.Messaging.ServiceBus/samples/Sample06_Transactions.md)                                                                                                                                                                                 | 0        |
| [ReceiveLoop](https://github.com/Azure/azure-service-bus/tree/master/samples/DotNet/Microsoft.Azure.ServiceBus/ReceiveLoop "ReceiveLoop")                                              | Since this isn't the recommended usage, this could be treated as a more advanced pattern and live in the samples repo.                                                                                                                                                                                | 1        |
| [RoleBasedAccessControl](https://github.com/Azure/azure-service-bus/tree/master/samples/DotNet/Microsoft.Azure.ServiceBus/RoleBasedAccessControl "RoleBasedAccessControl")             | [Using Azure.Identity](https://github.com/Azure/azure-sdk-for-net/tree/main/sdk/servicebus/Azure.Messaging.ServiceBus#authenticating-with-azureidentity)                                                                                                                                                                                 | 1        |
| [SendersReceiversWithTopics](https://github.com/Azure/azure-service-bus/tree/master/samples/DotNet/Microsoft.Azure.ServiceBus/SendersReceiversWithTopics "SendersReceiversWithTopics") | We should add a version of Sending/Receiving using topics/subscriptions to this repo.                                                                                                                                                                                | 1        |
| [TopicsGettingStarted](https://github.com/Azure/azure-service-bus/tree/master/samples/DotNet/Microsoft.Azure.ServiceBus/TopicsGettingStarted "TopicsGettingStarted")                   | This would be the same as SendersReceiversWithTopics for T2, since we don't have the Topic/SubscriptionClients anymore                                                                                                                                                                                 | 1        |
| [AutoForward](https://github.com/Azure/azure-service-bus/tree/master/samples/DotNet/Microsoft.Azure.ServiceBus/AutoForward "AutoForward")                                              | This is a pattern that could be demonstrated in the samples repo                                                                                                                                                                                 | 2        |
| [DuplicateDetection](https://github.com/Azure/azure-service-bus/tree/master/samples/DotNet/Microsoft.Azure.ServiceBus/DuplicateDetection "DuplicateDetection")                         |This is is essentially proving that the service feature works - it can live in the samples repo.                                                                                                                                                                                | 2        |
| [GeoReplication](https://github.com/Azure/azure-service-bus/tree/master/samples/DotNet/Microsoft.Azure.ServiceBus/GeoReplication "GeoReplication")                                     | This is a pattern that could be demonstrated in the samples repo.                                                                                                                                                                                 | 2        |
| [PartitionedQueues](https://github.com/Azure/azure-service-bus/tree/master/samples/DotNet/Microsoft.Azure.ServiceBus/PartitionedQueues "PartitionedQueues")                            | This demonstrates how partitioned queues work. It could be added to samples repo.                                                                                                                                                                                 | 2        |
| [Prefetch](https://github.com/Azure/azure-service-bus/tree/master/samples/DotNet/Microsoft.Azure.ServiceBus/Prefetch "Prefetch")                                                       | This should be added as part of a configuration sample to the repo.                                                                                                                                                                                 | 2        |
| [QueuesRequestResponse](https://github.com/Azure/azure-service-bus/tree/master/samples/DotNet/Microsoft.Azure.ServiceBus/QueuesRequestResponse "QueuesRequestResponse")                | This is a messaging pattern that can be added to samples repo.                                                                                                                                                                                 | 2        |
| [TimeToLive](https://github.com/Azure/azure-service-bus/tree/master/samples/DotNet/Microsoft.Azure.ServiceBus/TimeToLive "TimeToLive")                                                 | This could be added as part of one of the sender samples to this repo.                                                                                                                                                                                | 2        |
| [DurableSender](https://github.com/Azure/azure-service-bus/tree/master/samples/DotNet/Microsoft.Azure.ServiceBus/DurableSender "DurableSender")                                        | Messaging pattern that can be demonstrated in samples repo.                                                                                                                                                                                 | 3        |
| [PrioritySubscriptions](https://github.com/Azure/azure-service-bus/tree/master/samples/DotNet/Microsoft.Azure.ServiceBus/PrioritySubscriptions "PrioritySubscriptions")                | Messaging pattern that can be demonstrated in samples repo.                                                                                                                                                                                 | 3        |
| [SessionState](https://github.com/Azure/azure-service-bus/tree/master/samples/DotNet/Microsoft.Azure.ServiceBus/SessionState "SessionState")                                           | Library feature that should be included in sample.                                                                                                                                                                                 | 3        |
| [DeadletterQueue](https://github.com/Azure/azure-service-bus/tree/master/samples/DotNet/Microsoft.Azure.ServiceBus/DeadletterQueue "DeadletterQueue")                                  | [DeadLetterQueue](https://github.com/Azure/azure-sdk-for-net/tree/main/sdk/servicebus/Azure.Messaging.ServiceBus/samples/DeadLetterQueue)                        |          |
| [Deferral](https://github.com/Azure/azure-service-bus/tree/master/samples/DotNet/Microsoft.Azure.ServiceBus/Deferral "Deferral")                                                       | [Settling Messages](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/servicebus/Azure.Messaging.ServiceBus/samples/Sample02_MessageSettlement.md)                        |          |
| [ManagingEntities](https://github.com/Azure/azure-service-bus/tree/master/samples/DotNet/Microsoft.Azure.ServiceBus/ManagingEntities "ManagingEntities")                               | [CRUD Operations](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/servicebus/Azure.Messaging.ServiceBus/samples/Sample07_CrudOperations.md)                             |          |
| [MessageBrowse](https://github.com/Azure/azure-service-bus/tree/master/samples/DotNet/Microsoft.Azure.ServiceBus/MessageBrowse "MessageBrowse")                                        | [Sending and Receiving Messages](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/servicebus/Azure.Messaging.ServiceBus/samples/Sample01_HelloWorld.md)                  |          |
| [QueuesGettingStarted](https://github.com/Azure/azure-service-bus/tree/master/samples/DotNet/Microsoft.Azure.ServiceBus/QueuesGettingStarted "QueuesGettingStarted")                   | [Sending and Receiving Messages](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/servicebus/Azure.Messaging.ServiceBus/samples/Sample01_HelloWorld.md)                  |          |
| [ScheduledMessages](https://github.com/Azure/azure-service-bus/tree/master/samples/DotNet/Microsoft.Azure.ServiceBus/ScheduledMessages "ScheduledMessages")                            | [Sending and Receiving Messages](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/servicebus/Azure.Messaging.ServiceBus/samples/Sample01_HelloWorld.md)                  |          |
| [SendersReceiversWithQueues](https://github.com/Azure/azure-service-bus/tree/master/samples/DotNet/Microsoft.Azure.ServiceBus/SendersReceiversWithQueues "SendersReceiversWithQueues") | [Sending and Receiving Messages](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/servicebus/Azure.Messaging.ServiceBus/samples/Sample01_HelloWorld.md)                  |          |
| [Sessions](https://github.com/Azure/azure-service-bus/tree/master/samples/DotNet/Microsoft.Azure.ServiceBus/Sessions "Sessions")                                                       | [Sending and Receiving Session Messages](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/servicebus/Azure.Messaging.ServiceBus/samples/Sample03_SendReceiveSessions.md) |          |

**Comment by JoshLove-msft** [comment]
Another sample that we should include in the repo - handling non-Data message bodies.

**Comment by JoshLove-msft** [comment]
## SDK Scenarios
These samples should live somewhere in the language repo. Not all of these belong in the main README, but they should at least be covered in a sample.

- Constructing ServiceBusClient with the various auth forms - connection string, TokenCredential, NamedKeyCredential
- Sending and receiving from a queue
- Sending and receiving with a topic/subscription
- Settling messages
- Scheduling messages
- Setting TimeToLive on a message
- Peeking messages
- Using sessions - accept next session, accept specific, set/get session state
- Using the Admin client
- Configuring prefetch
- Using the processor

**Comment by JoshLove-msft** [comment]
All that is remaining is samples for NamedKeyCredential/SasCredential.
