### ISSUE TITLE
Cognitive - Form Recognizer - Prebuilt invoice OCR Service includes tables in next pages which are not relevant

### ISSUE THREAD

**Issue by akmichael** [Azure/azure-sdk-for-net#28217]
Cognitive - Form Recognizer, Azure.AI.FormRecognizer API 4.0.0-beta.3

**Issue 1**

actual invoice line items exists in the first page, other pages having the details or other informations as table format. but Prebuilt invoice api includes them in items result.  Is it a bug in api? how do i exclude invalid items?

**actual invoice line items**

<img width="615" alt="Screenshot 2022-04-15 at 12 50 33 PM" src="https://user-images.githubusercontent.com/8349884/163539817-07d554a6-94fc-43a5-921d-2d77020bc85c.png">

**extra details in second page**

<img width="578" alt="Screenshot 2022-04-15 at 12 53 00 PM" src="https://user-images.githubusercontent.com/8349884/163539935-02684860-981b-449e-a334-09c5f3323b52.png">

**prebuilt invoice lines list**
<img width="517" alt="Screenshot 2022-04-15 at 12 50 13 PM" src="https://user-images.githubusercontent.com/8349884/163539990-5ace68e5-41dd-48be-a8e7-d4537fb00c85.png">

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by akmichael** [comment]
In another customer invoice, invoice lines items are in 4 pages. first 2 page items  are considered by both Prebuilt invoice api and general document api. 3,4 skipped.

using prebuilt api
![image](https://user-images.githubusercontent.com/8349884/164217777-7dfec220-fc40-4831-b461-e8c93e220516.png)

4th page.
![image](https://user-images.githubusercontent.com/8349884/164218789-72ddb308-356b-4ba0-b23b-901d4ef73170.png)

----------------------------------------
general document api also recognise only tables from first, second pages. 3,4 not recognised.
![image](https://user-images.githubusercontent.com/8349884/164218477-050810fc-87e0-49dd-b2b0-774f09c33ea8.png)

**Comment by akmichael** [comment]
**issue 3:** 

2 invoices from same supplier have email id in the page footer. Invoice format is same for both the invoices. first invoice have 1 page, 2nd invoice have 5 pages with many invoice lines.

General document api identifies email from only one invoice.

**Comment by kinelski** [comment]
@ctstone @vkurpad Could you take a look?

**Comment by akmichael** [comment]
@kinelski any update?

**Comment by kinelski** [comment]
@ctstone @vkurpad Could you confirm if the scenarios the customer is describing are supported by the service? They're trying to extract invoice items from multi-page documents using the `prebuilt-invoice` model, but data extraction does not seems to be consistent. Service version is `2022-01-30-preview`.

**Comment by akmichael** [comment]
@kinelski , @ctstone , @vkurpad , also in other invoice,  invoice items available in 4 pages. invoice items from first 2 pages are read by api, next 2 page are missed by prebuilt-invoice and general document api.

**Comment by akmichael** [comment]
@kinelski, @ctstone , @vkurpad, gentle reminder. kindly provide some details. Without these fixes we can't proceed official release of our app.

**Comment by anatolip** [comment]
@akmichael, thanks for detailed report.
1. You are correct, current prebuilt invoice model does not differentiate between "summary" line items and "detailed" line items. They should be separated using some post processing logic (i.e. exclude "summary" line items from the first page). Different customers may need different level of details, that's why Form Recognizer team decided to return both of them at this moment.
2. Are you using "Free Tier" Form Recognizer resource? It looks like you are because "Free Tier" resource limits processing to only first 2 pages of PDF.
3. Is there some OCR errors in the email address on the first page? Extra spaces, some words are merged, @ character is not recognized, etc?

A few additional information, in case, it maybe helpful for your scenarios:
1. Have you tried "receipt" API which currently support hotel receipt (one of your samples, looks like hotel receipt)?
2. Are you aware there is "pages" API parameter for all Form Recognizer APIs which can limit processing to only specific pages?

**Comment by akmichael** [comment]
thanks It helps.
