### ISSUE TITLE
EVenthub Trigger Extension: Query about the ReceiveTimeOut and maxBatchSize

### ISSUE THREAD

**Issue by rkbalu** [Azure/azure-sdk-for-net#28243]
Hello Everyone,

We have been using the EVentHubTrigger Azure function to read the events from the EventHub. As part of this function, we are trying to implement some level of batching to the downstream by purely updating the host.json maxBatchSize property.

My understanding is that the EventHub Trigger function will wait to execute either each partition has more than the message count mentioned in the maxBatchSize or wait for ReceiveTimeOut exceeds(which is defaulted to 1 min with in the extension or Eventhub sdk).

But by look of it, function being triggered without honoring either of it. It's being triggered as soon as 1 message added to the EH.

Is there anyway we could delay trigger the EH trigger function to allow having some reasonable amount(i.e. minBatchSize) of message available in EH in first place?

Versions:
Azure Function V2(Consumption plan)
Microsoft.Azure.WebJobs.Extensions.EventHubs - 3.0.0

Perhaps it was related to Eventhub extension we use.

Any suggestion here would help us.

thanks!

**Comment by jsquire** [comment]
> My understanding is that the EventHub Trigger function will wait to execute either each partition has more than the message count mentioned in the maxBatchSize or wait for ReceiveTimeOut exceeds(which is defaulted to 1 min with in the extension or Eventhub sdk)

This isn't quite correct.  The Event Hubs client will wait up to the configured timeout (default: 60 seconds) for events to become available and return up to the `maxBatchSize`.   However, it will dispatch events as soon as any are available; it does not attempt to build a batch of the requested size.  

There is an open issue tracking a "minimum batch size" feature for v5+ of the extensions, [#19518](https://github.com/Azure/azure-sdk-for-net/issues/19518).  I'm going to link this in that issue and close as a duplicate so that we have a single tracking item.
