### ISSUE TITLE
[BUG] TextAnalytics BuildSnippets is failing

### ISSUE THREAD

**Issue by nisha-bhatia** [Azure/azure-sdk-for-net#28325]
### Library name and version

TextAnalytics

### Describe the bug

https://dev.azure.com/azure-sdk/public/_build/results?buildId=1518760&view=logs&j=b70e5e73-bbb6-5567-0939-8415943fadb9&t=9069f0a2-bd31-51b1-8b5c-08355cf80229&s=6884a131-87da-5381-61f3-d7acc3b91d76

BuildSnippets on my local Powershell passes, but doesn't seem to build in the Azure Pipelines

### Expected behavior

Build Snippets compiles successfully

### Actual behavior

Pipeline fails

### Reproduction Steps

Failing pipeline can be seen here: https://dev.azure.com/azure-sdk/public/_build/results?buildId=1518760&view=logs&j=b70e5e73-bbb6-5567-0939-8415943fadb9&t=9069f0a2-bd31-51b1-8b5c-08355cf80229&s=6884a131-87da-5381-61f3-d7acc3b91d76

**Comment by nisha-bhatia** [comment]
@chidozieononiwu please take a look :)

**Comment by maririos** [comment]
I keep looking into this and still have no idea why this is happening. @chidozieononiwu  any pointer will be great :)

**Comment by chidozieononiwu** [comment]
This is because there seems to be duplicates of these files not tracked, I got passed it by adding a `git clean` between the steps.
https://dev.azure.com/azure-sdk/public/_build/results?buildId=1525000&view=logs&j=b70e5e73-bbb6-5567-0939-8415943fadb9&t=d34cfe88-f3e1-5ca1-ec50-18a5cea1099a
No I need to find out why the previous step dumps those files

**Comment by maririos** [comment]
@chidozieononiwu do you have an update on this? is there a way we can help?

**Comment by maririos** [comment]
Fixed in PR https://github.com/Azure/azure-sdk-for-net/pull/28512
