### ISSUE TITLE
Figure out error story for LRO operations

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-for-net#28356]
Currently, the SDK doesn't support `Partiallysuccedded` result for the `StartAnalyzeActions` method because there is no way for us to know which tasks/actions failed. The service is looking into this.

**Comment by maririos** [comment]
https://dev.azure.com/msazure/Cognitive%20Services/_workitems/edit/14337635/

**Comment by heaths** [comment]
Talking with @deyaaeldeen and @kristapratico we're not currently handling this across languages because it's believed to be a short-term problem that the service team monitors carefully. This would effectively represent HTTP 500s for individual tasks. Any issues like HTTP 400 BadRequest would be returned immediately from the POST request.

That said, there is talk of adding support with task pointers like:

> The structure of the JSON pointer differs slightly between the two, since the shape of the API has evolved with the addition of the Language API. For example, error targets for TA will be of the form #/tasks/<tasksObject>/<index>, and error targets for the Language API will be of the form #/tasks/items/<index>.

**Comment by heaths** [comment]
Be sure to clean up any non-obvious locations like in our model factory. See https://github.com/Azure/azure-sdk-for-net/pull/30071#discussion_r927972509

**Comment by heaths** [comment]
This was effectively fixed in #30436. We don't explicitly support `PartiallyCompleted` and will instead throw, which is congruent with Java that has a similar API model for us, which has results in separate per-type collections where a JSON pointer wouldn't effectively match anyway. The other languages aren't doing anything in this space currently. The service is exploring options, however, so we can reopen this one or create a new one if/when we cross that bridge.
