### ISSUE TITLE
Verify what happens when user passes a jobId that is not a GUID to AnalyzeActionsOperation

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-for-net#28355]
We didn't have validation for this in 3.1 but Language API requires it. What is the error user experience? Would this be considered a breaking change?

**Comment by maririos** [comment]
Happens => https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/textanalytics/Azure.AI.TextAnalytics/src/ServiceClients/LanguageServiceClient.cs#L1534

**Comment by heaths** [comment]
We generally try not to - and shouldn't, based on current [guidelines](https://azure.github.io/azure-sdk/general_implementation.html#parameter-validation) - do client-side validation except when necessary for path parameters. We do check if `operationId` is null or empty.

That said, what happens in the client is less than ideal and doesn't even get sent to the service:
```
Unhandled exception: System.ArgumentException: Invalid value. Please use the AnalyzeActionsOperation.Id property value. (Parameter 'operationId')
 ---> System.Text.Json.JsonException: 'j' is an invalid start of a value. Path: $ | LineNumber: 0 | BytePositionInLine: 0.
 ---> System.Text.Json.JsonReaderException: 'j' is an invalid start of a value. LineNumber: 0 | BytePositionInLine: 0.
   at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)
   at System.Text.Json.Utf8JsonReader.ConsumeValue(Byte marker)
   at System.Text.Json.Utf8JsonReader.ReadFirstToken(Byte first)
   at System.Text.Json.Utf8JsonReader.ReadSingleSegment()
   at System.Text.Json.Utf8JsonReader.Read()
   at System.Text.Json.JsonSerializer.ReadCore(JsonSerializerOptions options, Utf8JsonReader& reader, ReadStack& readStack)
   --- End of inner exception stack trace ---
```
This is because it goes through an internal `OperationContinuationToken` class to de/serialize a base64 value. For the stack above I simply passed "asdf", which emits `["j", 0x6a, 0xdd]` hence the "j" in the error message.

**Comment by heaths** [comment]
Also, since there were no permalinks I can only assume this is about https://github.com/Azure/azure-sdk-for-net/blob/e811f016a3655e4b29a23c71f84d59f34fe01233/sdk/textanalytics/Azure.AI.TextAnalytics/src/ServiceClients/LanguageServiceClient.cs#L1547-L1550 and https://github.com/Azure/azure-sdk-for-net/blob/e811f016a3655e4b29a23c71f84d59f34fe01233/sdk/textanalytics/Azure.AI.TextAnalytics/src/ServiceClients/LanguageServiceClient.cs#L1453-L1456. I'm not sure why we're parsing these as GUIDs, since that's client-side validation and we should let the service throw.

**Comment by heaths** [comment]
Looking at `OperationContinuationToken`, I'm not sure what is going on here. Not only is it storing a separate stringified "latest version" of the API version (which isn't even later), but it does a simple string comparison which won't last the test of time. Will need to talk with the original author...

**Comment by heaths** [comment]
Even when the user does pass a GUID, the exception is the same. Turns out this has to be a continuation token with the service version, whether to show stats, and document ordering all baked in with the operation ID.

**Comment by heaths** [comment]
After discussion, I opened a tracking bug to see if languages should align on a format, but we know what happens here - `ArgumentException` - which is sufficient. We don't expect users to supply arbitrary values, and I added some comments to help clarify that, as well as source comments to clarify that the API version was used arbitrarily, which I found confusing when first reviewing this code since it has nothing to do with the service API version. The continuation token is entirely invented for the SDK, though each language does it a little differently. As such, I'm resolving this one since we know what the impact is. If you disagree with the resolution, please reopen and clarify the intent when you opened this bug.
