### ISSUE TITLE
Multiple consumer instances from a same Azure Event Hub partition, avoid duplicates using checkpointing

### ISSUE THREAD

**Issue by srivathsanvlb** [Azure/azure-sdk-for-net#28367]
### Library name and version

Azure.Messaging.EventHubs 5.6.2

### Query/Question

I see in the Azure Event Hub documentation that "There can be at most 5 concurrent readers on a partition per consumer group" also "if you have multiple readers on the same partition, then you process duplicate messages".
I also read several articles; they all recommend to have only one reader per partition per consumer group.

We have a scenario in which producers push events to partitions based on a partition key/id. We have several such producers each pushing messages to its partition. We have a single consumer group and several consumers in it in which each reader reads from a partition using partition id.  Sometimes, more events gets pushed in a particular partition due to the increase of input generated by the producer sending to that partition. During this scenario we are planning to increase the number of the instances of the consumer of that particular partition alone. But the consumer instances should not end up receiving the same events. 

Is there a way/sample in which consumers of the same partition can receive unique events (probably each consumer creating a checkpoint for the other, or something of that fashion). I read [this](https://docs.microsoft.com/en-us/azure/event-hubs/event-processor-balance-partition-load) and also other related threads, but our scenario is different I guess. Kindly provide your thoughts.

**Comment by jsquire** [comment]
Hi @srivathsanvlb.  Thank you for reaching out and sharing your scenario.   If I understand correctly, what you'd like is to have consumers share the work of processing a single partition, with each consumer having a filtered view.   Unfortunately, that is not something supported by Event Hubs.   As an event stream, each partition has a persistent set of data that can be read in a forward-only manner by any consumer; events are not removed from the stream when read nor can they be filtered.  

At a high level, it sounds like your scenario is better suited for Service Bus than Event Hubs.  Service Bus would allow you to have competing consumers and allow messages to be locked/completed with the intent of having them processed by a single consumer.  It also allows for filtering and creating a unique view over messages (subscriptions) so that you can have different groups of consumers each with a unique copy of messages.

If you're set on using Event Hubs, your application will need to own responsibility for guarding against duplicates and an approach to having a consumer be able to understand which events from the partition it should process, and which are "owned" by another consumer.   Generally, the pattern we see for similar scenarios is to have a single consumer for the partition which dispatches events to be processed elsewhere rather than having responsibility for reading and processing.

**Comment by srivathsanvlb** [comment]
Thanks @jsquire
