### ISSUE TITLE
[QUERY] Azure function upgrade from .NET Core 3.1 to .NET 6 for service bus triggered function

### ISSUE THREAD

**Issue by JD-4810** [Azure/azure-sdk-for-net#28373]
### Library name and version

Microsoft.Azure.WebJobs.Extensions.ServiceBus 4.3.0

### Query/Question

I upgraded a service bus triggered Azure function running inside a Kubernetes cluster to v4 and .NET6. Post that, the function stopped processing messages from the service bus. I see no logs whatsoever. 
Initially, I thought it could be that the package Microsoft.Azure.WebJobs.Extensions.ServiceBus version 4.3.0 might not be supported in .NET 6 but then I ran a newly created Azure function in .NET 6 and v4 locally with Microsoft.Azure.WebJobs.Extensions.ServiceBus 4.3.0 and it hit the breakpoint on sending a message to the Service bus. 

### Environment

Kubernetes cluster version 1.21.7

**Comment by jsquire** [comment]
Hi @JD-4810.   Thank you for reaching out and we regret that you're experiencing difficulties.  Because you're using an older version of the extension, I've transferred this to the repository where versions prior to v5 of `Microsoft.Azure.WebJobs.Extensions.ServiceBus` are maintained as [#188](https://github.com/Azure/azure-functions-servicebus-extension/issues/188).
