### ISSUE TITLE
[BUG] Cannot get SQL databases

### ISSUE THREAD

**Issue by lukipro** [Azure/azure-sdk-for-net#28387]
### Library name and version

Azure.ResourceManager.Sql 1.0.0-beta.4

### Describe the bug

Following code:
```
await foreach (SqlDatabaseResource resource in sqlServer.GetSqlDatabases().GetAllAsync())
{
    Console.WriteLine("SQL db: " + resource);
}
```
results with a InvalidOperationException:
```
The requested operation requires an element of type 'Number', but the target element has type 'String'.
```

### Expected behavior

Databases are listed

### Actual behavior

Exception is thrown

### Reproduction Steps

Just run this code:
```
try
{
     var subscription = subscriptions.Get(subscriptionId).Value;
     await foreach (var resource in subscription.GetResourceGroups().GetAllAsync())
     {
         Console.WriteLine("RG: " + resource.Data.Name);
     }

     var resourceGroup = subscription.GetResourceGroup(rgName).Value;
     await foreach (var resource in resourceGroup.GetSqlServers().GetAllAsync())
     {
         Console.WriteLine("SQL server: " + resource.Data.Name);
     }

    var sqlServer = resourceGroup.GetSqlServer(serverName).Value;
    await foreach (var resource in sqlServer.GetElasticPools().GetAllAsync())
    {
        Console.WriteLine("SQL ep: " + resource.Data.Name);
    }
    await foreach (SqlDatabaseResource resource in sqlServer.GetSqlDatabases().GetAllAsync())
    {
        Console.WriteLine("SQL db: " + resource);
    }
}
catch (InvalidOperationException e)
{
    Console.WriteLine(e.Message);
}
```

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by ArthurMa1978** [comment]
@fengzhou-msft please check this issue

**Comment by fengzhou-msft** [comment]
I have reproduced the issue locally and the root cause seems to be [JsonDocument.ParseAsync()](https://github.com/Azure/azure-sdk-for-net/blob/47043a7c772ffa12b8fe493cef51af9a4beca850/sdk/sqlmanagement/Azure.ResourceManager.Sql/src/Generated/RestOperations/DatabasesRestOperations.cs#L261) converts the number from the response like `"maxSizeBytes": 53687091200` to be a string element while it should be a number and the error occurs at [property0.Value.GetInt64()](https://github.com/Azure/azure-sdk-for-net/blob/47043a7c772ffa12b8fe493cef51af9a4beca850/sdk/sqlmanagement/Azure.ResourceManager.Sql/src/Generated/Models/SqlDatabaseData.Serialization.cs#L294) where we assume Value is a number instead of a string. I will investigate why  `JsonDocument.ParseAsync()` behaves in this way and try to come up with a fix.

**Comment by fengzhou-msft** [comment]
Further invetigation shows that `maxSizeBytes` is defined as integer in [swagger](https://github.com/Azure/azure-rest-api-specs/blob/4946dbb5b2893a77ce52d08e2a855056e1acd361/specification/sql/resource-manager/Microsoft.Sql/preview/2021-02-01-preview/Databases.json#L828), but service returns `"maxSizeBytes": "53687091200"` instead of `"maxSizeBytes": 53687091200`. Therefore, the value is parsed as string. We'll contact service team to see how to fix it properly.

**Comment by fengzhou-msft** [comment]
The fix will be released in the next monthly beta version.

**Comment by zhiweiv** [comment]
1.0.0-beta.5 works now.

**Comment by lukipro** [comment]
Thanks a lot. When can we expect 1.0.0 in GA?

**Comment by fengzhou-msft** [comment]
> Thanks a lot. When can we expect 1.0.0 in GA?

We're working on GAing batch 2 SDKs. Sql is in batch 3. It would probably take 2-3 months, before summer ends.
