### ISSUE TITLE
[BUG] Every class of formrecogonizer has internal constructor and requires parameters

### ISSUE THREAD

**Issue by waynebrantley** [Azure/azure-sdk-for-net#28421]
### Library name and version

Azure.AI.FormRecognizer 3.1.1

### Describe the bug

I recognize a form and get back a the results.
I would like to serialize to JSON and save the results out.

Later, I would like to load these results back into classes.

As it is written, ever constructor is listed as internal and as such I cannot create proper json objects (or deserialize them back).
And if they were internal, I still need default constructors (that do not take arguments).

As it is, we have had to recreate every class that is just like the classes you have already created because you did not provide a default public constructor.   Here is an example of one of your classes https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/formrecognizer/Azure.AI.FormRecognizer/src/FormRecognizerClient/FormField.cs

Would it be possible to change this?

### Expected behavior

Be able to easily save/restore the results of form recognition.

### Actual behavior

Will not allow it

### Reproduction Steps

Simply try to save/restore the results out to json 

### Environment

dotnet 6, vs2022

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by kinelski** [comment]
Hello @waynebrantley,

This is similar to https://github.com/Azure/azure-sdk-for-net/issues/28972, so I'm including my reply here as well:

<hr/>

Hiding the public constructors of models is a design choice. Unfortunately the .NET SDK has not been designed with (de)serialization in mind, specially because we would need to come up with a cross-version compatibility strategy. Creating a proxy class is the recommended way of achieving your goal, as you suggested. During deserialization, you can also use our `FormRecognizerModelFactory` static class to instantiate our models, but I agree it's still very inconvenient.

Serialization support is a request the Form Recognizer SDK received a lot in the last months and, if possible, we would like to support it, but it's still not part of our roadmap. I'll keep this issue open for now since the feedback can prove to be useful if we decide to implement this feature in the future.

**Comment by pallavit** [comment]
Serialization support is something we are tracking separately and hopefully should be implemented in the near future. I would recommend tagging this issue as addressed.

/cc: @kinelski please let me know if you think otherwise.
