### ISSUE TITLE
ShareDirectoryClient.CreateFileAsync() with MaxSize creates Files with maximum size in Fileshare

### ISSUE THREAD

**Issue by greatvivek11** [Azure/azure-sdk-for-net#28573]
### Library name and version

Azure.Storage.Files.Shares v12.10.0

### Describe the bug

When creating a file in fileshare with ShareDirectoryClient.CreateFileAsync(fileName,maxSize) creates an empty file with size of maxSize.
*maxSize is in long bytes C#.

[https://docs.microsoft.com/en-us/dotnet/api/azure.storage.files.shares.sharedirectoryclient.createfileasync?view=azure-dotnet]

### Expected behavior

ShareDirectoryClient.CreateFileAsync(fileName,maxSize) should create an empty file with very small (~10bytes) size?

### Actual behavior

ShareDirectoryClient.CreateFileAsync(fileName,maxSize) creates an empty file with actual maxSize.

### Reproduction Steps

ShareDirectoryClient.CreateFileAsync(fileName,maxSize) in c#.

Sorry this occurred at work, so I can't share the code but the steps are very simple. Try uploading any file with maxSize of 1 million bytes(~100Mb).

### Environment

OS - Windows 10
.NET version - 6.0
IDE - VS 2022 17.1.3

**Comment by PramodValavala-MSFT** [comment]
@greatvivek11 Thanks for the feedback! We will review and update accordingly.

**Comment by PramodValavala-MSFT** [comment]
@greatvivek11 This method translates to [this underlying API](https://docs.microsoft.com/en-us/rest/api/storageservices/create-file) and this is the expected behavior. Depending on premium or standard, you [either provision the storage or set it as the quota](https://docs.microsoft.com/en-us/azure/storage/files/understanding-billing#provisionedquota-logical-size-and-physical-size) respectively.
