### ISSUE TITLE
[FEATURE REQ] [EventsHubs Extension] Do not checkpoint in case of Functions host exception

### ISSUE THREAD

**Issue by RohitRanjanMS** [Azure/azure-sdk-for-net#28653]
### Library name

Microsoft Azure WebJobs SDK EventHubs Extension

### Please describe the feature.

We always checkpoint irrespective of the outcome of the Functions execution.  

"[When all function execution completes (with or without errors), checkpoints are added to the associated storage account. When check-pointing succeeds, all 1,000 messages are never retrieved again.](https://docs.microsoft.com/en-us/azure/architecture/serverless/event-hubs-functions/event-hubs-functions#:~:text=When%20all%20function%20execution%20completes%20(with%20or%20without%20errors)%2C%20checkpoints%20are%20added%20to%20the%20associated%20storage%20account.%20When%20check%2Dpointing%20succeeds%2C%20all%201%2C000%20messages%20are%20never%20retrieved%20again)".

Currently, we do not have the ability to differentiate between exception in the customer code vs exception in the Functions host but this [PR](https://github.com/Azure/azure-functions-host/pull/8314) is going to address this. 

Proposal is to skip checkpoint in case of Functions host failure.

**Comment by jsquire** [comment]
//cc: @JoshLove-msft

**Comment by JoshLove-msft** [comment]
Can you clarify what is meant by a function host failure? Would this mean that the customer function is never actually invoked? If that is the assumption, then I would agree that the proposed change makes sense.

**Comment by RohitRanjanMS** [comment]
> 

yes, for example if the language worker fails to initialize, the host will error out and recycle with the following exception.
System.InvalidOperationException : Did not find any initialized language workers

**Comment by JoshLove-msft** [comment]
Can you clarify how the extension will know whether this scenario has occurred? Will there be a new property exposed in the FunctionResult?

**Comment by RohitRanjanMS** [comment]
Once the PR to differentiate between host and customer error is merged, we will have to make the required changes to include this in the FunctionResult.

**Comment by mathewc** [comment]
The referenced PR is specific to OOP/GRPC scenarios. However I think the issue being discussed here is more general. For example, you'll have the same situation in an in-proc csx functions case. Csx functions are demand compiled/loaded, so in the EH case we'll be processing events, dispatching to the invoker, invocations will fail due to compilation error, and we'll checkpoint. Thus, just as in the OOP channel failure case, no user code was actually invoked.

So I think we'll need a general solution that applies to both.

**Comment by paulbatum** [comment]
I suggest being careful about this change, when it comes to defining what constitutes a "host" error. If the error is repeatable, the function app potentially gets stuck, processing the same events over and over again (because the checkpoint is not written). In the consumption plan that bills per execution, this could turn into a very large bill for the customer. These problems are discussed in more detail in these issues:
https://github.com/Azure/azure-functions-host/issues/2439
https://github.com/Azure/azure-webjobs-sdk/issues/1597

We might want to point customers that really want this behavior to the use of retry policies (and fix the [bugs](https://github.com/Azure/azure-webjobs-sdk/issues/2947) where retry policies do not work correctly).

**Comment by JoshLove-msft** [comment]
I think the idea is that we want to NOT checkpoint when the customer function was not given a chance to execute. More details are included here - https://github.com/Azure/azure-functions-host/issues/8994

**Comment by jsquire** [comment]
Agreed, but it would seem better than the unexpected data loss that occurs by checkpointing events that customer code wasn't given an opportunity to process.   Perhaps the better way forward would be some kind of "reject event(s)" method that would force an immediate checkpoint so that those events did not get dispatched for processing again.

**Comment by paulbatum** [comment]
Perhaps a sweet spot between these two extremes would be implementing an implicit exponential backoff retry policy for failures that occur before user code runs?
