### ISSUE TITLE
TiPCallback site url doesn't seem to work

### ISSUE THREAD

**Issue by realrubberduckdev** [Azure/azure-sdk-for-net#28703]
The url provided in documentation [https://www.siteextensions.net/packages/TiPCallback/](https://www.siteextensions.net/packages/TiPCallback/) doesn't work and browser returns

```
can't reach this page

ERR_CONNECTION_TIMED_OUT
```

Is the url correct?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1cc3c70d-7c82-b443-f1ed-1605eb6d9aa6
* Version Independent ID: 8214792d-c971-666a-f764-1169c1341125
* Content: [RampUpRule.ChangeDecisionCallbackUrl Property (Microsoft.Azure.Management.AppService.Fluent.Models) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.management.appservice.fluent.models.rampuprule.changedecisioncallbackurl?view=azure-dotnet)
* Content Source: [xml/Microsoft.Azure.Management.AppService.Fluent.Models/RampUpRule.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.Management.AppService.Fluent.Models/RampUpRule.xml)
* Service: **app-service**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by HarveyLink** [comment]
I believe all site extensions have been moved to Nuget.
Check: https://github.com/Azure/app-service-announcements/issues/87
For the specified extension you mentioned, I found one on Github  [TiPCallback](https://github.com/galiniliev/TiPCallback), if this is the correct repo, you could contact the owner to get it published on Nuget.
Add @weidongxu-microsoft  for confirmation since it is a Fluent SDK.
