### ISSUE TITLE
[QUERY] How to get the raw response header Location when downloading a layer blob from ACR

### ISSUE THREAD

**Issue by mnltejaswini** [Azure/azure-sdk-for-net#28735]
### Library name and version

Azure.Containers.ContainerRegistry 1.1.0-beta.4

### Query/Question

When Get Blob https://docs.microsoft.com/en-us/rest/api/containerregistry/blob/get#response returns 307 status code, is there a way to get the ```Location``` header value that was used to download the blob as part of this workflow

```c#
var repoArtifact = _registryClient.GetArtifact($"{repositoryNamespace}/{imagePath}", tag);

var manifestProperties = await repoArtifact.GetManifestPropertiesAsync();
var manifest = await blobClient.DownloadManifestAsync(new DownloadManifestOptions(digest: manifestProperties.Value.Digest));

var layer = manifest.Value.Manifest.Layers.First();

var layerResult = await blobClient.DownloadBlobAsync(layer.Digest);
var locationExists = raw.Headers.TryGetValue("Location", out var location);
```

Currently the headers doesn't have Location header value. 

### Environment

N/A

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by jsquire** [comment]
//cc: @Mohit-Chakraborty, @annelo-msft

**Comment by pallavit** [comment]
Thank you for reporting the issue @mnltejaswini. I have created an issue that can help us enable this behavior on ACR.

**Comment by pallavit** [comment]
Hi @mnltejaswini in what customer scenario would you use the Location header?

**Comment by mnltejaswini** [comment]
The scenario is when we use ACR as the backend storage for implementing distribution services and when they handle the download of the content. For example, I was trying to implement Terraform private registry API https://www.terraform.io/registry/api-docs#download-source-code-for-a-specific-module-version which expects the response to include a header ```X-Terraform-Get``` that will be used by the Terraform clients to download the terraform repository contents packaged as zip/tar balls 

To implement this API, I used [```oras```](https://oras.land/cli/1_pushing/) to push Terraform repository contents as OCI artifacts into ACR. This will push the tar file as a layer and will create and push a manifest in the ACR. Then, when I implement the private terraform registry API to download the content, I would download the manifest, get the layer blob and return the ```Location``` header as the ```X-Terraform-Get``` in the response to the Terraform registry API.

**Comment by pallavit** [comment]
@mnltejaswini - thank you for the explanation. We currently expose the following API - https://github.com/Azure/azure-sdk-for-net/blob/b283376b83ce293c87008b72ed860dfbb43a0321/sdk/containerregistry/Azure.Containers.ContainerRegistry/src/Blob/ContainerRegistryBlobClient.cs#L465 which returns the blob content as a stream. Our assumption was that in most scenarios the customers would like to use the SDK to download the blob. 

However, if I understand your use case correctly you want to know the location in order to read the blob content at a later time? Can you help me understand in what scenario would customer prefer that over reading the blob content returned by the API? Would they want to read this via the SDK or through other means? I will have to circle back with the service team but my understanding is that GetBlob call also returns the blob content and the customer will be doing an extra read if they only parse the location header and do a read after the fact?

**Comment by annelo-msft** [comment]
The change to Azure.Core [has merged](https://github.com/Azure/azure-sdk-for-net/pull/32810).  I will update this issue when the new version of Azure.Core has shipped.

**Comment by annelo-msft** [comment]
@mnltejaswini, this is now complete.  The following sample illustrates how to obtain the Location header without following the redirect.  This is considered an advanced scenario, so the APIs are relatively advanced.  Feel free to reach out with any questions.

```csharp
ContainerRegistryBlobClient client = new ContainerRegistryBlobClient(endpoint, credential, "<repository>", options);

var message = client.Pipeline.CreateMessage();
message.Request.Method = RequestMethod.Get;
message.Request.Uri.Reset(new Uri(client.Endpoint, "/v2/" + client.RepositoryName + "/blobs/" + digest));
message.Request.Headers.Add("Accept", "application/octet-stream");
RedirectPolicy.SetAllowAutoRedirect(message, false);

await client.Pipeline.SendAsync(message, CancellationToken.None);
var response = message.Response;
response.Headers.TryGetValue("Location", out string location);
```
