### ISSUE TITLE
[Doc]Clarify if/how to use `RequestContext` in a grow-up method when adding DPG to an existing HLC

### ISSUE THREAD

**Issue by heaths** [Azure/azure-sdk-for-net#28815]
<https://github.com/Azure/azure-sdk-for-net/blob/main/doc/DataPlaneCodeGeneration/Add_ProtocolMethods_In_Gen1_Convenience_Client_Generated_SDK.md> has a lot of good information, but could use some clarification in the section about adding DPG to an existing HLC:

1. Whether all methods need to have protocol methods or only some need them.
2. Whether it's okay to have a `RequestContext` in a grow-up looking method. There is actually a code example, but with no clear explanation it **initially** wasn't clear if that was a pure DPG method or not.

**Comment by heaths** [comment]
In my specific use case - #25125 - there are a few methods where I want to give callers more control over how errors are processed since .NET exceptions are pretty expensive.

**Comment by lirenhe** [comment]
@archerzz, could you help to follow up? Thanks

**Comment by pallavit** [comment]
@lirenhe is this guidance documented anywhere?

**Comment by lirenhe** [comment]
@ArcturusZhang, could you take a look at this issue?  thanks

**Comment by ArcturusZhang** [comment]
@heaths @pallavit 
1. it is OK only some methods are shipped with protocol method as long as your library is still generating from swaggers. Once you switch to typespec, the protocol methods are no longer optional, every method must have a protocol method.
2. I assume this question is asking "how to distinguish whether a method is a DPG method?". There is actually no such thing like "DPG method", I myself never heard or used this term. But if a method is generated by DPG generator, and if it is a protocol method, it should accept `RequestContext` instead of `CancellationToken`. But DPG generator also generates convenience methods, which accept `CancellationToken` instead of `RequestContext`. Therefore there is no way to distinguish a generated method. We could only determine that by "whether this method is generated and generated from which generating, using which configuration".

**Comment by heaths** [comment]
@ArcturusZhang take a look at #25125 for context. Basically, what I want clarification on - documented in our guidelines if any change is to be made - is whether we can ship methods that use a `RequestContext` as opposed to a `CancellationToken`. If we're saying a `RequestContext` is better - and it is - then why can't we use that instead? It would actually solve the customer case for that aforementioned issue in a way they control.

At the same time, I want to provide a convenience method that actually returns a known, already-coded model. That is what basically started the contention with @KrzysztofCwalina and @tg-msft that lead to this issue being opened: when should it be okay to use a `RequestContext` for more general purposes.

Personally, most customers probably don't pass a `CancellationToken` anyway so I think debating that vs. `RequestContext` is probably moot.
