### ISSUE TITLE
[BUG] BoundingBox is empty on Json serialization

### ISSUE THREAD

**Issue by ss-proc** [Azure/azure-sdk-for-net#28886]
### Library name and version

Azure.AI.FormRecognizer 4.0.0-beta.3

### Describe the bug

1. recognize a form
```
var formPageCollection = await client.StartRecognizeContentAsync(fileStream).WaitForCompletionAsync().value;
```
2. verify bounding box in debugger
```
BoundingBox = {FieldBoundingBox} {X=0.8039, Y=4.5392},{X=1.9006, Y=4.5437},{X=1.8957, Y=5.168},{X=0.8039, Y=5.1724}
 Points = {PointF[]} PointF[4]
  [0] = {PointF} {X=0.8039, Y=4.5392}
  [1] = {PointF} {X=1.9006, Y=4.5437}
  [2] = {PointF} {X=1.8957, Y=5.168}
  [3] = {PointF} {X=0.8039, Y=5.1724}
```
3. json serialize the `FormPageCollection`
```
await using var saveFileStream = File.Create("result01.json");
await JsonSerializer.SerializeAsync(saveFileStream, results);
```
4. open the serialized json in a text editor
```
{
...
  BoundingBox: {}
...
}
```
5. BUG: all the bounding box objects are empty in the JSON

### Expected behavior

`BoundingBox` should not be empty in the serialized JSON

### Actual behavior

`BoundingBox` is empty in the serialized JSON

### Reproduction Steps

Please see above

### Environment

```
.NET SDK (reflecting any global.json):
 Version:   6.0.203
 Commit:    a20feadf6d

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  12.3
 OS Platform: Darwin
 RID:         osx.12-arm64
 Base Path:   /usr/local/share/dotnet/sdk/6.0.203/

Host (useful for support):
  Version: 6.0.5
  Commit:  70ae3df4a6

.NET SDKs installed:
  6.0.203 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.5 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.5 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
```

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by kinelski** [comment]
Hello @ss-proc,

This has the same underlying cause as issue https://github.com/Azure/azure-sdk-for-net/issues/28972, so I'm including my reply here as well:

<hr/>

Unfortunately the .NET SDK has not been designed with (de)serialization in mind, specially because we would need to come up with a cross-version compatibility strategy. For now we recommend copying the properties into a custom class and serializing it. For deserialization, you can use our `FormRecognizerModelFactory` to instantiate our models since they don't have public constructors.

Serialization support is a request we received a lot in the last months and, if possible, we would like to support it, but it's still not part of our roadmap. I'll keep this issue open for now since the feedback can prove to be useful if we decide to implement this feature in the future.
