### ISSUE TITLE
Only methods returning a `Task<Operation<T>>` are being instrumented automatically

### ISSUE THREAD

**Issue by heaths** [Azure/azure-sdk-for-net#29140]
The `InstrumentResultInterceptor` is only automatically intercepting and proxying methods that return a `Task<Operation<T>>`. This was discovered when async tests were completing in tends of milliseconds, while sync tests were taking seconds. For the Conversations SDK, that triggered the 5s local playback error.

To work around this we can manually instrument, but it'd be nice if this was automatic so we didn't have to condition code to instrument.

**Comment by JoshLove-msft** [comment]
This is specific to SyncOnly tests. Most tests are written as async and will have their operations instrumented [here](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/core/Azure.Core.TestFramework/src/Instrumentation/InstrumentResultInterceptor.cs#L61). The UseSyncMethodsInterceptor runs after this to handle running the sync variant of tests. The operation instrumentation doesn't work for SyncOnly tests because the operation method doesn't return a Task.

**Comment by heaths** [comment]
IIRC, you had a reason why this wouldn't work but I wanted to ask it again here for posterity, but would it not be as easy as switching the order of the interceptors for instrumenting async operations (to bifurcate sync and async) and the one to instrument operations based on method signature?

**Comment by heaths** [comment]
I tried it, and it's not quite so simple as reversing the order. Some changes to the flow and method name calculation in the `UseSyncMethodIntercepter` got me further, but it's clear this is going to require more thought and careful evaluation. I have a scenario where this would be handy, but will just work around this for now by using `WaitUntil.Started` in non-`SNIPPET` code and disable recordings while I wait - perhaps something akin to what @m-nash suggested in Azure/azure-sdk-tools#2703.

**Comment by pallavit** [comment]
@heaths do you think there is value in exploring a solution here?

**Comment by heaths** [comment]
Yes. For sync-only tests that use LROs, we need a way to make sure they are runnable.
