### ISSUE TITLE
[QUERY] incorrect or Increased message DeliveryCount on ReceiveAsync() in dot net core 3.1

### ISSUE THREAD

**Issue by onlywithlad** [Azure/azure-sdk-for-net#29182]
### Library name and version

Microsoft.Azure.ServiceBus 5.1.3

### Query/Question

HI Team,

Message has its own DeliveryCount set to its system properties. But when we are trying to pick the message using ReceiveAsync() method it is giving wrong DeliveryCount in system properties. It is giving higher Count.

We can not use peek method as we want to remove that message from that queue once it is picked.  So once it is received we are using CompleteAsync method.

Package used Microsoft.Azure.ServiceBus 5.1.3
Coding Framework used Dot net core 3.1

Kindly help on the same.

**Comment by PramodValavala-MSFT** [comment]
@onlywithlad The delivery count value is increased when a message's lock is lost or was abandoned. So, in your case if a message was received but not completed in time, it could have had its value increased.

If you are looking to receive a message only once, you can use the [`ReceiveAndDelete`](https://docs.microsoft.com/en-us/azure/service-bus-messaging/message-transfers-locks-settlement#receiveanddelete) mode instead of using the default [`PeekLock`](https://docs.microsoft.com/en-us/azure/service-bus-messaging/message-transfers-locks-settlement#peeklock) mode.

In C#, you can set this mode in the [`ServiceBusReceiverOptions`](https://docs.microsoft.com/en-us/dotnet/api/azure.messaging.servicebus.servicebusreceiveroptions?view=azure-dotnet) object that you can pass when creating a receiver using the [`CreateReceiver`](https://docs.microsoft.com/en-us/dotnet/api/azure.messaging.servicebus.servicebusclient.createreceiver?view=azure-dotnet#azure-messaging-servicebus-servicebusclient-createreceiver(system-string-azure-messaging-servicebus-servicebusreceiveroptions)) method.

**Comment by jsquire** [comment]
@onlywithlad : Given your scenario, the delivery count is working as expected.  The count is a broker-owned property that is specific to a single message.  When you create a copy of that message and publish to a different queue, the delivery count resets.   Your application does not own the delivery count and cannot override the broker behavior.   This is by design and considered the correct behavior.  

If you want to have a delivery count-like property that your application owns and increments, you'll need to do so by adding an Application Property and managing when that gets incremented and when to manually dead letter that message.
