### ISSUE TITLE
Evaluate suppressions of analyzer rule CA1835

### ISSUE THREAD

**Issue by christothes** [Azure/azure-sdk-for-net#29197]
### Library name

Azure.Core

### Please describe the feature.

In a few different areas within Core, [we suppress CA1835 ](https://grep.app/search?q=%23pragma%20warning%20disable%20CA1835&regexp=true&filter[repo][0]=Azure/azure-sdk-for-net&filter[path][0]=sdk/). 

Investigate if these can be eliminated on a per target framework basis.

**Comment by pallavit** [comment]
I have seen a few issues around TFMs in general which I believe we need to look at wholistically especially for the new toolchain.

@christothes if I understand correctly the right solution here would be to have a way to use analyzer per TFM because some rules may not be applicable to all TFMs. CA1835 does not make sense on the frameworks where memory alternative are not available at all. If so, I think our new toolchain should absolutely look at what rules should be supported by the analyzers and which frameworks should support which rules.

/cc: @annelo-msft , @KrzysztofCwalina
