### ISSUE TITLE
Add test coverage for distributed tracing of LROs when nested span suppression is disabled

### ISSUE THREAD

**Issue by annelo-msft** [Azure/azure-sdk-for-net#29215]
@pshao25 identified that distributed tracing spans for LROs are incorrect when nested span suppression is disabled.  Her investigation is described here: https://github.com/Azure/autorest.csharp/issues/2297

Distributed tracing span scopes for LROs are described in the following two issues:
- https://github.com/Azure/autorest.csharp/issues/2136
- https://github.com/Azure/autorest.csharp/issues/2233#issuecomment-1127819652

Test for the LRO distributed tracing spans are currently here: https://github.com/Azure/autorest.csharp/blob/feature/v3/test/AutoRest.TestServerLowLevel.Tests/dpg-customization.cs#L96
Validation of diagnostic scopes should be moved to Azure.Core when the [Operation implementation methods move to Azure.Core](https://github.com/Azure/autorest.csharp/issues/2231).

We should add tests validating correct behavior for all cases:

- User calls LRO method with WaitUntil.Completed
- User calls LRO method with WaitUntil.Started and
    - UpdateStatus
    - WaitForCompletion
    - WaitForCompletionResponse

The above four cases should be validated for each of the following conditions:
- Operation and Operation\<T\>
- Protocol and Convenience methods
- Nested span supression on/off

**Comment by m-redding** [comment]
A set of written tests attempting to add test coverage for distributed tracing is held in https://github.com/Azure/autorest.csharp/pull/2961 

As of now, there doesn't seem to be a clear consensus about what the correct behavior is for each of these test cases from the information gathered in various linked GitHub discussions. In addition, it is unclear if these are tests that should be added across languages to the test server repo (or just .NET). It is also unclear if these cases are important for generated DPG libraries at all, since I was not able to find any real scenarios necessitating these tests in our generated libraries. If one is found though, I'm happy to move forward with the closed PR above.

**Comment by pallavit** [comment]
@m-redding given your investigation can we close this issue for now?
@annelo-msft as FYI.

**Comment by m-redding** [comment]
Yeah I think we should be able to close this.
