### ISSUE TITLE
[BUG]Two instance consume one partition at the same time

### ISSUE THREAD

**Issue by RetYn** [Azure/azure-sdk-for-net#29335]
### Library name and version

Microsoft.Azure.WebJobs.Extensions.EventHubs 5.0.0

### Describe the bug

![image](https://user-images.githubusercontent.com/7384252/174022057-1324c41b-d9b6-44c8-bc43-b086d80952ff.png)
![image](https://user-images.githubusercontent.com/7384252/174022469-2e677917-5064-44c7-a87c-6d6d283f1a35.png)

You can see for the offset 125251-125269, these messages has been consumed by the two different instance 
0752cba4-1700-43c3-96d0-8e30235d4310 and dbe7bca7-abd2-48dc-b7c8-31479129fb8e

### Expected behavior

Each partition should be consumed by one instance

### Actual behavior

Each partition is consumed by two different instance concurrently

### Reproduction Steps

It usually happens when a batch of message is executed overtime

**Comment by jsquire** [comment]
Hi @RetYn.  Thank you for reaching out and we regret that you're experiencing difficulties.  

When Function instances are scaling up/down, they will balance the partition ownership with other active instances for the same consumer group.  In many cases, the new instance needs to steal ownership from other instances in order to reach its fair share.  During this time, the new owner will begin reading from the last recorded checkpoint, rewinding the event stream and causing duplication.  At the same time, the old owner may be dispatching the events that it last read to the handler for processing; it will not understand that ownership has changed until it attempts to read the next set of events from the Event Hubs service.
 
As a result, you will see overlapping events processed for a short period when scaling occurs.  This will subside when a stable state for partition ownership is reached, and the local buffer is drained.  The duration of that window will differ depending on configuration and work done to process events.   

An important call-out is that Event Hubs has an at-least-once delivery guarantee; it is highly recommended that you ensure that your processing is resilient to event duplication in whatever way is appropriate for your application scenarios.

I'm going to mark this as addressed, but please feel free to unresolve if you'd like to discuss further.

**Comment by jsquire** [comment]
When an instance times out, the Functions runtime may or may not choose to spawn a new instance and consider the old one invalid.  In the scenario where it does, you wouldn't see the instance count change, but the old instance may still be running.   The new instance does not have the state from the old; it is a new member of the consumer group and when it claims ownership of a partition, it will start from the last recorded checkpoint.

In your case, the log screenshots that you shared show about a 3 minute difference between the event was processed by the different nodes.  It's possible that a portion of that is clock skew between the hosts, but its spread far enough apart that it makes it very likely that the stream rewound for an ownership change while the old owner was still working through the last batch that it read.

Exclusive access to a partition (within a consumer group) is enforced by Event Hubs at the service level; in the case of a client bug where ownership of a partition was mistakenly assigned twice, the readers would not both be allowed to connect at the same time.   This would manifest in the logs as a series of errors and you'd see the partition unable to make forward progress on any Function instance because two readers were fighting over it.

**Comment by jsquire** [comment]
Since discussion seems to have tapered off, I'm going to mark this as addressed and close it out.   Please feel free to unresolve if you'd like to discuss further.
