### ISSUE TITLE
[BUG] Microsoft.Workloads/SapVirtualInstance RT model and API issues (count = 3)

### ISSUE THREAD

**Issue by gargankit-microsoft** [Azure/azure-sdk-for-net#29355]
### Library name and version

Azure.ResourceManager.Workloads 1.0.0-beta.1 (Unreleased)

#### Issue 1

- Using the .NET SDK, while making a Get call for an SVI, we're getting an Argument Null exception. 
  - System.ArgumentNullException : Value cannot be null. Parameter name: fencingClientPassword
  - Issue is, Fencing Client password should not be required for a GetSVICall as per swagger. 
  - The same payload had been tested with ARMclient, and we got the expected result, without any error for same SVI.
  - Screenshots for all of these attached in comments. 

Screenshot for error from test explorer:
![1a3c3315-e948-470e-a92e-f80b50b1297b](https://user-images.githubusercontent.com/88656868/174255941-98ad7e47-efb1-429c-abf9-4c440e05e78b.png)

Screenshot for test code:
![165873ff-11d2-4828-81db-6c707b3ec0b0](https://user-images.githubusercontent.com/88656868/174255959-f7048b9d-74cb-4192-9876-5154ce4d0f70.png)

Screenshot for ARMclient result for Get call of same resource:
![f0e011b2-7e13-4793-a49a-75ff2e1f39c2](https://user-images.githubusercontent.com/88656868/174255978-a70c55e5-bd6c-4b21-b5f2-63e97ac1267b.png)

#### Issue 2

- Differences in payload between the SDK and Swagger Payload.
  - In create payload, in SDK for subnet ID, the expected structure is:
    `"subnetId": { "resourceId": <subnet resource id> }`
  - However in swagger, the expected format is:
`"subnetId": <subnet resource id>`
  - Screenshot from payload from portal pasted in comment below.

<img width="513" alt="e031016c-6e89-4e54-9a5a-0409e15bbbcd" src="https://user-images.githubusercontent.com/88656868/174256159-1ab3c097-15af-42f1-b4a8-b5bb9721dd21.png">

#### Issue 3

- Differences in payload between the SDK and Swagger payload.
  - For install payload, in the SDK for softwareConfiguration, the bomURL is specified as 
`softwareConfiguration": { "bomUri": <bomurl>,}`
  - While in the payload as defined in Swagger, it is:  
`softwareConfiguration": { "bomUrl": <bomurl>,}`
  - Difference between bomUri and bomUrl.
  - Screenshot from portal payload pasted in comments.
  
<img width="402" alt="2dd9357d-8936-4088-b620-5544a403bbd2" src="https://user-images.githubusercontent.com/88656868/174256183-cc2b858a-94db-4667-ae85-a1b6d174af1f.png">

 Please reference [This Work Item](https://dev.azure.com/msazure/One/_workitems/edit/14740437#) for any clarifications.

### Expected behavior

1. Get call should not require fencingClientPassword and should succeed.
2. subnetId should be of type string, not object in specified model.
3. it should be bomUrl, not bomUri at specified model.

### Actual behavior

added in description section.

### Reproduction Steps

Will update with a PR that uses existing models and failing get call. that'll fail if we change them to required value.

**Comment by Yao725** [comment]
Hi @gargankit-microsoft， some updates here：
For question 1, I'd like to know if your service is already deployed in production. If it is, could you show me the example code about how to create the SapVirtualInstance resource so I can repro your issue?
For question 2&3, we just change the property type and name, this change is required from the .NET SDK perspective, but it will not affect the request payload. In other words, the request will be sent to the backend service just as you expected.

**Comment by shreyks** [comment]
Hey @Yao725 , could you refer to this PR in reference to my  responses : https://github.com/Azure/azure-sdk-for-net/pull/29491/files#diff-37f1d7dbbf0797f4c4870261e082a861b05e093227ca60f65739665ca9e12cf7

1. No, we're planning public preview for 4th July. In the  PR, please take a look at sdk/workloads/Azure.ResourceManager.Workloads/tests/Tests/SviCRUDTests.cs , in the TestSVICrudOperations() we can see how SVIs are created. In TestSVIStartStopOperations() , the GetSapVirtualInstanceAsync("F62") is the one we faced issues with (needing fencing client psswd). 
2. Please take a look at GetSingleServerPayloadToPut() in SviCRUDTests.cs, in this function the imports and deserialising are failing when the JSON used is one as per Swagger defintion. Which is why the JSON payload had to be modified a bit, noticing the difference from Swagger defintion. Hope this helps, please feel free to contact skottukkal@microsoft.com for further clarification.
