### ISSUE TITLE
[BUG] [FormRecognizer] 4.0-beta4 Table parsing not as accurate compared to beta3

### ISSUE THREAD

**Issue by chrizy** [Azure/azure-sdk-for-net#29402]
### Library name and version

Azure.AI.FormRecognizer 4.0-beta4

### Describe the bug

Since upgrade to latest .net SDK beta4 (uses 2022-06-30-preview) table parsing is not as accurate as previous version.

Test case reproduced using Recogniser Studio.

### Expected behavior

2022-01-30-preview  — OLD VERSION OK
![image](https://user-images.githubusercontent.com/3624292/174902888-6b2353b7-ede3-4e88-b00c-89280e58a890.png)

### Actual behavior

2022-06-30-preview — FAIL
<img width="612" alt="image" src="https://user-images.githubusercontent.com/3624292/174903157-0669f860-45f4-4213-8592-3cc05fb8d5b9.png">

### Reproduction Steps

Input PDF
![image](https://user-images.githubusercontent.com/3624292/174902816-432429de-f22e-4929-b2e1-5311704f2e57.png)

**Comment by Freenex1911** [comment]
I have the same issue here. The custom model is still on the same version and hasn't been changed but as soon as I update the library to beta4 the table recognition becomes very inaccurate. I've read the change logs but couldn't figure out how to avoid it. Maybe it's because the default client version of `DocumentAnalysisClient` has changed? But this shouldn't affect the creation version of the custom models right?

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by kinelski** [comment]
Hello @chrizy and @Freenex1911. Can you reproduce the same issue with version 4.0.0 of the SDK? It targets a new service version (2022-08-31), so it could have solved your problem.

**Comment by Freenex1911** [comment]
It looks like this problem is gone since I've updated to 4.0.0, I also created new custom models just to make sure I'm up2date.

**Comment by chrizy** [comment]
Working better now. thanks
