### ISSUE TITLE
[QUERY] Possibility to Query Azure Blob in a Container with Page and Index

### ISSUE THREAD

**Issue by wlazuardi** [Azure/azure-sdk-for-net#29433]
### Library name and version

Azure.Storage.Blobs 12.2.0

### Query/Question

Can I query blobs on a container to a specific page and length? 

For instance, I want to go to the 5th page by taking only 10 rows of blobs.  

Here is the current function I use on the SDK, but it seems to get all the pages from the beginning.
`Pageable<BlobItem> results = containerClient.GetBlobs();`

I'm also curious about how the blob is indexed in the container. Does it have any ordered numbers that I can use for indexing?

### Environment

Environment: .NET 6.0 with Visual Studio 2022

**Comment by PramodValavala-MSFT** [comment]
@wlazuardi You could use the [`GetBlobsAsync()`](https://docs.microsoft.com/en-us/dotnet/api/azure.storage.blobs.blobcontainerclient.getblobsasync?view=azure-dotnet) and [`AsPages()`](https://docs.microsoft.com/en-us/dotnet/api/azure.asyncpageable-1.aspages?view=azure-dotnet) methods together to get pages one by one and loop over them (since they are iterable) until the page you need.

You can't go to a particular page by number but can do so if you have the continuation token for the page before it.

**Comment by wlazuardi** [comment]
@PramodValavala-MSFT alright, thanks for the explanation. It would be great if I can go to a specific page by using the page number.
