### ISSUE TITLE
qnamaker import excel metadata is not imported

### ISSUE THREAD

**Issue by hebaelfadly** [Azure/azure-sdk-for-net#29548]
Trying to import excel file to qna through qnamaker portal, and the file contains column Metadata.

File is imported correctly except for the metadata

Sample of the file:
![image](https://user-images.githubusercontent.com/61690067/176440365-271e39bb-3b74-4bcf-8143-da8e5690a06e.png)

Imported data:
![image](https://user-images.githubusercontent.com/61690067/176440693-190b9f41-8c8c-4ac5-9950-efd92ff55467.png)

**Comment by jsquire** [comment]
Hi @hebaelfadly.  Thank you for reaching out and we regret that you're experiencing difficulties.  Unfortunately, this repository is focused on the Azure SDK for .NET - we're unable to assist with other Azure issues.  Since what you're describing appears to be related to the QnA Maker Portal and not one of our SDK packages, your best path forward would be to [open an Azure support request](https://docs.microsoft.com/azure/azure-portal/supportability/how-to-create-azure-support-request).

I'm going to close this out; if I've misunderstood what you're describing, please let us know in a comment and we'd be happy to assist as we're able.
