### ISSUE TITLE
SearchModelFactory.FacetResult parameter not documented

### ISSUE THREAD

**Issue by julyvee** [Azure/azure-sdk-for-net#29871]
The parameter additionalProperties does not have any description. A list of possible properties, how they are used or at least some examples would be nice.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 23772ac0-d70d-4cec-cb13-c9c48a31c2a0
* Version Independent ID: da083860-3dd7-2650-3b35-28210b0cd827
* Content: [SearchModelFactory.FacetResult Method (Azure.Search.Documents.Models) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/azure.search.documents.models.searchmodelfactory.facetresult?view=azure-dotnet)
* Content Source: [xml/Azure.Search.Documents.Models/SearchModelFactory.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Azure.Search.Documents.Models/SearchModelFactory.xml)
* Service: **azure**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by ShivangiReja** [comment]
Hi @julyvee, Thanks for filing this issue. For context [FacetResult](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/search/Azure.Search.Documents/src/Generated/Models/FacetResult.cs) is an output model(read- only model) is an output model(read-only model) that's why we provide [SearchModelFactory.FacetResult](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/search/Azure.Search.Documents/src/Models/SearchModelFactory.cs#L324) to mock [FacetResult](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/search/Azure.Search.Documents/src/Generated/Models/FacetResult.cs) type for testing. We provide Model factory for all read-only models to support mocking to enable non-live testing of service clients by customers.

Since [FacetResult](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/search/Azure.Search.Documents/src/Generated/Models/FacetResult.cs) is an output model(read- only model), user can not pass `additionalProperties`, the values comes from the service.

If you want to mock [FacetResult](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/search/Azure.Search.Documents/src/Generated/Models/FacetResult.cs) type for testing, you can use something like:
```csharp
        public FacetResult MakeRangeFacet(int count, object from, object to) =>
            SearchModelFactory.FacetResult(count, new Dictionary<string, object>()
            {
                ["from"] = from,
                ["to"] = to
            });
```

For more details please refer [this](https://azure.github.io/azure-sdk/dotnet_introduction.html#dotnet-mocking) for ModelFactory.

**Comment by ShivangiReja** [comment]
Hi @julyvee, Thanks for filing this issue. For context [FacetResult](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/search/Azure.Search.Documents/src/Generated/Models/FacetResult.cs) is an output model(read-only model) that's why we provide [SearchModelFactory.FacetResult](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/search/Azure.Search.Documents/src/Models/SearchModelFactory.cs#L324) to mock [FacetResult](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/search/Azure.Search.Documents/src/Generated/Models/FacetResult.cs) type for testing. We provide Model factory for all read-only models to support mocking to enable non-live testing of service clients by customers.

Since [FacetResult](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/search/Azure.Search.Documents/src/Generated/Models/FacetResult.cs) is an output model(read- only model), user can not pass `additionalProperties`, the values comes from the service.

If you want to mock [FacetResult](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/search/Azure.Search.Documents/src/Generated/Models/FacetResult.cs) type for testing, you can use something like:
```csharp
        public FacetResult MakeRangeFacet(int count, object from, object to) =>
            SearchModelFactory.FacetResult(count, new Dictionary<string, object>()
            {
                ["from"] = from,
                ["to"] = to
            });
```

For more details please refer [this](https://azure.github.io/azure-sdk/dotnet_introduction.html#dotnet-mocking) for ModelFactory.

**Comment by ShivangiReja** [comment]
> I'm not sure I quite understand. If the user cannot pass additional properties, why is there a parameter for this in the factory method?

Because [FacetResult](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/search/Azure.Search.Documents/src/Generated/Models/FacetResult.cs) is an output model(read- only model) and user can not pass `additionalProperties` in `FacetResult` type, the values for this type come from the service. 
As I mentioned above, we provide Model factory for all read-only models to support mocking to enable non-live testing by customers. Since [FacetResult](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/search/Azure.Search.Documents/src/Generated/Models/FacetResult.cs) is a read-only model, we provide [SearchModelFactory.FacetResult](https://github.com/ShivangiReja/azure-sdk-for-net/blob/1f5d15f3663b67c071d5ffe1da4c94a6ce4a351d/sdk/search/Azure.Search.Documents/src/Generated/SearchModelFactory.cs#L22) to enable non-live testing, so customers can mock [FacetResult](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/search/Azure.Search.Documents/src/Generated/Models/FacetResult.cs) type but it's properties(count and additionalProperties) will not be passed to the service.

>If the user can pass additional properties for mocking through the factory method (which I assume is the case as per your example), my problem is that this isn't properly documented on the page mentioned in my issue.

I've created a PR [here](https://github.com/Azure/azure-sdk-for-net/pull/29909) and added a document coming from the service.

**Comment by julyvee** [comment]
In my testing case, I'm trying to mock the FacetResults but I always get an error because the value is null. So you're saying there is no way for me to specify a value or a range for a mocked FacetResult?

**Comment by ShivangiReja** [comment]
You can mock `FacetResult` type using [SearchModelFactory.FacetResult](https://github.com/ShivangiReja/azure-sdk-for-net/blob/1f5d15f3663b67c071d5ffe1da4c94a6ce4a351d/sdk/search/Azure.Search.Documents/src/Generated/SearchModelFactory.cs#L22) method where you can pass `FacetResult` properties(count and additionalProperties).

What I was saying is, you can use [SearchModelFactory.FacetResult](https://github.com/ShivangiReja/azure-sdk-for-net/blob/1f5d15f3663b67c071d5ffe1da4c94a6ce4a351d/sdk/search/Azure.Search.Documents/src/Generated/SearchModelFactory.cs#L22) only for non-live testing, hence `FacetResult` properties(count and additionalProperties) will not be passed to the service.

For your reference, [here](https://github.com/Azure/azure-sdk-for-net/blob/a5be1923656fb710090a7359056cddf364c10ab4/sdk/search/Azure.Search.Documents/tests/DocumentOperations/SearchMockTests.cs#L36) I've added a mock test for search facet and [here](https://github.com/Azure/azure-sdk-for-net/blob/a5be1923656fb710090a7359056cddf364c10ab4/sdk/search/Azure.Search.Documents/tests/DocumentOperations/SearchMockTests.cs#L76) I'm mocking `FacetResult` type using `SearchModelFactory.FacetResult`.


>In my testing case, I'm trying to mock the FacetResults but I always get an error because the value is null. 

Could you please provide an example of your testcase?

**Comment by ShivangiReja** [comment]
You can mock `FacetResult` type using [SearchModelFactory.FacetResult](https://github.com/ShivangiReja/azure-sdk-for-net/blob/1f5d15f3663b67c071d5ffe1da4c94a6ce4a351d/sdk/search/Azure.Search.Documents/src/Generated/SearchModelFactory.cs#L22) method where you can pass `FacetResult` properties(count and additionalProperties).

What I was saying is, you can use [SearchModelFactory.FacetResult](https://github.com/ShivangiReja/azure-sdk-for-net/blob/1f5d15f3663b67c071d5ffe1da4c94a6ce4a351d/sdk/search/Azure.Search.Documents/src/Generated/SearchModelFactory.cs#L22) only for non-live testing, hence `FacetResult` properties(count and additionalProperties) will not be passed to the service.

For your reference, [here](https://github.com/Azure/azure-sdk-for-net/blob/a5be1923656fb710090a7359056cddf364c10ab4/sdk/search/Azure.Search.Documents/tests/DocumentOperations/SearchMockTests.cs#L36) I've added a mock test for search facet and [here](https://github.com/Azure/azure-sdk-for-net/blob/a5be1923656fb710090a7359056cddf364c10ab4/sdk/search/Azure.Search.Documents/tests/DocumentOperations/SearchMockTests.cs#L76) I'm mocking `FacetResult` type using `SearchModelFactory.FacetResult`.

Also, if you want to add ModelFactory tests to mock `FacetResult` type, you can add something like
```csharp
[Test]
public void MockFacetResult()
{
     var count = 2;
     var additionalProperties = new Dictionary<string, object>()
     {
          "value"] = "Luxury"
      };
      var facetResult = SearchModelFactory.FacetResult(count, additionalProperties);
      Assert.AreEqual(count, facetResult.Count);

      var firstAdditionalProperty = additionalProperties.First();
      Assert.AreEqual(firstAdditionalProperty.Value, facetResult.TryGetValue(firstAdditionalProperty.Key, out object value) ? value : null);
}
```


>In my testing case, I'm trying to mock the FacetResults but I always get an error because the value is null. 

Could you please provide an example of your testcase?

**Comment by julyvee** [comment]
This example was super helpful thanks so much! I understand now to do it. Coming back to the issue, is there a way to add some of this explanation and example of the additionalProperties parameter to the documentation page mentioned in the issue? :) Thank you for your support!

**Comment by ShivangiReja** [comment]
The most relevant details we have are in this doc: [Search Documents (Azure Cognitive Search REST API) | Microsoft Docs](https://docs.microsoft.com/en-us/rest/api/searchservice/search-documents).

![image](https://user-images.githubusercontent.com/45216704/180568936-3209bf95-bb45-405a-9466-a8192a256947.png)


Essentially there's different types of facets so I'm guessing that's why it's modeled like [it is](https://github.com/ShivangiReja/azure-sdk-for-net/blob/1f5d15f3663b67c071d5ffe1da4c94a6ce4a351d/sdk/search/Azure.Search.Documents/src/Generated/SearchModelFactory.cs#L20). For example, there are interval facets, count facets, etc. For simple count facets, the service will generally return something like this:
![image](https://user-images.githubusercontent.com/45216704/180569160-c18c88dc-814b-4fd0-935f-b73e73d89003.png)

**Comment by ShivangiReja** [comment]
@julyvee I created a PR https://github.com/Azure/azure-sdk-for-net/pull/30093 to add an example for `SearchModelFactory.FacetResult` and added a reference link in remarks.

You should be able to see the updated docs [here](https://docs.microsoft.com/en-us/dotnet/api/azure.search.documents.models.searchmodelfactory.facetresult?view=azure-dotnet-preview) in our next beta release.

**Comment by julyvee** [comment]
Amazing thank you :) this resolves my issue!
