### ISSUE TITLE
[BUG] ResourceManager: Type Error

### ISSUE THREAD

**Issue by stevengiannakopoulos** [Azure/azure-sdk-for-net#29912]
### Library name and version

Azure.ResourceManager.Resources 1.2.0

### Describe the bug

When using the ARM Client, under the default subscription, GetSubscriptionPolicySetDefinitions() (or GetSubscriptionPolicySetDefinitions().GetAll()) throws an error:
'System.InvalidOperationException' in Azure.ResourceManager.dll ("The requested operation requires an element of type 'Boolean', but the target element has type 'String'.

### Expected behavior

Return a list of policy set definitions instead of an exception

### Actual behavior

Throws an exception every time:
'System.InvalidOperationException' in Azure.ResourceManager.dll ("The requested operation requires an element of type 'Boolean', but the target element has type 'String'.

### Reproduction Steps

var test = new ArmClient(new DefaultAzureCredential(),"SUBSCRIPTIONID").GetDefaultSubscription().GetSubscriptionPolicySetDefinitions().GetAll().ToList()

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by fengzhou-msft** [comment]
By checking the data types in `PolicyDefinitionData` recursively, I only found one boolean property:  [AssignPermissions](https://github.com/Azure/azure-sdk-for-net/blob/832e54ecdcd8cebcdd2f273396374ba8b7dac87f/sdk/resourcemanager/Azure.ResourceManager/src/Resources/Generated/Models/ParameterDefinitionsValueMetadata.cs#L45) @stevengiannakopoulos do you know if any of your policies has set `AssignPermissions`? This looks like a service issue, it should return boolean instead of string.

**Comment by stevengiannakopoulos** [comment]
@fengzhou-msft Revisiting this as I now understand what is happening. The AssignPermissions property in either the policy or policy initiative parameters metadata should be a boolean. I see instances where this property is accepted by Azure policy as a string. Please see image below from the Azure portal (with redacted information). If this property exists as a string within Azure, it cannot be listed or retrieved by the ArmClient.
![image](https://user-images.githubusercontent.com/87831686/201179988-a9fdbd1e-0527-4bdd-98d0-c207da185600.png)

**Comment by fengzhou-msft** [comment]
@armleads-azure please help check the type of [assignPermissions](https://github.com/Azure/azure-rest-api-specs/blob/4b7373a29b0cc90e654ca66a8ca3742affca732d/specification/resources/resource-manager/Microsoft.Authorization/stable/2021-06-01/policyDefinitions.json#L591-L594) in 
policyDefinitions.json. It is defined as boolean in swagger, but service accepts/returns string.

**Comment by ArthurMa1978** [comment]
Since this issue is related to the service side and not the SDK side, so we are not able to help you with it. Therefore, we are closing this issue for now. If you need more assistance, please [open an Azure support request](https://docs.microsoft.com/azure/azure-portal/supportability/how-to-create-azure-support-request). We apologize for any inconvenience this may cause you.

We value your feedback and we want to make sure that your problem is solved. If you think that we have misunderstood your issue or closed it incorrectly, please feel free to comment on this thread and reopen the issue. We will be happy to assist you further. Thank you for your understanding and cooperation.
