### ISSUE TITLE
Retry Policy is not Respected

### ISSUE THREAD

**Issue by xbaha** [Azure/azure-sdk-for-net#30034]
I am receiving this error message:

Azure.Messaging.ServiceBus.ServiceBusException: 'The operation did not complete within the allocated time 00:00:30 for object xxxxxxx.servicebus.windows.net:5671. (ServiceTimeout)'

notice the allocated time is 30 seconds.
My retry policy:

```
                var options = new ServiceBusClientOptions
                {
                    TransportType = ServiceBusTransportType.AmqpTcp,
                    RetryOptions = new ServiceBusRetryOptions()
                    {
                        Mode = ServiceBusRetryMode.Exponential,
                        Delay = TimeSpan.FromSeconds(1),
                        MaxDelay = TimeSpan.FromSeconds(59),
                        MaxRetries = 10,
                        TryTimeout= TimeSpan.FromSeconds(59),                       
                    }
                };
```

It is supposed to give an error that the allocated time is 00:00:59

If I change the value to anything less than 30 seconds, it works as expected.
Please advise if 30 seconds is the maximum.

Thanks.

**Comment by jsquire** [comment]
Hi @xbaha.  Therre's not much context for me to work from; if you'd like to share some additional samples of your code, we may be able to provide greater insight.   Based on the discussion, I believe what you're seeing is normal and expected behavior.   

The `TryTimeout` is the interval allowed for all steps needed to perform the requested operation.  In scenarios where multiple steps are needed - such as opening a connection/link to make the service request, the portion of the `TryTimeout` that is left after doing so is passed to the service as the limit for the operation itself.   Often, differences like this are due to establishing the connection, link, and authorization needed for the operation.  In your scenario, it may be this or it may be something else - there's not enough information to do more than speculate.

There's a couple of things that would be helpful to understand:

- I'm not sure what is meant by "If I change the value to anything less than 30 seconds, it works as expected."   Can you elaborate a bit on what you're seeing in that case?

- A `ServiceTimeout` is a retriable error; if you're seeing that propagate to your application, that indicates all retries have been exhausted.  That there's a disparity in this case may indicate a problem with being able to establish the connection.  Can you [collect verbose SDK logs](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/core/Azure.Core/samples/Diagnostics.md#logging) for a +/- 2-minute period around the behavior?
