### ISSUE TITLE
Autogenerated Id

### ISSUE THREAD

**Issue by LastTribunal** [Azure/azure-sdk-for-net#30044]
[Enter feedback here]
In the legacy cosmos client (document db), Cosmos generated a random id guid, and that guid can be retrieved in the response of the create record request.  in this new library, there is no way to let cosmos generate the id and then retrieve it from the response
It can only be done if the Id is supplied in the request and exists in the model.   But then the resulting id is futile, since it will always be equivalent to the supplied id.

so then we are forced to use Guid.NewGuid(), and that can lead to a conflict, although astronomically unlikely... still bad design

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ffbd77a6-f4fe-92d3-fe9d-faa9582ab798
* Version Independent ID: 23598212-dccb-4849-349e-b8ccc6fc90d3
* Content: [Resource.Id Property (Microsoft.Azure.Documents) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.documents.resource.id?view=azure-dotnet)
* Content Source: [xml/Microsoft.Azure.Documents/Resource.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.Documents/Resource.xml)
* Service: **cosmos-db**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by ealsur** [comment]
The legacy SDK client (document db) autogenerated the Id by doing Guid.NewGuid(), which is the same scenario you are describing: 

> so then we are forced to use Guid.NewGuid(), and that can lead to a conflict, although astronomically unlikely... still bad design

Because it is not a great design, now users are free to use whatever design they want to generate their Ids, and the client will not make any assumptions. You are not forced to use Guid.NewGuid().

If you want to have exactly the same experience as the legacy Microsoft.Azure.DocumentDB, then using the Guid.NewGuid() approach matches exactly. If you don't like that approach, then you also did not like what Microsoft.Azure.DocumentDB did and now you have the opportunity to use your own design and choose a much better approach, whichever it is that you desire.

For the migration path, because most commonly customers want to do the same thing Microsoft.Azure.DocumentDB did, we recommend Guid.NewGuid() because it's literally the same thing: https://docs.microsoft.com/azure/cosmos-db/sql/migrate-dotnet-v3?tabs=dotnet-v3#changes-to-item-id-generation

If you are writing a new application, then feel free to choose whatever logic you want and matches your business model.

**Comment by LastTribunal** [comment]
then it's my misunderstanding.. I thought the previous client allowed cosmos server generate the guid, preventing conflicts.. but based on what you are saying, the client was doing that.. in that case new is same as old..  then what's the point of getting the response id when it will always be the same as the one supplied in the create request?

**Comment by ealsur** [comment]
Correct, there was no server generated id.

The protocol (REST contract) says that when you create a document, you receive the document as part of the response. Yes, this is potentially useless information (if you just sent the Create request, you already know the document content, why would you need it?) but the default behavior cannot be changed.

Having said that, you can on the V3 SDK remove this extra (potentially not useful) information from the wire for write operations: https://devblogs.microsoft.com/cosmosdb/enable-content-response-on-write/, that will save network bandwidth.

**Comment by navba-MSFT** [comment]
@LastTribunal Thanks for reaching out to us. I hope you had a chance to look at the above suggestion provided by @ealsur. Please let us know if you have any follow-up questions on this.

**Comment by navba-MSFT** [comment]
@LastTribunal I hope your queries have been answered. We will now proceed with closure of this GitHub issue. If you need any further assistance on this issue in future, please feel free to reopen this thread. We would be happy to help.
