### ISSUE TITLE
No support for Managed Identity

### ISSUE THREAD

**Issue by peter-bertok** [Azure/azure-sdk-for-net#30045]
The current version of this API only allows connection strings with embedded "secrets", such as Account Keys or SAS tokens. These are terribly insecure, and there has been an ongoing push by Microsoft (and end-users) to remove them and migrate authentication to either System Assigned or User Assigned managed identities. This eliminates the need for "secrets management" such as Key Vault and the rigmarole of key rotation. It's also compatible with Visual Studio via the DefaultAzureCredential class, which makes the developer experience much "smoother", as non-secret connection strings can be left in the code, and will automatically use the developer's credentials when connecting to cloud-hosted resources such as Azure SQL Databases and Storage Accounts.

The problem is that Storage Account connection strings do not support any Azure AD authentication formats, and are coded to check for only the *legacy* secret key or token authentication styles:

https://github.com/Azure/azure-sdk-for-net/blob/bb22d47f4c7aa1ec5c6a3fe63e2cf8106f924e1e/sdk/storage/Azure.Storage.Common/src/Shared/StorageConnectionString.cs#L770-L775

For comparison, the Microsoft.Data.SqlClient connections strings allow a format such as:

```Server=tcp:foobar.database.windows.net,1433;Database=thedbname;Authentication=Active Directory Managed Identity;User Id=########-####-####-####-############;```

This then enables existing code to "just work" without requiring any direct reference to Azure.Identity, or jumping through any specific hoops to wire up the authentication. Code running at dev-time can use a connection string with "Active Directory Default" mode to pick up the Visual Studio user identity, and the App Service can use the style above to automatically switch to a managed identity.

While Blob storage supports the same authentication *mechanism*, it does not support the same style of *connection strings*, which means that the code needs to explicitly "input" this. It's easy to do this wrong, and then becomes inflexible because the code must have a specific "path" picked out. It won't be as flexible as the generic connection-string based mechanism, making such code non-portable, e.g.: to Azure Stack.

The happy path would be if all "service connections" including Azure Storage supported the ability to specify an identity clientid, and then automatically wired up the [ManagedIdentityClientId](https://docs.microsoft.com/en-us/dotnet/api/azure.identity.defaultazurecredentialoptions.managedidentityclientid?view=azure-dotnet#azure-identity-defaultazurecredentialoptions-managedidentityclientid) property of DefaultAzureCredentialOptions.

The change would be relatively simple, and would be largely the same as what SqlConnection does. Just add the various authentication modes (ideally copying the SqlConnection syntax verbatim), and then have the various storage client classes wire up the DefaultAzureCredential to match.

Customers can obviously still choose to select their authentication manually, but this would make Storage consistent with other Azure products.

**Comment by SaurabhSharma-MSFT** [comment]
@peter-bertok Redirecting this to services team.

**Comment by amnguye** [comment]
Apologies for the late reply. From reading the issue, for clarity this is a feature request for the storage service in general right? Hm this also seems like we need to engage with the Identity team to make sure we align with the proper way to address such an ask.

Unfortunately, this repository is focused on the Azure SDK for .NET - we're unable to assist with other Azure issues. Not to be confused, this is for SDK (in this case the Storage SDK), not the storage service in itself. The Storage SDK can only support what the storage service is willing to recognize as a proper connection string.

Even if the ask is for the Storage SDK to support these "new" connection strings, we would have to align all other storage products to take these "new" connection strings to prevent confusion of what connection strings are accepted.

We would highly recommend submitting requests through tech support or community forum.
https://azure.microsoft.com/en-us/support/community/
or to create an Azure support request
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

If there's any issues with the Storage SDK itself feel free to submit another issue again, and we will be here to help, we cannot help further with this feature ask unfortunately since it's out of our reach.

I'm going to close this issue for now since this is outside the scope of the SDK, however please comment again if I've misunderstood the ask here, and if it is an SDK ask.

**Comment by peter-bertok** [comment]
> Unfortunately, this repository is focused on the Azure SDK 

The code in question is literally in this repository, so it's within the scope of the Azure SDK.

The connection string is a "client side" feature. For example, Microsoft SQL Server connection strings are defined by and processed within client libraries such as ADO.NET, not in the database engine. 

In both this scenario and the SQL example above, the clients parse the connection strings and then used the parsed parameters to configure the connection.

All of this could be implemented in this code base, and minimal involvement would be needed from the Azure Identity team.

My recommendation is to just copy the same syntax used by the SQL team.

**Comment by amnguye** [comment]
Yes the connection string is a client side feature, but not specifically an SDK feature. It's a client side storage feature, which the SDK supports. I can see your point that it's in the scope however, it would be in the scope if all of storage supports this new connection string. For the SDK to push this new form of a connection string on all of our client side storage products, is out of the scope of the SDK.

As I said before,
> Even if the ask is for the Storage SDK to support these "new" connection strings, we would have to align all other storage products to take these "new" connection strings to prevent confusion of what connection strings are accepted.

We would have to align all our other client side storage products to support these new connection strings (e.g. storage explorer, powershell, azcopy) to support the new connection string. This feature ask is to support a new form of a connection string.
