### ISSUE TITLE
The  `static IQueueClient QueueClient` in the Microsoft.Azure.ServiceBus/BasicSendReceiveUsingQueueClient example is creating bugs and other usage questions

### ISSUE THREAD

**Issue by StingyJack** [Azure/azure-sdk-for-net#30371]
From [here](https://github.com/Azure/azure-service-bus/blob/master/samples/DotNet/GettingStarted/Microsoft.Azure.ServiceBus/BasicSendReceiveUsingQueueClient/Program.cs).

I recently saw this in an ASP.net web api controller, copied pretty much verbatim from this example. This not only led to some nasty bugs WRT connection orphaning and premature closures , but also to a few questions. The most important one is "Is this supposed to be treated like HttpClient, where one instance is intended to be used by the whole application?"   Its unclear from this console example if that's the correct usage case or not, and documentation is more or less empty.  Can someone speak to this, and if its not, can someone update the example to not be so "console app specific"?

**Comment by jsquire** [comment]
Hi @StingyJack.  Thanks for reaching out and we regret that you're experiencing difficulties.    Since you're inquiry is regarding the legacy package (Microsoft.Azure.ServiceBus), we'll need to defer to @shankarsama and @EldertGrootenboer for guidance.  That said, since `Microsoft.Azure.ServiceBus` is deprecated, we strongly advise upgrading to `Azure.Messaging.ServiceBus`.

For the client types in `Azure.Messaging.ServiceBus`, the [Client lifetime](https://github.com/Azure/azure-sdk-for-net/tree/main/sdk/servicebus/Azure.Messaging.ServiceBus#client-lifetime) guidance is to cache clients and use them as singletons for the lifetime of the application.  In an ASP.NET context, we recommend using the [Microsoft.Extensions.Azure](https://www.nuget.org/packages/Microsoft.Extensions.Azure) package which provides a set of [Service Bus extensions](https://docs.microsoft.com/dotnet/api/microsoft.extensions.azure.servicebusclientbuilderextensions?view=azure-dotnet) to allow for directly registering the clients with DI so that lifetime management takes place implicitly.

**Comment by StingyJack** [comment]
@jsquire - thanks for returning to this. Others watching this thread may still need the answer but I dont (changed jobs in the 2 years since I opened this)

**Comment by EldertGrootenboer** [comment]
As this is an issue with the old SDK, and the original poster is not in need of the answer anymore, we will close this issue. We recommend moving to the latest SDK, for which Jesse has thoroughly described the behavior.
