### ISSUE TITLE
[STORAGE][QUERY]Should not trim '/'s in beginning or ending of blob name 

### ISSUE THREAD

**Issue by EmmaZhu** [Azure/azure-sdk-for-net#30507]
### Library name and version

Azure.Storage.Blobs 12.2.0

### Query/Question

Storage SDK trimmed '/'s in the beginning or ending of blob name, which would change blob name like "///aa" to "a", while "///aa" is available blob name on storage server. Is it the correct behavior of blocking some blob names from client side?

**Comment by amnguye** [comment]
@jaschrep-msft Has been looking into this

**Comment by amnguye** [comment]
Hm but also is the user allowed to name blobs with /// in the name?

https://docs.microsoft.com/en-us/rest/api/storageservices/Naming-and-Referencing-Containers--Blobs--and-Metadata#blob-names

Looks like that's not recommended by the service. because the beginning slash could do something weird with the URL.

Is there a scenario where the customer needs to have a blob name like "////a" ?

**Comment by jaschrep-msft** [comment]
https://github.com/Azure/azure-sdk-for-net/pull/30271 will address a single leading slash (configurably, opt-in). I do not think it will address multiple leading slashes, as is. I am also concerned as to the need for a blob name like this.

**Comment by jaschrep-msft** [comment]
Discussed offline. Mentioned PR's flag will preserve all slashes.
