### ISSUE TITLE
[BUG] Azure.data.tables query timeout with over 1,000 records

### ISSUE THREAD

**Issue by tssmobile** [Azure/azure-sdk-for-net#30511]
### Library name and version

Azure.Data.Tables 12.6.1

### Describe the bug

When I use Pageable to create a query with data tables with over 1,000 records,
It always returns "Timed out after 1000 ms" and throws the exception when I use query.ToList().

Here is my code:
`Pageable<AnyTable> query = TableClient.Query<AnyTable>();
query.ToList();
`

Maybe someone had a similar issue and found a fix for it.
I really appreciate any help you can provide.

### Expected behavior

return a list of data

### Actual behavior

throw exception

### Reproduction Steps

`Pageable<AnyTable> query = TableClient.Query<AnyTable>();
query.ToList();
`

**Comment by m-redding** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by christothes** [comment]
Hi @tssmobile - using `.ToList()` on a query will iterate through all pages and return the whole result set. If there are a very large number of results, this could time out due to table throughput limits. You may want to handle one page at a time using `.AsPages()` as in [this sample](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/tables/Azure.Data.Tables/samples/Sample4QueryEntities.md#query-entities-with-maxperpage).
