### ISSUE TITLE
[FEATURE REQ] Rename Azure.Extensions.AspNetCore.Configuration.Secrets

### ISSUE THREAD

**Issue by mnj** [Azure/azure-sdk-for-net#30569]
### Library name

Azure.Extensions.AspNetCore.Configuration.Secrets

### Please describe the feature.

Isn't this supposed to be the Azure SDK for .NET not Azure SDK for AspNetCore?

Currently using "Azure.Extensions.AspNetCore.Configuration.Secrets" to access secrets from KeyVault from a .NET 6 Worker (dotnet new worker) project, it works fine, but a bit misleading to call it AspNetCore, when it's just a generic library, that also work with .Net 6 workers?

Wouldn't something like:
"Azure.Extensions.Configuration.Secrets" be better / more generic, it would certainly have made it a lot easier to find out it does indeed work in non aspnetcore projects.

**Comment by m-redding** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by JoshLove-msft** [comment]
Thanks for the feedback @mnj. You are correct that this can technically be used independent of ASP.NET Core. However, our [architects](https://github.com/Azure/azure-sdk-for-net/pull/11319#discussion_r409188139) felt that it was better to name this package in a similar way to our other extensions packages that do depend on ASP.NET Core:
https://www.nuget.org/packages/Azure.Extensions.AspNetCore.DataProtection.Blobs
https://www.nuget.org/packages/Azure.Extensions.AspNetCore.DataProtection.Keys

Because this package is already stable, we can't rename it at this point.
