### ISSUE TITLE
[QUERY] Is it any way to achieve download continuation when network issue and pause/continuation

### ISSUE THREAD

**Issue by IrakliLomidze** [Azure/azure-sdk-for-net#30641]
### Library name and version

Azure.Storage.Blobs

### Query/Question

is it possible to get blob storage stable downloader
When the blob file is large, we need continuation when network issues and pause/continuation functionality.

### Environment

.NET CORE / C#                                                                          
.

**Comment by navba-MSFT** [comment]
@IrakliLomidze [Retry options policies](https://docs.microsoft.com/en-us/dotnet/api/azure.core.retryoptions?view=azure-dotnet) instruct the Storage Client to retry failed requests (long running delayed operations / Network Timeouts etc). By default, only some failures are retried. For example, connection failures and throttling failures can be retried. Resource not found (404) or authentication failures are not retried, because these are not likely to succeed on retry. If not set, **the Storage Client uses an exponential backoff retry policy, where the wait time gets exponentially longer between requests, up to a total of around 30 seconds. The default retry policy is recommended for most scenarios.**

More Info [here](https://docs.microsoft.com/en-us/dotnet/api/azure.core.retryoptions?view=azure-dotnet) and [here](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.storage.blob.blobrequestoptions.retrypolicy?view=azure-dotnet-legacy).

If you are using [Storage DataMovementLibrary](https://github.com/Azure/azure-storage-net-data-movement), it supports to resume the transfer job from last checkpoint, it should be able to complete the remaining transferring with a resuming.

**TransferContext** instance is used to save and pass checkpoint. You can find sample code on how to use TransferContext to resume a transfer job here: https://github.com/Azure/azure-storage-net-data-movement/blob/master/samples/DataMovementSamples/DataMovementSamples/Samples.cs#L151

The sample code shows how to cancel and resume a transfer job. Actually, resuming also works for other exceptions. You can try to resume like samples here if there's error happened: https://github.com/Azure/azure-storage-net-data-movement/blob/master/samples/DataMovementSamples/DataMovementSamples/Samples.cs#L182

Hope this helps.
