### ISSUE TITLE
[QUERY] Is it safe to use different versions of storage SDKs which have different namespaces in the same project?

### ISSUE THREAD

**Issue by StephanieHan** [Azure/azure-sdk-for-net#30756]
### Library name and version

WindowsAzure.Storage: 8.7.0 and Microsoft.Azure.Storage.Blob: 11.2.3

### Query/Question

Hi,

I have a question about using different versions of storage .NET SDK in the same project. Currently, we are using version 8.7.0 which uses `WindowsAzure.Storage` namespace. But right now we need to use some new feature and it is not easy to upgrade the version in the legacy code. So we just added the version 11.2.3 which uses `Microsoft.Azure.Storage.Blob` namespace in the same project. We only use the new version to read data(which created/uploaded by the SDK version 9.x.x in another project) from the blob, and won't use the new version to create/upload/etc. anything. So far I don't see any issues, but I still  want to double check is it safe to have both of the two versions in the same project? Will there be any potential issues in the future?

Thanks!

**Comment by PramodValavala-MSFT** [comment]
@StephanieHan Since they are different packages from a .NET perspective, it isn't technically wrong but the problem would be in having any classes with the same name present in both and you would have to be more careful when working them to prevent ambiguity, which the compiler does already help with. So, you might have instances (especially when using both in the same file) where you have to use the fully qualified class name.

Also, cases where you are transferring data between the two, you may not be able to always convert directly and instead have to convert first to something else like a `byte[]` first, and then to the type required by the other namespace.

Any code within the packages shouldn't have any issue I believe since the namespaces are different, and they don't depend on each other.

**Comment by amnguye** [comment]
Taken offline. But as a summary 

Both versions and namespaces are deprecated. Due to the namespace change, sideloading appears to be safe. While we do not test this and so do not make guarantees, with the different root namespace it feels impossible to encounter conflicts, and other internal teams have done this successfully in the past with no reported issues.

If there’s already an effort to add v11.2.3, I think your team should consider adding v12 Azure.Storage.Blobs
