### ISSUE TITLE
[Query] AzureMediaServicesClient support for Azure.Identity

### ISSUE THREAD

**Issue by MarcoEnxuto** [Azure/azure-sdk-for-net#30762]
### Library name and version

Microsoft.Azure.Management.Media

### Query/Question

Hi,
I've been trying to acquire a token using TokenCredential from Azure.Identity.. for example by using DefaultAzureCredential class.
Since it only suppports the ServiceClientCredentials class, are you excepting to support using Identity in order to streamline the developer experience?
It seems confusing.

### Environment

Windows 11
.Net 4.8 and .Net 6.
IDE: Visual Studio 17.3.1

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by xboxeer** [comment]
@MarcoEnxuto, I don't quite get your idea of _Since it only suppports the ServiceClientCredentials class, are you excepting to support using Identity in order to streamline the developer experience?_ DefaultAzureCredential only support the below credentials
![image](https://user-images.githubusercontent.com/5089150/187403170-8971cc4f-e466-4e75-9d9f-41752ce6c52c.png)
https://docs.microsoft.com/en-us/dotnet/api/azure.identity.defaultazurecredential?view=azure-dotnet
I don't see the `ServiceClientCredentials ` that you are referring to

**Comment by MarcoEnxuto** [comment]
Hi @xboxeer , i didn't knew you're deprecating Azure Media Services SDK. I guess you're streamiling the developer experience and this looks great. Will provide feedback later. Thanks.
