### ISSUE TITLE
[FEATURE REQ] Data Factory support for data plane queries for importing schema

### ISSUE THREAD

**Issue by haitsong** [Azure/azure-sdk-for-net#30842]
### Library name

Azure.ResourceManager.DataFactory

### Please describe the feature.

To manipulate dataset that can be done in browser, for example, import default schema from dataset. In order to do it programmatically, we would have to construct client specifically to do data plane queries.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by xboxeer** [comment]
@haitsong would you share your code, tell us the actual behavior and expected behavior? I've noticed if if run the below code
```csharp
var resourceGroup = _client.GetDefaultSubscription().GetResourceGroup("DataFactoryRG").Value;

            var dataFactoryResource=resourceGroup.GetDataFactory("elendil-df").Value;            
            
            var dataset = dataFactoryResource.GetFactoryDataset("SourceDataset_s2o").Value;

            var schema = dataset.Data.Properties.Schema;
```
The Schema is null even though I can preview the schema in portal, are you expecting this Schema to be something not null? are you saying you used some query code and got that schema in code?
