### ISSUE TITLE
[QUERY] Very Slow to consume messages from ServiceBus

### ISSUE THREAD

**Issue by lommez** [Azure/azure-sdk-for-net#30869]
### Library name and version

Azure.Messaging.ServiceBus 7.10.0

### Query/Question

I`m trying to consume messages from the deadletter, but is very very slow to consume all messages

Here is my code:

![image](https://user-images.githubusercontent.com/10900667/187826991-66668e8c-02b2-48c3-aa9f-0090a2656127.png)

Am I doing something wrong or missing something?

Thank!

### Environment

.NET SDK (reflecting any global.json):
 Version:   6.0.400
 Commit:    7771abd614

.NET SDKs installed:
  3.1.422 [C:\Program Files\dotnet\sdk]
  5.0.303 [C:\Program Files\dotnet\sdk]
  5.0.404 [C:\Program Files\dotnet\sdk]
  5.0.408 [C:\Program Files\dotnet\sdk]
  6.0.100 [C:\Program Files\dotnet\sdk]
  6.0.108 [C:\Program Files\dotnet\sdk]
  6.0.202 [C:\Program Files\dotnet\sdk]
  6.0.203 [C:\Program Files\dotnet\sdk]
  6.0.303 [C:\Program Files\dotnet\sdk]
  6.0.400 [C:\Program Files\dotnet\sdk]

**Comment by jsquire** [comment]
Hi @lommez.   Thank you for reaching out and we regret that you're experiencing difficulties.    There's not enough information to diagnose what you're seeing authoritatively, but there's a couple of things that stand out on me in the code:

- You're creating 200 independent receivers that all share the same connection to Service Bus.   I suspect there's a very high chance that you're seeing some network contention going on.   Since each `ServiceBusClient` represents a connection, you may want to consider testing with additional clients to find the number of receivers sharing the connection for best performance in your scenario.   I'd suggest starting with 10 receivers per client and tweaking from there as you test.

- You're creating 200 background tasks.   I don't know how many cores your host machine has, but that seems a very high degree of concurrency for most.   I suspect that you may be seeing reduced performance due to contention in the threadpool due to continuations being queued and unable to execute more quickly.   The receivers are highly asynchronous and will struggle to make forward progress if continuations are delayed.  I'd suggest testing the amount of concurrency that works best for your host, starting with a ratio of 2 receivers to each CPU core to start and tweaking from there as you test.

Gathering a 5-minute slice of verbose logs from the SDK would help us to better understand what they're seeing.   Instructions for doing so can be found [here](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/core/Azure.Core/samples/Diagnostics.md#logging).   It may also be advantageous to grab a memory dump using the [dotnet-dump](https://docs.microsoft.com//dotnet/core/diagnostics/dotnet-dump) tool.  Examining `dumpasync`, `clrthreads`, and `clrstack` would help us to understand the state of the threadpool and the number of continuations waiting to execute.

**Comment by lommez** [comment]
Thank you so much @jsquire !
I've follow your tips and now is much better and faster!
