### ISSUE TITLE
A load balancing cycle has taken too long to complete. 

### ISSUE THREAD

**Issue by bilalmalik777** [Azure/azure-sdk-for-net#30883]
I am getting an error, given below, after some time, how to handle it and stopped to raise.
i am using **Azure.Messaging.EventHubs.Processor** **5.7.2** with dotnet 6.0

`Azure.Messaging.EventHubs.EventHubsException(GeneralError): "A load balancing cycle has taken too long to complete. A slow cycle can cause stability issues with partition ownership. Consider investigating storage latency and thread pool health. Common causes are soft delete being enabled for storage and too many partitions owned. You may also want to consider increasing the 'PartitionOwnershipExpirationInterval' in the processor options. Cycle Duration: '100.91' seconds. Partition Ownership Interval '1:20' seconds.")] `

**Comment by jsquire** [comment]
Hi @bilalmalik777.   Thank you for reaching out and we regret that you're experiencing difficulties.  This message typically indicates that you've asked the processor to own more partitions than your host machine is capable of with reasonable performance.   Generally, this causes contention in the threadpool that results in asynchronous continuations being delayed and/or threadpool starvation.

In this case, the load balancing loop that, by default, is expected to run every 30 seconds is taking more than 3 times as long to run.  This is likely to cause ownership issues with partitions potentially bouncing between processors.  It is also an indicator of slow performance when processing events that may lead to some partitions stalling, since the runtime does not guarantee fairness for continuation scheduling.

Mitigation will be scaling either vertically (more CPU cores) or horizontally (more host machines running processor instances).   More details and recommended configurations to use for testing can be found the linked section of our [Troubleshooting Guide](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/eventhub/Azure.Messaging.EventHubs/TROUBLESHOOTING.md#warnings-being-raised-to-the-error-handler-that-starts-with--a-load-balancing-cycle-has-taken-too-long-to-complete-).
