### ISSUE TITLE
[QUERY] End to end latency in Azure Event Hub (EventProcessorClient) over 50ms

### ISSUE THREAD

**Issue by vgpro54321** [Azure/azure-sdk-for-net#30898]
### Library name and version

Azure.essaging.EventHubs 5.7.2

### Query/Question

Hello All,

I am measuring latency between sending an event and receiving it on the same machine.
Azure Hub and sender/receiver box are in the same Azure region.

I calculate latency as:
a) DateTime.UtcNow - EnqueuedTime
b) DateTime.UtcNow - [utc property inside message object being sent]

No matter how I calculate latency it is over 50ms, which is double compared to say, same experiment using a storage queue.

Is this kind of latency normal? 

### Environment

Windows, .NET 6

**Comment by jsquire** [comment]
Hi @vgpro54321.  There's no one answer for this question.  The type of latency that you're measuring is impacted by many factors including:

- The SKU of the Event Hubs namespace (standard vs premium vs dedicated)
- The configuration of the Event Hub (number of partitions, enabled features)
- The number of concurrent operations taking place on the host (standard and premium are shared hosts)
- The configuration of your host machine and its network
- How the application is publishing/reading events, including the configuration of your clients

Of particular interest to this discussion is that connections are lazily instantiated within the client.  The first call for any service operation will pay to establish the connection, links, and perform authorization before any publishing/reading takes place - often on a per-partition basis.  Since AMQP uses a persistent connection, this sequence may need to be repeated any time there's a network blip or the client has been idle for a period of time.  

Another pertinent detail is that the service does not offer an SLA around the amount of time between when an event has been accepted as published and when that same event is committed to a partition and made available to read.  As a result, due to how host resources are shared, you'll generally see more latency in a standard SKU than premium/dedicated and in premium than dedicated.

At the end of the day, this seems within the normal range that I'd expect for a standard namespace and common configuration.  One thing to keep in mind is that the Event Hubs stack is optimized for throughput, not latency.   

I'm going to mark this as addressed, but please feel free to unresolve if you'd like to continue the discussion.
