### ISSUE TITLE
[FEATURE REQ] Make Argument class public instead of internal

### ISSUE THREAD

**Issue by Zer010** [Azure/azure-sdk-for-net#30923]
### Library name

Azure.Core

### Please describe the feature.

Per the guidelines for implementations outlined here: https://azure.github.io/azure-sdk/dotnet_implementation.html#dotnet-parameter-validation-class 

It is self-defeating to keep such a useful utility as internal. Developers of 3rd party packages should be able to take advantage of this class even if they are not writing a direct native Azure.* package themselves. Please consider making this a public part of the Azure.Core package so 3rd party packages can offer the same level of consistency provided by first class Azure.* packages.

Edit: To further clarify you cannot extend the object as it is a static object hence the point of this issue.

Example:
![image](https://user-images.githubusercontent.com/9933879/188337912-f5a6e392-4b9e-4166-9a53-80bcece6a8cc.png)

**Comment by jsquire** [comment]
Hi @Zer010.  Thank you for your feedback.  This is not a change that we'll be making in the short term.  Because of our strong guarantees around backwards compatibility, any additions to the public API become something that we must maintain and cannot change.  A utility class such as this is something that we want to retain the flexibility to extend and change as our implementation needs change.

In addition, we strive to limit the number of public types exposed by Azure libraries to keep a focused experience, improve discoverability, and reduce clutter in developer tooling such as IDE code-completion lists.  As the validation code within `Argument` is straightforward and non-specific to Azure, the value offered by this class is consistent error messaging throughout the Azure SDK.  We do not believe there is enough complexity nor Azure-specific functionality to warrant this being part of the Azure.Core public API at this time.
