### ISSUE TITLE
Is there any plan to replace Newtonsoft.Json with System.Text.Json in Microsoft.Rest.ClientRuntime project?

### ISSUE THREAD

**Issue by xiaomi7732** [Azure/azure-sdk-for-net#30957]
### Library name and version

Microsoft.Rest.ClientRuntime 2.3.24

### Query/Question

Is there a plan to drop the dependency on `Newtonsoft.json` in the future version?

We are looking into dropping the dependency of `Newtonsoft.Json` (replace it with System.Text.Json). Our project depends on a third-party library, which in turn, depends on `Microsoft.Rest.ClientRuntime`. Since `Microsoft.Rest.ClientRuntime` depends on `Newtonsoft.Json`, we can't do it unless we drop `Microsoft.Rest.ClientRuntime` at the same time.

### Environment

Our project targets `.NET Standard 2.1`.

**Comment by jsquire** [comment]
Hi @xiaomi7732.  The current generation of Azure SDK libraries makes use of `Azure.Core` rather than the AutoRest runtime for its HTTP pipeline and related functionality.  The AutoRest Runtime is not actively receiving new features, just critical bug fixes.   As a result, and because of the need to guarantee backwards compatibility, changing the serializer is not a feature that we're able to consider at this time.   

I'm going to mark this as addressed, but please feel free to unresolve if you'd like to continue the discussion.

**Comment by xiaomi7732** [comment]
Thanks for the quick turnaround and the communication. That makes sense.
