### ISSUE TITLE
[QUERY] Identity: Refresh token permissions after new grant?

### ISSUE THREAD

**Issue by RayGHeld** [Azure/azure-sdk-for-net#30959]
### Library name and version

Azure.Identity

### Query/Question

When getting an access token for a resource, once you make the request, the token always has the same permissions even after granting admin consent for new permissions on the MSI service principal.  You have to wait 24 hours before those permissions come in.  How can I "reset" this so that I can make permission changes and get a fresh access token without having to wait 24 hours?

### Environment

.net 4.8 framework for .net core application running on a windows 10 vm

**Comment by schaabs** [comment]
@RayGHeld thanks for reaching out with this question. Currently we don't have any mechanism for forcing the refresh of tokens in the credential types defined in Azure.Identity. This is because we don't have a reliable way to do this in most cases. Specifically for managed identity, we get tokens from the managed identity endpoint provided by the host. These endpoints have caching layers of their own, and don't provide any mechanism to force a refresh or bypass that cache. So if we were to provide an API to force refresh, there would be no way for us to guarantee that a new token would be acquired.

That being said, for the most part in Azure specific permissions are not baked into the token.  Most Azure services accept tokens scoped to `.default`, and so the tokens don't contain permission claims, but just the identity of the caller. They then use [RBAC](https://docs.microsoft.com/azure/role-based-access-control/overview) to authorize that identity has permission. Because of this you shouldn't need a new token to use newly granted permissions. There can be a delay between updates to RBAC and the services picking up those changes. This propagation time varies so you'd need to consult service specific RBAC documentation.

The exception to this would be using AAD groups to manage permissions. Group membership is baked into the token, so if you add an identity to a group with a specific permission a new token would be required to use that permission.

Hopefully this helps. Please let me know if you have other questions.

**Comment by RayGHeld** [comment]
Thanks for the answer.  I understand there isn't a way to force a refresh of the token.  What I'm experiencing is once a permission is added ( oauth 2 permission grant on the service principal ) I have to wait 24 hours from the last time a token was acquired to get a token with that permission in it.  Since the library isn't using a scope parameter ( it is going to the v1.0 endpoint ), I think it is just looking for a token for that resource in the cache ( in this case, a VM ) and just returning that until it expires and then requests a new token, which will then have my added permission.

**Comment by schaabs** [comment]
A few more details would help me to better understand the issue you're having. 
- What service are you calling? (Perhaps ARM since you said the resource you're trying to get a token for is a VM, but I wasn't sure.)
- Are you using client from the Azure SDK to call that service or calling it directly in your application? 
- What type of Azure host are you running on? (VM, VMSS, App Service, Functions, AKS etc.) 
- Are you using a system assigned or user assigned managed identity? 
- How are you assigning permissions to the identity? (Directly assigning the Role to the identity, or assigning the role to a Group and adding the identity)
