### ISSUE TITLE
[BUG] PluggableCheckpointStoreEventProcessor<EventProcessorPartition> fails to redistribute few or half or even more partitions in Azure event hub for several hours/days

### ISSUE THREAD

**Issue by viskumar-microsoft** [Azure/azure-sdk-for-net#31016]
### Library name and version

Azure.Messaging.EventHubs.Processor 5.7.2

### Describe the bug

I am using a very basic implementation for PluggableCheckpointStoreEventProcessor<EventProcessorPartition> to process events from an Azure Event Hub with 32 partitions. And we are using Azure service fabric to distribute the processing across 10 or so nodes.

I noticed that it stops processing on certain partitions suddenly. I do see that the partition ownership expired for these partitions and it claimed to have moved from one node to another, but there after the ownership blob doesnt show any updates, nor do i see any event flowing for this partition on any node either.

I have verified that there are events on these partitions in the event hub.

### Expected behavior

The processor host should process every single partition consistently

### Actual behavior

It drops processing for some of the partitions randomly.

### Reproduction Steps

Its happening randomly so not sure what is the best way to reproduce it.

### Environment

Azure service fabric cluster
Windows OS: Windows Server 2019 (Standard_D2_v2 10 nodes)
.NET Core 3.1
Visual Studio 2019

**Comment by jsquire** [comment]
Hi @viskumar-microsoft.  Thank you for reaching out and we regret that you're experiencing difficulties.  The common causes of this behavior are:

- The event processing handler is throwing; this will cause the task processing the partition to fault and be restarted at the next load balancing cycle.
- The host is experiencing contention in the threadpool and/or starvation.  Continuations are not scheduled to run consistently, and partitions appear to stall and migrate.
- The storage container in use has soft delete or blob versioning enabled which is preventing the load balancing loop from running on schedule.

To dig in, we'll want to capture SDK logs for the processor, so that we can understand what it is seeing.   We'll want to enable Verbose logs, which will come with a high volume of data, so we'll want to filter that down to a specific set.   An example for doing so can be found [here](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/eventhub/Azure.Messaging.EventHubs/samples/Sample10_AzureEventSourceListener.md#apply-filtering-logic-to-logs).    The logs that we're interested in are:

**_Event Source Name:  “Azure-Messsaging-EventHubs”_**

- All warnings
- All errors
- 6 (Event Receive Start)
- 7 (Event Receive End)
- 8 (Event Receive Error)
- 36 (Event Processor Task Error)
- 37 (EventProcessorPartitionProcessingStart)
- 38 (EventProcessorPartitionProcessingStartError)
- 39 (EventProcessorPartitionProcessingStartComplete)
- 40 (EventProcessorPartitionProcessingStop)
- 41 (EventProcessorPartitionProcessingStopError)
- 42 (EventProcessorPartitionProcessingStopComplete)
- 43 (EventProcessorParitionProcessingError)
- 44 (EventProcessorLoadBalancingError)
- 45 (EventProcessorClaimOwnershipError)
- 103 (EventProcessorLoadBalancingCycleSlowWarning)
- 104 (EventProcessorHighPartitionOwnershipWarning)
- 123 (EventProcessorProcessingHandlerStart)
- 124 (EventProcessorProcessingHandlerComplete)
- 125 (EventProcessorProcessingHandlerError)

It would also be helpful to understand what other handlers were seeing during this time.  Can you help me understand the pattern that you're seeing for `OnInitializingPartitionAsync` and `OnPartitionProcessingStoppedAsync` being triggered?   What is `OnProcessingErrorAsync` seeing during this time?

If possible, it would be helpful to see the code for your processor.
