### ISSUE TITLE
[BUG]Module crash when used over IIS but not on IIS Express

### ISSUE THREAD

**Issue by FranckSix** [Azure/azure-sdk-for-net#31070]
### Library name and version

Azure.Identity 1.6.1

### Describe the bug

I using the module _Azure.Security.KeyVault.Secrets_ need _Azure.Identity_ All working great when hosted under IIS Express. But when I host the project on IIS Local the module crash.

> Azure CLI authentication failed due to an unknown error. See the troubleshooting guide for more information. https://aka.ms/azsdk/net/identity/azclicredential/troubleshoot 'az' is not recognized as an internal command
> or external, an executable program or a batch file.

### Expected behavior

Retreive Secret Value from KeyVault

### Actual behavior

Exception was thrown

### Reproduction Steps

Add address in Web.Config
Host on IIS (not IIS Express)
[WebAppKeyVault.zip](https://github.com/Azure/azure-sdk-for-net/files/9551336/WebAppKeyVault.zip)

### Environment

Windows 11 Enterprise 21H2
IIS 10,0,22000.856
Visual Studio 2022 Enterprise 4.8.04161

**Comment by jsquire** [comment]
Hi @FranckSix.  Thank you for reaching out and we regret that you're experiencing difficulties.  It would be helpful if you could provide more context around how your application is using the KeyVault client - a code snippet would be appreciated, as would a full stack trace.

From the available information, this would seem to be an exception from Azure.Identity, likely due to `DefaultAzureCredential` attempting to authorize with the Azure CLI credential, as described in [this example of authentication flow](https://github.com/Azure/azure-sdk-for-net/tree/main/sdk/identity/Azure.Identity#defaultazurecredential).   

We would suggest testing by configuring the types of auth that DefaultAzureCredential uses by passing a [DefaultAzureCredentialOptions] instance that removes Azure CLI credential.   Alternatively, you may want to consider selecting just the type of authentication that your application should use and passing the specific [Azure.Identity credential type](https://github.com/Azure/azure-sdk-for-net/tree/main/sdk/identity/Azure.Identity#credential-classes) for that scenario.

**Comment by jsquire** [comment]
At this point, I think the question that we want to answer is "what credential type do we want to use in IIS?"    Thus far, it seems that `DefaultAzureCredential` is following its documented flow for credential types, and that many are not supported in the host environment.

The latest exception that you're seeing is due to the [Environment Variables] used by `DefaultAzureCredential` via `EnvironmentCredential` have not been defined.   More information can be found [here](https://github.com/Azure/azure-sdk-for-net/tree/main/sdk/identity/Azure.Identity#environment-variables).

**Comment by FranckSix** [comment]
Hi @jsquire,

I think I put my finger on it. Under IISExpress we seem to run under the local account authenticated on Windows. So because I have access to Azure, the authentication works. But under IIS, is the user associated with the Pool is used. Forcibly this account does not have access to Azure and the authentication fails.

I would have to create a token that would allow me to connect via the application. A bit like the identity managed by the Azure App. Is it possible ?

Also I get a timeout with managed authentication when my application is deployed under Azure. Is there something that can cause this behavior?

Thanks!

**Comment by jsquire** [comment]
> I would have to create a token that would allow me to connect via the application. A bit like the identity managed by the Azure App. Is it possible ?

I'd recommend taking a look at the [ClientSecretCredential](https://docs.microsoft.com/dotnet/api/azure.identity.clientsecretcredential?view=azure-dotnet) which allows you to create an application -specific identity in AAD. 

> Also I get a timeout with managed authentication when my application is deployed under Azure. Is there something that can cause this behavior?

Most often, this happens when running in a host environment that doesn't have a managed identity endpoint.   Without a stack trace and deeper understanding of your host, that's as much as I can speculate.
