### ISSUE TITLE
[BUG]Get TenantPolicyResponse will encounter a FormatException

### ISSUE THREAD

**Issue by dvbb** [Azure/azure-sdk-for-net#31127]
### Library name and version

Azure.ResourceManager.Subscription

### Describe the bug

When using a TenantResource to get a GetTenantPolicyResponseResource, it will splice `tenant`'s id: `/` and `/providers/Microsoft.Subscription/policies/default`, so spliced id is `Id:  //providers/Microsoft.Subscription/policies/default`, and then it will throw:
```
System.FormatException : The ResourceIdentifier must start with /subscriptions/ or /providers/
```

### Expected behavior

 spliced id is Id: `/providers/Microsoft.Subscription/policies/default`

### Actual behavior

 spliced id is Id: `//providers/Microsoft.Subscription/policies/default`

### Reproduction Steps

```
ArmClient Client = GetArmClient();
var tenants = await Client.GetTenants().GetAllAsync().ToEnumerableAsync();
var tenantPolicyResponse = tenants.FirstOrDefault().GetGetTenantPolicyResponse();
```

**Comment by ArcturusZhang** [comment]
The root cause of this issue is that we are concating new parts to the resource identifier using strings, instead we should use some method like `Append` in the `ResourceIdentifier` class to do that, in this way, we could avoid concating issues like this.

Issue also tracking here: https://github.com/Azure/autorest.csharp/issues/2537
