### ISSUE TITLE
ShareDirectoryClient.Exists boolean value not implemented if folder does not exist

### ISSUE THREAD

**Issue by WillGoldLO** [Azure/azure-sdk-for-net#31143]
In my experience using ShareDirectoryClient.Exists(), if the folder does not exist in the share, I am getting a 400 AzureResponse exception thrown instead of a false which I would intuitively think should be the result in this case.

var shareClient = GetFileShareClient(connectionString, shareName);
var x = shareClient.Exists();  -- exception thrown here

        private static ShareClient GetFileShareClient(string connectionString, string shareName)
        {
            return new ShareClient(connectionString, shareName.ToLower());
        }

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bb9aaba9-1334-3c24-de44-79bea30cfa16
* Version Independent ID: 2b1e5148-edd0-67e1-f493-29ac03bb36d3
* Content: [ShareDirectoryClient.Exists(CancellationToken) Method (Azure.Storage.Files.Shares) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/azure.storage.files.shares.sharedirectoryclient.exists?view=azure-dotnet)
* Content Source: [xml/Azure.Storage.Files.Shares/ShareDirectoryClient.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Azure.Storage.Files.Shares/ShareDirectoryClient.xml)
* Service: **azure**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by amnguye** [comment]
An HTTP Status Code of 400 does not mean that the Resource does not exist, it means that it was a Bad Request (It does not show if the Resource exists or not). ShareDirectoryClient.Exists() would return false if it got a 404 error of file error code `ParentNotFound`, `ShareNotFound` or `ResourceNotFound`.

What's the error code that came along with the 400? Because that would tell you what's going on when the request sends out to check if a file exists and the problem with the request, and probably how to resolve your issue.

**Comment by amnguye** [comment]
Also see this page for the possible 400 error codes that could have came back.
https://docs.microsoft.com/en-us/rest/api/storageservices/file-service-error-codes

**Comment by WillGoldLO** [comment]
The message is not listed on the storage service error codes page that you
referenced.  This error codes page also refers to "File service error
codes" and the object I am working with is a
"Azure.Storage.Files.Shares.ShareClient".  This documentation is quite
unclear as to differences in the classes used to access and work with Azure
shares, blobs, files, folders, and other structures to be accessed or
tested for existing via REST calls.  As trivial as checking for the
existence of a folder inside of a share sounds, the documentation is vague
and misleading at best and "shareClient.Exists()" is the best method I
could find to accomplish my task.


On the line "var x = shareClient.Exists();"
When the share does exist but the folder in that share does not, this is
the full exception thrown:

[image: image.png]



Alternatively, when the folder DOES exist, the value of the response in the
variable "x" is this:
[image: image.png]

**Comment by WillGoldLO** [comment]
I am using the Azure SDK for .NET and the code is in C#.  This is not a
REST API call.

My original request should have referenced this page:
https://docs.microsoft.com/en-us/dotnet/api/azure.storage.files.shares.shareclient.exists?f1url=%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(Azure.Storage.Files.Shares.ShareClient.Exists)%3Bk(DevLang-csharp)%26rd%3Dtrue&view=azure-dotnet

**Comment by amnguye** [comment]
> This error codes page also refers to "File service error codes" and the object I am working with is a "Azure.Storage.Files.Shares.ShareClient".

The reference page for the error codes is relevant. If you're using a Share Client, these are the error codes that you could get from the storage service. Share Client requests are from the "File service". I hope that clears up that confusion.

>This documentation is quite unclear as to differences in the classes used to access and work with Azure shares, blobs, files, folders, and other structures to be accessed or tested for existing via REST calls.

This documentation page regarding the specific method is not the right place to describe the SDK and how the classes work in general. This simply states in a concise manner what this specific method does, if we threw in a full description on how each class work and the differences between this and other classes, that would be unnecessary.

https://docs.microsoft.com/en-us/dotnet/api/overview/azure/storage.files.shares-readme

>  As trivial as checking for the existence of a folder inside of a share sounds, the documentation is vague and misleading at best and "shareClient.Exists()" is the best method I could find to accomplish my task.

I'm confused what you mean by the documentation for Exists is vague... reading through the description.

![image](https://user-images.githubusercontent.com/48961492/190468559-f90bfd2c-d955-40e8-abd1-d7e96b9947cc.png)

it says that it will check the "associated directory exists in the share on the storage account". Also you haven't stated your full scenario or task, or else we can't help you further find out how best to help resolve your scenario.

Looks like any images you pasted in your message did not get attached properly, I would recommend retrying because all that is shown is "[image: image.png]" for any image attached.

> I am using the Azure SDK for .NET and the code is in C#.  This is not a
REST API call.

Understood. The request you made using the `ShareClient.Exists()` which makes a REST API call to Get Properties to check if the Share exists. Essentially you are making a REST API call using the SDK.

> which I would intuitively think should be the result in this case.

As stated before, since you received back a `400` error code, which means it was a `Bad Request` Http Error code, which means that the service was not able to comprehend the request sent, and could not check whether or not the directory existed. We need to throw back this 400 error code because, passing back false or true would not be correct because we actually did not get the message from the service if the directory exists or not.

**Comment by WillGoldLO** [comment]
After some additional research and digging I was able to determine that I
was not using the proper object to detect a Directory in a Share.

I have altered my code to accomplish the task needed and you can close this
request.  If someone could make the concepts around the differences between
a share and a folder or other structure in that share more clear it might
help future developers avoid the same confusion that I experienced.

The following code is what I found to work for my purpose:

            var shareClient = GetFileShareClient(connectionString,
shareName);

*var directoryClient =
shareClient.GetDirectoryClient(folderName.ToLower());*            return*
directoryClient.Exists();*

Please close this request as I do not believe there is an issue with the
SDK. It was my understanding of the objects.

Thank you
