### ISSUE TITLE
Code tags are not displaying properly on this page

### ISSUE THREAD

**Issue by DavidKlempfner** [Azure/azure-sdk-for-net#31156]
The < code > tags are not working (using most up to date version of Chrome).
This is what I see (without the spaces before and after ampersand):

Gets or sets & lt;code & gt;true&lt;/code & gt; to enable client affinity;  & lt;code & gt;false & lt;/code & gt; to stop sending session affinity cookies, which route client requests in the same session to the same instance. Default is 
 & lt;code&gt;true & lt;/code & gt;.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c89f7c02-ca6c-3a95-b967-b8ca3e80e269
* Version Independent ID: d1c50b62-bbc7-304f-1313-65266458bdaa
* Content: [Site.ClientAffinityEnabled Property (Microsoft.Azure.Management.WebSites.Models) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.management.websites.models.site.clientaffinityenabled?view=azure-dotnet)
* Content Source: [xml/Microsoft.Azure.Management.WebSites.Models/Site.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.Management.WebSites.Models/Site.xml)
* Service: **app-service**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by ArthurMa1978** [comment]
Thank you for reaching out to us about the Azure SDK for .NET. Unfortunately, this issue is related to the service side and not the SDK side, so we are not able to help you with it. Therefore, we are closing this issue for now. If you need more assistance, please [open an Azure support request](https://docs.microsoft.com/azure/azure-portal/supportability/how-to-create-azure-support-request). We apologize for any inconvenience this may cause you.

We value your feedback and we want to make sure that your problem is solved. If you think that we have misunderstood your issue or closed it incorrectly, please feel free to comment on this thread and reopen the issue. We will be happy to assist you further. Thank you for your understanding and cooperation.

**Comment by DavidKlempfner** [comment]
I'm not sure what you mean by service side/SDK side, I'm talking about an issue on the website.
https://learn.microsoft.com/en-us/dotnet/api/microsoft.azure.management.websites.models.site.clientaffinityenabled?view=azure-dotnet has a link at the bottom that says "Submit and view feedback for This Page".
That is what I have done. There is an error on that page to do with the display of the code, so I am providing feedback about that.
