### ISSUE TITLE
[BUG] Incorrect exception type thrown for blobcontainerclient.createifnotexists()

### ISSUE THREAD

**Issue by ShreeShivaTejaJuluri** [Azure/azure-sdk-for-net#31163]
### Library name and version

Azure.Storage.Blobs v12.13.0

### Describe the bug

We are trying to create a container client from a storage account that doesnt exist in the following way.
storageAccountConnectionString is dummy here.

BlobServiceClient blobServiceClient = new BlobServiceClient(storageAccountConnectionString);
BlobContainerClient containerClient = blobServiceClient.GetBlobContainerClient("blobName");
containerClient.CreateIfNotExists();

We are getting 'The remote name could not be resolved' exception as expected.
Ideally we expect AzureRequestFailed exception as per [Link](https://docs.microsoft.com/en-us/dotnet/api/azure.storage.blobs.blobcontainerclient.createifnotexists?view=azure-dotnet), but we are getting System.Aggregate Exception with 6 internal retries.
Can you please help why we are not observing AzureRequestFailed exception? 

### Expected behavior

We are expecting AzureRequestFailed exception

### Actual behavior

We are observing System.Aggregate exception

### Reproduction Steps

Use dummy storageAccountConnectionString and implement the following code.

BlobServiceClient blobServiceClient = new BlobServiceClient(storageAccountConnectionString);
BlobContainerClient containerClient = blobServiceClient.GetBlobContainerClient("blobName");
containerClient.CreateIfNotExists();

**Comment by amnguye** [comment]
Because the storage account does not exist (or is a dummy in this case), when we go to send the request we will get back a Bad Connection attempting to request to a URL endpoint that does not exist. That doesn't necessarily mean that the storage account (or container) doesn't exist, it means that the connection or authentication was bad.

We cannot throw back a false if we were not able to initialize a connection to the service or it the authentication was invalid. It doesn't actually necessarily mean the storage account (or account does not exist), because this behavior would be created if you didn't have internet connection or if you gave us a malformed URL.

If you're trying to see if the storage account exists I would suggest using the [Management SDK](https://github.com/Azure/azure-sdk-for-net/tree/main/sdk/storage/Azure.ResourceManager.Storage). And then check if the container exists. Unfortunately there's no way to do this in one API call since each type of resource lives in a different REST API surface.

**Comment by ShreeShivaTejaJuluri** [comment]
We are not trying to see if the storage account exists. We are bothered with the type of the exception the SDK is giving. When we perform exception.GetType(), we expect AzureRequestFailed exception as per [Link](https://docs.microsoft.com/en-us/dotnet/api/azure.storage.blobs.blobcontainerclient.createifnotexists?view=azure-dotnet), but we are getting System.Aggregate Exception

**Comment by amnguye** [comment]
True, the documentation should be updated to state that "A RequestFailedException will be thrown if a storage service error is thrown." Instead of any failure. The error you're getting is thrown by Azure.Core underneath.

**Comment by ShreeShivaTejaJuluri** [comment]
Can you please summarize what all types of exception can occur apart from AzureRequestFailedException during blobcontainerclient.createifnotexists() call so that we can handle those error types separately?

**Comment by amnguye** [comment]
The ask is to go through all the documentation and every API, and all the dependencies and see what exceptions each exception is thrown, all their error codes (including general exceptions from `System`)? That seems a little excessive.

I empathize with the intention to cover all exception cases, however for us to document every possible exception case that does not get thrown by our library but by a dependency, seems a lot to maintain as dependencies can add more exception error codes. We do document our dependencies is the Nuget library, and those dependencies do document the exceptions.

We will take it into consideration to how to best document all the exceptions that can be thrown, to best help with exception handling.

**Comment by ShreeShivaTejaJuluri** [comment]
Ok. Thanks for your help
