### ISSUE TITLE
ARM API returns wrong endpoints for Synapse Workspaces when querying Sql Servers

### ISSUE THREAD

**Issue by smartguest** [Azure/azure-sdk-for-net#31182]
### Library name and version

N/A

### Describe the bug

When looking up SQL Server resources via a REST call, using the query "where type == microsoft.sql/servers", any Synapse Servers returned have an incorrect endpoint that does not work when trying to connect to it.

linked issue here: https://github.com/microsoft/azuredatastudio/issues/20180

### Expected behavior

The entry for the returned Synapse Workspace from the microsoft.sql/servers resource API call should have the endpoint: 

<synapse-workspace-name>.azuresynapse.net or similar (in our case, it is .sql.azuresynapse.net)

### Actual behavior

The entry for the returned Synapse Workspace from the API call is instead this:

<synapse-workspace-name>.database.windows.net

which is correct for general SQL servers, but it is not valid for Synapse Workspaces.

### Reproduction Steps

Add arm-resourcegraph node module to a project.

Attempt to make a resources query call using the query posted above.

See the returned server result objects and its fully qualified domain name properties, ones for any Synapse Workspaces will be incorrect.

**Comment by jsquire** [comment]
Hi @smartguest.  Thank you for reaching out and we regret that you're experiencing difficulties.  Unfortunately, this repository is focused on the Azure SDK for .NET - we're unable to assist with other Azure issues.  Since what you're describing appears to be related to the REST API of the service itself and not one of the SDKs, your best path forward would be to [open an Azure support request](https://docs.microsoft.com/azure/azure-portal/supportability/how-to-create-azure-support-request).

I'm going to close this out; if I've misunderstood what you're describing, please let us know in a comment and we'd be happy to assist as we're able.
