### ISSUE TITLE
[Synapse] Remove convenience layer in Azure.Analytics.Synapse.AccessControl

### ISSUE THREAD

**Issue by wonner** [Azure/azure-sdk-for-net#31194]
### Library name

Azure.Analytics.Synapse.AccessControl

### Please describe the feature.

The convenience layer in Azure.Analytics.Synapse.AccessControl just initial test work for onboarding to LLC. It's incomplete and abandoned. This convenience layer doesn't release to customers before, so it's safe to remove. In the future, we will consider onboarding to DPG.

related PR: https://github.com/Azure/azure-sdk-for-net/pull/31126

**Comment by pshao25** [comment]
@KrzysztofCwalina @tg-msft we added convenience layer before for experimental purpose. Now service team wants to remove them. Could you check out this [PR](https://github.com/Azure/azure-sdk-for-net/pull/31126) to see if it is OK?

**Comment by tg-msft** [comment]
Based on the Beta usage numbers at https://www.nuget.org/stats/packages/Azure.Analytics.Synapse.AccessControl?groupby=Version&groupby=ClientName, I think it's fine to make this change.

We should always take these on a case by case basis though because the customer impact of switching from models to protocol only could be very painful if we have a lot of Beta adopters.  While the bar to make changes during a Beta is much lower, we still might want to dial conveniences for select champion scenarios or find other ways to minimize pain during the transition.
