### ISSUE TITLE
[QUERY] Internal_BatchDeleteBlob operation causes a lot of errors when soft-delete is enabled on blob storage

### ISSUE THREAD

**Issue by JeroenJSmit** [Azure/azure-sdk-for-net#31388]
### Library name and version

Azure Blob Storage

### Query/Question

From August 11th on we are experiencing a lot of exceptions on Azure Storage Blobs when soft-delete is enabled. 
The default retention policy is set to 7 days and soft-delete has been enabled, also with the default 7 days to keep deleted blobs.
Currently there is only one container ($logs) which doesn't hold a lot of data but the number of exceptions is quite large.

As an example the following two screenshots showing what started on the mentioned data, without having done any changes/deployments to our environments:

![image](https://user-images.githubusercontent.com/4172510/191918795-cabe90a0-c3f3-4cde-af9e-9947ce7f73be.png)

![image](https://user-images.githubusercontent.com/4172510/191919013-179d7ede-5e41-4244-90a5-4df763413124.png)

During that same time, on all environments where we have this feature enabled, we started receiving automatic "dependency degradation" alerts on App Services using this storage account (mainly table storage though) which is why we disabled soft-delete amd the effect can be seen immediately in these screenshots. As a test we re-enabled soft-delete again a few weeks ago and the same exception pattern (and alerts) re-appeared.

Expected behavior:
Blobs get soft-deleted after 7 days and permanently deleted after another 7 days without exceptions and impact on the storage account.

Actual behavior:
It looks like the daily cleanup process keeps trying to delete already soft-deleted blobs, causing a lot of exceptions which also seems to have impact on table and blob operations executed from our apps.

If this is indeed a bug, where would the best place be to report this?

### Environment

Azure Storage Account
StorageV2 (general purpose v2)

Exceptions seen:
- on both RA-GRS and LRS redundancy setup
- in different locations: West-Europe, EUS2
- in dev/test environments and production environments

**Comment by jsquire** [comment]
Hi @JeroenJSmit.  Thank you for reaching out and we regret that you're experiencing difficulties.  Unfortunately, this repository is focused on the Azure SDK for .NET - we're unable to assist with other Azure issues.  Since what you're describing appears to be related to the Storage service itself and not one of the SDKs, your best path forward would be to [open an Azure support request](https://docs.microsoft.com/azure/azure-portal/supportability/how-to-create-azure-support-request).

I'm going to close this out; if I've misunderstood what you're describing, please let us know in a comment and we'd be happy to assist as we're able.
