### ISSUE TITLE
EventDataBatch.TryAdd does not copy buffer to batch as documentation indicates

### ISSUE THREAD

**Issue by Stabzs** [Azure/azure-sdk-for-net#31395]
### Library name and version

Azure.Messaging.EventHubs v5.7.2

### Describe the bug

The [documentation](https://learn.microsoft.com/en-us/dotnet/api/azure.messaging.eventhubs.producer.eventdatabatch.tryadd?view=azure-dotnet#azure-messaging-eventhubs-producer-eventdatabatch-tryadd(azure-messaging-eventhubs-eventdata)) for `Azure.Messaging.EventHubs.Producer.EventDataBatch.TryAdd` has the following remarks:

> Remarks
> When an event is accepted into the batch, its content and state are frozen; any changes made to the event will not be reflected in the batch nor will any state transitions be reflected to the original instance.

However, when trying to use a shared buffer as the backing source per EventData instance, the data is not persisted in the EventDataBatch

### Expected behavior

```
using var eventDataBatch = await _eventHubClient.CreateBatchAsync();
var buffer = new byte[1024];
while (true)
{
    buffer.Clear();
    buffer = someInput;
    if (!eventDataBatch.TryAdd(new EventData(buffer))
        break;
}
```

I would expect, based on the remark, that during TryAdd, the buffer's contents are serialized into the raw amqp message and added to the batch, allowing it to be reused in the add loop.

### Actual behavior

What I am seeing however is that clearing the buffer is being reflected back into the batch itself, making the use of a buffer completely impossible and causing the above remark to be inaccurate at best and (in my case), quite dangerous.

### Reproduction Steps

See the above.

### Environment

I am seeing the same behavior on Windows, Linux and MacOS, on .NET 6.

**Comment by jsquire** [comment]
Hi @Stabzs.  Thank you for reaching out and we regret that you're experiencing difficulties.  The value that you're passing the `EventData` constructor is of type `ReadOnlyMemory<byte>` which, by contract, offers a guarantee that it will not change and is safe to use as a buffer.   Internally, the body of the serialized message references this read-only memory buffer until it is sent over the network.

That said, it wasn't our intent to allow a side-effect like this and the serialized form is intended to be immutable; we did not account for this specific scenario.  I'll take a look at getting this patched up so the side-effect is no longer possible.

The mitigation, in the meantime, would be to create a new buffer for each `EventData` to honor the contract of `ReadOnlyMemory<T>`

**Comment by Stabzs** [comment]
Thanks for the quick response @jsquire!

Do you have documented guidance on the guarantee of `ReadOnlyMemory<byte>` by chance? My interpretation has always been that the guarantee is for that specific call and that there is no guarantee beyond the specific call, which would make sense whenever you have a reusable buffer that you have to project to `ReadOnlyMemory<T>`. I was expecting the behavior to be similar to `System.Text.Json.JsonSerializer.Deserialize<ReadOnlySpan<byte> utf8Json, ...)` where instead of returning an object, the `ReadOnlyMemory<byte>` was serialized to the amqp payload.

If it helps, the intent is have zero allocations during the serialization of the payload and adding to the batch, and instead allowing the batch itself to allocate what it needs for the raw amqp message.  I can absolutely continue creating intermediary byte arrays in the interim, but being able to use a patched version in the near future would be wonderful since it would avoid the intermediary allocation.

**Comment by jsquire** [comment]
Let me see if I can find a public write-up for ROM<T> where the .NET team talks about the contract.   

In the meantime, I'll mention that the number of allocations isn't likely to change for your scenario if we do add a specific guard.   We'd need to make a defensive copy of the buffer you pass in, which would then serve as where the body of the serialized message points as a buffer.  The main difference would likely be that we'd increase allocations for common case where callers don't mutate the body after creating the event, since we'd have to assume that any `byte[]` is potentially unsafe.

**Comment by Stabzs** [comment]
If there isn't any option for directly writing to the batch output stream, adding the guard doesn't make a lot of sense since like you said, it hurts the common case. That doesn't seem like a useful tradeoff to accommodate this edge case especially if it doesn't meet my optimization goal in the first place.

**Comment by jsquire** [comment]
Apologies for the slow follow-up.   I wanted to let my brain spin on things for a bit, poke at the code, and grab some additional opinions.   Here's where we're at:

I agree your statement "the guarantee is for that specific call".   In this case, since the memory was passed to the `EventData` constructor, and the scope of the "call" is the lifetime of the associated instance.  I verified that this also aligns with the internal guidance that we used when choosing the type.  After asking around, we weren't able to locate documentation with explicit guidance for the read-only memory contract.  I opened a request for the Docs team to consider adding some.  

Where it gets interesting is that, in this scenario, we explicitly state that the `EventData` is no longer relevant to the batch after `TryAdd` completes.   I believe your perspective here is the correct one - it should not matter what you do with the buffer at this point, the batch should be fully immutable.  We're not, currently, because "serialization" in this case means "projecting into an intermediate model that our transport library uses" rather than the normal connotation of "translated this into a set of bytes to put on the wire."   To avoid allocations, we're not making a defensive copy of the event body among some other optimizations which is where we violated our own intent.

The correct behavior is expressed by the docs; we overlooked this scenario and are going to patch it up.   I've got some thoughts that I want to play with around to avoid making a direct copy always to minimize impact on the common case.   It'll take me a bit to work through and given the potential impact, I also want to leave time to do a full set of stress/reliability runs.   

This won't make the October release, but we'll aim to include it in November.  For now, I'm going to reclassify as a bug and schedule it.

**Comment by Stabzs** [comment]
Makes sense @jsquire and I appreciate the thoughtful response! Looking forward to the November release :).

**Comment by jsquire** [comment]
Thank you all for the perspectives and discussion in the prototype PR (#31845).  The outcome of those conversations ended in agreement that the performance cost of making a defensive copy outweighs the desire to guarantee the batch is fully immutable.   Rather than doing so, we've updated the documentation to call out that any memory buffers held by the event are referenced by the batch and must remain available and unchanged until the batch is disposed.   (see: #3204)

Closing this out.
