### ISSUE TITLE
[BUG] IMDS token endpoint timeout was changed from 3s to 1s without consulting the IMDS IdentityProvider plugin owners

### ISSUE THREAD

**Issue by isaacbanner** [Azure/azure-sdk-for-net#31452]
### Library name and version

Azure.Identity 1.7.0

### Describe the bug

At some point over the last two years, the IMDS token acquisition flow was updated to the current model used by ImdsManagedIdentitySource and, as a part of this new model, the token acquisition timeout was updated to 1 second, as configured in `DefaultAzureCredentialFactory` (see `InitialImdsConnectionTimeout` on line 105). 

This is in direct contrast to the **_three-second_** timeout that the Managed Identity team previously updated this sdk to observe back in [2020](https://github.com/Azure/azure-sdk-for-net/commit/eae6c13105591ecaaf486c32a98e7e5261ba5c5b#diff-9ab640e69721a96e546d2eb8632016417f6a9943ca9b1ada0e738d8434c895cc) (see `AzureVmImdsProbeTimeoutInSeconds`). As far as we're aware, the MI/IMDS team were not involved in the conversation to change this timeout and now we're receiving tickets from partners complaining that these calls are timing out and failing to acquire a token. 

### Expected behavior

The timeout for calls to the IMDS token endpoint should be three seconds.

### Actual behavior

The timeout for calls to the IMDS token is one second.

### Reproduction Steps

N/A

### Environment

Azure VM/VMSS

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by christothes** [comment]
Hi @isaacbanner - Is the 3 second timeout guidance is documented somewhere? If so, a link would be greatly appreciated.

**Comment by isaacbanner** [comment]
There isn't a published SLA for token requests on IMDS that I know of - I can engage the IMDS team if you'd like a more concrete promise on that latency. I mention 3 seconds above because that's what we changed it to intentionally two years ago, and that configuration from our team is no longer being observed by the sdk. Is there documentation anywhere for why this was pulled down to 1s from 3?

**Comment by christothes** [comment]
The timeout is an implementation detail rather than a guarantee, so this would not be formally documented. However, [here is the PR](https://github.com/Azure/azure-sdk-for-net/pull/24328) that explains it a bit. The intent is to make it as short as possible while allowing enough time for the endpoint to make a connection (which normally should be very fast). Connection attempts are also retried 3 times, so it should be rare that the endpoint fails to respond after all attempts.

This short timeout should only be used when in the context of the `DefaultAzureCredential` credential chain. In this scenario, there is tension between wanting the connection to be resilient to failures to connect and failing as quickly as possible so that the developer experience is good when running outside of the cloud environment. 

All that said, the timeout is configurable via the following option - 
https://github.com/Azure/azure-sdk-for-net/blob/b96c72d47be6fbe074628a6942dbe7b1759fa638/sdk/identity/Azure.Identity/src/ManagedIdentityClientOptions.cs#L19

**Comment by isaacbanner** [comment]
If this is something that can be modified in the application configuration when using the SDK, then can the error message be updated to reflect this as a potential mitigation? We get support tickets because the error message says the MI service is unavailable, but the issue isn't to do with the identity plugin on the VM - it's usually an issue with the transport layer. 

There was also a change to the error message, which previously indicated that IMDS discovery failed rather than the connection to the Managed Identity endpoint. If we can at least shape the error messaging here to better indicate:

- This is a connection issue between the container and the IMDS host node (or between whatever compute platform and token service is supporting the identity), rather than an issue reaching the Managed Identity service
- This is potentially related to a configuration setting and a widening of the timeout may mitigate the problem

Then I think we can drastically reduce the mis-routed support volume here.
