### ISSUE TITLE
[QUERY] GetContainerGroupsAsync on ResourceGroup

### ISSUE THREAD

**Issue by zhiweiv** [Azure/azure-sdk-for-net#31462]
### Library name and version

Azure.ResourceManager.ContainerInstance 1.0.0

### Query/Question

There are GetContainerGroups and GetContainerGroupsAsync on Subscription level, but there is only GetContainerGroups on ResourceGroup level, no async method, can you add it?

**Comment by xboxeer** [comment]
@zhiweiv subscription.GetContainerGroups is actually different with resourceGroup.GetContainerGroups. subscription.GetContainerGroups is returning a Pageable<ContainerGroupResource> which actually represents an HTTP Rest API call and you'll need to do all the page operation by yourself

On the other hand, resourceGroup.GetContainerGroups returns ContainerGroupCollection, no actual HTTP REST API call is made , but within this ContainerGroupCollection class, you'll find async method such as GetAllAsync, It returns the same Pageable like subscription.GetContainerGroups did. since resourceGroup.GetContainerGroups does not making any actual HTTP REST API calls, it is not necessary for us to add an async version GetContainerGroups method for ResourceGroup.

More story behind that, subscription.GetContainerGroups() lists all container groups by subscription, while resourceGroup.GetContainerGroups.GetAll/GetAllAsync list all container groups by resource group. and resourceGroup.GetContainerGroups has method CreateOrUpdate while subscription.GetContainerGroups() does not.

**Comment by zhiweiv** [comment]
Thanks for the explanation, I can async get container groups on resource group level now.
```
var containerGroups = resourceGroup.GetContainerGroups().GetAllAsync();
await foreach( var containerGroup in containerGroups)
{
    Console.WriteLine(containerGroup.Data.Name);
}
```

**Comment by xboxeer** [comment]
> Thanks for the explanation, I can async get container groups on resource group level now.
> 
> ```
> var containerGroups = resourceGroup.GetContainerGroups().GetAllAsync();
> await foreach(var containerGroup in containerGroups)
> {
>     Console.WriteLine(containerGroup.Data.Name);
> }
> ```

It's so glad your issue is resolved, if you have any other feedback regarding our Azure SDK, feel free to let us know in this [survey](https://www.surveymonkey.com/r/YSYFMFF)
