### ISSUE TITLE
partition availability and sdk behavior 

### ISSUE THREAD

**Issue by spelluru** [Azure/azure-sdk-for-net#31556]
### Library name and version

Azure.Messaging.EventHubs

### Query/Question

Provided the client must have consistency, which is being achieved through adding the partitionKey when sending the message, the following things are unclear:

Why does a partition become not available, and is there any exception/notification forwarded to the client by the sdk, so the client is aware a partition is down
In case message A was sent with partitionKey PK and the partition becomes unavailable, when a new message B with the same partitionKey PK is published, to which partition will it end

**Comment by jsquire** [comment]
Hi @ivi-hamiti.  Thank you for reaching out.   This inquiry is really more focused on service functionality, as the client does not have insight or influence.   From the client perspective:

- When you call `SendAsync`, the events are packaged together in an envelope that is stamped with a partition key and delivered to the Event Hubs gateway.  If the gateway acknowledges receipt, the call returns without an exception and the Event Hubs service owns responsibility for ensuring that those events are committed to the correct partition.

- Since the client is communicating with the gateway, it has no awareness of the state of any partition node nor which partition that Event Hubs chooses to route events to.

That said, let's take a look at the Event Hubs service guarantees:

- If the gateway acknowledges delivery of a events, that indicates it has created multiple copies of that data to reliable storage and in the case of failure the data will not be lost.

- Partition keys have a stable association with partitions.  If a partition is unavailable, the gateway will hold onto the events for it and ensue they are delivered once the partition can receive them.   Given the highly redundant nature of the Event Hubs infrastructure, a partition is unlikely to be unavailable for more than seconds.

- In the posed scenario for A and B, both will end up at the same partition, as the association between the partition key and partition is stable.  For A, there would be a longer-than-typical delay in the time from when the client `SendAsync` call completed and A was available to be read.

> Why does a partition become not available

This is something that the Event Hubs service team would need to answer.   I suspect that it would be the typical reasons for a hosted service:  the host machine was being patched/rebooted, the partition migrated to a new host to balance load, an equipment failure caused a host migration.
