### ISSUE TITLE
The processor instance ... owns a higher than recommended number of partitions for average workloads

### ISSUE THREAD

**Issue by spelluru** [Azure/azure-sdk-for-net#31555]
### Library name and version

Azure.Messaging.EventHubs

### Query/Question

Hi,

With the latest SDK we started getting the below error:

Azure.Messaging.EventHubs[104] The processor instance with identifier '696b32d5-0a4c-4a9f-b79e-7aabe9456f8a' for Event Hub: xxx-xxxxxxx-xxxx-xxxxxx-xxxxx owns a higher than recommended number of partitions for average workloads. Owning too many partitions can cause slow performance and stability issues. Consider monitoring performance and partition ownership stability to ensure that they meet expectations. If not, adding processors to the group may help. Total partition count: '4'. Owned partition count: '4'. Maximum recommended partitions owned: '3'.

I cannot see any documentation regarding it, especially for the part "Consider monitoring performance and partition ownership stability to ensure that they meet expectations" - what exactly is unstable/slow in case too many partitions are handled by 1 EventProcessorClient?

Additionally, why is there no way to suppress this? Standard Event Hubs do not allow changing the partition count after creation, so we are somehow punished all of a sudden for something we cannot even fix, or?

Br,
Deyan

**Comment by spelluru** [comment]
Moving the issue to SDK repo. Here's the original issue. 
https://github.com/MicrosoftDocs/azure-docs/issues/99052

**Comment by jsquire** [comment]
Hi @deyanp.  Thank you for reaching out and we regret that you're experiencing difficulties.  This warning indicates that your `EventProcessorClient` instance is responsible for processing more partitions than our heuristic predicts that your host can handle reasonably.   This is something that will differ by host, application, processing being done, and event composition.   If you're not seeing issues, you can safely ignore the warning.

> what exactly is unstable/slow in case too many partitions are handled by 1 EventProcessorClient?

From the [Troubleshooting guide](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/eventhub/Azure.Messaging.EventHubs/TROUBLESHOOTING.md#too-many-partitions-are-owned)

```text
The event processor works in a concurrent and highly asynchronous manner. Each partition owned by the processor is hosted 
by a dedicated background task. The processor infrastructure also relies on a background task to perform health checks, error 
recovery, and load balancing activities. Each of these tasks relies on continuations for asynchronous operations being scheduled 
in a timely manner in order to make forward progress.

When a processor owns too many partitions, it will often experience contention in the thread pool leading to starvation. During 
this time, continuations will start to queue while waiting to be scheduled causing stalls in the processor. Because there is no 
fairness guarantee in scheduling, some partitions may appear to stop processing or load balancing may not be able to update 
ownership, causing partitions to "bounce" between owners.

It is generally recommended that an event processor own no more than three partitions for every 1 CPU core of the host. It is 
often helpful to start a ratio of 1.5 partitions for each CPU core and test increasing the number of owned partitions gradually to 
measure what works best for the specific application.
```

> Standard Event Hubs do not allow changing the partition count after creation

This recommendation from the client does not imply changing the partition count on your Event Hub, rather it suggests adding an additional `EventProcessorClient` instance to the consumer group so that the work is spread between hosts.

> Additionally, why is there no way to suppress this? 

If these warnings are not interesting or helpful to your application, I'd suggest filtering them.   Azure SDK logs are emitted as ETW events for which a listener has to subscribe.   Most listeners have the option to filter by level or Id.   The ETW sources for the Event Hubs client library can be found [here](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/eventhub/Azure.Messaging.EventHubs/samples/Sample10_AzureEventSourceListener.md#finding-the-desired-events).

**Comment by deyanp** [comment]
Thanks for the info, @jsquire !

We happened to create the event hubs with 8 partitions (for futureproofing) but due to low volume of messages 1 EventHubProcessor instance is more than enough ....

**Comment by spelluru** [comment]
Thank you @jsquire
