### ISSUE TITLE
[BUG] AMQP 5671 communication with a SSL/TLS header

### ISSUE THREAD

**Issue by arunprakashn** [Azure/azure-sdk-for-net#31575]
### Library name and version

Azure.Messaging.Servicebus 7.8.0

### Describe the bug

I am using the Azure Service Bus .net sdk 7.8.0 Azure.Messaging.ServiceBus. I am facing an issue w.r.t the firewall rules. My application uses transport type as amqptcp. I requested the outbound ports 5671,5672 be opened for the Service bus hostname in the firewall. I deployed this application to one customer and it is working fine. For another customer where the firewall shows 5671/2 are open, the application registers connection error logs. The firewall team says the application is sending SSL packets over 5671 which is a non-standard way of doing things. I am unable to understand why the same application is behaving differently in two places. The firewall team says TCP/5671 is open but there cannot be SSL headers or packets over it. The firewall is Layer7 PaloAlto for both customers. I tried to show the Microsoft documentation that it is AMQP over TLS and they still say SSL packets over 5671 are disallowed. Please throw some light.

### Expected behavior

I think SSL header should not be sent with AMQP 5671

### Actual behavior

SSL header is sent 

### Reproduction Steps

I am using the Azure Service Bus .net sdk 7.8.0 Azure.Messaging.ServiceBus. I am facing an issue w.r.t the firewall rules. My application uses transport type as amqptcp. I requested the outbound ports 5671,5672 be opened for the Service bus hostname in the firewall. I deployed this application to one customer and it is working fine. For another customer where the firewall shows 5671/2 are open, the application registers connection error logs. The firewall team says the application is sending SSL packets over 5671 which is a non-standard way of doing things. I am unable to understand why the same application is behaving differently in two places. The firewall team says TCP/5671 is open but there cannot be SSL headers or packets over it. The firewall is Layer7 PaloAlto for both customers. I tried to show the Microsoft documentation that it is AMQP over TLS and they still say SSL packets over 5671 are disallowed. Please throw some light.

**Comment by jsquire** [comment]
Hi @arunprakashn.   Thank you for reaching out and we regret that you're experiencing difficulties.  The behavior that you're describing is by design and follows the [AMQP specification](http://docs.oasis-open.org/amqp/core/v1.0/os/amqp-core-security-v1.0-os.html#toc) regarding TLS.  _(section 5.2)_   

is also consistent with the [Service Bus protocol guide](https://learn.microsoft.com/azure/service-bus-messaging/service-bus-amqp-protocol-guide) which states:

```text
The current Service Bus implementation only allows CBS in conjunction with the SASL method 
"ANONYMOUS." A SSL/TLS connection must always exist prior to the SASL handshake.
```

There's not much more insight that I can offer from the client library perspective, as the client is following the Service Bus requirements for connectivity.  Since this line of inquiry is related to the those requirements and not the SDKs, your best path forward would be to [open an Azure support request](https://docs.microsoft.com/azure/azure-portal/supportability/how-to-create-azure-support-request) if you'd like to discuss further or have follow-up questions that require more specific knowledge.

I'm going to mark this as addressed, but feel free to unresolve if there are any client-specific topics that you'd like to continue discussing.
