### ISSUE TITLE
[Featue Req] - Form Recognizer KeyValuePair Object missing Boundary Box Collection 

### ISSUE THREAD

**Issue by NSCapC** [Azure/azure-sdk-for-net#31577]
### Library name and version

Azure.AI.FormRecognizer 4.0

### Describe the bug

From the DocumentKeyValuePair List of the result object there doens't seem to be a way to get the bounding polygon. Only the Key, Value and confidence seem to be available.

Please add in the ability to retrieve the postiion from the DocumentKeyValuePair  list of the result object

### Expected behavior

Expect to get the position of the KVPs from the DocumentKeyValuePair 

### Actual behavior

Can not get the position from the DocumentKeyValuePair  list of the result object

### Reproduction Steps

Analyze a document with the prebuilt document model and iterate over the KeyValuePairs of the result.

### Environment

Windows server 2016
.Net 4.7.2
Forms Recognizer 3
Azure.AI.FormRecognizer 4.0 Beta 5

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by kinelski** [comment]
Hello @NSCapC,

I brought up this matter to the Form Recognizer service team and, according to them, this is by design. There are no plans to introduce a `BoundingRegions` property in `DocumentKeyValuePair`. You can, however, get the positions of the key and the value separately using their bounding regions:
```cs
DocumentKeyValuePair kvp = ...;
var kvpRegions = new List<BoundingRegion>();

kvpRegions.AddRange(kvp.Key.BoundingRegions);
kvpRegions.AddRange(kvp.Value.BoundingRegions);
```

If you really need a single polygon, you could try to create a box-shaped polygon for the whole key-value pair by taking the min/max x/y of its regions. Be aware that this is a workaround and that the resulting polygon may unintentionally cover other content, though:
```cs
using System.Linq;

DocumentKeyValuePair kvp = ...;
var points = new List<PointF>();

foreach (BoundingRegion region in kvp.Key.BoundingRegions)
{
    points.AddRange(region.BoundingPolygon);
}

foreach (BoundingRegion region in kvp.Value.BoundingRegions)
{
    points.AddRange(region.BoundingPolygon);
}

var pointsX = points.Select(p => p.X);
var pointsY = points.Select(p => p.Y);

float minX = pointsX.Min();
float maxX = pointsX.Max();
float minY = pointsY.Min();
float maxY = pointsY.Max();

var kvpPolygon = new IReadOnlyList<PointF>()
{
    new FloatF(minX, maxY),
    new FloatF(maxX, maxY),
    new FloatF(maxX, minY),
    new FloatF(minX, minY)
};
```
