### ISSUE TITLE
bad text formatting

### ISSUE THREAD

**Issue by chetta19** [Azure/azure-sdk-for-net#31646]
Following text is badly formatted in this page

 &lt;normalized service identity&gt;_&lt;normalized category name&gt;.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 949999ac-4951-1b66-c41d-4df5d3ed334a
* Version Independent ID: f5916372-52bb-634e-584a-dd95d8531739
* Content: [DiagnosticSettingsResource.LogAnalyticsDestinationType Property (Microsoft.Azure.Management.Monitor.Models) - Azure for .NET Developers](https://learn.microsoft.com/en-us/dotnet/api/microsoft.azure.management.monitor.models.diagnosticsettingsresource.loganalyticsdestinationtype?view=azure-dotnet)
* Content Source: [xml/Microsoft.Azure.Management.Monitor.Models/DiagnosticSettingsResource.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.Management.Monitor.Models/DiagnosticSettingsResource.xml)
* Service: **monitoring-and-diagnostics**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by ArthurMa1978** [comment]
Thank you for reaching out to us about the Azure SDK for .NET. Unfortunately, this issue is related to the service side and not the SDK side, so we are not able to help you with it. Therefore, we are closing this issue for now. If you need more assistance, please [open an Azure support request](https://docs.microsoft.com/azure/azure-portal/supportability/how-to-create-azure-support-request). We apologize for any inconvenience this may cause you.

We value your feedback and we want to make sure that your problem is solved. If you think that we have misunderstood your issue or closed it incorrectly, please feel free to comment on this thread and reopen the issue. We will be happy to assist you further. Thank you for your understanding and cooperation.
