### ISSUE TITLE
[BUG] Delivery count is 0

### ISSUE THREAD

**Issue by ljammala** [Azure/azure-sdk-for-net#31651]
### Library name and version

Azure.Messaging.ServiceBus 7.10.0

### Describe the bug

I have a queue and registered handlers to that queue in my code. Everything worked perfectly, but saw a strange behavior yesterday where a message was not "delivered". I can peek the message on Servicebus explorer, but when I trigger a receive, I am getting an alert saying "there are not messages to receive". I tried purging the queue, but getting similar message that "There are no messages to purge". 

![image](https://user-images.githubusercontent.com/4149908/194646907-91d5da15-55b7-464c-a32b-051b71b81974.png)

![image](https://user-images.githubusercontent.com/4149908/194647100-5f7f714b-e49f-4b84-925a-ba4cd7a1f8e0.png)

App Insights also shows that there were no faults with any message sends. 

### Expected behavior

Message is delivered or is faulted with an exception and deadlettered.

### Actual behavior

Delivery count is 0

### Reproduction Steps

Not sure how to reproduce the issue.

**Comment by jsquire** [comment]
Hi @ljammala.  Thank you for reaching out and we regret that you're experiencing difficulties.  Since you're seeing this behavior with Service Bus Explorer as well as with the client library, the behavior that you're seeing is coming from the service.  Unfortunately, that's not something that we're able to assist with in this repository; your best path forward would be to [open an Azure support request](https://docs.microsoft.com/azure/azure-portal/supportability/how-to-create-azure-support-request).

I'm going to mark this as addressed; if I've misunderstood what you're describing, please unresolve and let us know.

**Comment by ljammala** [comment]
Could be please provide some insight as to why a message would not be "received" by a handler? Why would the delivery count be 0? I added another message on this queue and that was received and processed by my client. But this particular message is stuck and won't be "received".

**Comment by jsquire** [comment]
The message cannot be received by a handler if the service is not sending it to the client, which appears to be the case here based on the delivery count and identical behavior in Service Bus Explorer.
