### ISSUE TITLE
[QUERY] How to read Application Insights trace and exception events?

### ISSUE THREAD

**Issue by jbaumbach** [Azure/azure-sdk-for-net#31765]
### Library name and version

Azure.Monitor.Query 1.1.0

### Query/Question

There was an SDK before called `Microsoft.Azure.ApplicationInsights` which apparently could read app insights data. This is exactly what we need. However, it's deprecated and if I try to use it, zero results are returned.

Nuget says this is the lib to get but... all the docs say to connect to some other thing called a "workspace". I looked at that, and it kind of seems like app insights... but it's not. I guess it collects data from virtual machines or something? Its pretty unclear what it is, but it's not app insights.

Note: I tried fooling this lib by using the ID of app insights anyway, and it says "The workspace could not be found".

Can someone please just point out the exact way to use this new library to read from App Insights trace logs? Surely it's still possible, yes?

### Environment

Azure

**Comment by jsquire** [comment]
@scottaddie :  Do you have insight that you can share for this?

**Comment by scottaddie** [comment]
@jbaumbach, [Azure.Monitor.Query](https://www.nuget.org/packages/Azure.Monitor.Query/) is the recommended package for querying App Insights data. As noted in [Resource mode support](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/monitor/Azure.Monitor.Query/MigrationGuideApplicationInsights.md#resource-mode-support), the classic resource mode for App Insights is being phased out. You'll need to migrate to the workspace-based resource mode before `Azure.Monitor.Query` will work for you. If migration isn't an option at this time, then you can use [Microsoft.Azure.ApplicationInsights.Query](https://www.nuget.org/packages/Microsoft.Azure.ApplicationInsights.Query). Just be aware that this package has been deprecated in favor of `Azure.Monitor.Query`.

`Azure.Monitor.Query` is capable of querying trace logs (the `AppTraces` table). See the [Logs query](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/monitor/Azure.Monitor.Query/README.md#logs-query) example. In your case, you'll write a Kusto query for the `AppTraces` table instead of the `AzureActivity` table used in this example.

**Comment by jbaumbach** [comment]
Ah, that worked! Had to "migrate" the App Insights instance to a workspace, but it looks like it left all the old alerts, data, queries, log data, etc. intact and it's still being populated with data by our app. Essentially the data is now magically going to both places. But, pretty painless. 

I had to figure out how to make an Active Directory application registration and grant "Reader" permissions as well.
