### ISSUE TITLE
Formatting feedback

### ISSUE THREAD

**Issue by qqnarwhal** [Azure/azure-sdk-for-net#31821]
There are multiple HTML <br> showing in the paragraphs, those needs to be cleaned up.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c6363043-1703-e15d-1714-a86ccb487c6c
* Version Independent ID: d13379f8-512a-33a0-49ff-26a3ef051d29
* Content: [OSDisk.DeleteOption Property (Azure.ResourceManager.Compute.Models) - Azure for .NET Developers](https://learn.microsoft.com/en-us/dotnet/api/azure.resourcemanager.compute.models.osdisk.deleteoption?view=azure-dotnet-preview)
* Content Source: [xml/Azure.ResourceManager.Compute.Models/OSDisk.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Azure.ResourceManager.Compute.Models/OSDisk.xml)
* Service: **azure**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by kimsey0** [comment]
Also the case at https://learn.microsoft.com/en-us/dotnet/api/azure.resourcemanager.resources.resourcegroupresource.getgenericresourcesasync

**Comment by kimsey0** [comment]
The issue is specifically about SDK documentation, not API documentation. However, I can see that the source code is in the https://github.com/Azure/azure-docs-sdk-dotnet/ repository. For example, the source for [the page I linked above](https://learn.microsoft.com/en-us/dotnet/api/azure.resourcemanager.resources.resourcegroupresource.getgenericresourcesasync), including the incorrectly encoded HTML formatting, is at https://github.com/Azure/azure-docs-sdk-dotnet/blob/fe880000c8e439d3bdf915f1d1ac098e44813e8c/xml/Azure.ResourceManager.Resources/ResourceGroupResource.xml#L516-L516

Would that be a better place to reopen the issue? If so, the _Submit and view feedback for this page_ link at the bottom of the page should perhaps be changed to open an issue in that repository instead of this one.

**Comment by kimsey0** [comment]
Looking one more time at the azure-docs-sdk-dotnet repository, I see that is says _Content provided here is generated from various NuGet packages that provide tooling to interact and manage Azure services._ That makes me think this may be the correct repository after all. @ArthurMa1978, can you clarify?
