### ISSUE TITLE
[BUG] [DataLake] 3 http calls to upload one small document

### ISSUE THREAD

**Issue by tovyhnal** [Azure/azure-sdk-for-net#31836]
### Library name and version

12.12.1

### Describe the bug

When using UploadAsync to upload small document to the server, it does 3 http requests in background. This is unexpected and it has performance  implications.

Here are all the calls:
![image](https://user-images.githubusercontent.com/65427136/196140737-bdccdbff-ce9d-46c7-a48e-7a156282ccba.png)

It also has perf implications compared to Blob SDK client. In half of the cases it is almost 10 times slower:

![image](https://user-images.githubusercontent.com/65427136/196139993-9ddc88df-0c75-44a2-8028-178fe1a67500.png)

### Expected behavior

I would expect, that simple UploadAsync call will do 1 http request to the server. Or at least it can be controlled by some settings.

### Actual behavior

UploadAsync makes 3 http calls to the server.

### Reproduction Steps

            var content = JsonConvert.SerializeObject(new
            {
                Property1 = "123",
                Property2 = "456",
            });

            var stream = new MemoryStream(Encoding.UTF8.GetBytes(content ?? ""));

            var uploadAsync = await fileClient.UploadAsync(stream);

### Environment

Windows 10, .NET6

**Comment by navba-MSFT** [comment]
@tovyhnal Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment]
The Swagger for the ADLS Gen 2 REST APIs is [here](https://github.com/Azure/azure-rest-api-specs/blob/master/specification/storage/data-plane/Microsoft.StorageDataLake/stable/2019-10-31/DataLakeStorage.json). You can check the syntax for the PUT operation.
 
If you’re trying to upload (PUT) using ADLS Gen 2 APIs, below is the flow:
-  [PUT](https://learn.microsoft.com/en-us/rest/api/storageservices/datalakestoragegen2/path/create) to create the file
-  [PATCH](https://learn.microsoft.com/en-us/rest/api/storageservices/datalakestoragegen2/path/update) with action=append to upload the data itself
-  PATCH with action=flush to write the data to the file

This is expected behavior. If you want to see just one single call for Upload Operation, As a workaround, you can use the [Azure.Storage.Blobs](https://www.nuget.org/packages/Azure.Storage.Blobs) package to perform the [UploadAsync](https://learn.microsoft.com/en-us/dotnet/api/azure.storage.blobs.blobclient.uploadasync?view=azure-dotnet) operation. Sample code is [here](https://learn.microsoft.com/en-us/azure/storage/blobs/storage-blob-upload). Hope this helps.

**Comment by tovyhnal** [comment]
Using blob SDK client does not work for me. Does it work for you? 

I am getting:
```
    "error": {
        "code": "MissingRequiredHeader",
        "message": "An HTTP header that's mandatory for this request is not specified.\nRequestId:f94e3b1c-801f-0043-74c6-e2833c000000\nTime:2022-10-18T07:55:19.0289178Z"
    }
```

When digging into it, it seems, that Datalake endpoint does not support PUT with non empty body.

PUT allows to have body specified, so can we merge above three operations into one? Is there anything preventing doing that on your side?

**Comment by navba-MSFT** [comment]
@tovyhnal I used the sample available [here](https://learn.microsoft.com/en-us/azure/storage/blobs/storage-blob-upload) and it works fine for Azure Datalake Gen 2 storage. I also used empty blob content and that worked fine. I am pasting my sample code here if you want to test.

```
using Azure.Storage.Blobs;
using Azure.Storage.Blobs.Models;
using System;
using System.IO;
using System.Threading.Tasks;

namespace BlobQuickstartV12
{
    class Program
    {
        static async Task Main()
        {
            Console.WriteLine("Azure Blob Storage v12 - .NET quickstart sample\n");
         
            string connectionString = "XXXXXXXXXXPASTE YOUR ADLS Gen2 STORAGE CONNECTING STRING HEREXXXXXXXXXXX
            // Create a BlobServiceClient object which will be used to create a container client
            BlobServiceClient blobServiceClient = new BlobServiceClient(connectionString);

            //Create a unique name for the container
            string containerName = "quickstartblobs" + Guid.NewGuid().ToString();

            // Create the container and return a container client object
            BlobContainerClient containerClient = await blobServiceClient.CreateBlobContainerAsync(containerName);

            // Create a local file in the ./data/ directory for uploading and downloading
            string localPath = "./data/";
            string fileName = "quickstart.txt";
            string localFilePath = Path.Combine(localPath, fileName);

            // Write text to the file
            await File.WriteAllTextAsync(localFilePath, "Hello World");
     
             //     BELOW LINE IS OR EMPTY FILE CONTENT - EMPTY PUT BODY
            //       await File.WriteAllTextAsync(localFilePath, "");

            // Get a reference to a blob
            BlobClient blobClient = containerClient.GetBlobClient(fileName);

            Console.WriteLine("Uploading to Blob storage as blob:\n\t {0}\n", blobClient.Uri);

            // Upload data from the local file
            await blobClient.UploadAsync(localFilePath, true);
        }
    }
}
```

Sending you the request / response while running my above sample code:

**PUT** https://navbaXXXXXXgen2.blob.core.windows.net/quickstartblobsa49fba9a-4cda-4c95-83a5-7430828065ba/quickstart.txt HTTP/1.1
Host: navbastorageadlsgen2.blob.core.windows.net
x-ms-blob-type: BlockBlob
x-ms-version: 2021-06-08
Accept: application/xml
x-ms-client-request-id: 88ea56eb-5e5d-40d8-a2de-323b2d71dab0
x-ms-return-client-request-id: true
User-Agent: azsdk-net-Storage.Blobs/12.12.0 (.NET 6.0.10; Microsoft Windows 10.0.22621)
x-ms-date: Tue, 18 Oct 2022 10:33:12 GMT
Authorization: SharedKey navbXXXXXXXXgen2:rBf9qDN1XXXXXXXXXXXXXXIVsR+3aZE=
**Content-Length: 0**
Content-Type: application/octet-stream


HTTP/1.1 **201 Created**
Content-Length: 0
Content-MD5: 1B2M2Y8AsgTpgAmY7PhCfg==
Last-Modified: Tue, 18 Oct 2022 10:33:11 GMT
ETag: "0x8DAB0F4281C4B9A"
Server: Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0
x-ms-request-id: a59b33d7-501e-0084-7ddd-e25f8a000000
x-ms-client-request-id: 88ea56eb-5e5d-40d8-a2de-323b2d71dab0
x-ms-version: 2021-06-08
x-ms-content-crc64: AAAAAAAAAAA=
x-ms-request-server-encrypted: true
Date: Tue, 18 Oct 2022 10:33:11 GMT

**Comment by navba-MSFT** [comment]
@tovyhnal Could you try with **blob** endpoint instead of **dfs** and check if that helps ?

**Comment by tovyhnal** [comment]
That works, but since this url is coming to us from external source I don't feel it is right to just change part of the url from dsf -> blob. I am not sure what can be the consequences...

So, my above question remains:

PUT allows to have body specified, so can we merge above three operations into one? Is there anything preventing doing that on your side?

**Comment by navba-MSFT** [comment]
@tovyhnal Could you please confirm if you are using[ Azure.Storage.Files.DataLake ](https://www.nuget.org/packages/Azure.Storage.Files.DataLake) .NET client library ?

**Comment by tovyhnal** [comment]
Yes, I can confirm we are using above package in version: 12.12.1

**Comment by navba-MSFT** [comment]
@tovyhnal Writing a file via the ADLS/DFS endpoint is a multi-request process. The semantics of this multi-part operation also match those of HDFS, on which the API design is based.

This is by design as this API is not intended for writing lots of small files (where a single-shot operation might be applicable), but instead writing large files in parallel. This cannot be changed. 

If you really want a single request write, then the above mentioned approach using the [Azure.Storage.Blobs](https://www.nuget.org/packages/Azure.Storage.Blobs) package and Blob API endpoint is the ONLY workaround to this. Hope this answers.
