### ISSUE TITLE
Missing remove SecondaryIPConfiguration API

### ISSUE THREAD

**Issue by tg123** [Azure/azure-sdk-for-net#3185]
I only see in NetworkInterfaces
```
DefineSecondaryIPConfiguration
UpdateIPConfiguration
```

looking for

```
WithoutSecondaryIPConfiguration
```

**Comment by martinsawicki** [comment]
This API was originally missed on purpose -- only one IP configuration was supported on a NIC by the Networking service at that time, so there was no point exposing a way to remove a secondary IP config.
For that matter, adding a secondary IP config to a NIC would not have worked all that well before either.

Since Azure Networking has by now added support for multiple IP configs on a NIC, v1.2 will have proper support for multiple NIC IP configs, including the ability to remove them.

This is addressed in PR: https://github.com/Azure/azure-sdk-for-net/pull/3579

**Comment by martinsawicki** [comment]
done in v1.3
