### ISSUE TITLE
[Perf Framework] Need documentation on how to configure

### ISSUE THREAD

**Issue by JoshLove-msft** [Azure/azure-sdk-for-net#31873]
There doesn't appear to be any existing documentation on how to use the .NET Perf Test framework, beyond using the [sample project](https://github.com/Azure/azure-sdk-for-net/tree/main/common/Perf/Azure.Sample.Perf) as a reference.

There is some behavior that is hard to know without debugging. For instance, if your perf scenario classes end with "Test" you need to strip it off before passing it in as a command line argument? The sample actually uses test in the scenario names, but I didn't find any docs explaining this. I know this now after debugging and finding this [code](https://github.com/Azure/azure-sdk-for-net/blob/main/common/PerfStressShared/PerfStressUtilities.cs#L69).

Also, there is no documentation on how to actually run the tests locally.

**Comment by mikeharder** [comment]
There is some documentation here:

https://github.com/Azure/azure-sdk-for-net/wiki/Writing-performance-tests-for-Client-libraries

Currently, one of the best ways to understand how to build and run perf tests is by looking at the pipeline logs and/or the perf automation code:

https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1925758&view=logs&j=42ded549-05ee-5cdb-7ba7-7a948a0cc056&t=49e32a0b-4245-531b-0723-9d45113ffbd3

https://github.com/Azure/azure-sdk-tools/blob/main/tools/perf-automation/Azure.Sdk.Tools.PerfAutomation/Cpp.cs

Related, we encourage people to use the perf pipelines as much as possible, rather than testing locally.  It's usually faster and easier, and you don't need to manually deploy resources, setup your VM, etc.

But if you are doing a lot of inner-loop development and testing, or testing scenarios which don't have pipelines yet, then running locally can make sense.  We can also add pipelines for more scenarios as needed, it's pretty easy (mostly copying an existing pipeline).

**Comment by JoshLove-msft** [comment]
I'd suggest we move that wiki content into a README in the perf directory. I didn't know to even look in the wiki directory.

**Comment by mikeharder** [comment]
I have no objection, if you or someone on the .NET team would like to create a PR for this.  @AlexanderSher is taking point as the perf representative for .NET.

**Comment by mikeharder** [comment]
The same is true for changes to the perf framework itself, like the behavior of removing the "Test" suffix from the verb names.  If the .NET team wants to change this, I have no objection.  Whatever you think makes the perf framework most useful for your team internally.  We do need to be careful about breaking changes, or doing this differently than other languages, but we should be able to accommodate most changes.
