### ISSUE TITLE
[FEATURE REQ] BlobUriBuilder as a real URI builder

### ISSUE THREAD

**Issue by brandonh-msft** [Azure/azure-sdk-for-net#31897]
### Library name

Azure.Storage.Blobs

### Please describe the feature.

I'd like to see if we can make BlobUriBuilder an actual URI builder as I find it frustrating and odd that I have to give it a URI to begin with. I would rather prefer it to have overloads like:

```csharp
BlobUriBuilder(string accountName)
BlobUriBuilder(string accountName, string containerName)
BlobUriBuilder(string accountName, string containerName, string blobPath)
```

and have it actually build the URI for me. In this way, I don't, as a new user, have to go look up that whole URI format (`.blob.core.windows.net`) and hard-code it into my usage which feels brittle.

Consider System.UriBuilder:
![](https://user-images.githubusercontent.com/20270743/196790416-5beec66d-8396-45ab-94cb-d39783a6d31b.png)

I recognize we might need some nuance to support private/gov't clouds but I think we can figure it out :)

**Comment by amnguye** [comment]
The feature request does sound like it needs a lot of iterating on, but a valid suggestion.

Things to note though..

Storage also creates Uri's that have "storage.azure.net" (including, as you noted, government cloud URLs ending suffixes) and well as custom URLs customers could possibly provide. 

Storage also supports Zonal DNS so URLs that look like "<storageaccount>.blob.z<XX>.storage.azure.net".

BlobUriBuilder also deals with IP address formed URLs. So we also would have to take into consideration how that would be formatted as well.

Might not be the best solution but
`BlobUriBuilder(string ipAddress, string accountName, string containerName, string blobPath)`
Could support IP address style addresses, while
`BlobUriBuilder(string endingSuffix, string accountName, string containerName, string blobPath)`
would support the storage URLs that aren't custom (e.g. "<account>.blob.core.windows.net")

However it doesn't make a big difference compared to doing,
```
BlobUriBuilder uriBuilder = new BlobUriBuilder(new Uri("https://<account>.blob.core.windows.net")
{
    BlobContainerName= containerName,
    BlobName = blobName,
}
```
but I could see it saving some lines of code if you had to concatenate the "https://<account>.blob.core.windows.net" together, however I don't believe we recommend hardcoding the ending suffix like that due to the complications in the future if the ending suffix changes or it becomes  a zonal endpoint. We recommend always passing the full endpoint, rather than constructing from scratch to prevent future breakage.

**Comment by brandonh-msft** [comment]
I would be curious to see telemetry and/or a search of github as to how many people are already hardcoding `.blob.core.windows.net` vs something else when using Storage APIs. I feel something that _defaults_ to this would be a massive improvement, especially for folks new to the Azure ecosystem and SDK.

**Comment by amnguye** [comment]
I know this isn't telemetry, but as someone who deals with countless github issues, we have a good assortment of customers who use different types of URLs to access their storage accounts.

We should **not be defaulting** to "blob.core.windows.net". As that DNS can be easily changed in the future as DNS eventually runs out of space. We cannot change the default in the future, because that would be a breaking change.

Customers should know what endpoint they are calling into. Instead of assuming the ending suffix for them. That's why in portal if you attempt to grab things such as the connection string or calling our `BlobClient` we take an endpoint and not just the storage account name.

I agree with you, that if a customer has the ending suffix "blob.core.windows.net" this would make things convenient for them. However this would be terrible for the rest of our customers, which I don't believe catering to the majority (if blob.core.windows.net is the majority) is a good design decision.

We've seen customers before (not just in our repository) but across other products running into issues when their endpoint changes (e.g. to use Azurite, IP addresses, custom endpoints, zonal DNS etc).
