### ISSUE TITLE
[BUG] AzureCoreEventSource should not log requests as information

### ISSUE THREAD

**Issue by EnemyArea** [Azure/azure-sdk-for-net#31967]
### Library name and version

Azure.Storage.Blobs / Microsoft.Azure.WebJobs.Extensions.Storage.Queues

### Describe the bug

Its releated to this issue here: https://github.com/Azure/azure-functions-dotnet-worker/issues/796
If you make an request in azure it goes through the logger which logs all as information instead of debug:
https://github.com/Azure/azure-sdk-for-net/blob/5ed8dcc561b00a3f4eb7eea3f91ea74e24639385/sdk/core/Azure.Core/src/Diagnostics/AzureCoreEventSource.cs#L34
https://github.com/Azure/azure-sdk-for-net/blob/5ed8dcc561b00a3f4eb7eea3f91ea74e24639385/sdk/core/Azure.Core/src/Diagnostics/AzureCoreEventSource.cs#L52

this will flood al logs in AI and you can not use the "Log-Stream" in azure-portal beacuse there are too many requests.

### Expected behavior

Should log as verbose / debug

### Actual behavior

Logs as information

### Reproduction Steps

Just setup an new solution and add one queue-trigger. azure will now logs all http-requests as "information".

### Environment

.net 6, Azure.Storage.Blobs 12.14.1, Microsoft.Azure.WebJobs.Extensions.Storage.Queues 5.0.1

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by JoshLove-msft** [comment]
@EnemyArea, you should be able to filter Azure.Core logs to the level you desire as follows in your host.json file:

```
  "Logging": {
    "LogLevel": {
      "Default": "Information",
      "Microsoft.AspNetCore": "Warning",
      "Azure.Core": "Warning"
    }
  },
```

**Comment by JoshLove-msft** [comment]
As for changing the level of these logs, we couldn't do that as it would probably break some user scenarios. In general, I think of requests going out from a function app to an Azure service as being Informational rather than Debug.

**Comment by EnemyArea** [comment]
@JoshLove-msft 
/unresolve
I already done this, but it does not work for AI and the Log-Stream in portal.azure, because it shows all logs which are generated in the application, regardless the log level for the categories. This makes it unable to use anymore because of the messages that are showing up. 

Either we need to be able to suppress logs in the log stream or the SDK needs to log it as debug so it can be suppressed.

Before I upated to the new Azure.Storage.Queues, the http-header messages are logged as verbose. For example all messages from "Microsoft.Azure.WebJobs.Host.Queues.Listeners.QueueListener" were logged as verbose. The HttpClient logs http-headers as verbose as well:

`2022-10-26T07:05:04Z   [Verbose]   Response Headers:
Date: Wed, 26 Oct 2022 07:05:03 GMT
Server: AtlassianEdge
Timing-Allow-Origin: *
X-Arequestid: 0815
X-Aaccountid: 0815
Cache-Control: no-store, no-transform, no-cache
Vary: Accept-Encoding
Expect-CT: report-uri="https://web-security-reports.services.atlassian.com/expect-ct-report/atlassian-proxy", max-age=86400
Strict-Transport-Security: max-age=63072000; preload
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block`

**Comment by TheCakeMonster** [comment]
The Azure log stream on our function apps have suddenly become very noisy for us, because of a lot of new logging from Azure.Storage.Blobs. This has happened in the past few weeks, probably the last 10 days. I think this might have been triggered by a new deployment of Azure Functions - perhaps caused by the rollout of .NET 7?

Our default log level is set to Warning, but these log entries get included anyway. I think there is something wrong somewhere with the way that log entries are being filtered, perhaps in .NET 7.

The log stream in Azure is suddenly pretty much unusable. Finding useful information from our own log entries in the midst of a wealth of debug information from the infrastructure that we don't want is really hard. I disagree that these being logged with a log level of Information is appropriate - but that is an aside. My main reason for posting is that they have suddenly got MUCH more noisy, because it appears that the filtering of logging is suddenly broken, or changed.

Whatever has caused this very recent change is not welcome.

I haven't tried applying the fix listed above because I'm not able to do a new deployment just at the moment. However, I shouldn't need to apply a fix - this is not related to anything I changed. It's a change in the behaviour of Azure functions.

**Comment by AJMcKane** [comment]
We're also getting this error and it's costing us _thousands_ in log entries. 

The assembly that's to blame for ours is noted as `Azure.Core.1` but setting the logLevel value for Azure.Core and Azure.Core.1 to `Error` doesn't impact it.
