### ISSUE TITLE
Is there any method to merge two FormElements?

### ISSUE THREAD

**Issue by mika-data** [Azure/azure-sdk-for-net#32025]
We would like to merge two FormElements, but could not find any merge, concatenation or addition of FormElements.
We are writing our own method.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 277708a3-a2b6-f115-28a3-77e9e30435ed
* Version Independent ID: 06a12831-b8e6-efb0-a69f-73b2eeb11774
* Content: [FormElement Class (Azure.AI.FormRecognizer.Models) - Azure for .NET Developers](https://learn.microsoft.com/en-us/dotnet/api/azure.ai.formrecognizer.models.formelement?view=azure-dotnet)
* Content Source: [xml/Azure.AI.FormRecognizer.Models/FormElement.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Azure.AI.FormRecognizer.Models/FormElement.xml)
* Service: **azure**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by kinelski** [comment]
Hello @mika-data,

Neither service nor the SDK provides tools for merging elements, so you need to write your own method as you suggested. Our models do not have public constructors so you'll need our `FormRecognizerModelFactory` class in order to instantiate them.

Please let us know if you have any more questions.
