### ISSUE TITLE
[QUERY] Serialization of resource models

### ISSUE THREAD

**Issue by davidobrien1985** [Azure/azure-sdk-for-net#32175]
### Library name and version

all

### Query/Question

Hi,

our application creates a sort of inventory of Azure resources and their configuration in our own database.
To do this with the old SDK we had to extract our own DTOs from the SDK models so we could ignore certain fields (like `Etag`), but also when we fetched a serialized SDK resource model from our database, we could not instantiate the instance of the SDK resource type because there were only `get` properties.

We are now wondering if the new SDK allows us to serialize the resource models so we can avoid creating our own DTOs.

As an example, the AWS dotnet SDK allows us to do this as they are POCOs that can be deserialized into.

Thanks.

### Environment

net6

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by xboxeer** [comment]
@davidobrien1985 in our new SDK, a resource object is not supposed to be serialized, you should try serialize the XXXData object that used for create or update a resource.  
May I know the reason you want to serialize those azure resource? Persistent those config info so that you can easily re-use them again or just for showing the resources you created in some places?

**Comment by alexguevara** [comment]
> @davidobrien1985 in our new SDK, a resource object is not supposed to be serialized, you should try serialize the XXXData object that used for create or update a resource. May I know the reason you want to serialize those azure resource? Persistent those config info so that you can easily re-use them again or just for showing the resources you created in some places? I'm asking this because currently Azure SDK for .NET deserialize does not support deserialize read only properties, so the serialize/deserialize is not a round-trip now.

We persist those models for:
a) running multiple security checks against resource configuration.
Re-using resources this way allows us to significantly reduce the number of calls to Azure API. Otherwise, we may hit API limits.
b) showing resources on the graph
c) fixing security vulnerabilities and presenting to the end user required config changes

Could you please suggest any workaround for producing POCOs from SDK models to serialize/deserialize into? I would highly appreciate any help as of now we have to manually re-create them and supporting this is very problematic. Could maybe recursive T4 template help here (in case it's even possible)?
Thanks.

**Comment by xboxeer** [comment]
@alexguevara First I'll suggest serialize the XXXData object instead of the resource object, for example
```csharp
var resourceIdentifier = ServiceBusQueueResource.CreateResourceIdentifier(client.GetDefaultSubscription().Data.SubscriptionId, resourceGroupName, serviceBusName, queueName);
            var queue = client.GetServiceBusQueueResource(resourceIdentifier).Get();
            var output = JsonSerializer.Serialize<ServiceBusQueueData>();
            Console.WriteLine("Serialization Output:");
            Console.WriteLine(output);
            var queueFromOutput = JsonSerializer.Deserialize<ServiceBusQueueData>(output)!;
            Console.WriteLine("Deserialization Output:");
            Console.WriteLine(queueFromOutput.Name);
```

So far this serialize and deserialize is not round-trip, the readonly property can not be deserialized so for that part you'll have to write some handy code
quick comparison:
![image](https://user-images.githubusercontent.com/5089150/199189142-b0ad5ff3-b674-491c-8ccb-f7541b3872c2.png)
