### ISSUE TITLE
[BUG] Deleting Function app with resource manager sdk creates zombie app service after a undetermined amount of time

### ISSUE THREAD

**Issue by BrettGoreham** [Azure/azure-sdk-for-net#32299]
### Library name and version

Azure.ResourceManager.AppService  1.0.0

### Describe the bug

Getting "websites" from the resource group. and retrieving the correct website to delete
Using the delete async method on the website results in a deleted function app.

however after a little bit of time a new app service (with the same name as the existing one) and a default app service plan appear in the resource group.
All actual config from the existing function app is deleted however the app service remains / is created.

### Expected behavior

A function app to be deleted and no remainder existing afterwards

### Actual behavior

After a wait usually longer than a couple minutes a app service of the same name and a default app service plan appears ( if not already existing)

### Reproduction Steps

`
            var subscriptionId = "Fill in"
            var resourceGroupName = "Fill in"
            var resourceNameToDelete = "Fill in"
            
            var client = new ArmClient(credential, subscriptionId);

            var resourceGroup = client.GetResourceGroupResource(ResourceGroupResource.CreateResourceIdentifier(subscriptionID, resourceGroupName));

            var websites = resourceGroup.GetWebSites();
            var website = websites.Where(s => s.Data.Name == resourceNameToDelete).First();
            await website.DeleteAsync(WaitUntil.Completed, deleteEmptyServerFarm: false);

`

### Environment

Azure AppService.
Windows 10,
Visual Studio Version 17.3.6

**Comment by BrettGoreham** [comment]
Note tested this function in the Azure portal and the same result exists. so It could be a general azure problem...

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by Yao725** [comment]
I'm trying to reproduce this issue, but based on the comment in this issue, I believe this should be a service issue.

**Comment by BrettGoreham** [comment]
I believe this is the case as well ^ have tested through the portal ui and could recreate the same issue. Microsoft support was very unhelpful so in the end we gave up on building what we needed

**Comment by ArthurMa1978** [comment]
This issue is related to the service side and not the SDK side, so we are not able to help you with it. Therefore, we are closing this issue for now. If you need more assistance, please [open an Azure support request](https://docs.microsoft.com/azure/azure-portal/supportability/how-to-create-azure-support-request). We apologize for any inconvenience this may cause you.

We value your feedback and we want to make sure that your problem is solved. If you think that we have misunderstood your issue or closed it incorrectly, please feel free to comment on this thread and reopen the issue. We will be happy to assist you further. Thank you for your understanding and cooperation.
