### ISSUE TITLE
[BUG] Deserialization throws exception

### ISSUE THREAD

**Issue by m-nash** [Azure/azure-sdk-for-net#32351]
### Library name and version

Azure.Containers.ContainerRegistry

### Describe the bug

We have custom code which marks [this base class as abstract](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/containerregistry/Azure.Containers.ContainerRegistry/src/Blob/ArtifactManifest.cs#L12) because its supposed to be a base type for a discriminator tree, however none of the properties on the type are marked as the discriminator which means that the internal `Unknown` type will not be generated which means that our deserialization has no way to construct the object.

The [deserialize throw statement is here](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/containerregistry/Azure.Containers.ContainerRegistry/src/Generated/Models/ArtifactManifest.Serialization.cs#L29).

### Expected behavior

No throw

### Actual behavior

throws

### Reproduction Steps

Deserialize the ArtifactManifest type.

**Comment by annelo-msft** [comment]
@m-nash, could you please provide a repro case for this issue?  I would like to understand how a customer could trigger this exception by calling a public API in the library.  Thanks!

**Comment by m-nash** [comment]
It looks like @archerzz has changed it in this [PR here](https://github.com/Azure/azure-sdk-for-net/commit/4c2887c01e7f94c72914b845f012fab29414c704#diff-ed75a55f011887b0edb873f5bab8217128fab426414adcbf2fb5582489b7068e).  We will need to follow up with him.  It appears he moved the throw from [here](https://github.com/Azure/azure-sdk-for-net/commit/4c2887c01e7f94c72914b845f012fab29414c704#diff-ed75a55f011887b0edb873f5bab8217128fab426414adcbf2fb5582489b7068eL29) to [here](https://github.com/Azure/azure-sdk-for-net/commit/4c2887c01e7f94c72914b845f012fab29414c704#diff-b13407eed09682ed40e4692f685b3ab5333b9b05596d214f68db08d40531934fR18).  He also [added the `abstract` keyword](https://github.com/Azure/azure-sdk-for-net/commit/4c2887c01e7f94c72914b845f012fab29414c704#diff-3930d6c66342cf2b58849ff51477971373672f49ba5594902a5e4b2c3eee2384R11) to the model which [should be fine](https://learn.microsoft.com/en-us/dotnet/core/compatibility/#types) since the signature didn't change and no new abstract members were added.

@annelo-msft  as far as the repro any public API that returns [this type](https://github.com/Azure/azure-sdk-for-net/commit/4c2887c01e7f94c72914b845f012fab29414c704#diff-b13407eed09682ed40e4692f685b3ab5333b9b05596d214f68db08d40531934fR14) will throw an exception.  If that doesn't exist today then this can / should be removed otherwise this is a time bomb waiting to explode on someone.

**Comment by annelo-msft** [comment]
> If that doesn't exist today then this can / should be removed

It doesn't exist - any method returning a manifest should return an instance of a base type and not the abstract type.
@m-nash, can you be specific about what should be removed here?  Are you suggesting we use the manual convenience layer to reimplement the `DeserializeArtifactManifest()` method?

**Comment by annelo-msft** [comment]
It looks like it was checked in as part of a [generator change](https://github.com/Azure/azure-sdk-for-net/pull/32335) - I'm not sure why, I'm not familiar with that change: https://github.com/Azure/azure-sdk-for-net/commits/main/sdk/containerregistry/Azure.Containers.ContainerRegistry/src/Blob/ArtifactManifest.Serialization.cs

**Comment by archerzz** [comment]
> It looks like it was checked in as part of a [generator change](https://github.com/Azure/azure-sdk-for-net/pull/32335) - I'm not sure why, I'm not familiar with that change: [`main`/sdk/containerregistry/Azure.Containers.ContainerRegistry/src/Blob/ArtifactManifest.Serialization.cs (commits)](https://github.com/Azure/azure-sdk-for-net/commits/main/sdk/containerregistry/Azure.Containers.ContainerRegistry/src/Blob/ArtifactManifest.Serialization.cs)

@annelo-msft That could be due to the manually written `src/Blob/ArtifactManifest.cs`: https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/containerregistry/Azure.Containers.ContainerRegistry/src/Blob/ArtifactManifest.cs. So, the generator will generate the corresponding `src/Blob/ArtifactManifest.Serialization.cs` on par.

It looks like the generator moved the method `ArtifactManifest DeserializeArtifactManifest()` from `src/Generated/Models/ArtifactManifest.serialization.cs` to the new file. I don't know that caused the changed behavior of the generator.

I think Michael is talking about forward compatibility. We've changed the generator to generate an `Unknown` type for base model with discriminator property. So, in the future, if the service returns a new type of model, (e.g. `NewManifest` as new child type of `ArtifactManifest`). When parsing the response, it will be parsed into `Unknown`, instead of throwing an exception.
Now we've made `ArtifactManifest` as `abstract` base class. But in swagger there is no discriminator property defined. Then if such case happens again, there will be exception thrown.

**Comment by annelo-msft** [comment]
Hi @archerzz --

I tried deleting that file and regenerating the code, as shown in this PR - https://github.com/Azure/azure-sdk-for-net/pull/33345.  It looks like the generated serialization file is correctly placed in the Generated folder again, but now it is generating code that does not compile because it is trying to create an instance of an abstract type.

Can you help me understand what is intended to resolve this issue?

Thanks!

**Comment by archerzz** [comment]
> Hi @archerzz --
> 
> I tried deleting that file and regenerating the code, as shown in this PR - #33345. It looks like the generated serialization file is correctly placed in the Generated folder again, but now it is generating code that does not compile because it is trying to create an instance of an abstract type.
> 
> Can you help me understand what is intended to resolve this issue?
> 
> Thanks!

Hi @annelo-msft Apology. I rechecked [my PR](https://github.com/Azure/azure-sdk-for-net/pull/32335) again. And I think the `src/Blob/ArtifactManifest.Serialization.cs` is a manually written file in [this commit](https://github.com/Azure/azure-sdk-for-net/pull/32335/commits/3fb69c4650f10c5dd018296ad894c7f7ca39658c). It contains `// <auto-generated/>` comment which made me think the generator generated it.

Back to Michael's initial request, I think he is asking if we could add discriminator property in swagger for `ArtifactManifest` and its child types.
