### ISSUE TITLE
[FEATURE REQ] DocumentAnalysisClient should take password protected documents as input

### ISSUE THREAD

**Issue by anildugar** [Azure/azure-sdk-for-net#32409]
### Library name

Azure.AI.FormRecognizer

### Please describe the feature.

Imagine i have a password protected PDF Document which needs to be analyzed, can we pass the password of the document, post which the document should be analyzed by formrecognizer

**Comment by jsquire** [comment]
Hi @anildugar.  Thank you for reaching out and we appreciate your suggestion.  The Form Recognizer service does not currently support this feature.

Unfortunately, this repository is focused on the Azure SDK for .NET - we're unable to assist with Azure service requests and issues.  Since you're suggesting a service feature, your best path forward would be to [submit feedback](https://learn.microsoft.com/azure/cognitive-services/cognitive-services-support-options?context=%2Fazure%2Fcognitive-services%2Fform-recognizer%2Fcontext%2Fcontext&view=form-recog-3.0.0#submit-feedback) and engage with the service team.

I'm going to close this out;  if I've misunderstood what you're describing, please let us know in a comment and we'd be happy to assist as we're able.
