### ISSUE TITLE
[FEATURE REQ] Feature to have EDM types exposed to clients in Azure.Data.Tables

### ISSUE THREAD

**Issue by Sandeep7OnShell** [Azure/azure-sdk-for-net#32463]
### Library name

Azure.Data.Tables

### Please describe the feature.

We are using Microsoft.Azure.Cosmos.Table and as part of the library we get access to EDM types of entities using DynamicTableEntity and we are using the same to have a generic solution that could connect to any storage account and do operations on the tables/entities. Since it's a generic solution, it becomes very important for us to have access to EDM types so that we keep that information intact in entities while doing data manipulations.

Now since Microsoft.Azure.Cosmos.Table is marked for deprecation and we are supposed to upgrade to Azure.Data.Tables. Azure.Data.Tables don't have any replacement for DynamicTableEntity, hence we lose out on that information. Without the library exposing EDM types, we feel we have a risk.

What is needed: A replacement of DynamicTableEntity in Azure.Data.Tables that expose EDM types that clients can use if needed.

The issue is discussed already in https://github.com/Azure/azure-sdk-for-net/issues/31826

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by christothes** [comment]
Thanks @Sandeep7OnShell - In order to consider this feature, please provide some general scenarios where this EDM data is needed in addition to the type information on the `TableEntity` Value collection, which already provides type information.

(note: This should include scenarios that would be valuable other than when data is incorrectly persisted to another data store where the type information has been removed, as in the referenced issue.)

**Comment by Sandeep7OnShell** [comment]
@christothes In addition to the type information on the TableEntity Value collection, which already provides type information. 
With the new package, I don't see whare is provides the type of information. Can you please guide which property in TableEntity does that?. If we have that information there, could be sufficient for handle the EDM scenario.
