### ISSUE TITLE
[BUG] Azure Communication Chat client - Sending message with ParticipantAdded type is not supported

### ISSUE THREAD

**Issue by KattieD** [Azure/azure-sdk-for-net#32623]
### Library name and version

Azure.Communication.Chat 1.1.0

### Describe the bug

After sending a message with ChatMessageType.ParticipantAdded by Azure Communication Chat client to an existing thread. the error occurs:  Sending a message with ParticipantAdded type is not supported.

### Expected behavior

Message is sent with ChatMessageType.ParticipantAdded. 

### Actual behavior

Message is not sent and an error occurs: Sending a message with ParticipantAdded type is not supported.

### Reproduction Steps

- Create a thread using the Azure Communication Chat client
- Add new participant to the thread 
- Send a message to this thread with the type ChatMessageType.ParticipantAdded

### Environment

.Net Core 6.0

**Comment by PramodValavala-MSFT** [comment]
@KattieD When sending messages, you can either [use the `Text` or `HTML` types](https://learn.microsoft.com/en-us/azure/communication-services/concepts/chat/concepts#message-types) while the other available options are for system messages only and are part of the enum since received messages could have that type.
