### ISSUE TITLE
[DevCenter] Weekly tests failure

### ISSUE THREAD

**Issue by ShivangiReja** [Azure/azure-sdk-for-net#32624]
### Library name

Azure.Developer.DevCenter

### Please describe the feature.

See [here](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=2001888&view=logs&j=a3682114-3f18-57fc-5b36-0513d1624e30&t=c2c78881-d3fb-5111-5a94-ab9a12aca51e&l=12) for more details:

![image](https://user-images.githubusercontent.com/45216704/203425367-0033c309-be62-43e6-82ca-35cbc78517bf.png)

DevCenter weekly test pipeline: https://dev.azure.com/azure-sdk/internal/_build?definitionId=5624&_a=summary

**Comment by pallavit** [comment]
/cc: @sebrenna @mharlan who I believe are the new owners.

**Comment by sebrenna** [comment]
@pallavit @ShivangiReja will take a look soon. We recently resolved some issues with the subscription config in the other pipeline; will see if this is related.

FYI, "net - devcenter - tests" has been trucking along fine, so I don't think this is an issue with the service or SDK: https://dev.azure.com/azure-sdk/internal/_build?definitionId=5623&_a=summary

**Comment by sebrenna** [comment]
@pallavit @ShivangiReja looks like the issue is that tests-weekly isn't pulling in config from our variable group, [Azure Dev Center Team Live Test Secrets](https://dev.azure.com/azure-sdk/internal/_library?itemType=VariableGroups&view=VariableGroupView&variableGroupId=125&path=Azure%20Dev%20Center%20Team%20Live%20Test%20Secrets).

@benbp do we need to take any additional steps to link that variable group to "net - devcenter - tests-weekly"? It's already connected to "net - devcenter - tests".

**Comment by benbp** [comment]
@sebrenna I just hooked up the weekly group, it should be good now.

**Comment by ShivangiReja** [comment]
The pipeline https://dev.azure.com/azure-sdk/internal/_build/results?buildId=2019747&view=results is now green. Thank you @benbp!
