### ISSUE TITLE
Excessive POST {storageAccount}/Tables() from [Table] attribute binding

### ISSUE THREAD

**Issue by marcinzi** [Azure/azure-sdk-for-net#32636]
We noticed on telemetry a lot of 409s from table storage dependency.
POST https://{our account}.table.core.windows.net:443/Tables()
result code 409

Looking for root cause found that [Table] attribute on binding to CloudTable object is most likely responsible for ensuring that table exists. 

#### Repro steps

Run Azure Function bound to CloudTable parameter

#### Expected behavior

No excessive POST call is done. We're in control of our Azure Dependencies and binding a parameter should not try to modify our Azure Resources.
At the minimum this behavior should be parametrized, and default off.

#### Actual behavior

Every AF invocation causes the POST call,
this is performance overhead

#### Known workarounds

Not known

#### Related information 

Most likely this line of code:
https://github.com/Azure/azure-webjobs-sdk/blob/ef265e20d4357f2a82871b63a778c99cb6aac8db/src/Microsoft.Azure.WebJobs.Extensions.Storage/Tables/Config/TablesExtensionConfigProvider.cs#L216

**Comment by metu** [comment]
It's been months since my previous comment and this isn't entirely related but I thought I'd just paste some code here that seems to work quite well for our Function Apps and Web Api's currently using .net core 3.1.... we have a pending release where we migrated everything to .net 7 but our code still works well i.e. can handle multiple requests rather quickly. (I included some dependency injection for other services such as Blob, Cosmos, and Service Bus so that you can see that they all kind of wire up the same when it comes to the HttpClientFactory)

**Dependency Injection**
```
services.AddHttpClient();
services.AddSingleton<CosmosClient>(x => CosmosDbClientFactory.CreateClient(_cosmosDbAccountUri, _violationsCosmosDbAuthKey, x.GetService<IHttpClientFactory>()));
services.AddSingleton<TableServiceClient>(x => TableServiceClientFactory.CreateClient(_stConnectionString, x.GetService<IHttpClientFactory>()));
services.AddSingleton<BlobServiceClient>(x => BlobServiceClientFactory.CreateClient(_stConnectionString, x.GetService<IHttpClientFactory>()));
services.AddSingleton<ServiceBusClient>(x => ServiceBusClientFactory.CreateClient(_sbConnectionString));
```

**TableServiceClientFactory**
```
public static TableServiceClient CreateClient(string storageConnectionString, IHttpClientFactory httpClientFactory)
{
    try
    {
        TableServiceClient serviceClient = new TableServiceClient(
            storageConnectionString,
            new TableClientOptions
            {
                Transport = new HttpClientTransport(httpClientFactory.CreateClient())
            }
            );

        return serviceClient;
    }
    catch (Exception ex)
    {
        Console.WriteLine(ex);
        throw;
    }
}
```

We then add a scoped lifetime instance of our `TableRepository` class which on it's very first call will check to see if the table exists and create it if it doesn't and returns a `TableClient` instance. Thereafter any call afterwards just checks to see if `TableClient` is null and if not, execute the desired request i.e. `TableClient.UpsertEntityAsync` or `TableClient.Query`. It looks something like this:

**Dependency Injection**

```
services.AddScoped<ITableRepository, TableRepository>(x =>
    new TableRepository(
            x.GetService<TableServiceClient>()
            )
        {
            TableName = _someTableName
        });
```

**TableRepository**

```
public TableRepository(
    TableServiceClient tableServiceClient
    )
{
    _tableServiceClient = tableServiceClient;
}

public async Task<int> UpsertEntityAsync<T>(T entity)
    where T : class
{
    try
    {
        if (_tableClient is null)
        {
            _tableClient = _tableServiceClient.GetTableClient(_tableName);
        }

        TableEntity tableEntity = CreateEntity(entity);

        Azure.Response response = await _tableClient.UpsertEntityAsync(tableEntity);

        return response.Status;
    }
    catch (Exception ex)
    {
        Console.WriteLine(ex);
        throw;
    }
}

```

**Comment by jsquire** [comment]
//cc: @christothes

**Comment by christothes** [comment]
Does this problem reproduce with the latest version of this extension? https://www.nuget.org/packages/Microsoft.Azure.WebJobs.Extensions.Tables

**Comment by ras-relativity** [comment]
Hi @christothes , yes it does.

**Comment by rdennyson** [comment]
Dependency Injection causing this issue. Change AddTransient to AddScoped will resolve this issue
