### ISSUE TITLE
[QUERY] Information level logs with Azure.Core.1 category

### ISSUE THREAD

**Issue by SeanFeldman** [Azure/azure-sdk-for-net#32694]
### Library name and version

latest

### Query/Question

I see multiple logs of information log level with the category `Azure.Core.1` showing in Application Insights. What is this, and why is it not using `Azure.Core` category? 

### Environment

N/A

**Comment by jsquire** [comment]
There are cases where multiple versions of different Azure libraries are loaded into different contexts.   For example, Functions uses some Azure libraries in its infrastructure that may differ from those used in developer-provided code for the Function itself.   This was causing issues due to a limitation of `EventSource` where names have to be unique within the process.   To avoid conflicts, if there is more than one version of an Azure library loaded, they'll start to use numeric suffixes for the name.

More context can be found in #22767.

**Comment by SeanFeldman** [comment]
Functions is exactly where I ran into this. Sadly, the logs emitted are all at the Information level (which is way too chatty and spamming AppInsights). And because this is a new category, it wasn't filtered out...

Thank you for the details, @jsquire.
