### ISSUE TITLE
Azure cognitive search with more fields

### ISSUE THREAD

**Issue by SathyaChenniappan** [Azure/azure-sdk-for-net#32745]
### Library name and version

Azure.Search.Documents(11.4.0)

### Query/Question

I have more than 1000+ fields. Expecting more fields in the future as well. How can I achieve the search for all these fields? 
Sample Cosmos data,

[{
"id":1,
"FirstName":"first name",
"LastName":"last name",
"MetaData":{
"field1":1,
"field2":"12/02/2020",
"field3":"test string"
},
{
"id":2,
"FirstName":"first name",
"LastName":"last name",
"MetaData":{
"field1":1,
"field4":1,
"field5":"12/02/2020",
"field6":"test string2",
"field7":"test string 3",
"field8": ["test1","test2"]
}
...]

MetaData will have dynamic fields. I need to create searchable index fields for all these metadata. 
since the index field max limit is 1000. I am unable to create index fields for metadata.
https://learn.microsoft.com/en-us/azure/search/search-limits-quotas-capacity#index-limits

Please suggest any other way of searching the metadata other than creating fields in the search index.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by ShivangiReja** [comment]
Hi @SathyaChenniappan, Documentation limit is set to 1000 as we don't recommend a huge number of fields since this would have performance impact with more fields. However, you should be able to continue adding fields to approx. 2000. If you are getting any issue with index creation because going beyond 1000 limit, please raise a support case accordingly through the Azure portal for Search.
