### ISSUE TITLE
CVE in  System.Drawing.Common 4.7.0 dependency

### ISSUE THREAD

**Issue by SymbioticKilla** [Azure/azure-sdk-for-net#32781]
Libs:
- azure.extensions.aspnetcore.dataprotection.blobs.1.2.3.nupkg
- azure.extensions.aspnetcore.dataprotection.keys.1.1.0.nupkg
 
CVE-2021-24112
https://msrc.microsoft.com/update-guide/en-US/vulnerability/CVE-2021-24112
![image](https://user-images.githubusercontent.com/59652865/204849999-627930a8-6b75-4c92-bd23-8179b8f64170.png)

**Comment by jsquire** [comment]
Hi @SymbioticKilla.   Thank you for bringing this to our attention.   From what I can see, `System.Security.Permissions` v4.7.0 has a dependency on `System.Windows.Extensions` only for its `netcoreapp3.0` target.  Neither its `netstandard2.0` or `net461` targets hold that dependency.  

Since `netcoreapp3.0` reached end of support in December, 2019 there should be no exposure.   We'll get this patched up with our next scheduled release window.   In the meantime, the recommended mitigation would be to add a direct reference to `Microsoft.AspNetCore.DataProtection` v3.1.31 in the application.

**Comment by jsquire** [comment]
This was addressed by #33011.    Release is pending and currently scheduled for early Feb, tracked by #33010.

**Comment by SymbioticKilla** [comment]
@jsquire  
Hi,

does the update fix the issue? 
![image](https://user-images.githubusercontent.com/59652865/218084636-6ab1e4ce-d6cb-42e4-81c1-55d5e5142781.png)

**Comment by jsquire** [comment]
The current release ensures there are no vulnerabilities in supported platforms.  The reference to `System.Drawing.Common` only exists in the `System.Windows.Extensions` package target for `NetCoreApp3.0`, which reached end of support in March 2020.  _([ref](https://dotnet.microsoft.com/en-us/platform/support/policy/dotnet-core))_   An application would have to be explicitly targeting `netcore3.0` in order to pull in the vulnerable library.

That says, it does appear that the bump did not resolve the issue the way that we intended.  `Microsoft.AspNetCore.DataProtection` got another bump since we last updated the dependency which includes a change to the tree for `System.Security.Cryptography.Xml` and eliminates the `System.Drawing.Common` dependency altogether.   I'll bump the dependency again and we'll release them next month with `Microsoft.AspNetCore.DataProtection` v3.1.32.

**Comment by jsquire** [comment]
Ok... trying this again via #34072 and #34071.

**Comment by SymbioticKilla** [comment]
@jsquire 
Hi!
Thank you for you for your effort and quick responses!

Unfortunately the problem is still there :(
![image](https://user-images.githubusercontent.com/59652865/228260947-184eae57-b807-41f4-bbd2-c9341083be76.png)

![image](https://user-images.githubusercontent.com/59652865/228260549-9eab0a49-5ee0-4dbc-ba3c-c259627d0e9f.png)
