### ISSUE TITLE
Message are being delivered late sometime

### ISSUE THREAD

**Issue by bilalmalik777** [Azure/azure-sdk-for-net#32832]
### Library name and version

Azure.Messaging.EventHubs.Processor 5.7.2

### Describe the bug

messages are getting received late from IoT hub using Azure.Messaging.EventHubs.Processor library. Even we are receiving the same messages at the same time at azure cli, but against my app which is using Azure.Messaging.EventHubs.Processor is showing zero received events. i am also sharing the time stamp when the message is delivered from our device to iot hub but at the same time no event was triggered in my app. timestamp is marked with pink color in the screenshot. please find the attached screenshot
![image](https://user-images.githubusercontent.com/23011613/205240194-fb7bf3a8-6495-4bdc-b4e2-a4a87cfac13a.png)

### Expected behavior

messages must be delivered with zero latency but messages are being delivered with latency in seconds from 1 to 100 seconds.

### Actual behavior

Messages are being delivered with latency, mostly it works well but sometimes it starts to send with lag.

### Reproduction Steps

- we started sending messages after each second using the mosquito bridge, also we tried the same method using emqs bridge
- To analyze the message delivery we configure azure cli with our local. it was receiving messages correctly at the same time. we use the following command to configure Azure CLI
- az iot hub events-monitor --device-id {deviceid} --hub-name {iot hub name}
-

### Environment

our app is using dotnet 6.0 and runs inside Linux container.

### Library configuration code

```csharp
////EventProcessor configuration at start of the console app
var blobContainerClient = new BlobContainerClient(
                    storageConnectionString,
                    blobContainerName);
                await blobContainerClient.CreateIfNotExistsAsync(PublicAccessType.Blob);

                var maximumBatchSize = 256;

                EventProcessorOptions options = new EventProcessorOptions();
                options.PrefetchCount = 512;
                options.MaximumWaitTime = TimeSpan.FromSeconds(30);

                var processor = new EventProcessor(
                    blobContainerClient,
                    maximumBatchSize,
                    consumerGroup,
                    eventHubsConnectionString,
                    eventHubName);

                using var cancellationSource = new CancellationTokenSource();

                // Starting the processor does not block when starting; delay
                // until the cancellation token is signaled.
                try
                {
                    await processor.StartProcessingAsync(cancellationSource.Token);
                    await Task.Delay(Timeout.Infinite, cancellationSource.Token);
                }
                catch (TaskCanceledException ex)
                {
                    Log.Logger.Error($"TaskCanceledException {ex}");

                    string emailBody = $"Environment: {environmentName}" + Environment.NewLine +
                                        $"Time: {DateTimeOffset.UtcNow}" + Environment.NewLine +
                    $"Error: {ex} {Environment.NewLine}" +
                                        $"TaskCanceledException Exception {ex}";

                    EventProcessor.LogException(emailBody);
                }
                finally
                {
                    //// Stopping may take up to the length of time defined
                    //// as the TryTimeout configured for the processor;
                    //// By default, this is 60 seconds.
                    await processor.StopProcessingAsync();
                }
                
                
                
           //// event triggered in case of the message received  in EventProcessor class inherited from PluggableCheckpointStoreEventProcessor<EventProcessorPartition>


         protected async override Task OnProcessingEventBatchAsync(
            IEnumerable<EventData> events,
            EventProcessorPartition partition,
            CancellationToken cancellationToken)
        {
            EventData lastEvent = null;

            try
            {
                Console.WriteLine($"Received events for partition {partition.PartitionId}");

                var sw = Stopwatch.StartNew();
                sw.Start();
                using (var serviceScope = Program.ServiceProvider.GetRequiredService<IServiceScopeFactory>().CreateScope())
                using (var DBContext = serviceScope.ServiceProvider.GetService<DBContext>())
                {
                    foreach (var message in events)
                    {
                        try
                        {
                            string telemetryData = message.EventBody.ToString();
                            Console.WriteLine($"telemetryDatas: {telemetryData}");
                        }
                        catch (Exception ex)
                        {
                            Console.WriteLine($"Exception while processing events: {ex}");
                        }

                        lastEvent = message;
                    }

                    if (lastEvent != null)
                    {
                        await this.UpdateCheckpointAsync(
                            partition.PartitionId,
                            lastEvent.Offset,
                            lastEvent.SequenceNumber,
                            cancellationToken)
                        .ConfigureAwait(false);
                    }
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine($"Exception while processing events: {ex}");
            }
        }
                
                
                ```

**Comment by 4ff4n** [comment]
I am also facing the same issue, @bilalmalik777 please let me know the solution. 
thanks.

**Comment by jsquire** [comment]
There's a lot to unpack here, and I'm not sure that I'm following the scenario end-to-end.  I'd like to start by ensuring that we have a common understanding of the ecosystem:

- IoT Hub and Event Hubs are different systems.  When messages are sent to IoT Hub, it then forwards them to Event Hubs.  A message being sent to IoT Hub will have some latency between the time it is accepted by IoT Hub, visible to IoT Hub, and available to be read from Event Hubs.   

- Event Hubs prioritizes maximizing throughput, not latency for an individual event.   As a result, it does not provide an SLA around latency for the time an event is accepted and when that event is available to be read from a partition.  Generally, this is in the order of milliseconds, but can take longer.   For example, if the host for a partition is being moved to a new node.   

- The Event Hubs processor works with Event Hubs and has no insight into IoT Hub; data must be available in an Event Hub partition for the processor to read it.   I cannot speak to what data the Azure CLI command in use is reading from.  It may be an apples-to-oranges comparison.

That established, I'd like to focus on the processor and see if there's anything that may cause abnormal results.   It would be helpful to know:

- How many partitions does the Event Hub have?
- How many other processors are working against the Event Hub for the same consumer group?
- How many CPU cores does the machine hosting each processor have?
- When your `OnProcessingEvents` method is invoked, what's the average number of events in each batch that it is being called with?
- What is the `OnProcessingError` method seeing during this period?
- What activities are the `OnInitializingPartitionAsync` and `OnPartitionProcessingStoppedAsync` methods observing during this period?
- What is the traffic pattern like in the Event Hub? (average payload size, how quickly they're being published, whether activity is consistent or comes in bursts)
- Is there an event backlog in the partitions or are events being read as-they-arrive?

Looking at the code snippets that you've provided, one thing stands out for me.   You're setting prefetch to 512 and batch size to 256.   That's a smaller prefetch size then would be recommended for the batch.  I'd recommend setting it to at least 768.   Because Event Hubs consumers read exclusively from prefetch, testing and tuning the prefetch against the desired batch size is important for optimizing throughput.   More context and guidance can be found [here](https://learn.microsoft.com/dotnet/api/azure.messaging.eventhubs.primitives.eventprocessoroptions.prefetchcount?view=azure-dotnet#remarks).

To understand what the processor is seeing, e'll also want to capture the SDK logs.  A +/- 5-minute slice around the behavior that you're describing should help us narrow things down.  Specifically, we're interested in capturing verbose logs and filtering to:

Event Source Name: "Azure-Messsaging-EventHubs"

- All warnings
- All errors
- 6 (Event Receive Start)
- 7 (Event Receive End)
- 8 (Event Receive Error)
- 36 (Event Processor Task Error)
- 37 (EventProcessorPartitionProcessingStart)
- 38 (EventProcessorPartitionProcessingStartError)
- 39 (EventProcessorPartitionProcessingStartComplete)
- 40 (EventProcessorPartitionProcessingStop)
- 41 (EventProcessorPartitionProcessingStopError)
- 42 (EventProcessorPartitionProcessingStopComplete)
- 43 (EventProcessorParitionProcessingError)
- 44 (EventProcessorLoadBalancingError)
- 45 (EventProcessorClaimOwnershipError)
- 103 (EventProcessorLoadBalancingCycleSlowWarning)
- 104 (EventProcessorHighPartitionOwnershipWarning)
- 123 (EventProcessorProcessingHandlerStart)
- 124 (EventProcessorProcessingHandlerComplete)
- 125 (EventProcessorProcessingHandlerError)

Techniques for capturing the logs are discussed in [this sample](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/eventhub/Azure.Messaging.EventHubs/samples/Sample10_AzureEventSourceListener.md).
