### ISSUE TITLE
[BUG] CreateOrUpdate on VaultResource deletes all AccessPolicies

### ISSUE THREAD

**Issue by cmenzi** [Azure/azure-sdk-for-net#32872]
### Library name and version

Azure.ResourceManager.KeyVault 1.0.0

### Describe the bug

`CreateOrUpdate` on a existing KeyVault deletes all existing AccessPolicies. I think the root case is this MR #28678, where the AccessPolicy list is set to a new list explicitly in the ctor.

### Expected behavior

`CreateOrUpdate` should only updates the KeyVault properties and not delete all Access Policies.

### Actual behavior

`CreateOrUpdate` deletes all Access Policies just by updating the `Tags` for examples.

### Reproduction Steps

1. Create KeyVault 
2. Assign Access Policy
3. CreateOrUpdate on the KeyVault with exsting AccessPolices

Result: Access Polices are gone.

### Environment

.NET SDK:
 Version:   7.0.100
 Commit:    e12b7af219

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19044
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.100\

Host:
  Version:      7.0.0
  Architecture: x64
  Commit:       d099f075e4

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by Yao725** [comment]
Thanks for your finding, I will dig into this issue.

**Comment by Yao725** [comment]
Hi @cmenzi, thanks for your feedback. I want to share more details here.

The change that I made in #28678 is not going to introduce bug, it's a workaround for https://github.com/Azure/azure-rest-api-specs/issues/19022. Without that change, this request cannot work and you will get the exception that the parameter accessPolicies is not specified if you call the method and don't specify the AccessPolicies.

If you want to update your existing KeyVault, I think you should use the [Update](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/keyvault/Azure.ResourceManager.KeyVault/src/Generated/KeyVaultResource.cs#L297) method instead of CreateOrUpdate. For example, you can only update the tags and this method should work as you expect. If you still want to use the CreateOrUpdate method, I believe you should keep the same AccessPolicies when you call the method for the second time.

**Comment by cmenzi** [comment]
@Yao725 Some of the resource are using some kind a change tracking list. For me the `CreateOrUpdate` method implies that it's created when it does not exists and it's updated when it's already exist.

The `Update` approach also works for my now. But it's really different to all other resource types.

**Comment by Yao725** [comment]
Ok, that makes sense. I'd like to wait for the fix of this [issue](https://github.com/Azure/azure-rest-api-specs/issues/19022) so we can decide how to handle this request. If the service team changes this property to be required, it's reasonable that you need to pass this parameter. If they just remove the requirement about this property, I will update the code corresponding,

**Comment by mcgallan** [comment]
This BUG has been fixed, you can try it out with the [new version](https://www.nuget.org/packages/Azure.ResourceManager.KeyVault/1.2.0-beta.1)

**Comment by mcgallan** [comment]
> @mcgallan What exactly has been fixed? Will the AccessPolicies now been preserved? Or are they mandatory?

Now you can use CreateOrUpdate() to update the properties(such as tags) without deleting Access Policies in the new version

**Comment by cmenzi** [comment]
Checked. It works now as expected.
