### ISSUE TITLE
[QUERY] Azure Search Indexers

### ISSUE THREAD

**Issue by ssghoda** [Azure/azure-sdk-for-net#32942]
### Library name and version

Azure.Search.Documents 11.3.0

### Query/Question

Can we have following two changes in Azure Search Service environment?

1. Can we separate Indexer's "Docs Succeeded" column into two separate columns: Docs Updated and Docs Deleted so that we are also able to know how many docs were deleted by Soft Delete policy?
2. Can we set up a way and register an email address or a distribution list for a Search Service environment so that whenever any Indexer's LastResult gets any Failed docs and/or gets errors, then that email address/distribution list will get an email of Indexer name, Search service name, other Indexer information such as linked Index/Data Source, FailedItemCount and all Error Messages?

Would like to hear thoughts.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by ShivangiReja** [comment]
This seems like a Search portal queries.

Adding @giakas from the Search Service team best able to assist you.

**Comment by ShivangiReja** [comment]
This seems like a Search portal queries.

Adding @gmndrg from the Search Service team best able to assist you.

**Comment by ssghoda** [comment]
Regarding point 1 above, my only curiosity was to see the number of docs updated and number of docs deleted (using soft delete policy) separately somehow.

**Comment by ssghoda** [comment]
Hi @gmndrg @ShivangiReja Any update on this one?

**Comment by gmndrg** [comment]
Hello @ssghoda Thank you so much for raising the above and apologies for the delay in the response. Most of our team is out on Holidays. Since these are requests for new additions to the current functionality or changes in the way it is deployed today, I have added this to our internal database of new functionality for consideration in future updates. This can't be tracked externally since this is not an issue of the current functionality, but instead a request to be able to support something different. New ideas/requests are discussed periodically based on customer demand and other projects' priority, so we are not able to provide further information regarding the feasibility of implementation at this time.

For request #2 specifically the consideration would be to add indexer errors as part of the indexers Monitoring->Create alert options in the portal so it is a separate signal. 

We really appreciate your feedback and your help to make our product better. If you have any other question or concern in the meantime, please let us know. Otherwise, we'll wait a few weeks to close the GitHub issue, since tracked separately. Thanks!

**Comment by ssghoda** [comment]
Hi @gmndrg I was just following up with you if there was any update on #1 item.

**Comment by gmndrg** [comment]
Hello @ssghoda there is no ETA for this functionality and not planned for this calendar year, unfortunately, due to very high priority projects at this time. We do have it in our backlog to consider in the future if there is more demand for this. I'm sorry there is no other update.

**Comment by ShivangiReja** [comment]
This feature request is specifically for the service team, and the SDK can only incorporate features that are supported by the service. If you have any questions related to the search service, please raise an issue at [Azure Search · Community](https://feedback.azure.com/d365community/forum/9325d19e-0225-ec11-b6e6-000d3a4f07b8). For any SDK-related questions, feel free to create issues on [Azure SDK for .NET Github](https://github.com/Azure/azure-sdk-for-net/issues).
