### ISSUE TITLE
[FEATURE REQ] Generate SAS Token for Blob directory

### ISSUE THREAD

**Issue by JKamsker** [Azure/azure-sdk-for-net#33079]
### Library name

Azure.Storage.Blobs

### Please describe the feature.

Creating a sas token for a blob works as following:

```csharp
var container = new BlobContainerClient(connectionString, containerName);
container.GetBlobClient("a/b.txt").GenerateSasUri(new BlobSasBuilder(BlobSasPermissions.All, DateTimeOffset.UtcNow.AddHours(1)));
```

This does not work for directories like "a/". 
According to [the docs](https://learn.microsoft.com/en-us/rest/api/storageservices/create-user-delegation-sas#user-delegation-sas-support-for-directory-scoped-access) this should be possible if  i understand it right.

Is there currently a way of archiving this? If not, can you  add this capability?

**Comment by navba-MSFT** [comment]
@JKamsker Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment]
@JKamsker Firstly, there is no concept of Directory (folder) in the Blob Storage, since it is a flat structure. You should [enable Hierarchal Namespace](https://learn.microsoft.com/en-us/azure/storage/blobs/upgrade-to-data-lake-storage-gen2-how-to?tabs=azure-portal) on your Azure Storage Account and Upgrade this to a Datalake Storage Account. This will provide the File System Semantics on your Storage account. You will then be able to set the SAS at the directory level.

In a storage account with a **hierarchical namespace enabled**, you can create a service SAS for a directory. To create the service SAS, make sure you have installed version 12.5.0 or later of the [Azure.Storage.Files.DataLake](https://www.nuget.org/packages/Azure.Storage.Files.DataLake/) package.

[Here ](https://learn.microsoft.com/en-us/azure/storage/blobs/sas-service-create?tabs=dotnet#create-a-service-sas-for-a-directory)is the sample code to achieve your requirement.

**Comment by navba-MSFT** [comment]
@JKamsker I wanted to do quick follow-up to check if you had a chance to look at my above comment. Please let us know if you had any updates on this. Awaiting your reply.

**Comment by JKamsker** [comment]
Yes, thanks that wors :)

@navba-MSFT
