### ISSUE TITLE
how to execute the given  swagger api

### ISSUE THREAD

**Issue by SatyaRvnkr** [Azure/azure-sdk-for-net#33138]
### Library name and version

swagger

### Query/Question

how to execute the given  swagger api

**Comment by jsquire** [comment]
Hi @SatyaRvnkr.  Thank you for reaching out and we regret that you're experiencing difficulties.  Unfortunately, this repository is focused on the Azure SDK for .NET - we're unable to assist with other issues.  Since what you're describing appears to be related to OpenAPI (swagger) and not one of the Azure SDKs, it is not something that we can help with.

I'm going to close this out; if I've misunderstood what you're describing, please let us know in a comment and we'd be happy to assist as we're able.

**Comment by SatyaRvnkr** [comment]
Thank you for your response
