### ISSUE TITLE
DOCS: `TableClient.GetEntityIfExists(-Async)` has misleading documentation about thrown exceptions

### ISSUE THREAD

**Issue by Ilia-Kosenkov** [Azure/azure-sdk-for-net#33144]
### Library name and version

Azure.Data.Tables 12.7.1

### Query/Question

(Since this is not strictly a bug or vulnerability, I file it as a question/query).

I believe that the documentation (xml comments) associated with the following methods
- [Azure.Data.Tables.TableClient.GetEntityIfExists](https://github.com/Azure/azure-sdk-for-net/blob/e8664098abd0fdc00edcee78867b1245d2f4529f/sdk/tables/Azure.Data.Tables/src/TableClient.cs#L710)
- [Azure.Data.Tables.TableClient.GetEntityIfExistsAsync](https://github.com/Azure/azure-sdk-for-net/blob/e8664098abd0fdc00edcee78867b1245d2f4529f/sdk/tables/Azure.Data.Tables/src/TableClient.cs#L727)

incorrectly inform consumers that these methods throw `RequestFailedException` if the entity is missing. Reading through https://github.com/Azure/azure-sdk-for-net/pull/30888 and related issues, I found that the purpose of these methods is to not raise an exception when a query to Azure table returns HTTP 404. We checked this against test Azure environment and got no exception when querying for a missing entity.

This information also gets reflected on the [Microsoft Learn](https://learn.microsoft.com/en-us/dotnet/api/azure.data.tables.tableclient.getentityifexistsasync?view=azure-dotnet#exceptions) page, and it is from there I first learned about inconsistent method documentation.

I am happy to submit a tiny PR if this is indeed an issue and it has not yet been fixed. Or perhaps you can fix it as part of your internal workflow.

### Environment

N/A

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by christothes** [comment]
You're correct that it appears that we fixed the sync one
https://github.com/Azure/azure-sdk-for-net/blob/e8664098abd0fdc00edcee78867b1245d2f4529f/sdk/tables/Azure.Data.Tables/src/TableClient.cs#L707

 but not the other. 
https://github.com/Azure/azure-sdk-for-net/blob/e8664098abd0fdc00edcee78867b1245d2f4529f/sdk/tables/Azure.Data.Tables/src/TableClient.cs#L724

I'm happy to accept a PR if you'd like to submit one. Otherwise, I'll get to this after the holidays.
