### ISSUE TITLE
[QUERY] Replacing KeyVaultClient with SecretClient

### ISSUE THREAD

**Issue by vidya123** [Azure/azure-sdk-for-net#33151]
### Library name and version

Azure.Security.KeyVault.Secrets

### Query/Question

    Hi,

We are using KeyVaultClient(Singleton) and used it to access multiple endpoints like below.

<img width="1124" alt="image" src="https://user-images.githubusercontent.com/6707597/208972172-50a731a8-6ba4-4e07-8dc6-9669f66fbdba.png">

But we are currently migrating to use Azure.Security.KeyVault.Secrets. Looking at the way SecretClient is instantiated, we were supposed to supply endpoint(uri) at the time of instantiation itself and needs to call Defaultcredential(). I do know that I can try to cache a secret client per endpoint, but this raises a bit of complexity in our scenario since the endpoints can be dynamic. 

Now:
<img width="729" alt="image" src="https://user-images.githubusercontent.com/6707597/208972389-8ea5399e-cd6e-403c-a6a6-b5359adc6bf3.png">

Creating SecretClient everytime we access new endpoint may cause performance regression.  So is there a way of using SecretClient to avoid such a regression?

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.  Please be aware that due to the US holidays, responses are likely to be delayed.

**Comment by vidya123** [comment]
Also is there a way around to mock CertificateOperation?

**Comment by heaths** [comment]
All our clients are thin clients. There's really not much overhead, so creating and caching one client per endpoint is not expensive, nor should instantiating one be - though more expensive than caching since we do instantiate a number of classes for the HTTP pipeline. If you want to decrease overhead more, you can use a shared `HttpClient` as described here: https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/core/Azure.Core/samples/Configuration.md#user-provided-httpclient-instance

As for mocking [`CertificateOperation`](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/keyvault/Azure.Security.KeyVault.Certificates/src/CertificateOperation.cs), it's mockable in the same way our clients are. You could use Moq, for example, to mock a `CertificateClient` and return a `Mock<CertificateOperation>`. All the methods and properties are virtual so you can override them, like `UpdateStatus` and `UpdateStatusAsync`. See https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/core/Azure.Core/samples/Mocking.md for how to return a pageable, for example. Returning a `Mock<CertificateOperation>` would be similar.
