### ISSUE TITLE
[FEATURE REQ] There doesn't appear to be a Quota API for Azure SQL Databases (and Logical Servers)

### ISSUE THREAD

**Issue by sdavis3** [Azure/azure-sdk-for-net#33164]
### Library name

Azure Quota Service API

### Please describe the feature.

There is currently no way to determine your quota or utilization of Azure SQL Databases (and Logical Servers) in an Azure subscription. The current limit is 250 per region, per subscription as defined at [https://learn.microsoft.com/en-us/azure/azure-sql/database/resource-limits-logical-server?view=azuresql](https://learn.microsoft.com/en-us/azure/azure-sql/database/resource-limits-logical-server?view=azuresql). However, the Azure Portal UI limits you to 200. This is likely a UI bug. Nevertheless, there is no Quota API that can be used to determine or change the current state. 

![Screenshot 2022-12-22 at 2 10 16 PM](https://user-images.githubusercontent.com/1821509/209228951-27035412-dc3c-433f-9ed9-4e07458b589b.jpg)

**Comment by jsquire** [comment]
Hi @sdavis3.  Thank you for reaching out and we regret that you're experiencing difficulties.  Unfortunately, this repository is focused on the Azure SDK for .NET - we're unable to assist with other Azure issues.  Since what you're describing appears to be related to the Azure portal and not one of the SDK packages, your best path forward would be to [open an Azure support request](https://docs.microsoft.com/azure/azure-portal/supportability/how-to-create-azure-support-request).

I'm going to close this out;  if I've misunderstood what you're describing, please let us know in a comment and we'd be happy to assist as we're able.

**Comment by sdavis3** [comment]
I would disagree. I used the portal as an example of how I ended up here. The SDK does not support the same functionality. It's a feature request of the SDK to add support for Azure SQL Database Quotas.

**Comment by jsquire** [comment]
Apologies; that's my mistake, then.   Reactivating and triaging.

**Comment by jsquire** [comment]
@xboxeer:  Can you please confirm whether or not this exists in the REST API and, if not, advise on a path for @sdavis3 to make a service request?

**Comment by sdavis3** [comment]
With all due respect, this has been one of the most painful exercises I've ever been through with an SDK.

1.) The link shared in the reply above is not available. However, I was able to search and find the area that was being referenced.
2) The institutional knowledge needed to populate the support ticket objects with precisely the right data is extremely difficult to find out without scouring the MSLearn pages and executing various REST calls to get precisely the right GUIDs needed to populate the request.

After spending hours doing this, only to finally get the following result back from the API: "Azure.RequestFailedException: Your support plan type is Standard. To create and update support tickets, and add communication operations, you need access to our high tier-support plans." Quota API increases should not be hidden behind a support paywall. This is misguided and misplaced as the portal does not require the same to submit a Quota request.

Regardless of the above, the idea that this level of effort is needed for a simple request to increase a Quota is beyond me. The API has been available for years to the community and there appears to be no action taken to resolve this gap. The portal incorrectly limits the number of Azure SQL Servers to 200 when the limit is actually 250. The API hides quota increases behind a paywall and the SDK does not appear to address or overcome either of these concerns.

As a long-standing customer of Azure, it feels like I'm chasing ghosts here. Who exactly can assist with resolving this issue?

**Comment by Yao725** [comment]
Hi @sdavis3, sorry for the wrong link, I forgot that we are doing some sample migration work, that's my bad.

And as a client-side tool, our SDK code is based on the API spec from the service team, we are continuing to providing more documents and samples to help the customers but here I don't see much space to improve the code itself. Back to your question, I think the better way is to create a support request on [Portal](https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request) about the incorrect limit number, so that the support engineer could trace and resolve this issue.
