### ISSUE TITLE
[BUG] Azure.ResourceManager.Logic.LogicWorkflowResource.UpdateAsync always returns 400 BadRequest

### ISSUE THREAD

**Issue by jdefesche1** [Azure/azure-sdk-for-net#33246]
### Library name and version

Azure.ResourceManager.Logic 1.0.0

### Describe the bug

When I call UpdateAsync irrespective of having updated the Data.Definition, it returns a bad request (Resource Definition is invalid). I've used fiddler to capture traffic using the deprecated package (Microsoft.Azure.Management.Logic) when calling UpdateAsync. Repeated the process for Azure.ResourceManager.Logic but there I see no body.

See the document containing the Fiddler traces:
[Azure.ResourceManager.Logic bug MS.docx](https://github.com/Azure/azure-sdk-for-net/files/10319651/Azure.ResourceManager.Logic.bug.MS.docx)

### Expected behavior

When calling LogicWorkflowResource.UpdateAsync the json representation of the definition should be included in the request.

### Actual behavior

The exception I get while debugging is
![badrequest](https://user-images.githubusercontent.com/54059023/209956828-cd44335c-1093-4c07-adf6-abc3c3fb5b2c.png)

### Reproduction Steps

1. Get a workflow using GetAsync()
2. Update the workflow using UpdateAsync()

### Environment

- Visual Studio 2022 (64 bit) 17.3.6
- Windows server 2022 version 21H2 OS Build 20348.887
- project is class library .net standard 2.0

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.  Please expect delayed responses due to the US holidays.

**Comment by Yao725** [comment]
Thanks for reaching out to us, will dig into this issue.

**Comment by Yao725** [comment]
This issue can be reproduced and the behavior is same when I used Postman to send the request directly. It turns out that this is API spec issue, this [request](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/logic/resource-manager/Microsoft.Logic/stable/2019-05-01/logic.json#L277-L298) doesn't define the body parameter. There is already [issue](https://github.com/Azure/azure-rest-api-specs/issues/18132) complaining about this problem.

I have left a comment in [18132](https://github.com/Azure/azure-rest-api-specs/issues/18132) to ask for the update, but considering the latest API version is almost four years ago, I opened #33944 to work around this issue from SDK side and the simple [test](https://github.com/Azure/azure-sdk-for-net/blob/6d963644a1940ed3039e76195e6fe0542a58e10c/sdk/logic/Azure.ResourceManager.Logic/tests/Scenario/LogicWorkflowsTests.cs#L91) shows this fix could work as expected.

**Comment by jdefesche1** [comment]
Hi, thanks for the update. Once your PR is approved, how much time does it take before the update becomes available?

**Comment by Yao725** [comment]
I think the release will be no later than the end of this month.

**Comment by Yao725** [comment]
The new version has been released: https://www.nuget.org/packages/Azure.ResourceManager.Logic/1.0.1

**Comment by jdefesche1** [comment]
Thanks, I've updated the package and the problem is gone
