### ISSUE TITLE
VirtualMachines.Define using WithStoredWindowsImage - The api-version '2016-04-30-preview

### ISSUE THREAD

**Issue by pppchris** [Azure/azure-sdk-for-net#3331]
"ExceptionMessage": "The api-version '2016-04-30-preview' is invalid. The supported versions are '2017-05-10,2017-05-01,2017-03-01,2016-09-01,2016-07-01,2016-06-01,2016-02-01,2015-11-01,2015-01-01,2014-04-01-preview,2014-04-01,2014-01-01,2013-03-01,2014-02-26,2014-04'.",

When trying to create a VM using a custom image.

**Comment by hovsepm** [comment]
@pppchris could you provide the REST communication (e.g. Fiddler trace log)? That API version should be still available.

**Comment by pppchris** [comment]
Sure, no worries. 

Have tried different settings with the network interface (such as create a new one) but that throws a similar error but pointing to a different API version. 

`{
  "properties": {
    "hardwareProfile": {
      "vmSize": "Standard_DS2"
    },
    "storageProfile": {
      "imageReference": {
        "id": "**image id**"
      },
      "osDisk": {
        "caching": "ReadWrite",
        "createOption": "fromImage",
        "managedDisk": {
          "storageAccountType": "Standard_LRS"
        }
      }
    },
    "osProfile": {
      "computerName": "**compname**",
      "adminUsername": "**admin user**",
      "adminPassword": "**admin pass**",
      "windowsConfiguration": {
        "provisionVMAgent": true,
        "enableAutomaticUpdates": true
      }
    },
    "networkProfile": {
      "networkInterfaces": [
        {
          "properties": {
            "primary": true
          },
          "id": "**network interface**"
        }
      ]
    }
  },
  "location": "eastus2",
  "tags": {
    "yey": "yey"
  }
}`

**Comment by anuchandy** [comment]
@pppchris 

It will be great if you can share the code fragment and full fiddler trace as @hovsepm mentioned.

Mean time we would like to share some details about "Custom image", since it can be created in various ways.

You have mentioned that you are trying to create virtual machine from "Custom Image". There are mainly 3 ways to create "custom image".

1. Custom image from native VHD
2. Custom image by capturing a virtual machine
3. Custom image from managed disks.

These 3 cases are covered in this [UT](https://github.com/Azure/azure-sdk-for-net/blob/Fluent/src/ResourceManagement/Azure.Fluent/Fluent.Tests/Compute/VirtualMachineCustomImageOperationsTest.cs). UT also shows how to create virtual machine from custom image.

The above listed ways of creating custom image feature is released along with `managed disk`. This is the new/recommended way of creating custom image.

There is older way of creating "custom image" (aka stored image) which is done by capturing a virtual machine based on `un-managed disk`. you can see the sample [here](https://github.com/Azure/azure-sdk-for-net/blob/Fluent/Samples/ResourceManagement/Compute/CreateVMsUsingCustomImageOrSpecializedVHD/Program.cs).

**Comment by pppchris** [comment]
Hey @hovsepm @anuchandy 
What's the best way to dump the full trace so I can remove sensitive information? The JSON trace above was the trace request going off upon the create request.

I am using "Custom image by capturing a virtual machine". I used the JSON above in a Deployment Template it worked out any issues as well. 

Code:

`            var NetworkInterface = Azure.Repo.NetworkInterfaces.GetById(interface);

            var baseVM = Azure.Repo.VirtualMachines.Define(name)
                .WithRegion(Region.USEast2)
                .WithExistingResourceGroup(resourcegroup)
                .WithExistingPrimaryNetworkInterface(NetworkInterface)
                .WithWindowsCustomImage(imageuri)
                .WithAdminUsername(username)
                .WithAdminPassword(password)
                .WithSize(VirtualMachineSizeTypes.StandardDS2)
                .WithTag("yey", "yey")
                .Create();`

**Comment by hovsepm** [comment]
This issue was moved to Azure/azure-libraries-for-net#53
