### ISSUE TITLE
Intermittent OperationCanceledExceptions upon EventHubConsumerClient.GetPartitionIdsAsync and GetPartitionPropertiesAsync

### ISSUE THREAD

**Issue by deyanp** [Azure/azure-sdk-for-net#33473]
We are running numerous pods in AKS which are either publishing messages to Azure Event Hubs, or consuming such. The number of messages we publish/consume is pretty low and irregular.

Every such pod has a "health check" configured to be invoked every 5 minutes (by Application Insights Availability checks) which simply calls `EventHubConsumerClient.GetPartitionIdsAsync` and `EventHubConsumerClient.GetPartitionPropertiesAsync` to get last enqueued time and calculate if there is any message which has not yet been consumed within a certain predefined timeframe (alert if that is the case). 

Every pod keeps a single static EventHubConsumerClient reference initialized upon pod startup.

From time to time (e.g. about 50 out of the 288 executions of the health check per day) we get something like this

```
[41m[30mfail[39m[22m[49m: Azure.Messaging.EventHubs[14] An exception occurred while retrieving properties for Event Hub: mon-alert-events. Error Message: 'The operation was canceled. (mon-alert-events).  For troubleshooting information, see https://aka.ms/azsdk/net/eventhubs/exceptions/troubleshoot'
```

If I look at the logs I see something like this:

```
2023-01-13T13:51:18.392642305Z info: object[9999] Health Check: Testing EventHub Connection to aaa-bbb-event-hubs3/cs-xxx-yyy-events/notif-svc (CorId: 9f5310d7-58ae-456a-955b-889e77d8e770)
**2023-01-13T13:51:18.393170275Z fail: Azure.Messaging.EventHubs[14] An exception occurred while retrieving properties for Event Hub: cs-xxx-yyy-events. Error Message: 'The operation was canceled. (cs-xxx-yyy-events).  For troubleshooting information, see https://aka.ms/azsdk/net/eventhubs/exceptions/troubleshoot'**
2023-01-13T13:51:20.030166592Z info: object[9999] Health Check: Tested OK EventHub Connection to aaa-bbb-event-hubs3/cs-xxx-yyy-events/notif-svc (CorId: 9f5310d7-58ae-456a-955b-889e77d8e770)
```

It seems that the operation gets cancelled immediately (within a couple of ms) and the automatic retry (done by the EventHubConsumerClient) is successful afterwards. 

My question is - why do we get these exceptions (flooding daily our logs) and what can we do to remove these? 

My initial suspicion was that connection becomes idle and disposed, but even after increasing the `ConnectionIdleTimeout` in `EventHubConsumerClientOptions.ConnectionOptions `to 10 minutes I still experience the issue ...

Additional details:
`<PackageVersion Include="Azure.Messaging.EventHubs" Version="5.7.5" />`

**Comment by jsquire** [comment]
Hi @deyanp.  Thank you for reaching out and we regret that you're experiencing difficulties.   This exception typically occurs when a service operation takes longer to complete than the configured `TryTimeout`.    More information on the timeout used for service operations and how to adjust it can be found in [this sample](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/eventhub/Azure.Messaging.EventHubs/samples/Sample02_EventHubsClients.md#configuring-the-timeout-used-for-event-hubs-service-operations).

Causes could be intermittent network issues, a slow network, acquiring an token for authorization was slow, contention in the threadpool preventing continuations from being scheduled in a timely manner, or other environmental factors.   Without the full stack trace, it's not possible to speculate on what the cause for this instance is.   If you're willing to share that, it may offer further insight.

**Comment by deyanp** [comment]
@jsquire, but why is the exception thrown only 1-2 **milliseconds** after the call? If it was a timeout, shouldn't it be a few seconds at least?

Not getting any stack trace, it seems that the log is done by the Azure SDK itself (as also the link to help page is included), and an automatic internal retry is done by Azure SDK immediately ...

I actually tried to simulate the error by running 500 calls in a loop with the following F# code, but I could not:

```fsharp

#r "nuget: Azure.Core"
#r "nuget: Azure.Messaging.EventHubs"
#r "nuget: Microsoft.Extensions.Logging.Abstractions"
#r "nuget: Microsoft.Extensions.Logging.Abstractions"
#r "nuget: Microsoft.Extensions.Azure"
#r "nuget: Microsoft.Extensions.Logging.Console"
#r "nuget: Microsoft.ApplicationInsights"

open System
open Azure.Messaging.EventHubs
open Azure.Messaging.EventHubs.Consumer
open FSharp.Control
open Microsoft.Extensions.Logging
open Microsoft.Extensions.DependencyInjection

let getConsumerClient (connectionString: string) (consumerGroup: string) : EventHubConsumerClient =
    EventHubConsumerClient(consumerGroup, connectionString)

let getPartitionWithLastEnqueuedTimeUtc (eventHubClient: EventHubConsumerClient) =
    async {
        let! partitionIds = eventHubClient.GetPartitionIdsAsync() |> Async.AwaitTask

        let! partProps =
            partitionIds
            |> Array.map (fun pid -> eventHubClient.GetPartitionPropertiesAsync(pid) |> Async.AwaitTask)
            |> Async.Parallel

        let partitionId, lastEnqTimeUtc =
            partProps
            |> Array.map (fun pInfo -> (pInfo.Id, pInfo.LastEnqueuedTime))
            |> Array.maxBy (fun (_, lastEnqTimeUtc) -> lastEnqTimeUtc)

        return partitionId, lastEnqTimeUtc
    }

let getLastEnqueuedTimeUtc (eventHubClient: EventHubConsumerClient) =
    async {
        let! _, lastEnqTimeUtc = getPartitionWithLastEnqueuedTimeUtc eventHubClient
        return lastEnqTimeUtc
    }

let connStr = "Endpoint=sb://XXXXX.servicebus.windows.net/;SharedAccessKeyName=YYYYY;SharedAccessKey=ZZZZ;EntityPath=AAAA"
let consGroup = "BBBB"
let eventHubSubClient: EventHubConsumerClient = getConsumerClient connStr consGroup

[1..500]
|> List.map (fun _ ->
    async {
        try
            let! x = getLastEnqueuedTimeUtc eventHubSubClient
            printfn "%A" x
        with e ->
            printfn "%A" e
    }
)
|> Async.Parallel
|> Async.RunSynchronously
```

**Comment by jsquire** [comment]
@deyanp:  The `TryTimeout` is the total amount of time allowed the entire end-to-end operation.   This includes multiple steps, such as establishing a connection, creating a link, performing authorization and, in this case, the read.   As each step completes, the amount of time left in the `TryTimeout` is calculated and passed for the next step.   

If, for example, establishing a connection, acquiring a token, and performing authorization takes 59 seconds, 750 milliseconds then the read has only 250 milliseconds left and will timeout after.   Since the error message is based only on the failed step, it would report that the operation could not be completed in 250 milliseconds.  This pattern is often helpful in troubleshooting, as it offers clues as to where bottlenecks are occurring.  For a straight cancellation like this, the timeout and resulting cancellation in the AMQP transport layer and is outside of the control of the Event Hubs SDK.   Without the full stack trace, that would be my speculation.  The stack trace would very likely help us understand exactly which step of the process saw the timeout.

These errors are often the result of transient network issues - like DNS resolution taking unusually long - which makes them difficult to reproduce in code and often unique to the given host and environment.  The one thing that I'll note is that even if you bump the connection idle timeout, the Event Hubs service will boot connections after a period of time and require reconnect.  This takes place whether the connection is idle or active.   

Performing operations in parallel, as you are, would be less likely to encounter the timeout if its related to connection or auth, as this cost is paid once and the resulting connection is shared for all of the parallel requests.  Better would be to a long-running a loop where you invoke the operation every few minutes.  That said, the nature of these and likelihood that it is a transient network issue makes it incredibly hard to reproduce on demand.   

My suggestion would continue to be ensuring that you do not allow for less than the default `TryTimeout` (60 seconds) and if you're seeing this happen with any regularity try diagnosing the network conditions (ability to resolve DNS, ability to perform a TLS handshake, ability to route to the Event Hubs namespace).    If you're using a token credential as your authorization (rather than connection string), then monitoring the time taken to acquire a token would also be worthwile.
