### ISSUE TITLE
[BUG] Empty messages in azure function service bus trigger using package Microsoft.Azure.WebJobs.Extensions.ServiceBus 5.8.1

### ISSUE THREAD

**Issue by hi-dasari** [Azure/azure-sdk-for-net#33485]
### Library name and version

Microsoft.Azure.WebJobs.Extensions.ServiceBus 5.8.1

### Describe the bug

When I use Microsoft.Azure.WebJobs.Extensions.ServiceBus 5.8.1", message is getting completely missing when we try to deserializing with type "Microsoft.Azure.ServiceBus.Message". Below is the sample code.

```csharp
using Microsoft.Azure.ServiceBus;
using Microsoft.Azure.WebJobs;
using Microsoft.Extensions.Logging;

namespace TestFunction
{
    public class Function1
    {
        private readonly ILogger<Function1> _logger;

        public Function1(ILogger<Function1> log)
        {
            _logger = log;
        }

        [FunctionName("Function1")]
        public void Run([ServiceBusTrigger("profileprodtopic", "hidasa-test", Connection = "ServiceBusConnectionKey")]Message mySbMsg)
        {
            _logger.LogInformation($"C# ServiceBus topic trigger function processed message: {mySbMsg}");
        }
    }
}
```

**Project file** 

```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <AzureFunctionsVersion>v4</AzureFunctionsVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.ServiceBus" Version="5.8.1" />
    <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="4.1.1" />
    <PackageReference Include="Microsoft.Azure.ServiceBus" Version="5.2.0" />
  </ItemGroup>
  <ItemGroup>
    <None Update="host.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="local.settings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>Never</CopyToPublishDirectory>
    </None>
  </ItemGroup>
</Project>
```

### Expected behavior

Messages triggered in function should get deserialized with Message type. 

### Actual behavior

when using "Microsoft.Azure.ServiceBus.Message" type for deserialization , its empty, but if its string type I can see body of message or if I downgrade package to  "Microsoft.Azure.WebJobs.Extensions.ServiceBus" 4.3.1, its working a expected.

### Reproduction Steps

- Create azure function with version net6 , c#
- Function runtime v4
- Configure a service bus topic & subscription.
- Use the configured subscription in azure function to trigger message to sample function.
- make sure package "Microsoft.Azure.WebJobs.Extensions.ServiceBus" with version 5.8.1 version is referred.

**Comment by jsquire** [comment]
Hi @hi-dasari.  Thank you for reaching out and we regret that you're experiencing difficulties.  Starting in v5, the Service Bus extensions moved to the `Azure.Messaging.ServiceBus` package for interacting with Service Bus.   Because there is no `Message` type in that library, the binding that you're asking for cannot be performed.   Because you still have a reference to the legacy `Microsoft.Azure.ServiceBus` library your project, the type reference is still recognized and you're not seeing the compiler error that would have helped to highlight this.

The type that you'll need to bind to is `ServiceBusReceivedMessage`.   Updating your sample, it would look something like:

```csharp
usingAzure.Messaging.ServiceBus;
using Microsoft.Azure.WebJobs;
using Microsoft.Extensions.Logging;

namespace TestFunction
{
    public class Function1
    {
        private readonly ILogger<Function1> _logger;

        public Function1(ILogger<Function1> log)
        {
            _logger = log;
        }

        [FunctionName("Function1")]
        public void Run([ServiceBusTrigger("profileprodtopic", "hidasa-test", Connection = "ServiceBusConnectionKey")]ServiceBusReceivedMessage mySbMsg)
        {
            _logger.LogInformation($"C# ServiceBus topic trigger function processed message: {mySbMsg}");
        }
    }
}
```

More information can be found in the [Usage](https://learn.microsoft.com/azure/azure-functions/functions-bindings-service-bus-trigger?tabs=in-process%2Cextensionv5&pivots=programming-language-csharp#usage) section of the trigger documentation.  Additional examples can be found in the [Microsoft.Azure.WebJobs.Extensions.ServiceBus README](https://github.com/Azure/azure-sdk-for-net/tree/main/sdk/servicebus/Microsoft.Azure.WebJobs.Extensions.ServiceBus#examples).
