### ISSUE TITLE
[BUG] "dotnet new azsdkdpg" generate unexpected file after PR 32814

### ISSUE THREAD

**Issue by dw511214992** [Azure/azure-sdk-for-net#33515]
### Library name and version

dotnet new azsdkdpg

### Describe the bug

This [PR](https://github.com/Azure/azure-sdk-for-net/pull/32814) breaks the command `dotnet new azsdkdpg --name Azure.XXX.Contosoz --clientName Contosoz --groupName XXX --serviceDirectory contoso --force` to generate a valid template. For example, there is a genereated file named `Azure.XXX..csproj` with two dots. It blocks all sdk automation pipeline for cadl.

I think the tool `dotnet new azsdkdpg` need to be fixed.

### Expected behavior

Generate valid file

### Actual behavior

Generate invalid file

### Reproduction Steps

See description

**Comment by jsquire** [comment]
@dw511214992 :  Please do not assign engineers when opening issues; our triage process will handle assignments.

**Comment by dw511214992** [comment]
@jsquire  I'm not familiar to .Net sdk. @chunyu3 could you please check it? Thanks

**Comment by dw511214992** [comment]
Add @lirenhe @maririos for awareness. As the command `dotnet new azsdkdpg...` is used by sdk automation pipeline and cadl dpg quickstart guide, it blocks all the scripts. So the azure sdk planner cadl dpg is also blocked.

**Comment by dw511214992** [comment]
Add @zzvswxy @chunyu3 for awareness. As the command `dotnet new azsdkdpg...` is used by sdk automation pipeline and cadl dpg quickstart guide, it blocks all the scripts. So the azure sdk planner cadl dpg is also blocked.

**Comment by heaths** [comment]
`dotnet tool` is a command. The `azsdkdpg` is the template in _sdk/template_ that @chunyu3 last worked on. I think the focus should be on fixing that rather than go backward. `netcoreapp3.1` is no longer supported.

I just installed the template and used it. The only problem I saw was ".." in a few file paths. This may be a regression in .NET 7. I can open a bug against it while @chunyu3 and I continue to investigate. There may be a problem in _sdk/template/.template.config/template.json_ where too many separators are output.

**Comment by jsquire** [comment]
//fyi: @m-nash

**Comment by heaths** [comment]
I've opened https://github.com/dotnet/sdk/issues/29962 to track.

I tried one change to the template to remove the "." separator, but while that fixed the extension problem it removed it from the "Azure." prefix as well, so you ended up with something like "Azureheaths.sln" instead of "Azure.heaths..sln". As a workaround, perhaps we can add another symbol that always makes sure "Azure." is present as a prefix. I can play around with that in a bit.

**Comment by heaths** [comment]
I've started an internal thread about this.

Would it be possible for now to rename any files with ".." to use just "."? We already have scripts that do a bunch of renaming, and I doubt there's any good scenario where we'd want ".." in a file name.

The scripts could add something like,

```pwsh
$filename = $filename -replace '\.\.', '.'
```

It's a short-term workaround, but one I don't see a reason to track removing either.

/cc @chunyu3 @m-nash
