### ISSUE TITLE
[BUG] AppSettings always null

### ISSUE THREAD

**Issue by RadekVoltr** [Azure/azure-sdk-for-net#33540]
### Library name and version

Azure.ResourceManager.AppService 1.0.0

### Describe the bug

I am unable to read application settings from WebApp. 

I can read res group, web app, and even settings (and have a list of default documents, etc...), but AppSettings are null.

Is there any workaround?

best regards
Radek

`                
var ResourceGroup = azure.GetResourceGroup("xxxx");                
var webapp = ResourceGroup.Value.GetWebSite("xxxx");
               
var settings = webapp.Value.GetWebSiteConfig().Get();
                
var x = settings.Value.Data.AppSettings;
`

### Expected behavior

AppSettings should contains list of keyvalue pairs

### Actual behavior

AppSettings is null

### Reproduction Steps

                var armClient = new ArmClient(new AzureCliCredential());

                var all_subs = armClient.GetSubscriptions();
                var azure = all_subs.Where(s =>
                {
                    Console.WriteLine(s.Data.Id.SubscriptionId);
                    return s.Data.Id.SubscriptionId == "xxxxxxx";
                }
                ).FirstOrDefault();

                var ResourceGroup = azure.GetResourceGroup("xxxx");
                var webapp = ResourceGroup.Value.GetWebSite("xxxx");

                var settings = webapp.Value.GetWebSiteConfig().Get();
                var x = settings.Value.Data.AppSettings;

### Environment

Visual Studio 2022, NET 6 Azure Function in local debugging

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by fengzhou-msft** [comment]
@RadekVoltr there is the [GetApplicationSettings](https://github.com/Azure/azure-sdk-for-net/blob/44fc1e23e9847b4799ceee19e22e6adca9923eb9/sdk/websites/Azure.ResourceManager.AppService/src/Generated/WebSiteResource.cs#L2133) method of the `WebSiteResource`. You may want to use that method instead of the `Get` method from the singleton `WebSiteConfigResource` (whose path is `/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Web/sites/{name}/config/web`).
