### ISSUE TITLE
Management Lib vs Client Lib, which one should I use?

### ISSUE THREAD

**Issue by johnsimons** [Azure/azure-sdk-for-net#33555]
### Library name and version

Not relevant

### Query/Question

I am sorry if this question has been asked before, but when does one use Client lib vs Management Lib.

I understand the Management Libs are easier to use and hence may be the go-to choice and only fallback to Client libs for advanced scenarios that cannot be achieved via Management. Am I on the right track?

**Comment by jsquire** [comment]
Hi @johnsimons.  Thank you for reaching out and we regret that you're experiencing difficulties.   The two categories of library have different purposes and there is often little, if any, overlap in functionality between them by design.

Our management libraries are intended to be used for managing Azure resources - for example, creating an Event Hub namespace or deleting a Storage account.   Our client libraries are intended for interacting with those resources - for example, sending events to an Event Hub or querying blobs in a Storage container.
