### ISSUE TITLE
Are there plans to implement Data Movement for file share?

### ISSUE THREAD

**Issue by johnsimons** [Azure/azure-sdk-for-net#33560]
### Library name and version

Azure.Storage.DataMovement  12.0.0-beta.1

### Query/Question

I am in the process of updating `Microsoft.Azure.Storage.DataMovement` to latest lib.
However, the preview packages for DataMovements only support blobs.

Are there plans to implement File Shares data movements?

**Comment by johnsimons** [comment]
Also, the package says it is "Active", but it does reference other deprecated packages, so it feels like is also deprecated right?
![image](https://user-images.githubusercontent.com/122651/213076677-18383f30-12f6-40e9-ab1f-7cbc382dd9d7.png)

**Comment by jsquire** [comment]
//cc: @amnguye, @schaabs

**Comment by amnguye** [comment]
Hi @johnsimons

There are plans to support File Shares for the Data Movement library. We're targeting a public preview release for the summer of this year.

**Comment by johnsimons** [comment]
Hi @amnguye,

Thanks for the answer. Are you referring to America summer (June - August)?
My concern is that, as I stated above, `Microsoft.Azure.Storage.DataMovement` [references packages](https://www.nuget.org/packages/Microsoft.Azure.Storage.DataMovement#dependencies-body-tab) that have been marked as deprecated, eg https://www.nuget.org/packages/Microsoft.Azure.Storage.File/ and according to https://azure.github.io/azure-sdk/releases/latest/all/dotnet.html it seems this package support finishes on the 31st of March 2023.
![image](https://user-images.githubusercontent.com/122651/213307480-9a41e1b2-bc82-40bc-9c1e-7f08e34733a2.png)

So assuming the development of the new supported File Shares for the Data Movement library finishes in June, we will still be running unsupported from March to June. Can you expand on this?

**Comment by amnguye** [comment]
Yes Summer as in June - August.

As defined by Deprecated Support we would address only critical bug fixes and security fixes. Because of the state of only GAed version of the Data Movement library depending on the deprecated package still, if there's any actual security or data integrity issues in the deprecated package, then we would go and fix it.

However we will not be adding any new feature support to the package, same for the Data Movement package. We haven't made any new releases to the v11 deprecated packages unless there was a security or data integrity issue (No new releases of the v11 version has been released since 4/15/2021).

I do agree that it's in an unfortunate state that the current DataMovement library is still depending on the deprecated package however, if there's any security or data integrity issue with the deprecated package we will make an update.

We apologize for any inconvenience this has caused.

We are working towards this public preview release. June - August is the soonest it can make it without dropping quality.

**Comment by johnsimons** [comment]
@amnguye thanks for the update. I'll close this issue.

Actually, before I go, I have another question, I have been timing the Data Movement library vs `azcopy` and azcopy seems to be way faster. Our usage case is to copy data server side. My question is, does DataMovement lib, when used to copy server side, does it still d/l data to the client at all?
Sorry for piggybacking another question on this one!

**Comment by amnguye** [comment]
@johnsimons To answer your question regarding the performance between azcopy and the Data Movement library, yes right now azcopy is outperforming the library however we're working to get close to azcopy's performance. However we can't guarantee the performance will be 100% at par.

And that's mainly due to the fact that azcopy is written in GoLang which doesn't use light-weight tasks (go routines) and allocates about 4KB (I don't remember off the top of my head about this) and then reuses that allocated memory as it picks up new tasks. While in C# and .NET tasks are light weight and does not do that and allocates what it needs. However we're looking into other ways we can match performance.

As for your question regarding downloading data to the client, that depends on what type of service copy (copy server) is happening. If you're using the download then upload method, then yes it would do this, but if it's using the service copy, it does not do this.
