### ISSUE TITLE
[Question] Performance question related to GetBlobs and DownloadContentAsync

### ISSUE THREAD

**Issue by GitNewbieHub** [Azure/azure-sdk-for-net#33578]
### Library name and version

Azure.Storage.Blobs 12.13.0

### Query/Question

Hello,

I'm new to Azure and has a few questions about accessing blob storage files

GetBlobs takes like 9 seconds to list 26500 files

foreach (BlobItem blobItem in container.GetBlobs())
 {
  count++;
}

If I try to download the file to string, it takes about 55 seconds to process 500 files. The files are JSON and the size is around 400-500B for each file.

BlobDownloadResult download = await blobClient.DownloadContentAsync();
string downloadedData = download.Content.ToString();

Are these expected speed? It takes like 9-10 mins to process 5000 files. Am I do something wrong?

**Comment by navba-MSFT** [comment]
@GitNewbieHub Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment]
@GitNewbieHub How are you checking the latency ? Could you please check the latency metrics from the Azure Portal Storage blade (as shown below) to check if the issue is from the E2E / Server latency ? and let us know the update.

![image](https://user-images.githubusercontent.com/57353862/213408418-f1866fb7-15a6-48c8-ab42-00a71e31313d.png)

Awaiting your reply.

**Comment by GitNewbieHub** [comment]
> @GitNewbieHub How are you checking the latency ? Could you please check the latency metrics from the Azure Portal Storage blade (as shown below) to check if the issue is from the E2E / Server latency ? and let us know the update.
> 
> ![image](https://user-images.githubusercontent.com/57353862/213408418-f1866fb7-15a6-48c8-ab42-00a71e31313d.png)
> 
> Awaiting your reply.

Here is the screenshot
![image](https://user-images.githubusercontent.com/123018009/213482076-86ed91fc-c00f-4f0e-a4a7-f4c8efefa3e0.png)

My time is from postman request. For example, I just ran it and processed 1000 files.

Status: 200OK
Time: 48.12 s
Size:  587.67 KB

Most time spent on following line
 
BlobDownloadResult download = await blobClient.DownloadContentAsync();

**Comment by navba-MSFT** [comment]
@GitNewbieHub Thanks for sharing the details. Our SLAs are for the availability and not for latency.

@amnguye Do we have any baseline for the expected response time for blobClient.DownloadContentAsync( ) ?

**Comment by amnguye** [comment]
Please see
https://learn.microsoft.com/en-us/azure/storage/common/scalability-targets-standard-account
https://learn.microsoft.com/en-us/azure/storage/blobs/storage-performance-checklist

There's no yes or no answer to that question because that would require the knowledge of the client's environment at the time of attempting these operations (network, amount of parallelism, blob size, other processes accessing the storage account at the time).

**Comment by navba-MSFT** [comment]
@GitNewbieHub I hope you had a chance to look at the above comment. There is no direct answer to this question. for all the criteria's mentioned above please refer the [performance checklist article](https://learn.microsoft.com/en-us/azure/storage/blobs/storage-performance-checklist) for the best practices recommendations.

**Comment by GitNewbieHub** [comment]
> @GitNewbieHub I hope you had a chance to look at the above comment. There is no direct answer to this question. for all the criteria's mentioned above please refer the [performance checklist article](https://learn.microsoft.com/en-us/azure/storage/blobs/storage-performance-checklist) for the best practices recommendations.

Thanks, I will take a look. I guess this post can be closed.

**Comment by navba-MSFT** [comment]
@GitNewbieHub We will now proceed with closure of this GitHub issue. If you need any further assistance on this issue in future, please feel free to reopen this thread. We would be happy to help.
