### ISSUE TITLE
[FEATURE REQ] Add support for sandboxPipelineRuns/*runId*/sandboxActivityRuns

### ISSUE THREAD

**Issue by shiftychris** [Azure/azure-sdk-for-net#33631]
### Library name

Microsoft.Azure.Management.DataFactory

### Please describe the feature.

Add support to call Sandbox Pipeline Run information and SandboxActivitiyRuns.

Odds are if you are integrating with the API then you will need to test using Debug runs. These methods are not available in the SDK but are available via the Management Rest API and Azure ADF. 
 
base url:

[https://management.azure.com/subscriptions/{subscription_id}/resourcegroups/{resource_group_name}/providers/Microsoft.DataFactory/](https://management.azure.com/subscriptions/%7Bsubscription_id%7D/resourcegroups/%7Bresource_group_name%7D/providers/Microsoft.DataFactory/)

... factories/{factory_name}/querydebugpipelineruns?api-version=2018-06-01
(with no other parameters)

....factories/{factory_name}/sandboxPipelineRuns/{run_id}/sandboxActivityRuns?

with parameters

startTime
endTime
api-version

If this functionality does happen to exist (or its undocumented but is a method then please direct).

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by Yao725** [comment]
Hi @shiftychris, I didn't find the corresponding API in the swagger spec, could you please share some documents such as the Management Rest API doc?

**Comment by shiftychris** [comment]
Hi @Yao725 - Agreed, I cant see it in the documentation but this call is made in ADF when viewing debug pipeline runs:

https://management.azure.com/subscriptions/[subscription]/resourcegroups/[resource-group]/providers/Microsoft.DataFactory/factories/[factory-name]/querydebugpipelineruns?api-version=2018-06-01

**Comment by Yao725** [comment]
This should be a service-related issue, marked it as `Service Attention`.

**Comment by ArthurMa1978** [comment]
This issue is related to the service side and not the SDK side, so we are not able to help you with it. Therefore, we are closing this issue for now. If you need more assistance, please [open an Azure support request](https://docs.microsoft.com/azure/azure-portal/supportability/how-to-create-azure-support-request). We apologize for any inconvenience this may cause you.

We value your feedback and we want to make sure that your problem is solved. If you think that we have misunderstood your issue or closed it incorrectly, please feel free to comment on this thread and reopen the issue. We will be happy to assist you further. Thank you for your understanding and cooperation.
