### ISSUE TITLE
[BUG] Authentication logs errors until succeeds in Azure Function

### ISSUE THREAD

**Issue by elias-rod** [Azure/azure-sdk-for-net#33642]
### Library name and version

Microsoft.Extensions.Azure 1.6.0

### Describe the bug

Using the dependency injection as described in the official [documentation](https://learn.microsoft.com/en-us/dotnet/azure/sdk/dependency-injection), an Azure Function running in isolated mode works but the authentication logs many errors before continue with normal execution. These are the [logs](https://github.com/elias-rod/poc-isolated-function/blob/debugging-di-errors/error.txt), it starts attempting to authenticate after line 26, then it logs errors until line 243 when it successfully authenticates with Visual Studio and finally continues the execution in line 261. This is a [sample project](https://github.com/elias-rod/poc-isolated-function/tree/debugging-di-errors) (branch debugging-di-errors) that can be used to validate the incorrect behavior. This does not happen when creating the client normally using DefaultAzureCredential:
`var client = new EventGridPublisherClient(new Uri("https://evgt-pocif-dev-bs2-1.brazilsouth-1.eventgrid.azure.net/api/events"), new DefaultAzureCredential());`

### Expected behavior

No error logging

### Actual behavior

Error logging

### Reproduction Steps

Create an Azure Event Grid resource and execute the following [project](https://github.com/elias-rod/poc-isolated-function/tree/debugging-di-errors) in the branch debugging-di-errors

### Environment

WindowsX64
VisualStudio 2022 17.4.4

dotnet --info
.NET SDK:
 Version:   7.0.102
 Commit:    4bbdd14480

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19045
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.102\

Host:
  Version:      7.0.2
  Architecture: x64
  Commit:       d037e070eb

.NET SDKs installed:
  7.0.102 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.13 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download

**Comment by jsquire** [comment]
Hi @elias-rod.   The logs that you're seeing appear to indicate that your host environment does not have a managed identity endpoint available.  Unless you are expecting managed identity to be available, this is a normal and expected part of the flow.  Because it's a chained credential, `DefaultAzureCredential` will attempt to authenticate using multiple sources, falling back until one is successful or all have failed.   More information can be found in [DefaultAzureCredential](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/identity/Azure.Identity/README.md#defaultazurecredential).   

The documentation uses `DefaultAzureCredential` because it is likely to work in most environments and is often preferred because code changes are not required when moving from local development to hosted production environments.  Any `TokenCredential` from the [Azure.Identity](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/identity/Azure.Identity/README.md) library will work as a replacement for `DefaultAzureCredentail` in that example, should you wish to use a specific method.  It is also possible to exclude certain authentication types from the `DefaultAzureCredential` chain, by configuring and passing an instance of [DefaultAzureCredentialOptions](https://learn.microsoft.com/dotnet/api/azure.identity.defaultazurecredentialoptions?view=azure-dotnet) to the constructor.

I'm going to mark this as addressed, but please feel free to unresolve if you'd like to continue the discussion.

**Comment by elias-rod** [comment]
/unresolve I think it is a bug, because if in Program.cs the first code snippet is used, the error occurs. However, if the second is used, the error do not occur:
**First**
```
serviceCollection.AddAzureClients(azureClientFactoryBuilder =>
{
    azureClientFactoryBuilder.AddEventGridPublisherClient(new Uri("https://x.eventgrid.azure.net/api/events"));
    azureClientFactoryBuilder.UseCredential(new DefaultAzureCredential());
});
```
**Second**
```serviceCollection.AddSingleton(new EventGridPublisherClient(new Uri("https://x.eventgrid.azure.net/api/events"), new DefaultAzureCredential()));```

**Comment by christothes** [comment]
Hi @elias-rod 
The logging you are seeing will be displayed anytime an EventSource listener is attached - the Azure.Identity library is agnostic to this fact and sends events to the EventSource regardless of the configuration. If a listener was not attached, the log output wouldn't be displayed. Is it possible that there is anything else about the configuration that is enabling logging in general for the first scenario? Do you have an example output from the function for the second scenario?

**Comment by elias-rod** [comment]
Sure, here are the [logs](https://github.com/elias-rod/poc-isolated-function/blob/debugging-di-errors/no-error-with-normal-di.txt) showing that using the Azure.Identity library with normal DI works fine.

**Comment by JoshLove-msft** [comment]
When you use the AddAzureClients method, this enables log forwarding from the Azure.Identity EventSource events to ILogger. This explains why you see the ldentity logs when using AddAzureClients, but not when you create the client directly yourself.
