### ISSUE TITLE
How to enrich Azure Service Bus messages with OpenTelemetry trace data?

### ISSUE THREAD

**Issue by object** [Azure/azure-sdk-for-net#33652]
### Library name and version

Azure.Monitor.OpenTelemetry.Exporter 1.0.0-beta.6

### Query/Question

I am trying to use Azure.Monitor.OpenTelemetry.Exporter to enrich Azure ServiceBus message with OpenTelemetry traces. I assumed that similar to HttpClient and AspNet instrumentation, it silently adds OpenTelemetry trace info to service bus messages and if the message consumer enables OpenTelemetry and installs and configures Azure.Monitor.OpenTelemetry.Exporter, then OpenTelemetry propagation context will be automatically created from the message bus service headers. But I don't see anything like this to be done. I also found an example where correlationId is manually set and parsed by publisher and consumer (https://devkimchi.com/2021/05/19/tracing-end-to-end-data-from-power-apps-to-azure-cosmos-db/).

So is there a way to configure Azure ServiceBus message publisher and consumer to a publisher will enrich messages with OpenTelemetry trace metadata and consumer will parse them, or this needs to be implemented using custom code?

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by JoshLove-msft** [comment]
Hi @object,
In order to integrate with open telemetry libraries, you will need to enable the experimental flag in your application as described in this [blog post](https://devblogs.microsoft.com/azure-sdk/introducing-experimental-opentelemetry-support-in-the-azure-sdk-for-net/#get-started).

The Service Bus client library enriches `ServiceBusMessage` by adding a `Diagnostic-Id` property into the ServiceBusMessage.ApplicationProperties dictionary if instrumentation is enabled. The library looks for this Diagnostic-Id when receiving/processing messages to establish the correlation.

Starting from the next version of Service Bus, 7.13.0, the `tracestate` and `traceparent` keys will also be added into the dictionary. `traceparent` will have the same value as `Diagnostic-Id. `tracestate` will correspond to the [Activity.TraceStateString](https://learn.microsoft.com/en-us/dotnet/api/system.diagnostics.activity.tracestatestring?view=net-7.0).

**Comment by object** [comment]
Thank you for the explanation. Looking forward to the new package release.
