### ISSUE TITLE
ConditionNotMet vs TargetConditionNotMet when updating Azure Blobs using etags

### ISSUE THREAD

**Issue by gaurav137** [Azure/azure-sdk-for-net#33668]
### Library name and version

WindowsAzure.Storage (old but should not matter)

### Query/Question

When updating an Azure Blob using an eTag we handle error due to eTag mismatch by handling the 'ConditionNotMet' error code. But we saw an instance of 'TargetConditionNotMet' in production being returned that we cannot repro locally for the same code path. Can someone please explain when to expect one error code over the other when using eTags? Should we rather rely on http status code of 412 and not specific storage error codes such as ConditionNotMet/TargetConditionNotMet/SourceConditionNotMet?

Failure stack:
Request Id: 141b74d1-901e-0054-51e4-2a9595000000. StartTime: 1/18/2023 2:30:25 AM. EndTime: 1/18/2023 2:30:25 AM. ExtendedErrorMessage: HResult: -[2146233088](tel:+12146233088)

ExtendedError: TargetConditionNotMet-The target condition specified using HTTP conditional header(s) is not met.

RequestId:141b74d1-901e-0054-51e4-2a9595000000

Time:2023-01-18T02:30:25.6608365Z

. FilterString: 'None'. SelectQuery: 'None'. :: AzureStorageHelpers.AzureStorageException ---> [Microsoft.WindowsAzure.Storage](http://microsoft.windowsazure.storage/).StorageException: The remote server returned an error: (412) The target condition specified using HTTP conditional header(s) is not met.. ---> [System.Net](http://system.net/).WebException: The remote server returned an error: (412) The target condition specified using HTTP conditional header(s) is not met..
```csharp
   at [System.Net](http://system.net/).HttpWebRequest.GetResponse()

   at [Microsoft.WindowsAzure.Storage](http://microsoft.windowsazure.storage/).Core.Executor.Executor.ExecuteSync[T](RESTCommand`1 cmd, IRetryPolicy policy, OperationContext operationContext)

   --- End of inner exception stack trace ---

   at [Microsoft.WindowsAzure.Storage](http://microsoft.windowsazure.storage/).Core.Executor.Executor.ExecuteSync[T](RESTCommand`1 cmd, IRetryPolicy policy, OperationContext operationContext)

   at [Microsoft.WindowsAzure.Storage](http://microsoft.windowsazure.storage/).Blob.CloudBlockBlob.UploadFromStreamHelper(Stream source, Nullable`1 length, AccessCondition accessCondition, BlobRequestOptions options, OperationContext operationContext)

   at [Microsoft.WindowsAzure.Storage](http://microsoft.windowsazure.storage/).Blob.CloudBlockBlob.UploadFromStream(Stream source, AccessCondition accessCondition, BlobRequestOptions options, OperationContext operationContext)

   at [Microsoft.WindowsAzure.Storage](http://microsoft.windowsazure.storage/).Blob.CloudBlockBlob.UploadFromByteArray(Byte[] buffer, Int32 index, Int32 count, AccessCondition accessCondition, BlobRequestOptions options, OperationContext operationContext)

   at [Microsoft.WindowsAzure.Storage](http://microsoft.windowsazure.storage/).Blob.CloudBlockBlob.UploadText(String content, Encoding encoding, AccessCondition accessCondition, BlobRequestOptions options, OperationContext operationContext)
```

**Comment by navba-MSFT** [comment]
@gaurav137 Thanks for reaching out to us and reporting this issue. When updating a blob in Azure Storage, an ETag (entity tag) value is used to ensure that the update is only applied if the blob has not been modified since it was last read. If the ETag value provided in the update request does not match the current ETag value of the blob, the update will fail with a "ConditionNotMet" error.

The "TargetConditionNotMet" error is similar to "ConditionNotMet", but it indicates that the update failed because the target ETag value provided in the request did not match the current ETag value of the blob. This error may occur if the blob has been modified by another process since it was last read.

In short, "ConditionNotMet" occurs when the Etag that you are trying to update with is not matching the current Etag of the blob and "TargetConditionNotMet" occurs when the target Etag you are trying to update to doesn't match the current Etag of the blob.

"`SourceConditionNotMet`" error is related to the "source" blob when doing a copy operation or rehydrate operation from archive blob. This error occurs when the source ETag value provided in the request does not match the current ETag value of the source blob. It means the source blob was modified after you last read it and before you tried to copy or rehydrate it.

For example, when using the Azure Storage SDK to copy a blob from one container to another, you can specify a source ETag value to ensure that the copy operation only proceeds if the source blob has not been modified since it was last read. If the source ETag value provided in the request does not match the current ETag value of the source blob, the copy operation will fail with a "SourceConditionNotMet" error.

In summary, "`SourceConditionNotMet`" error occurs when you are trying to copy or rehydrate a blob from archive to hot or cool and the source ETag you are providing does not match the current ETag of the source blob.

**Comment by gaurav137** [comment]
Thanks for the response. I'm not able to grasp the difference between ConditionNotMet and TargetConditionNotMet. Using V12 Azure.Storage.Blobs SDK if the code does:
```csharp
                BlobContentInfo contentInfo = await blobClient.UploadAsync(
                    BinaryData.FromString(payload),
                    new BlobUploadOptions
                    {
                        Conditions = new BlobRequestConditions
                        {
                            IfMatch = eTag
                        }
                    });

```
Then after the above call succeeds if I repeat the above call with the same eTag value as that used in the first call then it returns 'ConditionNotMet'. What did you mean by _"...the target ETag value provided in the request did not match the current ETag value of the blob. This error may occur if the blob has been modified by another process since it was last read."_ for TargetConditionNotMet as isn't that the same situation for which ConditionNotMet gets returned if I invoke UploadAsync() twice per above? It would be great if code snippet/repro for 'TargetConditionNotMet' could be shared.

**Comment by navba-MSFT** [comment]
@gaurav137 Thanks for getting back. I haven't tested the above sample. I am adding the Service team to check if they can assist on this further and see if they have the sample code snippet. 

@xgithubtriage Could you please look into this and provide some pointers ?  Thanks in advance.

**Comment by gaurav137** [comment]
Updated original question with failure stack

**Comment by navba-MSFT** [comment]
@gaurav137 Thanks for sharing the exception details. While we are waiting for the reply from the Service team, I looked at the backend logs for the failing request id. 

>**RequestId:141b74d1-901e-0054-51e4-2a9595000000
Time:2023-01-18T02:30:25.6608365Z**

This request id is a week old, due to this, the backend logs for the request ID is now rolled over. Do you have the most recent occurrence of this issue (not older than 2 days) ?

**Comment by gaurav137** [comment]
Here are a few more recent ones. I removed the stack traces as its the same as in the original question.

2023-01-29 20:17:46.5707558
Request Id: 1ce06077-001e-0046-5b1e-34ee45000000. StartTime: 1/29/2023 8:17:46 PM. EndTime: 1/29/2023 8:17:46 PM. ExtendedErrorMessage: HResult: -2146233088
ExtendedError: TargetConditionNotMet-The target condition specified using HTTP conditional header(s) is not met.
RequestId:1ce06077-001e-0046-5b1e-34ee45000000
Time:2023-01-29T20:17:46.5710815Z

2023-01-30 02:57:28.0941602
Request Id: d84c51f1-301e-0010-0a56-341faa000000. StartTime: 1/30/2023 2:57:28 AM. EndTime: 1/30/2023 2:57:28 AM. ExtendedErrorMessage: HResult: -2146233088
ExtendedError: TargetConditionNotMet-The target condition specified using HTTP conditional header(s) is not met.
RequestId:d84c51f1-301e-0010-0a56-341faa000000
Time:2023-01-30T02:57:28.0856182Z

2023-01-30 06:54:12.1830645
Request Id: ed09b4f5-001e-0034-6b77-34e90a000000. StartTime: 1/30/2023 6:54:12 AM. EndTime: 1/30/2023 6:54:12 AM. ExtendedErrorMessage: HResult: -2146233088
ExtendedError: TargetConditionNotMet-The target condition specified using HTTP conditional header(s) is not met.
RequestId:ed09b4f5-001e-0034-6b77-34e90a000000
Time:2023-01-30T06:54:12.1800686Z

2023-01-30 06:54:12.1995084
Request Id: ed09b510-001e-0034-7d77-34e90a000000. StartTime: 1/30/2023 6:54:12 AM. EndTime: 1/30/2023 6:54:12 AM. ExtendedErrorMessage: HResult: -2146233088
ExtendedError: TargetConditionNotMet-The target condition specified using HTTP conditional header(s) is not met.
RequestId:ed09b510-001e-0034-7d77-34e90a000000
Time:2023-01-30T06:54:12.1970585Z

**Comment by amnguye** [comment]
If you're looking to create a support ticket to look up the backend storage service logs you have to create an Azure Support Ticket.

https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

I think you will find more answers there because the SDK does not control what [Blob Error Codes](https://learn.microsoft.com/en-us/rest/api/storageservices/blob-service-error-codes) come back from the service.

**Comment by navba-MSFT** [comment]
@gaurav137 I agree with @amnguye's above comment. I would suggest you to open a support ticket if you need an indepth log analysis.

But on an extra-mile, I did spend sometime looking at the backend logs. I could see the conditional header that was used here is "`IfMatch`". The Request URL for which it failed is `https://ccy*********zpiz.blob.core.windows.net:443/706f6*********e65/5d7ff7e6-********f12f477`. 

The failure was due to The `blob last modification time does not match.` resulting in 412 error.

I could see 2 requests (concurrent requests) to the same above blob happening at the same time due to which it failed with the above error. 

Refer [this ](https://learn.microsoft.com/en-us/azure/storage/blobs/concurrency-manage?tabs=dotnet#optimistic-concurrency) Optimistic Concurrency section and the provided sample code. Hope this helps

**Comment by gaurav137** [comment]
Thanks @navba-MSFT @amnguye for your responses. Our code handled ConditionNotMet for the conflicting update situation and we had not seen TargetConditionNotMet before. But per @navba-MSFT investigation it looks like a conflicting update situation can also return TargetConditionNotMet. 

One remaining concern we had was that as we had not seen TargetConditionNotMet before and only started seeing this recently in canary regions, so could there be an off chance that the behavior has changed, and this change is rolling out further into production? On our end I'll ask our team to file a support ticket/incident but wanted to bring this concern up here also.

**Comment by amnguye** [comment]
@gaurav137 Thanks for trying to bring it to our attention, however there's very little we can do about this concern, as the SDK does not control what error messages the storage service can come back with, and if they decide to change the error message to be more specific, then I'm also not sure what we can do about that.

I would file a support ticket. Closing this issue as there's nothing further for the SDK team to do here.
