### ISSUE TITLE
The BinaryData format property can't handle byte[] data properly. 

### ISSUE THREAD

**Issue by ArthurMa1978** [Azure/azure-sdk-for-net#33804]
![image](https://user-images.githubusercontent.com/20514459/215972477-c1de148b-ada7-4442-a20d-c56c446785af.png)

**Comment by Yao725** [comment]
After investigation, here is what I found from this issue:

- Generally speaking, if we want to construct the BinaryData in management plane SDK from byte array, we should ensure that the byte array is a valid json value, this needs special attention especially when the byte array is representing a json string. Here the action should be similar to what we did with the method [BinaryData.FromString("\\"foo\\"")](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/resources/Azure.ResourceManager.Resources/src/Generated/Models/ArmDeploymentProperties.cs#L38). Take a look at below sample code for details.

```csharp
string sample = "this is the sample code.";

byte[] input = UTF8Encoding.UTF8.GetBytes($"\"{sample}\"");
// byte[] input = UTF8Encoding.UTF8.GetBytes(sample);  wrong way to get the byte array when faced with a string

BinaryData data = BinaryData.FromBytes(input);
```

- Back to this issue, another thing that we need to take care of is the encode and decode. BinaryData is actually based on the [UTF-8](https://github.com/terrajobst/designs/blob/main/accepted/2020/binary-data/binary-data.md#goals), but the value of X509Thumbprint is based on [Base64](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/keyvault/Azure.Security.KeyVault.Certificates/src/CertificateProperties.cs#L145). That are totally two different things, which means even if the value of X509Thumbprint is a valid json value, we still cannot get the correct result if we directly use these bytes to construct the BinaryData.

Based on above findings, we need to update the code so that the serialization could work as expected:
```csharp
Thumbprint = BinaryData.FromString($"\"{Base64Url.Encode(certificate.Properties.X509Thumbprint)}\"");
```


Finally, I think we really need a full documentation for BinaryData and this documentation could be part of the management plane SDK FAQ, and this documentation should contain below contents at least:

- what the BinaryData is
- Why we introduced it in our SDK
- How to transform between the value (such as string, JosnObject, etc.) and BinaryData
- Additional notes on using BinaryData

**Comment by live1206** [comment]
There is nothing wrong with `BinaryData` here, the below test will succeed with `BinaryData` and [`Base64Url`](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/core/Azure.Core/src/Shared/Base64Url.cs) encoding and decoding.
```csharp
            var str = "hello world";
            var encodedStr = Base64Url.EncodeString(str);
            var decodedBytes = Base64Url.Decode(encodedStr);
            var result = BinaryData.FromBytes(decodedBytes).ToString();
            Assert.AreNotEqual(str, result);
```

The error was thrown from JSON serialization, because the original content of `X509Thumprint` was a UTF-16 format string and we are using [JsonElement ](https://github.com/dotnet/runtime/blob/1e241c0044042409b8567c5ab9a72b7525ad128a/src/libraries/System.Text.Json/src/System/Text/Json/Document/JsonElement.Parse.cs#L47) in the implementation, which is expecting UTF-8 format.

We can convert the original string to a hex string, which is what the Azure Portal display text does, then it can be serialized by `JsonElement`. Then, the question is, does the server side always expect a hex string for [Thumprint](https://github.com/Azure/azure-sdk-for-net/blob/93da099ad71601dc14381de73a9e4855e4f18905/sdk/websites/Azure.ResourceManager.AppService/src/Generated/HostNameBindingData.cs#L99)?

**Comment by live1206** [comment]
In mgmt, we will add a new property named `X509ThumbprintAsHexString`, which returns `Convert.ToHexString(this.Thumbprint)`, and make `Thumbprint` to `EB.Never`

**Comment by heaths** [comment]
> In mgmt, we will add a new property named `X509ThumbprintAsHexString`, which returns `Convert.ToHexString(this.Thumbprint)`, and make `Thumbprint` to `EB.Never`

@live1206 that is not congruent with the latest conversation between @KrzysztofCwalina, @m-nash, and myself. Has the plan changed? As Krzysztof noted, he doesn't agree we should add a simple property getter that converts the `byte[]` to a hex string, so what value is there in accepting on in the management plane SDK when you could marshal the `byte[]` array instead?

**Comment by heaths** [comment]
Key Vault SDK long ago shipped a property of type `byte[]`. I could add a property e.g.,

```C#
public string X509ThumbprintAsHexString => Convert.ToHexString(X509Thumbprint);
```

But you said,

> I am totally on board with exposing byte[] (or binarydata) property in the management plane (as proposed below), but I am not sure we need a new property in the dataplane that simply converts bytes to hex string. This is a simple conversion that users can do themselves.

Seems we'd want congruent properties to avoid confusion.

**Comment by m-nash** [comment]
Agreed if we think hex string is the correct common format then adding the extra property in keyvault and switching from BinaryData to string in mgmt would solve the iterop issue here.

**Comment by heaths** [comment]
Ping @KrzysztofCwalina for feedback on the last couple comments. /cc @tg-msft

**Comment by KrzysztofCwalina** [comment]
I am fine with using hex string as the main interchange format (for thumbprints).

**Comment by heaths** [comment]
> I am fine with using hex string as the main interchange format (for thumbprints).

@KrzysztofCwalina the specific question was whether the Key Vault SDK should add a property that just returns the hex string or not. Previously you were opposed.

**Comment by KrzysztofCwalina** [comment]
> @KrzysztofCwalina the specific question was whether the Key Vault SDK should add a property that just returns the hex string or not. Previously you were opposed.

I was opposed to having both representations being "first class". I was (and am) arguing for picking one representation and then evolving the APIs in that direction. I don't think we should have both representations exposed prominently and asking users to pick.

**Comment by heaths** [comment]
The Key Vault SDK already returns a `byte[]` array, so exposing anything else means adding a property.

**Comment by heaths** [comment]
Discussing offline, we've decided to add a `string X509ThumbprintString` property to both Key Vault and managed SDKs. KV SDKs will also hide the `X509Thumbprint` but not remove it.

**Comment by live1206** [comment]
The new version of corresponding SDKs will be released soon.
