### ISSUE TITLE
[BUG] BlobDownloadDetails class is missing the CreatedOn property

### ISSUE THREAD

**Issue by krispenner** [Azure/azure-sdk-for-net#33899]
### Library name and version

Azure.Storage.Blobs 12.14.1.0

### Describe the bug

The `BlobDownloadDetails` class is missing the `CreatedOn` property. All other similar blob "properties" and "info" classes include this property.

https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/storage/Azure.Storage.Blobs/src/Models/BlobDownloadDetails.cs`

### Expected behavior

The `BlobDownloadDetails` class includes a `DateTimeOffset CreatedOn` property.

### Actual behavior

The `BlobDownloadDetails` class does not include a `DateTimeOffset CreatedOn` property.

### Reproduction Steps

Maybe this could be considered a feature request, but I see it as a bug since it's important information that seems to have been missed rather than intentionally excluded.

**Comment by navba-MSFT** [comment]
@krispenner Apologies for the late reply. Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment]
@krispenner Did you check the [CreatedOn ](https://learn.microsoft.com/en-us/dotnet/api/azure.storage.blobs.models.blobitemproperties.createdon?view=azure-dotnet#azure-storage-blobs-models-blobitemproperties-createdon)property of the BlobItemProperties Class ? Does that help ? Awaiting your reply.

**Comment by krispenner** [comment]
But that is not on the [BlobDownloadDetails](https://learn.microsoft.com/en-us/dotnet/api/azure.storage.blobs.models.blobdownloaddetails?view=azure-dotnet#properties) class.

**Comment by navba-MSFT** [comment]
@krispenner Thanks for your reply. I am checking this and I will update you.

**Comment by amnguye** [comment]
Thanks for bringing this up to our attention. You're correct looks like the `x-ms-creation-time` is being returned by the service but isn't being parsed by the SDK. 

https://learn.microsoft.com/en-us/rest/api/storageservices/get-blob#response-headers

Example Download Request:
```
GET https://<bloburl> HTTP/1.1
Host: <host>
x-ms-version: 2021-12-02
Accept: application/xml
x-ms-client-request-id: 99e1ccff-260f-4c02-96bd-f8cc1aa6f82b
x-ms-return-client-request-id: true
User-Agent: azsdk-net-Storage.Blobs/12.15.0-alpha.20230202.1 (.NET 6.0.13; Microsoft Windows 10.0.22621)
x-ms-date: Fri, 10 Feb 2023 17:57:09 GMT
Authorization: <auth>
traceparent: 00-c0baec73d0ab21941a53013cbab6c3e8-fb1408712b5a7523-00
```
Example Response:
```
HTTP/1.1 200 OK
Content-Length: 1024
Content-Type: application/octet-stream
Content-MD5: +fLiy1+WFoFNxR6OxmJk2g==
Last-Modified: Fri, 10 Feb 2023 17:57:10 GMT
Accept-Ranges: bytes
ETag: "0x8DB0B903BA908A4"
Server: Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0
x-ms-request-id: 84be3d5a-901e-002d-7779-3dc692000000
x-ms-client-request-id: 99e1ccff-260f-4c02-96bd-f8cc1aa6f82b
x-ms-version: 2021-12-02
x-ms-version-id: 2023-02-10T17:57:10.7186852Z
x-ms-is-current-version: true
x-ms-creation-time: Fri, 10 Feb 2023 17:57:10 GMT
x-ms-lease-status: unlocked
x-ms-lease-state: available
x-ms-blob-type: BlockBlob
x-ms-server-encrypted: true
Date: Fri, 10 Feb 2023 17:57:10 GMT
<body>
```

We will look to updating the generated REST code to catch this header because right now the `BlobDownloadHeaders` is generated not to parse for the `x-ms-creation-time`

https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/storage/Azure.Storage.Blobs/src/Generated/BlobDownloadHeaders.cs

cc: @seanmcc-msft

No changes need to occur in File.Shares because it's already accounted for in the `ShareFileDownloadDetails.FileSmbProperties`.

The same bug kinda exists for FIles.DataLake in the `FileDownloadDetails` but once the fix is made to blobs we just need to fix the conversion here to make sure the CreatedOn value carries over.

https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/storage/Azure.Storage.Files.DataLake/src/DataLakeExtensions.cs#L81

**Comment by krispenner** [comment]
@amnguye thanks for confirming. I am currently parsing `x-ms-creation-time` myself from `GetRawResponse()` but having this done by the SDK will be much nicer. Thank you for addressing this.

It looks like `CreatedOn` is also missing from `BlobContentInfo` returned from `UploadAsync()`, it does contain `LastModified` already. Maybe you can add this there at the same time.

I would also like to see a `UploadResult = Created|Replaced` or `bool WasCreated` similar property added to the `BlobContentInfo` class to be set based on `GetRawResponse().Status == 201` as it's very useful to know if the uploaded blob replaced an existing one or created a new one. I can add this as a new feature request if needed.

**Comment by amnguye** [comment]
Actually `BlobContentInfo` already has a `LastModified` public API already. There's no need to add it, it's named that way because of RFC standards.

**Comment by krispenner** [comment]
Oh interesting, I’m surprised uploading a new blob wouldn’t return the `x-ms-creation-time` header. Thanks for checking into it.

**Comment by amnguye** [comment]
This bug has been fixed in Azure.Storage.Blobs 12.15.0
