### ISSUE TITLE
adding new node pool to AKS cluster caused default azure credentials to failed

### ISSUE THREAD

**Issue by eranbar** [Azure/azure-sdk-for-net#33909]
### Library name and version

aad pod identity 

### Query/Question

my pod\managed identity worked perfect until added new node pool.
when my hosted service tried to authenticate against the key vault I'm getting below exception:

DefaultAzureCredentials failed to retrieve a token from  the included credentials .
EnvironmentCredentials authentication unavailable . environment variables are not fully configured.
ManagaedIdentityCredentials authentication unavailable. the requested identity has not been assigned to this resource.

when observing the cluster it seems like we dont have NMI on the node pool, I'm not sure I fully understand how it supposed to work but i guess this is part of the problem.

### Environment

AKS cluster
hosted service in .net 6.0

**Comment by jsquire** [comment]
Hi @eranbar.  Thank you for reaching out and we regret that you're experiencing difficulties.  You haven't mentioned which Azure SDK package you're seeking assistance with, but from context, it seems like you're looking to understand how authorization with `DefaultAzureCredential` works and why it is unable to authenticate in your environment.    

Assuming that's correct, I'd suggest starting with the [Troubleshooting Guide](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/identity/Azure.Identity/TROUBLESHOOTING.md#troubleshoot-defaultazurecredential-authentication-issues) which has a section for investigating `DefaultAzureCredential` failures and collecting the information that we would ask you to provide for investigation.

If I'm not correct, would you please help us  understand which Azure SDK package you're inquiring about so that we can get the right folks involved to assist?

**Comment by eranbar** [comment]
Hi,
Im referring to the managed identity and the aad pod identity.
We are trying to autheticate against azure key vault.
Just to emphasize, everything worked fine and we were able to use the managed identity and authenticate against the key vault.
Then we added new k8s node pool and seems like that from that point it was unable to authenticate and missing NMI on the new node pool.

Thanks for reaching out.


קבל ‏Outlook עבור Android‏<https://aka.ms/AAb9ysg>
________________________________

**Comment by jsquire** [comment]
Hi @eranbar.  Unfortunately, this repository is focused on the Azure SDK for .NET - we're unable to assist with other Azure issues.  Since what you're inquiring about appears to be related to the AKS platform and not one of the Azure SDK packages, your best path forward would be to [open an Azure support request](https://docs.microsoft.com/azure/azure-portal/supportability/how-to-create-azure-support-request).

I'm going to close this out;  if I've misunderstood what you're describing, please let us know in a comment and we'd be happy to assist as we're able.
