### ISSUE TITLE
[Question] How to refresh token when i use DefaultAzureCredential to get token to connect Azure MySQL

### ISSUE THREAD

**Issue by clgcn** [Azure/azure-sdk-for-net#33910]
### Library name and version

Azure.Identity 1.8

### Query/Question

Here is my code in program.cs file
```
    var credential = new DefaultAzureCredential();
    var token = credential.GetToken(new Azure.Core.TokenRequestContext(new[] { "https://ossrdbms-aad.database.windows.net" }));
    var connectionString = $"Server={builder.Configuration["DatabaseConfiguration:Server"]};" +
                           "Port=3306;" +
                           "SslMode=Required;" +
                           $"Database={builder.Configuration["DatabaseConfiguration:Database"]};" +
                           $"Uid={builder.Configuration["DatabaseConfiguration:UserId"]};" +
                           "Password=" + token.Token;
    var connection = new MySqlConnection(connectionString);
```
When i try to connect mysql by this way, (I'm a newer on c#, actually i also try DI, but it doesn't refresh token, so i try this simple way from offcial document, hope it can work), so how to refresh token when i use DefaultAzureCredential to get token to connect Azure MySQL, anyone can give some example to me ? 

### Environment

dotnet version is 6

**Comment by jsquire** [comment]
Hi @clgcn.   Thank you for reaching out and we regret that you're experiencing difficulties.  The Azure Identity credentials will refresh tokens when `GetToken` or `GetTokenAsync` is called, either for each invocation or when the cache entry is near expiration, depending on the credential used.

In this case, you're hardcoding the token into the connection string, which represents it as a static value.  Since nothing is calling `GetToken` or `GetTokenAsync` on the credential, the token value will never change.   To update the token, you would need to have an API that allows you to do so in the MySql package that you're using and call it with a new token value that your application requested via `GetToken` or `GetTokenAsync`.

Unfortunately, there is no further guidance that the Azure SDK team can provide.  We would suggest consulting the documentation for the MySql package that you're using and/or engaging their support process as your next step.

**Comment by clgcn** [comment]
Hi @jsquire , appreciate for your reply, actually i found some comment from DefaultAzureCredential class,
```
 /// <summary>
        /// Sequentially calls <see cref="TokenCredential.GetToken"/> on all the included credentials in the order
        /// <see cref="EnvironmentCredential"/>, <see cref="ManagedIdentityCredential"/>, <see cref="SharedTokenCacheCredential"/>, and
        /// <see cref="InteractiveBrowserCredential"/> returning the first successfully obtained <see cref="AccessToken"/>. Acquired tokens
        /// are cached by the credential instance. Token lifetime and refreshing is handled automatically. Where possible, reuse credential
        /// instances to optimize cache effectiveness.
        /// </summary>
        /// <remarks>
        /// Note that credentials requiring user interaction, such as the <see cref="InteractiveBrowserCredential"/>, are not included by default.
        /// </remarks>
        /// <param name="requestContext">The details of the authentication request.</param>
        /// <param name="cancellationToken">A <see cref="CancellationToken"/> controlling the request lifetime.</param>
        /// <returns>The first <see cref="AccessToken"/> returned by the specified sources. Any credential which raises a <see cref="CredentialUnavailableException"/> will be skipped.</returns>
```

can you help to explain what is mean refresh automatically ? and BTW, i use the code my previous comment, looks like it works fine, i didn't get token expired error anymore from last night

**Comment by jsquire** [comment]
That comment is basically the statement that I made above:  when `GetTokenAsync` or `GetToken` is called, the token will be refreshed.   In your scenario, you requested a token and then used it as a string value as part of your connection string.    At that point, the `Azure.Identity` credential is no longer being used so no calls to `GetToken` are made.    

If you want to refresh the token, something needs to be calling `GetToken` so that the logic runs to allow token renewal.   This is why the Azure SDK clients accept a `TokenCredential` during construction - they will implicitly refresh the token.   In your implementation, MySql is not using the credential - just the value of the token embedded into  its connection string.

To distill that to the important part:  the return value of `credential.GetToken(...).Token` is just a string, like any other .NET string.
