### ISSUE TITLE
The package version of Azure.AI.AnomalyDetector starts from 3.0.0 instead of 1.0.0

### ISSUE THREAD

**Issue by pshao25** [Azure/azure-sdk-for-net#33937]
In sdk\anomalydetector\Azure.AI.AnomalyDetector\CHANGELOG.md, the version starts from 3.0.0-preview.1 (2020-08-18)

**Comment by jsquire** [comment]
I'm not sure what this issue is supposed to be tracking nor what actions you believe should be taken.   The package versions on [NuGet](https://www.nuget.org/packages/Azure.AI.AnomalyDetector/3.0.0-preview.6#versions-body-tab) for the package mirrors the change log.

**Comment by m-nash** [comment]
@pshao25 technically we should have started at 2.0.0-beta.1 since the [track 1 library](https://www.nuget.org/packages/Microsoft.Azure.CognitiveServices.AnomalyDetector) is at 1.0.0 GA.  The general rule is start at track 1 version + 1.

Since we are already out at 3 lets not confuse customers but we should update the version in the csproj to release as 3.0.0-beta.7 for the next release.
