### ISSUE TITLE
Using Azure Reservation API to get networking quotas, but Provider Id = Microsoft.Network is not working

### ISSUE THREAD

**Issue by vikramdadwal** [Azure/azure-sdk-for-net#34093]
### Library name and version

Azure.ResourceManager.Reservations 1.1.0

### Query/Question

Using Azure Reservation API to get networking quotas, but Provider Id = Microsoft.Network is not working

using the following code:
`ReservationQuotaCollection reservationNetworkQuotas = subscriptionResource.GetAllReservationQuota("Microsoft.Network", new AzureLocation(region.Name));`

Getting following exception:

`{"error":{"code":"BadRequest","message":"The value provided for one of the Provider Ids was not in the correct format. Verify the value of Provider ID : Microsoft.Network'."}}`

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by ArcturusZhang** [comment]
Hi @vikramdadwal thanks for this issue!

Could you please share more of your sample code? This line
```
ReservationQuotaCollection reservationNetworkQuotas = subscriptionResource.GetAllReservationQuota("Microsoft.Network", new AzureLocation(region.Name));
```
is only constructing the `ReservationQuotaCollection` instance, no requests have been sent therefore the error is not produced by this line.
Could you share more of your sample so that I could try to reproduce?
