### ISSUE TITLE
Microsoft.Azure.Management.Fluent Nuget is dependent on every other fluent package

### ISSUE THREAD

**Issue by abhi1509** [Azure/azure-sdk-for-net#3429]
For .net 4.5.2 _Microsoft.Azure.Management.Fluent_ is dependent on all of these nuget.
**Is it really required?** i have no use of for eg: doc db, or sql in my project, why should I need to install those in my project. I do need to get Microsoft.Azure.Management.Fluent because IAzure comes from it.

```
Microsoft.Azure.Management.AppService.Fluent
Microsoft.Azure.Management.Batch.Fluent
Microsoft.Azure.Management.Cdn.Fluent
Microsoft.Azure.Management.Compute.Fluent
Microsoft.Azure.Management.ContainerRegistry.Fluent
Microsoft.Azure.Management.Dns.Fluent
Microsoft.Azure.Management.DocumentDB.Fluent
Microsoft.Azure.Management.Graph.RBAC.Fluent
Microsoft.Azure.Management.KeyVault.Fluent
Microsoft.Azure.Management.Network.Fluent
Microsoft.Azure.Management.Redis.Fluent
Microsoft.Azure.Management.ResourceManager.Fluent
Microsoft.Azure.Management.ServiceBus.Fluent
Microsoft.Azure.Management.Sql.Fluent
Microsoft.Azure.Management.Storage.Fluent
Microsoft.Azure.Management.TrafficManager.Fluent
```

**Comment by hovsepm** [comment]
@abhi1509 IAzure and the Microsoft.Azure.Management.Fluent  package is roll-up nuget package. You can still reference a single package e.g. Microsoft.Azure.Management.DocumentDB.Fluent and create only that manager instance. You can browse code of roll-up package here - https://github.com/Azure/azure-sdk-for-net/blob/Fluent/src/ResourceManagement/Azure.Fluent/Azure.cs 
By design.

**Comment by abhi1509** [comment]
Thanks. So if I am only using Microsoft.Azure.Management.ResourceManager.Fluent where do I get the IAzure instance as used in the sample all over? Or else what should I use?
