### ISSUE TITLE
[BUG] Azure.ResourceManager.SecurityInsights does not have feature parity with replaced (Deprecated) Microsoft.Azure.Management.SecurityInsights

### ISSUE THREAD

**Issue by bgelens** [Azure/azure-sdk-for-net#34312]
### Library name and version

Azure.ResourceManager.SecurityInsights 1.0.1

### Describe the bug

I'm trying to move over to Azure.ResourceManager.SecurityInsights as I was warned by nuget.org that Microsoft.Azure.Management.SecurityInsights was deprecated and I should now use the newer library

A few things that are making this task for me impossible right now is some things that are missing.

Techniques is not part of the AdditionalInfo model which is used by SecurityInsightsIncidentData. This used to be part of AdditionalData model in the earlier SDK.

The [EntitiesCollection](https://learn.microsoft.com/en-us/dotnet/api/azure.resourcemanager.securityinsights.entitycollection?view=azure-dotnet-preview&viewFallbackFrom=azure-dotnet) is not part of the new SDK, where in the old SDK this was available through the SecurityInsights service client.  See the Rest API [docs](https://learn.microsoft.com/en-us/rest/api/securityinsights/preview/entities/list?tabs=HTTP) for reference

I know both of these things are not part of any stable api but for my project this is a stopper for migrating to the new SDK.

### Expected behavior

Feature parity in new SDK with deprecated SDK to allow for migration

### Actual behavior

Not possible as of yet

### Reproduction Steps

As described above

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by ArcturusZhang** [comment]
Hi @bgelens thanks for this issue.
We explicitly removed the corresponding `Entities` APIs because it comes from a preview API. You could check the api-version of this operation in [the rest api doc](https://learn.microsoft.com/en-us/rest/api/securityinsights/preview/entities/list?tabs=HTTP).

We will release a new beta version based on the current 1.0.1 version to introduce the corresponding APIs back. Sorry for the inconvenience.

**Comment by bgelens** [comment]
Hey @ArcturusZhang! Thanks for the information. Any idea when this beta version will be up?

**Comment by bgelens** [comment]
Gentle ping @ArcturusZhang?

**Comment by ArcturusZhang** [comment]
Hi @bgelens sorry for the delay of response. I am working in this PR to introduce the new preview api in a new beta version: https://github.com/Azure/azure-sdk-for-net/pull/36520

Since it is not a stable api version, there will not be a stable SDK release for it until the service team brings those APIs into a new stable version.

But unfortunately when I am working on this, a bug in our code generator was discovered, and we need to fix that first before we could release the new version.
