### ISSUE TITLE
Incorrect error message [BUG]

### ISSUE THREAD

**Issue by json0007** [Azure/azure-sdk-for-net#34326]
### Library name and version

Azure.Identity latest

### Describe the bug

Why is this ticket closed?  It is still not fixed.  Also, 5 years?

https://github.com/Azure/azure-sdk-for-net/issues/4091

### Expected behavior

the issue to get fixed before closing the ticket

### Actual behavior

the issue was not fixed

### Reproduction Steps

See link above

### Environment

vs 2022 latest, .NET 4.6.2

**Comment by jsquire** [comment]
Hi @json0007.  The issue that you linked was closed for several reasons:

- AppAuthentication is a deprecated package no longer under active development
- The Visual Studio team acknowledged that the issue was not in the Azure SDK package and was being tracked internally
- The issue had not had engagement within 2 years.

Can you please help us understand if you are inquiring about issue with the AppAuthentication package or reporting an issue for Azure. Identity?   If the latter, would you please share the error message and associated stack trace for investigation?

**Comment by jsquire** [comment]
Because we do not have enough information to complete triage, I'm going to close this out.  If you'd like to move forward with this issue, please feel free to provide the requested information and ask for reopen.
