### ISSUE TITLE
[BUG] Cannot remove last SQL database from Failover Group using FailoverGroupPatch

### ISSUE THREAD

**Issue by rbe-planday** [Azure/azure-sdk-for-net#34577]
### Library name and version

Azure.ResourceManager.Sql 1.2.0

### Describe the bug

When updating a Failover Group to remove the one and only database of the Failover Group, the operation seems to succeed, but the database is not removed. 

Basically applying `FailoverGroupPatch` with an empty `IList<string> Databases` does not remove the database.

### Expected behavior

Database is removed from Failover Group.

### Actual behavior

Database is **not** removed from Failover Group.

### Reproduction Steps

```
var patch = new FailoverGroupPatch();
foreach(var dbId in failoverGroup.Value.Data.Databases)
{
    if (dbId != databaseToRemoveResourceId)
    {
        patch.Databases.Add(dbId); //not executed since no other databases in the failover group               
    }
}
await failoverGroup.Value.UpdateAsync(WaitUntil.Completed, patch);
```

### Environment

<TargetFramework>net6.0</TargetFramework>

**Comment by rbe-planday** [comment]
Any update here @ArthurMa1978 ?

**Comment by dvbb** [comment]
Hi @rbe-planday 

Sorry for the late reply, if you want to remove all Databases from a FailoverGroup, you can use this code block below
```
var patch = new FailoverGroupPatch() { };
patch.Databases.Clear();
var updateResponse = await failoverGroup.UpdateAsync(WaitUntil.Completed, patch);
```
Its request body is:
```
    {
        "properties": {
            "databases": [
            ]
        }
    }
```

BTW, The reason for this issue is the SDK has a property named `IsUndefined`, if a property has never been used so it will not add to the request.
The request body corresponding to `var patch = new FailoverGroupPatch() { };`  is `{"properties":{}}`, it will not change Database
![image](https://github.com/Azure/azure-sdk-for-net/assets/61542202/d3e7e0e2-bdf2-46e5-897b-de9fbed29550)
