### ISSUE TITLE
Investigate disappearance of Microsoft.FeatureManagement from docs

### ISSUE THREAD

**Issue by danieljurek** [Azure/azure-sdk-for-net#34603]
https://github.com/Azure/azure-docs-sdk-dotnet/commit/a519b7149ef133aebac62ff3dc570d63d046bf97#diff-e277a82f2677eaf61c517a8dbd9f74a170ca0c90cb30c55e32c3bd665a6e20bcL44-L45

**Comment by JimSuplizio** [comment]
@danieljurek from our chat, this particular issue is something we can add validation to avoid. I'm going to create two issues and reference this issue in both of them.

**Comment by JimSuplizio** [comment]
Every library that was removed in the PR was because their json file version entries were empty.

**Comment by JimSuplizio** [comment]
The PR that created json files with empty versions also didn't add required fields to the json files. Further, several of these don't have entries in the azure-sdk's dotnet-packages.csv which is supposed to be the source of truth. While I've got a fix for most of those, I'm going to I’m going to get the older version of the original bundledpackages/*.csv file and pull the version from there in order to fix the rest. I'm not sure what to do with the ServiceDirectory and SdkType yet but I'll get it straightened out.
