### ISSUE TITLE
[BUG] Resource Graph Query with new SDK 

### ISSUE THREAD

**Issue by bhsubra** [Azure/azure-sdk-for-net#34646]
### Library name and version

Azure.ResourceManager.ResourceGraph 1.0.1

### Describe the bug

We are using new ResourceGraph SDK(Azure.ResourceManager.ResourceGraph version 1.0.1) in [Bicep vscode extension](https://github.com/Azure/bicep) to run a query to get login server names in our completions. The query is taking lot longer than expected and is causing UI delay in completion scenario. Here's sample code snippet that I am using:
```
var armClient = GetArmClient(templateUri);
TenantCollection tenants = armClient.GetTenants();
await foreach (TenantResource tenant in tenants)
{
    var queryContent = new ResourceQueryContent(queryToGetRegistryNames);
    Response<ResourceQueryResult> queryResponse = await tenant.GetResourcesAsync(queryContent);
```
Query:
```
Resources
| where type == ""microsoft.containerregistry/registries""
| project properties[""loginServer""]
```
I noticed a lot of time is being spent in getting the TenantCollection. Could you please take a look and let me know If I am missing something?

### Expected behavior

More optimized API that we could use in completion scenario.

### Actual behavior

Latency in query execution

### Reproduction Steps

Provided sample code and query in description. Let me know if you need anything else.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by ArthurMa1978** [comment]
Thank you for reaching out to us about the Azure SDK for .NET. Unfortunately, this issue is related to the service side and not the SDK side, so we are not able to help you with it. Therefore, we are closing this issue for now. If you need more assistance, please [open an Azure support request](https://docs.microsoft.com/azure/azure-portal/supportability/how-to-create-azure-support-request). We apologize for any inconvenience this may cause you.

We value your feedback and we want to make sure that your problem is solved. If you think that we have misunderstood your issue or closed it incorrectly, please feel free to comment on this thread and reopen the issue. We will be happy to assist you further. Thank you for your understanding and cooperation.
