### ISSUE TITLE
Unable to receive deferred dead-letter from session-enabled queue

### ISSUE THREAD

**Issue by DeepakMohanSingh** [Azure/azure-sdk-for-net#34662]
I've a session-enabled queue with a message in DLQ and the state of the message is "Deferred". I use the "ReceiveDeferredMessageAsync()" method to receive the message but it fails with the exception "Azure.Messaging.ServiceBus.ServiceBusException: 'The session lock has expired on the MessageSession. Accept a new MessageSession.".

I don't think session locks are required for DLQ. Kindly suggest.

Here's the repro step:

**C#**
```
var serviceBusClient = new ServiceBusClient("<connectionstring>");
var serviceBusReceiver = serviceBusClient.CreateReceiver("<queue>", new ServiceBusReceiverOptions
{
    ReceiveMode = ServiceBusReceiveMode.PeekLock,
    SubQueue = SubQueue.DeadLetter
});

var message = await serviceBusReceiver.ReceiveDeferredMessageAsync(<sequence number>);
```

**Exception:**

> Azure.Messaging.ServiceBus.ServiceBusException: 'The session lock has expired on the MessageSession. Accept a new MessageSession. TrackingId:8d745660-ceed-4806-9c39-8bd2b0c63875_B3, SystemTracker:NoSystemTracker, Timestamp:2023-03-02T06:47:29 (SessionLockLost). For troubleshooting information, see https://aka.ms/azsdk/net/servicebus/exceptions/troubleshoot.'

**Comment by jsquire** [comment]
Hi @DeepakMohanSingh.  Thank you for reaching out and we regret that you're experiencing difficulties.  In order to receive from a session-enabled resource, you'll need to use a [ServiceBusSessionReceiver](https://learn.microsoft.com/dotnet/api/azure.messaging.servicebus.servicebussessionreceiver?view=azure-dotnet), which you create by accepting a session from the `ServiceBusClient` using either [AcceptNextSessionAsync](https://learn.microsoft.com/dotnet/api/azure.messaging.servicebus.servicebusclient.acceptnextsessionasync?view=azure-dotnet) or [AcceptSessionAsync](https://learn.microsoft.com/dotnet/api/azure.messaging.servicebus.servicebusclient.acceptsessionasync?view=azure-dotnet).   Once you've accepted the session, you'll hold its lock and will be able to receive from it.

More examples of sending/receiving from session-based entities can be found in [this sample](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/servicebus/Azure.Messaging.ServiceBus/samples/Sample03_SendReceiveSessions.md).

**Comment by DeepakMohanSingh** [comment]
Hi @jsquire, thanks for your reply. I am afraid I can’t use ServiceBusSessionReceiver to receive messages from a dead letter queue. Please assist. Thanks.

**Comment by jsquire** [comment]
apologies; that's my bad, I overlooked that we're talking about dead-lettered messages.

@JoshLove-msft:  Would you mind offering thoughts?

**Comment by JoshLove-msft** [comment]
@DeepakMohanSingh, can you clarify the full sequence of events here?
- you deadletter a session message
- you then receive the deadletter message and defer
- you then attempt to receive the deferred message?

**Comment by DeepakMohanSingh** [comment]
Hi @JoshLove-msft, I just sent a message with "TimeToLive" property set to 10 seconds. The message got dead-lettered as I've set "Move to dead-letter upon time expiration" already.

I then deferred the message manually using .Net.

I then tried to receive the message from another .Net application (Code is shared above), which gave me an exception stated above.

Please let me know if you need more details. Thanks.

**Comment by JoshLove-msft** [comment]
It is working as expected in my testing. Can you let me know if I'm doing something differently:

```c#
  await using var client = new ServiceBusClient(TestEnvironment.ServiceBusConnectionString);
  await using var sender = client.CreateSender(scope.QueueName);

  await sender.SendMessageAsync(ServiceBusTestUtilities.GetMessage("sessionId"));

  var receiver = await client.AcceptNextSessionAsync(scope.QueueName);
  var message = await receiver.ReceiveMessageAsync();
  await receiver.DeadLetterMessageAsync(message);

  var deadLetterReceiver = client.CreateReceiver(scope.QueueName, new ServiceBusReceiverOptions
  {
      SubQueue = SubQueue.DeadLetter
  });

  var deadLetterMessage = await deadLetterReceiver.ReceiveMessageAsync();
  await deadLetterReceiver.DeferMessageAsync(deadLetterMessage);

  var deferred = await deadLetterReceiver.ReceiveDeferredMessageAsync(deadLetterMessage.SequenceNumber);
  Assert.IsNotNull(deferred);
```

**Comment by DeepakMohanSingh** [comment]
Hey @JoshLove-msft, thanks for your reply. Your code works for me too. Can you try the below lines alone from your application? I actually wanted you to **_not try_** ReceiveMessageAsync() as that's the solver in your case. Please run the below lines alone and have nothing in your app:

```
await using var client = new ServiceBusClient("<connection_string>");

var deadLetterReceiver = client.CreateReceiver("<queue>", new ServiceBusReceiverOptions
{
    SubQueue = SubQueue.DeadLetter
});

var deferred = await deadLetterReceiver.ReceiveDeferredMessageAsync(<sequence_number>);
```

**Comment by JoshLove-msft** [comment]
I'm not sure I follow - I needed to receive the message to defer it. ReceiveDeferredMessage is used to receive messages that have been deferred - not messages that have merely been deadlettered.

**Comment by DeepakMohanSingh** [comment]
Please receive the deferred dead letter using sequence number (note it down). Run the code that I’ve shared (paste the connection string, queue name, and sequence number). 

Do not attempt to use ReceiveMessageAsync() . Just use ReceiveDeferredMessageAsync().

Note: I am deferring the message from application1 and receiving it from application2 (I store sequence number in my DB).

hope it helps.

**Comment by DeepakMohanSingh** [comment]
Hi team, any luck?

Thanks.

**Comment by JoshLove-msft** [comment]
I was able to reproduce the issue when using a separate receiver/client as you mentioned when attempting the final receive:

```c#
  await using var client = new ServiceBusClient(TestEnvironment.ServiceBusConnectionString);
  await using var sender = client.CreateSender(scope.QueueName);

  await sender.SendMessageAsync(ServiceBusTestUtilities.GetMessage("sessionId"));

  var receiver = await client.AcceptNextSessionAsync(scope.QueueName);
  var message = await receiver.ReceiveMessageAsync();
  await receiver.DeadLetterMessageAsync(message);

  var deadLetterReceiver = client.CreateReceiver(scope.QueueName, new ServiceBusReceiverOptions
  {
      SubQueue = SubQueue.DeadLetter
  });

  var deadLetterMessage = await deadLetterReceiver.ReceiveMessageAsync();
  await deadLetterReceiver.DeferMessageAsync(deadLetterMessage);

  await using var client2 = new ServiceBusClient(TestEnvironment.ServiceBusConnectionString);

  var deadLetterReceiver2 = client2.CreateReceiver(scope.QueueName, new ServiceBusReceiverOptions
  {
      SubQueue = SubQueue.DeadLetter
  });

 // this throws SessionLockLost
  var deferred = await deadLetterReceiver2.ReceiveDeferredMessageAsync(deadLetterMessage.SequenceNumber);
  Assert.IsNotNull(deferred);
```

I'll need to reach out to the service team to find out why this is happening.

**Comment by JoshLove-msft** [comment]
The service team is looking into this.

**Comment by DeepakMohanSingh** [comment]
> The service team is looking into this.

Thanks @JoshLove-msft, appreciate your support.

**Comment by yvgopal** [comment]
This is not an SDK issue. It is an issue with the service bus service. Service Bus never allowed receiving deferred messages from a session-ful queue or subscription. So I don't want to treat this as a bug or anything. I am closing this issue, since there is already a support ticket raised to the service team. We will have to decide whether to let a client defer dead-lettered messages or not.

**Comment by DeepakMohanSingh** [comment]
Thanks for explaining. I believe we were using this in the deprecated version of SDK but I’ll need to check it once.

Even in the latest version, the below code actually works. A bit strange though, but using this line _deadLetterReceiver.ReceiveMessageAsync();_ before receiving the deferred message makes it work as expected. 

An ETA of stopping deferring DLQ will be very helpful in our case. Thanks.

**Comment by yvgopal** [comment]
I have checked this again.
Receiving deferred messages works fine as long as a receive link is opened. Both .net core SDKs (Track1 and Track2) open the receive link only when the first receive request is made. Am I right? That's why the sample works fine when receive is called at least once on a receiver object, after it is created. @JoshLove-msft Am I right?

In Track 0 SDKs and Java SDKs, receive link is created when a receiver is created. They don't have this problem.
I will fix this corner case in the service, in the next release. Will probably roll out next month.

**Comment by JoshLove-msft** [comment]
@yvgopal - that's right. I just confirmed that if I call receive before the call to ReceiveDeferredMessage, the code above works.
