### ISSUE TITLE
[FEATURE REQ] Duration for Arm Deployments

### ISSUE THREAD

**Issue by stevengiannakopoulos** [Azure/azure-sdk-for-net#34703]
### Library name

Azure.ResourceManager.Resources

### Please describe the feature.

This feature request is for ArmDeploymentProperties. I would like to request the field "duration" which is the duration of the deployment for deploying ARM templates using the ArmClient. Right now it appears to be defaulting at 4 days.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by live1206** [comment]
@stevengiannakopoulos I suppose you want to add `duration` to [`ArmDeploymentProperties`](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/resources/Azure.ResourceManager.Resources/src/Generated/Models/ArmDeploymentProperties.cs). 
SDK is generated from swagger, if we take a look at [DeploymentProperties](https://github.com/Azure/azure-rest-api-specs/blob/d247207c59848d06facf8a7b4f884e356205c15c/specification/resources/resource-manager/Microsoft.Resources/stable/2022-09-01/resources.json#L4606) in swagger, duration is missing. This is not something SKD team can do, you need to raise a feature request to the service team. Please let me know if I misunderstand.

**Comment by ArthurMa1978** [comment]
Since this issue is related to the service side and not the SDK side, so we are not able to help you with it. Therefore, we are closing this issue for now. If you need more assistance, please [open an Azure support request](https://docs.microsoft.com/azure/azure-portal/supportability/how-to-create-azure-support-request). We apologize for any inconvenience this may cause you.

We value your feedback and we want to make sure that your problem is solved. If you think that we have misunderstood your issue or closed it incorrectly, please feel free to comment on this thread and reopen the issue. We will be happy to assist you further. Thank you for your understanding and cooperation.
