### ISSUE TITLE
[FEATURE REQ] Policy Exemptions SDK C#

### ISSUE THREAD

**Issue by stevengiannakopoulos** [Azure/azure-sdk-for-net#34704]
### Library name

Azure.ResourceManager.PolicyInsights

### Please describe the feature.

This feature request is for supporting policy exemptions by using the Azure SDK by using the ArmClient.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by live1206** [comment]
This is tracked in https://github.com/Azure/azure-sdk-for-net/issues/33377, because the corresponding [swagger](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/resources/resource-manager/Microsoft.Authorization/preview/2022-07-01-preview/policyExemptions.json) is only in preview, not in stable yet.
We would like to include it once it goes stable.
Close this for now.
