### ISSUE TITLE
Why is ProvisioningState in IDeployment not an Enum

### ISSUE THREAD

**Issue by abhi1509** [Azure/azure-sdk-for-net#3470]
Currently ProvisioningState is a string. From sample code I figured that possible values are:
"Succeeded", "Failed", "Canceled".

Why is this not an enum?

**Comment by hovsepm** [comment]
@abhi1509 ProvisioningState is not a finite list of three values. Each service team may have their additional statuses that they want to provide to caller - e.g. Restarting,

**Comment by abhi1509** [comment]
shouldn't then each service team have a version of it?
eg: https://msdn.microsoft.com/en-us/library/azure/microsoft.azure.management.resources.models.provisioningstate_members.aspx
How is a consumer to know what are valid values?

**Comment by shahabhijeet** [comment]
@abhi1509 are you getting provisioning state anything different from what you see in here? Please do let us know.
https://msdn.microsoft.com/en-us/library/azure/microsoft.azure.management.resources.models.provisioningstate_members.aspx

Regarding not making it an enum, that is a good suggestion. I agree that would be definitely easy from discoverability point of view.
But due to distributed and fluid nature of various teams across Azure, maybe string was a better/flexible option when ResourceManager teams designed this for the rest of the Azure service teams.

Please reopen this issue, if you have more information about the Provisioning state as requested above.

**Comment by abhi1509** [comment]
How is one supposed to know what the right values are across different
teams? Documentation is not discoverable.
Even at
https://msdn.microsoft.com/en-us/library/azure/microsoft.azure.management.resources.models.provisioningstate_members.aspx
it doesn't describe much.

**Comment by abhi1509** [comment]
Something like what Network team did would be really helpful-


using Microsoft.Azure.Management.ResourceManager.Fluent.Core;

namespace Microsoft.Azure.Management.Network.Fluent.Models
{
  public class ProvisioningState : ExpandableStringEnum<ProvisioningState>
  {
    public static readonly ProvisioningState Succeeded =
ExpandableStringEnum<ProvisioningState>.Parse("Succeeded");
    public static readonly ProvisioningState Updating =
ExpandableStringEnum<ProvisioningState>.Parse("Updating");
    public static readonly ProvisioningState Deleting =
ExpandableStringEnum<ProvisioningState>.Parse("Deleting");
    public static readonly ProvisioningState Failed =
ExpandableStringEnum<ProvisioningState>.Parse("Failed");
  }
}
