### ISSUE TITLE
[BUG] Not able to fetch Hybrid Connections for App Service Plan

### ISSUE THREAD

**Issue by JagodaMika** [Azure/azure-sdk-for-net#34745]
### Library name and version

Azure.ResourceManager.AppService v1.0.1

### Describe the bug

Not able to retrieve all Hybrid Connections in use in given App Service plan.

### Expected behavior

Being able to get a list of Hybrid Connections from App Service plan

### Actual behavior

When trying to iterate over a result from method GetHybridConnectionRelaysAsync() I receive an error:
Invalid URI: The format of the URI could not be determined.   

at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind, UriCreationOptions& creationOptions)
   at System.Uri..ctor(String uriString)
   at Azure.ResourceManager.AppService.HybridConnectionData.DeserializeHybridConnectionData(JsonElement element)
   at Azure.Core.PageableHelpers.PageableImplementation`1.<GetEnumerator>d__17.MoveNext()

### Reproduction Steps

1. Get appServicePlan from ResourceGroup - ResourceGroup.GetAppServicePlanAsync();
2.  Invoke GetHybridConnectionRelaysAsync() on returned appServicePlan
3. Try to iterate over result (according to Microsoft documentation - https://learn.microsoft.com/pl-pl/dotnet/api/azure.asyncpageable-1?view=azure-dotnet

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by ArcturusZhang** [comment]
Hi @JagodaMika 
This is probably caused by the inconsistent format on one of the properties on this HybridConnectionData, highly probable to be [this property](https://github.com/Azure/azure-sdk-for-net/blob/e0e5de62b9da73c576adeae2035dbdea85a69c87/sdk/websites/Azure.ResourceManager.AppService/src/Generated/HybridConnectionData.cs#L60) which says it is an "ArmUri" but actually means an arm resource id instead of Uri.

To confirm, could you please provide some log around that request? You could have the raw request and response by adding this listener before you run the problematic code:
```csharp
using AzureEventSourceListener listener = AzureEventSourceListener.CreateConsoleLogger(System.Diagnostics.Tracing.EventLevel.Verbose);
```
And add this ClientOptions when you are constructing the `ArmClient` instance
```
new ArmClientOptions()
{
    Diagnostics = {
        IsLoggingContentEnabled = true
    }
}
```
By doing these two, you should be able to see the request log and could you please paste the response of request `GET /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Web/serverfarms/{name}/hybridConnectionRelays` here so that we could confirm the root cause of this issue?

**Comment by ArcturusZhang** [comment]
OK never mind, I am able to reproduce the response and it looks like this:
```
{
  "value": [
    {
      "id": "/subscriptions/{subId}/resourceGroups/arcturus-test/providers/Microsoft.Web/serverfarms/arcturus-plan2/hybridConnectionNamespaces/arcturus-servicebus/relays/arcturusConnection",
      "name": "arcturusConnection",
      "type": "Microsoft.Web/serverfarms/hybridConnectionNamespaces/relays",
      "location": "East US",
      "properties": {
        "serviceBusNamespace": "arcturus-servicebus",
        "relayName": "arcturusConnection",
        "relayArmUri": "/subscriptions/{subId}/resourceGroups/arcturus-test/providers/Microsoft.Relay/namespaces/arcturus-servicebus/HybridConnections/arcturusConnection",
        "hostname": "arcturusHost",
        "port": 999,
        "sendKeyName": "defaultSender",
        "sendKeyValue": "",
        "serviceBusSuffix": ".servicebus.windows.net"
      }
    }
  ],
  "nextLink": null,
  "id": null
}
```
We will come up to a fix very soon.

**Comment by JagodaMika** [comment]
Great, thanks!
