### ISSUE TITLE
How to get some Service Bus message's data inside ProcessErrorAsync method using ServiceBusProcessor?

### ISSUE THREAD

**Issue by verdysh** [Azure/azure-sdk-for-net#34804]
### Library name and version

Azure.Messaging.ServiceBus, version 7.12.0

### Query/Question

I have such code:

```
var processor = client.CreateProcessor();

processor.ProcessMessageAsync += async (ProcessMessageEventArgs args) =>
{
	object tenantId = null;
	args.Message.ApplicationProperties.TryGetValue("tenantId", out var tenantId);

	// ...
};

processor.ProcessErrorAsync += async (ProcessErrorEventArgs args) =>
{
	// ...
	
	_logger.LogError(...);
};
```

I write log if something goes wrong. I want to add into the log item `tenantId` from the message's application properties. But I've not found a way how to get a message inside `ProcessErrorAsync `handler or how to set some data inside `ProcessMessageAsync` to make it available inside `ProcessErrorAsync`.

**Comment by jsquire** [comment]
Hi @verdysh.  There is not a way to correlate a specific message with an invocation of the `ProcessErrorAsync` handler.  The handler is invoked for a number of reasons, many of which are not associated with a message.  If there are actions that you'd like to take on a message if processing fails, it is recommended that you include a `try/catch` block in your `ProcessMessagesAsync` handler code to detect the processing error and perform those actions.

I'm going to mark this as addressed, but please feel free to unresolve if you'd like to continue the conversation.

**Comment by verdysh** [comment]
Hi @jsquire ! Thanks for the answer.

> many of which are not associated with a message

Could you give an example? Or tell me please when I should use `ProcessErrorAsync` if all the code inside `ProcessMessagesAsync` is wrapped in `try/catch`.

**Comment by jsquire** [comment]
Sure.  Examples would be any failure in the processor infrastructure itself, such as a transient network issue that persists after being retried.  Generally speaking, any action that you need to take in response to a failure with message processing should be handled in the processing handler.  

The error handler is intended to allow your application to have awareness of patterns of errors that may be occurring.   The processor itself is highly resilient and can recover from most error conditions, but it views each exception as an individual event.  Because it does not have insight into the host environment, application, and messaging workload, the processor cannot react to patterns of errors.  

For example, if the host network is unavailable, the processor cannot know whether it is appropriate to keep retrying until it returns or whether it should stop processing because the network is not expected to recover.  As a result, it will always attempt to make forward progress and relies on the application to understand patterns of events that should be interpreted as "we should stop processing" - and take the appropriate action.

**Comment by jsquire** [comment]
> Am I correct if I say that the general pattern is to view to the data provided by ProcessErrorEventArgs and depends on it we may do something with `ServiceBusProcessor` instance itself?

This is correct.   Though, I will mention that the scenarios for this are rare.   Unless you know for sure that the errors are unrecoverable (such as the Service Bus queue having been deleted), you generally want to let the processor recover on its own.

**Comment by verdysh** [comment]
Got it. Thank you for the answers!
