### ISSUE TITLE
Remove hard coded regions from Sql tests

### ISSUE THREAD

**Issue by dnayantara** [Azure/azure-sdk-for-net#3492]
This change is to remove the hard coded regions in Sql tests and allow the region to be specified by the connection string instead. Reference - https://github.com/Azure/azure-powershell/blob/preview/documentation/Using-Azure-TestFramework.md#environment--custom
This was found in the PR - https://github.com/Azure/azure-sdk-for-net/pull/3488

**Comment by cormacpayne** [comment]
@nathannfan any progress on this issue?

**Comment by nathannfan** [comment]
@cormacpayne the fix is coded and I've re-recorded all tests, but two areas are failing.

First area - vnetfirewallrules, is private preview and I can work with that team to get those recordings.

Second area - aad tests, is blocked on an issue around AAD that @jaredmoo  working on.  I think you're talking to him separately about this?

**Comment by jaredmoo** [comment]
AAD issue - there are some tests that rely on hardcoded AAD object id, I want to change these to use graph client to determine the current user's object id at runtime. Alternatively I can try injecting the object id in the same way that Nathan is injecting location.

**Comment by nathannfan** [comment]
Pull request for this issue: https://github.com/Azure/azure-sdk-for-net/pull/3535

**Comment by nathannfan** [comment]
@shahabhijeet @cormacpayne Hey guys, the pull request is ready for review - please have a look.  Thanks!

**Comment by jaredmoo** [comment]
Nice work Nathan! For the record, the AAD test recordability issue that I mentioned earlier was fixed with #3527 .
