### ISSUE TITLE
[QUERY] Use of AMQP session in EventHub

### ISSUE THREAD

**Issue by minghuaw** [Azure/azure-sdk-for-net#34948]
### Library name and version

Azure.Messaging.EventHubs

### Query/Question

I noticed that each AMQP sender/receiver link is created with a separate AMQP session. Is there any special reason behind this design decision? I am asking because I am currently working on a rust sdk for event hubs

**Comment by jsquire** [comment]
Hi @minghuaw.   The pattern used in `Azure.Messaging.EventHubs` was preserved from the previous generation package. _([src](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/eventhub/Microsoft.Azure.EventHubs/src/Amqp/AmqpEventDataSender.cs#L144))_    I don't know the reasoning behind why this was chosen, unfortunately.  Because most of the service interactions are undocumented beyond "use AMQP 1.0", we were careful to bring forward the existing patterns in transport layer to avoid behavioral differences and issues when migrating.

Your best bet for insight would be to open an issue in the [Microsoft.Azure.Amqp](https://github.com/Azure/azure-amqp/issues) repository with your inquiry.  The folks that maintain it are part of the Event Hubs service team and would be able to offer guidance for potential patterns in the Rust SDK.
