### ISSUE TITLE
Use DynamicData in CLU samples

### ISSUE THREAD

**Issue by heaths** [Azure/azure-sdk-for-net#35041]
For simpler samples and to provide feedback about DynamicJson to @annelo-msft, rewrite at least the CLU samples using DynamicJson. As a stretch, might be good to rewrite all tests using DynamicJson (start with samples, though, in case there are any blockers) so we can stop generating models using the old LLC generator. That would decrease the overall amount of work to update and should make it easier for the code gen folks to iterate on changes to the generator stack (one less potential roadblock).

**Comment by annelo-msft** [comment]
Thanks for filing this to track the work, Heath!

I'm adding the Azure.Core label as well, because your feedback on the behavior of DynamicJson will help raise our confidence that we can move it out of Azure.Core.Experimental.  Please share any issues you find with me and I'll do my best to fix them ASAP!
