### ISSUE TITLE
[BUG] Rest.ClientRuntime.Azure.Authentication references deprecated lib with vulnerability: IdentityModel.Clients.ActiveDirectory 

### ISSUE THREAD

**Issue by andyhammar** [Azure/azure-sdk-for-net#35076]
### Library name and version

Microsoft.Rest.ClientRuntime.Azure.Authentication 2.4.1

### Describe the bug

Hi!

Microsoft.Rest.ClientRuntime.Azure.Authentication 2.4.1 (latest)
references 
[Microsoft.IdentityModel.Clients.ActiveDirectory](https://www.nuget.org/packages/Microsoft.IdentityModel.Clients.ActiveDirectory/4.3.0) 4.3.0
which references
[System.Runtime.Serialization.Json](https://www.nuget.org/packages/System.Runtime.Serialization.Json) 4.3.0
which references
[System.Private.DataContractSerialization](https://www.nuget.org/packages/System.Private.DataContractSerialization/) 4.3.0
that is reported to have vulnerability [CVE-2023-21538](https://msrc.microsoft.com/update-guide/vulnerability/CVE-2023-21538) (reported by Dependency Track).

All packages are at their latest version except Microsoft.IdentityModel.Clients.ActiveDirectory, but the latest version also references libs of version 4.3.0.

Is there an update coming?

Is there something I can do to remedy? Is there an alternative package to use?

We're consuming `ClientCredential` and `ApplicationTokenProvider` in a .net7 function app running on Azure.

Thank you!

### Expected behavior

No reported vulnerabilities

### Actual behavior

Reported vulnerability on System.Private.DataContractSerialization by Dependency Track

### Reproduction Steps

-

### Environment

.net7 running on Azure function apps

**Comment by jsquire** [comment]
Hi @andyhammar.   Thank you for reaching out and we regret that you're experiencing difficulties.   According to its [NuGet page](https://www.nuget.org/packages/Microsoft.IdentityModel.Clients.ActiveDirectory), the `Microsoft.IdentityModel.Clients.ActiveDirectory` package has been formally retired and is no longer maintained or supported.   The page recommends moving to the `Microsoft.Identity.Client` library and suggests a migration guide.

Because this is out of support, I'm going to close this out rather than transfer to the repository where the Active Directory libraries are maintained.  If you decide that you'd like to file a report for the team that owned this package, you can do so [here](https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/issues).

**Comment by andyhammar** [comment]
/unresolve
Thanks a lot @jsquire, sorry for being unclear but my request is not actually for `Microsoft.IdentityModel.Clients.ActiveDirectory` but for the project referencing it, which is the one we're interacting with: [Microsoft.Rest.ClientRuntime.Azure.Authentication](https://www.nuget.org/packages/Microsoft.Rest.ClientRuntime.Azure.Authentication#dependencies-body-tab).
(I put that in the "lib name and version", but realize now that the title of the bug was quite misleading, sorry)

That project is not marked as deprecated, but is referencing the project that _is_ deprecated.

So, my question is: will `Microsoft.Identity.Client` replace both of them? That's is not clear from the nuget page of `Microsoft.Rest.ClientRuntime.Azure.Authentication`.

I understand that we should probably adopt the newer libraries overall, but right now I'm just trying to update packages to avoid the red flags in our vulnerability scans.

Thank you for your input!

**Comment by andyhammar** [comment]
@ArthurMa1978 Any input on the vulnerabilities being flagged? Thanks!

**Comment by ArthurMa1978** [comment]
Hey @andyhammar , the Rest.ClientRuntime.Azure.Authentication lib will also be deprecated soon.
