### ISSUE TITLE
[FEATURE REQ] Stream upload to ShareFileClient without requiring size first

### ISSUE THREAD

**Issue by nocoli** [Azure/azure-sdk-for-net#35095]
### Library name

Azure.Storage.Files.Shares

### Please describe the feature.

I have a scenario where I am trying to stream files from a third party API into a File share. Currently I am reading the whole file into memory (so I know the size of the content but would like to avoid this).

This is what I am currently doing where fileContent is a byte array (`byte[]`):
```
ShareClient shareClient = ShareClient(connectionString, name);
ShareDirectoryClient directory = shareClient.GetDirectoryClient("My Folder Name");
directory.CreateIfNotExists();

ShareFileClient sfc = directory.GetFileClient("My file name.pdf");

if (!await sfc.ExistsAsync()) {
    await sfc.CreateAsync(fileContent.Length);

    await sfc.UploadAsync(new MemoryStream(fileContent));
}

```

What I would like to do (or something like this) is this where myStream is just a Stream returned from `HttpResponseMessage.Content.ReadAsStreamAsync()`:
```
await sfc.CreateAsync();

await sfc.UploadAsync(myStream);
```

The goal is for my code to not be required to know the length of the stream before uploading to the File Share. This functionality already seems to exist for  `Azure.Storage.Blobs` where I can call `BlobClient.UploadAsync(Stream)`

**Comment by navba-MSFT** [comment]
@nocoli Apologies for the late reply. Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment]
@nocoli Could you please check if the [MaximumTransferSize ](https://learn.microsoft.com/en-us/dotnet/api/azure.storage.storagetransferoptions.maximumtransfersize?view=azure-dotnet#azure-storage-storagetransferoptions-maximumtransfersize)property helps ?

```
await fileClient.UploadAsync(MyLargeFile, transferOptions: new StorageTransferOptions
            { 
                InitialTransferSize = 1024 * 1024 * 4,
                MaximumTransferLength = 1024 * 1024 * 4
            })

```

**Comment by nocoli** [comment]
I can't see an overload for `UploadAsync` that has a parameter named `transferOptions`. Instead I set the `StorageTransferOptions` inside the `ShareFileUploadOptions` like so
```
await sfc.UploadAsync(stream, new ShareFileUploadOptions { 
    TransferOptions = new StorageTransferOptions() { 
        InitialTransferSize = 1024 * 1024 * 4,
        MaximumTransferSize = 1024 * 1024 * 4,
    } 
});
```
which gives me the following response:
```
RequestId:43460082-b01a-00a9-14ff-61ac04000000
Time:2023-03-29T05:30:02.9270218Z
Status: 404 (The specified resource does not exist.)
ErrorCode: ResourceNotFound
Content:
?<?xml version="1.0" encoding="utf-8"?><Error><Code>ResourceNotFound</Code><Message>The specified resource does not exist.
RequestId:43460082-b01a-00a9-14ff-61ac04000000
Time:2023-03-29T05:30:02.9270218Z</Message></Error>
Headers:
Server: Windows-Azure-File/1.0,Microsoft-HTTPAPI/2.0
x-ms-request-id: 43460082-b01a-00a9-14ff-61ac04000000
x-ms-client-request-id: a424490b-fb86-4273-8943-ceaa49f8824b
x-ms-version: 2021-12-02
x-ms-error-code: ResourceNotFound
Date: Wed, 29 Mar 2023 05:30:02 GMT
Content-Length: 223
Content-Type: application/xml
```
Assuming because I haven't called `sfc.CreateAsync()`

**Comment by navba-MSFT** [comment]
@nocoli Thanks for getting back. From the above error message, I looked at the failing request ID in our backend logs, I could see that the 404 is due to the resource Not found. It could be because either the share or directory folder or the file may not be present. So ensure that you create it first before you start uploading it.

**Request URL:**
https://thiXXXXXXing.file.core.windows.net:443/nicXXXXXhare/DEXXXXXlders/02.01.09.02%209b.%20EmXXXXe%20remXXXXXtegy%203XXXXX483/LF1_3XXXXX594.zip

**Comment by nocoli** [comment]
Hi @navba-MSFT Thanks for the quick response. I just retested and I'm positive the directory folder and file are both present. 

To further add to my suspicion that `sfc.CreateAsync()` needed to be called first I tested the following code and it worked:
```
await sfc.CreateAsync(224005475);

await sfc.UploadAsync(stream, new ShareFileUploadOptions { 
    TransferOptions = new StorageTransferOptions() { 
        InitialTransferSize = 1024 * 1024 * 4,
        MaximumTransferSize = 1024 * 1024 * 4,
    } 
});
```


Just to reiterate the problem with this is I don't know what the size of the file is going to be (this was just a local test and I knew what the size of the file was).

**Comment by navba-MSFT** [comment]
@amnguye @seanmcc-msft Any pointers on this are much appreciated.

**Comment by navba-MSFT** [comment]
@amnguye @seanmcc-msft re-tagging in case you missed checking this.

**Comment by amnguye** [comment]
Hi thanks for the ask.

Unfortunately that's not supported by the underlying REST API for creating Files in a File Share.
See the REST API documentaiton here
https://learn.microsoft.com/en-us/rest/api/storageservices/create-file#request-headers
![image](https://user-images.githubusercontent.com/48961492/229856518-bbf19f6b-cbf4-4127-9deb-0d0db210e92a.png)

If this is a requirement for you, I would suggest looking into a different type of storage option that would suit your needs best (e.g. block blob).

Closing this issue since this request is technically would be a feature request on the storage service not the SDK. Seek [Azure Support](https://support.microsoft.com/en-us/topic/contact-microsoft-azure-support-2315e669-8b1f-493b-5fb1-d88a8736ffe4) for storage service requests.
