### ISSUE TITLE
Add clientBuilder extensions to data plane SDKs

### ISSUE THREAD

**Issue by pallavit** [Azure/azure-sdk-for-net#35111]
Our design guidelines say we need to implement the following - https://azure.github.io/azure-sdk/dotnet_implementation.html#integration-with-aspnet-core. However some of the data plane SDKs do not follow this pattern. Creating a follow-up bug to evaluate these for the following SDK

- [ ] Azure.Security.Attestation
- [ ] Azure.AI.Language.Conversations
- [ ] Azure.AI.Language.QuestionAnswering
- [ ] Azure.Communication.AlphaIds
- [ ] Azure.Communication.CallAutomation
- [ ] Azure.Communication.CallingServer
- [ ] Azure.Communication.Chat
- [ ] Azure.Communication.Identity
- [ ] Azure.Communication.JobRouter
- [ ] Azure.Communication.MediaComposition
- [ ] Azure.Communication.NetworkTraversal
- [ ] Azure.Communication.PhoneNumbers
- [ ] Azure.Communication.Rooms
- [ ] Azure.Communication.ShortCodes
- [ ] Azure.Communication.Sms
- [ ] Azure.Security.ConfidentialLedger
- [ ] Azure.Containers.ContainerRegistry
- [ ] Azure.DigitalTwins.Core
- [x] Azure.Messaging.EventHubs.Processor  _**(no clients eligible for registration appear in this pacakge)**_
- [ ] Azure.IoT.Hub.Service
- [ ] Azure.Security.KeyVault.Administration
- [ ] Azure.Maps.Geolocation
- [ ] Azure.Maps.Rendering
- [ ] Azure.Maps.Routing
- [ ] Azure.Maps.Search
- [ ] Azure.AI.MetricsAdvisor
- [ ] Azure.MixedReality.Authentication
- [ ] Azure.IoT.ModelsRepository
- [ ] Azure.Monitor.OpenTelemetry.Exporter
- [ ] Azure.MixedReality.ObjectAnchors.Conversion
- [ ] Azure.AI.Personalizer
- [ ] Azure.Analytics.Purview.Administration
- [ ] Azure.Quantum.Jobs
- [ ] Azure.MixedReality.RemoteRendering
- [ ] Azure.Data.SchemaRegistry
- [ ] Azure.Storage.Blobs.Batch
- [ ] Azure.Storage.Blobs.ChangeFeed
- [ ] Azure.Analytics.Synapse.Artifacts
- [ ] Azure.Analytics.Synapse.ManagedPrivateEndpoints
- [ ] Azure.Analytics.Synapse.Monitoring
- [ ] Azure.Analytics.Synapse.Spark
- [ ] Azure.Graph.Rbac
- [ ] Azure.IoT.TimeSeriesInsights
- [ ] Azure.AI.Translation.Document
- [ ] Azure.Messaging.WebPubSub.Client

**Comment by lirenhe** [comment]
@ArcturusZhang,  please help to check why the extension is not generated for Azure.Analytics.Purview.Administration as it is also released by using DPG.

**Comment by ArcturusZhang** [comment]
@pallavit 
We only implemented asp.net extension generation in DPG.
The only package from HLC is Azure.Analytics.Purview.Administration, and its asp.net extension is explicitly suppressed by [this file](https://github.com/Azure/azure-sdk-for-net/blob/94b509a1c9a355a18ce2cb789b9aa1cbef492299/sdk/purview/Azure.Analytics.Purview.Administration/src/Customizations/TemporarySuppression.cs#L10) last time I introduced this feature, because in this package, we are introducing multiple top level clients with different client options. We did not support to generate this yet in the generator therefore generator cannot generate a proper version of asp.net for those clients that have manually written client options.
I will reenable the asp.net extension in this package, but it will only contain methods for one client, other clients must be manually added into the extension using customization code.

**Comment by pallavit** [comment]
Thanks for letting me know. Does the generator support this scenario today - i.e. generate builders when multiple top-level clients are available or is this expected to be manual for those scenarios?

**Comment by ArcturusZhang** [comment]
Hi @pallavit currently in the generator, we have explicitly blocked the combination of configuration `generation1-convenience-client: true` and `public-clients: true` (details in [this issue](https://github.com/Azure/autorest.csharp/issues/3151))
Therefore HLC packages will never have a generated public client, and this makes the generator impossible to generate client builder for them - because from the generator's perspective, it never knows a public clients in those packages.

Therefore, given the context above, it is reasonable to say, it is by-design that you have to write the client builder extensions along with your customization code of your new public clients in HLC packages. And I think the corresponding owners of those HLC packages should follow up on this issue to get the package updated with the client builder extensions.

**Comment by pallavit** [comment]
Sounds good. Thank you for clarification here.

**Comment by jsquire** [comment]
I'm going to close this out as it is really not actionable.   Each library will need to regenerate/address this individually, and it is purview of the architecture board to discuss the lack of extensions in the API for each as part of their GA review.
