### ISSUE TITLE
[BUG] warning MSB3277: There was a conflict between "Azure.Core, Version=1.27.0.0... nd "Azure.Core, Version=1.30.0.0

### ISSUE THREAD

**Issue by da-ms-22** [Azure/azure-sdk-for-net#35284]
### Library name and version

Azure.Core 1.30.0.0  and 1.27.0.0

### Describe the bug

Couldn't build my project. Thanks for your help.

Got this error - Microsoft.Common.CurrentVersion.targets(2352,5): warning MSB3277: There was a conflict between "Azure.Core, Version=1.27.0.0, Culture=neutral, PublicKeyToken=92742159e12e44c8" and "Azure.Core, Version=1.30.0.0, Culture=neutral, PublicKeyToken=92742159e12e44c8".

Microsoft.Common.CurrentVersion.targets(2352,5): warning MSB3277:     "Azure.Core, Version=1.27.0.0, Culture=neutral, PublicKeyToken=92742159e12e44c8" was chosen because it was primary and "Azure.Core, Version=1.30.0.0, Culture=neutral, PublicKeyToken=92742159e12e44c8" was not.

### Expected behavior

I could use 1.30.0.0 and project should build successfully.

### Actual behavior

Project couldn't build.

### Reproduction Steps

Project A has transitive package reference to Azure.Core 1.27.0.0. Class library project B has transitive package reference to Azure.Core 1.30.0.0. Project A references project B.dll. Error occurs when project A is building.

**Comment by jsquire** [comment]
Hi @da-ms-22.  Thank you for reaching out and we regret that you're experiencing difficulties.  The root cause of this is how .NET resolves dependencies and is not something that the Azure SDK packages can influence nor control.  Mitigation should be to add a direct reference for Azure.Core v1.30.0 to "Project A", which will allow it to take precedence over the conflicting transitive dependencies and hoist the version used.

I'm going to mark this as addressed, but please feel free to unresolve if you'd like to continue the discussion.

**Comment by da-ms-22** [comment]
Thank you. Adding a direct reference for Azure.Core v1.30.0 to "Project A" solved the issue.
