### ISSUE TITLE
[BUG] WebApiSkill is missing the authResourceId property

### ISSUE THREAD

**Issue by iulianmarius** [Azure/azure-sdk-for-net#35302]
### Library name and version

Azure.Search.Documents.Indexes.Models 11.5.0

### Describe the bug

The authResourceId Property that is used with a managed identity is not available

### Expected behavior

it should be possible to set the authResourceId 

### Actual behavior

cannot set authResourceId 

### Reproduction Steps

create a new WebApiSkill() and check for presence if the property

**Comment by ShivangiReja** [comment]
I see that `authResourceId` parameter is defined in the docs [here](https://learn.microsoft.com/en-us/azure/search/cognitive-search-custom-skill-web-api#section) but we are missing it in [WebApiSkill](https://github.com/Azure/azure-rest-api-specs/blob/904899a23a417768ce1ec1d5f89f33817f8ef8ad/specification/search/data-plane/Azure.Search/preview/2021-04-30-Preview/searchservice.json#L8824) swagger definition. 

 @gmndrg are we missing `authResourceId` property in the swagger definition or is it intentional?

**Comment by gmndrg** [comment]
Hello @iulianmarius first of all, please accept our apologies for any issue found with the current SDK preview version since this was not included as part of the swagger in the past. 
We are working to have this property as part of a release of beta SDK around July 2023. 
Unfortunately, this won't be released earlier since this has to be included in a version with other feature improvements and functionality as well. 
In the meantime, you can call directly the REST API from the SDK. Examples: https://stackoverflow.com/questions/9620278/how-do-i-make-calls-to-a-rest-api-using-c
If you have any other question or concern in the meantime, please let us know so we can help. Thank you for your time and patience.

**Comment by ShivangiReja** [comment]
The property `authResourceId` has been added in the release version 11.5.0-beta.3 of the Azure.Search.Documents package - [Azure.Search.Documents@11.5.0-beta.3](https://www.nuget.org/packages/Azure.Search.Documents/11.5.0-beta.3)

**Comment by iulianmarius** [comment]
@ShivangiReja thanks but i dont understand how to use this property. in the comment of the property is written : "..This value should be the application ID created for the function or app" but it accepty only a ResourceIdentifier. How to get the resource Identifier for the azure app that was registered? 
Thanks

**Comment by ShivangiReja** [comment]
[WebApiSkill.AuthResourceId](https://learn.microsoft.com/en-us/azure/search/cognitive-search-custom-skill-web-api#skill-parameters):
>A string that if set, indicates that this skill should use a managed identity on the connection to the function or app hosting the code. The value of this property is the application (client) ID of the function or app's registration in Azure Active Directory. This value will be used to scope the authentication token retrieved by the indexer, and will be sent along with the custom Web skill API request to the function or app. Setting this property requires that your search service is [configured for managed identity](https://learn.microsoft.com/en-us/azure/search/search-howto-managed-identities-data-sources) and your Azure function app is [configured for an Azure AD login](https://learn.microsoft.com/en-us/azure/app-service/configure-authentication-provider-aad).

>How to get the resource Identifier for the azure app that was registered?

@iulianmarius As per the description above, the value of this property is the application ID of the function or app's registration in Azure Active Directory. Please note that you cannot directly retrieve the `ResourceIdentifier` from the registered Azure app. Instead, you will get the application ID as a string value. You will have to create a new instance of the [ResourceIdentifier](https://learn.microsoft.com/en-us/dotnet/api/azure.core.resourceidentifier.-ctor?view=azure-dotnet#azure-core-resourceidentifier-ctor(system-string)) class by passing `application ID` as a string.
