### ISSUE TITLE
[BUG] RetriableStreamImpl NotSupportedException() when attempting to Seek it

### ISSUE THREAD

**Issue by elenadmoroz** [Azure/azure-sdk-for-net#35449]
### Library name and version

Azure.Storage.Blobs 12.15.0

### Describe the bug

NotSupportedException "Specified method is not supported." is thrown when trying to Seek 

   at Azure.Core.Pipeline.RetriableStream.RetriableStreamImpl.Seek(Int64 offset, SeekOrigin origin)

![image](https://user-images.githubusercontent.com/63601997/230858520-6c219525-bbc1-435e-b1a6-2bd2e4bc6c6d.png)

### Expected behavior

No Exception is thrown.

### Actual behavior

NotSupportedException "Specified method is not supported." is thrown when trying to Seek.

### Reproduction Steps

1. Create RetriableStreamImpl instance.
2. Call Seek method.

**Comment by jsquire** [comment]
Hi @elenadmoroz.  Thank you for reaching out and we regret that you're experiencing difficulties.  This behavior is by design; the stream does not support seeking.  Unfortunately, there's not enough context in the issue to understand the end-to-end scenario or provide suggestions.   If you would like to provide some additional details, we'd be happy to share thoughts for potential work-arounds.

I'm going to mark this as addressed, but please feel free to unresolve if you'd like to continue the discussion.

**Comment by elenadmoroz** [comment]
Hi @jsquire thank you for your comment.
