### ISSUE TITLE
[BUG] Response<T>.HasValue is inconsistent and returns unexpected results

### ISSUE THREAD

**Issue by Stabzs** [Azure/azure-sdk-for-net#35475]
### Library name and version

Azure.Storage.Queues 12.13.1

### Describe the bug

`QueueClient.ReceiveMessageAsync` returns a `Response<QueueMessage>` result, which is actually of type `ValueResponse<T>`. This internal class does NOT override the `Response<T>.HasValue` [property](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/core/Azure.Core/src/ResponseOfT.cs#L23). 

As a result, when checking the `HasValue` property, it unexpectedly returns true, even if `Value` is false. This is misleading and led to broken app code based on this assumption.

### Expected behavior

`HasValue` should reflect the current state of the `Value` property.

### Actual behavior

It always returns true, regardless of whether or not `Value` has a value that is different from `default(T)`.

### Reproduction Steps

```
var response = await _queueClient.ReceiveMessageAsync();
if (!response.HasValue)
{
    // this block should not be entered if response.Value is default(T) but it is
}
```

**Comment by jsquire** [comment]
@KrzysztofCwalina and @tg-msft:  Would you please offer thoughts on this scenario?  I believe that the assumption is `Response<T>` will always have a value returned by the service for an operation and that operation will respond with a 404 when there is no value.  In this case, the service is returning 200 but has no messages, so the "value" is equivalent to `default(T)`.

**Comment by jsquire** [comment]
Hi @Stabzs.  Thank you for reaching out and we regret that you're experiencing difficulties.  

I believe that the assumption is `Response<T>` will always have a value returned by the service for an operation and that operation will respond with a 404 when there is no value.  In this case, the service is returning 200 but has no messages, so the "value" is equivalent to `default(T)`.  I've looped in some folks to offer additional context and start a discussion on the developer experience.

**Comment by Stabzs** [comment]
Hi @jsquire, correct, that was my assumption. A 200 is returned but there is no message and, as a result, `Value` is null but `HasValue` continues to return true, which is unexpected.

While not necessarily a perfect parallel, `HasValue`/`Value` nomenclature in the Azure SDK strongly evokes nullable  `HasValue`/`Value`, and this departs from that expectation.

**Comment by christothes** [comment]
This is actually a storage API issue. `Response<T>` [does override](https://github.com/Azure/azure-sdk-for-net/blob/8237f559a56ded217e51727219cbf6df164472d3/sdk/core/Azure.Core/src/ResponseOfT.cs#L23) `HasResponse` and always sets it to `true`. This is because, generally, client operations should not be returning null as the value for a Response, but in this case I believe it was a tradeoff to avoid throwing when no messages are available. 

Since this API was originally released, we now have a [NullableResponse<T>](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/core/Azure.Core/src/NullableResponseOfT.cs) which can be used in scenarios where a null response is possible. [Here is an example usage](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/tables/Azure.Data.Tables/src/TableClient.cs#L710) in the Tables client SDK. Unfortunately, changing this `QueueClient` method now would be a breaking change, however we could certainly improve the API documentation to describe this behavior more clearly.

**Comment by Stabzs** [comment]
@christothes is it really a breaking change? The public api is still `Response<T>` which inherits from `NullableResponse<T>`. 

The issue is caused by the fact that the concrete type that is returned currently is internal `ValueResponse<T>` [here](https://github.com/Azure/azure-sdk-for-net/blob/8237f559a56ded217e51727219cbf6df164472d3/sdk/core/Azure.Core/src/Response.cs#L133).

It seems that if you wanted to keep the public api the same, you could instead return a new internal `NullableValueResponse<T>` inheriting from `Response<T>` that properly overrides `HasValue` to represent the state. That way your public api is intact and you can expose behavior that _actually_ represents the current state.

**Comment by christothes** [comment]
We can't override `Value` and make it nullable - this results in a [CS8764 - Nullability of return type doesn't match overridden member (possibly because of nullability attributes). ](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/nullable-warnings?f1url=%3FappId%3Droslyn%26k%3Dk(CS8764)#mismatch-in-nullability-declaration)

**Comment by KrzysztofCwalina** [comment]
> @KrzysztofCwalina and @tg-msft: Would you please offer thoughts on this scenario?

@Stabzs, did you really mean `if (!response.HasValue)` in the code above? i.e. did you intend to have the `!`? Also, I assume you meant `even if Value is default(T)` as opposed to `even if Value is false`.

If yes, I agree that we have a bit of a mess here. It's partially caused by trying to evolve these APIs over time while maintaining compatibility. But, I wonder if we could not improve the situation as follows:

1. HasValue should never "lie", i.e. must return true only if Value is not null and won't throw. 
2. `Response<T>` should override the Value property and the override should change the nullability annotation to "not nullable"
3. If a `Response<T>` instance does not have the value of T, accessing the Value property will throw.

**Comment by Stabzs** [comment]
@KrzysztofCwalina no, the block was intentionally `if (!response.HasValue)`. I can understand the confusion however...let me add some additional context. 

In my scenario, the queue client is being polled for additional messages and, if there is no message, it will call task delay, and then continue to loop. A more complete snippet would be:

```
// in the context of a loop

var response = await _queueClient.ReceiveMessageAsync();
if (!response.HasValue)
{
    await Task.Delay(duration);
    continue;
}

// else, process response.Value
```

As for the second half of your question, no, I mean `if Value is default(T)`; it should be semantically the same as `if response.HasValue == false` .

I do have concerns with number 3 of the above. Currently, to handle the broken `HasValue` property, I have to check for Value being null/default. If checking `.Value` throws if null, this breaks the current behavior of `QueueClient.ReceiveMessageAsync`, which will return a 200 with a null `Value` if there are no messages. Changing `Value` to throw if there is no value would certainly break the fix I just put into my application and would be very unexpected behavior.

In future major versions of the SDK, as a consumer, I'd love to see these response objects be properly updated to return `Response<T> where T : not null` in cases where Value can never be null, and `NullableResponse<T>` for things like QueueClient that can apparently have a null Value. That said, since that isn't accomplishable here (since `Response<T>` inherits from `NullableResponse<T>`), I'd love something that is both consistent and safe to call. I am still surprised to see `ValueResponse<T>` returned as `Response<T>` and I think there's an opportunity there to save the public `Response<T>` API with a different internal shape, but I'm also happy with anything that solves for your points 1 and 2.

**Comment by Stabzs** [comment]
In addition, only half of the issue lies with `Response<T>`. The other half belongs to `internal ValueResponse<T>` which _could_ override `HasValue` and instead chooses to delegate the responsibility on to `Response<T>`. 

If the behavior was inconsistently overridden in both classes, you could have `Response<T>` do the right thing and then end up with `ValueResponse<T>` overwriting the correct behavior.

**Comment by KrzysztofCwalina** [comment]
> Currently, to handle the broken HasValue property, I have to check for Value being null/default. If checking .Value throws if null, this breaks the current behavior 

and 

> In future major versions of the SDK, as a consumer, I'd love to see these response objects be properly updated to return `Response<T> where T : not null`

We cannot have both, i.e. `Response<T>.Value` needs to either throw or not be marked with "not null" (nullability annotation or a constraint)

> The other half belongs to internal `ValueResponse<T>` which could override HasValue and instead chooses to delegate the responsibility on to `Response<T>`.

Yeah, this is covered by the bullet 1, i.e. "HasValue should never "lie", i.e. must return true only if Value is not null and won't throw."

**Comment by Stabzs** [comment]
@KrzysztofCwalina understood. I was envisioning `Response<T> where T : not null` to be a breaking (major version) change which would throw on accessing `.Value` that is null. My point was that without a breaking change, it would be completely unexpected for it to throw currently.

**Comment by KrzysztofCwalina** [comment]
This would be a massive breaking change. We don't do these, even in major versions.

**Comment by Stabzs** [comment]
I think that's the right choice. Any code that throws where it didn't throw previously is a much poorer experience than a property that doesn't actually reflect the current state.

My guess is that most devs are currently checking `Value is null` and, if it changes to throw, their code suddenly breaks without warning.

By implementing your suggestion of suppressing nullability checks and preserving `Value` functionality, while adding `HasValue` functionality, it is a net improvement, even if nullability checks suffer. And since anything else is too large of a breaking change, I'm not sure what else you could do other than modifying my original suggestion of an `internal NullableValueResponse<T>` type that handles the nullability check suppression and is returned as the public type. That said, I'm guessing that also is too large of a breaking change.

I appreciate the effort to come up with a creative solution!
