### ISSUE TITLE
ApiManagementGatewayCollection.GetAllAsync does not support Region in filter

### ISSUE THREAD

**Issue by adahlinvcrs** [Azure/azure-sdk-for-net#35695]
### Library name and version

Azure.ResourceManager.ApiManagement 1.0.1

### Describe the bug

The documentation of the ApiManagementGatewayCollection.GetAllAsync method (https://learn.microsoft.com/en-us/dotnet/api/azure.resourcemanager.apimanagement.apimanagementgatewaycollection.getallasync?view=azure-dotnet#azure-resourcemanager-apimanagement-apimanagementgatewaycollection-getallasync(system-string-system-nullable((system-int32))-system-nullable((system-int32))-system-threading-cancellationtoken) specifies that you can filter based on the gateway region, however doing so results in a 400 with an error stating that the 'region' property is not found.

### Expected behavior

Gateways are filtered based on the provided region value.

### Actual behavior

The request fails with a 400 Bad Request and the message: Could not find a property named 'region' on type 'urn:microsoft:windowsazure:apimanagement.mgmt.gateway

### Reproduction Steps

Construct an ApiManagementServiceResource using Azure resource values for subscription, resourcegroup and servicename, then perform the call:

GetApiManagementGateways().GetAllAsync

providing a filter string invoking an operator on the region property, as described in the docs https://learn.microsoft.com/en-us/dotnet/api/azure.resourcemanager.apimanagement.apimanagementgatewaycollection.getallasync?view=azure-dotnet#azure-resourcemanager-apimanagement-apimanagementgatewaycollection-getallasync(system-string-system-nullable((system-int32))-system-nullable((system-int32))-system-threading-cancellationtoken)

Capture the resulting Azure.RequestFailedException and study the message and status.

### Environment

* Windows 10
* net6.0 project
* Visual Studio 2022 17.4.2

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by ArthurMa1978** [comment]
Hey @adahlinvcrs , thank you for reaching out to us about the Azure SDK for .NET. Unfortunately, this issue is related to the service side and not the SDK side, so we are not able to help you with it. Therefore, we are closing this issue for now. If you need more assistance, please [open an Azure support request](https://docs.microsoft.com/azure/azure-portal/supportability/how-to-create-azure-support-request). We apologize for any inconvenience this may cause you.

We value your feedback and we want to make sure that your problem is solved. If you think that we have misunderstood your issue or closed it incorrectly, please feel free to comment on this thread and reopen the issue. We will be happy to assist you further. Thank you for your understanding and cooperation.
