### ISSUE TITLE
CVE in System.Drawing.Common 4.7.0 dependency still there

### ISSUE THREAD

**Issue by SymbioticKilla** [Azure/azure-sdk-for-net#35693]
@jsquire 
Hi!
Thank you for your effort and quick responses!

Unfortunately the problem is still there :(
![image](https://user-images.githubusercontent.com/59652865/228260947-184eae57-b807-41f4-bbd2-c9341083be76.png)

![image](https://user-images.githubusercontent.com/59652865/228260549-9eab0a49-5ee0-4dbc-ba3c-c259627d0e9f.png)

_Originally posted by @SymbioticKilla in https://github.com/Azure/azure-sdk-for-net/issues/32781#issuecomment-1486938819_

**Comment by jsquire** [comment]
Hi @SymbioticKilla.  Thanks for reaching out and we regret that you're experiencing difficulties.  I discussed this with both the Azure SDK and .NET security teams and they confirmed that this is considered a false positive by the scanner rather than an active security risk, as the issue being flagged exists only for an unsupported platform.   If you have a need to mitigate the false positive, the recommendation is to take a direct dependency on a version of `Microsoft.AspNetCore.DataProtection` in your application that is not flagged by the scanner.

Unfortunately, we're out of minor versions of `Microsoft.AspNetCore.DataProtection` to move to.  This is good motivation for us to investigate moving forward to a new major which would eliminate the support for the `netcore3.0` and `netcore3.1` targets and remove the dependency that your scanner is flagging.   This is something that we'll need some time to run down and test thoroughly.   I've filed #35707 to track these efforts, but I don't currently have an estimate on when we'll have bandwidth to schedule work on it.

I'm going to mark this as addressed, but please feel free to unresolve if you'd like to continue the discussion.
