### ISSUE TITLE
[FEATURE REQ] Align capacity data types in SKU types

### ISSUE THREAD

**Issue by timmkrause** [Azure/azure-sdk-for-net#35730]
### Library name

Azure.ResourceManager.IotHub

### Please describe the feature.

To avoid casting and to align data types `Capacity` should be aligned either towards `long?` or `int?`.

https://github.com/Azure/azure-sdk-for-net/blob/d72d72a125cf224b9e140edaac654b681be1233b/sdk/iothub/Azure.ResourceManager.IotHub/src/Generated/Models/IotHubSkuInfo.cs#L36

vs.

https://github.com/Azure/azure-sdk-for-net/blob/d72d72a125cf224b9e140edaac654b681be1233b/sdk/resourcemanager/Azure.ResourceManager/src/Resources/Generated/Models/ResourcesSku.cs#L46

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by RodgeFu** [comment]
ResourceManager is a general definition of capacity aligning with most azure resources. Changing it to int64 will be a breaking change and cause casting in more user scenarios when users are using the capacity with other azure resources. The capacity for iothub needs int64 instead of int32 according to the service definition which is a special case, so resolve as by-design. thanks.
