### ISSUE TITLE
[BUG] Getting FunctionInputConverterException when parsing EventData from IoT hub

### ISSUE THREAD

**Issue by the-programmer** [Azure/azure-sdk-for-net#35866]
### Library name and version

Azure.Messaging.EventHubs 5.9.0

### Describe the bug

For my current project I am trying to get the lifecycle events from the IoT Hub via the Event Hub to my Function app. See also this [stackoverflow](https://stackoverflow.com/questions/76071566/how-to-get-the-event-type-in-an-azure-function-app-coming-from-iot-hub-via-event) question.

Even tough I use a .net 6.0 non-isolated environment I still keep running into the issue that once a message arrives at the Function app it throws an FunctionInputConverterException once it is called by the event hub.

### Expected behavior

No exceptions and a log with all the event data as well as the life cycle data from my IoT device.

### Actual behavior

See [here](https://pastebin.com/tFf93MnZ) and [here](https://pastebin.com/K3bYVb3W) for the exceptions I got.

### Reproduction Steps

I grabbed my full test project and uploaded it to github.
https://github.com/the-programmer/AzureFunctionIssue

See the original stackoverflow question for the full set-up details.

### Environment

The set-up for the Function app was as follows.
![](https://i.imgur.com/wTXdMM8.png)

IDE is Visual studio 17.5.4

**Comment by jsquire** [comment]
Hi @the-programmer.   Thank you for reaching out and we regret that you're experiencing difficulties.   I'm not sure how your project was created, but it's using the set of packages associated with the isolated host model.  Because of this, the bindings lack support for `EventData` and other complex types.   The reference that you'll want for working with the in-process model is `Microsoft.Azure.Extensions.WebJobs.EventHubs`.  

As an example, using the Visual Studio template to generate:
![image](https://user-images.githubusercontent.com/913445/234969077-dca366f8-ccb7-4890-9e13-cd1afd226e4a.png)

The resulting minimal project looks like the following, though I've bumped the extensions package to the latest version:
```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <AzureFunctionsVersion>v4</AzureFunctionsVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.EventHubs" Version="5.3.0" />
    <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="4.1.1" />
  </ItemGroup>
  <ItemGroup>
    <None Update="host.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="local.settings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>Never</CopyToPublishDirectory>
    </None>
  </ItemGroup>
</Project>
```

This will allow you to bind to `EventData` as an input from the trigger, allowing you to access the full set of data that was read:

```csharp
[FunctionName("ExampleFunction")]
public static async Task Run([EventHubTrigger("samples-workitems", Connection = "")] EventData[] events, ILogger log)
{
    // Code
}
```

I'm going to mark this as addressed, but please feel free to unresovle if you'd like to continue the discussion.

**Comment by the-programmer** [comment]
I think I know what went wrong. I used the .net 7 template to generate the original project.

Next I simply changed from .net 7 to 6, thus generating the issue.

Tomorrow I'll try with a new solution and post the results here.

**Comment by the-programmer** [comment]
Tried with a new solution. Now my code works as intended.
