### ISSUE TITLE
How is the property "Reserved" used for a Site? What does it *do*?

### ISSUE THREAD

**Issue by sharon-dinara** [Azure/azure-sdk-for-net#35871]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f504092c-384b-52c0-76c8-eb9f6a8cf910
* Version Independent ID: 681711c8-b872-c003-a55a-a0083de3e9fc
* Content: [Site.Reserved Property (Microsoft.Azure.Management.WebSites.Models) - Azure for .NET Developers](https://learn.microsoft.com/en-us/dotnet/api/microsoft.azure.management.websites.models.site.reserved?view=azure-dotnet#microsoft-azure-management-websites-models-site-reserved)
* Content Source: [xml/Microsoft.Azure.Management.WebSites.Models/Site.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.Management.WebSites.Models/Site.xml)
* Service: **app-service**
* Sub-service: **web-apps**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by postmeback** [comment]
Kindly check [https://github.com/Azure/azure-sdk-for-net/pull/35913](https://github.com/Azure/azure-sdk-for-net/pull/35913)

**Comment by ArthurMa1978** [comment]
Thank you for reaching out to us about the Azure SDK for .NET. Unfortunately, your query is related to the service side and not the SDK side, so we are not able to help you with it. Therefore, we are closing this issue for now. If you need more assistance, please [open an Azure support request](https://docs.microsoft.com/azure/azure-portal/supportability/how-to-create-azure-support-request). We apologize for any inconvenience this may cause you.

We value your feedback and we want to make sure that your problem is solved. If you think that we have misunderstood your issue or closed it incorrectly, please feel free to comment on this thread and reopen the issue. We will be happy to assist you further. Thank you for your understanding and cooperation.
