### ISSUE TITLE
[QUERY]  Block blobs are not supported. HTTP Status Code: 400 - HTTP Error Message: Block blobs are not supported

### ISSUE THREAD

**Issue by rohitjadhavmsft** [Azure/azure-sdk-for-net#35950]
### Library name and version

Conversion.ps1

### Query/Question

I am trying the conversion using steps noted [here](https://learn.microsoft.com/en-us/azure/remote-rendering/quickstarts/convert-model#2-conversion-via-a-powershell-script)

Running this [script](https://github.com/Azure/azure-remote-rendering/blob/master/Scripts/Conversion.ps1) with updated arrconfig.json file.
 
![image](https://user-images.githubusercontent.com/107584956/235814367-2a84b25d-359b-4874-84b2-adb6dfbc88bd.png)

The 3D object file couch95.OU_preview is very small 1.6kbs in size. Is there a way to bypass this error? Also any documentation on what us supported and how to achieve block blob upload? 

### Environment

local

**Comment by jsquire** [comment]
Hi @rohitjadhavmsft.  Thank you for reaching out and we regret that you're experiencing difficulties.  Unfortunately, this repository is focused on the Azure SDK for .NET - we're unable to assist with other Azure issues.  Since what you're describing appears to be related to the configuration of your Azure Storage account and not one of the SDKs, your best path forward would be to [open an Azure support request](https://docs.microsoft.com/azure/azure-portal/supportability/how-to-create-azure-support-request).

You don't mention what SKU and redundancy settings were used for your Storage account, but not all support Block Blobs.  The tutorial that you've referenced specifically suggests a Premium Block blobs SKU with ZRS.  Some additional information on restrictions can be found in the note [here](https://learn.microsoft.com/rest/api/storageservices/using-blob-service-operations-with-azure-premium-storage#premium-gpv2-storage-accounts-support-page-blobs-only).  

I'm going to close this out;  if I've misunderstood what you're describing, please let us know in a comment and we'd be happy to assist as we're able.

**Comment by rohitjadhavmsft** [comment]
Thanks @jsquire
