### ISSUE TITLE
[BUG] Dropping events after a period of time

### ISSUE THREAD

**Issue by courtzzz** [Azure/azure-sdk-for-net#35951]
### Library name and version

Azure.messaging.eventhubs 5.8.1

### Describe the bug

We are seeing events being dropped after a period of time. This can be after a few thousand events, or 10's of thousands - we have 'Capture' on and are not seeing the Arvo events from a certain point in time.

We inject the `EventProducerClient` and then use that singleton to simply keep sending in a service as required within a cronjob that runs in a Kubernetes pod. 

The pattern is as follows:

```csharp
public EventHubClient(ILogger<EventHubClient> logger, EventHubProducerClient producerClient)
        {
            _producerClient = producerClient;
            _logger = logger;
        }

        public async Task<bool> SendBatchAsync(IEnumerable<EventData> events)
        {
            var eventBatch = await _producerClient.CreateBatchAsync();

            foreach (var eventData in events)
            {
                if (!eventBatch.TryAdd(eventData))
                {
                    _logger.LogInformation("Could not add event hub batch - likely maximum size reached - sending first batch");
                    await SendAsync(eventBatch);
                    _logger.LogInformation("Sent previous batch. Create new batch");
                    eventBatch = await _producerClient.CreateBatchAsync();
                    eventBatch.TryAdd(eventData);
                }
            }

            return await SendAsync(eventBatch);
        }
        
        private async Task<bool> SendAsync(EventDataBatch eventBatch)
        {
            try
            {
                await _producerClient.SendAsync(eventBatch);
                _logger.LogInformation("Published eventBatch with event count of {0} and size in bytes {1}",
                    eventBatch.Count, eventBatch.SizeInBytes);

                return true;
            }
            catch (Exception e)
            {
                _logger.LogError(e,
                    $"Publishing with primary eventHub failed with message {e.Message}. ");

            }
            finally
            {
                eventBatch.Dispose();
            }
        }
```

We can't afford to drop events - so my question is is there an issue perhaps with the way we are doing the `TryAdd`?

We also do not get an error logs - so it appears that everything is being sent - according to the docs - the eventhub is "acknowledging" the message then - but it doesn't appear?

### Expected behavior

The service should simply keep sending

### Actual behavior

The service suddenly stops sending and any subsequent calls cease to send any events even though there are no error logs

### Reproduction Steps

As per the description above

### Environment

.NET 6.0

**Comment by courtzzz** [comment]
@jsquire  Thanks Jesse

Yes, I removed a line where we attempted to send it to a secondary eventhub in case of failure.

I believe the events simply did not arrive on the eventhub. They initially were sending fine, and then suddenly just stopped - The red circle shows where they suddenly just stopped.

![image](https://user-images.githubusercontent.com/384711/236079526-2eeee9b5-ffb3-48d7-a81d-bba6fbdc61e4.png)

Could this be something about closing and connection to force them to flush? Or what could it be?

**Comment by jsquire** [comment]
There's no buffering or caching in the `EventHubProducerClient`, the `SendAsync` call encompasses the entire service operation.  When it returns, either the service has acknowledged receipt and taken responsibility for the events or an exception is thrown.  Since you're not seeing errors on the client, this seems like a potential service issue. 

If you're willing, I'd like to take a peek at the SDK logs, just to be sure that we're not overlooking something.   We'll want to grab a 5-minute slice of Verbose logs at the time you're sending events.   We can filter them down to just a few:

- All warnings
- All errors
- 3 (Publish Start)
- 4 (Publish Complete)
- 5 (Publish Error)

Those will show us exactly what the client is seeing at the AMQP level.   Discussion of how to capture them can be found in [this sample](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/eventhub/Azure.Messaging.EventHubs/samples/Sample10_AzureEventSourceListener.md).
