### ISSUE TITLE
[QUERY] What could be reason the Processor stops receiving messages?

### ISSUE THREAD

**Issue by arunprakashn** [Azure/azure-sdk-for-net#36085]
### Library name and version

Azure.Messaging.Servicebus 7.5.1

### Query/Question

I have a .net6 application that uses Azure.Messaging.Servicebus library. It implements a Background Service and there is a ServiceBusProcessor to listen to messages from a subscription. The application is deployed in k8s with 5 pods. i.e. There are 5 SB processors listening to the messages from the subscription. It was all working fine and after processing a huge number of messages(400,000+) the messages were not received anymore. There are no errors in the application. If there is a problem with the application, I believe, one pod can have the situation of not receiving messages but in my case, all 5 stopped. 

Is this an issue on the Service Bus Server side? There are no system errors reported on the SB metrics. 

### Environment

Linux
K8s Pods

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by JoshLove-msft** [comment]
This does sound like it would be a service issue, though I would strongly recommend upgrading to the latest version of the client library as there have been numerous fixes and enhancements since 7.5.1. If after upgrading, you are still facing the issue, can you please file a support request in the Azure Portal?
