### ISSUE TITLE
[QUERY] How to use service principal / managed identity for Azure SQL Database Export

### ISSUE THREAD

**Issue by galvesribeiro** [Azure/azure-sdk-for-net#36231]
### Library name and version

Azure.ResourceManager.Sql 1.2.0

### Query/Question

I'm trying to use `SqlDatabaseResource.ExportAsync()` and `DatabaseExportDefinition` to export a database. 

However, `DatabaseExportDefinition` requires a username and password and the `AuthenticationType` in all examples in this repo are setting it to `Sql`. 

For my use case we need to use both Service Principal and Managed Identity (e.g. `DefaultAzureCredential`).

What is the proper way to use `DatabaseExportDefinition` with it? We really don't want to have to create a sql login just for the export.

Thank you!

### Environment

```
.NET SDK:
 Version:   7.0.102
 Commit:    4bbdd14480

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  13.3
 OS Platform: Darwin
 RID:         osx.13-arm64
 Base Path:   /usr/local/share/dotnet/sdk/7.0.102/

Host:
  Version:      7.0.2
  Architecture: arm64
  Commit:       d037e070eb

.NET SDKs installed:
  6.0.405 [/usr/local/share/dotnet/sdk]
  7.0.102 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.13 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.13 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.2 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  x64   [/usr/local/share/dotnet/x64]
    registered at [/etc/dotnet/install_location_x64]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
  ```

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by sbebrys** [comment]
@jsquire Any feedback from the team? I have similar challenge and it looks that export API doesn't support any service identities from AAD, the best will be accept ManagedIdentity.

To show some background - we have requirement to create db backups on demand (not from schedule) and execute that by automation tools not users, but from security point of view we want block access by sql superuser and limit it only to AAD ids.
As I know SqlPackage accept pure access token so if export action using this tool it should be feasible.

**Comment by ArthurMa1978** [comment]
Thank you for reaching out to us about the Azure SDK for .NET. Unfortunately, this issue is related to the service side and not the SDK side, so we are not able to help you with it. Therefore, we are closing this issue for now. If you need more assistance, please [open an Azure support request](https://docs.microsoft.com/azure/azure-portal/supportability/how-to-create-azure-support-request). We apologize for any inconvenience this may cause you.

We value your feedback and we want to make sure that your problem is solved. If you think that we have misunderstood your issue or closed it incorrectly, please feel free to comment on this thread and reopen the issue. We will be happy to assist you further. Thank you for your understanding and cooperation.
