### ISSUE TITLE
Response was not set, make sure SendAsync was called

### ISSUE THREAD

**Issue by coding-bunny** [Azure/azure-sdk-for-net#36349]
## Library name and version

Azure.Core.HttpMessage.get_response()

## Describe the bug

The bug I am running into is similar to the issue reported here: https://github.com/Azure/azure-sdk-for-net/issues/33294.
When using Rider, and running the application locally in Debug mode, I keep getting this error when making a call to the Azure Blob Storage. I've verified that I have access, that the storage exists, basically, everything is in place.

### Call Stack
```
"InnerExceptionMessages": "Response was not set, make sure SendAsync was called",
        "StackTrace": [
            "at Azure.Core.HttpMessage.get_Response()",
            "at System.Diagnostics.DiagnosticSourceEventSource.TransformSpec.PropertySpec.PropertyFetch.RefTypedFetchProperty`2.Fetch(Object obj)",
            "at System.Diagnostics.DiagnosticSourceEventSource.TransformSpec.PropertySpec.Fetch(Object obj)",
            "at System.Diagnostics.DiagnosticSourceEventSource.TransformSpec.Morph(Object obj)",
            "at System.Diagnostics.DiagnosticSourceEventSource.FilterAndTransform.Morph(Object args)",
            "at System.Diagnostics.DiagnosticSourceEventSource.FilterAndTransform.<>c__DisplayClass2_1.<.ctor>b__2(KeyValuePair`2 evnt)",
            "at System.Diagnostics.DiagnosticSourceEventSource.CallbackObserver`1.OnNext(T value)",
            "at System.Diagnostics.DiagnosticListener.Write(String name, Object value)",
            "at Azure.Core.Pipeline.DiagnosticScope.ActivityAdapter.Dispose()",
            "at Azure.Core.Pipeline.DiagnosticScope.Dispose()",
            "at Azure.Core.Pipeline.RequestActivityPolicy.ProcessAsync(HttpMessage message
```

I can also confirm that this is only happening in Rider. When I am using Visual Studio Community 2022 for example, I do not run into these problems. Unfortunately, I cannot upgrade `System.Diagnostics.DiagnosticSourceEventSource` to 6.0.0 due legacy code at the moment. (We run the 4.6.0 and 4.7.0) versions

## Expected Behavior
This should just work regardless of IDE/Environment.
It clearly works in Visual Studio, but not with Rider.

## Actual Behavior
When calling the `.ExistsAsync` or `.Exists` method to verify a container exists on the Azure Blob Storage, the error is thrown.

## Environment
Windows 11
Rider IDE 2023.1.1
.NET Core App 2.2
System.Diagnostics.DiagnosticSourceEventSource < 6.0

I'm not expecting a fix, but a workaround would at least be awesome.

**Comment by jsquire** [comment]
Hi @coding-bunny.  Unfortunately, there's not much assistance that we can provide for this.  As noted in the issue that you've linked, the root cause of this problem is an interaction between some debuggers and the `System.Diagnostics.DiagnosticSourceEventSource` library when debugging on certain target frameworks.  This isn't something that the Azure SDK can detect or influence.

In this case, the recommended workaround is upgrading the diagnostics package to v6 or greater, which you've indicated that you're unable to do.  The alternative would be to consider upgrading your target framework to run against `net6.0` or `net7.0 which has been reported to resolve this issue for others.  We'd also strongly recommend doing so, as `netcoreapp2.2` reached end of life in December of 2019 and is no longer supported. _([ref](https://github.com/dotnet/announcements/issues/147/))_
