### ISSUE TITLE
[FEATURE REQ] Include Export-Api.ps1 as last step of dotnet build /t:GenerateCode

### ISSUE THREAD

**Issue by m-nash** [Azure/azure-sdk-for-net#36361]
### Library name

Autorest.Csharp

### Please describe the feature.

Current people need to both call `dotnet build /t:GenerateCode` and then afterwards call `Export-API.ps1`.  It is very easy to forget the second step and as a new customer its difficult to find this instruction in the sea of instructions in our [contributing.md](https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md).

We could add another step in the [GenerateCode target](https://github.com/Azure/autorest.csharp/blob/feature/v3/src/AutoRest.CSharp/build/CodeGeneration.targets#L37) to run this powershell script for you and eliminate this need to remember the extra step.

**Comment by heaths** [comment]
We should probably only consider this for DPGs. The manual use case is intentional to help prevent breaking changes, since breaking change validation further left on the REST APIs won't catch many SDK breaking changes, like changing a required property to an optional property e.g., `int` to `int?` after code generation.

Is there an easy way to tell if a library is a DPG? I thought so from my own experience, but perhaps you know off the top of your head.

Still, it seems we should have validation in place to check for breaking changes. Generally, any git deletions (sans any expected changes, like if an MVID is written to the API exports) from GA to GA should trigger a more thorough review. Previews should not, if there was some easy way to know if they are deleting from the last GA or previous preview (REST APIs do this, but have some open issues yet).

**Comment by m-nash** [comment]
Any breaking change should get caught by the build command since it runs back compat.  Any libraries not in GA will get an apiview added to the pr where we can validate the changes are expected.

We would need this for all in order to have the fully functional regen preview that can pass ci as long as any api changes are in non ga'd libraries.

**Comment by heaths** [comment]
> Any breaking change should get caught by the build command since it runs back compat.

I've never seen that. Too often, admittedly, I forget to run the script and the CI complains because of this script. It's catching what we failed to: either through forgetfulness or because we didn't realize a public signature changed.

**Comment by chunyu3** [comment]
> > Any breaking change should get caught by the build command since it runs back compat.
> 
> I've never seen that. Too often, admittedly, I forget to run the script and the CI complains because of this script. It's catching what we failed to: either through forgetfulness or because we didn't realize a public signature changed.

When the .csproj file set `<ApiCompatVersion>XXXX</ApiCompatVersion>`, the build command will check back compatibility. The script `Export-Api.ps1` does not do specific check for breaking change or back compatibility. But in azure-sdk-for-net, many SDK does not set `ApiCompatVersion`.

**Comment by heaths** [comment]
> But in azure-sdk-for-net, many SDKs do not set ApiCompatVersion.

It's only for track 2 SDKs, and only SDKs that have GA'd.
