### ISSUE TITLE
[FEATURE REQ] OpenAI: Stable 2023-05-15 Api and 2023-07-01-preview Api ersions

### ISSUE THREAD

**Issue by dasMulli** [Azure/azure-sdk-for-net#36442]
### Library name

Azure.AI.OpenAI

### Please describe the feature.

The OpenAI libraries should support the GA API Version 2023-05-15.

https://learn.microsoft.com/en-us/azure/cognitive-services/openai/whats-new#may-2023
> If you are currently using the 2023-03-15-preview API, we recommend migrating to the GA 2023-05-15 API.

Update: 2023-07-01-preview was also just merged and should also be supported by the .NET SDK

**Comment by PramodValavala-MSFT** [comment]
@dasMulli Thanks for the feedback! We have routed this to the owning team to address.

**Comment by dasMulli** [comment]
Do note 2023-07-01-preview was also just merged in https://github.com/Azure/azure-rest-api-specs/pull/24534

**Comment by trrwilson** [comment]
Thanks for reaching out! I'm happy to share that the new `beta.6` release of the library is now available and includes updates to support DALL-E image generation, chat functions, and Azure content filter annotations. Please note that the new features require updated model versions (0613 or newer) for the `gpt-35-turbo` and (if available) `gpt-4` model families.

https://www.nuget.org/packages/Azure.AI.OpenAI/1.0.0-beta.6

If you run into any issues, have questions, or want to provide feedback, please don't hesitate to file new issues here. I'll close this particular issue since we now do have those new capabilities appropriately reflected.

Thanks again!

**Comment by ADefWebserver** [comment]
I posted a C# example at: [Recursive Azure OpenAI Function Calling](https://blazorhelpwebsite.com/ViewBlogPost/10068)
