### ISSUE TITLE
ChatCompletions and CompletionsUsage have only internal constructors

### ISSUE THREAD

**Issue by rosebyte** [Azure/azure-sdk-for-net#36462]
### Library name

Azure.AI.OpenAI

### Provide a way to instantiate ChatCompletions and CompletionsUsage

Azure SDK clients, OpenAIClient in this case, are supposed to be mockable, however, the GetChatCompletionsAsync method returns a response containing ChatCompletions and CompletionsUsage instances, both lacking a way to be instantiated by customer (other than using reflection).

Please consider letting customers instantiate these types in their tests.

**Comment by jsquire** [comment]
Hi @rosebyte.  Thank you for reaching out and we regret that you're experiencing difficulties.  It appears that because Open AI is still in an early beta, it has not yet implemented the model factory required by the [Azure SDK Guidelines](https://azure.github.io/azure-sdk/dotnet_introduction.html#dotnet-mocking) which serve this purpose.

I've triaged this over to the team working on Open AI.

**Comment by bsstahl** [comment]
I also need this feature. I see there is progress in this direction for beta 6. I'm currently using a local version of this SDK with my own implementation to keep my project progressing in a testable way. If there's any way I can help move this effort forward, please let me know. I'm happy to PR or otherwise share what I did, but that is absolutely minimal at this point. Happy to do more if it would help speed things along.

Even having a stub of the factory implementation for those 2 objects would be beneficial, as it might save me from having to make extensive changes to my tests later on if the method signature is different from what I used. 

Thanks for your efforts!

**Comment by vandenbergjp** [comment]
I also encountered this. It would be nice if the model factory were available. For now, I worked around the problem using reflection based on this blog post: https://haacked.com/archive/2023/05/01/calling-internal-ctors/

**Comment by trrwilson** [comment]
Thanks for surfacing this issue. We just released the beta.6 version of the library and it includes a basic `AzureOpenAIModelFactory` to facilitate the intended pattern -- e.g. you can now use code like the following to manually instantiate an instance of `ChatCompletions` (including with a manually-instantiated `CompletionsUsage`):

```c#
            ChatCompletions chatCompletions = AzureOpenAIModelFactory.ChatCompletions(
                expectedId,
                expectedCreationTime,
                chatChoices,
                promptFilterResults,
                AzureOpenAIModelFactory.CompletionsUsage(2, 5, 7));
```
