### ISSUE TITLE
Additional properties not serialized/deserialized as JsonExtensionData in polymorphic classes.

### ISSUE THREAD

**Issue by hvermis** [Azure/azure-sdk-for-net#3648]
I'm trying to use dictionaries as a catch-all for unlisted properties as described at swagger docs https://github.com/Azure/autorest/blob/master/docs/developer/guide/defining-clients-swagger.md#dictionaries-as-a-catch-all-for-unlisted-properties and generate the C# SDK from it, but it doesn't seem to be working with polymorphic classes. I've tried adding the additionalProperties to the base class and inherited class, in both cases the new properties are getting dropped after deserialization and the AdditionalProperties member is null.  

Parent model:

    "ParentType": {
      "description": "Description of parent type",
      "discriminator": "type",
      "type": "object",
      "properties": {
        "type": {
          "type": "string",
          "description": "...."
        },
        "description": {
          "description": ".....",
          "type": "string"
        },
        ....... other properties
      },
      "additionalProperties": {
        "type": "object"
      }
       .......
    },

Inherited model:

    "InheritedType": {
              ......
      "description": " Description of inherited type",
      "type": "object",
      "allOf": [
        {
          "$ref": "#/definitions/ParentType"
        }
      ],
      "properties": {
              ....
      },
      "additionalProperties": {
        "type": "object"
      }
     .....
    }

**Comment by olydis** [comment]
@hvermis Just renamed this issue since the unit tests I added actually also uncovered that serialization doesn't work either (i.e. stuff in the additional properties dictionary does not make it on the wire).

@shahabhijeet FYI, polymorphic serialization never wrote out additional properties. It uses [this](https://github.com/Azure/azure-sdk-for-net/blob/psSdkJson6/src/SdkCommon/ClientRuntime/ClientRuntime/Serialization/JsonConverterHelper.cs#L74-L77) helper method which doesn't handle `JsonExtensionData` at all. Furthermore, what is the marked section about? Am I correct that this is a hard-coded realization of property flattening? However, that doesn't even make any sense since flattening means *creating* nesting at serialization time (stuff is flattened at *deserialization*).
