### ISSUE TITLE
Confusion on Microsoft.Rest.ClientRuntime.Azure.Authentication reference to ADAL library versions

### ISSUE THREAD

**Issue by nzthiago** [Azure/azure-sdk-for-net#3664]
We created a new Azure Function using the latest Visual Studio 2017 15.3.3 update; the Azure Function project has a target framework of .NET Framework 4.6.1, which implements .NET Standard 1.4.
We added a reference to Microsoft.Azure.Management.Dns.Fluent to the function project.

According to the comments here #2616 for netStandard 1.4 we use ADAL 3.13.5; but for us it only worked when we lowered Microsoft.IdentityModel.Clients.ActiveDirectory package back to v2.28.3, otherwise it failed saying "Microsoft.Azure.Management.ResourceManager.Fluent: Could not load file or assembly "Microsoft.IdentityModel.Clients.ActiveDirectory, version=2.28.3.860 ..."

**Comment by hovsepm** [comment]
This is by design. netstandards are only applicable to .Net Core. You cannot have a .Net 4.X project that targets .Net Standard 1.4.

**Comment by hovsepm** [comment]
Please check here - https://blogs.msdn.microsoft.com/dotnet/2016/09/26/introducing-net-standard/

**Comment by hovsepm** [comment]
adal 3.x does not support interactive login
but can be executed on Linux and MacOS
while adal 2.28 does support interactive login (aka popup that asks for credentials)
but is only Windows targeted

**Comment by hovsepm** [comment]
you created a project that is targeting .Net 4.X
if you create a .Net core project (and all your nugets have .Net Core support)
then you will be able to use latest ADAL

**Comment by aggieben** [comment]
@hovsepm 
> You cannot have a .NET 4.X project that targets .Net Standard 1.4

Firstly, this doesn't make sense - if a project is targeting net4x, then naturally that targeting profile can't also target netstardard1.4 _or any other target_.  That's what it means to target.

But if I read between the lines a little bit to try and understand what you meant, I _think_ you meant to say that net4x projects can't utilize packages that target netstardard1.4, and that's incorrect.  Any project targeting net461 or higher would be able to reference packages targeting netstandard1.4 (as described on the very page you linked).

The problem here is not that @nzthiago referenced a netstandard1.4 package from his project.  There are other open issues that describe the issue(s) in more detail (such as #3821).  I think @nzthiago is experiencing symptoms of this dependency issue.
