### ISSUE TITLE
call GetLongRunningOperationResultAsync with header "Azure-AsyncOperation" and get 200 immediately while the long running operation is still running in portal

### ISSUE THREAD

**Issue by wangcancan1996** [Azure/azure-sdk-for-net#36798]
### Library name and version

Microsoft.Rest.ClientRuntime.Azure 3.0.0.0

### Query/Question

I called IVirtualMachineScaleSetsOperations.BeginUpdateWithHttpMessagesAsync to scale out a VMSS, and I got a response of type AzureOperationResponse\<VirtualMachineScaleSetInner\>. Then I called IAzureClient.GetLongRunningOperationResultAsync with the header "Azure-AsyncOperation" got from above response, polling the scaling-out operation status. It returns 200 (OK) immediately while the scaling long running operation is still running.

But, when I send reimaging node request, and poll this long running operation status with header "Azure-AsyncOperation", I got 200 after reimaging really finished.

Then I tried polling scaling-out operation with header "Azure-AsyncOperation" as well as Request/Response.Content got from the AzureOperationResponse\<VirtualMachineScaleSetInner\>, then it worked fine, I got 200 after scaling really finished.

Is there something different in scaling operation?

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by HarveyLink** [comment]
Looks like a service issue.

**Comment by hilaryw29** [comment]
Hi @wangcancan1996, please see the following - https://github.com/AzureExpert/azure-resource-manager-rpc/blob/master/v1.0/Addendum.md

"**The operation resource should be used for Azure-AsyncOperation header.** Location header should have different behavior described above.

The status values are similar to provisioningState – the transient / intermediate values can be service specific; however, the terminal values can be one of (1) Succeeded, (2) Failed or (3) Canceled. All other values imply that the operation is still running / being applied.

**When reading the operation resource entity, the status code should always be 200. The response payload indicates if the async operation is still running or has completed (successfully or with a failure).**"

**Comment by wangcancan1996** [comment]
What dose "The operation resource should be used for Azure-AsyncOperation header." means?  

about "When reading the operation resource entity, the status code should always be 200", I will get 202 when polling "Azure-AsyncOperation" url for reimaging and deleting request. Sorry I haven't got why it's different for scaling request.

If possible, could you please provide me an example showing the correct way to polling the long running operation status for a scaling request?

thanks very much!

**Comment by hilaryw29** [comment]
Hi @wangcancan1996, please see the following response from our dev team:

There are two headers

"Azure-AsyncOperation": 

- it’s return the operation resource entity, the status code should always be 200. The response payload indicates if the async operation is still running or has completed (successfully or with a failure).

“location”:

- If the operation is not complete, return 202 (Accepted) again with Location header and optionally an updated Retry-After header.
- If the operation is complete, return the exact same response that would have been returned had the operation been executed synchronously.

The best way for tracking Azure-AsyncOperation is to look at **operation.status** in the response body return by “Azure-AsyncOperation”

Operation Resource format (returned by Azure-AsyncOperation header)
{
"id": "/subscriptions/id/locations/westus/operationsStatus/sameguid",
"name": "sameguid",
**"status" : "RP defined values | Succeeded | Failed | Canceled",**
...
}

Hope this helps!

**Comment by wangcancan1996** [comment]
Hi @hilaryw29, thanks for your response. I have 2 questions want to further confirm.
1. I got such Operation Resource contained in respose.content, when we say "looking at operation.status", it means properties.provisioningState in my case, right?
![image](https://github.com/Azure/azure-sdk-for-net/assets/44257910/902e7d9a-37f0-4a01-a247-f7895a99f56e)

2. If I get "Location" header as well as "Azure-AsyncOperation" header in one request, it's ok calling back either of them, right?

thanks!

**Comment by hilaryw29** [comment]
Hi @wangcancan1996 

**The Operation Resource is returned by polling on the url "Azure-AsyncOperation" header.** The image you shared is the response of PutVmss itself, that contains the VMSS resource. It is not the Operation Resource. 

For the operation resource (see step 3, from https://github.com/AzureExpert/azure-resource-manager-rpc/blob/master/v1.0/Addendum.md#create-update-id):

**Creating or Updating Resources (PUT/PATCH)**

The API flow should be to:
1. Respond to the initial PUT request with a 201 Created or 200 OK (per normal guidance);
2. Since provisioning is not complete, the PUT response body MUST contain a provisioningState set to a non-terminal value (e.g. "Accepted", or "Created");
3. **Optional** : The response headers may include a Azure-AsyncOperation header pointing to an Operation resource (as described below);
4. Future GETs on the resource that was created should continue to return a 200 Status Code and provisioningState field that is *non-terminal* as long as the provisioning is in progress;
5. After the provisioning completes, the provisioningState field should transition to one of the terminal states (as described below).
6. The provisioningState field should be returned on all future GETs, even after it is complete, until some other operation (e.g. a DELETE or UPDATE) causes it to transition to a non-terminal state.

Regarding the two headers:
The "Location" and "Azure-AsyncOperation" header will have different behaviours.

Location headers: https://github.com/AzureExpert/azure-resource-manager-rpc/blob/master/v1.0/Addendum.md#location-id

Azure-Async Operation headers: https://github.com/AzureExpert/azure-resource-manager-rpc/blob/master/v1.0/Addendum.md#operation-id

Thanks!

**Comment by wangcancan1996** [comment]
Thanks a lot @hilaryw29 !
