### ISSUE TITLE
[BUG] : After adding TxtRecord in AzureDnsZone, AcmeChallinge is failing to validate Resource

### ISSUE THREAD

**Issue by shivamkdi07** [Azure/azure-sdk-for-net#36808]
### Library name and version

Azure.ResourceManager.Dns: 1.0.1

### Describe the bug

Steps:-
1. Creating a acmeContext
2. Create a txtrecord in azure dns zone
3. Get AzureDnsZone txt record (this is giving correct records while dns progapgation is still happening)
4. Validating acme and getting resource
5. deleting txt record

Below are the errors that i am getting :- 
[09:04:39 INF] Creating DNS record _acme-challenge.abcd.sudomain
[09:04:40 INF] DNS record propagation verifiation is completed
[09:04:40 ERR] DNS challenge validation failed: DNS problem: NXDOMAIN looking up TXT for _acme-challenge.abcd.sudomain - check that a DNS record exists for this domain
[09:04:40 INF] Deleting DNS record _acme-challenge.abcd.sudomain

Reason for Error logs -
While Dns Propagation is taking time in Azure DNS Server, Acme Validation is failing to fetch that txt record details from dns server.

### Expected behavior

Step 3 should give resould only when Txt record is propagated in respective Azure Dns Server

### Actual behavior

Step 3 is giving correct records while dns propagation is still happening

### Reproduction Steps

Steps:-
1. Creating a acmeContext
2. Create a txtrecord in azure dns zone
3. Get AzureDnsZone txt record (this is giving correct records while dns progapgation is still happening)
4. Validating acme and getting resource
5. deleting txt record

Don't use break points otherwise you won't be able to reproduce it

### Environment

Kubernetes
.Net6

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by HarveyLink** [comment]
Hey @shivamkdi07  , thank you for reaching out to us about the Azure SDK for .NET. Unfortunately, this issue is related to the service side and not the SDK side, so we are not able to help you with it. Therefore, we are closing this issue for now. If you need more assistance, please [open an Azure support request](https://docs.microsoft.com/azure/azure-portal/supportability/how-to-create-azure-support-request). We apologize for any inconvenience this may cause you.

We value your feedback and we want to make sure that your problem is solved. If you think that we have misunderstood your issue or closed it incorrectly, please feel free to comment on this thread and reopen the issue. We will be happy to assist you further. Thank you for your understanding and cooperation.
