### ISSUE TITLE
[QUERY] ShareFileClient.StartCopyAsync extremely slow

### ISSUE THREAD

**Issue by Lann094** [Azure/azure-sdk-for-net#36837]
### Library name and version

Azure.Storage.Files.Shares 12.12.1

### Query/Question

We're struggling with massive slowness of simple copy operations between storage accounts. We store files in blobs and copy them to file shares upon request from the application, and this operation is far too slow to be feasible for on-demand access.

Doing a simple `azcopy copy` can see the operation done in hundreds of milliseconds, but utilising `StartCopyAsync`, then polling `GetPropertiesAsync` to monitor when `CopyStatus` moves to `CopyStatus.Success` can see the process take up to minutes for files just >50 MB.

What can we do to optimise this interaction? The application is running in Azure on Kubernetes in the same region.

**Comment by navba-MSFT** [comment]
@Lann094 Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment]
@Lann094 I see that you are using [CloudBlockBlob.StartCopyAsync() ](https://learn.microsoft.com/en-us/dotnet/api/microsoft.azure.storage.blob.cloudblockblob.startcopyasync?view=azure-dotnet)which is part of the v11 deprecated package.

Please note, this package was officially deprecated on 3/31/2023 and is no longer maintained or monitored. The Azure SDK team encourages you to upgrade to the replacement package, **_Azure.Storage.Blobs_**, to continue receiving updates. Refer to the migration guide (https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/storage/Azure.Storage.Blobs/AzureStorageNetMigrationV12.md) for guidance on upgrading.

More info about Azure.Storage.Blobs: https://www.nuget.org/packages/Azure.Storage.Blobs/12.16.0

You can leverage the [BlobBaseClient.StartCopyFromUriAsync Method ](https://learn.microsoft.com/en-us/dotnet/api/azure.storage.blobs.specialized.blobbaseclient.startcopyfromuriasync?view=azure-dotnet)instead. Sample code is [here](https://learn.microsoft.com/en-us/azure/storage/blobs/storage-blob-copy-async-dotnet).

Also please follow the [performance checklist ](https://learn.microsoft.com/en-us/azure/storage/blobs/storage-performance-checklist)for optimizing the Storage performance.

**Comment by Lann094** [comment]
Hi @navba-MSFT, we're very much not using the old library, nor copying to blob. I'm talking about this method: https://github.com/Azure/azure-sdk-for-net/blob/ed2a68611b2fa3e0908a7d3746058fe4a6e06836/sdk/storage/Azure.Storage.Files.Shares/src/ShareFileClient.cs#L1327 
for file shares. We're generating a URI of the blob to be copied, and feeding it into the above method.

**Comment by navba-MSFT** [comment]
Adding Service team to look into this further and provide pointers.

@amnguye @seanmcc-msft for visibility.

**Comment by amnguye** [comment]
What's the full azcopy command you are using to copy blobs to a file share?

**Comment by Lann094** [comment]
We verified using `AzCopy copy <blob uri> <file uri>`.

**Comment by amnguye** [comment]
So the reason why there's a speed difference is because you're using a different REST API.

`StartCopyAsync`(https://learn.microsoft.com/en-us/dotnet/api/azure.storage.files.shares.sharefileclient.startcopyasync?view=azure-dotnet) is using the [Copy File REST API](https://learn.microsoft.com/en-us/rest/api/storageservices/copy-file).

While the default copy Blob to Share File AzCopy command is using the [Put Range From URL](https://learn.microsoft.com/en-us/rest/api/storageservices/put-page-from-url?tabs=azure-ad) which in the .NET SDK is [UploadRangeFromUriAsync](https://learn.microsoft.com/en-us/dotnet/api/azure.storage.files.shares.sharefileclient.uploadrangefromuriasync?view=azure-dotnet).

While we cannot guarantee matching performance between Azcopy and the SDK as they are two different products, I believe you can get closer to your expected performance if you used the [UploadRangeFromUriAsync](https://learn.microsoft.com/en-us/dotnet/api/azure.storage.files.shares.sharefileclient.uploadrangefromuriasync?view=azure-dotnet) API instead.

**Comment by Lann094** [comment]
Thanks @amnguye, this might have been the needle in the haystack. I'm seeing really positive results in initial testing, but will report back once we're tested and deployed.

The speed is orders of magnitude in difference. I seriously wonder whether the Copy File endpoint is fit for purpose at all.

**Comment by amnguye** [comment]
Ah just ignore the bot. I just marked it with needs author feedback awaiting your results.

**Comment by Lann094** [comment]
We got this fix pushed to prod and after monitoring throughout the day yesterday, can see huge reductions in wait times. 

I really question what the other method is doing, because even copies of files below the 4MB chunk size are moving so much quicker. 

Thanks again @amnguye, you were a massive help!
