### ISSUE TITLE
[BUG] : KeyClient class Getting certificates when asking for keys

### ISSUE THREAD

**Issue by Ichigo1705** [Azure/azure-sdk-for-net#37004]
### Library name and version

Azure.Security.KeyVault.Keys (version 4.5.0)

### Describe the bug

I am trying to use the KeyClient class present under this library to access the Keys present in my Key Vault.
Here I have a key vault under my Visual Studio Enterprise Subscription with vault uri as given in the code.
The problem is that I am not only getting the key names but also the certificate names 
where cert1 and cert2 are certificates and key1 and key2 are the required keys

### Expected behavior

The output should be
```text
Key1
Key2
```

### Actual behavior

Getting the output

```text
cert1
cert2
Key1
Key2
````

### Reproduction Steps

```csharp
using Azure.Security.KeyVault.Keys;
using Azure.Core;
using Azure.Identity;
using System.Threading;

internal class Program
{
    private static void Main(string[] args)
    {
        TokenCredential credential = new DefaultAzureCredential();
        KeyClient key = new KeyClient(new Uri("https://XX.vault.azure.net/"), credential);
        Azure.Pageable<KeyProperties> allkeys = key.GetPropertiesOfKeys();
        foreach(KeyProperties Key in allkeys)
        {
            Console.WriteLine(Key.Name);
        }
        //Console.WriteLine(key.ToString());
    }
}
```

### Environment

Os: Windows 11
.NET Framework: 6.0(Long term Support
IDE: Visual Studio Community version 17.6.1

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by heaths** [comment]
This is by design. Private key material for both keys and certificates are stored as secrets. To filter these out, you should check [`KeyVaultSecret.Properties.Managed`](https://learn.microsoft.com/dotnet/api/azure.security.keyvault.secrets.secretproperties.managed). There are scenarios when getting managed secrets are necessary so, like the service we call into, we always return them. Same with disabled secrets, which you can also filter out in your implementation.
