### ISSUE TITLE
Autorest PCL Support

### ISSUE THREAD

**Issue by DavidStrickland0** [Azure/azure-sdk-for-net#3703]
Reposted from https://github.com/Azure/autorest/issues/2584

The Microsoft.Rest.ClientRuntime. project appears to have dropped PCL support. The last version that supports PCL being 2.3.6. Unfortunately 2.3.6 also restricts the NewtonSoft Version >=9 but <10.

With Autorest relying on the ClientRuntime and the ClientRuntime PCL support deprecated and locked into a specific version of Newtonsoft. AutoRest no longer supports generating code for use in a PCL unless you want to permenently lock into a sunsetting version of Newtonsoft. Not sure if this is an issue or by intent but couldnt find any other discussions on the topic nor any annoucement that Autorest and the ClientRuntime is deprecating PCL support.

**Comment by DavidStrickland0** [comment]
What more information did you want? You've dropped PCL support. I need PCL support. Not sure what else to say.

**Comment by Petermarcu** [comment]
Hi @DavidStrickland0, I'm really sorry you didn't get a meaningful response here. Lots of time has passed since you opened this and PCL's in .NET have gotten more and more deprecated in many tools. Is this still an issue for you or have you been able to move to .NET Standard in general? I saw your other comments in the original bug and it sounded like you were moving to .NET Standard. I'm going to close this issue for now. In future versions of the Azure SDK for .NET we intend to remove the Json.NET dependency so this won't be an issue.

**Comment by DavidStrickland0** [comment]
In the end we just dropped Auto Rest entirely. Between the Json.Net issue coupled with the size of the class files Autorest created and the lack of the configurability we needed. We just used Roslyn and wrote our own generator. Thanks for the reply though.
