### ISSUE TITLE
Unable to set specific version of azure-sdk-for-net when running preview pipeline

### ISSUE THREAD

**Issue by pshao25** [Azure/azure-sdk-for-net#37033]
Before this [refactor](https://github.com/Azure/autorest.csharp/pull/3284), if I want to review my change in azure-sdk-for-net, I could do:
1. Go to [Autorest Regen Preview](https://dev.azure.com/azure-sdk/internal/_build?definitionId=5990&_a=summary).
2. When starting a new one, click resources and choose azure-sdk-for-net, type in the commit number that I want to test.

But now I couldn't because of this [line](https://github.com/Azure/autorest.csharp/blob/7261181993f1b4693c03e18d9965c73a1c116189/eng/pipelines/update-azure-sdk-for-net-codes.yml#L25-L33).

**Comment by pshao25** [comment]
@mikeharder @hallipr would you help on this?

**Comment by hallipr** [comment]
Syncing with @m-nash on the desired method for testing against non-main branches of azure-sdk-for-net

**Comment by chunyu3** [comment]
We have met with a senario:  The customized code of a SDK is not valid for the new version of spec, the codegen will fail to generate the SDK, such as there is model name changed in new spec, but in the customize code, it still use the previous model name, codegen will fail. In order to resolve this, we need to update the customized code in a branch and let regen to run on this specific branch.
