### ISSUE TITLE
[BUG] Can't set PrecalculatedChecksum - "Precalculated checksum not supported when potentially partitioning an upload."

### ISSUE THREAD

**Issue by ayeltsov** [Azure/azure-sdk-for-net#37086]
### Library name and version

Azure.Storage.Blobs 12.16.0

### Describe the bug

Could be me missing important bit in documentation, but I searched docs, stackoverflow and source code and I can't see the solution. Decided to start as bug report.

Goal: upload block blob from stream, with purposefully incorrect precalculated MD5, and get expected error that hash is incorrect.

Looking at the code, we throw this error before attempting to determine if the blob can be uploaded in one operation (and supplying checksum would actually be valid).

### Expected behavior

Failure to upload blob due to incorrect MD5

### Actual behavior

System.ArgumentException
  HResult=0x80070057
  Message=Precalculated checksum not supported when potentially partitioning an upload.
  Source=Azure.Storage.Blobs
  StackTrace:
   at Azure.Storage.PartitionedUploader`2..ctor(Behaviors behaviors, StorageTransferOptions transferOptions, UploadTransferValidationOptions transferValidation, ArrayPool`1 arrayPool, String operationName)
   at Azure.Storage.Blobs.Specialized.BlockBlobClient.GetPartitionedUploader(StorageTransferOptions transferOptions, UploadTransferValidationOptions validationOptions, ArrayPool`1 arrayPool, String operationName)
   at Azure.Storage.Blobs.Specialized.BlockBlobClient.<UploadAsync>d__30.MoveNext()
<user code>

### Reproduction Steps

```
            BlobContainerClient containerClient = new BlobContainerClient(new Uri("https://127.0.0.1:10000/devstoreaccount1/container-name"), new DefaultAzureCredential());

            BlockBlobClient blobClient = containerClient.GetBlockBlobClient("test.bin");

            BlobUploadOptions options = new BlobUploadOptions()
            {
                TransferValidation = new UploadTransferValidationOptions() { ChecksumAlgorithm = StorageChecksumAlgorithm.MD5, PrecalculatedChecksum = Convert.FromBase64String("BadChecksum="), },
                //TransferOptions = new StorageTransferOptions() { MaximumConcurrency = 1 },
            };

            MemoryStream stream = new System.IO.MemoryStream(Encoding.UTF8.GetBytes("Hello, World!"));
            await blobClient.UploadAsync(stream, options, cancellationToken: CancellationToken.None); // <-- exception here
```

### Environment

Win 11, 8.0.100-preview.3.23178.7, VS 2022 (Version 17.6.0 Preview 4.0)

**Comment by ayeltsov** [comment]
While I'd like this to work with Stream, same issue reproes with arguably simpler BinaryData upload (simpler because upload length is known).

**Comment by navba-MSFT** [comment]
Adding Service team to look into this.

**Comment by jaschrep-msft** [comment]
Hi @ayeltsov thanks for reaching out.

While you're correct that the invocation you use can technically make use of a precalculated MD5, it creates a situation where the calling code can continue to function as normal with varying sizes of data until one day they breach the single upload threshold and the argument becomes invalid. With a default threshold of 256 MiB, it's easy to imagine an application testing with data sizes of lower value, then pushing to production where a file larger than this threshold is provided and suddenly there are production failures.

However, this limitation is due to the non-composable nature of MD5. Were you to use the CRC checksum mechanism in the library, this would not be an issue you would encounter in the first place due to the composable nature of CRC values. Additionally, CRC is a more performant algorithm than MD5. With all these benefits, we recommend moving over.

**Comment by ayeltsov** [comment]
Thank you @jaschrep-msft for looking into this. 
Replying to your points:
- on size of the blob: 
   our client controls the blob size with chunking algorithm, this is not a concern in this scenario
- on "use the CRC checksum mechanism"
   I get same same exception with `ChecksumAlgorithm = StorageChecksumAlgorithm.StorageCrc64`, can you please expand on proposal ?

**Comment by jaschrep-msft** [comment]
> our client controls the blob size with chunking algorithm, this is not a concern in this scenario
I'm not sure this addresses our rationale of "it only works until one day the number its handed is too big." It's just so easy to suddenly tip over the edge in production without realizing the edge even existed.

> I get same same exception with `ChecksumAlgorithm = StorageChecksumAlgorithm.StorageCrc64`
That is not intentional. Can you please resupply a snippet invoking the upload and producing the exception with `StorageChecksumAlgorithm.StorageCrc64`?

**Comment by ayeltsov** [comment]
> I'm not sure this addresses our rationale of "it only works until one day the number its handed is too big." It's just so easy to suddenly tip over the edge in production without realizing the edge even existed.

I probably should have been clearer about chunking algorithm - it has strict max chunk size and guaranteed not to exceed a tested predefined threshold. 

> Can you please resupply a snippet invoking the upload and producing the exception with `StorageChecksumAlgorithm.StorageCrc64`?

Here we go:

```
            BlobContainerClient containerClient = new(
                connectionString: "UseDevelopmentStorage=true;",
                blobContainerName: "container");

            containerClient.CreateIfNotExists();

            BlobClient blobClient = containerClient.GetBlobClient(blobName: "test.txt");

            BlobUploadOptions options = new()
            {
                TransferValidation = new UploadTransferValidationOptions()
                {
                    ChecksumAlgorithm = StorageChecksumAlgorithm.StorageCrc64,
                    PrecalculatedChecksum = new byte[] {01, 02, 03, 04},
                },
            };

            byte[] content = "Hello, World!"u8.ToArray();
            blobClient.Upload(new MemoryStream(content), options); // <- exception here 
```

Exception:

```
Unhandled exception. System.ArgumentException: Precalculated checksum not supported when potentially partitioning an upload.
   at Azure.Storage.PartitionedUploader`2..ctor(Behaviors behaviors, StorageTransferOptions transferOptions, UploadTransferValidationOptions transferValidation, ArrayPool`1 arrayPool, String operationName)
   at Azure.Storage.Blobs.Specialized.BlockBlobClient.GetPartitionedUploader(StorageTransferOptions transferOptions, UploadTransferValidationOptions validationOptions, ArrayPool`1 arrayPool, String operationName)
   at Azure.Storage.Blobs.BlobClient.GetPartitionedUploader(StorageTransferOptions transferOptions, UploadTransferValidationOptions validationOptions, ArrayPool`1 arrayPool, String operationName)
   at Azure.Storage.Blobs.BlobClient.StagedUploadInternal(Stream content, BlobUploadOptions options, Boolean async, CancellationToken cancellationToken)
   at Azure.Core.Pipeline.TaskExtensions.EnsureCompleted[T](Task`1 task)
   at Azure.Storage.Blobs.BlobClient.Upload(Stream content, BlobUploadOptions options, CancellationToken cancellationToken)
```

**Comment by ayeltsov** [comment]
Confirmed this is working on 12.17. 
In P.S. there's a sample in case someone stumbles over this thread.

@jaschrep-msft - feel free to resolve but maybe check if any doc follow-up tasks are needed and worth investment.
I was trying to find my way with documentation and it was challenging.

P.S. This code follows @jaschrep-msft 's suggestion:

```

            // Did not work with emulator
            BlobContainerClient containerClient = await GetRealBlobContainerClient();

            BlobClient blobClient = containerClient.GetBlobClient(blobName: "test.txt");

            byte[] content = "Hello, World!"u8.ToArray();

            StorageCrc64HashAlgorithm crc64 = StorageCrc64HashAlgorithm.Create();
            crc64.Append(content);

           BlobUploadOptions options = new()
            {
                TransferValidation = new UploadTransferValidationOptions()
                {
                    ChecksumAlgorithm = StorageChecksumAlgorithm.StorageCrc64,
                    PrecalculatedChecksum = crc64.GetCurrentHash(),
                },
            };

            blobClient.Upload(new MemoryStream(content), options);
```

**Comment by jaschrep-msft** [comment]
Looking at the [docs for `BlobUploadOptions.TransferValidation`](https://learn.microsoft.com/en-us/dotnet/api/azure.storage.blobs.models.blobuploadoptions.transfervalidation):

> This operation does not allow [PrecalculatedChecksum](https://learn.microsoft.com/en-us/dotnet/api/azure.storage.uploadtransfervalidationoptions.precalculatedchecksum?view=azure-dotnet#azure-storage-uploadtransfervalidationoptions-precalculatedchecksum) to be set.

Additionally, the [docs for the precalculated checksum property](https://learn.microsoft.com/en-us/dotnet/api/azure.storage.uploadtransfervalidationoptions.precalculatedchecksum) state:

> Not all upload APIs can use this value, and will throw if one is provided. Please check documentation on specific APIs for whether this can be used.

@ayeltsov I think these docs do explain the trouble you were having, and they appear to be unchanged across versions since their introduction. However, it does look like the latest version should be updated to state that the property can be used if using CRC. I've filed #37882 to update that. Otherwise, I think this issue is resolved.
