### ISSUE TITLE
[BUG] SDK exception thrown despite 202 response

### ISSUE THREAD

**Issue by rwwsysdev** [Azure/azure-sdk-for-net#37116]
### Library name and version

Azure.ResourceManager.AppService

### Describe the bug

Calling **CreateOrUpdate** to create a new App Service Certificate on **AppCertificateCollection** throws an exception, despite success.
The remote call returns a HTTP 202 indicating success, and the certificate is created, however an exception is thrown by the SDK because the HTTP status is not 200.

### Expected behavior

No exception be thrown in response to a HTTP 202.

### Actual behavior

An exception is thrown:

```
Azure.RequestFailedException: 'Service request failed.
Status: 202 (Accepted)
```

### Reproduction Steps

``` 
AppCertificateCollection certCollection = resourceGroupResource.GetAppCertificates();

            string name = "dev.dev.uk";

            AppCertificateData data = new AppCertificateData(myWebsite.Data.Location)
            {
                CanonicalName = name,
                HostNames = { name },
                ServerFarmId = myWebsite.Data.AppServicePlanId
            };

            var certResult = certCollection.CreateOrUpdate(WaitUntil.Started, name, data);
```

### Environment

Dotnet7, Visual Studio 17.6.3, Windows 11, debugging in IDE.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by dvbb** [comment]
It is a service issue
![image](https://github.com/Azure/azure-sdk-for-net/assets/61542202/2ade6f6a-357f-4c11-9e3b-3ccbbb70a47e)
The [service side](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/web/resource-manager/Microsoft.Web/stable/2022-09-01/Certificates.json#L188) should return 200 or handle 202 status.

**Comment by ArthurMa1978** [comment]
This issue is related to the service side and not the SDK side, so we are not able to help you with it. Therefore, we are closing this issue for now. If you need more assistance, please [open an Azure support request](https://docs.microsoft.com/azure/azure-portal/supportability/how-to-create-azure-support-request). We apologize for any inconvenience this may cause you.

We value your feedback and we want to make sure that your problem is solved. If you think that we have misunderstood your issue or closed it incorrectly, please feel free to comment on this thread and reopen the issue. We will be happy to assist you further. Thank you for your understanding and cooperation.
