### ISSUE TITLE
[QUERY] Using DefaultAzureCredential to get PBI access token

### ISSUE THREAD

**Issue by mWekking** [Azure/azure-sdk-for-net#37144]
### Library name and version

using Azure.Identity 1.9.0

### Query/Question

Currently I pick up a acces token in the following way:

`AuthenticationResult authenticationResult = null;`
`var authenticationContext = new AuthenticationContext(authorityUrl + $"{TenantId.Trim()}");` 
`var credential = new ClientCredential($"{SPId}", $"{SPSecret}");`
`authenticationResult = authenticationContext.AcquireTokenAsync(resourceUrl, credential).Result;`
`return authenticationResult;`

with 
authorityUrl = https://login.microsoftonline.com/common/
TenantId = xxxxxx-xxxx-xxxx-xxxxx-xxxxxxxx (in form of)
SPId = xxxxxx-xxxx-xxxx-xxxxx-xxxxxxxx (in form of)
SPSecret = xxxxxxxxxxxxxxxxxxx= (in form of)
resourceUrl= https://analysis.windows.net/powerbi/api

Within the new company regulations I cant no longer connect via this way and need to connect via ManagedIdentites.

In order to do this I wanted to make use of `DefaultAzureCredential()` 

With the following code:
`var tokenCredential = new DefaultAzureCredential();` 
`var tokenContext = new TokenRequestContext( scopes: new string[] { resourceUrl });` 
`var accessToken = await tokenCredential.GetTokenAsync(tokenContext);` 

I do get a token back but if I try to connect to the PBI reports, I get a 401 not authorised error and I dont understand why.

Do I need to add the authorityUrl and TenentId somewhere? If so, where or why not? 
I cant find an example where this connection to PBI is made so I am really stuck here..

### Environment
ASP.NET 
WEBAPP

**Comment by jsquire** [comment]
Hi @mWekking.  Thank you for reaching out and we regret that you're experiencing difficulties.  Typically, the behavior that you're describing occurs when `DefaultAzureCredential` chooses a credential type that you weren't expecting, which causes the corresponding token to belong to an identity without permissions to the service.   [This section](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/identity/Azure.Identity/TROUBLESHOOTING.md#troubleshoot-defaultazurecredential-authentication-issues) of the Troubleshooting guide describes how to inspect which credential was chosen.  In this scenario, since you know that you'd like to use a managed identity, you may wish to explicitly use [ManagedIdentityCredential](https://learn.microsoft.com/dotnet/api/azure.identity.managedidentitycredential?view=azure-dotnet) directly.  Additional discussion and examples for `ManagedIdentityCredential` can be found [here](https://github.com/Azure/azure-sdk-for-net/tree/main/sdk/identity/Azure.Identity#managed-identity-support).

Unfortunately, there is no assistance that we can provide for PowerBI reports; if it turns out that you are using the expected identity and still seeing as unauthorized, your best path forward would be to open an Azure support request](https://docs.microsoft.com/azure/azure-portal/supportability/how-to-create-azure-support-request).
