### ISSUE TITLE
[FEATURE REQ] Support for the latest Open AI service version

### ISSUE THREAD

**Issue by zhuxingke** [Azure/azure-sdk-for-net#37200]
### Library name

Azure.AI.OpenAI 1.0.0-beta.5

### Please describe the feature.

hello,mate. i  found that the latested version had been updated.
https://learn.microsoft.com/en-us/azure/cognitive-services/openai/whats-new
now the latested version is '2023-05-15'.
expect your pull。

**Comment by trrwilson** [comment]
Hello! Thanks for reaching out. as @dasMulli mentioned, the feature set for the `2023-07-01-preview` service API recently reached full availability and we've now updated the SDK libraries to include new capabilities; beta 6 includes Image Generation, Chat Functions, and Chat Completions Content Filter Annotations: https://www.nuget.org/packages/Azure.AI.OpenAI/1.0.0-beta.6

As we're still releasing our libraries with a `prerelease` tag to iterate quickly and improve based on feedback, we currently snap to new, corresponding service API preview versions. Though you can configure the library to use the `2023-05-15` (non-preview) API version, it won't support the same feature set as `-preview` and may exhibit behavioral differences as a result.

Please share any feedback or questions with us via new issues! I'll close this one since the new versions are now (at last!) reflected in the libraries.
