### ISSUE TITLE
[Question] Large additional financial cost due to useless logs

### ISSUE THREAD

**Issue by Shazhko-Artem** [Azure/azure-sdk-for-net#37258]
### Library name and version

Azure.Messaging.ServiceBus 7.15.0

### Query/Question

Could you please explain why in the class [`ServiceBusRetryOptions`](https://github.com/Azure/azure-sdk-for-net/blob/Azure.Messaging.ServiceBus_7.5.0/sdk/servicebus/Azure.Messaging.ServiceBus/src/Primitives/ServiceBusRetryOptions.cs#L14) the property [`TryTimeout`](https://github.com/Azure/azure-sdk-for-net/blob/Azure.Messaging.ServiceBus_7.5.0/sdk/servicebus/Azure.Messaging.ServiceBus/src/Primitives/ServiceBusRetryOptions.cs#L98C25-L114) has a [check ](https://github.com/Azure/azure-sdk-for-net/blob/Azure.Messaging.ServiceBus_7.5.0/sdk/servicebus/Azure.Messaging.ServiceBus/src/Primitives/ServiceBusRetryOptions.cs#L111)that does not allow us to specify the value `TimeSpan.MaxValue`? Are there any reasons that do not allow us to turn off this timer for _Azure.Messaging.ServiceBus_? I would be very grateful if you give an example of when disabling the timer can lead to unpleasant consequences, this example will help a lot in understanding and we can use your package more correctly.

The fact is that _Azure.Messaging.ServiceBus_ uses [_Microsoft.Azure.Amqp_](https://github.com/Azure/azure-amqp) in which there are two options for initializing the message processing pipeline: by [timer ](https://github.com/Azure/azure-amqp/blob/aa887d026f903d408402e6c6e64c300d75595acd/Microsoft.Azure.Amqp/Amqp/ReceivingAmqpLink.cs#L829-L835)and by [signal](https://github.com/Azure/azure-amqp/blob/aa887d026f903d408402e6c6e64c300d75595acd/Microsoft.Azure.Amqp/Amqp/ReceivingAmqpLink.cs#L797-L800). Every time the timer expires, a message processing pipeline is started for each consumer, even if there are no messages in the queue, which as a result leads to a lot of meaningless logs inside _ApplicationInsights_. In _Microsoft.Azure.Amqp_ i[t is possible to disable the timer](https://github.com/Azure/azure-amqp/blob/aa887d026f903d408402e6c6e64c300d75595acd/Microsoft.Azure.Amqp/Amqp/ReceivingAmqpLink.cs#L717-L723), for this, you just need to specify the `TimeSpan.MaxValue` value. By default, the timer is set to 1 minute, so one log is created every minute for each consumer. If the project has 100 consumers, then every minute there will be 100 extra logs, 6 000 in one hour, 144 000 in one day, 4 320 000 in a month... This is an insane amount that requires additional financial costs. Changing the timer to 1 hour doesn't solve the problem, only slightly lessens it.

Since we have a very large project on SOA architecture, we have tens and hundreds of consumers, so this is a serious problem for us.

I made a [small test project](https://github.com/Shazhko-Artem/ServiceBus-Timer-Issue/tree/main) that you can use to reproduce the problem. You just need to run it, wait 5-10 minutes and you will see such a bunch of logs.

![image](https://github.com/Azure/azure-sdk-for-net/assets/31850295/b1ac9e7e-1c53-496a-b4f3-71bf174743c7)

### Environment

Windows 11 (10.0.22621)
dotnet SDK 6.0.410
Microsoft.ApplicationInsights.AspNetCore 2.22.0-beta3 (reproduced in all versions)

**Comment by jsquire** [comment]
Hi @Shazhko-Artem.  Thank you for reaching out and we regret that you're experiencing difficulties.   The `TryTimeout` governs a single service operation, none of which the service itself would permit to run for forever.  Can you please help us understand what service call you're making that you believe would take more than an hour to complete?

**Comment by Shazhko-Artem** [comment]
Hi @jsquire. Thank you very much for your prompt reply. I found only one way to change the timer in the class [`ReceiveAsyncResult`](https://github.com/Azure/azure-amqp/blob/aa887d026f903d408402e6c6e64c300d75595acd/Microsoft.Azure.Amqp/Amqp/ReceivingAmqpLink.cs#L717-L723)  using package _Azure.Messaging.ServiceBus_ functionality. As I wrote above, this is through the [`ServiceBusRetryOptions`](https://github.com/Azure/azure-sdk-for-net/blob/Azure.Messaging.ServiceBus_7.5.0/sdk/servicebus/Azure.Messaging.ServiceBus/src/Primitives/ServiceBusRetryOptions.cs#L14) class. Here is an example of how I changed the value of the timer from 1 minute to 1 hour in my example, but unfortunately I cannot specify the value `TimeSpan.MaxValue` to disable this timer, because I get a validation error inside your package.

**Comment by Shazhko-Artem** [comment]
@jsquire sorry for the misunderstanding. I understand what you mean. Let me give you more details about the actual situation we are facing and how we are using your package. We use [_MassTransit_](https://github.com/MassTransit/MassTransit) which already encapsulates all the queuing logic and directly uses _Azure.Messaging.ServiceBus_. In any scenario using _MassTransit_, we get extra logs. We have made an analysis and found out the cause of the problem and one of the options for how it can be solved.

The reason for the problem is the following. In _MassTransit_, the class [`ConnectionContextFactory `](https://github.com/MassTransit/MassTransit/blob/develop/src/Transports/MassTransit.Azure.ServiceBus.Core/AzureServiceBusTransport/ConnectionContextFactory.cs#L58-L101)is responsible for creating and configuring the `ServiceBusClient`. [Here ](https://github.com/MassTransit/MassTransit/blob/develop/src/Transports/MassTransit.Azure.ServiceBus.Core/AzureServiceBusTransport/ConnectionContextFactory.cs#L58-L68)you can see that they don't specify a value for [`TryTimeout`](https://github.com/Azure/azure-sdk-for-net/blob/Azure.Messaging.ServiceBus_7.5.0/sdk/servicebus/Azure.Messaging.ServiceBus/src/Primitives/ServiceBusRetryOptions.cs#L98C25-L114) at all, so the default value of one minute is used. I am going to open an issue for them and make a PR to add the ability to specify `TryTimeout`, but before that, I raised a ticket in [azure-amqp](https://github.com/Azure/azure-amqp/issues/249) to understand what this timer is for and raised a ticket here to understand why you have a validation that does not allow you to disable this timer (to disable the timer, I need to specify the value `TimeSpan.MaxValue` since the value from the `ServiceBusRetryOptions.TryTimeout` property is passed through the call chain to the [`ReceiveAsyncResult`](https://github.com/Azure/azure-amqp/blob/aa887d026f903d408402e6c6e64c300d75595acd/Microsoft.Azure.Amqp/Amqp/ReceivingAmqpLink.cs#L717-L723) class by the `timeout` parameter).

Earlier, I just wanted to provide an isolated code example that demonstrates that the problem is not related to _MassTransit_ and is reproduced already in the _Azure.Messaging.ServiceBus_ package itself. But if you need a usage scenario, then, as I said above, you can look it up in the [`ConnectionContextFactory`](https://github.com/MassTransit/MassTransit/blob/develop/src/Transports/MassTransit.Azure.ServiceBus.Core/AzureServiceBusTransport/ConnectionContextFactory.cs#L58-L101) class of the _MassTransit_ package.

Let me know if you need any more information, I will be happy to provide it as soon as possible.

**Comment by jsquire** [comment]
Thanks for the additional context, @Shazhko-Artem.  I think I'm now seeing the end-to-end picture.   

- The screenshot that you've shared are diagnostic spans being emitted, not SDK logs.
- The client type performing receives is a `ServiceBusProcessor`, which is doing its job and continually polling for messages.
- Each receive operation emits diagnostic spans that AI is pulling in.
- You're seeing a volume of spans that you'd like to reduce.

The operation timeout isn't the right way to do this, as it exists to govern all service operations - none of which should run indefinitely.  When receiving messages, there is a [maxWaitTime](https://learn.microsoft.com/dotnet/api/azure.messaging.servicebus.servicebusreceiver.receivemessageasync?view=azure-dotnet#parameters) parameter that is used for "How long should I wait for a message to be avaialble".   This has no upper bound and governs the time for a single receive.   The `TryTimeout` is used only if `maxWaitTime` is null.

The issue here comes from the processor not allowing the `maxWaittime` to be configured.  It exists on [ServiceBusProcessorOptions](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/servicebus/Azure.Messaging.ServiceBus/src/Processor/ServiceBusProcessorOptions.cs#L93) but is not exposed.   Because of that, it is always null and the `TryTimeout` is used.   

@JoshLove-msft : Do you know why `MaxReceiveWaitTime` is marked as `internal` on the processor options?  If we make that public, are there scenarios that I'm overlooking where it may cause problems?

@lmolkova : Do you have any suggestions for how a certain set of diagnostic spans can be filtered such that they aren't collected by AI?   That may help to mitigate the problem in the short term.

**Comment by lmolkova** [comment]
@Shazhko-Artem 

you can disable all Azure SDK requests and dependencies by configuring `DependencyTrackingTelemetryModule` with the following code 

```csharp 
builder.Services.ConfigureTelemetryModule<DependencyTrackingTelemetryModule>((m, _) => m.EnableAzureSdkTelemetryListener = false);
```

You can also filter out timed-out operations using [telemetry processors](https://learn.microsoft.com/en-us/azure/azure-monitor/app/api-filtering-sampling?tabs=javascriptwebsdkloaderscript)

We trace these calls since they tell that consumers are trying to receive messages and get nothing, which is still valuable information. The rate of them (2 dependencies per minute and subject to sampling would be quite low compared to the rest of the telemetry services under scale would generate).

**Comment by Shazhko-Artem** [comment]
@lmolkova Thank you very much for the answer. We cannot disable all Azure SDK requests and dependencies, but we considered the option of writing a filter. We have made the following filter.

``` c#
public class ServiceBusReceiverFilter : ITelemetryProcessor
{
    private readonly ITelemetryProcessor next;

    public ServiceBusReceiverFilter(ITelemetryProcessor next)
    {
        this.next = next;
    }

    public void Process(ITelemetry telemetry)
    {
        if (telemetry is DependencyTelemetry { Name: "ServiceBusReceiver.Receive" })
        {
            return;
        }

        this.next.Process(telemetry);
    }
}
```
Initially, we were worried that by filtering telemetry by the name `ServiceBusReceiver.Receive`, we might accidentally filter out another important telemetry with the same name, but with different content.

As we found out, without a filter, this log is written within this [DiagnosticScope](https://github.com/Azure/azure-sdk-for-net/blob/Azure.Messaging.ServiceBus_7.5.0/sdk/servicebus/Azure.Messaging.ServiceBus/src/Receiver/ServiceBusReceiver.cs#L281-L283) and displays the time that has passed since the previous call to the [ReceiveMessagesAsync](https://github.com/Azure/azure-sdk-for-net/blob/Azure.Messaging.ServiceBus_7.5.0/sdk/servicebus/Azure.Messaging.ServiceBus/src/Receiver/ServiceBusReceiver.cs#L291-L294) method. (The consumer received messages every 10-11 seconds and it created telemetry records with a duration of 10 seconds.)
![image](https://github.com/Azure/azure-sdk-for-net/assets/31850295/28dad557-b7b8-44cb-991a-3791d7323e89)

In general, this filter works for us, we will conduct a few more additional tests, and if everything goes well, I will close this ticket. Thank you very much for your support.

**Comment by jsquire** [comment]
@Shazhko-Artem :  Thank you for the update and I'm glad that we were able to get you unblocked.  I'm going to mark this as addressed, but if you come across difficulties with your testing, please /unresolve and we'd be happy to assist further.
