### ISSUE TITLE
CloudException: ForbiddenError using SubscriptionCredentialsAdapter in ExpressRouteManagementClient

### ISSUE THREAD

**Issue by rijs88** [Azure/azure-sdk-for-net#3762]
Im using Microsoft.Azure.Management.Fluent for retrieving VirtualMachines and have configured a client with clientsecret for authentication.
I want to retrieve express routes (which as far as i know are not yet available in the Fluent api), so Im using [Microsoft.WindowsAzure.Management.ExpressRoute](https://www.nuget.org/packages/Microsoft.WindowsAzure.Management.ExpressRoute/).
Im using [SubscriptionCredentialsAdapter](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/Documentation/AuthConflictsBetweenSDKs.md), but it fails to authenticate.

Exception thrown by ermClient.DedicatedCircuits.ListAsync():
CloudException: ForbiddenError: The server failed to authenticate the request. Verify that the certificate is valid and is associated with this subscription.

```csharp
private static string _clientId, _clientSecret, _tenantId, _subscriptionId;
static void Main(string[] args)
{
  AzureCredentials credentials = SdkContext.AzureCredentialsFactory
    .FromServicePrincipal(_clientId, _clientSecret, _tenantId, AzureEnvironment.AzureGlobalCloud);
  IAzure azureClient = Azure.Configure()
    .WithLogLevel(HttpLoggingDelegatingHandler.Level.None)
    .Authenticate(credentials)
    .WithSubscription(_subscriptionId);
  IVirtualMachine aVirtualMachine = azureClient.VirtualMachines.ListAsync().Result.First();

  ExpressRouteManagementClient ermClient = new ExpressRouteManagementClient(
    new SubscriptionCredentialsAdapter(credentials, _subscriptionId));
  AzureDedicatedCircuit anExpressRoute = ermClient.DedicatedCircuits.ListAsync().Result.First();
}
public class SubscriptionCredentialsAdapter [...]
```

In the code I've provided, collecting aVirtualMachine works. Is something wrong with my implementation of the SubscriptionCredentialsAdapter or ExpressRouteManagementClient?
How do you suggest I retrieve a list of expressroutes (with status and peerings available on further calls)?

**Comment by hovsepm** [comment]
"Verify that the certificate is valid and is associated with this subscription." does not seems that you have an issue with  SubscriptionCredentialsAdapter (if you use the same code that you pointed in your issue).  
From the nuget package that you pointed for ExpressRoute it seems that you are trying to use ARM authenticated client to access ASM (aka RDFE) endpoints and this will not work by design. You need to do a separate authentication for ExpressRouteManagementClient. There are some tests which use authentication code for that package that you can take a look to here https://github.com/Azure/azure-sdk-for-net/tree/master/src/ServiceManagement/ExpressRoute/ExpressRoute.Tests

**Comment by hovsepm** [comment]
@shahabhijeet this has nothing to do with Fluent. @rijs88 was trying to do RDFE call from ARM client. I think this issue can be closed.
