### ISSUE TITLE
[BUG] System.ArgumentNullException when getting SlotConfigNamesResource

### ISSUE THREAD

**Issue by wchigit** [Azure/azure-sdk-for-net#37642]
### Library name and version

Azure.ResourceManager.AppService 1.0.2

### Describe the bug

Using Azure SDK for .Net and Azure.ResourceManager.AppService packge, I used webSiteResource.GetSlotConfigNamesResource.GetAsync() to get slot config names of a web app and the folowing exception was thrown:

System.ArgumentNullException: Value cannot be null. (Parameter 'resourceId')

Stack Trace: 

Argument.AssertNotNullOrEmpty(String value, String name)

ResourceIdentifier.ctor(String resourceId)

SlotConfigNamesResourceData.DeserializeSlotConfigNamesResourceData(JsonElement element)

WebAppsRestOperations.ListSlotConfigurationNamesAsync(String subscriptionId, String resourceGroupName, String name, CancellationToken cancellationToken)

SlotConfigNamesResource.GetAsync(CancellationToken cancellationToken)

### Expected behavior

Get SlotConfigNamesResource along with its data

### Actual behavior

Exception is thrown because the resource id is null so the response can't be deserialized.

### Reproduction Steps

Get a WebSiteResource with GetWebSiteResource(_appId).GetAsync()
Get the SlotConfigNamesResource from the WebSiteResource with GetSlotConfigNamesResource().GetAsync()

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by wchigit** [comment]
Are there any updates? FYI, I tried the REST API to list slot configuration names and the id in the response is null indeed.

**Comment by HarveyLink** [comment]
Hi @wchigit , Thank you for using Azure SDK for .NET.
As ARM design requested, the `id` of a resource should **NOT** be a `null` value.

Unfortunately, this issue is related to the service side and not the SDK side, so we are not able to help you with it. Therefore, we are closing this issue for now. If you need more assistance, please [open an Azure support request](https://docs.microsoft.com/azure/azure-portal/supportability/how-to-create-azure-support-request). We apologize for any inconvenience this may cause you.
We value your feedback and we want to make sure that your problem is solved. If you think that we have misunderstood your issue or closed it incorrectly, please feel free to comment on this thread and reopen the issue. We will be happy to assist you further. Thank you for your understanding and cooperation.
