### ISSUE TITLE
[QUERY] Get database name of CosmosDB for PostgreSql

### ISSUE THREAD

**Issue by wchigit** [Azure/azure-sdk-for-net#37741]
### Library name and version

Azure.ResourceManager.CosmosDBForPostgreSql 1.0.0-beta.1

### Query/Question

Why is the database name not included in CosmosDBForPostgreSqlClusterData? Is there a way to get the database name of a cluster?

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by mcgallan** [comment]
Hi @wchigit ,The DatabaseName property is missing from the properties of Data in the current version, but the service team has addressed and resolved this issue. It will be fixed in the later versions released by the service team. Thank you for your feedback!

**Comment by ArthurMa1978** [comment]
Thank you for reaching out to us about the Azure SDK for .NET. Unfortunately, this issue is related to the service side and not the SDK side, so we are not able to help you with it. Therefore, we are closing this issue for now. If you need more assistance, please [open an Azure support request](https://docs.microsoft.com/azure/azure-portal/supportability/how-to-create-azure-support-request). We apologize for any inconvenience this may cause you.

We value your feedback and we want to make sure that your problem is solved. If you think that we have misunderstood your issue or closed it incorrectly, please feel free to comment on this thread and reopen the issue. We will be happy to assist you further. Thank you for your understanding and cooperation.
