### ISSUE TITLE
Azure Function app with event hub trigger stops randomly from consuming event hub message

### ISSUE THREAD

**Issue by TestUser0811** [Azure/azure-sdk-for-net#37753]
### Library name and version

Microsoft.Azure.EventHubs-4.3.2   Microsoft.Azure.WebJobs.Extensions.EventHubs-5.1.2

### Query/Question

All of sudden, Azure Function app with event hub trigger stopped consuming messages/events from partition. Restarting the function app mitigated the issue.

What would be possible reason?

It is happen on different partition on different time and no particular pattern observed?

host.json as below
```json
{
  "version": "2.0",
  "extensions": {
    "eventHubs": {
      "batchCheckpointFrequency": 5,
        "maxEventBatchSize": 10,
        "prefetchCount": 300
    }
  },
  "logging": {
    "logLevel": {
      "default": "Warning"
    },
    "applicationInsights": {
      "samplingSettings": {
        "isEnabled": true
      }
    }
  },
  "functionTimeout": "-1"
}
```

**Comment by jsquire** [comment]
Hi @TestUser0811.   Thank you for reaching out and we regret that you're experiencing difficulties.  It would be helpful to see a 5-minute slice of verbose logs around the stall so that we can understand what the trigger and function are seeing at this time.   It would also be helpful if you could share your code so that we can understand the patterns in use.   If you're unable to share your actual application code, a small self-contained sample that can reproduce the behavior would also work.
