### ISSUE TITLE
[QUERY] Determining IsOnline in ApiCollection.GetAllAsync

### ISSUE THREAD

**Issue by adahlinvcrs** [Azure/azure-sdk-for-net#37854]
### Library name and version

Azure.ResourceManager.ApiManagement 1.0.1

### Query/Question

When using the ApiCollection.GetAllAsync method, APIs that are offline are indicated by the IsOnline property being set as false, but for online APIs it is null. 
![image](https://github.com/Azure/azure-sdk-for-net/assets/131376167/8d74bb44-411c-4ecf-90ff-ee0bc53b48e7)

Using the API Management Rest API, we can see that the property is not included in the response for APIs that are online, but included as false for APIs that are offline.

Example properties for an API that is online:
```json
"properties": {
    "displayName": "Test Api",
    "apiRevision": "123123123",
    "description": "123123123",
    "subscriptionRequired": true,
    "serviceUrl": "123123123",
    "path": "123123123",
    "protocols": [
        "https"
    ],
    "authenticationSettings": {
        "oAuth2": null,
        "openid": null
    },
    "subscriptionKeyParameterNames": {
        "header": "123123123",
        "query": "123123123"
    },
    "contact": {
        "name": null,
        "url": null,
        "email": "123123123"
    },
    "isCurrent": true,
    "apiRevisionDescription": "123123123",
    "apiVersion": "v2",
    "apiVersionDescription": "",
    "apiVersionSetId": "123123123"
}
```

Example properties for an API that is offline:
```json
"properties": {
    "displayName": "Test Api",
    "apiRevision": "123123123",
    "description": "123123123",
    "subscriptionRequired": true,
    "serviceUrl": "123123123",
    "path": "123123123",
    "protocols": [
        "https"
    ],
    "authenticationSettings": {
        "oAuth2": null,
        "openid": null
    },
    "subscriptionKeyParameterNames": {
        "header": "123123123",
        "query": "123123123"
    },
    "contact": {
        "name": null,
        "url": null,
        "email": "123123123"
    },
    "isCurrent": true,
    "isOnline": false,
    "apiRevisionDescription": "123123123",
    "apiVersion": "v2",
    "apiVersionDescription": "",
    "apiVersionSetId": "123123123"
}
```

Is the expected method for determining that an API is online to check for the property being null when using the Azure.ResourceManager.ApiManagement nuget package?

Thank you!

### Environment

Windows 10
net6.0 project
Visual Studio 2022 17.4.2

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by HarveyLink** [comment]
This looks like a service domain quetion, add service attention label here.

**Comment by HarveyLink** [comment]
As the test results using REST Api, the `isOnline` property will only show when value is false in the result, its a service issue.

**Comment by ArthurMa1978** [comment]
Hey @adahlinvcrs , thank you for reaching out to us about the Azure SDK for .NET. Unfortunately, this issue is related to the service side and not the SDK side, so we are not able to help you with it. Therefore, we are closing this issue for now. If you need more assistance, please [open an Azure support request](https://docs.microsoft.com/azure/azure-portal/supportability/how-to-create-azure-support-request). We apologize for any inconvenience this may cause you.

We value your feedback and we want to make sure that your problem is solved. If you think that we have misunderstood your issue or closed it incorrectly, please feel free to comment on this thread and reopen the issue. We will be happy to assist you further. Thank you for your understanding and cooperation.
