### ISSUE TITLE
[BUG] ArgumentNullException when get SlotConfigNamesResource

### ISSUE THREAD

**Issue by ievgen-pavlenko** [Azure/azure-sdk-for-net#37850]
### Library name and version

Azure.ResourceManager.AppService 1.0.2 & 1.1.0-beta.1

### Describe the bug

Azure.ResourceManager.AppService NuGet package where an ArgumentNullException is thrown when attempting to retrieve the SlotConfigNamesResource. This problem is experienced in both versions 1.0.2 and the 1.1.0-beta.1.

### Expected behavior

The expectation is to be able to successfully retrieve the SlotConfigNamesResource without any exceptions being thrown.

### Actual behavior

When trying to retrieve the SlotConfigNamesResource, the System.ArgumentNullException is thrown with the message "Value cannot be null. (Parameter 'resourceId')".

### Reproduction Steps

Here's a snippet of the code that triggers the error:

```csharp
var client = new AzureClient(tokenCred);
var id = SlotConfigNamesResource.CreateResourceIdentifier(subscriptionId, rgName, siteName);
SlotConfigNamesResource slotConfigNamesResource = await client.GetSlotConfigNamesResource(id).GetAsync();
```

### Environment

.NET SDK:
 Version:   7.0.306
 Commit:    f500069cb7

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22000
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.306\

IDE: Visual Studio 17.6.5

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by HarveyLink** [comment]
Hi @ievgen-pavlenko , Thank you for using Azure SDK for .NET.
As ARM design requested, the `id` of a resource should **NOT** be a `null` value.

Unfortunately, this issue is related to the service side and not the SDK side, so we are not able to help you with it. Therefore, we are closing this issue for now. If you need more assistance, please [open an Azure support request](https://docs.microsoft.com/azure/azure-portal/supportability/how-to-create-azure-support-request). We apologize for any inconvenience this may cause you.
We value your feedback and we want to make sure that your problem is solved. If you think that we have misunderstood your issue or closed it incorrectly, please feel free to comment on this thread and reopen the issue. We will be happy to assist you further. Thank you for your understanding and cooperation.
