### ISSUE TITLE
[FEATURE REQ]  Form recognizer: Copy classifier models?

### ISSUE THREAD

**Issue by woeterman94** [Azure/azure-sdk-for-net#37879]
### Library name

FormRecognizer.DocumentAnalysis

### Please describe the feature.

I'd would like to see a method to be able to copy custom classification models. 

There is a model to copy models (**CopyDocumentModelTo**) but not to copy classification models.

![image](https://github.com/Azure/azure-sdk-for-net/assets/5755057/e194024c-903c-43e6-afbb-e5e1f720a8c3)

You will get an error when you try to pass in the ID of a classifier model into he copydocumentmodel method.
 
![image](https://github.com/Azure/azure-sdk-for-net/assets/5755057/6b72cf2d-8510-4508-85f6-6ab0af62a44d)

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by kinelski** [comment]
Hello @woeterman94. The feature you're requesting currently is not supported by the Form Recognizer service, so we cannot implement it on the client library side. To share this request with the Form Recognizer service team you can register feedback for [Azure Cognitive Services](https://feedback.azure.com/d365community/forum/09041fae-0b25-ec11-b6e6-000d3a4f0858).

I'm closing this issue since this repository is focused on the SDK only. Please feel free to reopen it if you think I misunderstood the issue.

**Comment by woeterman94** [comment]
Posted as suggestion here: https://feedback.azure.com/d365community/idea/74cf78b3-482d-ee11-a81c-000d3a040137

**Comment by kinelski** [comment]
@woeterman94 This feature is not supported in 2023-07-31 either.
