### ISSUE TITLE
[FEATURE REQ] Need to format the result from ConversationAnalysisClient response

### ISSUE THREAD

**Issue by Aiswarya1794** [Azure/azure-sdk-for-net#38050]
### Library name

Azure AI services

### Please describe the feature.

We are using Orchestrator workflow of Custom question answering service for connecting to multiple Question answering service.

We are fetching the predictions using ConversationAnalysisClient. The response contains all data but to access the values we need to use json. 

Question answering is returning the data in KnowledgeBaseAnswer format which is easy to access. 
Is there any possibility to develop a similar structure for fetching the response from Orchester for Question answering, Luis and Conversational analysis

**Comment by navba-MSFT** [comment]
@Aiswarya1794 Thanks for reaching out to us and reporting this issue. It seems like you are asking if there is a way to develop a similar structure for fetching the response from Orchestrator for Question answering, Luis, and Conversational analysis.

I'm not entirely sure what you mean by "similar structure". Could you please provide more information or clarify your question?

**Comment by Aiswarya1794** [comment]
For AI.Language.QuestionAnswering, its returning the response as list of Question Answers

public virtual Task<Response<AnswersResult>> GetAnswersAsync(string question, QuestionAnsweringProject project, AnswersOptions options = null, CancellationToken cancellationToken = default) =>
            GetAnswersAsync(project, (options ?? new()).WithQuestion(question), cancellationToken);

This answer result contains the list of KnowledgeBaseAnswer and this contains knowledge base answer in the below class staructure.

internal KnowledgeBaseAnswer(IReadOnlyList<string> questions, string answer, double? confidence, int? qnaId, string source, IReadOnlyDictionary<string, string> metadata, KnowledgeBaseAnswerDialog dialog, AnswerSpan shortAnswer)
        {
            Questions = questions;
            Answer = answer;
            Confidence = confidence;
            QnaId = qnaId;
            Source = source;
            Metadata = metadata;
            Dialog = dialog;
            ShortAnswer = shortAnswer;
        }

    But in case of Orchestrator workflow we are using conversationAnalysisClient for fecthing the data through 'AnalyzeConversationAsync' method and its just returing the method as Task<Response>

From a developer point of view , it will be good if this response can have a similar class structure for accessing the data easily , other wise every time we need to use json parser to parse the data and format for fetching the correct data

**Comment by navba-MSFT** [comment]
Adding Service team to look into this

**Comment by heaths** [comment]
Currently, the lack of models in Conversations is by design. The Azure SDK across all languages are working on a new way to generate idiomatic models from TypeSpec, and only when a service has authored their service in TypeSpec to mitigate breaking changes. The service team is working on a TypeSpec version of their service, so you can expect models sometime in the near future. Question Answering predates that effort.

To make it easier to work with JSON but have a C# feel, see our samples e.g., https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/cognitivelanguage/Azure.AI.Language.Conversations/samples/Sample2_AnalyzeConversation_OrchestrationPrediction.md#synchronous. You can use `ToDynamicFromJson` with C#'s `dynamic` keyword to access JSON properties idiomatically.
