### ISSUE TITLE
[QUERY] Copying blobs - performance

### ISSUE THREAD

**Issue by andrei-faber** [Azure/azure-sdk-for-net#38087]
### Library name and version

Azure.Storage.Blobs 12.17.0

### Query/Question

Here is the code that I wrote to copy blobs from one Azure storage account to another, and it's about an order of magnitude slower than azcopy.
Any ideas why so much difference and how to make it faster? Any settings that limit concurrency in the library (besides standard .NET settings) or anything else?
```
var tasks = new List<Task>();
var maxTasks = 0x100;

foreach (var blob in blobs)
{
	var blobClient = sourceContainerClient.GetBlobClient(blob.Name);
	var sourceUri = blobClient.Uri;

	var targetBlobPath = $"{targetInnerPath}/{blob.Name}";
	var targetBlobClient = targetContainerClient.GetBlobClient(targetBlobPath);

	var operation = targetBlobClient.StartCopyFromUri(new Uri($"{sourceUri}{sourceSas}"));
	var task = operation.WaitForCompletionAsync().AsTask();
	tasks.Add(task);

	if (tasks.Count < maxTasks)
		continue;

	Task.WaitAny(tasks.ToArray());
	tasks.RemoveAll(cur => cur.IsCompleted);
}

Task.WaitAll(tasks.ToArray());
```

**Comment by navba-MSFT** [comment]
@andrei-faber Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment]
@andrei-faber Regarding your query, there are a few things that you can do to improve the performance of your blob copying operations:

1. Use the [StartCopyFromUriAsync ](https://learn.microsoft.com/en-us/dotnet/api/azure.storage.blobs.specialized.blobbaseclient.startcopyfromuriasync?view=azure-dotnet) method instead of the StartCopyFromUri method to start the copy operation asynchronously. This can help improve the concurrency of your copy operations and reduce the overall time taken to copy the blobs.

2. Have you explored the [Azure Storage Data Movement library](https://learn.microsoft.com/en-us/azure/storage/common/storage-use-data-movement-library) that is designed for high performance uploading, downloading, and copying of blobs and files. The Data Movement library provides convenient methods that aren't available in the Azure Storage client library for .NET. These methods provide the ability to set the number of parallel operations, track transfer progress, easily resume a canceled transfer, and much more. _This library is based on the core data movement framework that powers_ [**AzCopy**](https://azure.microsoft.com/documentation/articles/storage-use-azcopy/).

3. [Have you configured your client to use a sufficient number of concurrent connections?](https://learn.microsoft.com/en-us/azure/storage/blobs/storage-performance-checklist#increase-default-connection-limit)
4. [For .NET applications, have you configured .NET to use a sufficient number of threads?](https://learn.microsoft.com/en-us/azure/storage/blobs/storage-performance-checklist#increase-minimum-number-of-threads)

5. [Have you ensured that parallelism is bounded appropriately so that you don't overload your client's capabilities or approach the scalability targets?](https://learn.microsoft.com/en-us/azure/storage/blobs/storage-performance-checklist#unbounded-parallelism)
6. [Are you copying blobs in the most efficient manner?](https://learn.microsoft.com/en-us/azure/storage/blobs/storage-performance-checklist#blob-copy-apis)
7. [Are you proactively tuning client library options to optimize data transfer performance?](https://learn.microsoft.com/en-us/azure/storage/blobs/storage-performance-checklist#performance-tuning-for-data-transfers)

Please follow the above suggestions. Hope this helps.

**Comment by andrei-faber** [comment]
@navba-MSFT looks like this problem is actually happening due to something in the PC configuration, as I ran the same code on another PC and it was about x100 faster. I wonder if you guys heard about problems that can affect this library in this way?
Also, I made a benchmark using AzCopy and it's not affected by this problem on the same PC.

**Comment by navba-MSFT** [comment]
@andrei-faber Thanks for getting back. Since the same code is working fine on another PC here are few things you can check:

1. Ensure that the `Azure.Storage.Blobs` library version is the same on both PC and its up to date. 
2. Are both the PC having the same configurations ( Like CPU cores, Memory, Disk IO and Network) ?

These 2 factors can affect the library performance. 

Also note that azcopy works by utilizing concurrent connections. You can also try and confirm the below:

[Have you configured your client to use a sufficient number of concurrent connections?](https://learn.microsoft.com/en-us/azure/storage/blobs/storage-performance-checklist#increase-default-connection-limit)

[For .NET applications, have you configured .NET to use a sufficient number of threads?](https://learn.microsoft.com/en-us/azure/storage/blobs/storage-performance-checklist#increase-minimum-number-of-threads)

**Comment by andrei-faber** [comment]
@navba-MSFT
1. it's exactly same code tested on both PCs. 
2. they are different, but I think this can't explain x10 difference in performance.
3. This code already is concurrent

**Comment by navba-MSFT** [comment]
> @navba-MSFT
> 
> 1. it's exactly same code tested on both PCs.
> 2. they are different in hardware, but I think this can't explain x10 difference in performance. The network is same.
> 3. This code already is concurrent

@andrei-faber The machine configuration can play a role here. Because the number of threads being spawned is linked to available procs on the machine. 

1. Could you please test with another machine having the same config as the working machine ?

2. Also are both the PCs in the same region ?

**Comment by shepshook** [comment]
I have exactly the same issue, any news on this?
