### ISSUE TITLE
[BUG] AppConfig: Cannot set ETag when constructing FeatureFlagConfigurationSetting

### ISSUE THREAD

**Issue by Charu03** [Azure/azure-sdk-for-net#38098]
### Library name and version

Azure.Data.AppConfiguration 1.1.0-beta.2

### Describe the bug

There is a property called 'eTag' that is inherited from ConfigurationSetting  in FeatuerFlagConfigurationSetting but there does not appear to be a way to set the property. When you try to update the featureFlag it does no evaluation with eTag.

### Expected behavior

The eTag should be allowed to set in the FeatureFlagConfigurationSetting object. The expected behaviour should be to enable eTags for Feature Flags, just as in ConfigurationSetting object.

### Actual behavior

Currently, FeatureFlagConfigurationSetting does not have eTag as a parameter, but the inherited class "ConfigurationSetting" has the eTag. But I am working with FeatureFlagConfigurationSetting object and I want to be able to update the flag and create the flag, which is difficult to do as there is no eTag in FeatureFlagConfigurationSetting.

### Reproduction Steps

Here are the links that have the documentation:

https://azuresdkdocs.blob.core.windows.net/$web/dotnet/Azure.Data.AppConfiguration/1.1.0-beta.2/api/Azure.Data.AppConfiguration/Azure.Data.AppConfiguration.ConfigurationSetting.html

https://azuresdkdocs.blob.core.windows.net/$web/dotnet/Azure.Data.AppConfiguration/1.1.0-beta.2/api/Azure.Data.AppConfiguration/Azure.Data.AppConfiguration.FeatureFlagConfigurationSetting.html

### Environment

.NET SDK:
 Version:   7.0.304
 Commit:    7e794e2806

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  13.5
 OS Platform: Darwin
 RID:         osx.13-arm64
 Base Path:   /usr/local/share/dotnet/sdk/7.0.304/

Host:
  Version:      7.0.7
  Architecture: arm64

- IDE is Rider 2022 version

**Comment by jsquire** [comment]
Hi @Charu03.   Normally, the ETag for a setting is generated by the AppConfig service and appears only on data that was read, not something newly created by the application.  Can you help me understand the scenario for your application setting the ETag directly?

**Comment by jsquire** [comment]
Hi @Charu03.  Thank you for the additional context.  I think we have two scenarios here - attempting to update a setting and attempting to unit test.   We definitely have a gap that needs to be addressed; I'd appreciate some additional information to better understand your scenario so that I can determine the right way to get things fixed up.

> I create a new instance of FeatureFlagConfigurationSetting (featureFlag) and then pass it to SetConfigurationSettingAsync(featureFlag, true, cancellationToken). 

Can you help me understand what ETag value you would be using in the scenario where you create a new instance of `FeatureFlagConfigurationSetting`?

The ETag is a service-owned value.  When you create or update a setting of any type, the service will generate an ETag value and assign it - you cannot directly create one.  The intention for `onlyIfUnchanged` is that you'll retrieve a setting using `GetConfigurationSetting`, modify its properties, and then call `SetConfigurationSetting`.  

> not being able to set eTag in the object, makes it difficult to write unit tests around it.

Agreed.  This is where the `ConfigurationModelFactory` comes in; the intent is for that to be used when creating service-owned types and types with service-owned fields.  The model factory should allow you to create a `FeatureFlagConfigurationSetting` and provide all of its attributes for testing purposes.   In this case, feature flag and secret settings can't be created.

For the interested, more detail on our strategy for unit testing can be found in [Unit testing and mocking with the Azure SDK for .NET](https://learn.microsoft.com/dotnet/azure/sdk/unit-testing-mocking?tabs=csharp).

**Comment by jsquire** [comment]
After discussion, we decided the fix for this would be to mark the configuration setting constructor overload as non-visible, as it should have been `internal` and the model factory used for creating test instances.   The feature flag and secret settings will be creatable from the model factory for testing and allow all service-owned properties to be set.   This is part of #38164.

**Comment by jsquire** [comment]
Digging through the commit history, I was able to trace the constructor back to a `GetSettingAsync` overload that accepted an `onlyIfUnchanged` parameter rather than the full match conditions.   This build the match conditions clause based on the ETag in the setting.   

To ensure that this overload can be used, previous fix hiding the ETag constructor for the base setting was reverted and we've added overloads to the specialized settings.  _(ref: #38450)_
