### ISSUE TITLE
[QUERY] Migration path for blob encryption from Microsoft.Azure.Storage.Blob to Azure.Storage.Blobs

### ISSUE THREAD

**Issue by tomkerkhove** [Azure/azure-sdk-for-net#38264]
### Library name and version

Azure.Storage.Blobs v12

### Query/Question

We're looking to migrate from Microsoft.Azure.Storage.Blob to Azure.Storage.Blobs but are using blob encryption.

I was looking at the [migration guide](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/storage/Azure.Storage.Blobs/AzureStorageNetMigrationV12.md) to see if there are any changes and/or if the encryption will be broken but this does not seem to be mentioned.

Does that mean there is full parity and there is no impact?

**Comment by navba-MSFT** [comment]
@tomkerkhove Apologies for the late reply. Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment]
@tomkerkhove The clientside encryption is not functionally broken, though it obviously shares the API breaks that come with the upgrade.

Since Azure.Storage.Blobs has been released, there has been a [CVE regarding clientside encryption](https://github.com/google/security-research/security/advisories/GHSA-6m8q-r22q-vfxh). While we have addressed this cve with an updated version of clientside encryption, upgrading requires you to rotate your own data encryption.

Microsoft.Azure.Blob uses what we are calling clientside encryption v1. Azure.Storage.Blobs also supports clientside encryption v1, and requires you specify such when [constructing encryption options](https://learn.microsoft.com/en-us/dotnet/api/azure.storage.clientsideencryptionoptions.-ctor?view=azure-dotnet#azure-storage-clientsideencryptionoptions-ctor(azure-storage-clientsideencryptionversion)). This is what you can upgrade to in a non-breaking way.

After that upgrade, we recommend you to take the time to migrate your encrypted data from v1 encryption to v2 encryption. You can learn more about this upgrade process with [this article](https://techcommunity.microsoft.com/t5/azure-storage-blog/ga-azure-storage-updating-client-side-encryption-in-sdk-to/ba-p/3563013).

**Comment by tomkerkhove** [comment]
Thank you very much, that answers my question for now and I'll look in to this!
