### ISSUE TITLE
[BUG]  Azure.Security.KeyVault.Secrets GetSecret tries to spawn a child process even though it's a synchronous function.

### ISSUE THREAD

**Issue by farzonl** [Azure/azure-sdk-for-net#38367]
### Library name and version

Azure.Security.KeyVault.Secrets

### Describe the bug

When I call the code below as part of a word VSTO App
```csharp
var client = new SecretClient(new Uri($"https://some_keyvault.azure.net/"), new DefaultAzureCredential());
client.GetSecret("some connection-connection-string")'
```
It is blocked by my customers IT policy because it is a word child process.
![image](https://github.com/Azure/azure-sdk-for-net/assets/1802579/989a0931-ceec-42b9-bdb5-cf1cbdd42768)

### Expected behavior

for the GetSecret function to not spawn a child process.

### Actual behavior

GetSecret spawns a child process on `_pipeline.SendRequest`

### Reproduction Steps

create a string you want to fetch from a keyvault using a connection string
create a skeleton vsto app.
your `ThisAddIn_Startup` should look like this
```csharp
private void ThisAddIn_Startup(object sender, System.EventArgs e) {
var client = new SecretClient(new Uri($"https://some_keyvault.azure.net/"), new DefaultAzureCredential());
client.GetSecret("some connection-connection-string")'
}
```
Run the application.

### Environment

.NET SDK:
 Version:   7.0.307
 Commit:    7b77e35a2b

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19045
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.307\

Host:
  Version:      7.0.10
  Architecture: x64
  Commit:       a6dbb800a4

.NET SDKs installed:
  6.0.316 [C:\Program Files\dotnet\sdk]
  7.0.307 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.21 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.21 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.21 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

**Comment by jsquire** [comment]
Hi @farzonl.  Thank you for reaching out and we regret that you're experiencing difficulties.  It is not KeyVault creating a child process, but Identity.  This is expected behavior for the unconfigured `DefaultAzureCredential` instance that you are using, which attempts a variety of authentication methods - including local development tools like VS Code and the Azure CLI which require the child process.  

You can work around this by either using a credential specific to the type of authorization that you would like your app to do, or by passing [DefaultAzureCredentialOptions](https://learn.microsoft.com/dotnet/api/azure.identity.defaultazurecredentialoptions?view=azure-dotnet) with the local development options disabled.   More information can be found in the [Azure Identity overview](https://learn.microsoft.com/dotnet/api/overview/azure/identity-readme?view=azure-dotnet#defaultazurecredential).

**Comment by farzonl** [comment]
@jsquire  You are awesome, thank you. I will try that!
