### ISSUE TITLE
Can no longer build AzureStack admin modules located under the AzureStack directory.

### ISSUE THREAD

**Issue by deathly809** [Azure/azure-sdk-for-net#3840]
I used to be able to build using the command:

msbuild build.proj /t:Build /p:Scope=AzureStack

I can no longer do this.  Was this removed on purpose?

**Comment by shahabhijeet** [comment]
@deathly809 build tools have been removed from the SDK repo.
In order to make sure you have the latest build tools, you will need to do the following:
1) Pull .NET SDK from upstream (get latest)
2) execute msbuild build.proj (this will update the build tools in your local repo)
3) msbuild build.proj /t:Build /p:Scope=AzureStack

Let me know if you still see an issue, please provide me the output of msbuild when this is not working.

**Comment by shahabhijeet** [comment]
Please re-open this issue if you are still not able to build AzureStack
