### ISSUE TITLE
[BUG] An exception is thrown when trying to load long datatype from AzureTableStorage

### ISSUE THREAD

**Issue by Jimmy-Ahmed** [Azure/azure-sdk-for-net#38407]
### Library name and version

Azure.Data.Tables 12.8.1

### Describe the bug

Hi,

I have the below code

```
await var result = this.tableClient.QueryAsync<RequestEntity>(x => x.PartitionKey == "123").ToListAsync()

public abstract class RequestEntity: ITableEntity
{
    public virtual long Id { get; set; }

    public virtual string Name { get; set; }

    // other properties
}
```

An exception is being thrown, when I change the "Id" from long to int. it works as expected.

### Expected behavior

No exception should be thrown and the data should be retrieved 

### Actual behavior

An exception is being thrown, when I change the "Id" from long to int. it works as expected.

### Reproduction Steps

Run my code

### Environment

VS 2022
Windows 11

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by Jimmy-Ahmed** [comment]
[AzureTableStorageBug.zip](https://github.com/Azure/azure-sdk-for-net/files/12467268/AzureTableStorageBug.zip)

Attaching a working solution for the issue. Please check and let me know

**Comment by christothes** [comment]
After looking over the repro and discussing offline, the code in question is attempting to do something that is unsupported. 

The example code creates an entity with a property Foo that is typed as `int`, but then tries to query it with a strongly typed model that changes this property type to `long`. 

This mismatch of types seems like it would be fine because int is always castable to long, but the table data model serializes `long`/`Int64` as string.

If your scenario requires a flexible entity schema, the `TableEntity` model will work, as demonstrated in your repro code. However, when providing a strongly typed model to the Query method, you are declaring that the entity schema will match the model schema. In some cases, this may work - but in cases where the wire protocol differs from the .NET type, this will fail, as in this case. If you intend to migrate this property in your model from `int` to `long`, I'd suggest you just add a new property to your model of the correct type.
