### ISSUE TITLE
Be able to obtain current swap status

### ISSUE THREAD

**Issue by tomaszgawlik** [Azure/azure-sdk-for-net#3843]
Currently, it's possible to use sdk to perform website swap. 
Using `Microsoft.Azure.Management.WebSites.WebSiteManagementClient client`:

```
AzureOperationResponse  response = await client.WebApps.BeginSwapSlotWithProductionWithHttpMessagesAsync("RG_Name", "App_name", new CsmSlotEntity("slot name", true));
```
But after starting the swap it's impossible (or at least unclear for me) to know exectly when swap is completed.

One can query the website:
```
var application = await client.WebApps.GetAsync("RG_Name", "App_name");
```
and there's `application.SlotSwapStatus` field. But it only contains slot names and timestamp.

Ideally, it would contain actual status for example Starting, Completed, Failure.
Is there a way to get that information?  `AzureOperationResponse` class contains `RequestId`. Is it possible to query some endpoint using that id?

**Comment by ttugates** [comment]
I am looking for how to do this as well without polling.

**Comment by shahabhijeet** [comment]
The operation is currently being polled during the long running operation.
It currently does not returns interim polling status to the client.
It only returns the final result of the operation.
We are thinking of providing a way to serialize polling state, and at that point you will be able to poll and also get polling status.

**Comment by isra-fel** [comment]
@MiYanni Hello Yanni, could this issue be resolved when we upgrade to v3 generator?

**Comment by MiYanni** [comment]
@isra-fel If you're asking about polling serialization, we do not have polling state serialization. I've created an issue here: https://github.com/Azure/autorest.csharp/issues/697
Here is our Operation class: https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/core/Azure.Core/src/Operation%7BT%7D.cs
You can call `UpdateStatus/Async` to manually poll the status. This response is raw, and would have the state somewhere in it, but you'd have to extract that information manually.

I don't know the exact scenario in this issue, but it sounds like `UpdateStatus/Async` from the new generator should allow this scenario. But, if you want a nice C# interface for it, you would have to build a class on top of this, and add a way to extract the state from the raw Response. We will have classes generated (that can be added to/modified) after this issue is resolved: https://github.com/Azure/autorest.csharp/issues/646
