### ISSUE TITLE
[BUG] Start Automation runbook test job fails with Status: 404 (Not Found) in some regions

### ISSUE THREAD

**Issue by davecader** [Azure/azure-sdk-for-net#38448]
### Library name and version

Azure.ResourceManager.Automation 1.1.0-beta.1

### Describe the bug

Start an Automation runbook test job fails with Status: 404 (Not Found) in some regions, but works in with others. I can start the runbook test job in the Azure portal OK. The resource definitely exists, as I can download the contents of the runbook using the SDK.

The full error message is:

"Service request failed.\r\nStatus: 404 (Not Found)\r\n\r\nHeaders:\r\nPragma: no-cache\r\nx-ms-ratelimit-remaining-subscription-writes: REDACTED\r\nx-ms-request-id: 4ad4e51d-745d-4abc-ad67-6ba6307492b0\r\nx-ms-correlation-request-id: REDACTED\r\nx-ms-routing-request-id: REDACTED\r\nStrict-Transport-Security: REDACTED\r\nX-Content-Type-Options: REDACTED\r\nX-Cache: REDACTED\r\nX-MSEdge-Ref: REDACTED\r\nContent-Length: 0\r\nCache-Control: no-cache\r\nDate: Wed, 30 Aug 2023 16:42:48 GMT\r\nExpires: -1\r\n"

### Expected behavior

You should be able to start runbooks in any valid region.

### Actual behavior

Stack trace:

at Azure.ResourceManager.Automation.TestJobRestOperations.<CreateAsync>d__6.MoveNext()
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Azure.ResourceManager.Automation.AutomationRunbookResource.<CreateTestJobAsync>d__42.MoveNext()
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()

### Reproduction Steps

var options = new InteractiveBrowserCredentialOptions
{
    TenantId = "YOUR TENANT ID",
    ClientId = "YOUR CLIENT ID,
    RedirectUri =  new Ui("YOUR REDIRECT URI")
};

var credential = new InteractiveBrowserCredential(options);
var context = new TokenRequestContext(new[] { "https://management.core.windows.net//.default" });
await credential.GetTokenAsync(context).ConfigureAwait(false);

var armClient = new ArmClient(credential);
var resourceId = AutomationRunbook.CreateResourceIdentifier("YOUR SUBSCRIPTION ID", "YOUR RESOURCE GROUP", "YOUR AUTOMATION ACCOUNT", "YOUR RUNBOOK NAME");
var resource = _armClient.GetAutomationRunbookResource(resourceId)

var content = new RunbookTestJobCreateContent();
var response = await _runbookResource.CreateTestJobAsync(content);

### Environment

.NET 4.8
Windows 10 Pro

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by davecader** [comment]
I updated my original comment to say that the problem is with different **Regions** and not different **Resource Groups**. For example, I can reproduce this issue with Automation Accounts that I create in East US, whereas those created in Canada Central work fine.

**Comment by ArthurMa1978** [comment]
Hey @davecader , thank you for reaching out to us, do you mean only the **Test Jobs** has the problem? If yes, then this issue is related to the service side and not the SDK side, so we are not able to help you with it. Therefore, we are closing this issue for now. If you need more assistance, please [open an Azure support request](https://docs.microsoft.com/azure/azure-portal/supportability/how-to-create-azure-support-request).

**Comment by davecader** [comment]
Sorry, I was on vacation the last couple of weeks with no internet access. Yes, this issue is specifically related to starting Test Jobs. However, in the affected regions I am able to start Test Jobs from within the Azure web portal - it is only when doing so using the Azure SDK that I am encountering problems. This suggests to me that it is indeed an SDK issue and not a server-side issue.

**Comment by ArthurMa1978** [comment]
Hey @davecader , thank you for reaching out to us about the Azure SDK for .NET. Unfortunately, this issue is related to the service side and not the SDK side, so we are not able to help you with it. Therefore, we are closing this issue for now. If you need more assistance, please [open an Azure support request](https://docs.microsoft.com/azure/azure-portal/supportability/how-to-create-azure-support-request). We apologize for any inconvenience this may cause you.

We value your feedback and we want to make sure that your problem is solved. If you think that we have misunderstood your issue or closed it incorrectly, please feel free to comment on this thread and reopen the issue. We will be happy to assist you further. Thank you for your understanding and cooperation.

**Comment by davecader** [comment]
Based on my own observations, this does not appear to be a server-side issue. As mentioned previously in the affected regions I am able to start Test Jobs from within the Azure web portal - it is only when doing so using the Azure SDK that I am encountering problems. This suggests to me that it is indeed an SDK issue and not a server-side issue.
