### ISSUE TITLE
[FEATURE REQ] Add support for replicas and automatic failover for Azure.Data.AppConfiguration.ConfigurationClient

### ISSUE THREAD

**Issue by fume** [Azure/azure-sdk-for-net#38446]
### Library name

Azure.Data.AppConfiguration

### Please describe the feature.

The ConfigurationClient doesn't seem to support multiple endpoints/connection strings. I was expecting to be able to use replicas with the ConfigurationClient just like i'm able to do so with the AppConfigurationProvider in ASP.NET Core (ref: https://learn.microsoft.com/en-us/azure/azure-app-configuration/howto-geo-replication?tabs=dotnet#use-replicas).

Am i missing something or there is no way to failover automatically to another replica when using the ConfigurationClient directly?

**Comment by fume** [comment]
Hi @jsquire, thank you very much for the prompt reply even if it's not what i was expecting 😄 
Another side-note: from the docs it's not clear that all the replicas are writable, while they are.

thanks again, regards.

P.S. There are other Azure SDKs which support failover/HA:
Cosmos DB: (https://learn.microsoft.com/en-us/azure/cosmos-db/nosql/troubleshoot-sdk-availability)
Azure Storage SDK: (https://github.com/Azure-Samples/storage-dotnet-circuit-breaker-ha-ra-grs/blob/master/v12/storage-dotnet-redundancy-ha-ra-grs/Program.cs)
Maybe there are others which i'm not used to, so the developer experience it's already non-consistent 😢

**Comment by jsquire** [comment]
Hi @fume.   Thanks for letting us know about the docs.   I'll pass that on to the AppConfiguration service team.   

With respect to the other libraries that you mention - the Storage library was the prototype that was studied by the archboard when forming that guidance.  The active/passive configuration was left in place due to special business needs.   Cosmos, on the other hand, is not part of the current generation of Azure SDK packages and does not follow our guidelines.  This is why is has a `Microsoft.Azure` prefix rather than `Azure.Data`.

**Comment by fume** [comment]
Oh, so you were referring to the Azure.Data.* SDKs. Got it, Thanks!

**Comment by jsquire** [comment]
Anything using the pattern `Azure.[[ AREA ]].[[ SERVICE ]]` are considered the current generation of the Aure SDK (aka "track 2") and required to comply with the [Azure SDK Guidelines](https://azure.github.io/azure-sdk/general_introduction.html).   Packages with the pattern "Microsoft.Azure.[[ SOMETHING ]]" fall into a few different categories (legacy, higher-level abstraction, bridge package for third party dependencies, service team-owned) and do not have the contract that they follow the guidlines.
