### ISSUE TITLE
The intranet requests kusto through a proxy, throwing errors

### ISSUE THREAD

**Issue by lp956** [Azure/azure-sdk-for-net#38515]
### Library name and version

Microsoft.Azure.Kusto.Data 11.3.3

### Query/Question

No such host is known. (*.chinanorth3.kusto.chinacloudapi.cn:443)

 

Retry failed after 4 tries. Retry settings can be adjusted in ClientOptions.Retry or by configuring a custom retry policy in ClientOptions.RetryPolicy. (The proxy tunnel request to proxy 'http://{ip}:8080/' failed with status code '403'.") (The proxy tunnel request to proxy 'http://{ip}:8080/' failed with status code '403'.") (The proxy tunnel request to proxy 'http://{ip}:8080/' failed with status code '403'.") (The proxy tunnel request to proxy 'http://{ip}:8080/' failed with status code '403'.")

---> Azure.RequestFailedException: The proxy tunnel request to proxy 'http://{ip}:8080/' failed with status code '403'."

```c#
    public sealed class AzureResourceOptions
    {
        public static AppClientConfigs ClientConfigs => App.GetConfig<AppClientConfigs>("AppClientConfigs");
        public static AzureSourceConfigs AzureResourceUris => App.GetConfig<AzureSourceConfigs>("AzureSourceConfigs");
        private static KustoConfigs KustoConfig => App.GetConfig<KustoConfigs>("KustoConfigs");
        public static ClientSecretCredential ClientSecretOptions
        {
            get
            {
                string proxyAddress = App.GetConfig<string>("MiddleServerProxy");
                HttpClientHandler httpClientHandler = new()
                {
                    Proxy = string.IsNullOrEmpty(proxyAddress) ? null : new WebProxy(proxyAddress),
                };
                var cred = new ClientSecretCredential(ClientConfigs.TenantID, ClientConfigs.AzureClientID, ClientConfigs.ClientSecret
                        , new ClientCertificateCredentialOptions()
                        {
                            AuthorityHost = new Uri(AzureResourceUris.AuthHost),
                            Transport = new HttpClientTransport(httpClientHandler),
                            SendCertificateChain = true
                        });
                return cred;
            }
        }
    
        public static KustoConnectionStringBuilder KustoConnectionBuilder
        {
            get => new KustoConnectionStringBuilder(KustoConfig.KustoConnectionString)
            {
                FederatedSecurity = KustoConfig.FederatedSecurity,
                ApplicationClientId = ClientConfigs.AzureClientID,
                ApplicationKey = ClientConfigs.ClientSecret,
                Authority = ClientConfigs.TenantID,
            }.WithAadAzureTokenCredentialsAuthentication(ClientSecretOptions);
        }

      // startup.cs 
      services.TryAddSingleton(iq =>
      {
            return KustoClientFactory.CreateCslQueryProvider(AzureResourceOptions.KustoConnectionBuilder);
      });

```

**Comment by jsquire** [comment]
Hi @lp956.  Thank you for reaching out and we regret that you're experiencing difficulties.  Unfortunately, the `Microsoft.Azure.Kusto.Data` package is not developed or supported from this repository, so we're unable to assist.  

One thing that I would note is that this appears to be an issue in your network environment with your proxy, which the error message seems to indicate requires some form of authorization.  As a result, I don't know that there is much that the authors of this package can do to assist.  In your code snippet, you are creating an instance of `WebProxy` but are not providing any credentials for it to use to authorize.  I'd suggest discussing with whomever in your organization is responsible for the network configuration and taking a look at [WebProxy.Credentials](https://learn.microsoft.com//dotnet/api/system.net.webproxy.credentials).  I would also suggest that you test [using the client options to configure a proxy](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/core/Azure.Core/samples/Configuration.md#configuring-a-proxy) rather than injecting a custom `HttpHandler` instance.

From its [NuGet page](https://www.nuget.org/packages/Microsoft.Azure.Kusto.Data), it appears that it is maintained by the Kusto team and does not appear to be open source.  If you decide that you're still in need of support, your best path forward would be to [open an Azure support request](https://docs.microsoft.com/azure/azure-portal/supportability/how-to-create-azure-support-request) to ensure the folks best able to assist are made aware.

**Comment by lp956** [comment]
> 

I understand, thanks for the reply
