### ISSUE TITLE
[QUERY] Intermittent slowness with Azure.ResourceManager.EventGrid

### ISSUE THREAD

**Issue by WTSParadigm** [Azure/azure-sdk-for-net#38519]
### Library name and version

Azure.ResourceManager.EventGrid 1.0.1

### Query/Question

I am trying to use the resource manager libraries to create some Event Grid Domains and Domain topics but am experiencing intermittent long delays in some of the calls. I'm trying to find out if I'm doing something wrong. I've had the following code take anywhere from 15 seconds to over 2 minutes, and that can be with no domains in the account or with a few. This is run from an Azure App Service where the service principal has the EventGrid Contributor role. There isn't a lot of documentation on this type of workflow so I've had to base it on the unit tests for these libraries.

```
ArmClient client = new(new DefaultAzureCredential());
var domains = await GetDomainsAsync(
    client: client,
    cancellationToken: cancellationToken);
EventGridDomainResource domain = await domains.GetAsync(
    domainName: domainTopicModel.DomainId,
    cancellationToken: cancellationToken);
if (domain == null)
{
    validationErrors.AddModelError(nameof(domainTopicModel.DomainId), $"No event grid domain found with name: {domainTopicModel.DomainId}");
    return null;
}
var domainTopics = domain.GetDomainTopics();

var newTopicResponse = await domainTopics.CreateOrUpdateAsync(
    waitUntil: WaitUntil.Started,
    domainTopicName: domainTopicModel.Id,
    cancellationToken: cancellationToken);
```

```
private async Task<EventGridDomainCollection> GetDomainsAsync(ArmClient client, 
      CancellationToken cancellationToken = default)
  {
      var subscriptions = client.GetSubscriptions();
      SubscriptionResource subscription = await subscriptions.GetAsync(
          subscriptionId: _azureSettings.SubscriptionId,
          cancellationToken: cancellationToken);
      var resourceGroups = subscription.GetResourceGroups();
      ResourceGroupResource resourceGroup = await resourceGroups.GetAsync(resourceGroupName: _azureSettings.ResourceGroupName,
          cancellationToken: cancellationToken);

      return resourceGroup.GetEventGridDomains();
  }
```

When I've run from code it seems like the loading of the resource group or domains can take the longest. Is there any way around this?

### Environment

.Net 7
Azure AppService (Linux)

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by ArthurMa1978** [comment]
Hey @WTSParadigm , thank you for reaching out to us about the Azure SDK for .NET. Unfortunately, this issue is related to the service side and not the SDK side, so we are not able to help you with it. Therefore, we are closing this issue for now. If you need more assistance, please [open an Azure support request](https://docs.microsoft.com/azure/azure-portal/supportability/how-to-create-azure-support-request). We apologize for any inconvenience this may cause you.

We value your feedback and we want to make sure that your problem is solved. If you think that we have misunderstood your issue or closed it incorrectly, please feel free to comment on this thread and reopen the issue. We will be happy to assist you further. Thank you for your understanding and cooperation.
