### ISSUE TITLE
[BUG] ACS Call Automation + Speech Recognition Error 401 Subcode 8565

### ISSUE THREAD

**Issue by romeroej-inch** [Azure/azure-sdk-for-net#38573]
### Library name and version

Azure.Communication.CallAutomation 1.1.0-beta.1

### Describe the bug

When using start_recognizing_media on a CallConnection, the server replies with the following error:

Action failed, cognitive services authentication error."  401 - Subcode 8565

or 

Action failed, forbidden request to cognitive services, free subscription used by the request ran out of quota.

403 - Subcode 8565

Both resources are S0 (ACS + Azure Multi Cog) and have been properly linked using the new interface.

The error started after feature moved from Private Preview to Public Preview. It was working properly before.

### Expected behavior

Speech Playback & Recognition works.

### Actual behavior

RecognizeFailed / PlayFailed

### Reproduction Steps

Start a Call or Answer a Call. Try to recognice voice or use Play for TTS.

 var recognize_result = await callConnectionMedia.StartRecognizingAsync(
                recognizeOptions
            );

### Environment

WebApp for Container - Net 7.0
Visual Studio Code

**Comment by romeroej-inch** [comment]
I was able to troubleshot this with the Engineering team. The issue was me not correctly setting the Voice (was sending blank). So the error is related to not using a proper neural voice but the log message is innapropiate.

**Comment by navba-MSFT** [comment]
@romeroej-inch Thanks for getting back. If you need any further assistance on this issue in future, please feel free to reopen this thread. We would be happy to help.

**Comment by JohnMelody** [comment]
I have a very similar issue with the Call Automation OpenAI_Sample in Java. I have simply downloaded the sample and built it and deployed it as a  Spring Application in my Azure environment. 

### Library Name and version.

Azure.Communication.CallAutomation 1.1.0 ( I updated the library - the download had a beta version initially but same issue with that)

### Problem Description 

I am getting a 401 with Subcode 8565 but the voice name is set to "en-US-NancyNeural". 

I have connected my ACS resource to my Cognitive Services resource as outlined in the documentation and it appears to be connected in ACS. 

When the incoming call arrives I get the following error: 
`023-11-24T12:27:25.042Z  INFO 1 --- [nio-8080-exec-7] c.c.callautomation.ProgramSample         : Call connected performing recognize for Call Connection ID: 411f3300-c0e2-4530-a4f1-a7e0d95e88ab
2023-11-24T12:27:25.637Z ERROR 1 --- [nio-8080-exec-9] c.c.callautomation.ProgramSample         : Received failed event: Action failed due to a Cognitive Services authentication error. Please check your authorization input and ensure it is correct.`

### Expected Behaviour
Plays a TTS message into the call and runs a recognition on the response 

### Additional Information 

The application.yml file has the following: 
`connectionstring: <ENTER YOUR ACS CONNECTION STRING>
  basecallbackuri: <ENTER YOUR DEV TUNNEL BASE URL>
  cognitiveServicesUrl: <ENTER YOUR COGNITIVE SERVICE URL>
  azureOpenAiServiceKey: <ENTER YOUR COGNITIVE SERVICE VAULT KEY>
  azureOpenAiServiceEndpoint: <ENTER YOUR COGNITIVE SERVICE URL>
  openAiModelName: <ENTER YOUR OPENAI MODEL NAME>`

There is no mention of the Cognitive Service "Key" - only the URL. It mentions a "Cognitive Service Vault Key" but that appears to be associated with the openai service key. I have added my cognitive services key to the url using the ?key= notation on the url but that makes no difference either. 

If I go into speech studio and try out speech recognition and tts using the cognitive resource used above everything works as expected.
