### ISSUE TITLE
[QUERY] What happens if two Eventhub Trigger Functions use one EventHubs consumer group？

### ISSUE THREAD

**Issue by SuyliuMS** [Azure/azure-sdk-for-net#38589]
### Library name and version

Microsoft.Azure.WebJobs.Extensions.EventHubs 5.0.0

### Query/Question

Hi, team,

According to [this doc](https://learn.microsoft.com/en-us/azure/event-hubs/event-hubs-features#consumer-groups), it says:

> in certain scenarios, you may use up to five consumers or receivers per partition where all receivers get all the events of the partition.

But in [this doc](https://learn.microsoft.com/en-us/azure/architecture/serverless/event-hubs-functions/performance-scale), it says:

> Don't share consumer groups between function apps and other consumer applications. Each function app should be a distinct application with its own assigned consumer group to ensure offset integrity for each consumer and to simplify dependencies in an event streaming architecture. Such a configuration, along with providing each event hub-triggered function its own function app and storage account, helps set the foundation for optimal performance and scaling.

It seems if the total Eventhub Trigger Functions are no more than 5, it would be fine to let them use one consumer group. I don't know if I understand correct, please help explain~~ Thanks~

**Comment by SuyliuMS** [comment]
Could you also please help explain, if an event hub trigger function instance undertakes excessive load, who will balance the work load?
And if the function instance just go down suddenly, who will discover and change this instance?

**Comment by jsquire** [comment]
To answer your section question first:  Azure Functions has scaling behavior that will add or remove instances based on load.  It does this by measuring the number of events that are waiting to be read and adjusting as your Function does its processing.    A good place for information is the [Target-based scaling](https://learn.microsoft.com/azure/azure-functions/functions-target-based-scaling?tabs=v5%2Ccsharp) documentation.  I would also recommend looking through the [Best practices for reliable Azure Functions](https://learn.microsoft.com/azure/azure-functions/functions-best-practices?tabs=csharp) documentation.

For the premise of your original question - **_you do not want to configure different Functions to use the same consumer group._**  The behavior will differ depending on what storage instance they're using:

- If using the same storage instance, the two Functions would coordinate such that each owns a unique set of partitions.  Each function instance would read only from the partitions that it owns and would not see events from other partitions.

- If not using the same storage instance, the two Functions would not be able to coordinate and would fight over partitions.  Since ownership would constantly cycle between them, you'd struggle to make forward progress and have extreme performance issues.
