### ISSUE TITLE
[BUG] MaxAutoLockRenewalDuration on Function's Service Bus Trigger Does Not Work

### ISSUE THREAD

**Issue by msbinli** [Azure/azure-sdk-for-net#38613]
### Library name and version

Azure.Messaging.ServiceBus (7.16.1)

### Describe the bug

With Service Bus trigger's "maxAutoLockRenewalDuration" configured to 100 days, there was one invocation almost every 1 minute. 

![image](https://github.com/Azure/azure-sdk-for-net/assets/14667962/bf7b46ef-7a12-4a3d-b9f4-bb38aad5ed86)

### Expected behavior

One invocation per Service Bus message, and that the peek lock is auto-renewed while the Function is running. 

### Actual behavior

One new invocation almost every 1 minute.

### Reproduction Steps

**Function signature**
[FunctionName("CollectorFunction_ServiceBusTriggered_Single")]
    public async Task RunAsync(
        [ServiceBusTrigger("jobtopic", "jobsubscription", Connection = "ServiceBusConnection_Jobs")]
        ServiceBusReceivedMessage message,
        ServiceBusMessageActions messageActions)
{
}

**host.json**
{
  "version": "2.0",
  "functionTimeout": "-1",
  "logging": {
    "logLevel": {
      "default": "Information"
    },
    "applicationInsights": {
      "samplingSettings": {
        "isEnabled": false,
        "excludedTypes": "Request"
      }
    }
  },
  "extensions": {
    "serviceBus": {
      "autoCompleteMessages": false,
      "maxAutoLockRenewalDuration":  "100.00:07:00"
    }
  }
}

### Environment

Windows, 
.Net stack
Function premium plan
VS

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by JoshLove-msft** [comment]
The issue here is that we call [CancellationTokenSource.CancelAfter](https://learn.microsoft.com/en-us/dotnet/api/system.threading.cancellationtokensource.cancelafter?view=net-7.0#system-threading-cancellationtokensource-cancelafter(system-timespan)) to handle the auto lock renewal. According to the docs, the method cannot be called with a TimeSpan having TotalMilliseconds greater than UInt32.MaxValue - 1, which works out to a little more than 49 days.


So effectively, you can't set the delay for longer than 49 days at least based on the current implementation of the SB extension.

**Comment by JoshLove-msft** [comment]
It looks like we could leverage Timeout.InfiniteTimeSpan which would be represented in config as
```
-00:00:00.0010000
```

It would require a few tweaks to the extension and the Service Bus library to allow this value, but it appears to work correctly with CancelAfter.
