### ISSUE TITLE
[QUERY] Reason why ProcessEventArgs is a struct instead of a record/class

### ISSUE THREAD

**Issue by sskorka** [Azure/azure-sdk-for-net#38663]
### Library name and version

Azure.Messaging.EventHubs

### Query/Question

Referring to [ProcessEventArgs.cs](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/eventhub/Azure.Messaging.EventHubs/src/Processor/ProcessEventArgs.cs).

This is a question of simple curiosity - is there any particular reason why `ProcessEventArgs` is a `struct`? What drives a decision to choose one over another in a case scenario like this? Various .NET `EventArgs` are classes, and my colleague and I have been wondering about this particular choice.

If performance is the main concern, and given that an enormous amount of eventargs objects are created every minute, would then heap allocation overhead significantly worsen the performance? On the other hand, aren't we risking blowing up the stack because of this? Or would JIT take care of this (still better than heap overhead?)

Perhaps this isn't even that big of a deal, I mean, we only store a boolean, two references, a token and a delegate. Surely that's small enough to warrant the use of a `struct`. And if event args contained data directly and have an arbitrary size, I assume this would immediately become a reference type. Or would it?

Apologies in advance, since I am not that familiar with the EventHub infrastructure, or maybe I have already answered myself, but it still felt like a good educational opportunity:-)

**Comment by jsquire** [comment]
Hi @sskorka.  Thank you for your inquiry.  `ProcessEventArgs` is a struct because:

- It allows for stack semantics and avoids heap allocations and garbage collection
- It is used heavily on a hot path in the code, where we expect a large number of instances to be created as part of normal operation
- It follows the [Azure SDK design guidelines](https://azure.github.io/azure-sdk/dotnet_introduction.html#dotnet-service-models-prefer-structs) for structs was advised by the architecture team
- It conforms to the characteristics advised by the [.NET design guidelines](https://learn.microsoft.com/en-us/dotnet/standard/design-guidelines/struct)

**Comment by sskorka** [comment]
Thanks a lot for the response, @jsquire, that does help. I was also not aware of Azure SDK design guidelines, which is something I was very much interested in.

Cheers!
