### ISSUE TITLE
[FEATURE REQ] Require Overload for QueryResourceAsync with QueryTimeRange as optional so that the time range can be included in the query

### ISSUE THREAD

**Issue by swathib-git** [Azure/azure-sdk-for-net#38707]
### Library name

Azure.Monitor.Query

### Please describe the feature.

As of now, the QueryResourceAsync method of the LogsQueryClient in Azure.Monitor.Query accepts the query and the time range separately.
It would be good to have an overload that accepts the time range as part of the query and hence the time range parameter can be ignored.

This will simplify automating the queries generation and avoid additional parsing to extract time range just for the need to pass it as a aparam

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by scottaddie** [comment]
@swathib-git We appreciate you creating this feature request. I regret to inform you that we've decided not to add the requested overload. Why? Our research has proven that most customers would use the overload you're proposing simply because it appears first in IntelliSense and requires one less argument. Customers then aren't forced to think about filtering by time range and therefore put excessive stress on the underlying service. This is the sole reason why the `timeRange` parameter was added.

The good news is that what you're hoping to accomplish is possible today. You'll want to pass `QueryTimeRange.All` for the `timeRange` parameter. Then include the time range filter in your Kusto query that you pass to the `query` parameter. I've attempted to explain the relationship between these 2 parameters in the linked PR.
