### ISSUE TITLE
Spelling error in CheckAvailabilityResult

### ISSUE THREAD

**Issue by vhe1** [Azure/azure-sdk-for-net#3873]
In https://github.com/Azure/azure-sdk-for-net/blob/3f736b5af3851ab99bbaa98483ae537de0d48cfb/src/SDKs/NotificationHubs/Management.NotificationHubs/Generated/Models/CheckAvailabilityResult.cs

The IsAvailiable property has one i too many.

**Comment by shahabhijeet** [comment]
https://github.com/Azure/azure-sdk-for-net/blob/3f736b5af3851ab99bbaa98483ae537de0d48cfb/src/SDKs/NotificationHubs/Management.NotificationHubs/Generated/Models/CheckAvailabilityResult.cs#L60

**Comment by adrianhall** [comment]
This is actually in the REST Swagger - see https://github.com/Azure/azure-rest-api-specs/blob/master/specification/notificationhubs/resource-manager/Microsoft.NotificationHubs/stable/2017-04-01/notificationhubs.json#L1589.  

Since it's an upstream issue, we can't fix it in the SDK (which is autogen from the swagger) - it needs to be fixed upstream.
