### ISSUE TITLE
[BUG] Relay sdk doesn't have option to Allow trusted Microsoft services

### ISSUE THREAD

**Issue by ashishranjan2011** [Azure/azure-sdk-for-net#38779]
### Library name and version

Azure.ResourceManager.Relay 1.1.1

### Describe the bug

RelayNetworkRuleSetData class doesn't have parameter to Allow trusted Microsoft services. From the portal there is the option.
![image](https://github.com/Azure/azure-sdk-for-net/assets/27609225/0d8ae224-c2dd-446e-9aae-c4a245001318)
 

### Expected behavior

.NET sdk should also have a parameter ( probably boolean ) to Allow trusted Microsoft services in relay firewall. 

### Actual behavior

TrustedServiceAccessEnabled this param is missing

### Reproduction Steps

Create a GetRelayNetworkRuleSet on relay namespace

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by ArthurMa1978** [comment]
Hey @ashishranjan2011 , thank you for reaching out to us about the Azure SDK for .NET. Unfortunately, this issue is related to the service side and not the SDK side which the [swagger spec](https://github.com/Azure/azure-rest-api-specs/blob/35215554aef59a30fa709e4b058931101a5ef26b/specification/relay/resource-manager/Microsoft.Relay/stable/2021-11-01/NetworkRuleSets.json) doesn't expose such option, so we are not able to help you with it. Therefore, we are closing this issue for now. If you need more assistance, please [open an Azure support request](https://docs.microsoft.com/azure/azure-portal/supportability/how-to-create-azure-support-request). We apologize for any inconvenience this may cause you.

We value your feedback and we want to make sure that your problem is solved. If you think that we have misunderstood your issue or closed it incorrectly, please feel free to comment on this thread and reopen the issue. We will be happy to assist you further. Thank you for your understanding and cooperation.
