### ISSUE TITLE
PartitionContext.PartitionId Data Type

### ISSUE THREAD

**Issue by TaffarelJr** [Azure/azure-sdk-for-net#38888]
### Library name and version

Azure.Messaging.EventHubs v5.9.3

### Query/Question

Is there a reason why the `PartitionContext.PartitionId` property is of type `string` instead of `int`?

My question applies specifically to the message consumer -- Every message _must_ come through a partition, so I imagine the property will _always_ be set to the `int` number of the partition in which the message was stored. Is that correct? Or is there a scenario where `null`, empty, or some other `string` value might come through that field?

I suppose the same question might be asked of the producer as well: I know the PartitionId can be specifically set, or left blank. Is there a reason why it's a `string` instead of a `Nullable<int>`?

### Environment

N/A

**Comment by jsquire** [comment]
> Is there a reason why the PartitionContext.PartitionId property is of type string instead of int?

Yes - because the service itself defines a partition identifier as an arbitrary string.  That they currently resemble integers is an implementation detail that may change and not part of the service contract.  It is not safe for the SDK nor an application using it to assume that these are numeric nor that they will follow a defined pattern.

**Comment by TaffarelJr** [comment]
Thanks very much for the quick reply!
