### ISSUE TITLE
[BUG] InternalServerError when creating a v4 function in Function App

### ISSUE THREAD

**Issue by yuramag** [Azure/azure-sdk-for-net#38929]
### Library name and version

Azure.ResourceManager.AppService

### Describe the bug

I have tried it both ways - via `Azure.ResourceManager.AppService` API and by sending an HTTP request to Azure REST API. Here is the REST example:

```
URL:
PUT https://management.azure.com/subscriptions/<my-subscription>/resourceGroups/<my-resource-group>/providers/Microsoft.Web/sites/<my-existing-function-app>/functions/test_func?api-version=2022-03-01

Body:
{
  "type": "Microsoft.Web/sites/functions",
  "location": "East US",
  "properties": {
    "name": "test_func",
	"config": {
      "name": "test_func",
      "entryPoint": "",
      "scriptFile": "test_func.js",
      "language": "node",
      "bindings": [
        {
          "authLevel": "function",
          "methods": [
            "POST"
          ],
          "type": "httpTrigger",
          "name": "httpTrigger1",
          "direction": "in"
        },
        {
          "type": "http",
          "name": "$return",
          "direction": "out"
        }
      ]
    },
  }	
}
```

I played with body content trying to randomly assign fields according to [this doc](https://learn.microsoft.com/en-us/rest/api/appservice/web-apps/get-function#functionenvelope), but I always get  a `BadRequest` error as such:

```
{
  "Code": "BadRequest",
  "Message": "Encountered an error (InternalServerError) from host runtime.",
  "Target": null,
  "Details": [
    {
      "Message": "Encountered an error (InternalServerError) from host runtime."
    },
    {
      "Code": "BadRequest"
    },
    {
      "ErrorEntity": {
        "Code": "BadRequest",
        "Message": "Encountered an error (InternalServerError) from host runtime."
      }
    }
  ],
  "Innererror": null
}
```

This error is not useful at all. I'd expect it to point to the actual reason of failure. Please advise or point to a working example of HTTP request to create a v4 function in Function App.

### Expected behavior

The error message should tell what exactly is wrong or missing.

### Actual behavior

Instead it reports a useless message about "InternalServerError".

### Reproduction Steps

1. Create a valid Function App
2. Send HTTP PUT request to https://management.azure.com specifying proper subscription, resource group, app name, etc.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by ArthurMa1978** [comment]
Thank you for reaching out to us about the Azure SDK for .NET. Unfortunately, this issue is related to the service side and not the SDK side, so we are not able to help you with it. Therefore, we are closing this issue for now. If you need more assistance, please [open an Azure support request](https://docs.microsoft.com/azure/azure-portal/supportability/how-to-create-azure-support-request). We apologize for any inconvenience this may cause you.

We value your feedback and we want to make sure that your problem is solved. If you think that we have misunderstood your issue or closed it incorrectly, please feel free to comment on this thread and reopen the issue. We will be happy to assist you further. Thank you for your understanding and cooperation.
