### ISSUE TITLE
[BUG] Azure Front Door CDN Storage Account Auth Error (Related to 34808)

### ISSUE THREAD

**Issue by realchrisparker** [Azure/azure-sdk-for-net#38951]
### Library name and version

N/A

### Describe the bug

Created an Azure Front Door, create a CDN that points to my storage account. Storage account has a container that allows public access to blobs. I get this error when trying to view an image using the CDN link.

`
<Error>
<Code>AuthorizationFailure</Code>
<Message>This request is not authorized to perform this operation. RequestId:6daef3bc-f01e-0044-6630-f07c01000000 Time:2023-09-26T04:17:37.0585941Z</Message>
</Error>
`

Image is viewable using the direct storage account link. Related to issue [34808](https://github.com/Azure/azure-sdk-for-net/issues/34808)

### Expected behavior

View cached image using CDN link.

### Actual behavior

Following error shows in the browser.

`
<Error>
<Code>AuthorizationFailure</Code>
<Message>This request is not authorized to perform this operation. RequestId:6daef3bc-f01e-0044-6630-f07c01000000 Time:2023-09-26T04:17:37.0585941Z</Message>
</Error>
`

### Reproduction Steps

Attempt to view image in browser and receive errro.

### Environment

Azure Front Door
Azure Storage Account with contaniner with public blob access.

**Comment by jsquire** [comment]
Hi @realchrisparker.  Thank you for reaching out and we regret that you're experiencing difficulties.  If I understand correctly, you are inquiring about the behavior of a Front Door resource that you created unrelated to one of the Azure SDK packages.  Unfortunately, this repository is focused on the Azure SDK for .NET and we're unable to assist with other issues.  

Since what you're describing appears to be related to the Front Door service itself, your best path forward would be to [open an Azure support request](https://docs.microsoft.com/azure/azure-portal/supportability/how-to-create-azure-support-request).  I'm going to close this out; if I've misunderstood what you're describing, please let us know in a comment and we'd be happy to assist as we're able.
