### ISSUE TITLE
[Feature Request] Compacted Eventhub Events with EntityKey and PartitionKey

### ISSUE THREAD

**Issue by AJosephsen** [Azure/azure-sdk-for-net#38964]
### Library name

Azure.Messaging.EventHubs

### Please describe the feature.

**Send events with a partition key to a specific partition (set both PartitionKey and PartitionID)**

Or be able to specify a PartitionKey and EntityKey 

Example we want all Account entities to be partitioned by ClientKey, so that all accounts for the same client are on the same partition. At the same time we compaction to happen on the AccountKey so that we only store the latest Account Event

**Comment by jsquire** [comment]
Hi @AJosephsen.  Thank you for your feedback and we regret that you're experiencing difficulties.  The limitation of being unable to publish an event using both the partition identifier and key is due to how the Event Hubs service works and is not something that the client library can influence.   Compaction itself requires that events be published using a partition key which, again, is service behavior and not something under control of the client.  

Because your inquiry is regarding behavior of the Event Hub service, your best path forward would be to [open an Azure support request](https://docs.microsoft.com/azure/azure-portal/supportability/how-to-create-azure-support-request) or use the [Event Hubs topic of the Azure Feedback site](https://feedback.azure.com/d365community/forum/86c37ae9-7526-ec11-b6e6-000d3a4f032c) to make a feature suggestion.
