### ISSUE TITLE
ActiveMessageCount property missing in TopicRuntimeProperties class for Azure.Messaging.ServiceBus.Administration nuget package

### ISSUE THREAD

**Issue by azad1612** [Azure/azure-sdk-for-net#39152]
Hi
I am using Azure.Messaging.ServiceBus nuget package and below property are missing in TopicRuntimeProperties class 

1. ActiveMessageCount
2. DeadLetterMessageCount
3. TransferMessageCount
4. TransferDeadLetterMessageCount

Please suggest me how can I get above properties of Topic

**Comment by jsquire** [comment]
Hi @azad1612.  Thank you for reaching out and we regret that you're experiencing difficulties.  Unfortunately, the information that you're looking for is not returned by the Service Bus service.   Since the feature that you're requesting is related to the service and not the Azure SDK package, we're unable to assist in this repository.  Your best path forward would be to [open an Azure support request](https://docs.microsoft.com/azure/azure-portal/supportability/how-to-create-azure-support-request) or submit your feedback on the [Service Bus forum of the Azure Feedback site](https://feedback.azure.com/d365community/forum/7c0a897d-2125-ec11-b6e6-000d3a4f0f84).

I'm going to close this out; if I've misunderstood what you're describing, please let us know in a comment and we'd be happy to assist as we're able.

**Comment by azad1612** [comment]
Hi @jsquire Thank for responding. To elaborate this issue, Currently I am migrating Microsoft.Azure.ServiceBus SDK to Azure.Messaging.ServiceBus sdk. but in new sdk we are not getting property ActiveMessageCount, DeadLetterMessageCount, TransferMessageCount, TransferDeadLetterMessageCount Azure.Messaging.ServiceBus for topicproperies.

**Comment by jsquire** [comment]
The legacy library uses endpoints specific to SBMP, which is a deprecated protocol and not something that newer libraries are permitted to interact with.   For the client to surface this information, it would need to be exposed by the service either via the AMQP runtime properties operation or the Atom-based administration endpoints.
