### ISSUE TITLE
[FEATURE REQ] Use Exists() in CreateIfNotExists() implementation to optimize storage costs

### ISSUE THREAD

**Issue by JeffreyCA** [Azure/azure-sdk-for-net#39182]
### Library name

Azure.Storage.Blobs

### Please describe the feature.

With how storage calls are billed, read operations are much cheaper than write/create operations, so I think there's room for calls like CreateIfNotExists() to be optimized by using Exists() under the hood, which counts as a read.

So instead of something like:

```cs
try
{
    response = await CreateInternal(...);
}
catch (RequestFailedException storageRequestFailedException)
when (storageRequestFailedException.ErrorCode == BlobErrorCode.ContainerAlreadyExists)
{
    response = default;
}
```

By simply adding an Exists call we can potentially avoid a CreateContainer call:

 ```cs
if (await Exists(...))
{
    response = default;
    return;
}

// Existing logic the same due to possibility of race conditions
try
{
    response = await CreateInternal(...);
}
catch (RequestFailedException storageRequestFailedException)
when (storageRequestFailedException.ErrorCode == BlobErrorCode.ContainerAlreadyExists)
{
    response = default;
}
```

Is this optimization reasonable? Are there any flaws with this approach?

**Comment by pallavit** [comment]
Thank you for reporting the issue. Tagging the team best able to assist you here.
/cc: @seanmcc-msft

**Comment by amnguye** [comment]
Some issues with this approach
1. This would be a behavior breaking change. Customers who once expected only 1 Create request to go out, will now have to account to 2 requests going out (Get Properties, then Create)
2. There are customers who would argue that the current approach is preferred because another extra request, would be slower more prone to latency

I do see the optimization in billing, that a Get Properties request is cheaper however, a better alternative would just to be to call `Exists` then `Create`, that way it's clear that two requests are going out, on top of which requests are going out to better maintain billing.
