### ISSUE TITLE
[BUG] Exception during retrieving ServerCallId from the CommunicationCall object

### ISSUE THREAD

**Issue by ultrasimulation** [Azure/azure-sdk-for-net#39310]
### Library name and version

Azure.Communication.Calling.WindowsClient 1.3.0-beta.2

### Describe the bug

I am using the Windows "Calling" Client of Azure Communication Service, after I start successful a call via the CallAgent:

`CommunicationCall communicationCall = await this.callAgent.StartCallAsync(new[] { new UnknownCallIdentifier(currentUsername) }, options);
Console.WriteLine(communicationCall.Id)
string currentServerCallId = await communicationCall.Info.GetServerCallIdAsync();`

The call is placed and a communicationCall.Id is generated. Then I need the ServerCallId but the last line always fails with the following error:
Exception thrown at 0x00007FFF4B994FFC in Application.exe: Microsoft C++ exception: winrt::hresult_error at memory location 0x000000C1E5BFF928.

The "Info" object of CommunicationCall was introduced with the version "1.3.0-beta.XX" and not present in the stable version "1.2.0".

### Expected behavior

The "communicationCall.Info.GetServerCallIdAsync()" should return the Server Call ID

### Actual behavior

An exception is raised:
Exception thrown at 0x00007FFF4B994FFC in Application.exe: Microsoft C++ exception: winrt::hresult_error at memory location 0x000000C1E5BFF928.

### Reproduction Steps

Start with the "CallingWinUI" quickstart:
https://github.com/Azure-Samples/communication-services-dotnet-quickstarts/tree/main/CallingWinUI

Update the code in order to call the method:
communicationCall.Info.GetServerCallIdAsync()

on the "CommunicationCall" object.

**Comment by scottaddie** [comment]
@gaobob-msft @jowang-msft Please review.

**Comment by ultrasimulation** [comment]
Hello, do you have an update about the issue? Thank you

**Comment by jowang-msft** [comment]
Hi @ultrasimulation,

I tried 1.3.0-beta.2 and it appeared working.

The CommunicationCall object is only going to reach a "_ready_" state after your code receives `StateChanged` event, informing the call has reached `CallState.Connected` state. Because the underlying call object is still transitioning asynchronously to a connected state, depending on how soon the callee responded to the call. Therefore, you can't reliably access the server id using the call object you received from calling `StartCallAsync()`. I recommend you modify your code to fetch the server call id in response to the StateChanged event::


`        private async void OnStateChangedAsync(object sender, PropertyChangedEventArgs args)
        {
            var call = sender as CommunicationCall;

            if (call != null)
            {
                var state = call.State;

                switch (state)
                {
                    case CallState.Connected:
                        {
                            var sid = await call.Info.GetServerCallIdAsync();  // This should work
` 

Please let us know. Thanks.

**Comment by ultrasimulation** [comment]
Hello @jowang-msft  thank you for your reply. I tested your code and it works good. I didn't find any documentation of that API (call.Info.GetServerCallIdAsync()) that seems is introduced in the new Beta versions of the client and the exception message was not talking at all. So I didn't know that I should soubscribe to that event.
I would suggest documenting its usage and/or raising an interpretable exception.

Thank you again
