### ISSUE TITLE
[QUERY] Cannot All TrafficeManagerEndpoints Data

### ISSUE THREAD

**Issue by Ptnan7** [Azure/azure-sdk-for-net#39417]
### Library name and version

Azure.ResourceManager.TrafficManager

### Query/Question

I am using this lib to create 2 apis, one for query a singge endpoint data with type and key
`NullableResponse<TrafficManagerEndpointResource> response = collection.Get(parameterMap[EndpointTypeKey], parameterMap[EndpointNameKey]);`

and the other is the get all data 

```
            var collection = trafficManagerProfile.GetTrafficManagerEndpoints();
            var res = collection.GetAll().ToList();
```

I test them with the same sub, rg and cluster name, the first test can pass but the second one all always returns

`The method can work only when the profileData is provided over ctor`

since the first test is OK, I assume that this cluster is not empty, so I don't know why this exception throws, is my way to get all endpoint data wrong? 

### Environment

Linux, net framework 4.6.2

**Comment by webbsk** [comment]
I'm seeing this same issue.

**Comment by dvbb** [comment]
Hi, @Ptnan7

You can see all the interfaces of a service through the [REST API documentation](https://learn.microsoft.com/en-us/rest/api/trafficmanager/endpoints?view=rest-trafficmanager-2022-04-01). 

However, due to design consistency, the Dotnet SDK has added an additional `GetAll` method, but it does not work. 

Apologize for causing you confusion.
