### ISSUE TITLE
[BUG] Key Vault adding escape characters on secret values.

### ISSUE THREAD

**Issue by mahesh139** [Azure/azure-sdk-for-net#39434]
### Library name and version

Azure.Security.KeyVault.Secrets 4.5.0

### Describe the bug

Key Vault secret value of **Pass\Word** comes out as **Pass\\\Word**

![image](https://github.com/Azure/azure-sdk-for-net/assets/11797119/07ea6307-0bcc-4286-9db8-df0708767bd1)

![image](https://github.com/Azure/azure-sdk-for-net/assets/11797119/64c20c8d-6243-4bf9-89e6-1e7365ffaac1)

![image](https://github.com/Azure/azure-sdk-for-net/assets/11797119/662ca25c-2a22-406e-a797-1a8bc9d52d5f)

### Expected behavior

Key Vault secret value of **Pass\Word** should not have escape character when read from configuration.

### Reproduction Steps

Please see attached screenshots.

### Environment

.Net 7

Azure.Security.KeyVault.Secrets 4.5.0

**Comment by heaths** [comment]
A backslash in most languages is an escape (control) character, so it has to be escaped to allow a `\` in your input. The portal or service is doing exactly that.

<img width="334" alt="image" src="https://github.com/Azure/azure-sdk-for-net/assets/1532486/f217ba88-918a-4b67-beed-95a0ebcd5d20">

<img width="849" alt="image" src="https://github.com/Azure/azure-sdk-for-net/assets/1532486/4df8a3b6-c762-45fd-9beb-2458d91e25e3">

`\W` is not a valid escape sequence, so I'm not aware of any way you could set that as a value and have it be valid. Secrets are strings and have to be encoded as proper strings or be rejected. If you really what invalid string sequences you'll have to base64 encode a byte array and store the base64-encoded value as a string, then base64 decode it when getting the secret.

The same is true in reverse for `\`: the debugger is showing `\\` (as does the Azure CLI and more) to make it a proper string. If you copied and pasted the value without the escaped `\` (as `\\`) into C# source, the compiler would err since `\W` is invalid.
