### ISSUE TITLE
Tracing: uber [Ge] task

### ISSUE THREAD

**Issue by lmolkova** [Azure/azure-sdk-for-net#39432]
GA tracing for HTTP and HTTP-based SDKs:

- [x] #39429
- [x] #39430
- [x] #39431
- [x] #31921
- [x] #30711
- [ ] #37446 - need to solve it in OTel/.NET, @lmolkova will follow-up

Messaging:
- [x] #39166
- [ ] #39450
- [ ] docs, dashboards, etc  as a part of #37698 

OpenAI:
- [ ] #39451

**Comment by christothes** [comment]
There are possibly some opportunities for Azure.Identity and tangentially Azure.Core for token acquisition we might add:

[BearerTokenAuthenticationPolicy](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/core/Azure.Core/src/Pipeline/BearerTokenAuthenticationPolicy.cs) logging true cache misses (this is nuanced due to background token refreshing).

[DefaultAzureCredential](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/identity/Azure.Identity/src/Credentials/DefaultAzureCredential.cs) chain traversal and credential selection durations.

**Comment by lmolkova** [comment]
Closing in favor of https://github.com/Azure/azure-sdk-for-net/issues/46018
