### ISSUE TITLE
How to filter autocomplete (Azure cognitive Search)

### ISSUE THREAD

**Issue by MohammadBoushi** [Azure/azure-sdk-for-net#39446]
### Library name and version

Azure.Search.Documents 11.4.0

### Query/Question

Hi There,
i want to filter the suggestions of cognitive search depending on the permissions.
All items in the index have this object.

```
 "permissions": {     
   "readitem": ";test1@test.com;;test2@test.com;;test3@test.com;",  
    "readlist": ";test1@test.com;;test2@test.com;;test3@test.com;" 
   },
```
If the email of the user is one of the emails in the readitem, then he is allowed to see only the suggestions of the items that have his email.

I'm trying to use search.ismatch("[test1@test.com](mailto:test1@test.com)|[test2@test.com](mailto:test2@test.com)|[test3@test.com](mailto:test3@test.com)",permissions/readitem) like that.
 

 ```
SuggestOptions sp = new SuggestOptions()      
  {            UseFuzzyMatching = query.Fuzzy,
               Size = 10, 
               Filter = "search.ismatch(\"test1@test.com|test2@test.com|test3@test.com\",permissions/readitem)"  
  };
```
but search.ismatch is only supported in the Search API, and I have tried to use odata-filter-expr, but it works only with arrays.

Is there any way to overcome this?

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by mattmsft** [comment]
hello @MohammadBoushi ,

1. We don't recommend storing permissions in complex types. Please see this guide for a recommendation on how to structure permissions. https://learn.microsoft.com/en-us/azure/search/search-security-trimming-for-azure-search
2. You can use the odata filter syntax with suggest instead of search.ismatch once you've structured your permissions as an array of strings. Here's an example

```
{
   "filter":"group_ids/any(g:search.in(g, 'group_id1, group_id2'))"  
}
```

I hope this helps.
