### ISSUE TITLE
[BUG] Internal Error with AsPages Method not found Exception

### ISSUE THREAD

**Issue by yossika-tr** [Azure/azure-sdk-for-net#39465]
### Library name and version

Azure.Security.KeyVault.Secrets 4.5.0.0 
Azure.Extensions.AspNetCore.Configuration.Secrets 1.2.2

### Describe the bug

our team moved from connecting directly to Azure Key Vault to use the nuget package Azure.Extensions.AspNetCore.Configuration.Secrets and use the AddAzureKeyVault(URI, AzureCredential) method.
when we did that the app threw the following exception: Method 'AsPages' in type 'FuncAsyncPageable`1' from assembly 'Azure.Security.KeyVault.Secrets, Version=4.5.0.0, Culture=neutral, PublicKeyToken=92742159e12e44c8' does not have an implementation.
attempts to reduce Azure.Security.KeyVault.Secrets to 4.3 and 4.2 did not help.
we also found this error in another open issue without solution: https://github.com/Azure/azure-functions-host/issues/9127

### Expected behavior

the expected beheviour it that we will manage to connect 

### Actual behavior

internal exception is thrown

### Reproduction Steps

remove all non microsoft related nuget packages - yet still the issue reproduces
it has not reproduced on other services 

### Environment

.net 6 (migration from .net 4.6.2)

**Comment by ewwwgiddings** [comment]
Can someone from Azure comment on all these issues. A lot of us are facing it for months doing silly work arounds and no one from Azure seems to care.

**Comment by jsquire** [comment]
Hi @yossika-tr.  Thank you for reaching out and we regret that you're experiencing difficulties.  The issue that you've linked is related to the Azure Functions in-process hosting model and its dependencies.  There's not enough context available to be able to comment on whether this may be the same scenario or not.  

Would you please let us know:

- The full text of the error message.
- The full stack trace of the exception.
- Is this an Azure Function or a custom app?
- If a custom application, can you share how you're using the Azure SDK package and where the error is observed?

That should help us be able to get started and understand the folks that are needed to provide assistance.

**Comment by ewwwgiddings** [comment]
@jsquire the error he linked has lots of discussion and full error stacks from multiple people: https://github.com/Azure/azure-functions-host/issues/9127 ( @yossika-tr I don't want to hijack your bug post just wanted to bring attention there to maybe save some effort of reposting stack traces and such if it is the same )

**Comment by jsquire** [comment]
@ewwwgiddings: The linked issue is specific to the Azure Functions host environment for its in-process model.  That may or may not be relevant to this issue.  Once the author has provided the requested context, we can determine next steps that need to be taken here.

**Comment by jsquire** [comment]
> @jsquire I get that but he did say specifically `we also found this error in another open issue without solution` and in that issue he was asking for answers as well (and it's still lacking any real help from Azure)

@ewwwgiddings: I understand your frustration, but the owners of the Azure SDK and the owners of the Azure Functions runtime are two different teams.  The Azure SDK team does not have insight nor influence over the Functions runtime or related issues.  As a result, the linked issue and its current status are outside of our insight and control.  The best place to seek assistance with that issue is in the repository that it is hosted in - it is not something that we can help with.

**Comment by yossika-tr** [comment]
@jsquire i added the linked issue as it involved the same error exactly.
also, when running the app locally with VS - no error
now to your questions: 

**Is this an Azure Function or a custom app?**
my app is a self hosted server app, not function, that runs on AKS. 

**If a custom application, can you share how you're using the Azure SDK package and where the error is observed?**
i will share the file and methods we use - but its pretty much taken from the basic tutorial
(please also note the comment i added there as it relates to the same issue)
[initConfig.txt](https://github.com/Azure/azure-sdk-for-net/files/13120971/initConfig.txt)

 **The full text of the error message.**
"Method 'AsPages' in type 'FuncAsyncPageable`1' from assembly 'Azure.Security.KeyVault.Secrets, Version=4.5.0.0, Culture=neutral, PublicKeyToken=92742159e12e44c8' does not have an implementation."

**The full stack trace of the exception.**
"   at Azure.Core.PageResponseEnumerator.CreateAsyncEnumerable[T](Func`2 pageFunc) in /_/sdk/core/Azure.Core/src/Shared/PageResponseEnumerator.cs:line 26\r\n   at Azure.Security.KeyVault.Secrets.SecretClient.GetPropertiesOfSecretsAsync(CancellationToken cancellationToken) in /_/sdk/keyvault/Azure.Security.KeyVault.Secrets/src/SecretClient.cs:line 211\r\n   at Azure.Extensions.AspNetCore.Configuration.Secrets.AzureKeyVaultConfigurationProvider.<LoadAsync>d__11.MoveNext() in /_/sdk/extensions/Azure.Extensions.AspNetCore.Configuration.Secrets/src/AzureKeyVaultConfigurationProvider.cs:line 82\r\n   at Azure.Extensions.AspNetCore.Configuration.Secrets.AzureKeyVaultConfigurationProvider.Load() in /_/sdk/extensions/Azure.Extensions.AspNetCore.Configuration.Secrets/src/AzureKeyVaultConfigurationProvider.cs:line 56\r\n   at Microsoft.Extensions.Configuration.ConfigurationManager.AddSource(IConfigurationSource source)\r\n   at Microsoft.Extensions.Configuration.ConfigurationManager.Microsoft.Extensions.Configuration.IConfigurationBuilder.Add(IConfigurationSource source)\r\n   at Microsoft.Extensions.Configuration.AzureKeyVaultConfigurationExtensions.AddAzureKeyVault(IConfigurationBuilder configurationBuilder, SecretClient client, AzureKeyVaultConfigurationOptions options) in /_/sdk/extensions/Azure.Extensions.AspNetCore.Configuration.Secrets/src/AzureKeyVaultConfigurationExtensions.cs:line 107\r\n   at Microsoft.Extensions.Configuration.AzureKeyVaultConfigurationExtensions.AddAzureKeyVault(IConfigurationBuilder configurationBuilder, Uri vaultUri, TokenCredential credential, KeyVaultSecretManager manager) in /_/sdk/extensions/Azure.Extensions.AspNetCore.Configuration.Secrets/src/AzureKeyVaultConfigurationExtensions.cs:line 47\r\n   at Microsoft.Extensions.Configuration.AzureKeyVaultConfigurationExtensions.AddAzureKeyVault(IConfigurationBuilder configurationBuilder, Uri vaultUri, TokenCredential credential) in /_/sdk/extensions/Azure.Extensions.AspNetCore.Configuration.Secrets/src/AzureKeyVaultConfigurationExtensions.cs:line 30\r\n   at MarketMaker.Host.Program.InitAzureConfig(WebApplicationBuilder builder)"

if you can provide me an upload link i can share a dump file i took that will show the exact error.

**Comment by jsquire** [comment]
Thanks, @yossika-tr.   That gives us just about enough to try and repro.   Would you also share the list of packages that your app is referencing?

**Comment by jsquire** [comment]
@JoshLove-msft:  This appears to be reproducible in a stand-alone app.  Would you mind taking a look from the extensions perspective?

**Comment by yossika-tr** [comment]
here are the list of packages we use:
<ItemGroup>
		<PackageReference Include="Azure.Core" Version="1.32.0" />
		<PackageReference Include="Azure.Extensions.AspNetCore.Configuration.Secrets" Version="1.2.2" />
		<PackageReference Include="Azure.Identity" Version="1.8.0" />
		<PackageReference Include="Microsoft.ApplicationInsights" Version="2.21.0" />
		<PackageReference Include="Microsoft.ApplicationInsights.AspNetCore" Version="2.21.0" />
		<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="6.0.15" />
		<PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="6.0.16" />
		<PackageReference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" Version="6.0.15" />
		<PackageReference Include="Microsoft.Azure.AppConfiguration.AspNetCore" Version="6.0.1" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="6.0.16" />
		<PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="6.0.0" />
		<PackageReference Include="Microsoft.NETCore.Platforms" Version="7.0.2" />
		<PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.17.0" />
		<PackageReference Include="Swashbuckle.AspNetCore" Version="6.5.0" />
	</ItemGroup>

**Comment by jsquire** [comment]
Hi @yossika-tr.   I'm unable to reproduce the behavior that you're reporting with the packages and sample code that you shared.  

The code that was shared does not compile using just the packages from that list - it appears that some are missing.  For example, I had to add `Microsoft.Extensions.Azure` and `Azure.Security.KeyVault.Certificates` just to get to a compliable state.  There's also nothing in that list that references `Azure.Security.KeyVault.Secrets` v4.5.0 from your error message, so that is either a direct reference or a transitive dependency of another package not included.   **_I also want point out that the version of Azure.Identity that you're referencing is quite old and has a known severe security issue._**  We would strongly suggest upgrading to the latest.

Generally, the class of error that you're seeing is related to version conflicts that cause a version to be loaded that is older than a component needs.  As a result, isolating the exact packages and environment is often necessary to reproduce and diagnose.  **Since you are able to reproduce, would you be willing to share a minimal self-contained app that reproduces the behavior?**

In the meantime, if you are willing, I'd like to suggest that we try a bit of version tweaks to see if we can force versions into alignment.   Would you please try adding direct references to the following in your application:

- Azure.Core v1.35.0
- Azure.Identity  v1.10.3
- Azure.Security.KeyVault.Secrets v4.5.0
- Azure.Security.KeyVault.Certificates v4.5.1
- Azure.Data.AppConfiguration v1.2.1
- Microsoft.Extensions.Azure v1.7.0
- Azure.Extensions.AspNetCore.Configuration.Secrets v1.2.2

That will hoist each Azure package to the latest, forcing all of the transitive dependencies to align.

**Comment by yossika-tr** [comment]
@jsquire as i mentioned, i will share the actual app dump file that replicates the exact exception im getting for your review
all i need is a link to upload the dump file to 
the strangest thing here is that we also didn't manage to reproduce it on other apps so its very unclear where the origin of this error comes from
i will also try to upgrade again based on your recommendations but on my app the packages i sent were all we got from nuget in order to build and run the app

**Comment by jsquire** [comment]
@yossika-tr:  Unfortunately, a dump file is not particularly helpful in this case.   In this case, the missing method is an internal class exists directly in the KeyVault library itself.  The root cause for these is that the .NET assembly resolution/load process does not pull in the version of a library expected by the application or one of its components and the location of a callable is different than expected.   [Logs from the assembly load process](https://learn.microsoft.com/dotnet/core/dependency-loading/collect-details) may be helpful, though usually it is a more expedient path to do some testing by pinning versions in the application via direct reference to force a known version.    

To do so requires that the issue can be reproduced, tested, and tweaked to isolate the exact conflict causing the issue.  This can be difficult, as the issue is often specific to a given application and environment.  This far, all of our attempts to reproduce have failed.  To move forward, we'll need to be able to do so.   As mentioned, it appears that the information shared with us is incomplete - given the full set of packages that was used with the code may help, or it may not.   The best chance for reliable repro may be to strip down your application to just the path that causes this, leaving the full set of referenced packages, and share that as minimal repro.   

If that is not appealing, moving forward with my suggestion on which versions to pin in the application and seeing if that resolves the issue may help to narrow things down.  If that resolves the issue, we can start to remove direct references one-by-one until we find the culprit or we would know that it isn't specific to an Azure package.

**Comment by ewwwgiddings** [comment]
We found the same issue as @yossika-tr when he said: "the strangest thing here is that we also didn't manage to reproduce it on other apps so its very unclear where the origin of this error comes from"

We have two apps with identical Nuget packages and one of them gave us this error (until the work around I mentioned in the duplicate bug report mentioned in this) and one of them didn't.

**Comment by yossika-tr** [comment]
hey @jsquire 
so based on your latest post i created a .nettrace file. 
what i did was creating some sort of delay in the app before the call to azure which causes the error happens and also a delay on the exception handling so i could collect the file from the container
[trace.zip](https://github.com/Azure/azure-sdk-for-net/files/13189678/trace.zip)

attaching it here for review

**Comment by yossika-tr** [comment]
also, when i ran the app - here is the list of packages i was using:
[packages.txt](https://github.com/Azure/azure-sdk-for-net/files/13189720/packages.txt)

**Comment by piotrbugla** [comment]
Also have the same issiue in Azure Container Apps. Anyone was able to find solution of workaround?

```
Unhandled exception. System.TypeLoadException: Method 'AsPages' in type 'FuncAsyncPageable`1' from assembly 'Azure.Data.AppConfiguration, Version=1.2.0.0, Culture=neutral, PublicKeyToken=92742159e12e44c8' does not have an implementation.
at Azure.Core.PageResponseEnumerator.CreateAsyncEnumerable[T](Func`2 pageFunc)
at Azure.Data.AppConfiguration.ConfigurationClient.GetConfigurationSettingsAsync(SettingSelector selector, CancellationToken cancellationToken)
at Microsoft.Extensions.Configuration.AzureAppConfiguration.AzureAppConfigurationProvider.<>c__DisplayClass29_1.<<LoadSelectedKeyValues>b__1>d.MoveNext()
--- End of stack trace from previous location ---
at Microsoft.Extensions.Configuration.AzureAppConfiguration.TracingUtils.CallWithRequestTracing(Boolean tracingEnabled, RequestType requestType, RequestTracingOptions requestTracingOptions, Func`1 clientCall)
at Microsoft.Extensions.Configuration.AzureAppConfiguration.AzureAppConfigurationProvider.LoadSelectedKeyValues(ConfigurationClient client, CancellationToken cancellationToken)
at Microsoft.Extensions.Configuration.AzureAppConfiguration.AzureAppConfigurationProvider.<>c__DisplayClass28_0.<<InitializeAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
at Microsoft.Extensions.Configuration.AzureAppConfiguration.AzureAppConfigurationProvider.<>c__DisplayClass41_0.<<ExecuteWithFailOverPolicyAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
at Microsoft.Extensions.Configuration.AzureAppConfiguration.AzureAppConfigurationProvider.ExecuteWithFailOverPolicyAsync[T](IEnumerable`1 clients, Func`2 funcToExecute, CancellationToken cancellationToken)
at Microsoft.Extensions.Configuration.AzureAppConfiguration.AzureAppConfigurationProvider.ExecuteWithFailOverPolicyAsync(IEnumerable`1 clients, Func`2 funcToExecute, CancellationToken cancellationToken)
at Microsoft.Extensions.Configuration.AzureAppConfiguration.AzureAppConfigurationProvider.InitializeAsync(Boolean ignoreFailures, IEnumerable`1 availableClients, CancellationToken cancellationToken)
at Microsoft.Extensions.Configuration.AzureAppConfiguration.AzureAppConfigurationProvider.Load()
Microsoft.Extensions.Configuration.ConfigurationManager.AddSource(IConfigurationSource source)
at Microsoft.Extensions.Configuration.ConfigurationManager.Microsoft.Extensions.Configuration.IConfigurationBuilder.Add(IConfigurationSource source)
at Microsoft.Extensions.Configuration.AzureAppConfigurationExtensions.AddAzureAppConfiguration(IConfigurationBuilder configurationBuilder, Action`1 action, Boolean optional)
at Program.<Main>$(String[] args)
```

**Comment by jsquire** [comment]
@yossika-tr : Thank you for sharing the trace and the additional package list.  The traces confirm that the expected versions of Azure libraries were loaded into the primary AppDomain and that the known down-level references were resolved to the pinned versions.  There also appear to be number of other dependencies for the app, many of which look like other internal packages or potentially projects in the solution.  

Unfortunately, that has not given any further hints to the root cause nor insight into how to reproduce.  We continue to be unable to reproduce the error across different target frameworks, project types, and host environments - including the container-based hosts mentioned by folks commenting on this issue.   

At this point, we're effectively blocked without repro.   Our best hope is that one of the folks who is experiencing this error can share a small, self-contained project that reproduces the error so that we can analyze.

**Comment by yossika-tr** [comment]
@jsquire so what you are saying is - we know there is an issue, we cannot reproduce it so we will just keep it as is and maybe someday we will manage to figure out what and fix it?
this is why i offered the dump file - maybe someone can debug it and understand this issue...
could you at least not deprecate the previous packages as it seems that in the Azure Function issue i shared with you in the beginning of this feed the user did manage to find a workaround with that deprecated package.....
and maybe even add to those deprecated packages similar functionality so we can use those as well?

thanks

**Comment by jsquire** [comment]
@yossika-tr:  I understand your frustration and apologize for the poor experience that you're having.  We have had several engineers looking at this and attempting to find a way to reproduce.  Unfortunately, until we are able to do so, we're blocked on being able to assist.  

To clarify, at this point what we know is that the issue you're experiencing is not something specific to a single Azure SDK package nor an obvious scenario of using a set of Azure SDK packages together.  This is a scenario that exists for a small number of specific applications and based on similar issues, is believed to be associated with a specific combination of transitive dependencies and host environments.   We do not know exactly what the scenario is, nor how to trigger it for debugging and live analysis.

If you'd like us to look at the dump you've collected, we'd be happy to do so.  Historically, based on similar issues, dump analysis did not provide any additional insights, but perhaps this is an exception.  I do not have access to a secure share or place other than GitHub for you to upload that to.  In order for that to be possible, you would have to [open an Azure support request](https://docs.microsoft.com/azure/azure-portal/supportability/how-to-create-azure-support-request) and work with the Azure support team.   That said, we're happy to pull it down from GitHub or a OneDrive instance or similar.

**Comment by piotrbugla** [comment]
Hi
I prepared sample app. If following code is deployed to ACA then app end up with mentioned error. On dev enviroment it works ok.

Regards

[SAMPLE.zip](https://github.com/Azure/azure-sdk-for-net/files/13242577/SAMPLE.zip)

**Comment by JoshLove-msft** [comment]
Trying to get a repro going with your sample app @piotrbugla, but when I try to either deploy to ACA or run locally with Docker Desktop, I get this error:

```
1>C:\Users\jolov\Downloads\SAMPLE\SAMPLE\src\SAMPLE.Api\Dockerfile : error CTC1014: 0.518 MSBUILD : error MSB1003: Specify a project or solution file. The current working directory does not contain a project or solution file.
1>C:\Users\jolov\Downloads\SAMPLE\SAMPLE\src\SAMPLE.Api\Dockerfile : error CTC1014: ------
1>C:\Users\jolov\Downloads\SAMPLE\SAMPLE\src\SAMPLE.Api\Dockerfile : error CTC1014: Dockerfile:4
1>C:\Users\jolov\Downloads\SAMPLE\SAMPLE\src\SAMPLE.Api\Dockerfile : error CTC1014: --------------------
1>C:\Users\jolov\Downloads\SAMPLE\SAMPLE\src\SAMPLE.Api\Dockerfile : error CTC1014:    2 |     WORKDIR /src
1>C:\Users\jolov\Downloads\SAMPLE\SAMPLE\src\SAMPLE.Api\Dockerfile : error CTC1014:    3 |     COPY . ./
1>C:\Users\jolov\Downloads\SAMPLE\SAMPLE\src\SAMPLE.Api\Dockerfile : error CTC1014:    4 | >>> RUN dotnet restore
1>C:\Users\jolov\Downloads\SAMPLE\SAMPLE\src\SAMPLE.Api\Dockerfile : error CTC1014:    5 |     RUN dotnet publish -c Release -o out /p:UseAppHost=false
1>C:\Users\jolov\Downloads\SAMPLE\SAMPLE\src\SAMPLE.Api\Dockerfile : error CTC1014:    6 |     
1>C:\Users\jolov\Downloads\SAMPLE\SAMPLE\src\SAMPLE.Api\Dockerfile : error CTC1014: --------------------
1>C:\Users\jolov\Downloads\SAMPLE\SAMPLE\src\SAMPLE.Api\Dockerfile : error CTC1014: ERROR: failed to solve: process "/bin/sh -c dotnet restore" did not complete successfully: exit code: 1
```

**Comment by yossika-tr** [comment]
also, please review the recent comment on the parallel feed (azure function)
https://github.com/Azure/azure-functions-host/issues/9127

**Comment by JoshLove-msft** [comment]
@yossika-tr, have you tried the [recommended workaround](https://github.com/Azure/azure-functions-host/issues/9127#issuecomment-1810305548) from the issue you linked?

**Comment by yossika-tr** [comment]
@JoshLove-msft I haven't tested it just yet - wanted the team's review before i do
will try and update of course
the thing is - it happens to several clients so there might be a solution waiting here or at least a way to recreate it

**Comment by yossika-tr** [comment]
@jsquire @JoshLove-msft i have just tested it and it seems to actually fix the issue - i will run some more check to verify
i have to say it's quite strange that when publishing the whole solution we get version issues where in the project itself it works as expected
really weird 

anyway - will verify and update you all on the results
Yossi

**Comment by jsquire** [comment]
@yossika-tr: Thanks for the update and I'm glad to hear that you're unblocked.  This also explains why capturing repro so difficult.   I'm going to mark this as addressed, but please feel free to unresolve if your verification turns up anything that you require further assistance with.

**Comment by ewwwgiddings** [comment]
Is there any action items from Azure to fix the issue of this happening when we target this builds this way? Something we can monitor to know when we can go back to doing it the way we've been doing it? Or is the official Azure fix to have everyone do what was suggested in that thread by changing the build target indefinitely?

**Comment by jsquire** [comment]
Hi @ewwwgiddings.  I can't speak for all of Azure, only on behalf of the Azure SDK.  I don't see any action that we can reasonably take for the Azure SDK packages that would resolve this class of issue in a general and reliable way across scenarios.

The root cause of this issue, and those similar, is a conflict between dependencies - direct or transitive - which the .NET runtime cannot resolve.  Unfortunately, the manifestation is most often specific to an application and its environment, depending heavily on what version of dependencies, toolchain, processes, and environment are being used.  As you had noted above, you were unable to reproduce the failure using the same set of packages in two different applications inside of your own environment.

While we do our best to provide a frictionless experience for all developers, there is no way for us to anticipate the dependency chain of an arbitrary set of packages and tooling of specific versions used together for an application and to be able to mitigate conflicts for that specific set in a way that does not introduce similar conflicts elsewhere.   Our focus is on validating scenarios most widely used by the community and helping to find mitigation for these conflicts when they arise elsewhere.

### Additional context

The Azure SDK must support a wide variety of runtimes, application types, and environments, covering all supported versions of the legacy .NET Framework, modern .NET, and some Mono-based environments.  As a result, we are very deliberate about what dependencies we take and intentionally select the lowest version possible to avoid forcing other referenced versions to be hoisted and to do the best that we can to avoid conflicts.

Our extensions packages, and those created by our Azure partners, must include a broader set of dependencies to serve their purpose as integration into the wider .NET ecosystem, which is why they are most often the trigger for these scenarios and our first try and direct references to work around the conflicts.

### Possible next steps

We remain unable to reproduce this specific failure, despite our investigation and the help that we've received from the community.   As we have limited resources, there is a reasonable mitigation available, and this is not impacting a large portion of the community, we are unable to continue to pursue repro.

If a community member is able to isolate repro steps and provide them, we would be happy to analyze and attempt to find a more permanent mitigation, if one can be made without introducing failures elsewhere.

**Comment by ewwwgiddings** [comment]
@jsquire There's a lot of us here that never got this error on earlier versions so I think something must have changed between this version and the last version that the Azure SDK team can look at for all of us. It is _only_ this latest version here that has the problem.

The path forward I see that Azure SDK could definitely look into is what change made in this latest version lead to all of this, and then once determined what change started to cause this issue look into if it can be reverted or altered to not break our apps in later versions.

**Comment by piotrbugla** [comment]
Hi

I was able to understand where the problem is.
In my case problem was with  AppConfiguration Labels. If we added config only with label that error occurs. Samle:

<img width="414" alt="image" src="https://github.com/Azure/azure-sdk-for-net/assets/57846194/9fe25341-9300-404a-b52e-a802dda7a707">

Setup:
ACA + App Configuration

Code snippet:

`var credential = new DefaultAzureCredential();
var appConfigEndpoint = builder.Configuration["Azure:AppConfig:Endpoint"];

builder.Configuration.AddAzureAppConfiguration(options =>       
        options.Connect(new Uri(appConfigEndpoint!), credential)
        .Select(KeyFilter.Any, LabelFilter.Null)
        .Select(KeyFilter.Any, "SOME_LABEL")
        .ConfigureKeyVault(kv => kv.SetCredential(credential)));`


`Method 'AsPages' in type 'FuncAsyncPageable`1' from assembly 'Azure.Data.AppConfiguration, Version=1.2.0.0, Culture=neutral, PublicKeyToken=92742159e12e44c8' does not have an implementation.
System.TypeLoadException: Method 'AsPages' in type 'FuncAsyncPageable`1' from assembly 'Azure.Data.AppConfiguration, Version=1.2.0.0, Culture=neutral, PublicKeyToken=92742159e12e44c8' does not have an implementation.
   at Azure.Core.PageResponseEnumerator.CreateAsyncEnumerable[T](Func`2 pageFunc)
   at Azure.Data.AppConfiguration.ConfigurationClient.GetConfigurationSettingsAsync(SettingSelector selector, CancellationToken cancellationToken)
   at Microsoft.Extensions.Configuration.AzureAppConfiguration.AzureAppConfigurationProvider.<>c__DisplayClass28_1.<<LoadSelectedKeyValues>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.Extensions.Configuration.AzureAppConfiguration.TracingUtils.CallWithRequestTracing(Boolean tracingEnabled, RequestType requestType, RequestTracingOptions requestTracingOptions, Func`1 clientCall)`
