### ISSUE TITLE
[QUERY]Disable SSL verification in azure keyvault .net sdk

### ISSUE THREAD

**Issue by HanCKPu** [Azure/azure-sdk-for-net#39494]
### Library name and version

Azure.Security.KeyVault.Secrets

### Query/Question

Hey folks I'm new to Azure keyvault and would like some help on some auth issue when testing azure keyvault .NET sdk v4 locally in a unit test.

The SecretClient is constructed as below:
`var secretClient = new SecretClient(vaultUri: new Uri(vaultUri), credential: new DefaultAzureCredential());`
And a `WebHostBuilder` to use as the test host.

However, it returns an error as below:
Bearer token authentication is not permitted for non TLS protected (https) endpoints.
   at Azure.Core.Pipeline.BearerTokenAuthenticationPolicy.<ProcessAsync>d__11.MoveNext()
   at Azure.Core.Pipeline.RedirectPolicy.<ProcessAsync>d__7.MoveNext()
   at Azure.Core.Pipeline.RetryPolicy.<ProcessAsync>d__5.MoveNext()
   at Azure.Core.Pipeline.RetryPolicy.<ProcessAsync>d__5.MoveNext()
   at Azure.Core.Pipeline.HttpPipeline.<SendRequestAsync>d__18.MoveNext()
   at System.Threading.Tasks.ValueTask 1.get_Result()
   at Azure.Security.KeyVault.KeyVaultPipeline.<SendRequestAsync>d__29.MoveNext()
   at Azure.Security.KeyVault.KeyVaultPipeline.<SendRequestAsync>d__21.MoveNext()
   at Azure.Security.KeyVault.Secrets.SecretClient.<GetSecretAsync>d__8.MoveNext()
   at MyProject.KeyVaultDataProvider.<GetSecretAsync>d__11.MoveNext()

Looks like it's required to use https. I'm wondering if there is any method to bypass this verification?

### Environment

windows .net 7.0

**Comment by jsquire** [comment]
Hi @HanCKPu.  Thanks for reaching out and we regret that you're experiencing difficulties.  For security reasons, it is not possible to relax the constraint that SSL is required when passing a bearer token.  To do so opens the door for potentially leaking credentials, as your token would be passed in plain text.

I'd like to understand more about your scenario.  For testing, it would be expected that you're either mocking the client methods or calling the KeyVault service.  Can you help us understand what testing you're doing that would support HTTP?

**Comment by HanCKPu** [comment]
Hey @jsquire Thank you for getting back! So in our tests we are not mocking the client, but instead we have a `WebHost` that listens to the GET secret calls sent from SecretClient and return the test secret. 

I think I can try switch to Mock but that would create a lot more work :)
Just wondering if there is any way to bypass the ssl verification. Maybe use a different credential rather than `DefaultAzureCredential`

**Comment by jsquire** [comment]
@HanCKPu: Thanks for the additional context.   The validation of SSL doesn't change with the type of auth used - it's always there and intentionally not configurable.   However, there are some things that you can do in the pipeline to force the request itself to use HTTP.   

Before we get to those, the cleanest approach would probably be to configure SSL support for Kestral so that your host supports it.  This would ensure that you don't have to change anything about app code to inject logic.   This is done using the [dotnet dev-certs](https://learn.microsoft.com/dotnet/core/tools/dotnet-dev-certs) command.   

If that doesn't work, a couple of alternatives come to mind:

### Configure the client with a pipeline policy that overrides the URL scheme

This injects a step into the pipeline used by Azure SDK clients that rewrites the URL before every request is made.  It requires manipulating your client options in test scenarios.   It would look something like:

```csharp

// Configure and create the client
 var options = new SecretClientOptions();
options.AddPolicy(new ForceHttpPolicy(), HttpPipelinePosition.PerCall);
    
var secretClient = new SecretClient(vaultUri: new Uri(vaultUri), new DefaultAzureCredential(), options);

// Force all outgoing requests to use HTTP
public class ForceHttpPolicy : HttpPipelineSynchronousPolicy
{
    public override void OnSendingRequest(HttpMessage message)
    {        
        base.OnSendingRequest(message);
        message.Request.Uri.Scheme = "http";
    }
}
```

More discussion and details can be found in the [Azure.Core pipeline samples](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/core/Azure.Core/samples/Pipeline.md#azurecore-pipeline-samples)

### Use a custom HttpHandler that can explicitly control the response

This injects a custom transport where the custom handler controls the response.  To just force HTTP, this is more involved than the policy - but if you wanted to return a known result from a database or other store, this would allow you to bypass your current host.

```csharp
```

**Comment by HanCKPu** [comment]
@jsquire This is awesome. Thank you for the quick response.
