### ISSUE TITLE
[BUG] Exception: Could not load file or assembly 'System.Diagnostics.DiagnosticSource, Version=6.0.0.0 after upgrading Azure.Identity from 1.5.0 to 1.10.2 as per security vulnerability

### ISSUE THREAD

**Issue by aayushsin** [Azure/azure-sdk-for-net#39632]
### Library name and version

Azure.Identity 1.10.2

### Describe the bug

 We are facing an exception as detailed below when we tried upgrading Azure.Identity from 1.5.0 to 1.10.2 which is required as per security vulnerability.

Encountered exception: Could not load file or assembly 'System.Diagnostics.DiagnosticSource, Version=6.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The located assembly's manifest definition does not match the assembly reference. (0x80131040). Retrying after waiting 250000000 ticks. Stack trace:
2023-10-31 09:04:35.095725: at Azure.Core.Pipeline.DiagnosticScopeFactory..ctor(String clientNamespace, String resourceProviderNamespace, Boolean isActivityEnabled, Boolean suppressNestedClientActivities)
2023-10-31 09:04:35.096857: at Azure.Core.Pipeline.ClientDiagnostics..ctor(String optionsNamespace, String providerNamespace, DiagnosticsOptions diagnosticsOptions, Nullable`1 suppressNestedClientActivities)
2023-10-31 09:04:35.097762: at Azure.Core.Pipeline.ClientDiagnostics..ctor(ClientOptions options, Nullable`1 suppressNestedClientActivities)
2023-10-31 09:04:35.098471: at Azure.Identity.CredentialPipeline..ctor(TokenCredentialOptions options)
2023-10-31 09:04:35.098754: at Azure.Identity.CredentialPipeline.GetInstance(TokenCredentialOptions options)
2023-10-31 09:04:35.100529: at Azure.Identity.ManagedIdentityCredential..ctor(String clientId, TokenCredentialOptions options)

### Expected behavior

The issue does not occur with Azure.Identity 1.3.0 or 1.5.0. Is there any breaking change while upgrading?

### Actual behavior

The exception as mentioned above.

### Reproduction Steps

Upgrade Azure.Idenity from 1.5.0 to 1.10.2

### Environment

.netcoreapp3.1

**Comment by jsquire** [comment]
Hi @aayushsin.   Thanks for reaching out and we regret that you're experiencing difficulties.   This problem generally occurs when the runtime is unable to load the needed set of dependencies; normally, this is due to a version mismatch due to an application reference that pins an older version either directly or as a transitive dependency.  Most often, this can be mitigated by adding an explicit reference to the application that hoists the version.  In this case, I'd suggest trying a direct reference to the latest `Azure.Core` in the application and seeing if that helps.

That said, you seem to be running/targeting `netcoreapp3.1`, which reached end-of-life in December 2022 and is no longer a supported framework.  _([src](https://dotnet.microsoft.com/en-us/platform/support/policy/dotnet-core))_    Unfortunately, we're unable to assist with problems specific to that environment and would need to be able to reproduce in `net6` or another supported version to help futher.

**Comment by Jiadosi** [comment]
Hi @jsquire , I am facing the same exception. I added a direct package reference to the latest `Azure.Core 1.35.0` but still no help.

**Comment by avendel** [comment]
For netstandard2.0, it looks like the Azure.Core nuspec specifies a dependency on System.Diagnostic.DiagnosticSource 6.0.1, but the assembly manifest indicates that the build dependency is for 6.0.0.

**Comment by m-redding** [comment]
This is the same as https://github.com/Azure/azure-sdk-for-net/issues/39798 - @Jiadosi & @aayushsin I'm going to close this issue and put updates on my investigation in the other thread.
