### ISSUE TITLE
[BUG] - No usage data returned when using the AzureChatExtensionsOptions with extension AzureCognitiveSearchChatExtensionConfiguration

### ISSUE THREAD

**Issue by jmayenSNL** [Azure/azure-sdk-for-net#39684]
### Library name and version

Azure.AI.OpenAI v1.0.0-beta.8

### Describe the bug

When using the AzureChatExtensionsOptions with extension AzureCognitiveSearchChatExtensionConfiguration  the response from the client does not contain USAGE data.

### Expected behavior

Usage data is returned.

### Actual behavior

Usage data is null

### Reproduction Steps

var chatCompletionOptions = new ChatCompletionsOptions()
{
  Messages =
  {
     new ChatMessage(ChatRole.System, @"You are an AI assistant that helps people find information about resumes.")
  },
  AzureExtensionsOptions = new AzureChatExtensionsOptions()
  {
    Extensions =
  {
      new AzureCognitiveSearchChatExtensionConfiguration()
      {
          SearchEndpoint = new Uri(searchEndpoint),
          IndexName = searchIndexName,
          SearchKey = new AzureKeyCredential(searchKey),
           ShouldRestrictResultScope = true,
            DocumentCount = 10,  
             

      }
  }
  }
};

chatCompletionOptions.Messages.Add(new ChatMessage(chatMessages[chatMessages.Count - 1].role == "user" ? ChatRole.User : ChatRole.Assistant, prompt));

//foreach (var message in chatMessages)
//{
//  chatCompletionOptions.Messages.Add(new ChatMessage(message.role == "user" ? ChatRole.User : ChatRole.Assistant, prompt));
//}

Response<ChatCompletions> responseWithoutStream = await client.GetChatCompletionsAsync(
  endpointModel,
  chatCompletionOptions );

responseWithoutStream has Usage equal to null

**Comment by pallavit** [comment]
Thank you for reporting the issue. Tagging and routing to the person best able to assist you
/cc: @trrwilson

**Comment by trrwilson** [comment]
Thanks for opening this issue! There's indeed no populated `usage` data in this scenario and this is a current limitation of the [On Your Data](https://learn.microsoft.com/azure/ai-services/openai/concepts/use-your-data) feature. You'll observe a similar lack of data if you e.g. [follow the REST quickstart](https://learn.microsoft.com/azure/ai-services/openai/use-your-data-quickstart?tabs=command-line&pivots=rest-api#example-output) and check the raw service response (which can also be seen in the .NET code you shared via `responseWithoutStream.GetRawResponse().Content.ToString()`). Much like with streaming responses, tokens are processed in a different manner relative to standard, non-streaming `/chat/completions` requests, which is why there's a difference.

Providing better response-time usage information for On Your Data (and also streaming) scenarios is on the service teams' radars and prioritized for a future release. We can't share an ETA or further details on how that'll work yet, but the SDK libraries will fully support reporting the usage data once it's available from the service.
