### ISSUE TITLE
[FEATURE REQ] Add parameter to query Cognitive Search Alias instead of index

### ISSUE THREAD

**Issue by willvelida** [Azure/azure-sdk-for-net#39692]
### Library name

Azure.Search.Documents

### Please describe the feature.

Currently, there are methods to operate on the [SearchClientIndex to create, update, delete etc. Aliases](https://github.com/Azure/azure-sdk-for-net/blob/Azure.Search.Documents_11.5.0-beta.1/sdk/search/Azure.Search.Documents/src/Indexes/SearchIndexClient.Aliases.cs), but there is no way to target an alias when querying. This is only available via REST API.

Would it be possible to comment on when this feature will be available? Currently the index name can be passed, so can we add a property to pass in the alias [here](https://github.com/Azure/azure-sdk-for-net/blob/Azure.Search.Documents_11.5.0-beta.1/sdk/search/Azure.Search.Documents/src/SearchClient.cs)?

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by willvelida** [comment]
Thanks @jsquire, LMK if I can assist further with this :)

**Comment by Eniak** [comment]
Version [11.5.0-beta.5 has code that supports aliases](https://github.com/Azure/azure-sdk-for-net/blob/Azure.Search.Documents_11.5.0-beta.5/sdk/search/Azure.Search.Documents/src/Indexes/SearchIndexClient.Aliases.cs) while the recent 1.5.0 does not. What is the timeline for these changes to go out of beta?

**Comment by willvelida** [comment]
Any updates on this team? @jsquire @ShivangiReja. To @Eniak's point, will we see this come in for 11.6.0? Can we target an alias in a query in a beta package?

**Comment by ShivangiReja** [comment]
@willvelida - Yes, you can use the preview version to utilize aliases. The reason alias operations aren't in the stable release is because they are part of a preview feature supported in the preview version of Azure Search service. A stable client library can't rely on a preview version of the service. If the feature becomes stable and is supported in the Search service, the client library will also include support.

@mattmsft can provide information from the service side about when this feature might be available in the stable version of Azure Search service.

cc: @pallavit

**Comment by ShivangiReja** [comment]
This feature request is specifically for the service team, and the SDK can only incorporate features that are supported by the service. If you have any questions related to the search service, please raise an issue at [Azure Search · Community](https://feedback.azure.com/d365community/forum/9325d19e-0225-ec11-b6e6-000d3a4f07b8). For any SDK-related questions, feel free to create issues on [Azure SDK for .NET Github](https://github.com/Azure/azure-sdk-for-net/issues).
