### ISSUE TITLE
[BUG] Trying to add a tag to a managed disk fails with InvalidResourceType

### ISSUE THREAD

**Issue by iverbitskiy** [Azure/azure-sdk-for-net#39761]
### Library name and version

Azure.ResourceManager 1.7.0 / 1.8.0

### Describe the bug

Trying to add a tag to a managed disk via the GenericResource model using AddTagAsync or the TagResource model using UpdateAsync fails with the following exception

Exactly the same like here: https://github.com/Azure/azure-sdk-for-net/issues/34796

```
The resource type 'locations/diskoperations' could not be found in the namespace 'Microsoft.Compute' for api version '2022-09-01'. The supported api-versions are '2016-04-30-preview,2017-03-30,2018-04-01,2018-06-01,2018-09-30,2019-03-01,2019-07-01,2019-11-01,2020-05-01,2020-06-30,2020-09-30,2020-12-01,2021-04-01,2021-08-01,2021-12-01,2022-03-02,2022-07-02,2023-01-02,2023-04-02'.
Status: 404 (Not Found)
ErrorCode: InvalidResourceType

Content:
{"error":{"code":"InvalidResourceType","message":"The resource type 'locations/diskoperations' could not be found in the namespace 'Microsoft.Compute' for api version '2022-09-01'. The supported api-versions are '2016-04-30-preview,2017-03-30,2018-04-01,2018-06-01,2018-09-30,2019-03-01,2019-07-01,2019-11-01,2020-05-01,2020-06-30,2020-09-30,2020-12-01,2021-04-01,2021-08-01,2021-12-01,2022-03-02,2022-07-02,2023-01-02,2023-04-02'."}}

Headers:
Cache-Control: no-cache
Pragma: no-cache
x-ms-failure-cause: REDACTED
x-ms-ratelimit-remaining-subscription-reads: REDACTED
x-ms-request-id: 4288f31a-a0ac-40ac-b238-440bc3e88013
x-ms-correlation-request-id: REDACTED
x-ms-routing-request-id: REDACTED
Strict-Transport-Security: REDACTED
X-Content-Type-Options: REDACTED
Date: Mon, 06 Nov 2023 11:29:54 GMT
Content-Type: application/json; charset=utf-8
Expires: -1
Content-Length: 434
```

### Expected behavior

The tag should be added successfully

### Actual behavior

In fact tag does adeed. BUT the code throws an RequestFailedException stating InvalidResourceType (as shown above)

### Reproduction Steps

Create or fetch a GenericResource representing an Azure Virtual Machine managed disk
Call AddTagAsync on the GenericResource to add a new tag
Call fails with a RequestFailedException

### Environment

Azure App Service (Windows)
Local Windows 11 machine, .net 6

**Comment by pallavit** [comment]
Thank you for reporting the issue. Tagging and routing to the member best able to assist you.
/cc: @ArthurMa1978

**Comment by flin-8** [comment]
We started seeing this happen on Sql databases from 4 November

```
Azure.RequestFailedException: The resource type 'locations/databaseOperationResults' could not be found in the namespace 'Microsoft.Sql' for api version '2022-09-01'. The supported api-versions are '2017-03-01-preview,2017-10-01-preview,2018-06-01-preview,2019-06-01-preview,2020-02-02-preview,2020-08-01-preview,2020-11-01-preview,2021-02-01-preview,2021-05-01-preview,2021-08-01-preview,2021-11-01,2021-11-01-preview,2022-02-01-preview,2022-05-01-preview,2022-08-01-preview,2022-11-01-preview,2023-02-01-preview,2023-05-01-preview'.
Status: 404 (Not Found)
ErrorCode: InvalidResourceType
```

**Comment by HarveyLink** [comment]
This is a general issue in ARM tags API endpoint. Multiple customers have reported it. We need ARM team to take a look at this issue.

Here is what happened.
1. When the client updates tags of a resource, it sends a request like below:
> https://management.azure.com/subscriptions/{subscription_id}/resourceGroups/{test_resource_group}/providers/Microsoft.Compute/disks/{test_disk}/providers/Microsoft.Resources/tags/default?api-version=2022-09-01

The `api-version` is ARM's API version, since it's sent to ARM endpoint.

2. Back-end service returns the polling URL through `Location` response header.
> https://management.azure.com/subscriptions/{subscription_id}/tagsoperationresults?api-version=2022-09-01&$originalLocation={hashed_value}

3. The client sends request to the given URL to poll the status. And the error returns. My guess is that ARM use the `2022-09-01` as the `api-version` when communicating with custom service.

You can try to replace the `api-version` with the value in the error messages, and it won't work because the API versions in the error message are for custom services (e.g. SQL, Compute,...), not for ARM. It will be rejected instantly.

So, there is not much we can do on SDK side. We need to ask ARM team to fix the issue. ARM need to preserve the `api-version` mapping between custom services and itself for each request, so that later on the polling requests can be correctly handled.

A work-around is using the Update method of a resource, instead of AddTag method. They use different API which should by-pass this issue.

**Comment by iverbitskiy** [comment]
@HarveyLink thank you for detailed explanations. This is exactly what is going on

**Comment by HarveyLink** [comment]
Closed since this is a service issue.
