### ISSUE TITLE
[QUERY] Using Custom processor passing eventBatchMaximumCount = 20 and processingTimeDurationMs = null getting small batch

### ISSUE THREAD

**Issue by oshvartz** [Azure/azure-sdk-for-net#39797]
### Library name and version

Azure.Messaging.EventHubs.Processor 5.9.3

### Query/Question

I have custom processor and there is large backlog of messages
passing eventBatchMaximumCount = 20
and processingTimeDurationMs  = null 
processing time is fast ~50 ms to process message
the batch size I get is 1-3 messages 
I want to increase throughput
How can I get batch size reach eventBatchMaximumCount  ?

### Environment

 Version:   6.0.408
 Commit:    0c3669d367

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  20.04
 OS Platform: Linux
 RID:         ubuntu.20.04-x64
 Base Path:   /usr/share/dotnet/sdk/6.0.408/

Host:
  Version:      6.0.16
  Architecture: x64
  Commit:       1e620a42e7

**Comment by m-redding** [comment]
Hi @oshvartz! I'm not sure if you have tried this already, but there are a couple ways that throughput can be tuned using the [`EventProcessorOptions`](https://learn.microsoft.com/en-us/dotnet/api/azure.messaging.eventhubs.primitives.eventprocessoroptions?view=azure-dotnet):
- [MaxWaitTime](https://learn.microsoft.com/en-us/dotnet/api/azure.messaging.eventhubs.primitives.eventprocessoroptions.maximumwaittime?view=azure-dotnet#azure-messaging-eventhubs-primitives-eventprocessoroptions-maximumwaittime)
- [PrefetchCount](https://learn.microsoft.com/en-us/dotnet/api/azure.messaging.eventhubs.primitives.eventprocessoroptions.prefetchcount?view=azure-dotnet#azure-messaging-eventhubs-primitives-eventprocessoroptions-prefetchcount)

It also may be worth looking at the size of the events you are processing. Large events can impact the behavior of the prefetch queue and you may need to tune the value a bit there to account for it. In general, the EventProcessor tries to maximize throughput by dispatching as quickly as possible once any events are available in the prefetch queue, it's not necessarily trying to fill a batch. So looking at what's going on with the prefetch queue and trying to tune it is going to be your best bet to increase throughput.

**Comment by oshvartz** [comment]
Hi @m-redding 
tried to update both MaxWaitTime - set it to null and PrefechCount which is 300 by default I tried setting it to higher number.
I know for a fact that there is a long backlog of messages - still the processor is getting up to 3 messages in a batch
In addition, experiment I did we to increase the message processing time and then I saw that the batch size increase
but when processing messages is ~100 millisecond the batch size is small although there are a lot of messages waiting to be processed
It's like the batching is just in memory in the processor size
please advise how can I get larger batch size

**Comment by m-redding** [comment]
The reason I recommended adjusting the prefetch queue is because the processor reads exclusively from the prefetch queue to avoid waiting on network/service operations. If all of your events are small and are processed extremely quickly it may just be that the processor is exhausting the prefetch queue. This would definitely lead to small batches and longer wait time. 

It could also be that the processor owns too many partitions and isn't able to perform optimally because of that. If this is the case, it would be easier for us to diagnose with a small slice of SDK logs - to capture follow the instructions [here](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/eventhub/Azure.Messaging.EventHubs/TROUBLESHOOTING.md#filing-github-issues).

One other idea - the service doesn't have a specific SLA for the time between an event being written and it being available for consumption. If you're using a standard tier this can sometimes take a little longer, so it might also be that events are taking longer than expected to be available to be read.

A few questions for you:
1. How many partitions do you have?
2. How are you determining the backlog of messages?

**Comment by oshvartz** [comment]
Hi @m-redding 
first let me answer your questions:

1. How many partitions do you have? - 32
2. How are you determining the backlog of messages? - I am logging time in queue and this flow is running as part of benchmarking so I created first a large backlog of messages by only sending creating a backlog of days.
3. Do you ever see full batches or are they always less than 3? - it reached up to 3 but in most cases 1 **I never see it reaching** 20 which is the max batch size I'm passing
To be clearer I'm following the example from https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/eventhub/Azure.Messaging.EventHubs/samples/Sample08_CustomEventProcessor.md
I tried opening more receivers - but I saw no impact event not increasing from batch size 3 to more 
I used standard tier with 40 TU but extremely far from it and not getting any throttled responses.
will work on collecting logs

**Comment by oshvartz** [comment]
Hi @m-redding 
adding the logs I collected
[out.txt](https://github.com/Azure/azure-sdk-for-net/files/13305783/out.txt)
[out1.txt](https://github.com/Azure/azure-sdk-for-net/files/13305785/out1.txt)
please update if more information is needed

**Comment by m-redding** [comment]
Thank you for sending those over and answering my questions! Both are really helpful. I read through the logs, and I did not notice any concerning exceptions, frequent load balancing, or stalling going on which is good. But I can also see the behavior you're observing as well - lots of small batches are being received from the same partition in a really short period of time. It looks like you have 2 consumer groups and 4 processor instances? Since you have around 8 partitions for each processor instance it may be worthwhile to consider creating additional processor instances to see if that can help. We usually recommend each processor own a maximum of 3 partitions for every 1 CPU core of the host. I know you said you had tried opening more receivers - did you mean processors or am I misunderstanding your solution?

**Comment by oshvartz** [comment]
Sorry for not being clear I'm using only processors and not receivers - try to open 10 processors (I have 32 partitions) and it didn't increase the batch size. my code is exactly like the example from https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/eventhub/Azure.Messaging.EventHubs/samples/Sample08_CustomEventProcessor.md
tell me if more information is needed

**Comment by oshvartz** [comment]
@m-redding I notice that the consumer and the namespace are not it the same region
You suggested it might be related to network issue, so I moved my consumer to be in the same region and the batch size increased
Thanks for your help closing it with insight that to reach max throughput we need to be near to the namespace
