### ISSUE TITLE
[Azure Search] NullReferenceException when checking if index exists 

### ISSUE THREAD

**Issue by jstensved** [Azure/azure-sdk-for-net#3991]
(This issue is based on [my question on Stack Overflow](https://stackoverflow.com/questions/47753559/nullreferenceexception-when-checking-if-index-exists-with-azure-search-for-net/47756744#47756744))

When trying to see if an index exists for a non-existing index with the .NET SDK (both 3.0.4 and 4.0.0-preview) the `ExistsAsync` (as well as `Exists`, and `ExistsWithHttpMessagesAsync`) throws the following exception.

    System.NullReferenceException: Object reference not set to an instance of an object.
       at Microsoft.Azure.Search.IndexesOperations.<GetWithHttpMessagesAsync>d__12.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at Microsoft.Azure.Search.ExistsHelper.<ExistsFromGetResponse>d__0`1.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at Microsoft.Azure.Search.IndexesOperationsExtensions.<ExistsAsync>d__3.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
       at InphizCore.MiddleLayer.Services.AzureSearch.Services.AzureSearchWriter`1.<AssertIndexExists>d__8.MoveNext() in C:\xxx\AzureSearchWriter.cs:line 109

Using http rest from postman works fine and returns a message saying the index doesn't exists.

     public async Task AssertIndexExists()
            {
                try
                {
                    if (await searchServiceClient.Indexes.ExistsAsync(options.Value.IndexName) == false)
                    {
                        searchServiceClient.Indexes.Create(new Index(options.Value.IndexName, FieldBuilder.BuildForType<SearchableItemModel>(), corsOptions: new CorsOptions(new List<string> { "*" })));
                    }
                }
                catch (Exception e)
                {
                    logger.LogError($"Azure Search Index '{options.Value.IndexName}' could not be created. ({e.Message})");
                    throw e;
                }
            }

This is how the client looks when running in a Unit Test:

[![enter image description here][1]][1]

This is how it looks from AspNetCore MVC:

[![enter image description here][2]][2]

Is seems like the Search Client fails to create instances of `FirstMessageHandler`, `HttpClient` and `HttpClientHandler`. Why doesn't it throw?

  [1]: https://i.stack.imgur.com/2kZuK.png
  [2]: https://i.stack.imgur.com/MT128.png

Well, this is strange but possibly some inner workings of the SearchServiceClient.

**This doesn't work:**

If I add a `HttpClientHandler` which I pass along to another of the constructors AND set lifetime to `Singleton` or `Transient` it works. I previously had `Scoped.`

     services.AddTransient<SearchServiceClient>(x =>
     {
         var httpClientHandler = new HttpClientHandler();

         var options = x.GetRequiredService<IOptions<AzureSearchOptions>>();
         var client = new SearchServiceClient(options.Value.SearchServiceName, new SearchCredentials(options.Value.AdminApiKey), httpClientHandler);
         return client;
     });

**UPDATE: This works:**

Behavior in solution above was unpredictable and I ended up with this method in the calling class.

When I created a new instance for each time I need a client it doesn't seem to give any errors at all:

      protected SearchServiceClient GetAzureSearchServiceClient()
            {
                return new SearchServiceClient(options.Value.SearchServiceName, new SearchCredentials(options.Value.AdminApiKey));
            }

**Comment by brjohnstmsft** [comment]
@jstensved Thanks for reporting this. We'll investigate.

**Comment by brjohnstmsft** [comment]
@jstensved Looking at the code, I see that the `FirstMessageHandler`, `HttpClient`, and `HttpClientHandler` properties are all defined in the [ServiceClient base class](https://github.com/Azure/azure-sdk-for-net/blob/psSdkJson6/src/SdkCommon/ClientRuntime/ClientRuntime/ServiceClient.cs). By tracing through the constructor logic in the base class and in `SearchServiceClient`, I can see that some subset of these properties is always initialized to non-null values. However, it is possible for all three to be `null` at the same time if `Dispose` was called prematurely. The fact that you observed different behavior for different [DI container lifetimes](https://docs.microsoft.com/aspnet/core/fundamentals/dependency-injection#service-lifetimes-and-registration-options) seems to support this hypothesis.

As a next step to reproducing this problem, I recommend that you substitute your own class that implements `IDisposable` into your ASP.NET Core DI setup code. Then you can put a breakpoint on `Dispose` and see where it's being called from and when.

In terms of how best to create a `SearchServiceClient`, I'd recommend using the `Singleton` lifetime, or register a singleton instance. This is because each `SearchServiceClient` has its own `HttpClient`, and creating too many of those can exhaust the TCP connection pool, leading to performance issues as the number of requests to your application increases. Just be careful not to call any methods or access any properties on `SearchServiceClient` outside of your factory method unless they're thread-safe (for example, don't set any settable properties). This advice goes for `SearchIndexClient` too.

Please let me know if you manage to confirm whether a premature call to `Dispose` is causing the problem.

**Comment by jstensved** [comment]
Thank you for looking into it. I'm currently not working on the affected client project but might be able to confirm.

We're using standard Microsoft .NET Core MVC DI so perhaps you're able to test it quickly on a fresh solution with that?

Otherwise please ping me and I'll setup a test.

**Comment by brjohnstmsft** [comment]
@jstensved I'm unable to repro the issue. Here's what I did:
  1. I created a new ASP.NET Core project using the Web Application MVC template.
  2. I added this reference to the .csproj file to work around [this known issue](https://github.com/Azure/azure-sdk-for-net/issues/3441), for which I will ship a fix very soon:

    <PackageReference Include="Newtonsoft.Json" Version="10.0.3" />

  3. I added this code to `ConfigureServices` in `Startup.cs`:

    services.AddSingleton(x => new SearchServiceClient(serviceName, new SearchCredentials(apiKey)));

  4. I added this code to `HomeController.Index` and set a breakpoint:

    _searchClient.Indexes.Exists("notanindex");

I was able to step over this line with no exceptions (after modifying the .csproj as I noted above to avoid a `SerializationBinder` exception).

I am 99% sure that the `NullReferenceException` you saw was the result of somehow disposing the client too early. I can't say more than that because I don't know the details of your application code. Do you have a minimal repro you can share that isolates the cause of this issue to the `Microsoft.Azure.Search` library? If not, I'd like to close this issue.

**Comment by brjohnstmsft** [comment]
I haven't heard back from @jstensved so I'm closing this since I can't reproduce it.
