### ISSUE TITLE
[QUESTION] NormalizerName property does not exist anymore

### ISSUE THREAD

**Issue by jonathanhallee** [Azure/azure-sdk-for-net#39939]
### Library name and version

Azure.Search.Documents v11.5.0

### Query/Question

In 11.5.0-beta5 we used to have search fields with normalizer names defined as followed
`[SearchableField(IsFilterable = true, IsSortable = true, NormalizerName = "standard", AnalyzerName = "custom-text-analyzer")]`

After migrating to 11.5.0, it appears the NormalizerName property on `SimpleFieldAttribute` is simply gone?

Yet unless I am missing something, this is not documented [as a breaking change](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/search/Azure.Search.Documents/CHANGELOG.md#1150-2023-11-10)

Has there been a replacement / change of feature for this?

### Environment

OS: Windows
.NET runtime: 7.0.103
Visual Studio 17.4.5

Azure.Search.Documents v11.5.0 vs 11.5.0-beta5

**Comment by jsquire** [comment]
Hi @jonathanhallee.  Thanks for reaching out and we regret that you're experiencing difficulties.   The reason that `NormalizerName` was removed for the v11.5.0 release is because it is a preview feature that is not supported in the stable version of the Azure Search service.   A stable version of the client library is unable to depend on a preview version of the service.  Should the feature progress to stable and support is added to the Search service, the client library will also support it.  Likewise, should the feature continue to exist in the preview version of the Search service, the next preview release of the client library will support it.

Please be aware that our beta releases should be considered unstable and potentially disruptive changes should be expected from release-to-release.   We do not guarantee that the public API will not change in our beta releases nor are those changes considered breaking.   Our stable releases, on the other hand, do follow the [.NET Breaking Change Rules](https://github.com/dotnet/runtime/blob/main/docs/coding-guidelines/breaking-change-rules.md) per the [Azure Design Guidelines](https://azure.github.io/azure-sdk/dotnet_introduction.html#dotnet-versioning).

### Additional resources

- [Azure Search REST API Spec v2023-11-01 (stable)](https://github.com/Azure/azure-rest-api-specs/tree/main/specification/search/data-plane/Azure.Search/stable/2023-11-01)
- [Azure Search REST API Spec v2023-10-01-Preview (preview)](https://github.com/Azure/azure-rest-api-specs/tree/main/specification/search/data-plane/Azure.Search/preview/2023-10-01-Preview)
- [Azure Search REST API CreateIndex example (stable)](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/search/data-plane/Azure.Search/stable/2023-11-01/examples/SearchServiceCreateIndex.json#L462)
- [Azure Search REST API CreateIndex example (preview)](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/search/data-plane/Azure.Search/preview/2023-10-01-Preview/examples/SearchServiceCreateIndex.json#L489)

**Comment by jonathanhallee** [comment]
Hi @jsquire thanks for the info!

Am I correct in saying that 11.6.0-beta1 will contain the NormalizerName?

Any idea when this feature might come out of preview?

**Comment by jsquire** [comment]
Hi @jonathanhallee.   Unfortunately, I do not have insight, though @pallavit or @ShivangiReja may have more information.   If they do not, you may want to ask on the [Azure Search forum](https://feedback.azure.com/d365community/forum/9325d19e-0225-ec11-b6e6-000d3a4f07b8).

**Comment by madameczek** [comment]
Is there a programmatical way to set NormalizerName using stable package release? Best when using C#. We have a console app in CI/CD pipeline creating an index and setting NormalizerName,

**Comment by ShivangiReja** [comment]
> Am I correct in saying that 11.6.0-beta1 will contain the NormalizerName?

@jonathanhallee - All the preview features are already present in the 11.5.0-beta.5 version, and yes, the 11.6.0-beta.1 version will also have all the preview features, including normalizers.

**Comment by ShivangiReja** [comment]
> Is there a programmatical way to set NormalizerName using stable package release? Best when using C#. We have a console app in CI/CD pipeline creating an index and setting NormalizerName

 @madameczek It's impossible to utilize preview features with a stable version, as mentioned by @jsquire [here](https://github.com/Azure/azure-sdk-for-net/issues/39939#issuecomment-1809126987). A stable version of the client library cannot rely on a preview version of the service, so we are unable to offer preview features using a stable version.

All the preview features are present in the 11.5.0-beta.5 version, including normalizers.
