### ISSUE TITLE
[BUG] System.InvalidOperationException: Cannot write a JSON property name following another property name. A JSON value is missing.

### ISSUE THREAD

**Issue by gui28347** [Azure/azure-sdk-for-net#39973]
### Library name and version

Azure.ResourceManager.Storage 1.8.1

### Describe the bug

Not able to run code to create storage account. This code was working for long long time, and after upgrading all nuget packages to latest it is now broken.

Source code:
  ResourceGroupResource resourceGroup = await subscription.GetResourceGroupAsync("TEST");
  StorageSku sku = new("Standard_LRS");
  StorageAccountCreateOrUpdateContent storageConfig = new(sku, StorageKind.StorageV2, region);
  storageConfig.MinimumTlsVersion = StorageMinimumTlsVersion.Tls1_2;
  storageConfig.AllowBlobPublicAccess = false;
  storageConfig.EnableHttpsTrafficOnly = true;
  storageConfig.Identity = new ManagedServiceIdentity(ManagedServiceIdentityType.SystemAssigned);
  var storage = resourceGroup.GetStorageAccounts().CreateOrUpdate(WaitUntil.Completed, stName, storageConfig);
Console.WriteLine($"DefaultEndpointsProtocol=https;AccountName={stName};AccountKey={st.Value.GetKeys().Take(1).First().Value};EndpointSuffix=core.windows.net");

### Expected behavior

Create storage account 

### Actual behavior

Exception:
at System.Text.Json.ThrowHelper.ReThrowWithPath(WriteStack& state, Exception ex)
   at System.Text.Json.Serialization.JsonConverter`1.WriteCore(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.JsonSerializer.WriteUsingSerializer[TValue](Utf8JsonWriter writer, TValue& value, JsonTypeInfo jsonTypeInfo)
   at System.Text.Json.JsonSerializer.Serialize[TValue](Utf8JsonWriter writer, TValue value, JsonSerializerOptions options)
   at Azure.ResourceManager.Models.ManagedServiceIdentity.Write(Utf8JsonWriter writer, JsonSerializerOptions options)
   at System.Text.Json.Serialization.JsonConverter`1.TryWrite(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.WriteCore(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.JsonSerializer.WriteUsingSerializer[TValue](Utf8JsonWriter writer, TValue& value, JsonTypeInfo jsonTypeInfo)
   at System.Text.Json.JsonSerializer.Serialize[TValue](Utf8JsonWriter writer, TValue value, JsonSerializerOptions options)
   at Azure.ResourceManager.Storage.Models.StorageAccountCreateOrUpdateContent.Azure.Core.IUtf8JsonSerializable.Write(Utf8JsonWriter writer)
   at Azure.Core.Utf8JsonWriterExtensions.WriteObjectValue(Utf8JsonWriter writer, Object value)
   at Azure.ResourceManager.Storage.StorageAccountsRestOperations.CreateCreateRequest(String subscriptionId, String resourceGroupName, String accountName, StorageAccountCreateOrUpdateContent content)
   at Azure.ResourceManager.Storage.StorageAccountsRestOperations.Create(String subscriptionId, String resourceGroupName, String accountName, StorageAccountCreateOrUpdateContent content, CancellationToken cancellationToken)
   at Azure.ResourceManager.Storage.StorageAccountCollection.CreateOrUpdate(WaitUntil waitUntil, String accountName, StorageAccountCreateOrUpdateContent content, CancellationToken cancellationToken)
   at AzureAutomation.Functions.CreateStorageAccount.<Run>d__0.MoveNext() 

### Reproduction Steps

Packages imported in my project:
  <PackageReference Include="Azure.Core" Version="1.36.0" />
  <PackageReference Include="Azure.Identity" Version="1.10.4" />
  <PackageReference Include="Azure.ResourceManager" Version="1.8.1" />
  <PackageReference Include="Azure.ResourceManager.AppService" Version="1.0.2" />
  <PackageReference Include="Azure.ResourceManager.Compute" Version="1.2.0" />
  <PackageReference Include="Azure.ResourceManager.KeyVault" Version="1.1.0" />
  <PackageReference Include="Azure.ResourceManager.Monitor" Version="1.2.0" />
  <PackageReference Include="Azure.ResourceManager.Network" Version="1.5.0" />
  <PackageReference Include="Azure.ResourceManager.Resources" Version="1.6.0" />
  <PackageReference Include="Azure.ResourceManager.Storage" Version="1.1.1" />
  <PackageReference Include="Azure.Security.KeyVault.Keys" Version="4.5.0" />
  <PackageReference Include="Azure.Security.KeyVault.Secrets" Version="4.5.0" />
  <PackageReference Include="Azure.Storage.Blobs" Version="12.19.1" />
  <PackageReference Include="FluentValidation" Version="11.8.0" />
  <PackageReference Include="Google.Protobuf" Version="3.25.0" />
  <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.DurableTask" Version="2.13.0" />
  <PackageReference Include="Microsoft.Graph" Version="5.34.0" />
  <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="4.2.0" />

Import these packages, and use the sample code I provided.

### Environment

.NET SDK:
 Version:   7.0.403
 Commit:    142776d834

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22631
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.403\

Host:
  Version:      7.0.13
  Architecture: x64
  Commit:       3f73a2f186

.NET SDKs installed:
  6.0.416 [C:\Program Files\dotnet\sdk]
  7.0.203 [C:\Program Files\dotnet\sdk]
  7.0.310 [C:\Program Files\dotnet\sdk]
  7.0.403 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.24 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.24 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.24 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.13 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download

**Comment by brah2008** [comment]
**Subject: [BUG] System.InvalidOperationException in Azure.ResourceManager.Storage 1.8.1**

Dear Azure.ResourceManager.Storage Team,

I hope this message finds you well. I am reaching out to report a bug in version 1.8.1 of the Azure.ResourceManager.Storage library. The issue arises when attempting to create a storage account using the provided code snippet after upgrading all NuGet packages to their latest versions.

Bug Description:
The code, which was functioning correctly for an extended period, is now encountering an exception after the package update. The exception thrown is:
**`System.InvalidOperationException: Cannot write a JSON property name following another property name. A JSON value is missing.
`**

**Code Snippet:**

**`ResourceGroupResource resourceGroup = await subscription.GetResourceGroupAsync("TEST");
StorageSku sku = new("Standard_LRS");
StorageAccountCreateOrUpdateContent storageConfig = new(sku, StorageKind.StorageV2, region);
storageConfig.MinimumTlsVersion = StorageMinimumTlsVersion.Tls1_2;
storageConfig.AllowBlobPublicAccess = false;
storageConfig.EnableHttpsTrafficOnly = true;
storageConfig.Identity = new ManagedServiceIdentity(ManagedServiceIdentityType.SystemAssigned);
var storage = resourceGroup.GetStorageAccounts().CreateOrUpdate(WaitUntil.Completed, stName, storageConfig);
Console.WriteLine($"DefaultEndpointsProtocol=https;AccountName={stName};AccountKey={st.Value.GetKeys().Take(1).First().Value};EndpointSuffix=core.windows.net");
`**


**Expected Behavior:**
The code should successfully create a storage account.

**Actual Behavior:**
The code throws a System.InvalidOperationException with the provided stack trace, indicating a JSON serialization issue.

**Reproduction Steps:**

**Import the following packages:**
**`Azure.ResourceManager.Storage 1.8.1
// Other packages used in the project
`**

**Use the provided code snippet.**

**Environment:**

.NET SDK Version: 7.0.403
Runtime Environment:
OS Name: Windows
OS Version: 10.0.22631
OS Platform: Windows
RID: win10-x64
Base Path: C:\Program Files\dotnet\sdk\7.0.403\
Host Version: 7.0.13
Architecture: x64
Commit: 3f73a2f186
Additional Information:
.NET SDKs installed:

6.0.416 [C:\Program Files\dotnet\sdk]
7.0.203 [C:\Program Files\dotnet\sdk]
7.0.310 [C:\Program Files\dotnet\sdk]
7.0.403 [C:\Program Files\dotnet\sdk]
.NET runtimes installed:

Microsoft.AspNetCore.App 6.0.24 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 7.0.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.NETCore.App 6.0.24 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 7.0.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.WindowsDesktop.App 6.0.24 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 7.0.13 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
I appreciate your attention to this matter and look forward to a resolution.

**Best regards,**

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by gui28347** [comment]
It was fixed after upgrading to Azure.ResourceManager 1.9.0 released today.
