### ISSUE TITLE
[FEATURE REQ] Add support for underscores in Key Vault secret names

### ISSUE THREAD

**Issue by TheCakeMonster** [Azure/azure-sdk-for-net#39975]
### Library name

Azure.Extensions.AspNetCore.Configuration.Secrets

### Please describe the feature.

I am aware that this will be a limitation with Key Vault itself, and not this package, but I'd appreciate help from the team who manage the package in moving this request to a more appropriate repo - or at the very least telling where I should create it, so that I can link to the final request from this one.

Key Vault does not allow underscores in its secret names. This is well documented. However, this limitation makes it much less useful as a storage location for developers, including .NET developers. Often .NET Devs cannot easily migrate from having values stored as configuration items of an Azure App Service to Key Vault because of this limitation.

It is common practice for developers to use the underscore character to separate words in the name of a configuration item, and the limitations on Key Vault's secret names means people have to rewrite their code in order to draw configuration from Key Vault instead.

Other configuration sources do not suffer from this limitation, so the inconsistency causes some confusion and frustration. That leads to a poor user experience.

Sadly, while this limitation is pretty well documented, it will be common for people to find this out only as they try to use KV for the first time - at the point of implementation, not design. This causes rework and lost productivity, or abandoning the use of the service altogether.

Is it possible to enhance Key Vault to overcome this limitation?

**Comment by brah2008** [comment]
Subject: Feature Request - Support for Underscores in Key Vault Secret Names



I hope this message finds you well. I am writing to request support for underscores in Key Vault secret names within the Azure.Extensions.AspNetCore.Configuration.Secrets library.

**Description of the Feature:**
I am aware that the limitation regarding underscores in Key Vault secret names is inherent to Key Vault itself and not specific to the Azure.Extensions.AspNetCore.Configuration.Secrets package. However, I believe addressing this limitation within the package could greatly enhance the user experience for .NET developers.

Currently, Key Vault does not allow the use of underscores in secret names, a well-documented constraint. This limitation poses challenges for developers, especially those working with .NET. Many .NET developers face difficulties migrating from storing configuration values as items in an Azure App Service to Key Vault due to this restriction.

In typical coding practices, developers use the underscore character to separate words in the name of a configuration item. The absence of this feature in Key Vault's secret names necessitates code rewriting when transitioning to Key Vault for configuration storage.

The inconsistency in this naming convention compared to other configuration sources adds confusion and frustration for users. This inconsistency not only affects the user experience but also leads to rework, lost productivity, or, in some cases, abandonment of Key Vault as a configuration storage solution.

While this limitation is well-documented, many users discover it only during implementation, not during the design phase. This often results in unplanned rework and a negative impact on productivity.

I understand that the limitation lies with Key Vault itself, and I kindly request your assistance in either addressing this limitation within the Azure.Extensions.AspNetCore.Configuration.Secrets package or guiding me to the appropriate repository where I can submit this feature request. Having your support in moving this request to a more suitable repository would be greatly appreciated.

Thank you for your time and consideration. I look forward to your guidance on how best to proceed with this request.

Best regards,

**Comment by brah2008** [comment]
Subject: Feature Request - Support for Underscores in Key Vault Secret Names



I hope this message finds you well. I am writing to request support for underscores in Key Vault secret names within the Azure.Extensions.AspNetCore.Configuration.Secrets library.

**Description of the Feature:**
I am aware that the limitation regarding underscores in Key Vault secret names is inherent to Key Vault itself and not specific to the Azure.Extensions.AspNetCore.Configuration.Secrets package. However, I believe addressing this limitation within the package could greatly enhance the user experience for .NET developers.

Currently, Key Vault does not allow the use of underscores in secret names, a well-documented constraint. This limitation poses challenges for developers, especially those working with .NET. Many .NET developers face difficulties migrating from storing configuration values as items in an Azure App Service to Key Vault due to this restriction.

In typical coding practices, developers use the underscore character to separate words in the name of a configuration item. The absence of this feature in Key Vault's secret names necessitates code rewriting when transitioning to Key Vault for configuration storage.

The inconsistency in this naming convention compared to other configuration sources adds confusion and frustration for users. This inconsistency not only affects the user experience but also leads to rework, lost productivity, or, in some cases, abandonment of Key Vault as a configuration storage solution.

While this limitation is well-documented, many users discover it only during implementation, not during the design phase. This often results in unplanned rework and a negative impact on productivity.

I understand that the limitation lies with Key Vault itself, and I kindly request your assistance in either addressing this limitation within the Azure.Extensions.AspNetCore.Configuration.Secrets package or guiding me to the appropriate repository where I can submit this feature request. Having your support in moving this request to a more suitable repository would be greatly appreciated.

Thank you for your time and consideration. I look forward to your guidance on how best to proceed with this request.

Best regards,

**Comment by jsquire** [comment]
Hi @TheCakeMonster.  Thank you for your feedback.  As you've mentioned, this limitation comes from the Key Vault service itself and is not something that the client library can influence.  Your best path forward to request the feature would be to [open an Azure support request](https://docs.microsoft.com/azure/azure-portal/supportability/how-to-create-azure-support-request).  If a support request is not feasible, I'd suggest requesting the feature on the [Azure Key Vault forum](https://feedback.azure.com/d365community/forum/285c5ae0-f524-ec11-b6e6-000d3a4f0da0) of the [Azure Feedback site](https://feedback.azure.com/).

**Comment by TheCakeMonster** [comment]
@jsquire Thanks for the links, much appreciated. I'll give that a go.
