### ISSUE TITLE
[BUG] ContainerAppWritableSecret fails deserialization when KeyVaultUri is an empty string

### ISSUE THREAD

**Issue by mburumaxwell** [Azure/azure-sdk-for-net#40119]
### Library name and version

Azure.ResourceManager.AppContainers 1.1.0

### Describe the bug

Deserialization of `ContainerAppWriteableSecret` fails for Container App Jobs but works for Container Apps.

Example for Container App:

```json
"secrets": [
    {
        "name": "authentication-internal-key",
        "keyVaultUrl": "https://<omited>.vault.azure.net/secrets/<omited>",
        "identity": "/subscriptions/<omited>/resourceGroups/<omited>/providers/Microsoft.ManagedIdentity/userAssignedIdentities/<omited>"
    },
    {
        "name": "connection-strings-mongo"
    }
],
```

Example for Container App Job:

```json
"secrets": [
    {
        "name": "authentication-internal-key",
        "keyVaultUrl": "https://<omited>.vault.azure.net/secrets/<omited>",
        "identity": "/subscriptions/<omited>/resourceGroups/<omited>/providers/Microsoft.ManagedIdentity/userAssignedIdentities/<omited>"
    },
    {
        "name": "connection-strings-mongo",
        "keyVaultUrl": "",
        "identity": ""
    }
],
```

Referenced from https://github.com/microsoft/azure-container-apps/issues/943#issuecomment-1817383694

### Expected behavior

Get or listing container app jobs should work

### Actual behavior

Fails at deserialization

### Reproduction Steps

// Create job with a keyvault secret from anywhere else (portal, CLI, etc)

```cs
var client = new ArmClient(new DefaultAzureCredential());
var sub = client.GetDefaultSubscription();
var jobs = sub.GetContainerAppJobsAsync(cancellationToken);
await foreach (var job in jobs)
{
    var name = job.Data.Name;
    Console.WriteLine($"Job: {name}");
}
```

**Comment by anandanthony** [comment]
thank you, we will check and provide an update on this.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by ArthurMa1978** [comment]
Hey @mburumaxwell , thank you for reaching out to us about the Azure SDK for .NET. Unfortunately, this issue is related to the service side and not the SDK side, so we are not able to help you with it. Therefore, we are closing this issue for now. If you need more assistance, please [open an Azure support request](https://docs.microsoft.com/azure/azure-portal/supportability/how-to-create-azure-support-request). We apologize for any inconvenience this may cause you.

We value your feedback and we want to make sure that your problem is solved. If you think that we have misunderstood your issue or closed it incorrectly, please feel free to comment on this thread and reopen the issue. We will be happy to assist you further. Thank you for your understanding and cooperation.

**Comment by mburumaxwell** [comment]
@ArthurMa1978 
Funny you say this is a service issues. The service persons ( @anandanthony ) said it should be opened here. Is this another way of saying everyone should go figure it out it on their own??

**Comment by anandanthony** [comment]
@mburumaxwell apologies for the confusion for this issue, what I meant by my comment on https://github.com/microsoft/azure-container-apps/issues/943 was that the specific issue you are facing was not introduced due to the fix for storage mounts.

We further found a similar issue on our end and are investigating it. Will provide you with an update on the fix.

**Comment by mburumaxwell** [comment]
@anandanthony is there need to open another issue?

**Comment by anandanthony** [comment]
@mburumaxwell I was able to check and confirm that we can use the `Azure.ResourceManager.AppContainers` package to GET a Job which was created with a secret which does not have keyvault or identity (having empty strings for these properties). I used version 1.1.1 to test this out.

Additionally, there has been a change which is rolling out which would ensure that if a secret does not have keyvault/identity defined, it would not be considered as an empty string which should further address any issues related to empty strings for keyvault/identity for secrets added to a job. (ETA for this fix to roll out completely would be end of next week).

**Comment by mburumaxwell** [comment]
Thanks @anandanthony I did update to version 1.1.1 but didn't update the work around since the [release notes](https://github.com/Azure/azure-sdk-for-net/releases/tag/Azure.ResourceManager.AppContainers_1.1.1) did not indicate a related change. It now seems to be working, thank you.

**Comment by mburumaxwell** [comment]
Well, I spoke too soon. The error persists. I will wait for the service-side fix next week

**Comment by mburumaxwell** [comment]
This is finally fixed. Thanks @anandanthony
