### ISSUE TITLE
[Key Vault] Fix AOT warnings reported in latest version of .NET 8

### ISSUE THREAD

**Issue by m-redding** [Azure/azure-sdk-for-net#40175]
### Library name

Azure.Security.KeyVault.Keys

### Please describe the feature.

There have been a lot of updates across the different versions of .NET 8 and its previews. With the official .NET 8 release, some new warnings are being reported in `Azure.Security.KeyVault.Keys`:

> C:\Users\mredding\source\repos\azure-sdk-for-net\sdk\keyvault\Azure.Security.KeyVault.Keys\src\JsonWebKey.cs(517): Trim analysis warning IL2026: Azure.Security.KeyVault.Keys.JsonWebKey.CreateRSAProvider(RSAParameters): Using member 'System.Security.Cryptography.RSA.Create(String)' which has 'RequiresUnreferencedCodeAttribute' can break functionality when trimming application code. The default algorithm implementations might be removed, use strong type references like 'RSA.Create()' instead. [C:\Users\mredding\source\repos\ResolveAOT\ResolveAOT\ResolveAOT.csproj]
>  
> C:\Users\mredding\source\repos\azure-sdk-for-net\sdk\keyvault\Azure.Security.KeyVault.Keys\src\JsonWebKey.cs(517): Trim analysis warning IL2026: Azure.Security.KeyVault.Keys.JsonWebKey.CreateRSAProvider(RSAParameters): Using member 'System.Security.Cryptography.AsymmetricAlgorithm.Create(String)' which has 'RequiresUnreferencedCodeAttribute' can break functionality when trimming application code. The default algorithm implementations might be removed, use strong type references like 'RSA.Create()' instead. [C:\Users\mredding\source\repos\ResolveAOT\ResolveAOT\ResolveAOT.csproj]
> 

After a preliminary investigation, it looks like the code is trying to call Create(RSAParameters) not Create(string), so it seems like it may be something that could be suppressed. If that is the case, then it would probably be best to get a review from the .NET team to make sure we're not misunderstanding the context.

To repro, follow the instructions here to make a console app: https://learn.microsoft.com/en-us/dotnet/core/deploying/trimming/prepare-libraries-for-trimming?pivots=dotnet-8-0#show-all-warnings-with-test-app

And have this be the .csproj:

```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <PublishAot>true</PublishAot>
    <TrimmerSingleWarn>false</TrimmerSingleWarn>
  </PropertyGroup>

  <ItemGroup>
	  <ProjectReference Include="..\..\azure-sdk-for-net\sdk\keyvault\Azure.Security.KeyVault.Keys\src\Azure.Security.KeyVault.Keys.csproj" />
      <PackageReference Include="Azure.Security.KeyVault.Keys" Version="4.6.0-beta.2" />
	     <TrimmerRootAssembly Include="Azure.Security.KeyVault.Keys" />

    <!-- Update this dependency to its latest, which has all the annotations -->
    <PackageReference Include="Microsoft.Extensions.Logging.Configuration" Version="8.0.0-preview.7.23375.6" />
  </ItemGroup>
	
```

run `dotnet publish` with .NET 8

**Comment by heaths** [comment]
@eerhardt these AOT warnings look errant. We don't call `AsymmetricAlgorithm.Create(String)` or `RSA.Create(String)`, but do call - via reflection - `RSA.Create(RSAParameters)`: https://github.com/Azure/azure-sdk-for-net/blob/616dbcb604f399545ef170ffc97eb099bd4c8065/sdk/keyvault/Azure.Security.KeyVault.Keys/src/JsonWebKey.cs#L512

Or is the warning conceptually correct, but maybe the warning message itself is erroneous i.e., mentions the `String` param form when it's pretty much any parameterized call?

I definitely need to be able to create keys using `RSAParameters` (or `ECParameters` for `ECDsa`), but maybe we just need to attribute these and move on. I can see some AOT scenarios needing this functionality, but not sure if there's a better alternative.

**Comment by eerhardt** [comment]
@heaths - this looks like a bug in the trimming tools (IMO). The code is clearly only targeting the `RSA.Create(RSAParameters)` method, but for some reason the trimming tools is complaining (and preserving) all overloads of the `RSA.Create` method, including the base class. And since the other overloads of the method have `RequiresUnreferencedCode` on them, it is giving a warning.

Can you open an issue in https://github.com/dotnet/runtime for this? @vitek-karas @agocke and @MichalStrehovsky should be able to advise on if it is a real issue. My assumption is that this behavior is there for a reason - I just don't know what that reason is.

For now, my thought is to suppress the 2 warnings with links to the runtime issue as justificaiton.

**Comment by agocke** [comment]
Rather than trying to massage the reflection, could we ifdef instead? It looks like this project is already multitargeted.

**Comment by MichalStrehovsky** [comment]
> I think in a perfect world, the trimming tools should be able to tell that this code is only talking about the `Create(RSAParameters)` overload and not warn (or preserve) the `Create(string)` overload.

The analysis doesn't look at this because replicating the algorithm that `GetMethod` uses to find the overload would likely be a bug farm. The original designers of the reflection stack wanted this API to be convenient, so the semantics are not what one would expect.

```csharp
using System;
using System.Reflection;

var m = typeof(Foo).GetMethod(nameof(Foo.Method), BindingFlags.Public | BindingFlags.Static,
    new Type[] { typeof(byte) });
Console.WriteLine(m);

class Foo
{
    public static void Method(int x) { }
}
```

Notice this is asking for a method that takes a `byte`, but reflection logic will just hand out the method that takes an `int`. The current trimming analysis is conservative, but correct (it may issue unnecessary warnings but it will not produce a broken program without warnings). Matching the overload resolution rules is not entirely trivial.

**Comment by heaths** [comment]
> Rather than trying to massage the reflection, could we ifdef instead? It looks like this project is already multitargeted.

The shipping package targets only netstandard2.0: https://github.com/Azure/azure-sdk-for-net/blob/2de1165621d8594ea70af1befa43ce3d647f31c8/sdk/keyvault/Azure.Security.KeyVault.Keys/src/Azure.Security.KeyVault.Keys.csproj#L11 (`$(RequiredTargetFrameworks)` is defined only as netstandard2.0 for shipping packages).

I've done an analysis previously and found a large number of TFMs are necessary and `#ifdef`s still won't cover all cases because the number of methods that are defined in supports runtimes but not declared in .NETStandard, hence all the reflection-based light-up. I'm not sure we want to multi-target just to satisfy an (understandably) errant warning so I'll likely just suppress it.
