### ISSUE TITLE
CloudConfigurationManager.GetSetting in 3.2.3 returns null

### ISSUE THREAD

**Issue by thuansoldier** [Azure/azure-sdk-for-net#4047]
I'm not sure if I'm missing something when using CloudConfigurationManager to load my setting from app.config for my .NET client.

```
   <appSettings>
      <add key="AzureSubscriptionId" value="XXX" />
      <add key="AzureTenantId" value="XXX" />
      <add key="AzureClientId" value="XXX" />
      <add key="AzureClientSecret" value="XXX" />
    </appSettings>

```
And use the following:

`string subscription = CloudConfigurationManager.GetSetting("AzureSubscriptionId");`

But in Debug mode, it returns null.

The directive is using Microsoft.Azure;

Version of **Microsoft.WindowsAzure.ConfigurationManage**r Nuget package is 3.2.3

**Comment by shahabhijeet** [comment]
@thuansoldier can you try the recently released package and let us know if this resolves your issue, if not please let us know.
https://www.nuget.org/packages/Microsoft.Azure.ConfigurationManager/

**Comment by jeevaeastpoint** [comment]
Hi Guys,

I have the same issue. I am using the latest version of the CloudConfigurationManager [Microsoft.Azure.ConfigurationManager] and the application could not get the app settings.

Error I get is "System.DllNotFoundException: 'Unable to load DLL 'fusion.dll' or one of its dependencies: The specified module could not be found. "
I am using .net core 2.1 and it is a console app. 

Below is the code snippet
`var connectionString = Microsoft.Azure.CloudConfigurationManager.GetSetting("StorageConnection");
            var storageAccount = CloudStorageAccount.Parse(connectionString);
            var blobClient = storageAccount.CreateCloudBlobClient();
            var container =  blobClient.GetContainerReference("Test");
            container.CreateIfNotExistsAsync();

            Console.ReadKey();`
Any idea why this is happening.

**Comment by premanshum** [comment]
I have a library that uses CloudConfigurationManager. This library is in .net framework 4.7.x.
This library is consumed by Azure Function, written in framework 4.7.x. Everything is fine.
However, I wanted to write test case against the library in .net core. And that is where I got this Fusion.dll error.
My question is not whether any fix available. Rather, why should I not move to Scripting languages. Because, this is not the first time. and the product, .Net Core, is still primitive.
