### ISSUE TITLE
Support for creating and operating StreamAnalytics in StandardV2 version.

### ISSUE THREAD

**Issue by zorc** [Azure/azure-sdk-for-net#40506]
### Library name

Azure.ResourceManager.StreamAnalytics

### Please describe the feature.

Hope to support the creation and operation of StreamAnalytics in StandardV2 version and set the number of units to 1/3.

If already supported, please inform the SDK version and how to input parameters.

```c#
StreamingJobData data = new StreamingJobData(new AzureLocation(AppConfigurationsInfo.Cloud_Azure_Management_StreamAnalytics_Location))
                {
                    //TODO:The commented-out portion of this code has no effect.
                    //SkuName = new StreamAnalyticsSkuName("StandardV2")
                    SkuName = new StreamAnalyticsSkuName("Standard"),
                    EventsOutOfOrderPolicy = Azure.ResourceManager.StreamAnalytics.Models.EventsOutOfOrderPolicy.Adjust,
                    OutputErrorPolicy = StreamingJobOutputErrorPolicy.Drop,
                    EventsOutOfOrderMaxDelayInSeconds = 0,
                    EventsLateArrivalMaxDelayInSeconds = 5,
                    Location=new AzureLocation("chinanorth2"),
                    CompatibilityLevel = StreamingJobCompatibilityLevel.Level1_0
                };
``` 

doc:
https://learn.microsoft.com/en-us/azure/stream-analytics/stream-analytics-streaming-unit-consumption#understand-streaming-unit-and-streaming-node

**Comment by ArthurMa1978** [comment]
Hey @zorc , thank you for reaching out to us about the Azure SDK for .NET. Unfortunately, this issue is related to the service side and not the SDK side, so we are not able to help you with it. Therefore, we are closing this issue for now. If you need more assistance, please [open an Azure support request](https://docs.microsoft.com/azure/azure-portal/supportability/how-to-create-azure-support-request) to ask service team to upgrade the swagger spec and then the SDK will be updated accordingly. We apologize for any inconvenience this may cause you.

We value your feedback and we want to make sure that your problem is solved. If you think that we have misunderstood your issue or closed it incorrectly, please feel free to comment on this thread and reopen the issue. We will be happy to assist you further. Thank you for your understanding and cooperation.
