### ISSUE TITLE
[QUERY] disable distributed tracing / Diagnostic-Id in messages

### ISSUE THREAD

**Issue by kimpenhaus** [Azure/azure-sdk-for-net#40609]
### Library name and version

Azure.Messaging.ServiceBus latest/7.17.1

### Query/Question

Hey @JoshLove-msft,

I hope it is okay to ask you directly from within this question - but it seems you are the head of knowledge on this topic :)

We would like to disable distributed tracing with the `Diagnostic-Id` in the message properties that causes Activities to have a parent and when it comes to Application Insights to see all those message chains under one operation_id (sorry that I am not able to be more precise in wording - no native speaker)

In the code I saw that there is a passage in the summary that says: `If tracing is enabled, a diagnostic id will be added to the message properties, which alters the message size.` But I can't find any docs describing how to disable the diagnostic id.

<img width="3148" alt="image" src="https://github.com/Azure/azure-sdk-for-net/assets/575109/c2c88e75-d1f5-4095-8cb8-8e94b20218b3">

We recently switch from custom handling of ServiceBusReceiver to the ServiceBusProcessor and lots f our queries are based on the fact that the operation id is unique upon the processing of a message - which now is not anymore as the operation id might return message chains. I know that it is not ideal on what is supposed to be a logical operation but that application is kind of brownfield.

If there is anything else you need, please, let me know.

Best,
Marcus

### Environment

We are using .NET 8 with Application Insights 2.22 and Azure ServiceBus Messaging 7.17.1

**Comment by jsquire** [comment]
Hi @kimpenhaus.   Thanks for reaching out and we regret that you're experiencing difficulties.   We do not currently expose a way to disable distributed tracing for Service Bus clients.  That said, can you help me understand your scenario better?   Specifically, I'm interested in what you're referring to as an "operation id" and what kind of queries you're pulling together.

**Comment by kimpenhaus** [comment]
Hi @jsquire,

thanks for your quick reply - with operation_id I specifically mean the operation_id used in application insights and quries for devops on that application insights data.

When we used to have our custom service bus receive handling each operation was unique in application insights - when we switched to the service bus processor we see "chains" od receiving and sending/receiving new messages. like in this sample:

<img width="1416" alt="image" src="https://github.com/Azure/azure-sdk-for-net/assets/575109/e3adf263-dcf9-4812-80c1-c588a58ec70e">

explanation:

we receive message event 12000 - which pushes message event 20099 - when that is received it pushes a new event 12000 to the service bus. formerly we would see each "processing" request within a unique operation id - nowadays we see all 3 processings under a single operation id.

from debugging and code review we could lead this back to the diagnostic-id inside the message property from the pushed message

<img width="3468" alt="image" src="https://github.com/Azure/azure-sdk-for-net/assets/575109/bae473da-11de-4495-a446-f97756e16ce8">

does this answer your qeuestion?

Best,
Marcus

**Comment by lmolkova** [comment]
Hi @kimpenhaus, thanks for reaching out!

As you mentioned, `operation_id` is intended to correlate producer and consumer telemetry, there is also `Id` property that identifies each request or dependency.
<img width="630" alt="image" src="https://github.com/Azure/azure-sdk-for-net/assets/2347409/bb3e1b8d-b0c2-45c3-9bf4-7eea70125ec3">

Please consider fixing the queries so that they won't break again in the future.

If you're interested in the hacky workaround, I can suggest the following.
I assume you create some custom telemetry to track message processing - force it to use a unique operation Id 
   - you can specify one when creating this custom telemetry. [Here's an example](https://learn.microsoft.com/en-us/azure/azure-monitor/app/custom-operations-tracking#process) that  demonstrates how to make it correlated with message, but you can do `requestTelemetry.Context.Operation.Id = Guid.NewGuid().ToString("n");` instead.
   - or, you can set `Activity.Current = null` first thing when processor callback start - this will prevent any telemetry you generate in that scope from being correlated to `ServiceBus.Process` request that's also correlated to the message.

**Comment by kimpenhaus** [comment]
Hey @lmolkova,

thanks for pointing out the possibilities. I think we will try in the short range one of the hacky workarounds :) and in the medium range to change the queries to match ther concepts better.

Cheers,
Marcus
