### ISSUE TITLE
[CVE-2023-36414 detection]

### ISSUE THREAD

**Issue by mezzofix** [Azure/azure-sdk-for-net#40693]
### Library name and version

Azure.Identity

### Query/Question

hi, is there any guidance, or can by guidance provided as to how identify vulnerable assets to CVE-2023-36414 ? I’m struggling to find assets vulnerable to this although we know at least some servers by working with the app teams. For example, in Defender 365 when I search for the CVE, I get “no devices exposed to this CVE were found”, although I’m not sure this is correct. 

![image](https://github.com/Azure/azure-sdk-for-net/assets/57439630/5a08775e-7e00-4b2f-a3c8-b4db530e0419)

I would assume that search for Azure.Identity.dll would be one way, however getting 18 hits, with varying hash values: 

![image](https://github.com/Azure/azure-sdk-for-net/assets/57439630/4cdac343-63ff-4ce6-b0c9-424b146376a6)

Any suggestion is appreciated !

**Comment by christothes** [comment]
Hi @mezzofix  -  It should be anything that has a direct or indirect dependency on Azure.Identity with a version < 1.10.2

**Comment by mezzofix** [comment]
hi @christothes I understand that, but how would I detect the dependency or even installation of the Azure Identity sdk ?

**Comment by jsquire** [comment]
> how would I detect the dependency or even installation of the Azure Identity sdk ?

Hi @mezzofix.  Unfortunately, this is not something that we're able to assist with.  The answer will be specific to your organization, environment, tooling preferences, and budget and is not related to the Azure SDK package itself.  If your organization has a security or ops team, you may want to ask there.  Otherwise, you may want to start by looking into the [dotnet CLI list package --vulnerable](https://devblogs.microsoft.com/nuget/how-to-scan-nuget-packages-for-security-vulnerabilities/).   There are also a number of third-party tools that could be found via web search.

**Comment by jsquire** [comment]
Hi @mezzofix.  The answer to this has not changed; this is not an issue that we're able to assist with.  Was there a specific follow-up that you wanted to ask?

**Comment by jsquire** [comment]
Closing this out as there do not appear to be follow-up questions.
