### ISSUE TITLE
[BUG] OpenAI GPT-4 Vision API should supports string as url

### ISSUE THREAD

**Issue by sdcb** [Azure/azure-sdk-for-net#40744]
### Library name and version

Azure.AI.OpenAI 1.0.0-beta.11

### Describe the bug

Currently Azure.AI.OpenAI 1.0.0-beta.11 supports GPT-4 Vision API, however it's using a Uri as a parameter, this uri supports a internet picture url or data url like this:
```
data:image/jpeg;base64,/9j/4AAQSkZJRgABAQEBLAEsAAD/4Rm4....
```

If the image data url is too long(> 65535 characters), it will throws a `UriFormatException`: `Invalid URI: The Uri string is too long.`

### Expected behavior

We should allow user use a string as a parameter instead of url.

### Actual behavior

If this image data url is too long(> 65535 characters), it will throws a `UriFormatException`: `Invalid URI: The Uri string is too long.`

### Reproduction Steps

Find a local image file that > 64KB, create the data url using following code:
```csharp
public class ImageHelper
{
	private static readonly Dictionary<string, string> MimeTypes = new Dictionary<string, string>
	{
		{ ".bmp", "image/bmp" },
		{ ".gif", "image/gif" },
		{ ".jpg", "image/jpeg" },
		{ ".jpeg", "image/jpeg" },
		{ ".png", "image/png" },
		{ ".tiff", "image/tiff" },
        // 更多的MIME类型可以在这里添加
    };

	public static string ReadAsBase64Url(string imagePath)
	{
		// 检查文件是否存在
		if (!File.Exists(imagePath))
		{
			throw new FileNotFoundException("Specified image path is not found.", imagePath);
		}

		// 获取文件的扩展名，并转换为小写
		string extension = Path.GetExtension(imagePath).ToLowerInvariant();

		// 根据文件扩展名获取MIME类型
		if (!MimeTypes.TryGetValue(extension, out string? mimeType))
		{
			throw new ArgumentException("Unsupported image type.", nameof(imagePath));
		}

		// 返回数据URI格式的Base64 URL
		return $"data:{mimeType};base64,{Convert.ToBase64String(File.ReadAllBytes(imagePath))}";
	}
}
```

Then call the Azure OpenAI GPT-4 vision using the data url:
```
OpenAIClient api = new OpenAIClient(new Uri($"https://your-endpoint.openai.azure.com/"), new AzureKeyCredential("your-api-key"));
var resp = await api.GetChatCompletionsStreamingAsync(new ChatCompletionsOptions("gpt-4-vision", new ChatRequestMessage[]
{
	new ChatRequestSystemMessage("你是智能AI助理，可以帮用户识别图像，并仔细遵循用户的问题，使用markdown回复。"),
	new ChatRequestUserMessage(new ChatMessageContentItem[]
	{
		new ChatMessageImageContentItem(new Uri(ImageHelper.ReadAsBase64Url(@"C:\Users\ZhouJie\Pictures\car.jpg"))),
		new ChatMessageTextContentItem("这张图里有什么？"),
	})
})
{
	MaxTokens = 4096
});
await foreach (var delta in resp)
{
	if (delta.ContentUpdate == null) continue;
	Console.Write(delta.ContentUpdate);
}
```

This line of code will causing the issue:
```csharp
new Uri(ImageHelper.ReadAsBase64Url(@"C:\Users\ZhouJie\Pictures\car.jpg"))
```

### Environment

.NET 8, LINQPad 8

**Comment by angandin** [comment]
Hi everyone, is there any update on this bug? I am trying with new library Azure.AI.OpenAI 1.0.0-beta.**13** but still having this issue

**Comment by jose-villegas-shift** [comment]
Same here.

**Comment by dersia** [comment]
I am working on this issue https://github.com/microsoft/semantic-kernel/issues/4781 and as Part of that I have implemented the use of `BinaryData` next to the `Uri`. This is sufficient to make this work, although I'd love to see `Uri` fixed to allow bigger content, I don't think this will be fixed before .NET 9. 

If `Azure.AI.OpenAI.ChatMessageImageUrl` would take a string instead of a Uri, this would solve the issues that we have before I can merge my PR for SK.

I think that changing it from `Uri` to `string` can be a potential breaking change, therefor I suggest to keep the `Uri` ctor and add another one that takes string and then have an internal or Property `dataUri` of type `string` which is then used when serializing and sending to the endpoint. The public Property `Url` can then be changed to create a `Uri` upon access from the `dataUri`, this might throw but I would say this is a good compromise.

**Comment by masegraye** [comment]
@dersia You're my hero.

**Comment by dersia** [comment]
@jpalvarezl @trrwilson can you please check this issue and my comment? I'd like to merge my PR in Semantic Kernel and we have customers waiting for this.

**Comment by vandana2015** [comment]
Any ETA for this to be made available?

**Comment by scottaddie** [comment]
This support exists in versions 1.0.0-beta.17 and later. See the changelog entry at https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/openai/Azure.AI.OpenAI/CHANGELOG.md#features-added-3.
