### ISSUE TITLE
ProvisioningState property is a string as opposed to an Enum so we must document possible values

### ISSUE THREAD

**Issue by GePerez** [Azure/azure-sdk-for-net#40863]
### Type of issue

Missing information

### Description

The documentation at:
https://learn.microsoft.com/en-us/dotnet/api/azure.resourcemanager.compute.virtualmachinescalesetvmdata.provisioningstate?view=azure-dotnet#azure-resourcemanager-compute-virtualmachinescalesetvmdata-provisioningstate

Does not list all possible values of ProvisioningState.

### Page URL

https://learn.microsoft.com/en-us/dotnet/api/azure.resourcemanager.compute.virtualmachinescalesetvmdata.provisioningstate?view=azure-dotnet#azure-resourcemanager-compute-virtualmachinescalesetvmdata-provisioningstate

### Content source URL

https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Azure.ResourceManager.Compute/VirtualMachineScaleSetVMData.xml

### Document Version Independent Id

31ee30ad-77c7-23f7-47c8-6d45332685aa

### Article author

@azure-sdk

### Metadata

* ID: 8b20f195-789e-9187-ae38-1c9025e2b59a 
* Service: **azure**

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by ArthurMa1978** [comment]
Hey @GePerez, thank you for reaching out to us about the Azure SDK for .NET. Unfortunately, this issue is coming from the [swagger spec](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/compute/resource-manager/Microsoft.Compute/ComputeRP/stable/2023-09-01/virtualMachineScaleSet.json#L5909) which is owned by service team, so we are not able to help you with it. Therefore, we are closing this issue for now. If you need more assistance, please [open an Azure support request](https://docs.microsoft.com/azure/azure-portal/supportability/how-to-create-azure-support-request). We apologize for any inconvenience this may cause you.

We value your feedback and we want to make sure that your problem is solved. If you think that we have misunderstood your issue or closed it incorrectly, please feel free to comment on this thread and reopen the issue. We will be happy to assist you further. Thank you for your understanding and cooperation.
