### ISSUE TITLE
[BUG] Azure.Search.Documents 11.5.1 removed Vectorizer from VectorSearchProfile 

### ISSUE THREAD

**Issue by freistli** [Azure/azure-sdk-for-net#40883]
### Library name and version

Azure.Search.Documents 11.5.1

### Describe the bug

Azure.Search.Documents 11.5.1 removed Vectorizer in VectorSearchProfile without clear explanation, seems Devloper needs to use external component to embed text again, instead of integration method introduced from 2023-10-01-preview

### Expected behavior

11.5.0-beta.5 uses Vectorizer in VectorSearchProfile. This matches the description in  https://learn.microsoft.com/en-us/rest/api/searchservice/indexes/create-or-update?view=rest-searchservice-2023-10-01-preview&tabs=HTTP#vectorsearch.

11.5.1 removed Vectorizer from VectorSearchProfile, and also matches the description in https://learn.microsoft.com/en-us/rest/api/searchservice/indexes/create-or-update?view=rest-searchservice-2023-11-01&tabs=HTTP#vectorsearch

The problem is there is not detailed reason to explain the change, and even from the official document, it said 2023-11-01, it has no break change based on https://learn.microsoft.com/en-us/azure/search/search-api-migration

***If you added vector support using 2023-10-01-preview, there are no breaking changes***

And this official document link, it still uses Vecorizer:
https://learn.microsoft.com/en-us/azure/search/vector-search-how-to-configure-vectorizer

The latest SDK contains conflicting logic with API usage and description.

### Actual behavior

Azure.Search.Documents 11.5.1 removed Vectorizer caused project compilation and break changes from 11.5.0-beta5

### Reproduction Steps

Build this sample with 11.5.1
https://github.com/Azure/azure-search-vector-samples/blob/main/demo-dotnet/DotNetIntegratedVectorizationDemo/Program.cs#L123

**Comment by jsquire** [comment]
Hi @freistli.  Thanks for reaching out and we regret that you're experiencing difficulties.   The reason that `Vectorizer` was removed for the v11.5.0 release is because it is a preview feature that is not supported in the stable version of the Azure Search service.   A stable version of the client library is unable to depend on a preview version of the service.  Should the feature progress to stable and support is added to the Search service, the client library will also support it.  Likewise, should the feature continue to exist in the preview version of the Search service, the next preview release of the client library will support it.

Please be aware that our beta releases should be considered unstable and potentially disruptive changes should be expected from release-to-release.  We do not guarantee that the public API will not change in our beta releases nor are those changes considered breaking.   Our stable releases, on the other hand, do follow the [.NET Breaking Change Rules](https://github.com/dotnet/runtime/blob/main/docs/coding-guidelines/breaking-change-rules.md) per the [Azure Design Guidelines](https://azure.github.io/azure-sdk/dotnet_introduction.html#dotnet-versioning).

### Additional resources

- [Azure Search REST API Spec v2023-11-01 (stable)](https://github.com/Azure/azure-rest-api-specs/tree/main/specification/search/data-plane/Azure.Search/stable/2023-11-01)
- [Azure Search REST API Spec v2023-10-01-Preview (preview)](https://github.com/Azure/azure-rest-api-specs/tree/main/specification/search/data-plane/Azure.Search/preview/2023-10-01-Preview)
