### ISSUE TITLE
[QUERY] How processor deal with dead letter queue by default?

### ISSUE THREAD

**Issue by maomaomqiu** [Azure/azure-sdk-for-net#40932]
### Library name and version

Azure.Messaging.ServiceBus (7.15.0)

### Query/Question

How processor deal with dead letter queue by default?

This question is ask from my colleague @AbeGeMS 

We use processor in out part of code, we initialize it like below
```
   //  ServiceBusProcessorOptionAdapter is class defined by ourselves to package ServiceBusProcessorOptions, it's Inner is ServiceBusProcessorOptions
    var optionAdapter = ServiceBusProcessorOptionAdapter.Create();
    optionAdapter.MaxConcurrentCalls = 10;
    optionAdapter.ReceiveMode = FormServiceBusReceiveMode.PeekLock;
    optionAdapter.SubQueue =FormServiceBusSubQueue.None;

    
    var newProcessor = Client.CreateProcessor(queueName, options: processorOptionAdapter.Inner);
```

And we observer a phenomenon, this is Dead-Letter amount
![image](https://github.com/Azure/azure-sdk-for-net/assets/154726587/1bb54b97-90eb-40cf-ae7d-cea094482332)
after several seconds, the deadletter count will be
![image](https://github.com/Azure/azure-sdk-for-net/assets/154726587/ff6e6a4d-54fc-4074-a0d8-b06227246f74)
decreased nearly a half..

We did not create dead letter processor to handle dead letter, so how processor handle dead letter by default?

If you could point out key points in source code, we would be really grateful, greatly thanks in advance!

**Comment by AbeGeMS** [comment]
@jsquire , thank you for your prompt response. I understand the process for handling DLQ messages, but we have encountered an issue. We have not taken any action on the DLQ. However, we have noticed that the DLQ message count randomly increases or decreases in the Azure portal. According to the official documentation, the DLQ message count should always increase in our case, but the Azure portal shows otherwise. I would like to know if there are any other conditions under which Service Bus removes DLQ messages, such as if the message size exceeds the Service Bus quota.
BTW, our message volume is quite large, even exceeding 70GB. Additionally, if I never handle the DLQ messages and they exceed 80GB, what will happen? Thank you for your assistance.

**Comment by AbeGeMS** [comment]
Jsquire, thank you for your prompt response. I understand the process for handling DLQ messages, but we have encountered an issue. We have not taken any action on the DLQ. However, we have noticed that the DLQ message count randomly increases or decreases in the Azure portal. According to the official documentation, the DLQ message count should always increase in our case, but the Azure portal shows otherwise. I would like to know if there are any other conditions under which Service Bus removes DLQ messages, such as if the message size exceeds the Service Bus quota. Our message volume is quite large, even exceeding 70GB. Additionally, if I never handle the DLQ messages and they exceed 80GB, what will happen? Thank you for your assistance.

**Comment by jsquire** [comment]
@AbeGeMS : The Azure SDK team has no insight or influence over what happens in the Azure portal nor can we comment on service behavior.  As a Microsoft internal, I'd suggest opening an IcM for the Service Bus service team for your inquiries.
