### ISSUE TITLE
[BUG] Authentication signature invalid for hosts with non-default port

### ISSUE THREAD

**Issue by tnc1997** [Azure/azure-sdk-for-net#41051]
### Library name and version

Azure.Data.AppConfiguration 1.3.0

### Describe the bug

I would like to thank you for your work on the Azure SDK for .NET. I am developing an emulator for Azure App Configuration however I have encountered an issue with how the authentication signature is generated in the Azure SDK for .NET compared with the Azure SDK for other languages. When constructing a `ConfigurationClient` with a connection string that has an endpoint that has a host with a non-default port the generated authentication signature is invalid because the [host](https://github.com/Azure/azure-sdk-for-net/blob/7b28451dd86917abd562804ef102ea39fa1efb29/sdk/appconfiguration/Azure.Data.AppConfiguration/src/AuthenticationPolicy.cs#L83) does not include the non-default port. This causes an authentication error when validating the signature because the host in the signature does not include the non-default port but the host header in the request does include the non-default port.

### Expected behavior

I would expect the port to be included in the host if it is non-default (e.g. not 80 nor 443) in order to match the host header.

### Actual behavior

The port is not included in the host if it is non-default (e.g. not 80 nor 443) which does not match the host header.

### Reproduction Steps

https://github.com/tnc1997/azure-app-configuration-issue-reproduction

**Comment by jsquire** [comment]
Hi @tnc1997.  Thanks for reaching out and we regret that you're experiencing difficulties.  It looks like AppConfig is parsing the connection string as expected and is preserving the custom port.  However, each time a request payload is prepared, the manipulation of the URI that takes place is resetting to the base URI, which is also resetting the port.  All of the requests are forced to the standard ports unless a proxy is used.

To me, this looks like a bug in our code generation; I believe the original port should be maintained during the reset.  That said, I'm not certain that this is not an intentional decision made for security reasons, because Azure services are required to use the default HTTP ports.  Because this is not specific to AppConfig and impacts all of the Azure SDK, I'll need to have some internal follow-up conversations before we're sure of the path forward.

### References

- [Example request creation](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/appconfiguration/Azure.Data.AppConfiguration/src/Generated/ConfigurationClient.cs#L1848)
- [Uri.Reset extension](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/core/Azure.Core/src/RequestUriBuilder.cs#L139)

**Comment by jsquire** [comment]
//cc: @kinelski for awareness

**Comment by tnc1997** [comment]
Hi @jsquire, thank you very much for getting back to me! Could this issue potentially be caused by the fact that [`Uri.Host`](https://learn.microsoft.com/en-us/dotnet/api/system.uri.host#remarks) does not include the port even if a non-default port is used? It looks like `Uri.Host` is used in the authentication signature which does not match the host header in the request when a non-default port is used.

**Comment by paulirwin** [comment]
I believe the solution should be to replace `uri.Host` with `uri.Authority` at the line @tnc1997 linked to above so that the port is included. This is backwards compatible with Azure default ports, as `.Authority` will not return the port if it is default for the scheme, even if specified.

**Comment by jsquire** [comment]
It looks like I pulled the wrong builder when I did the initial analysis; the port is maintained on the actual HTTP requests, only the auth policy is misbehaving.   I agree that `Authority` is what we should have used. The fix is out for review in #41077 and will appear in our next release.   In the meantime, it will appear in our [development feed](https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md#1-add-nuget-package-dev-feed) for testing the day after the PR closes.
