### ISSUE TITLE
Filter parameter not documented, what can I query and how?

### ISSUE THREAD

**Issue by bzuidgeest** [Azure/azure-sdk-for-net#41075]
### Library name and version

Azure.ResourceManager.RecoveryServicesBackup

### Query/Question

I have tried different things for filter and this one  

$"backupManagementType eq '{BackupManagementType.AzureWorkload}'"

Is the only one that works. According to examples I should be able to filter on workloadtype to, but that always fails with an error

string filter = "backupManagementType eq 'AzureStorage' and workloadType eq 'SQL'" gives BMSUserErrorInvalidInput  which gives zero information on what is wrong.

Same error when trying to filter on name string filter = "name eq 'blah'";

What am I doing wrong? Where is the documentation for what filter accepts? 

https://github.com/Azure/azure-sdk-for-net/blob/84c0361d53cc0cfa4c71f8267e28d5af34c6b889/sdk/recoveryservices-backup/Azure.ResourceManager.RecoveryServicesBackup/samples/Generated/Samples/Sample_ResourceGroupResourceExtensions.cs#L202

```
         RecoveryServicesVaultResource vault = await resourceGroup.GetRecoveryServicesVaultAsync(vaultName);



            //string filter = $"backupManagementType eq '{BackupManagementType.AzureWorkload}'"; // and workloadType eq 'SQL'"; // and WorkloadType eq 'MSSQL'
            //string filter = $"backupManagementType eq '{BackupManagementType.AzureWorkload}' and name eq 'sqldatabse;{sourceAGName};{sourceDatabaseName}'"; // and WorkloadType eq 'MSSQL'
            //var result = resourceGroup.GetBackupProtectableItems(vaultName, filter);
            string filter = "contains(Name, 'idm')";
            AsyncPageable<WorkloadProtectableItemResource> result = resourceGroup.GetBackupProtectableItemsAsync(vaultName, filter);

```

### Environment

.net 7

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by bzuidgeest** [comment]
take the example (generated) on this page
https://learn.microsoft.com/en-us/rest/api/backup/backup-protected-items/list?view=rest-backup-2023-02-01&tabs=HTTP

There is an URL with this filter: $filter=backupManagementType eq 'AzureIaasVM' and itemType eq 'VM'

In the response there is a backupManagementType property, but its hidden in a subproperties named properties. There is not property named "itemType" at all, but its value seems to match up with workloadtype. Am I to guess as to what the actual propertyname is to filter the list on "name"?

**Comment by bzuidgeest** [comment]
Using trail and error the following querystring doesn't throw errors, it also doesn't filter anything, things like friendlyname seems to be completely ignored, 

string filter = $"backupManagementType eq '{BackupManagementType.AzureWorkload}' and workloadType eq 'SQLDatabase' AND friendlyName eq '{sourceDatabaseName}'";

**Comment by HarveyLink** [comment]
Hey @bzuidgeest  , thank you for reaching out to us about the Azure SDK for .NET. Unfortunately, this issue is related to the service side and not the SDK side, so we are not able to help you with it. Therefore, we are closing this issue for now. If you need more assistance, please [open an Azure support request](https://docs.microsoft.com/azure/azure-portal/supportability/how-to-create-azure-support-request). We apologize for any inconvenience this may cause you.

We value your feedback and we want to make sure that your problem is solved. If you think that we have misunderstood your issue or closed it incorrectly, please feel free to comment on this thread and reopen the issue. We will be happy to assist you further. Thank you for your understanding and cooperation.
