### ISSUE TITLE
ServiceBusAdministrationClient Mocking

### ISSUE THREAD

**Issue by azad1612** [Azure/azure-sdk-for-net#41170]
### Library name and version

Azure.Messaging.ServiceBus.Administration

### Query/Question

Hi
I am using Azure.Messaging.ServiceBus 7.17.1 nuget package.

Trying Mock 'ServiceBusAdministrationClient' class and invoking TopicExistsAsync() and expecting value as true, but it is returning null values. please refer below screen code

var blobContainerClientResponseMock = new Mock<Response>();
            blobContainerClientResponseMock.Setup(e => e.Status).Returns(200);
            blobContainerClientResponseMock.Setup(e => e.ReasonPhrase).Returns("OK");
            var test = Response.FromValue(true, blobContainerClientResponseMock.Object);
var mockManagementClient = new Mock<ServiceBusAdministrationClient>("Endpoint=sb://abcdservicebus.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=NdfdfefefegpblMv5hiUTQ=");
var var = mockManagementClient.Setup(e => e.TopicExistsAsync("ops/achive", new System.Threading.CancellationToken())).Returns(result);

But its it returning null.

refer below screen shot
<img width="580" alt="image" src="https://github.com/Azure/azure-sdk-for-net/assets/147412434/c48e7893-7f8f-4627-b55e-468af8736221">

Please help on this

**Comment by jsquire** [comment]
Hi @azad1612.  Thank you for reaching out and we regret that you're experiencing difficulties.   Your code is not valid nor compliable in its current state, but if your actual code is using the same pattern then the likely problem is that your setup is incorrect:

```csharp
mockManagementClient.Setup(e => e.TopicExistsAsync("ops/achive", new System.Threading.CancellationToken())).Returns(result);
```

This will never match your actual call because you're telling the mocking framework to only match against the specific cancellation token reference that you're creating in the setup.  However, since you create the instance and throw it away, it will never match.   You'd want to use a less restrictive constraint.  For example, in Moq, this would look like `It.IsAny<CancellationToken>()`.

An end to end example would look something like:

```csharp
var mockResponse = new Mock<Azure.Response<bool>>();    
var mockClient = new Mock<ServiceBusAdministrationClient>();
    
mockResponse
    .SetupGet(response => response.Value)
    .Returns(true);

mockClient
    .Setup(client => client.TopicExistsAsync(
        "ops/achive",
        It.IsAny<CancellationToken>()))
    .ReturnsAsync(mockResponse.Object);
    
var existsResponse = await mockClient.Object.TopicExistsAsync("ops/achive", CancellationToken.None);
Assert.That(existsResponse.Value, Is.True);
```

More discussion and examples can be found in [Mocking Service Bus Clients](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/servicebus/Azure.Messaging.ServiceBus/samples/Sample15_MockingClientTypes.md#creating-topics-and-subscriptions-using-the-servicebusadministrationclient) and [Unit testing and mocking with the Azure SDK for .NET](https://learn.microsoft.com/dotnet/azure/sdk/unit-testing-mocking).

**Comment by azad1612** [comment]
Hi @jsquire Thanks for the helps this resolved my error. please help me to mock GetNamespacePropertiesAsync() and GetSubscriptionsAsync() methods in ServiceBusAdministrationClient class.
