### ISSUE TITLE
ClientModel: Determine whether private ModelBinaryContent<T> type in BinaryContent needs ModelWriter field

### ISSUE THREAD

**Issue by annelo-msft** [Azure/azure-sdk-for-net#41199]
Tracking resolution of this comment thread: https://github.com/Azure/azure-sdk-for-net/pull/41085#discussion_r1447690898

**Comment by m-nash** [comment]
The reason for the `_writer` field in my original implementation was to avoid a double serialize.

If a consumer has an instance of `BinaryContent` they can do 2 main call patterns that would affect this.

In the following usage knowing the length is important as it allows us to avoid resizing our memory stream.
```c#
BinaryContent myContent = GetContent();
if (!myContent.TryComputeLength(out var capacity))
  capacity = 0;
using MemoryStream stream = new MemoryStream(capacity);
myContent.WriteTo(stream);
```

In this usage we are sending to some other stream we don't own perhaps a network stream where knowing the size ahead of time does not matter
```c#
BinaryContent myContent = GetContent();
Stream stream = GetStream();
myContent.WriteTo(stream);
```

In order to know the length we must serialize into the shared buffers.  If we dispose of this internal and not keep a cached value of `_writer` around then when the WriteTo method is called we will again incur the cost of serializing a second time.

**Comment by KrzysztofCwalina** [comment]
@m-nash, why don't we cache the serialized bytes the first time we serialize (for whatever reason). The second time some API is called that needs the serialized content, we just use the cached array.

**Comment by m-nash** [comment]
By keeping `_writer` around we are effectively caching the serialized bytes.  If we move them to another contiguous buffer that will incur an unnecessary alloc / mem copy vs keeping them in the fragmented shared buffers until they are ready to go to their final destination.

**Comment by KrzysztofCwalina** [comment]
why would we need to copy? Don't we have an API to get reference[s] to the buffer[s]?

**Comment by m-nash** [comment]
Originally we did with a method to get them as a ReadOnlySequence<byte> however we removed all of those due to the use after free it exposes until we have time to solve for that.

`_writer` instance is your only `reference[s] to the buffer[s]`

**Comment by m-nash** [comment]
Spoke offline and I think we want to go with the following.

Create an internal class `SequenceBuffer` which holds an instance to shared buffers written by SequenceBuilder but does not expose the IBufferWriter APIs.  The only public methods on `SequenceBuffer` should be `CopyTo`, `CopyToAsync` and `TryComputeLength`.

This will allow us to reduce the complexity / memory footprint of what we need to hold around since `ModelWriter` is a fairly heavy weight object vs `SequenceBuffer` will just be the finalized buffers.

**Comment by annelo-msft** [comment]
Addressed in https://github.com/Azure/azure-sdk-for-net/pull/41560
