### ISSUE TITLE
[QUERY] Azure Form Recognizer DocumentFieldType always returns Unknown but expecting DocumentFieldType.Double

### ISSUE THREAD

**Issue by jlunarzewski** [Azure/azure-sdk-for-net#41247]
### Library name and version

Azure.AI.FormRecognizer 4.0.0

### Query/Question

Trying to map some values from Azure form recognizer Custom Extraction Model. Within Form Recognizer studio the field is type `number` -> `not-specified`. I would imagine this would map to the `DocumentFieldType.Double` within the C# library but it keeps returning as `DocumentFieldType.Unknown`. What is the correct way to map non-currency numeric values? Updating the library version to 4.1.0 does not help.

Here is the output json from the recognition for a field. I'd imagine it not having a `valueNumber` field might have something to do with it but I don't quite understand why it doesn't have one.

```
"WaterMeterReadingFrom": {
	"type": "number",
	"content": "2568",
	"boundingRegions": [
		{
			"pageNumber": 2,
			"polygon": [
				4.868,
				1.6141,
				5.1725,
				1.6141,
				5.1725,
				1.7562,
				4.868,
				1.7562
			]
		}
	],
	"confidence": 0.964,
	"spans": [
		{
			"offset": 1866,
			"length": 4
		}
	]
},
```
### Environment

Windows 11 .NET7.0
JetBrains Rider 2023.3.2

**Comment by pallavit** [comment]
Tagging and routing to the member best able to assist you. /cc:@kinelski

**Comment by kinelski** [comment]
@jlunarzewski ,

The SDK exposes the field type as `Unknown` because it lacks a `valueNumber`, as you noticed. This means that the service was not able to parse it into a floating point value on their end. If you still want to extract it as a number, you can get the string representation of the field in `DocumentField.Content` and you will need to parse it on your side.

You can still extract the expected field type from the `DocumentField.ExpectedType` property, which should be set to `Double`.
