### ISSUE TITLE
Close whether BinaryContent should live in System.ClientModel or System.ClientModel.Primitives

### ISSUE THREAD

**Issue by pallavit** [Azure/azure-sdk-for-net#41310]
It would stay in S.CM namespace if it would be used in convenience methods.
"Will it show in public APIs that are not protocol methods?" <-- criteria for inclusion in S.CM namespace.

**Comment by annelo-msft** [comment]
## What namespace should BinaryContent live in?

In ClientModel today, `BinaryContent` lives in the `System.ClientModel` namespace.

We have a principle that "types used in convenience methods should live in the `System.ClientModel` namespace."  If a type will only ever appear in a client's protocol method signature (or used internally to a client, or for other scenarios), it would live in the `System.ClientModel.Primitives` namespace.

As such, to put `BinaryContent`in the `System.ClientModel` namespace, we should believe that we would reasonably include it in a convenience API someday.  Even if we were _somewhat_ confident we might want to do this, we should put it in the root namespace.  This is because if we were to put it in the `.Primitives` namespace and later decide to use it in a convenience API, users working at the convenience layer might be confused about why they were using types from the `.Primitives` namespace.  Keeping it in the root namespace gives us the flexibility to use it in convenience APIs down the road without such confusion.  If we _never_ use it in a convenience API, then it will be regrettable to have added an unnecessary type to the root namespace, and may add confusion about protocol-layer types living in the namespace reserved for convenience APIs.

### Planned evolution of BinaryContent

Today, `BinaryContent` has the following API definition:

```csharp
public abstract partial class BinaryContent : System.IDisposable
{
    protected BinaryContent() { }
    public static System.ClientModel.BinaryContent Create(System.BinaryData value) { throw null; }
    public static System.ClientModel.BinaryContent Create<T>(T model, System.ClientModel.Primitives.ModelReaderWriterOptions? options = null) where T : System.ClientModel.Primitives.IPersistableModel<T> { throw null; }
    public abstract void Dispose();
    public abstract bool TryComputeLength(out long length);
    public abstract void WriteTo(System.IO.Stream stream, System.Threading.CancellationToken cancellationToken);
    public abstract System.Threading.Tasks.Task WriteToAsync(System.IO.Stream stream, System.Threading.CancellationToken cancellationToken);
}
```

We expect to add Create methods like the ones on Azure.Core's `RequestContent` today, e.g.:

```csharp
    public static System.ClientModel.BinaryContent Create(System.IO.Stream stream) { throw null; }
```

Stream overloads will enable streaming inputs that don't need to be buffered in memory.

### Example Convenience APIs

With the stream overload, we might add the following method, e.g. to `BlobClient`:

```csharp
blobClient.Upload(BinaryContent.Create(fileStream));
```

Or, to `DataMovement`:

```csharp
await transferManager.StartTransferAsync(BinaryContent.FromPath("c:\\largefilepath.txt"));
await transferManager.StartTransferAsync("c:\\largefilepath.txt".ToBinaryContent());
await transferManager.StartTransferAsync(BinaryContent.FromUri(new Uri("www.mylargeblob.com")));
```

### Questions

- **Couldn't we just use [BinaryDataSource](https://github.com/dotnet/runtime/issues/89804)?**

  We could, but we could also reduce the number of types in the Core libraries if we used `BinaryContent` for scenarios where we are considering using `BinaryDataSource`.  To do this, we might add `FromPath` and `FromUri` for inputs and `ToBinaryData` for outputs.

- **If we added `ToBinaryData` to `BinaryContent`, wouldn't that add it to `RequestContent` in the Azure.Core 2.0 integration with ClientModel, and be weird having output APIs on the `RequestContent` input type?**

  It might be a bit strange to see at first, but we had a partner request this API today to make it easier to inspect `Request.Content` from a pipeline policy.

**Comment by annelo-msft** [comment]
## Proposal

The recommendation is to keep `BinaryContent` in the `System.ClientModel` namespace.
