### ISSUE TITLE
[BUG] MissingMethodException on updating Azure.Identity to 1.10.2

### ISSUE THREAD

**Issue by gupta-sk** [Azure/azure-sdk-for-net#41338]
### Library name and version

Azure.Identity 1.10.2, Azure.Core 1.35.0, Azure.Security.KeyVault.Secrets 4.5.0

### Describe the bug

We are trying to update the Azure.Identity package from 1.8.2 to 1.10.2 as recommended by the component governance.
Now, since version 1.10.2 is dependent on Azure.Core package version >=1.35.0, we also have to upgrade the Azure.Core package from 1.30.0 to 1.35.0.

However, upgrading Azure.Core is causing a missing method exception while using Azure.Security.KeyVault.Secrets package to get secret. Tried to upgrade the packages to latest versions: Azure.Identity 1.10.4 and Azure.Core 1.37.0, but still getting same exception. The exception goes away if we downgrade Azure.Core back to 1.30.0.

### Expected behavior

Should work without any error.

### Actual behavior

Getting method not found error:

System.Exception: Caught exception of type MissingMethodException instead of AggregateException, full exception: Method not found: 'Void Azure.Security.KeyVault.Secrets.SecretClient..ctor(System.Uri, Azure.Core.TokenCredential)'.

### Reproduction Steps

<img width="655" alt="image" src="https://github.com/Azure/azure-sdk-for-net/assets/156887893/6de357a1-1c76-4cf9-b871-1d58f4b81b27">

**Comment by jsquire** [comment]
Hi @gupta-sk.  Thank you for reaching out and we regret that you're experiencing difficulties.  Most commonly, these types of errors are due to mismatched dependencies on certain platforms or transient references.   Unfortunately, there is not enough context available in this issue to reproduce the behavior that you're seeing.

Please provide more information about your application:

- Where is the behavior observed (local, CI pipeline only, etc)
- What type of application is it?   (Console, WebApp, Azure Function app, etc)
- Where is it being hosted?
- How is it being deployed?
- What is the full list of packages and versions referenced by the application?

If you're able to share a small, self-contained reproduction that would be quite helpful.

**Comment by gupta-sk** [comment]
I tried getting the fusion logs and found out it's a dependency binding issue.

Currently, one of the solutions is using Azure.Identity (1.10.4), Azure.Security.KeyVault.Secrets (4.6.0).

Now, Azure.Identity depends on Azure.Core (1.36.0) while Azure.Security.KeyVault.Secrets depends on Azure.Core (1.37.0).
Having 1.37.0 version, gives binding failure for Azure,Identity package.

Even the assembly redirects are not working (maybe because this is indirect dependency).

Any suggestions on how to resolve this?

I am an internal customer who works in AzNet on RNM service, where we are facing this issue.
