### ISSUE TITLE
[Service bus Administration] Unit test cases mocking for GetNamespacePropertiesAsync() & GetSubscriptionsAsync()

### ISSUE THREAD

**Issue by Piyushmumbaiwala007** [Azure/azure-sdk-for-net#41354]
### Library name and version

Azure.Messaging.ServiceBus.Administration 7.17.1

### Query/Question

Hi
I am using Azure.Messaging.ServiceBus 7.17.1 nuget package.

Trying Mock 'ServiceBusAdministrationClient' class and invoking GetNamespacePropertiesAsync() & GetSubscriptionsAsync() and expecting value as true, but it is returning null values. please refer below screen code

Below are the mocking method, but getting issue, can you please help us out to resolve this mocking issue. 

**_GetNamespacePropertiesAsync_()**
var mockResponseNamespace = new Mock<Azure.Response<NamespaceProperties>>();
            NamespaceProperties namespaceProperties = null;
            mockResponseNamespace.SetupGet(response => response.Value).Returns(namespaceProperties);
            mockClient.Setup(e => e.GetNamespacePropertiesAsync(new System.Threading.CancellationToken())).ReturnsAsync(mockResponseNamespace.Object);
var rest = mockClient.Object.GetNamespacePropertiesAsync().Result.Value.MessagingSku;

**_GetSubscriptionsAsync()_**
var mockResponseSubscription = new Mock<AsyncPageable<SubscriptionProperties>>();
mockResponseSubscription.SetupGet(response => response).Returns(new AsyncPageable<SubscriptionProperties>());
 mockClient.Setup(e => e.GetSubscriptionsAsync(It.IsAny<string>(), It.IsAny<CancellationToken>())).ReturnsAsync(mockResponseSubscription.Object);

Above are the mocking method, but getting issue, can you please help us out to resolve this mocking issue. 

Thanks in advance.

**Comment by jsquire** [comment]
Hi @azad1612.  Thank you for reaching out and we regret that you're experiencing difficulties.   Your code is not valid nor compliable in its current state, but if your actual code is using the same pattern then the likely problems are that your setup is incorrect, that the method you are calling does not return a true/false response, and that you are not populating the `NamespaceProperties` that you're returning, so the value of your response is actually `null`.

```csharp

// There is no value assigned
NamespaceProperties namespaceProperties = null;

// This setup won't ever match because you're bound to a specific instance
// of CancellationToken, which you define inline.
mockClient
    .Setup(e => e.GetNamespacePropertiesAsync(new System.Threading.CancellationToken()))
    .ReturnsAsync(mockResponseNamespace.Object);
```

This will never match your actual call because you're telling the mocking framework to only match against the specific cancellation token reference that you're creating in the setup.  However, since you create the instance and throw it away, it will never match.   You'd want to use a less restrictive constraint.  For example, in Moq, this would look like `It.IsAny<CancellationToken>()`.

An end to end example would look something like:

```csharp
var mockResponse = new Mock<Azure.Response<NamespaceProperties>>();
var mockClient = new Mock<ServiceBusAdministrationClient>();

var namespaceProperties = new NamespaceProperties();

mockResponse
    .SetupGet(response => response.Value)
    .Returns(namespaceProperties!);

mockClient
    .Setup(client => client.GetNamespacePropertiesAsync(
        It.IsAny<CancellationToken>()))
    .ReturnsAsync(mockResponse.Object);

var nsResponse = await mockClient.Object.GetNamespacePropertiesAsync(CancellationToken.None);
Assert.That(nsResponse.Value, Is.EqualTo(namespaceProperties));
```

There is one problem that I noticed while mocking this up; the `ServiceBusModelFactory` does not allow creation of a populated `NamespaceProperties` instance for testing.   I've filed #41356 to address that.  In the meantime, you'd have to work around by using reflection to invoke the internal setters:

```csharp
var namespaceProperties = new NamespaceProperties();

typeof(NamespaceProperties)
    .GetProperty("Name", BindingFlags.Instance | BindingFlags.Public)
    .GetSetMethod(true)
    .Invoke(namespaceProperties, new[] { "value of name" });
```

The approach for your second example is similar, but requires you to setup the pagables:

```csharp
var mockClient = new Mock<ServiceBusAdministrationClient>();

// Create a set of subscriptions to use for the first (only) page.
var subscriptions = new[]
{
    ServiceBusModelFactory.SubscriptionProperties(
        "topic1", 
        "sub1", 
        lockDuration: TimeSpan.FromDays(1), 
        defaultMessageTimeToLive: TimeSpan.FromDays(1), 
        autoDeleteOnIdle: TimeSpan.FromDays(1),
        maxDeliveryCount: 1,
        userMetadata: "empty"),

    ServiceBusModelFactory.SubscriptionProperties(
        "topic2",
        "sub2",
        lockDuration: TimeSpan.FromDays(1),
        defaultMessageTimeToLive: TimeSpan.FromDays(1),
        autoDeleteOnIdle: TimeSpan.FromDays(1),
        maxDeliveryCount: 1,
        userMetadata: "empty")
};

// Create the pagable with a single page of subscriptions.
var pageable = AsyncPageable<SubscriptionProperties>.FromPages(new[]
{
    Page<SubscriptionProperties>.FromValues(subscriptions,
    continuationToken: null,
    Mock.Of<Response>())
});
    
mockClient
    .Setup(client => client.GetSubscriptionsAsync(
        It.IsAny<string>(),
        It.IsAny<CancellationToken>()))
    .Returns(Response.FromValue(pageable, Mock.Of<Response>()));
    
var result = mockClient.Object.GetSubscriptionsAsync("anyTopic");

Assert.That(result, Is.Not.Null);

await foreach (var item in result)
{
    Assert.That(item.TopicName.StartsWith("topic"), Is.True);
}
```

More discussion and examples can be found in [Mocking Service Bus Clients](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/servicebus/Azure.Messaging.ServiceBus/samples/Sample15_MockingClientTypes.md#creating-topics-and-subscriptions-using-the-servicebusadministrationclient) and [Unit testing and mocking with the Azure SDK for .NET](https://learn.microsoft.com/dotnet/azure/sdk/unit-testing-mocking).

**Comment by jsquire** [comment]
@Piyushmumbaiwala007 :  The same techniques would apply.  There's nothing fundamentally different than the above.   Please reference the article and sample above and adapt for the additional methods.
