### ISSUE TITLE
Security: No CVE free Azure.Identity 1.3.x available for consumption in e.g. Microsoft.Data.SqlClient 3.1.x

### ISSUE THREAD

**Issue by simdanne** [Azure/azure-sdk-for-net#41448]
### Library name and version

Azure.Identity 1.3.x

### Describe the bug

Hi,
The still supported Microsoft.Data.SqlClient has a dependency on Azure.Identity >=1.3.0.

The recently released 3.1.5 version of this thereby still pulls in a version of Azure.Identity that has open CVEs against it (CVE-2023-36414).

I would expect that Azure.Identity team provides a bugfix release of 1.3.x, so the Microsoft.Data.SqlClient can release a 3.1.x that pulls a fixed version in. Upgrading to another minor version that has the fix is impossible for Microsoft.Data.SqlClient since Azure.Identity in already released fixed versions have way different depedencies clashing with MDS.

see https://github.com/dotnet/SqlClient/issues/2296 for reference.

### Expected behavior

Azure Identity team should backport fix for CVE to 3.1.x. Then MDS team should consume backport.

### Actual behavior

No release available that fixes CVE.

### Reproduction Steps

none needed.

### Environment

none needed.

**Comment by ErikEJ** [comment]
@simdanne Microsoft.Data.SqlClient does not expose the vulnerability in Azure.Identity

**Comment by jsquire** [comment]
Hi @simdanne.  Thank you for reaching out and we regret that you're experiencing difficulties.   The Azure SDK packages make all bug fixes and features against the latest version of our packages only.  We do not maintain separate lifecycles for earlier releases.   For more context, see the [Azure SDK lifecycle and support policy](https://azure.github.io/azure-sdk/policies_support.html#package-lifecycle).

The underlying issue is that the `Microsoft.Data.SqlClient` library is using a 3+ year old version of `Azure.Identity` and should move to the latest release.   In order to ensure that the team best able to assist has visibility, this issue has been transferred to the repository where the `Microsoft.Data.SqlClient` is maintained as [#2312](https://github.com/dotnet/SqlClient/issues/2312).
