### ISSUE TITLE
Add support for Partitioned Cookies

### ISSUE THREAD

**Issue by Ajay100000** [Azure/azure-sdk-for-net#41531]
### Library name and version

Azure 8.0.1

### Query/Question

Is your feature request related to a problem? Please describe the problem.

Azure should support the new Partitioned property from the CHIPS (Cookies Having Independent Partitioned State) spec. to prevent google chrome blocking these cookies.

Both Chrome and Safari have indicated their support.

Describe the solution you'd like

Change Azure cookies like ARRAffinitySameSite to be partitioned please.

Additional context
My company uses Azure and we use partitioned cookies for our httponly cookies. However Azure is a problem as shown in the attached screenshot.

![Azure_cookie_issue](https://github.com/Azure/azure-sdk-for-net/assets/107861091/52376c0a-26fb-4fe1-b8ef-3b7edbd6c1e3)

### Environment

Azure Appservice deployed from Dotnet Core v8.0.1

**Comment by jsquire** [comment]
Hi @Ajay100000.  Thank you for reaching out and we regret that you're experiencing difficulties.  Unfortunately, this repository is focused on the Azure SDK for .NET - we're unable to assist with other Azure issues.  Since what you're describing appears to be related to how the AppService hosting environment behaves, your best path forward would be to [open an Azure support request](https://docs.microsoft.com/azure/azure-portal/supportability/how-to-create-azure-support-request).

I'm going to close this out;  if I've misunderstood what you're describing, please let us know in a comment and we'd be happy to assist as we're able.
