### ISSUE TITLE
[FEATURE REQ] ServiceBus: TCP Transport without TLS

### ISSUE THREAD

**Issue by PejmanNik** [Azure/azure-sdk-for-net#41581]
### Library name

Azure.Messaging.ServiceBus

### Please describe the feature.

ServiceBus client only supports transport over TLS and it making it challenging to establish a local emulator. [This is my attempt](https://github.com/PejmanNik/lazvard-message) to create a service bus emulator, but deploying it on a development machine or a Docker container poses difficulties due to the requirement for trusted self-signed certificates.

Enabling TCP connectivity for Azure service bus client can significantly enhance the installation process or emulators, making it more straightforward and user-friendly.

**Comment by jsquire** [comment]
Hi @PejmanNik.  Thank you for reaching out and for your feature suggestion.  Unfortunately, this is not one that we'll be moving forward with in the short-term.  The Azure SDK clients are intended to be used with Azure services and products, which require the use of TLS when establishing connections.   Introducing an option to disable TLS would be confusing for developers, as it must be used with Azure Service Bus and introduces a potential security concern.

There is an official Azure Service Bus emulator planned _(see: [feature request](https://feedback.azure.com/d365community/idea/d45a6423-2225-ec11-b6e6-000d3a4f0f84))_ which will be supported by the Azure SDK package.  The design is not yet known, but if the official emulator requires non-TLS support, then we'll look at enabling it in a way that is specific to a local emulator context rather than general option.  Depending on the design, it may be possible to use that with non-official emulators.

In the meantime, if you'd like to create a local build of the client without TLS to aid in the development of your emulator, I'd be happy to walk you through the set of changes needed to do so.

**Comment by PejmanNik** [comment]
That is great, Thank you for letting me know, I would probably archive my emulator when there is an official one, but until then It could make it much easier to setup the emulator
