### ISSUE TITLE
[FEATURE REQ] OpenRead for BlockBlob should return properties

### ISSUE THREAD

**Issue by jbayardo** [Azure/azure-sdk-for-net#41697]
### Library name

Azure.Storage.Blobs

### Please describe the feature.

There's currently 2 families of methods to download blobs `OpenRead` and `DownloadStreaming`. As per https://github.com/Azure/azure-sdk-for-net/issues/22022 , the former is better for chunked downloads (because the connection is returned to the connection pool), and the latter is better for quick usages (because the pool is held for the lifetime of the stream).

Both families of methods do a `GetProperties` call as their first order of business as part of determining how to chunk the download, and potentially upon reaching the end of the stream if concurrent modifications are allowed. They also use this information for client-side encryption.

This is already (in my opinion) not ideal because the initial transfer size is part of the options that are passed in, so it should be possible to start with a range download except for cases where client side encryption is enabled. Nevertheless, that's not the focus of this feature request.

The `DownloadStreaming` family of methods returns the properties it fetches as part of the object, so downstream client code can use these for whatever purposes the client may intend. The `OpenRead` family of methods doesn't.

The problem with this is it leaves clients with bad options if they need to use the properties:
- Do an extra API call on top of the already "unnecessary" GetProperties that the SDK already does to obtain the properties beforehand and determine what needs to be done.
- Call `DownloadStreaming`, which doesn't do chunking and forces you to implement your own.

Ideally, `OpenRead` would return the properties that it's fetching as it's first order of business instead, which would allow downstream clients to rely on those. Even more ideally, none of these methods would call `GetProperties` unless they truly need to (for ex: in client side encryption).

**Comment by seanmcc-msft** [comment]
@jbayardo, the initial GetProperties() call exists so that we can fail fast if the underlying blob does not exist in the service, and so we can obtain the Etag of the blob in question, in case the customer is using allowModifiations == false.

We are [not allowed](https://devblogs.microsoft.com/azure-sdk/azure-approach-to-versioning-and-avoiding-breaking-changes/#:~:text=Azure%E2%80%99s%20policy%20on%20versioning%20and%20breaking%20changes%20rests,new%20API%20version%20without%20requiring%20any%20code%20changes.) to have breaking changes in the Storage SDK.  Today, OpenRead() returns a stream, and changing the return type for an existing API is considered a breaking change.

DownloadStream() returns a Response<BlobDownloadStreamingResult>.  You can access the blob properties with BlobDownloadStreamingResult.Details.
