### ISSUE TITLE
[QUERY] Why isn't there a AddClient overload that accepts an async factory?

### ISSUE THREAD

**Issue by dggmez** [Azure/azure-sdk-for-net#41793]
### Library name and version

Microsoft.Extensions.Azure 1.7.1

### Query/Question

So recently we were adding some Azure clients using the `AddAzureClients` method and we wanted to add some configuration values that are currently stored externally. We used the `AddClient` method that accepts a `Func<TOptions, IServiceProvider, TClient> factory` to get the let's call it the `ICacheService` and call the `GetValueAsync` method that returns a `Task<string>` to get let's say the connection string, the event hub name, etc. We just called `.Result` on the tasks and got it working but I would like to know if there is any reason why there is no `Func<TOptions, IServiceProvider, Task<TClient>> factory` overload to have a factory that calls *and awaits* async methods.

BTW if you think calling `.Result` on those tasks please let me know but we didn't see any other choice.

### Environment

Hosting platform: .NET 6 in-process Azure Functions
IDE and version: Visual Studio 17.8.3

**Comment by jsquire** [comment]
Hi @dggmez.  Thank you for reaching out and we regret that you're experiencing difficulties.  There is no async version of the factory for adding Azure clients, because the underlying [IServiceCollection](https://learn.microsoft.com/dotnet/api/microsoft.extensions.dependencyinjection.iservicecollection?view=dotnet-plat-ext-8.0) interface for the DI container does not support asynchronous operations.  For example, the [TryAddSingleton](https://learn.microsoft.com/dotnet/api/microsoft.extensions.dependencyinjection.extensions.servicecollectiondescriptorextensions.tryaddsingleton?view=dotnet-plat-ext-8.0#microsoft-extensions-dependencyinjection-extensions-servicecollectiondescriptorextensions-tryaddsingleton(microsoft-extensions-dependencyinjection-iservicecollection-system-type-system-func((system-iserviceprovider-system-object)))) method used by the client factory.
