### ISSUE TITLE
Correct usage of  SqlDatabaseResource.GetMetrics

### ISSUE THREAD

**Issue by Fungusware** [Azure/azure-sdk-for-net#41863]
### Library name and version

Azure.ResourceManager.Sql 1.3.0-beta.5

### Query/Question

I'm trying to use the following code :

```
                var metrics = databaseResource.GetMetrics($"name/value eq 'dtu_consumption_percent' and timeGrain eq duration'PT5M' and startTime eq '{startDateUTC.ToString("O")}' and endTime eq '{endDateUTC.ToString("O")}");
                var dtus = new List<string>();
                foreach (var met in metrics.AsPages())
                {
                    foreach (var item in met.Values)
                    {
                        foreach(var metricValue in item.MetricValues)
                        {
                            results.Add(new PerformanceReport()
                            {
                                StartTimeUTC = TimeZoneInfo.ConvertTime(metricValue.Timestamp.Value.UtcDateTime, args.TimeZone, TimeZoneInfo.Utc),
                                AverageDTUPercentage = metricValue.Average.GetValueOrDefault(),
                                MaximumDTUPercentage = metricValue.Maximum.GetValueOrDefault(),
                            }) ;
                        }
                    }
                }
```

My issue is that no mater when I try the values for 

```
AverageDTUPercentage = metricValue.Average.GetValueOrDefault(),
MaximumDTUPercentage = metricValue.Maximum.GetValueOrDefault(),
```

Are always the same, this is equally true for Minimum and Total.

Is there a way I can get these metric in different aggregations?

### Environment

Azure AppService 
.NET 6.0

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by welovej** [comment]
Hi @Fungusware , It's about the delicate usage of the specific function. It would be better go find help from the azure service team.
But I will give you some advice from my view below. Hope it would solve your confusion.
If you always got the same average and maximum value from the dtu_comsumption_percent, it's due to the timerGrain Parameter in your GetMetrics method.
In your case, it's set to `PT5M` which means the data is aggregated every 5 minutes. If the average and maximum value is the same, it could mean the metric value doesn't change during 5-minutes intervals.
So you can increase the aggregation Period Time from 5 to like 30, then you may get some different aggregations.

**Comment by welovej** [comment]
Hi @Fungusware ,  I can not see the picture.

**Comment by Fungusware** [comment]
I have edited my previous post.

**Comment by welovej** [comment]
Hey @Fungusware , thank you for reaching out to us about the Azure SDK for .NET. Unfortunately, this issue is related to the service side and not the SDK side, so we are not able to help you with it. Therefore, we are closing this issue for now. If you need more assistance, please [open an Azure support request](https://docs.microsoft.com/azure/azure-portal/supportability/how-to-create-azure-support-request). We apologize for any inconvenience this may cause you.

We value your feedback and we want to make sure that your problem is solved. If you think that we have misunderstood your issue or closed it incorrectly, please feel free to comment on this thread and reopen the issue. We will be happy to assist you further. Thank you for your understanding and cooperation.
