### ISSUE TITLE
[BUG] Vulnerable transitive package included with Azure.Extensions.AspNetCore.DataProtection.Blobs 1.3.3

### ISSUE THREAD

**Issue by clbarrett** [Azure/azure-sdk-for-net#42102]
### Library name and version

Azure.Extensions.AspNetCore.DataProtection.Blobs 1.3.3

### Describe the bug

When adding the nuget package for Azure.Extensions.AspNetCore.DataProtection.Blobs:1.3.3, I get a vulnerability warning.

![image](https://github.com/Azure/azure-sdk-for-net/assets/107525011/e28be16b-fabc-4d01-8404-a12cdf0e99a9)
Appears to include System.Common.Drawing 4.7.0 with known vulnerabilities.

I've already verified that this is added by the Azure.Extensions.AspNetCore.DataProtection.Blobs.  Has me nervous that there is a known vulnerable package being included with this one.

### Expected behavior

Should import without a vulnerable transative package

### Actual behavior

Get a vulnerability warning in the nuget manager
![image](https://github.com/Azure/azure-sdk-for-net/assets/107525011/4f7e40d5-df5c-460d-9d98-ec1f4ac7084b)

### Reproduction Steps

Get an empty project
Go to nuget package manager
Install Azure.Extensions.AspNetCore.DataProtection.Blobs 1.3.3
Refresh Installed (as needed)

### Environment

Windows 11
Visual Studio 2022
.Net 6.0

**Comment by clbarrett** [comment]
Just to further compound my confusion,  I just added Microsoft.AspNetCore.DataProtection.Extensions:8.0.2 and the System.Common.Drawing transative package vanished.  Removing said package brings it back.

**Comment by jsquire** [comment]
Hi @clbarrett.  Thanks for reaching out and we regret that you're experiencing difficulties.   This traces back to, `System.Security.Permissions` v4.7.0 has a dependency on `System.Windows.Extensions` only for its `netcoreapp3.0` target.  Neither its `netstandard2.0` or `net461` targets hold that dependency.  This has been discussed this with the Azure SDK and .NET security teams and they confirmed that this is considered a false positive by the scanner rather than an active security risk, as the issue being flagged exists only for an unsupported platform.   If you have a need to mitigate the false positive, the recommendation is to take a direct dependency on a version of `Microsoft.AspNetCore.DataProtection` in your application that is not flagged by the scanner. 

 Unfortunately, we're out of minor versions of `Microsoft.AspNetCore.DataProtection` to move to and moving to a new major version requires additional validation and testing.  We're tracking this work in #35707, but I don't currently have an estimate on when we'll have bandwidth to schedule work on it.

**Comment by clbarrett** [comment]
I... just realized that I was using the wrong package for my .Net 6.0 project.  Thanks for letting me know about the situation.
