### ISSUE TITLE
[BUG] Inconsistent Region disply name for US GOV locations

### ISSUE THREAD

**Issue by krizex** [Azure/azure-sdk-for-net#42309]
### Library name and version

Azure.Core 1.37.0

### Describe the bug

We have encountered an issue when comparing the region with its display name for the US GOV location.
For example, the region usgovarizona's display name is "USGov Arizona" in the Azure API response of 
/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Compute/galleries/{galleryName}/images/{galleryImageName}/versions/{galleryImageVersionName}?expand=ReplicationStatus. However, the display name for the same region is defined as "US Gov Arizona" in the Azure.Core namespace ([link](https://github.com/Azure/azure-sdk-for-net/blob/4102eeab6859f0b537ba3cb9442e5f9045a1c273/sdk/core/Azure.Core/src/AzureLocation.cs#L300)). (Please note the extra space between "US" and "Gov"). So it fails when comparing the region with the display name.

### Expected behavior

Comparing region with display name should success

### Actual behavior

failed

### Reproduction Steps

```
var client = new ArmClient(...);
var resourceId = "<Some gallery image version resource in the usgovarizona region>";
var resource = client.GetGalleryImageVersionResource(resourceId);
var resp = await resource.GetAsync("ReplicationStatus").ConfigureAwait(false);
var imageVersion = resp.Value.Data;
var location = new AzureLocation(usgovarizona);
foreach (var region in imageVersion.ReplicationStatus.Summary)
{
    // This will fail
    Assert.AreEqual(region.Region, location.DisplayName);
}
```

**Comment by jsquire** [comment]
Hi @krizex.  Thank you for reaching out and we regret that you're experiencing difficulties.  The mismatch that you're seeing is because the specific service that you're calling returns a different display name than is used by the `AzureLocation` type.   Display names are considered informational and should not be expected to have alignment across different sources.  Region codes, however, are normalized and will match across all of Azure.

The `AzureLocation` display names follow the [official Azure documentation for Government regions](https://azure.microsoft.com/explore/global-infrastructure/geographies/#overview) which refers to them in the format "US Gov ####".   The [documentation for Azure Compute](https://learn.microsoft.com/azure/virtual-machines/regions#special-azure-regions)  uses the same format.  I cannot answer why the Compute service uses something different.

We won't be changing the display format in `AzureLocation`.   If you would like to request that the Compute service changes to align with the format used elsewhere, your best path forward for would be to [open an Azure support request](https://docs.microsoft.com/azure/azure-portal/supportability/how-to-create-azure-support-request) or inquire on the [Microsoft Q&A site](https://learn.microsoft.com/answers/questions/).   You may also want to consider leaving your suggestion on the [Azure Feedback site](https://feedback.azure.com/d365community).

**Comment by krizex** [comment]
Hi @jsquire thanks for your swift response and clarification. If it is not a bug in the SDK, that's fine. I will update my code to comparing the region with the region codes.
