### ISSUE TITLE
Can't set Normalizer or CustomNormalizer for a field in a search index via SDK?

### ISSUE THREAD

**Issue by rzettinger** [Azure/azure-sdk-for-net#42359]
### Library name and version

Azure.Search.Documents 11.5.1

### Query/Question

Hi,

I am using the Azure.Search.Documents nuget to create my AI search index, and query the index. When creating the index one can specify a `CustomAnalyzer`, and one can set a field to use that partical custom analyzer via the attribute `[SearchableField(AnalyzerName = "my_custom_analyzer")]`. No problems. But the same does not go for `CustomNormalizer` (or any pre-defined `normalizer` for that matter).

The class `CustomAnalyzer` can be found under [/Models](https://github.com/Azure/azure-sdk-for-net/tree/main/sdk/search/Azure.Search.Documents/src/Models). The class `CustomNormalizer` can't. Instead, there is one under [Generated/Models](https://github.com/Azure/azure-sdk-for-net/tree/main/sdk/search/Azure.Search.Documents/src/Generated/Models), but that's not part of the SDK, right?.

I can create the desired index, **with** a chosen `normalizer` in the Azure Portal, like so:

```
"fields": [
    {
      "name": "firstName",
      "type": "Edm.String",
      "searchable": true,
      "filterable": true,
      "retrievable": true,
      "sortable": true,
      "facetable": true,
      "key": false,
      "indexAnalyzer": null,
      "searchAnalyzer": null,
      "analyzer": "my_custom_analyzer",
      "normalizer": "my_custom_normalizer",
      "dimensions": null,
      "vectorSearchProfile": null,
      "synonymMaps": []
    }
```

Is it not possible to set a `normalizer` for an AI Search index field via the SDK?

### Environment

Visual Studio 17.9

```
.NET SDK:
 Version:           8.0.200
 Commit:            438cab6a9d
 Workload version:  8.0.200-manifests.e575128c

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22631
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\8.0.200\

.NET workloads installed:
There are no installed workloads to display.

Host:
  Version:      8.0.2
  Architecture: x64
  Commit:       1381d5ebd2

.NET SDKs installed:
  8.0.101 [C:\Program Files\dotnet\sdk]
  8.0.200 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.27 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.27 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.27 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.16 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set
  ```

**Comment by jsquire** [comment]
Hi @rzettinger.  Thank you for reaching out and we regret that you're experiencing difficulties.  It is not possible to specify a normalizer when creating an index in v11.5.1 release is because doing so it is a preview feature that is not supported in the stable version of the Azure Search service.   A stable version of the client library is unable to depend on a preview version of the service.  Should the feature progress to stable and support is added to the Search service, the client library will also support it.  Likewise, should the feature continue to exist in the preview version of the Search service, the next preview release of the client library will support it.
### Additional resources

- [Azure Search REST API Spec v2023-11-01 (stable)](https://github.com/Azure/azure-rest-api-specs/tree/main/specification/search/data-plane/Azure.Search/stable/2023-11-01)
- [Azure Search REST API Spec v2024-03-01-Preview (preview)](https://github.com/Azure/azure-rest-api-specs/tree/main/specification/search/data-plane/Azure.Search/preview/2023-03-01-Preview)
- [Azure Search REST API CreateIndex example (stable)](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/search/data-plane/Azure.Search/stable/2023-11-01/examples/SearchServiceCreateIndex.json#L462)
- [Azure Search REST API CreateIndex example (preview)](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/search/data-plane/Azure.Search/preview/2024-03-01-Preview/examples/SearchServiceCreateIndex.json#L489)

**Comment by rzettinger** [comment]
Many thanks!
