### ISSUE TITLE
[BUG] Event hub consumer stops processing event hub messages for a specific period

### ISSUE THREAD

**Issue by YNauholnykh** [Azure/azure-sdk-for-net#42358]
### Library name and version

Azure.Messaging.EventHubs.Processor version 5.10.0

### Describe the bug

We have an event hub namespace on dev with a few event hubs. Messages are being populated to the event hub with ~1 message per minute per each event hub. For each event hub we have a service with an event consumer. The problem is that almost each night (usually happens around 23:00 - 02:00 UTC), consumers stop processing new messages from event hub for ~1-2 hours, then resume processing. 
We're using `PluggableCheckpointStoreEventProcessor` and store checkpoints to a blob storage. We've also added a custom health checker to monitor the events processing.

### Expected behavior

No interruptions in events processing.

### Actual behavior

Almost each night (usually happens around 23:00 - 02:00 UTC), consumers stop processing new messages from event hub for ~1-2 hours, then resume processing.

### Reproduction Steps

* Create an event hub namespace;
* Create and connect an event hub processor using `PluggableCheckpointStoreEventProcessor`;
* Monitor events processing per partition.

### Environment

AKS hosted service, .net6.

**Comment by jsquire** [comment]
Hi @YNauholnykh.  Thank you for reaching out and we regret that you're experiencing difficulties.   Please refer to [this section](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/eventhub/Azure.Messaging.EventHubs/TROUBLESHOOTING.md#a-partition-is-not-being-processed) of the Event Hubs Troubleshooting Guide for common causes and suggested mitigations.  

If those do not solve the issue, answer the questions from [this section](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/eventhub/Azure.Messaging.EventHubs/TROUBLESHOOTING.md#event-processor-issues) and capture a 5-10 minute slice of verbose SDK logs filtered to the events listed there for analysis.  Additional information for capturing logs can be found in [this sample](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/eventhub/Azure.Messaging.EventHubs/samples/Sample10_AzureEventSourceListener.md#apply-filtering-logic-to-logs).  It would also be quite helpful to share code snippets to illustrate how the processor is being created/configured and how it is being used within the application.

**Comment by YNauholnykh** [comment]
@jsquire I've checked the documentation you've provided. Here are my findings so far:

* `Exceptions being thrown in the event processing handler` - not our case, we catch exceptions on a top level.
* `"Soft Delete" or "Blob versioning" is enabled for a Blob Storage checkpoint store` - also not our case, they are disabled.
* `The "LoadBalancingUpdateInterval" and "PartitionOwnershipExpirationInterval" options are set too close together` - we use default values, so also not our case.
* `Too many partitions are owned` - need a bit more time to check this one. Will reach out to you in case I have any questions.

**Comment by YNauholnykh** [comment]
@jsquire I think I've found a potential reason. According to [Too many partitions are owned](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/eventhub/Azure.Messaging.EventHubs/TROUBLESHOOTING.md#too-many-partitions-are-owned), it's suggested to not have more than 3 partitions per cpu core. We have 32 partitions and only 2 cpu cores per pod on that environment, so that might be our problem.
I'll try to reduce the number of partitions and will monitor the situation. Will update you with the results.

**Comment by YNauholnykh** [comment]
@jsquire I have a question about [Too many partitions are owned](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/eventhub/Azure.Messaging.EventHubs/TROUBLESHOOTING.md#too-many-partitions-are-owned). When it says `Each partition owned by the processor is hosted by a dedicated background task.`, does it concern [PartitionProcessor](https://github.com/Azure/azure-sdk-for-net/blob/c4f3035e11f07b31946a618b816fc7a3937d9eeb/sdk/eventhub/Azure.Messaging.EventHubs/src/Primitives/EventProcessor.cs#L2291) in particular or [EventProcessor](https://github.com/Azure/azure-sdk-for-net/blob/c4f3035e11f07b31946a618b816fc7a3937d9eeb/sdk/eventhub/Azure.Messaging.EventHubs/src/Primitives/EventProcessor.cs#L48)?

**Comment by jsquire** [comment]
@YNauholnykh :  For each partition that an event processor owns, it uses a persistent, stateful, dedicated background thread to process it.  That processing is, essentially, a giant while loop that reads from the service and then dispatches events to your code for processing.  In addition, the processor has another dedicated background thread running at all times for load balancing and health monitoring.

For illustration, let's assume that you've got 32 partitions in your Event Hub and you're running 4 processors pointed at the same consumer group.   Each processor will own 8 partitions (32 / 4) and will start 9 persistent background threads to do the work.  Each of these is highly asynchronous, requiring the async continuations to be scheduled and run in a timely manner to make consistent forward progress.

If your host has 2 cores, then each of those 9 background threads is continually fighting for time to run.  The host/scheduler time slice things - particularly when there are awaits in the code - so that work is constantly context switching.  The .NET thread pool has no fairness when scheduling.  Since you've got more work constantly waiting than you have resources to process it, depending on how the work gets scheduled, you may see every partition stutter or you may see some partitions stall entirely because they're not being scheduled consistently and, therefore, can't make forward progress.

The challenge is that this kind of behavior is non-deterministic; things can be moving along for hours with everything making slow but reasonable forward progress and then you get unlucky with the scheduler and a partition just hangs.   It may get lucky and start again quickly or it may be unlucky for a while - there's no way to predict it accurately.   Load balancing is often a good "tell" in this scenario because the loop is sensitive to running on a consistent schedule and if it does not, there is obvious behavior that manifests.  Likewise, the processor controls all of the work done for load balancing, so it can raise warnings if the loop runs too slowly.    For partitions, we hand control over to your code and you're allowed to run for as long as you'd like - so the processor can't make any judgements about "what is too slow for one iteration of the read/process loop."

### Implementation details

Since you asked, the answer is - both.  `PartitionProcessor` is the encapsulation of that while loop to read and dispatch events.  When the processor takes ownership of a partition, it creates one of these and launches it in a Task explicitly marked as long running.  That hints to the thread pool that it should start a new thread for it, as the work isn't going to borrow a thread and return it to the pool in a reasonable amount of time.  We encapsulate partitions in this to allow them to more easily track partition-level state and because we're calling untrusted code (the app) so we cannot assume that error handling guidance is followed, so we want to ensure enough isolation that we can restart a faulted partition without causing issues for other parts of the processor.

The processor also kicks off load balancing in a long-running Task.  This is not a `PartitionProcessor` instance, because we can reason about how it behaves and know explicitly where failure points occur and handle them in a way that ensures we don't corrupt state and that it is safe to recover.

**Comment by YNauholnykh** [comment]
@jsquire thank you for such a comprehensive answer!
So basically if I increase a number of consumer instances to e.g. 5, I'll have 10 cores working with 32 partitions, which sounds like it should be enough (based on the 3 partitions per core recommendation). Not sure this will be a final solution, but at least I can confirm if this is the issue without recreating event hub instances. Will update you with the results.

**Comment by jsquire** [comment]
> @jsquire thank you for such a comprehensive answer! So basically if I increase a number of consumer instances to e.g. 5, I'll have 10 cores working with 32 partitions, which sounds like it should be enough (based on the 3 partitions per core recommendation). Not sure this will be a final solution, but at least I can confirm if this is the issue without recreating event hub instances. Will update you with the results.

That sounds like a good next step.   32 / 10 = 3.2, so you'll end up with 4 processors owning 3 partitions and 1 that owns 4.   Depending on your processing, event structure, host/network environment, you may be able to collapse that down to 4 hosts - which would give you a consistent 4 partitions owned per node.   That would be reasonable for many applications.   I'd advise testing thoroughly just to be sure.

I'll leave this in a "needs feedback" state for now.  That'll keep things open for a couple of weeks, in case you want to discuss further or share how things are going.

**Comment by YNauholnykh** [comment]
Hi @jsquire, an update from my end.

After I've increasd a number of replicas to 5, the issue was still reproducible. And even when increasing to 6. 
After that I've noticed that there's a setting which limits a number of concurrent event processings. I've reduced it to 6 and then it was not reproducible for almost a week.
After that I though maybe just limiting a number of concurrent processings will help. But turns out it doesn't

So basically we have the following options:
- Keep a number of pods 6 and a number of concurrent processings 6. But for dev environments it seems too much.
- Reduce a number of partitions and a number of concurrent processings to 6. Not that costy, but might have problems with the high load.
- Keep as it is with a workaround (restarting the event hub processing when the issue is detected).

We're discussing it within the team now. Will update you with the results.

**Comment by jsquire** [comment]
Hi @YNauholnykh:  Thanks for the update.  The recommended ratio is very much a generalization, as it depends on a number of factors, such as the host environment, workload of the app, event size, and rate of incoming events.   It's hard to say for sure whether it represents a problem, but having to scale above a 3:1 ratio is unusual.  

It may be worth capturing some Azure SDK logs and letting us take a look at what patterns we see there.  A 5-10-minute slice of verbose logs, filtered to the set described in [this section](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/eventhub/Azure.Messaging.EventHubs/TROUBLESHOOTING.md#event-processor-issues) of the Troubleshooting Guide should give us an idea of what the processor is seeing.   [This sample](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/eventhub/Azure.Messaging.EventHubs/samples/Sample10_AzureEventSourceListener.md#apply-filtering-logic-to-logs) demonstrates how to capture and filter.

**Comment by YNauholnykh** [comment]
Hi @jsquire, could you please share an email where I can send you the logs?

**Comment by YNauholnykh** [comment]
I've sent the logs to your mail, hope I used the correct one. Please let me know whether you received it or not.

**Comment by jsquire** [comment]
Confirming receipt.   I'll take a look at these today and let you know what I find.

**Comment by jsquire** [comment]
Discussion has moved to another format for log review, as there may be non-public information discussed.   Marking this as waiting for feedback to allow the issue to remain open in case there are any outcomes that would be helpful to share for general awareness.
