### ISSUE TITLE
[QUERY] How to mock PipelineCreateRunResult?

### ISSUE THREAD

**Issue by Nexus20** [Azure/azure-sdk-for-net#42459]
### Library name and version

Azure.ResourceManager.DataFactory 1.0.0-beta.6

### Query/Question

Hello everyone.
I have a question about mocking PipelineCreateRunResult.

I have such code
![изображение](https://github.com/Azure/azure-sdk-for-net/assets/40770350/1d5fc0ed-b776-4d62-a5d4-02afe2997ddf)
And I want to write unit tests for this code
So I have a question how am I supposed to mock PipelineCreateRunResult

![изображение](https://github.com/Azure/azure-sdk-for-net/assets/40770350/08f0d673-a7d8-4bcf-b915-7a9021be51bb)
![изображение](https://github.com/Azure/azure-sdk-for-net/assets/40770350/6c551a0b-fafe-4e10-a54d-6f77b3458466)
And the problem occurs when I try to mock PipelineCreateRunResult. It throws an exception because PipelineCreateRunResult is not supported for mocking because it does not have protected constructor without parameters.
![изображение](https://github.com/Azure/azure-sdk-for-net/assets/40770350/cf03cfd4-a1a3-420d-a15d-77a125be1807)
![изображение](https://github.com/Azure/azure-sdk-for-net/assets/40770350/1b787c79-9696-4f7e-9599-eaae8fe01f09)

So please help.

### Environment

Windows 11
.NET SDK v.6
IDE: JetBrains Rider/ Visual Studio 2022 Enterprice

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by ArthurMa1978** [comment]
Hey @Nexus20 , this has been fixed in the [latest version](https://www.nuget.org/packages/Azure.ResourceManager.DataFactory/1.0.0) which the `ArmDataFactoryModelFactory` exposes [public method](https://github.com/Azure/azure-sdk-for-net/blob/Azure.ResourceManager.DataFactory_1.0.0/sdk/datafactory/Azure.ResourceManager.DataFactory/src/Generated/ArmDataFactoryModelFactory.cs#L447) to create a model mocking, more information can be found [here](https://azure.github.io/azure-sdk/dotnet_introduction.html#dotnet-mocking-factory-builder).
