### ISSUE TITLE
Wait Time between receiving batch messages from service bus topic

### ISSUE THREAD

**Issue by gunjan0921** [Azure/azure-sdk-for-net#42863]
### Library name and version

Microsoft.Azure.WebJos.Extensions.ServiceBus

### Query/Question

I have configured an azure function app with ServiceBusTrigger. This Trigger is meant to receive messages in batches. I configured batch size, MaxBatchWaitTime and everything works fine so far. But now I want my trigger to wait for certain amount of time between different batch requests. Is there a configuration like MinBatchWaitTime that I can use? I see that with MaxBatchWaitTime set, the next request wait for sometime to fill the batch before picking up the messages. Is there some configuration available that can be used to make next requests wait like minBatchWaitTime?

Please see attached screenshot here:
<img width="872" alt="ServiceBusTriggerBatchMessageReciever" src="https://github.com/Azure/azure-sdk-for-net/assets/50559986/42265413-484c-4f95-a70f-be139500e37d">

In the above screenshot, since the batchsize is 3 and total messages in service bus is 10, the last request waits until "MaxBatchWaitTime" (10 secs in my case)  before receiving the batch messages from service bus. I want second request also to be tiggered at 10:55:46 instead of being triggered immediately and third request to be triggered at 10:56:06. How can this be achieved? Could you please help me here? 

I tried several configuration settings like FixedDelayRetry attribute, setting retryTimeout in host.json. But most of the settings are only for retry scenarios. Also there is something like MaxPollingInterval for queues but not for topics. Even the maxConcurrentCalls works only for receivers receiving single messages not in batch.

### Environment

My application is azure function app hosted in azure. OS: Windows. .Net 6 (in-process Model). IDE: Visual Studio 2022

**Comment by gunjan0921** [comment]
I got a workaround for this using Prefetch Count. If I set PrefetchCount lower than BatchSize then, it would always wait for batch to be filled in before fetching messages. But here I am facing an issue when keeping PrefetchCount to 3 and BathSize to 4 or 5, it fetches 3 messages first time but then onwards it only fetches 2 messages even though my topic subscription has 16-17 messages. Could you please explain why is that the case? Although using any other numbers like setting Prefetch Count to 4 and BatchSize to 5 or 6 works perfectly fine!

**Comment by jsquire** [comment]
> I got a workaround for this using Prefetch Count. If I set PrefetchCount lower than BatchSize then, it would always wait for batch to be filled in before fetching messages. 

This is incorrect.  

> But here I am facing an issue when keeping PrefetchCount to 3 and BathSize to 4 or 5, it fetches 3 messages first time but then onwards it only fetches 2 messages even though my topic subscription has 16-17 messages. Could you please explain why is that the case? Although using any other numbers like setting Prefetch Count to 4 and BatchSize to 5 or 6 works perfectly fine!

If prefetch is enabled and a read takes place, it will read only what is currently in prefetch and then return.  There is no concept of waiting to build a batch that meets the `maximumBatchSize` - that parameter controls the upper limit only.   If you need to specify a minmum number of messages in a batch, you'll want to use "minBatchSize", which you can read about [here](https://learn.microsoft.com/azure/azure-functions/functions-bindings-service-bus?tabs=isolated-process%2Cextensionv5%2Cextensionv3&pivots=programming-language-csharp#hostjson-settings).

**Comment by gunjan0921** [comment]
> This is incorrect.
> 
> >

Hey, I tried this and seems to be working. So if I configure PrefetchCount 7lower than minMessageBatchSize with maxBatchWaitTime, then every next read operation always wait for maxBatchWaitTime to fill the batch with minMessageBatchSize no of messages. This is because PrefetchCount is set to lower. Please see the configuration here:

`"serviceBus": {
  "prefetchCount": 4,
  "minMessageBatchSize": 5,
  "maxBatchWaitTime": "00:00:10"`

What I want to know is doesnt PrefetchCount (when Prefetch is enabled) not always fetch same no of messages in buffer? ie. If my service bus has 20 msgs, Above is my configuration, then how many runs will it take to process all messages and what is the no of messages that will be processed in each run?

**Comment by gunjan0921** [comment]
Also I have one question:

If my azure function app with service bus trigger is running and scales to more than 1 instance dynamically based on load, is there way to share PrefetchCount amongst all the running instances? i.e. If PrefetchCount is set to 4, then at any given time, I dont want all the instances combined to process more than 4 messages. Is that possible?

**Comment by jsquire** [comment]
> Hey, I tried this and seems to be working. So if I configure PrefetchCount lower than minMessageBatchSize with maxBatchWaitTime, then every next read operation always wait for maxBatchWaitTime to fill the batch with minMessageBatchSize no of messages. This is because PrefetchCount is set to lower. Please see the configuration here:
> 
> `"serviceBus": { "prefetchCount": 4, "minMessageBatchSize": 5, "maxBatchWaitTime": "00:00:10" }`

This is still incorrect, unless there ae no messages available in the entity to read.  When a minimum size is specified, then the listener will wait to dispatch messages until EITHER the requested minimum size is satisfied, OR the wait time expired without enough events to meet the requested minimum.   Whichever condition is satisfied first will trigger the dispatch.

> What I want to know is doesnt PrefetchCount (when Prefetch is enabled) not always fetch same no of messages in buffer? ie. If my service bus has 20 msgs, Above is my configuration, then how many runs will it take to process all messages and what is the no of messages that will be processed in each run?

There are no guarantees when streaming messages from the service, whether via prefetch or direct read.  The client places some number of credits on an AMQP link which signals to the service that it may stream up to that many messages to the client.   How the service chooses to put messages on the link influences how they stream down.   The service is not obligated to put enough messages on the link at once to consume the available credits and may choose to control the flow for various reasons.

Prefetch is simply an implementation of this, where the local transport keeps a memory cache so that when the client attempts to read, it is not network bound when doing so.  The transport manages the cache and will choose when to refill it based on its own internal heuristics, which may not align "always refill exactly what was read."    For example, the transport may choose to refill prefetch when it reaches 1/2 empty rather than doing so after each read.

When messages are in prefetch, a read attempt will consume between 1 and `maxBatchSize` messages from the cache and that read attempt will not wait on the network - whatever happens to be in the cache when the read is made is returned to the client.   In the scenario that you're describing here, if we assume 4 messages are available in prefetch, then the client will need to make two read attempts to build the minBatchSize - the first gets back 4 messages from prefetch, the next read will either grab 1 additional message from prefetch or will be network-bound and must wait for a message to stream in from the service.   

**The key take-away is:  the behavior and how reads are satisfied very much depends on the state of prefetch at the time a read is attempted, which depends how quickly messages can refill, which itself depends on a number of factors.**

> If my service bus has 20 msgs, Above is my configuration, then how many runs will it take to process all messages and what is the no of messages that will be processed in each run?

There's no way to deterministically answer this.  As described above, it will vary depending on a number of factors including the speed of the network, size of the messages, configuration of the host machine, and state of shared resources for non-dedicated SKUs.

> If my azure function app with service bus trigger is running and scales to more than 1 instance dynamically based on load, is there way to share PrefetchCount amongst all the running instances? i.e. If PrefetchCount is set to 4, then at any given time, I dont want all the instances combined to process more than 4 messages. Is that possible?

No; the prefetch queue is a local cache held in memory of a single machine.
