### ISSUE TITLE
[FEATURE REQ] Return object for SendMessageAsync with success or failure state

### ISSUE THREAD

**Issue by GeertVerthe** [Azure/azure-sdk-for-net#42949]
### Library name

Azure.Messaging.ServiceBus

### Please describe the feature.

We had some issues on our Cloud environment where messages were not sent to the service bus. This was in fact entirely our fault, we bursted the messages towards the service bus without closing our Sender and Client connection (not using DisposeAsync()). 

At a certain point, no messages were sent as described above, but also no feedback or error message was given from the call to SendMessageAsync(). 

We would expect if connection exhausting (which was the issue in our case) or general failure occurs in sending the message, we would get some feedback. Now we could only deduct it from watching the metrics of our service bus in Azure portal. 

It would be nice to have some sort of object containing a success state when send a message.

**Comment by jsquire** [comment]
Hi @GeertVerthe.  Thank you for reaching out and we regret that you're experiencing difficulties.  The contract for `SendMessageAsync` is that the sender invokes the service operation and waits for acknowledgement from the service that it has accepted the message and, therefore, responsibility for it.   If the call completes and you have not seen an error, then the operation was successful, and the service has acknowledged the message.   For any other scenario, whether a failure on the client related to the network or a failure/rejection from the service, the sender will throw, and your application will observe an exception.

The scenario that you describe above sounds like one where the sender had to wait for resources to be available for its work to be scheduled and was otherwise in an awaiting state.  Once the host had the resources to allow the sender to complete the end-to-end service operation, your application would have observed either a timeout or another network-related failure if the message was not able to be sent.
