### ISSUE TITLE
[BUG] Azure SDKs and Virtual Machine Scale Set VMs - Get does not return network interface for VMSS VMs (Flexible orchestration mode)

### ISSUE THREAD

**Issue by vhphuocvo** [Azure/azure-sdk-for-net#43000]
### Library name and version

Azure.ResourceManager.Compute 1.4.0

### Describe the bug

Hi,
I have a VMSS with network configuration as:
- Network interface
- Application Security Group
- Subnet
- Public IP Address
- 
I have to load network interfaces of VMSS VMs with Flexible mode but Azure SDK to get VMSS VM does not return as expected.
- NetworkProfile: null
- NetworkInterfaceConfigurations: Empty
Checked out code VirtualMachineScaleSetVmData.cs look like NetworkProfile is null cause the issues, since I already config network,  it can't be null here.
```
if (NetworkProfileConfiguration is null)
    NetworkProfileConfiguration = new VirtualMachineScaleSetVmNetworkProfileConfiguration();
return NetworkProfileConfiguration.NetworkInterfaceConfigurations;
```

Did tried using "Try it" here but the same issues: https://learn.microsoft.com/en-us/rest/api/compute/virtual-machine-scale-set-vms/get?view=rest-compute-2023-10-02&tabs=dotnet

### Expected behavior

I need to get VMSS VMs network interface

### Actual behavior

Null network profile and empty network interface returned

### Reproduction Steps

Create VMSS with network interface, subnet, NSG, ASG configuration and get VMSS VMs data

**Comment by mcgallan** [comment]
Hi @vhphuocvo, thank you for reaching out to us about the Azure SDK for .NET. Unfortunately, this issue is related to the service side and not the SDK side, so we are not able to help you with it. Therefore, we are closing this issue for now. If you need more assistance, please [open an Azure support request](https://docs.microsoft.com/azure/azure-portal/supportability/how-to-create-azure-support-request). We apologize for any inconvenience this may cause you.
We value your feedback and we want to make sure that your problem is solved. If you think that we have misunderstood your issue or closed it incorrectly, please feel free to comment on this thread and reopen the issue. We will be happy to assist you further. Thank you for your understanding and cooperation.
