### ISSUE TITLE
System.Text.Json.JsonSerizlizer exception - Could not load file or assembly 'System.Text.Json, Version=8.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'

### ISSUE THREAD

**Issue by avnet78** [Azure/azure-sdk-for-net#43629]
### Library name and version

Azure.ResourceManager.DataFactory 1.0.0

### Describe the bug

Getting error message - "Could not load file or assembly 'System.Text.Json, Version=8.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'."

Followed the instructions in the link below to Create a pipeline run:

https://learn.microsoft.com/en-us/azure/data-factory/quickstart-create-data-factory-dot-net#create-a-pipeline-run

This line of code is throwing exception: BinaryData.FromObjectAsJson(inputBlobContainer)

### Expected behavior

The string must be serialized

### Actual behavior

Getting error message - "Could not load file or assembly 'System.Text.Json, Version=8.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'."

### Reproduction Steps

Follow the instructions in the link below to Create a pipeline run:

https://learn.microsoft.com/en-us/azure/data-factory/quickstart-create-data-factory-dot-net#create-a-pipeline-run

### Environment

Target Framework - net6.0
AzureFunctionsVersion - v4
Microsoft Visual Studio Professional 2022 (64-bit) - Version 17.9.6

**Comment by jsquire** [comment]
Hi @avnet78.   Thanks for reaching out and we regret that you're experiencing difficulties.   We're unable to reproduce the problem locally.   This class of issue is difficult to troubleshoot, as they are out of control of the libraries themselves and often are caused by unexpected dependencies - such as implicit ones.  

This problem generally occurs when the runtime is unable to load the needed set of dependencies; normally, this is due to a version mismatch due to an application reference that pins an older version either directly or as a transitive dependency.  Most often, this can be mitigated by adding an explicit reference to the application that hoists the version.  In this case, I'd suggest trying a direct reference to the latest `System.Text.Json` in the application and seeing if that helps.  

If that does not resolve your issue, we'll need to ask that you share a small, self-contained project that reproduces the error.  That will allow us to take a deeper look and offer insight.
