### ISSUE TITLE
DNS forwarding for virtual network gateway

### ISSUE THREAD

**Issue by dklwong** [Azure/azure-sdk-for-net#43622]
### Type of issue

Typo

### Description

[Enter feedback here]

### Page URL

https://learn.microsoft.com/en-us/dotnet/API/microsoft.azure.management.network.models.virtualnetworkgateway.enablednsforwarding?view=azure-dotnet

### Content source URL

https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.Management.Network.Models/VirtualNetworkGateway.xml

### Document Version Independent Id

0f16c61b-2428-6bc9-0f37-4aca311d72b3

### Article author

@azure-sdk

### Metadata

* ID: ad21f69f-ebf4-a935-dceb-1eddac64b0d4 
* Service: **virtual-network**

**Comment by jsquire** [comment]
Hi @dklwong.  Thanks for reaching out with your feedback.   The `Microsoft.Azure.Management.Network` package reached end-of-life in September 2023 and is no longer published nor supported by Microsoft.   Since these docs are automatically generated from the library source a package release is required to update them.   Unfortunately, this means that we're unable to correct the typo.
