### ISSUE TITLE
[QUERY] I need to get cost per subscription, per resourcegroup, per resource for the last whole month and last 365 days to day.

### ISSUE THREAD

**Issue by MCDPRO** [Azure/azure-sdk-for-net#43673]
### Library name and version

Azure resource Manager SDK

### Query/Question

As the title suggest. I need to get cost per subscription, per resourcegroup, per resource for the last whole month and last 365 days to day.

i am really trying with your SDK but the docs are not very clear to me, or because there is too much with many terms which look alike i cannot really find what i need. 

i have an admin role and i need to make a small app which creates Excel files (this is not my question) which contain the following:
for each subscription of the company a list of all resources under that subscription with the cost within a certain timeframe:
i created this small code BUT it returns just two columns, a valuta code {EUR} and a datestring like 01052023, can somebody advice me what to add or improve or where to search:

`
private static async Task<decimal> GetCostForTimeFrame(ArmClient client, ResourceIdentifier id, TimeframeType timeFrame, string name)
{
    try 
    {
        var queryDataSet = new QueryDataset()
        {
            Granularity = GranularityType.Daily,
        };
        var query = new QueryDefinition(ExportType.ActualCost, timeFrame, queryDataSet);
        if (timeFrame == TimeframeType.Custom)
        {
            var today = DateTime.UtcNow;
            var startDate = new DateTime(today.Year, today.Month, 1).AddYears(-1);
            var endDate = new DateTime(today.Year, today.Month, 1).AddDays(-1);
            query.TimePeriod = new QueryTimePeriod(startDate, endDate);
        }

        var result = await client.UsageQueryAsync(id, query);

        var x = result.Value;
        var y = result.GetRawResponse();

        return 0;
    } catch (Exception ex) 
    {
        Console.WriteLine(ex.Message);
        return 0;
    }
}`

### Environment

,NET core, with Azure SDK

**Comment by ArthurMa1978** [comment]
@MCDPRO, our team is responsible for creating the SDK based on the provided Swagger spec. As such, our domain knowledge regarding the specific use cases for each API is limited.
Add @HarveyLink to assist with a sample; however, we cannot assure its accuracy.

**Comment by mcgallan** [comment]
Hi @MCDPRO , thank you for your feedback. Regarding the issue you mentioned, I will provide a runnable example. In Azure SDK, `client.UsageQueryAsync()` by default only has Number type UsageDate and String type Currency in columns. Therefore, we need to add aggregation in the dataset parameter so that columns can have the cost we need. Also, if you want to get the cost of the last complete month, `TimeframeType.TheLastBillingMonth` is a good choice. If you need to get it by year, the custom part in the original code is feasible. Here is a runnable example:
```
private static async Task GetCostForTimeFrame(ArmClient client, ResourceIdentifier id, TimeframeType timeFrame)
{
    try
    {
        var queryDataSet = new QueryDataset()
        {
            Granularity = GranularityType.Daily,
            Aggregation =
            {
                ["Cost"] = new QueryAggregation(function: FunctionType.Sum, name: "PreTaxCost")
                {
                }
            },
        };
        var query = new QueryDefinition(ExportType.Usage, timeFrame, queryDataSet);
        if (timeFrame == TimeframeType.Custom)
        {
            var today = DateTime.UtcNow;
            var startDate = new DateTime(today.Year, today.Month, 1).AddYears(-1);
            var endDate = new DateTime(today.Year, today.Month, 1).AddDays(-1);
            query.TimePeriod = new QueryTimePeriod(startDate, endDate);
        }

        var result = await client.UsageQueryAsync(id, query);

        var x = result.Value;
        var y = result.GetRawResponse();
        foreach (var row in result.Value.Rows)
        {

            Console.WriteLine($"Date: {row[1]}, Cost: {row[0].ToString()}");
        }

    }
    catch (Exception ex)
    {
        Console.WriteLine(ex.Message);
    }
}
```
It's worth mentioning that row[2] represents the currency unit of the cost. If needed, you can add it yourself. Also, please make sure to write the subscription, resourcegroup, and resource correctly. If you need to query the cost data for an entire year, please be aware of the API endpoint's request limit to avoid errors like "too many requests". You can refer to [this document](https://learn.microsoft.com/zh-cn/rest/api/cost-management/query/usage?view=rest-cost-management-2023-11-01&tabs=HTTP#subscriptionquery-legacy) for further work, it will help you to use the SDK better. If you have any further questions, please reply to me under this issue. I will reply as soon as I see it to help you solve the problem better.
