### ISSUE TITLE
[QUERY] Does Azure.ResourceManager.CosmosDB support Cosmos DB Emulator?

### ISSUE THREAD

**Issue by blankor1** [Azure/azure-sdk-for-net#43754]
### Library name and version

Azure.ResourceManager.CosmosDB

### Query/Question

Does Azure.ResourceManager.CosmosDB support Cosmos DB Emulator?

For example, do the control plane operation like CreateDatabase, CreateCollection using this client's API.

### Environment

Windows
Dotnet 6

**Comment by jsquire** [comment]
HI @blankor1.  Thank you for reaching out and for your inquiry.  The Azure SDK management packages are intended to work with the official Azure ARM endpoints.  Unfortunately, we cannot answer what the emulator may or may not support.   In order to get an authoritative answer to your question, you'd need to ask the owners of the Cosmos emulator if they officially support the ARM API.   

As the emulator is not open source, there is no GitHub repository for me to transfer your inquiry to.  Your best path forward for would be to [open an Azure support request](https://docs.microsoft.com/azure/azure-portal/supportability/how-to-create-azure-support-request) or inquire on the [Microsoft Q&A site](https://learn.microsoft.com/answers/questions/).   

I'm going to close this out; if I've misunderstood what you're describing, please let us know in a comment and we'd be happy to assist as we're able.
