### ISSUE TITLE
Move codegen to consume the new System.ClientModel release version 1.1.0-beta.3

### ISSUE THREAD

**Issue by pallavit** [Azure/azure-sdk-for-net#43824]
Codegen was recently moved to the System.ClientModel v1.1.0-beta.3 but has a bug where the .csproj is generated still referencing the older version.

**Comment by jsquire** [comment]
Root cause is due to a base AutoRest assumption that references do not need to be maintained after the project is generated, due to the use of central versioning in the Azure SDK repository.   For unbranded scenarios, this is a poor experience.   A feature request will be opened in the AutoRest repository to improve this scenario.
