### ISSUE TITLE
Add Uri parameter on AddServiceBusClient

### ISSUE THREAD

**Issue by kingsznhone** [Azure/azure-sdk-for-net#43931]
### Library name

Azure.Messaging.ServiceBus

### Please describe the feature.

When I'm setting up my asp .net core program.

I have a good feeling on ```services.AddAzureClients(x =>x.AddBlobServiceClient(new Uri(configuration.GetValue<string>("Endpoint")))```
But when I'm trying to add service bus  like blob service do. 
I only have one choice of using connect string ``` x.AddServiceBusClient("ConnectString");```

**Comment by jsquire** [comment]
Hi @kingsznhone.  Thanks for reaching out and we regret that you're experiencing difficulties.   Because Service Bus uses a string-based fully qualified namespace rather than a URI to identify namespace locations, both the connection name and FQNS are string values.  As a result, it is not possible to just overload `AddServiceBusClient` and a new name is needed for the FQNS form.

The method that you're looking for is  [AddServiceBusClientWithNamespace](https://learn.microsoft.com/dotnet/api/microsoft.extensions.azure.servicebusclientbuilderextensions.addservicebusclientwithnamespace?view=azure-dotnet), which allows you to pass the fully qualified namespace name of the Service Bus resource and authenticate via credential.   

```csharp
services.AddAzureClients(clientBuilder =>
{
    clientBuilder.AddServiceBusClientWithNamespace("<your_namespace>.servicebus.windows.net");
}
```

More context and discussion can be found in [Dependency injection with the Azure SDK for .NET](https://learn.microsoft.com/en-us/dotnet/azure/sdk/dependency-injection?tabs=host-app-builder).

**Comment by kingsznhone** [comment]
> Hi @kingsznhone. Thanks for reaching out and we regret that you're experiencing difficulties. Because Service Bus uses a string-based fully qualified namespace rather than a URI to identify namespace locations, both the connection name and FQNS are string values. As a result, it is not possible to just overload `AddServiceBusClient` and a new name is needed for the FQNS form.
> 
> The method that you're looking for is [AddServiceBusClientWithNamespace](https://learn.microsoft.com/dotnet/api/microsoft.extensions.azure.servicebusclientbuilderextensions.addservicebusclientwithnamespace?view=azure-dotnet), which allows you to pass the fully qualified namespace name of the Service Bus resource and authenticate via credential.
> 
> ```cs
> services.AddAzureClients(clientBuilder =>
> {
>     clientBuilder.AddServiceBusClientWithNamespace("<your_namespace>.servicebus.windows.net");
> }
> ```
> 
> More context and discussion can be found in [Dependency injection with the Azure SDK for .NET](https://learn.microsoft.com/en-us/dotnet/azure/sdk/dependency-injection?tabs=host-app-builder).

Thanks for your explaination. I'll have a try.
