### ISSUE TITLE
[BUG]Isolated Service Bus Trigger with Object parameter type body is empty 

### ISSUE THREAD

**Issue by HaochenQ** [Azure/azure-sdk-for-net#43950]
### Library name and version

Microsoft.Azure.Functions.Worker.Extensions.ServiceBus 5.18.0

### Describe the bug

I migrated my Azure Function from .Net 6 In-Process to .Net 8 Isolated model. 

However, some of my service bus trigger functions with
 `[ServiceBusTrigger("%MyServiceBusQueue%", Connection = "ServiceBusConnection")] MyCutomTypeMessage myMyCutomTypeMessage ` 
have myMyCutomTypeMessage is empty {} when triggerred.

Now I can only use ServiceBusReceivedMessage to get body then deserialise to my MyCutomTypeMessage type.
`[ServiceBusTrigger("%ServiceBusWasteTrackCollectionExceptionsQueue%", Connection = "ServiceBusConnection")] ServiceBusReceivedMessage serviceBusReceivedMessage, FunctionContext context`

`var serviceBusMessageString = serviceBusReceivedMessage.Body.ToString();
var collectionException = JsonConvert.DeserializeObject<MyCutomTypeMessage >(serviceBusMessageString);`

Not sure if it has something to do with DI:

`services.AddMvcCore().AddNewtonsoftJson();`

Interestingly, some other servicebus trigger function within the same function app are still working fine.

### Expected behavior

The plan Object type should work as per doc: 

> When a message contains JSON, Functions tries to deserialize the JSON data into known plain-old CLR object type.

### Actual behavior

The message triggered function is empty

### Reproduction Steps

1. Migrate a service bus trigger funciton with a Object parameter type from .Net6 in-process to .Net 8 isolated
2. Add `services.AddMvcCore().AddNewtonsoftJson(); `in DI
3. Run the function and print the service bus message, it is empty

### Environment

VS 2022
.NET 8

**Comment by jsquire** [comment]
Hi @HaochenQ.   Thank you for reaching out and we regret that you're experiencing difficulties.   Using a POCO is a supported scenario for the isolated worker and one that we validate as part of our test runs.   We're not seeing test failures, we're not seeing other developers have these failures, and we're unable to reproduce the behavior that you're seeing.

Generally, these failures often come down to a type mismatch between the message body and the type expected by the trigger.   Given that you're able to manually deserialize, a full type mismatch seems unlikely.   It may come down to a mismatch between serialization formats for your specific type, due to your `AddNewtonsoftJson` call.   I'd suggest testing without that line and seeing if you're able to reproduce.

If that doesn't resolve your issue, we'll need to ask that you provide a small, self-contained app that reproduces the behavior for us, as we're unable to do so.
