### ISSUE TITLE
[QUERY] Azure Service Bus "Batch Receive Timeout" 

### ISSUE THREAD

**Issue by dylan-asos** [Azure/azure-sdk-for-net#44004]
### Library name and version

Azure.Messaging.ServiceBus

### Query/Question

In the AmqpReceiver, when receiving messages in batch it uses a hard coded value of 20ms as a parameter to the "batch receive timeout" 

https://github.com/Azure/azure-sdk-for-net/blob/7c5d4781ca84a82021fb75d5d0f2cd54a2fe17c0/sdk/servicebus/Azure.Messaging.ServiceBus/src/Amqp/AmqpReceiver.cs#L364

e.g. the behaviour here is if I have set a batch size of 500 but only 100 have been retrieved by the timeout value, then it will return the smaller batch size to the client to allow them to start processing those messages.

Is there a reason why this is hard-coded and not configurable? In some scenarios, I'd happily wait for longer if it meant I could receive a larger batch in one go.

**Comment by jsquire** [comment]
Hi @dylan-asos.  This is an intentional design decision that was made, and not something that we intend to make configurable at present.  The rationale behind this decision is to:

- Ensure that messages received by the application have consistent lock durations of the expected interval.   We want to avoid locked messages being held in the client and not visible to the application while their timer is ticking down while waiting for other messages.

- Provide a single means for client-side caching/queueing of messages to avoid the confusion of having multiple ways to fetch/cache messages on the client-side.  In this case, prefetch is that mechanism with the difference being that it is an eager fetch rather than an on-demand fetch.   

- Prioritize throughput by returning messages to the application as quickly as possible so that processing can be performed.  User studies have shown us that prefetching was the more effective approach for maximizing throughput in the majority of application scenarios where message batching was advantageous.

For scenarios in which reaching your `maxBatchSize` is important, the general guidance is to consider tuning the prefetch count to eagerly pull messages and have them available.

**Comment by dylan-asos** [comment]
Many thanks @jsquire - really helps understand the rationale + will make a few tweaks accordingly.
