### ISSUE TITLE
feat(lro): honor `retry-after` in the initial response

### ISSUE THREAD

**Issue by archerzz** [Azure/azure-sdk-for-net#44147]
## Description

According to the specs([here](https://github.com/Azure/azure-resource-manager-rpc/blob/master/v1.0/async-api-reference.md) and [here](https://github.com/microsoft/api-guidelines/blob/vNext/azure/ConsiderationsForServiceDesign.md#long-running-operations)), in LRO, the initial response (e.g. the response of the initial request) can carry `retry-after` header, which suggest the clients should wait the given time before sending the 1st polling request.
> Return HTTP code 202 (Accepted) with a Location header and, optionally, a Retry-After header.

In track2, we haven't implemented that. The benefits are:
- optimizing performance since we could reduce the number of polling requests
- some services may not correctly implement the LRO logic, sending polling request too soon could cause error. Note that `retry-after` is a gentleman protocol, and the clients can choose not to follow it.

**Comment by annelo-msft** [comment]
@archerzz, could you share which clients depend on this feature, so we can prioritize it correctly?

**Comment by heng-liu** [comment]
App Configuration.
When migrating from Track1 SDK to Track2 SDK, we started to encounter this issue.
The LRO is aborted when the first polling request failed with 404.

**Comment by archerzz** [comment]
> @archerzz, could you share which clients depend on this feature, so we can prioritize it correctly?

@annelo-msft I've included you in the original email thread. It's `AppConfiguration`.

**Comment by annelo-msft** [comment]
Would it be possible to provide a repro case for the specific operation that is not respecting the header interval?  Azure.Core types [should be respecting the RetryAfter header](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/core/Azure.Core/src/DelayStrategy.cs#L83) on a response if it’s available, as part of the default DelayStrategy implementation.  Because of this, I'm interested to understand the specific case where this is not happening.  Thanks!
