### ISSUE TITLE
[BUG] Name has space will throw DoubleEncodedException.

### ISSUE THREAD

**Issue by melina5656** [Azure/azure-sdk-for-net#44309]
### Library name and version

Azure Cosmos DB

### Describe the bug

When both the database name and container name contain spaces, a Double Encoded Exception is thrown.
Set database name to "database 1" and container name to "container 1".
The container name will be encoded as container%201, and the database will be re encoded as database%25201.

### Expected behavior

The name should not allow the use of spaces, or the database name should not be encoded.

### Actual behavior

Double Encoded Exception

### Reproduction Steps

1.Create a cosmos DB account resource.
2.Create a cosmos DB SQL database resource, database name contains space: e.g. "database 1".
3.Create a cosmos DB SQL Container resource, container name contains space: e.g. "container 1".
4.Get a cosmos DB SQL Container.

**Comment by jsquire** [comment]
@melina5656:  Please do not add tags when opening issues unless they are for your team.   This interferes with triage and the ability to route this appropriately.    In this case, it is unclear what package you're discussing, which matters because the CosmosDB management package is maintained in this repository but the client library is not.

Please clarify the full package name and version.
