### ISSUE TITLE
[FEATURE REQ] Enhance MockableTrafficManagerArmClient Usability for Unit Testing by Adding Setters to TrafficManagerRegion Properties

### ISSUE THREAD

**Issue by chensy96** [Azure/azure-sdk-for-net#44435]
### Library name

Azure.ResourceManager.DataFactory.Mocking

### Please describe the feature.

When trying to write the unit test using 'MockableTrafficManagerArmClient.GetTrafficManagerGeographicHierarchyResource' method, and to get 'TrafficManagerGeographicHierarchyData' as the result (which is required in the method we need to test as a parameter) we ran into a dead end:

- When mocking, the data is empty, but we need such a hierarchy object
- We also can not create an instance of this object and give it customized values, because the missing setter in the list of 'TrafficManagerRegion'

Would there be a better way of approaching this issue? or could you add the setter?

**Comment by ArthurMa1978** [comment]
Hey @chensy96 , thank you for reaching out to us, I guess your question is about Azure.ResourceMananger.TrafficManager.
For you question:
1. You need to fill in all data if you want to mock a class.
2. You meant this [TrafficManagerGeoGraphicHierarchyData.TrafficManagerRegion](https://learn.microsoft.com/en-us/dotnet/api/azure.resourcemanager.trafficmanager.trafficmanagergeographichierarchydata.geographichierarchy?view=azure-dotnet) ? It's not a collection. If a property is a collection, then there is no setter because you can use collection's add/update/delete methods to update the property, instead of assign a new collection.
