### ISSUE TITLE
[QUERY] ArmDeploymentResource.ValidateAsync doesn't return ArmDeploymentValidateResult but throws exception when "Preflight validation failed"

### ISSUE THREAD

**Issue by heng-liu** [Azure/azure-sdk-for-net#44456]
### Library name and version

Azure.ResourceManager.Resources 1.7.0

### Query/Question

ArmDeploymentResource.ValidateAsync throws exception when "Preflight validation failed".
As such, it doesn't return ArmDeploymentValidateResult with error details.
I have to parse the exception.Message to get the error details.
Is this by design? Or did I miss anything? Thanks!

I saw [ArmDeploymentValidateResult](https://learn.microsoft.com/en-us/dotnet/api/azure.resourcemanager.resources.models.armdeploymentvalidateresult?view=azure-dotnet) has the error property and expect ArmDeploymentResource.ValidateAsync will not throw exception when validation failed.

The [ValidateAtScopeAsync ](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/resources/Azure.ResourceManager.Resources/src/Generated/ArmDeploymentResource.cs#L462)returns 400 with no exception but ValidateAsync still failed.

**Comment by heng-liu** [comment]
Hi, @HarveyLink , fyi, the track1 SDK doesn't throw exceptions when "Preflight validation failed".

**Comment by welovej** [comment]
hi @heng-liu 

When working with Long-Running Operations (LROs) in the Azure SDK, the SDK typically throws an exception if a 400 response is returned by the service. This is intended to simplify error handling by treating non-successful HTTP responses as exceptions. However, this can be problematic if you need to handle 400 responses as non-exceptional cases, such as when you want to parse and process the validation result directly.
 
**ARM Specification and Expected Behavior**
According to Azure Resource Manager (ARM) specifications, LROs should not return a 400 status code as part of their standard operation flow. The expectation is that successful operations will return 200-series status codes, and failure scenarios will return appropriate status codes that are handled as exceptions. Due to this specification, the Azure SDK is designed to treat 400 responses as errors and throws exceptions accordingly.
 
**Custom Handling Approach**
To manage this, you can wrap the LRO call in a try-catch block and handle exceptions specifically for the 400 status code. This allows you to extract the necessary information from the response and handle it appropriately without treating it as an error.

**Seeking Further Assistance**
If the current SDK behavior does not fully meet your needs or requires more customization than you can implement, it is advisable to contact the Azure service team for further assistance. They can provide specific guidance or consider feature requests for future SDK updates. By reaching out to the service team, you can get specialized support and potentially influence future improvements in the SDK to better handle your scenarios.
