### ISSUE TITLE
[QUERY] How to mock SubscriptionCollection resources.

### ISSUE THREAD

**Issue by sainuthaha** [Azure/azure-sdk-for-net#44526]
### Library name and version

Azure.ResourceManager

### Query/Question

I am trying to write a unit test case for the follwing method

```
  public async Task<List<Subscription>> ListSubscriptionsAsync()
  {
      AsyncPageable<SubscriptionResource> subscriptions = armClient
          .GetSubscriptions()
          .GetAllAsync();
      List<Subscription> subscriptionDataList = new List<Subscription>();

      await foreach (SubscriptionResource subscriptionResource in subscriptions)
      {
          subscriptionDataList.Add(mapper.Map<Subscription>(subscriptionResource.Data));
      }

      return subscriptionDataList;
  }
```

As part of this i need to create SubscriptionCollection and SubscriptionResource objects and am not able to find public methods that will do this for me. How to handle unit tests in these scenarios?

### Environment

Environment details:

dotnet version 8
Azure api app

**Comment by sainuthaha** [comment]
Hi Team, Any update?

**Comment by mcgallan** [comment]
@sainuthaha Currently, the SDK does not support any operations to create SubscriptionCollection and SubscriptionResource. If you attempt to use Moq for mocking, it will also fail because all properties in SubscriptionData are non-overridable. Therefore, I cannot provide an appropriate method to fulfill your creation request. If possible, you can try using the [Get](vscode-file://vscode-app/c:/Users/v-zihewang/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-sandbox/workbench/workbench.esm.html) method to obtain the test data you need.
