### ISSUE TITLE
[BUG] Azure Service Bus Timeout instead of correct response: MessagingEntityNotFound

### ISSUE THREAD

**Issue by michael-eckhart-woellkart** [Azure/azure-sdk-for-net#44555]
### Library name and version

Azure Service Bus Timeout (7.17.5)

### Describe the bug

We have a big cloud application where we distribute data between queues. Each customer could have multiple queues and we will push data there (all in one azure service bus, premium tier). 
It could be that a customer does not have a queue, in that case the documentation says that a 404 (Messaging Entity Not Found) will be returned, It could be that at the same time messages are send to houndrtes of different queues.

### Expected behavior

We expect that if the queue does not exist, we get a 404 (MessagingEntityNotFound), which works with less workload.

### Actual behavior

If there is a lot of workload, we are getting timeouts, instead of 404. If a 404 is returned, we will not send any data to that queue for an amount of time (as it does not exists).
But if there is a timout, we can not know if there is an existing queue or not, in that case we send more data to that queue.

### Reproduction Steps

I added a small application where you can reproduce the issue. I just decreased the timeout to 10 seconds to let happen the issue with 100 queues after some seconds. If you have more queues, you can also increase the timeout and it will still happens.

```
using Azure.Messaging.ServiceBus;

namespace ConsoleApp50
{
    internal class Program
    {
        static int counter = 0;
        static async Task Main(string[] args)
        {
            var serviceBusClient = new ServiceBusClient("[CONNECTION_STRING]", new ServiceBusClientOptions
            {
                RetryOptions = new ServiceBusRetryOptions
                {
                    TryTimeout = TimeSpan.FromSeconds(10)
                }
            });

            for(var i = 0; i < 100; i++)
            {
                _ = Task.Run(() => Send(serviceBusClient.CreateSender("queue" + i)));
                await Task.Delay(25);
            }

            while (true)
            {
                Console.ForegroundColor = ConsoleColor.White;
                Console.WriteLine("Counter: " + counter);
                Console.ForegroundColor = ConsoleColor.Red;
                await Task.Delay(1000);
            }
           

            Console.WriteLine("Hello, World!");
        }

        static async Task Send(ServiceBusSender serviceBusSender)
        {
            var message = new ServiceBusMessage("Hello, World!");

            while (true)
            {
                try
                {
                    await serviceBusSender.SendMessagesAsync(new List<ServiceBusMessage> { message });
                }
                catch (ServiceBusException ex)
                {
                    if (ex.Reason == ServiceBusFailureReason.MessagingEntityNotFound)
                    {
                        counter++;
                    }
                    else
                    {
                        Console.WriteLine("ERROR: " + ex.ToString());
                    }
                }
            }
        }
    }
}
```

### Environment

I use Visual Studion 2022 and dotnet 8.

**Comment by jsquire** [comment]
@michael-eckhart-woellkart : By service contract, the Service Bus service will return a `MessagingEntityNotFound` response if a queue does not exist.  The client reflects this error.   In your case, you are seeing timeouts because the client was unable to create a connection, authorize, create an AMQP link, and send the data within the 10 seconds that you provided when overriding the default `TryTimeout`.   

As a result, the end-to-end service operation did not complete, the service did not send its error response, and the client was therefore unable to observe and surface it.   To verify the behavior, I'd suggest testing without changing the default `TryTimeout` and using a single `ServiceBusSender` instance.

**Comment by michael-eckhart-woellkart** [comment]
/unresolve

Hi @jsquire, thanks for the very fast response.
I just put the timeout to 10 seconds for testing, productive we use the default timeout and still have this issue (there we have more queues) and I think it should not be normal that checking if there is a queue takes more then 30 seconds.

One `ServiceBusSender ` does not work, as the `ServiceBusSender` is only for one queue, and we have a lot of different queues.

**Comment by jsquire** [comment]
@michael-eckhart-woellkart:  You're sharing one connection across all of your senders, which is going to cause queueing of traffic to occur.   You're also starting a large number of background processes, each of which are highly asynchronous and need to be scheduled.  As there are no fairness guarantees with thread pool scheduling, it is possible that some of these will be waiting for a while.   Much depends on your host environment.    All of this is unrelated to the Azure SDK packages - it's how the .NET runtime and network stack work.

Depending on the state of your network, potential transient errors, and similar, it can sometimes take 30-60 seconds to establish the connection, perform auth, open an AMQP link, and complete a service operation.   Given that your sample shares a connection, all of your senders are blocked on the first two steps completing, and then they'll race to complete the latter two.   All of those stages are highly asynchronous and will be fighting for time to complete.

As stated, to test the base error condition, use a single sender pointed at a queue that does not exist and use the default `TryTimeout`.  

With respect to your scenario, if you are seeing timeouts that indicates that you are trying to do too much at once and the `TryTimeout` is inadequate due to your high degree of concurrency.   To mitigate this, I'd suggest either revising your implementation to control concurrency to a degree that is appropriate for your host environment or upping the `TryTimeout` to a value that allows all of those concurrent operations to complete.
