### ISSUE TITLE
ServiceBus trigger session issues causing active message count to spike. Trigger falls behind for ~ 1.5 hour

### ISSUE THREAD

**Issue by iamsamcoder** [Azure/azure-sdk-for-net#44612]
### Library name and version

Microsoft.Azure.Functions.Worker.Extensions.ServiceBus 5.18.0

### Describe the bug

We have a servicebus trigger that appears to stall occaisionally and messages backup in the queue. It happened this morning for ~1h 30m. During this period the active message count rose to ~5k messages and normally it stays under 10. 

By the time this situation was discovered, the function was starting to catch up. Nothing was done to resolve this backup of active messages, but it is not normal operation during this period for our service. 

There was a gap of traces for ~45m during this active message back-up. There were only 4 exceptions for this period, which were all servicebus related exceptions.

Any suggestions on further investigation? This has happened on 6/13/24 and 6/14/24 and today 6/17/24. On 6/13 the function app was restarted twice to resolve the issue.
![projection-queue-back-log](https://github.com/Azure/azure-sdk-for-net/assets/7739218/bd89cc64-a7e3-4994-8fe2-7715b0f90bac)

### Expected behavior

Don't expect the active messages to backup and function operation to stall for long period of time.

### Actual behavior

On 3 occasions in last 5 days, the service bus triggered function has active messages backup and operations are degraded or stalled for 45+ minutes. 

### Reproduction Steps

Have not reproduced this issue. It has occurred 3 times in last 5 days in production environment.

**Comment by jsquire** [comment]
Hi @iamsamcoder.  Thank you for reaching out and we regret that you're experiencing difficulties.  In the majority of scenarios, a Function instance stalling is related to the Azure Functions infrastructure rather than associated with the trigger.  Generally speaking, your best path forward for would be to [open an Azure support request](https://docs.microsoft.com/azure/azure-portal/supportability/how-to-create-azure-support-request) as that will allow you to engage the Azure Functions team who will have access to the platform logs and diagnostics for the period of time that you experienced the behavior.

That said, we would be happy to take a look at client logs from the trigger and offer thoughts, if you'd like.  Because the trigger is a client-side construct, all of its logs are emitted in the scope of your application and would require that you had been collecting them during the time you experienced the behavior.  For most applications, this flows into Applicaiton Insights using the default configuration.  If you have these available and you'd like us to analyze, please share a 10-minute slice of client logs around the time the behavior was observed.
