### ISSUE TITLE
Should not check response body when a DELETE LRO return 204

### ISSUE THREAD

**Issue by ArthurMa1978** [Azure/azure-sdk-for-net#44640]
According to https://github.com/Azure/azure-resource-manager-rpc/blob/master/v1.0/async-api-reference.md#delete-resource-asynchronously, the LRO DELETE operation can return 204 NoContent to indicate success, that means the response body is empty.
However the Azure.Core code still try to extract the `status` from the response body, that will trigger `RequestFailedException` exception, the code in Azure.Core is here https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/core/Azure.Core/src/Shared/NextLinkOperationImplementation.cs#L531.

The issue raised from the new Storage release, which the LRO DELETE operation of the new Task resource returns 204, test code is here
https://github.com/Azure/azure-sdk-for-net/pull/44571/files#diff-ebeebbcae04850fff767b20e818a0857ed54aaa6143f3ee3087497aefd3791ceR190

This block Storage team to release the new stable version of the [.Net SDK](https://github.com/Azure/azure-sdk-for-net/pull/44571) by end of June.

**Comment by live1206** [comment]
@blueww is the contact from storage team

**Comment by jsquire** [comment]
Digging into the Storage PR, it looks like this is related to `/tests/Tests/StorageTaskAssignmentTests::CreateUpdateGetDeleteTaskAssignment` on L190.   That currently corresponds to [this test recording](https://github.com/Azure/azure-sdk-assets/blob/net/storage/Azure.ResourceManager.Storage_3e3c747f5a/net/sdk/storage/Azure.ResourceManager.Storage/tests/SessionRecords/StorageTaskAssignmentTests/CreateUpdateGetDeleteTaskAssignement.json).

The response body in the recording indicates that the status code was 204 and the response body was `null`.    This would then fall to [L571](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/core/Azure.Core/src/Shared/NextLinkOperationImplementation.cs#L571) and [validate there is no location header](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/core/Azure.Core/src/Shared/NextLinkOperationImplementation.cs#L627).    The recording does not indicate a location header being present, so it the clause `headerSource == HeaderSource.None` on [L572](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/core/Azure.Core/src/Shared/NextLinkOperationImplementation.cs#L571) would be satisfied, returning `true` rather than an error.

There seems to be something more going on, though it is unclear what.   We need to isolate repro in a stand-alone manner for further investigation.

@ArthurMa1978 / @blueww :   Please provide the full exception message that you're seeing, along with the stack trace.

**Comment by ArthurMa1978** [comment]
> @ArthurMa1978: There's a check on [L533](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/core/Azure.Core/src/Shared/NextLinkOperationImplementation.cs#L533) that tests to see if the response body has content available:
> 
> ```cs
> if (response.Status is >= 200 and <= 204)
> {
>     if (response.ContentStream is { Length: > 0 })
>     {
>         // Extract content
>     }
> }
> ```
> 
> In the case of a 204 with no content returned, the length of the stream should be 0. That will prevent content from being read. If you're seeing an error extracting content in the 204 case, that would seem to indicate that the service is returning content that we cannot parse despite the response code saying that there is none. The latest swagger seems to
> 
> Please provide an example of the response body and what the content stream is populated where you're seeing this error.

The response.ContentStream contains both header and body, so the `Length > 0` here is true.

**Comment by ArthurMa1978** [comment]
> Digging into the Storage PR, it looks like this is related to `/tests/Tests/StorageTaskAssignmentTests::CreateUpdateGetDeleteTaskAssignment` on L190. That currently corresponds to [this test recording](https://github.com/Azure/azure-sdk-assets/blob/net/storage/Azure.ResourceManager.Storage_3e3c747f5a/net/sdk/storage/Azure.ResourceManager.Storage/tests/SessionRecords/StorageTaskAssignmentTests/CreateUpdateGetDeleteTaskAssignement.json).
> 
> The response body in the recording indicates that the status code was 204 and the response body was `null`. This would then fall to [L571](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/core/Azure.Core/src/Shared/NextLinkOperationImplementation.cs#L571) and [validate there is no location header](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/core/Azure.Core/src/Shared/NextLinkOperationImplementation.cs#L627). The recording does not indicate a location header being present, so it the clause `headerSource == HeaderSource.None` on [L572](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/core/Azure.Core/src/Shared/NextLinkOperationImplementation.cs#L571) would be satisfied, returning `true` rather than an error.
> 
> There seems to be something more going on, though it is unclear what. We need to isolate repro in a stand-alone manner for further investigation.
> 
> @ArthurMa1978 / @blueww : Please provide the full exception message that you're seeing, along with the stack trace.

The `headerSource` is  `HeaderSource.AzureAsyncOperation`, so it fall to [L578](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/core/Azure.Core/src/Shared/NextLinkOperationImplementation.cs#L578), the exception is:


Source=Azure.ResourceManager.Storage
  StackTrace:
   at Azure.Core.OperationInternal`1.GetResponseFromState(OperationState`1 state) in D:\code\srpsdk\sdk\core\Azure.Core\src\Shared\OperationInternalOfT.cs:line 285
   at Azure.Core.OperationInternal`1.<UpdateStatusAsync>d__20.MoveNext() in D:\code\srpsdk\sdk\core\Azure.Core\src\Shared\OperationInternalOfT.cs:line 275
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at Azure.Core.Pipeline.TaskExtensions.EnsureCompleted[T](ValueTask`1 task) in D:\code\srpsdk\sdk\core\Azure.Core\src\Shared\TaskExtensions.cs:line 53
   at Azure.Core.OperationInternalBase.UpdateStatus(CancellationToken cancellationToken) in D:\code\srpsdk\sdk\core\Azure.Core\src\Shared\OperationInternalBase.cs:line 105
   at Azure.Core.OperationInternal.<UpdateStatusAsync>d__9.MoveNext() in D:\code\srpsdk\sdk\core\Azure.Core\src\Shared\OperationInternal.cs:line 110
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at Azure.Core.Pipeline.TaskExtensions.EnsureCompleted[T](ValueTask`1 task) in D:\code\srpsdk\sdk\core\Azure.Core\src\Shared\TaskExtensions.cs:line 53
   at Azure.Core.OperationInternalBase.UpdateStatus(CancellationToken cancellationToken) in D:\code\srpsdk\sdk\core\Azure.Core\src\Shared\OperationInternalBase.cs:line 105
   at Azure.Core.OperationPoller.<WaitForCompletionAsync>d__11.MoveNext() in D:\code\srpsdk\sdk\core\Azure.Core\src\Shared\OperationPoller.cs:line 83
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at Azure.Core.Pipeline.TaskExtensions.EnsureCompleted[T](ValueTask`1 task) in D:\code\srpsdk\sdk\core\Azure.Core\src\Shared\TaskExtensions.cs:line 53
   at Azure.Core.OperationPoller.WaitForCompletionResponse(OperationInternalBase operation, Nullable`1 delayHint, CancellationToken cancellationToken) in D:\code\srpsdk\sdk\core\Azure.Core\src\Shared\OperationPoller.cs:line 35
   at Azure.Core.OperationInternalBase.<WaitForCompletionResponseAsync>d__19.MoveNext() in D:\code\srpsdk\sdk\core\Azure.Core\src\Shared\OperationInternalBase.cs:line 202
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at Azure.Core.Pipeline.TaskExtensions.EnsureCompleted[T](ValueTask`1 task) in D:\code\srpsdk\sdk\core\Azure.Core\src\Shared\TaskExtensions.cs:line 53
   at Azure.Core.OperationInternalBase.WaitForCompletionResponse(CancellationToken cancellationToken) in D:\code\srpsdk\sdk\core\Azure.Core\src\Shared\OperationInternalBase.cs:line 165
   at Azure.ResourceManager.Storage.StorageArmOperation.WaitForCompletionResponse(CancellationToken cancellationToken) in D:\code\srpsdk\sdk\storage\Azure.ResourceManager.Storage\src\Generated\LongRunningOperation\StorageArmOperation.cs:line 83
   at Azure.ResourceManager.Storage.StorageTaskAssignmentResource.Delete(WaitUntil waitUntil, CancellationToken cancellationToken) in D:\code\srpsdk\sdk\storage\Azure.ResourceManager.Storage\src\Generated\StorageTaskAssignmentResource.cs:line 251
  ...
    ...
    [Call Stack Truncated]

**Comment by jsquire** [comment]
@ArthurMa1978:  According to that recording, the 204 response does not contain the `AzureAsyncOperation` header.
https://github.com/Azure/azure-sdk-assets/blob/net/storage/Azure.ResourceManager.Storage_3e3c747f5a/net/sdk/storage/Azure.ResourceManager.Storage/tests/SessionRecords/StorageTaskAssignmentTests/CreateUpdateGetDeleteTaskAssignement.json#L1086

**Comment by jsquire** [comment]
Oh, I think that I see what's going on now.   I grabbed the wrong response.  That 204 is from a GET operation.   The DELETE operations in that recording all return either a 200 or 202.   The one that I think correlates to this is a 202 that includes an `Azure-AsyncOperation` header and a `null` body.

https://github.com/Azure/azure-sdk-assets/blob/net/storage/Azure.ResourceManager.Storage_3e3c747f5a/net/sdk/storage/Azure.ResourceManager.Storage/tests/SessionRecords/StorageTaskAssignmentTests/CreateUpdateGetDeleteTaskAssignement.json#L1306

**Comment by annelo-msft** [comment]
It looks like there are a couple of different things happening here.  The first is that Response.ContentStream.Length should be 0 for a response with no body -- I'm wondering if this is due to a test proxy issue and will follow up on that separately from this issue.  

The second is that, even if Response.ContentStream.Length were correctly set to zero, this LRO would be marked as failed because the first 202 response has a Azure-AsyncOperation header, so when the final 204 response is received, the logic expects to be able to parse the status from the response body.  It is true that [this guidance](Azure-AsyncOperation) says 204/NoContent is valid for the final response for delete, but it looks like that section also redirects to [separate guidance](https://github.com/Azure/azure-resource-manager-rpc/blob/master/v1.0/async-api-reference.md#azure-asyncoperation-resource-format) for use of the Azure-AsyncOperation header.  In that separate guidance it says that responses from that approach should always have a 200 status code, and the response body should indicate the status of the operation.

Given this, I'll close this issue -- I believe if the service either uses 204/NoContent without the Azure-AsyncOperation header, or uses the Azure-AsyncOperation header with a 200 response with status in the response body, the logic in NextLinkOperationImplementation should mark the LRO as Succeeded.  I will follow up separately to understand whether the response ContentStream Length being non-zero is due to the test proxy or another issue.  Thanks!

**Comment by annelo-msft** [comment]
@ArthurMa1978, it looks like the response ContentStream is not getting populated by the test proxy when it replays recordings as I had originally thought (and many thanks to @scbedd for having looked into this on the test proxy side!).

It appears that there is a [pipeline policy in the ARM TestFramework](https://github.com/Azure/azure-sdk-for-net/blob/main/common/ManagementTestShared/Redesign/ResponseNullFilterPolicy.cs#L42-L48) that, when it detects a null response body, adds `"{}"` to the response ContentStream.  

Since there are implementations like NextLengthOperationImplementation that use ContentStream.Length to check whether the response has a body, this policy is going to interfere with that logic.  I would recommend evaluating the need for this in light of such logic in internal shared source and elsewhere -- I do not know offhand how prevalent such checks are.  I would expect other such checks to fail in those cases as well.  And if a service correctly implemented the 204/NoContent part of the ARM LRO spec (without the Azure-AsyncOperation header), this policy would cause the LRO implementation to try to check the status in the body, and it would correctly fail.
