### ISSUE TITLE
[BUG] Unable to use Multipart Form data content types with Azure Core functionalities.

### ISSUE THREAD

**Issue by maichuin** [Azure/azure-sdk-for-net#44774]
### Library name and version

Azure.Core

### Describe the bug

Here [MultiPartFormDataContent](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/core/Azure.Core/src/Shared/Multipart/MultipartFormDataContent.cs) is internal class but generally we use [MultiPartFromDataContent](https://learn.microsoft.com/en-us/dotnet/api/system.net.http.multipartcontent?view=net-8.0) which comes from System.Net.Http is a public class. How can we utilize Azure's internal MultipartFormDataContent class in our APIs to create an API with multipart content type?

### Expected behavior

[MultiPartFormDataContent](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/core/Azure.Core/src/Shared/Multipart/MultipartFormDataContent.cs) should be public class right?

### Actual behavior

Unable to get the instance of the class from the Azure.Core namespace

### Reproduction Steps

Create a sample application and try to create like`data =new Azure.Core.MultipartFormDataContent()`

**Comment by jsquire** [comment]
Hi @maichuin.  Thanks for reaching out and we regret that you're experiencing difficulties.  The visibility for `MultiPartFormDataContent` is intentional; the type is not a full implementation and makes assumptions based on Azure service patterns.  It is intended to be used internally by Azure SDK packages for specific services and is not part of their public API.   At this time, we do not have plans to make this public nor extend the type to fully conform to the HTTP spec.   

It is recommended that you use the official .NET implementation, [System.Net.Http.MultiPartFormDataContent](https://learn.microsoft.com/dotnet/api/system.net.http.multipartcontent?view=net-8.0) as you have already noted.
