### ISSUE TITLE
Does uploading files by azure core is supported

### ISSUE THREAD

**Issue by maichuin** [Azure/azure-sdk-for-net#44770]
### Library name and version

**Azure.Core**

### Query/Question

I am providing the sample code for uploading PDF file to the server through Http. Conetnt type of API is multimedia format.

```
var client = new HttpClient();

var request = new HttpRequestMessage(HttpMethod.Post, API_end_point);
request.Headers.Add("Authorization", "Bearer  token");
var content = new MultipartFormDataContent(); 
string directoryPath = @"C:\folder";

// File name
string fileName = "a.pdf";

// Combine directory path and file name
string filePath = Path.Combine(directoryPath, fileName);
var stream = new FileStream(filePath, FileMode.Open, FileAccess.Read);
content.Add(new StreamContent(stream), "stream", fileName);

request.Content = content;
var response = await client.SendAsync(request);
response.EnsureSuccessStatusCode();
Console.WriteLine(await response.Content.ReadAsStringAsync()); 
```

How can I create an API (Multi Part Form Data Content)  using Azure Core functionalities and include client diagnostics? Could you provide a code snippet?

Thanks in advance

**Comment by jsquire** [comment]
Hi @maichuin.  Azure.Core provides a pipeline for processing HTTP requests and responses.  This is done using the [HttpPipeline](https://learn.microsoft.com//dotnet/api/azure.core.pipeline.httppipeline?view=azure-dotnet) instance that you create using the [HttpPipelineBuilder](https://learn.microsoft.com/en-us/dotnet/api/azure.core.pipeline.httppipelinebuilder?view=azure-dotnet).    The members of `HttpPipeline` allow you to create requests with any content that you like - including multipart form data. 

You would need to follow the HTTP spec and format the request content as the service expects.  As Azure.Core is primarily intended to be used as a building block for Azure SDK libraries rather than used directly in your application, we do not have public samples at this time of usage.   Your best bet would be to look through the Azure SDK source to see usage.  For example, [TextAnalyticsRestClient](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/textanalytics/Azure.AI.TextAnalytics.Legacy.Shared/src/Generated/TextAnalyticsRestClient.cs) is based on the Azure Core pipeline and interacts with MPFD content.
