### ISSUE TITLE
Azure.Identity/1.12.0 - CVE-2024-30105 -  System.Text.Json4.7.2. 

### ISSUE THREAD

**Issue by rsrinivasanhome** [Azure/azure-sdk-for-net#45029]
### Library name and version

Azure.Identity/1.12.0

### Describe the bug

Azure Identity is using System.Text.Json4.7.2. 

CVE-2024-30105  is applicable

https://github.com/advisories/GHSA-hh2w-p6rv-4g7w

### Expected behavior

CVE should not present

### Actual behavior

cve is present

### Reproduction Steps

Binary scan of the product

### Environment

visual studio

**Comment by ajtruckle** [comment]
![image](https://github.com/user-attachments/assets/25271e48-7b22-45f2-9b60-e6a54ea83930)

Is this fixed in 1.12.0?

**Comment by ajtruckle** [comment]
@jsquire  It is listed as a transitive dependency and Visual Studio is indicating the packages mentioned as using version 8.0.0:

* Azure.Identity.1.11.4
* Microsoft.Exstensions.Configuration.Json.8.0.0
* Microsoft.Exstensions.Configuration.UserSecrets.8.0.0
* Microsoft.Graph.5.56.0

**Comment by ajtruckle** [comment]
@jsquire I can confirm that this package is using version 8.0.0:

* Microsoft.Exstensions.Configuration.Json.8.0.0

![image](https://github.com/user-attachments/assets/dd11a818-1125-43d0-a810-eca4ef671caa)

But I don't know how to bring this issue to their attention.

**Comment by jsquire** [comment]
@ajtruckle:

Visual Studio is telling you what is being used by Azure.Identity, either because the app or another dependency hoisted the version being loaded.   This is due to how .NET manages assembly loading and the restriction of having a single version of an assembly loaded into a process.   This is something that you'll need to troubleshoot in your application, as the Azure SDK packages do not have insight nor influence over forced upgrades.

[Azure.Identity (latest)](https://www.nuget.org/packages/Azure.Identity#dependencies-body-tab)
![image](https://github.com/user-attachments/assets/d8b82374-5cd4-40a6-9936-7b0d857fd45f)

[Azure.Core (latest)](https://www.nuget.org/packages/Azure.Core#dependencies-body-tab):
![image](https://github.com/user-attachments/assets/d3a22032-d21f-4a26-9771-98668c09e4d5)

[System.ClientModel (latest)](https://www.nuget.org/packages/System.ClientModel/#dependencies-body-tab)
![image](https://github.com/user-attachments/assets/4ca374eb-04ef-47b6-9fbc-85b384c44d89)

**Comment by ajtruckle** [comment]
@jsquire  Thanks for the info. 🙏 Please see my previous comment which identifies the culprit.

**Comment by jsquire** [comment]
@ajtruckle:  That is maintained by the .NET team from the runtime repository:
https://github.com/dotnet/runtime

I believe that would be the place to file an issue.   Their response is likely to be that the recommended short-term mitigation is to take a direct reference to v8.0.4 in your app, which will take precedence and hoist the version loaded.
