### ISSUE TITLE
In the Azure .Net SDK , VectorQuery.KNearestNeighborsCount it seems that this parameter controls the total number of results from the Vector Search returned[QUERY]

### ISSUE THREAD

**Issue by aveekr** [Azure/azure-sdk-for-net#45053]
### Library name and version

Azure AI Search client library for .NET - version 11.5.1

### Query/Question

If the customer is not using exhaustive search then also this parameter controls the number of search results returned. Also for Hybrid Search this parameter is controlling the total no of search results. Is this the expected behavior

### Environment

Using Azure .Net SDK

**Comment by ShivangiReja** [comment]
Yes, this is the expected behavior. The `KNearestNeighborsCount` parameter controls the number of search results returned from the vector query, regardless of whether exhaustive search is used. It determines the number of nearest neighbors to retrieve as the top hits.

For pure single-field vector queries, they will behave the same way. Here's an example of how it works.

_vector query is received -> execute vector query to produce kNearestNeighborsCount results -> using this result set, return top results._

For hybrid or cross-field vector or multi-vector queries, the results are fused using Reciprocal Rank Fusion (RRF). This means `KNearestNeighborsCount` controls how many results you want to consider for the RRF re-ranking from the vector query part. Since RRF can re-order documents depending on the rank and number of result sets a document appears in, this parameter value can change the result order and contents.

Regarding the `exhaustive` parameter, it controls whether an exhaustive k-nearest neighbor search is performed across all vectors within the vector index. When set to true, it ensures that exact matches are found, which is useful for scenarios where ground truth values are critical. However, even with exhaustive search enabled, the `KNearestNeighborsCount` parameter still determines the number of search results returned.

I hope this clarifies how the `KNearestNeighborsCount` parameter controls the number of results you receive.

For more detailed information, you can refer to the [Azure documentation](https://learn.microsoft.com/en-us/azure/search/vector-search-how-to-query?tabs=query-2023-11-01%2Cfilter-2023-11-01#number-of-ranked-results-in-a-vector-query-response).
