### ISSUE TITLE
[BUG] EventHubs logs a lot of error with "receiver 'guid' with epoch '0' is getting disconnected."

### ISSUE THREAD

**Issue by andrew-lis** [Azure/azure-sdk-for-net#45225]
### Library name and version

Azure.Messaging.EventHubs.Processor 5.11.3

### Describe the bug

Usually the service that reads the stream from EventHubs work OK. But at least once a day we get a wall of error logs from our service. 

Error details are listed on the bottom of this description. The errors are weird because they complain about Epoch client, but non of clients use Epoch clients. When the errors start to occur, the number of processed events raises (it suggests that it behaves like reconnections and last seconds are reread). 

Configuration/setup used:
* .Net 8, with Azure SDK Azure.Messaging.EventHubs.Processor 5.11.3
* `EventProcessorClient` instance with the `StartProcessingAsync()` method
* `DefaultStartingPosition` with `EventPosition.FromEnqueuedTime(DateTime.UtcNow.Add(TimeSpan.FromSeconds(5)));`
* We do NOT use Epoch clients
* We do not use checkpoints.
* `PartitionOwnershipExpirationInterval` = 45 seconds
* `LoadBalancingUpdateInterval` = 15seconds 
* We have 10 partitions, 1 consumer group, 3 clients (3 instances of the same service), 

Error 1:
An exception occurred while receiving events for Event Hub: myhub (Consumer Group: 'mygroup', Partition Id: '4'); Operation Id: 'ea436097-4247-4163-84ac-632b5b5b6022'. Error Message: 'New receiver 'P4-ddc8f043-abb7-4d47-80b4-712fab393092' with higher epoch of '0' is created hence current receiver 'P4-a8f54af2-5659-4506-b755-5fc27ac60c63' with epoch '0' is getting disconnected. If you are recreating the receiver, make sure a higher epoch is used. TrackingId:601237a0000420810019f7e666a77060_G1_B5, SystemTracker:name:eventhub:myhub~16384|mygroup, Timestamp:2024-07-29T10:35:28 (myhub). For troubleshooting information, see https://aka.ms/azsdk/net/eventhubs/exceptions/troubleshoot'

Error 2:
An exception occurred while processing events for partition '6' by processor instance with identifier '020c2dee-b089-4608-89c9-e6f0558ae917' for Event Hub: myhub and Consumer Group: mygroup.  Error Message: 'New receiver 'P6-ddc8f043-abb7-4d47-80b4-712fab393092' with higher epoch of '0' is created hence current receiver 'P6-020c2dee-b089-4608-89c9-e6f0558ae917' with epoch '0' is getting disconnected. If you are recreating the receiver, make sure a higher epoch is used. TrackingId:c4f8c9d0000420810019f7e166a7705f_G19_B5, SystemTracker:name:eventhub:myhub~22938|mygroup, Timestamp:2024-07-29T10:35:28 (myhub).  For troubleshooting information, see https://aka.ms/azsdk/net/eventhubs/exceptions/troubleshoot'

### Expected behavior

There should be no such error when epoch clients are not used.

### Actual behavior

Once or twice a day we get a wall of exceptions like the ones described in "Expected behavior". It's not deterministic. 

### Reproduction Steps

1. Configure service in a similar way it's described in the Description
2. Let it run for a day or two
3. Observe the errors. 

### Environment

Azure EventHubs; Service in .net 8 on debian on AKS.

**Comment by jsquire** [comment]
Hi @andrew-lis.  Thank you for reaching out and we regret that you're experiencing difficulties.   This is a common issue due to how the application is configuring event processors.  The root cause is either that you've got other processors using the same consumer group, all processors are not using the same Storage container, or your environment does not have enough resources to the workload that you're putting on the processor and load balancing cannot run consistently.  This scenario is covered in detail in our [Troubleshooting Guide](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/eventhub/Azure.Messaging.EventHubs/TROUBLESHOOTING.md#frequent-errors-for-current-receiver--receiver_name--with-epoch-0-is-getting-disconnected).   Please follow steps there to diagnose and mitigate.

If you have completed all TSG steps and require further assistance, please collect a 5-minute slice of verbose logs as discussed in the TSG [[here](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/eventhub/Azure.Messaging.EventHubs/TROUBLESHOOTING.md#event-processor-issues)] and answer the questions from the TSG [[here](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/eventhub/Azure.Messaging.EventHubs/TROUBLESHOOTING.md#filing-github-issues)].   Once logs and answers are available, reactivate.

**Comment by jsquire** [comment]
One thing that I'll call out from the information shared:

> PartitionOwnershipExpirationInterval = 45 seconds
> LoadBalancingUpdateInterval = 15seconds

Those values are very aggressive and we  wouldn't recommend them unless you are open to the risk of seeing ownership slip during any network blip.  Your partition ownership interval is less that what we advice for a `TryTimeout` to cover an end-to-end network operation.   Any break in your Event Hubs connection that causes the client to reconnect will potentially cause your partitions to migrate and see contention as they bounce.
