### ISSUE TITLE
[QUERY] [Search] Missing NativeBlobSoftDeleteDeletionDetectionPolicy after update

### ISSUE THREAD

**Issue by albx** [Azure/azure-sdk-for-net#45255]
### Library name and version

Azure.Search.Documents v.11.6.0

### Query/Question

After updating the package Azure.Search.Documents from version 11.6.0-beta4 I can't find the class NativeBlobSoftDeleteDeletionDetectionPolicy anymore

![image](https://github.com/user-attachments/assets/1fb94b15-70f3-4516-b67a-40cb926db5ec)

Which class can be used to achieve the same behavior?

**Comment by ShivangiReja** [comment]
Currently, the search service supports the `NativeBlobSoftDeleteDeletionDetectionPolicy` type only in preview releases. This type is not included in the stable release because it is part of a preview feature supported only in the preview version of the Azure Search service. A stable client library cannot rely on a preview version of the service. If the feature becomes stable and is supported in the Search service, the client library will include support for it.

This feature request is specifically for the service team. The SDK can only incorporate features that are supported by the service. If you have any support requests or questions related to the search service, please raise an issue at [Azure Search · Community](https://feedback.azure.com/d365community/forum/9325d19e-0225-ec11-b6e6-000d3a4f07b8). For any SDK-related questions, feel free to create issues on the [Azure SDK for .NET GitHub](https://github.com/Azure/azure-sdk-for-net/issues).
