### ISSUE TITLE
403 Forbidden when ai search and azure openai public networking is disabled

### ISSUE THREAD

**Issue by GijsVoogd** [Azure/azure-sdk-for-net#45326]
### Library name and version

latest

### Query/Question

Question regarding Azure OpenAI using RAG on our own data via AI Search with the SDK. Our setup is as follows:

AI Search:
- private network disabled
- private endpoint for inbound traffic
- shared private link for openai (type account), and blob storage (type blob and dfs)
- allow Azure services on the trusted services list to access this cognitive services account

Azure OpenAI:
- private network disabled
- private endpoint for inbound traffic (the openai account and search shared private link)
- allow Azure services on the trusted services list to access this cognitive services account

The issue we’re facing with the SDK is that it is calling OpenAI and from OpenAI, AI Search is called. This gives a 403 which seems to make sense since AI Search public network is disabled and we cannot integrate Azure OpenAI in the VNET. Shared private access is not an option on Azure OpenAI.

It works when we enable public access on AI Search but we have a requirement for private access only. Is there a way to make this work without enabling public access? 

{

  "error": {

    "requestid": "5ff1d736-ce49-4df8-91b3-4870b5e86805",

    "code": 400,

    "message": "Invalid AzureCognitiveSearch configuration detected: Call to get Azure Search index failed. Check if you are using the correct Azure Search endpoint and index name. If you are using key based authentication, check if the admin key is correct. If you are using access token authentication or managed identity of Azure OpenAI, check if the Azure Search has enabled RBAC based authentication and if the user identity or Azure OpenAI managed identity has required role assignments to access Azure Search resource [
https://aka.ms/aoaioydauthentication].
If the Azure Search resource has no public network access, make sure enable trusted service of Azure Search.\nAzure Search Error: 403, message\u003d\u0027Server responded with status 403.

**Comment by jsquire** [comment]
Hi @GijsVoogd.  Thank you for reaching out and we regret that you're experiencing difficulties.  The behavior that you're seeing is from the Search service itself; the Azure SDK packages have no insight into how the Azure Search service authenticates against OpenAI nor influence over the behavior.

Unfortunately, this is not something that the maintainers of the Azure SDK packages can assist with.  Because the Azure services themselves are not managed on GitHub, we're unable to transfer this on your behalf.  To ensure that the right team has visibility and can help, your best path forward for would be to [open an Azure support request](https://docs.microsoft.com/azure/azure-portal/supportability/how-to-create-azure-support-request) or inquire on the [Microsoft Q&A site](https://learn.microsoft.com/answers/questions/).  

I'm going to close this out; if I've misunderstood what you're describing, please let us know in a comment and we'd be happy to assist as we're able.

**Comment by dmbuk** [comment]
Hi @GijsVoogd  

We are having the same issue using off the shelf BYOD app from MS.
Have you managed to find a solution for this? 
![Image](https://github.com/user-attachments/assets/bd7e1657-b79e-42d4-b322-e9092082ab45)

**Comment by GijsVoogd** [comment]
Hi @dmbuk the solution is to change the key based authentication to MI based authentication

**Comment by GijsVoogd** [comment]
It's not about setting at the OpenAI resource level. If you use managed identity: true in your dotnet code it should work. It doesn't have to do with the OpenAI resource if that is configured properly

**Comment by dmbuk** [comment]
ok, cool. We use MS stock app that calls OpenAI and then OpenAI calls AI search. The last bit is where it fails. 
Looks like our case is different. 
Thanks @GijsVoogd  anyway 👍
