### ISSUE TITLE
Azure Table Storage Query with Timestamp Filter Returns Inconsistent Page Sizes

### ISSUE THREAD

**Issue by utpal-appseconnect** [Azure/azure-sdk-for-net#45349]
### Library name and version

Azure.Data.Tables

### Describe the bug

We have an Azure Table Storage setup where we store a large amount of data for different organizations. We use the Organization ID as the partition key.

For some operations, we need to fetch data from the last 24 hours for a particular organization. We've written the following code to achieve this, using pagination to handle large datasets. According to our logic, each page should return 1,000 entities.

The code works perfectly when filtering only by the partition key; each page returns 1,000 entities as expected. However, when we add an additional filter for the Timestamp, the results become inconsistent. Some pages return 100 entities, others return 60, and some even return as few as 0 or 1 entities. This seems like a bug in the SDK.

Has anyone else encountered this issue? Is there a known workaround or a fix for this? Could this be an issue with how the SDK handles compound filters, or is there something wrong with the logic in the code?

```
public async Task<IEnumerable<T>> RetrieveEntitiesWithDailyFilterAsync(string tableName, string partitionKey)
{
    List<T> entities = new List<T>();
    //List<TableEntity> entities = new List<TableEntity>();
    string continuationToken = null;

    // Calculate the date and time 24 hours ago from now
    DateTime fromDate = DateTime.UtcNow.AddHours(-24);

    // Build the predicate to filter by PartitionKey and Timestamp
    var predicate = PredicateBuilder.Build<T>(x => x.PartitionKey == partitionKey);
    //for daily
    // predicate = predicate.AndAlso(x => x.Timestamp >= fromDate);
   
    do
    {
        
        var _tableClient = _tableServiceClient.GetTableClient(tableName);

        // Query the table with the predicate and maxPerPage
        var queryResult = _tableClient.QueryAsync<T>(predicate, maxPerPage: 1000);

        // Iterate through pages of results
        await foreach (var page in queryResult.AsPages(continuationToken))
        {
            continuationToken = page.ContinuationToken;
            entities.AddRange(page.Values);
        }
    } while (!string.IsNullOrEmpty(continuationToken));

    return entities;
}
```

### Expected behavior

When querying Azure Table Storage with only the partition key filter, pagination works correctly, and each page consistently returns 1,000 entities. 

### Actual behavior

But when adding a Timestamp filter to limit the results to the last 24 hours, the page sizes vary drastically. This happens even when there should be a large amount of data within the time range.

### Reproduction Steps

List<T> entities = new List<T>();
//List<TableEntity> entities = new List<TableEntity>();
string continuationToken = null;

// Calculate the date and time 24 hours ago from now
DateTime fromDate = DateTime.UtcNow.AddHours(-24);

// Build the predicate to filter by PartitionKey and Timestamp
var predicate = PredicateBuilder.Build<T>(x => x.PartitionKey == partitionKey);
//for daily
// predicate = predicate.AndAlso(x => x.Timestamp >= fromDate);
           
do
{
    
    var _tableClient = _tableServiceClient.GetTableClient(tableName);

    // Query the table with the predicate and maxPerPage
    var queryResult = _tableClient.QueryAsync<T>(predicate, maxPerPage: 1000);

    // Iterate through pages of results
    await foreach (var page in queryResult.AsPages(continuationToken))
    {
        continuationToken = page.ContinuationToken;
        entities.AddRange(page.Values);
    }
} while (!string.IsNullOrEmpty(continuationToken));

return entities;

### Environment

.net core application

**Comment by jsquire** [comment]
Hi @utpal-appseconnect.  Thanks for reaching out and we regret that you're experiencing difficulties.   Page results for queries are calculated entirely by the Tables endpoint of the associated service; the client has no insight into what results are assigned to a page nor influence over it.   The client only surfaces each page as returned by the service and facilitates a request with the associated continuation token to request the next page as the application asks for it.   

Unfortunately, because your inquiry is regarding behavior of the service, the maintainers of the Azure SDK packages are unable to assist.  Azure services are not managed on GitHub, so we are also unable to transfer this to the appropriate team on your behalf.  To ensure that the right team has visibility and can help, your best path forward for would be to [open an Azure support request](https://docs.microsoft.com/azure/azure-portal/supportability/how-to-create-azure-support-request) or inquire on the [Microsoft Q&A site](https://learn.microsoft.com/answers/questions/).   For feature suggestions, you may also want to consider the [Azure Feedback site](https://feedback.azure.com/d365community).

I'm going to close this out; if I've misunderstood what you're describing, please let us know in a comment and we'd be happy to assist as we're able.

**Comment by utpal-appseconnect** [comment]
Per day we store nearly 4-5k data per partition key and we want to retrive all of them.If this kind of inconsistent behaviour we face then for fetchich all data will take huge amount of time .is there any alternate way to retrive data in a faster way.What are the modification we need to do in the service end.please suggest

**Comment by jsquire** [comment]
As mentioned, the maintainers of the Azure SDK packages have no insight into the service behavior beyond what their OpenAPI specification states is the contract.   You'll want to follow one of the suggested paths above and ask your question of the service team.
