### ISSUE TITLE
Threshold is missing on VectorizedQuery

### ISSUE THREAD

**Issue by kim4848** [Azure/azure-sdk-for-net#45531]
### Type of issue

Typo

### Description

Feedback on Azure.Search.Documents.Models.VectorQuery Package: Azure.Search.Documents v11.6.0

**Issue Identified:**
It seems there is confusion or a possible discrepancy regarding the Threshold property in the VectorQuery class.

**Details:**
According to the [Microsoft documentation](https://learn.microsoft.com/en-us/dotnet/api/azure.search.documents.models.vectorquery.threshold?view=azure-dotnet#azure-search-documents-models-vectorquery-threshold), there is a Threshold property associated with VectorQuery. However, it appears that the VectorizedQuery class should inherit the Threshold property from VectorQuery, but currently, VectorQuery does not contain a Threshold property.

**Potential Issues:**

1. Documentation Error: There might be an error in the documentation where the Threshold property is mentioned, but the actual implementation does not include it.
2. Code Implementation Bug: Alternatively, the VectorQuery class might be intended to include the Threshold property, and its absence could be a bug in the codebase.

**Request for Clarification:**
Could you please confirm whether this issue is a documentation error or a bug in the code implementation? This clarification is essential for developers relying on the accuracy of both the documentation and the API's functionality.

### Page URL

https://learn.microsoft.com/en-us/dotnet/api/azure.search.documents.models.vectorquery?view=azure-dotnet

### Content source URL

https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Azure.Search.Documents.Models/VectorQuery.xml

### Document Version Independent Id

6c4d2760-ba6c-0339-348e-b6705b970ae9

### Article author

@azure-sdk

### Metadata

* ID: fd72d24a-9347-4442-3820-a89d9ec38739 
* Service: **azure**

**Comment by jsquire** [comment]
Hi @kim4848. Thank you for reaching out and we regret that you're experiencing difficulties.   The documentation that you're looking for is for prerelease versions of the library.   The `VectorQuery` property exists in 11.16.0-beta.4 version of the library, as it is tied to a beta feature of the service.   The stable package, 11.16.0, does not include this property because it is not supported by the stable version of the Azure Search service.   The [stable version of the VectorQuery docs](https://learn.microsoft.com/dotnet/api/azure.search.documents.models.vectorquery?view=azure-dotnet) do not include this property.
