### ISSUE TITLE
Microsoft.Azure.EventGrid - Event Grid Client, PublishEventsAsync exception - "A task was canceled" during parallel execution.  

### ISSUE THREAD

**Issue by MaxVL** [Azure/azure-sdk-for-net#4575]
Visual Studio 2017 Enterprize
Framework Net 4.5.1

Tried both debug and running .exe. 

I am running Parallel.For loop sending 5 000 events with the degree of parallelism 8. 

At some point half way I am noticing slow down, and later on getting an exception, that "Task was cancelled".

Not sure why is this happening. 

System.Threading.Tasks.TaskCanceledException

◢ | Task | Id = 70169, Status = Canceled, Method = "{null}", Result = "{Not yet computed}" | System.Threading.Tasks.Task {System.Threading.Tasks.Task<System.Net.Http.HttpResponseMessage>}

   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.Azure.EventGrid.EventGridClient.<PublishEventsWithHttpMessagesAsync>d__38.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.EventGrid.EventGridClientExtensions.<PublishEventsAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at UniModelSample.MainWindow.<>c__DisplayClass72_0.<<btnEventGridSDKSend_Click>b__0>d.MoveNext() in C:\Source\Repos\UniModelSample\UniModelSample\MainWindow.xaml.cs:line 1898

**Comment by mevansdev** [comment]
May be related https://github.com/Azure/azure-functions-host/issues/3160

**Comment by ahamad-MS** [comment]
@MaxVL  Are you still hitting this issue? If yes, please open a support ticket with the required information as the call stack here is not helpful. We will need fresh run with exact time and location and sample of event ids that failed for you in order to be able to determine if this is coming from the service side or not. thanks.

**Comment by jfggdl** [comment]
@MaxVL, we are closing this issue, but feel free to reopen it if you have any additional questions or cannot create a technical support request on the Azure portal.

**Comment by kalyanaj** [comment]
The following is some general guidance to avoid hitting HTTP timeouts during publishing of events using the EventGridClient:

1. Whenever possible, publish a batch of events instead of publishing individual events: For example:

                List<EventGridEvent> eventGridEvents = new List<EventGridEvent>();

                for (int i = 0; i < numberOfEvents; i++)
                {
                    EventGridEvent gridEvent = new EventGridEvent( /* build EventGridEvent object with the right values */);
                    eventGridEvents.Add(gridEvent);
                }

                await client.PublishEventsAsync(BaseAddress.Host, eventGridEvents);

2. Configure the connection limit appropriately. Please see https://docs.microsoft.com/en-us/dotnet/framework/network-programming/managing-connections for additional guidance.

3. Make sure you are reusing connections by setting httpClient.DefaultRequestHeaders.ConnectionClose to false. You can use this in conjunction with the ConnectionLeaseTimeout to ensure that the connections don't stay open indefinitely.
      var sp = ServicePointManager.FindServicePoint(new Uri(<topic-URI>));
      sp.ConnectionLeaseTimeout = 60*1000; // 1 minute

The above set of steps should help with reducing the number/latency of HTTP requests made from the client and it should help in avoid hitting the request timeouts.

**Comment by MattHartz** [comment]
@kalyanaj Do you know how to consistently replicate this issue? I am experiencing this in a production environment, but cannot replicate. I have a wrapper class that has a local EventGridClient in a container with Unity. So it shouldn't be creating HttpClients per event.

Or if anyone has some ideas that would be great! :)
