### ISSUE TITLE
[BUG] - An exception occured while creating receive link for Identifier: xxx. Error message: 'System.Net.Sockets.SocketException (10054): An existing connection was forcibly closed by the remote host.

### ISSUE THREAD

**Issue by fabioloreggian** [Azure/azure-sdk-for-net#45775]
### Library name and version

Microsoft.Azure.Functions.Worker.Extensions.ServiceBus 5.20.0

### Describe the bug

When setting up a Function App trigger on a service bus queue, we are getting a "An exception occured while creating receive link for Identifier: xxx. Error message: 'System.Net.Sockets.SocketException (10054): An existing connection was forcibly closed by the remote host" error when trying to create the receiver link. 

We started getting this error when migrating to a new service bus. 

Everything has only been tested on local and we haven't deployed the function app to an environment. 

### Expected behavior

We expect the connection to succeed and pull messages off of the queue and process them.

### Actual behavior

An exception occured while creating receive link for Identifier: xxx. Error message: 'System.Net.Sockets.SocketException (10054): An existing connection was forcibly closed by the remote host. Thus the messages are not being processed.

### Reproduction Steps

Not sure, since it works for another sb + queue.

### Environment

Dotnet: 6.0.425
Windows 10.0.19045

**Comment by fabioloreggian** [comment]
[log.log](https://github.com/user-attachments/files/16842746/log.log)

**Comment by jsquire** [comment]
Hi @fabioloreggian.  Thanks for reaching out and we regret that you're experiencing difficulties.  The error indicates that there was a network issue when attempting to open an AMQP connection and link to Service Bus.  This may be due to conditions of the local network or may be due to a service issue.   Unfortunately, the client has no insight nor influence over this behavior.  The maintainers of the Azure SDK are unable to assist with your inquiry.

To ensure that the right team has visibility and can help, your best path forward for would be to [open an Azure support request](https://docs.microsoft.com/azure/azure-portal/supportability/how-to-create-azure-support-request) for Service Bus.  That will engage the service team who will have access to server-side logs and telemetry that can answer whether this was a local network failure, or the service rejected the link.   In the latter case, they'll also be able to tell you why.

I'm going to close this out; if I've misunderstood what you're describing, please let us know in a comment and we'd be happy to assist as we're able.
