### ISSUE TITLE
GetPropertiesOfSecretVersions order of list of versions

### ISSUE THREAD

**Issue by OzBob** [Azure/azure-sdk-for-net#45792]
### Type of issue

Missing information

### Description

[Enter feedback here]
The list of SecretVersions returned requires an order. From experimenting I deduce the order is oldest to newest. Making the 2nd last item (if present) the 'previous' version.

### Page URL

https://learn.microsoft.com/en-us/dotnet/api/azure.security.keyvault.secrets.secretclient.getpropertiesofsecretversions?view=azure-dotnet

### Content source URL

https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Azure.Security.KeyVault.Secrets/SecretClient.xml

### Document Version Independent Id

3a7d6e3f-aacc-d4c6-070c-4f23261e8ca9

### Article author

@azure-sdk

### Metadata

* ID: 7573bde6-64f2-e198-ef89-5456ca36d793 
* Service: **azure**

**Comment by jsquire** [comment]
Hi @OzBob.  Thanks for reaching out and for your suggestion.  The ordering of results is controlled by the Key Vault service.  The client does not have any insight nor influence over how they're ordered.  Because the service does not document a guaranteed ordering in the [REST API documentation](https://learn.microsoft.com/rest/api/keyvault/secrets/get-secret-versions/get-secret-versions?view=rest-keyvault-secrets-7.4&tabs=HTTP), we're unable to provide that information in the client documentation.   As it exists today, the order is an implementation detail of the service and may change.

If you would like to provide feedback for the service documentation, your best path forward for would be to [open an Azure support request](https://docs.microsoft.com/azure/azure-portal/supportability/how-to-create-azure-support-request) or leave feedback on the [Azure Feedback site](https://feedback.azure.com/d365community).  Both paths will ensure that the Key Vault service team has visibility.
