### ISSUE TITLE
[QUERY][ServiceBus][ManagedIdentity]

### ISSUE THREAD

**Issue by loGit123** [Azure/azure-sdk-for-net#45875]
### Library name and version

Microsoft.Azure.WebJobs.Extensions.ServiceBus - 5.2.0 ,Azure.Messaging.ServiceBus - 7.8.0

### Query/Question

I am trying to Use ServiceBus Trigeer with Managed Identity but it not able to run as it is giving below error 
The listener for function 'ProcessSubscriptions' was unable to start. The connection string used for an Service Bus client must specify the Service Bus namespace host and either a Shared Access Key (both the name and value) OR a Shared Access Signature to be valid. (Parameter 'connectionString')

My template.json 
appsetting - json(concat('{\"name\":\"ServiceBusConnection__fullyQualifiedNamespace\",\"value\":\"Endpoint=sb://', variables('servicebus_name'), '.servicebus.windows.net\"}'))),

### Environment

dotnet - 6.0

**Comment by jsquire** [comment]
@loGit123 : Thanks for reaching out and we regret that you're experiencing difficulties.  The error message indicates that Functions believes that you're using a connection string rather than an identity-based connection.  Unfortunately, there's not enough context available here to offer additional thoughts.  

**Please be aware that the version of the extensions package that you're using is ~3 years old.  Please update to the latest packages and confirm that you're able to reproduce.**

 If so, please share a code snippet demonstrating your function with its trigger attribute, the relevant section of your host.json, and the relevant section of your configuration settings - with any sensitive information redacted.

**Comment by loGit123** [comment]
Can you please point me to the latest stable version to use for this ?
This tutorail I followed - https://learn.microsoft.com/en-us/azure/service-bus-messaging/service-bus-managed-service-identity

**Comment by jsquire** [comment]
The [Microsoft.Azure.WebJobs.Extensions.ServiceBus package](https://www.nuget.org/packages/Microsoft.Azure.WebJobs.Extensions.ServiceBus) is currently at v5.16.4.   The [Azure.Messaging.ServiceBus package](https://www.nuget.org/packages/Azure.Messaging.ServiceBus) is currently at v7.18.1.   The versions that you've detailed using are 2-3 years old.

**Comment by loGit123** [comment]
I have changed the version to 5.16.4 and 7.18.1 
but still at listener I am getting this error 

The listener for function 'ProcessSubscriptions' was unable to start. The connection string used for an Service Bus client must specify the Service Bus namespace host and either a Shared Access Key (both the name and value) OR a Shared Access Signature to be valid. (Parameter 'connectionString') 

in arm template, I have added servicebusconnection__fullyQualifiedNamespace.
and added roleAssignments for Data Owner and Receiver, Example is like below .... 

and for the listener below is the code... 

this.QueueClient = client ?? new ServiceBusClient("testservicebus.servicebus.windows.net", new DefaultAzureCredential()).CreateSender(QueueNAme);


Is there anything else has to added to resolve this error?

**Comment by jsquire** [comment]
@loGit123 :  Please share your Function signature with the trigger attribute and your config.   The listener is part of the trigger infrastructure and has nothing to do with the snippet below.  That snippet is creating a sender.   That said, you are also leaking the ServiceBusClient which you need to ensure gets disposed or you'll end up orphaning the connection.

**Comment by loGit123** [comment]
public async Task Run(
         [ServiceBusTrigger(ServiceBusSubscriptionQueue.SUBSCRIPTIONQUEUE, Connection = "ServiceBusConnection")]
         Subscription subscription,
         ILogger logger)
 
 Config 
 
 appsetting - json(concat('{\"name\":\"ServiceBusConnection__fullyQualifiedNamespace\",\"value\":\"Endpoint=sb://', variables('servicebus_name'), '.servicebus.windows.net\"}'))),

**Comment by loGit123** [comment]
Sometimes this error also I am getting - The listener for function 'ProcessGroups' listener was unable to start. The connection string could not be parsed; either it was malformed or contains no well-known tokens.

**Comment by jsquire** [comment]
A fully qualified namespace name should be something like: `your-namespace.servicebus.windows.net`.    The value that you're setting is not a valid namespace and is interpreted as a connection string.   It is also not a valid connection string, as it's missing the shared key or SAS, so it fails validation.   _(see: [docs](https://learn.microsoft.com/azure/azure-functions/functions-bindings-service-bus-trigger?tabs=python-v2%2Cisolated-process%2Cnodejs-v4%2Cextensionv5&pivots=programming-language-csharp#identity-based-connections))_. 

A couple of other notes:

- The config is just a JSON file; I've never seen an active statement like that the app.config consumed by the runtime, and I wouldn't think that it works.   I'm assuming that you're showing an interim transform rather than the final config (ARM template, maybe?)   But I thought it worth mentioning, just in case.

- I would strongly recommend against assuming the suffix of your namespace and forming by hand.  There's no guarantee that it will not change in the future and is not valid in all Azure clouds.

**Comment by loGit123** [comment]
BUT i AM USING MANAGED IDENITY then why sas is required?  and how it is not a valid namespace?

**Comment by jsquire** [comment]
> /unresolve BUT i AM USING MANAGED IDENITY then why sas is required?

It's not.   You're malforming the fully qualified namespace name, as discussed.   
> and how it is not a valid namespace

Because a valid fully qualified namespace does not have `Endpoint=` in it.   Remove all but the URI.   Please see linked docs for examples and details.

**Comment by loGit123** [comment]
> > /unresolve BUT i AM USING MANAGED IDENITY then why sas is required?
> 
> It's not. You're malforming the fully qualified namespace name, as discussed.
> 
> > and how it is not a valid namespace
> 
> Because a valid fully qualified namespace does not have `Endpoint=` in it. Remove all but the URI. Please see linked docs for examples and details.

Actually I have tried that too, removing the Endpoint= and sb:// but still I got the same issue I am getting. I am not sure what else I am missing.

**Comment by jsquire** [comment]
So long as you're using the raw form, then things should be well.  At this point, I think it would be helpful if you shared a small, stand-alone app that reproduces your issue.   There's a lot of this discussion that are environmental, and I'm not sure that all of the relevant context is clear.
