### ISSUE TITLE
[QUERY] Why were index aliases removed from Azure.Search.Documents 11.6.0?

### ISSUE THREAD

**Issue by vanzegbroecke** [Azure/azure-sdk-for-net#46003]
### Library name and version

Azure.Search.Documents 11.6.0

### Query/Question

Could you please explain to me what the reasoning is behind removing index aliases from version 11.6.0? 

What is the proposed approach to rebuild an index without index aliases and without downtime?

**Comment by jsquire** [comment]
Hi @vanzegbroecke.  Thanks for reaching out and we regret that you're experiencing difficulties.   The reason that index aliases were removed for the v11.7.0 release is because they are a preview feature that is not supported in the stable version of the Azure Search service.   This is discussed in [Create an index alias in Azure AI Search](https://learn.microsoft.com/azure/search/search-how-to-alias?tabs=rest) and detailed in the REST API documentation [Aliases - Create Or Update](https://learn.microsoft.com/rest/api/searchservice/aliases/create-or-update?view=rest-searchservice-2025-08-01-preview&viewFallbackFrom=rest-searchservice-2025-09-01&preserve-view=true&tabs=HTTP)

A stable version of the client library is unable to depend on a preview version of the service.  Should the feature progress to stable and support is added to the Search service, the client library will also support it.  Likewise, should the feature continue to exist in the preview version of the Search service, the next preview release of the client library will support it.

Please be aware that our beta releases should be considered unstable and potentially disruptive changes should be expected from release-to-release.  We do not guarantee that the public API will not change in our beta releases nor are those changes considered breaking.   Our stable releases, on the other hand, do follow the [.NET Breaking Change Rules](https://github.com/dotnet/runtime/blob/main/docs/coding-guidelines/breaking-change-rules.md) per the [Azure Design Guidelines](https://azure.github.io/azure-sdk/dotnet_introduction.html#dotnet-versioning).
