### ISSUE TITLE
[FEATURE REQ] Support for Retrieving Secrets from Key Vault with Specific Secret Version

### ISSUE THREAD

**Issue by nsztyk** [Azure/azure-sdk-for-net#46196]
### Library name

Azure.Extensions.AspNetCore.Configuration.Secrets

### Please describe the feature.

Currently, when retrieving secrets from the Key Vault, there is no option to specify a particular version of a secret. 

This limitation makes it challenging to access historical versions or specific iterations of a secret when needed for rollback scenarios, auditing, or compliance purposes.

It would be highly beneficial to have the ability to pass the secret version alongside the name to retrieve the correct data

**Comment by jsquire** [comment]
Hi @nsztyk.  Thanks for reaching out and your suggestion.  As the extensions are meant to integrate with [IConfiguration](https://learn.microsoft.com/dotnet/api/microsoft.extensions.configuration.iconfiguration?view=net-8.0) which does not have the concept of versioning, I'm not sure that this request is feasible.  Given that `IConfiguration` represents settings using only a string-based key, in order to include version information, we would likely need to create some custom notation that embeds a secret name and version as the configuration item name, such as "MyThing:1234", which deviates from the standard patterns that we're integrating with.

Is there a reason that you're unable to use the KeyVault client library directly where you need versioned secrets?  Was there a specific way to pass version information that you had in mind, which I'm potentially overlooking?

**Comment by nsztyk** [comment]
Hi, @jsquire, thanks for your quick response. I understand that IConfiguration doesn't support versioning natively. However, my main goal is to specify the secret's version only at the time of retrieval from Key Vault. Once the secret is fetched, I don't need the version information anymore; I just want to use the secret value under its standard key.

For example, I'd like to specify something like MyThing@old in the Appsettings file. This way, the application can download the 'old' version of the MyThing secret from Key Vault and store it in IConfiguration under the key MyThing, without any version suffix.

Additionally, my aim is to coordinate the deployment of the application so that under the same key in IConfiguration, I can have one version of a secret, and later, by changing, for example, the Appsettings file, I can run the application using a different version of the secret.

**Comment by TripleEmcoder** [comment]
@jsquire to add to what @nsztyk wrote I'll exaplin that our team is already using a custom implementation of `KeyVaultSecretManager` to decide which secrets to load, which has access to full `SecretProperties` and can in fact filter based on the secret version (or so it seems from the signature):

```csharp
public override bool Load(SecretProperties secret)
{
   return secret.Name == "mysecret" && secret.Version == "myversoin";
}
```

We have our own way of specifying the names and versions to load, which is based on `IConfiguration` coming in from the `CreateDefaultBuilder`, and then we configure the Key Vault provider inside of `ConfigureWebHostDefaults(webBuilder => webBuilder.ConfigureAppConfiguration(...))` - but that is irrelevant, you can assume names & version are hardcoded for the purpose if this discussion, even if that seems impractical. In any case we are not looking for any new notation inside of `IConfiguration`.

The actual issue comes later, where an inconsistency seems to manifest between the `Load` method's contract and what happens next in [AzureKeyVaultConfigurationProvider.AddSecretToLoader](https://github.com/Azure/azure-sdk-for-net/blob/d4745c54329f66a6446c919702a4a0c3bbdec2e9/sdk/extensions/Azure.Extensions.AspNetCore.Configuration.Secrets/src/AzureKeyVaultConfigurationProvider.cs#L79) - after `Load` has been queried only the secret's name is passed on down the chain, and then the usual logic of getting the latest version kicks in:

```csharp
private void AddSecretToLoader(SecretProperties secret, Dictionary<string, KeyVaultSecret> oldLoadedSecrets, Dictionary<string, KeyVaultSecret> newLoadedSecrets, ParallelSecretLoader secretLoader)
{
    if (!_manager.Load(secret) || secret.Enabled != true)
    {
        return;
    }

    var secretId = secret.Name;
    ...
}
```

So you see, `bool Load(SecretProperties secret)` is a bit misleading in that in the end it actually behaves like `bool Load(string secretName)`.

What we propose is to pass the entire `SecretProperties` object down the chain and load by `Id` or pass down `Name`+`Version`.

There might be some backward compatibility issues here though - I'm not sure how to combine this with the existing version selection logic, as consumers will already depend on it. Perhaps something like `bool LoadSelectsVersions { get; }` would be needed in `KeyVaultSecretManager` to enable the new code path with `Name`+`Version`, otherwise `Version` would be left null for autoselection down the chain.

**Comment by jsquire** [comment]
Thanks for the additional context, @nsztyk and @TripleEmcoder.  Given that this library is intended to be a straight-forward extension of `IConfiguration` which lacks any concept of versioned configuration, the additional complexity that this would introduce for callers, and the non-trivial backwards compatibility impact, I don't think that this is a feature suggestion that we'll be moving forward with.   

For versioned scenarios, we would recommend using the KeyVault SDK explicitly rather than this extensions package.
