### ISSUE TITLE
[BUG]  Azure.Communication.Chat is not mockable

### ISSUE THREAD

**Issue by cmeyertons** [Azure/azure-sdk-for-net#46283]
### Library name and version

Azure.Communication.Chat 1.3.1

### Describe the bug

The Azure Communication Chat library is not mockable.

Especially for a service that I cannot emulate locally, I need to be able to mock out the interactions with it.

### Expected behavior

I would expect the library to adhere to the design guidlines for testability:

https://learn.microsoft.com/en-us/dotnet/azure/sdk/unit-testing-mocking?tabs=csharp

### Actual behavior

I cannot mock:

- `CreateChatThreadResult`
- `ChatThreadProperties`
- there's probably many more

### Reproduction Steps

n/a

**Comment by jsquire** [comment]
Hi @cmeyertons.  Thanks for reaching out and we regret that you're experiencing difficulties.   To my knowledge, the Chat library is following Azure SDK standards for mockability and testing.  As the unit testing article describes in the note from [this section](https://learn.microsoft.com/dotnet/azure/sdk/unit-testing-mocking?tabs=csharp#service-client-input-and-output-models):

> Some input models have read-only properties that are only populated when the model is returned by the service. In this case, a model factory method will be available that allows setting these properties.

The types that you're asking about fall into that category and can be created using the [ChatModelFactory](https://learn.microsoft.com/dotnet/api/azure.communication.chat.chatmodelfactory?view=azure-dotnet):

- [CreateChatThreadResult](https://learn.microsoft.com/dotnet/api/azure.communication.chat.chatmodelfactory.createchatthreadresult?view=azure-dotnet#azure-communication-chat-chatmodelfactory-createchatthreadresult(azure-communication-chat-chatthreadproperties-system-collections-generic-ienumerable((azure-communication-chat-chaterror))))
- [ChatThreadProperties](https://learn.microsoft.com/dotnet/api/azure.communication.chat.chatmodelfactory.chatthreadproperties?view=azure-dotnet#azure-communication-chat-chatmodelfactory-chatthreadproperties(system-string-system-string-system-datetimeoffset-azure-communication-communicationidentifier-system-datetimeoffset))

If there are types that are not publicly constructable and do not exist in the model factory, please let us know so that we can make the necessary adjustments.
