### ISSUE TITLE
[BUG]: Read only access for retry property in clientoptions.cs file

### ISSUE THREAD

**Issue by karthik825** [Azure/azure-sdk-for-net#46322]
### Library name and version

Azure.Core

### Describe the bug

In Client options adding we are having retry property as read only property. Adding link of the [code](https://github.com/Azure/azure-sdk-for-net/blob/bb02d72bf158045f5b0e8f0c0fa47fc9a8efdf20/sdk/core/Azure.Core/src/ClientOptions.cs#L84C1-L92C43) for reference. We are having in docs of  [retry samples](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/core/Azure.Core/samples/Configuration.md#configuring-retry-options) for changing the retry in client options. Could you please let us know whether this is a bug or not. If it is bug could you please fix it

### Expected behavior

It should be have setter and getter for Retry property in client options.

### Actual behavior

Having only getter for the retry property in the clientoptions.cs

### Reproduction Steps

please go through the [code](https://github.com/Azure/azure-sdk-for-net/blob/bb02d72bf158045f5b0e8f0c0fa47fc9a8efdf20/sdk/core/Azure.Core/src/ClientOptions.cs#L84C1-L92C43)

**Comment by jsquire** [comment]
Hi @karthik825.  Thanks for reaching out and we regret that you're experiencing difficulties.  The `Retry` property is meant to be read-only with the intent that your application mutates the existing instance of the retry policy rather than creating a new instance.   This is possible using initializer syntax, as shown in the sample that you referenced, or by directly calling members on the `Retry` instance.

For example, both of these are legal C# and update the policy in the same exact way:

**Initializer syntax**
```csharp
var options = new SecretClientOptions()
{
    Retry =
    {
        Mode = RetryMode.Fixed
    }
};
```

**Direct member references**
```csharp
var options = new SecretClientOptions();
options.Retry.Mode = RetryMode.Fixed;
```
