### ISSUE TITLE
Opt-out of sending data via userAgents

### ISSUE THREAD

**Issue by shahabhijeet** [Azure/azure-sdk-for-net#4647]
There are scenarios where Generated clients are not sending data to Azure.
We should provide a way to opt-out of setting useragent data.
Let's first come up with a design as part of this task and let's have a prototype.
The purpose of this task is to figure out how feasible is it to turn on/off and yet provide flexibility for our SDKs to individuall turn on/off.

Cost: 4

**Comment by dsgouda** [comment]
Per investigation:
- Default user agent information is calculated within the constructor of `ServiceClient`. Conditionally enabling/disabling calculation or sending this data along with request headers is therefore a very sensitive change
- While most of the user agent properties can be populated, there have been reports of `AmbiguousMatchException` being thrown from [here](https://github.com/Azure/azure-sdk-for-net/blob/psSdkJson6/src/SdkCommon/ClientRuntime/ClientRuntime/ServiceClient.cs#L172-L197). This implies that the same dlls but with different versions were loaded in the runtime.
- We did multiple tests to check if there are cases where we can run into an `AmbiguousException` due to assembly versions but could not figure out any.
- Confirmed with the .NET Runtime folks that there cannot be multiple versions of the same dll loaded into runtime. The only way forward here is to get a repro/complete stack trace details for customers before moving forward
