### ISSUE TITLE
Example of using RelayManagementClient

### ISSUE THREAD

**Issue by DavidBetteridge** [Azure/azure-sdk-for-net#4650]
Is there an example or any documentation for using the RelayManagementClient from the Microsoft.Azure.Management.Relay nuget package.

I am unsure how to initially authenticate,  I've tried passing an instance of Microsoft.Rest.BasicAuthenticationCredentials to the ctor but I only seem to get an 401 response code.

thanks

David

**Comment by DavidBetteridge** [comment]
I've got it working by creating an Application Registration in  Azure AD and then using that to create a token via the authenticationContext.AcquireTokenAsync method.

I then pass the token into the ctor of Microsoft.Rest.TokenCredential

Is this the correct way of working?

**Comment by jfggdl** [comment]
@DavidBetteridge, glad to hear that you have it working. I will close this issue.

**Comment by joaroyen** [comment]
I'm upgrading relay management code from classic service bus management library to the new relay management library. I've tried acquiring a token using `Microsoft.Azure.Relay.TokenProvider.CreateSharedAccessSignatureTokenProvider(keyName, key)` but this token is of course a SharedAccessSignature token intended for the service bus namespace endpoint.

Is there a similar library like the service bus `Microsoft.Azure.ServiceBus.Management.ManagementClient(connectionString)`that can be used to manage Azure Relay on dotnet standard?

My reason for asking is that we have legacy code that we don't want to issue certificates and create app registrations for so that we can acquire token from AAD.
