### ISSUE TITLE
[BUG] Azure database status is 'Online' when its 'Paused'

### ISSUE THREAD

**Issue by stashut** [Azure/azure-sdk-for-net#46513]
### Library name and version

Azure.ResourceManager.Sql

### Describe the bug

The core problem appears to be related to Azure Status handling. I have a database 'TestDB' set with an auto-pause delay for testing different statuses. In the SQL Databases section, the status is shown as 'Paused'

![testDB](https://github.com/user-attachments/assets/e5b799ef-f640-450d-ba18-5be7a2e545da)

However, when querying the same database in Azure Resource Graph Explorer, the status is returned as 'Online', which is also the status reflected in my application. This discrepancy indicates some inconsistencies in how the status is being reported.

![ql](https://github.com/user-attachments/assets/0ebc47c1-57bc-415e-aeaa-402f2b8847df)

after a while (like 6-8 hours) status polled as paused
P.S I created same issue before but pointed on the wrong library
 

### Expected behavior

Database status reflecting correctly with auto-pause delay

### Actual behavior

Database status does not reflect correctly with auto-pause delay, Azure Resource Graph Explorer returns status as 'Online' for a few hours when on database UI its 'Paused'

### Reproduction Steps

1.Create sql DB
2. Set auto-pause delay for 1 hour
3. wait for status to be 'Paused' on UI
4. Go to Azure Resource Graph Explorer and query for DB
5. Find properties of DB
6. Status is 'Online' instead of 'Paused'

**Comment by HarveyLink** [comment]
Hey @stashut  , thank you for reaching out to us about the Azure SDK for .NET. Unfortunately, this issue is related to the service side and not the SDK side, so we are not able to help you with it. Therefore, we are closing this issue for now. If you need more assistance, please [open an Azure support request](https://docs.microsoft.com/azure/azure-portal/supportability/how-to-create-azure-support-request). We apologize for any inconvenience this may cause you.

We value your feedback and we want to make sure that your problem is solved. If you think that we have misunderstood your issue or closed it incorrectly, please feel free to comment on this thread and reopen the issue. We will be happy to assist you further. Thank you for your understanding and cooperation.
