### ISSUE TITLE
[BUG] Cant get publishing profile when using GetPublishingProfileXmlWithSecretsAsync for functions staging slot

### ISSUE THREAD

**Issue by hawkzey** [Azure/azure-sdk-for-net#46531]
### Library name and version

Azure.ResourceManager 1.11.0

### Describe the bug

When using:

`
  var functionApp = await resourceGroup.GetWebSiteAsync(functionAppName, cancellationToken);
  functionApp.GetPublishingProfileXmlWithSecretsAsync(new CsmPublishingProfileOptions(), cancellationToken);
`
on a staging slot of azure functions app, the function app is returned but getting the publishing profile fails.

This works for the function app itself but not the staging slot:

when using the app name on its own to fetch the function app this doesn't work

If I specify slots/staging at the end of app name it fetches the slot but fails on getting publishing profile.
"appname/slots/staging";

### Expected behavior

I expect the publish Credentials to be returned as a stream response so that I can read them into GitHub like I have done for the main slot of the functions app.

### Actual behavior

an error is thrown 404 not found

### Reproduction Steps

App name being: $"appname-backend/slots/staging";

fetch the functions staging slot app using:
`var functionApp = await resourceGroup.GetWebSiteAsync(functionAppName, cancellationToken);`

and then trey get the profile from this:
`var publishCreds = await functionApp.Value.GetPublishingProfileXmlWithSecretsAsync(new CsmPublishingProfileOptions(), cancellationToken);`

### Environment

Running this locally in windows

**Comment by mcgallan** [comment]
@hawkzey Thank you for your feedback. Regarding the issue you mentioned, there is an error I need to point out. If you want to get a web app deployed in the staging slot, you cannot directly obtain it by modifying the path. Instead, you can only get it by creating the corresponding WebSiteSlotResource. This is why you encountered the 404 Not Found error, because you were using the GetWebsite method to get a WebsiteSlot. The correct code should be:
```
var lro = await collection.CreateOrUpdateAsync(WaitUntil.Completed, name, input);
var site = lro.Value;
var slotCollection = site.GetWebSiteSlots();
var slot = (await slotCollection.CreateOrUpdateAsync(WaitUntil.Completed, "staging", input)).Value;
var slotPublishCreds = await slot.GetPublishingProfileXmlWithSecretsSlotAsync(new CsmPublishingProfile());
```

Additionally, Using GetPublishingProfileXmlWithSecretsSlotAsync in WebSiteResource to get the data you need is a simple, straightforward, and correct approach. However, the failure you encountered is due to the current SDK still using JSON data handling to receive and process XML data sent from the service side. We will continue to monitor this issue and strive to resolve this problem for you as soon as possible.

**Comment by hawkzey** [comment]
> corresponding WebSiteSlotResource

I noticed this doesn't exist with the Azure.ResourceManager.AppService 1.0.0-beta.2, so i am not sure this is even possible with that version of the package. 

I will try and update to the more recent version which contains your suggestion.

**Comment by mcgallan** [comment]
> > corresponding WebSiteSlotResource
> 
> [@mcgallan](https://github.com/mcgallan)
> 
> I noticed this doesn't exist with the Azure.ResourceManager.AppService 1.0.0-beta.2, so i am not sure this is even possible with that version of the package.
> 
> I will try and update to the more recent version which contains your suggestion.

@hawkzey  Regarding my previous comment, I have additional information to supplement. The issue I mentioned about handling XML data using the JSON data processing method, after investigation, this issue only occurs in the SDK unit tests. This is due to some problems in the test base code (i.e., the code we wrote ourselves). However, in the already released SDK versions, I have tested and found that similar errors do not occur. Therefore, you only need to upgrade the AppService version to 1.1.0-beta4 or higher (latest stable version 1.3.0). I believe the issue you encountered will be resolved.
