### ISSUE TITLE
[BUG] while trying to upload xml content using HttpPipeline we are getting The XML specified is not syntactically valid.

### ISSUE THREAD

**Issue by v-rohank** [Azure/azure-sdk-for-net#46703]
### Library name and version

Azure.Core 1.44.1

### Describe the bug

We're encountering an issue with the Post Import Large File API, which is used to upload Power BI files larger than 1 GB into the service. The process involves uploading the data to a temporary location in Azure Blob Storage. However, when using the API to upload the list of blocks as XML content, we're receiving an error: `The XML specified is not syntactically valid`.
This issue occurs when using the `HttpPipeline`, but the same request (URL and XML content) works fine when using `HttpClient`.

We've noticed that similar issues have been reported on GitHub, specifically related to `Azure.Storage.Files.DataLake`. 
Here's a link to the relevant [GitHub issue](https://github.com/Azure/azure-sdk-for-net/issues/27958) (which has been acknowledged as bug)

### Expected behavior

API response should be 200

### Actual behavior

While we are trying to hit the API, we are getting 400 API response with the following error `The XML specified is not syntactically valid`

### Reproduction Steps

Step 1: Create a PowerBI file with size of 1gb and pass it as a stream in the upload file to blob function
Step 2: Hit the [Create Temporary Upload Location](https://learn.microsoft.com/en-us/rest/api/power-bi/imports/create-temporary-upload-location) for getting the temporary upload location
Step 3: Hit the upload file to blob funtion. 

Method we are using to upload file to Blob:

       private async Task UploadFileToBlobAsync(string temporaryUploadLocationUrl, Stream file, CancellationToken cancellationToken)
       {

           const int maxBlockSize = 4 * MB;

           var blockIds = new List<string>();
           var buffer = new byte[maxBlockSize];
           int i = 1;
           var clientOptions = new PowerBIClientOptions();
           var pipeline =  HttpPipelineBuilder.Build(clientOptions);
           using (var message = pipeline.CreateMessage())
           {
               var baseUploadUrl = temporaryUploadLocationUrl + "&comp=block&blockid=";
               HttpHeader headers = new HttpHeader("x-ms-blob-type", "BlockBlob");
               message.Request.Headers.Add("x-ms-version", "2015-04-05");
               do
               {
                   var plainTextBytes = System.Text.Encoding.UTF8.GetBytes("block-" + i.ToString("000000"));
                   var blockId = Convert.ToBase64String(plainTextBytes);
                   var bytesRead = await file.ReadAsync(buffer, 0, maxBlockSize);

                   var uploadBlockUrl = baseUploadUrl + blockId;
                   var content = new ByteArrayContent(buffer, 0, bytesRead);
                   message.Request.Method = RequestMethod.Put;
                   message.NetworkTimeout = TimeSpan.FromMinutes(15);
                   var uri = new RawRequestUriBuilder();
                   uri.Reset(new Uri(uploadBlockUrl));
                   message.Request.Uri = uri;
                   message.Request.Content = RequestContent.Create(content);
                   message.Request.Headers.Add(headers);
                   await pipeline.SendAsync(message, cancellationToken);
                   blockIds.Add(blockId);
                   i++;
                   if (message.Response.Status != 201)
                   {
                       throw new Exception("Error uploading file to blob");
                   }
               }
               while (file.Length - file.Position > 0);

               var tempMessage = pipeline.CreateMessage();
               var blockList = new BlockList { BlockIds = blockIds };
               XmlSerializerNamespaces xsn = new XmlSerializerNamespaces();
               xsn.Add(String.Empty, String.Empty);

               XmlSerializer serializer = new XmlSerializer(typeof(BlockList));
               UTF8StringWriter myWriter = new UTF8StringWriter();
               serializer.Serialize(myWriter, blockList, xsn);
               var requestBody = myWriter.ToString();

               HttpHeader header = new HttpHeader("x-ms-blob-content-type", "application/x-zip-compressed");
               var uploadBlocListkUrl = temporaryUploadLocationUrl + "&comp=blocklist";

               tempMessage.Request.Headers.Add(header);
               tempMessage.Request.Headers.Add("x-ms-version", "2015-04-05");
               tempMessage.Request.Content = RequestContent.Create(new StringContent(requestBody));
               tempMessage.Request.Method = RequestMethod.Put;
               var URI = new RawRequestUriBuilder();
               URI.Reset(new Uri(uploadBlocListkUrl));
               tempMessage.Request.Uri = URI;

               //we are getting issue at this step, when we are trying to upload the list of block ids as xml content through HttpPipeline
               await pipeline.SendAsync(tempMessage, cancellationToken);
           }

**Comment by ArthurMa1978** [comment]
Thank you for your feedback. This issue pertains to Azure.Core. Could you please direct it to the appropriate team member who can assist?

**Comment by jsquire** [comment]
@seanmcc-msft:  This is blocking a PowerBI release.   Would you please help route?

**Comment by amnguye** [comment]
The github issue you linked is irrelevant since it's just the same symptom however completely separate cause.

There's no evidence of any `Azure.Storage.*` package being used here. There's no issue with the storage SDK here.

If you're having issues using `HttpClient` vs `HttpPipeline` I suggest going to a different forum regarding dotnet core.

Closing due to no usage of any Azure SDK here

**Comment by amnguye** [comment]
Reopening use of `Azure.Core` library. However no use of `Azure.Storage.*` library.

**Comment by annelo-msft** [comment]
Hi @v-rohank, thank you for your inquiry.

I would like to help you with this, and will need some more information to understand and reproduce the issue you are seeing.

> We're encountering an issue with the Post Import Large File API

Would you be able to share the endpoint of this API?  Is this a blob storage REST endpoint or a PowerBI endpoint?  If you could like to both the REST API docs and share the specific URI (with any private information removed) you are sending, both of these items would be helpful to our efforts reproducing the issue.

> While we are trying to hit the API, we are getting 400 API response with the following error The XML specified is not syntactically valid

Would it be possible to share the HTTP traffic for both the request and the response?

> Step 3: Hit the upload file to blob funtion.

This step sounds to me like you are pressing a button in an application or tool.  Is that correct?  Would it be possible to share the details of what tool that is and how it interacts with Azure clients that send and receive HTTP requests and responses?

> Method we are using to upload file to Blob:

I am interested that you are using manually written code that creates its own instance of `HttpPipeline`, rather than calling a method on a client in the Azure.Storage.Blobs package.  Could you help us understand what motivated this choice?

Could you also help us understand what the method you have shared in the issue is based on?  Did you look at other code as a reference to author this function?  Otherwise, what documentation is it based on?  Could you also share a sample that illustrates the `HttpClient` code that you have reported succeeds with a 200 response?

Many thanks in advance for these details and I look forward to helping you resolve this issue.

**Comment by v-rohank** [comment]
Hi @annelo-msft, thank you for your assistance.

> > We're encountering an issue with the Post Import Large File API
>
> Would you be able to share the endpoint of this API? Is this a blob storage REST endpoint or a PowerBI endpoint? If you could like to both the REST API docs and share the specific URI (with any private information removed) you are sending, both of these items would be helpful to our efforts reproducing the issue.

After hitting the Temporary upload location API as present in the [Upload Large Function](https://github.com/microsoft/PowerBI-CSharp/blob/4ad33dd6bd49691bfe16725407ea478ca98a8acb/sdk/PowerBI.Api/Imports/ImportsOperations.cs#L294C1-L334C10), then we will be uploading the data, list of blocks to the blobs by using this [Upload file to bob function](https://github.com/microsoft/PowerBI-CSharp/blob/4ad33dd6bd49691bfe16725407ea478ca98a8acb/sdk/PowerBI.Api/Imports/ImportsOperations.cs#L336C8-L380C10)  then we will be hitting the [Imports - Post Import In Group - REST API ](https://learn.microsoft.com/en-us/rest/api/power-bi/imports/post-import-in-group#code-try-0) (where we will be giving SAS URL in the request body, this is the request URL Post  [https://api.powerbi.com/v1.0/myorg/groups/{groupId}/imports](https://api.powerbi.com/v1.0/myorg/groups/%7bgroupId%7d/imports) )

> > While we are trying to hit the API, we are getting 400 API response with the following error The XML specified is not syntactically valid
> 
> Would it be possible to share the HTTP traffic for both the request and the response?

We will be sharing the Http traffic over teams 

> > Step 3: Hit the upload file to blob function.
> 
> This step sounds to me like you are pressing a button in an application or tool. Is that correct? Would it be possible to share the details of what tool that is and how it interacts with Azure clients that send and receive HTTP requests and responses?

We are using this [Upload file to bob function](https://github.com/microsoft/PowerBI-CSharp/blob/4ad33dd6bd49691bfe16725407ea478ca98a8acb/sdk/PowerBI.Api/Imports/ImportsOperations.cs#L336C8-L380C10) for uploading the data, list of blocks to the blob, it will be called in the  [Upload Large Function](https://github.com/microsoft/PowerBI-CSharp/blob/4ad33dd6bd49691bfe16725407ea478ca98a8acb/sdk/PowerBI.Api/Imports/ImportsOperations.cs#L294C1-L334C10) as a part of the SDK not any application or tool

> > Method we are using to upload file to Blob:
> 
> I am interested that you are using manually written code that creates its own instance of `HttpPipeline`, rather than calling a method on a client in the Azure.Storage.Blobs package. Could you help us understand what motivated this choice?
> 
> Could you also help us understand what the method you have shared in the issue is based on? Did you look at other code as a reference to author this function? Otherwise, what documentation is it based on? Could you also share a sample that illustrates the `HttpClient` code that you have reported succeeds with a 200 response?
> 

Currently we are working on migrating the Power BI C# SDK from Auto Rest v2 to v3.

As a part of migration, we are migrating to HttpPipeline (which comes from the AutoRest V3 generated code).

We are creating our own HttpPipeline because we are getting the" Authentication not in correct format" with response 401 while we are trying to upload the data to the blobs using shared access signature URL (where authentication headers are getting added with the generated pipelines.)  To fix this issue, we had created new HttpPipeline .

Please refer to the [Upload Large Function](https://github.com/microsoft/PowerBI-CSharp/blob/4ad33dd6bd49691bfe16725407ea478ca98a8acb/sdk/PowerBI.Api/Imports/ImportsOperations.cs#L294C1-L334C10), where we had implemented using HttpClient and by this approach we were able to upload 1GB file to the Power BI service.

**Comment by annelo-msft** [comment]
Many thanks for these details, @v-rohank, this is just what I needed to understand the issue!

I'll provide two suggestions -- the first intended to address the specific issue you're seeing currently, and the second intended to save you some time overall in your development process.

The **first suggestion** is regarding the 400 response you are getting from the service.  I believe I have found the issue in the code sample you provided.  It results from this line:

> `tempMessage.Request.Content = RequestContent.Create(new StringContent(requestBody));`

What is happening in this line of code is that you are creating an instance of `System.Net.Http.StringContent` holding a string that is the XML content of your request.  By default, Azure.Core's `RequestContent.Create` method serializes unrecognized `object` instances to JSON.  That means that the `StringContent` object itself is being serialized into JSON bytes and then those bytes are what is written to the content of the HTTP request by the `RequestContent` instance returned from the `Create` method.

You can see this if you look closely at the request content of the HTTP request you are sending to the service.  It is the same as what you would get if you called `JsonSerializer.Serialize(new StringContent(requestBody))` -- specifically, `{"Headers":[{"Key":"Content-Type","Value":["text/plain; charset=utf-8"]}]}`.  I expect that is why the service is returning an error message saying it is unable to parse the XML document you have sent.  It is because the request content holds a JSON document that the service is unable to interpret.

I believe there is also a straightforward fix for this issue.  If I am understanding your code sample correctly, in lines of code preceding the call to `RequestContent.Create`, you have serialized to XML the runtime object corresponding to the request content you wish to send to the service.  The `requestBody` variable holds this XML document.  Since `requestBody` holds what you need, you should be able to create a `RequestContent` instance that will write this XML document to the HTTP request content, and assign this different instance to the request's `Content` property.  To achieve this, I would suggest changing the line of code above to the following:

```diff
- tempMessage.Request.Content = RequestContent.Create(new StringContent(requestBody));
+ tempMessage.Request.Content = RequestContent.Create(requestBody);
```

You can refer to the documentation for [RequestContent.Create](https://learn.microsoft.com/en-us/dotnet/api/azure.core.requestcontent.create?view=azure-dotnet) for more details of what overloads are provided for this method; since the content is already serialized, the [overload taking a string parameter](https://learn.microsoft.com/en-us/dotnet/api/azure.core.requestcontent.create?view=azure-dotnet#azure-core-requestcontent-create(system-string)) should help you succeed here.


My **second suggestion** is intended to save you time in your development process, if it is something you would consider.   It looks to me from the HTTP traffic you have shared that your overarching goal is to upload a blob to Azure blob storage using their block blobs APIs.  Specifically, this one: [Put Block List (REST API) - Azure Storage | Microsoft Learn](https://learn.microsoft.com/en-us/rest/api/storageservices/put-block-list?tabs=microsoft-entra-id).  If that is correct, then you may find that you need to write much less code to implement your own client, and potentially save time investigating and debugging issues along the way, if you use the Azure SDK Blob Storage client library -- specifically the [BlockBlobClient Class (Azure.Storage.Blobs.Specialized) - Azure for .NET Developers | Microsoft Learn](https://learn.microsoft.com/en-us/dotnet/api/azure.storage.blobs.specialized.blockblobclient?view=azure-dotnet).  My understanding is that much of the logic involved with incremental large file upload is already implemented in this client, and you should be able to leverage their implementation rather that writing you own.  If you are unable to find the documentation or samples you need to implement your specific scenarios, I am optimistic that some of the people who responded to this issue in prior comments may be able to help you understand the right patterns of calls to use to do what you intend -- including authenticating and calling the methods on the BlockBlobClient in the right order to stage and commits the blocks in your file upload.


Let me know if you have further questions about this, I am happy to help.

**Comment by v-rohank** [comment]
Hi @annelo-msft, 
 
We had implemented your first suggestion, we were able to upload the list of the blocks to the blob, then we were facing issues while we are trying to call the [Post Import API](https://learn.microsoft.com/en-us/rest/api/power-bi/imports/post-import) with the following error `Invalid File Size`.
 
So, we implemented your 2nd suggestion, it worked for us.
 
Thank you for your assistance
