### ISSUE TITLE
ServiceTagsListResult POCO has wrong field types

### ISSUE THREAD

**Issue by kennyvanle** [Azure/azure-sdk-for-net#46767]
### Type of issue

Code doesn't work

### Description

I am trying to deserialize the ServiceTagsListResult object from service tag downloadable files here: [aka.ms/servicetags](https://learn.microsoft.com/en-us/azure/virtual-network/service-tags-overview)

The POCOs listed in the documentation and in code for the ServiceTagsListResult and the child objects are listing all of the numeric fields as strings. For example:

![Image](https://github.com/user-attachments/assets/aed58f17-8168-4e72-bbf2-20718692a65a)

[source code](https://github.com/Azure/azure-sdk-for-net/blob/72d188c4fa824bc5c7e963744513036921ace7e5/sdk/network/Azure.ResourceManager.Network/src/Generated/Models/ServiceTagsListResult.cs#L76C38-L76C42)

![Image](https://github.com/user-attachments/assets/b170143c-76c0-4cf3-be27-39581a4f5cae)

This is causing an issue when deserializing the IJsonModel object using the following recommended patterns from the azure github sample [ModelReaderWriter.md](https://github.com/Azure/azure-sdk-for-net/blob/72d188c4fa824bc5c7e963744513036921ace7e5/sdk/network/Azure.ResourceManager.Network/src/Generated/Models/ServiceTagsListResult.cs#L76C38-L76C42)

![Image](https://github.com/user-attachments/assets/100444e4-56fb-43d4-9df9-4f100b42e085)

This is an issue as System.Json.Text won't allow us to convert Numbers -> String without manual converters, but the usage of JsonModelConverter causes all other converters to be ignored so we cannot use a custom converter on top of this.

My request is to update the POCOs with the proper type to match the json objects stored in the service tags.

### Page URL

https://learn.microsoft.com/en-us/dotnet/api/azure.resourcemanager.network.models.servicetagslistresult?view=azure-dotnet

### Content source URL

https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Azure.ResourceManager.Network.Models/ServiceTagsListResult.xml

### Document Version Independent Id

fdb8b0d7-0fc5-a5c2-8f88-265f19f77e38

### Article author

@azure-sdk

### Metadata

* ID: 45527980-bb82-72a6-772c-f1df8c505451 
* Service: **azure**

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by ArcturusZhang** [comment]
Hi @kennyvanle we would like to know where the issue was.
This property `string ChangeNumber` aligns with the API spec of network RP, but there is possibility that this API spec does not align with the actual traffic.
Could you attach some your code for us to reproduce the issue? And if the issue happens when you call the `GetServiceTag`, it would help even more if you could attach how the payload looks like.
To get the payload, you could either inspect the payload using something like fiddler or turn on the verbose traffic log in azure by following this: https://github.com/Azure/azure-sdk-for-net/blob/412c027f1d7ed8cb9675f506d2f863184c55dda2/sdk/core/Azure.Core/README.md#setting-up-console-logging

**Comment by kennyvanle** [comment]
@ArcturusZhang i am actually reading the data from service tag downloadable files here: [aka.ms/servicetags](https://learn.microsoft.com/en-us/azure/virtual-network/service-tags-overview) which contains the JSONs. From API response it looks okay. Seems like the issue is with whenever the file is getting published

![Image](https://github.com/user-attachments/assets/3707f95a-697d-4875-aae3-3c153237e2db)

**Comment by ArcturusZhang** [comment]
Thank you @kennyvanle . I see.
In this downloadable JSON, `changeNumber` appears to be a number, which might be incorrect.
I have tagged this issue so that the corresponding team should pay attention to.
In the meantime, I think it is no harm that we could introduce some flexibility into the deserialization so that it can handle both string and numbers.

**Comment by kennyvanle** [comment]
Thank you! Please keep me updated. Updating the deserialization to handle both would be great since there are limitations with adding custom converters.

**Comment by kennyvanle** [comment]
Hey @ArcturusZhang any update on this?
