### ISSUE TITLE
[BUG] Updating to Azure.Identity to 1.13.0 and Microsoft.Identity.Client to 4.65.0/4.66.1 fails with invalid_client 

### ISSUE THREAD

**Issue by pgrandhi** [Azure/azure-sdk-for-net#46762]
### Azure.Identity to 1.13.0 and Microsoft.Identity.Client to 4.65.0/4.66.1 

Updating to Azure.Identity to 1.13.0 and Microsoft.Identity.Client to 4.65.0/4.66.1 fails with invalid_client 

### Describe the bug

We started getting this AuthenticationFailed Exception that the client application is missing Service principal in 1P AAD tenant even though we are actually passing a different tenantId where the app is created to the TokenCredential. Not sure why it is looking for 1P AAD tenant and complaining that the Service Principal does not exist. 

Azure.Identity.AuthenticationFailedException: ClientCertificateCredential authentication failed: 
 ---> MSAL.NetCore.4.65.0.0.MsalServiceException:
	ErrorCode: invalid_client
Microsoft.Identity.Client.MsalServiceException: A configuration issue is preventing authentication - check the error message from the server for details. You can modify the configuration in the application registration portal. See https://aka.ms/msal-net-invalid-client for details.  Original exception: AADSTS7000229: The client application <appId> is missing service principal in the tenant f8cdef31-a31e-4b4a-93e4-5f571e91255a. See instructions here: https://go.microsoft.com/fwlink/?linkid=2225119 Trace ID: adbf2a0d-cf9c-4779-b8e4-5e986a530f00 Correlation ID: 70425c48-461c-4720-b354-c12eeda72c5d Timestamp: 2024-10-22 18:44:50Z
...
   at Azure.Identity.ClientCertificateCredential.GetTokenAsync(TokenRequestContext requestContext, CancellationToken cancellationToken)
	StatusCode: 401 
	ResponseBody: {"error":"invalid_client","error_description":"AADSTS7000229: The client application fe81293a-4ae8-47a7-ab18-4da55488b2bc is missing service principal in the tenant f8cdef31-a31e-4b4a-93e4-5f571e91255a. See instructions here: https://go.microsoft.com/fwlink/?linkid=2225119 Trace ID: adbf2a0d-cf9c-4779-b8e4-5e986a530f00 Correlation ID: 70425c48-461c-4720-b354-c12eeda72c5d Timestamp: 2024-10-22 18:44:50Z","error_codes":[7000229],"timestamp":"2024-10-22 18:44:50Z","trace_id":"adbf2a0d-cf9c-4779-b8e4-5e986a530f00","correlation_id":"70425c48-461c-4720-b354-c12eeda72c5d","error_uri":"https://login.microsoftonline.com/error?code=7000229"} 
	Headers: Cache-Control: no-store, no-cache
Pragma: no-cache
Strict-Transport-Security: max-age=31536000; includeSubDomains
X-Content-Type-Options: nosniff
P3P: CP="DSP CUR OTPi IND OTRi ONL FIN"
client-request-id: 70425c48-461c-4720-b354-c12eeda72c5d
x-ms-request-id: adbf2a0d-cf9c-4779-b8e4-5e986a530f00
x-ms-ests-server: 2.1.19184.6 - WEULR1 ProdSlices
x-ms-clitelem: 1,7000229,0,,
x-ms-srs: 1.P
X-XSS-Protection: 0
Set-Cookie: fpc=AruZXyKpADZGp5Fk_LL_iohhQeiFAQAAAKHpqd4OAAAA; expires=Thu, 21-Nov-2024 18:44:50 GMT; path=/; secure; HttpOnly; SameSite=None, x-ms-gateway-slice=estsfd; path=/; secure; samesite=none; httponly, stsservicecookie=estsfd; path=/; secure; samesite=none; httponly
Date: Tue, 22 Oct 2024 18:44:49 GMT

### Expected behavior

There has been no code except for nuget version updates, and it started failing with this error. The app is not in 1P tenant, but in the tenant that we are explicitly passing. We are calling 

 new CustomClientCertificateCredential(
                AppHomeTenantId,
                ApplicationId,
                Cert.X509Certificate,
                "https://management.azure.com/.default",
                new ClientCertificateCredentialOptions
                {
                    AuthorityHost = new Uri("https://login.microsoftonline.com/common"),
                    AdditionallyAllowedTenants = { "*" },
                    SendCertificateChain = true
                });

Expected behavior : successfully acquire token

### Actual behavior

AuthenticationFailed Exception

### Reproduction Steps

 new CustomClientCertificateCredential(
                AppHomeTenantId,
                ApplicationId,
                Cert.X509Certificate,
                "https://management.azure.com/.default",
                new ClientCertificateCredentialOptions
                {
                    AuthorityHost = new Uri("https://login.microsoftonline.com/common"),
                    AdditionallyAllowedTenants = { "*" },
                    SendCertificateChain = true
                });

### Environment

AAD PROD

**Comment by christothes** [comment]
Hi @pgrandhi - 
Could you share the implementation of `CustomClientCertificateCredential` ?

Also, could you reproduce this with logging enabled? 
For console output, you would just need to add the following line to your program. 

```c#
using AzureEventSourceListener listener = AzureEventSourceListener.CreateTraceLogger();
```

If you need to log the output somewhere other than the console, this can be done as described in [these docs](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/core/Azure.Core/samples/Diagnostics.md#custom-logging-callback).

**Comment by TobiasBreuer** [comment]
We are seeing a similar issue currently within an Azure DevOps pipeline.
As part of the pipeline an integration test is running which connects to AzureAppConfiguration service.
To make sure we are authenticated to read the AzureAppConfiguration resource, we perform an `az login ...` first, using a service principal dedicated for these integration tests.

Within the TestFixture, the connection to AzureAppConfiguration is authenticated using `new DefaultAzureCredential()`
With `Azure.Identity.1.12.0` this process is running fine.

After updating to `1.13.0` it is failing at `Azure.Identity.ManagedIdentityCredential.GetTokenImplAsync(Boolean async, TokenRequestContext requestContext, CancellationToken cancellationToken)` with 

> Azure.Identity.AuthenticationFailedException : ManagedIdentityCredential authentication failed: [Managed Identity] Authentication unavailable.

The issue is, we are **not using ManagedIdentity Authentication anywhere** in the devops pipeline, but rely on Azure CLI Credentials.

I assume that these mentioned breaking changes are somewhat related, but I really cannot find any EnvironmentVariable or other parameter in the pipeline that would match any of these...

> 1.13.0 (2024-10-14)
Breaking Changes
Previously, if a clientID or ResourceID was specified for Cloud Shell managed identity, which is not supported, the clientID or resourceID would be silently ignored. Now, an exception will be thrown if a clientID or resourceID is specified for Cloud Shell managed identity.
Previously, if a clientID or ResourceID was specified for Service Fabric managed identity, which is not supported, the clientID or resourceID would be silently ignored. Now, an exception will be thrown if a clientID or resourceID is specified for Service Fabric managed identity.

An alternative explanation would be that, some **other** errors in the authentication flow of `ManagedIdentityCredential` that were silently caught in the previous version, eventually leading to the factory to traverse further through the configured identity providers, **now** actually make the process fail early, and not providing the factory with the chance to continue...
