### ISSUE TITLE
[BUG]Azure.core 1.44 version depends on System.memory 4.5.4  [ Assembly version 4.0.1.2]

### ISSUE THREAD

**Issue by ektab92** [Azure/azure-sdk-for-net#46776]
### Library name and version

azure.core Version 1.44

### Describe the bug

Azure.core version 1.44 is dependent on System.memory 4.5.4 version, which is assembly version 4.0.1.1. 
However, the nuget webpage mentions a dependency on system.memory.data >=6.0.0 which depends on system.memory 4.5.5 above.

### Expected behavior

Ideally Azure.core 1.44 should depend on System.memory 4.5.5 only.

### Actual behavior

Summary 
Azure.core 1.44  depends on system.memorydata >= 6.0.0
and System.memorydata  depends on system.memory >= 4.5.5

However, azure.core is dependent on system.memory 4.5.4. I checked in ILSPY: screenshot below "
![Image](https://github.com/user-attachments/assets/cd70b68d-e9ca-4b76-938e-90d2e7eda1b8)

### Reproduction Steps

Install Azure.core 1.44 version
Use ILSPY to check references and check for system.memory version. It depends on 4.5.4 , which is not ideal

**Comment by jsquire** [comment]
Hi @ektab92.   Thanks for reaching out and we regret that you're experiencing difficulties.   Azure.Core does not have a direct dependency on any version of `System.Memory`, any dependency on that package is a transitive dependency.  As such, the version loaded by the runtime will resolve to the highest transitive reference.  Any downgrade due to ambiguous priority would result in a build warning that would fail our CI and test runs.

What I'm not clear on is what problem you're running into, so we cannot offer potential work arounds nor reproduce behavior for analysis.   Could you provide additional details to help us understand your scenario and what you're trying to overcome?

**Comment by ektab92** [comment]
Hi Azure.core team ,

I understand the issue is transitive. But looking at the references of system.memory.data in ILSPY , it is not pointing to system.memory (4.5.4)

Steps to repro  issue:-


Open Azure.Core 1.44.1 dll in Software named "ILSPY"
see the references section, and check, what is assembly version of System.memory loaded.

**Comment by ektab92** [comment]
Azure.core dll is strongly dependent on system.memory.data 6.0.0 , which strongly depends on system.memory 4.5.4.

I suspect if azure.core will have strict dependency on system.memory.data 8.0.0. above, it will resolve issue. I can get into a teams call if needed as we are internal team of MS.

**Comment by jsquire** [comment]
@ektab92 :  The Azure SDK cannot move to the 8.x line of dependencies until all of our supported host platforms - notably Azure Functions and PowerShell - no longer have compatibility issues which require us to stay locked on `System.Text.Json` 6.x.    

Can you please help us understand the end-to-end scenario of the problem that you're experiencing and whether taking a direct application reference to either `System.Memory.Data`  8.x or a higher version of `System.Memory` resolves the issue?
