### ISSUE TITLE
Azure Event Grid - Extend 3 Minute Retry

### ISSUE THREAD

**Issue by aherrick** [Azure/azure-sdk-for-net#46815]
### Library name and version

Microsoft.Azure.Functions.Worker.Extensions.EventGrid 3.4.2

### Query/Question

I have a simple Azure Event Grid Subscription that's fired when a blob container is hit. If my Azure Function doesn't respond it 3 minutes, it attempts to retry. 

So I'm in a position where my first Azure function is still running (about a 5-6 minute process) yet another transaction gets sent in. So it ends up doubling my transactions that are created.

**How can I extend the 3 minute window for the Event Grid to retry?** 

Azure Functions have a runtime of up to 10 minutes before they timeout, so there has to be a way to do this. Thanks.

**Comment by JoshLove-msft** [comment]
It doesn't appear that the retry timing is configurable based on [this service doc](https://learn.microsoft.com/en-us/azure/event-grid/delivery-and-retry). Tagging this as a service issue for confirmation.

**Comment by jsquire** [comment]
Hi @aherrick.   Based on Josh's analysis, the retry behavior that you're asking about is controlled by the Azure Functions infrastructure.   The Azure SDK extensions package has no insight nor influence into these.    Unfortunately, the Azure Functions team does not monitor this repository nor respond to issues here.  

In order to make sure that the right folks to assist have visibility, I've transferred this over to the repository where the Azure Functions .NET worker is maintained as [#2819](https://github.com/Azure/azure-functions-dotnet-worker/issues/2819).

**Comment by jsquire** [comment]
Apologies, @aherrick.   I incorrectly read this as an ask on the Functions-level retries failures when what you're actually asking about is retry behavior of the Event Grid service.   Neither the Functions infrastructure nor Azure SDK client have insight into nor influence over service behavior.   This is not something that the maintainers of the Azure SDK can assist with.   

Unfortunately, the Event Grid service team does not monitor issues in our repository nor offer support from here.  To ensure that the right team has visibility and can help, your best path forward for would be to [open an Azure support request](https://docs.microsoft.com/azure/azure-portal/supportability/how-to-create-azure-support-request) or inquire on the [Microsoft Q&A site](https://learn.microsoft.com/answers/questions/).   

Again, our apologies for the mis-classification and confusion with the initial triage.
