### ISSUE TITLE
[BUG] with TimerTrigger and library System.Memory.Data, Version=6.0.0.0

### ISSUE THREAD

**Issue by MikeP707** [Azure/azure-sdk-for-net#47396]
### Library name and version

Microsoft.Azure.Functions.Worker.Extensions.Timer 4.3.1

### Describe the bug

I created empty azure function, dotnet 9, dotnet-isolated, I tried to add timer from library Microsoft.Azure.Functions.Worker.Extensions.Timer. 
Every time that I run this function there is an error.
The listener for function 'abc' was unable to start. Azure.Core: Could not load file or assembly 'System.Memory.Data, Version=6.0.0.0, ...' the system cannot find the file specified.

When I replaced by Http trigger everything works fine.

I tried different approaches to Include library with version 6.0.0, addition of _FunctionsSkipCleanOutput, but nothing works

### Expected behavior

Function should be executed without any errors with TimerTrigger

### Actual behavior

Function throws an error after exectuin with TimerTrigger

### Reproduction Steps

Create Azure function, dotnet-isolated, .net 9, add latest libraries Microsoft.Azure.Functions.Worker.
Add TimerTrigger to example function with some code.

### Environment

.net 9
Dotnet-isolated 
Visual Studio 2022 17.12.1

**Comment by jsquire** [comment]
Hi @MikeP707.  Thanks for reaching out and we regret that you're experiencing difficulties.   I've transferred this over to the repository where the `Microsoft.Azure.Functions.Extensions.Worker` package is maintained as [#2886](https://github.com/Azure/azure-functions-dotnet-worker/issues/2886) so that the folks who maintain that package have visibility and can assist.   That'll be your best path for support, and you should consider the Functions team responding to that issue the authoritative voice.

While we're waiting for the Functions team to engage, I'll mention that there is a known incompatibility in the in-process model due to version conflicts with `System.Memory.Data` that the Functions team is aware of and working on.   To my knowledge, this should not impact the isolated model.   The most likely means that you've got a conflict with transitive dependencies.

You may want to try either including a direct reference to `System.Memory.Data` to your application and/or adding the following to hint to the Functions runtime that it shouldn't override your dependencies with the host versions:

```xml
  <ItemGroup>
    <FunctionsPreservedDependencies Include="System.Memory.Data.dll" />
  </ItemGroup>

```

**Comment by MikeP707** [comment]
I checked solution with FunctionsPreservedDependencies but this solution doesn't fix issue. I tried to combine it with _FunctionsSkipCleanOutput and still no effect.

Probably the only thing now to wait for final fix and now try to use HttpTrigger with logic app that will trigger it in scheduled way.
