### ISSUE TITLE
[BUG] empty responses throw exceptions

### ISSUE THREAD

**Issue by cataggar** [Azure/azure-sdk-for-net#47544]
### Library name and version

Azure.Core 1.44.0

### Describe the bug

Empty HTTP responses throw exceptions when using Azure.Core >= 1.44.0 with System.Memory.Data == 6.0.0 due to https://github.com/dotnet/runtime/issues/68262. It was fixed in https://github.com/dotnet/runtime/pull/68349, so System.Memory.Data >= 7.0.0 no longer has the bug. Please consider updating to System.Memory.Data >= 7.0.0

Sounds like you have a plan:
> We're currently working to bump the 6.x dependencies to 8.x, but doing so requires internal coordination to ensure we retain compatibility with the Azure Functions host and supported versions of PowerShell.
https://github.com/Azure/azure-sdk-for-net/issues/46444#issuecomment-2540144397

I understand the workaround is to update our apps ourselves to System.Memory.Data >= 7.0.0. In this [internal pull request](https://dev.azure.com/msazure/One/_git/Azure-Dedicated-AVS/pullrequest/11402245), I have to update it in a couple of dozen projects. If we miss one, we potentially have runtime exceptions in the clients.

### Expected behavior

Empty HTTP responses do not throw exceptions.

### Actual behavior

Empty HTTP responses throw exceptions.

### Reproduction Steps

The internal pull request is using Geneva Actions, so here is the unit test that reproduced it:

``` cs
        [TestMethod]
        public void LogResponseEmptyContent_Test()
        {
            // Arrange
            var mockResponse = new StubAzureResponse(content: BinaryData.Empty);

            // Act
            var logResponse = AcisOpUtils.LogResponse(mockResponse, logger);

            // Assert
            Assert.AreEqual(SuccessResult.Success, logResponse.SuccessResult);
            Assert.AreEqual(string.Empty, logResponse.Result);
        }
```

It should be pretty easy to do in the Azure.Core unit tests as well.

**Comment by cataggar** [comment]
Thsi bug was introduced in #46143. The bump to a newer System.Memory.Data is being tracked in #41941.

**Comment by jsquire** [comment]
Hi @cataggar.   Thanks for reaching out and we regret that you're experiencing difficulties.  As we discussed in #46444, we intend to update our dependencies across the Azure SDK to the 8.x range.  In order to ensure stability across platforms on which the Azure SDK runs - particularly with Azure Functions - these updates need to be coordinated with updates/deployments for the host and thoroughly tested.   

This work is tracked by #46280 (overall dependency bump) and #41941 (incorporate in code generation).   I'm going to link this issue there and close this as a duplicate.

As you noted, the mitigation in the short-term is to take a direct reference to `System.Memory.Data` in your application which will hoist the version for transitive depdencies.
