### ISSUE TITLE
Recommend path for pulling Application Insights data

### ISSUE THREAD

**Issue by alfredmyers** [Azure/azure-sdk-for-net#4785]
[Global Service Monitor](https://docs.microsoft.com/en-us/system-center/scom/gsm/how-to-configure-web-application-availability-monitoring-in-gsm?view=sc-om-1807) has been used to ping against a couple dozen URLs for a couple of years now.
The resulting data is extracted and summarized by a custom application to show periods of unavailability (start, finish, timespan) of each URL.
Now, GSM monitoring is being phased out in favor of Application Insights.

I have prototyped a working sample that pulls data directly from the REST APIs (https://api.applicationinsights.io/v1/apps/) using HttpClient.

I also have another working prototype that references [Microsoft.Azure.ApplicationInsights](https://www.nuget.org/packages/Microsoft.Azure.ApplicationInsights/) and [Microsoft.Azure.Management.ApplicationInsights](https://www.nuget.org/packages/Microsoft.Azure.Management.ApplicationInsights/), but both are in preview and haven't been updated in a while. Are these two going to move forward? If so, any estimates on when they'll RTW?

**Comment by alexeldeib** [comment]
Hi! I've been working towards a 1.0.0 (stable) release for the Microsoft.Azure.ApplicationInsights package. We plan to continue supporting the C# SDK as a way to retrieve, metrics, events, and logs. Prior to stable release, we may rename the package along the lines of Microsoft.Azure.ApplicationInsights.Query to reduce ambiguity with Microsoft.ApplicationInsights (for sending telemetry to App Insights).

I'm currently syncing up a [fairly large PR](https://github.com/Azure/azure-sdk-for-net/pull/4790) with breaking changes After that, I'd like to have a chance to start to see some usage with the new version and work out kinks. I'd expect something stable here soon -- ideally Oct '18, conservatively  Dec '18.

I can't comment on a timeline for the management plane side of things. These will likely get some love in the near-but-not-immediate future.

If I can help in other ways with the App Insights REST API, please let me know 😊

**Comment by alexeldeib** [comment]
@alfredmyers BTW -- [New package is live](https://www.nuget.org/packages/Microsoft.Azure.ApplicationInsights.Query/). I'm still working on reference info + docs for this. If you prototyped, it looks fairly similar to the existing client. Key changes:
- Metrics, Events, and Query are distinguished into their own interfaces, with method names slightly renamed to reflect this. 
    - e.g. `client.GetMetric` -> `client.Metrics.Get`
    - for metrics extension methods there is still e.g. `client.Metrics.GetMetricSummary`. This isn't consistent with the other naming, is a possible candidate for further refinement as e.g. `client.Metrics.GetSummary`
- AppId is now a parameter to methods rather than a property on the client. This makes querying more than one app easy with a single client. 
- Query results should now return values as their actual types, rather than forcing them all into strings. 
- Various parameter fixes. C# TimeSpans don't model all of our time values properly, so some are strings. Tightened and loosened validation as necessary on some other parameters (e.g., MetricId, MetricsAggregration)

If you are interested in trying this out, I'd love to get some direct feedback to shape any additional changes before 1.0.0 👍 Unfortunately until the docs are sync'd as well (in progress), I can only point to the [source ](https://github.com/Azure/azure-sdk-for-net/blob/psSdkJson6/src/SDKs/ApplicationInsights/DataPlane/ApplicationInsights/Generated/IApplicationInsightsDataClient.cs)and [tests ](https://github.com/Azure/azure-sdk-for-net/blob/psSdkJson6/src/SDKs/ApplicationInsights/DataPlane/Data.ApplicationInsights.Tests/ScenarioTests/QueryTests.cs#L33)for specific usage.

**Comment by older** [comment]
@alexeldeib Maybe [SDK documentation](https://dev.applicationinsights.io/documentation/Tools/CSharp-Sdk) should be updated as well, as it still points to the old NuGe package.
