### ISSUE TITLE
[Azure Search] .NET SDK 5.0.2 returns Int64 when retrieving Int32 index fields via DocumentSearchResult with the non-generic SearchAsync overload.

### ISSUE THREAD

**Issue by AlkisFortuneFish** [Azure/azure-sdk-for-net#4817]
Our index has some Int32 fields. We perform our searches using the non-generic version of SearchAsync. When retrieving each Document, the Int32 fields are returned as boxed Int64s. As a result, they need to be cast to Int64 and then Int32, rather than directly to Int32.

**Comment by brjohnstmsft** [comment]
@AlkisFortuneFish This is a known issue with the non-generic Search/Suggest/Get methods. It is documented in the remarks [here](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.search.idocumentsoperations.getwithhttpmessagesasync?view=azure-dotnet#Microsoft_Azure_Search_IDocumentsOperations_GetWithHttpMessagesAsync_System_String_System_Collections_Generic_IEnumerable_System_String__Microsoft_Azure_Search_Models_SearchRequestOptions_System_Collections_Generic_Dictionary_System_String_System_Collections_Generic_List_System_String___System_Threading_CancellationToken_) (which is linked to from the Search and Suggest reference documentation as well).

Fixing it in a robust way would require changes to the API to return more type information with the response. This is not on our short-term roadmap.

Since you're casting to Int32 in your application code, does this mean you know the expected types of the fields? If so, what is your reason for using `Document` and the non-generic methods instead of having a strongly-typed model and using the generic methods?

**Comment by brjohnstmsft** [comment]
@AlkisFortuneFish I don't recall offhand. We're working in this area of the SDK for other reasons and will revisit this constraint to see whether it's necessary.

Since I've answered your original question, is it alright with you if I close this issue?

**Comment by AlkisFortuneFish** [comment]
Yes, absolutely, thank you.

**Comment by brjohnstmsft** [comment]
@AlkisFortuneFish I just wanted to let you know that the next preview version of the .NET SDK will no longer have the generic type restriction. See this commit for details: https://github.com/Azure/azure-sdk-for-net/pull/5324/commits/3b172562b7a08edbd40919eb20168234f4771c6b

I expect this new SDK version to drop in the early April timeframe. The change should make it to the GA SDK about a month later.
