### ISSUE TITLE
JSON Templates support in .NET Azure Batch SDK

### ISSUE THREAD

**Issue by worldbeater** [Azure/azure-sdk-for-net#4820]
Hi folks.

Today I've realized that there is no way to use Azure Batch C# SDK with <a href="https://github.com/Azure/BatchExplorer-data/blob/master/ncj/3dsmax/standard/job.template.json">JSON templates</a>. You know, JSON format is an extremely convenient way to store and manage configuration files. So it would be nice if .NET SDK could support such templates, providing a flexible way to serialize or deserialize models.

Another thing is, that we are now unable to use several features from such templates. 
Assuming we have such a <a href="https://github.com/Azure/BatchExplorer-data/blob/master/ncj/3dsmax/standard/job.template.json#L180">configuration file</a>:
```json
"job": {
  "taskFactory": {
    "type": "parametricSweep",
    "parameterSets": [{
      "start": "[parameters('frameStart')]",
      "end": "[parameters('frameEnd')]",
      "step": 1
    }],
    "repeatTask": { ... }
  }
}
```
The `BatchServiceClient` doesn't accept any parameter named `taskFactory` or `task_factory`, but Python SDK client does. <a href="https://github.com/Azure/azure-batch-cli-extensions/blob/dd6873c64191eb7cb01fdf3f60f6198b4efccd06/samples/sdk/ffmpeg.py#L99">See here</a>, Python SDK has an `ExtendedJobParameter` that accepts a Task Factory, but .NET SDK doesn't. Why? 

I'm familiar with .NET technologies and would like to use them with Azure, but at this point it seems I'm unable to do this, Python tools and CLI extensions support features .NET SDK doesn't support. I really hope the situation could change in the future and we could use **templates** and **task factories** with .NET SDK. 

It is really unfair that Microsoft tooling for languages like Python is more feature-rich than tooling for Microsoft's own <a href="https://www.microsoft.com/net">.NET platform</a>.

Thanks in advance,
Artyom

**Comment by matthchr** [comment]
JSON template support is a feature specific to the CLIs currently precisely because complex configuration via a commandline is difficult - people often ended up writing scripts around the command lines to accomplish their job. The same problems aren't as true with code (C#, Java, etc).

There are some underlying technical reasons why it's difficult to replicate the same support in every language, but I do understand the ask as obviously even coming from C# or some other language you may want your deployments to be primarily configuration based.

Given that this would be a longer term ask likely cross-cutting across multiple SDKs (C#, Java, etc) I'm closing this and suggest you open an issue over at [The Azure Batch UserVoice](https://feedback.azure.com/forums/269742-batch)
