### ISSUE TITLE
Azure Search soft delete from Azure Storage IsDeleted flag

### ISSUE THREAD

**Issue by rozele** [Azure/azure-sdk-for-net#4879]
Azure Storage Blob service supports it's own soft-delete feature. Would it be possible to use the `IsDeleted` state from the Azure Storage blob to detect soft-delete in Azure Search, rather than a custom metadata field on a blob?

Sorry if this is not the right place to file this issue.

**Comment by brjohnstmsft** [comment]
@rozele Feel free to ask your question either on [Stack Overflow](stackoverflow.com) and tag it with "azure-search", or on the [MSDN forums](https://social.msdn.microsoft.com/forums/azure/en-US/home?forum=AzureSearch). We monitor those two sites, so if you ask your question there, an engineer will be assigned to answer it.

Since this is a product question and not an issue related to the .NET SDK, I'm going to close it.
