### ISSUE TITLE
I am wondering if you support .NET Standard 2.0

### ISSUE THREAD

**Issue by learnersm** [Azure/azure-sdk-for-net#4927]

**Comment by shahabhijeet** [comment]
@learnersm not yet.
Can you give us more information as to what is that you need from .NET Standard 2.0
this information will help us to prioritize.

**Comment by srini1978** [comment]
@shahabhijeet  - what is the .net standard that you support as of now.

**Comment by garfbradaz** [comment]
So we can build ASP.NET Core 2.0 Apps. .NET Standard 1.4 only allows 1.x Apps

https://github.com/dotnet/standard/blob/master/docs/versions.md

**Comment by shahabhijeet** [comment]
@srini1978 we currently support .NET 4.5.2 and .NET Standard 1.4 for all management plane SDKs
@garfbradaz I am sorry, I still don't follow. Can you help me understand your scenario:
1. are you saying you cannot load azure .NET SDKs inside ASP.NET Core 2.0 apps? If yes, can you describe your app setup, because I would like to reproduce this scenario and understand what is not working for you.

**Comment by MHHenriksen** [comment]
You've misunderstood. A package that targets .NET Standard 1.4 works in .NET Core apps version 1.0 **and up**, including .NET Core 2.0 and 2.1. We're using it in an Azure Functions 2.0 app, and our projects target netstandard2.0 and netcoreapp2.0. We use the Microsoft.Azure.Search.Data version 5.0.1 package without issues.

**Comment by garfbradaz** [comment]
@MHHenriksen thanks for this. Yeah I have completely read that wrong then. I've read that as if you want to target Core 2.x the minimum standard you target should be 2.0. Thanks for clarifying.

**Comment by garfbradaz** [comment]
@shahabhijeet  Thanks  matey close off.

**Comment by learnersm** [comment]
@shahabhijeet Thanks a lot!
