### ISSUE TITLE
Implement retry logic in App Authentication library

### ISSUE THREAD

**Issue by varunsh-msft** [Azure/azure-sdk-for-net#5012]
https://docs.microsoft.com/en-us/azure/active-directory/managed-identities-azure-resources/how-to-use-vm-token#retry-guidance

**Comment by AlexKeySmith** [comment]
Thanks @varunsh-msft for raising the ticket, for others reading we began the discussions from a stackoverflow post: https://stackoverflow.com/questions/53259254/transient-error-handling-for-azure-msi-authentication

It would be handy, if rather than the retry logic purely being embedded into the App Authentication Library if it can expose it for external implementation in e.g. Polly. Perhaps something as simple as exposing IsTransient() on the exception or a different exception if it's Transient.

Or even better if App Authentication library can handle the retry, as it will be in the best place to retry it properly. But allow for external code to influence it, for example if Polly is defining an overall timeout, then the MSI retry logic adheres to it - maybe simply being able to pass a CancellationToken will be enough.

Most useful would be the retry logic can expose telemetry for logging (to app insights).

**Comment by nonik0** [comment]
Hi @AlexKeySmith, we have [a new preview release](https://www.nuget.org/packages/Microsoft.Azure.Services.AppAuthentication/1.2.0-preview3) where we've implemented retry logic for our MSI access token provider. This logic follows the suggested [retry guidance in the MSI documentation](https://docs.microsoft.com/en-us/azure/active-directory/managed-identities-azure-resources/how-to-use-vm-token#retry-guidance).

At the moment we don't have the hooks to allow external influence of the retry logic, but please let us know your feedback on how we can improve.

**Comment by varunsh-msft** [comment]
Implemented logic as per Managed identity documentation.
