### ISSUE TITLE
Microsoft.Azure.KeyVault.Tests.csproj can't be built/tests on Linux

### ISSUE THREAD

**Issue by kurtzeborn** [Azure/azure-sdk-for-net#5089]
Because it depends on Windows Cryptography Next Generation (CNG) the KeyVault test project Microsoft.Azure.KeyVault.Tests.csproj can't be built or run on Linux machines.

**Comment by AlexGhiondea** [comment]
@schaabs I don't think there is anything we can do here to get this to build on Linux, right?

**Comment by schaabs** [comment]
Once we move to the target framework netstandard2.0 we will be able to fix this dependency.  Until then we'll need to just exclude tests.  However, I would expect Microsoft.Azure.KeyVault.Cryptography.Tests.csproj to be the test project which would need to be excluded since Microsoft.Azure.KeyVault.Cryptography is the package which actually depends on CNG.  Also, it's possibly that you could be even more specific because only the tests which use ECKey will rely on CNG, I would expect the rest to run without issue.

**Comment by heaths** [comment]
With the track 1 test skipping execution of CNG code (well, after letting it throw to say it isn't supported) and track 2 correctly and currently running on non-Windows platforms, I'm resolving this as fixed in track 2.
