### ISSUE TITLE
[Azure Search] Support cleaning cache for Azure Search Client

### ISSUE THREAD

**Issue by TsuyoshiUshio** [Azure/azure-sdk-for-net#5105]
My customer wants to have a feature to clear the cache of the Azure Search. 

My customer encounter the shortage of Azure Search. Azure Search had a shortage however, it successfully fail over to change the DNS. However, the client side, they cache Azure Search Client, and there is no way to clear cache.  Azure Functions recommend to make Client Static. For the standard API of the Client, we can pass the HttpClientHandler instance to the client. However not for SocketsHttpHandler which support cleaning DNS cache. 

We ended up with use refrection to inject the DNS cache configuration. This might be mandatory to support the fail over. 

This is our current work around. 

```csharp
    public class KeepAliveAvailableHttpClientHandler : HttpClientHandler
    {
        private readonly FieldInfo _fieldInfo =
            typeof(HttpClientHandler).GetField("_socketsHttpHandler", BindingFlags.NonPublic | BindingFlags.Instance);

        public KeepAliveAvailableHttpClientHandler()
        {
            var socketHttpHandler = (SocketsHttpHandler) _fieldInfo.GetValue(this);
            socketHttpHandler.PooledConnectionIdleTimeout = TimeSpan.FromMinutes(3);
            socketHttpHandler.PooledConnectionLifetime = TimeSpan.FromMinutes(1);
        }

    }
```
pass it. 
```
var handler = new KeepAliveAvailableHttpClientHandler();
indexClient = new SearchIndexClient(searchServiceName, "azuresql-index", new SearchCredentials(adminApiKey), handler , null);
 
```

For more detail, I wrote a blog about it. 

https://medium.com/@tsuyoshiushio/cleaning-dns-cache-with-azure-search-client-14cbd73d8195

**Comment by shahabhijeet** [comment]
@TsuyoshiUshio @brjohnstmsft 
If I understand the ask correctly, the ask is to provide support for SocketsHttpHandler.
And this you need to clean DNS cache or Azure Search Cache.
@brjohnstmsft if you can clarify that will be great.

**Comment by brjohnstmsft** [comment]
@shahabhijeet I believe that's the ask, yes. The purpose is to clean the DNS cache when a search service is re-created with the same name (@TsuyoshiUshio please correct me if I'm misunderstanding your scenario). This could potentially be an issue for any data plane service where the tenant name is part of the FQDN of the endpoint.

**Comment by shahabhijeet** [comment]
Assuming this particular scenario is around webApp
@TsuyoshiUshio more questions for you to ask the customers for clarification.
If what @brjohnstmsft said is correct (recreating the service client with the same name), but are they doing this in the same app pool before the app pool is recycled?

because there are at least two different (that I know of) to clear DNS
ServicePointManager.DnsRefreshTimeout = 0
and/or
request.KeepAlive = false

**Comment by TsuyoshiUshio** [comment]
He is right. The scenario of the customer is, They got two shortages of Azure Search per month. According to the Root Cause Analysis, it said that the shortage happens but recovered. However client side program can't clear the DNS cache. So the customer shortage last for several hours. Customer wanted to avoid this. The customer using Azure Functions. It requires to single ton client to access outbound request. Unless it, it will cause an exhaustion of the routing table of Scale Unit. So Azure Functions recommend to have client as static or DI.  So we need to keep on using the same Azure Search instance.  

https://docs.microsoft.com/en-us/azure/azure-functions/manage-connections#connections-limit

DnsRefreshTimeout = 0 might work, however, it'll add extra requests. And KeepAlive might against the guideline I put the link.  If I'm wrong, please give me an advice.

**Comment by shahabhijeet** [comment]
@TsuyoshiUshio I am not sure I follow on your last comment about "extra requests".
I am not asking to clear DNS cache on every requests, only when the service tries to recover from 503 scenarios. I am sure the customer has anticipated 5xx (502, 503, 504) scenarios and has recovery code added.
Also currently SocketsHandler is only available in netCoreApp2.1, adding support for such types will make the SDK shape inconsistent across other supported Target Fx.

**Comment by TsuyoshiUshio** [comment]
Hi @shahabhijeet ,
You mean, customer should clear cache when they've got 503 by themselves? One question is, can we do it for Azure Search client? The first one (System.Net.ServicePointManager.DnsRefreshTimeout = 0) seems ok. however, If I remember correctly, ServicePointManager works fine for .NetFramework and not for .NetCore (Azure Functions V2 is .NetCore). For KeepAlive, how can we set the requestObject for Azure Search SDK?

**Comment by brjohnstmsft** [comment]
@TsuyoshiUshio I am not in favor of clearing the DNS cache for all 503s in the SDK layer. There are many reasons a service might return 503. The Azure .NET SDKs have built-in retry logic that by default will retry with exponential backoff on 503. If a request fails all retries, the SDK will throw `CloudException`, which the application can handle in whatever way makes the most sense. I don't think we should bake more policy into this retry logic that may only apply to some situations for some Azure services (the infrastructure we're talking about is shared by all Azure .NET SDKs, not just Azure Search).

If we could solve this by adding an extensibility point to make the above `KeepAliveAvailableHttpClientHandler` workaround cleaner, that would make more sense, if @shahabhijeet agrees. Otherwise, I think this is something that should be solved at the application layer.

**Comment by TsuyoshiUshio** [comment]
It's ok for covering by Application layer. We need to come up with the best practice for Azure Functions. 
One of the limitation of the Azure Functions is outbound requests. They can't allow a lot of client instances of HttpClient.  The customer might need to dispose current instance once they've got 503 then create a new instance for new cache.  I just wanted to share this issue because my customer struggled this one. However there is some guidance is there, I don't care how to solve. That's fine. :)

**Comment by brjohnstmsft** [comment]
@TsuyoshiUshio In that case, I propose we close this issue. Do you agree?

**Comment by brjohnstmsft** [comment]
@TsuyoshiUshio I haven't heard from you, so I'm closing this issue. Please let me know if you have a reason to re-open it.
