### ISSUE TITLE
KeyVaultClientExtensions.GetCertificateAsync returns null for policy attribute in certificate bundle

### ISSUE THREAD

**Issue by jijohn14** [Azure/azure-sdk-for-net#5119]
GetCertificateAsync returns null for policy attribute in certificate bundle. There should be an option to fill this value vs calling separately calling GetCertificatePolicyAsync. Additionally, certificatebundle object cannot be modified to update policy attribute.

**Comment by AlexGhiondea** [comment]
[triage] Thank you for filing this issue. We have added this to our backlog.

**Comment by heaths** [comment]
With the release of Azure.Security.KeyVault.Certificates, `GetCertificate` will return a `KeyVaultCertificateWithPolicy`, which will always have a policy. The old `GetCertificate` in the description has been renamed to `GetCertificateVersion` and returns a `KeyVaultCertificate` that does not have a `Policy` property defined at all to avoid confusion. Separate calls are still required because service permissions for getting a certificate version (list) are separate from getting a certificate with policy (get).
