### ISSUE TITLE
Unable to retrieve keyvault secret using user assigned managed identity

### ISSUE THREAD

**Issue by Bunzab** [Azure/azure-sdk-for-net#5121]
I have a console app using "Microsoft.Azure.Services.AppAuthentication" Version="1.2.0-preview" and "Microsoft.Azure.KeyVault" Version="3.0.2". I have a user assigned managed identity on my Windows 2019 VM. 
The managed identity has been given the contributor role assignment on my keyvault and read to the resource group it lives in. 
I am using a user assigned managed identity as the intention is to run a similar app in a kubernetes pod (with aad-pod identity). I have a connection string environment variable set as AzureServicesAuthConnectionString RunAs=App;&lt;clientId of my user assigned MI>;TenantId=&lt;tenantId>

When I try to connect to the keyvault to retrieve a secret I get a Forbidden exception:
Unhandled Exception: System.AggregateException: One or more errors occurred. (Operation returned an invalid status code 'Forbidden') ---> Microsoft.Azure.KeyVault.Models.KeyVaultErrorException: Operation returned an invalid status code 'Forbidden'
   at Microsoft.Azure.KeyVault.KeyVaultClient.GetSecretWithHttpMessagesAsync(String vaultBaseUrl, String secretName, String secretVersion, Dictionary`2 customHeaders, CancellationToken cancellationToken)
   at Microsoft.Azure.KeyVault.KeyVaultClientExtensions.GetSecretAsync(IKeyVaultClient operations, String secretIdentifier, CancellationToken cancellationToken)
   at msiauth.AzureStuff.Run() in C:\Users\aiadmin\src\azure\msiauth\tests.cs:line 50
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at msiauth.Program.Main(String[] args) in C:\Users\aiadmin\src\azure\msiauth\Program.cs:line 10

When I try to create a Resource Group using "Microsoft.Azure.Management.ResourceManager" Version="2.0.0-preview" it works fine so the user assigned MI works for that.

I tried the exact same keyvault code but with a system assigned managed identity and it worked correctly so permissions are fine and the code works. 

Is this a known issue and is there any way to work around it for now? I do realise this is still preview but any help would be appreciated.

**Comment by franzoir** [comment]
@Bunzab did you manage to solve this issue? I'm getting almost the exact same error

**Comment by tauqirghani** [comment]
Using a very basic console program, I am getting the same error reading secrets from a keyvault that I have admin rights on.

**Comment by UmairSyed** [comment]
same here...any resolutions yet?

**Comment by schaabs** [comment]
I believe this might be an issue in AppAuthentication with user assigned identities rather than in the KeyVault library. @nonik0 are you aware of any known issues here?

@Bunzab @tauqirghani or @UmairSyed can you verify that you're user assigned identity has the desired access to the vault? If you have the Azure CLI on the VM you can authenticate with your user assigned identity with the command

~~~
az login --identity -u /subscriptions/<subscriptionId>/resourcegroups/<resourcegroup>/providers/Microsoft.ManagedIdentity/userAssignedIdentities/<userAssignedIdentityId>
~~~

Then once logged in you can try to access the keyvault secret via the command

~~~
az keyvault secret show --vault-name <vaultname> --name <secretname>
~~~

**Comment by nonik0** [comment]
@Bunzab Sorry for the delay. Have you created an access policy on that key vault for the user-assigned managed identity? If I remember correctly, you need to specifically create an access policy because just the role assignment doesn't give the needed access for the secret.

If that fails, can you take a look at the token you are getting from AppAuth (crack it open with jwt.io) and see if the token is for the correct identity?

**Comment by UmairSyed** [comment]
creating an access policy fixed my issue thanks
