### ISSUE TITLE
Please update Json.Net

### ISSUE THREAD

**Issue by curia-damiano** [Azure/azure-sdk-for-net#5205]
Please update Json.Net to the latest version, otherwise I can't remove the following warnings:
- Found conflicts between different versions of "Microsoft.CSharp" that could not be resolved.  These reference conflicts are listed in the build log when log verbosity is set to detailed.
- Found conflicts between different versions of "System.Net.Http" that could not be resolved.  These reference conflicts are listed in the build log when log verbosity is set to detailed.

My project is a sample Xamarin application (latest version, all NuGet packages updated), referencing a .Net Standard library (version 2.0.3, everything updated) that uses this SDK.

This is very incovenient, as even with .Net Standard the dll hell is not going away, like also reported here: https://github.com/Azure/azure-sdk-for-net/issues/4380

**Comment by curia-damiano** [comment]
[BingSpellChecker_Android.zip](https://github.com/Azure/azure-sdk-for-net/files/2828618/BingSpellChecker_Android.zip)

I attach the repro project showing the compilation issue

**Comment by shahabhijeet** [comment]
@curia-damiano couple of things:
I hate to link more GitHub issues for you to read, but here are few things to consider
https://github.com/dotnet/standard/issues/481
https://github.com/dotnet/cli/issues/6583

Also I will need more information to understand the issue:
1. I can't even build the project (I am sure I don't have the required components to build the project)
2. So describing what you did that makes you believe this issue belongs to .NET SDK repository and not Xamarin.
3. And finally the issue here is, you want to get rid of the warnings here, but you can still successfully build and run your app? Or am I missing to understand the issue.
Also could you clarify, what version of newtonsoft are you using

**Comment by curia-damiano** [comment]
Hi Shahabhijeet,
1. I have not written I can't build my project... it compiles but with warnings
2. The issue about the NuGet packages that references an old version of Json.Net
3. It would be enough that you update your version of Json.Net, that removes the reference to the CSharp dll, and the project would compile without warnings
Thank you!

**Comment by Petermarcu** [comment]
The Azure SDK is planning to remove references to JSON.NET in upcoming releases to avoid pinning dependencies like this. It will take time to get through all the different places where this dependency exists but over time, the pain should go away. We want people to be able to use whatever JSON.NET version they want without the Azure SDK causing problems.

You can get a glimpse of the first wave of libraries doing this here: https://azure.microsoft.com/en-in/blog/previewing-azure-sdks-following-new-azure-sdk-api-standards/
