### ISSUE TITLE
Create mechanism for supporting different TargetFrameworks for Track1 and Track2

### ISSUE THREAD

**Issue by AlexGhiondea** [Azure/azure-sdk-for-net#5214]
For now (this might change) we need to have different requirements for the TargetFrameworks for Track1 and Track2.

The current list for Track1 is `net452;netstandard1.4` and for Track2 is `net461;netstandard2.0`

The build system currently requires all the SDKs to support the same set of TargetFrameworks.

**Comment by shahabhijeet** [comment]
@AlexGhiondea 
There is a subtle difference the way you have mentioned it above, and I would say the underlying issue here like below:
The current build system will block from "Publishing" nuget pacakages that are not in the supported list of TargetFramework. This we do to maintain consistency for all azure .net SDK packages and most importantly consistency with external dependencies like Newtonsoft and ADAL.

But the build system will build any target Framework and will allow you to run test against any TargetFx, as long as that targetFx is installed on the CI machine.

For e.g. all SDKs to maintain consistency are targeted net452, net461, netstandard1.4 and netstandard2.0
If you happen to have a requirement to build against net462, you can still do it, but the package cannot be published if it's targeting .NET 4.6.2

**Comment by AlexGhiondea** [comment]
@shahabhijeet the build system that @weshaggard has put in place has a check that will ensure that you are targeting *at least* net452 and netstandard1.4. 

If you need to build a library that targets netstandard2.0 because you need to use an API that is only present in that TargetFramework, you *cannot* build the netstandard1.4 target (since the API is not there). And removing the build for netstandard1.4 trips the check we have to ensure that we have a consistent build.

This came up when I tried to port the Azure.Core package to the central repo. Because that package is a Track 2 package and because the guidelines for Track 2 are that the packages target net461 and netstandard20 I wasn't able to build the project (without a workaround). This issue is filed to make sure we have a path forward without a workaround.

**Comment by weshaggard** [comment]
Supported added with https://github.com/Azure/azure-sdk-for-net/pull/5298
