### ISSUE TITLE
When Microsoft.Azure.Management.BotService GA?

### ISSUE THREAD

**Issue by andreatosato** [Azure/azure-sdk-for-net#5321]
**Microsoft.Azure.Management.BotService** is in preview.
I can't install this component **Microsoft.Azure.Management.Fluent** with Bot SDK 

I need also this feature:
https://github.com/Azure/azure-sdk-for-net/issues/4546

Roadmap for this?

**Comment by andreatosato** [comment]
Any ARM template for bot and appid?

**Comment by kurtzeborn** [comment]
Thank you for opening this issue! We are routing it to the appropriate team for follow up.

**Comment by isra-fel** [comment]
Sorry for late response. Could you share some insights, Scott? Thanks

**Comment by sgellock** [comment]
@isra-fel, adding @swagatmishra2007 who is the engineer who can help you

**Comment by swagatmishra2007** [comment]
botservice has been GA for over 1.5 years now. My guess is that the reason the generated SDK's are showing up as in preview is because the swagger files in https://github.com/microsoft/azure-rest-api-specs/tree/master/specification/botservice/resource-manager are under a preview folder. Is that correct? If so, we should start an issue on the swagger repo side to mark the files as GA and that should fix the generated SDK's here

**Comment by isra-fel** [comment]
@akning-ms Hi Arthur, could you help @swagatmishra2007 to correct the folder structure of BotService specs? Thanks

I think after that, we can regereante and announce GA.
FYI @nickzhums

**Comment by NullMDR** [comment]
@swagatmishra2007 You can go to https://portal.azure-devex-tools.com/branch/create to create a new api-version from a preview version.

**Comment by jsquire** [comment]
@swagatmishra2007:  Can you please advise as to whether this is still an outstanding workstream or if it has been resolved?
