### ISSUE TITLE
[CS] Productize LoggingPolicy

### ISSUE THREAD

**Issue by KrzysztofCwalina** [Azure/azure-sdk-for-net#5489]
Azure.Base contains a type called LoggingPolicy. The type is a prototype. Here is some work that needs to be done:

- [ ] Should we provide ILogger style extension point
- [ ] Should we use Microsoft.Extensions.Logging for it. 
- [x] HttpPipelineEventSource needs to be made internal. It should be wrapped in a nice logging API.
- [x] It should be easy to read logs
- [x] It should be easy/automatic to integrated the logs with ASP.NET's logging system
- [x] The implementation should follow Azure logging guidelines
- [x] Test coverage
- [ ] Code samples, docs, etc.

**Comment by pakrym** [comment]
I looked around so here are some of my thoughts about the state of logging:

`LoggingPolicy` is not the greatest extensibility point for logging - Logging is a cross-cutting concern and many components would want to log somethings at different parts of the pipeline (retry policy is one obvious example). I would also argue that Transport should be the one logging sends/receives because if othen has more diagnostic information.

There are two most commonly used mechanisms for logging in .NET - structured EventSource and non-structured ILogger-style interfaces (`Action<string>` variations included). There are some advantages and disadvantages to both of them:

EventSource

*pros*
1. In BCL and doesn't require dependencies
2. Fast
3. Events are collected by profilers (perfview)
4. Easy to collect out-of-proc because of ETW transport

*cons*
0. Harder to produce - correct usage requires to define method per message kind and an EventSource class per assembly.
1. Poor integration with 3rd party logging solutions - almost no logging frameworks know how to consume and forwatd EvenSource events
2. EventSources are global singletons so it's hard to filter/route events in multi-tenant configurations
3. Hard to consume in-process without a non-trivial adapter.

ILogger and friends

*pros*
1. Easy to write non-structured data to (formatted strings with 
2. Easy integration with 3rd-party libraries using a simple adapter, same with console logging
3. As it's not usually a global sigleton ILogger can be easily integrated into multi-tenant or DI enabled applications.

*cons*
1. Not in BLC, requires a common exchange type 
2. Harder to write structured data as exchange type is often already formatted string.

There are alse EventCounters that are implemented on top of EventSource and provider a way to expose very fast counters withouth additional information.

We should set our priorities and requirements and pick how are we going to produce logs. Unfortunately there is no easy answer ASP.NET Core writes both to ILogger (uses https://github.com/aspnet/Extensions/tree/master/src/Logging/Logging.Abstractions/src as exchange library, it has good 3rd party adoption) and EventSource, BCL does only EventSource.

Honestly, it's not the first time the question of doing logging in libraries comes up and it requires an answer at .NET ecosystem level.

cc @davidfowl
