### ISSUE TITLE
Determine code style strategy for .Net

### ISSUE THREAD

**Issue by kurtzeborn** [Azure/azure-sdk-for-net#5497]
This is an investigation task for determining the strategy we will use for code style enforcement in .Net including whether we'll use linting tools and/or code editor plug-ins to enforce them. The architect for Azure SDK on .Net should be consulted.

Once a plan is made, additional issues should be created for implementation.

We already have a .editorconfig for many of the library folders.  As part of this work we should consider replacing all of those with a single common one (they are not hierarchical).

**Comment by chidozieononiwu** [comment]
# EditorConfig for Code Style Enforcement
We have settled on using EditorConfig for code style enforcement. There are two versions of .editor config currently in the repo. One in the storage service and another in Azure Core and AppConiguration. I have merged the rules from both versions into one to be able to drive consensus for use repo wide. I have highlighted places where the rules differ between the two version. Some rules are present in the storage version but not in the other, other rules are present in both but with different values, for that I have appended the storage value in front of the value in the other version e.g. `#Storage: flush_left`

As this will affect sections of the code which you own, please take a look and indicate agreement or suggestions to the rules below

## top-most EditorConfig file
root = true

## Default settings:
[*]
insert_final_newline = true
indent_style = space
indent_size = 4

## C# files
[*.cs]
`charset = utf-8-bom`

## New line preferences
csharp_new_line_before_open_brace = all # vs-default: any
csharp_new_line_before_else = true # vs-default: true
csharp_new_line_before_catch = true # vs-default: true
csharp_new_line_before_finally = true # vs-default: true
csharp_new_line_before_members_in_object_initializers = true # vs-default: true
csharp_new_line_before_members_in_anonymous_types = true # vs-default: true
csharp_new_line_between_query_expression_clauses = true # vs-default: true

## Indentation preferences
csharp_indent_block_contents = true # vs-default: true
csharp_indent_braces = false # vs-default: false
csharp_indent_case_contents = true # vs-default: true
csharp_indent_switch_labels = true # vs-default: true
`csharp_indent_labels = one_less_than_current # vs-default: one_less_than_current #Storage: flush_left`

## avoid this. unless absolutely necessary
`dotnet_style_qualification_for_field = false:suggestion # vs-default: false:none #Storage: true : warning`
`dotnet_style_qualification_for_property = false:suggestion # vs-default: false:none #Storage: true : warning`
`dotnet_style_qualification_for_method = false:suggestion # vs-default: false:none #Storage: true : warning`
`dotnet_style_qualification_for_event = false:suggestion # vs-default: false:none #Storage: true : warning`

## only use var when it's obvious what the variable type is
`csharp_style_var_for_built_in_types = false:none # vs-default: true:none #Storage: true : warning`
`csharp_style_var_when_type_is_apparent = false:none # vs-default: true:none #Storage: true : warning`
`csharp_style_var_elsewhere = false:suggestion # vs-default: true:none #Storage: true : warning`

## use language keywords instead of BCL types
`dotnet_style_predefined_type_for_locals_parameters_members = true:suggestion # vs-default: true:none #Storage: true : error`
`dotnet_style_predefined_type_for_member_access = true:suggestion # vs-default: true:none #Storage: false : error`

## Parentheses preferences
`dotnet_style_parentheses_in_arithmetic_binary_operators = always_for_clarity : suggestion`
`dotnet_style_parentheses_in_relational_binary_operators = always_for_clarity : suggestion`
`dotnet_style_parentheses_in_other_binary_operators = always_for_clarity : suggestion`
`dotnet_style_parentheses_in_other_operators = never_if_unnecessary : suggestion`


## name all constant fields using PascalCase
dotnet_naming_rule.constant_fields_should_be_pascal_case.severity = suggestion
dotnet_naming_rule.constant_fields_should_be_pascal_case.symbols = constant_fields
dotnet_naming_rule.constant_fields_should_be_pascal_case.style = pascal_case_style
dotnet_naming_symbols.constant_fields.applicable_kinds = field
`dotnet_naming_symbols.constant_fields.applicable_accessibilities = *`
dotnet_naming_symbols.constant_fields.required_modifiers = const
dotnet_naming_style.pascal_case_style.capitalization = pascal_case

## static fields should have s_ prefix
dotnet_naming_rule.static_fields_should_have_prefix.severity = suggestion
dotnet_naming_rule.static_fields_should_have_prefix.symbols = static_fields
dotnet_naming_rule.static_fields_should_have_prefix.style = static_prefix_style
dotnet_naming_symbols.static_fields.applicable_kinds = field
dotnet_naming_symbols.static_fields.required_modifiers = static
dotnet_naming_style.static_prefix_style.required_prefix = s_
dotnet_naming_style.static_prefix_style.capitalization = camel_case

## internal and private fields should be _camelCase
dotnet_naming_rule.camel_case_for_private_internal_fields.severity = suggestion
dotnet_naming_rule.camel_case_for_private_internal_fields.symbols = private_internal_fields
dotnet_naming_rule.camel_case_for_private_internal_fields.style = camel_case_underscore_style
dotnet_naming_symbols.private_internal_fields.applicable_kinds = field
dotnet_naming_symbols.private_internal_fields.applicable_accessibilities = private, internal
dotnet_naming_style.camel_case_underscore_style.required_prefix = _
dotnet_naming_style.camel_case_underscore_style.capitalization = camel_case

## Code style defaults
dotnet_sort_system_directives_first = true # vs-default: true
csharp_preserve_single_line_blocks = true # vs-default: true
`csharp_preserve_single_line_statements = false # vs-default: true #Storage: true : suggestion`

## Expression-level preferences
dotnet_style_object_initializer = true:suggestion # vs-default: true:suggestion
dotnet_style_collection_initializer = true:suggestion # vs-default: true:suggestion
dotnet_style_explicit_tuple_names = true:suggestion # vs-default: true:suggestion
dotnet_style_coalesce_expression = true:suggestion # vs-default: true:suggestion
dotnet_style_null_propagation = true:suggestion # vs-default: true:suggestion
`dotnet_style_prefer_is_null_check_over_reference_equality_method = true : suggestion`
`dotnet_style_prefer_inferred_tuple_names = true : error`
`dotnet_style_prefer_inferred_anonymous_type_member_names = true : suggestion`
`dotnet_style_prefer_auto_properties = true : suggestion`
`dotnet_style_prefer_conditional_expression_over_assignment = true : suggestion`
`dotnet_style_prefer_conditional_expression_over_return = true : suggestion`

## Expression-bodied members
`csharp_style_expression_bodied_methods = false:none # vs-default: false:none #Storage: true : suggestion`
`csharp_style_expression_bodied_constructors = false:none # vs-default: false:none #Storage: true : suggestion`
`csharp_style_expression_bodied_operators = false:none # vs-default: false:none #Storage: true : suggestion`
`csharp_style_expression_bodied_properties = true:none # vs-default: true:none #Storage: true : suggestion`
`csharp_style_expression_bodied_indexers = true:none # vs-default: true:none #Storage: true : suggestion`
`csharp_style_expression_bodied_accessors = true:none # vs-default: true:none #Storage: true : suggestion`

## Pattern matching
`csharp_style_pattern_matching_over_is_with_cast_check = true:suggestion # vs-default: true:suggestion #Storage: true : warning`
`csharp_style_pattern_matching_over_as_with_null_check = true:suggestion # vs-default: true:suggestion #Storage: true : warning`
csharp_style_inlined_variable_declaration = true:suggestion # vs-default: true:suggestion

## Expression-level preferences
`csharp_prefer_braces = true : warning`
`csharp_style_deconstructed_variable_declaration = true : suggestion`
`csharp_prefer_simple_default_expression = true : suggestion`
`csharp_style_pattern_local_over_anonymous_function = true : suggestion`

## Null checking preferences
`csharp_style_throw_expression = true:suggestion # vs-default: true:suggestion #Storage: true : warning`
csharp_style_conditional_delegate_call = true:suggestion # vs-default: true:suggestion

## Modifier preferences
`csharp_preferred_modifier_order = public,private,protected,internal,static,extern,new,virtual,abstract,sealed,override,readonly,unsafe,volatile,async : suggestion`

## Space preferences
csharp_space_after_cast = false # vs-default: false
csharp_space_after_colon_in_inheritance_clause = true # vs-default: true
csharp_space_after_comma = true # vs-default: true
csharp_space_after_dot = false # vs-default: false
csharp_space_after_keywords_in_control_flow_statements = true # vs-default: true
csharp_space_after_semicolon_in_for_statement = true # vs-default: true
csharp_space_around_binary_operators = before_and_after # vs-default: before_and_after
csharp_space_around_declaration_statements = do_not_ignore # vs-default: false
csharp_space_before_colon_in_inheritance_clause = true # vs-default: true
csharp_space_before_comma = false # vs-default: false
csharp_space_before_dot = false # vs-default: false
csharp_space_before_open_square_brackets = false # vs-default: false
csharp_space_before_semicolon_in_for_statement = false # vs-default: false
csharp_space_between_empty_square_brackets = false # vs-default: false
csharp_space_between_method_call_empty_parameter_list_parentheses = false # vs-default: false
csharp_space_between_method_call_name_and_opening_parenthesis = false # vs-default: false
csharp_space_between_method_call_parameter_list_parentheses = false # vs-default: false
csharp_space_between_method_declaration_empty_parameter_list_parentheses = false # vs-default: false
csharp_space_between_method_declaration_name_and_open_parenthesis = false # vs-default: false
csharp_space_between_method_declaration_parameter_list_parentheses = false # vs-default: false
csharp_space_between_parentheses = false # vs-default: false
csharp_space_between_square_brackets = false # vs-default: false

## Modifier preferences
`dotnet_style_require_accessibility_modifiers = for_non_interface_members:suggestion # vs-default: for_non_interface_members:none #Storage: never : suggestion`
`dotnet_style_readonly_field = true : error`

```
## Exclude Generated Code
[Generated/**.cs]
root = true
dotnet_style_predefined_type_for_locals_parameters_members = true:none
dotnet_style_predefined_type_for_member_access = true:none
dotnet_style_null_propagation = true:none
csharp_style_var_for_built_in_types = false:none
csharp_style_var_when_type_is_apparent = false:none
csharp_style_var_elsewhere = false:none
csharp_style_inlined_variable_declaration = false:none
csharp_style_expression_bodied_methods = false:none
csharp_style_expression_bodied_constructors = false:none
csharp_style_expression_bodied_operators = false:none
csharp_style_expression_bodied_properties = false:none
csharp_style_expression_bodied_indexers = false:none
csharp_style_expression_bodied_accessors = false:none
dotnet_style_object_initializer = false:none
csharp_style_throw_expression = false:none
dotnet_style_prefer_conditional_expression_over_assignment = false:none
dotnet_style_prefer_conditional_expression_over_return = false:none
dotnet_style_qualification_for_field = false:none
dotnet_style_qualification_for_property = false:none
dotnet_style_qualification_for_method = false:none
dotnet_style_qualification_for_event = false:none
```

**Comment by pakrym** [comment]
Can we unify on what was decided in https://github.com/Azure/azure-sdk-for-net/pull/5528 ? We've spent a considerable amount of time arguing and trying to get everyone to agree it would be unfortunate to open this can of worms again.

The title of the issues says "enforcement", are there any plans on how we are going to enforce these rules?

**Comment by chidozieononiwu** [comment]
> Can we unify on what was decided in #5528 ? We've spent a considerable amount of time arguing and trying to get everyone to agree it would be unfortunate to open this can of worms again.
> The title of the issues says "enforcement", are there any plans on how we are going to enforce these rules?

- Since the rules in used in the storage service .editorconfig was different I thought it will be best to provide a chance to incorporate or discard those differences rather that just changing what they have without notice.
- You are right enforcement might not be the right word here, since the rules will only updated when work is done on the code specific file.
