### ISSUE TITLE
Enable support for ADAL >= 3.14.2 in AppAuthentication

### ISSUE THREAD

**Issue by SahilSancheti** [Azure/azure-sdk-for-net#5513]
This is messing with our other projects since it has a hard dependency on 3.14.2 even though it says it should be compatible with >=3.14.2 We are using 3.19.4 and are unable to get it working.

**Comment by kurtzeborn** [comment]
Thank you for opening this issue! We are routing it to the appropriate team for follow up.

**Comment by varunsh-msft** [comment]
There is no upper limit set in the ADAL dependency. You should be able to use any ADAL version above 3.14.2 for the stable release and above 3.19.4 for the preview release of App Auth. Can you please try to upgrade the ADAL version after you install App Auth package?

**Comment by varunsh-msft** [comment]
@SahilSancheti , do you have an update on this?

**Comment by varunsh-msft** [comment]
Closing as this is a false positive.

**Comment by Zenuka** [comment]
> There is no upper limit set in the ADAL dependency. You should be able to use any ADAL version above 3.14.2 for the stable release and above 3.19.4 for the preview release of App Auth. Can you please try to upgrade the ADAL version after you install App Auth package?
Unfortunately there is an upper limit. You cannot use it with version 4.3 or higher

**Comment by varunsh-msft** [comment]
Can you please elaborate? Where is this upper limit being defined? What scenario is not working? Thanks!

**Comment by Zenuka** [comment]
Sorry, should have provided some more information. Yesterday ran into the problem that the latest version (1.0.3) doesn't work with the latest version of ADAL (4.5.1) because of breaking changes in the ADAL lib (https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/wiki/Changes-adalnet-4.0) and in particular the missing file `Microsoft.Identity.Models.Clients.ActiveDirectory.Platform.dll`. Does this clear everything up?

**Comment by varunsh-msft** [comment]
Created an issue for this. https://github.com/Azure/azure-sdk-for-net/issues/5788
