### ISSUE TITLE
[Query] Microsoft.Azure.Storage.Blob dependencies are not netstandard2.0 compatible

### ISSUE THREAD

**Issue by AgSync-Aaron** [Azure/azure-sdk-for-net#5673]
**Query/Question**
When attempting to use `Microsoft.Azure.Storage.Blob` one of the dependencies is `Microsoft.Azure.KeyVault.Core 1.0.0` but is not built for netstandard2.0. Do I need to worry about these warnings in my project?

Warning NU1701 Package 'Microsoft.Azure.KeyVault.Core 1.0.0' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETStandard,Version=v2.0'. This package may not be fully compatible with your project.	

Can `Microsoft.Azure.KeyVault.Core` please be compiled for netstandard2.0 to reduce the dependency warnings & issues?

***Why is this not a Bug or a feature Request?***
This could be an oversight (bug) or it could be a feature request (compile for netstandard2.0) but I'm just asking the question.

**Setup (please complete the following information if applicable):**
 - OS: Windows 10
 - IDE : Visual Studio 2019
 - Microsoft.Azure.Storage.Blob: v9.4.2
 - Microsoft.Azure.KeyVault.Core: v3.0.3
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [] Query Added
- [] Setup information Added

**Comment by AgSync-Aaron** [comment]
This is my project file.
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>netstandard1.3;netstandard2.0;net45</TargetFrameworks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Azure.Storage.Blob" Version="9.4.2" />
  </ItemGroup>

</Project>
```

**Comment by AgSync-Aaron** [comment]
Adding this to my csproj fixes the warning, but it doesn't feel right
```
  <ItemGroup Condition="'$(TargetFramework)' == 'netstandard2.0'">
    <PackageReference Include="Microsoft.Azure.KeyVault.Core">
      <Version>3.0.3</Version>
    </PackageReference>
  </ItemGroup>
```

**Comment by kurtzeborn** [comment]
Thank you for opening this issue! We are routing it to the appropriate team for follow up.

CC: @AlexGhiondea @schaabs @tg-msft

**Comment by schaabs** [comment]
@AgSync-Aaron  Thanks for reaching with your question.  First to answer your question about the warnings, these are benign. Microsoft.Azure.KeyVault.Core only contains two interfaces and will work on netcore or desktop.  See, https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.keyvault.core?view=azure-dotnet.  Also, while I agree that your project level fix feels 'not right' it is also benign as these interfaces haven't changed since 1.0.0.  In fact the only changes we've made to this package are in the targeted frameworks.  (This is most likely why Microsoft.Azure.Storage.Blob hasn't rev'd it's dependency on 1.0.0)

That being said I agree that this issue is confusing and causes doubt about whether the developer is doing the right thing, or whether it will work at run time, so I think we should consider reving Microsoft.Azure.Storage.Blob's dependency to a version of Microsoft.Azure.KeyVault.Core to a version which targets netstandard.

**Comment by AgSync-Aaron** [comment]
Thank you for the detailed response! That make a lot of sense.

**Comment by AgSync-Aaron** [comment]
Amazing this just came out today just a couple hours ago...
https://www.nuget.org/packages/Microsoft.Azure.Storage.Blob/10.0.0
