### ISSUE TITLE
Remove 'TestCategory!=Live' from build definition

### ISSUE THREAD

**Issue by chidozieononiwu** [Azure/azure-sdk-for-net#5767]
**Problem**
There are two steps (tasks) in the build definition that run unit tests. One for live tests and the other for non-live tests. The tests are not able on their own to determine if connection strings are present in the environment, so '--filter TestCategory!=Live' is used to filter out live tests in one of the steps.

**Solution**
The tests should detect the presence or absences of connection strings in the build environment and use that to make the run/no-run decision. That way one step can be used for all unit tests.

**Comment by weshaggard** [comment]
We could consider using an conditional fact similar to the .NET team (https://github.com/dotnet/arcade/blob/master/src/Microsoft.DotNet.XUnitExtensions/src/Attributes/ConditionalFactAttribute.cs), at least for the xunit based tests. 

What we want to avoid is requiring that people need to always pass TestCategory!=Live explicitly in order to get a passing local test run.

**Comment by kurtzeborn** [comment]
@danieljurek we should get the test guidelines updated with what should happen here generally.  Specifically that live tests check if their settings are set up before running rather than having the engineering system condition their execution.

**Comment by pakrym** [comment]
Silently skipping when there is no connection string in the environment is prone to hiding issues with tests. I would rather have tests fail loudly when things are not set up correctly than silently pass.

**Comment by weshaggard** [comment]
@jsquire I'm fine with closing this but I do still think it would be nice to have the default runs when folks run locally to not pick-up live tests. However that for your team to decide.
