### ISSUE TITLE
Upgrade App Auth library ADAL dependency to 4.X

### ISSUE THREAD

**Issue by varunsh-msft** [Azure/azure-sdk-for-net#5788]
**Is your feature request related to a problem? Please describe.**
Couple of customers have requested this. ADAL 4.X GAed over 6 months back. 

**Describe the solution you'd like**
Upgrade App Auth's ADAL dependency to 4.X.

**Comment by Zenuka** [comment]
There was already an issue for this right?
https://github.com/Azure/azure-sdk-for-net/issues/5006

**Comment by Alezis** [comment]
I have multiple projects and one of them use ADAL 4.4.1, another one use Microsoft.Azure.Management.AppService.Fluent that used Microsoft.Rest.ClientRuntime.Azure.Authentication. As result in third project has:

> NU1608: Detected package version outside of dependency constraint: Microsoft.Rest.ClientRuntime.Azure.Authentication 2.3.4 requires Microsoft.IdentityModel.Clients.ActiveDirectory (>= 3.14.0 && < 4.0.0) but version Microsoft.IdentityModel.Clients.ActiveDirectory 4.4.1 was resolved.

I vote for this issue with two hands.

**Comment by varunsh-msft** [comment]
@Alezis , this issue is for Microsoft.Azure.Services.AppAuthentication and not for Microsoft.Rest.ClientRuntime.Azure.Authentication Nuget. Can you please create a separate issue for that? Thanks!

**Comment by MattSFT** [comment]
Hey Folks,

I am facing this issue with my usage of 'Microsoft.Azure.Services.AppAuthentication'

I have these dependencies:
`Microsoft.Bot.Builder >= 4.4.3`
`Microsoft.Extensions.Configuration.AzureKeyVault >= 2.2.0`

`Microsoft.Bot.Builder` brings in `Microsoft.Bot.Connector >= 4.4.3` which in turn brings in `Microsoft.IdentityModel.Clients.ActiveDirectory >= 4.5.0`.

`Microsoft.Extensions.Configuration.AzureKeyVault` brings in `Microsoft.Azure.Services.AppAuthentication >= 1.0.1` which in turn brings in `Microsoft.IdentityModel.Clients.ActiveDirectory >= 3.19.4`

My solution ends up resolving `Microsoft.IdentityModel.Clients.ActiveDirectory` to `4.5.0` since it fulfils all the dependency requirements, however `Microsoft.IdentityModel.Clients.ActiveDirectory` had a change between `3.x` and `4.x` in that it no longer packages an additional DLL named `Microsoft.IdentityModel.Clients.ActiveDirectory.Platform`.

My application crashes when trying to configure KeyVault with this exception:
`System.IO.FileNotFoundException
  HResult=0x80070002
  Message=Could not load file or assembly 'Microsoft.IdentityModel.Clients.ActiveDirectory.Platform, Version=3.14.2.11, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.
  Source=Microsoft.Extensions.Configuration.AzureKeyVault
  StackTrace:
   at Microsoft.Extensions.Configuration.AzureKeyVaultConfigurationExtensions.<GetTokenFromClientCertificate>d__5.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)`

I made this PR to fix this: https://github.com/Azure/azure-sdk-for-net/pull/6343 However I then stumbled upon this issue which shows that something similar has been merged in and reverted for some undocumented reason.

**Comment by MattSFT** [comment]
New PR: https://github.com/Azure/azure-sdk-for-net/pull/6734

**Comment by nonik0** [comment]
Hi all, we have just released the newest [version 1.3.0 of AppAuth](https://www.nuget.org/packages/Microsoft.Azure.Services.AppAuthentication) that updates its ADAL dependency to 4.3. Please let us know if you have any issues

**Comment by jbaek080** [comment]
I have basically the same issue as @Matt: 
Also stuck on this problem, anyone taking a look?

In my case I'm trying to use Microsoft.Cloud.Metrics.Client.Metrics.MetricReader (v 2.2018.1214.1056) in a Bot Framework v4 project. The MetricReader requires Microsoft.IdentityModel.Clients.ActiveDirectory.Platform; BFv4 requires Microsoft.IdentityModel.Clients.ActiveDirectory >= v 4.5.0. But the .Platform is deprecated on .ActiveDirectory as of v >= 4.0 (not the Bot Framework version, the ActiveDirectory version.)

**Comment by nonik0** [comment]
@jbaek080 It sounds like your issue would be with the MetricReader package since it has a dependency on ADAL 3.x.

**Comment by varunsh-msft** [comment]
Closing since app auth has been upgraded to use 4.X
