### ISSUE TITLE
Investigate the removal of the InternalsVisibleTo attribute from Azure.Core

### ISSUE THREAD

**Issue by AlexGhiondea** [Azure/azure-sdk-for-net#5819]
If there is a better approach that does not require the use of InternalsVisibleToAttribute on Azure.Core we should use that.

/cc @KrzysztofCwalina

**Comment by maririos** [comment]
We are using it for both Azure.Core and Azure.ApplicationModel.Configuration

@pakrym

**Comment by pakrym** [comment]
What is the motivation?

**Comment by AlexGhiondea** [comment]
I would like to remove the use of the InternalsVisibleTo attribute from the core library.

**Comment by pakrym** [comment]
I understand, is there a reason to remove it?

We mostly use it to take components in isolation that we don't want to be exposed in public. Some examples:
1. Uri generation tests in App Config
2. We override Delay operations in retry policies to be able to deterministically tests them.

**Comment by maririos** [comment]
This will apply to other SDKs, so adding @jsquire and @tg-msft to see what their thoughts are

**Comment by jsquire** [comment]
As a general rule, I find it more helpful than a burden - which really only seems to come up in some cases when signing is involved.   As Pavel was asking, I'd also be interested in understanding the underlying motivation behind the request.

For my two cents, I'd agree that we should consider whether it is needed before using it.   For example, a couple of questions that I like to ask myself:

- Are we testing an implementation detail rather than a public interface?
- Is there value in hiding the construct or should we consider making it public?
- Are we using non-public members because our implementation hasn't considered testability in it's design?
- If we're only using a small number of non-public members, should we consider using reflection rather than asserting a friend relationship?

That said, a good, modular design based around composition often has a few levels and complexity is abstracted into a set of dependencies that our public interface makes use of.  As such, I find that it often makes sense to both keep those implementation details non-public and make use of `InternalsVisibleTo` in order to allow testing at that level.  In my opinion, this allows us to more easily isolate issues that may otherwise be difficult to uncover and remove the complexity that otherwise would be present due to the additional moving parts used by the public interface.

**Comment by tg-msft** [comment]
None of Storage libraries currently depend on `Azure.Core` internals so removing `InternalsVisibleTo` there won't affect us.  

Trying to change the pattern to no longer use `InternalsVisibleTo` anywhere would be a problem though.  In addition to testing, it's used to communicate between `Azure.Storage.Common` and the other `Azure.Storage.*` libraries.  We've received the guidance to eliminate base classes that customers won't polymorph over or derive from, so this leads to a bunch of internal static methods that we want to easily share across assembly boundaries but not expose.
