### ISSUE TITLE
Does $(RequiredTargetFrameworks) include all frameworks in $(SdkTargetFx)?

### ISSUE THREAD

**Issue by chidozieononiwu** [Azure/azure-sdk-for-net#5959]
In the process of updating the .Net Repo structure [#5213](https://github.com/Azure/azure-sdk-for-net/issues/5213) $(RequiredTargetFrameworks) is used instead of the $(SdkTargetFx) property used in some of the services.
Does  $(RequiredTargetFrameworks) include all the frameworks specified in $(SdkTargetFx) _i.e. net452;net461;netstandard1.4;netstandard2.0_

The build process doesn't break. But we need to make sure its building for all the required frameworks.

**Comment by weshaggard** [comment]
@shahabhijeet It looks like a couple months ago you added net461 and netstandard2.0 to SdkTargetFx with PR https://github.com/Azure/azure-sdk-for-net/pull/5204. I know you want that for all the management plane libraries but for the data-plane libraries that were already in this repo should they also have those additional target frameworks?

@AlexGhiondea I guess this is a question for you as well.

**Comment by AlexGhiondea** [comment]
This would add more assets into the data plane packages for the additional frameworks, right? 

I am also wondering if the resolution rules for the packages during restore will change because there are now more assets. But it might end up not being a real issue.

I wouldn’t add more framework versions to the package right now.

@shahabhijeet

**Comment by weshaggard** [comment]
@shahabhijeet @AlexGhiondea We should make a decision about this pretty soon. I just double checked the eventgrid package we released today and this showed up in the diff. The 3.0.0 package had net452 and netstandard14, and the 3.1.0 package had net461, net452, netstandard2.0, netstandard1.4, but because of the move the 3.2.0 package again only had the net452 and netstandard1.4 build. I don't expect this to really cause any issue beyond perhaps some extra package dependencies but it is something we should fix sooner rather then later.

**Comment by weshaggard** [comment]
@shahabhijeet and I chatted about this and we think we should add net461 and netstandard2.0 to the list of target frameworks that the track 1 data-plane libraries target.
