### ISSUE TITLE
Repo SDK folder subfolders should be cased as the service names are cased

### ISSUE THREAD

**Issue by KrzysztofCwalina** [Azure/azure-sdk-for-net#6093]
The SDK folder (https://github.com/Azure/azure-sdk-for-net/tree/master/sdk) contains subfolders such as "eventhub", "keyvault", etc. 

The folders should use PascalCasing, just like the names of the packages, i.e. "EventHub", "KeyVault" etc. 

Also, the feature is called "Event Hubs" not "Event Hub"

Lastly, the folders should correspond to package/namespace names, e.g. Azure.Identity.KeyValue.

**Comment by weshaggard** [comment]
The currently approved guidelines are at https://github.com/Azure/azure-sdk/blob/master/docs/engineering-system/repo-structure.md and the reason the the service names are like such is because that is how they currently are in the api specs repo (https://github.com/Azure/azure-rest-api-specs/tree/master/specification). We are trying to make those consistent across all languages thus the first 2 directories, `sdk\<service name>`, should be consistent across all languages and specs, and in general they are lowercase because that tends to be better for cross-platform development and they are just names and not matching any shipping artifacts. 

As for the package folder it is intended that they have the exact name of the shipping package so that will be language specific and should already be that way and if there are any that aren't we should align them. 

For the specific eventhub vs eventhubs we went for consistency with the specs repo as well as we have generally used singular for the service name as opposed to plural. Although I agree there is definitely some inconsistency about it across documentation as well as the portal (for example it is called keyvault in the docs but keyvaults in the portal).

**Comment by kurtzeborn** [comment]
We've talked about this and we're going to move forward with the current plan.  We may change some of the names as we get feedback.
