### ISSUE TITLE
Is old ServiceBus SDK (WindowsAzure.ServiceBus) Open source ?

### ISSUE THREAD

**Issue by cortex93** [Azure/azure-sdk-for-net#6329]
Hello,

Is the old SDK (WindowsAzure.ServiceBus) with support for on prem azure service open sourced ? I wanted to move my app to netcoreapp but it has dependency on .net452 and this new SDK was never meant to support on prem (and I don't request for that).
If the old SDK was open sourced, I may be able to remove .net452 dependencies.

**Comment by kurtzeborn** [comment]
Thank you for opening this issue! We are routing it to the appropriate team for follow up.

**Comment by SeanFeldman** [comment]
@cortex93 no.
Also the Service Bus for Windows Server is out of support. See details [here](https://azure.microsoft.com/en-us/blog/collaboration-and-federation-azure-service-bus-messaging-on-premises-futures/).

If you wish to move to .NET Core, you'll need to use the new Service Bus client and switch to Azure Service Bus.

**Comment by jfggdl** [comment]
@cortex93 , as Sean mentioned, Service Bus for Windows is out of support and it is not open sourced. 
By the way, I am part of the messaging team in Azure that is responsible for Service Bus, Event Hubs, Event Grid, and Relay. I see that this issue was created last year, but if you are still interested, I can have a phone/Teams conversation with you on potential options and to understand your on-prem scenario. Please let me know.

**Comment by cortex93** [comment]
@jfggdl My on-prem scenario also involved Biztalk with the SB-Messaging Adapter which is based on this now unsupported library while Biztalk and its adapter are still supported...
Unfortunately, Azure is not an option. If it has ever been, we would never have chosen the on-prem solution. And if Microsoft has been clearer about SB for Windows roadmap, we would have chosen an other product from the ground start. Since then, we moved to an other on-prem messaging bus.
I'm closing this issue as I guess, solution for others in our situation is to either move to Azure SB or to change for another SB product. Thanks for your proposal.
