### ISSUE TITLE
Expose the Batch File Conventions storage path for a task

### ISSUE THREAD

**Issue by jeffw-wherethebitsroam** [Azure/azure-sdk-for-net#6542]
**Is your feature request related to a problem? Please describe.**
I want to use Batch File Conventions for uploading the log files for my task. The code for scheduling the task is in C#, however, the task itself is not. I want to upload the files after the task has completed using CloudTask.OutputFiles.

I can get a signed URL for the container using CloudTask.GetOutputStorageContainerUrl, however there appears to be no way to obtain the path within that container using the Batch File Conventions library. So I end up having to do this:

```
           var logContainerUrl = batchJob.GetOutputStorageContainerUrl(_linkedStorageAccount);
            var cloudTask = new CloudTask(taskId, cmd)
            {
                OutputFiles = new List<OutputFile>
                {
                    // upload the stderr.txt and stdout.txt
                    new OutputFile(
                        filePattern: @"../std*.txt",
                        destination: new OutputFileDestination(
                            new OutputFileBlobContainerDestination(
                                containerUrl: logContainerUrl,
                                // ffs. The conventions library doesn't provide a method to get this path
                                path: $"{taskId}/${TaskOutputKind.TaskLog.ToString()}/"
                            )
                        ),
                        uploadOptions: new OutputFileUploadOptions(
                            uploadCondition: OutputFileUploadCondition.TaskCompletion
                        )
                    ),
               }
          };
```

**Describe the solution you'd like**
A method on CloudTask to give the output path based on a TaskOutputKind.

i.e. `task.GetOutputStoragePath(TaskOutputKind.TaskLog)

**Describe alternatives you've considered**
I looked for methods on CloudTask and TaskOutputStorage. I ended up looking at the code.

**Additional context**
nothing else

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x ] Description Added
- [x ] Expected solution specified

**Comment by kurtzeborn** [comment]
Thank you for opening this issue! We are routing it to the appropriate team for follow up.

**Comment by matthchr** [comment]
Hey @jeffw-wherethebitsroam - when we initially wrote the file conventions library our goal was to abstract away the actual mechanics behind where the files were going. Basically the idea being that the file conventions library would implement the [file conventions](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/batch/Microsoft.Azure.Batch.Conventions.Files/README.md) which would then be understood by the SDK and the portal - with the goal being that you as a customer didn't have to worry about the specific mechanics of where task files were going in storage.

When we released `OutputFiles` in the service this changed a bit though, as obviously you need to understand the conventions if you're going to use `OutputFiles` to emit logs following them.

I think you really have two asks here (correct me if I am wrong):
1. (You didn't explicitly ask this) The Batch service should support file conventions as part of `OutputFiles` natively. This would probably take the form of a new `destination` kind rather than `OutputFileBlobContainerDestination` - possibly a `OutputFileBlobFileConventionsDestination` where you provided the container URL and the `kind`.
2. (What you actually asked for) Exposing more details about what storage layout(s) would be chosen for a given task based on `kind`.

Item 1 we are already tracking internally.
Item 2 we can do - we have such a method internally but it's not exposed publicly. We can do this alongside our next REST API release which is coming in ~1 month (or less).
