### ISSUE TITLE
Generate/publish reference docs on github.io

### ISSUE THREAD

**Issue by kurtzeborn** [Azure/azure-sdk-for-net#6581]
We need to generate and publish reference docs to github.io.  The goal of this task is to set up a pipeline similar to the one we have for python which runs the tools to generate the HTML documentation and then publishes it all to github.io.  Please work with @scbedd when setting up the pipeline.  @AlexGhiondea and @weshaggard will know the proper way to generate the documentation pages from the code.

**Comment by scbedd** [comment]
Ok so the goal here is create a build that generates documentation html so that we can publish to github.io. Here is an [example github io site.](https://azure.github.io/azure-sdk-for-python)

We have already locked down how to publish to github.io, all you need to do is create a build that generates the HTML for it.

We have one example live for this. It is powered by this [yaml.](https://github.com/Azure/azure-sdk-for-python/blob/master/.azure-pipelines/docs.yml) 

That YML is hooked up to an `internal only` build that triggers on checkin to `master`. (Read: CI only, no PR)
