### ISSUE TITLE
[BUG] Missing StartWithHttpMessagesAsync in released ContainerInstance package

### ISSUE THREAD

**Issue by nrandell** [Azure/azure-sdk-for-net#6616]
**Describe the bug**
The IContainerGroupsOperations in the published nuget package (2.0.0) doesn't have StartWithHttpMessagesAsync

**Expected behavior**
All the available operations should be present

**Setup (please complete the following information):**
 - OS: Windows 10
 - IDE : Visual Studio 2019
nuget 2.0.0

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ x ] Bug Description Added
- [ n/a ] Repro Steps Added
- [ x ] Setup information Added

**Comment by praries880** [comment]
Thank you for opening this issue! We are routing it to the appropriate team for follow up.

@shahabhijeet, can you kindly take a look at this?

**Comment by nrandell** [comment]
If you look at the rest api definition there is a start container api but the library does not reference it. I think it's a simple case of just regenerating this library against the complete api definition. (From memory as it was a few weeks ago I raised this)

**Comment by erich-wang** [comment]
@samkreter,  please regenerate source code from swagger spec for containerinstance since StartWithHttpMessagesAsync was missed in nuget package 2.0.0? The process is available at https://github.com/Azure/adx-documentation-pr/blob/master/engineering/adx_netsdk_process.md#sdk-generation-from-updated-spec

**Comment by erich-wang** [comment]
@samkreter, any update?

**Comment by erenes** [comment]
I am currently running into this issue and thought maybe I could follow the process myself, since it does not seem complicated. Unfortunately it appears that the link is either dead or I do not have access. 

@erich-wang is there a public url where I can see the process so that I may submit a pull request?

**Comment by erich-wang** [comment]
Close the issue as new package was released two months ago at https://www.nuget.org/packages/Microsoft.Azure.Management.ContainerInstance/3.0.0.
