### ISSUE TITLE
[FEATURE REQ] Decoupling AzureCredentials from Authenticated by IAzureCredentials

### ISSUE THREAD

**Issue by qub1n** [Azure/azure-sdk-for-net#6730]
**Is your feature request related to a problem? Please describe.**

We have an application that accesses Azure in parallel, but Azure SDK is not threadsafe. We cannot change it to the single-threaded application, because of

1.  performance, it would be too slow.
2. Moving the locks to the business logic would be difficult to maintain.
3.  in some cases some regions and environments need to be independent. Timeouts (unavailability) of one region should not block access to another region.

**Describe the solution you'd like**
 I suggest:

1. Decoupling AzureCredentials from Authenticated.Authenticate method. It would be better if there is an interface IAzureCredentials, so I can pass my own threadsafe object instead. The current design breaks the Liskov Substitution principle because I cannot replace AzureCredentials by anything else.

2. Change members of AzureCredentials to protected instead of private, so I can implement my own threadsafe version of ProcessHttpRequestAsync method.

**Describe alternatives you've considered**
Theoretically, we could create a new Azure object with its own credentials for every thread, but it would be very difficult to maintain because some function is just retrieving the IAzure interface and works in parallel. Furthermore to authenticate before every call would be overkill and performance issue.
I noticed that some decoupling was already made inversion 1.9, see https://github.com/Azure/azure-libraries-for-net/pull/195, but it will probably not solve my problem, because injected RestClient is again coupled to the AzureCredentials. So it would be also nice if RestClient depends on IAzureCredentials instead.

**Additional context**
Our application is heavily asynchronous (async await everywhere) and runs in parallel. It is very difficult to track the thread context.

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ X] Description Added
- [ X] Expected solution specified

**Comment by maggiepint** [comment]
Hi,

Thank you - this is good feedback. We are currently working on a revamp of our client library [design guidelines](/Azure/Azure-sdk). This issue is definitely something we could look at incorporating into those.

What service's library are you using here? It would help me to be able to have a look at the exact code in question.

Thanks,
Maggie

cc @KrzysztofCwalina

**Comment by Petermarcu** [comment]
@schaabs for his thoughts on this. In our new wave of libraries we are doing auth/identity differently.

**Comment by schaabs** [comment]
@qub1n I believe this issue is referencing the [AzureCredentials](https://github.com/Azure/azure-libraries-for-net/blob/master/src/ResourceManagement/ResourceManager/Authentication/AzureCredentials.cs) class from the c# fluent library https://github.com/Azure/azure-libraries-for-net.  If that's the case this issue should probably be moved to that repo.

**Comment by qub1n** [comment]
@schaabs What is "a new  wave of libraries"? Is there any other recommended library I should used instead?

**Comment by Petermarcu** [comment]
@schaabs is this addressed in Azure.Identity? Either way, can this be closed as it looks like a tracking issue was opened in the fluent repo?

**Comment by schaabs** [comment]
Apologies, @qub1n I missed your reply to this issue. The Azure.Identity library which @Petermarcu mentioned is an authentication library designed to be used with the latest generation of the Azure SDK. Information about the Azure.Identity library can be found [here](https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/identity/Azure.Identity). Also a list of libraries which can authenticate with the credential types defined in Azure.Identity can be found [here](https://azure.github.io/azure-sdk/releases/latest/#net) and they are all published on nuget as Azure.* packages.

I'd encourage you to try out our latest libraries to see if they meet your needs, and please open issues for any questions or issues you encounter. I'm closing this issue since it's concerning classes not defined in this repo.
