### ISSUE TITLE
Calling GetSecrets on KeyVault with no secrets should not throw an exception.

### ISSUE THREAD

**Issue by mitchdenny** [Azure/azure-sdk-for-net#6758]
**Describe the bug**
Using the ```SecretClient.GetSecrets(...)``` from the ```Azure.Security.KeyVault.Secrets@4.0.0-preview.1``` library throws an exception when trying to list the secrets in an empty vault. This should be a bug since an empty vault is a completely valid state. It should instead return an empty enumeration.

***Exception or Stack Trace***
Add the exception log and stack trace if available

```
System.InvalidOperationException
  HResult=0x80131509
  Message=The requested operation requires an element of type 'Array', but the target element has type 'Null'.
  Source=System.Text.Json
  StackTrace:
   at System.Text.Json.JsonDocument.GetArrayLength(Int32 index)
   at Azure.Security.KeyVault.Secrets.Page`1.ReadProperties(JsonElement json)
   at Azure.Security.KeyVault.Secrets.Model.Deserialize(Stream content)
   at Azure.Security.KeyVault.Secrets.SecretClient.GetPage[T](Uri firstPageUri, String nextLink, Func`1 itemFactory, CancellationToken cancellationToken)
   at Azure.Security.KeyVault.Secrets.SecretClient.<>c__DisplayClass13_0.<GetSecrets>b__0(String nextLink)
   at Azure.Core.PageResponseEnumerator.<CreateEnumerable>d__0`1.MoveNext()
   at KeyVaultNetCore.Program.Main(String[] args) in C:\Code\KeyVaultNetCore\src\KeyVaultNetCore\Program.cs:line 22
```

**To Reproduce**

1. Setup an empty keyvault.
2. Setup an AAD application.
3. Grant AAD application access to the KeyVault.
4. Run the code below.

***Code Snippet***
Add the code snippet that causes the issue.

```
var credential = new ClientSecretCredential(
  "<tenant id>",
  "<aad app client id>",
  "<add app secret>"
  );

var client = new SecretClient(
  vaultUri: new Uri("https://midenn-keyvault.vault.azure.net/"),
  credential: credential
  );

var secrets = client.GetSecrets();

foreach (var secret in secrets)
{
  var theActualSecret = client.Get(secret.Value.Name);
  Console.WriteLine($"{secret.Value.Name}: {theActualSecret.Value.Value}");
}
```
**Expected behavior**
I would expect an empty enumeration to be returned resulting in no output, but not an exception.

**Screenshots**

**Setup (please complete the following information):**
 - OS: [e.g. iOS] Windows
 - IDE : [e.g. IntelliJ] Visual Studio 2019
 - Version of the Library used: Azure.Security.KeyVault.Secrets@4.0.0-preview.1

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x ] Bug Description Added
- [x ] Repro Steps Added
- [x ] Setup information Added

**Comment by maririos** [comment]
After looking at the issue, the problem only happens when the vault is new and it has never had a secret stored on it. If the vault had secrets and now they are all deleted, we don't fail.

The  problem is caused when we are deserializing the json payload in [here](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/keyvault/Azure.Security.KeyVault.Secrets/src/Page.cs#L40) as we are expecting an array with content, but the server is sending null.

Note that this looks more like a server error. 
- New Vault server returns : `{{"value":null,"nextLink":null}}`
- Old empty vault returns: `{{"value":[],"nextLink":null}}`

@AlexGhiondea and @schaabs we could always make our code more robust, although we should communicate this with the service team as a possible bug for them to fix and leave our code as it is.

Lastly, I don't consider this urgent enough to do a re-release KV, but open to other views.

**Comment by schaabs** [comment]
The deserialization should handle the value being null and treat it the same as empty.  And it is also possible that  null or empty list is returned and a next link is specified.  This must be handled as well.

**Comment by maririos** [comment]
Sure, we can always do that. For preview 2 right?

Do you know who from the service team I can contact about this too? I want to see their thoughts on the subject.

**Comment by maririos** [comment]
Changed merged.
