### ISSUE TITLE
[QUERY] dependencies versions

### ISSUE THREAD

**Issue by SeanFeldman** [Azure/azure-sdk-for-net#6858]
**Query/Question**

When client libraries are released they indicate what version of dependencies should be used. Those dependencies and their versions have been clearly tested and verified.
Looking at the Azure Service Bus client, it appears version ranges for dependency libraries have been removed, removing information what version of the dependencies was verified.

For example, ASB client takes a dependency on the [Microsoft AMQP library](https://github.com/Azure/azure-amqp/). The AMQP library has a new patch released, 2.4.3, but has this patch been verified to work with the ASB client? There's no way to know that since any version of the AMQP library is [permitted](https://github.com/Azure/azure-sdk-for-net/blob/a4d63568466cfc569ec67d595cb8ba52068f7259/sdk/servicebus/Microsoft.Azure.ServiceBus/src/Microsoft.Azure.ServiceBus.csproj#L39).

Could you please elaborate on the reasons this change was made and how to avoid surprises when an untested dependency is used with the client. Thank you.

**Comment by maggiepint** [comment]
Hi Sean!

As always, thanks for the feedback. Perhaps @AlexGhiondea or @jfggdl can chip in?

**Comment by AlexGhiondea** [comment]
@jsquire do you recall anything around this from when we moved the code over?

**Comment by SeanFeldman** [comment]
@AlexGhiondea this is what the original code contained: [Microsoft.Azure.ServiceBus.csproj](https://github.com/Azure/azure-service-bus-dotnet/blob/1607601d3d3c6cf7e0c2a757ccb398d803482e7c/src/Microsoft.Azure.ServiceBus/Microsoft.Azure.ServiceBus.csproj#L30-L34).

**Comment by jsquire** [comment]
This isn't quite what it seems on the surface; each package reference is still locked to an approved version or range of versions, they are just not defined inline in the project file.

This was a recent effort by our engineering team to centralize dependency versions across all libraries in the repository.   Each project contains only a reference to the package that it would like and the versions are controlled upstream by a linked set of package properties, found in [/eng/Packages.Data.props](https://github.com/Azure/azure-sdk-for-net/blob/master/eng/Packages.Data.props).  If I'm being frank, I'm surprised that they made this change across the existing client libraries rather than isolating it to the track two versions.

I'm only a consumer of the engineering system;  Unfortunately, I lack insight into how each version was chosen during the centralization as well as how the versions are managed and validated.  @AlexGhiondea:  I'm not sure who the right person would be to pull into the conversation who may be able to shed light there.

**Comment by maggiepint** [comment]
I would start with @bsiegel

**Comment by AlexGhiondea** [comment]
Adding @weshaggard as well

**Comment by bsiegel** [comment]
The vast majority of the dependency version ranges were consistent across packages, those were just copied directly into the Packages.Data.props file.

The next set of dependencies differed by only a patch or minor version. Each time I aligned these dependencies I read the full release notes of the dependency and often looked at the source changes to make sure that the update was in fact compatible. The automated testing as well as integration testing is in place to verify that these dependencies work.

The final set of dependencies were very few - these are the ones that differed by major version. For these, I put the most common one inside Packages.Data.props. For all others, I applied a `VersionOverride="<version range>"` property to the `<PackageReference>` so that they would continue to use their preferred version of the dependency.

The largest change made here is that we have bumped some packages to a new minor version, and we have a test pipeline to validate these changes, so we felt relatively safe in applying these changes to all data plane packages (as has been done in our other language repos).

**Comment by weshaggard** [comment]
>When client libraries are released they indicate what version of dependencies should be used. Those dependencies and their versions have been clearly tested and verified.
Looking at the Azure Service Bus client, it appears version ranges for dependency libraries have been removed, removing information what version of the dependencies was verified.

@SeanFeldman I think there are some incorrect assumptions here. Even if a library has a package dependency range it doesn't necessary imply it was tested\verified with all the packages in that range. Setting up a testing system to handle that would be very costly and have little benefit. Generally version ranges are used in a package dependency to tell nuget that we can only work with packages in a given range and we only do that when we know there are known breaking changes in some set of versions that will cause our library to break. 

Ultimately there is a lot of reliance on people not introducing breaking changes when new package versions are release, especially if they only increment the patch or minor version.

**Comment by SeanFeldman** [comment]
@weshaggard correct. It's not possible. This is why the range indicates "lowest version resolved by nuget which stands for the version tested, till next major, assuming the component is following SemVer".

Thank you for the details. I can see the reason behind centralization. At the same time, having a single file to "rule them all" with overrides feels counter to the idea of (quote) [it should feel a lot like it were in its own repo](https://disqus.com/home/discussion/thewindowsazureblog/previewing_azure_sdks_following_new_azure_sdk_api_standards/#comment-4533744043). What will happen if one of the dependencies has to change but it will introduce a breaking change to one of the clients? Will this mean the change is no longer isolated to a single client? Thank you.

**Comment by jsquire** [comment]
>  What will happen if one of the dependencies has to change but it will introduce a breaking change to one of the clients? Will this mean the change is no longer isolated to a single client? 

@SeanFeldman: I'll let Brandon and Wes continue to drive the larger discussion, but I can offer a bit of context on that last bit.  Each individual project has the ability to override the central versioning for its dependencies, if there is a need to do so - such as isolating a breaking change.   Obviously, if this is something that gets used often, it weakens the value of having centralized coordination, but it does help special cases.   The syntax would look something like:

```xml
<PackageReference Include="SOME.PACKAGE.NAME" PrivateAssets="All"  VersionOverride="[3.17.9, 4.9.0)" />
```

**Comment by Petermarcu** [comment]
We've had lots of issues where people couldn't use multiple services in the same application because there was "no right answer" when NuGet tried to resolve dependencies across a breaking change. One side of the breaking change has to win because you can't load these assemblies SxS in applications. Even if the projects were isolated and free to move across the breaking change boundary, once it got to customers, the result would be that the common dependency will actually break people when NuGet lifts the version underneath another library. We would much rather be intentional and knowledgeable about those package upgrades and the impact its going to have on the ecosystem. When we have to go across a breaking change boundary, we need to test and reship anyone else that is broken by that change. This is a value in having everything in a common repo.
