### ISSUE TITLE
[QUERY] How to wait for Azure Search to finish indexing document?

### ISSUE THREAD

**Issue by YakunJin** [Azure/azure-sdk-for-net#6911]
**Query/Question**
Currently, we encountered an issue that when update a index document, we have to wait a few seconds before we could search out the updated result correctly (the IndexAsync api is asynchronously).

This will introduce a concurrent issue when update the same index document frequently. **Is there any way to help us ensure the update process successfully or no?**

Below is the simlar code we currenly used. And the **searchResult** is not the updated record that we expected without the **WaitForIndexing** method.

```
 await fixture.SearchService.IndexAsync(dto);

 	WaitForIndexing(dto);

 var searchResult = await fixture.SearchService.Search(dto.Id); 
```

**Comment by brjohnstmsft** [comment]
Hi @YakunJin,

Please refer to [this thread on StackOverflow](https://stackoverflow.com/questions/40108369/how-to-wait-for-azure-search-to-finish-indexing-document-for-integration-testin), and feel free to post any follow-up questions or comments there.

Since this is not related to the .NET SDK, I'm closing this issue.
