### ISSUE TITLE
[FEATURE REQ] Can we update nuget package to make it refer to newer version Microsoft.IdentityModel.Clients.ActiveDirectory (>= 3.17.2 && < 5.0.0)

### ISSUE THREAD

**Issue by chinadragon0515** [Azure/azure-sdk-for-net#7006]
Now the version of package in nuget is 3.4, it requires Microsoft.IdentityModel.Clients.ActiveDirectory (>= 3.17.2 && < 5.0.0)， but we have other project which require newer version of Microsoft.IdentityModel.Clients.ActiveDirectory, this causes a conflict, can we update the required version of Microsoft.IdentityModel.Clients.ActiveDirectory and publish a new nuget.

**Comment by eriksteinebach** [comment]
I am running into a similar issue with Microsoft.Azure.Management.EventGrid. I would like to update Microsoft.Rest.ClientRuntime, but Microsoft.Azure.Management.EventGrid has the requirement Microsoft.Rest.ClientRuntime (>= 2.3.19 && < 3.0.0). So I cannot update to the latest 3.0.3. 

Do these packages really need a limit of a highest version? I understand that theoretically packages might not always be backwards compatible, but most of the time this is probably the case. Specifying a max version does cause problems when we need to update that required dependency because of another package or new functionality.

**Comment by Petermarcu** [comment]
Thanks for logging this. I believe the challenge here is that there were major breaking changes in Microsoft.IdentityModel.Clients.ActiveDirectory in 5.0.0. @shahabhijeet can you confirm thats the case? If we move everything up to v5, then we will hit the reverse problem right? People that need to reference things that depend on v3-v4.X will be broken?

**Comment by Petermarcu** [comment]
Here is another bug like this. https://github.com/Azure/azure-sdk-for-net/issues/5788 with a PR. @shahabhijeet can you take a look at that one too and the PR?

**Comment by chinadragon0515** [comment]
@shahabhijeet  can I know whether we can update this in near future? thanks

**Comment by yaohaizh** [comment]
@shahabhijeet We are blocking by this issue for fluent .net SDK. So just wondering when this issue will be resolved?

**Comment by jsquire** [comment]
Given the age of this issue and pending deprecation of the fluent package, closing this as stale.  Please feel free to reopen if further discussion is needed.
