### ISSUE TITLE
Unify AzyncCollection and Cosmos FeedIterator<T>

### ISSUE THREAD

**Issue by KrzysztofCwalina** [Azure/azure-sdk-for-net#7099]
Cosmos sources:https://github.com/Azure/azure-cosmos-dotnet-v3/blob/master/Microsoft.Azure.Cosmos/src/Resource/QueryResponses/FeedIterator.cs

We should try to unify AsyncCollection and FeedIterator<T>. 

The reasons Cosmos has a separate type is that they were not aware that we support paging in our collection primitives.
There might be other reasons and we should dig into this deeper.

**Comment by j82w** [comment]
The biggest blocker is IAsyncEnumerable is not supported in .NET standard 2.0.

**Comment by pakrym** [comment]
It is, see https://www.nuget.org/packages/Microsoft.Bcl.AsyncInterfaces/

**Comment by j82w** [comment]
Interesting I was looking at [this](https://docs.microsoft.com/en-us/dotnet/api/system.collections.generic.iasyncenumerable-1?view=netstandard-2.1). In that case I think the biggest blocker I see is the [issue](https://github.com/Azure/azure-sdk-for-net/issues/7097) about the different response types. 

The other issue I see is that the [PageSizeHint](https://github.com/Azure/azure-sdk-for-net/blob/0b5f4731bd00a081cb83fb3bacef16fe85122b33/sdk/core/Azure.Core/src/AsyncCollection.cs#L59) in GetPage. The Cosmos DB SDK will load pages in the background to reduce latency. The SDK doesn't support getting partial pages because of the continuation token.

**Comment by pakrym** [comment]
> The SDK doesn't support getting partial pages because of the continuation token. 

Sorry, I didn't understand this part

**Comment by j82w** [comment]
The Cosmos SDK supports buffering pages to reduce latency. The SDK doesn't support a way of updating the continuation token to allow it to take a partial page that has already been buffered. What user scenario requires a different page size for each GetPage?

**Comment by pakrym** [comment]
Let me clarify a couple of things.

1. PageSizeHint is not required to be supported
2. PageSizeHint is used for all pages you get after calling ByPage, you aren't supposed to be changing it per page.

**Comment by j82w** [comment]
In Cosmos SDK we take the max page size as part of creating the iterator/asyncollection. What scenario did the user need to change the page size between page loads?

**Comment by pakrym** [comment]
> What scenario did the user need to change the page size between GetPage operations?

We don't support this scenario, ByPage returns IAsyncEnumerable of pages and page size hint is passed in only once and applied to all of them.

``` C#
await foreach (var page in client.GetEntries().ByPage(50))
{
}
```

So we are also only taking page size when creating a page iterator. There is no way to change it in between iterations.
