### ISSUE TITLE
[BUG]Microsoft.Build.Tasks.Git.LocateRepository Task fail

### ISSUE THREAD

**Issue by chidozieononiwu** [Azure/azure-sdk-for-net#7140]
**Describe the bug**
Source Link causes build failure for all projects in the repo.

***Exception or Stack Trace***
The "Microsoft.Build.Tasks.Git.LocateRepository" task failed unexpectedly.

**Comment by amnguye** [comment]
Bug Description:
![git-locaterepo-error-dotnet](https://user-images.githubusercontent.com/48961492/62566382-af97fc80-b83d-11e9-941e-838988f5ec39.png)

For reference this was the errors I was getting
The "Microsoft.Build.Tasks.Git.LocateRepository" task failed unexpectedly.
For each project I was attempting to build(e.g. Azure.Core, Azure.Storage.Common, Azure.Identity..)
This is the error that pops up when you try to build the Azure.Storage.sln.

**Comment by amnguye** [comment]
Repro steps:
If git is installed with this option (as I can see how you select the other options does not matter)
![image](https://user-images.githubusercontent.com/48961492/62567365-e66f1200-b83f-11e9-8e96-a12e1145f989.png)

If you choose 'Use Git from Git Bash only' it will reproduce the problem and break the build. Choosing 'Git from command line and also 3rd-party software' or 'Use Git and optional Unix tools from the Command Prompt' does not reproduce this problem and allows the solution to build.
(Make sure you clean before you build, because if you've had a successful build before, it will use the existing files to build. This is just to reproduce the problem better)

**Comment by weshaggard** [comment]
looks related to https://github.com/dotnet/sourcelink/issues/337.

**Comment by amnguye** [comment]
Thanks for linking the related issue Wes!

I updated the sourcelink version and reinstalled git to only be used from git bash and it builds now!

**Comment by chidozieononiwu** [comment]
Fixed with #7226
