### ISSUE TITLE
IEventProcessor in library Microsoft.Azure.EventHubs.ServiceFabricProcessor should be an interface

### ISSUE THREAD

**Issue by pwlodek** [Azure/azure-sdk-for-net#7161]
## Actual Behavior
1. IEventProcessor is an abstract class, which makes in difficult if you want to have your own base class for processors

## Expected Behavior
1. IEventProcessor is an interface
2. 

## Versions  
- OS platform and version: Does not apply
- .NET Version: .NET Standard 2.0
- NuGet package version or commit ID:
Microsoft.Azure.EventHubs.ServiceFabricProcessor 0.5.2

**Comment by JamesBirdsall** [comment]
We could make it an interface except for the default implementation of GetLoadMetric, which is there because we believe it's an advanced scenario and most customers will be OK with the default. That said, the point about base classes is a good one, and we could be blocking a lot of customer scenarios by not being an interface.

How about this as a compromise: we make IEventProcessor an interface, so customers who can't use the base class aren't blocked, but they have to implement GetLoadMetric. We also provide an abstract base class, BaseEventProcessor, which implements GetLoadMetric -- customers who don't care about the base class can use that, and it provides a sample GetLoadMetric for customers who need to use IEventProcessor.

**Comment by jsquire** [comment]
Moving this to the backlog milestone, as the associated sprint has passed.

**Comment by samuelkoppes** [comment]
Thank you for reporting this opportunity to improve the Azure experience. We have taken this ask into our internal backlog for evaluation for prioritization in the first semester of 2021.

**Comment by kasun04** [comment]
The Microsoft.Azure.EventHubs.ServiceFabricProcessor package is in preview and there are no plans for a stable release. This package will soon be deprecated and therefore we won't be taking any changes.
