### ISSUE TITLE
Consider Uri as a type for endpoint parameter of EventHub constructor

### ISSUE THREAD

**Issue by pakrym** [Azure/azure-sdk-for-net#7230]
I've extracted all instances of `sb://[\w\-/\.]+` from the repo and they are all possible to represent with the Uri object.

Java SDKs use URI: https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/servicebus/microsoft-azure-servicebus/src/main/java/com/microsoft/azure/servicebus/MessageSender.java#L38

Some other ServiceBus docs show endpoint represented as URI too: https://github.com/Azure/azure-service-bus/tree/master/samples/DotNet/Microsoft.ServiceBus.Messaging/NetMessagingBinding

cc @jsquire 
<details>

```
sb:///example/data/gutenberg/davinci.txt
sb:///example/data/sample.log
sb://contoso.servicebus.windows.net
sb://default8714
sb://eventhubnamespace616.servicebus.windows.net/
sb://event-hubs-rezas.servicebus.windows.net
sb://fake.servicebus.windows.net/
sb://hydranh-namespace1661.servicebus.windows.net/
sb://hydranh-namespace2438.servicebus.windows.net/
sb://ihsuprodbyres085dednamespace.servicebus.windows.net/
sb://iothubcsharpsdkehnamespacetest.servicebus.windows.net
sb://iothubcsharpsdkehnamespacetest.servicebus.windows.net/
sb://iothubcsharpsdksbnamespacetest.servicebus.windows.net
sb://iothubcsharpsdksbnamespacetest.servicebus.windows.net/
sb://iothub-ns-affanbacku-722541-e6d3b9e3d3.servicebus.windows.net/
sb://iothub-ns-affancentr-1228701-2801317b54.servicebus.windows.net/
sb://iothub-ns-affanga-85919-dbb37074f2.servicebus.windows.net/
sb://iothub-ns-affanmain-723068-75224a8e64.servicebus.windows.net/
sb://iothub-ns-alekseynor-1636439-2947969b98.servicebus.windows.net/
sb://iothub-ns-andbuc-tes-271231-875dddaed9.servicebus.windows.net/
sb://iothub-ns-ankurwestc-1792419-67d0616a9c.servicebus.windows.net/
sb://iothub-ns-askhura-io-1648528-e856d03cc0.servicebus.windows.net/
sb://iothub-ns-asrudra-io-1707361-9db3d6caa7.servicebus.windows.net/
sb://iothub-ns-asrudrates-1770836-658e50b9f3.servicebus.windows.net/
sb://iothub-ns-cymgtest-1795267-6f4620a3c8.servicebus.windows.net/
sb://iothub-ns-demo-asrud-1782619-30ec784c08.servicebus.windows.net/
sb://iothub-ns-dmpypin-cd-1791907-fbf12ba05a.servicebus.windows.net/
sb://iothub-ns-dmpypin-cd-1820624-aa7de2a50e.servicebus.windows.net/
sb://iothub-ns-dotnetcert-1873424-7b5f3593a2.servicebus.windows.net/
sb://iothub-ns-dotnethub-1873374-1bd981a938.servicebus.windows.net/
sb://iothub-ns-dotnethub-1873374-efe0efab53.servicebus.windows.net/
sb://iothub-ns-ea-genhub-1647445-5ddfdc94ff.servicebus.windows.net/
sb://iothub-ns-ea-trustbo-1845736-4cbb218ecb.servicebus.windows.net/
sb://iothub-ns-egmgmttest-1626137-c697d5c7b8.servicebus.windows.net/
sb://iothub-ns-eliohub-1766795-c81a49aca3.servicebus.windows.net/
sb://iothub-ns-eliohub2-1766902-3fffe330de.servicebus.windows.net/
sb://iothub-ns-icm1157738-1635035-4a1220ecb2.servicebus.windows.net/
sb://iothub-ns-ilieedgete-193665-3774bf2376.servicebus.windows.net/
sb://iothub-ns-ilie-test-207274-908460fd83.servicebus.windows.net/
sb://iothub-ns-infra-edge-1848973-1557c6e6f3.servicebus.windows.net/
sb://iothub-ns-iot-hub-re-1608616-9da2f04507.servicebus.windows.net/
sb://iothub-ns-iot-hub-re-1812185-14d8e75e5a.servicebus.windows.net/
sb://iothub-ns-kapilbuild-1609938-ede937158c.servicebus.windows.net/
sb://iothub-ns-maga-canar-1711650-9883db24e0.servicebus.windows.net/
sb://iothub-ns-manualfail-1762885-7a26ecb045.servicebus.windows.net/
sb://iothub-ns-manul-fail-1770469-8055c2fd21.servicebus.windows.net/
sb://iothub-ns-maxgpgtest-1669398-0ab6e73e26.servicebus.windows.net/
sb://iothub-ns-mchaihub-1704167-8fa11e789d.servicebus.windows.net/
sb://iothub-ns-routingrun-1620581-7f4b19c2b2.servicebus.windows.net/
sb://iothub-ns-sachinctes-1643119-627b7767d2.servicebus.windows.net/
sb://iothub-ns-sapan-iot-1608720-c892db45e1.servicebus.windows.net/
sb://iothub-ns-sapan-iot-1622287-aabfd81b00.servicebus.windows.net/
sb://iothub-ns-sapan-iot-1762324-93d1e6ff1c.servicebus.windows.net/
sb://iothub-ns-shishu-can-1635078-9a79c62305.servicebus.windows.net/
sb://iothub-ns-skintali-t-1674510-dfbfe560a5.servicebus.windows.net/
sb://iothub-ns-smoke-iot-1796043-571607922d.servicebus.windows.net/
sb://iothub-ns-smoke-iot-1870061-d35d0a962a.servicebus.windows.net/
sb://iothub-ns-testopsmon-1795455-0c0fa49709.servicebus.windows.net/
sb://iothub-ns-unittestin-417834-12c39aa948.servicebus.windows.net/
sb://iothub-ns-updatedotn-1873405-ca0aee630a.servicebus.windows.net/
sb://iothub-ns-vishalg-eu-1036652-c086004927.servicebus.windows.net/
sb://magaoneboxsbns.servicebus.windows.net
sb://myapp.WindowsAzure.com/
sb://myehnamespace.servicebus.windows.net
sb://mynamespace.someotherregion.windows
sb://namespace_DNS_Name
sb://newendpoint
sb://NOTREAL.servicebus.windows.net/
sb://not-real.servicebus.windows.net/
sb://output
sb://resourcelocator/entityname
sb://routingrunnerscenariotestsehtest-ns.servicebus.windows.net
sb://routingrunnerscenariotestssbqtest-ns.servicebus.windows.net
sb://routingrunnerscenariotestssbtopictest-ns.servicebus.windows.net
sb://sdk-disasterrecovery486.servicebus.windows.net/
sb://sdk-disasterrecovery-5011.servicebus.windows.net/
sb://sdk-namespace-108.servicebus.windows.net/
sb://sdk-namespace-131.servicebus.windows.net/
sb://sdk-namespace-1585.servicebus.windows.net/
sb://sdk-namespace-2064.servicebus.windows.net/
sb://sdk-namespace-3315.servicebus.windows.net/
sb://sdk-namespace-3870.servicebus.windows.net/
sb://sdk-namespace-5149.servicebus.windows.net/
sb://sdk-namespace-6418.servicebus.windows.net/
sb://sdk-namespace-8689.servicebus.windows.net/
sb://sdk-namespace-8898.servicebus.windows.net/
sb://sdk-relaynamespace-1162.servicebus.windows.net/
sb://sdk-relaynamespace-1293.servicebus.windows.net/
sb://sdk-relaynamespace-6031.servicebus.windows.net/
sb://sdk-relaynamespace-7689.servicebus.windows.net/
sb://sdk-relaynamespace-9129.servicebus.windows.net/
sb://shishueh.servicebus.windows.net
sb://test.servicebus.windows.net/
sb://testcontainer13369
sb://vishalgoneboxsbnamespace.servicebus.windows.net
```
</details>

**Comment by jsquire** [comment]
The Event Hubs client does not have a parameter that corresponds to the endpoint, conceptually.  The constructor takes the `host` for the Event Hubs namespace, which is assigned by the resource manager.   This value has historically taken the form of `{your-namespace-name}.servicebus.windows.net` but the ownership of that decision is external to the client library.

Unfortunately, this value is not displayed within the portal making it difficult for developers to discover.  The closest illustration that appears in the portal is the `Endpoint` component of the connection string, which further muddies the waters, as it has an arbitrary `sb://` scheme prefix by convention - but which actually is not needed nor used with the client library.  The library makes use of the host, along with the requested Event Hub name, and a scheme that is determined by the requested transport type in order to form a uri used for connecting to the service.

The decision to use a `string` host was made for a couple of reasons:
- Allow developers the flexibility to either use the documentation to build the host from their namespace name or to copy/paste the endpoint value directly from the connection string.

- Provide the flexibility to do a better job in the future of assisting developers by allowing them to use just the name of their Event Hubs namespace in addition to the other forms.

- Not take a dependency on the format of the host, as this value is controlled by the service team and may change, such as taking different forms for different transport types.  _(currently, AMQP is the only supported transport, but others have been used in the past and are being discussed for inclusion)_

This was a decision made by the feature team across languages, and the approach between .NET, Java, TypeScript, and Python are aligned for the track two client.  I would prefer to keep this more loosely typed as a string to give developers more freedom and allow the library to provide assistance on forming the correct resource from the only item of information prominent in the portal - the namespace name.

That said, @ramya-rao-a is leading the Event Hubs feature all-up.  Since this change would be one that would need to be accepted by all languages, I'll assign to her and give her the opportunity to share thoughts or bring it to the feature team for wider discussion.

**Comment by jsquire** [comment]
Filed [#7242](https://github.com/Azure/azure-sdk-for-net/issues/7242) to begin formally tracking this enhancement.   It's been something that I've informally been tracking for a bit, but this was a good motivator to formalize it.

**Comment by pakrym** [comment]
Thank you for the response, the reasoning is clear to me now. I was asking because I was trying to avoid  an unfortunate AddEventHubClientWithHost https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/eventhub/Azure.Messaging.EventHubs/src/Compatibility/AzureClientBuilderExtensions.cs#L35 method name that is required because without TokenCredential there is nothing to disambiguate connectionString + hub and host + hub overloads.

I tried to go in both direction at this point - considering strongly typed connectionString and now host but it seems that we'll have to live with this one.
