### ISSUE TITLE
Consider removing RetryPolicy property from client instances

### ISSUE THREAD

**Issue by pakrym** [Azure/azure-sdk-for-net#7294]
The usual pattern we use for clients is that their options are fixed after creation with RetryPolicy being a prominent exception from this rule.

In addition to not following the pattern, it raises all kinds of questions about what happens when  RetryPolicy is changed while some operation is running, etc.

Clients in other languages (I checked JS) do not seem to expose it also.

Is there an important scenario we trying to support that would warrant breaking the pattern and adding a level of complexity for implementation.

@jsquire @ramya-rao-a

**Comment by jsquire** [comment]
This was a request from the service team around keeping parity with scenarios that they had for the track one client.   We had originally proposed allowing a custom policy to be set as part of the option when a client type was created and were requested to continue to support change-on-the-fly for parity.

@ramya-rao-a:  I don't have a strong opinion here, though I do continue to prefer locking it once the client was created.   Since you've been driving service team conversations and cross-language decisions, I'll defer to your judgement.    If you would be so kind, please assign it to me if you'd like to take this and I'll work it into the next release plan or close it if you believe that we should not.

**Comment by jsquire** [comment]
I'm going to bring this into the redesign around the client hierarchy.   I feel that we've got enough drift now from the track one code that we're justified in changing some of the established patterns.   In some exploratory conversations with the Event Hubs team, they seem to feel that its reasonable, so long as we continue to offer the ability for developers to create their own custom retry policies.
