### ISSUE TITLE
Cannot import nx package module using AutomationClient.Modules.CreateOrUpdate

### ISSUE THREAD

**Issue by minhhc** [Azure/azure-sdk-for-net#7321]
Hi everyone,

I've been trying to import nx package using the AutomationClient namespace but it does not work, the status of this module keeps hanging on "Importing". I found that it works fine with the modules which are created by author azure-sdk. 

Here is my code:

```
var moduleCreateOrUpdateParameters = new ModuleCreateOrUpdateParameters()
{
   Name = module.Name,
   Location = ResourceGroupInfo.Location,
   Tags = null,
   Properties = new ModuleCreateOrUpdateProperties
   {
      ContentLink = new ContentLink
      {
         Uri = new Uri(module.Url),
         Version = module.Version
      },                       
    },               
};
var result = AutomationClient
                       .Modules
                       .CreateOrUpdate(ResourceGroupInfo.Name, 
                                                  AutomationAccountName, 
                                                  moduleCreateOrUpdateParameters);
```

Here is Az.Accounts module by azure-sdk ([link](https://www.powershellgallery.com/packages/Az.Accounts/1.5.2) which works fine with the code above:

```
name: Az.Accounts
url: https://www.powershellgallery.com/api/v2/package/Az.Accounts/1.5.2
version: 1.5.2
```

And the code does not work with nx package by MSFT_OSTC ([link](https://www.powershellgallery.com/packages/nx/1.0) on Powershell Gallery):

```
name: "nx"
url: "https://www.powershellgallery.com/api/v2/package/nx/1.0"
version: "1.0"
```

Is there anything wrong with my code or Azure-SDK does not support such kind this function at this moment?

I really appreciate if any helps. thank you guys.

**Comment by zjalexander** [comment]
Hi, we took a look at the code and it seems fine. We also looked at the module you are trying to import and other people are able to successfully import it. We don't filter module uploads by author at all.

Unfortunately it seems like you need to open a support ticket so we can figure out if there's anything going on with your automation account in particular. By opening a support ticket and giving permission for us to access your data, we are able to see some backend data about your account which can help narrow down the cause. Sorry we couldn't solve the issue here!

**Comment by minhhc** [comment]
Hi zjalexander, I wonder if the location of automation account played the role for this issue. I'll create a support ticket soon. Thank you for your support.

**Comment by minhhc** [comment]
Just want to make a note here. I solved this issue by ignoring the version.
