### ISSUE TITLE
Change partition identifier type to numeric

### ISSUE THREAD

**Issue by jsquire** [Azure/azure-sdk-for-net#7417]
# Summary

The current track two implementation follows the pattern of using strings as the partition identifiers.  In conversation with the Event Hubs service team, they confirmed that they had historically used a string in order to have flexibility with the implementation.  Going forward, were willing to make a strong guarantee that the identifiers would be numeric and in the range of `[0 .. Total Number of Partitions - 1]`.

In order to provide the best experience, the track two library should alter its representation of the partition identifier to shift to an integer-based value.

# Scope of Work

- Change the representation of partition identifier within the track two client library from `string` to `int`.

- Update existing tests as needed to incorporate changes.

# Out of Scope

- Any changes to the approach for identifying partitions; the scope is limited to altering the type only.

# Success Criteria

- The concept of a partition identifier is consistently represented by an `int` within all facets of the client library.

- The implementation has extensive test coverage and those tests pass consistently and reliably with deterministic results.

**Comment by jsquire** [comment]
Additional context around `EventHubClient` methods to take into account is mentioned in [#7664](https://github.com/Azure/azure-sdk-for-net/issues/7664), which was closed as a duplicate.

**Comment by ramya-rao-a** [comment]
As per feedback from the API review, removal of getPartitionIds() results in new users trying to find a way to fetch the partition id from the client, keeping it with it returning numbers from 0 to n-1 feels silly. Since the service team is not intending to change the API for `runtimeinfo` and will continue to return partition ids as strings, the decision is to continue treating them as strings
