### ISSUE TITLE
Send a message directly to the dead letter queue

### ISSUE THREAD

**Issue by philrowan-mtb** [Azure/azure-sdk-for-net#7476]
**Query/Question**
Is it possible to send a poison (queue) message received via ReceiveAndDelete directly to the dead letter queue? Or is it possible to send a poison (queue) message received via PeekLock directly to the dead letter queue via a different instance of QueueClient or MessageReceiver?

***Why is this not a Bug or a feature Request?***
I'm an idiot. I'm sure it is not a bug because nothing is broken. It may become a feature request if it is even possible.

**Setup (please complete the following information if applicable):**
 - OS: Azure
 - IDE : Visual Studio 2019
<PackageReference Include="Microsoft.Azure.WebJobs.Extensions.ServiceBus" Version="3.0.6" />
<PackageReference Include="Microsoft.Azure.ServiceBus" Version="4.0.0" />
 
I am using queues not topics.
I am using an Azure durable function to orchestrate some long running tasks. I retrieve messages from the queue via a `MessageReceiver`. Do some other stuff in activity functions and finally run a cleanup activity function. If I use `PeekLock` I get a LockToken but I cannot guarantee the same instance of the `MessageReceiver` to either `CompleteAsync` or `DeadLetterAsync` a message because the functions cannot guarantee it. If I use `ReceiveAndDelete` I don't have to worry about `CompleteAsync` but if the message is poison or needs a retry or otherwise needs to make it to the DLQ I don't see a way to send it there. Is there anyway to do this? 

- I cannot guarantee the same instance of `MessageReceiver` will be used to receive and perform final cleanup of a message (without possibly running up against execution time limits in Azure functions).
- I'd prefer to use ReceiveAndDelete over PeekLock to avoid lock timeout limits.
- I'd prefer to send the message directly to the DLQ then since I won't have a LockToken

Cheers  🍺 

 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Query Added
- [x] Setup information Added

**Comment by axisc** [comment]
@philrowan-mtb

Thanks for raising this issue. 

If you can use the same instance of the MessageReceiver, then you can lock the message using the Peek Lock receive mode, and call the [deadletter method](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.servicebus.queueclient.deadletterasync?view=azure-dotnet) to explicitly dead letter the message.

However, in your case, since you cannot guarantee the same message receiver will make the decision to deadletter the message, I would consider using a regular queue as a deadletter queue (perhaps name it as such to avoid confusion) and send the poison messages there.

Let us know if you have additional questions.

**Comment by philrowan-mtb** [comment]
@axisc Thank you for the reply. That's what I figured. I was just hoping to avoid it so we could use the same DLQ convention as our other queues. Not a huge problem though. Thanks again.
