### ISSUE TITLE
Message.Clone() does not create a new user properties bag instance, and instead uses a reference to the same instance.

### ISSUE THREAD

**Issue by jub1482** [Azure/azure-sdk-for-net#7690]
**Describe the bug**
Message.Clone() depends on the MemberwiseClone method for cloning of the user properties bag from a message to a new instance which is a shallow clone operation. After the clone method is used, both the original message and the cloned message have a pointer to the same UserProperties dictionary instance.

**To Reproduce**
1. Get or create a message.
2. Set a user property on the message.
3. Clone the message.
4. Set the same user property to a new value on the cloned message.
5. Get the value of the original object. Value is now "barbar".

***Code Snippet***
Message message = new Message() {
    Body = System.Text.Encoding.UTF8.GetBytes("Test");
};
message.UserProperties["foo"] = "bar";
var clonedMessage = message.Clone();
clonedMessage.UserProperties["foo"] = "barbar";
var value = message.userProperties["foo"]; // value is barbar

**Expected behavior**
I expect the clone to create a new dictionary for user properties so that modification to the cloned message do not affect values stored in the main message.

In order to achieve this deep clone outcome, Microsoft.Azure.ServiceBus.Message.Clone() should include creating a new user properties bag from the old values, i.e.:
clone.UserProperties = new Dictionary<string, object>(this.UserProperties);

**Setup (please complete the following information):**
 - OS: Windows
 - IDE : Visual Studio
 - Version of the Library used 3.0.0

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [X] Bug Description Added
- [X] Repro Steps Added
- [X] Setup information Added

**Comment by jfggdl** [comment]
@jub1482, Thank you for reporting this issue. We are validating the need for deep cloning and if appropriate, we will update the cloning algorithm.

**Comment by jfggdl** [comment]
@jub1482, as @nemakam mentioned, the pr/fix for this is a breaking change.  Hence, we will merge whenever the next major version is planned to release. Note - There is no tentative date for it however.

**Comment by jsquire** [comment]
Shifting to the backlog milestone, as the previously assigned sprint has passed.

**Comment by Rayzbam** [comment]
Still an issue on my side. Clone just work on the same user properties bag. Pretty uncommon behavior i guess

**Comment by ramya-rao-a** [comment]
Thanks for your patience @jub1482 and @Rayzbam
 
Please note that a newer package `Azure.Messaging.ServiceBus` is available as of November 2020. While the older `Microsoft.Azure.ServiceBus` package for which this issue was logged will continue to receive critical bug fixes, we strongly encourage you to upgrade. Read the [migration guide](https://aka.ms/azsdk/net/migrate/sb) for more details.

@JoshLove-msft Can you share if this issue applies to the newer Azure.Messaging.ServiceBus package too?

@shankarsama Can you share if you are considering fixing this in Microsoft.Azure.ServiceBus?

**Comment by JoshLove-msft** [comment]
> @JoshLove-msft Can you share if this issue applies to the newer Azure.Messaging.ServiceBus package too?

The equivalent to the Message.Clone method is the [constructor](https://docs.microsoft.com/en-us/dotnet/api/azure.messaging.servicebus.servicebusmessage.-ctor?view=azure-dotnet#Azure_Messaging_ServiceBus_ServiceBusMessage__ctor_Azure_Messaging_ServiceBus_ServiceBusReceivedMessage_) for ServiceBusMessage that takes a ServiceBusReceivedMessage. This constructor will create a new ApplicationProperties dictionary.

**Comment by ramya-rao-a** [comment]
@jub1482 and @Rayzbam 

Please note that the package `Microsoft.Azure.ServiceBus` has now been deprecated in favor of `Azure.Messaging.ServiceBus`. Since the deprecated package will only be taking critical bug fixes, fix for this bug will not be considered. We strongly encourage you to upgrade to the new package. Read the [migration guide](https://aka.ms/azsdk/net/migrate/sb) for more details
