### ISSUE TITLE
ListHybridConnections didnt return list

### ISSUE THREAD

**Issue by CrazyBaran** [Azure/azure-sdk-for-net#7735]
Extension method WebAppsOperationsExtensions.ListHybridConnections(IWebAppsOperations, String, String) Method in Microsoft.Azure.Management.WebSites should return List of HybridConnection but it return one Hybrid with all null property. Something is wrongly implemented here.

**Comment by isra-fel** [comment]
Sorry for late response. App service team could you share some insights? Thanks

**Comment by CrazyBaran** [comment]
I cannot say right now it is working or not after so long time cause after couple other bugs on your azure client for c#, we move to use restsharp and implement this alone, but anyway it is buggy on endpoints which we like to use. I assumed that this client is generated automaticly but something is broken on definition of this generation.

**Comment by isra-fel** [comment]
Thanks for the info and sorry again @CrazyBaran 

I can reproduce the issue with v3.0.0.
Sample code:
```csharp
var connections = await client.WebApps.ListHybridConnectionsAsync("resourcegroup", "webapp");
```
@panchagnula  @Kotasudhakarreddy  could you help assign somebody for this issue? Thanks

**Comment by Kotasudhakarreddy** [comment]
This is causing because of the response schema/ metadata configured for [ListHybridConnections(Async)](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/web/resource-manager/Microsoft.Web/stable/2021-02-01/WebApps.json#L4710) and [ListHybridConnectionsSlot(Async)](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/web/resource-manager/Microsoft.Web/stable/2021-02-01/WebApps.json#L13646) is not a collection type. But the actual API is returning a collection. So the metadata needs to modify to accept the response in collection form.
@panchagnula please assign this to API team.

**Comment by JagodaMika** [comment]
Hello, 

Any update on this?
