### ISSUE TITLE
Azure SDK GetFileReference incorrectly escaping spaces

### ISSUE THREAD

**Issue by pgmolloy** [Azure/azure-sdk-for-net#7800]
[The](url) GetFileReference method is adding %2520 instead of %20 when creating the primary URI. 

The example here is processing a file  named 6-AN005B (02).pdf.
The correct listFileItem.Uri.Segments[3] is 6-AN005B**%20**(02).pdf.

GetFileReference method returns this : 6-AN005B**%2520**(02).pdf and causes an error when then trying to copy that reference. All files without a space are copied correctly. I can modify the string but I believe the GetFileReference should not include a 25 after the % escape just the 20.

**Comment by amnguye** [comment]
Hi,

Thank you for bringing this issue to our attention.

I was wondering if you're using an older version of our storage SDK. Because the GetFileReference method does not exist in the current SDK version, it actually exists in the older SDK version I linked above. Also CloudBlockBlob, CloudFile and StartCopy are all objects/methods that exist in there as well.

What version of the SDK are you using?

**Comment by amnguye** [comment]
Hi @pgmolloy, I just wanted to ping you and see if this is still an issue for you and if you could answer my above post.

**Comment by kartikshah9** [comment]
@pgmolly can you provide inputs to the above? Else can we  go ahead and close the issue

**Comment by zhusijia26** [comment]
Close the issue as there is no response. Please reopen if needed.
