### ISSUE TITLE
Is Nullable<DateTime> working properly in Storage Client Library 4.3?

### ISSUE THREAD

**Issue by GuardRex** [Azure/azure-sdk-for-net#785]
Nullable<DateTime> should be working ... what am I doing wrong here?
```
public class MyClass : TableEntity {

    public MyClass(string pkey, string rkey) {
        this.PartitionKey = pkey;
        this.RowKey = rkey;
    }

    public MyClass() {
    }

    public Nullable<DateTime> DT { get; set; }

}
```
If there is a datetime in the property of an entity, then I expected this to work to null it:
```
CloudTable table = tableClient.GetTableReference("MyTable");
TableResult retrievedResult = table.Execute(TableOperation.Retrieve<Storage.MyClass>(pkey, rkey));
Storage.MyClass entity = (Storage.MyClass)retrievedResult.Result;
entity.DT = null;
entity.ETag = "*";
table.Execute(TableOperation.Merge(entity));
```
It's NOT clearing the date to null in the Azure table. A datetime value in the property remains in the entity after executing the table operation. Otherwise, I am able to modify other properties of the entity just fine. Everything works except the `Nullable<DateTime>` property of the table. What am I doing wrong?

**Comment by veena-udayabhanu** [comment]
Sorry for the late response. The Storage SDK has been moved to - https://github.com/Azure/azure-storage-net/ and we regularly monitor issues on that repository now. Regarding this issue, please see https://msdn.microsoft.com/en-us/library/azure/dd179392.aspx that explains Merge operation in detail. From that link - "Any properties with null values are ignored by the Merge Entity operation. All other properties will be updated.
A property cannot be removed with a Merge Entity operation. To remove a property from an entity, replace the entity by calling the Update Entity operation."

Since this issue is very old, we are closing it in the hope that you were able to resolve it. If you are still facing issues or have new issues, please report it on the new repository. Thank you!

**Comment by GuardRex** [comment]
@veena-udayabhanu Thanks. I think you're correct: It's probably just that `Merge` doesn't update properties to `null`; therefore `Update` should work in that case.

**Comment by mouliraji** [comment]
This should work;
Change your code like below. 

entity.DT = DBNull.Value;
