### ISSUE TITLE
EventHubConsumer.LastEnqueuedEventInformation should return an immutable object

### ISSUE THREAD

**Issue by mikeharder** [Azure/azure-sdk-for-net#7862]
Callers should be able to ask "what are the properties of the last enqueued event", and they should get a consistent, immutable set of properties to examine.  For example, in the following code the reference to `LastEnqueuedEventProperties` should never be mutated, and the 4 properties should be consistent:

```c#
LastEnqueuedEventProperties props = EventHubConsumer.GetLastEnqueuedEventInformation();
```

Currently, `EventHubConsumer.LastEnqueuedEventInformation` is a property instead of a method, it returns a mutable object, and the properties are not updated atomically.  So there is no way for a caller to get a consistent set of properties, and they may also be surprised if their reference is mutated after they acquired it.

**Comment by jsquire** [comment]
@ramya-rao-a:  Mike is proposing a change to the way last enqueued event information is returned by the consumer.   

Currently, it is treated as a loose set of independent properties that happen to be grouped into an object.   These properties are not maintained as a cohesive set; information will change properties independently as it arrives.  The base assertion is that the properties are interesting to users of the library individually and that there is no strong association that the object represents a single snapshot of state.  

The service team used this pattern for Track One, and the scenarios that they presented when we reviewed the feature revolved around customers using a single property as the basis of "monitoring the backlog" for their processing.  They did not specifically highlight service guarantees that the information is tracked accurately on the service nor that it was not.

Mike correctly points out that this does violate language norms and is potentially unclear to callers and proposes that we change the pattern such that the set of `LastEnqueuedEventInformation` is treated as a coherent set, and that we create an immutable snapshot from our last observed event on-demand.   This would allow callers to better reason about the guarantees and work against a stable snapshot.    If we go down this path, I believe that we would want to change the current property to a method, so that we're not allocating a new object on each receive tick nor replacing the instance that callers can access.  

I've no strong opinion on the approach; I believe the current design serves the stated scenarios and follows an established pattern.   However, I also agree with Mike's observations.  Given that the effort here is low (likely 1-2 hours including tests and documentation updates),  I'd suggest that we take this change; though there may not be much practical benefit given the use cases, it does position us in a better and more consistent design.

- Do you agree that we should move forward with this?
- Should we align the approach across languages, such that they all convert to a method with standard name?
- Do you object to the proposed `GetLastEnqueuedEventInformation` as a method name?   _(it is consistent with our other runtime metadata naming)_

**Comment by jsquire** [comment]
//cc: @kinelski, @conniey, @chradek, @srnagar, @ShivangiReja, @yunhaoling, @YijunXieMS, @AlexGhiondea
