### ISSUE TITLE
Azure Search service search on two fileds with special characters

### ISSUE THREAD

**Issue by AbhishekAdusumilli** [Azure/azure-sdk-for-net#7989]
Hi 

I want to search on two fileds with deifferent search. It should search work for partial search and full text search. When my search text has special characters like "-".It is not working properly

Ex : I want below functionality in Azure search

SkuNumber = '2333IPTS1USD-01' & SkuDecription =  Setup&Cnfig Srvc'
 SkuNumber = '%SL1%' & SkuDecription = '%Setup%'

**Comment by brjohnstmsft** [comment]
@AbhishekAdusumilli Please create a new question on [Stack Overflow](https://stackoverflow.com) and tag it with "azure-search". The Azure Search team monitors that tag and automatically assigns engineers to answer questions there.

I'm going to close this issue now since it's a question about the Azure Search service itself, not the .NET SDK per se.
