### ISSUE TITLE
[QUERY] Azure Service Bus - How do i set 2-3 seconds of Retry timeout for interactive publish scenario

### ISSUE THREAD

**Issue by sanjaysingh** [Azure/azure-sdk-for-net#7990]
**Query/Question**
I am following the guidance for handling retries at https://docs.microsoft.com/en-us/azure/architecture/best-practices/retry-service-specific#service-bus 
It aligns with our requirement to have 2-3 seconds of max time the publish should for our interactive use cases. We however found that
1) There was not way to override the delta backoff in the RetryExponential policy as was recommended in the article
2) OperationTimeout seems to play a role here and the RetryPolicy does not seem to matter in case i have network issues. It seems to timeout after 1 min which is too long for my interactive use case. I could not find any good doc on how to correctly configure OperationTimeout for this retry scenario. In this case we want the Publish to either succeed or fail within 2-3 seconds and it should not matter what kind of failure it was. OperationTimeshout seems to complicate this configuration and there is no documented guidance on how to use them together.

***Why is this not a Bug or a feature Request?***
It might  be an enhancement but i am not sure yet. Retry is getting complicated because OperationTimeout in play here and it does not align with usual retry thinking of how long max a given operation should take. If there is a good guidance then i can live that. If it can be improved with better API to combine RetryPolicy and OperationTimeout that would be even better.

**Setup (please complete the following information if applicable):**
 - OS: Windows 10
 - IDE : Visual Studio 2019, .Net 4.6.2
 - Version of the Library used: Microsoft.Azure.ServiceBus 3.4.0

**Comment by jfggdl** [comment]
@sanjaysingh, implementing an operational timeout of 2 or 3 seconds is too aggressive of a value. @axisc should be able to provide more guidance on this point.

**Comment by nemakam** [comment]
@sanjaysingh 
`OperationTimeout` is the max time an operation can be valid for. If you want to succeed or fail within 2-3 seconds, then that should be operation timeout for you. 
i.e., if you set it to 3 seconds, then no RetryPolicy would try to attempt a second `SendAsync()` if it returned after 3 seconds.
And if you assume you set it to 60 seconds, but then `SendAsync()` failed with some `ServiceBusCommunicationException` within 10 seconds, then the retry policy would kick in and decide to retry again since there is time left (60 - 10 seconds).
Does this provide some clarity?

**Comment by axisc** [comment]
@sanjaysingh

Thanks for opening this query. Hope the recommendations helped unblock you. Please feel free to reopen the issue if you have follow up questions.
