### ISSUE TITLE
Storage: Add simple method overloads

### ISSUE THREAD

**Issue by tg-msft** [Azure/azure-sdk-for-net#8047]
[Per the API Review](https://apiview.azurewebsites.net/Assemblies/Review/c52f059a-6d57-4d40-b7d2-a5816565a660/2568639e2d374a2c8522362fcabee5e1), we should add simple method overloads to every client member in the `Azure.Storage.Blobs` namespace (but not those in `.Specialized`).

This is additive, so I don't consider it blocking.

**Comment by tg-msft** [comment]
Can you check if this can be done in the future without breaking?

**Comment by JoshLove-msft** [comment]
I agree that this should be doable as a non-breaking change. We would create overloads of the relevant methods with the optional params removed and we would have these new methods call into the overloads with the optional params and prevent recursing by passing default for the first optional parameter. Any customer code using the original methods would automatically switch to use the new methods (since the method resolution will prefer methods with fewer parameters) when they take the library update, but there would be no change in behavior.
We would not need to make any optional parameters from the original method required to do this change as the method resolution rules allow for having multiple overloads that differ only in optional parameters.

**Comment by tg-msft** [comment]
Discussed with @KrzysztofCwalina  and we think it'll be safe to (carefully) add these in a future release.  Will add "blocking-release" back if we hear otherwise.

**Comment by JimSuplizio** [comment]
Hi @tg-msft, we deeply appreciate your input into this project. Regrettably, this issue has remained inactive for over 2 years, leading us to the decision to close it. We've implemented this policy to maintain the relevance of our issue queue and facilitate easier navigation for new contributors. If you still believe this topic requires attention, please feel free to create a new issue, referencing this one. Thank you for your understanding and ongoing support.
