### ISSUE TITLE
[P0] Storage: Replace `FileInfo file` with `string path` in Upload methods

### ISSUE THREAD

**Issue by tg-msft** [Azure/azure-sdk-for-net#8048]
[Per the API review](https://apiview.azurewebsites.net/Assemblies/Review/c52f059a-6d57-4d40-b7d2-a5816565a660/2568639e2d374a2c8522362fcabee5e1)

**Comment by amnguye** [comment]
Changing FileInfo to string and having the Upload methods that take in a 'string path' to call the upload(stream) methods actually causes an issue where the stream gets closed too early.

I attempted to create the stream within the method when they pass the path. This works fine for sync. Async runs into issues.
'''
        public virtual Response<BlobContentInfo> Upload(string path)
        {
            Response<BlobContentInfo> response;
            using (FileStream stream = new FileStream(path, FileMode.Open))
            {
                response = Upload(
                    stream,
                    CancellationToken.None);
                stream.Close();
            }
            return response;
'''

'''
public virtual Task<Response<BlobContentInfo>> UploadAsync(string path)
        {
            Task<Response<BlobContentInfo>> response;
            using (FileStream stream = File.Open(path, FileMode.Open, FileAccess.Read))
            {
                response = UploadAsync(
                    stream,
                    CancellationToken.None);
                stream.Close();
            }
            return response;
        }
'''

So when we try uploading the method returns early even though it's not finished yet. Which is expected behavior. However when the code propagates up and closes the stream, it will close the stream that the upload process is currently using to upload information to the service.

Just wanted to see if I'm approaching this wrong, or if should let the user continue handling the streams or file objects when they upload.

@tg-msft Let me know if you have any suggestions for this issue, because other than that I'm kinda blocked on the approach to replace FileInfo with string

**Comment by pakrym** [comment]
@amnguye you have to `await` the `UploadAsync`. If you don't await the task `Disponse` on the stream runs while the task is executing.
