### ISSUE TITLE
[BUG] JsonWebKey.ToRSAParameters incorrectly forces length of RSAParameters.Exponent to 4 bytes

### ISSUE THREAD

**Issue by ti82** [Azure/azure-sdk-for-net#8366]
In the method JsonWebKey.ToRSAParameters, the Exponent is forced to 4 bytes, justified per the reference found here: https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-wcce/5cf2e6b9-3195-4f85-bc18-05b50e6d4e11

However, this is a proprietary protocol, and does not reflect ITU-T X.609 standard defining ASN.1 encoding, section 8.3.2 (https://www.itu.int/ITU-T/studygroups/com17/languages/X.690-0207.pdf) which states:
"8.3.2  If the contents octets of an integer value encoding consist of 
more than one octet, then the bits of the first octet and bit 8 of the 
second octet:
   a) shall not all be ones; and
   b) shall not all be zero.
NOTE – These rules ensure that an integer value is always encoded in the 
smallest possible number of octets."

The leading zero byte is even referenced as necessary due to a positive INTEGER with leading bit set in Microsoft's own documentation on DER Encoding of ASN.1 Types for INTEGER (https://docs.microsoft.com/en-us/windows/win32/seccertenroll/about-integer), which states:

"The fourth byte, 0x00, is added to the content to indicate that the integer is indeed a positive value even though the sign bit of the leading content byte (0x8F) is set to 1."

***Exception or Stack Trace***
ASN.1 Encoding libraries that comply to X.609 ASN.1 rules may reject data that is ASN.1 encoded, as shown by this example which tries to parse an X.509 certificate using GO crypto/x509 that was generated with a key fetched from KeyVault:

"2019/10/23 17:29:58 ParseCertificate: asn1: structure error: integer not minimally-encoded"

**To Reproduce**
1. Create an 2048-bit RSA key in KeyVault
2. Fetch the KeyBundle using the KeyVaultClient and call ToRSAParameters on the nested Key property
3. Observe the Exponent property showing 4 bytes with a leading 0 byte
![jwt2rsa-bug](https://user-images.githubusercontent.com/8225564/67444901-e11c9a80-f5d8-11e9-95dc-7ca30f229e61.png)

**Expected behavior**
The RSA Exponent 0x01 0x00 0x01 is minimally encoded in 3 bytes.

**Comment by heaths** [comment]
Thank you for pointing this out, but [RSAParameters.Exponent](https://docs.microsoft.com/dotnet/api/system.security.cryptography.rsaparameters.exponent?view=netstandard-2.0) and [RSAParameters 
 itself](https://docs.microsoft.com/dotnet/api/system.security.cryptography.rsaparameters?view=netstandard-2.0) make no guarantees that this data is ASN.1 encoded, nor does the [service model definition](https://docs.microsoft.com/rest/api/keyvault/getkey/getkey#keybundle). The service does return base64url-encoded "AQAB" (0x1, 0x0, 0x1) as minimal bytes which is what we store in the JWK, but only force 4 bytes per [BCrypt documentation](https://docs.microsoft.com/openspecs/windows_protocols/ms-wcce/5cf2e6b9-3195-4f85-bc18-05b50e6d4e11) only when creating the parameters.

With our impending release of [Azure.Security.KeyVault.Keys](https://www.nuget.org/packages/Azure.Security.KeyVault.Keys), we're hesitant to fix the older code with concerns of backcompat, but we can fix this in the upcoming release, which gives you an `RSA` provider instead of the raw `RSAParameters`. We'll not force the length there to avoid the problem, and recommend you use the newer package when preview.6 releases (API will be stable) or at least when fully released.

We will consider whether to update the older code but are trying to maintain that for only critical fixes. If you must stick with the older code for now, is this leading byte something you can trim for now?

**Comment by ti82** [comment]
For now, I am doing an extra conversion like this:

```
using (var rsa = key.Key.ToRSA())
{
    var rsaParams = rsa.ExportParameters(false);
    return new PKCS.SubjectPublicKeyInfo(rsaParams);
}
```
This seems to strip the leading zero as needed, and I have confirmed that the GO server is now able to understand the certificates I was generating from the KeyVault keys. After reviewing the source, I see that this basically does an import/export but it is fast enough for my case that it won't impact system performance.

I will keep an eye out for the new package when it is officially released.

**Comment by heaths** [comment]
The new package has been released: https://www.nuget.org/packages/Azure.Security.KeyVault.Keys

**Comment by ti82** [comment]
@heaths I've thought about this more, and I am having trouble understanding your justification for padding the public exponent in ToRSAParameters. You are citing "BCrypt documentation" but linking to the "Windows Client Certificate Enrollment" protocol. Everything I find about BCrypt says that it is a hashing algorithm. 

Ignoring that confusion, you say "RSAParameters.Exponent and RSAParameters
itself make no guarantees that this data is ASN.1 encoded" but along those lines, using ToRSAParameters or the RSAParameters struct makes no guarantee that I care about the WCCE protocol.

On Microsoft's own documentation about that struct (https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.rsaparameters?view=netstandard-2.0#summary-of-fields) it references section A.1.2 of PKCS #1: RSA Cryptography Standard which is the ASN.1 syntax definition of RSA keys! Nowhere in that document is a 4-byte field size mentioned, and the ITU-T X.609 standard is relevant, and should be followed.

**Comment by heaths** [comment]
See https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-wcce/5cf2e6b9-3195-4f85-bc18-05b50e6d4e11.

> PubExp (4 bytes): Length MUST be 4 bytes.

This is what the original code was following. Based on what you stated and subsequent research, we have removed padding from the new packages we released yesterday on which our focus will be.

**Comment by ti82** [comment]
I didn't pick up on the fact that the new API _only_ has ToRSA and not ToRSAParameters. Thanks for the fix!
