### ISSUE TITLE
[EVENTHUBS] ServiceFabricProcessor - Exception Handling Sample

### ISSUE THREAD

**Issue by perokvist** [Azure/azure-sdk-for-net#8374]
What is the recommended exception handling for running the Processor. (try/catch in RunAsync)
Does all exceptions from handling events, bubble up/out, and call OnShutDown ?

Could there also be internal errors bubbling out, like accessing reliable collections after close/role changes?

An added sample, that show this would be great! (if not already covered)

**Comment by jfggdl** [comment]
@perokvist, thank you for creating this issue. A member of our team is preparing an answer to your question.

**Comment by JamesBirdsall** [comment]
The plan is that transient errors are caught and retried, but nontransient errors are not and will bubble up until processing is shut down the Task returned by ServiceFabricProcessor.RunAsync completes. At that point the user's code can examine the error and decide whether to try again (new up another instance of ServiceFabricProcessor and call RunAsync) or whether the problem requires human intervention.

The reality at the moment is that there are a couple transient errors which are not being caught, and we are still refining the model in general. For example, if a transient error persists long enough, the retry mechanism will run out of retries and it will turn into a fatal error -- but is that the right thing to do? If the underlying problem is a network outage, then it would probably be better to keep retrying and resume transparently when the network comes back.

If you have any thoughts on the subject, we would welcome the feedback!

**Comment by perokvist** [comment]
Hi,

Thanks for the clarification.
We currently wrap the execution in our custom exception handling. 
Its a delicate balance if the processor's runasync should handle "everything", or let the user handle "some". Maybe is should default as "everyting", but let devs configure to "some".

Looking forward to future releases.

You'll find examples of our usage here; 

https://github.com/cdon-dev/CMP.ServiceFabricReceivers/blob/master/CMP.ServiceFabricReceiver.Stateful/ReceiverService.cs#L112

https://github.com/cdon-dev/CMP.ServiceFabricReceivers/blob/master/CMP.ServiceFabricReceiver.Common/Execution.cs

**Comment by samuelkoppes** [comment]
Closing as James' guidance answers the question. Please reopen if you would like more assistance.
