### ISSUE TITLE
Service Bus - Azure metrics affected by maxMessageCount paramter in MessageReceiver.ReceiveAsync [BUG]

### ISSUE THREAD

**Issue by erickbp** [Azure/azure-sdk-for-net#8443]
**Describe the bug**
Service Bus

In the Azure portal, when looking at the "outgoing messages" metric, I see way more outgoing messages that what they should be (in my case millions more). Based on my tests and looking at the source code I think that the value we pass of maxMessageCount when calling MessageReceiver.ReceiveAsync is affecting this metric. The value of maxMessageCount is what I see gets reflected in the "outgoing message count" instead of the actual number of messages I receive.

For example: if I call MessageReceiver.ReceiveAsync(500,...) but I actually receive only 1 message then the Azure metric "outgoing message count" reports 500 instead of 1.

Is this a bug in library reporting maxMessageCount instead of the actual number of messages received?

Is Azure going to bill us for what the metric says or for the actual number of messages we receive?

**Screenshots**
![image](https://user-images.githubusercontent.com/10678433/67594493-77180880-f732-11e9-99dc-080fc3f65254.png)

**Setup (please complete the following information):**
 - Windows 10
 - VS 2019
 - 4.1.0

**Comment by jfggdl** [comment]
@erickbp, Thanks for creating this issue. A member of our engineering team is investigating this issue.

**Comment by nemakam** [comment]
@erickbp, the outgoingMessages count represents the real messages that were sent out from the service, and doesn't reflect the number of messages requested. 
Billing and the telemetry that you see are captured separately.
If you call `ReceiveAsync`, and don't get any messages back, it is still counted as 1 billable request (for 1 message), but doesn't add anything to `outgoingMessages`.
If you use `RegisterMessageHandler`, which internally works by periodically polling using `ReceiveAsync`, then each request would be billed. 
If you have prefetch enabled, then client prefetches more messages than you requested on your code. For service, client prefetch is same as client-Receive and will be billed similarly. 

If you think this still doesn't answer the telemetry discrepancy, then I would request you to create an azure support request on the portal along with your namespace/queue details so that it can be investigated further.

**Comment by erickbp** [comment]
@nemakam this happens for all my namespaces and I can reproduce the following.
1. create a brand new namespace
2. create a brand new queue
3. send one single message to the queue.
4. call MessageReceiver.ReceiveAsync(500,...)
5. that single message is received and completed.
6. stop the code ( no more polling)
7. then I see in the "outgoing messages" metric that 500 messages where delivered.

Based on the expected behavior you described then this is a bug somewhere. Is in the Azure portal metrics or Service Bus?

Thanks

**Comment by erickbp** [comment]
Hi @nemakam , I understand what you are saying but can you explain the following?
I can reproduce this and I have just did it.
Steps:
1. Send 1000 messages with the same session to the queue
2. Register session handler and also call `messageSession.ReceiveAsync(500...)` inside of it.
3. I never receive the 500 messages even when the queue has 1000. I always receive less, let's say that 30 messages were actually received
4. Complete messages and kill the session/queue so no more messages are received.
5. What I'm seeing in the azure metrics:
      - incoming messages: 1000
      - outgoing messages: 501 = 1 (first message from the session handler) + 500 ( from `ReceiveAsync` )
      - active messages: 969 = 1000 - 1 - 30

Here is the source code. Enter your own the connection string and queue name. In my example the queue has the following properties:
- Lock duration: 5 min
- Enable dead lettering = true
- Enable session = true
- Enable partitioning = true

```
internal static class Program
{
    private static async Task Main()
    {
        var queueClient = new QueueClient("SERVICE BUS CONNECTION STRING HERE", "debug");

        await Send1000MessagesAsync(queueClient);

        Console.WriteLine("================Waiting for messages...================");
        var sessionHandlerOptions = new SessionHandlerOptions(ExceptionReceivedHandler)
        {
            AutoComplete = false,
            MaxConcurrentSessions = 1
        };
        queueClient.RegisterSessionHandler(async (messageSession, firstMessage, cancellationToken) =>
        {
            await messageSession.CompleteAsync(firstMessage.SystemProperties.LockToken);
            Console.WriteLine("================First message received and completed================");

            Console.WriteLine("================Requesting 500 messages of the same session================");
            var messages = await messageSession.ReceiveAsync(500, TimeSpan.FromSeconds(10));
            Console.WriteLine($"================Actual number of messages received: {messages.Count}================");
            if (messages.Count > 0)
                await messageSession.CompleteAsync(messages.Select(m => m.SystemProperties.LockToken));

            await messageSession.CloseAsync();
            await queueClient.CloseAsync();
            Console.WriteLine("================Session and Queue closed================");
        }, sessionHandlerOptions);

        Console.ReadLine();
    }

    private static async Task Send1000MessagesAsync(ISenderClient queueClient)
    {
        var messagesToSend = new List<Message>();
        for (var i = 0; i < 1000; i++)
        {
            messagesToSend.Add(new Message
            {
                Body = Encoding.UTF8.GetBytes($"body {i}"),
                SessionId = "session"
            });
        }

        Console.WriteLine("================Sending 1000 messages================");
        await queueClient.SendAsync(messagesToSend);
        Console.WriteLine("================1000 messages sent================");
    }

    private static Task ExceptionReceivedHandler(ExceptionReceivedEventArgs exceptionReceivedEventArgs)
    {
        Console.WriteLine(exceptionReceivedEventArgs.Exception);
        return Task.CompletedTask;
    }
}
```

**Comment by nemakam** [comment]
@erickbp, Thanks for the detailed explanation. 
I would still recommend opening a support ticket for this issue. This github repo is used for client issues and this one doesn't look like a client bug. The support ticket will be routed appropriately to the right team to look into this. I'm going to keep this issue marked as closed.

**Comment by nemakam** [comment]
@erickbp , I went through this issue again. Its my bad that I pointed you to the service as I didnt understand the concern properly.
This behavior is by design.
This is due to the concept of "prefetch". You can read about it here - https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-prefetch. 
In short, you requested for 500 messages, and service started sending 500 messages to you. But the messages arrive one by one on the connection(link) to the client. The client waits for few milliseconds for the messages and then hands over all the messages that were received till now to you (which is 30). The remaining 470 is also on their way, just that its on the client's machine, but not given to you yet. Once you do `receive(20)` again, you'd realize that the 20 was received from the client cache itself and the request never went to the service. 
From the service's perspective, it has already sent 500 messages to you, and hence the metric. 
From the client's perspective, it waited for sometime to get messages, it received 30 messages, and then decided to hand over the messages to you instead of waiting for all the 500 messages. The remaining ones just piled on the client side. 
Hence the param name - `maxMessageCount`. The remarks on the API provides slightly more details.
