### ISSUE TITLE
[BUG] Service Bus QueueClient stops receiving messages

### ISSUE THREAD

**Issue by j055** [Azure/azure-sdk-for-net#8498]
**Describe the bug**
QueueClient stops receiving messages (sometimes silently). Four separate VMs with the same applications all stop receiving messages within minutes of each other. 

***Exception or Stack Trace***
This is the last error before the service stopped receiving messages. Only 2 VMs logged the exceptions. The other 2 failed silently,
```
Message handler encountered an exception Microsoft.Azure.ServiceBus.MessageLockLostException: The lock supplied is invalid. Either the lock expired, or the message has already been removed from the queue.
   at Microsoft.Azure.ServiceBus.Core.MessageReceiver.<DisposeMessagesAsync>d__99.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.ServiceBus.RetryPolicy.<RunOperation>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Azure.ServiceBus.RetryPolicy.<RunOperation>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.ServiceBus.Core.MessageReceiver.<CompleteAsync>d__68.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ****.****Service.MessageProcessor.<ProcessMessagesAsync>d__8.MoveNext() in D:\source\repos\****\****.****Service\****.****Service.Library\MessageProcessor.cs:line 75
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.ServiceBus.MessageReceivePump.<MessageDispatchTask>d__13.MoveNext().
```

**To Reproduce**
•	Create Windows Service targeting .NET Framework 4.7.2
•	In OnStart method create a list of new QueueClient objects for queues configured in the ServiceBus, RegisterMessageHandler for each queue.
•	Receive code follows example outlined here: https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-dotnet-how-to-use-topics-subscriptions#receive-messages-from-the-subscription
•	Start Windows service on VMs. Wait for 10 to 20 days! The service runs fine until then and stops abruptly.

***Code Snippet***
Not applicable

**Expected behavior**
If there is a temporary failure with the Service Bus service the QueueClients should try to connect again and throw exceptions if the service is unavailable. 

**Screenshots**
Nothing that would help.

**Setup (please complete the following information):**
 - OS: Windows Server 2019 Core
 - IDE : Visual Studio 2019 version 16.3.6
 - Version of the Library used: Microsoft.Azure.ServiceBus -Version 4.1.0

**Additional context**
I raised a support ticket on Oct 17, 2019 when all our VMs stopped receiving from the queues at the same time. There were no exceptions in our logs and  Azure support said there were no reported problems their side.

I raised another ticket on Oct 29, 2019 when the VMs stopped receiving messages again. I got the response: ‘cannot connect to your Service bus was due to SQL restarts/recycle of the backend nodes on the scale unit that hosts your namespace’. We are on the Standard SKU and use partitioned entities with all the queues.

When the service came back the applications needed to be restarted, effectively to ‘new’ up the QueueClients. 

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ x] Bug Description Added
- [ x] Repro Steps Added
- [ x] Setup information Added

**Comment by jfggdl** [comment]
@j055, thank you for creating this issue. We have started our investigation and we will come back with our findings.

**Comment by nemakam** [comment]
@j055, this is interesting. 
We have an internal testing where we didn't run into this issue. Probably there are lot more external factors causing this issue.
If you get a repro of this, could you please take a full memory dump of it and share it with us? That would be useful for investigation.
Also, if telemetry could be captured, it might be make it even better. 

Simplest way to enable ETW would be:

1. Download [PerfView](https://www.microsoft.com/en-us/download/details.aspx?id=28567)
1. Run `PerfView.exe /OnlyProviders=*Microsoft-Azure-ServiceBus Collect`
1. Stop the collection of traces once you have successful repro.
1. Share the `.etl` files with us. (Please note, you might have sensitive data like entityName and MessageId as part of the trace file. But information like message.Body or connectionString will not be present).

**Comment by nemakam** [comment]
Also, I would recommend you to try this with `4.1.1`. 
Wondering if that exception is causing this problem.

**Comment by nemakam** [comment]
Looking at the code, the only place where I see where this can get stuck is when user provided handlers are called and then they haven't returned. (Either message handler, or the exception handler)

**Comment by j055** [comment]
@nemakam Just a quick update: I have installed PerfView on 2 servers, one with ```4.1.1``` and one with ```4.1.0``` Unfortunately I missed an opportunity to start a trace the other day where the same behaviour occurred.

I couldn't find anything about changes in ```4.1.1```. Can you point me in the right direction?
Thanks

**Comment by j055** [comment]
Hi @nemakam, Another serious degradation in performance today. I have managed to obtain a dump. Can you give me a private address to send it because it contains the service bus URI?

The perf drop seems to be related to numbers of messages in the queue. The more messages in the queue, the slower the service gets at receiving them. There was a gradual increase of messages to around 60,000. We kept restarting the VMs and saw that there was an immediate spike in outgoing messages, then a drop off. We expect to process about 3,000 outbound messages per minute. See chart:

![sb1](https://user-images.githubusercontent.com/6011428/69883681-22395600-12cd-11ea-9857-406d35f58b83.png)

We have tried scaling up the VMs, no difference, Also CPU is typically never more than 50% for any VM.

We hand most if not all exceptions inside try/catch blocks inside the handlers.

Please let me know if you want any particular metrics.

**Comment by j055** [comment]
![sb2](https://user-images.githubusercontent.com/6011428/69886460-f1abe900-12d9-11ea-9fe9-24ecc3c99ea0.png)

**Comment by j055** [comment]
# This chart shows expected behaviour.
![sb-2019-11-22](https://user-images.githubusercontent.com/6011428/69902273-7141c280-1383-11ea-8a66-e15e5c39c57c.png)

# This is a week later at the same time of day handling the same number of messages. 
![sb-2019-11-29](https://user-images.githubusercontent.com/6011428/69902274-7141c280-1383-11ea-952e-918d73ff38d0.png)

**Comment by nemakam** [comment]
@j055 ,
Given that you are on standard namespace, we cannot provide any guarantees on performance. It is a shared resource across namespaces and it is not unexpected to have period of time when the latency is high. If performance and latency is a concern, then you'd have to go to premium messaging which provides resource isolation. 
If things are slow, I probably cannot help you much with it.
If messages stopped flowing on the client completely, and if we are certain the service is working, we can debug further. I personally doubt there is a bug since this is a mainline scenario and we haven't had any changes around this. However, we can continue taking a look at this. 
One thing I would really like you to instrument and check is whether you are returning from all the user handlers (both message handlers, as well as exception handlers). That is generally the most common issue I've seen. There might be some client level deadlock or any other bug due to which the handlers don't return and that can definitely lead to this. It would be great if you could log the beginning and ending of each handler and see that the counts tally. 
You could raise a support request and request them to provide insights on how the latency from service looks like around the time when you are facing issues. If service is taking say 10s of seconds to receive the message due to some noisy neighbor, then there's not much you could do on the client. 

> There were no exceptions in our logs and Azure support said there were no reported problems their side.

If there is were no exceptions in the exception handler, then you are suggesting client didn't see any exception when serviceBus-service had issues? That seems odd again. Could you double check if your logging infra is working as expected.

> If there is a temporary failure with the Service Bus service the QueueClients should try to connect again and throw exceptions if the service is unavailable.

Yes. The code is already written in such a way that this happens. If there is an exception, the exception handler is called (where it is expected to be logged in your code) and then retried.

After all these things, if you are still certain there's something wrong with the client, please send me the client dump and .etl traces to nemakam at microsoft dot com. Also, do mention your namespace name, queue name, time at which this happened, and what exactly happened when you took this dump, and did client restart fix this?

And the changelog for service bus client can be found here - https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/servicebus/Microsoft.Azure.ServiceBus/changelog.md

**Comment by j055** [comment]
@nemakam, thank you for your detailed explanation. I agree with your assessment. I think there may be a third-party component waiting indefinitely for a task to complete in certain situations. I will add a counter to the handler as you suggest and update when I have something.

**Comment by jfggdl** [comment]
@j055, do you have an update on the suggested next step?>

**Comment by davismatt-dir** [comment]
@j055 Did you ever identify the root cause of this issue? I just experienced a similar failure with the javascript version of the sdk. 4 instances all simultaneously stopped receiving (all silent failures).
