### ISSUE TITLE
Integrate logging into the Event Processor Client and associated types

### ISSUE THREAD

**Issue by jsquire** [Azure/azure-sdk-for-net#8571]
# Summary

As a library, it is important for the Event Hubs client library to provide a means for developers using it to understand its activities and the sequence of operations that comprise them, in order to assist in development and debugging efforts.   The standard .NET event source is used for logging within the library, but has not yet been integrated with the `EventProcessorClient`.

# Scope of Work

- The `EventProcessorClient` conforms to the patterns elsewhere in the Event Hubs client library for logging the beginning and completion of key operations, as well as any errors that occurred during them.  

- Operation logging should extend to areas that are likely to be of interest to developers using and troubleshooting the of the processor client.

- Event source data is exposed alongside the other client library types; the `EventProcessorClient` does not employ its own event source.

# Success Criteria

- The `EventProcessorClient` has integrated logging via the existing event source, capturing key operations and following the established patterns within the Event Hubs client library.

- The existing test suite continues to produce deterministic results and pass reliably.

**Comment by sebader** [comment]
will this also include instrumentation for Application Insights? It seems to me the preview library is lacking that so far. Or did I miss something? thanks

**Comment by jsquire** [comment]
> will this also include instrumentation for Application Insights? It seems to me the preview library is lacking that so far. Or did I miss something? thanks

Hi Sebastian.  Thank you for your feedback. 

I'm happy to say that the Event Hubs client is instrumented for tracing and supports both Application Insights and Open Telemetry.  Because of the compatibility with Open Telemetry, you may need to upgrade to the most recent Application Insights library, as there was a fairly recent contribution for an adapter to enable that support.

**Comment by sebader** [comment]
Hi Jesse,
I just double checked and I'm on the latest version of the SDKs. I have a producer (ASP.NET Core 3.1) that uses the `EventHubProducerClient` to send messages. This part seems to be instrumented, as it shows up just fine in my AppInsights application map - without me adding anything extra.

However, the consumer part is a .NET Core 3.1 `BackgroundService` that uses the Azure.Messaging.EventHubs.Processor to read the messages from the event hub. The message processing does not seem to be instrumented on that end, or at least it does not show up in the Application Map (as I would expect it would?!).
![image](https://user-images.githubusercontent.com/11445087/71195506-54b3ee80-228e-11ea-916d-23cd418de512.png)

(The arrow between frontend and backend only shows up since I manually added the correlation ID to my messages and reading them on the backend side).

**Comment by jsquire** [comment]
I can confirm that we're creating a diagnostic scope within the processor for two scenarios:

- When a checkpoint is written
- When an event is read during partition processing and dispatched to the event handler provided

Beyond that, unfortunately, I'll have plead ignorance as I'm not familiar with the specifics around how our diagnostic scope abstraction interacts with the larger telemetry ecosystem.   If you think there may be a problem, would you be so kind as to log an issue and tag me in a comment?   That will let me route it to some folks who would have a deeper knowledge and better be able to assist.
