### ISSUE TITLE
[BUG] Filter does not work when using encoded whitespaces

### ISSUE THREAD

**Issue by hugobarona** [Azure/azure-sdk-for-net#8756]
**Describe the bug**
When you are filtering using special characters, according to the documentation, you need to encode your filters. When encoding, if you encode everything, and if there are whitespaces in your tags that you are searching for, it will encode as well. So, using the Search explorer the queries below work, but using the SDK the second query does not work with the SDK.

Query 1: Tags/any(t: search.in(t, 'Paid Tours %26 Additional Products',','))
Query 2: Tags/any(t: search.in(t, 'Paid Tours%20%26%20Additional%20Products',','))

**To Reproduce**
- Execute both queries using the Search Explorer in the Azure Portal
- Execute both queries using the SDK

**Expected behavior**
Both queries should work on the SDK as it works nowadays in the Search Explorer.

**Setup (please complete the following information):**
 - Version of the Library used: 10.1.0

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ x ] Bug Description Added
- [ x ] Repro Steps Added
- [ x ] Setup information Added

**Comment by AlexGhiondea** [comment]
@brjohnstmsft could you take a look?

**Comment by brjohnstmsft** [comment]
@hugobarona The .NET SDK URL-encodes parameters for you, so you don't have to. Search Explorer just calls the REST API directly, which is why some characters need to be encoded.

For now it's not going to be possible to just paste strings from Search Explorer directly into code that uses the SDK. Going forward, a better approach would be if the portal itself could provide code snippets in C#, Java, F#, etc. (or other languages, once other SDKs for those languages are available). I've created an item on [User Voice](https://feedback.azure.com/forums/263029-azure-search/suggestions/39027553-search-explorer-in-the-portal-should-interoperate) to track this -- please vote for it to help us prioritize.

**Comment by hugobarona** [comment]
@brjohnstmsft thank you for the clarification. For some reason, yesterday i was trying to execute queries using the SDK and special characters and it was failing, complaining about the _&_ character. So that's why i encoded the filter query in order to be able to run the query. But then i realized that encoding the whitespace does not work. This morning i just commented the encoding and the unit tests are working, so i will keep without encoding the queries in the SDK. Thank you.
