### ISSUE TITLE
Why do the KeyVault client methods throw exceptions for normal operations?

### ISSUE THREAD

**Issue by lukos** [Azure/azure-sdk-for-net#8846]
Exceptions are a relatively slow operation in a scalable web application and should only be used for "exceptional" situations that warrant the desire for a call-stack and propagation etc. and I don't consider that calling GetSecretAsync for a missing secret is exceptional in some cases.

I can't find this asked before but why do things like NotFound throw exceptions rather than returning an error code or similar, which would be much more efficient?

If this was a feature request, I would be asking to only use exceptions for real problems like authentication and not for things like missing secrets (in my case I merely want to get a secret for a specific domain if it exists, otherwise to continue) but since this would be asking a lot, is there another way to avoid the exception being thrown?

**Setup (please complete the following information if applicable):**
 - Windows 10 (dotnet core app running on Linux)
 - Client version 3.0.4
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [*] Query Added
- [*] Setup information Added

**Comment by heaths** [comment]
Thank you for your feedback. Is there any reason this should be any different than, say, opening a file that doesn't exist? We try to provide a consistent experience not only across Key Vault libraries (especially the newer libraries we just released a few weeks ago, i.e. for Key Vault are Azure.Security.KeyVault.*, version 4.0.0.0), but also for the frameworks they target, like .NET in this case.

Another reason for this behavior is because the server returns an error with more information. We throw for any server errors, which, for example, could occur if you listed secrets then tried to get them while one of them was deleted (race condition). It could also be an authentication issue (e.g. HTTP 403), server issue (e.g. HTTP 500), etc. While we could certainly parse out the "NotFound" error in this particular case, it would be a breaking change to return a type that contains either an error; or secret, key, or certificate. An exception ensures that even if developers don't handle it closer to the call, diagnostic information is still available.

Could you reduce the frequency of exceptions by getting and caching secret names periodically? If it's difficult to avoid, we could consider additional methods that behave differently, but we'd want to better understand the scenarios in which this is a major performance issue.

**Comment by lukos** [comment]
Hi @heaths Thanks for the reply.

I think the comparison is not quite correct between files and secrets. Calling Open on something shows an intention which assumes the file is there. Also, File.Exists() is available so there is a workaround there anyway. Getting an object from the key store is more like getting it from a remote source and I don't think indicates an expectation that the object exists. Unfortunately, a workaround like "Exists" is also not desirable for network-bound operations since it would often involve two network calls.

I appreciate that special handling for 404 is smelly but it would be possibly to add another method like TryGetSecret (is that less smelly?).

In my specific case, I don't think the frequency of calls would make the exception handling unbearable, just a little nasty, and that is what I have gone with for now, I have tried to lazy load the secret and store the result but since I am using DI, I don't always have the ability to hold onto the secret for as long as I would like. Of course, the other issue is about handling updated secrets which would preclude holding them for too long.

Thanks for the explanation though.

**Comment by heaths** [comment]
A `TryGetSecret` (and for keys, certificates) is a good idea. We will discuss.

**Comment by heaths** [comment]
What is currently the impact to your application? While throwing may not be the best course of action in all cases, we are consistent throughout the newer libraries and we'd have to throw a lot of exceptions to make a significant impact to performance. We can prioritize this accordingly.

**Comment by lukos** [comment]
It is not a significant impact for us currently since we are using it for an email service. The service attempts to lookup a DKIM private key for the domain, which might or might not be present to sign the message. This is only done once per batch so possibly a few times per minute. The exception won't bring the system down, it would just be nice to have an option of a no-exception method.

I could store the presence of the key in a database to know whether to look it up but we don't currently store domain info in the email microservice.

**Comment by heaths** [comment]
Thank you again for suggesting this. After discussing internally with the other Key Vault library languages and performance experts, we will add this to the backlog but see no practical reason to add more methods to the clients at this time. While throwing and catching exceptions does reduce the operations/second, it wasn't a significant amount compared to the current rate limit enforced by Azure Key Vault. We also expect that the normal use case is to request keys/secrets/certificates you know exist, or to enumerate them and retrieve full information shortly after which should significantly reduce 404s.

Should we see feedback about significant application performance degradation, we will revisit this matter and consider possibilities such as `TryGet`-style methods, at least for 404s.

However, given our findings from investigating this issue, we will seriously consider this for other services that have a much higher or no rate limit where rapid 404s could result in serious degradation.

**Comment by heaths** [comment]
We have internal conversations about changes to make going forward, but given the low rate limit for Key Vault we believe the performance impact is negligible in this particular case.
