### ISSUE TITLE
Design exception model consistent with Cognitive Services error handling patterns

### ISSUE THREAD

**Issue by annelo-msft** [Azure/azure-sdk-for-net#8864]
- Understand the Cognitive Services error library and patterns
Conceptual: https://dev.azure.com/msazure/Cognitive%20Services/_wiki/wikis/Cognitive%20Services.wiki/15797/Errors-Long-running-operations
Library: https://dev.azure.com/msazure/Cognitive%20Services/_packaging?_a=package&feed=CognitiveServices&package=Microsoft.CloudAI.Containers.Common.Errors&version=1.1.10490001&protocolType=NuGet
Code: https://dev.azure.com/msazure/Cognitive%20Services/_git/Platform-Containers-Common?path=%2Fsrc%2FCommon.Errors&version=GBmaster

Decide how to expose these errors to users.

Goal: Developers can tell what's going wrong easily.

**Comment by maririos** [comment]
Designed decided (copied from Teams from Anne):

At a high level, we have the following places we could consider throwing an exception:
1. Single input methods
  1.1 Document Error
  1.2 HTTP Error
2. Batch methods
  2.1 Document Error
  2.2 HTTP Error

Because in .NET you throw an exception when there is an error, we throw for 1.1, 1.2, and 2.2.  We do not throw for 2.1 (because probably most of documents have success results), but we do throw an exception if you try to access the success result in the `TextAnalyticsResult` returned from a batch operation.
