### ISSUE TITLE
Enable nullable reference types in the new Track 2 libraries

### ISSUE THREAD

**Issue by KPixel** [Azure/azure-sdk-for-net#8880]
**Feature request:**
With the release of C# 8, [nullable reference types are now live](https://devblogs.microsoft.com/dotnet/try-out-nullable-reference-types/).

I think that it would be great for all Track 2 libraries to take advantage of it and provide a clearer API regarding where null is expected.

Doing this now seems ideal to avoid potential "breaking" changes in the API surface. (Although, they would probably result in compile-time warnings only.)

I found the following issues where this request was mentioned (but not in the context of these new libraries): #5752, #6938, #7271

Note that [Azure.Core has already enabled it](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/core/Azure.Core/src/Azure.Core.csproj#L14-L15). Pull request and findings here: #7263

**Comment by maggiepint** [comment]
@AlexGhiondea @KrzysztofCwalina plans here?

**Comment by AlexGhiondea** [comment]
@KPixel thanks for bringing this up. We did discuss this in the team and we do plan to add support for this in our libraries.

**Comment by chwarr** [comment]
/unresolve: my read of this discussion is "Yes, planned." but implemention has yet to happen. If plans have changed, an update would be nice for those of us waiting for libraries to update to use nullable reference types.

**Comment by AlexGhiondea** [comment]
@chwarr can you share more about your scenario? Where would you benefit from having those annotations enabled?

**Comment by chwarr** [comment]
When I'm programming against an API, .NET nullable annotations let me quickly know when an API admits a null value and when it doesn't. I have to look at documentation or guess otherwise, both of which are slower than looking at the API signature or IntelliSense. Often, the documentation doesn't talk about whether null is an admissible value either.

**Comment by AlexGhiondea** [comment]
@chwarr I intentionally added the label to the issue. I am going through all of our old issues and trying to close/resolve the ones that we can.

I don't think keeping this issue around would change anything in the approach the team is doing which is why I was marking it as addressed.

**Comment by KPixel** [comment]
I would feel better if this request was mentioned somewhere else, maybe in a bigger epic/theme-like issue.
Otherwise, it could easily be overlooked/forgotten.

For context: I opened this issue before the Track 2 libraries had shipped, so there wouldn't have been any breaking changes concerns at that time (NRT by itself should only lead to warnings at compile time).

**Comment by AlexGhiondea** [comment]
@KPixel we did look into this as we were building our Track 2 libraries. But we decided not to do this across the board. And the breaking changes we are talking about are not between Track 1 and Track 2 libraries but more about breaking changes between different versions of the same Track 2 library.

At this point we are not planning to make additional changes to enable this feature until we have more confidence in the data that we have around nullability and the tooling that is available. We periodically look at the .NET features that are available and evaluating if they are something that we should enable (this feature included).

**Comment by chwarr** [comment]
Thank you for explaining the trade off you're making. That makes sense, and it helps me understand the values and priorities of the project better.

Please feel free to use me as an example customer who would benefit from human and machine-readable nullable/optional data about all the Azure APIs. This would help everyone invoking the APIs, from those manually making REST calls, to those using the .NET SDK, and beyond.

I was worried that the issue was going to be closed with "the ball in the project's court" simply due to age. (I've seen bots make this mistake often. It's an easy mistake to make in a bot's rules.)

(FWIW: I have no idea what Track 1 and Track 2 mean.)

**Comment by AlexGhiondea** [comment]
@chwarr Track 1 represents the previous generation of Azure Client Libraries. A couple of years ago we created a set of guidelines that new Client Libraries should follow (in .NET, Java, JavaScript, Python) and Track 2 represents the implementation of Client Libraries that follow those guidelines. There are several improvements to the Track 2 libraries such as performance, usability and dependency management.

About closing this issue -- I am  considering what is the right thing to do. I don't think that keeping it around would change the way our team evaluates enabling these features so I am inclined to close it to reduce the number of issues we have in the repo.
