### ISSUE TITLE
Client Libraries Azure Pipeline failed 20 days ago and still in failed state

### ISSUE THREAD

**Issue by jongio** [Azure/azure-sdk-for-net#8889]
https://github.com/Azure/azure-sdk-for-net/blob/master/CONTRIBUTING.md

![image](https://user-images.githubusercontent.com/2163001/69502791-08ac9e80-0ec8-11ea-982b-7e5daae8ee8b.png)

![image](https://user-images.githubusercontent.com/2163001/69502794-0ea27f80-0ec8-11ea-9d09-17d14b9309d7.png)

https://dev.azure.com/azure-sdk/public/_build/results?buildId=180842&view=results

**Comment by chidozieononiwu** [comment]
Removing badge with https://github.com/Azure/azure-sdk-for-net/pull/8910

**Comment by jongio** [comment]
@chidozieononiwu - FYI the badge is still here: https://azure.github.io/azure-sdk-for-net/

**Comment by chidozieononiwu** [comment]
@jongio Yes I see that. Unfortunately I can't update that right now without breaking some of the doc links. I am still working on integrating the doc index with the unified pipelines so that this updates automatically. I will see about pushing a single file update to the ghpages (which will be a lot different from the current process)

**Comment by chidozieononiwu** [comment]
Badge Removed
