### ISSUE TITLE
GitHub Pages 404s

### ISSUE THREAD

**Issue by jongio** [Azure/azure-sdk-for-net#8891]
GitHub Pages have the following 404s:
https://azure.github.io/azure-sdk-for-net/

```
://azure.github.io/azure-sdk-for-net/
	https://azure.github.io/sdk/core/Azure.Core/README.md
	  \_____ error code: 404 (not found)

https://azure.github.io/azure-sdk-for-net/CONTRIBUTING.html
	https://github.com/Azure/azure-sdk/blob/master/docs/engineering-system/repo-structure.md
	  \_____ error code: 404 (not found)
	https://azure.github.io/azure-sdk-for-net/doc/dev/Versioning.md
	  \_____ error code: 404 (not found)

https://azure.github.io/azure-sdk-for-net/index.html
	https://azure.github.io/sdk/core/Azure.Core/README.md
	  \_____ error code: 404 (not found)
```

**Comment by jongio** [comment]
@chidozieononiwu

**Comment by weshaggard** [comment]
@chidozieononiwu have a look at the current broken links using the pipeline https://dev.azure.com/azure-sdk/internal/_build/results?buildId=225016&view=logs&j=275f1d19-1bd8-5591-b06b-07d489ea915a&t=e2acf9c4-1534-54a3-1ef0-dea62490483f. 

We need to update our doc indexing to replace relative likes in the root readme, similar to what we are doing in other languages, and then make sure we are using relative links instead of links to master in these readmes.

**Comment by chidozieononiwu** [comment]
Doc index already uses the replace relative link tool. I fixed the only remaining case with this PR https://github.com/Azure/azure-sdk-for-net/pull/9331

**Comment by chidozieononiwu** [comment]
All 404 are now fixed.
