### ISSUE TITLE
Using Batch management API on .NET Core

### ISSUE THREAD

**Issue by FilippoPolo** [Azure/azure-sdk-for-net#8917]
**Query/Question**
I want to make a .NET Core application that manages Application Packages for a Batch account.

I was able to do this for .NET Framework using the information found here: https://docs.microsoft.com/en-us/azure/batch/batch-aad-auth-management

Unfortunately, the above will not work on .NET Core, because there's no way to create a prompt (the right constructor for PlatformParameters does not exist). I understand that this makes sense, because .NET Core does not have a GUI, and so cannot present a prompt. However, that leaves me with no idea of how to get a usable token.

I've tried using MSAL to authenticate with a Client Secret instead, but that seems to only work for Application API permissions, and not for Delegated API permissions. The Azure Batch and Azure Service Management permissions seem to only exist as Delegated. But I can't see any way to get Delegated permissions without the ability to show a prompt.

So: how can I perform Batch management operations via .NET Core?

***Why is this not a Bug or a feature Request?***
This may be due to lack of knowledge on my part, rather than a problem or missing feature.

**Setup (please complete the following information if applicable):**
Microsoft.Azure.Management.Batch 9.0.0
Microsoft.Identity.Client 4.7.1 (when I tried MSAL)
Microsoft.IdentityModel.Clients.ActiveDirectory 5.2.0 (when I tried ADAL)

**Comment by matthchr** [comment]
@kiwidev who might just know

This question is I believe not actually specific to Batch, as the Batch management SDK makes use of the same AAD auth patterns as all other Azure management SDKs. I'm not an AAD expert so I'm not sure of the answer here right now but wondering if @AlexGhiondea knows somebody on the client SDK team which has familiarity with the ARM AAD stuff and could advise?

**Comment by bgklein** [comment]
Adding ARM Core as the management SDK makes use of shared standard management auth and therefore they might have an idea

**Comment by bgklein** [comment]
Ping @AlexGhiondea  , @armleads-azure

**Comment by Tiano2017** [comment]
@isra-fel This issue seems to be about the common auth functionality in SDK. It's not specifically on Azure Batch or ARM. can you please triage this issue in the SDK team?

**Comment by snaheth** [comment]
@isra-fel, @erich-wang - To the comment by @Tiano2017 above, can you triage this issue to the right owner can help with getting delegated permissions for Azure Batch via .NET Core?

**Comment by ransagy** [comment]
Still an issue. I'm trying to use this for the "Managed Identities on Azure Batch", which supplies this SDK as the ONLY way to add an identity to a batch pool, but it does not work in .NET Core for the mentioned reasons.

**Comment by markcowl** [comment]
@ransagy What specific kind of credential are you trying to use to authenticate, and it what kind of app?  If you are using a third party application to log in as a user, then there does, indeed need to be some kind of ui - if you are writing a web application, then this is generally handled through redirects.  If you are writing a client application, then this is a bit trickier, but generally handled through a browser pop-up.  Here is some advice from msal.net on this specific issue: https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-net-web-browsers.

The add-on authentication library for these sdks is here: https://www.nuget.org/packages/Microsoft.Rest.ClientRuntime.Azure.Authentication/  and you are correct that it does not support this scenario in .net core, because the .net full version uses a windows forms browser control, which is not available in netstandard.
