### ISSUE TITLE
Hyak.Generator missing?

### ISSUE THREAD

**Issue by FeodorFitsner** [Azure/azure-sdk-for-net#893]
Hello,

While trying to build the latest I'm getting the following error:

```
Error	6	This project references NuGet package(s) that are missing on this computer. Enable NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is ..\..\packages\Hyak.Generator.1.0.5478.27459-prerelease\build\Hyak.Generator.targets.	C:\Projects\GitHub\azure-sdk-for-net\src\BatchManagement\BatchManagement.csproj	90	5	BatchManagement
```

Seems I can't find that package on nuget.org. Could you please direct me?

**Comment by AnneTheAgile** [comment]
+1 This seems like a blocker, right @FeodorFitsner ?
I see a SO question related; http://stackoverflow.com/questions/27048837/azure-sdk-for-netcompiling-source-code
Google shows no hits for Hyak.Generator.targets.

**Comment by FeodorFitsner** [comment]
Exactly, looks like something internal ;)

**Comment by AnneTheAgile** [comment]
@FeodorFitsner , yes, I hope one of the repo owners can fix it for us, since seeing the builds certainly is required for FOSS work.

I was scoping out how fast the azure projects are responding to PR's, that's what brought me here. I have gotten excited about the chef azure-knife idea so I'm research..

**Comment by bcrosnier** [comment]
The Azure SDK already uses a project-specific public feed, [MyGet/azure-sdk-internal](http://www.myget.org/F/azure-sdk-internal/), publicly available in [/libraries.msbuild#L508](https://github.com/Azure/azure-sdk-for-net/blob/master/libraries.msbuild#L508), as well as a private feed ([MyGet/hydra](https://www.myget.org/F/hydra/), pulled from the various [GenerateCode.props](https://github.com/Azure/azure-sdk-for-net/search?q=PRIVATE_FEED_URL)). `Hyak.Generator` is not available in the former, however.

The issue is caused by some projects checking explicitly for this NuGet package reference in their `.csproj`.

Affected projects:

- `NetworkManagement`
- `ComputeManagement`
- `Insights`
- `BatchManagement`
- `StreamAnalyticsManagement`
- `StorSimple`

All other projects have their `msbuild` target `EnsureNuGetPackageBuildImports` removed, which in turn allows them to build without having the `Hyak.Generator` package.

Removing it from the relevant `.csproj` files makes the various projects build successfully (except `DataFactoryManagement`, but that's because of missing files, and is not related to `Hyak.Generator`).

Removing the specified target from the affected `.csproj` files seems to fix the issue.

I'd submit a PR, but I cannot estimate the side effects it would have (I'm not a Microsoft employee, I don't actually *have* `Hyak.Generator` or know exactly what it does), so I'll restrain.

I've published a quick `.patch` file [on this gist](https://gist.github.com/bcrosnier/7a6638b5e7db9876360b), however.

**Comment by yugangw-msft** [comment]
Thanks for reporting this. The project file of "DataFactoryManagement" did miss some files which was addressed today through PR 903. 
However, the whole solution is still not able to build error free without the internal nuget feed set up. We are actively working on it, and will update this with progress. At the same time, the workaround mentioned by "bcrosnier" can be tried out.
       Yugang

**Comment by yugangw-msft** [comment]
We have submitted the changes which enables you to build in command line like the following sample:
         "C:\Program Files (x86)\MSBuild\12.0\Bin\MSBuild.exe" build.proj /t:build;package 

If you would like build out a specific package, you can leverage the property such as  /p:scope="C:\SDK\azure-sdk-for-net\src\Authorization\Authorization.csproj" 

Inside "build.proj", you can see all the important flags at the top comment sections. 

For build inside Visual Studio, I am still working on that.

At the same time, please let us know if you have any comments, preferences.

Thank you.

**Comment by yugangw-msft** [comment]
Building inside Visual Studio is also working now. Please give it a try and let me know if you have any questions
