### ISSUE TITLE
[BUG]MissingMethodException is thrown when invoking Azure search SDK

### ISSUE THREAD

**Issue by angelwen1396** [Azure/azure-sdk-for-net#8955]
An exception is thrown when invoking Azure search SDK. 
MissingMethodException: Method not found: 'Newtonsoft.Json.SerializationBinder Newtonsoft.Json.JsonSerializerSettings.get_Binder()'.

var client = new SearchIndexClient("service name", "index name", new SearchCredentials("service key name"));
 var response = await client.Documents.SearchWithHttpMessagesAsync<T>(term, searchParameters, customHeaders: headers);

It should provide the search result upon the term.

The dependencies versions are:
Microsoft.Azure.Search(3.0.4)
Microsoft.Rest.ClientRuntime.Azure(3.3.10)
Newtonsoft.json(11.0.2)

This method works when I downgrade the Newtonsoft.json to 10.0.1.  But currently due to the new feature development,  I need to upgrade Newtonsoft.json from 10.0.1 to higher version like 11.0.2 or higher.  Then this exception was thrown. 
If upgrading the version of Microsoft.Azure.Search to higher version, lot of code changes need to be made due to build failures and I am not sure if this issue can be resolved.
Is there anything I can do to get over it before making big code changes?

**Comment by AlexGhiondea** [comment]
@brjohnstmsft could you take a look at this? Have you seen this before?

**Comment by brjohnstmsft** [comment]
@angelwen1396 This is a [known issue](https://github.com/Azure/azure-sdk-for-net/issues/3441) that was fixed in version 5.0.0 back in April 2018. You will need to upgrade to at least that version, but I strongly recommend you upgrade to the latest version.

We have provided a [comprehensive set of guides](https://docs.microsoft.com/azure/search/search-dotnet-sdk-migration-version-10) to upgrading code that calls the .NET SDK. It should require minimal effort on your part, and the benefit is that you will get the latest features and bug fixes. We generally do not update old SDK versions unless a critical security issue is found.

**Comment by brjohnstmsft** [comment]
Closing this issue since we do not plan to backport this fix to old SDK versions. @angelwen1396 If you have trouble upgrading to the new version, feel free to ask questions on [Stack Overflow](https://stackoverflow.com) and tag them with `azure-cognitive-search`. Engineers from our team are automatically assigned to answer such questions.
