### ISSUE TITLE
Can you Defer Messages to be retried later?

### ISSUE THREAD

**Issue by BrettBailey** [Azure/azure-sdk-for-net#8958]
**Query/Question**
When using the QueueClient RegisterMessageHandler pattern is there anyway to defer processing of a message to a later time.  The functionality does exist on the MessageReceiver class but It doesn't seem to be accessible.  

***Why is this not a Bug or a feature Request?***
I think it might be  just a case of confusing documentation.

**Setup (please complete the following information if applicable):**
 - OS:Windows 10
 - IDE :Visual Studio 2019
 - 4.1.1 runnning in full .net framework
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Query Added 
- [x] Setup information Added

**Comment by nemakam** [comment]
@BrettBailey ,
Once you defer a message, the way to get that message back is to use `MessageReceiver.ReceiveDeferredMessage` API. By design, `QueueClient` doesn't have this method, and there is no plan to support receiving a single message using QueueClient. Hence there is no need to support deferral of messages using QueueClient.

If you need advanced functionality like message deferral, we suggest you directly using the core pieces like `MessageReceiver` and perform the operation. You should be able to defer the message and also receive it there.

**Comment by axisc** [comment]
@BrettBailey 

Thanks for raising this issue. When you defer a message, you need to store the sequence number on the receiver side so that you can selectively receive that message at a later time.

Due to this, it is a method on the MessageReceiver and not on each individual message.

Please let us know if there are any follow up questions.
