### ISSUE TITLE
[BUG] UsernamePasswordCredentials constructors swapping tenantid, clientid params

### ISSUE THREAD

**Issue by megburnett** [Azure/azure-sdk-for-net#8965]
_One of the UsernamePasswordCredentials constructors is swapping the tenantId/clientId parameters._ 

**Code example:**

UsernamePasswordCredentials cred = new UsernamePasswordCredentials(userName, password, tenantId, clientId);

In the class code, this constructor calls a second constructor, but sends the clientId into the tenantId parameter and the tenantId in as the clientId parameter.

The code results in the following error:

Microsoft.Identity.Client.MsalServiceException: AADSTS90002: Tenant '[clientidparameter]' not found. This may happen if there are no active subscriptions for the tenant. Check with your subscription administrator.

**Comment by schaabs** [comment]
@megburnett Thanks for tracking this issue down! We should have a fix out for this shortly which will be included in the next release of the Azure.Identity library.

**Comment by schaabs** [comment]
@megburnett This issue has been fixed with PR https://github.com/Azure/azure-sdk-for-net/pull/8997. The next release of Azure.Identity will contain this fix. In the meantime you should be able to work around this issue by using the `UsernamePasswordCredential` constructor which also takes `TokenCredentialOptions`.

~~~c#
UsernamePasswordCredentials cred = new UsernamePasswordCredentials(userName, password, tenantId, clientId, new TokenCredentialOptions());
~~~

Please let me know if you run into trouble with the work around or the fix.
