### ISSUE TITLE
[BUG] GetToken fails when providing multiple scopes

### ISSUE THREAD

**Issue by jongio** [Azure/azure-sdk-for-net#9076]
This code uses two scopes:

`new DefaultAzureCredential().GetToken(new TokenRequestContext(new string[]{"https://management.azure.com/.default", "https://storage.azure.com/.default"}));`

Throws this exception for EnvironmentCredential
```
Content:
{"error":"invalid_scope","error_description":"AADSTS70011: The provided request must include a 'scope' input parameter. The provided value for the input parameter 'scope' is not valid. The scope https://management.azure.com/.default https://storage.azure.com/.default is not valid.\r\nTrace ID: 81053cae-3879-4358-a9de-95bf1e230800\r\nCorrelation ID: c6855d6c-d11b-40da-ab7f-826f95a51dda\r\nTimestamp: 
2019-12-11 02:19:59Z","error_codes":[70011],"timestamp":"2019-12-11 02:19:59Z","trace_id":"81053cae-3879-4358-a9de-95bf1e230800","correlation_id":"c6855d6c-d11b-40da-ab7f-826f95a51dda"}
```

Throws this exception for Managed Identity enabled VM
```
 ---> (Inner Exception #1) Azure.Identity.AuthenticationFailedException: The authentication request failed due to an unhandled exception.  See inner exception for details.
 ---> System.ArgumentException: To convert to a resource string the specified array must be exactly length 1 (Parameter 'scopes')
   at Azure.Identity.ScopeUtilities.ScopesToResource(String[] scopes)
   at Azure.Identity.ManagedIdentityClient.CreateImdsAuthRequest(String[] scopes, String clientId)
```

This exception for SharedTokenCacheCredential:
```
---> (Inner Exception #1) Azure.Identity.AuthenticationFailedException: The authentication request failed due to an unhandled exception.  See inner exception for details.
 ---> Microsoft.Identity.Client.MsalServiceException: AADSTS70011: The provided request must include a 'scope' input parameter. The provided value for the input parameter 'scope' is not valid. The scope https://management.azure.com/.default https://storage.azure.com/.default offline_access openid profile is not valid. .default scope can't be combined with resource-specific scopes.
```
They work individually:
```

Azure.Identity.ClientSecretCredential.GetToken succeeded. Scopes: [ https://storage.azure.com/.default ] ParentRequestId:  ExpiresOn: 2019-12-11T03:21:30.6755818+00:00
Azure.Identity.EnvironmentCredential.GetToken succeeded. Scopes: [ https://storage.azure.com/.default ] ParentRequestId:  ExpiresOn: 2019-12-11T03:21:30.6755818+00:00
Azure.Identity.DefaultAcureCredential.GetToken succeeded. Scopes: [ https://storage.azure.com/.default ] ParentRequestId:  ExpiresOn: 2019-12-11T03:21:30.6755818+00:00

Azure.Identity.ClientSecretCredential.GetToken succeeded. Scopes: [ https://management.azure.com/.default ] ParentRequestId:  ExpiresOn: 2019-12-11T03:21:44.3453129+00:00
Azure.Identity.EnvironmentCredential.GetToken succeeded. Scopes: [ https://management.azure.com/.default ] ParentRequestId:  ExpiresOn: 2019-12-11T03:21:44.3453129+00:00
Azure.Identity.DefaultAcureCredential.GetToken succeeded. Scopes: [ https://management.azure.com/.default ] ParentRequestId:  ExpiresOn: 2019-12-11T03:21:44.3453129+00:00
```

**Comment by PawelCiucias** [comment]
Any movement on this? I'm banging my head against it too; trying to get a token for a keyvault and an api
api://00000000-0000-0000-0000-000000000000/.default https://vault.azure.net/.default seporatly they work great, but I can't get a token for both 

AADSTS70011: The provided request must include a 'scope' input parameter. The provided value for the input parameter 'scope' is not valid. The scope https://vault.azure.net/.default api://00000000-0000-0000-0000-000000000000/.default openid profile is not valid. .default scope can't be combined with resource-specific scopes.

**Comment by PawelCiucias** [comment]
after i removed the .default scope and specified them explicitly I got the following error

Message: AADSTS28000: Provided value for the input parameter scope is not valid **because it contains more than one resource**. Scope https://vault.azure.net/user_impersonation api://00000000-0000-0000-0000-000000000000/Candidates openid profile is not valid.

which leads me to the conclusions that you cannot request multiple scopes for multiple resources

if i try the following

["api://00000000-0000-0000-0000-000000000000/Profiles", 
"api://00000000-0000-0000-0000-000000000000/Candidates"]
 
it works no problem.

so yea, one token per resource, multiple scopes  on that resource seems to be the takeaway

**Comment by jongio** [comment]
@schaabs - It would be great to get the error messages to include the "because it contains more than one resource" text even if the scope doesn't include .default.  Pawel had to remove .default to see that error.

**Comment by galvesribeiro** [comment]
Almost 1 year later... I was bitten by this bug as well... 

I wish someone from AAD team could get some light on this...

**Comment by schaabs** [comment]
Adding @rayluo who might be able to provide more information here.

**Comment by rayluo** [comment]
1. AAD/ESTS simply does not and probably will not support issuing token for multiple resources. The client-side does not control how those AADSTS70011 etc. error messages.

2. So, the programming model has to be acquiring separated tokens per resource. This is about documentation/education work. It is not otherwise exposed in MSAL API surface(*). It MIGHT, however, be feasible to have MSAL or Azure Identity to error out early when multiple resources are detected inside the given scopes, with meaningful message, thus bypass # 1 above.

(*) The only API in MSAL that exposes the Multiple Resource concept, is the AcquireTokenInteractive(). Even so, it still won't get you a token for multiple resources, it just streamline the consenting process. https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/Acquiring-tokens-interactively#withextrascopetoconsent

Azure Identity will need to factor in the information above.

**Comment by jongio** [comment]
@schaabs - Can you have a look at this and see if we can integrate this into the error message and docs for all langs?  

@chlowell FYI

**Comment by mtucker2112** [comment]
Do I understand this to mean that there is no way to get the WithExtraScopesToConsent behavior with the InteractiveBrowserCredential?  Streamlining the consent process is precisely what I need using Azure.Identity (1.5.0-beta.4)

**Comment by christothes** [comment]
Hi @mtucker2112 Currently, `InteractiveBrowserCredential` doesn't implement any support for `WithExtraScopesToConsent`. Can you describe the specific scenario you wanting to implement with Azure.Identity? Is this related to On-Behalf-Of flows?

**Comment by timrobinson33** [comment]
Just been hit by this bug myself - Why even define the scopes parameter as a list of strings if it only supports one?

**Comment by JimSuplizio** [comment]
Hi @jongio, we deeply appreciate your input into this project. Regrettably, this issue has remained inactive for over 2 years, leading us to the decision to close it. We've implemented this policy to maintain the relevance of our issue queue and facilitate easier navigation for new contributors. If you still believe this topic requires attention, please feel free to create a new issue, referencing this one. Thank you for your understanding and ongoing support.
