### ISSUE TITLE
[BUG] Documentation Bug: GetCertificatesAsync does not specify behavior when includePending is null

### ISSUE THREAD

**Issue by the-m4a** [Azure/azure-sdk-for-net#9119]
**Describe the bug**
Documentation Bug: GetCertificatesAsync does not specify behavior when includePending is null.  

The comment for that parameter is currently:
_Specifies whether to include certificates which are not completely provisioned._

This is visible on this page:
https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.keyvault.keyvaultclientextensions.getcertificatesasync?view=azure-dotnet-legacy&viewFallbackFrom=azure-dotnet

***Exception or Stack Trace***
N/A

**To Reproduce**
N/A

***Code Snippet***
N/A

**Expected behavior**
A nullable boolean means it has three possible values (true, false, null).  It's unclear what the behavior of this parameter happens to be when it is null.

**Screenshots**
N/A

**Setup (please complete the following information):**
N/A

**Additional context**
I came across this while conducting a peer code review, so it was not something I could quickly test and observe.  I do realize it's a very minor issue, but in this kind of context, it's something that saves me a few minutes worth of time as I'd be certain what the expected behavior of the code should be without having to execute that code myself.

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ x] Bug Description Added
- [ x] Repro Steps Added
- [ x] Setup information Added

**Comment by heaths** [comment]
I can update the documentation, but I'm afraid it won't clarify much. After much discussion, we left it as a nullable boolean to accept the server default since the [query parameter](https://docs.microsoft.com/en-us/rest/api/keyvault/getcertificates/getcertificates#uri-parameters) is optional. In general, we have tried to avoid hard-coding behaviors in the client that are not explicitly documented for the service in case the service changes.
