### ISSUE TITLE
[BUG] No option to pass Timeout.InfiniteTimeSpan to operations that have a timeout

### ISSUE THREAD

**Issue by nathanblair** [Azure/azure-sdk-for-net#9134]
**Describe the bug**
A timespan value of 0 or negative values cannot be passed to methods like MessageReceiver.ReceiveAsync, or similarly set as the OperationTimeout of the MessageReceiver. There needs to be some way to denote that an indefinite amount of time should be awaited for MessageReceiver and similar class operations. I've read in some of the documentation and previous bugs that this was decided to be a _feature_, but this should be changed (otherwise what's the point in even using an async methodology?!)

***Exception or Stack Trace***
```Unhandled exception. System.ArgumentOutOfRangeException: Argument operationTimeout must be a positive non-zero timeout value. The provided value was -00:00:00.0010000. (Parameter 'operationTimeout')```

When passed with Timeout.InfiniteTimeSpan

**To Reproduce**
`_messageReceiver.ReceiveAsync(maxMessageCount, Timeout.InfiniteTimeSpan)`

***Code Snippet***
`_messageReceiver.ReceiveAsync(maxMessageCount, Timeout.InfiniteTimeSpan)`

**Expected behavior**
ReceiveAsync should wait indefinitely until it receives a signal that it should return from whatever host it is connected to.

**Setup (please complete the following information):**
 - OS: ArchLinux
 - IDE : Command-line
 - Version of Dotnet: `dotnet --version: 3.0.100`

**Comment by nemakam** [comment]
@nathanblair, 
Thanks for the request. 
Going into the details, this library is built on top of AMQP protocol and in AMQP terms, we issue a `credit` on the `AmqpLink` when you do a `ReceiveAsync()`. 
Behind the scenes, there are other things that are happening within `MessageReceiver.ReceiveAsync()`, one of the important one being - creation of the link itself (if its not already created). 
Now when you send over a credit to service, and then due to some communication error, the connection is closed. You will still end up getting a null response back, which you need to handle. There is no way in the current SDK to figure out whether the connection was dropped or not. Even in terms of billing, you would not be charged extra if you change it from infinite to 60 seconds. 

I'm going to keep this open as a feature-request, but meanwhile, you could use a large timeout value and work with it.
