### ISSUE TITLE
Long running task throws Microsoft.Azure.ServiceBus.MessageLockLostException

### ISSUE THREAD

**Issue by ivanvaliente** [Azure/azure-sdk-for-net#9185]
We are getting the following exception when executing a long-running task in our service bus subscriber.

> Microsoft.Azure.ServiceBus.MessageLockLostException: The lock supplied is invalid. Either the lock expired, or the message has already been removed from the queue.

The long-running task does several things including reading 4.5M records from the database, building an Excel document _(using OpenXml)_ with multiple sheets _(~1M records per sheet)_, updating a few entities in the database, etc. It's all wrapped inside one method of a service, and that's the only method exposed to the subscriber.

Since this task takes longer than the message is locked for, the message is released to the queue. The subscriber picks it up and starts working on it again. When the first call to the task is finished, we make the following call which immediately throws the exception:

`await client.CompleteAsync(message.SystemProperties.LockToken)`

We'd like to successfully renew the message lock before it is released back to the queue. We've added an alternative logic using a timer to execute `await client.RenewLockAsync(message.SystemProperties.LockToken)` before the message is released based on the value of `message.SystemProperties.LockedUntilUtc`. This seems to work correctly and effectively if we mimic the task with a `Task.Delay(TimeSpan.FromHours(2))`, for example, but with the actual call `await internalService.ExportReport()`, the renew doesn't seem to be effective. The message lock release seems to happen at the 5 minute mark always. We've registered our client's `OperationTimeout` and `ServisceBusConnection.OperationTimeout` with `TimeSpan.FromHours(10)`, but that doesn't seem to have an effect on the message lock timeout.

Our core libraries target _netstandard2.0_, our application targets _netcoreapp2.2_ and we're using _Microsoft.Azure.ServiceBus v4.0.0_.

Can anyone give us some suggestions on how better approach this case, or any long-running task in general?

**Comment by jsquire** [comment]
@nemakam and @binzywu : If one of you would be kind enough to offer your thoughts, it would be appreciated.

**Comment by nemakam** [comment]
@ivanvaliente 
Two things,
1. Use `MessageHandlerOptions.MaxAutoRenewDuration`. The message pump is already designed to renew the messages automatically for you in a background thread. The default value for this is 5 minutes. But if you say set it to 1 hour, it will keep renewing the message for upto an hour automatically. You wouldn't have to do it yourself.
2. You will still have to worry about `MessageLockLostException`. In the happy path, the first point above should do the trick. But lets say there is a communcation issue or a network blip or the service restarts due to a new deployment etc, in that case, the lock is lost since the locks are not persisted. There can be a combination of "message being locked but not able to complete()", or "message being not locked and gets delivered to you again". If the network has issues and service hasn't restarted, the lock is valid, but you wont be able to complete / renew the message. If the service restarts, the connection is closed as well as the lock is lost. Its up to the client now to take care of this scenario.

Changing `OperationTimeout` isn't going to affect this. It manages each individual operation's timeout and not "how long a message is locked" on the service.
