### ISSUE TITLE
[Event Hubs] Telemetry instrumentation on EH processor does not seem to properly work

### ISSUE THREAD

**Issue by sebader** [Azure/azure-sdk-for-net#9208]
**Describe the bug**
As discussed [here](https://github.com/Azure/azure-sdk-for-net/issues/8571#issuecomment-567591694) with @jsquire  
I have a producer (ASP.NET Core 3.1) that uses the EventHubProducerClient to send messages. This part seems to be instrumented, as it shows up just fine in my AppInsights application map - without me adding anything extra.

However, the consumer part is a .NET Core 3.1 BackgroundService that uses the Azure.Messaging.EventHubs.Processor (5.0.0-preview.6) to read the messages from the event hub. The message processing does not seem to be instrumented on that end, or at least it does not show up in the Application Map (as I would expect it would?!).

It uses package Microsoft.ApplicationInsights.WorkerService (2.12.0)

**To Reproduce**
Implement EH processor host and add AppInsights instrumentation

**Expected behavior**
I would expect to get the correlation between sender and processor out-of-the-box

**Screenshots**
![image](https://user-images.githubusercontent.com/11445087/71198286-b9257c80-2293-11ea-8df4-549cb493258f.png)
The arrow between frontend and backend only shows up since I manually added the correlation ID to my messages and reading them on the backend side.

The calls to blob storage are indeed the checkpointing calls from the processor. The backend does not make any other calls to blob.

It is also possible that my expectation is just wrong on what should happen :) But since the map shows the outgoing calls to Event Hub just fine, I would expect something similar for the backend/EH processor.

**Comment by jsquire** [comment]
@pakrym : If you'd be so kind, I'd appreciate your thoughts here.   I'm a bit outside of my knowledge of how our diagnostics scope interacts with the larger telemetry ecosystem.

From the previous discussion:

> I can confirm that we're creating a diagnostic scope within the processor for two scenarios:
> 
> - When a checkpoint is written
> - When an event is read during partition processing and dispatched to the event handler provided

//cc: @kinelski

**Comment by pakrym** [comment]
@lmolkova, is this caused by one of the things you've mentioned we are doing wrong?

**Comment by lmolkova** [comment]
@sebader can you give a bit more info?

From ApplicationInsights UX side, changes to support batched message processing are not fully finalized and app map is not expected to connect frontend and backend yet (but should show both nodes) just yet, [transaction viewer](https://docs.microsoft.com/en-us/azure/azure-monitor/app/transaction-diagnostics#transaction-diagnostics-experience)  should work fine.

We are actively working to support it in app-map and  I'm clarifying when is it expected to be working. I'll get back to you on that.

But let's check if you are not affected by some other issue: you mentioned that you manually propagate ids. What happens if you don't? 

1. Do you see both frontend and backend nodes (or just frontend)?
2. Can you share the request telemetry backend reports: (export it from the log analytics please, I, mostly interested in presence of and contents of '_MS.links' in custom dimensions). 
3. pick one of the _MS.links and search for dependency telemetry on the frontend with the same operation_Id and id
4. how does [transaction viewer](https://docs.microsoft.com/en-us/azure/azure-monitor/app/transaction-diagnostics#transaction-diagnostics-experience) shows operation with this operation_Id?

Let me know if you need help with the queries.

**Comment by sebader** [comment]
@lmolkova is there any update on this after we chatted before Christmas? thanks!

**Comment by lmolkova** [comment]
@sebader yes, we are still working on this. 
Besides UX changes it still depends on https://github.com/Azure/azure-sdk-for-net/issues/9075 Azure SDK side, https://github.com/microsoft/ApplicationInsights-dotnet/pull/1674 on Application Insights side.

We are clarifying the timeline with UX  team.

**Comment by sebader** [comment]
thanks for the update @lmolkova !
