### ISSUE TITLE
Either update or remove use of LoggingExtensions

### ISSUE THREAD

**Issue by JoshLove-msft** [Azure/azure-sdk-for-net#9274]
Throughout the Storage API, we call logging extensions such as LogMethodEnter, LogMethodExit, LogException, etc. Currently these extensions, don't do anything as they are behind a Conditional compilation attribute that isn't enabled, e.g.:
```
        [Conditional("EnableLoggingHelpers")]
        public static void LogMethodExit(
            this HttpPipeline pipeline,
            string className,
            [CallerMemberName] string member = default,
            string message = "")
        => LogTrace(pipeline, $"EXIT METHOD {className} {member}\n{message}");
```
If we want this logging, we should define EnableLoggingHelpers and do any other updates that are needed. If we don't need this, we can delete this file and remove all calls to these methods.

**Comment by seanmcc-msft** [comment]
I vote we remove the LoggingExtensions.

**Comment by tg-msft** [comment]
`LoggingExtensions` was a bridge from Track 1.8 that I added when migrating to Track 2 because the logging story was one of the last things to be settled.  I wrote it all as no-ops that we could hook into whatever logging story we arrived at.  We eventually decided on `EventSource`, swept all the blood and teeth off the conference room table, and implemented [HTTP request/response logging](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/core/Azure.Core/src/Diagnostics/AzureCoreEventSource.cs).

If I execute `await blob.GetPropertiesAsync(new BlobRequestConditions { IfModifiedSince = DateTime.UtcNow.AddDays(-1) })`, the logs today look something like:

```
Azure-Core: [Informational] Request [c9d17663-1c3d-b3db-af1d-6030399034a4] HEAD http://acct.blob.core.windows.net/test-container-35e0bde6-cad4-96f5-179e-066ea28095a0/test-blob-0f71a2b8-938d-0619-34c6-7ccaa9ef867b 
x-ms-version:2019-02-02
If-Modified-Since:Wed, 11 Sep 2019 23:56:23 GMT
x-ms-client-request-id:c9d17663-1c3d-b3db-af1d-6030399034a4
x-ms-return-client-request-id:true
User-Agent:azsdk-net-Storage.Blobs/12.1.0-dev.20200114.1+888654670f74346317655f08dc7e6dd6b4967112 (.NET Core 4.6.28207.04; Microsoft Windows 10.0.18363 )
x-ms-date:Wed, 15 Jan 2020 01:33:41 GMT
Authorization:REDACTED

Azure-Core: [Informational] Response [] 200  (00.0s)
Accept-Ranges:bytes
Content-Length:1024
Content-MD5:3IqUxTWYVQZ0V9rD/j+TxQ==
Content-Type:application/octet-stream
Date:Thu, 12 Sep 2019 23:56:23 GMT
ETag:"0x8D737DCD1387E9B"
Last-Modified:Thu, 12 Sep 2019 23:56:23 GMT
Server:Windows-Azure-Blob/1.0,Microsoft-HTTPAPI/2.0
x-ms-access-tier:Hot
x-ms-access-tier-inferred:true
x-ms-blob-type:BlockBlob
x-ms-client-request-id:c9d17663-1c3d-b3db-af1d-6030399034a4
x-ms-creation-time:Thu, 12 Sep 2019 23:56:23 GMT
x-ms-lease-state:available
x-ms-lease-status:unlocked
x-ms-request-id:652fb45b-501e-000b-13c5-696950000000
x-ms-server-encrypted:true
x-ms-version:2019-02-02
```

If we look at [the implementation of `GetProperties`](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/storage/Azure.Storage.Blobs/src/BlobBaseClient.cs#L2249) we can see the following no-op logging details:

```c#
using (Pipeline.BeginLoggingScope(nameof(BlobBaseClient)))
{
    Pipeline.LogMethodEnter(
        nameof(BlobBaseClient),
        message:
        $"{nameof(Uri)}: {Uri}\n" +
        $"{nameof(conditions)}: {conditions}");
    try
    {
        return await BlobRestClient.Blob.GetPropertiesAsync(...).ConfigureAwait(false);
    }
    catch (Exception ex)
    {
        Pipeline.LogException(ex);
        throw;
    }
    finally
    {
        Pipeline.LogMethodExit(nameof(BlobBaseClient));
    }
}
```

In the Track 1.8 logging world, this displayed something more like:

```
ENTER BlobBaseClient.GetPropertiesAsync (Uri: http://acct.blob.core.windows.net/test-container-35e0bde6-cad4-96f5-179e-066ea28095a0/test-blob-0f71a2b8-938d-0619-34c6-7ccaa9ef867b, conditions: [BlobRequestConditions IfModifiedSince=9/11/2019 3:56:23 PM])

...
...
...

EXIT BlobBaseClient.GetPropertiesAsync (200 OK)
```

I think both are super useful.  The raw HTTP traces are incredibly helpful for debugging exactly what's being sent over the wire, but they're not as friendly for new users who don't know how to map backwards from REST endpoint URIs to our operations.

I'd like us to come up with a plan to add higher level logging to Track 2 so we can dump out the C# type/method names and the .NET `ToString()`s of higher level types [like `BlobRequestConditions`](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/storage/Azure.Storage.Blobs/src/Models/BlobRequestConditions.cs#L28) that get sandwiched around the HTTP traces.  Customers could of course turn off different event types in their tooling to drop one or the other if they had a preference.

Ideally we'd start this in Azure.Core and then implement it in Storage.  Thoughts @pakrym and @KrzysztofCwalina?

**Comment by pakrym** [comment]
We can start by adding EventSource calls to diagnostic scope start/stop/failed calls, this way you'll get to reuse existing instrumentation for "free".

Do we have customers asking for this?

**Comment by seanmcc-msft** [comment]
Nope, there's no customer ask, we're just trying to see what the path forward with logging is.

**Comment by tg-msft** [comment]
Logging events for scope start/stop/failure is a good starting point - we might need to reconfigure things a little to allow them to be passed in to the protocol layer, create the request ID earlier so we can associate scope events with HTTP events, etc.

**Comment by JimSuplizio** [comment]
Hi @JoshLove-msft, we deeply appreciate your input into this project. Regrettably, this issue has remained inactive for over 2 years, leading us to the decision to close it. We've implemented this policy to maintain the relevance of our issue queue and facilitate easier navigation for new contributors. If you still believe this topic requires attention, please feel free to create a new issue, referencing this one. Thank you for your understanding and ongoing support.
