### ISSUE TITLE
[BUG] BlobContainerClient.UploadBlobAsync throws exception when the file already exists

### ISSUE THREAD

**Issue by ThisWillDoIt** [Azure/azure-sdk-for-net#9470]
**Describe the bug**
According to the documentation BlobContainerClient.UploadBlobAsync should update a blob if there is already a blob with the same name but instead it throws. 'The specified blob already exists'

***Exception or Stack Trace***
Azure.RequestFailedException: 'The specified blob already exists.'

**To Reproduce**
Just call await blobContainerClient.UploadBlobAsync("testblob.txt", stream); two times.
Or use this sample repo I uploaded:
https://github.com/ThisWillDoIt/BlobUpload 

***Code Snippet***
https://github.com/ThisWillDoIt/BlobUpload/blob/master/UpdateBlob/Program.cs

**Expected behavior**
The blob should be overwritten.

**Setup (please complete the following information):**
 - OS: Windows 10 Build 18363
 - IDE : Visual Studio 16.4.2
- .NET Core 3.1
 - Azure.Storage.Blobs 12.2.0

**Additional context**
Documentation stating in case of an existing blob it will be overwritten instead of an exception:
https://azuresdkdocs.blob.core.windows.net/$web/dotnet/Azure.Storage.Blobs/12.2.0/api/Azure.Storage.Blobs/Azure.Storage.Blobs.BlobContainerClient.html#Azure_Storage_Blobs_BlobContainerClient_UploadBlobAsync_System_String_System_IO_Stream_System_Threading_CancellationToken_

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by tg-msft** [comment]
`BlobContainerClient.UploadBlobAsync` is a shortcut for `BlobClient.UploadAsync` and only provides the simplest overload semantics.  We default `overwrite = false` on [BlobClient.UploadAsync](https://docs.microsoft.com/en-us/dotnet/api/azure.storage.blobs.blobclient.uploadasync?view=azure-dotnet#Azure_Storage_Blobs_BlobClient_UploadAsync_System_IO_Stream_System_Boolean_System_Threading_CancellationToken_) because we want folks to consciously opt-in to behavior that might cause data loss.  Try `container.GetBlobClient("blobname").UploadAsync(content, overwrite: true)` to accomplish your task.

**Comment by ThisWillDoIt** [comment]
Thank you for providing those insights. The suggested alternative is working.  👍 
Therefore this "bug report" can be changed into adjusting the documentation for UploadAsync if possible.
If this is already planned or if the documentation cannot be updated simply feel free to close this issue.
Thank you!

**Comment by seanmcc-msft** [comment]
I've updated the BlobContainerClient.Upload()/UploadAsync() XML documentation to accurately reflect the behavior of the API.

**Comment by marceardz** [comment]
Hi, I granted my service principal write and execute permissions (Using access control lists) for it to have access to a specific container and a folder inside it. I'm using the suggested code line :

await containerClient.GetBlobClient(blobName).UploadAsync(stream, overwrite: true); 

Nevertheless I'm still getting a 403 error:
This request is not authorized to perform blob overwrites.
Time:2020-03-25T22:00:08.8451368Z
Status: 403 (This request is not authorized to perform blob overwrites.)
ErrorCode: UnauthorizedBlobOverwrite

Are control access list permissions not enough for the service principal to perform overwrite actions?? 
I don't want to give the service principal Storage Blob Data Contributor RBAC role because I don't want it to have access to the whole container, just to specific folder.

**Comment by mdarefull** [comment]
@seankane-msft I've just stumbled upon this exception. I'm using version 12.8.3 of Azure.Storage.Blobs and was using the default BlobClient method that uploads a blob from a stream. 

After reading through the method XML documentation, I was really confused:

> // Summary:
        //     The Azure.Storage.Blobs.BlobClient.UploadAsync(System.IO.Stream) operation creates
        //     a new block blob or **updates the content of an existing block blob**. Updating an
        //     existing block blob overwrites any existing metadata on the blob. For partial
        //     block blob updates and other advanced features, please see Azure.Storage.Blobs.Specialized.BlockBlobClient.
        //     To create or modify page or append blobs, please see Azure.Storage.Blobs.Specialized.PageBlobClient
        //     or Azure.Storage.Blobs.Specialized.AppendBlobClient. For more information, see
        //     Put Blob.

I did some reading and then I expected that options to be part of the `BlobUploadOptions` parameter, which it's not. It wasn't trivial to find that single default parameter, it even appeared as the last method overload recommendation for me.

Could it be possible to at least update the summary of the methods and add a remark about overwriting. 
IMO overwriting a file is the expected default by many of us, confirmed by just reading through the first sentence of the method summary.
