### ISSUE TITLE
Include Files.DataLake in ApiCompat.csproj once it is GA'ed

### ISSUE THREAD

**Issue by JoshLove-msft** [Azure/azure-sdk-for-net#9585]
https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/126/API-Compatibility-Verification-.NET

Steps to include Files.DataLake:

Update eng/ApiCompat/ApiCompat.csproj to include package references for the Files.DataLake library.
Update eng/Packages.Data.props to include the current versions of the packages.
Remove EnableApiCompat param (or set to true) from Files.DataLake csproj file.

**Comment by seanmcc-msft** [comment]
- [ApiCompat.csproj](https://github.com/Azure/azure-sdk-for-net/blob/master/eng/ApiCompat/ApiCompat.csproj) has changed since this issue was opened.
- https://github.com/Azure/azure-sdk-for-net/blob/master/eng/Packages.Data.props#L27
- EnableApiCompat is no longer present in [DataLake.csproj](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/storage/Azure.Storage.Files.DataLake/src/Azure.Storage.Files.DataLake.csproj)
