### ISSUE TITLE
EventHubs tracing: error logging happens outside of diagnostic scope and cannot be correlated 

### ISSUE THREAD

**Issue by lmolkova** [Azure/azure-sdk-for-net#9726]
**Describe the bug**
In the ProcessError callback, DiagnosticScope is already gone. So this is impossible to correlate error and telemetry reported from error callback to  the message processing.

![image](https://user-images.githubusercontent.com/2347409/73480637-1b6fa380-434f-11ea-8bac-83d5a6636b1e.png)

**Expected behavior**
ProcessError is called while Diagnostic scope (Activity) is still active.

**Actual behavior (include Exception or Stack Trace)**
DiagnosticScope is gone.

**To Reproduce**
0. create an app similar to https://github.com/pakrym/LineCounter/blob/master/LineCounter.Worker/LineCounterWorker.cs

1. throw exception in the ProcessEvent callback
2. put breakpoint inside ProcessError. 
3. Check if Activity is available (it's not)

You can also configure ApplicationInsights Logger + OpenTelemetry and check that exception tracked in AppInsights is not correlated to message processing. Here is the code snippets

```csharp
                .ConfigureServices(s =>
                    s.Configure<TelemetryConfiguration>(tc => {
                        tc.TelemetryInitializers.Add(new OperationCorrelationTelemetryInitializer());
                    });
            
                    s.AddOpenTelemetry(b => b
                          .SetResource(Resources.CreateServiceResource("line-counter-worker")) 
                          .UseApplicationInsights(o => o.InstrumentationKey = "ikey")
                          .AddDependencyCollector()
                         .AddRequestCollector());)
                .ConfigureLogging(b => b.AddApplicationInsights("ikey"))

```
 

**Environment:**
 - Name and version of the Library package used: Azure.Messaging.EventHubs 5.0.0.
 - Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects): N/A
 - IDE and version : N/A

**Comment by jsquire** [comment]
Hi @lmolkova, thanks for continuing to help us build our tracing story.  As I'm looking at this issue more closely, I'm not sure that I understand what the expectation is, is related to this request.   I was hoping that you may be able to help provide more context.

The processor's event handler is not used for surfacing issues with developer code where events are being processed; instead it is used to surface processor-based errors, such as trying and failing to assert ownership over a partition during load balancing.   _(see: [troubleshooting](https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/eventhub/Azure.Messaging.EventHubs.Processor#troubleshooting))_

Currently, the only diagnostic scope that exists within the processor is one that wraps events being read and dispatched for processing  _(see: [code snippet](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/eventhub/Azure.Messaging.EventHubs.Processor/src/EventProcessorClient.cs#L838))_.   Because the error handler is explicitly not called from this block by design, there wouldn't be an active scope to associate with calls.   Since that scope is associated with receiving events only, there is no scope currently in use that would be applicable to the error handler.

Moving forward, I'm not sure if the request is due to a misunderstanding of the responsibility of the error handler or if you're advocating for use of additional scopes that would represent the inner workings of the processor itself for key activities, such as load balancing.   Any insight that you can provide would be appreciated.

//cc: @pakrym

**Comment by lmolkova** [comment]
@jsquire 
Here is the scenario I want to enable

1. User processes the message
2. during the processing, unhanded exception is raised from ProcessEventAsync
3. It raises ProcessErrorAsync where user logs error 
4. It is possible to correlate error to message processing

It seems this is not a valid scenario according to your comment and troubleshooting page you referred to.

> surfacing issues with developer code where events are being processed; instead it is used to surface processor-based errors, such as trying and failing to assert ownership over a partition during load balancing

However, `ProcessErrorAsync` is still raised when exception is thrown from `ProcessEventAsync`. Is it a bug? Is it going to change? I would guess that since it's possible, users will use Error callback to handle/log exceptions and will have hard time correlating log/errors to the particular message processing.

Am I missing something?

**Comment by jsquire** [comment]
> @jsquire
> Here is the scenario I want to enable
> 
> 1. User processes the message
> 2. during the processing, unhanded exception is raised from ProcessEventAsync
> 3. It raises ProcessErrorAsync where user logs error

Correct, the scenario isn't the processor's behaivor;  we explicitly do not handle errors that occur in the user-provided code of `ProcessEventAsync`.   An exception there is not caught and surfaced by `ProcessErrorAsync` - it is left unhandled and will propagate as dictated by the runtime and host environment.   

Depending on the type/severity of exception and the host, it may be severe enough to trigger the background task processing the partition to fault, which would result in the processor seeing an internal error with the partition,  trigger the handler, and then surrender ownership of the partition.    However, that's not a guaranteed behavior nor is it a pattern that we recommend for developers using the library.

Our intention is that developers explicitly own the responsibility for error handling within their processing implementation and should `try/catch` as appropriate, including any logs.   That would occur within the active diagnostic scope, as it is maintained until the handler call has completed.

**Comment by lmolkova** [comment]
Thanks for the explanation @jsquire, it makes sense now.
