### ISSUE TITLE
Some packages not showing up in ToC on Docs.MS.com

### ISSUE THREAD

**Issue by scbedd** [Azure/azure-sdk-for-net#9940]
Specifically:
 - `Azure.Storage.Blobs.Batch`
 - `Azure.Storage.Common`

They aren't where we expect them to be. 

Unfortunately, this is not an onboarding issue:
![image](https://user-images.githubusercontent.com/45376673/74388881-6eb30e80-4db1-11ea-9e19-5291f6e3f3a6.png)

As our CI configuration is both up to date and correct. The CI build is even downloading and installing these two packages. We just aren't getting the XML output for it.

**Comment by scbedd** [comment]
I believe the output is coming out properly, but I'm asking @danieljurek to follow up on [this issue](https://dev.azure.com/ceapex/Engineering/_queries/edit/177273/?triage=true)

**Comment by danieljurek** [comment]
Just spoke with the docs team. This behavior is by design because the ToCs are built from the _namespaces_ not the package names. In the case of `Azure.Storage.Blobs.Batch` and `Azure.Storage.Common` the types are declared under namespaces like `Azure.Storage.Blobs.Specialized` and `Azure.Storage` respectively. 

For example, the `BlobBatch` class lives under the `Azure.Storage.Blobs.Specialized` namespace -- https://docs.microsoft.com/en-us/dotnet/api/azure.storage.blobs.specialized.blobbatch?view=azure-dotnet
